[python] Rework graphenelibos python library
gramineproject/gramine pull request #72
Opened 2021-09-18 01:48 UTC by boryspoplawski

## Description of the changes 
Too tired to write full description at the moment, will fix later.

Does this fix RFC #11 fully or only partially ?

2021-09-18 01:50 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/72)* status: 0 of 21 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

___
*[-- commits, line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/72#-Mjqa6x_28gsaywZ5efO):*
blocking until done.


<!-- Sent from Reviewable.io -->

2021-09-18 15:35 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/72)* status: 0 of 21 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/72#-MjtXxWh9ULgbAUYCJnF:-MjtXxWi4qt_pkmMg371:b7wwsmp) (no related file):*
TOOD: write documentation (but first we need to settle whether the new APIs are ok)

---


<!-- Sent from Reviewable.io -->

2021-09-19 00:46 UTC, mkow requested changes
Submitting partial review for now, the rest will come tomorrow.

> Reviewed 16 of 21 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/72#-:-MjvV2ks2YondNr25ZVK:b-5x3doj)* status: 17 of 21 files reviewed, 15 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/72#-MjvW2VNBlZ4l0iOML37:-MjvW2VNBlZ4l0iOML38:b-lxmhoy) (no related file):*
> Does this fix RFC #11 fully or only partially ?

Only partially, missing parts: (quoting [the RFC](https://github.com/gramineproject/gramine/issues/11))
- _Manifests will be renamed: app.toml.jinja (the template) and app.toml (after rendering and trusted files measurement)._
- _`graphene-sgx-get-mrenclave` new tool, will calculate MRENCLAVE based on manifest and `libpal.so`_
- _`graphene-sgx-keygen` new tool, will generate serviceable RSA-3072 key in proper place_
- _The default key location will be in `~/.config/graphene/enclave-key.pem` (really in `$XDG_CONFIG_HOME`)._

But the current version should be fine for the upcoming release.

---
___
*[python/graphene-gen-depend, line 2 at r2](https://reviewable.io/reviews/gramineproject/gramine/72#-MjvK3aP9JlDZi6yp4US:-MjvK3aP9JlDZi6yp4UT:b-q31za9) ([raw file](https://github.com/gramineproject/gramine/blob/578263e7d17126a6a7a18fbceac17c580c5f7375/python/graphene-gen-depend#L2)):*
> ```
>  */
> ```

Please drop this
___
*[python/graphene-gen-depend, line 11 at r2](https://reviewable.io/reviews/gramineproject/gramine/72#-MjvKWzS9TyM8961YkmG:-MjvKWzS9TyM8961YkmH:b-nio9av) ([raw file](https://github.com/gramineproject/gramine/blob/578263e7d17126a6a7a18fbceac17c580c5f7375/python/graphene-gen-depend#L11)):*
> ```
> @click.option('--manifest', '-manifest', 'manifest_path'
> ```

How does this work? Do we have 2 different names for this option? ditto for the whole PR
___
*[python/graphene-gen-depend, line 16 at r2](https://reviewable.io/reviews/gramineproject/gramine/72#-MjvLpn9Eya2wlNR5EYI:-MjvLpn9Eya2wlNR5EYJ:b-optdw8) ([raw file](https://github.com/gramineproject/gramine/blob/578263e7d17126a6a7a18fbceac17c580c5f7375/python/graphene-gen-depend#L16)):*
> ```
> encoding='UTF-8'
> ```

This is the default in the whole Python3 world, do we want to specify it explicitly? I guess this is to highlight that our manifests are in UTF?
btw. Python docs use lowercase for encoding names (`'utf-8'`). ditto for the whole PR
___
*[python/graphene-manifest, line 2 at r2](https://reviewable.io/reviews/gramineproject/gramine/72#-MjvNnAkEJVzVhSVbI_w:-MjvNnAl16deyi8bwiY6:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/578263e7d17126a6a7a18fbceac17c580c5f7375/python/graphene-manifest#L2)):*
> ```
> #!/usr/bin/env python3
> # SPDX-License-Identifier: LGPL-3.0-or-later */
> ```

ditto
___
*[python/graphene-sgx-get-token, line 2 at r2](https://reviewable.io/reviews/gramineproject/gramine/72#-MjvNoyMEwsXEX6QHyka:-MjvNoyMEwsXEX6QHykb:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/578263e7d17126a6a7a18fbceac17c580c5f7375/python/graphene-sgx-get-token#L2)):*
> ```
> #!/usr/bin/env python3
> # SPDX-License-Identifier: LGPL-3.0-or-later */
> ```

ditto
___
*[python/graphene-sgx-sign, line 2 at r2](https://reviewable.io/reviews/gramineproject/gramine/72#-MjvNpq5C6VSSnTedorK:-MjvNpq5C6VSSnTedorL:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/578263e7d17126a6a7a18fbceac17c580c5f7375/python/graphene-sgx-sign#L2)):*
> ```
> #!/usr/bin/env python3
> # SPDX-License-Identifier: LGPL-3.0-or-later */
> ```

ditto
___
*[python/graphene-sgx-sign, line 14 at r2](https://reviewable.io/reviews/gramineproject/gramine/72#-MjvTePZ9Np9m1JsCGpI:-MjvTePZ9Np9m1JsCGpJ:b-7cpfjj) ([raw file](https://github.com/gramineproject/gramine/blob/578263e7d17126a6a7a18fbceac17c580c5f7375/python/graphene-sgx-sign#L14)):*
> ```
>               help='Output .manifest.sgx file (manifest augmented with autogenerated fields)')
> @click.option('--libpal', '-libpal', help='Input libpal file')
> @click.option('--key', '-key', required=True, help='specify signing key(.pem) file')
> ```

missing space before `(.pem)`
___
*[python/meson.build, line 5 at r2](https://reviewable.io/reviews/gramineproject/gramine/72#-MjvUPr89ly7Pdi5vyxR:-MjvUPr89ly7Pdi5vyxS:bfur1f3) ([raw file](https://github.com/gramineproject/gramine/blob/578263e7d17126a6a7a18fbceac17c580c5f7375/python/meson.build#L5)):*
> ```Meson
> install_data([
>     'graphene-manifest',
>     'graphene-gen-depend',
> ```

please sort
___
*[python/graphenelibos/__init__.py, line 16 at r2](https://reviewable.io/reviews/gramineproject/gramine/72#-MjvUW91CgJVp8zWsG4_:-MjvUW91CgJVp8zWsG4a:bbiub20) ([raw file](https://github.com/gramineproject/gramine/blob/578263e7d17126a6a7a18fbceac17c580c5f7375/python/graphenelibos/__init__.py#L16)):*
> ```Python
> # pylint: disable=wrong-import-position
> from .manifest import Manifest
> if '@SGX_ENABLED@' == 'True': # please kill me
> ```

We should rather drop this comment before merging ;)
___
*[python/graphenelibos/sgx_get_token.py, line 2 at r2](https://reviewable.io/reviews/gramineproject/gramine/72#-MjvNsMk2PT3rVBB6B_m:-MjvNsMk2PT3rVBB6B_n:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/578263e7d17126a6a7a18fbceac17c580c5f7375/python/graphenelibos/sgx_get_token.py#L2)):*
> ```Python
> #!/usr/bin/env python3
> # SPDX-License-Identifier: LGPL-3.0-or-later */
> ```

ditto
___
*[python/graphenelibos/sgx_sign.py, line 2 at r2](https://reviewable.io/reviews/gramineproject/gramine/72#-MjvV-bN8rFxaHYZuqJQ:-MjvV-bN8rFxaHYZuqJR:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/578263e7d17126a6a7a18fbceac17c580c5f7375/python/graphenelibos/sgx_sign.py#L2)):*
> ```Python
> #!/usr/bin/env python3
> # SPDX-License-Identifier: LGPL-3.0-or-later */
> ```

ditto
___
*[python/graphenelibos/sigstruct.py, line 2 at r2](https://reviewable.io/reviews/gramineproject/gramine/72#-MjvNvLeBXljo5IiUfeY:-MjvNvLeBXljo5IiUfeZ:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/578263e7d17126a6a7a18fbceac17c580c5f7375/python/graphenelibos/sigstruct.py#L2)):*
> ```Python
> #!/usr/bin/env python3
> # SPDX-License-Identifier: LGPL-3.0-or-later */
> ```

ditto


<!-- Sent from Reviewable.io -->

2021-09-19 18:51 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/72)* status: 10 of 22 files reviewed, 15 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/72#-MjvW2VNBlZ4l0iOML37:-MjyiPO35TRzWQUQNvu1:b-cj9i1n) (no related file):*
> graphene-sgx-get-mrenclave new tool, will calculate MRENCLAVE based on manifest and libpal.so
> graphene-sgx-keygen new tool, will generate serviceable RSA-3072 key in proper place

These 2 I could easily add, but not sure if it's worth it, in this PR. Also I don't see much point in `graphene-sgx-keygen`

---
___
*[python/graphene-gen-depend, line 2 at r2](https://reviewable.io/reviews/gramineproject/gramine/72#-MjvK3aP9JlDZi6yp4US:-Mjz7YDrErdA7jfGRtP2:b4tacor) ([raw file](https://github.com/gramineproject/gramine/blob/578263e7d17126a6a7a18fbceac17c580c5f7375/python/graphene-gen-depend#L2)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
>  */
> ```

Please drop this
</blockquote></details>

Done.
I've grepped whole repo and dropped all occurrences of this.
___
*[python/graphene-gen-depend, line 11 at r2](https://reviewable.io/reviews/gramineproject/gramine/72#-MjvKWzS9TyM8961YkmG:-Mjz8Fq_4CTMhXe6Q9hA:b-m0h2a0) ([raw file](https://github.com/gramineproject/gramine/blob/578263e7d17126a6a7a18fbceac17c580c5f7375/python/graphene-gen-depend#L11)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> @click.option('--manifest', '-manifest', 'manifest_path'
> ```

How does this work? Do we have 2 different names for this option? ditto for the whole PR
</blockquote></details>

A long one and short one. Usually the short one is one letter (e.g. `-m`), but I wanted to preserve old cli, so left old versions everywhere.
___
*[python/graphene-gen-depend, line 16 at r2](https://reviewable.io/reviews/gramineproject/gramine/72#-MjvLpn9Eya2wlNR5EYI:-Mjz9mB71afARsjf7oWA:b-6n3h7j) ([raw file](https://github.com/gramineproject/gramine/blob/578263e7d17126a6a7a18fbceac17c580c5f7375/python/graphene-gen-depend#L16)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> encoding='UTF-8'
> ```

This is the default in the whole Python3 world, do we want to specify it explicitly? I guess this is to highlight that our manifests are in UTF?
btw. Python docs use lowercase for encoding names (`'utf-8'`). ditto for the whole PR
</blockquote></details>

I've just used what was already here, introduced in https://github.com/gramineproject/gramine/commit/f8c12bac stating `Also, scripts now explicitly use UTF-8 when reading/writing the manifest files because they are written in TOML which forces UTF-8.`
___
*[python/graphene-manifest, line 2 at r2](https://reviewable.io/reviews/gramineproject/gramine/72#-MjvNnAkEJVzVhSVbI_w:-MjzDhk_1350cLxCLOVw:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/578263e7d17126a6a7a18fbceac17c580c5f7375/python/graphene-manifest#L2)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[python/graphene-sgx-get-token, line 2 at r2](https://reviewable.io/reviews/gramineproject/gramine/72#-MjvNoyMEwsXEX6QHyka:-MjzDiY52GgbNvOaCgxH:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/578263e7d17126a6a7a18fbceac17c580c5f7375/python/graphene-sgx-get-token#L2)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[python/graphene-sgx-sign, line 2 at r2](https://reviewable.io/reviews/gramineproject/gramine/72#-MjvNpq5C6VSSnTedorK:-MjzDj6B6rba0fiie-o_:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/578263e7d17126a6a7a18fbceac17c580c5f7375/python/graphene-sgx-sign#L2)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[python/graphene-sgx-sign, line 14 at r2](https://reviewable.io/reviews/gramineproject/gramine/72#-MjvTePZ9Np9m1JsCGpI:-MjzDpUJ7VGheBTCfQzG:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/578263e7d17126a6a7a18fbceac17c580c5f7375/python/graphene-sgx-sign#L14)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

missing space before `(.pem)`
</blockquote></details>

Done.
___
*[python/meson.build, line 5 at r2](https://reviewable.io/reviews/gramineproject/gramine/72#-MjvUPr89ly7Pdi5vyxR:-MjzDtlk3wsj6SzVJLDr:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/578263e7d17126a6a7a18fbceac17c580c5f7375/python/meson.build#L5)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

please sort
</blockquote></details>

Done.
___
*[python/graphenelibos/__init__.py, line 16 at r2](https://reviewable.io/reviews/gramineproject/gramine/72#-MjvUW91CgJVp8zWsG4_:-MjzEwtKEg9M5B3PHO0d:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/578263e7d17126a6a7a18fbceac17c580c5f7375/python/graphenelibos/__init__.py#L16)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

We should rather drop this comment before merging ;)
</blockquote></details>

Done.
___
*[python/graphenelibos/sgx_get_token.py, line 2 at r2](https://reviewable.io/reviews/gramineproject/gramine/72#-MjvNsMk2PT3rVBB6B_m:-MjzExp26te16VUuhHRf:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/578263e7d17126a6a7a18fbceac17c580c5f7375/python/graphenelibos/sgx_get_token.py#L2)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[python/graphenelibos/sgx_sign.py, line 2 at r2](https://reviewable.io/reviews/gramineproject/gramine/72#-MjvV-bN8rFxaHYZuqJQ:-MjzEyP_111Zpvdr_J5N:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/578263e7d17126a6a7a18fbceac17c580c5f7375/python/graphenelibos/sgx_sign.py#L2)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[python/graphenelibos/sigstruct.py, line 2 at r2](https://reviewable.io/reviews/gramineproject/gramine/72#-MjvNvLeBXljo5IiUfeY:-MjzEytV4lXu8LENMksz:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/578263e7d17126a6a7a18fbceac17c580c5f7375/python/graphenelibos/sigstruct.py#L2)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-09-20 00:19 UTC, mkow requested changes
> Reviewed 1 of 21 files at r1, 11 of 11 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/72)* status: all files reviewed, 11 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/72#-MjvW2VNBlZ4l0iOML37:-Mk-EncC09OJMhNaL5Kc:b-x7fxbb) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

> graphene-sgx-get-mrenclave new tool, will calculate MRENCLAVE based on manifest and libpal.so
> graphene-sgx-keygen new tool, will generate serviceable RSA-3072 key in proper place

These 2 I could easily add, but not sure if it's worth it, in this PR. Also I don't see much point in `graphene-sgx-keygen`
</blockquote></details>

We can do this in another PR, but we should then create a TODOlist in #11. No strong opinion about `graphene-sgx-keygen` from my side, I guess we need to discuss it.

Ah, and also _use `cryptography` (https://cryptography.io/) instead of `subprocess.run('openssl')` and hand-crafted RSA signature_ is not done.

---
___
*[python/graphene-gen-depend, line 11 at r2](https://reviewable.io/reviews/gramineproject/gramine/72#-MjvKWzS9TyM8961YkmG:-Mk-D0t21OmBwvPANQ-e:b-d8ov5j) ([raw file](https://github.com/gramineproject/gramine/blob/578263e7d17126a6a7a18fbceac17c580c5f7375/python/graphene-gen-depend#L11)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

A long one and short one. Usually the short one is one letter (e.g. `-m`), but I wanted to preserve old cli, so left old versions everywhere.
</blockquote></details>

Ok, but we should deprecate this version at some point...
___
*[python/graphene-gen-depend, line 16 at r2](https://reviewable.io/reviews/gramineproject/gramine/72#-MjvLpn9Eya2wlNR5EYI:-Mk-DHOfBZIm9JZDDbfH:bbca11o) ([raw file](https://github.com/gramineproject/gramine/blob/578263e7d17126a6a7a18fbceac17c580c5f7375/python/graphene-gen-depend#L16)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I've just used what was already here, introduced in https://github.com/gramineproject/gramine/commit/f8c12bac stating `Also, scripts now explicitly use UTF-8 when reading/writing the manifest files because they are written in TOML which forces UTF-8.`
</blockquote></details>

I guess it was just missed there. Could you at least make it lowercase? The uppercased version looks odd to me.
___
*[python/graphenelibos/manifest.py, line 111 at r3](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk-G0oH7Obv4c5TVvgN:-Mk-G0oI-8rObmqZuFXM:b-2iw7b9) ([raw file](https://github.com/gramineproject/gramine/blob/30fec89398d430410f387e34ab29c508e3cddcdb/python/graphenelibos/manifest.py#L111)):*
> ```Python
> 
> def hash_path(path):
>     # FIXME: is this name ok? Doesn't it sound like the path itself is hashed?
> ```

It's bad IMO, why not just `hash_file`?
___
*[python/graphenelibos/manifest.py, line 141 at r3](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk-H44_6Wf7slyQVeZW:-Mk-H44_6Wf7slyQVeZX:blfytwh) ([raw file](https://github.com/gramineproject/gramine/blob/30fec89398d430410f387e34ab29c508e3cddcdb/python/graphenelibos/manifest.py#L141)):*
> ```Python
>     if path.is_dir():
>         if not uri.endswith('/'):
>             # XXX: do we want to check this?
> ```

I think so. I'd just drop this "XXX" and leave the code as is.
___
*[python/graphenelibos/manifest.py, line 143 at r3](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk-Hk1I-V9Yqto3Px1y:-Mk-Hk1J-fMNzO1R7BQa:b-obhu2x) ([raw file](https://github.com/gramineproject/gramine/blob/30fec89398d430410f387e34ab29c508e3cddcdb/python/graphenelibos/manifest.py#L143)):*
> ```Python
>             # XXX: do we want to check this?
>             raise ManifestError(f'Directory URI ({uri}) does not end with "/"')
>         for sub_path in filter(pathlib.Path.is_file, path.rglob('*')):
> ```

You dropped sorting from here, why? It made the manifest generation reproducible.
___
*[python/graphenelibos/manifest.py, line 174 at r3](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk-ISH48IneiVKPaLAv:-Mk-ISH48IneiVKPaLAw:b-dfa207) ([raw file](https://github.com/gramineproject/gramine/blob/30fec89398d430410f387e34ab29c508e3cddcdb/python/graphenelibos/manifest.py#L174)):*
> ```Python
>         loader.setdefault('preload', '')
> 
>         # Current toml versions (< 1.0) do not support non homogeneous arrays
> ```

`non homogeneous` -> `non-homogeneous` (or `nonhomogeneous`)
___
*[python/graphenelibos/manifest.py, line 225 at r3](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk-KJht-C5SEDzGMYsz:-Mk-KJht-C5SEDzGMYt-:b-eq8zxh) ([raw file](https://github.com/gramineproject/gramine/blob/30fec89398d430410f387e34ab29c508e3cddcdb/python/graphenelibos/manifest.py#L225)):*
> ```Python
>             if tf['uri'] in preloads:
>                 preloads_seen = True
>         return preloads_seen or not preloads
> ```

What if there are no preloads, but TFs were not expanded yet? Won't this return `True`?
___
*[python/graphenelibos/manifest.py, line 244 at r3](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk-Kt3V306YgzgwyQCZ:-Mk-Kt3V306YgzgwyQC_:bqnbq4j) ([raw file](https://github.com/gramineproject/gramine/blob/30fec89398d430410f387e34ab29c508e3cddcdb/python/graphenelibos/manifest.py#L244)):*
> ```Python
>         if self.has_tfs_expanded() and self['sgx']['trusted_files']:
>             raise ManifestError('Trusted files are already expanded in this manifest cannot decide '
>                                 'which files are local')
> ```

This sentence is either missing punctuation or some "so"/"because"/"then".
___
*[python/graphenelibos/sigstruct.py, line 64 at r3](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk-XkyXEF29Rrq92KfG:-Mk-XkyXEF29Rrq92KfH:b-v9wwcv) ([raw file](https://github.com/gramineproject/gramine/blob/30fec89398d430410f387e34ab29c508e3cddcdb/python/graphenelibos/sigstruct.py#L64)):*
> ```Python
>             raise KeyError(f'unknown field name {key}')
>         except struct.error:
>             raise ValueError(f'{val} does not match requred format {self.fields[key][1]}')
> ```

`requred` -> `required`


<!-- Sent from Reviewable.io -->

2021-09-20 10:19 UTC, woju requested changes
> Reviewed 2 of 11 files at r3.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/72)* status: all files reviewed, 24 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/72#-MjvW2VNBlZ4l0iOML37:-Mk1IUSM4nCXBgwfjVfI:be5tjye) (no related file):*
> These 2 I could easily add, but not sure if it's worth it, in this PR.

It's not.

> Also I don't see much point in graphene-sgx-keygen

This is nice to have, for easy UX. Nothing you couldn't do with `openssl genrsa` or whatever you please. The main point is to create the key in right path and with correct parameters.

---
___
*[python/graphene-gen-depend, line 1 at r3](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk1OXWz4nPdHMLvfY71:-Mk1OXWz4nPdHMLvfY72:bunp808) ([raw file](https://github.com/gramineproject/gramine/blob/30fec89398d430410f387e34ab29c508e3cddcdb/python/graphene-gen-depend#L1)):*
> ```
> #!/usr/bin/env python3
> ```

Why is this another command, instead of an optional, side output of `graphene-manifest`? Because it's not needed before first make run, the use case is that on subsequent runs the output is regenerated only when needed. Is it "because that's how it was before"?
___
*[python/graphene-gen-depend, line 11 at r3](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk1JIbuDQXDtLD68XdV:-Mk1JIbvCLtu-EzgeU2x:b-388xbm) ([raw file](https://github.com/gramineproject/gramine/blob/30fec89398d430410f387e34ab29c508e3cddcdb/python/graphene-gen-depend#L11)):*
> ```
> 
> @click.command()
> @click.option('--manifest', '-manifest', 'manifest_path', required=True, help='Input .manifest file')
> ```

`@click.option(..., type=click.File('r', encoding='utf-8'))`, and in main the object will be an already open'd file which you don't have to close yourself. Filename is `.name` attribute.

https://click.palletsprojects.com/en/8.0.x/api/#click.File
___
*[python/graphene-gen-depend, line 12 at r3](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk1NTEy13WfCyz2MdQX:-Mk1NTEy13WfCyz2MdQY:b9sb9ch) ([raw file](https://github.com/gramineproject/gramine/blob/30fec89398d430410f387e34ab29c508e3cddcdb/python/graphene-gen-depend#L12)):*
> ```
> @click.command()
> @click.option('--manifest', '-manifest', 'manifest_path', required=True, help='Input .manifest file')
> @click.option('--libpal', '-libpal', default=os.path.join(_CONFIG_PKGLIBDIR, 'sgx/libpal.so'),
> ```

`@click.option(..., type=click.Path(exists=True, dir_okay=False))`

https://click.palletsprojects.com/en/8.0.x/api/#click.Path
___
*[python/graphene-gen-depend, line 14 at r3](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk1Nx3wD9ko8ZYOi42k:-Mk1Nx3wD9ko8ZYOi42l:b-48o3p8) ([raw file](https://github.com/gramineproject/gramine/blob/30fec89398d430410f387e34ab29c508e3cddcdb/python/graphene-gen-depend#L14)):*
> ```
> @click.option('--libpal', '-libpal', default=os.path.join(_CONFIG_PKGLIBDIR, 'sgx/libpal.so'),
>               help='Input libpal file', show_default=True)
> @click.option('--output', '-output', required=True, help='Output .manifest.d file')
> ```

`@click.option(..., type=click.File('w'))`, and I'm not sure about encoding, probably should be left like the rest of the system, because the file contains path names.
___
*[python/graphene-sgx-sign, line 11 at r3](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk1R8Gb7o1Q-2IRLnCh:-Mk1R8Gb7o1Q-2IRLnCi:bopjfr7) ([raw file](https://github.com/gramineproject/gramine/blob/30fec89398d430410f387e34ab29c508e3cddcdb/python/graphene-sgx-sign#L11)):*
> ```
> 
> @click.command()
> @click.option('--output', '-output', required=True,
> ```

`click.File`
___
*[python/graphene-sgx-sign, line 13 at r3](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk1RAh12fFJanFvWtLz:-Mk1RAh12fFJanFvWtM-:b-hn50n2) ([raw file](https://github.com/gramineproject/gramine/blob/30fec89398d430410f387e34ab29c508e3cddcdb/python/graphene-sgx-sign#L13)):*
> ```
> @click.option('--output', '-output', required=True,
>               help='Output .manifest.sgx file (manifest augmented with autogenerated fields)')
> @click.option('--libpal', '-libpal', help='Input libpal file')
> ```

`click.Path`, and this should have a default.
___
*[python/graphene-sgx-sign, line 14 at r3](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk1RLQl6XawystFeBck:-Mk1RLQl6XawystFeBcl:b-pdbobq) ([raw file](https://github.com/gramineproject/gramine/blob/30fec89398d430410f387e34ab29c508e3cddcdb/python/graphene-sgx-sign#L14)):*
> ```
>               help='Output .manifest.sgx file (manifest augmented with autogenerated fields)')
> @click.option('--libpal', '-libpal', help='Input libpal file')
> @click.option('--key', '-key', required=True, help='specify signing key (.pem) file')
> ```

`click.Path` I guess
___
*[python/graphene-sgx-sign, line 15 at r3](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk1RPYs81G9JblM7mgh:-Mk1RPYt6rVY_85A7taM:bopjfr7) ([raw file](https://github.com/gramineproject/gramine/blob/30fec89398d430410f387e34ab29c508e3cddcdb/python/graphene-sgx-sign#L15)):*
> ```
> @click.option('--libpal', '-libpal', help='Input libpal file')
> @click.option('--key', '-key', required=True, help='specify signing key (.pem) file')
> @click.option('--manifest', '-manifest', 'manifest_path', required=True,
> ```

`click.File`
___
*[python/graphene-sgx-sign, line 17 at r3](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk1RQjyAP4D6bUMN8Xv:-Mk1RQjz63QRQdOHmFK6:b-21179w) ([raw file](https://github.com/gramineproject/gramine/blob/30fec89398d430410f387e34ab29c508e3cddcdb/python/graphene-sgx-sign#L17)):*
> ```
> @click.option('--manifest', '-manifest', 'manifest_path', required=True,
>               help='Input .manifest file')
> @click.option('--sigfile', '-sigfile', help='Output .sig file')
> ```

`click.File('wb')` probably
___
*[python/graphenelibos/__init__.py, line 16 at r3](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk1QeTK-aCE26CsY0S7:-Mk1QeTK-aCE26CsY0S8:bo1cfro) ([raw file](https://github.com/gramineproject/gramine/blob/30fec89398d430410f387e34ab29c508e3cddcdb/python/graphenelibos/__init__.py#L16)):*
> ```Python
> # pylint: disable=wrong-import-position
> from .manifest import Manifest
> if '@SGX_ENABLED@' == '1':
> ```

Why not just

```python
try:
    from .sgx_whatever import something
    #...
except ImportError:
    pass
```

?
___
*[python/graphenelibos/manifest.py, line 111 at r3](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk-G0oH7Obv4c5TVvgN:-Mk1PkVABgy9OwCK_e5G:b32v57) ([raw file](https://github.com/gramineproject/gramine/blob/30fec89398d430410f387e34ab29c508e3cddcdb/python/graphenelibos/manifest.py#L111)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

It's bad IMO, why not just `hash_file`?
</blockquote></details>

+1
___
*[python/graphenelibos/manifest.py, line 141 at r3](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk-H44_6Wf7slyQVeZW:-Mk1SgS_E_t584pURyGa:b32v57) ([raw file](https://github.com/gramineproject/gramine/blob/30fec89398d430410f387e34ab29c508e3cddcdb/python/graphenelibos/manifest.py#L141)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I think so. I'd just drop this "XXX" and leave the code as is.
</blockquote></details>

+1
___
*[python/graphenelibos/manifest.py, line 150 at r3](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk1hIEJ74pScPgHwqIw:-Mk1hIEJ74pScPgHwqIx:b2mql6d) ([raw file](https://github.com/gramineproject/gramine/blob/30fec89398d430410f387e34ab29c508e3cddcdb/python/graphenelibos/manifest.py#L150)):*
> ```Python
> 
> class Manifest:
>     _env = make_env()
> ```

Jinja env should not belong to this class, it should either be globa [...]

2021-09-20 12:32 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/72)* status: 17 of 22 files reviewed, 24 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/72#-MjvW2VNBlZ4l0iOML37:-Mk1bAhM0SFl_dLU_MaY:b-6k9dso) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

> These 2 I could easily add, but not sure if it's worth it, in this PR.

It's not.

> Also I don't see much point in graphene-sgx-keygen

This is nice to have, for easy UX. Nothing you couldn't do with `openssl genrsa` or whatever you please. The main point is to create the key in right path and with correct parameters.
</blockquote></details>

All right, let's add the TODO list after the review.

---
___
*[python/graphene-gen-depend, line 16 at r2](https://reviewable.io/reviews/gramineproject/gramine/72#-MjvLpn9Eya2wlNR5EYI:-Mk1WdSZEZpmxrRgwB9y:b5kqbe0) ([raw file](https://github.com/gramineproject/gramine/blob/578263e7d17126a6a7a18fbceac17c580c5f7375/python/graphene-gen-depend#L16)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I guess it was just missed there. Could you at least make it lowercase? The uppercased version looks odd to me.
</blockquote></details>

I've left the explicit encoding - after all we now expose and API, so if somebody uses our library and changed the encoding in their script, things would break.
___
*[python/graphene-gen-depend, line 1 at r3](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk1OXWz4nPdHMLvfY71:-Mk1syUo0GkYM5-r8BwN:bqglf5w) ([raw file](https://github.com/gramineproject/gramine/blob/30fec89398d430410f387e34ab29c508e3cddcdb/python/graphene-gen-depend#L1)):*
> Is it "because that's how it was before"?

Yes. Also, normal manifests don't need it, only the sgx ones (because hashes change), yet it can only be generated based on a normal manifest (i.e. before TFs are expanded). It got a bit messy.
___
*[python/graphene-gen-depend, line 11 at r3](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk1JIbuDQXDtLD68XdV:-Mk1tTdU3kmOxTGEzBJV:b-dqk8wm) ([raw file](https://github.com/gramineproject/gramine/blob/30fec89398d430410f387e34ab29c508e3cddcdb/python/graphene-gen-depend#L11)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

`@click.option(..., type=click.File('r', encoding='utf-8'))`, and in main the object will be an already open'd file which you don't have to close yourself. Filename is `.name` attribute.

https://click.palletsprojects.com/en/8.0.x/api/#click.File
</blockquote></details>

I didn't use `File` because I needed it's path and didn't know `.name` exists. Where can I find such info? click documentation is silent about it...
___
*[python/graphene-gen-depend, line 12 at r3](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk1NTEy13WfCyz2MdQX:-Mk1wubz6DsdeNawR1Sk:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/30fec89398d430410f387e34ab29c508e3cddcdb/python/graphene-gen-depend#L12)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

`@click.option(..., type=click.Path(exists=True, dir_okay=False))`

https://click.palletsprojects.com/en/8.0.x/api/#click.Path
</blockquote></details>

Done.
___
*[python/graphene-gen-depend, line 14 at r3](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk1Nx3wD9ko8ZYOi42k:-Mk1xd1DDSg1wpouHy1t:b4gxs60) ([raw file](https://github.com/gramineproject/gramine/blob/30fec89398d430410f387e34ab29c508e3cddcdb/python/graphene-gen-depend#L14)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

`@click.option(..., type=click.File('w'))`, and I'm not sure about encoding, probably should be left like the rest of the system, because the file contains path names.
</blockquote></details>

Done. I've added explicit encoding - these path names must be 'utf-8' encodable, because they end up in our manifests (and TOML requires UTF-8).
___
*[python/graphene-sgx-sign, line 11 at r3](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk1R8Gb7o1Q-2IRLnCh:-Mk1ylTk-jfDuVJLK3Iq:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/30fec89398d430410f387e34ab29c508e3cddcdb/python/graphene-sgx-sign#L11)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

`click.File`
</blockquote></details>

Done.
___
*[python/graphene-sgx-sign, line 13 at r3](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk1RAh12fFJanFvWtLz:-Mk1zDTIA-C5RfT4KG3c:b-dyqaoe) ([raw file](https://github.com/gramineproject/gramine/blob/30fec89398d430410f387e34ab29c508e3cddcdb/python/graphene-sgx-sign#L13)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

`click.Path`, and this should have a default.
</blockquote></details>

Done. `default` is useless here, as the API call where it's used `get_mrenclave` must handle missing `libpal` anyway.
___
*[python/graphene-sgx-sign, line 14 at r3](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk1RLQl6XawystFeBck:-Mk2-1hv-I-WheL4rzb-:b3bx2p2) ([raw file](https://github.com/gramineproject/gramine/blob/30fec89398d430410f387e34ab29c508e3cddcdb/python/graphene-sgx-sign#L14)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

`click.Path` I guess
</blockquote></details>

Yeah. We should be able to change to `File` when we migrate to `cryptography`.
___
*[python/graphene-sgx-sign, line 15 at r3](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk1RPYs81G9JblM7mgh:-Mk2-g-e6-gTw9fXQ91c:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/30fec89398d430410f387e34ab29c508e3cddcdb/python/graphene-sgx-sign#L15)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

`click.File`
</blockquote></details>

Done.
___
*[python/graphene-sgx-sign, line 17 at r3](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk1RQjyAP4D6bUMN8Xv:-Mk2-lyW2Wj1XEvAp16L:b-wbcq8u) ([raw file](https://github.com/gramineproject/gramine/blob/30fec89398d430410f387e34ab29c508e3cddcdb/python/graphene-sgx-sign#L17)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

`click.File('wb')` probably
</blockquote></details>

We have to open the file manually anyway (sometimes), so I left this as is. Maybe this could be done with some mixture of callbacks, proper laziness and extracting other arguments (`manifest_file`) from context, but I'm not familiar enough with click and it would probably be ugly.
___
*[python/graphenelibos/__init__.py, line 16 at r3](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk1QeTK-aCE26CsY0S7:-Mk20pYb1TM0-IHwXrwI:b-99to9t) ([raw file](https://github.com/gramineproject/gramine/blob/30fec89398d430410f387e34ab29c508e3cddcdb/python/graphenelibos/__init__.py#L16)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Why not just

```python
try:
    from .sgx_whatever import something
    #...
except ImportError:
    pass
```

?
</blockquote></details>

This proved very useful while debugging. I can change it as the last thing, but I don't like it: it would silence all `ImportError`s from these submodules. 
___
*[python/graphenelibos/manifest.py, line 111 at r3](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk-G0oH7Obv4c5TVvgN:-Mk1_qlB7Iey0TXn8Ouv:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/30fec89398d430410f387e34ab29c508e3cddcdb/python/graphenelibos/manifest.py#L111)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

It's bad IMO, why  [...]

2021-09-20 13:11 UTC, mkow requested changes
> Reviewed 4 of 5 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/72)* status: all files reviewed, 17 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @woju)

___
*[python/graphenelibos/__init__.py, line 16 at r3](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk1QeTK-aCE26CsY0S7:-Mk2J0wW7rSy-q8tQh4c:b7pcn14) ([raw file](https://github.com/gramineproject/gramine/blob/30fec89398d430410f387e34ab29c508e3cddcdb/python/graphenelibos/__init__.py#L16)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This proved very useful while debugging. I can change it as the last thing, but I don't like it: it would silence all `ImportError`s from these submodules. 
</blockquote></details>

+1, `except ImportError:` sounds like a footgun, as it catches also import errors from deeper levels
___
*[python/graphenelibos/manifest.py, line 143 at r3](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk-Hk1I-V9Yqto3Px1y:-Mk2JJKg092HTTCVvScg:bvk5hwc) ([raw file](https://github.com/gramineproject/gramine/blob/30fec89398d430410f387e34ab29c508e3cddcdb/python/graphenelibos/manifest.py#L143)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Hm, so that was the reason behind that sort? Is `rglob(*)` not reproducible if run on the same fs layout?
</blockquote></details>

I think `rglob()` doesn't have any guarantees about the order, I guess it just calls `readdir()` recursively and filters the results.
___
*[python/graphenelibos/manifest.py, line 225 at r3](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk-KJht-C5SEDzGMYsz:-Mk2Jyhb5lwjhg_SDzEo:b-7vo826) ([raw file](https://github.com/gramineproject/gramine/blob/30fec89398d430410f387e34ab29c508e3cddcdb/python/graphenelibos/manifest.py#L225)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

No. It would return `True` if there are no preloads and no TFs. The loop above checks whether a TF is expanded already and directly returns `False` otherwise.
</blockquote></details>

Ah, I see.


<!-- Sent from Reviewable.io -->

2021-09-20 14:34 UTC, woju requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/72)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[Pal/regression/Bootstrap3.manifest, line 6 at r3](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk1xh5uDtgjd1m_DkAJ:-Mk1xh5uDtgjd1m_DkAK:b-a4sgal) ([raw file](https://github.com/gramineproject/gramine/blob/30fec89398d430410f387e34ab29c508e3cddcdb/Pal/regression/Bootstrap3.manifest#L6)):*
> ```
> loader.argv0_override = "Bootstrap3"
> 
> sgx.trusted_files = [ "file:Bootstrap3" ]
> ```

No spaces inside parenthesis.
___
*[python/graphene-gen-depend, line 1 at r3](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk1OXWz4nPdHMLvfY71:-Mk2Dhz4DE48X7rsmx66:b-k83rfp) ([raw file](https://github.com/gramineproject/gramine/blob/30fec89398d430410f387e34ab29c508e3cddcdb/python/graphene-gen-depend#L1)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

> Is it "because that's how it was before"?

Yes. Also, normal manifests don't need it, only the sgx ones (because hashes change), yet it can only be generated based on a normal manifest (i.e. before TFs are expanded). It got a bit messy.
</blockquote></details>

Sure, I guess we can sort it out later.
___
*[python/graphene-gen-depend, line 11 at r3](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk1JIbuDQXDtLD68XdV:-Mk2CHBY0I6NnTBNrbyW:b-tkyi18) ([raw file](https://github.com/gramineproject/gramine/blob/30fec89398d430410f387e34ab29c508e3cddcdb/python/graphene-gen-depend#L11)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I didn't use `File` because I needed it's path and didn't know `.name` exists. Where can I find such info? click documentation is silent about it...
</blockquote></details>

Because this is a general python feature, documented in https://docs.python.org/3/library/io.html#io.FileIO.name. Every `open()`ed file has such attribute and I guess click devs assumed you should have known it already.
___
*[python/graphene-gen-depend, line 12 at r3](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk1NTEy13WfCyz2MdQX:-Mk2Es0_4dUkzcG9lVTj:bgqr9gk) ([raw file](https://github.com/gramineproject/gramine/blob/30fec89398d430410f387e34ab29c508e3cddcdb/python/graphene-gen-depend#L12)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Wait, why there's `sgx/` hardcoded there?
___
*[python/graphene-gen-depend, line 14 at r3](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk1Nx3wD9ko8ZYOi42k:-Mk2PQR70YOMHAM5HOqx:b-h7rf3v) ([raw file](https://github.com/gramineproject/gramine/blob/30fec89398d430410f387e34ab29c508e3cddcdb/python/graphene-gen-depend#L14)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Done. I've added explicit encoding - these path names must be 'utf-8' encodable, because they end up in our manifests (and TOML requires UTF-8).
</blockquote></details>

I guess it's OK. Technically you can have invalid UTF-8 strings in TOML, they're encoded with surrogates, but I'm not sure what would then break.
___
*[python/graphene-sgx-sign, line 17 at r3](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk1RQjyAP4D6bUMN8Xv:-Mk2Q5uXAwe9JRl5JUnT:bvurjwx) ([raw file](https://github.com/gramineproject/gramine/blob/30fec89398d430410f387e34ab29c508e3cddcdb/python/graphene-sgx-sign#L17)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

We have to open the file manually anyway (sometimes), so I left this as is. Maybe this could be done with some mixture of callbacks, proper laziness and extracting other arguments (`manifest_file`) from context, but I'm not familiar enough with click and it would probably be ugly.
</blockquote></details>

OK, let's think about this another time.
___
*[python/graphenelibos/__init__.py, line 16 at r3](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk1QeTK-aCE26CsY0S7:-Mk2ZW0F5wY56ZJVgI82:b-8dwua1) ([raw file](https://github.com/gramineproject/gramine/blob/30fec89398d430410f387e34ab29c508e3cddcdb/python/graphenelibos/__init__.py#L16)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

+1, `except ImportError:` sounds like a footgun, as it catches also import errors from deeper levels
</blockquote></details>

The problem is, everyone using this modules has to do their own try/except, because just importing graphenelibos means you can have those attributes or not, so we're not solving anything with this contraption.

So maybe we shouldn't expose those APIs as part of this module, but have something like `graphenelibos.sgx` instead?
___
*[python/graphenelibos/manifest.py, line 111 at r3](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk-G0oH7Obv4c5TVvgN:-Mk2QRcTCJC2I5C7h6H9:b-rlob0d) ([raw file](https://github.com/gramineproject/gramine/blob/30fec89398d430410f387e34ab29c508e3cddcdb/python/graphenelibos/manifest.py#L111)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I like this.
___
*[python/graphenelibos/manifest.py, line 150 at r3](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk1hIEJ74pScPgHwqIw:-Mk2RBSG3JS2Tl8Q3lMQ:b-ynguf9) ([raw file](https://github.com/gramineproject/gramine/blob/30fec89398d430410f387e34ab29c508e3cddcdb/python/graphenelibos/manifest.py#L150)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why? It's tightly couple with this class (used and required) and we have only one instance of it shared by all instanced of `Manifest` class. Also if you ever want to create some specialized `Manifest` subclass, you can adjust it only for that subclass. This lead me to putting it here.
</blockquote></details>

It starts to matter when you have loaders for templates and/or some configurable globals (like "debug" maybe?). Those are typically set somewhere around main.
___
*[python/graphenelibos/manifest.py, line 152 at r3](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk1e84QD5e4gGeUjdbC:-Mk2Ru9Q4fXSCjCBboFs:b-wcjwt8) ([raw file](https://github.com/gramineproject/gramine/blob/30fec89398d430410f387e34ab29c508e3cddcdb/python/graphenelibos/manifest.py#L152)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Keep in mind that there are some functions/APIs that I did not change (e.g. actual mrenclave calculations).

> Something is wrong about instantiating manifest from string/bytes vs get_mrenclave. In the current version there's no way to get mrenclave from a manifest given by file without load+dump again, but it'll be needed when you are on the other end of RA-TLS and would like to verify mrenclave against known manifest.

This is not true, other end in case of RATLS can, and actually have to, parse the manifest, so `load()` is inevitable. `dump()` might not be needed - discussed below.

> In that path you should just calculate from bytes, as read from file, because loading and dumping might change order, drop comments and/or whitespace etc.

That's true, see below.

> I don't know where this should be fixed, the easiest way probably would be to accept bytes as arguments to get_mrenclave. The Pythonic Way™ would be to make Manifest instances immutable and have it hold two parallel data structures, bytes and dict, so if you need the other, you silently generate it.

We cannot make all `Manifest` instances immutable, because this class is used everywhere.

What I can do is create a subclass `SignedManifest` (or `ConstManifest [...]

2021-09-20 23:05 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/72)* status: 20 of 24 files reviewed, 10 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @woju)

___
*[-- commits, line 1 at r6](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk2ybQw4olgiwOGjK-T):*
TODO (at rebase): reorder commits, so FIX is the first.
___
*[Pal/regression/Bootstrap3.manifest, line 6 at r3](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk1xh5uDtgjd1m_DkAJ:-Mk2mMmh-wun4bWDZ2eP:blbvpz1) ([raw file](https://github.com/gramineproject/gramine/blob/30fec89398d430410f387e34ab29c508e3cddcdb/Pal/regression/Bootstrap3.manifest#L6)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

No spaces inside parenthesis.
</blockquote></details>

Why? This looks more readable.
___
*[python/graphene-gen-depend, line 11 at r3](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk1JIbuDQXDtLD68XdV:-Mk2mjD6-47JOK31VEyt:b56m0os) ([raw file](https://github.com/gramineproject/gramine/blob/30fec89398d430410f387e34ab29c508e3cddcdb/python/graphene-gen-depend#L11)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Because this is a general python feature, documented in https://docs.python.org/3/library/io.html#io.FileIO.name. Every `open()`ed file has such attribute and I guess click devs assumed you should have known it already.
</blockquote></details>

Well, how could I knew they are not using any wrappers?
___
*[python/graphene-gen-depend, line 12 at r3](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk1NTEy13WfCyz2MdQX:-Mk2nLMs6vlmwRTcG1i2:b-sgsqb9) ([raw file](https://github.com/gramineproject/gramine/blob/30fec89398d430410f387e34ab29c508e3cddcdb/python/graphene-gen-depend#L12)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Wait, why there's `sgx/` hardcoded there?
</blockquote></details>

What is hardcoded where?
___
*[python/graphenelibos/__init__.py, line 16 at r3](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk1QeTK-aCE26CsY0S7:-Mk2nlcECzg-CHexMd8D:b-z9rzes) ([raw file](https://github.com/gramineproject/gramine/blob/30fec89398d430410f387e34ab29c508e3cddcdb/python/graphenelibos/__init__.py#L16)):*
> The problem is, everyone using this modules has to do their own try/except, because just importing graphenelibos means you can have those attributes or not, so we're not solving anything with this contraption.

What? This is substituted by meson, just like some variables above. So if you've installed SGX version, they you have these files and if you didn't, they they are not imported. No need for any try+except.
___
*[python/graphenelibos/manifest.py, line 143 at r3](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk-Hk1I-V9Yqto3Px1y:-Mk2o65P4qQ_m6N3VTKm:b-dlolmo) ([raw file](https://github.com/gramineproject/gramine/blob/30fec89398d430410f387e34ab29c508e3cddcdb/python/graphenelibos/manifest.py#L143)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I think `rglob()` doesn't have any guarantees about the order, I guess it just calls `readdir()` recursively and filters the results.
</blockquote></details>

Done.
We also base on the fact that dict is ordered, which is only true since python 3.7 (in practice 3.6).
Also we base on the fact that the python TOML implemenation we use is ordered, which I'm not sure is true.
Given the above I'm not sure we want this change and I'm thinking about reverting it (i.e. there seem to be no point in it).
___
*[python/graphenelibos/manifest.py, line 150 at r3](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk1hIEJ74pScPgHwqIw:-Mk2opfs1YD2tjlqg8U4:b-4xto88) ([raw file](https://github.com/gramineproject/gramine/blob/30fec89398d430410f387e34ab29c508e3cddcdb/python/graphenelibos/manifest.py#L150)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

It starts to matter when you have loaders for templates and/or some configurable globals (like "debug" maybe?). Those are typically set somewhere around main.
</blockquote></details>

If I put `_env` in global scope it wont change anything w.r.t. arguments you gave.
___
*[python/graphenelibos/manifest.py, line 152 at r3](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk1e84QD5e4gGeUjdbC:-Mk4RTSL4EA1rbYJT1RI:b-dr0nik) ([raw file](https://github.com/gramineproject/gramine/blob/30fec89398d430410f387e34ab29c508e3cddcdb/python/graphenelibos/manifest.py#L152)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

"Immutable" doesn't need to be truly immutable, it'd be enough to have the actual mutable thingy `_`-private and have all exposed methods which "change" something return new instances. Also there are primitives for read-only dicts like https://docs.python.org/3/library/types.html#types.MappingProxyType (this is actually a view, you need to have underlying dict) and maybe TOML parser could be persuaded to return such objects. Or `Manifest.from_dict` could change dicts recursively to mapping proxies.

But if this is too much work, then maybe just `get_mrenclave` should accept bytes (or `rb`-opened file), and parse them to a Manifest itself?
</blockquote></details>

Postponing this for now, need to think about a good solution (e.g. issue: `Manifest` exposes a `__setitem__`, but we can also change it indirectly, e.g. `manifest['sgx']['something'] = 'asdf'`).
___
*[python/graphenelibos/manifest.py, line 228 at r3](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk1V3qA9p7vv4p8-8AN:-Mk2rKf28O3V_nuKlwB6:b-scej3h) ([raw file](https://github.com/gramineproject/gramine/blob/30fec89398d430410f387e34ab29c508e3cddcdb/python/graphenelibos/manifest.py#L228)):*
> What's the difference between a file that wasn't expanded and preloads? Isn't it just that it's on a different list before being measured?

Preloads are expanded implicitly and are not on TFs list by default.

> Also, IIUC this means that it's an error to write a manifest with preload already present in trusted files.

Yes it is an error to do so, just like specifying same file twice.

> That's probably not a useful thing to do, but not that harmful either (if you didn't make a mistake while copy-pasting the hash).

That's true.

I've changed it so that you can manually expand preloads

Update: nvm, I've decided to completely remove `has_tfs_expanded` as currently it was only used in deps generation, which we probably will remove in the future.


<!-- Sent from Reviewable.io -->

2021-09-20 23:28 UTC, mkow reviewed
> Reviewed 1 of 1 files at r6, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/72)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @woju)

___
*[python/graphenelibos/manifest.py, line 143 at r3](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk-Hk1I-V9Yqto3Px1y:-Mk4Wb7vDAS30GPilUn6:b-xo1p7l) ([raw file](https://github.com/gramineproject/gramine/blob/30fec89398d430410f387e34ab29c508e3cddcdb/python/graphenelibos/manifest.py#L143)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Done.
We also base on the fact that dict is ordered, which is only true since python 3.7 (in practice 3.6).
Also we base on the fact that the python TOML implemenation we use is ordered, which I'm not sure is true.
Given the above I'm not sure we want this change and I'm thinking about reverting it (i.e. there seem to be no point in it).
</blockquote></details>

I'd leave it. That we aren't reproducible yet doesn't mean that we shouldn't make the code reproducible. It will make doing it later easier.


<!-- Sent from Reviewable.io -->

2021-09-21 10:01 UTC, dimakuv requested changes
> Reviewed 10 of 21 files at r1, 7 of 11 files at r3, 3 of 5 files at r4, 1 of 1 files at r6, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/72)* status: all files reviewed, 17 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @woju)

___
*[-- commits, line 32 at r7](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk6YwLtDJ9X2YccCymY):*
`build` -> `built` (2x)

`linked each version is linked...` -- broken English
___
*[-- commits, line 47 at r7](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk6Z5PtEd0Zhgk4yGfA):*
Why do you write `for Trusted Files`? These should be `Protected Files`.

Also, I think we should also allow the opposite case: translate `O_RDONLY` to `O_RDWR` because it may also require changes in the PF metadata (see e.g. the `PF rename` PR: https://github.com/gramineproject/gramine/pull/31)
___
*[LibOS/shim/test/fs/Makefile, line 52 at r7](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk6_2YyA6Z24LAtNSvw:-Mk6_2YyA6Z24LAtNSvx:b-gm5n0p) ([raw file](https://github.com/gramineproject/gramine/blob/a192d04d5d73a8b254438c83c00749b19ba666bc/LibOS/shim/test/fs/Makefile#L52)):*
> ```Makefile
> common_copy_mmap.o: CFLAGS += -DCOPY_MMAP
> common_copy_mmap.o: common_copy.c
> 	$(call cmd,cc_o_c)
> ```

How did this bug manifest itself? Why didn't we notice it previously?
___
*[Pal/regression/Makefile, line 80 at r7](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk6f_QXB8CHbag9FEQD:-Mk6f_QXB8CHbag9FEQE:ba9k32a) ([raw file](https://github.com/gramineproject/gramine/blob/a192d04d5d73a8b254438c83c00749b19ba666bc/Pal/regression/Makefile#L80)):*
> ```Makefile
> graphene = direct
> endif
> pal_lib ?= $(shell graphene-manifest -c 'EXTRACT = "{{ graphene.pkglibdir }}"' | grep -F EXTRACT | sed -e "s/EXTRACT = \"\(.*\)\"/\1/")/$(graphene)/libpal.so
> ```

What does it do? Why is it needed?
___
*[Pal/src/host/Linux-SGX/db_files.c, line 137 at r7](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk6foBpBOKHl2x_eVQj:-Mk6foBpBOKHl2x_eVQk:b8f14vp) ([raw file](https://github.com/gramineproject/gramine/blob/a192d04d5d73a8b254438c83c00749b19ba666bc/Pal/src/host/Linux-SGX/db_files.c#L137)):*
> ```C
>              * (e.g. some metadata got invalidated). */
>             flags = (flags & ~O_ACCMODE) | O_RDWR;
>         }
> ```

I would change `flags` unconditionally and add a comment about this, that Protected Files sometimes need to be read/written even if they are opened with another access mode.

https://github.com/gramineproject/gramine/pull/31 needs this as well. That PR goes to great lengths to conditionally change `flags` as well (only for the rename flow). With the unconditional assignment, a lot of complexity goes away.
___
*[python/graphene-sgx-get-token, line 16 at r7](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk6iHfeAJpM0M5ma12J:-Mk6iHfeAJpM0M5ma12K:b88ixbc) ([raw file](https://github.com/gramineproject/gramine/blob/a192d04d5d73a8b254438c83c00749b19ba666bc/python/graphene-sgx-get-token#L16)):*
> ```
>     token = get_token(sig)
>     if output:
>         output.write(token)
> ```

Why is `output` not required? What is the usage of `graphene-sgx-get-token --sig myfile`?
___
*[python/graphenelibos/manifest.py, line 140 at r7](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk6k3fL7tXZsjWxUYj7:-Mk6k3fL7tXZsjWxUYj8:b-ky23qg) ([raw file](https://github.com/gramineproject/gramine/blob/a192d04d5d73a8b254438c83c00749b19ba666bc/python/graphenelibos/manifest.py#L140)):*
> ```Python
>     if path.is_dir():
>         if not uri.endswith('/'):
>             raise ManifestError(f'Directory URI ({uri}) does not end with "/"')
> ```

Why do you have this artificial requirement? Will it not break existing manifest templates?
___
*[python/graphenelibos/sgx_sign.py, line 61 at r7](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk6maQLCabLGCSkBXWI:-Mk6maQLCabLGCSkBXWJ:by1977i) ([raw file](https://github.com/gramineproject/gramine/blob/a192d04d5d73a8b254438c83c00749b19ba666bc/python/graphenelibos/sgx_sign.py#L61)):*
> ```Python
>     for opt, bit in options_dict.items():
>         if manifest_sgx[opt] == 1:
>             val |= bit
> ```

Some items in `options_dict` are not single-bit. A good example is `offs.SGX_XFRM_AVX512` which has three bits set.

So at least change `bit` -> `bits`. I don't see that there can be any problems with the current code, but take this multiple-bit case into consideration.


<!-- Sent from Reviewable.io -->

2021-09-21 12:24 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/72)* status: all files reviewed, 17 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @woju)

___
*[LibOS/shim/test/fs/Makefile, line 52 at r7](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk6_2YyA6Z24LAtNSvw:-Mk7IJxl6lUA97-hxBif:b-itma8i) ([raw file](https://github.com/gramineproject/gramine/blob/a192d04d5d73a8b254438c83c00749b19ba666bc/LibOS/shim/test/fs/Makefile#L52)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

How did this bug manifest itself? Why didn't we notice it previously?
</blockquote></details>

`Make` chose the version randomly and everything ended up compiled with RDWR, so it just worked.
___
*[Pal/regression/Makefile, line 80 at r7](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk6f_QXB8CHbag9FEQD:-Mk7IV3JC4SDtsQXq2v4:bb3xrcz) ([raw file](https://github.com/gramineproject/gramine/blob/a192d04d5d73a8b254438c83c00749b19ba666bc/Pal/regression/Makefile#L80)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What does it do? Why is it needed?
</blockquote></details>

Because the old `-c` was weird, it only rendered the Jinja template, but didn't treat this as TOML. And the old argument was an invalid TOML, so it exploded on Borys' rework.
___
*[python/graphenelibos/manifest.py, line 140 at r7](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk6k3fL7tXZsjWxUYj7:-Mk7IuRL7QmS_3eZDxPi:b-3cu1r9) ([raw file](https://github.com/gramineproject/gramine/blob/a192d04d5d73a8b254438c83c00749b19ba666bc/python/graphenelibos/manifest.py#L140)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do you have this artificial requirement? Will it not break existing manifest templates?
</blockquote></details>

I like it, I think this is a very reasonable requirement for manifest readability.


<!-- Sent from Reviewable.io -->

2021-09-21 15:52 UTC, bigdata-memory reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/72)* status: all files reviewed, 14 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/72#-MjtXxWh9ULgbAUYCJnF:-Mk80tE56JQsMQgGcCFs:bbwrbjm) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

TOOD: write documentation (but first we need to settle whether the new APIs are ok)
</blockquote></details>

This feature is expected to interact with signing facility for 2 step signing that has a clear boundary defined in Intel dev. reference document. the difference should be clarified and elaborated first for us to evaluate the changes/impact on existing signing facility, thanks.

---


<!-- Sent from Reviewable.io -->

2021-09-21 18:20 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/72)* status: all files reviewed, 14 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @woju)

___
*[-- commits, line 47 at r7](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk6Z5PtEd0Zhgk4yGfA):*
<details><summary><i>Previously, bigdata-memory (Gordon King) wrote…</i></summary><blockquote>

This workaround may need to be further explained in documentation w.r.t security and also produce warning messages when it got triggered, thanks.
</blockquote></details>

This has nothing to do with security.


<!-- Sent from Reviewable.io -->

2021-09-21 23:29 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/72)* status: 20 of 25 files reviewed, 14 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/72#-MjtXxWh9ULgbAUYCJnF:-Mk9eRJQ7IEAVZBAjAf6:bz2kher) (no related file):*
> This feature is expected to interact with signing facility for 2 step signing that has a clear boundary defined in Intel dev. reference document. 

I do not understand this.

Generally, now we expose a python API, which can use any signing callback whatsoever.

---
___
*[-- commits, line 32 at r7](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk6YwLtDJ9X2YccCymY):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`build` -> `built` (2x)

`linked each version is linked...` -- broken English
</blockquote></details>

TODO: at rebase
___
*[-- commits, line 47 at r7](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk6Z5PtEd0Zhgk4yGfA):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This has nothing to do with security.
</blockquote></details>

@dimakuv typo, need to fix at rebase. As for other change: sure, but let's not do this here (or submit another PR which we can merge quickly, then I would drop this commit)
@bigdata-memory no, it does not need to
___
*[LibOS/shim/test/fs/Makefile, line 52 at r7](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk6_2YyA6Z24LAtNSvw:-Mk80Ixf4g7wQ53gcify:b-dfbe1r) ([raw file](https://github.com/gramineproject/gramine/blob/a192d04d5d73a8b254438c83c00749b19ba666bc/LibOS/shim/test/fs/Makefile#L52)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`Make` chose the version randomly and everything ended up compiled with RDWR, so it just worked.
</blockquote></details>

Yeah, this PR added another dependency on the final binary, which changed the order of building. Previously everything was RW.
___
*[Pal/regression/Makefile, line 80 at r7](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk6f_QXB8CHbag9FEQD:-Mk80WLJ87cxkyJjY4Sw:b-tuik1l) ([raw file](https://github.com/gramineproject/gramine/blob/a192d04d5d73a8b254438c83c00749b19ba666bc/Pal/regression/Makefile#L80)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Because the old `-c` was weird, it only rendered the Jinja template, but didn't treat this as TOML. And the old argument was an invalid TOML, so it exploded on Borys' rework.
</blockquote></details>

Exactly
___
*[python/graphene-sgx-get-token, line 16 at r7](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk6iHfeAJpM0M5ma12J:-Mk812JXCG-ApAmThW8t:b-oa3n8h) ([raw file](https://github.com/gramineproject/gramine/blob/a192d04d5d73a8b254438c83c00749b19ba666bc/python/graphene-sgx-get-token#L16)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why is `output` not required? What is the usage of `graphene-sgx-get-token --sig myfile`?
</blockquote></details>

I've just preserver old CLI syntax 1 to 1. The answer is: no, even slightest, idea.
___
*[python/graphenelibos/manifest.py, line 152 at r3](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk1e84QD5e4gGeUjdbC:-Mk9fsruC6z1AANdGsAQ:bl2u0e2) ([raw file](https://github.com/gramineproject/gramine/blob/30fec89398d430410f387e34ab29c508e3cddcdb/python/graphenelibos/manifest.py#L152)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Postponing this for now, need to think about a good solution (e.g. issue: `Manifest` exposes a `__setitem__`, but we can also change it indirectly, e.g. `manifest['sgx']['something'] = 'asdf'`).
</blockquote></details>

`get_mrenclave` now takes a path, I've figured this is the best way to stop ppl shooting their feet, and integrates ok-ish with other functions. It now also returns a manifest, in case you need that too (since it's already parsed).
___
*[python/graphenelibos/manifest.py, line 140 at r7](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk6k3fL7tXZsjWxUYj7:-Mk81NuI-ni22XofQpa8:bfk2zt0) ([raw file](https://github.com/gramineproject/gramine/blob/a192d04d5d73a8b254438c83c00749b19ba666bc/python/graphenelibos/manifest.py#L140)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Hm, ok.
</blockquote></details>

I thought we had that requirement already. Anyway, all current manifests are written like that.


<!-- Sent from Reviewable.io -->

2021-09-21 23:53 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/72)* status: 18 of 25 files reviewed, 14 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @woju)

___
*[Pal/src/host/Linux-SGX/db_files.c, line 137 at r7](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk6foBpBOKHl2x_eVQj:-Mk80h9rApId7eB7yCBK:b-ogehkm) ([raw file](https://github.com/gramineproject/gramine/blob/a192d04d5d73a8b254438c83c00749b19ba666bc/Pal/src/host/Linux-SGX/db_files.c#L137)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I would change `flags` unconditionally and add a comment about this, that Protected Files sometimes need to be read/written even if they are opened with another access mode.

https://github.com/gramineproject/gramine/pull/31 needs this as well. That PR goes to great lengths to conditionally change `flags` as well (only for the rename flow). With the unconditional assignment, a lot of complexity goes away.
</blockquote></details>

Let's stick the discussion to one place (in commit messages).
___
*[python/graphenelibos/sgx_sign.py, line 61 at r7](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk6maQLCabLGCSkBXWI:-Mk9lYsU6K6CXMMY6tMd:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/a192d04d5d73a8b254438c83c00749b19ba666bc/python/graphenelibos/sgx_sign.py#L61)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Some items in `options_dict` are not single-bit. A good example is `offs.SGX_XFRM_AVX512` which has three bits set.

So at least change `bit` -> `bits`. I don't see that there can be any problems with the current code, but take this multiple-bit case into consideration.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-09-22 00:25 UTC, mkow requested changes
> Reviewed 2 of 3 files at r8, 2 of 3 files at r9, 5 of 5 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/72)* status: all files reviewed, 14 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @bigdata-memory, @boryspoplawski, @dimakuv, @mkow, and @woju)

___
*[python/graphene-sgx-get-token, line 16 at r7](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk6iHfeAJpM0M5ma12J:-Mk9jbm76HCMAG6kYAcv:b-v26w6w) ([raw file](https://github.com/gramineproject/gramine/blob/a192d04d5d73a8b254438c83c00749b19ba666bc/python/graphene-sgx-get-token#L16)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I've just preserver old CLI syntax 1 to 1. The answer is: no, even slightest, idea.
</blockquote></details>

I'd stop supporting it, I can't imagine someone calling this tool without this argument.


<!-- Sent from Reviewable.io -->

2021-09-22 09:08 UTC, dimakuv requested changes
> Reviewed 1 of 3 files at r8, 5 of 5 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/72)* status: all files reviewed, 16 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @bigdata-memory, @boryspoplawski, @dimakuv, @mkow, and @woju)

___
*[-- commits, line 47 at r7](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk6Z5PtEd0Zhgk4yGfA):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

@dimakuv typo, need to fix at rebase. As for other change: sure, but let's not do this here (or submit another PR which we can merge quickly, then I would drop this commit)
@bigdata-memory no, it does not need to

</blockquote></details>

@boryspoplawski I would create a separate PR, looks like we need it. It will also simplify significantly #31 
___
*[python/graphene-gen-depend, line 8 at r10](https://reviewable.io/reviews/gramineproject/gramine/72#-MkBhP32BZfN96RpQrhZ:-MkBhP32BZfN96RpQrh_:b4xdsyw) ([raw file](https://github.com/gramineproject/gramine/blob/7bbdb47b2aec829872d8c8698b2e5367794d6fd1/python/graphene-gen-depend#L8)):*
> ```
> import os
> 
> import click
> ```

Python linter complained? Why this reordering?
___
*[python/graphene-sgx-get-token, line 16 at r7](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk6iHfeAJpM0M5ma12J:-MkBhXYD7CPKXF66t0fx:b3g9uby) ([raw file](https://github.com/gramineproject/gramine/blob/a192d04d5d73a8b254438c83c00749b19ba666bc/python/graphene-sgx-get-token#L16)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd stop supporting it, I can't imagine someone calling this tool without this argument.
</blockquote></details>

Let's make it required here and see if Jenkins fails
___
*[python/graphenelibos/manifest.py, line 140 at r7](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk6k3fL7tXZsjWxUYj7:-MkBhiySBMuy_IvkSMGR:bv5l5yu) ([raw file](https://github.com/gramineproject/gramine/blob/a192d04d5d73a8b254438c83c00749b19ba666bc/python/graphenelibos/manifest.py#L140)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I thought we had that requirement already. Anyway, all current manifests are written like that.
</blockquote></details>

OK. Though it's surprising -- are we really that disciplined in our manifests? Cool.
___
*[python/graphenelibos/sgx_sign.py, line 447 at r10](https://reviewable.io/reviews/gramineproject/gramine/72#-MkBk0ij7lOwJp8CmxWG:-MkBk0ij7lOwJp8CmxWH:b-v2q1w0) ([raw file](https://github.com/gramineproject/gramine/blob/7bbdb47b2aec829872d8c8698b2e5367794d6fd1/python/graphenelibos/sgx_sign.py#L447)):*
> ```Python
> 
> 
> def get_mrenclave(manifest_path, date, libpal=None):
> ```

The name doesn't make much sense now. `get_mrenclave` returns not only the MRENCLAVE, but **also** the manifest dict? Please rename.

Also, why `date` here? You only need the date for the SIGSTRUCT generation (you put it there as one of the fields). But for manifest/MRENCLAVE generation it is not needed at all. I also think that we can simply remove the date print from the below, it is useless.
___
*[python/graphenelibos/sgx_sign.py, line 475 at r10](https://reviewable.io/reviews/gramineproject/gramine/72#-MkBkX0UBAR4jU8kq8yB:-MkBkX0UBAR4jU8kq8yC:bhq3ko0) ([raw file](https://github.com/gramineproject/gramine/blob/7bbdb47b2aec829872d8c8698b2e5367794d6fd1/python/graphenelibos/sgx_sign.py#L475)):*
> ```Python
>     print(f'    attr.xfrm:   {attr["xfrms"]:#x}')
>     print(f'    misc_select: {attr["misc_select"]:#x}')
>     print(f'    date:        {attr["year"]:04d}-{attr["month"]:02d}-{attr["day"]:02d}')
> ```

We can delete this print, it's useless.
___
*[python/graphenelibos/sgx_sign.py, line 514 at r10](https://reviewable.io/reviews/gramineproject/gramine/72#-MkBkbL5BL38Buk-0qa7:-MkBkbL5BL38Buk-0qa8:b-2ihqku) ([raw file](https://github.com/gramineproject/gramine/blob/7bbdb47b2aec829872d8c8698b2e5367794d6fd1/python/graphenelibos/sgx_sign.py#L514)):*
> ```Python
> 
> 
> def get_tbssigstruct(manifest_path, date, args=None):
> ```

This looks weird -- we either specify `manifest_path` OR we specify a tuple `args = (mrenclave, manifest)`. Can we somehow change the signature of this func?


<!-- Sent from Reviewable.io -->

2021-09-22 12:03 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/72)* status: all files reviewed, 16 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @bigdata-memory, @boryspoplawski, @dimakuv, @mkow, and @woju)

___
*[python/graphene-gen-depend, line 8 at r10](https://reviewable.io/reviews/gramineproject/gramine/72#-MkBhP32BZfN96RpQrhZ:-MkCM8vQ3Zje-nq0OMEn:b-ogjwbe) ([raw file](https://github.com/gramineproject/gramine/blob/7bbdb47b2aec829872d8c8698b2e5367794d6fd1/python/graphene-gen-depend#L8)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Python linter complained? Why this reordering?
</blockquote></details>

Yup. This looks a bit weird with only 3 imports, but this is just import grouping - first group is for standard imports, second are third-party and third is our own.
___
*[python/graphenelibos/sgx_sign.py, line 447 at r10](https://reviewable.io/reviews/gramineproject/gramine/72#-MkBk0ij7lOwJp8CmxWG:-MkCMmAsB4dziNdaSYAj:bopdmxy) ([raw file](https://github.com/gramineproject/gramine/blob/7bbdb47b2aec829872d8c8698b2e5367794d6fd1/python/graphenelibos/sgx_sign.py#L447)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

The name doesn't make much sense now. `get_mrenclave` returns not only the MRENCLAVE, but **also** the manifest dict? Please rename.

Also, why `date` here? You only need the date for the SIGSTRUCT generation (you put it there as one of the fields). But for manifest/MRENCLAVE generation it is not needed at all. I also think that we can simply remove the date print from the below, it is useless.
</blockquote></details>

You need to pass the original signing date if you want to reproduce the MRENCLAVE (note, that this is from the enclave user perspective, not enclave author or host).

Or maybe we're missing something and this date doesn't go into MRENCLAVE at all?
___
*[python/graphenelibos/sgx_sign.py, line 475 at r10](https://reviewable.io/reviews/gramineproject/gramine/72#-MkBkX0UBAR4jU8kq8yB:-MkCNHLC52QHebgpCC5I:b90cbyw) ([raw file](https://github.com/gramineproject/gramine/blob/7bbdb47b2aec829872d8c8698b2e5367794d6fd1/python/graphenelibos/sgx_sign.py#L475)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We can delete this print, it's useless.
</blockquote></details>

The date is required to be able to reproduce MRENCLAVE, see above.


<!-- Sent from Reviewable.io -->

2021-09-22 12:40 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/72)* status: all files reviewed, 15 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @bigdata-memory, @boryspoplawski, @dimakuv, @mkow, and @woju)

___
*[python/graphenelibos/sgx_sign.py, line 447 at r10](https://reviewable.io/reviews/gramineproject/gramine/72#-MkBk0ij7lOwJp8CmxWG:-MkCWHpI7euJQ8sJ1ZKP:b-nolub9) ([raw file](https://github.com/gramineproject/gramine/blob/7bbdb47b2aec829872d8c8698b2e5367794d6fd1/python/graphenelibos/sgx_sign.py#L447)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

You need to pass the original signing date if you want to reproduce the MRENCLAVE (note, that this is from the enclave user perspective, not enclave author or host).

Or maybe we're missing something and this date doesn't go into MRENCLAVE at all?
</blockquote></details>

This cannot be true. MRENCLAVE shouldn't depend on the date at all (why would it?), and I looked through our `sgx_sign.py` script, nowhere it uses the date (other than for the final SIGSTRUCT generation).


<!-- Sent from Reviewable.io -->

2021-09-22 14:49 UTC, bigdata-memory reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/72)* status: all files reviewed, 15 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/72#-MjtXxWh9ULgbAUYCJnF:-MkCwQHQ5-SVzw9lO6-N:b-37ur2z) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

> This feature is expected to interact with signing facility for 2 step signing that has a clear boundary defined in Intel dev. reference document. 

I do not understand this.

Generally, now we expose a python API, which can use any signing callback whatsoever.
</blockquote></details>

You can check out the description in SGX Developer Reference(https://download.01.org/intel-sgx/sgx-linux/2.11/docs/Intel_SGX_Developer_Reference_Linux_2.11_Open_Source.pdf) P18, you can also find the associated screenshots in #2617

---


<!-- Sent from Reviewable.io -->

2021-09-22 15:31 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/72)* status: 22 of 25 files reviewed, 15 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @woju)

___
*[-- commits, line 47 at r7](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk6Z5PtEd0Zhgk4yGfA):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@boryspoplawski I would create a separate PR, looks like we need it. It will also simplify significantly #31 
</blockquote></details>

Done in https://github.com/gramineproject/gramine/pull/78
This needs to be dropped at rebase.
___
*[python/graphene-gen-depend, line 8 at r10](https://reviewable.io/reviews/gramineproject/gramine/72#-MkBhP32BZfN96RpQrhZ:-MkCyBM3BRxpNELgrH6H:b-81uofk) ([raw file](https://github.com/gramineproject/gramine/blob/7bbdb47b2aec829872d8c8698b2e5367794d6fd1/python/graphene-gen-depend#L8)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Yup. This looks a bit weird with only 3 imports, but this is just import grouping - first group is for standard imports, second are third-party and third is our own.
</blockquote></details>

pylint complained on the order of imports (standard before third-party), empty lines added just for clarity.
___
*[python/graphene-sgx-get-token, line 16 at r7](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk6iHfeAJpM0M5ma12J:-MkCzARm-9lMC-kry2r7:b-i35c1q) ([raw file](https://github.com/gramineproject/gramine/blob/a192d04d5d73a8b254438c83c00749b19ba666bc/python/graphene-sgx-get-token#L16)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Let's make it required here and see if Jenkins fails
</blockquote></details>

All usages have it (grepped manually).
Done.
___
*[python/graphenelibos/sgx_sign.py, line 447 at r10](https://reviewable.io/reviews/gramineproject/gramine/72#-MkBk0ij7lOwJp8CmxWG:-MkD-e5L4s0RCHuDKai9:b-3sphzz) ([raw file](https://github.com/gramineproject/gramine/blob/7bbdb47b2aec829872d8c8698b2e5367794d6fd1/python/graphenelibos/sgx_sign.py#L447)):*
Yeah, it seems to just be a remnant of an older version, which had this and sigstruct generation in one place.
Fixed.

> The name doesn't make much sense now. get_mrenclave returns not only the MRENCLAVE, but also the manifest dict? Please rename.

Yes it does, but only for convenience (because we have to parse it inside anyway). I left the old name, because I expect most users will ignore the returned manifest and the main point of this function is to get MRENCLAVE.
If you insist on this change, please give me some hint on the new name.
___
*[python/graphenelibos/sgx_sign.py, line 475 at r10](https://reviewable.io/reviews/gramineproject/gramine/72#-MkBkX0UBAR4jU8kq8yB:-MkD4UFw3dv-DjyX85hc:b-yetiov) ([raw file](https://github.com/gramineproject/gramine/blob/7bbdb47b2aec829872d8c8698b2e5367794d6fd1/python/graphenelibos/sgx_sign.py#L475)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

The date is required to be able to reproduce MRENCLAVE, see above.
</blockquote></details>

Nope it is not.
___
*[python/graphenelibos/sgx_sign.py, line 514 at r10](https://reviewable.io/reviews/gramineproject/gramine/72#-MkBkbL5BL38Buk-0qa7:-MkD4XvgBfUJ52Ccf-_N:bu0sgxa) ([raw file](https://github.com/gramineproject/gramine/blob/7bbdb47b2aec829872d8c8698b2e5367794d6fd1/python/graphenelibos/sgx_sign.py#L514)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This looks weird -- we either specify `manifest_path` OR we specify a tuple `args = (mrenclave, manifest)`. Can we somehow change the signature of this func?
</blockquote></details>

How exactly would you do that? Having one argument and check if with `isinstance` would be ugly.


<!-- Sent from Reviewable.io -->

2021-09-22 15:36 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/72)* status: 22 of 25 files reviewed, 15 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/72#-MjtXxWh9ULgbAUYCJnF:-MkD8LenEHs9sgJTYn1J:bhufndn) (no related file):*
<details><summary><i>Previously, bigdata-memory (Gordon King) wrote…</i></summary><blockquote>

You can check out the description in SGX Developer Reference(https://download.01.org/intel-sgx/sgx-linux/2.11/docs/Intel_SGX_Developer_Reference_Linux_2.11_Open_Source.pdf) P18, you can also find the associated screenshots in #2617
</blockquote></details>

I still have no idea what you mean by "clear boundary ".
We expose an API, which you can use to sign the sigstruct in any way you desire (including sending the data to a signing facility).

---


<!-- Sent from Reviewable.io -->

2021-09-22 16:15 UTC, mkow reviewed
> Reviewed 3 of 3 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/72)* status: all files reviewed, 15 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @bigdata-memory, @boryspoplawski, @dimakuv, @mkow, and @woju)

___
*[python/graphenelibos/sgx_sign.py, line 447 at r10](https://reviewable.io/reviews/gramineproject/gramine/72#-MkBk0ij7lOwJp8CmxWG:-MkDH86p7mhNO2nALW0P:b-4p7ia5) ([raw file](https://github.com/gramineproject/gramine/blob/7bbdb47b2aec829872d8c8698b2e5367794d6fd1/python/graphenelibos/sgx_sign.py#L447)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Yeah, it seems to just be a remnant of an older version, which had this and sigstruct generation in one place.
Fixed.

> The name doesn't make much sense now. get_mrenclave returns not only the MRENCLAVE, but also the manifest dict? Please rename.

Yes it does, but only for convenience (because we have to parse it inside anyway). I left the old name, because I expect most users will ignore the returned manifest and the main point of this function is to get MRENCLAVE.
If you insist on this change, please give me some hint on the new name.
</blockquote></details>

Ah, I actually thought that it depends on the date. If not, it can be dropped from here (as Borys just did).
___
*[python/graphenelibos/sgx_sign.py, line 475 at r10](https://reviewable.io/reviews/gramineproject/gramine/72#-MkBkX0UBAR4jU8kq8yB:-MkDHO2K-HPztMR3JmYK:b81xnf2) ([raw file](https://github.com/gramineproject/gramine/blob/7bbdb47b2aec829872d8c8698b2e5367794d6fd1/python/graphenelibos/sgx_sign.py#L475)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Nope it is not.
</blockquote></details>

Yeah, now I already know ;)


<!-- Sent from Reviewable.io -->

2021-09-23 09:33 UTC, dimakuv approved these changes
> Reviewed 3 of 3 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/72)* status: all files reviewed, 11 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @bigdata-memory, @boryspoplawski, @dimakuv, @mkow, and @woju)

___
*[python/graphenelibos/sgx_sign.py, line 447 at r10](https://reviewable.io/reviews/gramineproject/gramine/72#-MkBk0ij7lOwJp8CmxWG:-MkGzt1S-ripdbqkwHra:bpskiu7) ([raw file](https://github.com/gramineproject/gramine/blob/7bbdb47b2aec829872d8c8698b2e5367794d6fd1/python/graphenelibos/sgx_sign.py#L447)):*
> If you insist on this change, please give me some hint on the new name.

Doesn't matter that much. Resolving.
___
*[python/graphenelibos/sgx_sign.py, line 514 at r10](https://reviewable.io/reviews/gramineproject/gramine/72#-MkBkbL5BL38Buk-0qa7:-MkH-BL45urkUGLeErZe:bp16wd4) ([raw file](https://github.com/gramineproject/gramine/blob/7bbdb47b2aec829872d8c8698b2e5367794d6fd1/python/graphenelibos/sgx_sign.py#L514)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

How exactly would you do that? Having one argument and check if with `isinstance` would be ugly.
</blockquote></details>

Can't come up with something simple. Resolving.


<!-- Sent from Reviewable.io -->

2021-09-23 20:48 UTC, woju requested changes
> Reviewed 2 of 21 files at r1, 1 of 5 files at r4, 1 of 3 files at r9.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/72)* status: all files reviewed, 9 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @bigdata-memory, @boryspoplawski, @dimakuv, and @mkow)

___
*[Pal/regression/Bootstrap3.manifest, line 6 at r3](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk1xh5uDtgjd1m_DkAJ:-MkIPBfKBMu5jWJQDTOj:b4umsrf) ([raw file](https://github.com/gramineproject/gramine/blob/30fec89398d430410f387e34ab29c508e3cddcdb/Pal/regression/Bootstrap3.manifest#L6)):*
<details><summary><i>Previously, bigdata-memory (Gordon King) wrote…</i></summary><blockquote>

Looks more readability for me.
</blockquote></details>

In all other languages we don't have whitespace inside parens and brackets, why would we do things differently in TOML?
___
*[python/graphene-gen-depend, line 11 at r3](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk1JIbuDQXDtLD68XdV:-Mk7AQCm8TA7v9y0jA_J:b-fnitvs) ([raw file](https://github.com/gramineproject/gramine/blob/30fec89398d430410f387e34ab29c508e3cddcdb/python/graphene-gen-depend#L11)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Well, how could I knew they are not using any wrappers?
</blockquote></details>

Oh they do (esp. for lazy, `atomic=True`, etc.), but even then it would be a bug to filter this attribute, so they pass all of them: https://github.com/pallets/click/blob/c1a42a1c545c138266be61c7b0fda02b9a423fe0/src/click/utils.py#L135-L136. Also, there aren't any other ways to open in file in python apart from `os.open()` which returns an `int` and possibly `ctypes`, so one way or another you'll get this name.
___
*[python/graphene-gen-depend, line 12 at r3](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk1NTEy13WfCyz2MdQX:-Mk7COZs70rjNYUJFeJI:b-kc9hpo) ([raw file](https://github.com/gramineproject/gramine/blob/30fec89398d430410f387e34ab29c508e3cddcdb/python/graphene-gen-depend#L12)):*
> ```
> os.path.join(_CONFIG_PKGLIBDIR, 'sgx/libpal.so')
> ```
___
*[python/graphenelibos/__init__.py, line 16 at r3](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk1QeTK-aCE26CsY0S7:-Mk7CSVLBWpWoHs3WkvZ:b-bte392) ([raw file](https://github.com/gramineproject/gramine/blob/30fec89398d430410f387e34ab29c508e3cddcdb/python/graphenelibos/__init__.py#L16)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

> The problem is, everyone using this modules has to do their own try/except, because just importing graphenelibos means you can have those attributes or not, so we're not solving anything with this contraption.

What? This is substituted by meson, just like some variables above. So if you've installed SGX version, they you have these files and if you didn't, they they are not imported. No need for any try+except.
</blockquote></details>

I mean when you actually use this by importing the module (not by launching cli tools from shell, but from python, as advertised). You then have to do your own try/except, because you need to check if the installed graphene wasn't configured with `-Dsgx=disabled`. Otherwise, your enterprise tool will barf a traceback.
___
*[python/graphenelibos/manifest.py, line 150 at r3](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk1hIEJ74pScPgHwqIw:-MkIPjxQ4Co64qarNH9t:bzf4g0z) ([raw file](https://github.com/gramineproject/gramine/blob/30fec89398d430410f387e34ab29c508e3cddcdb/python/graphenelibos/manifest.py#L150)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

If I put `_env` in global scope it wont change anything w.r.t. arguments you gave.
</blockquote></details>

`Environment` is logically more tied to the file than to any class or function inside, because typically you have `FileSystemLoader` there, which has path from which you load templates. The path is typically calculated relative to `__file__`. That you create it using `make_env()` which does correct thing does not change this.
___
*[python/graphenelibos/manifest.py, line 152 at r3](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk1e84QD5e4gGeUjdbC:-Mk7QC1s7e2yJQszyPoO:b-juoh3i) ([raw file](https://github.com/gramineproject/gramine/blob/30fec89398d430410f387e34ab29c508e3cddcdb/python/graphenelibos/manifest.py#L152)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`get_mrenclave` now takes a path, I've figured this is the best way to stop ppl shooting their feet, and integrates ok-ish with other functions. It now also returns a manifest, in case you need that too (since it's already parsed).
</blockquote></details>

OK. It's good enough for now.


<!-- Sent from Reviewable.io -->

2021-09-23 22:08 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/72)* status: all files reviewed, 9 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @bigdata-memory, @boryspoplawski, @dimakuv, @mkow, and @woju)

___
*[Pal/regression/Bootstrap3.manifest, line 6 at r3](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk1xh5uDtgjd1m_DkAJ:-MkJbNhF-wGWqm9Ern4y:b-8krqyg) ([raw file](https://github.com/gramineproject/gramine/blob/30fec89398d430410f387e34ab29c508e3cddcdb/Pal/regression/Bootstrap3.manifest#L6)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

In all other languages we don't have whitespace inside parens and brackets, why would we do things differently in TOML?
</blockquote></details>

I always put them in C.
___
*[python/graphene-gen-depend, line 12 at r3](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk1NTEy13WfCyz2MdQX:-MkJcQyo8D_Dn2TyMMI-:b-n7qsr0) ([raw file](https://github.com/gramineproject/gramine/blob/30fec89398d430410f387e34ab29c508e3cddcdb/python/graphene-gen-depend#L12)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

> ```
> os.path.join(_CONFIG_PKGLIBDIR, 'sgx/libpal.so')
> ```

</blockquote></details>

It was like this before. Actually you've written it like that: https://github.com/gramineproject/gramine/commit/a2734d5f3173d6969cd4c33a573f49e111d4490e#diff-ab312b09bfc527501dd02eb9577a589f0a8ac352d7f6a66e8d47fa5f38b348c7R659
___
*[python/graphenelibos/__init__.py, line 16 at r3](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk1QeTK-aCE26CsY0S7:-MkJcux44lWPuyFjrnvU:b-9yeklk) ([raw file](https://github.com/gramineproject/gramine/blob/30fec89398d430410f387e34ab29c508e3cddcdb/python/graphenelibos/__init__.py#L16)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

I mean when you actually use this by importing the module (not by launching cli tools from shell, but from python, as advertised). You then have to do your own try/except, because you need to check if the installed graphene wasn't configured with `-Dsgx=disabled`. Otherwise, your enterprise tool will barf a traceback.
</blockquote></details>

In your final tool you require Gramine to be already install and you can require some version (e.g. with sgx enabled) to be installed. Why don't we have try+except around `import click`? Because we require `click` to be installed. I really don't get your point here.
___
*[python/graphenelibos/manifest.py, line 150 at r3](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk1hIEJ74pScPgHwqIw:-MkJg8INEgx0SFOORujH:bgu3nof) ([raw file](https://github.com/gramineproject/gramine/blob/30fec89398d430410f387e34ab29c508e3cddcdb/python/graphenelibos/manifest.py#L150)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

`Environment` is logically more tied to the file than to any class or function inside, because typically you have `FileSystemLoader` there, which has path from which you load templates. The path is typically calculated relative to `__file__`. That you create it using `make_env()` which does correct thing does not change this.
</blockquote></details>

I just figured that if you want, for example, create another template to be able to render for different Gramine versions, then all you have to do is:
```python
class ManifestSomething(Manifest):
    _env = gen_jinja_env_for_gramine_v1337()
```
and then you can transparently use the new class and everything will work correctly.
If I put `_env` in global scope, then such flexibility would be gone.


<!-- Sent from Reviewable.io -->

2021-09-23 22:26 UTC, woju requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/72)* status: all files reviewed, 8 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @bigdata-memory, @boryspoplawski, @dimakuv, and @mkow)

___
*[Pal/regression/Bootstrap3.manifest, line 6 at r3](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk1xh5uDtgjd1m_DkAJ:-MkJhweQ6BFsPysAzkXA:bt9fc4t) ([raw file](https://github.com/gramineproject/gramine/blob/30fec89398d430410f387e34ab29c508e3cddcdb/Pal/regression/Bootstrap3.manifest#L6)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I always put them in C.
</blockquote></details>

I beg to differ. This file has probably most brackets in C and lists you as contributor: https://github.com/gramineproject/gramine/blob/master/LibOS/shim/src/arch/x86_64/shim_table.c
___
*[python/graphene-gen-depend, line 12 at r3](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk1NTEy13WfCyz2MdQX:-MkJhCUWA2d6V4dAjaaL:bs6kj4q) ([raw file](https://github.com/gramineproject/gramine/blob/30fec89398d430410f387e34ab29c508e3cddcdb/python/graphene-gen-depend#L12)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

It was like this before. Actually you've written it like that: https://github.com/gramineproject/gramine/commit/a2734d5f3173d6969cd4c33a573f49e111d4490e#diff-ab312b09bfc527501dd02eb9577a589f0a8ac352d7f6a66e8d47fa5f38b348c7R659
</blockquote></details>

In `graphene-*sgx*-sign` this was appropriate, now in `graphene-manifest` which serves both pals it might not. IDK, in graphene-gen-depend might not hurt, because in installed system it doesn't change.
___
*[python/graphenelibos/__init__.py, line 16 at r3](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk1QeTK-aCE26CsY0S7:-MkJkRw0CzF6QmQjr4Mo:b-vv01he) ([raw file](https://github.com/gramineproject/gramine/blob/30fec89398d430410f387e34ab29c508e3cddcdb/python/graphenelibos/__init__.py#L16)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

In your final tool you require Gramine to be already install and you can require some version (e.g. with sgx enabled) to be installed. Why don't we have try+except around `import click`? Because we require `click` to be installed. I really don't get your point here.
</blockquote></details>

The point is that this SGX_ENABLED stinks, but well, if you'd like it, I have no strong opinion.
___
*[python/graphenelibos/manifest.py, line 150 at r3](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk1hIEJ74pScPgHwqIw:-MkJiHUcBYXKEDZhDSVf:buis00q) ([raw file](https://github.com/gramineproject/gramine/blob/30fec89398d430410f387e34ab29c508e3cddcdb/python/graphenelibos/manifest.py#L150)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I just figured that if you want, for example, create another template to be able to render for different Gramine versions, then all you have to do is:
```python
class ManifestSomething(Manifest):
    _env = gen_jinja_env_for_gramine_v1337()
```
and then you can transparently use the new class and everything will work correctly.
If I put `_env` in global scope, then such flexibility would be gone.
</blockquote></details>

Hmm? The template is loaded from string, and from external file, so I think that wouldn't work here. Also, instead of owning an env, we can always have a overloadable method for manipulating the env (like changing `graphene` global with different `graphene.runtime` etc.).


<!-- Sent from Reviewable.io -->

2021-09-23 22:38 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/72)* status: all files reviewed, 8 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @bigdata-memory, @boryspoplawski, @dimakuv, @mkow, and @woju)

___
*[Pal/regression/Bootstrap3.manifest, line 6 at r3](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk1xh5uDtgjd1m_DkAJ:-MkJmVam4ZWlVmrfMyLG:bw5ukln) ([raw file](https://github.com/gramineproject/gramine/blob/30fec89398d430410f387e34ab29c508e3cddcdb/Pal/regression/Bootstrap3.manifest#L6)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

I beg to differ. This file has probably most brackets in C and lists you as contributor: https://github.com/gramineproject/gramine/blob/master/LibOS/shim/src/arch/x86_64/shim_table.c
</blockquote></details>

These are not lists, but array indexes like:
```c
type_t array[15];
array[4] = something;
```
which is totally different case. This is an example of struct initialization: https://github.com/gramineproject/gramine/blob/master/LibOS/shim/src/bookkeep/shim_pid.c#L42
___
*[python/graphene-gen-depend, line 12 at r3](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk1NTEy13WfCyz2MdQX:-MkJnNPq8YKeqk50Qyw2:b-j708rc) ([raw file](https://github.com/gramineproject/gramine/blob/30fec89398d430410f387e34ab29c508e3cddcdb/python/graphene-gen-depend#L12)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

In `graphene-*sgx*-sign` this was appropriate, now in `graphene-manifest` which serves both pals it might not. IDK, in graphene-gen-depend might not hurt, because in installed system it doesn't change.
</blockquote></details>

This is not `graphene-manifest`. Tis is `gen-depdent` which was split exactly from `graphene-sgx-sign`, that's why it ended up like this.
Anyway, what should I put here? If we have 2 versions installed, then we cannot pick one...
___
*[python/graphenelibos/__init__.py, line 16 at r3](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk1QeTK-aCE26CsY0S7:-MkJlntdABSO46weCn84:b-pd0hyo) ([raw file](https://github.com/gramineproject/gramine/blob/30fec89398d430410f387e34ab29c508e3cddcdb/python/graphenelibos/__init__.py#L16)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

The point is that this SGX_ENABLED stinks, but well, if you'd like it, I have no strong opinion.
</blockquote></details>

I don't like it, but neither I like `@PKGLIBDIR@`. And try+except ImportError is 10x worse.
___
*[python/graphenelibos/manifest.py, line 150 at r3](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk1hIEJ74pScPgHwqIw:-MkJmCmI7X3-arr6QLf6:bp929h6) ([raw file](https://github.com/gramineproject/gramine/blob/30fec89398d430410f387e34ab29c508e3cddcdb/python/graphenelibos/manifest.py#L150)):*
> The template is loaded from string, and from external file, so I think that wouldn't work here. 

What does that have to do with env?

> Also, instead of owning an env, we can always have a overloadable method for manipulating the env (like changing graphene global with different graphene.runtime etc.).

Manipulating means you cannot have 2 different instances at the same time.

Anyway, this is purely academical discussion.


<!-- Sent from Reviewable.io -->

2021-09-23 23:12 UTC, woju requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/72)* status: all files reviewed, 7 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @bigdata-memory, @boryspoplawski, @dimakuv, and @mkow)

___
*[Pal/regression/Bootstrap3.manifest, line 6 at r3](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk1xh5uDtgjd1m_DkAJ:-MkJvMD06P4YWISgxUN5:besn7d7) ([raw file](https://github.com/gramineproject/gramine/blob/30fec89398d430410f387e34ab29c508e3cddcdb/Pal/regression/Bootstrap3.manifest#L6)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

These are not lists, but array indexes like:
```c
type_t array[15];
array[4] = something;
```
which is totally different case. This is an example of struct initialization: https://github.com/gramineproject/gramine/blob/master/LibOS/shim/src/bookkeep/shim_pid.c#L42
</blockquote></details>

Hmm, OK. So if there's precedent for this, we can keep it. In python this would be very wrong.
___
*[python/graphene-gen-depend, line 12 at r3](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk1NTEy13WfCyz2MdQX:-MkJuDJD9kld-OnixMng:b8kusc) ([raw file](https://github.com/gramineproject/gramine/blob/30fec89398d430410f387e34ab29c508e3cddcdb/python/graphene-gen-depend#L12)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This is not `graphene-manifest`. Tis is `gen-depdent` which was split exactly from `graphene-sgx-sign`, that's why it ended up like this.
Anyway, what should I put here? If we have 2 versions installed, then we cannot pick one...
</blockquote></details>

I don't know. For now let's leave it as is, we'll fix this when merging this with graphene-manifest.
___
*[python/graphenelibos/manifest.py, line 150 at r3](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk1hIEJ74pScPgHwqIw:-MkJuS8eAZ5NYw9IFYDt:b-scgjtg) ([raw file](https://github.com/gramineproject/gramine/blob/30fec89398d430410f387e34ab29c508e3cddcdb/python/graphenelibos/manifest.py#L150)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

> The template is loaded from string, and from external file, so I think that wouldn't work here. 

What does that have to do with env?

> Also, instead of owning an env, we can always have a overloadable method for manipulating the env (like changing graphene global with different graphene.runtime etc.).

Manipulating means you cannot have 2 different instances at the same time.

Anyway, this is purely academical discussion.
</blockquote></details>

Yes, so while this is academic, please change to global.


<!-- Sent from Reviewable.io -->

2021-09-23 23:19 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/72)* status: all files reviewed, 7 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @bigdata-memory, @boryspoplawski, @dimakuv, @mkow, and @woju)

___
*[python/graphenelibos/manifest.py, line 150 at r3](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk1hIEJ74pScPgHwqIw:-MkJwEVP76GZctljSMg-:b7uojja) ([raw file](https://github.com/gramineproject/gramine/blob/30fec89398d430410f387e34ab29c508e3cddcdb/python/graphenelibos/manifest.py#L150)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Yes, so while this is academic, please change to global.
</blockquote></details>

No. I've gave you arguments why I put it inside class. The only argument that you gave in favor of putting env in globals is that some paths are calculated relative to `__file__`, which doesn't really make sense to me, because `__file__` will be exactly the same, whether env is global or in class; also we do not use such paths.


<!-- Sent from Reviewable.io -->

2021-09-23 23:34 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/72)* status: all files reviewed, 7 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @bigdata-memory, @boryspoplawski, @dimakuv, @mkow, and @woju)

___
*[python/graphenelibos/manifest.py, line 150 at r3](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk1hIEJ74pScPgHwqIw:-MkJzrR53MORXPsd4hoU:b698w92) ([raw file](https://github.com/gramineproject/gramine/blob/30fec89398d430410f387e34ab29c508e3cddcdb/python/graphenelibos/manifest.py#L150)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

No. I've gave you arguments why I put it inside class. The only argument that you gave in favor of putting env in globals is that some paths are calculated relative to `__file__`, which doesn't really make sense to me, because `__file__` will be exactly the same, whether env is global or in class; also we do not use such paths.
</blockquote></details>

I like the current version, this variable is used only for manifests rendering and now it has global lifetime, but local visibility, which sounds like exactly what we want?


<!-- Sent from Reviewable.io -->

2021-09-23 23:43 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/72)* status: all files reviewed, 7 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @bigdata-memory, @boryspoplawski, @dimakuv, @mkow, and @woju)

___
*[python/graphenelibos/manifest.py, line 150 at r3](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk1hIEJ74pScPgHwqIw:-MkK1ID35wrWEmr80kEq:b-8ty7dk) ([raw file](https://github.com/gramineproject/gramine/blob/30fec89398d430410f387e34ab29c508e3cddcdb/python/graphenelibos/manifest.py#L150)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I like the current version, this variable is used only for manifests rendering and now it has global lifetime, but local visibility, which sounds like exactly what we want?
</blockquote></details>

Changing it to global would only mean global for this module. The only difference w.r.t. to visibility would be accessing/modifying it directly (`graphenelibos.manifest._env` vs `Manifest._env`).


<!-- Sent from Reviewable.io -->

2021-09-23 23:44 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/72)* status: all files reviewed, 7 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @bigdata-memory, @boryspoplawski, @dimakuv, @mkow, and @woju)

___
*[python/graphenelibos/manifest.py, line 150 at r3](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk1hIEJ74pScPgHwqIw:-MkK1kcM5jdEaWQmLBgj:bk2cxjk) ([raw file](https://github.com/gramineproject/gramine/blob/30fec89398d430410f387e34ab29c508e3cddcdb/python/graphenelibos/manifest.py#L150)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Changing it to global would only mean global for this module. The only difference w.r.t. to visibility would be accessing/modifying it directly (`graphenelibos.manifest._env` vs `Manifest._env`).
</blockquote></details>

Only advantage of keeping this in class is that you can modify it for each subclass. I don't see any advantages of putting this in global.


<!-- Sent from Reviewable.io -->

2021-09-28 23:27 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/72)* status: 7 of 34 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @bigdata-memory, @boryspoplawski, @dimakuv, @mkow, and @woju)

___
*[-- commits, line 32 at r7](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk6YwLtDJ9X2YccCymY):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

TODO: at rebase
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-09-28 23:30 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/72)* status: 7 of 34 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @bigdata-memory, @boryspoplawski, @dimakuv, @mkow, and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/72#-MkijdYK7-u_I-Pp06OQ:-MkijdYL2C3STPsrKTVh:b-rny2j7) (no related file):*
FYI: I did a rebase, hopefully did not mess anything. Diffs might be a bit messy, due to rename conflicts.

---


<!-- Sent from Reviewable.io -->

2021-09-29 10:24 UTC, dimakuv approved these changes
> Reviewed 25 of 27 files at r12, 2 of 2 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/72)* status: all files reviewed, 5 unresolved discussions (waiting on @bigdata-memory, @boryspoplawski, @mkow, and @woju)



<!-- Sent from Reviewable.io -->

2021-09-29 17:03 UTC, mkow requested changes
> Reviewed 25 of 27 files at r12, 2 of 2 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/72)* status: all files reviewed, 6 unresolved discussions (waiting on @bigdata-memory, @boryspoplawski, @mkow, and @woju)

___
*[python/graminelibos/sgx_sign.py, line 447 at r13](https://reviewable.io/reviews/gramineproject/gramine/72#-MkmVRpD339jvy_MRgJm:-MkmVRpD339jvy_MRgJn:b-piftv6) ([raw file](https://github.com/gramineproject/gramine/blob/17e6e9d88d3bb745c68a2540c75c926e7121b58e/python/graminelibos/sgx_sign.py#L447)):*
> ```Python
> 
> 
> def get_mrenclave(manifest_path, libpal=None):
> ```

Ok, so what do we do with this API in the light of the attestation bug? Maybe it should actually be something like "get enclave identity"? (and return e.g. a tuple or something)
___
*[python/graminelibos/sgx_sign.py, line 471 at r13](https://reviewable.io/reviews/gramineproject/gramine/72#-MkmV8fJ0c5Jyf5xTR3G:-MkmV8fK9P0djNyriLEi:bppkwmf) ([raw file](https://github.com/gramineproject/gramine/blob/17e6e9d88d3bb745c68a2540c75c926e7121b58e/python/graminelibos/sgx_sign.py#L471)):*
> ```Python
>     print(f'    attr.flags:  {attr["flags"]:#x}')
>     print(f'    attr.xfrm:   {attr["xfrms"]:#x}')
>     print(f'    misc_select: {attr["misc_select"]:#x}')
> ```

Actually, why is this API printing stuff to the console? I know it was like this before, but back then we didn't have any API, just the CLI tool.


<!-- Sent from Reviewable.io -->

2021-09-29 17:16 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/72)* status: all files reviewed, 6 unresolved discussions (waiting on @bigdata-memory, @boryspoplawski, @mkow, and @woju)

___
*[python/graminelibos/sgx_sign.py, line 447 at r13](https://reviewable.io/reviews/gramineproject/gramine/72#-MkmVRpD339jvy_MRgJm:-MkmXTtL4Sn_G1FLXIGi:b-tq577t) ([raw file](https://github.com/gramineproject/gramine/blob/17e6e9d88d3bb745c68a2540c75c926e7121b58e/python/graminelibos/sgx_sign.py#L447)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Ok, so what do we do with this API in the light of the attestation bug? Maybe it should actually be something like "get enclave identity"? (and return e.g. a tuple or something)
</blockquote></details>

IMO this API is kind of temporary: we should probably just use SIGSTRUCT (either filled with signature or just TBSSIGSTRUCT, depending on context).
___
*[python/graminelibos/sgx_sign.py, line 471 at r13](https://reviewable.io/reviews/gramineproject/gramine/72#-MkmV8fJ0c5Jyf5xTR3G:-MkmY5_1AEAqUy0nnkxI:b-eap4xb) ([raw file](https://github.com/gramineproject/gramine/blob/17e6e9d88d3bb745c68a2540c75c926e7121b58e/python/graminelibos/sgx_sign.py#L471)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Actually, why is this API printing stuff to the console? I know it was like this before, but back then we didn't have any API, just the CLI tool.
</blockquote></details>

Ah, somebody finally noticed :)

Generally speaking, I've left as much prints as possible. I don't know what's their use and where, so had no idea how to fix this.
Ideally, the library should have 0 prints and only the final tools would print some info, where needed. We could add a `-v --verbose` flag to `gramine-manifest` and `gramine-sign` scripts, that would enable these prints.


<!-- Sent from Reviewable.io -->

2021-09-29 17:35 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/72)* status: all files reviewed, 6 unresolved discussions (waiting on @bigdata-memory, @boryspoplawski, @mkow, and @woju)

___
*[python/graminelibos/sgx_sign.py, line 447 at r13](https://reviewable.io/reviews/gramineproject/gramine/72#-MkmVRpD339jvy_MRgJm:-MkmbCpEEVs2OXPcd8AR:b53m19u) ([raw file](https://github.com/gramineproject/gramine/blob/17e6e9d88d3bb745c68a2540c75c926e7121b58e/python/graminelibos/sgx_sign.py#L447)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

IMO this API is kind of temporary: we should probably just use SIGSTRUCT (either filled with signature or just TBSSIGSTRUCT, depending on context).
</blockquote></details>

Could you add this to the TODOlist we discuss above then? (and then to the corresponding issue)
___
*[python/graminelibos/sgx_sign.py, line 471 at r13](https://reviewable.io/reviews/gramineproject/gramine/72#-MkmV8fJ0c5Jyf5xTR3G:-MkmbKow5Mv7RJjWSMNa:bq2zwke) ([raw file](https://github.com/gramineproject/gramine/blob/17e6e9d88d3bb745c68a2540c75c926e7121b58e/python/graminelibos/sgx_sign.py#L471)):*
> Ideally, the library should have 0 prints and only the final tools would print some info, where needed.

I think that's what we should do. But we can do this later, but please add this to the TODOlist above.


<!-- Sent from Reviewable.io -->

2021-09-29 21:57 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/72)* status: all files reviewed, 6 unresolved discussions (waiting on @bigdata-memory, @boryspoplawski, @mkow, and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/72#-MjvW2VNBlZ4l0iOML37:-MknXIa71sDLoeYM6eW6:b-tbl8qi) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

All right, let's add the TODO list after the review.
</blockquote></details>

List of things to be done (needs to be moved to #11 after final rebase):
- "Manifests will be renamed: `app.toml.jinja` (the template) and `app.toml` (after rendering and trusted files measurement)."
- "`graphene-sgx-get-mrenclave` new tool, will calculate MRENCLAVE based on manifest and `libpal.so`" - this needs rethinking, as `mrenclave` is not enough. Probably we will just add a tool to generate and print `TBSSIGSTRUCT`. Then we could also remove `get_mrenclave` from API
- "`graphene-sgx-keygen` new tool, will generate serviceable RSA-3072 key in proper place"
- "The default key location will be in `~/.config/graphene/enclave-key.pem` (really in `$XDG_CONFIG_HOME`)." - idk about this one, also my system does not have `XDG_CONFIG_HOME` set.
- "use cryptography (https://cryptography.io/) instead of `subprocess.run('openssl')` and hand-crafted RSA signature"
- remove all prints from python library; add some to our script wrappers: `gramine-sgx-sign` etc (probably behind `-v/--verbose` flag).

---
___
*[python/graminelibos/sgx_sign.py, line 447 at r13](https://reviewable.io/reviews/gramineproject/gramine/72#-MkmVRpD339jvy_MRgJm:-MknYekh6aXwEeF6PQZA:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/17e6e9d88d3bb745c68a2540c75c926e7121b58e/python/graminelibos/sgx_sign.py#L447)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you add this to the TODOlist we discuss above then? (and then to the corresponding issue)
</blockquote></details>

Done.
___
*[python/graminelibos/sgx_sign.py, line 471 at r13](https://reviewable.io/reviews/gramineproject/gramine/72#-MkmV8fJ0c5Jyf5xTR3G:-MknYlrD4Nh6CIWwsrhT:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/17e6e9d88d3bb745c68a2540c75c926e7121b58e/python/graminelibos/sgx_sign.py#L471)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> Ideally, the library should have 0 prints and only the final tools would print some info, where needed.

I think that's what we should do. But we can do this later, but please add this to the TODOlist above.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-09-30 00:49 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/72)* status: 31 of 34 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @bigdata-memory, @boryspoplawski, @dimakuv, @mkow, and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/72#-MjvW2VNBlZ4l0iOML37:-Mko9rKJ72Y3Fofu0jTM:bfks3py) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

List of things to be done (needs to be moved to #11 after final rebase):
- "Manifests will be renamed: `app.toml.jinja` (the template) and `app.toml` (after rendering and trusted files measurement)."
- "`graphene-sgx-get-mrenclave` new tool, will calculate MRENCLAVE based on manifest and `libpal.so`" - this needs rethinking, as `mrenclave` is not enough. Probably we will just add a tool to generate and print `TBSSIGSTRUCT`. Then we could also remove `get_mrenclave` from API
- "`graphene-sgx-keygen` new tool, will generate serviceable RSA-3072 key in proper place"
- "The default key location will be in `~/.config/graphene/enclave-key.pem` (really in `$XDG_CONFIG_HOME`)." - idk about this one, also my system does not have `XDG_CONFIG_HOME` set.
- "use cryptography (https://cryptography.io/) instead of `subprocess.run('openssl')` and hand-crafted RSA signature"
- remove all prints from python library; add some to our script wrappers: `gramine-sgx-sign` etc (probably behind `-v/--verbose` flag).
</blockquote></details>

Update: removed `get_mrenclave` from API, as it's not enough for secure verification. Probably need to add some `EnclaveIdentity` class, which could be derived from `Sigstruct` and contain only user verifiable data (e.g. could skip date), that we could pretty-print.

---


<!-- Sent from Reviewable.io -->

2021-09-30 01:03 UTC, mkow reviewed
> Reviewed 3 of 3 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/72)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @bigdata-memory, @boryspoplawski, @mkow, and @woju)



<!-- Sent from Reviewable.io -->

2021-09-30 11:43 UTC, dimakuv submitted a review, later dismissed
> Reviewed 3 of 3 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/72)* status: all files reviewed, 4 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @bigdata-memory, @boryspoplawski, @mkow, and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/72#-MjvW2VNBlZ4l0iOML37:-MkqVPyZ779N9fCmjCr4:bc910in) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Update: removed `get_mrenclave` from API, as it's not enough for secure verification. Probably need to add some `EnclaveIdentity` class, which could be derived from `Sigstruct` and contain only user verifiable data (e.g. could skip date), that we could pretty-print.
</blockquote></details>

Btw, I introduced something like this in GSC: https://github.com/gramineproject/gsc/pull/21. I believe I covered all relevant enclave info there. You can have something similar in your API.

---


<!-- Sent from Reviewable.io -->

2021-09-30 15:04 UTC, woju requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/72)* status: all files reviewed, 4 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @bigdata-memory, @boryspoplawski, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/72#-MjvW2VNBlZ4l0iOML37:-MkrCKmxB9HR1IBOWstj:b-8zkh6m) (no related file):*
> "The default key location will be in ~/.config/graphene/enclave-key.pem (really in $XDG_CONFIG_HOME)." - idk about this one, also my system does not have XDG_CONFIG_HOME set.

That's OK. https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html:

> If $XDG_CONFIG_HOME is either not set or empty, a default equal to $HOME/.config should be used.

No one ever sets this, but in case anyone does, we should be XDG® Compliant™.

---
___
*[python/graphenelibos/manifest.py, line 150 at r3](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk1hIEJ74pScPgHwqIw:-MkrCyI848Ly-oBHR989:b-yywrx6) ([raw file](https://github.com/gramineproject/gramine/blob/30fec89398d430410f387e34ab29c508e3cddcdb/python/graphenelibos/manifest.py#L150)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Only advantage of keeping this in class is that you can modify it for each subclass. I don't see any advantages of putting this in global.
</blockquote></details>

Oh, and I forgot about another problem: this env might be not only for manifests, but for other files that we hypothetically would render. For example, if we ever merged GSC into this repo (not that we should), then we would probably use the same env for gsc's templates too. Env really belongs to the app, not to any particular class.

Please, can I get Python laid out as I like it? It will be me who would be reviewing it in the future.


<!-- Sent from Reviewable.io -->

2021-09-30 20:22 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/72)* status: 29 of 36 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/72#-MjtXxWh9ULgbAUYCJnF:-MksAKtO0RohpARkV5sI:bs5z45n) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I still have no idea what you mean by "clear boundary ".
We expose an API, which you can use to sign the sigstruct in any way you desire (including sending the data to a signing facility).
</blockquote></details>

Unblocking as we seem to have no existing documentation, except `graphene-manifest` manpage, which does not need any updates.
Update: added small manpages for `gramine-sgx-sign` and `gramine-sgx-get-token`. `gramine-gen-depend` was not documented, since it will probably be deleted soon.
Python API documentation is not yet documented, added it to the TODO list below.

---
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/72#-MjvW2VNBlZ4l0iOML37:-MksH8a_2AckTJmN66X9:b-7kb1mj) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

> "The default key location will be in ~/.config/graphene/enclave-key.pem (really in $XDG_CONFIG_HOME)." - idk about this one, also my system does not have XDG_CONFIG_HOME set.

That's OK. https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html:

> If $XDG_CONFIG_HOME is either not set or empty, a default equal to $HOME/.config should be used.

No one ever sets this, but in case anyone does, we should be XDG® Compliant™.
</blockquote></details>

All right.

Also add to the list:
- document python API - actually where to put this? In what format?

---
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/72#-MksGcwnBKUSQlbhE-qe:-MksGcwnBKUSQlbhE-qf:b26vcav) (no related file):*
Updated all short options in all python scripts as it turns out we did not use them (e.g. `-o` instead of `-output`).

---
___
*[python/graphenelibos/manifest.py, line 150 at r3](https://reviewable.io/reviews/gramineproject/gramine/72#-Mk1hIEJ74pScPgHwqIw:-MksIRNu00jJH6GlDJ9e:b-r2boi) ([raw file](https://github.com/gramineproject/gramine/blob/30fec89398d430410f387e34ab29c508e3cddcdb/python/graphenelibos/manifest.py#L150)):*
Moved to `__init__`, because we don't have time for this, the release is happening soon.

> Please, can I get Python laid out as I like it? It will be me who would be reviewing it in the future.

No you cannot. Others will review these as well.


<!-- Sent from Reviewable.io -->

2021-09-30 20:50 UTC, mkow requested changes
> Reviewed 7 of 7 files at r15, 1 of 1 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/72)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @woju)

___
*[Documentation/manpages/gramine-sgx-get-token.rst, line 11 at r16](https://reviewable.io/reviews/gramineproject/gramine/72#-MksQmWVCeHkCLV9ZP-R:-MksQmWW9jQvkJsLOTAW:b-mkdwod) ([raw file](https://github.com/gramineproject/gramine/blob/62ac9c5cf1bf10ccd33572981710291514c5781e/Documentation/manpages/gramine-sgx-get-token.rst#L11)):*
> ```reStructuredText
> ========
> 
> :command:`gramine-sgx-get-token` [*OPTION*]... --sig sigstruct_file
> ```

This is incorrectly formatted after rendering: no const-width and things like e.g. `--` changed to `–`.
___
*[Documentation/manpages/gramine-sgx-get-token.rst, line 17 at r16](https://reviewable.io/reviews/gramineproject/gramine/72#-MksR1JH60VSkBDI4dFY:-MksR1JH60VSkBDI4dFZ:b77fchi) ([raw file](https://github.com/gramineproject/gramine/blob/62ac9c5cf1bf10ccd33572981710291514c5781e/Documentation/manpages/gramine-sgx-get-token.rst#L17)):*
> ```reStructuredText
> ===========
> 
> :program:`gramine-sgx-get-token` is used to generate the SGX Token file for
> ```

`Token` -> `token`
___
*[Documentation/manpages/gramine-sgx-sign.rst, line 11 at r16](https://reviewable.io/reviews/gramineproject/gramine/72#-MksRQlW8T0XbTK0W1Lr:-MksRQlW8T0XbTK0W1Ls:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/62ac9c5cf1bf10ccd33572981710291514c5781e/Documentation/manpages/gramine-sgx-sign.rst#L11)):*
> ```reStructuredText
> ========
> 
> :command:`gramine-sgx-sign` [*OPTION*]... --output output_manifest
> ```

ditto
___
*[Documentation/manpages/gramine-sgx-sign.rst, line 17 at r16](https://reviewable.io/reviews/gramineproject/gramine/72#-MksRW3d8xsQhy9oLw76:-MksRW3d8xsQhy9oLw77:b62sfwj) ([raw file](https://github.com/gramineproject/gramine/blob/62ac9c5cf1bf10ccd33572981710291514c5781e/Documentation/manpages/gramine-sgx-sign.rst#L17)):*
> ```reStructuredText
> ===========
> 
> :program:`gramine-sgx-sign` is used to expand Truested Files and generate
> ```

`Truested` -> `Trusted`


<!-- Sent from Reviewable.io -->

2021-09-30 21:15 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/72)* status: 35 of 37 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @woju)

___
*[Documentation/manpages/gramine-sgx-get-token.rst, line 11 at r16](https://reviewable.io/reviews/gramineproject/gramine/72#-MksQmWVCeHkCLV9ZP-R:-MksXv8l52Z8V0ZJEVIc:b-urmhx0) ([raw file](https://github.com/gramineproject/gramine/blob/62ac9c5cf1bf10ccd33572981710291514c5781e/Documentation/manpages/gramine-sgx-get-token.rst#L11)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This is incorrectly formatted after rendering: no const-width and things like e.g. `--` changed to `–`.
</blockquote></details>

This is in manpages directory and renders correctly if you use man to open in (after `make man`).
As to why https://gramine.readthedocs.io/en/latest/manpages/is_sgx_available.html is rendering incorrectly, I have no idea, but it's unrelated to this PR (the tool I've linked here is not modified in this PR and renders incorrectly).
___
*[Documentation/manpages/gramine-sgx-get-token.rst, line 17 at r16](https://reviewable.io/reviews/gramineproject/gramine/72#-MksR1JH60VSkBDI4dFY:-MksYgGx2lUDCNB0W4nf:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/62ac9c5cf1bf10ccd33572981710291514c5781e/Documentation/manpages/gramine-sgx-get-token.rst#L17)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`Token` -> `token`
</blockquote></details>

Done.
___
*[Documentation/manpages/gramine-sgx-sign.rst, line 11 at r16](https://reviewable.io/reviews/gramineproject/gramine/72#-MksRQlW8T0XbTK0W1Lr:-MksYgyuBc5I9tvNn1ey:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/62ac9c5cf1bf10ccd33572981710291514c5781e/Documentation/manpages/gramine-sgx-sign.rst#L11)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

ditto
___
*[Documentation/manpages/gramine-sgx-sign.rst, line 17 at r16](https://reviewable.io/reviews/gramineproject/gramine/72#-MksRW3d8xsQhy9oLw76:-MksYkM16_szP8_uGVLD:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/62ac9c5cf1bf10ccd33572981710291514c5781e/Documentation/manpages/gramine-sgx-sign.rst#L17)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`Truested` -> `Trusted`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-09-30 21:23 UTC, mkow submitted a review, later dismissed
> Reviewed 2 of 2 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/72)* status: all files reviewed, 2 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @woju)

___
*[Documentation/manpages/gramine-sgx-get-token.rst, line 11 at r16](https://reviewable.io/reviews/gramineproject/gramine/72#-MksQmWVCeHkCLV9ZP-R:-Mks_W8U675YdPUMGuUo:bnlmnrd) ([raw file](https://github.com/gramineproject/gramine/blob/62ac9c5cf1bf10ccd33572981710291514c5781e/Documentation/manpages/gramine-sgx-get-token.rst#L11)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This is in manpages directory and renders correctly if you use man to open in (after `make man`).
As to why https://gramine.readthedocs.io/en/latest/manpages/is_sgx_available.html is rendering incorrectly, I have no idea, but it's unrelated to this PR (the tool I've linked here is not modified in this PR and renders incorrectly).
</blockquote></details>

Ok, other already existing pages are also broken :/ We'll need to fix this separately.
CC: @woju.


<!-- Sent from Reviewable.io -->

2021-10-01 08:44 UTC, dimakuv approved these changes
> Reviewed 5 of 7 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/72)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @woju)



<!-- Sent from Reviewable.io -->

2021-10-01 10:12 UTC, woju requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/72)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/72#-MjvW2VNBlZ4l0iOML37:-Mkv7GQwEkzprbrGQqpB:b-vq3p8g) (no related file):*
> where to put this? In what format?

Preferably as Google-style docstrings parsed with https://www.sphinx-doc.org/en/master/usage/extensions/napoleon.html. Those should be included using https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html in descriptive documents somewhere in `Documentation/`.

---
___
*[Documentation/manpages/gramine-sgx-get-token.rst, line 11 at r16](https://reviewable.io/reviews/gramineproject/gramine/72#-MksQmWVCeHkCLV9ZP-R:-MkvJogN5wyVwQ_DqFI6:b8gasdm) ([raw file](https://github.com/gramineproject/gramine/blob/62ac9c5cf1bf10ccd33572981710291514c5781e/Documentation/manpages/gramine-sgx-get-token.rst#L11)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Ok, other already existing pages are also broken :/ We'll need to fix this separately.
CC: @woju.
</blockquote></details>

You don't usually list any options in synopsis, so in theory this should be included in `*options*`. The problem stems from the fact that `--sig` is mandatory. Optimally we should fix the invocation to just `gramine-sgx-get-token INPUT [OUTPUT]`.

Not now, obviously. Maybe add TODO item to revise all CLIs.
___
*[python/graminelibos/__init__.py, line 87 at r15](https://reviewable.io/reviews/gramineproject/gramine/72#-Mkv6hvJ77sEP7qYNnbo:-Mkv6hvJ77sEP7qYNnbp:buk1j9v) ([raw file](https://github.com/gramineproject/gramine/blob/48d58031f2daac92bc745c08171cdb52fc1eb57b/python/graminelibos/__init__.py#L87)):*
> ```Python
>     add_globals_from_python(env)
>     add_globals_misc(env)
>     return env
> ```

If you add this here instead of a separate file, at least add `__all__` without all this stuff. https://docs.python.org/3/tutorial/modules.html?highlight=__all__#importing-from-a-package


<!-- Sent from Reviewable.io -->

2021-10-01 13:43 UTC, mkow submitted a review, later dismissed
> Reviewed 3 of 3 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/72)* status: all files reviewed, 2 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @woju)



<!-- Sent from Reviewable.io -->

2021-10-01 17:13 UTC, woju submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/72)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/72#-MjvW2VNBlZ4l0iOML37:-MkwgQEVBbeqFeDHVt1M:b-fk2v4t) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

> Preferably as Google-style docstrings

Sounds good, will do.

> in descriptive documents somewhere in Documentation/

Since it will be you who would be reviewing it in the future, please tell me what to put and where exactly, I don't want to mess with your flows.
</blockquote></details>

Here you are: https://github.com/gramineproject/gramine/tree/woju/wip-python-docs-for-borys

Obviously subject to approval from other maintainers, who will also review it. I don't insist on menu placement nor `python/` subdirectory, but it might come handy for splitting off examples or whatnot.

---
___
*[Documentation/manpages/gramine-sgx-get-token.rst, line 11 at r16](https://reviewable.io/reviews/gramineproject/gramine/72#-MksQmWVCeHkCLV9ZP-R:-MkwpDOp0o7LvB8Xz5pB:b-2xu19i) ([raw file](https://github.com/gramineproject/gramine/blob/62ac9c5cf1bf10ccd33572981710291514c5781e/Documentation/manpages/gramine-sgx-get-token.rst#L11)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

The problem is with `gramine-sgx-sign` which has 3 mandatory arguments - I think that's too much for unnamed args. So I think we need (at least) a workaround anyway.
</blockquote></details>

Yes, I agree. Can we rethink this after putting the key in `.config/gramine`, so the key becomes optional? That will be 2 arguments, which I'd argue is OK.
___
*[python/graminelibos/__init__.py, line 87 at r15](https://reviewable.io/reviews/gramineproject/gramine/72#-Mkv6hvJ77sEP7qYNnbo:-MkwpwjQ-AiECcwHgX0i:b-9755fa) ([raw file](https://github.com/gramineproject/gramine/blob/48d58031f2daac92bc745c08171cdb52fc1eb57b/python/graminelibos/__init__.py#L87)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Moved to another file.
</blockquote></details>

Thank you.


<!-- Sent from Reviewable.io -->

2021-10-01 17:59 UTC, dimakuv approved these changes
> Reviewed 7 of 7 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/72)* status: all files reviewed, 1 unresolved discussion (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2021-10-01 18:07 UTC, mkow approved these changes
> Reviewed 7 of 7 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/72)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-10-01 18:27 UTC, merged