Update secret provisioning example and the libsecret_prov_attest.so to terminate execution when remote attestation fails.
gramineproject/gramine pull request #721
Opened 2022-07-01 19:11 UTC by aneessahib

The `libsecret_prov_attest.so` library provisions a secret upon successful attestation. However, there can be cases when applications would want Gramine to terminate upon an unsuccessful attestation, as opposed to the application directly handling this part. In this PR,  `libsecret_prov_attest.so`  exits when attestation is unsuccessful, also handles a case where there aren't any keys to provision, under which case a `REMOTE_ATTESTATION_SUCCESSFUL` string is set at the host enclave (by the server), that client applications are free to modify and use if they want.

2022-07-04 07:20 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/721)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @aneessahib)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/721#-N6745MU75mmycWF-ZjI:-N6741mT01iUw8tYIY5N:b-cbwzzp) (no related file):*
Could you please update the README for the `ra-tls-secret-prov` example? But please check my other comments first -- I suggest to add a command-line argument to `secret_prov_server`.

___
___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/721#-N6735z2-IxB8iq-8np4):*
Needs to be modified for final merge. I'll come up with some message.
___
*[`CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c` line 110 at r1](https://reviewable.io/reviews/gramineproject/gramine/721#-N673U7k0T50rVWgENsm:-N673U7lDpkNcocgvfYr:b49n6a7) ([raw file](https://github.com/gramineproject/gramine/blob/bc5415595009fdbccd57db8cf4befff8a3e9c163/CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c#L110)):*
> ```C
>     puts("--- Reading the master key for protected files from '" WRAP_KEY_FILENAME "' ---");
>     int fd = open(WRAP_KEY_FILENAME, O_RDONLY);
>     if (fd >= 0) {
> ```

Hm, wouldn't it be better to introduce an argument to `secret_prov_server`, e.g.:
```
./secret_prov_server <wrap-key-filename>
```

Then we can:
1. remove the hard-coded `WRAP_KEY_FILENAME` and use `argv[1]` instead -- gives more flexibility
2. if there is no `argv[1]` (`argc == 1`), then do your proposed flow with sending this `"REMOTE_ATTESTATION_SUCCESSFUL"` string
___
*[`CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c` line 144 at r1](https://reviewable.io/reviews/gramineproject/gramine/721#-N671fSK26wN9Bk8ZwLC:-N671fSK26wN9Bk8ZwLD:b-y44y8v) ([raw file](https://github.com/gramineproject/gramine/blob/bc5415595009fdbccd57db8cf4befff8a3e9c163/CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c#L144)):*
> ```C
>             sprintf(&g_secret_string[i * 2], "%02x", ptr[i]);
>     }
>     else {
> ```

Please re-wrap like this:
```
} else {
```
___
*[`CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c` line 145 at r1](https://reviewable.io/reviews/gramineproject/gramine/721#-N671ie9ALAQa_Gu9Cat:-N671ie9ALAQa_Gu9Cau:bpg3tek) ([raw file](https://github.com/gramineproject/gramine/blob/bc5415595009fdbccd57db8cf4befff8a3e9c163/CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c#L145)):*
> ```C
>     }
>     else {
>         strcpy(g_secret_string, "ATTESTATION_SUCCESS_STRING");
> ```

Before this, please add an explanatory message:
```
    puts("[ file '" WRAP_KEY_FILENAME "' cannot be opened; proceeding without the master key]");
```
___
*[`CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c` line 145 at r1](https://reviewable.io/reviews/gramineproject/gramine/721#-N6725Cb8sVtlCqVOKPa:-N6725Cb8sVtlCqVOKPb:bcueisu) ([raw file](https://github.com/gramineproject/gramine/blob/bc5415595009fdbccd57db8cf4befff8a3e9c163/CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c#L145)):*
> ```C
>     }
>     else {
>         strcpy(g_secret_string, "ATTESTATION_SUCCESS_STRING");
> ```

I guess you didn't mean to put `ATTESTATION_SUCCESS_STRING` in double quotes? Otherwise you're sending this string `"ATTESTATION_SUCCESS_STRING"` instead of the actual macro contents (`"REMOTE_ATTESTATION_SUCCESSFUL"`).
___
*[`CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c` line 145 at r1](https://reviewable.io/reviews/gramineproject/gramine/721#-N672VmlB9MfZwdfDsuq:-N672VmlB9MfZwdfDsur:b-5z3fga) ([raw file](https://github.com/gramineproject/gramine/blob/bc5415595009fdbccd57db8cf4befff8a3e9c163/CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c#L145)):*
> ```C
>     }
>     else {
>         strcpy(g_secret_string, "ATTESTATION_SUCCESS_STRING");
> ```

This can be a potential buffer overflow. Please add a check before strcpy:
```
static_assert(sizeof(g_secret_string) >= sizeof(ATTESTATION_SUCCESS_STRING), "size of g_secret_string is too small");
```
___
*[`pal/src/host/linux-sgx/tools/ra-tls/secret_prov_attest.c` line 313 at r1](https://reviewable.io/reviews/gramineproject/gramine/721#-N670v1k2U-4MPTKpmf3:-N670v1lDFZoQlNKovMV:b-2c1l9y) ([raw file](https://github.com/gramineproject/gramine/blob/bc5415595009fdbccd57db8cf4befff8a3e9c163/pal/src/host/linux-sgx/tools/ra-tls/secret_prov_attest.c#L313)):*
> ```C
>                                          /*out_ctx=*/NULL);
>         if (ret < 0) {
>             ERROR("Attestation unsuccessful\n");
> ```

I suggest this message: `Secret provisioning failed, terminating the whole process\n`


<!-- Sent from Reviewable.io -->

2022-07-11 04:20 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/721)* status: 0 of 3 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib and @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/721#-N6745MU75mmycWF-ZjI:-N6fTOgt4xBVnDoOe_mi:b-896fix) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you please update the README for the `ra-tls-secret-prov` example? But please check my other comments first -- I suggest to add a command-line argument to `secret_prov_server`.
</blockquote></details>

Done.

___
___
*[`CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c` line 110 at r1](https://reviewable.io/reviews/gramineproject/gramine/721#-N673U7k0T50rVWgENsm:-N6fTaCVCqUFpCglYyOl:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/bc5415595009fdbccd57db8cf4befff8a3e9c163/CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c#L110)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Hm, wouldn't it be better to introduce an argument to `secret_prov_server`, e.g.:
```
./secret_prov_server <wrap-key-filename>
```

Then we can:
1. remove the hard-coded `WRAP_KEY_FILENAME` and use `argv[1]` instead -- gives more flexibility
2. if there is no `argv[1]` (`argc == 1`), then do your proposed flow with sending this `"REMOTE_ATTESTATION_SUCCESSFUL"` string
</blockquote></details>

Done.
___
*[`CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c` line 144 at r1](https://reviewable.io/reviews/gramineproject/gramine/721#-N671fSK26wN9Bk8ZwLC:-N6fTbeF3wqwQr1XLeBW:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/bc5415595009fdbccd57db8cf4befff8a3e9c163/CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c#L144)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please re-wrap like this:
```
} else {
```
</blockquote></details>

Done.
___
*[`CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c` line 145 at r1](https://reviewable.io/reviews/gramineproject/gramine/721#-N671ie9ALAQa_Gu9Cat:-N6fU2_T2EmMcPPwOkyW:b-fwfop0) ([raw file](https://github.com/gramineproject/gramine/blob/bc5415595009fdbccd57db8cf4befff8a3e9c163/CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c#L145)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Before this, please add an explanatory message:
```
    puts("[ file '" WRAP_KEY_FILENAME "' cannot be opened; proceeding without the master key]");
```
</blockquote></details>

Done. Modified to suit keys being passed as argument
___
*[`CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c` line 145 at r1](https://reviewable.io/reviews/gramineproject/gramine/721#-N6725Cb8sVtlCqVOKPa:-N6fU8uS14-QToQ8YyLi:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/bc5415595009fdbccd57db8cf4befff8a3e9c163/CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c#L145)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I guess you didn't mean to put `ATTESTATION_SUCCESS_STRING` in double quotes? Otherwise you're sending this string `"ATTESTATION_SUCCESS_STRING"` instead of the actual macro contents (`"REMOTE_ATTESTATION_SUCCESSFUL"`).
</blockquote></details>

Done.
___
*[`CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c` line 145 at r1](https://reviewable.io/reviews/gramineproject/gramine/721#-N672VmlB9MfZwdfDsuq:-N6fUAVE9csGaqeuWMrM:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/bc5415595009fdbccd57db8cf4befff8a3e9c163/CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c#L145)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This can be a potential buffer overflow. Please add a check before strcpy:
```
static_assert(sizeof(g_secret_string) >= sizeof(ATTESTATION_SUCCESS_STRING), "size of g_secret_string is too small");
```
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/tools/ra-tls/secret_prov_attest.c` line 313 at r1](https://reviewable.io/reviews/gramineproject/gramine/721#-N670v1k2U-4MPTKpmf3:-N6fUCLfEBj5fUrojYGF:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/bc5415595009fdbccd57db8cf4befff8a3e9c163/pal/src/host/linux-sgx/tools/ra-tls/secret_prov_attest.c#L313)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I suggest this message: `Secret provisioning failed, terminating the whole process\n`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-11 07:09 UTC, dimakuv requested changes
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/721)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib)

___
*[`CI-Examples/ra-tls-secret-prov/README.md` line 23 at r2](https://reviewable.io/reviews/gramineproject/gramine/721#-N6g2Ht0CAKjeMSeB8o5:-N6g2Ht0CAKjeMSeB8o6:b-affgcj) ([raw file](https://github.com/gramineproject/gramine/blob/4ec073a9dc3d62f9209627293ba11c1dc05023ef/CI-Examples/ra-tls-secret-prov/README.md#L23)):*
> ```Markdown
> verifies the client's RA-TLS certificate and the embedded SGX quote and, if
> verification succeeds, sends the first secret back to the client (the master key
> for encrypted files, read from `files/wrap-key that is passed as a user argument
> ```

You accidentally removed the closing backtick.
___
*[`CI-Examples/ra-tls-secret-prov/README.md` line 23 at r2](https://reviewable.io/reviews/gramineproject/gramine/721#-N6g2O0s9E90A83Vqoxj:-N6g2O0s9E90A83Vqoxk:bsupdup) ([raw file](https://github.com/gramineproject/gramine/blob/4ec073a9dc3d62f9209627293ba11c1dc05023ef/CI-Examples/ra-tls-secret-prov/README.md#L23)):*
> ```Markdown
> verifies the client's RA-TLS certificate and the embedded SGX quote and, if
> verification succeeds, sends the first secret back to the client (the master key
> for encrypted files, read from `files/wrap-key that is passed as a user argument
> ```

`user argument` -> `command-line argument`
___
*[`CI-Examples/ra-tls-secret-prov/README.md` line 24 at r2](https://reviewable.io/reviews/gramineproject/gramine/721#-N6g4d6O9rIIv9zsv4K6:-N6g4d6O9rIIv9zsv4K7:b-e6i7pt) ([raw file](https://github.com/gramineproject/gramine/blob/4ec073a9dc3d62f9209627293ba11c1dc05023ef/CI-Examples/ra-tls-secret-prov/README.md#L24)):*
> ```Markdown
> verification succeeds, sends the first secret back to the client (the master key
> for encrypted files, read from `files/wrap-key that is passed as a user argument
> while running the server). If the client requests a second secret, the server
> ```

`... the server)` -> `...... the server, or the string "REMOTE_ATTESTATION_SUCCESSFUL" if no command-line argument is provided)`
___
*[`CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c` line 22 at r2](https://reviewable.io/reviews/gramineproject/gramine/721#-N6g30fu3fpDUtpCwO_w:-N6g30fu3fpDUtpCwO_x:b-lmyjse) ([raw file](https://github.com/gramineproject/gramine/blob/4ec073a9dc3d62f9209627293ba11c1dc05023ef/CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c#L22)):*
> ```C
> #define ATTESTATION_SUCCESS_STRING "REMOTE_ATTESTATION_SUCCESSFUL"
> 
> #define WRAP_KEY_FILENAME "files/wrap-key"
> ```

This is not needed anymore.
___
*[`CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c` line 108 at r2](https://reviewable.io/reviews/gramineproject/gramine/721#-N6g3jgh9MxSrPCywVvn:-N6g3jgh9MxSrPCywVvo:b-4w0wjx) ([raw file](https://github.com/gramineproject/gramine/blob/4ec073a9dc3d62f9209627293ba11c1dc05023ef/CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c#L108)):*
> ```C
>         return ret;
> 
>     if (argc == 1) {
> ```

Technically, it is possible that `argvc == 0` and then you jump into the else branch where accessing `argv[1]` results in a segfault.

So I suggest to change to `if (argc < 2)`.
___
*[`CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c` line 109 at r2](https://reviewable.io/reviews/gramineproject/gramine/721#-N6g37dYEnca4udCJHWt:-N6g37dYEnca4udCJHWu:b-xwz2sg) ([raw file](https://github.com/gramineproject/gramine/blob/4ec073a9dc3d62f9209627293ba11c1dc05023ef/CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c#L109)):*
> ```C
> 
>     if (argc == 1) {
>         puts("--- Proceeding without a master key");
> ```

Add ` ---` at the end, this looks more pleasing
___
*[`CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c` line 110 at r2](https://reviewable.io/reviews/gramineproject/gramine/721#-N6g341N6_GqBrVy0B-F:-N6g341N6_GqBrVy0B-G:b-4a0u18) ([raw file](https://github.com/gramineproject/gramine/blob/4ec073a9dc3d62f9209627293ba11c1dc05023ef/CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c#L110)):*
> ```C
>     if (argc == 1) {
>         puts("--- Proceeding without a master key");
>         static_assert(sizeof(g_secret_string) >= sizeof(ATTESTATION_SUCCESS_STRING), "size of g_secret_string is too small");
> ```

Please re-wrap to fit into 100 char per line limit
___
*[`CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c` line 113 at r2](https://reviewable.io/reviews/gramineproject/gramine/721#-N6g3PYFBF8LF9hK6aB2:-N6g3PYFBF8LF9hK6aB3:bbnm7tr) ([raw file](https://github.com/gramineproject/gramine/blob/4ec073a9dc3d62f9209627293ba11c1dc05023ef/CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c#L113)):*
> ```C
>         strcpy(g_secret_string, ATTESTATION_SUCCESS_STRING);
>     } else {
>         puts("--- Reading the master key for encrypted files");
> ```

`printf("--- Reading the master key for encrypted files from '%s' ---", argv[1]);`
___
*[`CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c` line 115 at r2](https://reviewable.io/reviews/gramineproject/gramine/721#-N6g44mv-WR1sYYSzDxX:-N6g44mv-WR1sYYSzDxY:bfqqecs) ([raw file](https://github.com/gramineproject/gramine/blob/4ec073a9dc3d62f9209627293ba11c1dc05023ef/CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c#L115)):*
> ```C
>         puts("--- Reading the master key for encrypted files");
>         int fd = open(argv[1], O_RDONLY);
>         if (fd >= 0) {
> ```

This is hard to read, I suggest to use the original check:
```
    if (fd < 0) {
        fprintf(stderr, "[error] cannot open '%s'\n", argv[1]);
        return 1;
    }
```

... and then continue with your new code:
```
        char buf[WRAP_KEY_SIZE + 1] = {0}; /* +1 is to detect if file is not bigger than expected */
        ...
```


<!-- Sent from Reviewable.io -->

2022-07-11 13:27 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/721)* status: 1 of 3 files reviewed, 10 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib and @dimakuv)

___
*[`CI-Examples/ra-tls-secret-prov/README.md` line 23 at r2](https://reviewable.io/reviews/gramineproject/gramine/721#-N6g2Ht0CAKjeMSeB8o5:-N6hR-KV9AbQkbdfSCC_:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/4ec073a9dc3d62f9209627293ba11c1dc05023ef/CI-Examples/ra-tls-secret-prov/README.md#L23)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You accidentally removed the closing backtick.
</blockquote></details>

Done.
___
*[`CI-Examples/ra-tls-secret-prov/README.md` line 23 at r2](https://reviewable.io/reviews/gramineproject/gramine/721#-N6g2O0s9E90A83Vqoxj:-N6hR-iX2iPvevJK7K8n:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/4ec073a9dc3d62f9209627293ba11c1dc05023ef/CI-Examples/ra-tls-secret-prov/README.md#L23)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`user argument` -> `command-line argument`
</blockquote></details>

Done.
___
*[`CI-Examples/ra-tls-secret-prov/README.md` line 24 at r2](https://reviewable.io/reviews/gramineproject/gramine/721#-N6g4d6O9rIIv9zsv4K6:-N6hR1IADXuhv0LViXjk:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/4ec073a9dc3d62f9209627293ba11c1dc05023ef/CI-Examples/ra-tls-secret-prov/README.md#L24)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`... the server)` -> `...... the server, or the string "REMOTE_ATTESTATION_SUCCESSFUL" if no command-line argument is provided)`
</blockquote></details>

Done.
___
*[`CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c` line 22 at r2](https://reviewable.io/reviews/gramineproject/gramine/721#-N6g30fu3fpDUtpCwO_w:-N6hR3-h27fBmUWJYqTD:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/4ec073a9dc3d62f9209627293ba11c1dc05023ef/CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c#L22)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This is not needed anymore.
</blockquote></details>

Done.
___
*[`CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c` line 108 at r2](https://reviewable.io/reviews/gramineproject/gramine/721#-N6g3jgh9MxSrPCywVvn:-N6hR7lv9To2Usy6nxEH:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/4ec073a9dc3d62f9209627293ba11c1dc05023ef/CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c#L108)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Technically, it is possible that `argvc == 0` and then you jump into the else branch where accessing `argv[1]` results in a segfault.

So I suggest to change to `if (argc < 2)`.
</blockquote></details>

Done.
___
*[`CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c` line 109 at r2](https://reviewable.io/reviews/gramineproject/gramine/721#-N6g37dYEnca4udCJHWt:-N6hR8AgDEPV8Fd-u-cE:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/4ec073a9dc3d62f9209627293ba11c1dc05023ef/CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c#L109)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Add ` ---` at the end, this looks more pleasing
</blockquote></details>

Done.
___
*[`CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c` line 110 at r2](https://reviewable.io/reviews/gramineproject/gramine/721#-N6g341N6_GqBrVy0B-F:-N6hRBmI4yxaKR4-lajS:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/4ec073a9dc3d62f9209627293ba11c1dc05023ef/CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c#L110)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please re-wrap to fit into 100 char per line limit
</blockquote></details>

Done.
___
*[`CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c` line 113 at r2](https://reviewable.io/reviews/gramineproject/gramine/721#-N6g3PYFBF8LF9hK6aB2:-N6hRDoy5rEUMBIgY8nf:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/4ec073a9dc3d62f9209627293ba11c1dc05023ef/CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c#L113)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`printf("--- Reading the master key for encrypted files from '%s' ---", argv[1]);`
</blockquote></details>

Done.
___
*[`CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c` line 115 at r2](https://reviewable.io/reviews/gramineproject/gramine/721#-N6g44mv-WR1sYYSzDxX:-N6hRFC67uEsne0O05KN:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/4ec073a9dc3d62f9209627293ba11c1dc05023ef/CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c#L115)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This is hard to read, I suggest to use the original check:
```
    if (fd < 0) {
        fprintf(stderr, "[error] cannot open '%s'\n", argv[1]);
        return 1;
    }
```

... and then continue with your new code:
```
        char buf[WRAP_KEY_SIZE + 1] = {0}; /* +1 is to detect if file is not bigger than expected */
        ...
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-12 06:32 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/721)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib)

___
*[`CI-Examples/ra-tls-secret-prov/README.md` line 24 at r3](https://reviewable.io/reviews/gramineproject/gramine/721#-N6l42W_7m90jw8cB8sR:-N6l42W_7m90jw8cB8sS:b-yxm7f2) ([raw file](https://github.com/gramineproject/gramine/blob/971006b11731e0aec7cb9035f71428ac36faa524/CI-Examples/ra-tls-secret-prov/README.md#L24)):*
> ```Markdown
> verification succeeds, sends the first secret back to the client (the master key
> for encrypted files, read from `files/wrap-key` that is passed as a command-line
> argument while running the server, or the string "REMOTE_ATTESTATION_SUCCESSFUL"
> ```

```
"REMOTE_ATTESTATION_SUCCESSFUL"
```
->
```
`REMOTE_ATTESTATION_SUCCESSFUL`
```
___
*[`CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c` line 110 at r2](https://reviewable.io/reviews/gramineproject/gramine/721#-N6g341N6_GqBrVy0B-F:-N6l4MxI9JnF9rcIm11A:bt31xfn) ([raw file](https://github.com/gramineproject/gramine/blob/4ec073a9dc3d62f9209627293ba11c1dc05023ef/CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c#L110)):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

In Gramine, we re-wrap so that the beginning of the second line is intended to be right-below the first argument in the first line. So like this:
```
        static_assert(sizeof(g_secret_string) >= sizeof(ATTESTATION_SUCCESS_STRING),
                      "size of g_secret_string is too small");
```
___
*[`CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c` line 113 at r2](https://reviewable.io/reviews/gramineproject/gramine/721#-N6g3PYFBF8LF9hK6aB2:-N6l4_-u1c5-cPOJ29e8:b-35xdkb) ([raw file](https://github.com/gramineproject/gramine/blob/4ec073a9dc3d62f9209627293ba11c1dc05023ef/CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c#L113)):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Oops, sorry, forgot `\n` at the end of the line. Please add it.
___
*[`CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c` line 116 at r3](https://reviewable.io/reviews/gramineproject/gramine/721#-N6l4lHE0sR71IDrUxC6:-N6l4lHE0sR71IDrUxC7:bxjlgwk) ([raw file](https://github.com/gramineproject/gramine/blob/971006b11731e0aec7cb9035f71428ac36faa524/CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c#L116)):*
> ```C
>         int fd = open(argv[1], O_RDONLY);
>         if (fd < 0) {
>             fprintf(stderr, "[error] cannot read %s\n", argv[1]);
> ```

`read` -> `open`


<!-- Sent from Reviewable.io -->

2022-07-12 09:36 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/721)* status: 1 of 3 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib and @dimakuv)

___
*[`CI-Examples/ra-tls-secret-prov/README.md` line 24 at r3](https://reviewable.io/reviews/gramineproject/gramine/721#-N6l42W_7m90jw8cB8sR:-N6lkzPs8_lk9i3E1qT9:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/971006b11731e0aec7cb9035f71428ac36faa524/CI-Examples/ra-tls-secret-prov/README.md#L24)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

```
"REMOTE_ATTESTATION_SUCCESSFUL"
```
->
```
`REMOTE_ATTESTATION_SUCCESSFUL`
```
</blockquote></details>

Done.
___
*[`CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c` line 110 at r2](https://reviewable.io/reviews/gramineproject/gramine/721#-N6g341N6_GqBrVy0B-F:-N6ll1lXCPKpQ-uDIDlu:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/4ec073a9dc3d62f9209627293ba11c1dc05023ef/CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c#L110)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

In Gramine, we re-wrap so that the beginning of the second line is intended to be right-below the first argument in the first line. So like this:
```
        static_assert(sizeof(g_secret_string) >= sizeof(ATTESTATION_SUCCESS_STRING),
                      "size of g_secret_string is too small");
```
</blockquote></details>

Done.
___
*[`CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c` line 113 at r2](https://reviewable.io/reviews/gramineproject/gramine/721#-N6g3PYFBF8LF9hK6aB2:-N6ll3YsCFdj084_khZw:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/4ec073a9dc3d62f9209627293ba11c1dc05023ef/CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c#L113)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Oops, sorry, forgot `\n` at the end of the line. Please add it.
</blockquote></details>

Done.
___
*[`CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c` line 116 at r3](https://reviewable.io/reviews/gramineproject/gramine/721#-N6l4lHE0sR71IDrUxC6:-N6ll54G53KpJgPteLAD:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/971006b11731e0aec7cb9035f71428ac36faa524/CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c#L116)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`read` -> `open`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-12 09:36 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/721)* status: 1 of 3 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib and @dimakuv)

___
*[`CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c` line 113 at r2](https://reviewable.io/reviews/gramineproject/gramine/721#-N6g3PYFBF8LF9hK6aB2:-N6ll86r-6VJNElwhjA0:b-bi9ofc) ([raw file](https://github.com/gramineproject/gramine/blob/4ec073a9dc3d62f9209627293ba11c1dc05023ef/CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c#L113)):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

my bad.


<!-- Sent from Reviewable.io -->

2022-07-12 11:42 UTC, dimakuv submitted a review, later dismissed
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/721)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @aneessahib)



<!-- Sent from Reviewable.io -->

2022-07-23 18:41 UTC, mkow requested changes
> Reviewed 1 of 3 files at r2, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/721)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @aneessahib)

___
*[`CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c` line 111 at r4](https://reviewable.io/reviews/gramineproject/gramine/721#-N7gLNb-0Vx70Ibsq9Uk:-N7gLNb-0Vx70Ibsq9Ul:bv7cq15) ([raw file](https://github.com/gramineproject/gramine/blob/1ae61c06ed853dddc67341f2c88a23102d725da0/CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c#L111)):*
> ```C
>         static_assert(sizeof(g_secret_string) >= sizeof(ATTESTATION_SUCCESS_STRING),
>                       "size of g_secret_string is too small");
>         strcpy(g_secret_string, ATTESTATION_SUCCESS_STRING);
> ```

Please also assert that the length of `ATTESTATION_SUCCESS_STRING` is different than `WRAP_KEY_SIZE * 2`, otherwise `ATTESTATION_SUCCESS_STRING` could also be a valid key, which is quite ugly and hacky.
___
*[`CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c` line 117 at r4](https://reviewable.io/reviews/gramineproject/gramine/721#-N7gLm8K95QZwiv-78h4:-N7gLm8K95QZwiv-78h5:b-azuwls) ([raw file](https://github.com/gramineproject/gramine/blob/1ae61c06ed853dddc67341f2c88a23102d725da0/CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c#L117)):*
> ```C
>         if (fd < 0) {
>             fprintf(stderr, "[error] cannot open %s\n", argv[1]);
>             close(fd);
> ```

Ugh, you're closing a negative fd here? The code was correct before.
___
*[`pal/src/host/linux-sgx/tools/ra-tls/secret_prov_attest.c` line 313 at r4](https://reviewable.io/reviews/gramineproject/gramine/721#-N7gLC-ADIGR5LCiK8Wr:-N7gLC-B0JAAmZyLbuBZ:b7icsh) ([raw file](https://github.com/gramineproject/gramine/blob/1ae61c06ed853dddc67341f2c88a23102d725da0/pal/src/host/linux-sgx/tools/ra-tls/secret_prov_attest.c#L313)):*
> ```C
>                                          /*out_ctx=*/NULL);
>         if (ret < 0) {
>             ERROR("Secret provisioning failed, terminating the whole process\n");
> ```

Do we want to do this? It makes impossible for a well written app to handle this error gracefully...


<!-- Sent from Reviewable.io -->

2022-07-23 19:59 UTC, boryspoplawski requested changes
> Reviewed 1 of 3 files at r2, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/721)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @aneessahib)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/721#-N7gcwrS7VBPbUetdkIG:-N7gcwrS7VBPbUetdkIH:by3pv1r) (no related file):*
What's the point of this PR? It modifies an example called "secret provisioning" (optionally) not to send any secrets??

___


<!-- Sent from Reviewable.io -->

2022-07-25 07:07 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/721)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @aneessahib and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/721#-N7gcwrS7VBPbUetdkIG:-N7oAXlUBH39TKKkLHS6:b3tb2vh) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

What's the point of this PR? It modifies an example called "secret provisioning" (optionally) not to send any secrets??
</blockquote></details>

Well, yes, this sounds counter-intuitive. One can say that this string `REMOTE_ATTESTATION_SUCCESSFUL` is a "dummy" secret. But to be honest, I don't know what is the exact scenario where @aneessahib needs it. @aneessahib Could you comment?

___
___
*[`pal/src/host/linux-sgx/tools/ra-tls/secret_prov_attest.c` line 313 at r4](https://reviewable.io/reviews/gramineproject/gramine/721#-N7gLC-ADIGR5LCiK8Wr:-N7o9Iz60MXAmiJAuXMj:b-vx9jw6) ([raw file](https://github.com/gramineproject/gramine/blob/1ae61c06ed853dddc67341f2c88a23102d725da0/pal/src/host/linux-sgx/tools/ra-tls/secret_prov_attest.c#L313)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Do we want to do this? It makes impossible for a well written app to handle this error gracefully...
</blockquote></details>

But how can the app handle this error gracefully?

Don't forget that we end up in this code snippet only if:
- The enclave developer didn't want to modify the app in the first place (at all),
- therefore the enclave developer added `loader.env.SECRET_PROVISION_CONSTRUCTOR = "true"`,
- most probably this secret is the key for file encryption (`loader.env.SECRET_PROVISION_SET_KEY = "default"`)

So, the enclave developer wants the enclave to get the secret without the app informed about it. It is explicitly specified in the manifest file. So I think there is no other way but to kill the process if Secret Provisioning failed for some reason.


<!-- Sent from Reviewable.io -->

2022-07-25 09:17 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/721)* status: 2 of 3 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @boryspoplawski, @dimakuv, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/721#-N7gcwrS7VBPbUetdkIG:-N7oak5K8LFFDR49Pw6B:b-ecv8cc) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Well, yes, this sounds counter-intuitive. One can say that this string `REMOTE_ATTESTATION_SUCCESSFUL` is a "dummy" secret. But to be honest, I don't know what is the exact scenario where @aneessahib needs it. @aneessahib Could you comment?
</blockquote></details>

The idea here is that, secrets does not have to only be a wrap key (as it is currently). User can choose this to be anything - I have added `REMOTE_ATTESTATION_SUCCESSFUL` as a default secret, that host enclave can confirm to be sure the attestation is indeed successful. This PR also have changes to terminate the full process in the event of an unsuccessful attestation - and the extra `REMOTE_ATTESTATION_SUCCESSFUL`  secret would also give the developer further flexibility to re-confirm if she/he wishes.

I'm not sure if this is what @boryspoplawski  meant to ask though. Not sending secrets is something that's already possible in the existing flow, and then it's upto the app to handle this.

___
___
*[`CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c` line 111 at r4](https://reviewable.io/reviews/gramineproject/gramine/721#-N7gLNb-0Vx70Ibsq9Uk:-N7oaL6lAo1g42nyGq3l:besrwh4) ([raw file](https://github.com/gramineproject/gramine/blob/1ae61c06ed853dddc67341f2c88a23102d725da0/CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c#L111)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please also assert that the length of `ATTESTATION_SUCCESS_STRING` is different than `WRAP_KEY_SIZE * 2`, otherwise `ATTESTATION_SUCCESS_STRING` could also be a valid key, which is quite ugly and hacky.
</blockquote></details>

Done. Kept a separate assert statement itself to know what's what. Let me know if the messaging needs to be specific.
___
*[`CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c` line 117 at r4](https://reviewable.io/reviews/gramineproject/gramine/721#-N7gLm8K95QZwiv-78h4:-N7oaMcs9jZFzMF7v4dx:b-hmpdme) ([raw file](https://github.com/gramineproject/gramine/blob/1ae61c06ed853dddc67341f2c88a23102d725da0/CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c#L117)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Ugh, you're closing a negative fd here? The code was correct before.
</blockquote></details>

yuck !


<!-- Sent from Reviewable.io -->

2022-07-25 11:35 UTC, boryspoplawski requested changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/721)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @dimakuv, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/721#-N7gcwrS7VBPbUetdkIG:-N7p6oMuESAm5L_lVc1Q:bppnvqs) (no related file):*
But user cannot use anything, current example has many limitations (with or without this PR), e.g. max length, must be a C string, etc.
1) This is an example. Users needing more complex solutions need to write it themselves. 
2) This example already sends an arbitrary string `SECRET_STRING`.

> This PR also have changes to terminate the full process in the event of an unsuccessful attestation

This is completely orthogonal. Actually, why these two things are in one PR?

___
___
*[`CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c` line 111 at r4](https://reviewable.io/reviews/gramineproject/gramine/721#-N7gLNb-0Vx70Ibsq9Uk:-N7p6F4Y5ykbQgsRqdhW:b-zg7l2) ([raw file](https://github.com/gramineproject/gramine/blob/1ae61c06ed853dddc67341f2c88a23102d725da0/CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c#L111)):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

Done. Kept a separate assert statement itself to know what's what. Let me know if the messaging needs to be specific.
</blockquote></details>

Not done, you asserted something completely different. Should be `sizeof(ATTESTATION_SUCCESS_STRING) != WRAP_KEY_SIZE * 2 + 1`


<!-- Sent from Reviewable.io -->

2022-07-26 03:42 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/721)* status: 2 of 3 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @boryspoplawski, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/721#-N7gcwrS7VBPbUetdkIG:-N7pSzxyDQBpTZVCLP4O:bz0h8zk) (no related file):*
> This is an example. Users needing more complex solutions need to write it themselves.
In this PR, Gramine take a conservative/strict stance of terminating the process in the event of a failed secret provisioning flow. And this behavior (AFAIK) - is something quite many applications desire today (also minimizes any mods to the source application). If this does not work for a user (which is a scenario we are yet to widely see), he is free to modify the example to suit his needs, just like you mentioned.   

> This example already sends an arbitrary string SECRET_STRING.
An empty string is sent if secret provisioning fails - but the premise there again is that a secret cannot be anything other a wrap key - which is quite restrictive. 

> This is completely orthogonal. Actually, why these two things are in one PR?
loosely related since the PR attempts at streamlining the attestation piece of the secret prov flow, moreover this ones a single line change. But could have gone as a separate PR (or atleast a separate commit) now when I think of it. Let me know if I need to split up.

___
___
*[`CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c` line 111 at r4](https://reviewable.io/reviews/gramineproject/gramine/721#-N7gLNb-0Vx70Ibsq9Uk:-N7pPbos6wllTE4_ZRXa:b-qyj8iv) ([raw file](https://github.com/gramineproject/gramine/blob/1ae61c06ed853dddc67341f2c88a23102d725da0/CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c#L111)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Not done, you asserted something completely different. Should be `sizeof(ATTESTATION_SUCCESS_STRING) != WRAP_KEY_SIZE * 2 + 1`
</blockquote></details>

Ahh. So this is to prevent lazy users from abusing this macro by hardcoding keys!. Again - do i need to message this in a different way - like "ATTESTATION_SUCCESS_STRING should not be a key"


<!-- Sent from Reviewable.io -->

2022-07-26 06:28 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/721)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @boryspoplawski, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/721#-N7gcwrS7VBPbUetdkIG:-N7tA4CR7TN7MHgnegoo:biomyo2) (no related file):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

> This is an example. Users needing more complex solutions need to write it themselves.
In this PR, Gramine take a conservative/strict stance of terminating the process in the event of a failed secret provisioning flow. And this behavior (AFAIK) - is something quite many applications desire today (also minimizes any mods to the source application). If this does not work for a user (which is a scenario we are yet to widely see), he is free to modify the example to suit his needs, just like you mentioned.   

> This example already sends an arbitrary string SECRET_STRING.
An empty string is sent if secret provisioning fails - but the premise there again is that a secret cannot be anything other a wrap key - which is quite restrictive. 

> This is completely orthogonal. Actually, why these two things are in one PR?
loosely related since the PR attempts at streamlining the attestation piece of the secret prov flow, moreover this ones a single line change. But could have gone as a separate PR (or atleast a separate commit) now when I think of it. Let me know if I need to split up.
</blockquote></details>

@aneessahib At this point, I feel like we need to separate the change in `secret_prov_attest.c` into a separate PR. And keep the changes to the SecretProv CI-Example in this PR.

I have another suggestion if Borys dislikes the change with `ATTESTATION_SUCCESS_STRING` that much. I think the whole point of this change to the SecretProv CI-Example was to *not* open the file `files/wrap-key` unconditionally. So Anees introduced a `argv[1]` for this. But if there is no argument, Anees currently sends some this dummy `ATTESTATION_SUCCESS_STRING`.

So maybe instead of sending `ATTESTATION_SUCCESS_STRING`, we can have a hard-coded dummy key (like all-zeros) and send it, instead of that string? This way the flow would be less surprising -- we will always send some secret.

___


<!-- Sent from Reviewable.io -->

2022-07-26 12:47 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/721)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @boryspoplawski, @dimakuv, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/721#-N7gcwrS7VBPbUetdkIG:-N7uWShg6jw2jRvjR-_K:b-eee2xq) (no related file):*
@aneessahib Please look at your messages before posting them, your responses are appended to quotes and I have no idea what is what now.

> In this PR, Gramine take a conservative/strict stance of terminating the process in the event of a failed secret provisioning flow.

And nobody objected this change. The problem is that most of the PR is about completely different thing, which is completely unrelated and it's unclear if we even need it.

> but the premise there again is that a secret cannot be anything other a wrap key - which is quite restrictive.

No. Please read the example carefully before you modify them. If it doesn't help then grep for `SECRET_STRING`

> I have another suggestion if Borys dislikes the change with ATTESTATION_SUCCESS_STRING that much. 

It's not that I dislike it - it makes no sense to me.

> So maybe instead of sending ATTESTATION_SUCCESS_STRING, we can have a hard-coded dummy key (like all-zeros) and send it, instead of that string? This way the flow would be less surprising -- we will always send some secret.

How about we just don't send the key if there is no key?

___


<!-- Sent from Reviewable.io -->

2022-07-26 13:22 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/721)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @boryspoplawski, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/721#-N7gcwrS7VBPbUetdkIG:-N7ueulp6w5tgtFY7oQj:b-7hjcam) (no related file):*
> How about we just don't send the key if there is no key?

You mean, why can't the server *not* reply to the client (SGX enclave) at all? But then the SGX enclave will get stuck, waiting for some reply from the server (that's how Secret Prov library works). So there must be some reply/ack from the server.

___


<!-- Sent from Reviewable.io -->

2022-07-26 14:05 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/721)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @boryspoplawski, @dimakuv, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/721#-N7gcwrS7VBPbUetdkIG:-N7uo6JT9f5_1YbnsDNA:bide9n3) (no related file):*
No, I mean if there is no key, then don't send one. This server sends two secrets.

> But then the SGX enclave will get stuck, waiting for some reply from the server (that's how Secret Prov library works)

So it makes no sense not to send any key if the client expects it?

___


<!-- Sent from Reviewable.io -->

2022-07-26 15:37 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/721)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @boryspoplawski, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/721#-N7gcwrS7VBPbUetdkIG:-N7v8gAD-DvW5LegKBaF:b-9vozaj) (no related file):*
> So it makes no sense not to send any key if the client expects it?

Which of the *three* clients? We have one server example that serves three different client examples, see the example: https://github.com/gramineproject/gramine/tree/master/CI-Examples/ra-tls-secret-prov

One client just prints the secret (doesn't care if it's a key or not). Another client uses the secret as the Encrypted Files key. Yet another client gets two secrets and also simply prints them (doesn't care if these are keys or not).

___


<!-- Sent from Reviewable.io -->

2022-07-26 18:29 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/721)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @boryspoplawski, @dimakuv, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/721#-N7gcwrS7VBPbUetdkIG:-N7vlJ35CUxcjbMP9VYO:bhu952h) (no related file):*
> But then the SGX enclave will get stuck, waiting for some reply from the server (that's how Secret Prov library works). 

This client.

___


<!-- Sent from Reviewable.io -->

2022-07-27 06:20 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/721)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @boryspoplawski, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/721#-N7gcwrS7VBPbUetdkIG:-N7yIiR_-pHltA8zAC8F:b-ciaulm) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

> But then the SGX enclave will get stuck, waiting for some reply from the server (that's how Secret Prov library works). 

This client.
</blockquote></details>

I'm getting confused. What are we talking about?

Maybe you're referring to the fact that the SecretProv server already sends a secret `SECRET_STRING` (currently only as the second string if requested by the client), and this PR adds a kinda new secret `ATTESTATION_SUCCESS_STRING`. So your proposal is to just send already-existing `SECRET_STRING` if there is no `argv[1]` in the server process?

___


<!-- Sent from Reviewable.io -->

2022-07-27 10:23 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/721)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @boryspoplawski, @dimakuv, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/721#-N7gcwrS7VBPbUetdkIG:-N7z9Z-tEVRERHZ18rpM:bepftv5) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I'm getting confused. What are we talking about?

Maybe you're referring to the fact that the SecretProv server already sends a secret `SECRET_STRING` (currently only as the second string if requested by the client), and this PR adds a kinda new secret `ATTESTATION_SUCCESS_STRING`. So your proposal is to just send already-existing `SECRET_STRING` if there is no `argv[1]` in the server process?
</blockquote></details>

That was the initial idea.

Well, my minimal requirement would be always sending stuff of the same type, e.g. message 1 is always a C string, 64B blob of data, hash, key, whatever. But no mixups, no sometimes a key, sometimes a string.

Another idea is not to use one server for different clients, unless they all expect the same kind of secrets. Do we really need 3 examples? What's wrong with one sending a key and then some arbitrary data blob/string?

___


<!-- Sent from Reviewable.io -->

2022-07-27 11:27 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/721)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @boryspoplawski, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/721#-N7gcwrS7VBPbUetdkIG:-N7zP3aaDlDhGOtL-YnK:b-drgmt1) (no related file):*
> Well, my minimal requirement would be always sending stuff of the same type, e.g. message 1 is always a C string, 64B blob of data, hash, key, whatever. But no mixups, no sometimes a key, sometimes a string.

In this case, I vote for a dummy key to be sent if `argv[1] == NULL`. @aneessahib Would that suit your needs?

> Do we really need 3 examples? What's wrong with one sending a key and then some arbitrary data blob/string?

I'd say yes, we need 3 examples (3 clients). They showcase three different, incompatible usages of Secret Prov lib.

___


<!-- Sent from Reviewable.io -->

2022-07-27 12:50 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/721)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @boryspoplawski, @dimakuv, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/721#-N7gcwrS7VBPbUetdkIG:-N7zh8At7NWjx3Zo7nnl:b-nn5s74) (no related file):*
> In this case, I vote for a dummy key to be sent if argv[1] == NULL. @aneessahib Would that suit your needs?

Yes this makes sense - will make the changes soon.

___


<!-- Sent from Reviewable.io -->

2022-07-28 09:25 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/721)* status: 1 of 3 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @boryspoplawski, @dimakuv, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/721#-N7gcwrS7VBPbUetdkIG:-N836ipoAGMuTajQVjVk:b-svypqy) (no related file):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

> In this case, I vote for a dummy key to be sent if argv[1] == NULL. @aneessahib Would that suit your needs?

Yes this makes sense - will make the changes soon.
</blockquote></details>

Done. Updated README as well.

___


<!-- Sent from Reviewable.io -->

2022-07-28 11:47 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/721)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @boryspoplawski, and @mkow)

___
*[`CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c` line 151 at r7](https://reviewable.io/reviews/gramineproject/gramine/721#-N83cJk71kGTRYb3_Bwo:-N83cJk71kGTRYb3_Bwp:b54h4n3) ([raw file](https://github.com/gramineproject/gramine/blob/9621fb12d73823c4d6c610533f4e141d7d235ff2/CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c#L151)):*
> ```C
>         for (size_t i = 0; i < bytes_read; i++)
>             sprintf(&g_secret_string[i * 2], "%02x", ptr[i]);
> ```

Please remove an empty line.
___
*[`pal/src/host/linux-sgx/tools/ra-tls/secret_prov_attest.c` line 315 at r7](https://reviewable.io/reviews/gramineproject/gramine/721#-N83cNAO4IXs4K_pt90q:-N83cNAP1W-xMMKhwWJh:b-wj5xwl) ([raw file](https://github.com/gramineproject/gramine/blob/9621fb12d73823c4d6c610533f4e141d7d235ff2/pal/src/host/linux-sgx/tools/ra-tls/secret_prov_attest.c#L315)):*
> ```C
>             ERROR("Secret provisioning failed, terminating the whole process\n");
>             exit(1);
>         }
> ```

This whole change should be reverted now.


<!-- Sent from Reviewable.io -->

2022-07-28 11:54 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/721)* status: 1 of 3 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @boryspoplawski, @dimakuv, and @mkow)

___
*[`CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c` line 151 at r7](https://reviewable.io/reviews/gramineproject/gramine/721#-N83cJk71kGTRYb3_Bwo:-N83e1rV52mWVSFvYfLo:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9621fb12d73823c4d6c610533f4e141d7d235ff2/CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c#L151)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please remove an empty line.
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/tools/ra-tls/secret_prov_attest.c` line 313 at r4](https://reviewable.io/reviews/gramineproject/gramine/721#-N7gLC-ADIGR5LCiK8Wr:-N83e6Lq7porFQwsMvqV:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/1ae61c06ed853dddc67341f2c88a23102d725da0/pal/src/host/linux-sgx/tools/ra-tls/secret_prov_attest.c#L313)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

But how can the app handle this error gracefully?

Don't forget that we end up in this code snippet only if:
- The enclave developer didn't want to modify the app in the first place (at all),
- therefore the enclave developer added `loader.env.SECRET_PROVISION_CONSTRUCTOR = "true"`,
- most probably this secret is the key for file encryption (`loader.env.SECRET_PROVISION_SET_KEY = "default"`)

So, the enclave developer wants the enclave to get the secret without the app informed about it. It is explicitly specified in the manifest file. So I think there is no other way but to kill the process if Secret Provisioning failed for some reason.
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/tools/ra-tls/secret_prov_attest.c` line 315 at r7](https://reviewable.io/reviews/gramineproject/gramine/721#-N83cNAO4IXs4K_pt90q:-N83e3TM1HVBiDLm6L8e:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9621fb12d73823c4d6c610533f4e141d7d235ff2/pal/src/host/linux-sgx/tools/ra-tls/secret_prov_attest.c#L315)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This whole change should be reverted now.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-28 13:14 UTC, dimakuv submitted a review, later dismissed
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/721)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @boryspoplawski, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/721#-N83wO7H11gmIP1ip0ef:-N83wO7H11gmIP1ip0eg:bnhu7nb) (no related file):*
The PR looks fine to me now. I'll fix the commit message during the rebase.

___


<!-- Sent from Reviewable.io -->

2022-07-28 14:36 UTC, mkow requested changes
> Reviewed 1 of 2 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/721)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @aneessahib and @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/721#-N7gcwrS7VBPbUetdkIG:-N84CMMX9AbHlbE37k_N:b-21op9h) (no related file):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

Done. Updated README as well.
</blockquote></details>

Sorry, but I still don't get the overall purpose of this PR. This is a simple example which tries to showcase our APIs, but it's unusable for production (it has a lot of things hardcoded, etc.). And you're changing one tiny part to optionally not provision any secrets (or rather a dummy key), what's even the usecase for this?

___
___
*[`CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c` line 20 at r8](https://reviewable.io/reviews/gramineproject/gramine/721#-N84BqUV3_CKD3YbwOSx:-N84BqUW0fd94KXS2V1L:be7bnc) ([raw file](https://github.com/gramineproject/gramine/blob/7697d68b1b46fdd3441c6dc2521fc577999d5e68/CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c#L20)):*
> ```C
> #define EXPECTED_STRING "MORE"
> #define SECRET_STRING "42" /* answer to ultimate question of life, universe, and everything */
> #define DUMMY_KEY   "FEDCBA9876543210FEDCBA9876543210"
> ```

Why three spaces here? It's not even aligned to anything ;)


<!-- Sent from Reviewable.io -->

2022-07-28 14:58 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/721)* status: 2 of 3 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @boryspoplawski, @dimakuv, and @mkow)

___
*[`CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c` line 20 at r8](https://reviewable.io/reviews/gramineproject/gramine/721#-N84BqUV3_CKD3YbwOSx:-N84JA6u6R5KwnU3333O:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/7697d68b1b46fdd3441c6dc2521fc577999d5e68/CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c#L20)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why three spaces here? It's not even aligned to anything ;)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-29 07:09 UTC, dimakuv reviewed
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/721)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @boryspoplawski, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/721#-N7gcwrS7VBPbUetdkIG:-N87kNaL6d0HPTYsd4E5:b-74nihm) (no related file):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

So, in the current state, the RA-TLS verifier exits if there's no wrap key argument passed to it. We will need one library to handle both secret provisioning use case, as well as simple attestation pass use case (means there are no keys to provision, but yet - applications would want to know if attestation has passed atleast). This is precisely why we had the "ATTESTATION_SUCCESS" string set as default in the initial versions of this PR. Now - after several feedbacks - it was decided that the default secret too has to be a key for consistency.  
</blockquote></details>

@mkow I think this change is generally reasonable. In our `ra-tls-secret-prov` example, we have one server (verifier of the SGX enclave and releaser of the secrets) and three different kinds of clients (three SGX enclaves, each showcases a different possible flow). But only one of the clients actually needs a real Encrypted Files key to be provisioned (this client is `secret_prov_pf_client`).

Consider what we force users to do in the README to run this example:
```bash
make files/input.txt
./secret_prov_server_epid &
# test minimal client
gramine-sgx ./secret_prov_min_client
# test feature-rich client
gramine-sgx ./secret_prov_client
# test encrypted-files client
gramine-sgx ./secret_prov_pf_client
```

In the current code, without this PR, it is impossible for users to do this:
```bash
rm files/wrap-key
./secret_prov_server_epid &  # this fails
gramine-sgx ./secret_prov_min_client
```

With this PR, the sanity is restored a bit:
- We don't need to rely on `files/wrap-key` to test non-pf clients:

```bash
rm files/wrap-key
./secret_prov_server_epid &  # this works fine
gramine-sgx ./secret_prov_min_client
```

- When we want to test the pf client, we do the logical thing:

```bash
make files/input.txt  # uses files/wrap-key
./secret_prov_server_epid files/wrap-key &
gramine-sgx ./secret_prov_pf_client
```

So to me, this PR doesn't harm anything and makes it slightly more logical.

___
___
*[`CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c` line 111 at r4](https://reviewable.io/reviews/gramineproject/gramine/721#-N7gLNb-0Vx70Ibsq9Uk:-N87jyaLAwtEmbHODiXe:b-ab4351) ([raw file](https://github.com/gramineproject/gramine/blob/1ae61c06ed853dddc67341f2c88a23102d725da0/CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c#L111)):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

Ahh. So this is to prevent lazy users from abusing this macro by hardcoding keys!. Again - do i need to message this in a different way - like "ATTESTATION_SUCCESS_STRING should not be a key"
</blockquote></details>

Btw, this comment is stale now. We don't have `ATTESTATION_SUCESS_STRING` anymore, but `DUMMY_KEY` instead.


<!-- Sent from Reviewable.io -->

2022-08-04 13:23 UTC, mkow requested changes
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/721)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib and @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/721#-N7gcwrS7VBPbUetdkIG:-N8czpX738xxacbiBryV:b7kqvza) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@mkow I think this change is generally reasonable. In our `ra-tls-secret-prov` example, we have one server (verifier of the SGX enclave and releaser of the secrets) and three different kinds of clients (three SGX enclaves, each showcases a different possible flow). But only one of the clients actually needs a real Encrypted Files key to be provisioned (this client is `secret_prov_pf_client`).

Consider what we force users to do in the README to run this example:
```bash
make files/input.txt
./secret_prov_server_epid &
# test minimal client
gramine-sgx ./secret_prov_min_client
# test feature-rich client
gramine-sgx ./secret_prov_client
# test encrypted-files client
gramine-sgx ./secret_prov_pf_client
```

In the current code, without this PR, it is impossible for users to do this:
```bash
rm files/wrap-key
./secret_prov_server_epid &  # this fails
gramine-sgx ./secret_prov_min_client
```

With this PR, the sanity is restored a bit:
- We don't need to rely on `files/wrap-key` to test non-pf clients:

```bash
rm files/wrap-key
./secret_prov_server_epid &  # this works fine
gramine-sgx ./secret_prov_min_client
```

- When we want to test the pf client, we do the logical thing:

```bash
make files/input.txt  # uses files/wrap-key
./secret_prov_server_epid files/wrap-key &
gramine-sgx ./secret_prov_pf_client
```

So to me, this PR doesn't harm anything and makes it slightly more logical.
</blockquote></details>

Ok, now I understand the idea, thanks @dimakuv for a good explanation.

___
___
*[`CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c` line 20 at r9](https://reviewable.io/reviews/gramineproject/gramine/721#-N8d-s-2-l3Grn7VNlCB:-N8d-s-2-l3Grn7VNlCC:b-70ag2x) ([raw file](https://github.com/gramineproject/gramine/blob/d0efc0221289f14c7d5bfc39b941d517e2ce55d6/CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c#L20)):*
> ```C
> #define EXPECTED_STRING "MORE"
> #define SECRET_STRING "42" /* answer to ultimate question of life, universe, and everything */
> #define DUMMY_KEY "FEDCBA9876543210FEDCBA9876543210"
> ```

I think it would be safer if we returned a _random_ key in this case, not a hardcoded one. This way there's no risk that someone misuses the example (i.e. accidentally using the hardcoded key in production).
CC: @boryspoplawski


<!-- Sent from Reviewable.io -->

2022-08-04 14:12 UTC, boryspoplawski approved these changes
> Reviewed 1 of 2 files at r7, 1 of 2 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/721)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @aneessahib and @mkow)

___
*[`CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c` line 20 at r9](https://reviewable.io/reviews/gramineproject/gramine/721#-N8d-s-2-l3Grn7VNlCB:-N8dAZYD7BJXcbd2rhib:b-xfrrbm) ([raw file](https://github.com/gramineproject/gramine/blob/d0efc0221289f14c7d5bfc39b941d517e2ce55d6/CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c#L20)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I think it would be safer if we returned a _random_ key in this case, not a hardcoded one. This way there's no risk that someone misuses the example (i.e. accidentally using the hardcoded key in production).
CC: @boryspoplawski
</blockquote></details>

Idk, to me this example is still weird. I would say we need 3 separate examples, or one with 3 different run modes, which would serve different things based on the mode it's run in. Then we would have 1-1 correspondence between a client and mode and no confusions.
But I'm not blocking, since everybody seems to be fine with the current approach.
Static vs random key: yeah, I think random would be less error prone.


<!-- Sent from Reviewable.io -->

2022-08-05 09:26 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/721)* status: 1 of 3 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @boryspoplawski, @dimakuv, and @mkow)

___
*[`CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c` line 20 at r9](https://reviewable.io/reviews/gramineproject/gramine/721#-N8d-s-2-l3Grn7VNlCB:-N8hJc2s5z4EUe5QrUX0:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d0efc0221289f14c7d5bfc39b941d517e2ce55d6/CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c#L20)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@boryspoplawski Yes, I was also thinking about three different examples... Maybe in some follow up PR. Because I agree, the current server example is "weird", cramming 3 different usages into one binary.

@aneessahib Could you use a random key instead of the `DUMMY_KEY`? I think the easiest is to use https://man7.org/linux/man-pages/man2/getrandom.2.html.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-05 09:52 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/721)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib and @mkow)

___
*[`CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c` line 116 at r10](https://reviewable.io/reviews/gramineproject/gramine/721#-N8hP8xrAKA9djWEEPmE:-N8hP8xrAKA9djWEEPmF:b-2173yy) ([raw file](https://github.com/gramineproject/gramine/blob/519e266b374a543c7e742f1d09e7edcb5432a410/CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c#L116)):*
> ```C
>             return 1;
>         }
>         bytes_read = size;
> ```

No need to use the `size` temporary variable. Just directly use `bytes_read` and compare against `WRAP_KEY_SIZE` for sanity:
```
        bytes_read = getrandom(buf, WRAP_KEY_SIZE, 0);
        if (bytes_read != WRAP_KEY_SIZE) {
            fprintf(stderr, "[error] cannot generate a random key");
            return 1;
        }
```

Also, I see no need in `GRND_NONBLOCK` flag.
___
*[`CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c` line 150 at r10](https://reviewable.io/reviews/gramineproject/gramine/721#-N8hOy9p-2GFAIM6SBre:-N8hOy9p-2GFAIM6SBrf:b-23tiju) ([raw file](https://github.com/gramineproject/gramine/blob/519e266b374a543c7e742f1d09e7edcb5432a410/CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c#L150)):*
> ```C
>             return 1;
>         }
>     }
> ```

Please add an empty line after this.


<!-- Sent from Reviewable.io -->

2022-08-05 10:38 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/721)* status: 2 of 3 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @dimakuv, and @mkow)

___
*[`CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c` line 116 at r10](https://reviewable.io/reviews/gramineproject/gramine/721#-N8hP8xrAKA9djWEEPmE:-N8h_TVT565WQ7sj5IkN:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/519e266b374a543c7e742f1d09e7edcb5432a410/CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c#L116)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

No need to use the `size` temporary variable. Just directly use `bytes_read` and compare against `WRAP_KEY_SIZE` for sanity:
```
        bytes_read = getrandom(buf, WRAP_KEY_SIZE, 0);
        if (bytes_read != WRAP_KEY_SIZE) {
            fprintf(stderr, "[error] cannot generate a random key");
            return 1;
        }
```

Also, I see no need in `GRND_NONBLOCK` flag.
</blockquote></details>

Done.
___
*[`CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c` line 150 at r10](https://reviewable.io/reviews/gramineproject/gramine/721#-N8hOy9p-2GFAIM6SBre:-N8h_UjD0AaAQAlm84xy:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/519e266b374a543c7e742f1d09e7edcb5432a410/CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c#L150)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add an empty line after this.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-05 10:54 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/721)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @aneessahib and @mkow)



<!-- Sent from Reviewable.io -->

2022-08-05 10:54 UTC, dimakuv commented
Jenkins, test this plesae

2022-08-05 10:54 UTC, dimakuv commented
Jenkins, test this please

2022-08-08 22:19 UTC, mkow requested changes
> Reviewed 1 of 2 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/721)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @aneessahib)

___
*[`CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c` line 111 at r11](https://reviewable.io/reviews/gramineproject/gramine/721#-N8zWrR2BtUBsq_9YOHq:-N8zWrR2BtUBsq_9YOHr:b-erx5uo) ([raw file](https://github.com/gramineproject/gramine/blob/50c5f1d50a51d9cf12c2e5ea7c4d2e138d0c39ba/CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c#L111)):*
> ```C
>     if (argc < 2) {
>         puts("--- No master key is provided, proceeding with a random key ---");
>         ssize_t bytes_read = getrandom(buf, WRAP_KEY_SIZE, 0);
> ```

You made a potential security bug around here. Please read `getrandom()` manual entry carefully.


<!-- Sent from Reviewable.io -->

2022-08-09 03:12 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/721)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @aneessahib)

___
*[`CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c` line 116 at r10](https://reviewable.io/reviews/gramineproject/gramine/721#-N8hP8xrAKA9djWEEPmE:-N9-_UDUCC3KKdUPn8tS:b-2ptlfo) ([raw file](https://github.com/gramineproject/gramine/blob/519e266b374a543c7e742f1d09e7edcb5432a410/CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c#L116)):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

The call would block forever if sufficient entropy is not achieved?


<!-- Sent from Reviewable.io -->

2022-08-09 03:13 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/721)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @aneessahib and @mkow)

___
*[`CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c` line 111 at r11](https://reviewable.io/reviews/gramineproject/gramine/721#-N8zWrR2BtUBsq_9YOHq:-N9-_s3F1Jh432dgKhHC:b-d7deia) ([raw file](https://github.com/gramineproject/gramine/blob/50c5f1d50a51d9cf12c2e5ea7c4d2e138d0c39ba/CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c#L111)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

You made a potential security bug around here. Please read `getrandom()` manual entry carefully.
</blockquote></details>

The call would block forever if sufficient entropy is not achieved?


<!-- Sent from Reviewable.io -->

2022-08-09 23:15 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/721)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @aneessahib)

___
*[`CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c` line 111 at r11](https://reviewable.io/reviews/gramineproject/gramine/721#-N8zWrR2BtUBsq_9YOHq:-N93skfL3uu4RpJzS9an:b-rtudcu) ([raw file](https://github.com/gramineproject/gramine/blob/50c5f1d50a51d9cf12c2e5ea7c4d2e138d0c39ba/CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c#L111)):*
> The call would block forever if sufficient entropy is not achieved?

How's that a security bug?

```
RETURN VALUE
       On success, getrandom() returns the number of bytes that were copied to the buffer buf.  This  may  be  less
       than  the number of bytes requested via buflen if either GRND_RANDOM was specified in flags and insufficient
       entropy was present in the random source or the system call was interrupted by a signal.

       On error, -1 is returned, and errno is set appropriately.
```


<!-- Sent from Reviewable.io -->

2022-08-10 11:45 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/721)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @aneessahib and @mkow)

___
*[`CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c` line 111 at r11](https://reviewable.io/reviews/gramineproject/gramine/721#-N8zWrR2BtUBsq_9YOHq:-N94cRmT8vA1ghMrsG_5:b-3pi4eu) ([raw file](https://github.com/gramineproject/gramine/blob/50c5f1d50a51d9cf12c2e5ea7c4d2e138d0c39ba/CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c#L111)):*
Yes I had read this one. This shouldn't apply to this specific example since we're only requesting 16B. Moreover, I'm going with defaults here (not specifying `GRND_RANDOM` flag).

``   By default, getrandom() draws entropy from the urandom source
       (i.e., the same source as the /dev/urandom device).  This
       behavior can be changed via the flags argument.

       If the urandom source has been initialized, reads of up to 256
       bytes will always return as many bytes as requested and will not
       be interrupted by signals.  No such guarantees apply for larger
       buffer sizes.  For example, if the call is interrupted by a
       signal handler, it may return a partially filled buffer, or fail
       with the error EINTR.``

And I have an assert statement too `assert(bytes_read == WRAP_KEY_SIZE);` . This is just incase if people are going to modify our example to use bigger keys, and upto them to handle partial writes. Sufficient?

>How's that a security bug?
Well, something like a DoS attack where someone manages to keep the system busy with EINTR etc. I thought we were covered otherwise based on the manpage.


<!-- Sent from Reviewable.io -->

2022-08-10 12:31 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/721)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @aneessahib)

___
*[`CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c` line 111 at r11](https://reviewable.io/reviews/gramineproject/gramine/721#-N8zWrR2BtUBsq_9YOHq:-N96hihJD1jBzJsqd0zd:b-xm8xc0) ([raw file](https://github.com/gramineproject/gramine/blob/50c5f1d50a51d9cf12c2e5ea7c4d2e138d0c39ba/CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c#L111)):*
I'm not sure what does "If the urandom source has been initialized" mean precisely, so I prefer to not rely on this and actually check the returned size. And the additional argument you yourself gave - people may modify the code and it's almost guaranteed that they won't be aware of this magic threshold of 256 bytes when doing so.

> And I have an assert statement too `assert(bytes_read == WRAP_KEY_SIZE);`

Asserts are not compiled in release builds, so they are not suitable for security checks.


<!-- Sent from Reviewable.io -->

2022-08-10 13:14 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/721)* status: 2 of 3 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @dimakuv, and @mkow)

___
*[`CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c` line 111 at r11](https://reviewable.io/reviews/gramineproject/gramine/721#-N8zWrR2BtUBsq_9YOHq:-N96sZARAQHyL8Z50u1h:b-q3u6a0) ([raw file](https://github.com/gramineproject/gramine/blob/50c5f1d50a51d9cf12c2e5ea7c4d2e138d0c39ba/CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c#L111)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'm not sure what does "If the urandom source has been initialized" mean precisely, so I prefer to not rely on this and actually check the returned size. And the additional argument you yourself gave - people may modify the code and it's almost guaranteed that they won't be aware of this magic threshold of 256 bytes when doing so.

> And I have an assert statement too `assert(bytes_read == WRAP_KEY_SIZE);`

Asserts are not compiled in release builds, so they are not suitable for security checks.
</blockquote></details>

Done. I'm now thinking if it should be `if (bytes_read != WRAP_KEY_SIZE)`


<!-- Sent from Reviewable.io -->

2022-08-10 13:20 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/721)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @aneessahib)



<!-- Sent from Reviewable.io -->

2022-08-12 12:17 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/721)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/721#-N6735z2-IxB8iq-8np4):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Needs to be modified for final merge. I'll come up with some message.
</blockquote></details>

Done + stole @dimakuv's explanation, please ACK that you're ok with this :)


<!-- Sent from Reviewable.io -->

2022-08-12 12:17 UTC, mkow commented
Jenkins, retest this please

2022-08-12 12:18 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/721)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2022-08-12 12:18 UTC, mkow commented
Jenkins, retest this please

2022-08-12 12:28 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/721)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/721#-N6735z2-IxB8iq-8np4):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Done + stole @dimakuv's explanation, please ACK that you're ok with this :)
</blockquote></details>

I'm acknowledging that I'm fine with the new commit message.


<!-- Sent from Reviewable.io -->

2022-08-12 13:51 UTC, boryspoplawski requested changes
> Reviewed 1 of 2 files at r10, 1 of 1 files at r12, 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/721)* status: all files reviewed, 1 unresolved discussion (waiting on @aneessahib)

___
*[`CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c` line 111 at r14](https://reviewable.io/reviews/gramineproject/gramine/721#-N9HJcik-XKFlbBj18k5:-N9HJcil4VYiT1NdJC1S:b-t4uhr5) ([raw file](https://github.com/gramineproject/gramine/blob/803a518cc3f6d033a187ba888126fa50a552811c/CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c#L111)):*
> ```C
>     if (argc < 2) {
>         puts("--- No master key is provided, proceeding with a random key ---");
>         ssize_t bytes_read = getrandom(buf, WRAP_KEY_SIZE, 0);
> ```

You redefine the variable, which you need values out of this block



_Code quote:_
```C
ssize_t 
```


<!-- Sent from Reviewable.io -->

2022-08-12 13:57 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/721)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[`CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c` line 111 at r14](https://reviewable.io/reviews/gramineproject/gramine/721#-N9HJcik-XKFlbBj18k5:-N9HKzZW1NHT3Fwwc1kW:bt1uzp) ([raw file](https://github.com/gramineproject/gramine/blob/803a518cc3f6d033a187ba888126fa50a552811c/CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c#L111)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

You redefine the variable, which you need values out of this block
</blockquote></details>

Ehhh. I'll take over this PR and fix this.


<!-- Sent from Reviewable.io -->

2022-08-12 14:08 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/721)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

___
*[`CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c` line 111 at r14](https://reviewable.io/reviews/gramineproject/gramine/721#-N9HJcik-XKFlbBj18k5:-N9HNZfF5HwqgN4yposN:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/803a518cc3f6d033a187ba888126fa50a552811c/CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c#L111)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Ehhh. I'll take over this PR and fix this.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-12 14:08 UTC, mkow commented
Jenkins, retest this please

2022-08-12 14:52 UTC, boryspoplawski approved these changes
> Reviewed 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/721)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2022-08-12 17:49 UTC, mkow commented
Jenkins, retest this please

2022-08-12 18:00 UTC, mkow commented
Jenkins, retest this please

2022-08-12 18:58 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/721)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2022-08-12 19:18 UTC, boryspoplawski approved these changes
> Reviewed 1 of 1 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/721)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2022-08-15 17:37 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/721)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-08-15 21:55 UTC, merged