Support running scripts as the entrypoint
gramineproject/gramine pull request #722
Opened 2022-07-04 13:12 UTC by aneessahib

This will enable users to run scripts in Gramine (as opposed to manually providing a ELF entrypoint - this can be quite an inconvenience to users). This will also minimize the need to create wrapper docker files for entrypoint manipulation while using GSC.

2022-07-05 09:35 UTC, dimakuv requested changes
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/722)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @aneessahib)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/722#-N6CdQaGDU2vhcYBfAlM:-N6CdQaH-VvJieAPaHOa:bzalxg2) (no related file):*
This is a new feature, and it needs at least one (preferrably 2 or 3) different tests, with manifests containing`libos.entrypoint = "script.sh"`.

___
___
*[`libos/include/libos_process.h` line 73 at r1](https://reviewable.io/reviews/gramineproject/gramine/722#-N6CahZMBbwV95bF4t6f:-N6CahZMBbwV95bF4t6g:btsvxba) ([raw file](https://github.com/gramineproject/gramine/blob/cec58448e6795614f536a0f2189c9a46a5842c2a/libos/include/libos_process.h#L73)):*
> ```objc
> 
> int init_process(void);
> int init_process_args(int argc, const char** argv);
> ```

I suggest to rename to `init_process_cmdline()`, because this is the only thing that this function does -- it initializes `/proc/self/cmdline` based on arguments.
___
*[`libos/src/libos_init.c` line 431 at r1](https://reviewable.io/reviews/gramineproject/gramine/722#-N6CaCIyAtKpcstTV9il:-N6CaCIyAtKpcstTV9im:bcrefpc) ([raw file](https://github.com/gramineproject/gramine/blob/cec58448e6795614f536a0f2189c9a46a5842c2a/libos/src/libos_init.c#L431)):*
> ```C
>         log_error("libos_init: failed to load exec: %d", ret);
>         PalProcessExit(1);
>     }
> ```

You should wrap it in `RUN_INIT`, smth like this:
```
    struct libos_handle* exec = NULL;
    char** new_argv = NULL;
    RUN_INIT(load_and_check_exec, argv[0], argv, &exec, &new_argv);
```

Actually, can you create a new helper function `init_process_args()` (note that the old `init_process_args()` should be renamed to `init_process_cmdline()`, as per my other comment) and put this call to `load_and_check_exec()` in that new function? This way it will be much cleaner and easy to understand.

Also, you have a dummy `exec` handle which should be `put_handle()` at the end of that new function, otherwise there will be a memory leak. I would also rename the variable to `dummy_exec`.
___
*[`libos/src/bookkeep/libos_handle.c` line 114 at r1](https://reviewable.io/reviews/gramineproject/gramine/722#-N6CeSWE50CxuqMpqDTa:-N6CeSWE50CxuqMpqDTb:b2yjrnn) ([raw file](https://github.com/gramineproject/gramine/blob/cec58448e6795614f536a0f2189c9a46a5842c2a/libos/src/bookkeep/libos_handle.c#L114)):*
> ```C
>     }
> 
>     struct libos_handle* exec_handle = NULL;
> ```

Please add a comment before this snippet:
```
/* entrypoint may be a shebang script instead of the ELF binary,  get the actual ELF binary name in this case */
```
___
*[`libos/src/bookkeep/libos_handle.c` line 115 at r1](https://reviewable.io/reviews/gramineproject/gramine/722#-N6CfMRo6HWighXR6NST:-N6CfMRo6HWighXR6NSU:bfblxkn) ([raw file](https://github.com/gramineproject/gramine/blob/cec58448e6795614f536a0f2189c9a46a5842c2a/libos/src/bookkeep/libos_handle.c#L115)):*
> ```C
> 
>     struct libos_handle* exec_handle = NULL;
>     char** new_argv = NULL;
> ```

`new_argv` -> `dummy_new_argv` (you're not using these arguments)
___
*[`libos/src/bookkeep/libos_handle.c` line 116 at r1](https://reviewable.io/reviews/gramineproject/gramine/722#-N6CfR9-0FlDCjkp6Rhu:-N6CfR9-0FlDCjkp6Rhv:b9di1ix) ([raw file](https://github.com/gramineproject/gramine/blob/cec58448e6795614f536a0f2189c9a46a5842c2a/libos/src/bookkeep/libos_handle.c#L116)):*
> ```C
>     struct libos_handle* exec_handle = NULL;
>     char** new_argv = NULL;
>     const char* argv[] = {exec_path, NULL};
> ```

`argv` -> `dummy_argv` (you're not using these arguments)
___
*[`libos/src/bookkeep/libos_handle.c` line 117 at r1](https://reviewable.io/reviews/gramineproject/gramine/722#-N6CfV6HDLZV2ERNK9RY:-N6CfV6I626ZINuvBf8T:b-xsg6fx) ([raw file](https://github.com/gramineproject/gramine/blob/cec58448e6795614f536a0f2189c9a46a5842c2a/libos/src/bookkeep/libos_handle.c#L117)):*
> ```C
>     char** new_argv = NULL;
>     const char* argv[] = {exec_path, NULL};
>     ret = load_and_check_exec(argv[0], argv, &exec_handle, &new_argv);
> ```

`argv[0]` -> `exec_path` (semantically equivalent, but easier to read)
___
*[`libos/src/bookkeep/libos_handle.c` line 122 at r1](https://reviewable.io/reviews/gramineproject/gramine/722#-N6Cg-scDbDe7vEEzh7a:-N6Cg-scDbDe7vEEzh7b:b-13fz98) ([raw file](https://github.com/gramineproject/gramine/blob/cec58448e6795614f536a0f2189c9a46a5842c2a/libos/src/bookkeep/libos_handle.c#L122)):*
> ```C
>     }
> 
>     hdl = get_new_handle();
> ```

This is already done inside `load_and_check_exec()`. The created-and-opened handle is returned by that function in `exec_handle`, so you could just use that one.
___
*[`libos/src/bookkeep/libos_handle.c` line 129 at r1](https://reviewable.io/reviews/gramineproject/gramine/722#-N6Cg7NB4M0q9B1FV9EG:-N6Cg7NB4M0q9B1FV9EH:b6fh2ij) ([raw file](https://github.com/gramineproject/gramine/blob/cec58448e6795614f536a0f2189c9a46a5842c2a/libos/src/bookkeep/libos_handle.c#L129)):*
> ```C
> 
>     const char* new_exec_path = new_argv[0];
>     ret = open_executable(hdl, new_exec_path);
> ```

This is already done inside `load_and_check_exec()`. The created-and-opened handle is returned by that function in `exec_handle`, so you could just use that one.

So what I propose is to remove this snippet with `get_new_handle()` and `open_executable()` and simply have:
```
    char** dummy_new_argv = NULL;
    const char* dummy_argv[] = {exec_path, NULL};
    ret = load_and_check_exec(exec_path, dummy_argv, &hdl, &dummy_new_argv);
    if (ret < 0) {
        log_error("Error opening %s: %d", exec_path, ret);
        goto out;
    }

    free(*dummy_new_argv);
    free(dummy_new_argv);
```
___
*[`libos/src/bookkeep/libos_process.c` line 66 at r1](https://reviewable.io/reviews/gramineproject/gramine/722#-N6C_TN-754Q2EmrpZF5:-N6C_TN-754Q2EmrpZF6:b6sfg8g) ([raw file](https://github.com/gramineproject/gramine/blob/cec58448e6795614f536a0f2189c9a46a5842c2a/libos/src/bookkeep/libos_process.c#L66)):*
> ```C
>      * They are not separated by space, but by NUL instead. So, it is essential to maintain the
>      * cmdline_size also as a member here. */
> ```

Please remove this empty line.


<!-- Sent from Reviewable.io -->

2022-07-12 17:04 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/722)* status: 0 of 6 files reviewed, 10 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib and @dimakuv)

___
*[`libos/include/libos_process.h` line 73 at r1](https://reviewable.io/reviews/gramineproject/gramine/722#-N6CahZMBbwV95bF4t6f:-N6nLa2UCD6gzqeE-CHB:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/cec58448e6795614f536a0f2189c9a46a5842c2a/libos/include/libos_process.h#L73)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I suggest to rename to `init_process_cmdline()`, because this is the only thing that this function does -- it initializes `/proc/self/cmdline` based on arguments.
</blockquote></details>

Done.
___
*[`libos/src/libos_init.c` line 431 at r1](https://reviewable.io/reviews/gramineproject/gramine/722#-N6CaCIyAtKpcstTV9il:-N6nLdXrAIys5BO2gIHi:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/cec58448e6795614f536a0f2189c9a46a5842c2a/libos/src/libos_init.c#L431)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You should wrap it in `RUN_INIT`, smth like this:
```
    struct libos_handle* exec = NULL;
    char** new_argv = NULL;
    RUN_INIT(load_and_check_exec, argv[0], argv, &exec, &new_argv);
```

Actually, can you create a new helper function `init_process_args()` (note that the old `init_process_args()` should be renamed to `init_process_cmdline()`, as per my other comment) and put this call to `load_and_check_exec()` in that new function? This way it will be much cleaner and easy to understand.

Also, you have a dummy `exec` handle which should be `put_handle()` at the end of that new function, otherwise there will be a memory leak. I would also rename the variable to `dummy_exec`.
</blockquote></details>

Done.
___
*[`libos/src/bookkeep/libos_handle.c` line 114 at r1](https://reviewable.io/reviews/gramineproject/gramine/722#-N6CeSWE50CxuqMpqDTa:-N6nLomh1u6-CYvlIE6b:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/cec58448e6795614f536a0f2189c9a46a5842c2a/libos/src/bookkeep/libos_handle.c#L114)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add a comment before this snippet:
```
/* entrypoint may be a shebang script instead of the ELF binary,  get the actual ELF binary name in this case */
```
</blockquote></details>

Done.
___
*[`libos/src/bookkeep/libos_handle.c` line 115 at r1](https://reviewable.io/reviews/gramineproject/gramine/722#-N6CfMRo6HWighXR6NST:-N6nLq6a4kp_KfyvP8ib:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/cec58448e6795614f536a0f2189c9a46a5842c2a/libos/src/bookkeep/libos_handle.c#L115)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`new_argv` -> `dummy_new_argv` (you're not using these arguments)
</blockquote></details>

Done.
___
*[`libos/src/bookkeep/libos_handle.c` line 116 at r1](https://reviewable.io/reviews/gramineproject/gramine/722#-N6CfR9-0FlDCjkp6Rhu:-N6nLrpz5z2ZW5leQPRM:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/cec58448e6795614f536a0f2189c9a46a5842c2a/libos/src/bookkeep/libos_handle.c#L116)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`argv` -> `dummy_argv` (you're not using these arguments)
</blockquote></details>

Done.
___
*[`libos/src/bookkeep/libos_handle.c` line 117 at r1](https://reviewable.io/reviews/gramineproject/gramine/722#-N6CfV6HDLZV2ERNK9RY:-N6nLtIyBsy0fLMSqYZa:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/cec58448e6795614f536a0f2189c9a46a5842c2a/libos/src/bookkeep/libos_handle.c#L117)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`argv[0]` -> `exec_path` (semantically equivalent, but easier to read)
</blockquote></details>

Done.
___
*[`libos/src/bookkeep/libos_handle.c` line 122 at r1](https://reviewable.io/reviews/gramineproject/gramine/722#-N6Cg-scDbDe7vEEzh7a:-N6nLuRe-KNOz-rezV3B:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/cec58448e6795614f536a0f2189c9a46a5842c2a/libos/src/bookkeep/libos_handle.c#L122)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This is already done inside `load_and_check_exec()`. The created-and-opened handle is returned by that function in `exec_handle`, so you could just use that one.
</blockquote></details>

Done.
___
*[`libos/src/bookkeep/libos_handle.c` line 129 at r1](https://reviewable.io/reviews/gramineproject/gramine/722#-N6Cg7NB4M0q9B1FV9EG:-N6nLwJv1s8rHF7RtqVF:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/cec58448e6795614f536a0f2189c9a46a5842c2a/libos/src/bookkeep/libos_handle.c#L129)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This is already done inside `load_and_check_exec()`. The created-and-opened handle is returned by that function in `exec_handle`, so you could just use that one.

So what I propose is to remove this snippet with `get_new_handle()` and `open_executable()` and simply have:
```
    char** dummy_new_argv = NULL;
    const char* dummy_argv[] = {exec_path, NULL};
    ret = load_and_check_exec(exec_path, dummy_argv, &hdl, &dummy_new_argv);
    if (ret < 0) {
        log_error("Error opening %s: %d", exec_path, ret);
        goto out;
    }

    free(*dummy_new_argv);
    free(dummy_new_argv);
```
</blockquote></details>

Done.
___
*[`libos/src/bookkeep/libos_process.c` line 66 at r1](https://reviewable.io/reviews/gramineproject/gramine/722#-N6C_TN-754Q2EmrpZF5:-N6nMa7e2zzanR7DVMhC:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/cec58448e6795614f536a0f2189c9a46a5842c2a/libos/src/bookkeep/libos_process.c#L66)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please remove this empty line.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-13 03:20 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/722)* status: 0 of 6 files reviewed, 11 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib and @dimakuv)

___
*[`libos/src/sys/libos_exec.c` line 173 at r5](https://reviewable.io/reviews/gramineproject/gramine/722#-N6pZEqe947yN1Mn_wj0:-N6pZEqe947yN1Mn_wj1:b-v0bub3) ([raw file](https://github.com/gramineproject/gramine/blob/a500aa830f617933b68f930a73c5865655e54fdb/libos/src/sys/libos_exec.c#L173)):*
> ```C
>         file, argv[0]);
>     }
>     const char* orig_argv[] = {file, argv[1] ? argv[1] : NULL, NULL};
> ```

Typically `argv[0]` and file would be the same. As in, an application normally passes `argv[0]`  to `pathname` while calling `execve` . Occasionally I see this not being met - and mostly in cases where the binary is present in one of the `$PATH` locations. for eg - `execve ("/usr/local/bin/baz.sh", ["baz.sh", .. ], .. )`

In such cases when Gramine obtains the interpreter for `/usr/local/bin/baz.h` by the reading the shebang line (which lets say is `/bin/sh` ) , but what gets passed to it is just `baz.sh` and not the full the path, resulting in Gramine not finding `baz.sh`


<!-- Sent from Reviewable.io -->

2022-07-13 09:03 UTC, dimakuv requested changes
> Reviewed 4 of 6 files at r3, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/722)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib)

___
*[`libos/include/libos_process.h` line 74 at r6](https://reviewable.io/reviews/gramineproject/gramine/722#-N6qkN7f4DkI1lyR24WU:-N6qkN7f4DkI1lyR24WV:btd49hi) ([raw file](https://github.com/gramineproject/gramine/blob/7cfe30b2ad61d1ce0c17a87378dd55d90c45e9f1/libos/include/libos_process.h#L74)):*
> ```objc
> int init_process(void);
> int init_process_cmdline(int argc, const char** argv);
> int init_process_args(const char* path, const char** argv, char*** out_new_argv);
> ```

There is no need for the `path` argument -- you are passing `argv[0]` here anyway, so just use `argv[0]` intead of `path` in this func. And remove the `path` argument.
___
*[`libos/src/libos_init.c` line 426 at r6](https://reviewable.io/reviews/gramineproject/gramine/722#-N6qkgMiBJyvlEDDRBR_:-N6qkgMiBJyvlEDDRBRa:b6kov6f) ([raw file](https://github.com/gramineproject/gramine/blob/7cfe30b2ad61d1ce0c17a87378dd55d90c45e9f1/libos/src/libos_init.c#L426)):*
> ```C
>     RUN_INIT(init_mount);
> 
>     char** new_argv = NULL;
> ```

In this function, we have now `new_argv` and `new_argp`. This is very confusing.

I suggest to rename the newly added `new_argv` to `expanded_argv`.
___
*[`libos/src/libos_rtld.c` line 697 at r6](https://reviewable.io/reviews/gramineproject/gramine/722#-N6qktv_08snh3BO_cKW:-N6qktv_08snh3BO_cKX:bmg9p6h) ([raw file](https://github.com/gramineproject/gramine/blob/7cfe30b2ad61d1ce0c17a87378dd55d90c45e9f1/libos/src/libos_rtld.c#L697)):*
> ```C
>     size_t curr_argv_bytes = 0, curr_argv_cnt = 0;
>     for (const char** a = argv; *a; a++) {
>         curr_argv_bytes += strlen(curr_argv_cnt == 0? path: *a) + 1;
> ```

Why is this change needed? What happens if you revert this change?

I highly dislike this change. Something is wrong here, and should be fixed at another level, not here.
___
*[`libos/src/libos_rtld.c` line 716 at r6](https://reviewable.io/reviews/gramineproject/gramine/722#-N6ql-QW82brWmXHuRTa:-N6ql-QW82brWmXHuRTb:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/7cfe30b2ad61d1ce0c17a87378dd55d90c45e9f1/libos/src/libos_rtld.c#L716)):*
> ```C
>     for (const char** a = argv; *a; a++) {
>         size_t size = strlen(curr_argv_idx == 0? path: *a) + 1;
>         memcpy(curr_argv_ptr, curr_argv_idx == 0? path: *a, size);
> ```

ditto
___
*[`libos/src/bookkeep/libos_handle.c` line 114 at r6](https://reviewable.io/reviews/gramineproject/gramine/722#-N6qhNTJ6Zau3E49YHlZ:-N6qhNTJ6Zau3E49YHl_:brwbmt) ([raw file](https://github.com/gramineproject/gramine/blob/7cfe30b2ad61d1ce0c17a87378dd55d90c45e9f1/libos/src/bookkeep/libos_handle.c#L114)):*
> ```C
>     }
> 
>     /* entrypoint may be a shebang script instead of the ELF binary,  get the actual ELF binary name in this case */
> ```

Please remove a double-space after comma
___
*[`libos/src/bookkeep/libos_process.c` line 63 at r6](https://reviewable.io/reviews/gramineproject/gramine/722#-N6ql31FANjk40AhY-xW:-N6ql31FANjk40AhY-xX:b-38txxg) ([raw file](https://github.com/gramineproject/gramine/blob/7cfe30b2ad61d1ce0c17a87378dd55d90c45e9f1/libos/src/bookkeep/libos_process.c#L63)):*
> ```C
> 
> int init_process_args(const char* path, const char** argv, char*** out_new_argv) {
> ```

Please remove empty line.
___
*[`libos/src/bookkeep/libos_process.c` line 67 at r6](https://reviewable.io/reviews/gramineproject/gramine/722#-N6qlC-b3PrUSeMnxeZ0:-N6qlC-b3PrUSeMnxeZ1:btpad4n) ([raw file](https://github.com/gramineproject/gramine/blob/7cfe30b2ad61d1ce0c17a87378dd55d90c45e9f1/libos/src/bookkeep/libos_process.c#L67)):*
> ```C
>     int ret = load_and_check_exec(path, argv, &dummy_exec, out_new_argv);
>     if (ret < 0) {
>         log_error("libos_init: failed to load exec:%s  ret %d", argv[0], ret);
> ```

I see no need in this error message. The caller of `init_process_args()` will print some error message anyway. Just remove this line.
___
*[`libos/src/bookkeep/libos_process.c` line 68 at r6](https://reviewable.io/reviews/gramineproject/gramine/722#-N6qlHrcBGSt40xtXffJ:-N6qlHrcBGSt40xtXffK:bmlbpdp) ([raw file](https://github.com/gramineproject/gramine/blob/7cfe30b2ad61d1ce0c17a87378dd55d90c45e9f1/libos/src/bookkeep/libos_process.c#L68)):*
> ```C
>     if (ret < 0) {
>         log_error("libos_init: failed to load exec:%s  ret %d", argv[0], ret);
>         PalProcessExit(1);
> ```

This is wrong. You need to `return ret`.
___
*[`libos/src/sys/libos_exec.c` line 173 at r5](https://reviewable.io/reviews/gramineproject/gramine/722#-N6pZEqe947yN1Mn_wj0:-N6qltHK7QJXe86zMt3M:b-o6os8) ([raw file](https://github.com/gramineproject/gramine/blob/a500aa830f617933b68f930a73c5865655e54fdb/libos/src/sys/libos_exec.c#L173)):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

Typically `argv[0]` and file would be the same. As in, an application normally passes `argv[0]`  to `pathname` while calling `execve` . Occasionally I see this not being met - and mostly in cases where the binary is present in one of the `$PATH` locations. for eg - `execve ("/usr/local/bin/baz.sh", ["baz.sh", .. ], .. )`

In such cases when Gramine obtains the interpreter for `/usr/local/bin/baz.h` by the reading the shebang line (which lets say is `/bin/sh` ) , but what gets passed to it is just `baz.sh` and not the full the path, resulting in Gramine not finding `baz.sh`


</blockquote></details>

I don't get the explanation. This will need a more detailed flow that breaks.

Anyway, I have two issues with this:
1. How is this related to this PR (to "running scripts as the entrypoint")? This seems to deserve a separate PR.
2. Why the need for this debug message? It doesn't change anything in Gramine execution, so how does it help in anything?

Bottom line: let's remove this code snippet from this PR, and create a new PR. This code snippet is very suspicious, and we'll need several rounds of discussions before it come to some conclusion. So by removing this snippet from this PR, we can concentrate on the core of the PR and merge it faster.

UPDATE: Hm, now I realize that you added this snippet because you also added a strange fix inside `load_and_check_exec()` (see my comments there). I believe both these changes have nothing to do with your current PR and should be discussed in another PR.


<!-- Sent from Reviewable.io -->

2022-07-13 17:49 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/722)* status: 1 of 6 files reviewed, 10 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib and @dimakuv)

___
*[`libos/src/libos_rtld.c` line 697 at r6](https://reviewable.io/reviews/gramineproject/gramine/722#-N6qktv_08snh3BO_cKW:-N6sf4XG4cf6sOmvGi3-:b2t2om) ([raw file](https://github.com/gramineproject/gramine/blob/7cfe30b2ad61d1ce0c17a87378dd55d90c45e9f1/libos/src/libos_rtld.c#L697)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why is this change needed? What happens if you revert this change?

I highly dislike this change. Something is wrong here, and should be fixed at another level, not here.
</blockquote></details>

Per our separate discussion - submitted another PR with this change 
___
*[`libos/src/libos_rtld.c` line 716 at r6](https://reviewable.io/reviews/gramineproject/gramine/722#-N6ql-QW82brWmXHuRTa:-N6sfKEO2LK_A2NKKe3A:bplfbt9) ([raw file](https://github.com/gramineproject/gramine/blob/7cfe30b2ad61d1ce0c17a87378dd55d90c45e9f1/libos/src/libos_rtld.c#L716)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Per our separate discussion - submitted another PR with this change https://github.com/gramineproject/gramine/pull/754


<!-- Sent from Reviewable.io -->

2022-07-14 07:17 UTC, dimakuv requested changes
> Reviewed 4 of 4 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/722)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/722#-N6CdQaGDU2vhcYBfAlM:-N6vZR9cA0HwQxS7vZVo:b-q18bph) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This is a new feature, and it needs at least one (preferrably 2 or 3) different tests, with manifests containing`libos.entrypoint = "script.sh"`.
</blockquote></details>

This will need to be done.

___
___
*[`libos/src/libos_init.c` line 428 at r8](https://reviewable.io/reviews/gramineproject/gramine/722#-N6vXrfODxC2l6TAk-Mu:-N6vXrfP1-nOQ7K2GbIW:ba88mcm) ([raw file](https://github.com/gramineproject/gramine/blob/e55362b6f11f1ef8ca0ad0a2ed90d061215b5bff/libos/src/libos_init.c#L428)):*
> ```C
>     char** expanded_argv = NULL;
>     RUN_INIT(init_process_args, argv, &expanded_argv);
>     RUN_INIT(init_process_cmdline, argc, (const char**)expanded_argv);
> ```

Wait, actually, does it make sense? Your new `expanded_argv` may have a different number of arguments now. But you're still using the old `argc` value.

I think you need to modify `init_process_cmdline()` implementation to remove this `argc` argument completely -- we can calculate the number of arguments from `argv` itself.
___
*[`libos/src/libos_init.c` line 429 at r8](https://reviewable.io/reviews/gramineproject/gramine/722#-N6vZ5sFEFAffewNmc2s:-N6vZ5sFEFAffewNmc2t:b-4zu1h8) ([raw file](https://github.com/gramineproject/gramine/blob/e55362b6f11f1ef8ca0ad0a2ed90d061215b5bff/libos/src/libos_init.c#L429)):*
> ```C
>     RUN_INIT(init_process_args, argv, &expanded_argv);
>     RUN_INIT(init_process_cmdline, argc, (const char**)expanded_argv);
>     RUN_INIT(init_threading);
> ```

Can you add an empty line before this `init_threading()` invocation? To visually separate "work on args" and "work on other stuff".
___
*[`libos/src/libos_init.c` line 439 at r8](https://reviewable.io/reviews/gramineproject/gramine/722#-N6vYzOYCZuJCqjQn_5P:-N6vYzOYCZuJCqjQn_5Q:b-mcdjmh) ([raw file](https://github.com/gramineproject/gramine/blob/e55362b6f11f1ef8ca0ad0a2ed90d061215b5bff/libos/src/libos_init.c#L439)):*
> ```C
>     const char** new_argp;
>     elf_auxv_t* new_auxv;
> ```

Please remove this empty line. These two variable declarations naturally "belong" to the `init_stack()` invocation.
___
*[`libos/src/sys/libos_exec.c` line 173 at r5](https://reviewable.io/reviews/gramineproject/gramine/722#-N6pZEqe947yN1Mn_wj0:-N6vYTHm4sM_AfZvspWp:brrv0r4) ([raw file](https://github.com/gramineproject/gramine/blob/a500aa830f617933b68f930a73c5865655e54fdb/libos/src/sys/libos_exec.c#L173)):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

The need for this change (or some fix) arises only when executing scripts, and not with elf, which is why I chose to include it here. I'll create another PR just to address this.
</blockquote></details>

Please revert this code snippet here. I see no useful information to users when they see `Unusual anomaly...` message. Also, it's not unusual, now we now that this is how `execve()` works -- it is written in the man pages (and somewhere in the POSIX standard).


<!-- Sent from Reviewable.io -->

2022-07-15 07:21 UTC, dimakuv requested changes
> Reviewed 4 of 4 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/722)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/722#-N6CdQaGDU2vhcYBfAlM:-N7-hPorBXarFfgQO6zb:b6gnk9w) (no related file):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

Working on it. Tests framework seem to be designed around test executables written in C. So this will be a first (I think) to run scripts as the entrypoint. 
</blockquote></details>

The tests framework shouldn't care about scripts. I mean, you can just create a script file `execscript.sh` in `libos/test/regression/` directory and create a manifest file `execscript.manifest.template` that will contain (among other things):
```
libos.entrypoint = "execscript.sh"
```

Then you add your `execscript` manifest entry here: https://github.com/gramineproject/gramine/blob/e5cbd1518d882844eb62dffaa1f1f10511fd40da/libos/test/regression/tests.toml#L3

and here: https://github.com/gramineproject/gramine/blob/e5cbd1518d882844eb62dffaa1f1f10511fd40da/libos/test/regression/tests_musl.toml#L5

And you add a new test somewhere here: https://github.com/gramineproject/gramine/blob/e5cbd1518d882844eb62dffaa1f1f10511fd40da/libos/test/regression/test_libos.py#L224

That should be it. No need to modify the framework, just add required files.

___
___
*[`libos/src/libos_init.c` line 428 at r8](https://reviewable.io/reviews/gramineproject/gramine/722#-N6vXrfODxC2l6TAk-Mu:-N7-ihGB6Dj5g3G5864B:b-55rsio) ([raw file](https://github.com/gramineproject/gramine/blob/e55362b6f11f1ef8ca0ad0a2ed90d061215b5bff/libos/src/libos_init.c#L428)):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

Done. But note that now you don't use this argument at all in the entire `libos_init` function. 
</blockquote></details>

True, but that's for another PR. The current `UNUSED(argc)` is good.


<!-- Sent from Reviewable.io -->

2022-07-15 12:03 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/722)* status: 6 of 11 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib and @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/722#-N6CdQaGDU2vhcYBfAlM:-N70j3US7PRSAF7Pj4Rn:b-2xjia0) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

The tests framework shouldn't care about scripts. I mean, you can just create a script file `execscript.sh` in `libos/test/regression/` directory and create a manifest file `execscript.manifest.template` that will contain (among other things):
```
libos.entrypoint = "execscript.sh"
```

Then you add your `execscript` manifest entry here: https://github.com/gramineproject/gramine/blob/e5cbd1518d882844eb62dffaa1f1f10511fd40da/libos/test/regression/tests.toml#L3

and here: https://github.com/gramineproject/gramine/blob/e5cbd1518d882844eb62dffaa1f1f10511fd40da/libos/test/regression/tests_musl.toml#L5

And you add a new test somewhere here: https://github.com/gramineproject/gramine/blob/e5cbd1518d882844eb62dffaa1f1f10511fd40da/libos/test/regression/test_libos.py#L224

That should be it. No need to modify the framework, just add required files.
</blockquote></details>

Done. I misunderstood that the test must be a part of meson too. Btw - I named the test as `run_script`  (too much similarity between `execscript` and `exec_script`)

___


<!-- Sent from Reviewable.io -->

2022-07-15 12:04 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/722)* status: 6 of 11 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`libos/src/libos_init.c` line 428 at r8](https://reviewable.io/reviews/gramineproject/gramine/722#-N6vXrfODxC2l6TAk-Mu:-N70jbBV-sn9fJ3JbVFj:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/e55362b6f11f1ef8ca0ad0a2ed90d061215b5bff/libos/src/libos_init.c#L428)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

True, but that's for another PR. The current `UNUSED(argc)` is good.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-16 19:17 UTC, mkow requested changes
> Reviewed 1 of 1 files at r8, 3 of 4 files at r9, 5 of 5 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/722)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib and @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/722#-N77HvySEOHHDrp9gwjP:-N77HvySEOHHDrp9gwjQ:bwf7mf5) (no related file):*
> aneessahib:nonelf_entrypoint

Please read https://gramine.readthedocs.io/en/latest/devel/contributing.html#branch-names (and actually this whole document).

___
___
*[`libos/src/libos_init.c` line 429 at r10](https://reviewable.io/reviews/gramineproject/gramine/722#-N77K2oO4RLx96L3PufB:-N77K2oO4RLx96L3PufC:b-8vz9qv) ([raw file](https://github.com/gramineproject/gramine/blob/421c497f0f8cf56e30edd24f743808c3e279d79c/libos/src/libos_init.c#L429)):*
> ```C
>     char** expanded_argv = NULL;
>     RUN_INIT(init_process_args, argv, &expanded_argv);
>     RUN_INIT(init_process_cmdline, (const char**)expanded_argv);
> ```

Why can't you change the type of `expanded_argv` instead? (and all functions using it)



_Code quote:_
```C
(const char**)expanded_argv
```
___
*[`libos/src/bookkeep/libos_handle.c` line 114 at r10](https://reviewable.io/reviews/gramineproject/gramine/722#-N77EYRG8lQCH_QqCNHh:-N77EYRG8lQCH_QqCNHi:b1yby4v) ([raw file](https://github.com/gramineproject/gramine/blob/421c497f0f8cf56e30edd24f743808c3e279d79c/libos/src/bookkeep/libos_handle.c#L114)):*
> ```C
>     }
> 
>     /* entrypoint may be a shebang script instead of the ELF binary, get the actual ELF binary name in this case */
> ```

line too long
___
*[`libos/src/bookkeep/libos_handle.c` line 114 at r10](https://reviewable.io/reviews/gramineproject/gramine/722#-N77LQRO6x91qJjMLFJE:-N77LQRO6x91qJjMLFJF:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/421c497f0f8cf56e30edd24f743808c3e279d79c/libos/src/bookkeep/libos_handle.c#L114)):*
> ```C
>     }
> 
>     /* entrypoint may be a shebang script instead of the ELF binary, get the actual ELF binary name in this case */
> ```





_Suggestion:_
```C
an ELF binary
```
___
*[`libos/test/regression/run_script.sh` line 1 at r10](https://reviewable.io/reviews/gramineproject/gramine/722#-N77Itm_6EP6QnBuiyJO:-N77Itm_6EP6QnBuiyJP:b-vpxx8s) ([raw file](https://github.com/gramineproject/gramine/blob/421c497f0f8cf56e30edd24f743808c3e279d79c/libos/test/regression/run_script.sh#L1)):*
> ```Shell
> #!  /bin/sh
> ```

Please name this script differently, so that it's visible that it's a test (not some utility script for running tests, as it may sound now), e.g. prefix it with `shebang_test_`.
___
*[`libos/test/regression/run_script.manifest.template` line 3 at r10](https://reviewable.io/reviews/gramineproject/gramine/722#-N77N2Mv0R_d4VSDENp-:-N77N2MwC1l38bbgtaYl:bdk7ku9) ([raw file](https://github.com/gramineproject/gramine/blob/421c497f0f8cf56e30edd24f743808c3e279d79c/libos/test/regression/run_script.manifest.template#L3)):*
> ```
> loader.entrypoint = "file:{{ gramine.libos }}"
> libos.entrypoint = "run_script.sh"
> loader.argv0_override = "run_script.sh"
> ```

Why is this needed?
___
*[`libos/test/regression/run_script.manifest.template` line 25 at r10](https://reviewable.io/reviews/gramineproject/gramine/722#-N77MdQe6njqrTM5Tarv:-N77MdQf7EVUK9VkivcP:b99pnfj) ([raw file](https://github.com/gramineproject/gramine/blob/421c497f0f8cf56e30edd24f743808c3e279d79c/libos/test/regression/run_script.manifest.template#L25)):*
> ```
>   "file:/usr{{ arch_libdir }}/libstdc++.so.6",
>   "file:{{ binary_dir }}/{{ entrypoint }}",
>   "file:{{ binary_dir }}/exec_victim",
> ```

What's this? And half of the things above?
___
*[`libos/test/regression/test_libos.py` line 225 at r10](https://reviewable.io/reviews/gramineproject/gramine/722#-N77NRhh2UGcYr0It_ae:-N77NRhh2UGcYr0It_af:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/421c497f0f8cf56e30edd24f743808c3e279d79c/libos/test/regression/test_libos.py#L225)):*
> ```Python
>             'scripts/foo.sh STRING FROM EXECVE', stdout)
> 
>     @unittest.skipIf(USES_MUSL, 'Test uses /bin/sh from the host which is built against Glibc')
> ```





_Suggestion:_
```Python
which is usually built against glibc
```


<!-- Sent from Reviewable.io -->

2022-07-18 07:19 UTC, dimakuv requested changes
> Reviewed 4 of 5 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/722)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib and @mkow)

___
*[`libos/src/libos_init.c` line 429 at r10](https://reviewable.io/reviews/gramineproject/gramine/722#-N77K2oO4RLx96L3PufB:-N7F863J9PDVsyEUr83Y:bw881zg) ([raw file](https://github.com/gramineproject/gramine/blob/421c497f0f8cf56e30edd24f743808c3e279d79c/libos/src/libos_init.c#L429)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why can't you change the type of `expanded_argv` instead? (and all functions using it)
</blockquote></details>

@mkow I don't get your comment. If changing anything, then Anees should change either one of those:
- either change the type of `expanded_argv` to `const char**` (but then also typecast it in `init_process_args()`? I'm not sure about it, probably not needed),
- or change the argument types in `init_process_cmdline()` and `init_stack()` to accept `char**` instead of `const char**`

I would prefer the first option.
___
*[`libos/test/regression/run_script.sh` line 1 at r10](https://reviewable.io/reviews/gramineproject/gramine/722#-N77Itm_6EP6QnBuiyJO:-N7F8oOP1cJDmMVNceQ5:b-9j5zfc) ([raw file](https://github.com/gramineproject/gramine/blob/421c497f0f8cf56e30edd24f743808c3e279d79c/libos/test/regression/run_script.sh#L1)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please name this script differently, so that it's visible that it's a test (not some utility script for running tests, as it may sound now), e.g. prefix it with `shebang_test_`.
</blockquote></details>

+1, I like `shebang_test_script.sh`. This file and all corresponding files (the manifest).
___
*[`libos/test/regression/run_script.manifest.template` line 3 at r10](https://reviewable.io/reviews/gramineproject/gramine/722#-N77N2Mv0R_d4VSDENp-:-N7F9AFSA45D3rCtWBDo:b3q4apm) ([raw file](https://github.com/gramineproject/gramine/blob/421c497f0f8cf56e30edd24f743808c3e279d79c/libos/test/regression/run_script.manifest.template#L3)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why is this needed?
</blockquote></details>

I have a feeling we need this line. Otherwise we'll end up with `argc == 0`, and this is not how Linux starts programs.

Alternatively, we could have `loader.insecure__use_cmdline_argv`.
___
*[`libos/test/regression/run_script.manifest.template` line 25 at r10](https://reviewable.io/reviews/gramineproject/gramine/722#-N77MdQe6njqrTM5Tarv:-N7F96CRBJRUw3HXE44L:b-xmdrz) ([raw file](https://github.com/gramineproject/gramine/blob/421c497f0f8cf56e30edd24f743808c3e279d79c/libos/test/regression/run_script.manifest.template#L25)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What's this? And half of the things above?
</blockquote></details>

+1, please remove all the unnecessary lines in this file
___
*[`libos/test/regression/test_libos.py` line 225 at r10](https://reviewable.io/reviews/gramineproject/gramine/722#-N77NRhh2UGcYr0It_ae:-N7F9qoY19Y6LkVnjh6w:b-hnp4e2) ([raw file](https://github.com/gramineproject/gramine/blob/421c497f0f8cf56e30edd24f743808c3e279d79c/libos/test/regression/test_libos.py#L225)):*
> ```Python
>             'scripts/foo.sh STRING FROM EXECVE', stdout)
> 
>     @unittest.skipIf(USES_MUSL, 'Test uses /bin/sh from the host which is built against Glibc')
> ```

When resolving according to @mkow's comment, please also fix it in the test above.
___
*[`libos/test/regression/tests_musl.toml` line 87 at r10](https://reviewable.io/reviews/gramineproject/gramine/722#-N7F9fVT3SlubF4TwYpI:-N7F9fVT3SlubF4TwYpJ:byohun9) ([raw file](https://github.com/gramineproject/gramine/blob/421c497f0f8cf56e30edd24f743808c3e279d79c/libos/test/regression/tests_musl.toml#L87)):*
> ```TOML
>   "readdir",
>   "rename_unlink",
>   "run_script",
> ```

You don't need to update this file since you're only testing for Glibc, and skipping for Musl.


<!-- Sent from Reviewable.io -->

2022-07-18 10:57 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/722)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib and @boryspoplawski)

___
*[`libos/test/regression/run_script.manifest.template` line 3 at r10](https://reviewable.io/reviews/gramineproject/gramine/722#-N77N2Mv0R_d4VSDENp-:-N7FwSZYD02226mzt1el:b-7pt1od) ([raw file](https://github.com/gramineproject/gramine/blob/421c497f0f8cf56e30edd24f743808c3e279d79c/libos/test/regression/run_script.manifest.template#L3)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Wait, why `argc` would be 0? If it would, isn't this just a bug in this PR?
</blockquote></details>

Do you mean that Gramine should correctly handle the case where the manifest doesn't specify any argv-related options (i.e., `argc == 0`)?

Yeah, sounds like you're right. Gramine should detect this case and put the `libos.entrypoint` string as the first and only `argv`. I don't know if this is actually supported in Gramine currently. Or maybe I'm incorrectly understanding how Linux starts programs? @boryspoplawski 


<!-- Sent from Reviewable.io -->

2022-07-18 11:26 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/722)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib and @boryspoplawski)

___
*[`libos/test/regression/run_script.manifest.template` line 3 at r10](https://reviewable.io/reviews/gramineproject/gramine/722#-N77N2Mv0R_d4VSDENp-:-N7G247w5HYarBJX8c5W:bn2us9h) ([raw file](https://github.com/gramineproject/gramine/blob/421c497f0f8cf56e30edd24f743808c3e279d79c/libos/test/regression/run_script.manifest.template#L3)):*
> Do you mean that Gramine should correctly handle the case where the manifest doesn't specify any argv-related options (i.e., `argc == 0`)?

Yes, although it's not `argc == 0` then - it's just not specified anywhere.

> Or maybe I'm incorrectly understanding how Linux starts programs?

This is unrelated to how Linux starts programs. Linux always gets requests to start processes from `execve` where you always have `argv` specified. The only similar case is init process, where arguments are (I think) taken from some config file / boot options (like in our case).


<!-- Sent from Reviewable.io -->

2022-07-18 13:18 UTC, boryspoplawski reviewed
> Reviewed 1 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/722)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib and @mkow)

___
*[`libos/test/regression/run_script.manifest.template` line 3 at r10](https://reviewable.io/reviews/gramineproject/gramine/722#-N77N2Mv0R_d4VSDENp-:-N7GR1nlBmt37a2lwHXy:b7352f1) ([raw file](https://github.com/gramineproject/gramine/blob/421c497f0f8cf56e30edd24f743808c3e279d79c/libos/test/regression/run_script.manifest.template#L3)):*
I think `argc == 0` should work in Graimne, but `argv == NULL` won't. We probably need to fix it at some point, but that was never a priority, since nothing really uses it.

>  from execve where you always have argv specified. 

Not true, you can have `argv == NULL`.

> Wait, why argc would be 0? If it would, isn't this just a bug in this PR?

Why wouldn't it be? If we did not specify any arguments anywhere...
I think `argv0_override` was introduced exactly due to this - not to have `argc == 0` (bascially poor-mans inline in manifest argv), but I might remember it wrong.

> Gramine should detect this case and put the libos.entrypoint string as the first and only argv. I don't know if this is actually supported in Gramine currently. Or maybe I'm incorrectly understanding how Linux starts programs? @boryspoplawski

Not sure what you mean. As @mkow pointed out, all args always come from `execve`


<!-- Sent from Reviewable.io -->

2022-07-18 14:15 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/722)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib and @mkow)

___
*[`libos/test/regression/run_script.manifest.template` line 3 at r10](https://reviewable.io/reviews/gramineproject/gramine/722#-N77N2Mv0R_d4VSDENp-:-N7Gd_6IEllM7q5TYt--:buqto20) ([raw file](https://github.com/gramineproject/gramine/blob/421c497f0f8cf56e30edd24f743808c3e279d79c/libos/test/regression/run_script.manifest.template#L3)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> Not sure what you mean. As @mkow pointed out, all args always come from `execve`

But for the first process, Gramine should do some magic; similar to how Linux does some magic for the `init` process. I mean, there is no `execve` for the first process under Gramine. I'm talking solely about this case.
</blockquote></details>

Yes, but then it's not "how Linux starts programs", just something more specific to Gramine.
Putting entrypoint as argv0 sounds good to me


<!-- Sent from Reviewable.io -->

2022-07-18 16:20 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/722)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @boryspoplawski, and @dimakuv)

___
*[`libos/test/regression/run_script.manifest.template` line 3 at r10](https://reviewable.io/reviews/gramineproject/gramine/722#-N77N2Mv0R_d4VSDENp-:-N7H4hnl962L8sudEfu0:brs7bjx) ([raw file](https://github.com/gramineproject/gramine/blob/421c497f0f8cf56e30edd24f743808c3e279d79c/libos/test/regression/run_script.manifest.template#L3)):*
> > from execve where you always have argv specified.
> 
> Not true, you can have `argv == NULL`.

Ok, I rather meant that you have clearly specified what should process receive.

> > Wait, why argc would be 0? If it would, isn't this just a bug in this PR?
> 
> Why wouldn't it be? If we did not specify any arguments anywhere...

"we did not specify any arguments anywhere" - exactly, so argc/argv is just unspecified, not "specified as empty" ;) The user just didn't configure this at all in this case.

> I think argv0_override was introduced exactly due to this - not to have argc == 0 (bascially poor-mans inline in manifest argv), but I might remember it wrong.

`argv0_override` is super old (although it had a different name before), AFAIR even older than the support to block host argv from being passed through.

So, summarizing: in this particular case we don't have argv specified anywhere, so we need to pick some default. And IMO `argv = [entrypoint]` is a good one.


<!-- Sent from Reviewable.io -->

2022-07-19 07:42 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/722)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib and @mkow)

___
*[`libos/src/libos_init.c` line 429 at r10](https://reviewable.io/reviews/gramineproject/gramine/722#-N77K2oO4RLx96L3PufB:-N7Fw7jo0butNva1ph1K:b-fesw3q) ([raw file](https://github.com/gramineproject/gramine/blob/421c497f0f8cf56e30edd24f743808c3e279d79c/libos/src/libos_init.c#L429)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

But why `init_process_args()` can't receive a compatible argument? I.e. why we need any casts here?
</blockquote></details>

Maybe we don't need any casts. @aneessahib Could you change:
```
char** expanded_argv = NULL;
```
to
```
const char** expanded_argv = NULL;
```

And then update the `init_process_args()` function definition to accept the compatible type in the second argument?
___
*[`libos/test/regression/run_script.manifest.template` line 3 at r10](https://reviewable.io/reviews/gramineproject/gramine/722#-N77N2Mv0R_d4VSDENp-:-N7KOsct26-t0N7ggYRo:b-4vbuvu) ([raw file](https://github.com/gramineproject/gramine/blob/421c497f0f8cf56e30edd24f743808c3e279d79c/libos/test/regression/run_script.manifest.template#L3)):*
> So, summarizing: in this particular case we don't have argv specified anywhere, so we need to pick some default. And IMO `argv = [entrypoint]` is a good one.

I agree with this. But didn't we derail the conversation? The PR is called "Support running scripts as the entrypoint", and what we're discussing here is a different feature. We should make a new PR for it.


<!-- Sent from Reviewable.io -->

2022-07-19 08:11 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/722)* status: 2 of 11 files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/722#-N77HvySEOHHDrp9gwjP:-N7KTi1bEC63OCTt7wrX:b-3lkpcg) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> aneessahib:nonelf_entrypoint

Please read https://gramine.readthedocs.io/en/latest/devel/contributing.html#branch-names (and actually this whole document).
</blockquote></details>

Ok - will it mess with the ongoing PR if I rename branch? I'll take care of this in future PRs if that's ok. 

___
___
*[`libos/src/libos_init.c` line 429 at r10](https://reviewable.io/reviews/gramineproject/gramine/722#-N77K2oO4RLx96L3PufB:-N7KTuZBBGyFR1JwVP7S:b-r20ltt) ([raw file](https://github.com/gramineproject/gramine/blob/421c497f0f8cf56e30edd24f743808c3e279d79c/libos/src/libos_init.c#L429)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Maybe we don't need any casts. @aneessahib Could you change:
```
char** expanded_argv = NULL;
```
to
```
const char** expanded_argv = NULL;
```

And then update the `init_process_args()` function definition to accept the compatible type in the second argument?
</blockquote></details>

Does this look ok now? I thought Michal's concern is the cast that we do here (which is actually needed). i.e use `char**` as the type all through `init_process_cmdline`
___
*[`libos/src/bookkeep/libos_handle.c` line 114 at r10](https://reviewable.io/reviews/gramineproject/gramine/722#-N77EYRG8lQCH_QqCNHh:-N7KUs9089F3VV_E91FQ:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/421c497f0f8cf56e30edd24f743808c3e279d79c/libos/src/bookkeep/libos_handle.c#L114)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

line too long
</blockquote></details>

Done.
___
*[`libos/src/bookkeep/libos_handle.c` line 114 at r10](https://reviewable.io/reviews/gramineproject/gramine/722#-N77LQRO6x91qJjMLFJE:-N7KVPeq3BoMT-8jssgM:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/421c497f0f8cf56e30edd24f743808c3e279d79c/libos/src/bookkeep/libos_handle.c#L114)):*
> ```C
>     }
> 
>     /* entrypoint may be a shebang script instead of the ELF binary, get the actual ELF binary name in this case */
> ```

Done.
___
*[`libos/test/regression/test_libos.py` line 225 at r10](https://reviewable.io/reviews/gramineproject/gramine/722#-N77NRhh2UGcYr0It_ae:-N7KVavr9dabtITBkkiw:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/421c497f0f8cf56e30edd24f743808c3e279d79c/libos/test/regression/test_libos.py#L225)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

When resolving according to @mkow's comment, please also fix it in the test above.
</blockquote></details>

Done.
___
*[`libos/test/regression/tests_musl.toml` line 87 at r10](https://reviewable.io/reviews/gramineproject/gramine/722#-N7F9fVT3SlubF4TwYpI:-N7KVdcDCt78GyUf92ca:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/421c497f0f8cf56e30edd24f743808c3e279d79c/libos/test/regression/tests_musl.toml#L87)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You don't need to update this file since you're only testing for Glibc, and skipping for Musl.
</blockquote></details>

Done.
___
*[`libos/test/regression/run_script.sh` line 1 at r10](https://reviewable.io/reviews/gramineproject/gramine/722#-N77Itm_6EP6QnBuiyJO:-N7KVRMd9PgDHucJWMnX:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/421c497f0f8cf56e30edd24f743808c3e279d79c/libos/test/regression/run_script.sh#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

+1, I like `shebang_test_script.sh`. This file and all corresponding files (the manifest).
</blockquote></details>

Done.
___
*[`libos/test/regression/run_script.manifest.template` line 25 at r10](https://reviewable.io/reviews/gramineproject/gramine/722#-N77MdQe6njqrTM5Tarv:-N7KVZBkDJTmpBN_8tIB:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/421c497f0f8cf56e30edd24f743808c3e279d79c/libos/test/regression/run_script.manifest.template#L25)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

+1, please remove all the unnecessary lines in this file
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-19 08:48 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/722)* status: 2 of 11 files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`libos/src/libos_init.c` line 429 at r10](https://reviewable.io/reviews/gramineproject/gramine/722#-N77K2oO4RLx96L3PufB:-N7KdCF210E4k_EW_gBy:bs63ju7) ([raw file](https://github.com/gramineproject/gramine/blob/421c497f0f8cf56e30edd24f743808c3e279d79c/libos/src/libos_init.c#L429)):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

Does this look ok now? I thought Michal's concern is the cast that we do here (which is actually needed). i.e use `char**` as the type all through `init_process_cmdline`
</blockquote></details>

typo - actually *not* needed


<!-- Sent from Reviewable.io -->

2022-07-19 09:12 UTC, dimakuv requested changes
> Reviewed 8 of 9 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/722)* status: 10 of 11 files reviewed, 13 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/722#-N77HvySEOHHDrp9gwjP:-N7Kh6ha2SEdmA-im2-W:bwf9cy) (no related file):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

Ok - will it mess with the ongoing PR if I rename branch? I'll take care of this in future PRs if that's ok. 
</blockquote></details>

@aneessahib Yep, please don't rename this branch. Just keep it in mind for the future, that you need not only a name-explanation for the branch (like `nonelf_entrypoint`) but also your nickname as a prefix (so it should have been `aneessahib/nonelf_entrypoint`).

___
___
*[`libos/include/libos_process.h` line 73 at r11](https://reviewable.io/reviews/gramineproject/gramine/722#-N7KiZK09v9Und6cHod4:-N7KiZK09v9Und6cHod5:bxfa89) ([raw file](https://github.com/gramineproject/gramine/blob/02a30849b34f1881bc3a20ad65d305fab288a12b/libos/include/libos_process.h#L73)):*
> ```objc
> 
> int init_process(void);
> int init_process_cmdline(char** argv);
> ```

This is a wrong change, please keep `const`
___
*[`libos/src/libos_init.c` line 429 at r10](https://reviewable.io/reviews/gramineproject/gramine/722#-N77K2oO4RLx96L3PufB:-N7KhVr4DG8QwBQwYMGl:bppfwns) ([raw file](https://github.com/gramineproject/gramine/blob/421c497f0f8cf56e30edd24f743808c3e279d79c/libos/src/libos_init.c#L429)):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

typo - actually *not* needed
</blockquote></details>

No, this change looks wrong. `init_process_cmdline()` should take `const char**` as input. This basically tells the reader of this code and the compiler that "this argument is an input argument, the strings in this list are constant". Now you removed `const`, and the meaning changed -- now it is "this argument is an input/output argument, *maybe* this function will change the strings in this list".

So you should actually change `expanded_argv` variable to be `const char**`.
___
*[`libos/src/libos_init.c` line 441 at r11](https://reviewable.io/reviews/gramineproject/gramine/722#-N7Ki-F62DoNPd1BTviD:-N7Ki-F62DoNPd1BTviE:b-207dw2) ([raw file](https://github.com/gramineproject/gramine/blob/02a30849b34f1881bc3a20ad65d305fab288a12b/libos/src/libos_init.c#L441)):*
> ```C
>     const char** new_argp;
>     elf_auxv_t* new_auxv;
>     RUN_INIT(init_stack, (const char**)expanded_argv, envp, &new_argp, &new_auxv);
> ```

@aneessahib Also note that you have this typecast here.
___
*[`libos/src/bookkeep/libos_process.c` line 75 at r11](https://reviewable.io/reviews/gramineproject/gramine/722#-N7Ki6s8806gz9EGipQF:-N7Ki6s8806gz9EGipQG:bxfa89) ([raw file](https://github.com/gramineproject/gramine/blob/02a30849b34f1881bc3a20ad65d305fab288a12b/libos/src/bookkeep/libos_process.c#L75)):*
> ```C
> }
> 
> int init_process_cmdline(char** argv) {
> ```

This is a wrong change, please keep `const`
___
*[`libos/src/bookkeep/libos_process.c` line 83 at r11](https://reviewable.io/reviews/gramineproject/gramine/722#-N7Ki8tj0kzW2XybGyaf:-N7Ki8tj0kzW2XybGyag:bxfa89) ([raw file](https://github.com/gramineproject/gramine/blob/02a30849b34f1881bc3a20ad65d305fab288a12b/libos/src/bookkeep/libos_process.c#L83)):*
> ```C
>     size_t tmp_size = 0;
> 
>     for (char** a = argv; *a; a++) {
> ```

This is a wrong change, please keep `const`
___
*[`libos/test/regression/test_libos.py` line 217 at r11](https://reviewable.io/reviews/gramineproject/gramine/722#-N7KiOuwC0VBMta9k7wE:-N7KiOuwC0VBMta9k7wF:b-5eoelc) ([raw file](https://github.com/gramineproject/gramine/blob/02a30849b34f1881bc3a20ad65d305fab288a12b/libos/test/regression/test_libos.py#L217)):*
> ```Python
>         self.assertIn('execve(invalid-envp) correctly returned error', stdout)
> 
>     @unittest.skipIf(USES_MUSL, 'Test uses /bin/sh from the host which is built against Glibc')
> ```

You forgot to change this test as well.


<!-- Sent from Reviewable.io -->

2022-07-19 10:04 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/722)* status: 10 of 11 files reviewed, 13 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @dimakuv, and @mkow)

___
*[`libos/src/libos_init.c` line 429 at r10](https://reviewable.io/reviews/gramineproject/gramine/722#-N77K2oO4RLx96L3PufB:-N7KuSKx-frklzGe4pW-:bt1z6mr) ([raw file](https://github.com/gramineproject/gramine/blob/421c497f0f8cf56e30edd24f743808c3e279d79c/libos/src/libos_init.c#L429)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

No, this change looks wrong. `init_process_cmdline()` should take `const char**` as input. This basically tells the reader of this code and the compiler that "this argument is an input argument, the strings in this list are constant". Now you removed `const`, and the meaning changed -- now it is "this argument is an input/output argument, *maybe* this function will change the strings in this list".

So you should actually change `expanded_argv` variable to be `const char**`.
</blockquote></details>

Yes i get that. Its just that we will run into this casting issue somewhere down the line. Read my other comment on `init_stack`
___
*[`libos/src/libos_init.c` line 441 at r11](https://reviewable.io/reviews/gramineproject/gramine/722#-N7Ki-F62DoNPd1BTviD:-N7Ku4mN7nvGBCsSODNV:b-kp2k4u) ([raw file](https://github.com/gramineproject/gramine/blob/02a30849b34f1881bc3a20ad65d305fab288a12b/libos/src/libos_init.c#L441)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@aneessahib Also note that you have this typecast here.
</blockquote></details>

Yep - This is similar to what we are doing here. https://github.com/gramineproject/gramine/blob/cf8095d83b634f37d2c5f33a4d9a7881a11432bc/libos/src/sys/libos_exec.c#L125 
So to fix this whole casting issue - we are going to have to get to what we have in TODO.


<!-- Sent from Reviewable.io -->

2022-07-19 11:17 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/722)* status: 10 of 11 files reviewed, 13 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @boryspoplawski, @dimakuv, and @mkow)

___
*[`libos/src/libos_init.c` line 429 at r10](https://reviewable.io/reviews/gramineproject/gramine/722#-N77K2oO4RLx96L3PufB:-N7LAESJ-FX7PAMlqu5a:b-uq8fob) ([raw file](https://github.com/gramineproject/gramine/blob/421c497f0f8cf56e30edd24f743808c3e279d79c/libos/src/libos_init.c#L429)):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

Yes i get that. Its just that we will run into this casting issue somewhere down the line. Read my other comment on `init_stack`
</blockquote></details>

Hm. I'll let @mkow and @boryspoplawski decide on the correct type for `expanded_argv` and the function signatures. I'm unsure how they would like it to be fixed.


<!-- Sent from Reviewable.io -->

2022-07-19 11:56 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/722)* status: 9 of 11 files reviewed, 13 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @boryspoplawski, @dimakuv, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/722#-N77HvySEOHHDrp9gwjP:-N7LIZaC41db3LrVPbOE:byum42b) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@aneessahib Yep, please don't rename this branch. Just keep it in mind for the future, that you need not only a name-explanation for the branch (like `nonelf_entrypoint`) but also your nickname as a prefix (so it should have been `aneessahib/nonelf_entrypoint`).
</blockquote></details>

sure will do

___
___
*[`libos/test/regression/test_libos.py` line 217 at r11](https://reviewable.io/reviews/gramineproject/gramine/722#-N7KiOuwC0VBMta9k7wE:-N7LJ7VLDjnaM7PocjOj:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/02a30849b34f1881bc3a20ad65d305fab288a12b/libos/test/regression/test_libos.py#L217)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You forgot to change this test as well.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-21 11:32 UTC, boryspoplawski requested changes
> Reviewed 3 of 9 files at r11, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/722)* status: all files reviewed, 17 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @dimakuv, and @mkow)

___
*[`libos/src/libos_init.c` line 429 at r10](https://reviewable.io/reviews/gramineproject/gramine/722#-N77K2oO4RLx96L3PufB:-N7VT0bL1tuP4Ll6pfde:b-ctf2cb) ([raw file](https://github.com/gramineproject/gramine/blob/421c497f0f8cf56e30edd24f743808c3e279d79c/libos/src/libos_init.c#L429)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Hm. I'll let @mkow and @boryspoplawski decide on the correct type for `expanded_argv` and the function signatures. I'm unsure how they would like it to be fixed.
</blockquote></details>

Why the strings have to be `const`? They array should not strings, so this function should take `char* const*`
But see the other comments.
___
*[`libos/src/libos_init.c` line 370 at r12](https://reviewable.io/reviews/gramineproject/gramine/722#-N7VSjKP8IxTiA675o0k:-N7VSjKP8IxTiA675o0l:b-306g9z) ([raw file](https://github.com/gramineproject/gramine/blob/ebf1a477dff13e6b48aa0bef0952af6209ff1681/libos/src/libos_init.c#L370)):*
> ```C
> 
> noreturn void* libos_init(int argc, const char** argv, const char** envp) {
>     __UNUSED(argc);
> ```

If it's unused then please remove it.
___
*[`libos/src/libos_init.c` line 424 at r12](https://reviewable.io/reviews/gramineproject/gramine/722#-N7VTKkMAS9d1ukXJxBg:-N7VTKkMAS9d1ukXJxBh:b-crkjvw) ([raw file](https://github.com/gramineproject/gramine/blob/f0419a8652820bca664b575a9b6b93ccf2d878c0/libos/src/libos_init.c#L424)):*
> ```C
>     RUN_INIT(init_process, argc, argv);
>     RUN_INIT(init_mount_root);
>     RUN_INIT(init_threading);
> ```

Wait, you cannot just change order of initialization functions as you please, it's important to have this in correct order.
Why cannot `init_process_args` and `init_process_cmdline` run together with `init_stack`?
___
*[`libos/test/regression/test_libos.py` line 218 at r12](https://reviewable.io/reviews/gramineproject/gramine/722#-N7VUkws8d7dvyp5i1uO:-N7VUkws8d7dvyp5i1uP:b-2lk81g) ([raw file](https://github.com/gramineproject/gramine/blob/ebf1a477dff13e6b48aa0bef0952af6209ff1681/libos/test/regression/test_libos.py#L218)):*
> ```Python
> 
>     @unittest.skipIf(USES_MUSL, 'Test uses /bin/sh from the host which is usually built against'
>     'glibc')
> ```

Please align the string
___
*[`libos/test/regression/test_libos.py` line 227 at r12](https://reviewable.io/reviews/gramineproject/gramine/722#-N7VUoHw5EHjIKrFKzhE:-N7VUoHw5EHjIKrFKzhF:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/ebf1a477dff13e6b48aa0bef0952af6209ff1681/libos/test/regression/test_libos.py#L227)):*
> ```Python
> 
>     @unittest.skipIf(USES_MUSL, 'Test uses /bin/sh from the host which is usually built against'
>     'glibc')
> ```

ditto
___
*[`libos/test/regression/shebang_test_script.sh` line 2 at r12](https://reviewable.io/reviews/gramineproject/gramine/722#-N7VVclL98KFaBYLUL3P:-N7VVclL98KFaBYLUL3Q:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/ebf1a477dff13e6b48aa0bef0952af6209ff1681/libos/test/regression/shebang_test_script.sh#L2)):*
> ```Shell
> #!  /bin/sh
> scripts/foo.sh
> ```





_Suggestion:_
```Shell
#!/bin/sh

exec scripts/foo.sh
```


<!-- Sent from Reviewable.io -->

2022-07-21 12:59 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/722)* status: all files reviewed, 18 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @dimakuv, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/722#-N7VpuvjCiEkGGcvGVGW:-N7VpuvjCiEkGGcvGVGX:b4sl3kc) (no related file):*
I'm taking over this branch, to fix the `const` typecast issue.

___


<!-- Sent from Reviewable.io -->

2022-07-21 13:03 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/722)* status: all files reviewed, 18 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @dimakuv, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/722#-N7VpuvjCiEkGGcvGVGW:-N7Vqhmh4fTgeWu837L0:b-pdagdj) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I'm taking over this branch, to fix the `const` typecast issue.
</blockquote></details>

But I would rather fix other issues - they affect where we have these pointers

___


<!-- Sent from Reviewable.io -->

2022-07-21 13:52 UTC, dimakuv requested changes
> Reviewed 5 of 5 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/722)* status: all files reviewed, 18 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @boryspoplawski, @dimakuv, and @mkow)

___
*[`libos/src/libos_init.c` line 429 at r10](https://reviewable.io/reviews/gramineproject/gramine/722#-N77K2oO4RLx96L3PufB:-N7W0rdW2PhfMWeIVwJ_:blqcr4b) ([raw file](https://github.com/gramineproject/gramine/blob/421c497f0f8cf56e30edd24f743808c3e279d79c/libos/src/libos_init.c#L429)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why the strings have to be `const`? They array should not strings, so this function should take `char* const*`
But see the other comments.
</blockquote></details>

So this is a complicated change by itself. I will do it in a separate PR, blocking this PR until we merge that one.
___
*[`libos/src/libos_init.c` line 441 at r11](https://reviewable.io/reviews/gramineproject/gramine/722#-N7Ki-F62DoNPd1BTviD:-N7W0zla4uH3nQLGcqmK:b-vvy50m) ([raw file](https://github.com/gramineproject/gramine/blob/02a30849b34f1881bc3a20ad65d305fab288a12b/libos/src/libos_init.c#L441)):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

Yep - This is similar to what we are doing here. https://github.com/gramineproject/gramine/blob/cf8095d83b634f37d2c5f33a4d9a7881a11432bc/libos/src/sys/libos_exec.c#L125 
So to fix this whole casting issue - we are going to have to get to what we have in TODO.
</blockquote></details>

I am on it...
___
*[`libos/src/libos_init.c` line 370 at r12](https://reviewable.io/reviews/gramineproject/gramine/722#-N7VSjKP8IxTiA675o0k:-N7Vw0tE7eJoETRqPtIU:b4q6ar1) ([raw file](https://github.com/gramineproject/gramine/blob/ebf1a477dff13e6b48aa0bef0952af6209ff1681/libos/src/libos_init.c#L370)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

If it's unused then please remove it.
</blockquote></details>

Done. I'm not sure it's easier to read now, given introduced weirdness in the asm code...
___
*[`libos/test/regression/test_libos.py` line 218 at r12](https://reviewable.io/reviews/gramineproject/gramine/722#-N7VUkws8d7dvyp5i1uO:-N7Vr6bz0iMiu6Q0sEJh:b-qn2o4) ([raw file](https://github.com/gramineproject/gramine/blob/ebf1a477dff13e6b48aa0bef0952af6209ff1681/libos/test/regression/test_libos.py#L218)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please align the string
</blockquote></details>

Done (did similarly as to how other `skipIf`s are implemented in this file)
___
*[`libos/test/regression/test_libos.py` line 227 at r12](https://reviewable.io/reviews/gramineproject/gramine/722#-N7VUoHw5EHjIKrFKzhE:-N7VrAmE0sm5CNQsjoPs:b-qn2o4) ([raw file](https://github.com/gramineproject/gramine/blob/ebf1a477dff13e6b48aa0bef0952af6209ff1681/libos/test/regression/test_libos.py#L227)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done (did similarly as to how other `skipIf`s are implemented in this file)
___
*[`libos/test/regression/shebang_test_script.sh` line 2 at r12](https://reviewable.io/reviews/gramineproject/gramine/722#-N7VVclL98KFaBYLUL3P:-N7VdrzOEukPUfeoLtPZ:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/ebf1a477dff13e6b48aa0bef0952af6209ff1681/libos/test/regression/shebang_test_script.sh#L2)):*
> ```Shell
> #!  /bin/sh
> scripts/foo.sh
> ```

Done


<!-- Sent from Reviewable.io -->

2022-07-21 15:17 UTC, boryspoplawski requested changes
> Reviewed 4 of 5 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/722)* status: all files reviewed, 14 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @dimakuv, and @mkow)

___
*[`libos/src/libos_init.c` line 370 at r12](https://reviewable.io/reviews/gramineproject/gramine/722#-N7VSjKP8IxTiA675o0k:-N7WJeKR8h0SM4CVBU5h:besr2mb) ([raw file](https://github.com/gramineproject/gramine/blob/ebf1a477dff13e6b48aa0bef0952af6209ff1681/libos/src/libos_init.c#L370)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. I'm not sure it's easier to read now, given introduced weirdness in the asm code...
</blockquote></details>

What's weird about it?
___
*[`libos/test/regression/test_libos.py` line 218 at r12](https://reviewable.io/reviews/gramineproject/gramine/722#-N7VUkws8d7dvyp5i1uO:-N7WKFIA0491H6nirNmp:bkeq83g) ([raw file](https://github.com/gramineproject/gramine/blob/ebf1a477dff13e6b48aa0bef0952af6209ff1681/libos/test/regression/test_libos.py#L218)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done (did similarly as to how other `skipIf`s are implemented in this file)
</blockquote></details>

I don't like it, but it's probably some PEP requirement or something..


<!-- Sent from Reviewable.io -->

2022-07-21 15:20 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/722)* status: all files reviewed, 15 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @dimakuv, and @mkow)

___
*[`libos/src/libos_init.c` line 422 at r13](https://reviewable.io/reviews/gramineproject/gramine/722#-N7WL5oJBrxTEcmX9PFJ:-N7WL5oJBrxTEcmX9PFK:beo8b22) ([raw file](https://github.com/gramineproject/gramine/blob/0d88aa7e0fa9453e736ef6fb3bfb8ef47f727e0a/libos/src/libos_init.c#L422)):*
> ```C
> 
>     RUN_INIT(init_ipc);
>     RUN_INIT(init_process);
> ```

Testing Reviewable, ignore this comment please



_Suggestion:_
```C
    RUN_INIT(aaa);
    
    RUN_INIT(bbb);
```


<!-- Sent from Reviewable.io -->

2022-07-21 15:22 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/722)* status: all files reviewed, 15 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @dimakuv, and @mkow)

___
*[`libos/src/libos_init.c` line 422 at r13](https://reviewable.io/reviews/gramineproject/gramine/722#-N7WLS0s46HMOgAhOIYJ:-N7WLS0s46HMOgAhOIYK:beo8b22) ([raw file](https://github.com/gramineproject/gramine/blob/0d88aa7e0fa9453e736ef6fb3bfb8ef47f727e0a/libos/src/libos_init.c#L422)):*
> ```C
> 
>     RUN_INIT(init_ipc);
>     RUN_INIT(init_process);
> ```

Testing Reviewable, ignore this comment please



_Suggestion:_
```C
    RUN_INIT(aaaa);

    RUN_INIT(bbbb);
```


<!-- Sent from Reviewable.io -->

2022-07-21 15:37 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/722)* status: all files reviewed, 14 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @boryspoplawski, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/722#-N7VpuvjCiEkGGcvGVGW:-N7WOvR33u_NVAPbhlLD:b3c2vif) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

But I would rather fix other issues - they affect where we have these pointers
</blockquote></details>

Blocking this PR on this prerequisite: https://github.com/gramineproject/gramine/pull/777

___


<!-- Sent from Reviewable.io -->

2022-07-22 07:40 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/722)* status: all files reviewed, 14 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @boryspoplawski, and @mkow)

___
*[`libos/src/libos_init.c` line 429 at r10](https://reviewable.io/reviews/gramineproject/gramine/722#-N77K2oO4RLx96L3PufB:-N7ZqECb3JHPxAhvw_yC:b-9morzx) ([raw file](https://github.com/gramineproject/gramine/blob/421c497f0f8cf56e30edd24f743808c3e279d79c/libos/src/libos_init.c#L429)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

So this is a complicated change by itself. I will do it in a separate PR, blocking this PR until we merge that one.
</blockquote></details>

I created a PR: https://github.com/gramineproject/gramine/pull/777
___
*[`libos/src/libos_init.c` line 370 at r12](https://reviewable.io/reviews/gramineproject/gramine/722#-N7VSjKP8IxTiA675o0k:-N7Zq3nY2KkxxGRmEImk:b8a7anl) ([raw file](https://github.com/gramineproject/gramine/blob/ebf1a477dff13e6b48aa0bef0952af6209ff1681/libos/src/libos_init.c#L370)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

What's weird about it?
</blockquote></details>

Using `argc` passed by PAL to calculate `envp`. But maybe it's normal, I'm just too used to C conventions...


<!-- Sent from Reviewable.io -->

2022-07-26 09:08 UTC, dimakuv approved these changes
> Reviewed 8 of 8 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/722)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/722#-N7VpuvjCiEkGGcvGVGW:-N7tkU6BCoTBmVkc1Gw3:b-6ltctw) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Blocking this PR on this prerequisite: https://github.com/gramineproject/gramine/pull/777
</blockquote></details>

Done, rebased on top of #777

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/722#-N7tkpl-CTChaI8hFfuN:-N7tkpl-CTChaI8hFfuO:bjxvdk9) (no related file):*
NOTE: I rebased on top of #777 (current master), and also modified the PR substantially, so at this point it is easier to review from the very first revision!

___
___
*[`libos/include/libos_handle.h` line 281 at r14](https://reviewable.io/reviews/gramineproject/gramine/722#-N7tjxNGBXmg7ahhehTe:-N7tjxNHDe4Cn9vLi2Za:b4cj28a) ([raw file](https://github.com/gramineproject/gramine/blob/b3f65d5c1b05535b63872acc5220a53858de37ef/libos/include/libos_handle.h#L281)):*
> ```objc
> int init_handle(void);
> int init_std_handles(void);
> int init_exec_handle(const char* const* argv, char*** out_new_argv);
> ```

FYI: I had to separate `init_important_handles()` into two functions:
1. It is more readable.
2. More importantly, `init_exec_handle()` also expands the entrypoint if it is a shebang, expanding the arguments as well.
___
*[`libos/src/libos_init.c` line 429 at r10](https://reviewable.io/reviews/gramineproject/gramine/722#-N77K2oO4RLx96L3PufB:-N7tkIqZ9x3uHjUG-AIu:b-8ugvgc) ([raw file](https://github.com/gramineproject/gramine/blob/421c497f0f8cf56e30edd24f743808c3e279d79c/libos/src/libos_init.c#L429)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I created a PR: https://github.com/gramineproject/gramine/pull/777
</blockquote></details>

Done. Rebased on top of #777.
___
*[`libos/src/libos_init.c` line 441 at r11](https://reviewable.io/reviews/gramineproject/gramine/722#-N7Ki-F62DoNPd1BTviD:-N7tkLu86892dU9WCa4m:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/02a30849b34f1881bc3a20ad65d305fab288a12b/libos/src/libos_init.c#L441)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I am on it...
</blockquote></details>

Done.
___
*[`libos/src/libos_init.c` line 424 at r12](https://reviewable.io/reviews/gramineproject/gramine/722#-N7VTKkMAS9d1ukXJxBg:-N7tkDLg7rrcSagA4baG:b-i4kskx) ([raw file](https://github.com/gramineproject/gramine/blob/f0419a8652820bca664b575a9b6b93ccf2d878c0/libos/src/libos_init.c#L424)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Wait, you cannot just change order of initialization functions as you please, it's important to have this in correct order.
Why cannot `init_process_args` and `init_process_cmdline` run together with `init_stack`?
</blockquote></details>

Done. Not exactly as Borys wrote, but without any re-ordering.
___
*[`libos/src/sys/libos_exec.c` line 126 at r14](https://reviewable.io/reviews/gramineproject/gramine/722#-N7tkduDAuL9Q7lrsgMk:-N7tkduDAuL9Q7lrsgMl:bolplqx) ([raw file](https://github.com/gramineproject/gramine/blob/b3f65d5c1b05535b63872acc5220a53858de37ef/libos/src/sys/libos_exec.c#L126)):*
> ```C
>     elf_auxv_t* new_auxv;
> 
>     ret = init_process_cmdline((const char* const*)argv);
> ```

FYI: This was a missing functionality. We forgot to update `/proc/self/cmdline` after `execve()`


<!-- Sent from Reviewable.io -->

2022-07-26 09:09 UTC, dimakuv commented
Jenkins, test this please

2022-07-26 12:53 UTC, mkow requested changes
> Reviewed 3 of 9 files at r11, 2 of 5 files at r13, 8 of 8 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/722)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @aneessahib, @boryspoplawski, and @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/722#-N7uVHCGAXO_fO2ugozH:-N7uVHCGAXO_fO2ugozI:bs8z9q8) (no related file):*
Please add "Fixes https://github.com/gramineproject/gramine/issues/320" to the PR description.

___
___
*[`-- commits` line 4 at r14](https://reviewable.io/reviews/gramineproject/gramine/722#-N7uODfpDsJJGvaImg3X):*
@dimakuv: You'll need to add `Co-authored-by` and your sign-off here.
___
*[`libos/test/regression/run_script.manifest.template` line 3 at r10](https://reviewable.io/reviews/gramineproject/gramine/722#-N77N2Mv0R_d4VSDENp-:-N7uPAuH1CFFS1b5yT85:b-wchqdi) ([raw file](https://github.com/gramineproject/gramine/blob/421c497f0f8cf56e30edd24f743808c3e279d79c/libos/test/regression/run_script.manifest.template#L3)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> So, summarizing: in this particular case we don't have argv specified anywhere, so we need to pick some default. And IMO `argv = [entrypoint]` is a good one.

I agree with this. But didn't we derail the conversation? The PR is called "Support running scripts as the entrypoint", and what we're discussing here is a different feature. We should make a new PR for it.
</blockquote></details>

@dimakuv: Could you create an issue for this and then fix it (after this PR gets merged), while you're on it?


<!-- Sent from Reviewable.io -->

2022-07-26 13:45 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/722)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/722#-N7uVHCGAXO_fO2ugozH:-N7ukI0N7G0xFd25OznU:bb6un1j) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please add "Fixes https://github.com/gramineproject/gramine/issues/320" to the PR description.
</blockquote></details>

Done

___
___
*[`-- commits` line 4 at r14](https://reviewable.io/reviews/gramineproject/gramine/722#-N7uODfpDsJJGvaImg3X):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

@dimakuv: You'll need to add `Co-authored-by` and your sign-off here.
</blockquote></details>

Blocked myself on this.
___
*[`libos/test/regression/run_script.manifest.template` line 3 at r10](https://reviewable.io/reviews/gramineproject/gramine/722#-N77N2Mv0R_d4VSDENp-:-N7ukBJDALz_qQTRoqIS:b-lrl1eq) ([raw file](https://github.com/gramineproject/gramine/blob/421c497f0f8cf56e30edd24f743808c3e279d79c/libos/test/regression/run_script.manifest.template#L3)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

@dimakuv: Could you create an issue for this and then fix it (after this PR gets merged), while you're on it?
</blockquote></details>

Done: https://github.com/gramineproject/gramine/issues/795

Yes, I can do a follow up PR.


<!-- Sent from Reviewable.io -->

2022-07-26 15:52 UTC, boryspoplawski requested changes
> Reviewed 8 of 8 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/722)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @aneessahib and @mkow)

___
*[`libos/src/libos_init.c` line 370 at r14](https://reviewable.io/reviews/gramineproject/gramine/722#-N7uwymj2NGT1d2a85Ak:-N7uwymj2NGT1d2a85Al:bpscmyw) ([raw file](https://github.com/gramineproject/gramine/blob/b3f65d5c1b05535b63872acc5220a53858de37ef/libos/src/libos_init.c#L370)):*
> ```C
> 
> noreturn void libos_init(const char* const* argv, const char* const* envp) {
>     int ret;
> ```

Why this moved here? Not opposing, just curious, what's the point
___
*[`libos/src/libos_init.c` line 430 at r14](https://reviewable.io/reviews/gramineproject/gramine/722#-N7uwqh_Aj9Fzp1wc3FI:-N7uwqh_Aj9Fzp1wc3FJ:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/b3f65d5c1b05535b63872acc5220a53858de37ef/libos/src/libos_init.c#L430)):*
> ```C
>     RUN_INIT(init_std_handles);
> 
>     char** expanded_argv;
> ```





_Suggestion:_
```C
char** expanded_argv = NULL;
```
___
*[`libos/src/bookkeep/libos_handle.c` line 72 at r14](https://reviewable.io/reviews/gramineproject/gramine/722#-N7vCKa-63S6JeZYTBpx:-N7vCKa-63S6JeZYTBpy:be9h7av) ([raw file](https://github.com/gramineproject/gramine/blob/b3f65d5c1b05535b63872acc5220a53858de37ef/libos/src/bookkeep/libos_handle.c#L72)):*
> ```C
> }
> 
> int init_exec_handle(const char* const* argv, char*** out_new_argv) {
> ```

Actually, why this is a step separate from `init_elf_objects()`?


<!-- Sent from Reviewable.io -->

2022-07-26 17:02 UTC, mkow submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/722)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @aneessahib)



<!-- Sent from Reviewable.io -->

2022-07-26 18:06 UTC, dimakuv reviewed
> Reviewed 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/722)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib and @boryspoplawski)

___
*[`libos/src/libos_init.c` line 370 at r14](https://reviewable.io/reviews/gramineproject/gramine/722#-N7uwymj2NGT1d2a85Ak:-N7vedk0A_w2pMrIiaG-:b-aj2oyo) ([raw file](https://github.com/gramineproject/gramine/blob/b3f65d5c1b05535b63872acc5220a53858de37ef/libos/src/libos_init.c#L370)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why this moved here? Not opposing, just curious, what's the point
</blockquote></details>

Actually, leftover from an intermediate solution (which used `ret` extensively). Reverted, since this only clatters the PR.
___
*[`libos/src/libos_init.c` line 430 at r14](https://reviewable.io/reviews/gramineproject/gramine/722#-N7uwqh_Aj9Fzp1wc3FI:-N7vf8dTEW5nBLpOJt2p:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/b3f65d5c1b05535b63872acc5220a53858de37ef/libos/src/libos_init.c#L430)):*
> ```C
>     RUN_INIT(init_std_handles);
> 
>     char** expanded_argv;
> ```

Done
___
*[`libos/src/bookkeep/libos_handle.c` line 72 at r14](https://reviewable.io/reviews/gramineproject/gramine/722#-N7vCKa-63S6JeZYTBpx:-N7vfOPZ03eVBG6Of4NZ:b-rkgs7a) ([raw file](https://github.com/gramineproject/gramine/blob/b3f65d5c1b05535b63872acc5220a53858de37ef/libos/src/bookkeep/libos_handle.c#L72)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Actually, why this is a step separate from `init_elf_objects()`?
</blockquote></details>

No idea, but I wouldn't clatter this PR with the merge of `init_exec_handle()` and `init_elf_objects()`. Deserves a separate PR.


<!-- Sent from Reviewable.io -->

2022-07-26 19:16 UTC, boryspoplawski submitted a review, later dismissed
> Reviewed 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/722)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @aneessahib and @dimakuv)

___
*[`libos/src/bookkeep/libos_handle.c` line 72 at r14](https://reviewable.io/reviews/gramineproject/gramine/722#-N7vCKa-63S6JeZYTBpx:-N7vw0FxEgcWn8riXPy7:b-z26pjn) ([raw file](https://github.com/gramineproject/gramine/blob/b3f65d5c1b05535b63872acc5220a53858de37ef/libos/src/bookkeep/libos_handle.c#L72)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

No idea, but I wouldn't clatter this PR with the merge of `init_exec_handle()` and `init_elf_objects()`. Deserves a separate PR.
</blockquote></details>

But you already reworked how it behaves in this PR...
Well, approving anyway


<!-- Sent from Reviewable.io -->

2022-07-27 06:45 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/722)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[`-- commits` line 4 at r14](https://reviewable.io/reviews/gramineproject/gramine/722#-N7uODfpDsJJGvaImg3X):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Blocked myself on this.
</blockquote></details>

Done
___
*[`libos/src/bookkeep/libos_handle.c` line 72 at r14](https://reviewable.io/reviews/gramineproject/gramine/722#-N7vCKa-63S6JeZYTBpx:-N7yOY4-7E2q97UXd2Dh:b-1jlhnh) ([raw file](https://github.com/gramineproject/gramine/blob/b3f65d5c1b05535b63872acc5220a53858de37ef/libos/src/bookkeep/libos_handle.c#L72)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

But you already reworked how it behaves in this PR...
Well, approving anyway
</blockquote></details>

My main problem is that `init_exec_handle()` and `init_elf_objects()` are called far away from each other during LibOS init. Rearranging the order of function calls may break something unexpected, and we'll spend time in debugging that.


<!-- Sent from Reviewable.io -->

2022-07-27 06:46 UTC, dimakuv commented
Jenkins, test this please

2022-07-27 08:55 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/722)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-07-27 09:13 UTC, merged