[PAL] Simplify 'file_getname',same for 'dir_getname'
gramineproject/gramine pull request #724
Opened 2022-07-05 02:15 UTC by billionairiam

## Description of the changes 
The function `file_getname` defined [here](https://github.com/gramineproject/gramine/blob/839ba4eef309350c41005e670562193a5f6d0767/pal/src/host/linux/pal_files.c#L260) and 'dir_getname' defined [here](https://github.com/gramineproject/gramine/blob/839ba4eef309350c41005e670562193a5f6d0767/pal/src/host/linux/pal_files.c#L488).
you’ll see that there are two actions:
1. First copy **URI_PREFIX_FILE** into buffer and return the end-of-string in the variable `tmp`
2. Then copy `handle->file.realpath` into buffer (after **URI_PREFIX_FILE** string)

The problem with this code is that it is very obscure. Mostly because of this weird : 
[function](https://github.com/gramineproject/gramine/blob/5a39aee217955701b412d4ff807c32da8e53ab94/common/include/api.h#L277)
In reality, we can just use the `alloc_concat()` [function](https://github.com/gramineproject/gramine/blob/839ba4eef309350c41005e670562193a5f6d0767/common/src/string/utils.c#L19) instead of all that code.

2022-07-05 02:42 UTC, guzongmin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/724)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @billionairiam)

___
*[`pal/src/host/linux/db_files.c` line 504 at r1](https://reviewable.io/reviews/gramineproject/gramine/724#-N6BD_3z-LPPajvPXQta:-N6BD_3z-LPPajvPXQtb:b-a4yz5z) ([raw file](https://github.com/gramineproject/gramine/blob/17eb82affa48cacab7b99979fa7a4c38f9c16e0c/pal/src/host/linux/db_files.c#L504)):*
> ```C
> 
> static int dir_getname(PAL_HANDLE handle, char* buffer, size_t count) {
>     if (!handle->file.realpath)
> ```

Weirdly, you changed the "dir" to "file"—same comments for the left code.


<!-- Sent from Reviewable.io -->

2022-07-05 02:47 UTC, billionairiam commented
> 

Thanks zongmin!

2022-07-05 02:48 UTC, guzongmin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/724)* status: 0 of 1 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @billionairiam)

___
*[`pal/src/host/linux/db_files.c` line 281 at r1](https://reviewable.io/reviews/gramineproject/gramine/724#-N6BF7Er0oFTG2FXwVGQ:-N6BF7Er0oFTG2FXwVGR:b-ykug0) ([raw file](https://github.com/gramineproject/gramine/blob/17eb82affa48cacab7b99979fa7a4c38f9c16e0c/pal/src/host/linux/db_files.c#L281)):*
> ```C
>         return -ENOMEM;
> 
>     if(strlen(tmp)+1>count)
> ```

The value strlen(tmp) is used three times. Maybe we can add this line of code: tmp_len = strlen(tmp);
___
*[`pal/src/host/linux/db_files.c` line 286 at r1](https://reviewable.io/reviews/gramineproject/gramine/724#-N6BErzu2F1epZcI94yd:-N6BErzu2F1epZcI94ye:b-k14ldu) ([raw file](https://github.com/gramineproject/gramine/blob/17eb82affa48cacab7b99979fa7a4c38f9c16e0c/pal/src/host/linux/db_files.c#L286)):*
> ```C
>     memcpy(buffer,tmp,strlen(tmp)+1);
> 
>     return strlen(tmp);
> ```

Do you need to free the memory allocated for the tmp before return?


<!-- Sent from Reviewable.io -->

2022-07-05 05:41 UTC, guzongmin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/724)* status: 0 of 3 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), period found at the end of a one-liner (waiting on @billionairiam)

___
*[`pal/src/host/linux/pal_files.c` line 270 at r3](https://reviewable.io/reviews/gramineproject/gramine/724#-N6BrpJZ0yx_3Zj13pTx:-N6BrpJZ0yx_3Zj13pTy:b-ml116n) ([raw file](https://github.com/gramineproject/gramine/blob/5af823f4f340253ed25a6b6393f992edc6c4c6f0/pal/src/host/linux/pal_files.c#L270)):*
> ```C
> 
>     size_t tmp_len=strlen(tmp);
>     if(tmp_len+1>count)
> ```

Memory leak. It would help if you freed the tmp before returning the error code.


<!-- Sent from Reviewable.io -->

2022-07-05 05:43 UTC, guzongmin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/724)* status: 0 of 3 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), period found at the end of a one-liner (waiting on @billionairiam)

___
*[`-- commits` line 5 at r3](https://reviewable.io/reviews/gramineproject/gramine/724#-N6BsSA23TqM6T5zuoQA):*
Please remove those useless commits.


<!-- Sent from Reviewable.io -->

2022-07-05 05:48 UTC, billionairiam reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/724)* status: 0 of 3 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), period found at the end of a one-liner (waiting on @guzongmin)

___
*[`-- commits` line 5 at r3](https://reviewable.io/reviews/gramineproject/gramine/724#-N6BsSA23TqM6T5zuoQA):*
<details><summary><i>Previously, guzongmin (Zongmin.Gu) wrote…</i></summary><blockquote>

Please remove those useless commits.
</blockquote></details>

Done.
___
*[`pal/src/host/linux/pal_files.c` line 270 at r3](https://reviewable.io/reviews/gramineproject/gramine/724#-N6BrpJZ0yx_3Zj13pTx:-N6Btj7o8VDoWW7DWty4:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/5af823f4f340253ed25a6b6393f992edc6c4c6f0/pal/src/host/linux/pal_files.c#L270)):*
<details><summary><i>Previously, guzongmin (Zongmin.Gu) wrote…</i></summary><blockquote>

Memory leak. It would help if you freed the tmp before returning the error code.
</blockquote></details>

Done.
___
*[`pal/src/host/linux/db_files.c` line 281 at r1](https://reviewable.io/reviews/gramineproject/gramine/724#-N6BF7Er0oFTG2FXwVGQ:-N6BtkGN0HAzd7_FvegU:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/17eb82affa48cacab7b99979fa7a4c38f9c16e0c/pal/src/host/linux/db_files.c#L281)):*
<details><summary><i>Previously, guzongmin (Zongmin.Gu) wrote…</i></summary><blockquote>

The value strlen(tmp) is used three times. Maybe we can add this line of code: tmp_len = strlen(tmp);
</blockquote></details>

Done.
___
*[`pal/src/host/linux/db_files.c` line 286 at r1](https://reviewable.io/reviews/gramineproject/gramine/724#-N6BErzu2F1epZcI94yd:-N6Btjyb-KBJ-oIyv1zE:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/17eb82affa48cacab7b99979fa7a4c38f9c16e0c/pal/src/host/linux/db_files.c#L286)):*
<details><summary><i>Previously, guzongmin (Zongmin.Gu) wrote…</i></summary><blockquote>

Do you need to free the memory allocated for the tmp before return?
</blockquote></details>

Done.
___
*[`pal/src/host/linux/db_files.c` line 504 at r1](https://reviewable.io/reviews/gramineproject/gramine/724#-N6BD_3z-LPPajvPXQta:-N6BtjfWAi45l90ZvU4r:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/17eb82affa48cacab7b99979fa7a4c38f9c16e0c/pal/src/host/linux/db_files.c#L504)):*
<details><summary><i>Previously, guzongmin (Zongmin.Gu) wrote…</i></summary><blockquote>

Weirdly, you changed the "dir" to "file"—same comments for the left code.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-05 11:18 UTC, dimakuv requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/724)* status: 0 of 3 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), period found at the end of a one-liner (waiting on @billionairiam and @guzongmin)

___
*[`-- commits` line 5 at r3](https://reviewable.io/reviews/gramineproject/gramine/724#-N6BsSA23TqM6T5zuoQA):*
<details><summary><i>Previously, billionairiam wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done. When you add modifications to your original commit, please use `git fixup` flow: https://blog.sebastian-daschner.com/entries/git-commit-fixup-autosquash
___
*[`pal/src/host/linux/pal_files.c` line 277 at r3](https://reviewable.io/reviews/gramineproject/gramine/724#-N6D3UdY5-uIAFSdCLv0:-N6D3UdY5-uIAFSdCLv1:b-tp1btw) ([raw file](https://github.com/gramineproject/gramine/blob/5af823f4f340253ed25a6b6393f992edc6c4c6f0/pal/src/host/linux/pal_files.c#L277)):*
> ```C
> 
>     return tmp_len;
> }
> ```

Sorry, I know that I suggested this `alloc_concat()` way of rewriting this function, but now I see that it only got more complicated and less readable.

Here is my suggested way to rewrite these functions:
```
    if (!handle->file.realpath)
        return 0;

    size_t realpath_size = strlen(handle->file.realpath) + 1;
    if (count < URI_PREFIX_FILE_LEN + realpath_size)
        return -PAL_ERROR_TOOLONG;

    memcpy(buffer, URI_PREFIX_FILE, count);
    memcpy(buffer + URI_PREFIX_FILE_LEN, handle->file.realpath, realpath_size);
    return URI_PREFIX_FILE_LEN + realpath_size - 1; /* return string length, not size */
```

I suggest to close this PR (as all its code and its description are incorrect). And create a new PR with the new code and new description.


<!-- Sent from Reviewable.io -->

2022-07-05 12:55 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/724)* status: 0 of 3 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), period found at the end of a one-liner (waiting on @billionairiam and @guzongmin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/724#-N6DQOkpCPNYyW3nI0qq:-N6DQOkq8gja7u5I3SSe:b-kbo930) (no related file):*
@billionairiam: In https://github.com/gramineproject/gramine/pull/707 review we asked you to read our contributing guidelines, but it seems you didn't do this. Blocking this PR until you do.

___


<!-- Sent from Reviewable.io -->

2022-07-12 06:41 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/724)* status: 0 of 3 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), period found at the end of a one-liner, "fixup! " found in commit messages' one-liners (waiting on @billionairiam and @guzongmin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/724#-N6l6J7a0zVhS1dWipPR:-N6l6J7a0zVhS1dWipPS:b-hg2zg2) (no related file):*
@billionairiam Please follow our guidelines (check out documentation) and suggestions (read our PR comments carefully), otherwise this is counter-productive.

You made several mistakes in the latest iteration of this PR:
1. You ignore my comment `I suggest to close this PR ...`.
2. Even if you decided to modify everything in this already-existing PR, you ignored the second part of my comment: `...with new description` -- the PR description didn't change yet.
3. You incorrectly created a fixup commit -- the fixup should be on the *first* (main) commit of the PR, not on some random/last commit in the series. Basically, you did a fixup to a fixup, which is a wrong flow. Please see how other PRs are updated.
4. After your changes, you did a git push, but you didn't mark your work as "Done" in Reviewable. The reviewers have no way of knowing whether you're ready for a next round of review of not, until you leave replies to their comments.
5. Why do you still have a `billionairiam <liang3.ma@intel.com>` sign-off message? It should be your name: `Liang Ma <liang3.ma@intel.com>`.

___


<!-- Sent from Reviewable.io -->

2022-07-12 06:54 UTC, billionairiam reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/724)* status: 0 of 3 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), period found at the end of a one-liner, "fixup! " found in commit messages' one-liners (waiting on @billionairiam, @dimakuv, @guzongmin, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/724#-N6DQOkpCPNYyW3nI0qq:-N6lAhxyACHZFyDT2WMI:b-896fix) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

@billionairiam: In https://github.com/gramineproject/gramine/pull/707 review we asked you to read our contributing guidelines, but it seems you didn't do this. Blocking this PR until you do.
</blockquote></details>

Done.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/724#-N6l6J7a0zVhS1dWipPR:-N6lAiZo8fBTowd3gGDS:b-896fix) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@billionairiam Please follow our guidelines (check out documentation) and suggestions (read our PR comments carefully), otherwise this is counter-productive.

You made several mistakes in the latest iteration of this PR:
1. You ignore my comment `I suggest to close this PR ...`.
2. Even if you decided to modify everything in this already-existing PR, you ignored the second part of my comment: `...with new description` -- the PR description didn't change yet.
3. You incorrectly created a fixup commit -- the fixup should be on the *first* (main) commit of the PR, not on some random/last commit in the series. Basically, you did a fixup to a fixup, which is a wrong flow. Please see how other PRs are updated.
4. After your changes, you did a git push, but you didn't mark your work as "Done" in Reviewable. The reviewers have no way of knowing whether you're ready for a next round of review of not, until you leave replies to their comments.
5. Why do you still have a `billionairiam <liang3.ma@intel.com>` sign-off message? It should be your name: `Liang Ma <liang3.ma@intel.com>`.
</blockquote></details>

Done.

___


<!-- Sent from Reviewable.io -->

2022-07-27 08:45 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/724)* status: 0 of 3 files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), period found at the end of a one-liner, "fixup! " found in commit messages' one-liners (waiting on @billionairiam, @dimakuv, @guzongmin, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/724#-N7yp9XnCcTNIS-9XIJi:-N7yp9XnCcTNIS-9XIJj:b-9cf07o) (no related file):*
@billionairiam Let me close this PR, and let's create a new one, with everything done properly this time.

___


<!-- Sent from Reviewable.io -->

2022-07-27 08:45 UTC, closed without merging