[tests] Fix detecting LTP timeouts
gramineproject/gramine pull request #732
Opened 2022-07-06 14:54 UTC by NieDzejkob

## Description of the changes 

Apparently we didn't test the case when the tests are actually timing out. This fixes a subtle bug in the handling of that.

## How to test this PR? 

Artificially reduce the timeout of a test in `ltp.cfg` and observe the test suite behaving correctly.

2022-07-13 18:03 UTC, boryspoplawski requested changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/732)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @NieDzejkob)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/732#-N6JC0O188_Pjb0fv5BF:-N6si09v-EwHiFZN-hRg:b1eowia) (no related file):*
<details><summary><i>Previously, NieDzejkob (Jakub Kądziołka) wrote…</i></summary><blockquote>

Hmm. Both should work, now that I think about it. Do you have a link handy to a run where it broke previously?
</blockquote></details>

No and I'm afraid they might be gone with the amount of runs we do lately. You'll need to check Jenkins to confirm

___
___
*[`python/graminelibos/regression.py` line 101 at r2](https://reviewable.io/reviews/gramineproject/gramine/732#-N6siXdq6oX7LgilI0Qg:-N6siXdq6oX7LgilI0Qh:bunex40) ([raw file](https://github.com/gramineproject/gramine/blob/f513023a70cd487f42747b7bf36ed4bb1db3c37c/python/graminelibos/regression.py#L101)):*
> ```Python
>             proc.wait(time_remaining)
> 
>         time_remaining = time_end - time.time()
> ```

Maybe indent this to be inside `if`? looks a bit weird now


<!-- Sent from Reviewable.io -->

2022-07-13 18:08 UTC, boryspoplawski requested changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/732)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @NieDzejkob)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/732#-N6JC0O188_Pjb0fv5BF:-N6sjjVDBONXOtGr8N0q:bfxh1yw) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

No and I'm afraid they might be gone with the amount of runs we do lately. You'll need to check Jenkins to confirm
</blockquote></details>

Another PR just failed with it: graphene-debug-18.04/8146

___


<!-- Sent from Reviewable.io -->

2022-07-13 20:01 UTC, NieDzejkob reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/732)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/732#-N6JC0O188_Pjb0fv5BF:-N6t4sqn5qSqIh3BM55-:bj63a6o) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Another PR just failed with it: graphene-debug-18.04/8146
</blockquote></details>

Ah, looks like that's because `fdatasync01` is only one test case and the only output is after it passes. The test is quite quick, too — 0.02 to 0.4s, depending on which timestamps you're looking at. While `fcntl14` *might* be slowness causing a timeout, `fdatasync01` sounds like a legitimate deadlock.

___
___
*[`python/graminelibos/regression.py` line 101 at r2](https://reviewable.io/reviews/gramineproject/gramine/732#-N6siXdq6oX7LgilI0Qg:-N6sjz0b9RrJq-zr0XgI:b18ipo0) ([raw file](https://github.com/gramineproject/gramine/blob/f513023a70cd487f42747b7bf36ed4bb1db3c37c/python/graminelibos/regression.py#L101)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Maybe indent this to be inside `if`? looks a bit weird now
</blockquote></details>

Okay, how about this then?


<!-- Sent from Reviewable.io -->

2022-07-13 23:49 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/732)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)



<!-- Sent from Reviewable.io -->

2022-07-14 00:05 UTC, boryspoplawski submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/732)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2022-07-14 07:36 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/732)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2022-07-14 13:47 UTC, merged