[nasm] Make stack nonexecutable
gramineproject/gramine pull request #736
Opened 2022-07-07 13:25 UTC by boryspoplawski

## Description of the changes 
On x64 stack is executable by default, unless we specify a special GNU-stack section.

## How to test this PR? 
Check `GNU_STACK` section (e.g. using `readelf`) of e.g. `libsysdb.so` before and after this PR.

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/736)

2022-07-07 13:37 UTC, mkow approved these changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/736)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski and @dimakuv)

___
*[`common/src/arch/x86_64/no_exec_stack.nasm` line 1 at r1](https://reviewable.io/reviews/gramineproject/gramine/736#-N6Nr5S78Eq88E-eNDYB:-N6Ns25e7wpQU-78x2sn:b25rte2) ([raw file](https://github.com/gramineproject/gramine/blob/156e1bc95c92ece46b780dccd0f722600e3b2705/common/src/arch/x86_64/no_exec_stack.nasm#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Stack is `nowrite`? How is this possible, or do I misunderstand the docs: `write defines the section to be one which should be writable when the program is run. nowrite defines it as one which should not.` ?
</blockquote></details>

This is only about `.note.GNU-stack` section, not about the stack itself (I think).


<!-- Sent from Reviewable.io -->

2022-07-07 13:38 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/736)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

___
*[`common/src/arch/x86_64/no_exec_stack.nasm` line 1 at r1](https://reviewable.io/reviews/gramineproject/gramine/736#-N6Nr5S78Eq88E-eNDYB:-N6NsYnzBfhZ14XiMbMj:b-arvgei) ([raw file](https://github.com/gramineproject/gramine/blob/156e1bc95c92ece46b780dccd0f722600e3b2705/common/src/arch/x86_64/no_exec_stack.nasm#L1)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This is only about `.note.GNU-stack` section, not about the stack itself (I think).
</blockquote></details>

Well, I'm looking at https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/arch/arm/kernel/elf.c?h=v5.17&id=f443e374ae131c168a065ea1748feac6b2e76613#n84 and it seems to say that this section should have `RW`.


<!-- Sent from Reviewable.io -->

2022-07-07 13:42 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/736)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

___
*[`common/src/arch/x86_64/no_exec_stack.nasm` line 1 at r1](https://reviewable.io/reviews/gramineproject/gramine/736#-N6Nr5S78Eq88E-eNDYB:-N6NtEegAHuMuO5oD6zM:b9qw5xe) ([raw file](https://github.com/gramineproject/gramine/blob/156e1bc95c92ece46b780dccd0f722600e3b2705/common/src/arch/x86_64/no_exec_stack.nasm#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Well, I'm looking at https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/arch/arm/kernel/elf.c?h=v5.17&id=f443e374ae131c168a065ea1748feac6b2e76613#n84 and it seems to say that this section should have `RW`.
</blockquote></details>

Interesting, seems you're right. I actually thought that only the presence of this section matters, not it's permissions.
@boryspoplawski: please fix :)


<!-- Sent from Reviewable.io -->

2022-07-07 14:14 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/736)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @mkow)

___
*[`common/src/arch/x86_64/no_exec_stack.nasm` line 1 at r1](https://reviewable.io/reviews/gramineproject/gramine/736#-N6Nrd7IBTwQJ1Jh22I1:-N6Nxl9lAA2WBVuEsh-L:b-1f5vll) ([raw file](https://github.com/gramineproject/gramine/blob/156e1bc95c92ece46b780dccd0f722600e3b2705/common/src/arch/x86_64/no_exec_stack.nasm#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Same question for `progbits`... Docs says this: `progbits defines the section to be one with explicit contents stored in the object file: an ordinary code or data section, for example, nobits defines the section to be one with no explicit contents given, such as a BSS section.`
</blockquote></details>

With `noalloc` I believe this is irrelevant (i.e. exact setting does not matter). We can remove it (but it's default so it will be set anyway).
___
*[`common/src/arch/x86_64/no_exec_stack.nasm` line 1 at r1](https://reviewable.io/reviews/gramineproject/gramine/736#-N6Nr5S78Eq88E-eNDYB:-N6NyKSx73350pTgID_l:b21byqo) ([raw file](https://github.com/gramineproject/gramine/blob/156e1bc95c92ece46b780dccd0f722600e3b2705/common/src/arch/x86_64/no_exec_stack.nasm#L1)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Interesting, seems you're right. I actually thought that only the presence of this section matters, not it's permissions.
@boryspoplawski: please fix :)
</blockquote></details>

The only bit that matters is `exec`, rest of them are ignored. This is what I've always used (admittedly I probably copied it from internet) and it worked as intended.
If you want I can remove `progbits`.
What about `nowrite`? Do you wan to have `write` or remove it (to have default `nowrite`, which we do not care about, because kernel will ignore it)?
___
*[`libos/src/arch/x86_64/libos_elf_entry.nasm` line 13 at r1](https://reviewable.io/reviews/gramineproject/gramine/736#-N6Nrle5-Rlt5vdizQhI:-N6NuS113XuCSavO0TRM:b-9ep62s) ([raw file](https://github.com/gramineproject/gramine/blob/156e1bc95c92ece46b780dccd0f722600e3b2705/libos/src/arch/x86_64/libos_elf_entry.nasm#L13)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This one is unrelated, right?
</blockquote></details>

Partially. It's a different issue, but I've hit it with this PR (because different `section ...` was appended to the top of this file).


<!-- Sent from Reviewable.io -->

2022-07-07 14:55 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/736)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @mkow)

___
*[`common/src/arch/x86_64/no_exec_stack.nasm` line 1 at r1](https://reviewable.io/reviews/gramineproject/gramine/736#-N6Nr5S78Eq88E-eNDYB:-N6O8wiS5EHYfaOAhKn0:b6c2ojf) ([raw file](https://github.com/gramineproject/gramine/blob/156e1bc95c92ece46b780dccd0f722600e3b2705/common/src/arch/x86_64/no_exec_stack.nasm#L1)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

The only bit that matters is `exec`, rest of them are ignored. This is what I've always used (admittedly I probably copied it from internet) and it worked as intended.
If you want I can remove `progbits`.
What about `nowrite`? Do you wan to have `write` or remove it (to have default `nowrite`, which we do not care about, because kernel will ignore it)?
</blockquote></details>

I don't care then. It's ok.
___
*[`common/src/arch/x86_64/no_exec_stack.nasm` line 1 at r1](https://reviewable.io/reviews/gramineproject/gramine/736#-N6Nrd7IBTwQJ1Jh22I1:-N6O9-NM0hmwtLusN6UP:b-u3hyh2) ([raw file](https://github.com/gramineproject/gramine/blob/156e1bc95c92ece46b780dccd0f722600e3b2705/common/src/arch/x86_64/no_exec_stack.nasm#L1)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

With `noalloc` I believe this is irrelevant (i.e. exact setting does not matter). We can remove it (but it's default so it will be set anyway).
</blockquote></details>

I don't care, it's ok.


<!-- Sent from Reviewable.io -->

2022-07-07 15:10 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/736)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`common/src/arch/x86_64/no_exec_stack.nasm` line 1 at r1](https://reviewable.io/reviews/gramineproject/gramine/736#-N6Nr5S78Eq88E-eNDYB:-N6OCOmp1PzbHDtpU07P:b-lcjg6m) ([raw file](https://github.com/gramineproject/gramine/blob/156e1bc95c92ece46b780dccd0f722600e3b2705/common/src/arch/x86_64/no_exec_stack.nasm#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't care then. It's ok.
</blockquote></details>

Ok, whatever then. Although this comment in the kernel is a bit worrying, sounds like they assumed W, but didn't check it (and maybe will start checking it in the future?)


<!-- Sent from Reviewable.io -->

2022-07-07 18:36 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/736)* status: 2 of 3 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @mkow)

___
*[`common/src/arch/x86_64/no_exec_stack.nasm` line 1 at r1](https://reviewable.io/reviews/gramineproject/gramine/736#-N6Nr5S78Eq88E-eNDYB:-N6OwVBx3-OTQr8SQDR1:b6s4zwu) ([raw file](https://github.com/gramineproject/gramine/blob/156e1bc95c92ece46b780dccd0f722600e3b2705/common/src/arch/x86_64/no_exec_stack.nasm#L1)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Ok, whatever then. Although this comment in the kernel is a bit worrying, sounds like they assumed W, but didn't check it (and maybe will start checking it in the future?)
</blockquote></details>

Although it does not matter, I've changed it, so that this does not confuse any future readers.


<!-- Sent from Reviewable.io -->

2022-07-07 19:55 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/736)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2022-07-07 22:01 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/736)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @boryspoplawski)

___
*[`meson.build` line 65 at r2](https://reviewable.io/reviews/gramineproject/gramine/736#-N6PelaR-76OyeWUlofp:-N6PelaR-76OyeWUlofq:b-sy8hw8) ([raw file](https://github.com/gramineproject/gramine/blob/f908791a482720d94d85b13376ed9f50ab352fb8/meson.build#L65)):*
> ```Meson
>         arguments: [
>             '-f', 'elf64',
>             '-p', '@SOURCE_DIR@/common/src/arch/x86_64/no_exec_stack.nasm',
> ```

Wait, shouldn't this be `-P`? My `nasm` doesn't have `-p` switch, how does this even work? (but it somehow does work for me...)



_Code quote:_
```Meson
'-p'
```


<!-- Sent from Reviewable.io -->

2022-07-08 06:54 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/736)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @mkow)

___
*[`meson.build` line 65 at r2](https://reviewable.io/reviews/gramineproject/gramine/736#-N6PelaR-76OyeWUlofp:-N6R_Vp87B7fKx5Nok7g:b-yk6ouu) ([raw file](https://github.com/gramineproject/gramine/blob/f908791a482720d94d85b13376ed9f50ab352fb8/meson.build#L65)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Wait, shouldn't this be `-P`? My `nasm` doesn't have `-p` switch, how does this even work? (but it somehow does work for me...)
</blockquote></details>

Both small and capital `p` works. Man page says:
```
       -P|-p file
           Specifies a file to be pre-included, before the main source file starts to be processed.
```


<!-- Sent from Reviewable.io -->

2022-07-08 09:59 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/736)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @dimakuv)

___
*[`meson.build` line 65 at r2](https://reviewable.io/reviews/gramineproject/gramine/736#-N6PelaR-76OyeWUlofp:-N6SErUV73ywxyl1a0vP:b-rt6aom) ([raw file](https://github.com/gramineproject/gramine/blob/f908791a482720d94d85b13376ed9f50ab352fb8/meson.build#L65)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Both small and capital `p` works. Man page says:
```
       -P|-p file
           Specifies a file to be pre-included, before the main source file starts to be processed.
```
</blockquote></details>

Interesting... What nasm version do you have?
I have 2.14.02 and it doesn't have it.


<!-- Sent from Reviewable.io -->

2022-07-08 11:44 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/736)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @mkow)

___
*[`meson.build` line 65 at r2](https://reviewable.io/reviews/gramineproject/gramine/736#-N6PelaR-76OyeWUlofp:-N6Sc-Fn3oJnM_XP6_tj:bl1bzei) ([raw file](https://github.com/gramineproject/gramine/blob/f908791a482720d94d85b13376ed9f50ab352fb8/meson.build#L65)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Interesting... What nasm version do you have?
I have 2.14.02 and it doesn't have it.
</blockquote></details>

`NASM version 2.14.02`

My man page for NASM is from `12/26/2018`.


<!-- Sent from Reviewable.io -->

2022-07-08 11:45 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/736)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @mkow)

___
*[`meson.build` line 65 at r2](https://reviewable.io/reviews/gramineproject/gramine/736#-N6PelaR-76OyeWUlofp:-N6ScETMBADrNFzsJ9mV:b-xtc6go) ([raw file](https://github.com/gramineproject/gramine/blob/f908791a482720d94d85b13376ed9f50ab352fb8/meson.build#L65)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`NASM version 2.14.02`

My man page for NASM is from `12/26/2018`.
</blockquote></details>

You're probably just looking at `nasm --help` output? There indeed the only option listed is `-P`.


<!-- Sent from Reviewable.io -->

2022-07-08 12:19 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/736)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @mkow)

___
*[`meson.build` line 65 at r2](https://reviewable.io/reviews/gramineproject/gramine/736#-N6PelaR-76OyeWUlofp:-N6SjxaI-kyIRoRHzLqo:b-5jpimh) ([raw file](https://github.com/gramineproject/gramine/blob/f908791a482720d94d85b13376ed9f50ab352fb8/meson.build#L65)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You're probably just looking at `nasm --help` output? There indeed the only option listed is `-P`.
</blockquote></details>

Just as @dimakuv said.


<!-- Sent from Reviewable.io -->

2022-07-08 13:02 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/736)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`meson.build` line 65 at r2](https://reviewable.io/reviews/gramineproject/gramine/736#-N6PelaR-76OyeWUlofp:-N6StfnOBWVVJOdDChf2:b-fd69f3) ([raw file](https://github.com/gramineproject/gramine/blob/f908791a482720d94d85b13376ed9f50ab352fb8/meson.build#L65)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Just as @dimakuv said.
</blockquote></details>

Oh, you're right, they lied to me in `nasm --help` :(


<!-- Sent from Reviewable.io -->

2022-07-08 13:03 UTC, merged