[common] Don't extend files while reading data from protected files
gramineproject/gramine pull request #738
Opened 2022-07-11 10:12 UTC by oshogbo

## Description of the changes 

The file should grow only during write and truncation. The protected file was extended when the application opened it for reading and writing and read from an offset larger than the current size. Previous logic, in the `ipf_update_after_seek` function, assumed that if the file is writable, the file should be extended. This function was called in the read and write routine of protected files.

New tests verify that the file is not extended after seek/tell routine, and they are not extended after the read syscall.

## How to test this PR? 

```
gramine-test -C libos/test/fs pytest
gramine-test --sgx -C libos/test/fs pytest
```

2022-07-11 11:53 UTC, mkow requested changes
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/738)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @oshogbo)

___
*[`-- commits` line 13 at r1](https://reviewable.io/reviews/gramineproject/gramine/738#-N6h1IiX-QNursYOZbRZ):*




_Suggestion:_
```
and that they are not
```
___
*[`common/src/protected_files/protected_files.c` line 1337 at r1](https://reviewable.io/reviews/gramineproject/gramine/738#-N6h4zOOAXlmSPwThaw0:-N6h4zOOAXlmSPwThaw1:b-dfuv92) ([raw file](https://github.com/gramineproject/gramine/blob/3e60bcbba22f7469baf8b5e7bd20c2fdc05fa6c6/common/src/protected_files/protected_files.c#L1337)):*
> ```C
>             return pf->last_error;
>         }
>         pf->end_of_file = false;
> ```

Shouldn't this be `true`?
Actually, do we even still need `end_of_file`? There's only one place reading it, and it seems that it's redundant there.
___
*[`libos/test/fs/seek_tell.c` line 69 at r1](https://reviewable.io/reviews/gramineproject/gramine/738#-N6h1r7yB6qbGpkcxnl7:-N6h1r7yB6qbGpkcxnl8:bj90qn) ([raw file](https://github.com/gramineproject/gramine/blob/3e60bcbba22f7469baf8b5e7bd20c2fdc05fa6c6/libos/test/fs/seek_tell.c#L69)):*
> ```C
>     printf("seek(%s) output end 4 OK\n", path);
>     pos = tell_fd(path, f);
>     printf("tell(%s) output end 3 OK: %zd\n", path, pos);
> ```

Why is it 4 and then 3? Also, what do you mean by "output end"? You're seeking beyond it, not just to the end.



_Code quote:_
```C
    printf("seek(%s) output end 4 OK\n", path);
    pos = tell_fd(path, f);
    printf("tell(%s) output end 3 OK: %zd\n", path, pos);
```
___
*[`libos/test/fs/seek_tell.c` line 75 at r1](https://reviewable.io/reviews/gramineproject/gramine/738#-N6h2Tgb8YXOivt2rTcT:-N6h2Tgb8YXOivt2rTcU:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/3e60bcbba22f7469baf8b5e7bd20c2fdc05fa6c6/libos/test/fs/seek_tell.c#L75)):*
> ```C
>     printf("seek(%s) output end 5 OK\n", path);
>     pos = tell_fd(path, f);
>     printf("tell(%s) output end 4 OK: %zd\n", path, pos);
> ```

ditto


<!-- Sent from Reviewable.io -->

2022-07-11 12:06 UTC, dimakuv requested changes
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/738)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @oshogbo)

___
*[`common/src/protected_files/protected_files.c` line 1334 at r1](https://reviewable.io/reviews/gramineproject/gramine/738#-N6h6KHC5QbhCzF82cq2:-N6h6KHC5QbhCzF82cq3:b-bf543s) ([raw file](https://github.com/gramineproject/gramine/blob/3e60bcbba22f7469baf8b5e7bd20c2fdc05fa6c6/common/src/protected_files/protected_files.c#L1334)):*
> ```C
>     if (offset > pf->encrypted_part_plain.size) {
>         if (!PF_SUCCESS(pf_set_size(pf, offset))) {
>             pf->last_error = PF_STATUS_INVALID_PARAMETER;
> ```

Wouldn't it make more sense to memorize the return value of `pf_set_size()` and assign `pf->last_error` to this return value?
___
*[`common/src/protected_files/protected_files.c` line 1337 at r1](https://reviewable.io/reviews/gramineproject/gramine/738#-N6h4zOOAXlmSPwThaw0:-N6h6XpLDb1AACV6dk-a:b-wzyzjx) ([raw file](https://github.com/gramineproject/gramine/blob/3e60bcbba22f7469baf8b5e7bd20c2fdc05fa6c6/common/src/protected_files/protected_files.c#L1337)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Shouldn't this be `true`?
Actually, do we even still need `end_of_file`? There's only one place reading it, and it seems that it's redundant there.
</blockquote></details>

+1, `end_of_file` seems to be pointless.
___
*[`libos/test/fs/seek_tell.c` line 116 at r1](https://reviewable.io/reviews/gramineproject/gramine/738#-N6h8d_B1w7yV7To9A9J:-N6h8d_B1w7yV7To9A9K:b-wvx4gt) ([raw file](https://github.com/gramineproject/gramine/blob/3e60bcbba22f7469baf8b5e7bd20c2fdc05fa6c6/libos/test/fs/seek_tell.c#L116)):*
> ```C
>     printf("fseek(%s) output end 5 OK\n", path);
>     pos = tell_stdio(path, f);
>     printf("ftell(%s) output end 4 OK: %zd\n", path, pos);
> ```

Hm, probably @boryspoplawski will want you to rewrite this test to be self-checking. But maybe not -- this is the old test being modifying, not a brand new test...
___
*[`libos/test/fs/test_fs.py` line 133 at r1](https://reviewable.io/reviews/gramineproject/gramine/738#-N6h7nim5QsTXwvMyawQ:-N6h7nim5QsTXwvMyawR:b-7kkb3z) ([raw file](https://github.com/gramineproject/gramine/blob/3e60bcbba22f7469baf8b5e7bd20c2fdc05fa6c6/libos/test/fs/test_fs.py#L133)):*
> ```Python
>         self.assertIn('read(' + output_path_2 + ') output OK: 0', stdout)
>         self.assertIn('seek(' + output_path_2 + ') output end 5 OK', stdout)
>         self.assertIn('tell(' + output_path_2 + ') output end 4 OK: ' + str(size + 4098), stdout)
> ```

What does it mean? Why does it work this way?

You first perform a `seek((size + 4098) * 2)` -- which works fine. Then you perform a `seek(SEEK_END)`, and it returns `size + 4098`. So the update to max size of the file is lost -- is this how POSIX dictates it to work? Like, if there was no write, then no matter how far you seeked, the real end of the file is at the point of the last write?


<!-- Sent from Reviewable.io -->

2022-07-11 12:12 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/738)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @oshogbo)

___
*[`libos/test/fs/seek_tell.c` line 116 at r1](https://reviewable.io/reviews/gramineproject/gramine/738#-N6h8d_B1w7yV7To9A9J:-N6h9xvTA-13VYhYxPXH:b-5i1k42) ([raw file](https://github.com/gramineproject/gramine/blob/3e60bcbba22f7469baf8b5e7bd20c2fdc05fa6c6/libos/test/fs/seek_tell.c#L116)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Hm, probably @boryspoplawski will want you to rewrite this test to be self-checking. But maybe not -- this is the old test being modifying, not a brand new test...
</blockquote></details>

I would prefer that, but won't insist since, as you noted, this is old test being extended (and it does not require a complete rewrite).


<!-- Sent from Reviewable.io -->

2022-07-11 14:29 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/738)* status: 0 of 4 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "squash! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`-- commits` line 13 at r1](https://reviewable.io/reviews/gramineproject/gramine/738#-N6h1IiX-QNursYOZbRZ):*
Done.
___
*[`common/src/protected_files/protected_files.c` line 1334 at r1](https://reviewable.io/reviews/gramineproject/gramine/738#-N6h6KHC5QbhCzF82cq2:-N6hO_J-BwODWxc2UixP:b-pfhe0c) ([raw file](https://github.com/gramineproject/gramine/blob/3e60bcbba22f7469baf8b5e7bd20c2fdc05fa6c6/common/src/protected_files/protected_files.c#L1334)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Wouldn't it make more sense to memorize the return value of `pf_set_size()` and assign `pf->last_error` to this return value?
</blockquote></details>

So that was my initial idea, but I'm wasn't sure about that because the previous code was setting this value.

So if there isn't any downsides I will change that.
___
*[`common/src/protected_files/protected_files.c` line 1337 at r1](https://reviewable.io/reviews/gramineproject/gramine/738#-N6h4zOOAXlmSPwThaw0:-N6hOBxD1QT083XZtYB4:b2htuvm) ([raw file](https://github.com/gramineproject/gramine/blob/3e60bcbba22f7469baf8b5e7bd20c2fdc05fa6c6/common/src/protected_files/protected_files.c#L1337)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

+1, `end_of_file` seems to be pointless.
</blockquote></details>

In the previous code:
```
result = PF_SUCCESS(pf_set_size(pf, new_offset));
```
then
```
if (result)
    pf->end_of_file = false;
```

But now when I think about it you are right, it doesn't make sense.
I will remove `end_of_file` completely.
___
*[`libos/test/fs/seek_tell.c` line 69 at r1](https://reviewable.io/reviews/gramineproject/gramine/738#-N6h1r7yB6qbGpkcxnl7:-N6hP6iN5Cs7aQgCyZ4e:bffcmgf) ([raw file](https://github.com/gramineproject/gramine/blob/3e60bcbba22f7469baf8b5e7bd20c2fdc05fa6c6/libos/test/fs/seek_tell.c#L69)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why is it 4 and then 3? Also, what do you mean by "output end"? You're seeking beyond it, not just to the end.
</blockquote></details>

It's the number of `tell`, and then numbers of `seek`.
So this is 4th time that the `seek` was called, in this test,and 3rd time `tell`.
As pointed out by @dimakuv in other PR we have to distinguish the operation otherwise the ` self.assertIn` will check only the first occurrence.
This is done in this test already for example:
```
    printf("seek(%s) output end 2 OK\n", path);
    write_fd(path, f, buf, 1);
    seek_fd(path, f, -EXTEND_SIZE - 1, SEEK_CUR); // rewind to former end
    printf("seek(%s) output end 3 OK\n", path);
```
I also think it's messy. So I will create another PR which changes this in whole file to notation:
```
1st tell...
2nd seek...
```
And so on.

The `output`, if I understand correctly is the type of file. You can see that there are `input` tests and `output` tests here.
Ou, in case of "end" I assumed this is just saying "end OK", not that it seeking to "end" I will fix that.
___
*[`libos/test/fs/seek_tell.c` line 75 at r1](https://reviewable.io/reviews/gramineproject/gramine/738#-N6h2Tgb8YXOivt2rTcT:-N6haBLaC4n17V9WyUz8:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/3e60bcbba22f7469baf8b5e7bd20c2fdc05fa6c6/libos/test/fs/seek_tell.c#L75)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`libos/test/fs/seek_tell.c` line 116 at r1](https://reviewable.io/reviews/gramineproject/gramine/738#-N6h8d_B1w7yV7To9A9J:-N6hP-A09dHrRykuG2W6:bs1nd7p) ([raw file](https://github.com/gramineproject/gramine/blob/3e60bcbba22f7469baf8b5e7bd20c2fdc05fa6c6/libos/test/fs/seek_tell.c#L116)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I would prefer that, but won't insist since, as you noted, this is old test being extended (and it does not require a complete rewrite).
</blockquote></details>

ACK. :)
___
*[`libos/test/fs/test_fs.py` line 133 at r1](https://reviewable.io/reviews/gramineproject/gramine/738#-N6h7nim5QsTXwvMyawQ:-N6hQ6M84SsgotxJ0qR6:b-br1ipi) ([raw file](https://github.com/gramineproject/gramine/blob/3e60bcbba22f7469baf8b5e7bd20c2fdc05fa6c6/libos/test/fs/test_fs.py#L133)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What does it mean? Why does it work this way?

You first perform a `seek((size + 4098) * 2)` -- which works fine. Then you perform a `seek(SEEK_END)`, and it returns `size + 4098`. So the update to max size of the file is lost -- is this how POSIX dictates it to work? Like, if there was no write, then no matter how far you seeked, the real end of the file is at the point of the last write?
</blockquote></details>

I'm not sure what you mean the "the update to max size of the file is lost" means.

The seek itself doesn't change the size of the file.
Dunno if this is POSIX, this is how Linux works (tested), and this is documented in man page:
```
lseek() allows the file offset to be set beyond the end of the file (but this does not change the size of the file). 
```


<!-- Sent from Reviewable.io -->

2022-07-11 17:47 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/738)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "squash! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`libos/test/fs/seek_tell.c` line 75 at r2](https://reviewable.io/reviews/gramineproject/gramine/738#-N6i0RwqA-BW8OPdsvfV:-N6iMls96V-lwv2Hpb5H:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d48c62b72d1fc6f8ded97639c7ac63224f52f79f/libos/test/fs/seek_tell.c#L75)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

off-by-one? (you already used "2" above)
</blockquote></details>

Done.
___
*[`libos/test/fs/seek_tell.c` line 116 at r2](https://reviewable.io/reviews/gramineproject/gramine/738#-N6i0Y-P5-lL3XYUPB9l:-N6iMlb8BtVEsbsMjVlH:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d48c62b72d1fc6f8ded97639c7ac63224f52f79f/libos/test/fs/seek_tell.c#L116)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-12 13:09 UTC, mkow approved these changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/738)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2022-07-12 13:14 UTC, mkow submitted a review, later dismissed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/738)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2022-07-13 10:24 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/738)* status: 3 of 4 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "squash! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[`-- commits` line 2 at r4](https://reviewable.io/reviews/gramineproject/gramine/738#-N6mxYiS-aE_MVrRIHVD):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

One liner lacks info that this is about PF
</blockquote></details>

Done.
___
*[`common/src/protected_files/protected_files.c` line 1299 at r4](https://reviewable.io/reviews/gramineproject/gramine/738#-N6n-Pa73vhRN4Uv4TIC:-N6r2pLDBor0T_qr0GyA:bcjjxqc) ([raw file](https://github.com/gramineproject/gramine/blob/b5eac6892db82717af3a9e502a5f1fcf13782915/common/src/protected_files/protected_files.c#L1299)):*
> pf->last_error = pf->file_status
Nice catch.
___
*[`common/src/protected_files/protected_files_internal.h` line 64 at r4](https://reviewable.io/reviews/gramineproject/gramine/738#-N6n01ni1lJbGA2r_m8_:-N6r2C2H5xw0iv8EpKQh:bfw5h6h) ([raw file](https://github.com/gramineproject/gramine/blob/b5eac6892db82717af3a9e502a5f1fcf13782915/common/src/protected_files/protected_files_internal.h#L64)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Wait, what is this? Why do we have static noinline functions in header? How is this supposed to work?
Also this one is used only in one file.
</blockquote></details>

I guess the idea was to define all the static functions in one place, include them and don't care about the order of definition. 

I'm not sure why you suggesting inlinie functions here.

But yea this file is weird, and kinda useless.


<!-- Sent from Reviewable.io -->

2022-07-13 11:42 UTC, boryspoplawski requested changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/738)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "squash! " found in commit messages' one-liners (waiting on @oshogbo)

___
*[`common/src/protected_files/protected_files_internal.h` line 64 at r4](https://reviewable.io/reviews/gramineproject/gramine/738#-N6n01ni1lJbGA2r_m8_:-N6rMSdz6pky_8wPdmQ3:bfqi67h) ([raw file](https://github.com/gramineproject/gramine/blob/b5eac6892db82717af3a9e502a5f1fcf13782915/common/src/protected_files/protected_files_internal.h#L64)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

I guess the idea was to define all the static functions in one place, include them and don't care about the order of definition. 

I'm not sure why you suggesting inlinie functions here.

But yea this file is weird, and kinda useless.
</blockquote></details>

Even if you don't remove all of this, then please don't add new functions here, it makes no sense.


<!-- Sent from Reviewable.io -->

2022-07-13 15:16 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/738)* status: 2 of 4 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[`common/src/protected_files/protected_files_internal.h` line 64 at r4](https://reviewable.io/reviews/gramineproject/gramine/738#-N6n01ni1lJbGA2r_m8_:-N6s7YHj22NPewoTPjwi:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b5eac6892db82717af3a9e502a5f1fcf13782915/common/src/protected_files/protected_files_internal.h#L64)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Even if you don't remove all of this, then please don't add new functions here, it makes no sense.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-13 16:19 UTC, boryspoplawski approved these changes
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/738)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2022-07-14 07:07 UTC, dimakuv submitted a review, later dismissed
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/738)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2022-07-14 07:34 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/738)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2022-07-14 09:28 UTC, mkow approved these changes
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/738)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2022-07-14 11:33 UTC, boryspoplawski approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/738)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-07-14 11:35 UTC, merged