[LibOS] Add support to handle AF_UNIX domain type sockets
gramineproject/gramine pull request #74
Opened 2021-09-21 04:16 UTC by jkr0103

Signed-off-by: Jitender Kumar <jitender.kumar@intel.com>

## Description of the changes 
Current implementation of `shim_do_getsockname` and `shim_do_getpeername` functions handles only
 AF_INET and AF_INET6 domain type sockets but misses UNIX domain type socket. This PR 
 adds functionality to handle UNIX domain type sockets inside `shim_do_getsockname` and 
 `shim_do_getpeername` functions.

## How to test this PR? 
Create client and servers using AF_UNIX domain socket within same application, establish connection between client and server. Make a call to `shim_do_getsockname` and `shim_do_getpeername` functions from server code.

2021-09-21 08:07 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/74)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @jkr0103)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/74#-Mk6OBjK-mdodL-7iV8c:-Mk6OBjL2QbsehTba9dk:b-58faz6) (no related file):*
Cannot we add a couple lines of code to https://github.com/gramineproject/gramine/blob/master/LibOS/shim/test/regression/unix.c to test this?

---
___
*[LibOS/shim/src/sys/shim_socket.c, line 301 at r1](https://reviewable.io/reviews/gramineproject/gramine/74#-Mk6NgWdDgZM3vYgfNqP:-Mk6NgWdDgZM3vYgfNqQ:b1ym2kz) ([raw file](https://github.com/gramineproject/gramine/blob/f8859caf3808fd2b7112ce51e3e55a3a5a90a64c/LibOS/shim/src/sys/shim_socket.c#L301)):*
> ```C
>     }
>     free(path);
>     return 0;
> ```

You should return `MAX(size, ARRAY_SIZE(un->sun_path))` here instead of zero. To have the same semantics as `inet_copy_addr`.
___
*[LibOS/shim/src/sys/shim_socket.c, line 1717 at r1](https://reviewable.io/reviews/gramineproject/gramine/74#-Mk6NuZu4WWf3O2kjGtQ:-Mk6NuZu4WWf3O2kjGtR:b53st88) ([raw file](https://github.com/gramineproject/gramine/blob/f8859caf3808fd2b7112ce51e3e55a3a5a90a64c/LibOS/shim/src/sys/shim_socket.c#L1717)):*
> ```C
> 
>     if(sock->domain == AF_UNIX)
>         ret = unix_copy_addr(addr, sock->addr.un.dentry);
> ```

But you don't update `*addrlen` in this case. Please see my suggestion on `unix_copy_addr()` function, and update `*addrlen` here.
___
*[LibOS/shim/src/sys/shim_socket.c, line 1770 at r1](https://reviewable.io/reviews/gramineproject/gramine/74#-Mk6O08x-IJcipqsRBIS:-Mk6O08x-IJcipqsRBIT:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/f8859caf3808fd2b7112ce51e3e55a3a5a90a64c/LibOS/shim/src/sys/shim_socket.c#L1770)):*
> ```C
> 
>     if(sock->domain == AF_UNIX)
>         ret = unix_copy_addr(addr, sock->addr.un.dentry);
> ```

ditto


<!-- Sent from Reviewable.io -->

2021-09-21 08:51 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/74)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @jkr0103)

___
*[LibOS/shim/src/sys/shim_socket.c, line 301 at r1](https://reviewable.io/reviews/gramineproject/gramine/74#-Mk6NgWdDgZM3vYgfNqP:-Mk6Y1iH3LIAF8yI4RYJ:b-92ddsi) ([raw file](https://github.com/gramineproject/gramine/blob/f8859caf3808fd2b7112ce51e3e55a3a5a90a64c/LibOS/shim/src/sys/shim_socket.c#L301)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You should return `MAX(size, ARRAY_SIZE(un->sun_path))` here instead of zero. To have the same semantics as `inet_copy_addr`.
</blockquote></details>

As discussed offline, we shouldn't change this function. Ignore my comment.
___
*[LibOS/shim/src/sys/shim_socket.c, line 1717 at r1](https://reviewable.io/reviews/gramineproject/gramine/74#-Mk6NuZu4WWf3O2kjGtQ:-Mk6Y7jU2L7LyHn5NVMg:bmhxbsf) ([raw file](https://github.com/gramineproject/gramine/blob/f8859caf3808fd2b7112ce51e3e55a3a5a90a64c/LibOS/shim/src/sys/shim_socket.c#L1717)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

But you don't update `*addrlen` in this case. Please see my suggestion on `unix_copy_addr()` function, and update `*addrlen` here.
</blockquote></details>

As discussed offline, smth like:
```
ret = unix_copy_addr(addr, sock->addr.un.dentry);
if (ret >= 0)
    *addrlen = sizeof(struct sockaddr_un);
```

is enough.


<!-- Sent from Reviewable.io -->

2021-09-21 10:13 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/74)* status: 0 of 1 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @jkr0103)

___
*[LibOS/shim/src/sys/shim_socket.c, line 1717 at r1](https://reviewable.io/reviews/gramineproject/gramine/74#-Mk6NuZu4WWf3O2kjGtQ:-Mk6pm9g3z18oGdiEIqf:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/f8859caf3808fd2b7112ce51e3e55a3a5a90a64c/LibOS/shim/src/sys/shim_socket.c#L1717)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

As discussed offline, smth like:
```
ret = unix_copy_addr(addr, sock->addr.un.dentry);
if (ret >= 0)
    *addrlen = sizeof(struct sockaddr_un);
```

is enough.
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_socket.c, line 1770 at r1](https://reviewable.io/reviews/gramineproject/gramine/74#-Mk6O08x-IJcipqsRBIS:-Mk6pnYD7yip7DhqzJdE:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/f8859caf3808fd2b7112ce51e3e55a3a5a90a64c/LibOS/shim/src/sys/shim_socket.c#L1770)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-09-21 11:05 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/74)* status: 0 of 2 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/74#-Mk6OBjK-mdodL-7iV8c:-Mk70hZa-9eqaJepX1Cq:brcu20b) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Cannot we add a couple lines of code to https://github.com/gramineproject/gramine/blob/master/LibOS/shim/test/regression/unix.c to test this?
</blockquote></details>

added `getsockname` and `getpeername` calls to `unix.c` and tested the same.

---


<!-- Sent from Reviewable.io -->

2021-09-21 13:44 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/74)* status: all files reviewed, 14 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @jkr0103)

___
*[LibOS/shim/src/sys/shim_socket.c, line 1720 at r3](https://reviewable.io/reviews/gramineproject/gramine/74#-Mk7Y_37E-V-SENv-Q04:-Mk7Y_388L9PKt5lgy_j:bpa4mr8) ([raw file](https://github.com/gramineproject/gramine/blob/63202f2e070e52ebbf8cb16460a2edd2f6a449dc/LibOS/shim/src/sys/shim_socket.c#L1720)):*
> ```C
>         if (ret < 0)
>             goto out_locked;
>         if (addrlen)
> ```

There is no need to check `if (addrlen)` -- it is already checked above in this function (see check with `is_user_memory_writable`). So just remove this line.
___
*[LibOS/shim/src/sys/shim_socket.c, line 1779 at r3](https://reviewable.io/reviews/gramineproject/gramine/74#-Mk7Ym7_EPX5ilL1fKtI:-Mk7Ym7_EPX5ilL1fKtJ:bblvwhu) ([raw file](https://github.com/gramineproject/gramine/blob/63202f2e070e52ebbf8cb16460a2edd2f6a449dc/LibOS/shim/src/sys/shim_socket.c#L1779)):*
> ```C
>         if (ret < 0)
>             goto out_locked;
>         if (addrlen)
> ```

ditto (remove this line)
___
*[LibOS/shim/test/regression/unix.c, line 115 at r3](https://reviewable.io/reviews/gramineproject/gramine/74#-Mk7YtRNEL7nNlwWoQB1:-Mk7YtRNEL7nNlwWoQB2:b-z8a4ju) ([raw file](https://github.com/gramineproject/gramine/blob/63202f2e070e52ebbf8cb16460a2edd2f6a449dc/LibOS/shim/test/regression/unix.c#L115)):*
> ```C
> 
>     addrlen = sizeof(peer_addr);
>     int ret = getpeername(new_socket, (struct sockaddr *) &peer_addr, (socklen_t *)&addrlen);
> ```

Please remove three unneeded spaces here: `(struct sockaddr*)&peer_addr, (socklen_t*)&addrlen`
___
*[LibOS/shim/test/regression/unix.c, line 116 at r3](https://reviewable.io/reviews/gramineproject/gramine/74#-Mk7Z6BM-1FQOy52ulfy:-Mk7Z6BM-1FQOy52ulfz:b-tle64t) ([raw file](https://github.com/gramineproject/gramine/blob/63202f2e070e52ebbf8cb16460a2edd2f6a449dc/LibOS/shim/test/regression/unix.c#L116)):*
> ```C
>     addrlen = sizeof(peer_addr);
>     int ret = getpeername(new_socket, (struct sockaddr *) &peer_addr, (socklen_t *)&addrlen);
>     if (ret == -1){
> ```

Please use `if (ret < 0) {` (add a space and use `< 0` for uniformity in this file)
___
*[LibOS/shim/test/regression/unix.c, line 117 at r3](https://reviewable.io/reviews/gramineproject/gramine/74#-Mk7ZS825STXrcVlfe-Y:-Mk7ZS825STXrcVlfe-Z:b-gk1se1) ([raw file](https://github.com/gramineproject/gramine/blob/63202f2e070e52ebbf8cb16460a2edd2f6a449dc/LibOS/shim/test/regression/unix.c#L117)):*
> ```C
>     int ret = getpeername(new_socket, (struct sockaddr *) &peer_addr, (socklen_t *)&addrlen);
>     if (ret == -1){
>         perror("getpeername failed. Error");
> ```

Simply `perror("getpeername");` -- this function automatically adds the error message
___
*[LibOS/shim/test/regression/unix.c, line 121 at r3](https://reviewable.io/reviews/gramineproject/gramine/74#-Mk7ZYe_5ZnaeFR-f8lD:-Mk7ZYe_5ZnaeFR-f8lE:b-490rhc) ([raw file](https://github.com/gramineproject/gramine/blob/63202f2e070e52ebbf8cb16460a2edd2f6a449dc/LibOS/shim/test/regression/unix.c#L121)):*
> ```C
>         exit(1);
>     }
>     if(strcmp(peer_addr.sun_path, "/u") !=0) {
> ```

Please add the spaces, like this: `if (strcmp(peer_addr.sun_path, "/u") != 0) {`
___
*[LibOS/shim/test/regression/unix.c, line 122 at r3](https://reviewable.io/reviews/gramineproject/gramine/74#-Mk7Zm4M-XxAC8uig8kv:-Mk7Zm4M-XxAC8uig8kw:b9usqou) ([raw file](https://github.com/gramineproject/gramine/blob/63202f2e070e52ebbf8cb16460a2edd2f6a449dc/LibOS/shim/test/regression/unix.c#L122)):*
> ```C
>     }
>     if(strcmp(peer_addr.sun_path, "/u") !=0) {
>         printf("returned wrong peername:%s\n", peer_addr.sun_path);
> ```

`peer name: %s`
___
*[LibOS/shim/test/regression/unix.c, line 126 at r3](https://reviewable.io/reviews/gramineproject/gramine/74#-Mk7_I4lDjJ5YnTBnI2U:-Mk7_I4lDjJ5YnTBnI2V:b-y4y3v3) ([raw file](https://github.com/gramineproject/gramine/blob/63202f2e070e52ebbf8cb16460a2edd2f6a449dc/LibOS/shim/test/regression/unix.c#L126)):*
> ```C
>         exit(1);
>     }
>     printf("peer name: %s\n", peer_addr.sun_path);
> ```

You can remove this printf. At this point, your program can only have `/u` as the peer name.
___
*[LibOS/shim/test/regression/unix.c, line 129 at r3](https://reviewable.io/reviews/gramineproject/gramine/74#-Mk7ZwCq6gK0-k1up_uX:-Mk7ZwCq6gK0-k1up_uY:b-jg72ql) ([raw file](https://github.com/gramineproject/gramine/blob/63202f2e070e52ebbf8cb16460a2edd2f6a449dc/LibOS/shim/test/regression/unix.c#L129)):*
> ```C
> 
>     addrlen = sizeof(sockname_addr);
>     ret = getsockname(new_socket, (struct sockaddr *) &sockname_addr, (socklen_t *)&addrlen);
> ```

Please remove three unneeded spaces here: `(struct sockaddr*)&sockname_addr, (socklen_t*)&addrlen`
___
*[LibOS/shim/test/regression/unix.c, line 130 at r3](https://reviewable.io/reviews/gramineproject/gramine/74#-Mk7ZD_O65mo_UmsucSG:-Mk7ZD_O65mo_UmsucSH:b-tle64t) ([raw file](https://github.com/gramineproject/gramine/blob/63202f2e070e52ebbf8cb16460a2edd2f6a449dc/LibOS/shim/test/regression/unix.c#L130)):*
> ```C
>     addrlen = sizeof(sockname_addr);
>     ret = getsockname(new_socket, (struct sockaddr *) &sockname_addr, (socklen_t *)&addrlen);
>     if (ret == -1){
> ```

Please use `if (ret < 0) {` (add a space and use `< 0` for uniformity in this file)
___
*[LibOS/shim/test/regression/unix.c, line 131 at r3](https://reviewable.io/reviews/gramineproject/gramine/74#-Mk7_3UQ4P4_jouGNwz-:-Mk7_3UQ4P4_jouGNwz0:bshnqw9) ([raw file](https://github.com/gramineproject/gramine/blob/63202f2e070e52ebbf8cb16460a2edd2f6a449dc/LibOS/shim/test/regression/unix.c#L131)):*
> ```C
>     ret = getsockname(new_socket, (struct sockaddr *) &sockname_addr, (socklen_t *)&addrlen);
>     if (ret == -1){
>         perror("getsockname failed. Error");
> ```

Simply `perror("getsockname");` -- this function automatically adds the error message
___
*[LibOS/shim/test/regression/unix.c, line 135 at r3](https://reviewable.io/reviews/gramineproject/gramine/74#-Mk7_8Pk2QSHUjoDwfq_:-Mk7_8Pk2QSHUjoDwfqa:b-klhf1v) ([raw file](https://github.com/gramineproject/gramine/blob/63202f2e070e52ebbf8cb16460a2edd2f6a449dc/LibOS/shim/test/regression/unix.c#L135)):*
> ```C
>         exit(1);
>     }
>     if(strcmp(sockname_addr.sun_path, "/u") !=0) {
> ```

Please add the spaces, like this: `if (strcmp(sockname_addr.sun_path, "/u") != 0) {`
___
*[LibOS/shim/test/regression/unix.c, line 136 at r3](https://reviewable.io/reviews/gramineproject/gramine/74#-Mk7_C8KDvISoxH5z6eP:-Mk7_C8KDvISoxH5z6eQ:baib7ow) ([raw file](https://github.com/gramineproject/gramine/blob/63202f2e070e52ebbf8cb16460a2edd2f6a449dc/LibOS/shim/test/regression/unix.c#L136)):*
> ```C
>     }
>     if(strcmp(sockname_addr.sun_path, "/u") !=0) {
>         printf("returned wrong socket name:%s\n", sockname_addr.sun_path);
> ```

Add a space after `name:`
___
*[LibOS/shim/test/regression/unix.c, line 140 at r3](https://reviewable.io/reviews/gramineproject/gramine/74#-Mk7_NZpDfNQsXdZorTy:-Mk7_NZpDfNQsXdZorTz:b-7lsmgu) ([raw file](https://github.com/gramineproject/gramine/blob/63202f2e070e52ebbf8cb16460a2edd2f6a449dc/LibOS/shim/test/regression/unix.c#L140)):*
> ```C
>         exit(1);
>     }
>     printf("getsockname.sun_path: %s\n", sockname_addr.sun_path);
> ```

You can remove this printf. At this point, your program can only have `/u` as the socket name.


<!-- Sent from Reviewable.io -->

2021-09-21 15:29 UTC, dimakuv commented
Jenkins, test this please

2021-09-22 03:10 UTC, boryspoplawski requested changes
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/74)* status: all files reviewed, 23 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @jkr0103)

___
*[-- commits, line 2 at r4](https://reviewable.io/reviews/gramineproject/gramine/74#-MkAKeid5DHfMhDy8EWe):*
This one liner is not very informative. Add support of what? Add it where?
___
*[LibOS/shim/src/sys/shim_socket.c, line 1716 at r4](https://reviewable.io/reviews/gramineproject/gramine/74#-MkALCeN4RMeyGUWr4Un:-MkALCeN4RMeyGUWr4Uo:b-a5ht26) ([raw file](https://github.com/gramineproject/gramine/blob/e5d8faa90951baede85e4796560a59afef50679f/LibOS/shim/src/sys/shim_socket.c#L1716)):*
> ```C
>     lock(&hdl->lock);
> 
>     if(sock->domain == AF_UNIX) {
> ```

Space after `if` missing.
___
*[LibOS/shim/src/sys/shim_socket.c, line 1717 at r4](https://reviewable.io/reviews/gramineproject/gramine/74#-MkALhw62X0NIe7jjdEE:-MkALhw62X0NIe7jjdEF:bwlwey0) ([raw file](https://github.com/gramineproject/gramine/blob/e5d8faa90951baede85e4796560a59afef50679f/LibOS/shim/src/sys/shim_socket.c#L1717)):*
> ```C
> 
>     if(sock->domain == AF_UNIX) {
>         ret = unix_copy_addr(addr, sock->addr.un.dentry);
> ```

First you need to verify that `addrlen` is actually big enough.
___
*[LibOS/shim/src/sys/shim_socket.c, line 1722 at r4](https://reviewable.io/reviews/gramineproject/gramine/74#-MkALFKL-qOu9Q__WaZU:-MkALFKL-qOu9Q__WaZV:bfywxco) ([raw file](https://github.com/gramineproject/gramine/blob/e5d8faa90951baede85e4796560a59afef50679f/LibOS/shim/src/sys/shim_socket.c#L1722)):*
> ```C
>         *addrlen = sizeof(struct sockaddr_un);
>     }
>     else
> ```

Please adhere to our coding style: https://graphene.readthedocs.io/en/latest/devel/coding-style.html
___
*[LibOS/shim/src/sys/shim_socket.c, line 1774 at r4](https://reviewable.io/reviews/gramineproject/gramine/74#-MkAMUqb45WMxfOrM7b2:-MkAMUqb45WMxfOrM7b3:btqrwb4) ([raw file](https://github.com/gramineproject/gramine/blob/e5d8faa90951baede85e4796560a59afef50679f/LibOS/shim/src/sys/shim_socket.c#L1774)):*
> ```C
>     }
> 
>     if(sock->domain == AF_UNIX) {
> ```

ditto (space)
___
*[LibOS/shim/src/sys/shim_socket.c, line 1775 at r4](https://reviewable.io/reviews/gramineproject/gramine/74#-MkAMXSgDGjFAmdXLNmk:-MkAMXShBJH9ENXIuVun:b-gzpv71) ([raw file](https://github.com/gramineproject/gramine/blob/e5d8faa90951baede85e4796560a59afef50679f/LibOS/shim/src/sys/shim_socket.c#L1775)):*
> ```C
> 
>     if(sock->domain == AF_UNIX) {
>         ret = unix_copy_addr(addr, sock->addr.un.dentry);
> ```

ditto (size check)
___
*[LibOS/shim/src/sys/shim_socket.c, line 1780 at r4](https://reviewable.io/reviews/gramineproject/gramine/74#-MkAMkOB25en2YuuH4bw:-MkAMkOCASeH5A75QuIf:btswoap) ([raw file](https://github.com/gramineproject/gramine/blob/e5d8faa90951baede85e4796560a59afef50679f/LibOS/shim/src/sys/shim_socket.c#L1780)):*
> ```C
>         *addrlen = sizeof(struct sockaddr_un);
>     }
>     else
> ```

ditto (coding style)
___
*[LibOS/shim/test/regression/unix.c, line 6 at r4](https://reviewable.io/reviews/gramineproject/gramine/74#-MkAS8kc7gaEGwPcKuFB:-MkAS8kd4FKunKP7oZ0y:bcezny6) ([raw file](https://github.com/gramineproject/gramine/blob/e5d8faa90951baede85e4796560a59afef50679f/LibOS/shim/test/regression/unix.c#L6)):*
> ```C
>  * (i.e. only between parent and its child in this test).
>  */
> ```

This test does not pass natively (without Gramine).
___
*[LibOS/shim/test/regression/unix.c, line 75 at r4](https://reviewable.io/reviews/gramineproject/gramine/74#-MkANLUYAYLukYUFRPwR:-MkANLUYAYLukYUFRPwS:bfywxco) ([raw file](https://github.com/gramineproject/gramine/blob/e5d8faa90951baede85e4796560a59afef50679f/LibOS/shim/test/regression/unix.c#L75)):*
> ```C
>     int bufsize  = 1024;
>     char* buffer = malloc(bufsize);
>     struct sockaddr_un address, peer_addr, sockname_addr;
> ```

Please adhere to our coding style: https://graphene.readthedocs.io/en/latest/devel/coding-style.html
___
*[LibOS/shim/test/regression/unix.c, line 107 at r4](https://reviewable.io/reviews/gramineproject/gramine/74#-MkANoutDF3Qhi5F9FW2:-MkANoutDF3Qhi5F9FW3:bj15kvc) ([raw file](https://github.com/gramineproject/gramine/blob/e5d8faa90951baede85e4796560a59afef50679f/LibOS/shim/test/regression/unix.c#L107)):*
> ```C
>     new_socket = accept(create_socket, (struct sockaddr*)&address, &addrlen);
> 
>     close(create_socket);
> ```

Why did you move this? Doesn't seem to be needed.
___
*[LibOS/shim/test/regression/unix.c, line 115 at r4](https://reviewable.io/reviews/gramineproject/gramine/74#-MkAP5MrAHQ4bAGBf4wV:-MkAP5MsCMPL1ka5zKNo:b-ucj7gy) ([raw file](https://github.com/gramineproject/gramine/blob/e5d8faa90951baede85e4796560a59afef50679f/LibOS/shim/test/regression/unix.c#L115)):*
> ```C
> 
>     addrlen = sizeof(peer_addr);
>     int ret = getpeername(new_socket, (struct sockaddr*)&peer_addr, (socklen_t*)&addrlen);
> ```

Remove `socklen_t` cast. If the underlying type does not match, then it's an error to use it here.
___
*[LibOS/shim/test/regression/unix.c, line 117 at r4](https://reviewable.io/reviews/gramineproject/gramine/74#-MkATfUUBvPH04JZQo0v:-MkATfUUBvPH04JZQo0w:bg1yr6j) ([raw file](https://github.com/gramineproject/gramine/blob/c0181a072419be893b3f3f3debc194b08564b2cf/LibOS/shim/test/regression/unix.c#L117)):*
> ```C
>     printf("The client is connected...\n");
> 
>     if (do_fork) {
> ```

Why this was removed?
___
*[LibOS/shim/test/regression/unix.c, line 118 at r4](https://reviewable.io/reviews/gramineproject/gramine/74#-MkAPS6QC2ypO_9dDqrF:-MkAPS6QC2ypO_9dDqrG:b-djqn5x) ([raw file](https://github.com/gramineproject/gramine/blob/e5d8faa90951baede85e4796560a59afef50679f/LibOS/shim/test/regression/unix.c#L118)):*
> ```C
>     if (ret < 0) {
>         perror("getpeername");
>         close(new_socket);
> ```

No need to close `fd`s on exit.
___
*[LibOS/shim/test/regression/unix.c, line 121 at r4](https://reviewable.io/reviews/gramineproject/gramine/74#-MkATX7B-3SGyqGtEX3A:-MkATX7B-3SGyqGtEX3B:b-mfkyqx) ([raw file](https://github.com/gramineproject/gramine/blob/e5d8faa90951baede85e4796560a59afef50679f/LibOS/shim/test/regression/unix.c#L121)):*
> ```C
>         exit(1);
>     }
>     if (strcmp(peer_addr.sun_path, "/u") != 0) {
> ```

Why `/u`? It's supposed to be the address of the peer, whatever that is for UNIX stream sockets.
___
*[LibOS/shim/test/regression/unix.c, line 122 at r4](https://reviewable.io/reviews/gramineproject/gramine/74#-MkASwzK3kXY4_2y6DSZ:-MkASwzK3kXY4_2y6DS_:bjs1c3j) ([raw file](https://github.com/gramineproject/gramine/blob/e5d8faa90951baede85e4796560a59afef50679f/LibOS/shim/test/regression/unix.c#L122)):*
> ```C
>     }
>     if (strcmp(peer_addr.sun_path, "/u") != 0) {
>         printf("returned wrong socket name: %s\n", peer_addr.sun_path);
> ```

"socket" -> "peer"
___
*[LibOS/shim/test/regression/unix.c, line 123 at r4](https://reviewable.io/reviews/gramineproject/gramine/74#-MkAPW0g8UlhHqarxsPa:-MkAPW0g8UlhHqarxsPb:bm441b2) ([raw file](https://github.com/gramineproject/gramine/blob/e5d8faa90951baede85e4796560a59afef50679f/LibOS/shim/test/regression/unix.c#L123)):*
> ```C
>     if (strcmp(peer_addr.sun_path, "/u") != 0) {
>         printf("returned wrong socket name: %s\n", peer_addr.sun_path);
>         close(new_socket);
> ```

ditto (close)
___
*[LibOS/shim/test/regression/unix.c, line 128 at r4](https://reviewable.io/reviews/gramineproject/gramine/74#-MkATnm0BoSgruvTQUw5:-MkATnm0BoSgruvTQUw6:blbviyl) ([raw file](https://github.com/gramineproject/gramine/blob/e5d8faa90951baede85e4796560a59afef50679f/LibOS/shim/test/regression/unix.c#L128)):*
> ```C
> 
>     addrlen = sizeof(sockname_addr);
>     ret = getsockname(new_socket, (struct sockaddr*)&sockname_addr, (socklen_t*)&addrlen);
> ```

ditto (cast)
___
*[LibOS [...]

2021-09-22 15:53 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/74)* status: all files reviewed, 22 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @jkr0103)

___
*[LibOS/shim/test/regression/unix.c, line 75 at r4](https://reviewable.io/reviews/gramineproject/gramine/74#-MkANLUYAYLukYUFRPwR:-MkDCQvj1KzdfLmnDm2x:beip99y) ([raw file](https://github.com/gramineproject/gramine/blob/e5d8faa90951baede85e4796560a59afef50679f/LibOS/shim/test/regression/unix.c#L75)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please adhere to our coding style: https://graphene.readthedocs.io/en/latest/devel/coding-style.html
</blockquote></details>

Sorry, I was wrong here, we do allow for multiple declarations at one line, as long as non of them is a pointer.


<!-- Sent from Reviewable.io -->

2021-09-23 11:55 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/74)* status: all files reviewed, 23 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @jkr0103)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/74#-MkHThUi--9pBzSypSFc:-MkHThUi--9pBzSypSFd:bx52ebw) (no related file):*
It turns out it's not that simple to support `getsockname()` and `getpeername()` for UNIX sockets (`AF_UNIX`).

Here is what native Linux does:
```
sun_path   |   getsockname()
-----------------------------
./u        |   ./u
u          |   u
../u       |   ../u
/tmp/u     |   /tmp/u
----------------------------
```

So Linux memorizes the `sun_path` (more specifically, `addr.un.name`) with which the socket was created in an exact manner (no path normalization). And then Linux returns this value in `getsockname()` and `getpeername()` verbatim.

It poses some problems to our emulation in Gramine. First of all, `../u` may resolve to something completely different inside Gramine due to our chroot semantics. Second, we already abuse `addr.un.name` to store the hash of the path: https://github.com/gramineproject/gramine/blob/40e942db6b02555cf2414f20bbd313b63f50e400/LibOS/shim/src/sys/shim_socket.c#L785.

In other words, we cannot reproduce exactly what Linux does. (We may introduce a new `char[108]` field to our socket handle, but this is just a weird workaround.) From what I understand, we cannot directly compare what Linux does and what Gramine does wrt UNIX domain sockets.

---
___
*[LibOS/shim/src/sys/shim_socket.c, line 289 at r4](https://reviewable.io/reviews/gramineproject/gramine/74#-MkHUzDc6XrJ90zuM0p_:-MkHUzDc6XrJ90zuM0pa:b-p8p9mg) ([raw file](https://github.com/gramineproject/gramine/blob/e5d8faa90951baede85e4796560a59afef50679f/LibOS/shim/src/sys/shim_socket.c#L289)):*
> ```C
>     char* path;
>     size_t size;
>     int ret = dentry_abs_path(dent, &path, &size);
> ```

FYI: Our Gramine emulation always returns the absolute path (e.g. `/u` in the test code below). Whereas Linux returns whatever it saved on socket creation -- a non-normalized path.
___
*[LibOS/shim/test/regression/unix.c, line 6 at r4](https://reviewable.io/reviews/gramineproject/gramine/74#-MkAS8kc7gaEGwPcKuFB:-MkHVFy2AjQ8sa-6qChz:b-b5d8j7) ([raw file](https://github.com/gramineproject/gramine/blob/e5d8faa90951baede85e4796560a59afef50679f/LibOS/shim/test/regression/unix.c#L6)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This test does not pass natively (without Gramine).
</blockquote></details>

My explanation is in the top-level comment.
___
*[LibOS/shim/test/regression/unix.c, line 134 at r4](https://reviewable.io/reviews/gramineproject/gramine/74#-MkASsTB372ZOzCIppwH:-MkHVNhx2QfaYgM8UyCV:b-rgcrqs) ([raw file](https://github.com/gramineproject/gramine/blob/e5d8faa90951baede85e4796560a59afef50679f/LibOS/shim/test/regression/unix.c#L134)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why is it `/u` not `u`?
</blockquote></details>

That's what our Gramine emulation returns. See my top-level comment.

What about we simply add another clause here:
```
/* Gramine returns absolute path, whereas native Linux returns non-normalized path */
if (strcmp(sockname_addr.sun_path, "/u") != 0 || strcmp(sockname_addr.sun_path, "u") != 0)
```


<!-- Sent from Reviewable.io -->

2021-09-23 17:30 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/74)* status: all files reviewed, 23 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @jkr0103)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/74#-MkHThUi--9pBzSypSFc:-MkIgtj3-y1upswFYARp:bta7sp1) (no related file):*
> So Linux memorizes the sun_path 

Can confirm, checked the source.

> In other words, we cannot reproduce exactly what Linux does.

Of course we can, it just requires some changes.

> From what I understand, we cannot directly compare what Linux does and what Gramine does wrt UNIX domain sockets.

Why is that?

---


<!-- Sent from Reviewable.io -->

2021-09-23 20:08 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/74)* status: all files reviewed, 23 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @jkr0103)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/74#-MkHThUi--9pBzSypSFc:-MkJEhnc18xF7auObxGb:b-js35cw) (no related file):*
>> From what I understand, we cannot directly compare what Linux does and what Gramine does wrt UNIX domain sockets. 
>
> Why is that?

Bad wording. What I meant is that because we forward only a subset of host directories with a different hirarchy between them, we cannot generally compare what we get when running the same app natively on Linux and running it in Gramine.

I mean, it is the same as with regular files -- a `../somefile` relpath in Gramine may generally mean something very different than what it means on the host (natively).

So @boryspoplawski comment `This test does not pass natively (without Gramine)` doesn't mean a bug in Gramine generally. I guess I just came to this realization today (though the same may be said about regular files). In other words, UNIX domain sockets are really different from host ones (recall that they don't really create a e.g. `u` file -- they create some file somewhere under `/tmp/graphene/` or smth), and trying to get them to produce the exact same result as on the host generally doesn't sound right.

---


<!-- Sent from Reviewable.io -->

2021-09-23 20:35 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/74)* status: all files reviewed, 23 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @jkr0103)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/74#-MkHThUi--9pBzSypSFc:-MkJJA8h7Jg3CuY6bktz:b-uhno0n) (no related file):*
> What I meant is that because we forward only a subset of host directories with a different hirarchy between them, we cannot generally compare what we get when running the same app natively on Linux and running it in Gramine.

I disagree. The layout that app sees inside Gramine and when run natively should be the same. What Gramine forwards to the host is completely different thing.

> I mean, it is the same as with regular files -- a `../somefile relpath` in Gramine may generally mean something very different than what it means on the host (natively).

What do you mean? If you arrange both initial filesystem layouts (in Gramine and natively) to be the same, then there shouldn't be any differences.

> So @boryspoplawski comment This test does not pass natively (without Gramine) doesn't mean a bug in Gramine generally.

It does. Actually, it means that there is a bug/inconsistency in the test itself - this is because the test was written treating Gramine return values as the source of truth, not what native Linux returns.

> In other words, UNIX domain sockets are really different from host ones (recall that they don't really create a e.g. u file -- they create some file somewhere under /tmp/graphene/ or smth), and trying to get them to produce the exact same result as on the host generally doesn't sound right.

It does not matter where the Gramine stores the actual UNIX socket. What matters is what Gramine presents to the user app - and this should be the very same thing as native Linux.

---


<!-- Sent from Reviewable.io -->

2021-09-24 09:01 UTC, dimakuv commented
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/74#-MkHThUi--9pBzSypSFc:-MkLzk7811THIVYeiU3z:b-cj00up) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

> What I meant is that because we forward only a subset of host directories with a different hirarchy between them, we cannot generally compare what we get when running the same app natively on Linux and running it in Gramine.

I disagree. The layout that app sees inside Gramine and when run natively should be the same. What Gramine forwards to the host is completely different thing.

> I mean, it is the same as with regular files -- a `../somefile relpath` in Gramine may generally mean something very different than what it means on the host (natively).

What do you mean? If you arrange both initial filesystem layouts (in Gramine and natively) to be the same, then there shouldn't be any differences.

> So @boryspoplawski comment This test does not pass natively (without Gramine) doesn't mean a bug in Gramine generally.

It does. Actually, it means that there is a bug/inconsistency in the test itself - this is because the test was written treating Gramine return values as the source of truth, not what native Linux returns.

> In other words, UNIX domain sockets are really different from host ones (recall that they don't really create a e.g. u file -- they create some file somewhere under /tmp/graphene/ or smth), and trying to get them to produce the exact same result as on the host generally doesn't sound right.

It does not matter where the Gramine stores the actual UNIX socket. What matters is what Gramine presents to the user app - and this should be the very same thing as native Linux.
</blockquote></details>

I understand your point @boryspoplawski.

But consider a scenario that I got into yesterday. The app below may be slightly insane to use relative paths, but we're talking about the Gramine vs native Linux semantics currently. (Also, this is about regular files.)

So the original app wants to open a regular file `../foo` (yes, exactly like this, hard-coded in the app, searching in the parent dir). Recall that Gramine sets the current app directory as a root dir (so, host-level `./` becomes `/` inside Gramine). So `../foo` translates into `/foo` in Gramine, and the regular file is searched in the current app dir on the host. Since the file is not there (but instead in the parent dir), the app fails.

We circumvented this by adding a new mount point in the manifest:
```
fs.mount.parent.type = "chroot"
fs.mount.parent.path = "/"
fs.mount.parent.uri = "file:../"
```
(Writing this by memory, forgot the exact text.)

Surely this is a terrible hack. Now imagine that some files in the current app dir and the parent dir have the same names -- I don't even know how Gramine will behave. And I don't see a way around this, without re-designing Gramine FS logic.

This example is orthogonal to this PR (I got really carried away :)). Just want to highlight that some things in Gramine cannot be made such that ` layout that app sees inside Gramine and when run natively should be the same`. Of course, we can always hack around in the manifest file, or we can ignore such weird applications. But generally some things cannot be made exactly the same in Gramine as on the host, without some serious re-design.

---


<!-- Sent from Reviewable.io -->

2021-09-24 09:04 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/74)* status: all files reviewed, 23 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @jkr0103)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/74#-MkHThUi--9pBzSypSFc:-MkM1YOt3C8IqEcrBnET:b58dooy) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I understand your point @boryspoplawski.

But consider a scenario that I got into yesterday. The app below may be slightly insane to use relative paths, but we're talking about the Gramine vs native Linux semantics currently. (Also, this is about regular files.)

So the original app wants to open a regular file `../foo` (yes, exactly like this, hard-coded in the app, searching in the parent dir). Recall that Gramine sets the current app directory as a root dir (so, host-level `./` becomes `/` inside Gramine). So `../foo` translates into `/foo` in Gramine, and the regular file is searched in the current app dir on the host. Since the file is not there (but instead in the parent dir), the app fails.

We circumvented this by adding a new mount point in the manifest:
```
fs.mount.parent.type = "chroot"
fs.mount.parent.path = "/"
fs.mount.parent.uri = "file:../"
```
(Writing this by memory, forgot the exact text.)

Surely this is a terrible hack. Now imagine that some files in the current app dir and the parent dir have the same names -- I don't even know how Gramine will behave. And I don't see a way around this, without re-designing Gramine FS logic.

This example is orthogonal to this PR (I got really carried away :)). Just want to highlight that some things in Gramine cannot be made such that ` layout that app sees inside Gramine and when run natively should be the same`. Of course, we can always hack around in the manifest file, or we can ignore such weird applications. But generally some things cannot be made exactly the same in Gramine as on the host, without some serious re-design.
</blockquote></details>

Anyway, the discussion got seriously derailed. In this PR, what do we want to do? Add a new field to `shim_sock_handle::shim_sock_addr::addr_unix` (see https://github.com/gramineproject/gramine/blob/master/LibOS/shim/include/shim_handle.h)? This field would store the user-supplied `sun_path`, and `getsockname`/`getpeername` will return this field's value, without any path normalization?

---


<!-- Sent from Reviewable.io -->

2021-09-24 15:16 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/74)* status: all files reviewed, 23 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @jkr0103)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/74#-MkHThUi--9pBzSypSFc:-MkNLqus84GM96yhJyPe:b56nz1z) (no related file):*
If your app expect some very specific fs layout, then it's your job, as a manifest writer, to provide it (and if it opens `../foo` then it clearly made some assumptions about it). (NB: automounting host `.` is a feature I would like to see gone.)

> Now imagine that some files in the current app dir and the parent dir have the same names -- I don't even know how Gramine will behave. And I don't see a way around this, without re-designing Gramine FS logic.

It's not Gramine FS fault, it's a problem with manifest. I don't see anything we should change about it (except removing `.` automount).

> Just want to highlight that some things in Gramine cannot be made such that layout that app sees inside Gramine and when run natively should be the same. Of course, we can always hack around in the manifest file, or we can ignore such weird applications.

It's not hacking around, it's a normal, expected thing to do. If your app expect any given FS layout, then you have to provide it (writing correct manifest).

> But generally some things cannot be made exactly the same in Gramine as on the host, without some serious re-design.

I don't see a reason why then cannot be. There is no need for serious re-desing, at least in this case. Of course there are some features that we won't able to emulate 1-1, but it's not the case with FS layout.

---


<!-- Sent from Reviewable.io -->

2021-09-24 15:18 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/74)* status: all files reviewed, 23 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @jkr0103)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/74#-MkHThUi--9pBzSypSFc:-MkNNTSWDOaDCjmnYhOk:b-14lga7) (no related file):*
> Anyway, the discussion got seriously derailed. In this PR, what do we want to do? 

I feel like we should completely redesign getting `sockname` (which would probably include storing `sockaddr`, but only on some types of sockets).

---


<!-- Sent from Reviewable.io -->

2021-09-27 07:23 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/74)* status: all files reviewed, 23 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @jkr0103)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/74#-MkHThUi--9pBzSypSFc:-Mka7FlzAQhDTrTC1Ncc:b6cn09x) (no related file):*
> I feel like we should completely redesign getting sockname (which would probably include storing sockaddr, but only on some types of sockets).

Why do you say "completely redesign"? We don't have any special logic in these functions. Wouldn't my suggestion to change `unix_copy_addr()` to use a new field in `shim_sock_handle::shim_sock_addr::addr_unix` be enough?

---


<!-- Sent from Reviewable.io -->

2021-09-27 14:43 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/74)* status: all files reviewed, 23 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @jkr0103)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/74#-MkHThUi--9pBzSypSFc:-MkbgliuE6Iaja_ic0AE:b-2boy5w) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> I feel like we should completely redesign getting sockname (which would probably include storing sockaddr, but only on some types of sockets).

Why do you say "completely redesign"? We don't have any special logic in these functions. Wouldn't my suggestion to change `unix_copy_addr()` to use a new field in `shim_sock_handle::shim_sock_addr::addr_unix` be enough?
</blockquote></details>

But we probably should have. What if we want to support netlink sockets to use crypto api? Or any other new functionality requiring custom callbacks? Generally I think most of the sock operations should be handled by fops.

---


<!-- Sent from Reviewable.io -->

2021-09-28 06:06 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/74)* status: all files reviewed, 23 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @jkr0103)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/74#-MkHThUi--9pBzSypSFc:-Mkf-RcVDSnF7dgjQmJi:b-mj09vd) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

But we probably should have. What if we want to support netlink sockets to use crypto api? Or any other new functionality requiring custom callbacks? Generally I think most of the sock operations should be handled by fops.
</blockquote></details>

Got it, you want `fops` callbacks for socket operations. I agree, this will be the clean approach.

@boryspoplawski So what would you suggest to do with the current PR?

---


<!-- Sent from Reviewable.io -->

2021-09-28 19:51 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/74)* status: all files reviewed, 23 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @jkr0103)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/74#-MkHThUi--9pBzSypSFc:-MkhxYqe4rWkKs0qG3XX:bkwvgyn) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Got it, you want `fops` callbacks for socket operations. I agree, this will be the clean approach.

@boryspoplawski So what would you suggest to do with the current PR?
</blockquote></details>

We could have some temporary workaround, but only one that is correct

---


<!-- Sent from Reviewable.io -->

2021-09-30 09:16 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/74)* status: 0 of 3 files reviewed, 23 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[-- commits, line 2 at r4](https://reviewable.io/reviews/gramineproject/gramine/74#-MkAKeid5DHfMhDy8EWe):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This one liner is not very informative. Add support of what? Add it where?
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_socket.c, line 1716 at r4](https://reviewable.io/reviews/gramineproject/gramine/74#-MkALCeN4RMeyGUWr4Un:-MkpwIae6xbRE5bosRuk:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/e5d8faa90951baede85e4796560a59afef50679f/LibOS/shim/src/sys/shim_socket.c#L1716)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Space after `if` missing.
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_socket.c, line 1717 at r4](https://reviewable.io/reviews/gramineproject/gramine/74#-MkALhw62X0NIe7jjdEE:-Mkpwk9q3ZA65P33RU6E:b2fu4j7) ([raw file](https://github.com/gramineproject/gramine/blob/e5d8faa90951baede85e4796560a59afef50679f/LibOS/shim/src/sys/shim_socket.c#L1717)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

First you need to verify that `addrlen` is actually big enough.
</blockquote></details>

addrlen is already verified above using function `is_user_memory_writable`
___
*[LibOS/shim/src/sys/shim_socket.c, line 1722 at r4](https://reviewable.io/reviews/gramineproject/gramine/74#-MkALFKL-qOu9Q__WaZU:-Mkpwu06ByWr2qZjGnyY:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/e5d8faa90951baede85e4796560a59afef50679f/LibOS/shim/src/sys/shim_socket.c#L1722)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please adhere to our coding style: https://graphene.readthedocs.io/en/latest/devel/coding-style.html
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_socket.c, line 1774 at r4](https://reviewable.io/reviews/gramineproject/gramine/74#-MkAMUqb45WMxfOrM7b2:-Mkpwv2y7k3pWn8Cf5qa:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/e5d8faa90951baede85e4796560a59afef50679f/LibOS/shim/src/sys/shim_socket.c#L1774)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto (space)
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_socket.c, line 1775 at r4](https://reviewable.io/reviews/gramineproject/gramine/74#-MkAMXSgDGjFAmdXLNmk:-Mkpwydl7u2H7lj_BnKI:b-5987u3) ([raw file](https://github.com/gramineproject/gramine/blob/e5d8faa90951baede85e4796560a59afef50679f/LibOS/shim/src/sys/shim_socket.c#L1775)):*
> addrlen is already verified above using function `is_user_memory_writable`
___
*[LibOS/shim/src/sys/shim_socket.c, line 1780 at r4](https://reviewable.io/reviews/gramineproject/gramine/74#-MkAMkOB25en2YuuH4bw:-Mkpx-Ei5KBeHlIXtJz-:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/e5d8faa90951baede85e4796560a59afef50679f/LibOS/shim/src/sys/shim_socket.c#L1780)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto (coding style)
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/unix.c, line 6 at r4](https://reviewable.io/reviews/gramineproject/gramine/74#-MkAS8kc7gaEGwPcKuFB:-Mkpx6rC2RviBDDyDGhs:bljaxun) ([raw file](https://github.com/gramineproject/gramine/blob/e5d8faa90951baede85e4796560a59afef50679f/LibOS/shim/test/regression/unix.c#L6)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

My explanation is in the top-level comment.
</blockquote></details>

test passed in native, gramine-direct and gramine-sgx successfully after the new code changes
___
*[LibOS/shim/test/regression/unix.c, line 107 at r4](https://reviewable.io/reviews/gramineproject/gramine/74#-MkANoutDF3Qhi5F9FW2:-MkpxJZt2gBi62ywp8DG:b-a6ygv5) ([raw file](https://github.com/gramineproject/gramine/blob/e5d8faa90951baede85e4796560a59afef50679f/LibOS/shim/test/regression/unix.c#L107)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why did you move this? Doesn't seem to be needed.
</blockquote></details>

create_socket was closed in all cases whether accept call successed or failed. It was clsoed in `if` statement as well as after if. I removed one duplicate line by putting it before `if`
___
*[LibOS/shim/test/regression/unix.c, line 115 at r4](https://reviewable.io/reviews/gramineproject/gramine/74#-MkAP5MrAHQ4bAGBf4wV:-MkpxmV59oBULO5CkkSa:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/e5d8faa90951baede85e4796560a59afef50679f/LibOS/shim/test/regression/unix.c#L115)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Remove `socklen_t` cast. If the underlying type does not match, then it's an error to use it here.
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/unix.c, line 117 at r4](https://reviewable.io/reviews/gramineproject/gramine/74#-MkATfUUBvPH04JZQo0v:-Mkpy3TSE5eTc4BKVpgS:bidqu7t) ([raw file](https://github.com/gramineproject/gramine/blob/c0181a072419be893b3f3f3debc194b08564b2cf/LibOS/shim/test/regression/unix.c#L117)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why this was removed?
</blockquote></details>

there is already one fork in `main`. I feel fork calls inside `client` and `server` are unnecessary, hence removed.
___
*[LibOS/shim/test/regression/unix.c, line 118 at r4](https://reviewable.io/reviews/gramineproject/gramine/74#-MkAPS6QC2ypO_9dDqrF:-MkpyTEf6wxw8mCmCl5Z:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/e5d8faa90951baede85e4796560a59afef50679f/LibOS/shim/test/regression/unix.c#L118)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

No need to close `fd`s on exit.
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/unix.c, line 121 at r4](https://reviewable.io/reviews/gramineproject/gramine/74#-MkATX7B-3SGyqGtEX3A:-Mkpyih0ClcZFa_Rauh0:b-pf5pll) ([raw file](https://github.com/gramineproject/gramine/blob/e5d8faa90951baede85e4796560a59afef50679f/LibOS/shim/test/regression/unix.c#L121)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why `/u`? It's supposed to be the address of the peer, whatever that is for UNIX stream sockets.
</blockquote></details>

removed `/u`. Now we get exactly same path whatsever supplied.
___
*[LibOS/shim/test/regression/unix.c, line 122 at r4](https://reviewable.io/reviews/gramineproject/gramine/74#-MkASwzK3kXY4_2y6DSZ:-MkpzAjl3paT4qGFeWLG:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/e5d8faa90951baede85e4796560a59afef50679f/LibOS/shim/test/regression/unix.c#L122)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

"socket" -> "peer"
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/unix.c, line 123 at r4](https://reviewable.io/reviews/gramineproject/gramine/74#-MkAPW0g8UlhHqarxsPa:-MkpyuER2b4MFyixl8XG:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/e5d8faa90951baede85e4796560a59afef50679f/LibOS/shim/test/regression/unix.c#L123)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto (close)
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/unix.c, line 128 at r4](https://reviewable.io/reviews/gramineproject/gramine/74#-MkATnm0BoSgruvTQUw5:- [...]

2021-09-30 10:46 UTC, dimakuv requested changes
> Reviewed 2 of 3 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/74)* status: all files reviewed, 34 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @jkr0103)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/74#-MkHThUi--9pBzSypSFc:-MkqJ0Vu4UyZ41vj3El0:byrli1e) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

We could have some temporary workaround, but only one that is correct
</blockquote></details>

Agreed :)

---
___
*[-- commits, line 2 at r4](https://reviewable.io/reviews/gramineproject/gramine/74#-MkAKeid5DHfMhDy8EWe):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Now this title misses the most important part: that this concerns `getsockname` and `getpeername`.

I suggest the following: `[LibOS] Return correct AF_UNIX-socket name in getsockname/getpeername`.

No need to change it now, we can change it during final rebase.
___
*[-- commits, line 7 at r6](https://reviewable.io/reviews/gramineproject/gramine/74#-Mkq8rXV1ZojJkkt6r2Q):*
`This PR` -> `This commit`.

No need to change it now, we can change it during final rebase.
___
*[LibOS/shim/include/shim_handle.h, line 125 at r6](https://reviewable.io/reviews/gramineproject/gramine/74#-Mkq8zpn7Gn4EeMO1CVd:-Mkq8zpn7Gn4EeMO1CVe:byag7rw) ([raw file](https://github.com/gramineproject/gramine/blob/88354e86880a7399d61500c791d6662dbc7cb565/LibOS/shim/include/shim_handle.h#L125)):*
> ```objc
>             struct shim_dentry* dentry;
>             char name[PIPE_URI_SIZE];
>             char sun_path[108]; /* Path name.  */
> ```

`108` -> `SOCK_URI_SIZE` (we have this macro defined above)

`Path name` -> `Linux stores user-supplied name as-is; we do the same` (otherwise the comment is vague)
___
*[LibOS/shim/src/sys/shim_socket.c, line 1716 at r4](https://reviewable.io/reviews/gramineproject/gramine/74#-MkALCeN4RMeyGUWr4Un:-MkqDIycB361bpZcZooX:b-8nyi3w) ([raw file](https://github.com/gramineproject/gramine/blob/e5d8faa90951baede85e4796560a59afef50679f/LibOS/shim/src/sys/shim_socket.c#L1716)):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done
___
*[LibOS/shim/src/sys/shim_socket.c, line 1717 at r4](https://reviewable.io/reviews/gramineproject/gramine/74#-MkALhw62X0NIe7jjdEE:-MkqFatpCy2eHffWq83E:b-qgz6qw) ([raw file](https://github.com/gramineproject/gramine/blob/e5d8faa90951baede85e4796560a59afef50679f/LibOS/shim/src/sys/shim_socket.c#L1717)):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

addrlen is already verified above using function `is_user_memory_writable`
</blockquote></details>

That's now what Borys meant. This function `shim_do_getsockname()` is called by the user app, and the user app may supply any weird number in `*addrlen` (the actual size of the buffer). So say the user app supplies `*addrlen = 1`, which means that the buffer `addr` is 1-byte long.

Now we call `unix_copy_addr()` which does `memcpy(un->sun_path, path, ARRAY_SIZE(un->sun_path) - 1)`. We are screwed: the supplied buffer was only 1 byte, but we wrote much more than 1 byte. Buffer overflow and security vulnerability!

Because we know that our current implementation of `unix_copy_addr()` always wants `sizeof(struct sockaddr_un)`, let's just require it. I suggest this code snippet:
```
    if (sock->domain == AF_UNIX) {
        if (*addrlen < sizeof(struct sockaddr_un)) {
            /* unix_copy_addr currently always requires the max possible size of AF_UNIX address */
            return -EINVAL;
        }
        *addrlen = unix_copy_addr(addr, sock->addr.un.sun_path);
```
___
*[LibOS/shim/src/sys/shim_socket.c, line 1722 at r4](https://reviewable.io/reviews/gramineproject/gramine/74#-MkALFKL-qOu9Q__WaZU:-MkqDlLA6ypAlKE_2_3D:bvz13tf) ([raw file](https://github.com/gramineproject/gramine/blob/e5d8faa90951baede85e4796560a59afef50679f/LibOS/shim/src/sys/shim_socket.c#L1722)):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done. Borys mentioned that you need to structure your lines of code like this:
```
    if (sock->domain == AF_UNIX) {
        *addrlen = unix_copy_addr(addr, sock->addr.un.sun_path);
    } else {
        *addrlen = inet_copy_addr(sock->domain, addr, *addrlen, &sock->addr.in.bind);
    }
```
___
*[LibOS/shim/src/sys/shim_socket.c, line 1774 at r4](https://reviewable.io/reviews/gramineproject/gramine/74#-MkAMUqb45WMxfOrM7b2:-MkqHHrl3dUwK7v31Akd:b-8nyi3w) ([raw file](https://github.com/gramineproject/gramine/blob/e5d8faa90951baede85e4796560a59afef50679f/LibOS/shim/src/sys/shim_socket.c#L1774)):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done
___
*[LibOS/shim/src/sys/shim_socket.c, line 1775 at r4](https://reviewable.io/reviews/gramineproject/gramine/74#-MkAMXSgDGjFAmdXLNmk:-MkqHIrl677VtUdzHcOu:b6o6xst) ([raw file](https://github.com/gramineproject/gramine/blob/e5d8faa90951baede85e4796560a59afef50679f/LibOS/shim/src/sys/shim_socket.c#L1775)):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

> addrlen is already verified above using function `is_user_memory_writable`
</blockquote></details>

Not done, see my comment above
___
*[LibOS/shim/src/sys/shim_socket.c, line 1780 at r4](https://reviewable.io/reviews/gramineproject/gramine/74#-MkAMkOB25en2YuuH4bw:-MkqHTYO9qSUXuOqYB-0:b-8nyi3w) ([raw file](https://github.com/gramineproject/gramine/blob/e5d8faa90951baede85e4796560a59afef50679f/LibOS/shim/src/sys/shim_socket.c#L1780)):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done
___
*[LibOS/shim/src/sys/shim_socket.c, line 295 at r6](https://reviewable.io/reviews/gramineproject/gramine/74#-MkqF7PA4VTfkO6ClqVX:-MkqF7PB-4gnIOuX_OrK:b67n5sy) ([raw file](https://github.com/gramineproject/gramine/blob/88354e86880a7399d61500c791d6662dbc7cb565/LibOS/shim/src/sys/shim_socket.c#L295)):*
> ```C
>         memcpy(un->sun_path, path, size);
> 
>     return sizeof(struct sockaddr_un);
> ```

Here you return not the dynamically-calculated minimally needed size, but the maximum possible (static) size for a UNIX domain address object. I'm fine with this but please add a comment:
```
/* for simplicity, we return not the dynimically-calculated minimally needed size but a static max size */
```
___
*[LibOS/shim/src/sys/shim_socket.c, line 476 at r6](https://reviewable.io/reviews/gramineproject/gramine/74#-MkqC6sr4c-nuCjkyIwh:-MkqC6sr4c-nuCjkyIwi:bububxn) ([raw file](https://github.com/gramineproject/gramine/blob/88354e86880a7399d61500c791d6662dbc7cb565/LibOS/shim/src/sys/shim_socket.c#L476)):*
> ```C
>         }
> 
>         size_t sun_path_size = addrlen - offsetof(struct sockaddr_un, sun_path);
> ```

FYI: You can simply use `sun_path_size` which is calculated on this line. Also note that the below `if` check verifies a too-long user-supplied name, so no need for your check.
___
*[LibOS/shim/src/sys/shim_socket.c, line 502 at r6](https://reviewable.io/reviews/gramineproject/gramine/74#-MkqCKUm52tEPuNkgCij:-MkqCKUm52tEPuNkgCik:b-lukl4b) ([raw file](https://github.com/gramineproject/gramine/blob/88354e86880a7399d61500c791d6662dbc7cb565/LibOS/shim/src/sys/shim_socket.c#L502)):*
> ```C
>             goto out;
>         }
>         memcpy(sock->addr.un.sun_path, saddr->sun_path, size);
> ```

You don't need to calculate the size and you don't need the check. It is already calculated and checked, see  [...]

2021-09-30 11:04 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/74)* status: all files reviewed, 34 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @jkr0103)

___
*[LibOS/shim/src/sys/shim_socket.c, line 985 at r6](https://reviewable.io/reviews/gramineproject/gramine/74#-MkqClu10RrKGng6h3rf:-MkqMcbL8Y_HlmGsv2H9:be2d3w6) ([raw file](https://github.com/gramineproject/gramine/blob/88354e86880a7399d61500c791d6662dbc7cb565/LibOS/shim/src/sys/shim_socket.c#L985)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We know that both these buffers are of constant size (108 bytes). So no need to do `strlen()`, simply do:
```
        memcpy(cli_sock->addr.un.sun_path, sock->addr.un.sun_path,
               sizeof(cli_sock->addr.un.sun_path));
```
</blockquote></details>

`memcpy` will always copy all 108 bytes even if path is 1 byte long. this will consume some extra cpu cycles, hence I used `strlen` as by this time we should be having path whixh is null terminated...


<!-- Sent from Reviewable.io -->

2021-09-30 11:29 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/74)* status: all files reviewed, 34 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @jkr0103)

___
*[LibOS/shim/src/sys/shim_socket.c, line 985 at r6](https://reviewable.io/reviews/gramineproject/gramine/74#-MkqClu10RrKGng6h3rf:-MkqSBfR1XyrpRjqAuc3:b-r8vqt8) ([raw file](https://github.com/gramineproject/gramine/blob/88354e86880a7399d61500c791d6662dbc7cb565/LibOS/shim/src/sys/shim_socket.c#L985)):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

`memcpy` will always copy all 108 bytes even if path is 1 byte long. this will consume some extra cpu cycles, hence I used `strlen` as by this time we should be having path whixh is null terminated...
</blockquote></details>

First, difference between copying 108 bytes and 1 byte is 0.00000001% of the CPU cycles. Don't do premature optimizations when it's not warranted.

Second, `strlen()` is a function that dynamically calculates the length of the string. So the CPU cycles you saved on not copying 107 bytes will be spent (10x as much) on calling `strlen()` and traversing through the string.


<!-- Sent from Reviewable.io -->

2021-09-30 12:27 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/74)* status: 0 of 3 files reviewed, 36 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @jkr0103)

___
*[-- commits, line 7 at r6](https://reviewable.io/reviews/gramineproject/gramine/74#-Mkq8rXV1ZojJkkt6r2Q):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`This PR` -> `This commit`.

No need to change it now, we can change it during final rebase.
</blockquote></details>

sure
___
*[LibOS/shim/include/shim_handle.h, line 125 at r6](https://reviewable.io/reviews/gramineproject/gramine/74#-Mkq8zpn7Gn4EeMO1CVd:-Mkqdejm5S3WSsgDbDUO:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/88354e86880a7399d61500c791d6662dbc7cb565/LibOS/shim/include/shim_handle.h#L125)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`108` -> `SOCK_URI_SIZE` (we have this macro defined above)

`Path name` -> `Linux stores user-supplied name as-is; we do the same` (otherwise the comment is vague)
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_socket.c, line 1716 at r4](https://reviewable.io/reviews/gramineproject/gramine/74#-MkALCeN4RMeyGUWr4Un:-Mkqe_PL8ZASqLHBBiVV:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/e5d8faa90951baede85e4796560a59afef50679f/LibOS/shim/src/sys/shim_socket.c#L1716)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Not done
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_socket.c, line 1717 at r4](https://reviewable.io/reviews/gramineproject/gramine/74#-MkALhw62X0NIe7jjdEE:-MkqeasW4R_69kv5dpqT:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/e5d8faa90951baede85e4796560a59afef50679f/LibOS/shim/src/sys/shim_socket.c#L1717)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

That's now what Borys meant. This function `shim_do_getsockname()` is called by the user app, and the user app may supply any weird number in `*addrlen` (the actual size of the buffer). So say the user app supplies `*addrlen = 1`, which means that the buffer `addr` is 1-byte long.

Now we call `unix_copy_addr()` which does `memcpy(un->sun_path, path, ARRAY_SIZE(un->sun_path) - 1)`. We are screwed: the supplied buffer was only 1 byte, but we wrote much more than 1 byte. Buffer overflow and security vulnerability!

Because we know that our current implementation of `unix_copy_addr()` always wants `sizeof(struct sockaddr_un)`, let's just require it. I suggest this code snippet:
```
    if (sock->domain == AF_UNIX) {
        if (*addrlen < sizeof(struct sockaddr_un)) {
            /* unix_copy_addr currently always requires the max possible size of AF_UNIX address */
            return -EINVAL;
        }
        *addrlen = unix_copy_addr(addr, sock->addr.un.sun_path);
```
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_socket.c, line 1722 at r4](https://reviewable.io/reviews/gramineproject/gramine/74#-MkALFKL-qOu9Q__WaZU:-Mkqecbp2hKyA0Jl3DMh:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/e5d8faa90951baede85e4796560a59afef50679f/LibOS/shim/src/sys/shim_socket.c#L1722)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Not done. Borys mentioned that you need to structure your lines of code like this:
```
    if (sock->domain == AF_UNIX) {
        *addrlen = unix_copy_addr(addr, sock->addr.un.sun_path);
    } else {
        *addrlen = inet_copy_addr(sock->domain, addr, *addrlen, &sock->addr.in.bind);
    }
```
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_socket.c, line 1774 at r4](https://reviewable.io/reviews/gramineproject/gramine/74#-MkAMUqb45WMxfOrM7b2:-Mkqee0b1SfkXddJRCgY:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/e5d8faa90951baede85e4796560a59afef50679f/LibOS/shim/src/sys/shim_socket.c#L1774)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Not done
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_socket.c, line 1775 at r4](https://reviewable.io/reviews/gramineproject/gramine/74#-MkAMXSgDGjFAmdXLNmk:-Mkqefbv0CcqshJf48Ut:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/e5d8faa90951baede85e4796560a59afef50679f/LibOS/shim/src/sys/shim_socket.c#L1775)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Not done, see my comment above
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_socket.c, line 1780 at r4](https://reviewable.io/reviews/gramineproject/gramine/74#-MkAMkOB25en2YuuH4bw:-MkqegTSA8pfxzSTW-6I:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/e5d8faa90951baede85e4796560a59afef50679f/LibOS/shim/src/sys/shim_socket.c#L1780)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Not done
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_socket.c, line 502 at r6](https://reviewable.io/reviews/gramineproject/gramine/74#-MkqCKUm52tEPuNkgCij:-MkqeMUV2Sygb54Lg0rv:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/88354e86880a7399d61500c791d6662dbc7cb565/LibOS/shim/src/sys/shim_socket.c#L502)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You don't need to calculate the size and you don't need the check. It is already calculated and checked, see my comment above.

So you can replace your whole code snippet with a simple:
```
memcpy(sock->addr.un.sun_path, saddr->sun_path, sun_path_size);
```
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_socket.c, line 793 at r6](https://reviewable.io/reviews/gramineproject/gramine/74#-MkqCbGeB72HCPVUcPbJ:-MkqeNju5CU-10nOFiYg:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/88354e86880a7399d61500c791d6662dbc7cb565/LibOS/shim/src/sys/shim_socket.c#L793)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You don't need to calculate the size and you don't need the check. It is already calculated and checked, see my comment above.

So you can replace your whole code snippet with a simple:
```
memcpy(sock->addr.un.sun_path, saddr->sun_path, sun_path_size);
```
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_socket.c, line 985 at r6](https://reviewable.io/reviews/gramineproject/gramine/74#-MkqClu10RrKGng6h3rf:-MkqeQ3c6ujL0x59109a:b-t77xdy) ([raw file](https://github.com/gramineproject/gramine/blob/88354e86880a7399d61500c791d6662dbc7cb565/LibOS/shim/src/sys/shim_socket.c#L985)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

First, difference between copying 108 bytes and 1 byte is 0.00000001% of the CPU cycles. Don't do premature optimizations when it's not warranted.

Second, `strlen()` is a function that dynamically calculates the length of the string. So the CPU cycles you saved on not copying 107 bytes will be spent (10x as much) on calling `strlen()` and traversing through the string.
</blockquote></details>

agree!
___
*[LibOS/shim/src/sys/shim_socket.c, line 1075 at r6](https://reviewable.io/reviews/gramineproject/gramine/74#-MkqeTmq9RkEknkHtxrI:-MkqeTmq9RkEknkHtxrJ:b-el7lvm) ([raw file](https://github.com/gramineproject/gramine/blob/88354e86880a7399d61500c791d6662dbc7cb565/LibOS/shim/src/sys/shim_socket.c#L1075)):*
> ```C
> 
>     if (addr) {
>         if (addrlen < 0 || (size_t)addrlen < minimal_addrlen(sock->domain)) {
> ```

removed redundant check.
___
*[LibOS/shim/src/sys/shim_socket.c, line 1320 at r6](https://reviewable.io/reviews/gramineproject/gramine/74#-MkqeXlR0a9jDzf [...]

2021-09-30 12:28 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/74)* status: 0 of 3 files reviewed, 36 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[LibOS/shim/src/sys/shim_socket.c, line 295 at r6](https://reviewable.io/reviews/gramineproject/gramine/74#-MkqF7PA4VTfkO6ClqVX:-MkqfIkdCk0VfDw9Y-IR:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/88354e86880a7399d61500c791d6662dbc7cb565/LibOS/shim/src/sys/shim_socket.c#L295)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Here you return not the dynamically-calculated minimally needed size, but the maximum possible (static) size for a UNIX domain address object. I'm fine with this but please add a comment:
```
/* for simplicity, we return not the dynimically-calculated minimally needed size but a static max size */
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-09-30 12:52 UTC, dimakuv requested changes
> Reviewed 2 of 3 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/74)* status: all files reviewed, 32 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @jkr0103)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/74#-MkqkGWhDxsp6VYMqT_J:-MkqkGWhDxsp6VYMqT_K:bbnpdcq) (no related file):*
Every time I look at `shim_socket.c`, I have tears in my eyes. This code is so bad. Sorry @jkr0103 that you have to work with this. It's like the code was written explicitly to be as unreadable as possible :(

---
___
*[LibOS/shim/src/sys/shim_socket.c, line 1075 at r6](https://reviewable.io/reviews/gramineproject/gramine/74#-MkqeTmq9RkEknkHtxrI:-Mkqkhhy5_O4q9UeCbha:b-vfqeed) ([raw file](https://github.com/gramineproject/gramine/blob/88354e86880a7399d61500c791d6662dbc7cb565/LibOS/shim/src/sys/shim_socket.c#L1075)):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

removed redundant check.
</blockquote></details>

@jkr0103 Please resolve this comment on your side (you created a blocking comment).
___
*[LibOS/shim/src/sys/shim_socket.c, line 1320 at r6](https://reviewable.io/reviews/gramineproject/gramine/74#-MkqeXlR0a9jDzfqdcb_:-MkqkmVpBDe7nOXIyXQ_:b-vfqeed) ([raw file](https://github.com/gramineproject/gramine/blob/88354e86880a7399d61500c791d6662dbc7cb565/LibOS/shim/src/sys/shim_socket.c#L1320)):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

removed redundant check.
</blockquote></details>

@jkr0103 Please resolve this comment on your side (you created a blocking comment).
___
*[LibOS/shim/src/sys/shim_socket.c, line 297 at r8](https://reviewable.io/reviews/gramineproject/gramine/74#-MkqioHL67ZS4OeRNRjP:-MkqioHL67ZS4OeRNRjQ:bwlm9a2) ([raw file](https://github.com/gramineproject/gramine/blob/e9348ec7d9dc6e85dd3b3f177bbbd5c5e29a3dc5/LibOS/shim/src/sys/shim_socket.c#L297)):*
> ```C
>         memcpy(un->sun_path, path, size);
> 
>     /* for simplicity, we return not the dynimically-calculated minimally needed size but a static
> ```

Typo: `dynamically`
___
*[LibOS/shim/src/sys/shim_socket.c, line 897 at r8](https://reviewable.io/reviews/gramineproject/gramine/74#-Mkqjc0k0OOIhAUZ7Pno:-Mkqjc0k0OOIhAUZ7Pnp:b828iws) ([raw file](https://github.com/gramineproject/gramine/blob/e9348ec7d9dc6e85dd3b3f177bbbd5c5e29a3dc5/LibOS/shim/src/sys/shim_socket.c#L897)):*
> ```C
>             return -EINVAL;
> 
>         if ((size_t)*addrlen < minimal_addrlen(sock->domain))
> ```

FYI: Please use this check for `getsockname` and `getpeername` (see my other comments)
___
*[LibOS/shim/src/sys/shim_socket.c, line 1697 at r8](https://reviewable.io/reviews/gramineproject/gramine/74#-MkqjY6u0xq7PujQr5YW:-MkqjY6v8Na8jPI7BeuF:bn1a2qk) ([raw file](https://github.com/gramineproject/gramine/blob/e9348ec7d9dc6e85dd3b3f177bbbd5c5e29a3dc5/LibOS/shim/src/sys/shim_socket.c#L1697)):*
> ```C
>     }
> 
>     if (*addrlen <= 0) {
> ```

Actually, please replace this check with `if ((size_t)*addrlen < minimal_addrlen(sock->domain))`. Then you won't need the newly-added check below.
___
*[LibOS/shim/src/sys/shim_socket.c, line 1714 at r8](https://reviewable.io/reviews/gramineproject/gramine/74#-MkqjncA1Z_mbVsUlKug:-MkqjncA1Z_mbVsUlKuh:b-iffhm8) ([raw file](https://github.com/gramineproject/gramine/blob/e9348ec7d9dc6e85dd3b3f177bbbd5c5e29a3dc5/LibOS/shim/src/sys/shim_socket.c#L1714)):*
> ```C
>             /* unix_copy_addr currently always requires the max possible size of AF_UNIX address */
>             return -EINVAL;
>         }
> ```

Actually, now that you added AF_UNIX logic to `minimal_addrlen()`, we can remove this If check completely (and add the check as I asked in the comment above).
___
*[LibOS/shim/src/sys/shim_socket.c, line 1742 at r8](https://reviewable.io/reviews/gramineproject/gramine/74#-Mkqk5ejAQlrcv8dsotk:-Mkqk5ejAQlrcv8dsotl:bn1a2qk) ([raw file](https://github.com/gramineproject/gramine/blob/e9348ec7d9dc6e85dd3b3f177bbbd5c5e29a3dc5/LibOS/shim/src/sys/shim_socket.c#L1742)):*
> ```C
>     }
> 
>     if (*addrlen <= 0) {
> ```

Actually, please replace this check with `if ((size_t)*addrlen < minimal_addrlen(sock->domain))`. Then you won't need the newly-added check below.
___
*[LibOS/shim/src/sys/shim_socket.c, line 1772 at r8](https://reviewable.io/reviews/gramineproject/gramine/74#-Mkqk24O7uS92rql6dnL:-Mkqk24O7uS92rql6dnM:b-iffhm8) ([raw file](https://github.com/gramineproject/gramine/blob/e9348ec7d9dc6e85dd3b3f177bbbd5c5e29a3dc5/LibOS/shim/src/sys/shim_socket.c#L1772)):*
> ```C
>             /* unix_copy_addr currently always requires the max possible size of AF_UNIX address */
>             return -EINVAL;
>         }
> ```

Actually, now that you added AF_UNIX logic to `minimal_addrlen()`, we can remove this If check completely (and add the check as I asked in the comment above).


<!-- Sent from Reviewable.io -->

2021-10-01 07:28 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/74)* status: 2 of 3 files reviewed, 30 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @jkr0103)

___
*[-- commits, line 2 at r4](https://reviewable.io/reviews/gramineproject/gramine/74#-MkAKeid5DHfMhDy8EWe):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Now this title misses the most important part: that this concerns `getsockname` and `getpeername`.

I suggest the following: `[LibOS] Return correct AF_UNIX-socket name in getsockname/getpeername`.

No need to change it now, we can change it during final rebase.
</blockquote></details>

sure
___
*[LibOS/shim/src/sys/shim_socket.c, line 297 at r8](https://reviewable.io/reviews/gramineproject/gramine/74#-MkqioHL67ZS4OeRNRjP:-Mkujnro-zwq69da7-9C:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/e9348ec7d9dc6e85dd3b3f177bbbd5c5e29a3dc5/LibOS/shim/src/sys/shim_socket.c#L297)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Typo: `dynamically`
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_socket.c, line 1697 at r8](https://reviewable.io/reviews/gramineproject/gramine/74#-MkqjY6u0xq7PujQr5YW:-MkujzWKBGArnNhyuzqT:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/e9348ec7d9dc6e85dd3b3f177bbbd5c5e29a3dc5/LibOS/shim/src/sys/shim_socket.c#L1697)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Actually, please replace this check with `if ((size_t)*addrlen < minimal_addrlen(sock->domain))`. Then you won't need the newly-added check below.
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_socket.c, line 1714 at r8](https://reviewable.io/reviews/gramineproject/gramine/74#-MkqjncA1Z_mbVsUlKug:-Mkuk0O4Aja675jjbe_y:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/e9348ec7d9dc6e85dd3b3f177bbbd5c5e29a3dc5/LibOS/shim/src/sys/shim_socket.c#L1714)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Actually, now that you added AF_UNIX logic to `minimal_addrlen()`, we can remove this If check completely (and add the check as I asked in the comment above).
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_socket.c, line 1742 at r8](https://reviewable.io/reviews/gramineproject/gramine/74#-Mkqk5ejAQlrcv8dsotk:-Mkuk1rm3b2mB9G9BNWh:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/e9348ec7d9dc6e85dd3b3f177bbbd5c5e29a3dc5/LibOS/shim/src/sys/shim_socket.c#L1742)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Actually, please replace this check with `if ((size_t)*addrlen < minimal_addrlen(sock->domain))`. Then you won't need the newly-added check below.
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_socket.c, line 1772 at r8](https://reviewable.io/reviews/gramineproject/gramine/74#-Mkqk24O7uS92rql6dnL:-Mkuk3Rn-5c-LA7wLdlN:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/e9348ec7d9dc6e85dd3b3f177bbbd5c5e29a3dc5/LibOS/shim/src/sys/shim_socket.c#L1772)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Actually, now that you added AF_UNIX logic to `minimal_addrlen()`, we can remove this If check completely (and add the check as I asked in the comment above).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-10-01 11:56 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/74)* status: all files reviewed, 37 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @jkr0103)

___
*[LibOS/shim/src/sys/shim_socket.c, line 453 at r10](https://reviewable.io/reviews/gramineproject/gramine/74#-MkvevHaDQR0FQ847XQ7:-MkvevHbBIkIZM106OgM:b2wfqgw) ([raw file](https://github.com/gramineproject/gramine/blob/961ea2f9dce06e91ee6b9165a651fc1a6a0a9d26/LibOS/shim/src/sys/shim_socket.c#L453)):*
> ```C
>     struct shim_sock_handle* sock = &hdl->info.sock;
>     if (addr) {
>         if ((size_t)_addrlen < minimal_addrlen(sock->domain))
> ```

You also need to check `_addrlen < 0` because your current check will cast a negative number to some huge positive number (if `_addrlen` was negative,  then `(size_t)_addrlen` gives some huuuge number which is definitely greater than `minimal_addrlen()`).

So you need:
```
        if (_addrlen < 0 || (size_t)_addrlen < minimal_addrlen(sock->domain))
            return -EINVAL;
```
___
*[LibOS/shim/src/sys/shim_socket.c, line 455 at r10](https://reviewable.io/reviews/gramineproject/gramine/74#-MkvfOOr5gFzrn6BLpQd:-MkvfOOr5gFzrn6BLpQe:babdlje) ([raw file](https://github.com/gramineproject/gramine/blob/961ea2f9dce06e91ee6b9165a651fc1a6a0a9d26/LibOS/shim/src/sys/shim_socket.c#L455)):*
> ```C
>         if ((size_t)_addrlen < minimal_addrlen(sock->domain))
>             return -EINVAL;
>         if (!is_user_memory_readable(addr, _addrlen))
> ```

Are you sure this compiles without errors? `is_user_memory_readable()` expects the second argument of type `size_t`, and you supply `_addrlen` of type `int`...
___
*[LibOS/shim/src/sys/shim_socket.c, line 457 at r10](https://reviewable.io/reviews/gramineproject/gramine/74#-MkvedD24OA36Hkr3jvC:-MkvedD24OA36Hkr3jvD:bq4fzkg) ([raw file](https://github.com/gramineproject/gramine/blob/961ea2f9dce06e91ee6b9165a651fc1a6a0a9d26/LibOS/shim/src/sys/shim_socket.c#L457)):*
> ```C
>         if (!is_user_memory_readable(addr, _addrlen))
>             return -EFAULT;
>     }
> ```

Why did you add `if (addr)` check? It is not needed -- `man 2 bind` tells us that `addr` is a required argument. If `addr = NULL` is passed to this function, then it should result in `EFAULT` (which is what happened before because of the check `!is_user_memory_readable`).

Please remove the `if (addr)` check.
___
*[LibOS/shim/src/sys/shim_socket.c, line 720 at r10](https://reviewable.io/reviews/gramineproject/gramine/74#-MkvfZiXAw0QFVK2Crgg:-MkvfZiXAw0QFVK2Crgh:b-ndtcyb) ([raw file](https://github.com/gramineproject/gramine/blob/961ea2f9dce06e91ee6b9165a651fc1a6a0a9d26/LibOS/shim/src/sys/shim_socket.c#L720)):*
> ```C
>         if (!is_user_memory_readable(addr, _addrlen))
>             return -EFAULT;
>     }
> ```

ditto (all the same comments as above)
___
*[LibOS/shim/src/sys/shim_socket.c, line 893 at r10](https://reviewable.io/reviews/gramineproject/gramine/74#-MkvfeHkE_qlr01foWZL:-MkvfeHkE_qlr01foWZM:b8u31yg) ([raw file](https://github.com/gramineproject/gramine/blob/3e778e576f25ad2e497e8651b919487cfb9fc076/LibOS/shim/src/sys/shim_socket.c#L893)):*
> ```C
>         return -EOPNOTSUPP;
>     }
> ```

Why did you remove this line? It was more readable with this empty line.
___
*[LibOS/shim/src/sys/shim_socket.c, line 898 at r10](https://reviewable.io/reviews/gramineproject/gramine/74#-Mkvfuz2A16Jnd_vfSLH:-Mkvfuz2A16Jnd_vfSLI:b19cpud) ([raw file](https://github.com/gramineproject/gramine/blob/3e778e576f25ad2e497e8651b919487cfb9fc076/LibOS/shim/src/sys/shim_socket.c#L898)):*
> ```C
>             return -EINVAL;
> 
>         if (*addrlen < 0 || (size_t)*addrlen < minimal_addrlen(sock->domain))
> ```

Please keep this `*addrlen < 0`. See my comment above.
___
*[LibOS/shim/src/sys/shim_socket.c, line 1072 at r10](https://reviewable.io/reviews/gramineproject/gramine/74#-MkvgB3v5P9lAQg139j8:-MkvgB3v5P9lAQg139j9:buvdq5u) ([raw file](https://github.com/gramineproject/gramine/blob/3e778e576f25ad2e497e8651b919487cfb9fc076/LibOS/shim/src/sys/shim_socket.c#L1072)):*
> ```C
> 
>     if (addr) {
>         if (addrlen < 0 || (size_t)addrlen < minimal_addrlen(sock->domain)) {
> ```

This is needed, please keep it
___
*[LibOS/shim/src/sys/shim_socket.c, line 1317 at r10](https://reviewable.io/reviews/gramineproject/gramine/74#-MkvgDJY-FLN3UIxZi4E:-MkvgDJY-FLN3UIxZi4F:buvdq5u) ([raw file](https://github.com/gramineproject/gramine/blob/3e778e576f25ad2e497e8651b919487cfb9fc076/LibOS/shim/src/sys/shim_socket.c#L1317)):*
> ```C
> 
>     if (addr) {
>         if (*addrlen < 0 || (size_t)*addrlen < minimal_addrlen(sock->domain)) {
> ```

This is needed, please keep it
___
*[LibOS/shim/src/sys/shim_socket.c, line 1547 at r10](https://reviewable.io/reviews/gramineproject/gramine/74#-MkvgRc42ToptJjnnV1e:-MkvgRc42ToptJjnnV1f:bxgvsa5) ([raw file](https://github.com/gramineproject/gramine/blob/961ea2f9dce06e91ee6b9165a651fc1a6a0a9d26/LibOS/shim/src/sys/shim_socket.c#L1547)):*
> ```C
>         return -ENOTSOCK;
> 
>     struct shim_sock_handle* sock = &hdl->info.sock;
> ```

Please remove your changes from here and instead add the check `(size_t)*addrlen < minimal_addrlen(sock->domain)` to `do_recvmsg()`. Because this function anyway calls `do_recvmsg()` which gets the `hdl` and so on...
___
*[LibOS/shim/src/sys/shim_socket.c, line 1702 at r10](https://reviewable.io/reviews/gramineproject/gramine/74#-MkvgmsHDiLA69UhuYri:-MkvgmsHDiLA69UhuYrj:b-cw8ila) ([raw file](https://github.com/gramineproject/gramine/blob/961ea2f9dce06e91ee6b9165a651fc1a6a0a9d26/LibOS/shim/src/sys/shim_socket.c#L1702)):*
> ```C
>     }
>     struct shim_sock_handle* sock = &hdl->info.sock;
>     if (addr) {
> ```

Please remove this `if (addr)`. `man 2 getsockname` tells us that `addr` is a required argument.
___
*[LibOS/shim/src/sys/shim_socket.c, line 1708 at r10](https://reviewable.io/reviews/gramineproject/gramine/74#-MkvgskGCO7hCVSEm2Hg:-MkvgskGCO7hCVSEm2Hh:b-e46bde) ([raw file](https://github.com/gramineproject/gramine/blob/961ea2f9dce06e91ee6b9165a651fc1a6a0a9d26/LibOS/shim/src/sys/shim_socket.c#L1708)):*
> ```C
>         }
> 
>         if ((size_t)*addrlen < minimal_addrlen(sock->domain)) {
> ```

I think this was my mistaken suggestion to remove `*addrlen <= 0`. This is actually needed (as I explained in the other comment). So please replace with this:
```
if (*addrlen < 0 || (size_t)*addrlen < minimal_addrlen(sock->domain)) {
```
___
*[LibOS/shim/src/sys/shim_socket.c, line 1744 at r10](https://reviewable.io/reviews/gramineproject/gramine/74#-MkvhGnjBDrLQhJJS7dy:-MkvhGnjBDrLQhJJS7dz:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/961ea2f9dce06e91ee6b9165a651fc1a6a0a9d26/LibOS/shim/src/sys/shim_socket.c#L1744)):*
> ```C
>     }
>     struct shim_sock_handle* sock = &hdl->info.sock;
>     if (addr) {
> ```

ditto
___
*[LibOS/shim/src/sys/shim_socket.c, line 1750 at r10](https://reviewable.io/reviews/gramineproject/gramine/74#-MkvhF1YB6pZYsbKq0zT:-MkvhF1bBJTN9nkigD_a:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/961ea2f9dce06e91ee6b9165a651fc1a6a0a9d26/LibOS/shim/src/sys/shim_socket.c#L1750)):*
> ```C
>         }
> 
>         if ((size_t)*addrlen < minimal_addrlen(sock->domain)) {
> ```

ditto


<!-- Sent from Reviewable.io -->

2021-10-01 12:29 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/74)* status: all files reviewed, 37 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @jkr0103)

___
*[LibOS/shim/src/sys/shim_socket.c, line 455 at r10](https://reviewable.io/reviews/gramineproject/gramine/74#-MkvfOOr5gFzrn6BLpQd:-Mkvp1-M6gkfGz9St_RI:b200qy2) ([raw file](https://github.com/gramineproject/gramine/blob/961ea2f9dce06e91ee6b9165a651fc1a6a0a9d26/LibOS/shim/src/sys/shim_socket.c#L455)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Are you sure this compiles without errors? `is_user_memory_readable()` expects the second argument of type `size_t`, and you supply `_addrlen` of type `int`...
</blockquote></details>

yes this compiled with both debug and release builds.
___
*[LibOS/shim/src/sys/shim_socket.c, line 1547 at r10](https://reviewable.io/reviews/gramineproject/gramine/74#-MkvgRc42ToptJjnnV1e:-MkvoBap9Jfmj6P5MzVE:b-b6ppyu) ([raw file](https://github.com/gramineproject/gramine/blob/961ea2f9dce06e91ee6b9165a651fc1a6a0a9d26/LibOS/shim/src/sys/shim_socket.c#L1547)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please remove your changes from here and instead add the check `(size_t)*addrlen < minimal_addrlen(sock->domain)` to `do_recvmsg()`. Because this function anyway calls `do_recvmsg()` which gets the `hdl` and so on...
</blockquote></details>

should not we check for correct `addrlen` before this check`is_user_memory_writable(addr, *addrlen)`. I did it consistently as per Borys's suggestion.
`(size_t)*addrlen < minimal_addrlen(sock->domain)` check is already there in `do_recvmsg()`.


<!-- Sent from Reviewable.io -->

2021-10-01 12:47 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/74)* status: all files reviewed, 36 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @jkr0103)

___
*[LibOS/shim/src/sys/shim_socket.c, line 455 at r10](https://reviewable.io/reviews/gramineproject/gramine/74#-MkvfOOr5gFzrn6BLpQd:-MkvsH_K0aTvvmuMGkVr:b3685hx) ([raw file](https://github.com/gramineproject/gramine/blob/961ea2f9dce06e91ee6b9165a651fc1a6a0a9d26/LibOS/shim/src/sys/shim_socket.c#L455)):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

yes this compiled with both debug and release builds.
</blockquote></details>

OK, then it's all good, nothing to change here.
___
*[LibOS/shim/src/sys/shim_socket.c, line 1547 at r10](https://reviewable.io/reviews/gramineproject/gramine/74#-MkvgRc42ToptJjnnV1e:-MkvsSvU1hnt9rPiX1_f:bhxygiz) ([raw file](https://github.com/gramineproject/gramine/blob/961ea2f9dce06e91ee6b9165a651fc1a6a0a9d26/LibOS/shim/src/sys/shim_socket.c#L1547)):*
But then why would you check the same condition twice in the same code flow? There is no need for this.

> should not we check for correct addrlen before this checkis_user_memory_writable(addr, *addrlen). I did it consistently as per Borys's suggestion.

But the original code already checks everything correctly: it first checks that `addrlen` memory cell itself is writable, then it checks that `*addrlen` (value in that memory cell) is non-negative, and then it checks that the memory region `[addr, *addrlen)]` is writable. Everything seems correct there. Plus you now have this new check of `(size_t)*addrlen < minimal_addrlen(sock->domain)` in `do_recvmsg()`, so everything is already checked and everything is fine.


<!-- Sent from Reviewable.io -->

2021-10-01 13:17 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/74)* status: 2 of 3 files reviewed, 36 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[LibOS/shim/src/sys/shim_socket.c, line 453 at r10](https://reviewable.io/reviews/gramineproject/gramine/74#-MkvevHaDQR0FQ847XQ7:-Mkw-2zm9qR-6zeF5Ov-:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/961ea2f9dce06e91ee6b9165a651fc1a6a0a9d26/LibOS/shim/src/sys/shim_socket.c#L453)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You also need to check `_addrlen < 0` because your current check will cast a negative number to some huge positive number (if `_addrlen` was negative,  then `(size_t)_addrlen` gives some huuuge number which is definitely greater than `minimal_addrlen()`).

So you need:
```
        if (_addrlen < 0 || (size_t)_addrlen < minimal_addrlen(sock->domain))
            return -EINVAL;
```
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_socket.c, line 457 at r10](https://reviewable.io/reviews/gramineproject/gramine/74#-MkvedD24OA36Hkr3jvC:-MkvzznS9XEZpyM-OjOd:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/961ea2f9dce06e91ee6b9165a651fc1a6a0a9d26/LibOS/shim/src/sys/shim_socket.c#L457)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why did you add `if (addr)` check? It is not needed -- `man 2 bind` tells us that `addr` is a required argument. If `addr = NULL` is passed to this function, then it should result in `EFAULT` (which is what happened before because of the check `!is_user_memory_readable`).

Please remove the `if (addr)` check.
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_socket.c, line 720 at r10](https://reviewable.io/reviews/gramineproject/gramine/74#-MkvfZiXAw0QFVK2Crgg:-MkvzxBZBMxXQ8rbojUY:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/961ea2f9dce06e91ee6b9165a651fc1a6a0a9d26/LibOS/shim/src/sys/shim_socket.c#L720)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto (all the same comments as above)
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_socket.c, line 893 at r10](https://reviewable.io/reviews/gramineproject/gramine/74#-MkvfeHkE_qlr01foWZL:-MkvzsdLC0Pt8QET0TR8:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/3e778e576f25ad2e497e8651b919487cfb9fc076/LibOS/shim/src/sys/shim_socket.c#L893)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why did you remove this line? It was more readable with this empty line.
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_socket.c, line 898 at r10](https://reviewable.io/reviews/gramineproject/gramine/74#-Mkvfuz2A16Jnd_vfSLH:-Mkvzr8X2-18y5f7O0CM:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/3e778e576f25ad2e497e8651b919487cfb9fc076/LibOS/shim/src/sys/shim_socket.c#L898)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please keep this `*addrlen < 0`. See my comment above.
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_socket.c, line 1072 at r10](https://reviewable.io/reviews/gramineproject/gramine/74#-MkvgB3v5P9lAQg139j8:-Mkvzpae9kzuiTzfpJmn:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/3e778e576f25ad2e497e8651b919487cfb9fc076/LibOS/shim/src/sys/shim_socket.c#L1072)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This is needed, please keep it
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_socket.c, line 1317 at r10](https://reviewable.io/reviews/gramineproject/gramine/74#-MkvgDJY-FLN3UIxZi4E:-Mkvzo9K2VXZmBW7wTxv:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/3e778e576f25ad2e497e8651b919487cfb9fc076/LibOS/shim/src/sys/shim_socket.c#L1317)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This is needed, please keep it
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_socket.c, line 1547 at r10](https://reviewable.io/reviews/gramineproject/gramine/74#-MkvgRc42ToptJjnnV1e:-MkvzlzJ4xyaqzzG88xU:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/961ea2f9dce06e91ee6b9165a651fc1a6a0a9d26/LibOS/shim/src/sys/shim_socket.c#L1547)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

But then why would you check the same condition twice in the same code flow? There is no need for this.

> should not we check for correct addrlen before this checkis_user_memory_writable(addr, *addrlen). I did it consistently as per Borys's suggestion.

But the original code already checks everything correctly: it first checks that `addrlen` memory cell itself is writable, then it checks that `*addrlen` (value in that memory cell) is non-negative, and then it checks that the memory region `[addr, *addrlen)]` is writable. Everything seems correct there. Plus you now have this new check of `(size_t)*addrlen < minimal_addrlen(sock->domain)` in `do_recvmsg()`, so everything is already checked and everything is fine.
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_socket.c, line 1702 at r10](https://reviewable.io/reviews/gramineproject/gramine/74#-MkvgmsHDiLA69UhuYri:-MkvzeJkCMhqPUpO25Qz:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/961ea2f9dce06e91ee6b9165a651fc1a6a0a9d26/LibOS/shim/src/sys/shim_socket.c#L1702)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please remove this `if (addr)`. `man 2 getsockname` tells us that `addr` is a required argument.
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_socket.c, line 1708 at r10](https://reviewable.io/reviews/gramineproject/gramine/74#-MkvgskGCO7hCVSEm2Hg:-MkvzbvOC734ENSmIbEa:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/961ea2f9dce06e91ee6b9165a651fc1a6a0a9d26/LibOS/shim/src/sys/shim_socket.c#L1708)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I think this was my mistaken suggestion to remove `*addrlen <= 0`. This is actually needed (as I explained in the other comment). So please replace with this:
```
if (*addrlen < 0 || (size_t)*addrlen < minimal_addrlen(sock->domain)) {
```
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_socket.c, line 1744 at r10](https://reviewable.io/reviews/gramineproject/gramine/74#-MkvhGnjBDrLQhJJS7dy:-MkvzWHH2TKxfR8ONO21:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/961ea2f9dce06e91ee6b9165a651fc1a6a0a9d26/LibOS/shim/src/sys/shim_socket.c#L1744)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_socket.c, line 1750 at r10](https://reviewable.io/reviews/gramineproject/gramine/74#-MkvhF1YB6pZYsbKq0zT:-MkvzUU10AYYrKpUwdy5:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/961ea2f9dce06e91ee6b9165a651fc1a6a0a9d26/LibOS/shim/src/sys/shim_socket.c#L1750)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-10-02 17:11 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/74)* status: all files reviewed, 30 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @jkr0103)

___
*[LibOS/shim/src/sys/shim_socket.c, line 452 at r11](https://reviewable.io/reviews/gramineproject/gramine/74#-Ml0yCtI99zxG0vTiZRw:-Ml0yCtI99zxG0vTiZRx:blkuccc) ([raw file](https://github.com/gramineproject/gramine/blob/33037726d3bbff6aabc048447ec2ddb3d5eadd08/LibOS/shim/src/sys/shim_socket.c#L452)):*
> ```C
>     struct shim_sock_handle* sock = &hdl->info.sock;
>     if (_addrlen < 0 || (size_t)_addrlen < minimal_addrlen(sock->domain))
>         return -EINVAL;
> ```

You also need to `put_handle(hdl)` before returning. Otherwise you have a memory leak.
___
*[LibOS/shim/src/sys/shim_socket.c, line 454 at r11](https://reviewable.io/reviews/gramineproject/gramine/74#-Ml0yJIO6aYw1AxiefnW:-Ml0yJIO6aYw1AxiefnX:blkuccc) ([raw file](https://github.com/gramineproject/gramine/blob/33037726d3bbff6aabc048447ec2ddb3d5eadd08/LibOS/shim/src/sys/shim_socket.c#L454)):*
> ```C
>         return -EINVAL;
>     if (!is_user_memory_readable(addr, _addrlen))
>         return -EFAULT;
> ```

You also need to `put_handle(hdl)` before returning. Otherwise you have a memory leak.
___
*[LibOS/shim/src/sys/shim_socket.c, line 713 at r11](https://reviewable.io/reviews/gramineproject/gramine/74#-Ml0yQT562JQ925s8hy-:-Ml0yQT562JQ925s8hy0:blkuccc) ([raw file](https://github.com/gramineproject/gramine/blob/33037726d3bbff6aabc048447ec2ddb3d5eadd08/LibOS/shim/src/sys/shim_socket.c#L713)):*
> ```C
>     struct shim_sock_handle* sock = &hdl->info.sock;
>     if (_addrlen < 0 || (size_t)_addrlen < minimal_addrlen(sock->domain))
>         return -EINVAL;
> ```

You also need to `put_handle(hdl)` before returning. Otherwise you have a memory leak.
___
*[LibOS/shim/src/sys/shim_socket.c, line 716 at r11](https://reviewable.io/reviews/gramineproject/gramine/74#-Ml0yR4l00mO6EQ1ADcQ:-Ml0yR4l00mO6EQ1ADcR:blkuccc) ([raw file](https://github.com/gramineproject/gramine/blob/33037726d3bbff6aabc048447ec2ddb3d5eadd08/LibOS/shim/src/sys/shim_socket.c#L716)):*
> ```C
> 
>     if (!is_user_memory_readable(addr, _addrlen))
>         return -EFAULT;
> ```

You also need to `put_handle(hdl)` before returning. Otherwise you have a memory leak.
___
*[LibOS/shim/src/sys/shim_socket.c, line 1692 at r11](https://reviewable.io/reviews/gramineproject/gramine/74#-Ml0yupWCKih6KvTvSwu:-Ml0yupWCKih6KvTvSwv:b8g104j) ([raw file](https://github.com/gramineproject/gramine/blob/33037726d3bbff6aabc048447ec2ddb3d5eadd08/LibOS/shim/src/sys/shim_socket.c#L1692)):*
> ```C
>         goto out;
>     }
>     struct shim_sock_handle* sock = &hdl->info.sock;
> ```

Could you add an empty line after this one? It will be easier to read.
___
*[LibOS/shim/src/sys/shim_socket.c, line 1732 at r11](https://reviewable.io/reviews/gramineproject/gramine/74#-Ml0zDyt4cjgaJJ11RW2:-Ml0zDyt4cjgaJJ11RW3:b8g104j) ([raw file](https://github.com/gramineproject/gramine/blob/33037726d3bbff6aabc048447ec2ddb3d5eadd08/LibOS/shim/src/sys/shim_socket.c#L1732)):*
> ```C
>         goto out;
>     }
>     struct shim_sock_handle* sock = &hdl->info.sock;
> ```

Could you add an empty line after this one? It will be easier to read.


<!-- Sent from Reviewable.io -->

2021-10-02 17:12 UTC, dimakuv commented
Jenkins, test this please

2021-10-03 10:54 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/74)* status: all files reviewed, 32 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @jkr0103)

___
*[LibOS/shim/src/sys/shim_socket.c, line 446 at r11](https://reviewable.io/reviews/gramineproject/gramine/74#-Ml4m-DeAzweidaeKWhj:-Ml4m-DeAzweidaeKWhk:b-h6x2uv) ([raw file](https://github.com/gramineproject/gramine/blob/3e778e576f25ad2e497e8651b919487cfb9fc076/LibOS/shim/src/sys/shim_socket.c#L446)):*
> ```C
>     size_t addrlen = _addrlen;
>     if (!is_user_memory_readable(addr, addrlen))
>         return -EFAULT;
> ```

Now that you rearranged the order of errors (you now may fail with `EBADF` and `ENOTSOCK` instead of `EINVAL`/`EFAULT`), some LTP tets fail:
```
test-direct / apps.LTP.getpeername01 (from (ltp.xml))

Standard Output
getpeername01    1  TPASS  :  test getpeername() EBADF successful
getpeername01    2  TPASS  :  test getpeername() ENOTSOCK successful
getpeername01    3  TPASS  :  test getpeername() ENOTCONN successful
getpeername01    4  TPASS  :  test getpeername() EINVAL successful
getpeername01    5  TFAIL  :  /home/jenkins/workspace/graphene-18.04/LibOS/shim/test/ltp/src/testcases/kernel/syscalls/getpeername/getpeername01.c:116: test getpeername() EFAULT failed; returned -1 (expected -1), errno 22 (expected 14)
getpeername01    6  TPASS  :  test getpeername() EFAULT successful
getpeername01    7  TPASS  :  test getpeername() EFAULT successful
```

```
test-direct / apps.LTP.accept01 (from (ltp.xml))

Standard Output
/home/jenkins/workspace/graphene-18.04/LibOS/shim/test/ltp/src/lib/tst_test.c:1250: TINFO: Timeout per run is 0h 05m 00s
/home/jenkins/workspace/graphene-18.04/LibOS/shim/test/ltp/src/testcases/kernel/syscalls/accept/accept01.c:112: TPASS: bad file descriptor successful: EBADF (9)
/home/jenkins/workspace/graphene-18.04/LibOS/shim/test/ltp/src/testcases/kernel/syscalls/accept/accept01.c:112: TPASS: fd is not socket successful: ENOTSOCK (88)
/home/jenkins/workspace/graphene-18.04/LibOS/shim/test/ltp/src/testcases/kernel/syscalls/accept/accept01.c:108: TFAIL: invalid socket buffer: expected errno EINVAL, got : EFAULT (14)
/home/jenkins/workspace/graphene-18.04/LibOS/shim/test/ltp/src/testcases/kernel/syscalls/accept/accept01.c:112: TPASS: invalid salen successful: EINVAL (22)
/home/jenkins/workspace/graphene-18.04/LibOS/shim/test/ltp/src/testcases/kernel/syscalls/accept/accept01.c:112: TPASS: no queued connections successful: EINVAL (22)
/home/jenkins/workspace/graphene-18.04/LibOS/shim/test/ltp/src/testcases/kernel/syscalls/accept/accept01.c:112: TPASS: UDP accept successful: EOPNOTSUPP (95)
```

Please fix (by returning to the correct order of errors).

Please also run all LTP tests locally on your machine before pushing here, to make sure everything passes with your changes.
___
*[LibOS/shim/src/sys/shim_socket.c, line 708 at r11](https://reviewable.io/reviews/gramineproject/gramine/74#-Ml4mK76Bxqih5AOoW1I:-Ml4mK772GvTlXrpACA3:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/3e778e576f25ad2e497e8651b919487cfb9fc076/LibOS/shim/src/sys/shim_socket.c#L708)):*
> ```C
> 
>     if (!is_user_memory_readable(addr, addrlen))
>         return -EFAULT;
> ```

ditto


<!-- Sent from Reviewable.io -->

2021-10-04 06:06 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/74)* status: all files reviewed, 32 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @jkr0103)

___
*[LibOS/shim/src/sys/shim_socket.c, line 446 at r11](https://reviewable.io/reviews/gramineproject/gramine/74#-Ml4m-DeAzweidaeKWhj:-Ml8qvUC9o0V1825Yl2x:bkrk1z7) ([raw file](https://github.com/gramineproject/gramine/blob/3e778e576f25ad2e497e8651b919487cfb9fc076/LibOS/shim/src/sys/shim_socket.c#L446)):*
> ```
>   if (_addrlen < 0)
> ```
earlier only condition`if (_addrlen < 0)` was executed, but now I have added one more condition `(size_t)_addrlen < minimal_addrlen(sock->domain)` to this test and for this, we need `sock->domain`. That is the reason I have rearranged the order of errors. Another way to fix the `LTP` test failure, is to modify the `LTP` tests itself instead of the code here.


<!-- Sent from Reviewable.io -->

2021-10-04 06:14 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/74)* status: all files reviewed, 32 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @jkr0103)

___
*[LibOS/shim/src/sys/shim_socket.c, line 446 at r11](https://reviewable.io/reviews/gramineproject/gramine/74#-Ml4m-DeAzweidaeKWhj:-Ml8v5PI5TzqRr04nBNr:bgwzx4d) ([raw file](https://github.com/gramineproject/gramine/blob/3e778e576f25ad2e497e8651b919487cfb9fc076/LibOS/shim/src/sys/shim_socket.c#L446)):*
> earlier only conditionif (_addrlen < 0) was executed, but now I have added one more condition (size_t)_addrlen < minimal_addrlen(sock->domain) to this test and for this, we need sock->domain. That is the reason I have rearranged the order of errors.

I understand this. I am suggesting to restore the previous code (the check for `_addrlen < 0` and the check for `!is_user_memory_readable(addr, addrlen))`). **Plus** add your new check `(size_t)_addrlen < minimal_addrlen(sock->domain)` as you do after the statement `struct shim_sock_handle* sock = &hdl->info.sock;`.

This way you'll have both the previous correct ordering of error codes, and your new check for `minimal_addrlen`. I understand your desire to simplify the code and have similar checks together, but here we just can't do it (without incorrect side effects).

> Another way to fix the LTP test failure, is to modify the LTP tests itself instead of the code here.

No, this is impossible. First of all, LTP is a thirdy-party test suite, we cannot modify it to "fit" into Gramine. Second, LTP tests how Linux kernel would behave, and Gramine should be a "drop-in" replacement for the Linux kernel -- so if Linux behaves likes this (what LTP tests), then Gramine should behave exactly like this (even if sometimes it is stupid).


<!-- Sent from Reviewable.io -->

2021-10-04 09:20 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/74)* status: 2 of 3 files reviewed, 32 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @jkr0103)

___
*[LibOS/shim/src/sys/shim_socket.c, line 446 at r11](https://reviewable.io/reviews/gramineproject/gramine/74#-Ml4m-DeAzweidaeKWhj:-Ml9aO2l1Q4mYdNCvfXS:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/3e778e576f25ad2e497e8651b919487cfb9fc076/LibOS/shim/src/sys/shim_socket.c#L446)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> earlier only conditionif (_addrlen < 0) was executed, but now I have added one more condition (size_t)_addrlen < minimal_addrlen(sock->domain) to this test and for this, we need sock->domain. That is the reason I have rearranged the order of errors.

I understand this. I am suggesting to restore the previous code (the check for `_addrlen < 0` and the check for `!is_user_memory_readable(addr, addrlen))`). **Plus** add your new check `(size_t)_addrlen < minimal_addrlen(sock->domain)` as you do after the statement `struct shim_sock_handle* sock = &hdl->info.sock;`.

This way you'll have both the previous correct ordering of error codes, and your new check for `minimal_addrlen`. I understand your desire to simplify the code and have similar checks together, but here we just can't do it (without incorrect side effects).

> Another way to fix the LTP test failure, is to modify the LTP tests itself instead of the code here.

No, this is impossible. First of all, LTP is a thirdy-party test suite, we cannot modify it to "fit" into Gramine. Second, LTP tests how Linux kernel would behave, and Gramine should be a "drop-in" replacement for the Linux kernel -- so if Linux behaves likes this (what LTP tests), then Gramine should behave exactly like this (even if sometimes it is stupid).
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_socket.c, line 452 at r11](https://reviewable.io/reviews/gramineproject/gramine/74#-Ml0yCtI99zxG0vTiZRw:-Ml9aT-tA97d2YIkFgaS:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/33037726d3bbff6aabc048447ec2ddb3d5eadd08/LibOS/shim/src/sys/shim_socket.c#L452)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You also need to `put_handle(hdl)` before returning. Otherwise you have a memory leak.
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_socket.c, line 454 at r11](https://reviewable.io/reviews/gramineproject/gramine/74#-Ml0yJIO6aYw1AxiefnW:-Ml9aSiz4XtUX95Jiyq0:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/33037726d3bbff6aabc048447ec2ddb3d5eadd08/LibOS/shim/src/sys/shim_socket.c#L454)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You also need to `put_handle(hdl)` before returning. Otherwise you have a memory leak.
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_socket.c, line 708 at r11](https://reviewable.io/reviews/gramineproject/gramine/74#-Ml4mK76Bxqih5AOoW1I:-Ml9aOtD-TOWK-Ymf7vv:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/3e778e576f25ad2e497e8651b919487cfb9fc076/LibOS/shim/src/sys/shim_socket.c#L708)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_socket.c, line 713 at r11](https://reviewable.io/reviews/gramineproject/gramine/74#-Ml0yQT562JQ925s8hy-:-Ml9aSKS8FGD9QFcwztd:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/33037726d3bbff6aabc048447ec2ddb3d5eadd08/LibOS/shim/src/sys/shim_socket.c#L713)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You also need to `put_handle(hdl)` before returning. Otherwise you have a memory leak.
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_socket.c, line 1692 at r11](https://reviewable.io/reviews/gramineproject/gramine/74#-Ml0yupWCKih6KvTvSwu:-Ml9aRCJ5tyapBW-zSKT:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/33037726d3bbff6aabc048447ec2ddb3d5eadd08/LibOS/shim/src/sys/shim_socket.c#L1692)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you add an empty line after this one? It will be easier to read.
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_socket.c, line 1732 at r11](https://reviewable.io/reviews/gramineproject/gramine/74#-Ml0zDyt4cjgaJJ11RW2:-Ml9aQ4SEcKuVRbqTNPE:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/33037726d3bbff6aabc048447ec2ddb3d5eadd08/LibOS/shim/src/sys/shim_socket.c#L1732)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you add an empty line after this one? It will be easier to read.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-10-04 09:20 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/74)* status: 2 of 3 files reviewed, 32 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[LibOS/shim/src/sys/shim_socket.c, line 716 at r11](https://reviewable.io/reviews/gramineproject/gramine/74#-Ml0yR4l00mO6EQ1ADcQ:-Ml9aeKu0aZbB7s6BzDB:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/33037726d3bbff6aabc048447ec2ddb3d5eadd08/LibOS/shim/src/sys/shim_socket.c#L716)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You also need to `put_handle(hdl)` before returning. Otherwise you have a memory leak.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-10-04 10:05 UTC, dimakuv reviewed
> Reviewed 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/74)* status: all files reviewed, 24 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)



<!-- Sent from Reviewable.io -->

2021-10-04 10:17 UTC, dimakuv commented
Jenkins, test this please

2021-10-04 15:42 UTC, boryspoplawski requested changes
> Reviewed 1 of 1 files at r8, 1 of 2 files at r10, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/74)* status: all files reviewed, 24 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @jkr0103)

___
*[LibOS/shim/src/sys/shim_socket.c, line 1717 at r4](https://reviewable.io/reviews/gramineproject/gramine/74#-MkALhw62X0NIe7jjdEE:-MlAswRW3MVy67IST4_e:b-1dpyp7) ([raw file](https://github.com/gramineproject/gramine/blob/e5d8faa90951baede85e4796560a59afef50679f/LibOS/shim/src/sys/shim_socket.c#L1717)):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Unfortunately, we cannot require full `sizeof(struct sockaddr_un)`.
___
*[LibOS/shim/src/sys/shim_socket.c, line 1775 at r4](https://reviewable.io/reviews/gramineproject/gramine/74#-MkAMXSgDGjFAmdXLNmk:-MlAtmol5g6IEBB-xg6x:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/e5d8faa90951baede85e4796560a59afef50679f/LibOS/shim/src/sys/shim_socket.c#L1775)):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

ditto
___
*[LibOS/shim/src/sys/shim_socket.c, line 54 at r12](https://reviewable.io/reviews/gramineproject/gramine/74#-MlAcam31JxEOjMV_riQ:-MlAcam4AXPY9lTjdxXC:b-q9nqi8) ([raw file](https://github.com/gramineproject/gramine/blob/2064b02050e345f318b5bd8191df2b2034295461/LibOS/shim/src/sys/shim_socket.c#L54)):*
> ```C
>     switch (domain) {
>         case AF_UNIX:
>             return sizeof(struct sockaddr_un);
> ```

This is invalid, Linux allows for smaller sizes for `AF_UNIX`.
___
*[LibOS/shim/src/sys/shim_socket.c, line 286 at r12](https://reviewable.io/reviews/gramineproject/gramine/74#-MlAnNFNBBS7kvungAVY:-MlAnNFNBBS7kvungAVZ:b-hghdlj) ([raw file](https://github.com/gramineproject/gramine/blob/2064b02050e345f318b5bd8191df2b2034295461/LibOS/shim/src/sys/shim_socket.c#L286)):*
> ```C
> }
> 
> static int unix_copy_addr(struct sockaddr* saddr, const char* path) {
> ```

This function should have `struct sockaddr_un*` as first argument (it was like that before, but since you are changing it, then please also fix this). It should be responsibility of the caller to cast to appropriate type.
Also since it does no longer return errors, please change return type to `size_t`.
___
*[LibOS/shim/src/sys/shim_socket.c, line 297 at r12](https://reviewable.io/reviews/gramineproject/gramine/74#-MlAoXxV8m0jvjC-JQOJ:-MlAoXxW2icRTZmbiobr:b-1jc21c) ([raw file](https://github.com/gramineproject/gramine/blob/2064b02050e345f318b5bd8191df2b2034295461/LibOS/shim/src/sys/shim_socket.c#L297)):*
> ```C
>         memcpy(un->sun_path, path, size);
> 
>     /* for simplicity, we return not the dynamically-calculated minimally needed size but a static
> ```

This might be simpler, but is incorrect, Linux kernel returns actual size.
___
*[LibOS/shim/src/sys/shim_socket.c, line 306 at r12](https://reviewable.io/reviews/gramineproject/gramine/74#-MlAVwuF5R8xzeJ6fqAH:-MlAVwuF5R8xzeJ6fqAI:b-lb33wm) ([raw file](https://github.com/gramineproject/gramine/blob/2064b02050e345f318b5bd8191df2b2034295461/LibOS/shim/src/sys/shim_socket.c#L306)):*
> ```C
>         if (addr->sa_family != AF_INET)
>             return -EAFNOSUPPORT;
>         if (addrlen != minimal_addrlen(addr->sa_family))
> ```

Why this change? It doesn't make sense to me, the previous code was fine.
___
*[LibOS/shim/src/sys/shim_socket.c, line 457 at r12](https://reviewable.io/reviews/gramineproject/gramine/74#-MlAe7cb4XBUI9327Kl0:-MlAe7cb4XBUI9327Kl1:b96yffv) ([raw file](https://github.com/gramineproject/gramine/blob/2064b02050e345f318b5bd8191df2b2034295461/LibOS/shim/src/sys/shim_socket.c#L457)):*
> ```C
> 
>     struct shim_sock_handle* sock = &hdl->info.sock;
>     if ((size_t)addrlen < minimal_addrlen(sock->domain)) {
> ```

What's the point of this? We have a check on `addrlen` in `AF_UNIX` case.
___
*[LibOS/shim/src/sys/shim_socket.c, line 723 at r12](https://reviewable.io/reviews/gramineproject/gramine/74#-MlAhj9x14qLIRgLPwCs:-MlAhj9y1Ab_Y0_gZ63O:bg09fn8) ([raw file](https://github.com/gramineproject/gramine/blob/2064b02050e345f318b5bd8191df2b2034295461/LibOS/shim/src/sys/shim_socket.c#L723)):*
> ```C
> 
>     struct shim_sock_handle* sock = &hdl->info.sock;
>     if ((size_t)addrlen < minimal_addrlen(sock->domain)) {
> ```

ditto (we already have a correct check in `AF_UNIX` case)
___
*[LibOS/shim/src/sys/shim_socket.c, line 991 at r12](https://reviewable.io/reviews/gramineproject/gramine/74#-MlAmfcxDabaos4ei70B:-MlAmfcyECSGv9RTWjkO:b-xelxjk) ([raw file](https://github.com/gramineproject/gramine/blob/2064b02050e345f318b5bd8191df2b2034295461/LibOS/shim/src/sys/shim_socket.c#L991)):*
> ```C
> 
>         if (addr) {
>             *addrlen = unix_copy_addr(addr, sock->addr.un.sun_path);
> ```

You need to verify whether `addr` has enough space, i.e. `*addrlen` could be smaller than required (now we only know its >= than minimal size).
___
*[LibOS/shim/src/sys/shim_socket.c, line 1463 at r12](https://reviewable.io/reviews/gramineproject/gramine/74#-MlAp4RZ3LgnNSW9SnkH:-MlAp4RZ3LgnNSW9SnkI:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/2064b02050e345f318b5bd8191df2b2034295461/LibOS/shim/src/sys/shim_socket.c#L1463)):*
> ```C
>         if (addr && !address_received) {
>             if (sock->domain == AF_UNIX) {
>                 *addrlen = unix_copy_addr(addr, sock->addr.un.sun_path);
> ```

ditto
___
*[LibOS/shim/src/sys/shim_socket.c, line 1707 at r12](https://reviewable.io/reviews/gramineproject/gramine/74#-MlAsh5c-4bkHpN-EBpP:-MlAsh5dCguaUlyHGgfQ:bazv8ab) ([raw file](https://github.com/gramineproject/gramine/blob/2064b02050e345f318b5bd8191df2b2034295461/LibOS/shim/src/sys/shim_socket.c#L1707)):*
> ```C
>     }
> 
>     if (*addrlen <= 0) {
> ```

Actually this is incorrect, `0` is valid.
___
*[LibOS/shim/src/sys/shim_socket.c, line 1718 at r12](https://reviewable.io/reviews/gramineproject/gramine/74#-MlAsmDm9BaYV2rgZZCM:-MlAsmDm9BaYV2rgZZCN:b-xm5bm2) ([raw file](https://github.com/gramineproject/gramine/blob/2064b02050e345f318b5bd8191df2b2034295461/LibOS/shim/src/sys/shim_socket.c#L1718)):*
> ```C
> 
>     struct shim_sock_handle* sock = &hdl->info.sock;
>     if ((size_t)*addrlen < minimal_addrlen(sock->domain)) {
> ```

This is incorrect, Linux accept all sizes  `>= 0`.
___
*[LibOS/shim/src/sys/shim_socket.c, line 1764 at r12](https://reviewable.io/reviews/gramineproject/gramine/74#-MlAtjPT-Rq8grE5Z8--:-MlAtjPT-Rq8grE5Z8-0:bo1tmoh) ([raw file](https://github.com/gramineproject/gramine/blob/2064b02050e345f318b5bd8191df2b2034295461/LibOS/shim/src/sys/shim_socket.c#L1764)):*
> ```C
> 
>     struct shim_sock_handle* sock = &hdl->info.sock;
>     if ((size_t)*addrlen < minimal_addrlen(sock->domain)) {
> ```

ditto (incorrect)
___
*[LibOS/shim/test/regression/unix.c, line 107 at r4](https://reviewable.io/reviews/gramineproject/gramine/74#-MkANoutDF3Qhi5F9FW2:-MlAuDaG1kHftDrpnGnk:biv4zp5) ([raw file](https://github.com/gramineproject/gramine/blob/e5d8faa90951baede85e4796560a59afef50679f/LibOS/shim/test/regression/unix.c#L107)):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

create_socket was closed in all cases whether accept call successed or failed. It was clsoed in `if` statement as well as after if. I removed one duplicate line by putting it before `if`
</blockquote></details>

You can fix hundreds of bugs in this test, as well as clear/optimize some code. I'm just curious why you've changed only this line.
___
*[LibOS/shim/test/regression/unix.c, line 121 at r4](https://reviewable.io/reviews/gramineproject/gramine/74#-MkATX7B-3SGyqGtEX3A:-MlAv50jASxa3_6v6t7H:b-xrajmg) ([raw file](http [...]

2021-10-04 17:26 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/74)* status: all files reviewed, 24 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @jkr0103)

___
*[LibOS/shim/src/sys/shim_socket.c, line 1717 at r4](https://reviewable.io/reviews/gramineproject/gramine/74#-MkALhw62X0NIe7jjdEE:-MlBHUZtCaFZsLLlBKSv:b-3un9mi) ([raw file](https://github.com/gramineproject/gramine/blob/e5d8faa90951baede85e4796560a59afef50679f/LibOS/shim/src/sys/shim_socket.c#L1717)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Unfortunately, we cannot require full `sizeof(struct sockaddr_un)`.
</blockquote></details>

@boryspoplawski You mean that this is too much of an oversimplification?
___
*[LibOS/shim/src/sys/shim_socket.c, line 54 at r12](https://reviewable.io/reviews/gramineproject/gramine/74#-MlAcam31JxEOjMV_riQ:-MlBIpik0xhmCtZjHEkP:bflsrqr) ([raw file](https://github.com/gramineproject/gramine/blob/2064b02050e345f318b5bd8191df2b2034295461/LibOS/shim/src/sys/shim_socket.c#L54)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This is invalid, Linux allows for smaller sizes for `AF_UNIX`.
</blockquote></details>

The idea was to fix it to some "close to normality" oversimplified version. But I guess this doesn't cut it, and you want a proper same-as-Linux fix...

I'm getting tired of this PR. Jinen hoped to fix one small bug, and it turned out that *almost everything* is wrong wrt to size calculations in `shim_socket.c` file. `minimal_addrlen()` is incorrectly named, `*addrlen` for some reason is checked against `0`, sometimes the code returns EFAULT and sometimes EINVAL, sometimes the code calls `minimal_addrlen()` and sometimes not, `unix_copy_addr()` doesn't take the actual size of the supplied buffer into account (and just copies the whole 108 chars), and all this code is barely readable.

What about we close this PR and ask one of the maintainers to re-write `shim_socket.c` completely from scratch? It's clearly impossible to just fix one thing in this code, everything cascades, and inconsistencies in the code only confuse novices.
___
*[LibOS/shim/src/sys/shim_socket.c, line 306 at r12](https://reviewable.io/reviews/gramineproject/gramine/74#-MlAVwuF5R8xzeJ6fqAH:-MlBFlN99QOe4aU3dGQ8:bml3lvo) ([raw file](https://github.com/gramineproject/gramine/blob/2064b02050e345f318b5bd8191df2b2034295461/LibOS/shim/src/sys/shim_socket.c#L306)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why this change? It doesn't make sense to me, the previous code was fine.
</blockquote></details>

@boryspoplawski Because there was an inconsistency with the code below (see my FYI comment below).
___
*[LibOS/shim/src/sys/shim_socket.c, line 314 at r12](https://reviewable.io/reviews/gramineproject/gramine/74#-MlBFuj69R8Aw-Fo5dfg:-MlBFuj69R8Aw-Fo5dfh:bk96s90) ([raw file](https://github.com/gramineproject/gramine/blob/2064b02050e345f318b5bd8191df2b2034295461/LibOS/shim/src/sys/shim_socket.c#L314)):*
> ```C
>         if (addr->sa_family != AF_INET && addr->sa_family != AF_INET6)
>             return -EAFNOSUPPORT;
>         if (addrlen != minimal_addrlen(addr->sa_family))
> ```

FYI: Here we have `minimal_addrlen()` for IPv6 address. That's why Jinen changed it above -- for consistency.
___
*[LibOS/shim/src/sys/shim_socket.c, line 457 at r12](https://reviewable.io/reviews/gramineproject/gramine/74#-MlAe7cb4XBUI9327Kl0:-MlBGGapAgv80NFgVZOx:bhpk9wv) ([raw file](https://github.com/gramineproject/gramine/blob/2064b02050e345f318b5bd8191df2b2034295461/LibOS/shim/src/sys/shim_socket.c#L457)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

What's the point of this? We have a check on `addrlen` in `AF_UNIX` case.
</blockquote></details>

Actually true, this is undeeded. We have a check below (see my FYI comment).
___
*[LibOS/shim/src/sys/shim_socket.c, line 472 at r12](https://reviewable.io/reviews/gramineproject/gramine/74#-MlBGJub7U6hheGEYt6l:-MlBGJub7U6hheGEYt6m:b-qcbmec) ([raw file](https://github.com/gramineproject/gramine/blob/2064b02050e345f318b5bd8191df2b2034295461/LibOS/shim/src/sys/shim_socket.c#L472)):*
> ```C
>     if (sock->domain == AF_UNIX) {
>         if (addrlen < offsetof(struct sockaddr_un, sun_path) + 1 ||
>                 addrlen > sizeof(struct sockaddr_un)) {
> ```

FYI: Here is the check for `addrlen`. So the added code above is indeed redundant.
___
*[LibOS/shim/src/sys/shim_socket.c, line 723 at r12](https://reviewable.io/reviews/gramineproject/gramine/74#-MlAhj9x14qLIRgLPwCs:-MlBGPuHD3oGM1Ee88IC:b-g8qdj0) ([raw file](https://github.com/gramineproject/gramine/blob/2064b02050e345f318b5bd8191df2b2034295461/LibOS/shim/src/sys/shim_socket.c#L723)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto (we already have a correct check in `AF_UNIX` case)
</blockquote></details>

Agreed, this check can be simply removed.
___
*[LibOS/shim/src/sys/shim_socket.c, line 759 at r12](https://reviewable.io/reviews/gramineproject/gramine/74#-MlBGRp79obzw_H4uJU-:-MlBGRp79obzw_H4uJU0:b-qcbmec) ([raw file](https://github.com/gramineproject/gramine/blob/2064b02050e345f318b5bd8191df2b2034295461/LibOS/shim/src/sys/shim_socket.c#L759)):*
> ```C
>     if (sock->domain == AF_UNIX) {
>         if (addrlen < offsetof(struct sockaddr_un, sun_path) + 1 ||
>                 addrlen > sizeof(struct sockaddr_un)) {
> ```

FYI: Here is the check for `addrlen`. So the added code above is indeed redundant.
___
*[LibOS/shim/src/sys/shim_socket.c, line 906 at r12](https://reviewable.io/reviews/gramineproject/gramine/74#-MlBGelv7_wyj215Rwjm:-MlBGelv7_wyj215Rwjn:bk0ekyn) ([raw file](https://github.com/gramineproject/gramine/blob/2064b02050e345f318b5bd8191df2b2034295461/LibOS/shim/src/sys/shim_socket.c#L906)):*
> ```C
>             return -EFAULT;
> 
>         if (*addrlen < 0 || (size_t)*addrlen < minimal_addrlen(sock->domain))
> ```

FYI: Borys, here we error out if `*addrlen` is smaller than the max size (108 chars in `sun_path`) of the UNIX domain socket.
___
*[LibOS/shim/src/sys/shim_socket.c, line 991 at r12](https://reviewable.io/reviews/gramineproject/gramine/74#-MlAmfcxDabaos4ei70B:-MlBGos524LYtUPidR91:bbvuxrl) ([raw file](https://github.com/gramineproject/gramine/blob/2064b02050e345f318b5bd8191df2b2034295461/LibOS/shim/src/sys/shim_socket.c#L991)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

You need to verify whether `addr` has enough space, i.e. `*addrlen` could be smaller than required (now we only know its >= than minimal size).
</blockquote></details>

Technically we don't need the check, because we already error out on `*addrlen < minimal_addrlen()` above, see my other comment.
___
*[LibOS/shim/src/sys/shim_socket.c, line 1322 at r12](https://reviewable.io/reviews/gramineproject/gramine/74#-MlBGyA98HZik8zy8Pvc:-MlBGyA98HZik8zy8Pvd:bk0ekyn) ([raw file](https://github.com/gramineproject/gramine/blob/2064b02050e345f318b5bd8191df2b2034295461/LibOS/shim/src/sys/shim_socket.c#L1322)):*
> ```C
> 
>     if (addr) {
>         if (*addrlen < 0 || (size_t)*addrlen < minimal_addrlen(sock->domain)) {
> ```

FYI: Borys, here we error out if `*addrlen` is smaller than the max size (108 chars in `sun_path`) of the UNIX domain socket.
___
*[LibOS/shim/src/sys/shim_socket.c, line 1463 at r12](https://reviewable.io/reviews/gramineproject/gramine/74#-MlAp4RZ3LgnNSW9SnkH:-MlBH3Em0vt5i2kKi9bF:b-lnu0wz) ([raw file](https://github.com/gramineproject/gramine/blob/2064b02050e345f318b5bd8191df2b2034295461/LibOS/shim/src/sys/shim_socket.c#L1463)):*
<details><summary><i>Previously, boryspoplawski ( [...]

2021-10-04 17:37 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/74)* status: all files reviewed, 24 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @jkr0103)

___
*[LibOS/shim/test/regression/unix.c, line 121 at r4](https://reviewable.io/reviews/gramineproject/gramine/74#-MkATX7B-3SGyqGtEX3A:-MlBNHBg-nIpI719eLun:bhm1ha6) ([raw file](https://github.com/gramineproject/gramine/blob/e5d8faa90951baede85e4796560a59afef50679f/LibOS/shim/test/regression/unix.c#L121)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@boryspoplawski You forgot the context here :) Please check r3 (e.g., choose `r3 - r12` on this file).

"Removed" was a wrong word from Jinen. He meant that he "reverted back to `u` because initially it was `/u` which was a bug in Gramine" (and Jinen at first didn't recognize that this is not how native Linux returns sun_path).

So Jinen didn't remove the test that didn't pass. Jinen reverted back his incorrect change, and kept the correct `u` (which is returned both on native Linux and under Gramine now -- previously Gramine returned `/u` because you know, 5-year-old code written by students).
</blockquote></details>

Oops, sorry, I meant Jitender.


<!-- Sent from Reviewable.io -->

2021-10-04 18:41 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/74)* status: all files reviewed, 24 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @jkr0103)

___
*[LibOS/shim/src/sys/shim_socket.c, line 1717 at r4](https://reviewable.io/reviews/gramineproject/gramine/74#-MkALhw62X0NIe7jjdEE:-MlBaQUyAh4myKUp8DyU:b-jwuld6) ([raw file](https://github.com/gramineproject/gramine/blob/e5d8faa90951baede85e4796560a59afef50679f/LibOS/shim/src/sys/shim_socket.c#L1717)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@boryspoplawski You mean that this is too much of an oversimplification?
</blockquote></details>

I mean that's `*addrlen == 10` is a valid parameter that we need to handle correctly.
___
*[LibOS/shim/src/sys/shim_socket.c, line 54 at r12](https://reviewable.io/reviews/gramineproject/gramine/74#-MlAcam31JxEOjMV_riQ:-MlBYvC6CaHiLRhuvBbZ:bbjo8a5) ([raw file](https://github.com/gramineproject/gramine/blob/2064b02050e345f318b5bd8191df2b2034295461/LibOS/shim/src/sys/shim_socket.c#L54)):*
> The idea was to fix it to some "close to normality" oversimplified version. But I guess this doesn't cut it, and you want a proper same-as-Linux fix...

I don't see much point in changing one incorrect version to another.

As for the rest of the comment: yes, this file is a mess, we will need to deal with the socket code.
___
*[LibOS/shim/src/sys/shim_socket.c, line 306 at r12](https://reviewable.io/reviews/gramineproject/gramine/74#-MlAVwuF5R8xzeJ6fqAH:-MlBZHkKD5i22EtO1KXX:b-smeaz1) ([raw file](https://github.com/gramineproject/gramine/blob/2064b02050e345f318b5bd8191df2b2034295461/LibOS/shim/src/sys/shim_socket.c#L306)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@boryspoplawski Because there was an inconsistency with the code below (see my FYI comment below).
</blockquote></details>

What inconsistency? This function literally checks for `AF_INET` 2 lines above...
___
*[LibOS/shim/src/sys/shim_socket.c, line 906 at r12](https://reviewable.io/reviews/gramineproject/gramine/74#-MlBGelv7_wyj215Rwjm:-MlB_QCO3SwavFTWsizF:b-mzo6h3) ([raw file](https://github.com/gramineproject/gramine/blob/2064b02050e345f318b5bd8191df2b2034295461/LibOS/shim/src/sys/shim_socket.c#L906)):*
> minimal_addrlen
> smaller than the max size

Makes total sense.
Yes, I've seen this check, and I assume that `minial_addrlen` works as expected, i.e. returns the smallest valid size, which is not 108.
___
*[LibOS/shim/src/sys/shim_socket.c, line 991 at r12](https://reviewable.io/reviews/gramineproject/gramine/74#-MlAmfcxDabaos4ei70B:-MlBaEu8DHUPSyl-ybvF:b-927cts) ([raw file](https://github.com/gramineproject/gramine/blob/2064b02050e345f318b5bd8191df2b2034295461/LibOS/shim/src/sys/shim_socket.c#L991)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Technically we don't need the check, because we already error out on `*addrlen < minimal_addrlen()` above, see my other comment.
</blockquote></details>

Technically we do, see my other comment.
___
*[LibOS/shim/src/sys/shim_socket.c, line 1463 at r12](https://reviewable.io/reviews/gramineproject/gramine/74#-MlAp4RZ3LgnNSW9SnkH:-MlBaJy7BsnUWGqQICsa:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/2064b02050e345f318b5bd8191df2b2034295461/LibOS/shim/src/sys/shim_socket.c#L1463)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto (technically already have the check)
</blockquote></details>

ditto
___
*[LibOS/shim/test/regression/unix.c, line 121 at r4](https://reviewable.io/reviews/gramineproject/gramine/74#-MkATX7B-3SGyqGtEX3A:-MlBanhc5-y5swp1KXnA:b-phnhru) ([raw file](https://github.com/gramineproject/gramine/blob/e5d8faa90951baede85e4796560a59afef50679f/LibOS/shim/test/regression/unix.c#L121)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Oops, sorry, I meant Jitender.
</blockquote></details>

I did not. He added 2 tests, both didn't pass, now he fixed one of them and removed the other (`getpeername`).


<!-- Sent from Reviewable.io -->

2021-10-04 18:51 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/74)* status: all files reviewed, 24 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @jkr0103)

___
*[LibOS/shim/src/sys/shim_socket.c, line 1717 at r4](https://reviewable.io/reviews/gramineproject/gramine/74#-MkALhw62X0NIe7jjdEE:-MlBd6k7DvCSNv56x_03:b-5b4wpr) ([raw file](https://github.com/gramineproject/gramine/blob/e5d8faa90951baede85e4796560a59afef50679f/LibOS/shim/src/sys/shim_socket.c#L1717)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I mean that's `*addrlen == 10` is a valid parameter that we need to handle correctly.
</blockquote></details>

Ok, so too much of an oversimplification. Ok, let's close this PR, rewrite `shim_socket.c` partially, and return back to UNIX domain sockets, which will be able to have variable-sized length (not just a hard constant of 108 chars).
___
*[LibOS/shim/src/sys/shim_socket.c, line 306 at r12](https://reviewable.io/reviews/gramineproject/gramine/74#-MlAVwuF5R8xzeJ6fqAH:-MlBc0Y0-QeY82MdjHC4:bipbgyr) ([raw file](https://github.com/gramineproject/gramine/blob/2064b02050e345f318b5bd8191df2b2034295461/LibOS/shim/src/sys/shim_socket.c#L306)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

What inconsistency? This function literally checks for `AF_INET` 2 lines above...
</blockquote></details>

I mean that the original code has this:
```
    if (domain == AF_INET) {
        ...
        if (addrlen != sizeof(struct sockaddr_in))
            return -EINVAL;
    }

// and 2 lines below

    if (domain == AF_INET6) {
        if (addrlen != minimal_addrlen(addr->sa_family))
            return -EINVAL;
    }
```

So it is natural to go ahead and fix one of these checks to another one. Jitender chose to use `minimal_addrlen()` in this case.
___
*[LibOS/shim/src/sys/shim_socket.c, line 906 at r12](https://reviewable.io/reviews/gramineproject/gramine/74#-MlBGelv7_wyj215Rwjm:-MlBcS8338_Mk1HDKDLj:bsdaxm1) ([raw file](https://github.com/gramineproject/gramine/blob/2064b02050e345f318b5bd8191df2b2034295461/LibOS/shim/src/sys/shim_socket.c#L906)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

> minimal_addrlen
> smaller than the max size

Makes total sense.
Yes, I've seen this check, and I assume that `minial_addrlen` works as expected, i.e. returns the smallest valid size, which is not 108.
</blockquote></details>

Well, it's not :) `minimal_addrlen()` is a bad name and bad function :) I thought of this function as `get_const_addrlen_based_on_socket_type()` -- for INET/INET6 it returns an only possible constant, and for UNIX it returns the max size (header + 108 chars).

I feel like I'm talking nonsense now... Let's just agree that all this must be re-written, and with meaningful names.


<!-- Sent from Reviewable.io -->

2021-10-04 19:05 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/74)* status: all files reviewed, 24 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @jkr0103)

___
*[LibOS/shim/src/sys/shim_socket.c, line 306 at r12](https://reviewable.io/reviews/gramineproject/gramine/74#-MlAVwuF5R8xzeJ6fqAH:-MlBfeOD059NIPeoUBj0:blli8qk) ([raw file](https://github.com/gramineproject/gramine/blob/2064b02050e345f318b5bd8191df2b2034295461/LibOS/shim/src/sys/shim_socket.c#L306)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I mean that the original code has this:
```
    if (domain == AF_INET) {
        ...
        if (addrlen != sizeof(struct sockaddr_in))
            return -EINVAL;
    }

// and 2 lines below

    if (domain == AF_INET6) {
        if (addrlen != minimal_addrlen(addr->sa_family))
            return -EINVAL;
    }
```

So it is natural to go ahead and fix one of these checks to another one. Jitender chose to use `minimal_addrlen()` in this case.
</blockquote></details>

No, you couldn't pick any of those, there is a difference: first checks for `if (addr->sa_family != AF_INET)` which means there is only 1 possibility, the other checks for two: `if (addr->sa_family != AF_INET && addr->sa_family != AF_INET6)`.
But I now see what you meant by "inconsistency".


<!-- Sent from Reviewable.io -->

2021-10-04 19:10 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/74)* status: all files reviewed, 24 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @jkr0103)

___
*[LibOS/shim/src/sys/shim_socket.c, line 306 at r12](https://reviewable.io/reviews/gramineproject/gramine/74#-MlAVwuF5R8xzeJ6fqAH:-MlBhPqV6j3Rg_EGG1x9:bfslza8) ([raw file](https://github.com/gramineproject/gramine/blob/2064b02050e345f318b5bd8191df2b2034295461/LibOS/shim/src/sys/shim_socket.c#L306)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

No, you couldn't pick any of those, there is a difference: first checks for `if (addr->sa_family != AF_INET)` which means there is only 1 possibility, the other checks for two: `if (addr->sa_family != AF_INET && addr->sa_family != AF_INET6)`.
But I now see what you meant by "inconsistency".
</blockquote></details>

Oh, I didn't even notice that. You're right. I'm giving up on understanding this code, it's very hard to read (at least for me). I constantly overlook these subtle differences in this file.


<!-- Sent from Reviewable.io -->

2021-10-05 04:20 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/74)* status: all files reviewed, 24 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @jkr0103)

___
*[LibOS/shim/test/regression/unix.c, line 107 at r4](https://reviewable.io/reviews/gramineproject/gramine/74#-MkANoutDF3Qhi5F9FW2:-MlDdlKg0lUy0Nz3akTl:bqr5qnb) ([raw file](https://github.com/gramineproject/gramine/blob/e5d8faa90951baede85e4796560a59afef50679f/LibOS/shim/test/regression/unix.c#L107)):*
> (not just a hard constant of 108 chars).
I did make some changes like removed unnecessary fork calls etc.. which ever were obvious to me.
___
*[LibOS/shim/test/regression/unix.c, line 121 at r4](https://reviewable.io/reviews/gramineproject/gramine/74#-MkATX7B-3SGyqGtEX3A:-MlDe9uI-bEGOlPyeWth:b-k4u63i) ([raw file](https://github.com/gramineproject/gramine/blob/e5d8faa90951baede85e4796560a59afef50679f/LibOS/shim/test/regression/unix.c#L121)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I did not. He added 2 tests, both didn't pass, now he fixed one of them and removed the other (`getpeername`).
</blockquote></details>

Yes I added two tests and still both tests exists but one is moved to client code. `getpeername` returns empty string on server oriented sockets with AF_UNIX domain type sockets.  POSIX docs do not really specify what the proper behavior of `getpeername` and `getsockname` with AF_UNIX. This link explains how these functions behave with AF_UNIX socket in LINUX.

https://comp.unix.programmer.narkive.com/4XZorZxy/get-peer-sock-name-on-af-unix-sockets explains below: 

If the AF_UNIX socket is a client oriented socket getpeername(2) does
fill in sun_path and getsockname(2) does not (whereas the reverse is
true of a server oriented socket).

But because the POSIX docs do not really specify what the proper behavior
is I suspect results on platforms other than Linux may not be consistent
with my observations.


<!-- Sent from Reviewable.io -->

2021-10-05 06:57 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/74)* status: all files reviewed, 24 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @jkr0103)

___
*[LibOS/shim/test/regression/unix.c, line 121 at r4](https://reviewable.io/reviews/gramineproject/gramine/74#-MkATX7B-3SGyqGtEX3A:-MlEEJEH0pl1NjcAcS9-:b4meo7t) ([raw file](https://github.com/gramineproject/gramine/blob/e5d8faa90951baede85e4796560a59afef50679f/LibOS/shim/test/regression/unix.c#L121)):*
> I did not. He added 2 tests, both didn't pass, now he fixed one of them and removed the other (getpeername).

That's incorrect, see Jitender's reply and my comment below.
___
*[LibOS/shim/test/regression/unix.c, line 167 at r12](https://reviewable.io/reviews/gramineproject/gramine/74#-MlEDmCN6BHLq7KyH-h7:-MlEDmCN6BHLq7KyH-h8:bkgonr2) ([raw file](https://github.com/gramineproject/gramine/blob/2064b02050e345f318b5bd8191df2b2034295461/LibOS/shim/test/regression/unix.c#L167)):*
> ```C
> 
>     addrlen = sizeof(peer_addr);
>     int ret = getpeername(create_socket, (struct sockaddr*)&peer_addr, &addrlen);
> ```

FYI: @boryspoplawski `getpeername()` was moved here, to the client code. Which makes sense because the client does `connect()`. From the NOTES of `man 2 getpeername`:
```
       ... The caller of  con‐
       nect(2)  can  use  getpeername()  to obtain the peer address that it earlier set for the socket.  However, the peer
       socket is unaware of this information, and calling getpeername() on the peer socket will return no useful  informa‐
       tion  (unless  a  connect(2)  call  was  also executed on the peer).
```


<!-- Sent from Reviewable.io -->

2021-10-05 13:00 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/74)* status: all files reviewed, 24 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @jkr0103)

___
*[LibOS/shim/test/regression/unix.c, line 121 at r4](https://reviewable.io/reviews/gramineproject/gramine/74#-MkATX7B-3SGyqGtEX3A:-MlFWw4d-_hhzx6BcexR:b9hv0oq) ([raw file](https://github.com/gramineproject/gramine/blob/e5d8faa90951baede85e4796560a59afef50679f/LibOS/shim/test/regression/unix.c#L121)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> I did not. He added 2 tests, both didn't pass, now he fixed one of them and removed the other (getpeername).

That's incorrect, see Jitender's reply and my comment below.
</blockquote></details>

1. We are not implementing POSIX compliant OS. We are emulating Linux.
2. Adding `getpeername` to client code is a **new** test case. We also want to run it on connected server socked, not-connected one and probably a normal file fd. We had one of these cases and it was removed.
___
*[LibOS/shim/test/regression/unix.c, line 167 at r12](https://reviewable.io/reviews/gramineproject/gramine/74#-MlEDmCN6BHLq7KyH-h7:-MlFXVB464d1UDR4tv5p:bx4kibn) ([raw file](https://github.com/gramineproject/gramine/blob/2064b02050e345f318b5bd8191df2b2034295461/LibOS/shim/test/regression/unix.c#L167)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

FYI: @boryspoplawski `getpeername()` was moved here, to the client code. Which makes sense because the client does `connect()`. From the NOTES of `man 2 getpeername`:
```
       ... The caller of  con‐
       nect(2)  can  use  getpeername()  to obtain the peer address that it earlier set for the socket.  However, the peer
       socket is unaware of this information, and calling getpeername() on the peer socket will return no useful  informa‐
       tion  (unless  a  connect(2)  call  was  also executed on the peer).
```
</blockquote></details>

Of course it makes sense to add it here, but the old one should stay as well.


<!-- Sent from Reviewable.io -->

2022-05-11 12:15 UTC, mkow commented
No activity for half a year, so I'm closing it. The networking code is being rewritten right now anyways.

2022-05-11 12:15 UTC, closed without merging