[LibOS] Add peak memory usage support in procfs
gramineproject/gramine pull request #742
Opened 2022-07-11 14:08 UTC by kailun-qin

Resolves https://github.com/gramineproject/gramine/issues/614. Use the VMA subsystem instead of adding a PAL API.

An application may want to adjust itself based on the peak memory usage in some scenarios. This patch adds VmPeak stats into the pseudo-file `/proc/<pid>/status` to support the usage.

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/742)

2022-07-11 16:09 UTC, boryspoplawski requested changes
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/742)* status: all files reviewed, 17 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @kailun-qin)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/742#-N6hq_i56PC1Z3QjfLox):*

___
*[`-- commits` line 6 at r1](https://reviewable.io/reviews/gramineproject/gramine/742#-N6hqcwy98qPGSJGvFrQ):*




_Suggestion:_
```
"/proc/<pid>/status"
```
___
*[`libos/include/libos_vma.h` line 135 at r1](https://reviewable.io/reviews/gramineproject/gramine/742#-N6i0Lfq38ouHf0d6xQZ:-N6i0Lfq38ouHf0d6xQ_:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/888e706e8abbf04183c86e48de2b6b4ffe499c71/libos/include/libos_vma.h#L135)):*
> ```objc
> 
> /* Returns the peak amount of memory usage */
> size_t peak_memory_usage(void);
> ```





_Suggestion:_
```objc
get_peak_memory_usage
```
___
*[`libos/src/bookkeep/libos_vma.c` line 28 at r1](https://reviewable.io/reviews/gramineproject/gramine/742#-N6htKTp3-tCqb7jdlW2:-N6htKTp3-tCqb7jdlW3:b-f4ftrc) ([raw file](https://github.com/gramineproject/gramine/blob/888e706e8abbf04183c86e48de2b6b4ffe499c71/libos/src/bookkeep/libos_vma.c#L28)):*
> ```C
> #include "spinlock.h"
> 
> struct atomic_int g_allocated_pages;
> ```

This variable is always protected by `vma_tree_lock`, which makes sense, since it effectively tracks the sum of lengths of elements in `vma_tree`. Thanks to that it does not need to be atomic at all.
___
*[`libos/src/bookkeep/libos_vma.c` line 28 at r1](https://reviewable.io/reviews/gramineproject/gramine/742#-N6hwODV1ElXkgcqT7u3:-N6hwODV1ElXkgcqT7u4:b-3l1byr) ([raw file](https://github.com/gramineproject/gramine/blob/888e706e8abbf04183c86e48de2b6b4ffe499c71/libos/src/bookkeep/libos_vma.c#L28)):*
> ```C
> #include "spinlock.h"
> 
> struct atomic_int g_allocated_pages;
> ```

Why do you track pages instead of total memory? There would be no need for these `ALLOC_ALIGNMENT` multiplication and division.
___
*[`libos/src/bookkeep/libos_vma.c` line 29 at r1](https://reviewable.io/reviews/gramineproject/gramine/742#-N6hs7Hu2jRgWlIoK0ig:-N6hs7Hu2jRgWlIoK0ih:b-see3km) ([raw file](https://github.com/gramineproject/gramine/blob/888e706e8abbf04183c86e48de2b6b4ffe499c71/libos/src/bookkeep/libos_vma.c#L29)):*
> ```C
> 
> struct atomic_int g_allocated_pages;
> struct atomic_int g_peak_allocated_pages;
> ```

Please don't use `struct atomic_int`, we want to get rid of them.
For now we use compiler builtins for atomic (e.g. `__atomic_load_n`).
Update: I see you used them anyway.
___
*[`libos/src/bookkeep/libos_vma.c` line 58 at r1](https://reviewable.io/reviews/gramineproject/gramine/742#-N6hx6i7Ey1BGhWB56sh:-N6hx3J30oocsJezhJEc:bjyvfyy) ([raw file](https://github.com/gramineproject/gramine/blob/888e706e8abbf04183c86e48de2b6b4ffe499c71/libos/src/bookkeep/libos_vma.c#L58)):*
> ```C
> };
> 
> static inline void allocated_record_add(size_t length) {
> ```

Please remove `inline`.
Also I would change the name to `total_memory_size_add`, assuming we start tracking memory instead of pages.



_Suggestion:_
```C
static void allocated_record_add(size_t length) {
```
___
*[`libos/src/bookkeep/libos_vma.c` line 68 at r1](https://reviewable.io/reviews/gramineproject/gramine/742#-N6hvnjg50Mmz96hQ0vM:-N6hvnjg50Mmz96hQ0vN:baksal0) ([raw file](https://github.com/gramineproject/gramine/blob/888e706e8abbf04183c86e48de2b6b4ffe499c71/libos/src/bookkeep/libos_vma.c#L68)):*
> ```C
>         assert(allocated_pages >= 0);
> 
>         peak_allocated_pages = __atomic_load_n(&g_peak_allocated_pages.counter, __ATOMIC_SEQ_CST);
> ```

And you can also move this out of the loop, `peek_allocated_pages` is updated in cmp&echg



_Suggestion:_
```C
RELAXED
```
___
*[`libos/src/bookkeep/libos_vma.c` line 75 at r1](https://reviewable.io/reviews/gramineproject/gramine/742#-N6hvfI2Brcrj3ENRHVr:-N6hvfI2Brcrj3ENRHVs:b45h) ([raw file](https://github.com/gramineproject/gramine/blob/888e706e8abbf04183c86e48de2b6b4ffe499c71/libos/src/bookkeep/libos_vma.c#L75)):*
> ```C
>         }
>     } while (!__atomic_compare_exchange_n(&g_peak_allocated_pages.counter, &peak_allocated_pages,
>                                           allocated_pages, /*weak=*/false,
> ```





_Suggestion:_
```C
true,
```
___
*[`libos/src/bookkeep/libos_vma.c` line 76 at r1](https://reviewable.io/reviews/gramineproject/gramine/742#-N6huY888olONEF3rUGH:-N6huY888olONEF3rUGI:bpyolki) ([raw file](https://github.com/gramineproject/gramine/blob/888e706e8abbf04183c86e48de2b6b4ffe499c71/libos/src/bookkeep/libos_vma.c#L76)):*
> ```C
>     } while (!__atomic_compare_exchange_n(&g_peak_allocated_pages.counter, &peak_allocated_pages,
>                                           allocated_pages, /*weak=*/false,
>                                           __ATOMIC_SEQ_CST, __ATOMIC_RELAXED));
> ```

I think even `RELAXED` would work fine, but if for some reason you want synchronization then:



_Suggestion:_
```C
__ATOMIC_RELEASE
```
___
*[`libos/src/bookkeep/libos_vma.c` line 79 at r1](https://reviewable.io/reviews/gramineproject/gramine/742#-N6hxIhX-dEbJk9s7xiR:-N6hxIhX-dEbJk9s7xiS:b-9dpsl3) ([raw file](https://github.com/gramineproject/gramine/blob/888e706e8abbf04183c86e48de2b6b4ffe499c71/libos/src/bookkeep/libos_vma.c#L79)):*
> ```C
> }
> 
> static inline void allocated_record_sub(size_t length) {
> ```

ditto (`inline` and name)
___
*[`libos/src/bookkeep/libos_vma.c` line 273 at r1](https://reviewable.io/reviews/gramineproject/gramine/742#-N6hxU15Azon6FZ1Ek3J:-N6hxU15Azon6FZ1Ek3K:b-rpnulc) ([raw file](https://github.com/gramineproject/gramine/blob/888e706e8abbf04183c86e48de2b6b4ffe499c71/libos/src/bookkeep/libos_vma.c#L273)):*
> ```C
>             avl_tree_insert(&vma_tree, &new_vma->tree_node);
> 
>             allocated_record_add(new_vma->end - new_vma->begin);
> ```

I would remove the empty line between `avl_tree_*` and `allocated_record_*` (ditto for the whole PR), they logically belong together.
___
*[`libos/src/bookkeep/libos_vma.c` line 756 at r1](https://reviewable.io/reviews/gramineproject/gramine/742#-N6hxtVM4PvfpsHB35Sm:-N6hxtVM4PvfpsHB35Sn:b-qf37i8) ([raw file](https://github.com/gramineproject/gramine/blob/888e706e8abbf04183c86e48de2b6b4ffe499c71/libos/src/bookkeep/libos_vma.c#L756)):*
> ```C
>     spinlock_unlock(&vma_tree_lock);
> 
>     allocated_record_sub(vma->end - vma->begin);
> ```

If you change `g_allocated_pages` to be non-atomic, this will need to be moved above `spinlock_unlock`
___
*[`libos/src/bookkeep/libos_vma.c` line 1507 at r1](https://reviewable.io/reviews/gramineproject/gramine/742#-N6hzKZyBVD4YfVsE8MZ:-N6hzKZyBVD4YfVsE8M_:b7pirsq) ([raw file](https://github.com/gramineproject/gramine/blob/888e706e8abbf04183c86e48de2b6b4ffe499c71/libos/src/bookkeep/libos_vma.c#L1507)):*
> ```C
> 
> size_t peak_memory_usage(void) {
>     return __atomic_load_n(&g_peak_allocated_pages.counter, __ATOMIC_SEQ_CST) * ALLOC_ALIGNMENT;
> ```

ditto (I think `RELAXED` would work here, but if you want synchronization then)



_Suggestion:_
```C
ACQUIRE
```
___
*[`libos/src/fs/proc/thread.c` line 332 at r1](https://reviewable.io/reviews/gramineproject/gramine/742#-N6i-joL7gwehGgTYkLe:-N6i-joL7gwehGgTYkLf:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/888e706e8abbf04183c86e48de2b6b4ffe499c71/libos/src/fs/proc/thread.c#L332)):*
> ```C
> 
>     /*
>      * Enumerate minimal set of `/proc/[pid]/status`. Only `VmPeak` is supported currently.
> ```





_Suggestion:_
```C
Minimal set of attributes from `/proc/[pid]/status`.
```
___
*[`libos/src/fs/proc/thread.c` line 339 at r1](https://reviewable.io/reviews/gramineproject/gramine/742#-N6i-pw7Bvt14M0YMfWA:-N6i-pw7Bvt14M0YMfWB:b-74dw7a) ([raw file](https://github.com/gramineproject/gramine/blob/888e706e8abbf04183c86e48de2b6b4ffe499c71/libos/src/fs [...]

2022-07-11 16:13 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/742)* status: all files reviewed, 17 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski and @kailun-qin)

___
*[`libos/src/bookkeep/libos_vma.c` line 29 at r1](https://reviewable.io/reviews/gramineproject/gramine/742#-N6hs7Hu2jRgWlIoK0ig:-N6i1DAbEPj8vAkyDFPB:b80qd3f) ([raw file](https://github.com/gramineproject/gramine/blob/888e706e8abbf04183c86e48de2b6b4ffe499c71/libos/src/bookkeep/libos_vma.c#L29)):*
> we want to get rid of them

I think we haven't made the decision yet. I guess time to finally find some time to take a look at https://github.com/gramineproject/gramine/pull/277...


<!-- Sent from Reviewable.io -->

2022-07-11 16:16 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/742)* status: all files reviewed, 17 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @kailun-qin and @mkow)

___
*[`libos/src/bookkeep/libos_vma.c` line 29 at r1](https://reviewable.io/reviews/gramineproject/gramine/742#-N6hs7Hu2jRgWlIoK0ig:-N6i1y274yzxk7Jw2FFC:bnmd4c4) ([raw file](https://github.com/gramineproject/gramine/blob/888e706e8abbf04183c86e48de2b6b4ffe499c71/libos/src/bookkeep/libos_vma.c#L29)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> we want to get rid of them

I think we haven't made the decision yet. I guess time to finally find some time to take a look at https://github.com/gramineproject/gramine/pull/277...
</blockquote></details>

That's a different topic. We want get rid of `struct atomic_int`. The linked issue is about using C11 atomics vs compiler builtins.


<!-- Sent from Reviewable.io -->

2022-07-11 16:34 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/742)* status: all files reviewed, 17 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @kailun-qin and @mkow)

___
*[`libos/src/bookkeep/libos_vma.c` line 29 at r1](https://reviewable.io/reviews/gramineproject/gramine/742#-N6hs7Hu2jRgWlIoK0ig:-N6i6Bw515Um6NHoS716:bvap1sa) ([raw file](https://github.com/gramineproject/gramine/blob/888e706e8abbf04183c86e48de2b6b4ffe499c71/libos/src/bookkeep/libos_vma.c#L29)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I'll submit a PR removing them now.
</blockquote></details>

Done in https://github.com/gramineproject/gramine/pull/744


<!-- Sent from Reviewable.io -->

2022-07-11 18:15 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/742)* status: all files reviewed, 17 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski, @kailun-qin, and @mkow)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/742#-N6hq_i56PC1Z3QjfLox):*
Done.
___
*[`-- commits` line 6 at r1](https://reviewable.io/reviews/gramineproject/gramine/742#-N6hqcwy98qPGSJGvFrQ):*
Done.
___
*[`libos/include/libos_vma.h` line 135 at r1](https://reviewable.io/reviews/gramineproject/gramine/742#-N6i0Lfq38ouHf0d6xQZ:-N6i7vY86ElAuaY6kcAM:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/888e706e8abbf04183c86e48de2b6b4ffe499c71/libos/include/libos_vma.h#L135)):*
> ```objc
> 
> /* Returns the peak amount of memory usage */
> size_t peak_memory_usage(void);
> ```

Done.
___
*[`libos/src/bookkeep/libos_vma.c` line 28 at r1](https://reviewable.io/reviews/gramineproject/gramine/742#-N6hwODV1ElXkgcqT7u3:-N6i8AQFBkhgqLoVVxAU:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/888e706e8abbf04183c86e48de2b6b4ffe499c71/libos/src/bookkeep/libos_vma.c#L28)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why do you track pages instead of total memory? There would be no need for these `ALLOC_ALIGNMENT` multiplication and division.
</blockquote></details>

Done.
___
*[`libos/src/bookkeep/libos_vma.c` line 28 at r1](https://reviewable.io/reviews/gramineproject/gramine/742#-N6htKTp3-tCqb7jdlW2:-N6i8Axc0wyHX1BLrahy:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/888e706e8abbf04183c86e48de2b6b4ffe499c71/libos/src/bookkeep/libos_vma.c#L28)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This variable is always protected by `vma_tree_lock`, which makes sense, since it effectively tracks the sum of lengths of elements in `vma_tree`. Thanks to that it does not need to be atomic at all.
</blockquote></details>

Done.
___
*[`libos/src/bookkeep/libos_vma.c` line 29 at r1](https://reviewable.io/reviews/gramineproject/gramine/742#-N6hs7Hu2jRgWlIoK0ig:-N6i8J1O1ceuul4WvyXW:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/888e706e8abbf04183c86e48de2b6b4ffe499c71/libos/src/bookkeep/libos_vma.c#L29)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Done in https://github.com/gramineproject/gramine/pull/744
</blockquote></details>

Done.
___
*[`libos/src/bookkeep/libos_vma.c` line 58 at r1](https://reviewable.io/reviews/gramineproject/gramine/742#-N6hx6i7Ey1BGhWB56sh:-N6i8ZrG6B9dRbwWQzpT:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/888e706e8abbf04183c86e48de2b6b4ffe499c71/libos/src/bookkeep/libos_vma.c#L58)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please remove `inline`.
Also I would change the name to `total_memory_size_add`, assuming we start tracking memory instead of pages.
</blockquote></details>

Done.
___
*[`libos/src/bookkeep/libos_vma.c` line 68 at r1](https://reviewable.io/reviews/gramineproject/gramine/742#-N6hvnjg50Mmz96hQ0vM:-N6i8ca-DB1OHeyxp31R:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/888e706e8abbf04183c86e48de2b6b4ffe499c71/libos/src/bookkeep/libos_vma.c#L68)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

And you can also move this out of the loop, `peek_allocated_pages` is updated in cmp&echg
</blockquote></details>

Done.
___
*[`libos/src/bookkeep/libos_vma.c` line 75 at r1](https://reviewable.io/reviews/gramineproject/gramine/742#-N6hvfI2Brcrj3ENRHVr:-N6i8s1v8s6BOIBiCIu0:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/888e706e8abbf04183c86e48de2b6b4ffe499c71/libos/src/bookkeep/libos_vma.c#L75)):*
> ```C
>         }
>     } while (!__atomic_compare_exchange_n(&g_peak_allocated_pages.counter, &peak_allocated_pages,
>                                           allocated_pages, /*weak=*/false,
> ```

Done.
___
*[`libos/src/bookkeep/libos_vma.c` line 76 at r1](https://reviewable.io/reviews/gramineproject/gramine/742#-N6huY888olONEF3rUGH:-N6i8riEAsxK2eRPJfS3:b-gwbgtg) ([raw file](https://github.com/gramineproject/gramine/blob/888e706e8abbf04183c86e48de2b6b4ffe499c71/libos/src/bookkeep/libos_vma.c#L76)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I think even `RELAXED` would work fine, but if for some reason you want synchronization then:
</blockquote></details>

Changed all to `RELAXED`, done.
___
*[`libos/src/bookkeep/libos_vma.c` line 79 at r1](https://reviewable.io/reviews/gramineproject/gramine/742#-N6hxIhX-dEbJk9s7xiR:-N6i98-vC89XLvuuUywc:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/888e706e8abbf04183c86e48de2b6b4ffe499c71/libos/src/bookkeep/libos_vma.c#L79)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto (`inline` and name)
</blockquote></details>

Done.
___
*[`libos/src/bookkeep/libos_vma.c` line 273 at r1](https://reviewable.io/reviews/gramineproject/gramine/742#-N6hxU15Azon6FZ1Ek3J:-N6i99La6R3_yejE9b5k:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/888e706e8abbf04183c86e48de2b6b4ffe499c71/libos/src/bookkeep/libos_vma.c#L273)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I would remove the empty line between `avl_tree_*` and `allocated_record_*` (ditto for the whole PR), they logically belong together.
</blockquote></details>

Done.
___
*[`libos/src/fs/proc/thread.c` line 332 at r1](https://reviewable.io/reviews/gramineproject/gramine/742#-N6i-joL7gwehGgTYkLe:-N6iFD_JBsi7uiXJrlrs:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/888e706e8abbf04183c86e48de2b6b4ffe499c71/libos/src/fs/proc/thread.c#L332)):*
> ```C
> 
>     /*
>      * Enumerate minimal set of `/proc/[pid]/status`. Only `VmPeak` is supported currently.
> ```

Done.
___
*[`libos/src/fs/proc/thread.c` line 339 at r1](https://reviewable.io/reviews/gramineproject/gramine/742#-N6i-pw7Bvt14M0YMfWA:-N6iFQUhCiDpKjXgPFoH:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/888e706e8abbf04183c86e48de2b6b4ffe499c71/libos/src/fs/proc/thread.c#L339)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why this rather arbitrary amount of spaces after `:`? Please use `\t` as the kernel does instead.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-12 08:26 UTC, dimakuv requested changes
> Reviewed 3 of 6 files at r1, 3 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/742)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @kailun-qin, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/742#-N6lUf3X3m5ElsVd8yRh:-N6lUf3X3m5ElsVd8yRi:b-8q57xi) (no related file):*
Looks good! Could I ask you to manually verify (if not already) that this change indeed works as expected, by writing a small program that e.g. allocates 64KB chunks of memory multiple times, and after each allocation it shows peak memory; then deallocates all these chunks, and after each deallocation again shows peak memory. Of course, during dellocations, peak memory value should not change.

I just want to be sure that it was tested at least once, at least manually. Ideally, we chould add this test to the list of LibOS regression tests, but I don't insist.

___
___
*[`libos/src/bookkeep/libos_vma.c` line 29 at r3](https://reviewable.io/reviews/gramineproject/gramine/742#-N6lT1KX4yVErkp5teH6:-N6lT1KX4yVErkp5teH7:bagrmc2) ([raw file](https://github.com/gramineproject/gramine/blob/de9f27759942db4dd90e6ae85e354b12cf3d79f3/libos/src/bookkeep/libos_vma.c#L29)):*
> ```C
> 
> size_t g_total_memory_size;
> size_t g_peak_total_memory_size;
> ```

Could you add a comment that `g_total_memory_size` must be protected by the `vma_tree_lock`, and `g_peak_total_memory_size` must use atomics?
___
*[`libos/src/bookkeep/libos_vma.c` line 106 at r3](https://reviewable.io/reviews/gramineproject/gramine/742#-N6lRfag6j2m3cRmcn9h:-N6lRfag6j2m3cRmcn9i:btldtm9) ([raw file](https://github.com/gramineproject/gramine/blob/de9f27759942db4dd90e6ae85e354b12cf3d79f3/libos/src/bookkeep/libos_vma.c#L106)):*
> ```C
>     assert(spinlock_is_locked(&vma_tree_lock));
> 
>     g_total_memory_size += length;
> ```

Don't we want to add `assert(g_total_memory_size <= g_aslr_addr_top)` after this line? Just to make sure we loudly fail if in the future we'll modify this VMA code and introduce a bug.

Also summon @boryspoplawski here.
___
*[`libos/src/bookkeep/libos_vma.c` line 120 at r3](https://reviewable.io/reviews/gramineproject/gramine/742#-N6lRQCgEDm1TOf1qFLj:-N6lRQCgEDm1TOf1qFLk:bytxbyp) ([raw file](https://github.com/gramineproject/gramine/blob/de9f27759942db4dd90e6ae85e354b12cf3d79f3/libos/src/bookkeep/libos_vma.c#L120)):*
> ```C
> static void total_memory_size_sub(size_t length) {
>     assert(spinlock_is_locked(&vma_tree_lock));
>     g_total_memory_size -= length;
> ```

Don't we want to add `assert(g_total_memory_size >= length)` before this line? Just to make sure we loudly fail if in the future we'll modify this VMA code and introduce a bug.


<!-- Sent from Reviewable.io -->

2022-07-12 09:55 UTC, boryspoplawski requested changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/742)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @kailun-qin, and @mkow)

___
*[`libos/src/bookkeep/libos_vma.c` line 29 at r3](https://reviewable.io/reviews/gramineproject/gramine/742#-N6lT1KX4yVErkp5teH6:-N6lorI50I5b_etWHKMT:b32v57) ([raw file](https://github.com/gramineproject/gramine/blob/de9f27759942db4dd90e6ae85e354b12cf3d79f3/libos/src/bookkeep/libos_vma.c#L29)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you add a comment that `g_total_memory_size` must be protected by the `vma_tree_lock`, and `g_peak_total_memory_size` must use atomics?
</blockquote></details>

+1
___
*[`libos/src/bookkeep/libos_vma.c` line 106 at r3](https://reviewable.io/reviews/gramineproject/gramine/742#-N6lRfag6j2m3cRmcn9h:-N6lpKEvADbVl1LLbjA6:b-7ptqrp) ([raw file](https://github.com/gramineproject/gramine/blob/de9f27759942db4dd90e6ae85e354b12cf3d79f3/libos/src/bookkeep/libos_vma.c#L106)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Don't we want to add `assert(g_total_memory_size <= g_aslr_addr_top)` after this line? Just to make sure we loudly fail if in the future we'll modify this VMA code and introduce a bug.

Also summon @boryspoplawski here.
</blockquote></details>

But that's not the case, we can allocate memory over `g_aslr_addr_top`.
___
*[`libos/src/bookkeep/libos_vma.c` line 120 at r3](https://reviewable.io/reviews/gramineproject/gramine/742#-N6lRQCgEDm1TOf1qFLj:-N6lpRdc0aoZgtK5k4fO:be144r3) ([raw file](https://github.com/gramineproject/gramine/blob/de9f27759942db4dd90e6ae85e354b12cf3d79f3/libos/src/bookkeep/libos_vma.c#L120)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Don't we want to add `assert(g_total_memory_size >= length)` before this line? Just to make sure we loudly fail if in the future we'll modify this VMA code and introduce a bug.
</blockquote></details>

This we could do.


<!-- Sent from Reviewable.io -->

2022-07-12 11:43 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/742)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @kailun-qin, and @mkow)

___
*[`libos/src/bookkeep/libos_vma.c` line 106 at r3](https://reviewable.io/reviews/gramineproject/gramine/742#-N6lRfag6j2m3cRmcn9h:-N6mCvzp0nHNeHqHt4Uh:b-qbx0ia) ([raw file](https://github.com/gramineproject/gramine/blob/de9f27759942db4dd90e6ae85e354b12cf3d79f3/libos/src/bookkeep/libos_vma.c#L106)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

But that's not the case, we can allocate memory over `g_aslr_addr_top`.
</blockquote></details>

Well, can we check against some other constant? In particular, does `g_pal_public_state->user_address_end` fit here?


<!-- Sent from Reviewable.io -->

2022-07-12 11:57 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/742)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @kailun-qin, and @mkow)

___
*[`libos/src/bookkeep/libos_vma.c` line 106 at r3](https://reviewable.io/reviews/gramineproject/gramine/742#-N6lRfag6j2m3cRmcn9h:-N6mFhcv1fgTfaHzg6fl:b-l6ogr1) ([raw file](https://github.com/gramineproject/gramine/blob/de9f27759942db4dd90e6ae85e354b12cf3d79f3/libos/src/bookkeep/libos_vma.c#L106)):*
> Well, can we check against some other constant?

Nothing comes to my mind.

>  In particular, does g_pal_public_state->user_address_end fit here?

No, we also have some memory from PAL bookkeeped (and I plan to extend that in the future), which can lie after that address, so in theory we could have more memory mapped that it.


<!-- Sent from Reviewable.io -->

2022-07-12 13:04 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/742)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @kailun-qin, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/742#-N6lUf3X3m5ElsVd8yRh:-N6mOSQuC1TXaCN43wkM:be6pnbp) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Looks good! Could I ask you to manually verify (if not already) that this change indeed works as expected, by writing a small program that e.g. allocates 64KB chunks of memory multiple times, and after each allocation it shows peak memory; then deallocates all these chunks, and after each deallocation again shows peak memory. Of course, during dellocations, peak memory value should not change.

I just want to be sure that it was tested at least once, at least manually. Ideally, we chould add this test to the list of LibOS regression tests, but I don't insist.
</blockquote></details>

Yes, I've already manually tested using a very similar approach - issuing a bunch of `malloc` of large buffers (to make sure `mmap` is called) and check VmPeak cat in `/proc/<pid>/status` is exactly increased.
I can add/port my test sample into the regression test in a following patch.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/742#-N6m69KaCx8Nizt_V_fg:-N6mS3z84jtiBv4pyxrr:b-786dxz) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`The initial requirement was from #614.` -> `Resolves #614.`

btw. In the future, please don't hard-wrap your PR descriptions, it looks ugly.
</blockquote></details>

Got it, thanks mkow.

___
___
*[`-- commits` line 17 at r3](https://reviewable.io/reviews/gramineproject/gramine/742#-N6mASCJ-5QmOkKJX2op):*
Done.
___
*[`-- commits` line 21 at r3](https://reviewable.io/reviews/gramineproject/gramine/742#-N6mADtX9Sx_T4JlYVmI):*
Done.
___
*[`-- commits` line 22 at r3](https://reviewable.io/reviews/gramineproject/gramine/742#-N6mAIHFDUonoaSyd0PU):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This explanation doesn't make sense to me, for these you'd need current memory usage, not peak.
</blockquote></details>

It's cited from the initial issue discussions. The usage can be user-specific, e.g., monitoring, here I simply remove the example to avoid confusions.
___
*[`libos/src/bookkeep/libos_vma.c` line 29 at r3](https://reviewable.io/reviews/gramineproject/gramine/742#-N6lT1KX4yVErkp5teH6:-N6mQ2xh0HDAjif6v2Mz:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/de9f27759942db4dd90e6ae85e354b12cf3d79f3/libos/src/bookkeep/libos_vma.c#L29)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.
___
*[`libos/src/bookkeep/libos_vma.c` line 120 at r3](https://reviewable.io/reviews/gramineproject/gramine/742#-N6lRQCgEDm1TOf1qFLj:-N6mRW8G2tf7x60PfXnw:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/de9f27759942db4dd90e6ae85e354b12cf3d79f3/libos/src/bookkeep/libos_vma.c#L120)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This we could do.
</blockquote></details>

Done.
___
*[`libos/src/fs/proc/info.c` line 72 at r3](https://reviewable.io/reviews/gramineproject/gramine/742#-N6mQ36D4hxRcNB2tTGG:-N6mSKKtCeFUxG6t5XwG:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/de9f27759942db4dd90e6ae85e354b12cf3d79f3/libos/src/fs/proc/info.c#L72)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please add a TODO to use `realloc()` here once we implement it (you wouldn't need to reset `i` and `size` then).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-12 14:16 UTC, mkow approved these changes
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/742)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " and "squash! " found in commit messages' one-liners (waiting on @boryspoplawski and @kailun-qin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/742#-N6m69KaCx8Nizt_V_fg:-N6mk1Yy7kRvjOJpvZ5o:bllxabi) (no related file):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Got it, thanks mkow.
</blockquote></details>

Not done? See the first part of my message.

___
___
*[`-- commits` line 22 at r3](https://reviewable.io/reviews/gramineproject/gramine/742#-N6mAIHFDUonoaSyd0PU):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

It's cited from the initial issue discussions. The usage can be user-specific, e.g., monitoring, here I simply remove the example to avoid confusions.
</blockquote></details>

I don't care where you got it from, it was just plainly incorrect ¯\\_(ツ)_/¯


<!-- Sent from Reviewable.io -->

2022-07-12 15:01 UTC, boryspoplawski submitted a review, later dismissed
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/742)* status: all files reviewed, 1 unresolved discussion, "fixup! " and "squash! " found in commit messages' one-liners (waiting on @kailun-qin)



<!-- Sent from Reviewable.io -->

2022-07-12 17:23 UTC, mkow commented
Jenkins, test this please

2022-07-12 17:25 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/742)* status: all files reviewed, all discussions resolved, "fixup! " and "squash! " found in commit messages' one-liners

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/742#-N6m69KaCx8Nizt_V_fg:-N6nR5By9t827FvU7Yob:b-xui7cx) (no related file):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

`The initial requirement was from #614` - this was not included in the commit message, just in the PR description. I've updated the description anyway.
</blockquote></details>

Yes, and I wanted you to fix it in the PR description to auto-close #614 when this PR is merged :)

___


<!-- Sent from Reviewable.io -->

2022-07-13 00:50 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/742)* status: all files reviewed, all discussions resolved, "fixup! " and "squash! " found in commit messages' one-liners

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/742#-N6m69KaCx8Nizt_V_fg:-N6p1GTdC7f-s3GLACpU:b-ycx6ei) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Yes, and I wanted you to fix it in the PR description to auto-close #614 when this PR is merged :)
</blockquote></details>

Got you, fixed and thanks ;)

___


<!-- Sent from Reviewable.io -->

2022-07-13 07:28 UTC, dimakuv submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/742)* status: all files reviewed, all discussions resolved, "fixup! " and "squash! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2022-07-13 08:05 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/742)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2022-07-13 10:19 UTC, boryspoplawski approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/742)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-07-13 11:07 UTC, merged