[tools/sgx,common,Doc] Enable configurable signing algo for RA-TLS certs
gramineproject/gramine pull request #748
Opened 2022-07-12 08:08 UTC by kailun-qin

The initial requirement was from https://github.com/gramineproject/gramine/issues/156 and an initial PR was created by @dimakuv at https://github.com/gramineproject/graphene/pull/2314. This PR augments it w/ the possible RSA key size selection and drops ECDSA_SECP256K1 and ECDSA_SECP256R1 support based on Intel crypto guidelines/recommandations.

Previously, RA-TLS generated only RSA-3072 keypairs (and signed self-signed RA-TLS X.509 certificates with these RSA keys). This commit adds the ability to specify the signing algo: RSA (RSA-3072, RSA-4096) or ECDSA (ECDSA-384, ECDSA-521) for RA-TLS via a new envvar `RA_TLS_CERT_SIGNATURE_ALGO`.

2022-07-13 09:25 UTC, dimakuv requested changes
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/748)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @kailun-qin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/748#-N6qsCC27hZ8HaXGctrq:-N6qsCC27hZ8HaXGctrr:b-lx0kqi) (no related file):*
Thanks for this PR!

___
___
*[`common/include/pal_error.h` line 60 at r1](https://reviewable.io/reviews/gramineproject/gramine/748#-N6qo1Vw-97K-RkcBC8c:-N6qo1Vx3a9LyaJIF7ZY:b-7ctalc) ([raw file](https://github.com/gramineproject/gramine/blob/ba056ab6031bed69ab5297df75b012d92aeb5bcb/common/include/pal_error.h#L60)):*
> ```objc
>     PAL_ERROR_CRYPTO_INVALID_DH_STATE,
>     PAL_ERROR_CRYPTO_INVALID_PK_ALG,
> #define PAL_ERROR_CRYPTO_END PAL_ERROR_CRYPTO_INVALID_DH_STATE
> ```

This should be updated to
`#define PAL_ERROR_CRYPTO_END PAL_ERROR_CRYPTO_INVALID_PK_ALG`
___
*[`tools/sgx/ra-tls/ra_tls.h` line 38 at r1](https://reviewable.io/reviews/gramineproject/gramine/748#-N6qolfwCmIjHITcYyd1:-N6qolfwCmIjHITcYyd2:b-ylua9o) ([raw file](https://github.com/gramineproject/gramine/blob/ba056ab6031bed69ab5297df75b012d92aeb5bcb/tools/sgx/ra-tls/ra_tls.h#L38)):*
> ```objc
> #define SHA256_DIGEST_SIZE       32
> #define IAS_REQUEST_NONCE_LEN    32
> #define PUB_KEY_SIZE_MAX         512
> ```

You accidentally added these two lines here? The same macros are defined below.
___
*[`tools/sgx/ra-tls/ra_tls_attest.c` line 13 at r1](https://reviewable.io/reviews/gramineproject/gramine/748#-N6qpHdO6tVFWQyTL-79:-N6qpHdP-Qnj6yyNIBqb:bkr8app) ([raw file](https://github.com/gramineproject/gramine/blob/ba056ab6031bed69ab5297df75b012d92aeb5bcb/tools/sgx/ra-tls/ra_tls_attest.c#L13)):*
> ```C
>  *
>  * The self-signed RA-TLS certificate is signed by an ephemeral keypair generated and kept inside
>  * the enclave. The keypair is either RSA (the available public key size are 3072, 4096) or ECDSA
> ```

`key size` -> `key sizes`
___
*[`tools/sgx/ra-tls/ra_tls_attest.c` line 163 at r1](https://reviewable.io/reviews/gramineproject/gramine/748#-N6qpPgzALVuTetNqcsb:-N6qpPgzALVuTetNqcsc:bt76l09) ([raw file](https://github.com/gramineproject/gramine/blob/ba056ab6031bed69ab5297df75b012d92aeb5bcb/tools/sgx/ra-tls/ra_tls_attest.c#L163)):*
> ```C
>     int pk_der_size_byte = mbedtls_pk_write_pubkey_der(pk, pk_der, PUB_KEY_SIZE_MAX);
>     if (pk_der_size_byte <= 0)
>         return MBEDTLS_ERR_PK_BAD_INPUT_DATA;
> ```

Why did you decide to change the error code? Is it more logical, in your opinion?
___
*[`tools/sgx/ra-tls/ra_tls_attest.c` line 174 at r1](https://reviewable.io/reviews/gramineproject/gramine/748#-N6qqnQA-8bXYMS1tO-7:-N6qqnQA-8bXYMS1tO-8:b3o9nm2) ([raw file](https://github.com/gramineproject/gramine/blob/ba056ab6031bed69ab5297df75b012d92aeb5bcb/tools/sgx/ra-tls/ra_tls_attest.c#L174)):*
> ```C
> static int create_key(mbedtls_ctr_drbg_context* ctr_drbg, mbedtls_pk_context* pk) {
>     int ret;
>     size_t key_size = 0;
> ```

This is used only for RSA. Please rename to a more specific `rsa_key_size`
___
*[`tools/sgx/ra-tls/ra_tls_attest.c` line 179 at r1](https://reviewable.io/reviews/gramineproject/gramine/748#-N6qqCVz-scaZ-tY2anp:-N6qqCVz-scaZ-tY2anq:b-tlpv8x) ([raw file](https://github.com/gramineproject/gramine/blob/ba056ab6031bed69ab5297df75b012d92aeb5bcb/tools/sgx/ra-tls/ra_tls_attest.c#L179)):*
> ```C
>     key_algo = strdup(getenv(RA_TLS_CERT_SIGNATURE_ALGO) ? : RA_TLS_CERT_SIGNATURE_ALGO_DEFAULT);
>     if (!key_algo) {
>         ret = MBEDTLS_ERR_PK_UNKNOWN_PK_ALG;
> ```

This error code is a bit misleading. The only error that can happen above is "out of memory". In my previous PR, I used `MBEDTLS_ERR_X509_ALLOC_FAILED`. I agree this is also not amazing, but at least it conveys the information "some memory allocation failed during creation of the X.509 certificate". And since `create_key()` is part of the cert creation, it sounds like a better error code.
___
*[`tools/sgx/ra-tls/ra_tls_attest.c` line 182 at r1](https://reviewable.io/reviews/gramineproject/gramine/748#-N6qrMT7-iMUuPBavji_:-N6qrMT7-iMUuPBavjia:b-urkzk0) ([raw file](https://github.com/gramineproject/gramine/blob/ba056ab6031bed69ab5297df75b012d92aeb5bcb/tools/sgx/ra-tls/ra_tls_attest.c#L182)):*
> ```C
>         goto out;
>     }
> ```

I recommend to add a check against *all* currently supported algos, and if `key_algo` is not any of them, then explicitly fail with `MBEDTLS_ERR_PK_UNKNOWN_PK_ALG`.

I know this is a bit redundant, because you will already land into such code path in the `ECDSA pk generation` branch below. But the current logic is obscure, and with my proposed check it will be very obvious that we immediately fail if the key algo (specified by the user in envvar) is unsupported.
___
*[`tools/sgx/ra-tls/ra_tls_attest.c` line 207 at r1](https://reviewable.io/reviews/gramineproject/gramine/748#-N6qs1_gDWUrwuxyk91u:-N6qs1_gDWUrwuxyk91v:b-oh1awe) ([raw file](https://github.com/gramineproject/gramine/blob/ba056ab6031bed69ab5297df75b012d92aeb5bcb/tools/sgx/ra-tls/ra_tls_attest.c#L207)):*
> ```C
>             goto out;
> 
>         int elliptic_curve_group_id = 0;
> ```

I think it's better to initialize to a special value `MBEDTLS_ECP_DP_NONE`.
___
*[`tools/sgx/ra-tls/ra_tls_attest.c` line 216 at r1](https://reviewable.io/reviews/gramineproject/gramine/748#-N6qrnLb8ueLekL9vx58:-N6qrnLc8oNZhEp8gDCG:b-igh7bl) ([raw file](https://github.com/gramineproject/gramine/blob/ba056ab6031bed69ab5297df75b012d92aeb5bcb/tools/sgx/ra-tls/ra_tls_attest.c#L216)):*
> ```C
>             ret = MBEDTLS_ERR_ECP_BAD_INPUT_DATA;
>             goto out;
>         }
> ```

If you will follow my comment above, you'll never land into this else branch. So you can just remove it and instead have:
```
assert(elliptic_curve_group_id != MBEDTLS_ECP_DP_NONE);
```


<!-- Sent from Reviewable.io -->

2022-07-13 11:57 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/748)* status: 3 of 6 files reviewed, 9 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`common/include/pal_error.h` line 60 at r1](https://reviewable.io/reviews/gramineproject/gramine/748#-N6qo1Vw-97K-RkcBC8c:-N6rNkMJAX1dnApfi2w0:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/ba056ab6031bed69ab5297df75b012d92aeb5bcb/common/include/pal_error.h#L60)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This should be updated to
`#define PAL_ERROR_CRYPTO_END PAL_ERROR_CRYPTO_INVALID_PK_ALG`
</blockquote></details>

Done.
___
*[`tools/sgx/ra-tls/ra_tls.h` line 38 at r1](https://reviewable.io/reviews/gramineproject/gramine/748#-N6qolfwCmIjHITcYyd1:-N6rHv4d30kkB0zOvXSW:b8nlvge) ([raw file](https://github.com/gramineproject/gramine/blob/ba056ab6031bed69ab5297df75b012d92aeb5bcb/tools/sgx/ra-tls/ra_tls.h#L38)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You accidentally added these two lines here? The same macros are defined below.
</blockquote></details>

Just wanted to reorder a bit, but forgot to remove the below same macros. Thanks!
___
*[`tools/sgx/ra-tls/ra_tls_attest.c` line 13 at r1](https://reviewable.io/reviews/gramineproject/gramine/748#-N6qpHdO6tVFWQyTL-79:-N6rI5VTDXO8_T1ltBnV:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/ba056ab6031bed69ab5297df75b012d92aeb5bcb/tools/sgx/ra-tls/ra_tls_attest.c#L13)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`key size` -> `key sizes`
</blockquote></details>

Done.
___
*[`tools/sgx/ra-tls/ra_tls_attest.c` line 163 at r1](https://reviewable.io/reviews/gramineproject/gramine/748#-N6qpPgzALVuTetNqcsb:-N6rIKLg2ynpC4rSrnf5:b-a4y7oa) ([raw file](https://github.com/gramineproject/gramine/blob/ba056ab6031bed69ab5297df75b012d92aeb5bcb/tools/sgx/ra-tls/ra_tls_attest.c#L163)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why did you decide to change the error code? Is it more logical, in your opinion?
</blockquote></details>

Yes, the return error of `mbedtls_pk_write_pubkey_der` can be multiple reasons, i.e., not only `MBEDTLS_ERR_PK_INVALID_PUBKEY`, but can also be the bad input of `buf` or `size`. Let me know if does not make sense to you, I'm open to it.
___
*[`tools/sgx/ra-tls/ra_tls_attest.c` line 174 at r1](https://reviewable.io/reviews/gramineproject/gramine/748#-N6qqnQA-8bXYMS1tO-7:-N6rJQbc8fp_60MyD_pO:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/ba056ab6031bed69ab5297df75b012d92aeb5bcb/tools/sgx/ra-tls/ra_tls_attest.c#L174)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This is used only for RSA. Please rename to a more specific `rsa_key_size`
</blockquote></details>

Done.
___
*[`tools/sgx/ra-tls/ra_tls_attest.c` line 179 at r1](https://reviewable.io/reviews/gramineproject/gramine/748#-N6qqCVz-scaZ-tY2anp:-N6rJRd41ns-udsdryHU:bekot5m) ([raw file](https://github.com/gramineproject/gramine/blob/ba056ab6031bed69ab5297df75b012d92aeb5bcb/tools/sgx/ra-tls/ra_tls_attest.c#L179)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This error code is a bit misleading. The only error that can happen above is "out of memory". In my previous PR, I used `MBEDTLS_ERR_X509_ALLOC_FAILED`. I agree this is also not amazing, but at least it conveys the information "some memory allocation failed during creation of the X.509 certificate". And since `create_key()` is part of the cert creation, it sounds like a better error code.
</blockquote></details>

Yes, agree. `MBEDTLS_ERR_X509_ALLOC_FAILED` makes more sense.
___
*[`tools/sgx/ra-tls/ra_tls_attest.c` line 182 at r1](https://reviewable.io/reviews/gramineproject/gramine/748#-N6qrMT7-iMUuPBavji_:-N6rJmpYC8z3BlFuyLbm:bdsrc8b) ([raw file](https://github.com/gramineproject/gramine/blob/ba056ab6031bed69ab5297df75b012d92aeb5bcb/tools/sgx/ra-tls/ra_tls_attest.c#L182)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I recommend to add a check against *all* currently supported algos, and if `key_algo` is not any of them, then explicitly fail with `MBEDTLS_ERR_PK_UNKNOWN_PK_ALG`.

I know this is a bit redundant, because you will already land into such code path in the `ECDSA pk generation` branch below. But the current logic is obscure, and with my proposed check it will be very obvious that we immediately fail if the key algo (specified by the user in envvar) is unsupported.
</blockquote></details>

Thanks for the suggestion, I changed a bit the logic, pls kindly see if it's expected.
___
*[`tools/sgx/ra-tls/ra_tls_attest.c` line 207 at r1](https://reviewable.io/reviews/gramineproject/gramine/748#-N6qs1_gDWUrwuxyk91u:-N6rK5rY4Uq33ZE1P3Lt:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/ba056ab6031bed69ab5297df75b012d92aeb5bcb/tools/sgx/ra-tls/ra_tls_attest.c#L207)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I think it's better to initialize to a special value `MBEDTLS_ECP_DP_NONE`.
</blockquote></details>

Done.
___
*[`tools/sgx/ra-tls/ra_tls_attest.c` line 216 at r1](https://reviewable.io/reviews/gramineproject/gramine/748#-N6qrnLb8ueLekL9vx58:-N6rMZDWERaLMJ3Gj-Oo:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/ba056ab6031bed69ab5297df75b012d92aeb5bcb/tools/sgx/ra-tls/ra_tls_attest.c#L216)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

If you will follow my comment above, you'll never land into this else branch. So you can just remove it and instead have:
```
assert(elliptic_curve_group_id != MBEDTLS_ECP_DP_NONE);
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-13 14:26 UTC, dimakuv requested changes
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/748)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

___
*[`tools/sgx/ra-tls/ra_tls_attest.c` line 163 at r1](https://reviewable.io/reviews/gramineproject/gramine/748#-N6qpPgzALVuTetNqcsb:-N6rwa5l3Ofzhy8mBwyG:b-81ibl3) ([raw file](https://github.com/gramineproject/gramine/blob/ba056ab6031bed69ab5297df75b012d92aeb5bcb/tools/sgx/ra-tls/ra_tls_attest.c#L163)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Yes, the return error of `mbedtls_pk_write_pubkey_der` can be multiple reasons, i.e., not only `MBEDTLS_ERR_PK_INVALID_PUBKEY`, but can also be the bad input of `buf` or `size`. Let me know if does not make sense to you, I'm open to it.
</blockquote></details>

I'm fine with your version.
___
*[`tools/sgx/ra-tls/ra_tls_attest.c` line 209 at r2](https://reviewable.io/reviews/gramineproject/gramine/748#-N6rwwaJ6PBNs9AMl_HV:-N6rwwaK-SQW-trcF_Vo:b-m73bc0) ([raw file](https://github.com/gramineproject/gramine/blob/b05ca8ef0c395ffaa9e7011d11805156975531c6/tools/sgx/ra-tls/ra_tls_attest.c#L209)):*
> ```C
>         if (ret < 0)
>             goto out;
>     } else {
> ```

Please add `assert(elliptic_curve_group_id != MBEDTLS_ECP_DP_NONE);` after the else statement. Just for sanity.


<!-- Sent from Reviewable.io -->

2022-07-13 14:38 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/748)* status: 5 of 7 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`tools/sgx/ra-tls/ra_tls_attest.c` line 209 at r2](https://reviewable.io/reviews/gramineproject/gramine/748#-N6rwwaJ6PBNs9AMl_HV:-N6rzmBK5ZdnteG2jMdn:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b05ca8ef0c395ffaa9e7011d11805156975531c6/tools/sgx/ra-tls/ra_tls_attest.c#L209)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add `assert(elliptic_curve_group_id != MBEDTLS_ECP_DP_NONE);` after the else statement. Just for sanity.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-13 14:48 UTC, dimakuv approved these changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/748)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/748#-N6s0fFz8kd5eFj4Snmk:-N6s0fG-11eJV-BW_ath:bg83tmh) (no related file):*
I would want to verify this PR manually on e.g. `ra-tls-mbedtls` before the final merge. Other than that, the PR looks legitimate to me.

___
___
*[`tools/sgx/ra-tls/meson.build` line 16 at r3](https://reviewable.io/reviews/gramineproject/gramine/748#-N6s0Qwp9yNH89uNFece:-N6s0QwqCoHZqaankAlp:b-oa1n1k) ([raw file](https://github.com/gramineproject/gramine/blob/fa78335512c16a8414faaaf1569e1ba245c80365/tools/sgx/ra-tls/meson.build#L16)):*
> ```Meson
>     include_directories: sgx_inc,
>     dependencies: [
>         sgx_util_dep,
> ```

Why did you add it here?


<!-- Sent from Reviewable.io -->

2022-07-13 14:48 UTC, dimakuv commented
Jenkins, test this please

2022-07-13 15:16 UTC, dimakuv commented
Jenkins, retest Jenkins-SGX-18.04-apps please

An interesting error log which doesn't seem to be related to this PR:
```
17:11:08  gramine-sgx server & SERVER_ID=$!; \
17:11:08  ./client epid > OUTPUT; \
17:11:10  User requested RA-TLS attestation but cannot find lib
17:11:42  Makefile:158: recipe for target 'check_epid' failed
```

Surprisingly, Jenkins-SGX-20.04-apps pipeline succeeded, even though it runs the same test. Let's see if it reproduces.

2022-07-13 15:34 UTC, kailun-qin reviewed
Interesting... Looks like it reproduces.

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/748#-:-N6sBSQuBq3d0Ct7EKn1:b5ppe8b)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @kailun-qin)



<!-- Sent from Reviewable.io -->

2022-07-13 15:37 UTC, dimakuv reviewed
Can you debug this?

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/748#-:-N6sCH5o7mYj0fLiNQG9:b-psm85e)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

___
*[`tools/sgx/ra-tls/meson.build` line 16 at r3](https://reviewable.io/reviews/gramineproject/gramine/748#-N6s0Qwp9yNH89uNFece:-N6sBkVHDKliRqe5wgSP:b-j46g91) ([raw file](https://github.com/gramineproject/gramine/blob/fa78335512c16a8414faaaf1569e1ba245c80365/tools/sgx/ra-tls/meson.build#L16)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

According to https://github.com/gramineproject/gramine/blob/master/tools/sgx/common/util.c#L233, I suppose it's needed for the added `assert`.
</blockquote></details>

I see. Ok, fair enough.


<!-- Sent from Reviewable.io -->

2022-07-13 16:41 UTC, kailun-qin reviewed
If it's only specific to 18.04+epid (since not able to access the full log), then unfortunately I don't have such env in hand...

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/748#-:-N6sQeRq8uaWYZKY4LeA:b81lmp)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)



<!-- Sent from Reviewable.io -->

2022-07-13 17:50 UTC, boryspoplawski reviewed
There is no more information in the log than @dimakuv posted above.
Ad 18.04: you can just run it inside Docker (it's actually how our CI works), the only thing you need is a machine that can run epid attestation

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/748#-:-N6sfT-K01eY5Qad5prY:b4c3409)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)



<!-- Sent from Reviewable.io -->

2022-07-14 07:12 UTC, kailun-qin reviewed
Thanks borys. I don't have an epid env at this moment but I'll see if I can find/setup one to verify.

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/748#-:-N6vY0Ht-FGWqaCzAiZz:b-m8xspi)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)



<!-- Sent from Reviewable.io -->

2022-07-14 09:00 UTC, dimakuv reviewed
Let me see if I can create an Azure CC VM with Ubuntu 18.04 and EPID. I'll try it out, debug and report the results.

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/748#-:-N6vvvb024kL9h3Yq6Tg:b-hupv4q)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)



<!-- Sent from Reviewable.io -->

2022-07-14 09:56 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/748)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/748#-N6s0fFz8kd5eFj4Snmk:-N6w7eyW0wntwfoW6K9_:bm9ojhu) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I would want to verify this PR manually on e.g. `ra-tls-mbedtls` before the final merge. Other than that, the PR looks legitimate to me.
</blockquote></details>

Done. Verified (not the final version, but close-to-final). Found a couple bugs.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/748#-N6w2vMc6mIDb46RvNLH:-N6w2vMc6mIDb46RvNLI:b-dcl2qa) (no related file):*
@kailun-qin Please add this change:
```
diff --git a/CI-Examples/ra-tls-mbedtls/server.manifest.template b/CI-Examples/ra-tls-mbedtls/server.manifest.template
index 1510c83f..4d01dace 100644
--- a/CI-Examples/ra-tls-mbedtls/server.manifest.template
+++ b/CI-Examples/ra-tls-mbedtls/server.manifest.template
@@ -19,6 +19,7 @@ fs.mounts = [
 ]

 sgx.debug = true
+sgx.enclave_size = "512M"

 sgx.remote_attestation = "{{ ra_type }}"
 sgx.ra_client_spid = "{{ ra_client_spid }}"
```

This fixes the problem with `ra-tls-mbedtls` example on Ubuntu 18.04. The reason was simple: the default enclave size of 256MB became not enough after your changes (I suspect the inclusion of `libsgx_util` library). So the `ra-tls-mbedtls` example failed on an `mmap()` required by the `libra-tls-attest.so`.

___
___
*[`tools/sgx/ra-tls/ra_tls_attest.c` line 162 at r3](https://reviewable.io/reviews/gramineproject/gramine/748#-N6w6bS_7_YU2QIinP7g:-N6w6bS_7_YU2QIinP7h:b-38xejw) ([raw file](https://github.com/gramineproject/gramine/blob/fa78335512c16a8414faaaf1569e1ba245c80365/tools/sgx/ra-tls/ra_tls_attest.c#L162)):*
> ```C
> 
>     /* below function writes data at the end of the buffer */
>     int pk_der_size_byte = mbedtls_pk_write_pubkey_der(pk, pk_der, PUB_KEY_SIZE_MAX);
> ```

This doesn't work with `RSA-4096`. I just did a quick debugging session, but I didn't go deep why it fails.

The return error code from `mbedtls_pk_write_pubkey_der()` is:
```
(gdb) p/x $rax
$4 = 0xffffff94
(gdb) p (int)$rax
$6 = -108
```

My suspicion is that `PUB_KEY_SIZE_MAX` (= 512 bytes) is not sufficient to hold the 4096 RSA.

UPDATE: Yes, my suspicion was correct. I fixed this via:
```
diff --git a/tools/sgx/ra-tls/ra_tls.h b/tools/sgx/ra-tls/ra_tls.h
index 04bc79d6..8ef393bb 100644
--- a/tools/sgx/ra-tls/ra_tls.h
+++ b/tools/sgx/ra-tls/ra_tls.h
@@ -35,7 +35,7 @@

 #define SHA256_DIGEST_SIZE       32
 #define IAS_REQUEST_NONCE_LEN    32
-#define PUB_KEY_SIZE_MAX         512
+#define PUB_KEY_SIZE_MAX         1024

 #define RSA_PUB_3072_KEY_LEN     3072
 #define RSA_PUB_4096_KEY_LEN     4096
```

Please update your PR accordingly.


<!-- Sent from Reviewable.io -->

2022-07-14 11:13 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/748)* status: 6 of 8 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/748#-N6s0fFz8kd5eFj4Snmk:-N6wPNrT1oC7fXxc3UDO:b-c1s8fo) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. Verified (not the final version, but close-to-final). Found a couple bugs.
</blockquote></details>

Thanks for checking!

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/748#-N6w2vMc6mIDb46RvNLH:-N6wOSZR03q0-NVZc15_:bd0skhc) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@kailun-qin Please add this change:
```
diff --git a/CI-Examples/ra-tls-mbedtls/server.manifest.template b/CI-Examples/ra-tls-mbedtls/server.manifest.template
index 1510c83f..4d01dace 100644
--- a/CI-Examples/ra-tls-mbedtls/server.manifest.template
+++ b/CI-Examples/ra-tls-mbedtls/server.manifest.template
@@ -19,6 +19,7 @@ fs.mounts = [
 ]

 sgx.debug = true
+sgx.enclave_size = "512M"

 sgx.remote_attestation = "{{ ra_type }}"
 sgx.ra_client_spid = "{{ ra_client_spid }}"
```

This fixes the problem with `ra-tls-mbedtls` example on Ubuntu 18.04. The reason was simple: the default enclave size of 256MB became not enough after your changes (I suspect the inclusion of `libsgx_util` library). So the `ra-tls-mbedtls` example failed on an `mmap()` required by the `libra-tls-attest.so`.
</blockquote></details>

Thanks a lot for the explanation, updated.

___
___
*[`tools/sgx/ra-tls/ra_tls_attest.c` line 162 at r3](https://reviewable.io/reviews/gramineproject/gramine/748#-N6w6bS_7_YU2QIinP7g:-N6wOl_R4iasLj0XdmVa:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/fa78335512c16a8414faaaf1569e1ba245c80365/tools/sgx/ra-tls/ra_tls_attest.c#L162)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This doesn't work with `RSA-4096`. I just did a quick debugging session, but I didn't go deep why it fails.

The return error code from `mbedtls_pk_write_pubkey_der()` is:
```
(gdb) p/x $rax
$4 = 0xffffff94
(gdb) p (int)$rax
$6 = -108
```

My suspicion is that `PUB_KEY_SIZE_MAX` (= 512 bytes) is not sufficient to hold the 4096 RSA.

UPDATE: Yes, my suspicion was correct. I fixed this via:
```
diff --git a/tools/sgx/ra-tls/ra_tls.h b/tools/sgx/ra-tls/ra_tls.h
index 04bc79d6..8ef393bb 100644
--- a/tools/sgx/ra-tls/ra_tls.h
+++ b/tools/sgx/ra-tls/ra_tls.h
@@ -35,7 +35,7 @@

 #define SHA256_DIGEST_SIZE       32
 #define IAS_REQUEST_NONCE_LEN    32
-#define PUB_KEY_SIZE_MAX         512
+#define PUB_KEY_SIZE_MAX         1024

 #define RSA_PUB_3072_KEY_LEN     3072
 #define RSA_PUB_4096_KEY_LEN     4096
```

Please update your PR accordingly.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-14 11:37 UTC, dimakuv submitted a review, later dismissed
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/748)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2022-07-14 11:37 UTC, dimakuv commented
Jenkins, test this please

2022-09-01 21:51 UTC, boryspoplawski requested changes
> Reviewed 3 of 6 files at r1, 1 of 3 files at r2, 2 of 2 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/748)* status: all files reviewed, 13 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/748#-NAuwxH4D7dfhMLRdC6M:-NAuwxH57rdFWkEGBjf2:bjbc1y2) (no related file):*
How about ed25519?
Update: I see, mbedtls does not support it.

___
___
*[`-- commits` line 2 at r4](https://reviewable.io/reviews/gramineproject/gramine/748#-NAutRvVEciFfR9nJpfw):*
No need to list `Doc` if the core change is elsewhere and is just also documented. `common` has only some error constants added, not worth mentioning in oneliner.



_Suggestion:_
```
[tools/sgx]
```
___
*[`-- commits` line 5 at r4](https://reviewable.io/reviews/gramineproject/gramine/748#-NAv16Aj6ajqwzrbH7Yl):*
This reads weirdly to me. Maybe:



_Suggestion:_
```
  Previously, RA-TLS generated only RSA-3072 keypairs (and used them to
  sign RA-TLS X.509 certificates). This commit ...
```
___
*[`common/include/pal_error.h` line 59 at r4](https://reviewable.io/reviews/gramineproject/gramine/748#-NAuvKyv9F49ZEE_Hf6N:-NAuvKyv9F49ZEE_Hf6O:b-7du6xj) ([raw file](https://github.com/gramineproject/gramine/blob/4483dc5428848b72810abfb69228d9566b081e23/common/include/pal_error.h#L59)):*
> ```objc
>     PAL_ERROR_CRYPTO_RNG_FAILED,
>     PAL_ERROR_CRYPTO_INVALID_DH_STATE,
>     PAL_ERROR_CRYPTO_INVALID_PK_ALG,
> ```

Maybe let's call it `PAL_ERROR_CRYPTO_INVALID_ALGO`? It doesn't have to be about public keys (which I assume `PK` stands for). Also I believe `ALGO` is more common abbreviation and you also use it elsewhere already.



_Suggestion:_
```objc
PAL_ERROR_CRYPTO_INVALID_ALGO
```
___
*[`common/src/crypto/adapters/mbedtls_adapter.c` line 96 at r4](https://reviewable.io/reviews/gramineproject/gramine/748#-NAuuXg66paBBvFDcfkS:-NAuuXg79cStoHZXUDon:by7b61c) ([raw file](https://github.com/gramineproject/gramine/blob/4483dc5428848b72810abfb69228d9566b081e23/common/src/crypto/adapters/mbedtls_adapter.c#L96)):*
> ```C
> 
>         case MBEDTLS_ERR_ECP_INVALID_KEY:
>         case MBEDTLS_ERR_ECP_SIG_LEN_MISMATCH:
> ```

Let's move this one elsewhere, this doesn't make sense to me. Maybe `PAL_ERROR_CRYPTO_INVALID_FORMAT` or `PAL_ERROR_CRYPTO_VERIFY_FAILED`?
___
*[`tools/sgx/ra-tls/meson.build` line 16 at r3](https://reviewable.io/reviews/gramineproject/gramine/748#-N6s0Qwp9yNH89uNFece:-NAuwONQCCdAWDnt-kAL:bq7n1o2) ([raw file](https://github.com/gramineproject/gramine/blob/fa78335512c16a8414faaaf1569e1ba245c80365/tools/sgx/ra-tls/meson.build#L16)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I see. Ok, fair enough.
</blockquote></details>

Wait, what? This library is linked against glibc not our common utils.
___
*[`tools/sgx/ra-tls/ra_tls.h` line 126 at r4](https://reviewable.io/reviews/gramineproject/gramine/748#-NAuy3WPE2HsxvXfkNdK:-NAuy3WPE2HsxvXfkNdL:b-i40ozd) ([raw file](https://github.com/gramineproject/gramine/blob/4483dc5428848b72810abfb69228d9566b081e23/tools/sgx/ra-tls/ra_tls.h#L126)):*
> The RSA keypair has one of 3072, 4096  public key size and has PKCS#1 v1.5 encoding; the ECDSA keypair has one of SECP384R1, SECP521R1 curves.

Is this good place for such information? What if we add new types, will we keep appending to this list here?
___
*[`tools/sgx/ra-tls/ra_tls_attest.c` line 163 at r1](https://reviewable.io/reviews/gramineproject/gramine/748#-N6qpPgzALVuTetNqcsb:-NAuzQyN9m4cWu415yJ6:b-gkne9p) ([raw file](https://github.com/gramineproject/gramine/blob/ba056ab6031bed69ab5297df75b012d92aeb5bcb/tools/sgx/ra-tls/ra_tls_attest.c#L163)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I'm fine with your version.
</blockquote></details>

Why not pass the error returned by `mbedtls_pk_write_pubkey_der`?
___
*[`tools/sgx/ra-tls/ra_tls_attest.c` line 12 at r4](https://reviewable.io/reviews/gramineproject/gramine/748#-NAuyR1o9GlvgE0COUv5:-NAuyR1o9GlvgE0COUv6:bfsmmoj) ([raw file](https://github.com/gramineproject/gramine/blob/4483dc5428848b72810abfb69228d9566b081e23/tools/sgx/ra-tls/ra_tls_attest.c#L12)):*
> ```C
>  * agnostic to the format of the SGX quote).
>  *
>  * The self-signed RA-TLS certificate is signed by an ephemeral keypair generated and kept inside
> ```

This reads weirdly. We know what "self-signed" cert is signed by...



_Code quote:_
```C
The self-signed RA-TLS certificate is signed by an ephemeral keypair generated and kept inside
```
___
*[`tools/sgx/ra-tls/ra_tls_attest.c` line 162 at r4](https://reviewable.io/reviews/gramineproject/gramine/748#-NAuyrE_5xiHaSk-5qZn:-NAuyrE_5xiHaSk-5qZo:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/4483dc5428848b72810abfb69228d9566b081e23/tools/sgx/ra-tls/ra_tls_attest.c#L162)):*
> ```C
> 
>     /* below function writes data at the end of the buffer */
>     int pk_der_size_byte = mbedtls_pk_write_pubkey_der(pk, pk_der, PUB_KEY_SIZE_MAX);
> ```





_Suggestion:_
```C
sizeof(pk_der)
```
___
*[`tools/sgx/ra-tls/ra_tls_attest.c` line 179 at r4](https://reviewable.io/reviews/gramineproject/gramine/748#-NAv-Chq8a3SNwd1uTxJ:-NAv-Chq8a3SNwd1uTxK:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/4483dc5428848b72810abfb69228d9566b081e23/tools/sgx/ra-tls/ra_tls_attest.c#L179)):*
> ```C
>     char* key_algo = NULL;
> 
>     key_algo = strdup(getenv(RA_TLS_CERT_SIGNATURE_ALGO) ? : RA_TLS_CERT_SIGNATURE_ALGO_DEFAULT);
> ```





_Suggestion:_
```C
    char* key_algo = strdup(getenv(RA_TLS_CERT_SIGNATURE_ALGO) ?: RA_TLS_CERT_SIGNATURE_ALGO_DEFAULT);
```
___
*[`tools/sgx/ra-tls/ra_tls_attest.c` line 204 at r4](https://reviewable.io/reviews/gramineproject/gramine/748#-NAv0N3l6DlNIvnl8poq:-NAv0N3m2GSStWvf1tDm:bxvo0fi) ([raw file](https://github.com/gramineproject/gramine/blob/4483dc5428848b72810abfb69228d9566b081e23/tools/sgx/ra-tls/ra_tls_attest.c#L204)):*
> ```C
>             goto out;
> 
>         mbedtls_rsa_init((mbedtls_rsa_context*)pk->pk_ctx, MBEDTLS_RSA_PKCS_V15, /*hash_id=*/0);
> ```

Why do we need this cast?



_Code quote:_
```C
(mbedtls_rsa_context*)
```
___
*[`tools/sgx/ra-tls/ra_tls_attest.c` line 206 at r4](https://reviewable.io/reviews/gramineproject/gramine/748#-NAv0OdV78_8c4geXukJ:-NAv0OdV78_8c4geXukK:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/4483dc5428848b72810abfb69228d9566b081e23/tools/sgx/ra-tls/ra_tls_attest.c#L206)):*
> ```C
>         mbedtls_rsa_init((mbedtls_rsa_context*)pk->pk_ctx, MBEDTLS_RSA_PKCS_V15, /*hash_id=*/0);
> 
>         ret = mbedtls_rsa_gen_key((mbedtls_rsa_context*)pk->pk_ctx, mbedtls_ctr_drbg_random,
> ```

ditto
___
*[`tools/sgx/ra-tls/ra_tls_verify_common.c` line 171 at r4](https://reviewable.io/reviews/gramineproject/gramine/748#-NAv0qmp1VF0ekFSmhzZ:-NAv0qmp1VF0ekFSmhz_:bg8r165) ([raw file](https://github.com/gramineproject/gramine/blob/4483dc5428848b72810abfb69228d9566b081e23/tools/sgx/ra-tls/ra_tls_verify_common.c#L171)):*
> ```C
>     /* below function writes data at the end of the buffer */
>     int pk_der_size_byte = mbedtls_pk_write_pubkey_der(&crt->pk, pk_der, PUB_KEY_SIZE_MAX);
>     if (pk_der_size_byte <= 0)
> ```

ditto (why not pass the error)


<!-- Sent from Reviewable.io -->

2022-09-02 04:49 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/748)* status: all files reviewed, 13 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[`-- commits` line 2 at r4](https://reviewable.io/reviews/gramineproject/gramine/748#-NAutRvVEciFfR9nJpfw):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

No need to list `Doc` if the core change is elsewhere and is just also documented. `common` has only some error constants added, not worth mentioning in oneliner.
</blockquote></details>

Got it, done, thanks!
___
*[`-- commits` line 5 at r4](https://reviewable.io/reviews/gramineproject/gramine/748#-NAv16Aj6ajqwzrbH7Yl):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This reads weirdly to me. Maybe:
</blockquote></details>

Done.
___
*[`common/include/pal_error.h` line 59 at r4](https://reviewable.io/reviews/gramineproject/gramine/748#-NAuvKyv9F49ZEE_Hf6N:-NAvyY8D0r_3NC9FOv-A:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/4483dc5428848b72810abfb69228d9566b081e23/common/include/pal_error.h#L59)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Maybe let's call it `PAL_ERROR_CRYPTO_INVALID_ALGO`? It doesn't have to be about public keys (which I assume `PK` stands for). Also I believe `ALGO` is more common abbreviation and you also use it elsewhere already.
</blockquote></details>

Done.
___
*[`common/src/crypto/adapters/mbedtls_adapter.c` line 96 at r4](https://reviewable.io/reviews/gramineproject/gramine/748#-NAuuXg66paBBvFDcfkS:-NAvyygp5kyliaaXKOrN:bclk2rf) ([raw file](https://github.com/gramineproject/gramine/blob/4483dc5428848b72810abfb69228d9566b081e23/common/src/crypto/adapters/mbedtls_adapter.c#L96)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Let's move this one elsewhere, this doesn't make sense to me. Maybe `PAL_ERROR_CRYPTO_INVALID_FORMAT` or `PAL_ERROR_CRYPTO_VERIFY_FAILED`?
</blockquote></details>

Moved to `PAL_ERROR_CRYPTO_VERIFY_FAILED`.
___
*[`tools/sgx/ra-tls/meson.build` line 16 at r3](https://reviewable.io/reviews/gramineproject/gramine/748#-N6s0Qwp9yNH89uNFece:-NAw8o9lDl-OtoHIsmeq:b9fo68y) ([raw file](https://github.com/gramineproject/gramine/blob/fa78335512c16a8414faaaf1569e1ba245c80365/tools/sgx/ra-tls/meson.build#L16)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Wait, what? This library is linked against glibc not our common utils.
</blockquote></details>

Interesting... Looks like we're using https://github.com/gramineproject/gramine/blob/f1e1d22d29a08c05a6cf19188aa0241787608371/tools/sgx/ra-tls/meson.build#L14 here which includes our `<assert.h>` in common (which requires `_log()` and `abort()` then). I can add new meson declarations to exclude `common_inc` specifically for this one... I'm leaving this unchanged for now, any suggestions?
___
*[`tools/sgx/ra-tls/ra_tls.h` line 126 at r4](https://reviewable.io/reviews/gramineproject/gramine/748#-NAuy3WPE2HsxvXfkNdK:-NAwJNAC7OrR9ykzx3fV:bqqfsyn) ([raw file](https://github.com/gramineproject/gramine/blob/4483dc5428848b72810abfb69228d9566b081e23/tools/sgx/ra-tls/ra_tls.h#L126)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

> The RSA keypair has one of 3072, 4096  public key size and has PKCS#1 v1.5 encoding; the ECDSA keypair has one of SECP384R1, SECP521R1 curves.

Is this good place for such information? What if we add new types, will we keep appending to this list here?
</blockquote></details>

emm... I think it's better to have as it's for the public API `ra_tls_create_key_and_crt_der()` below and in our latest version: https://github.com/gramineproject/gramine/blob/f1e1d22d29a08c05a6cf19188aa0241787608371/tools/sgx/ra-tls/ra_tls.h#L118. But it's also doc'ed in `Documentation/attestation.rst` and `tools/sgx/ra-tls/ra_tls_attest.c`, maybe we can just keep the one here and the one in `Documentation/attestation.rst`. WDYT?
___
*[`tools/sgx/ra-tls/ra_tls_attest.c` line 163 at r1](https://reviewable.io/reviews/gramineproject/gramine/748#-N6qpPgzALVuTetNqcsb:-NAwUYwY3gmVvaDbaQ0j:b-1lmj7r) ([raw file](https://github.com/gramineproject/gramine/blob/ba056ab6031bed69ab5297df75b012d92aeb5bcb/tools/sgx/ra-tls/ra_tls_attest.c#L163)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why not pass the error returned by `mbedtls_pk_write_pubkey_der`?
</blockquote></details>

I guess it's for considering `pk_der_size_byte == 0` as an error so that callers can fail/return fast in some cases.
___
*[`tools/sgx/ra-tls/ra_tls_attest.c` line 12 at r4](https://reviewable.io/reviews/gramineproject/gramine/748#-NAuyR1o9GlvgE0COUv5:-NAwP5mFCc6SZ-qpHwkU:bdf9qcc) ([raw file](https://github.com/gramineproject/gramine/blob/4483dc5428848b72810abfb69228d9566b081e23/tools/sgx/ra-tls/ra_tls_attest.c#L12)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This reads weirdly. We know what "self-signed" cert is signed by...
</blockquote></details>

Removed the para according to the above comment.
___
*[`tools/sgx/ra-tls/ra_tls_attest.c` line 162 at r4](https://reviewable.io/reviews/gramineproject/gramine/748#-NAuyrE_5xiHaSk-5qZn:-NAwQ0qWBR5d4vI9iF83:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/4483dc5428848b72810abfb69228d9566b081e23/tools/sgx/ra-tls/ra_tls_attest.c#L162)):*
> ```C
> 
>     /* below function writes data at the end of the buffer */
>     int pk_der_size_byte = mbedtls_pk_write_pubkey_der(pk, pk_der, PUB_KEY_SIZE_MAX);
> ```

Done.
___
*[`tools/sgx/ra-tls/ra_tls_attest.c` line 179 at r4](https://reviewable.io/reviews/gramineproject/gramine/748#-NAv-Chq8a3SNwd1uTxJ:-NAwQ7Of5jkqPvNhuaPX:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/4483dc5428848b72810abfb69228d9566b081e23/tools/sgx/ra-tls/ra_tls_attest.c#L179)):*
> ```C
>     char* key_algo = NULL;
> 
>     key_algo = strdup(getenv(RA_TLS_CERT_SIGNATURE_ALGO) ? : RA_TLS_CERT_SIGNATURE_ALGO_DEFAULT);
> ```

Done.
___
*[`tools/sgx/ra-tls/ra_tls_attest.c` line 204 at r4](https://reviewable.io/reviews/gramineproject/gramine/748#-NAv0N3l6DlNIvnl8poq:-NAwRs9I03JvFva9OJNR:b2e2586) ([raw file](https://github.com/gramineproject/gramine/blob/4483dc5428848b72810abfb69228d9566b081e23/tools/sgx/ra-tls/ra_tls_attest.c#L204)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why do we need this cast?
</blockquote></details>

It's using `mbedtls_pk_rsa()` to access the private field since mbedTLS 3.x (in our latest version): https://github.com/gramineproject/gramine/blob/dd07c4a335f1d9c3fa465fe03a63dc79060faaa6/tools/sgx/ra-tls/ra_tls_attest.c#L234. I'll leave it here as it'll be fixed during rebase.
___
*[`tools/sgx/ra-tls/ra_tls_attest.c` line 206 at r4](https://reviewable.io/reviews/gramineproject/gramine/748#-NAv0OdV78_8c4geXukJ:-NAwSKWt59QBC1O-6rQh:b-oea9dd) ([raw file](https://github.com/gramineproject/gramine/blob/4483dc5428848b72810abfb69228d9566b081e23/tools/sgx/ra-tls/ra_tls_attest.c#L206)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Pls kindly see above.
___
*[`tools/sgx/ra-tls/ra_tls_verify_common.c` line 171 at r4](https://reviewable.io/reviews/gramineproject/gramine/748#-NAv0qmp1VF0ekFSmhzZ:-NAwU_b35QogDEbM1ZvD:b-oea9dd) ([raw file](https://github.com/gramineproject/gramine/blob/4483dc5428848b72810abfb69228d9566b081e23/tools/sgx/ra-tls/ra_tls_verify_common.c#L171)):*
<details><summary><i>Previously, boryspoplawski (Bory [...]

2022-09-02 07:41 UTC, dimakuv requested changes
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/748)* status: all files reviewed, 13 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " and "squash! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[`tools/sgx/ra-tls/meson.build` line 16 at r3](https://reviewable.io/reviews/gramineproject/gramine/748#-N6s0Qwp9yNH89uNFece:-NAx5V7KAqLyN6-ULEFk:b-953xp7) ([raw file](https://github.com/gramineproject/gramine/blob/fa78335512c16a8414faaaf1569e1ba245c80365/tools/sgx/ra-tls/meson.build#L16)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Interesting... Looks like we're using https://github.com/gramineproject/gramine/blob/f1e1d22d29a08c05a6cf19188aa0241787608371/tools/sgx/ra-tls/meson.build#L14 here which includes our `<assert.h>` in common (which requires `_log()` and `abort()` then). I can add new meson declarations to exclude `common_inc` specifically for this one... I'm leaving this unchanged for now, any suggestions?
</blockquote></details>

Borys is right, this is all stupid.

I suggest to remove the `assert()` from `ra_tls_attest.c` and thus remove `#include <assert.h>`. This will solve this problem for now.

And I would also like to create a GitHub issue that reminds us to remove this `sgx_inc` from RA-TLS include dependencies. And check all headers that RA-TLS actually needs (I guess these are SGX-hardware-specific structs) and include only them. And then create a PR that untangles this mess. (Same for Secret Prov library).
___
*[`tools/sgx/ra-tls/ra_tls.h` line 126 at r4](https://reviewable.io/reviews/gramineproject/gramine/748#-NAuy3WPE2HsxvXfkNdK:-NAx70bu5mj083wUZveN:b-aq7rzm) ([raw file](https://github.com/gramineproject/gramine/blob/4483dc5428848b72810abfb69228d9566b081e23/tools/sgx/ra-tls/ra_tls.h#L126)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

emm... I think it's better to have as it's for the public API `ra_tls_create_key_and_crt_der()` below and in our latest version: https://github.com/gramineproject/gramine/blob/f1e1d22d29a08c05a6cf19188aa0241787608371/tools/sgx/ra-tls/ra_tls.h#L118. But it's also doc'ed in `Documentation/attestation.rst` and `tools/sgx/ra-tls/ra_tls_attest.c`, maybe we can just keep the one here and the one in `Documentation/attestation.rst`. WDYT?
</blockquote></details>

I would vote for keeping this info here (+ in `attestation.rst`). I think these are the most obvious two places where we must list all available options. So I'm fine with current implementation.
___
*[`tools/sgx/ra-tls/ra_tls_attest.c` line 163 at r1](https://reviewable.io/reviews/gramineproject/gramine/748#-N6qpPgzALVuTetNqcsb:-NAx7pRp0IcUhAacpCcH:bfng5rx) ([raw file](https://github.com/gramineproject/gramine/blob/ba056ab6031bed69ab5297df75b012d92aeb5bcb/tools/sgx/ra-tls/ra_tls_attest.c#L163)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

I guess it's for considering `pk_der_size_byte == 0` as an error so that callers can fail/return fast in some cases.
</blockquote></details>

Actually, Borys is right. This function cannot return `0`, so we can just return the error. See the function implementation here: https://os.mbed.com/teams/sandbox/code/mbedtls/docs/tip/pkwrite_8c_source.html#l00151

So this should be fine:
```
    if (pk_der_size_byte < 0)
        return pk_der_size_byte;
```
___
*[`tools/sgx/ra-tls/ra_tls_verify_common.c` line 171 at r4](https://reviewable.io/reviews/gramineproject/gramine/748#-NAv0qmp1VF0ekFSmhzZ:-NAx8I9h8sq1aqRklBas:b-hlw7fv) ([raw file](https://github.com/gramineproject/gramine/blob/4483dc5428848b72810abfb69228d9566b081e23/tools/sgx/ra-tls/ra_tls_verify_common.c#L171)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Pls kindly see above.
</blockquote></details>

ditto (we can pass the error, let's do it)


<!-- Sent from Reviewable.io -->

2022-09-02 07:42 UTC, dimakuv reviewed
> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/748)* status: all files reviewed, 13 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " and "squash! " found in commit messages' one-liners (waiting on @boryspoplawski)



<!-- Sent from Reviewable.io -->

2022-09-02 08:04 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/748)* status: all files reviewed, 13 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " and "squash! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[`tools/sgx/ra-tls/meson.build` line 16 at r3](https://reviewable.io/reviews/gramineproject/gramine/748#-N6s0Qwp9yNH89uNFece:-NAxBe7O5WJf-JGt9ebe:bo3uir3) ([raw file](https://github.com/gramineproject/gramine/blob/fa78335512c16a8414faaaf1569e1ba245c80365/tools/sgx/ra-tls/meson.build#L16)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Borys is right, this is all stupid.

I suggest to remove the `assert()` from `ra_tls_attest.c` and thus remove `#include <assert.h>`. This will solve this problem for now.

And I would also like to create a GitHub issue that reminds us to remove this `sgx_inc` from RA-TLS include dependencies. And check all headers that RA-TLS actually needs (I guess these are SGX-hardware-specific structs) and include only them. And then create a PR that untangles this mess. (Same for Secret Prov library).
</blockquote></details>

Yep, make sense to me to have another thorough checking. Removed the assert.
___
*[`tools/sgx/ra-tls/ra_tls_attest.c` line 163 at r1](https://reviewable.io/reviews/gramineproject/gramine/748#-N6qpPgzALVuTetNqcsb:-NAxCpKf59b_TIHqIduC:blckjz7) ([raw file](https://github.com/gramineproject/gramine/blob/ba056ab6031bed69ab5297df75b012d92aeb5bcb/tools/sgx/ra-tls/ra_tls_attest.c#L163)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Actually, Borys is right. This function cannot return `0`, so we can just return the error. See the function implementation here: https://os.mbed.com/teams/sandbox/code/mbedtls/docs/tip/pkwrite_8c_source.html#l00151

So this should be fine:
```
    if (pk_der_size_byte < 0)
        return pk_der_size_byte;
```
</blockquote></details>

Indeed, thanks for checking! Done.
___
*[`tools/sgx/ra-tls/ra_tls_verify_common.c` line 171 at r4](https://reviewable.io/reviews/gramineproject/gramine/748#-NAv0qmp1VF0ekFSmhzZ:-NAxCznq9MKyx1SHWxzx:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/4483dc5428848b72810abfb69228d9566b081e23/tools/sgx/ra-tls/ra_tls_verify_common.c#L171)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto (we can pass the error, let's do it)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-09-02 08:47 UTC, dimakuv submitted a review, later dismissed
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/748)* status: all files reviewed, 13 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[`tools/sgx/ra-tls/meson.build` line 16 at r3](https://reviewable.io/reviews/gramineproject/gramine/748#-N6s0Qwp9yNH89uNFece:-NAxNJF685avDTk0eoqK:b-fwg74q) ([raw file](https://github.com/gramineproject/gramine/blob/fa78335512c16a8414faaaf1569e1ba245c80365/tools/sgx/ra-tls/meson.build#L16)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Yep, make sense to me to have another thorough checking. Removed the assert.
</blockquote></details>

Could you also create the GitHub issue as I described?


<!-- Sent from Reviewable.io -->

2022-09-02 09:30 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/748)* status: all files reviewed, 13 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[`tools/sgx/ra-tls/meson.build` line 16 at r3](https://reviewable.io/reviews/gramineproject/gramine/748#-N6s0Qwp9yNH89uNFece:-NAxXPUi4UF7FnmQNG9H:b-bqfkzj) ([raw file](https://github.com/gramineproject/gramine/blob/fa78335512c16a8414faaaf1569e1ba245c80365/tools/sgx/ra-tls/meson.build#L16)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you also create the GitHub issue as I described?
</blockquote></details>

Created at https://github.com/gramineproject/gramine/issues/876.


<!-- Sent from Reviewable.io -->

2022-09-02 14:07 UTC, boryspoplawski requested changes
> Reviewed 3 of 4 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/748)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

___
*[`tools/sgx/ra-tls/ra_tls_attest.c` line 211 at r3](https://reviewable.io/reviews/gramineproject/gramine/748#-NAyWbJ-4aK3Luz08tFg:-NAyWbJ-4aK3Luz08tFh:bvqrouc) ([raw file](https://github.com/gramineproject/gramine/blob/fa78335512c16a8414faaaf1569e1ba245c80365/tools/sgx/ra-tls/ra_tls_attest.c#L211)):*
> ```C
>             goto out;
>     } else {
>         assert(elliptic_curve_group_id != MBEDTLS_ECP_DP_NONE);
> ```

Please leave the assert commented with a TODO (and link to the GH issue)


<!-- Sent from Reviewable.io -->

2022-09-02 15:52 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/748)* status: 7 of 8 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[`tools/sgx/ra-tls/ra_tls_attest.c` line 211 at r3](https://reviewable.io/reviews/gramineproject/gramine/748#-NAyWbJ-4aK3Luz08tFg:-NAytj2s1RfVIYEO9gOY:b-dtkds3) ([raw file](https://github.com/gramineproject/gramine/blob/fa78335512c16a8414faaaf1569e1ba245c80365/tools/sgx/ra-tls/ra_tls_attest.c#L211)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please leave the assert commented with a TODO (and link to the GH issue)
</blockquote></details>

Done, thanks!


<!-- Sent from Reviewable.io -->

2022-09-02 16:39 UTC, boryspoplawski submitted a review, later dismissed
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/748)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2022-09-05 07:59 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/748)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2022-09-05 08:00 UTC, dimakuv commented
Jenkins, test this please

2022-10-04 18:37 UTC, dimakuv approved these changes
> Reviewed 6 of 6 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/748)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/748#-N6s0fFz8kd5eFj4Snmk:-NDZHFe-77NiBtW9692C:b-br5vtx) (no related file):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Thanks for checking!
</blockquote></details>

FYI: I tested it again now, on the final rebased version. It works.

___


<!-- Sent from Reviewable.io -->

2022-10-04 18:38 UTC, dimakuv commented
Jenkins, test this please

2022-10-04 18:53 UTC, boryspoplawski approved these changes
> Reviewed 6 of 6 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/748)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-10-04 19:04 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/748)* status: all files reviewed, 1 unresolved discussion (waiting on @kailun-qin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/748#-NDZLbEK47jSUI_9rE1x:-NDZLbEK47jSUI_9rE1y:b47vbse) (no related file):*
I'm late to the game, sorry :( But why not just change RSA to ECDSA and be done?
Arguments for doing this instead of this PR:
- It's trivial and obviously works.
- We can choose a proper ECDSA version which is universally accepted as secure. We don't need (and shouldn't) leave this choice to the users.
- It doesn't add a new user API which we'll need to maintain and keep backwards-compatible.
- It doesn't add complexity to the code in a security-critical part.

Another high level argument for not leaving the crypto algo configurable is to just check how many serious vulnerabilities SSL/TLS had just because the algorithm was configurable.

___


<!-- Sent from Reviewable.io -->

2022-10-05 07:50 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/748)* status: all files reviewed, 1 unresolved discussion (waiting on @boryspoplawski and @kailun-qin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/748#-NDZLbEK47jSUI_9rE1x:-NDb5zLj1fK7E7-bZ12J:b-vim5xe) (no related file):*
> We don't need (and shouldn't) leave this choice to the users.

Ok, I agree with this argument.

> Another high level argument for not leaving the crypto algo configurable is to just check how many serious vulnerabilities SSL/TLS had just because the algorithm was configurable.

I agree with this argument too.

So in general, it makes sense to me -- we choose one universal ECDSA algo and use it in RA-TLS. This will simplify this PR and will remove the need for `RA_TLS_CERT_SIGNATURE_ALGO`. This should also be harmless because all modern TLS implementations detect the ECDSA algo used to sign the X.509 cert and use it.

@boryspoplawski @kailun-qin What do you think? By the way, do we have a crypto-algos expert here?

___


<!-- Sent from Reviewable.io -->

2022-10-05 14:10 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/748)* status: all files reviewed, 1 unresolved discussion (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/748#-NDZLbEK47jSUI_9rE1x:-NDcJePs3oNIlFi_4mnc:brtfup5) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> We don't need (and shouldn't) leave this choice to the users.

Ok, I agree with this argument.

> Another high level argument for not leaving the crypto algo configurable is to just check how many serious vulnerabilities SSL/TLS had just because the algorithm was configurable.

I agree with this argument too.

So in general, it makes sense to me -- we choose one universal ECDSA algo and use it in RA-TLS. This will simplify this PR and will remove the need for `RA_TLS_CERT_SIGNATURE_ALGO`. This should also be harmless because all modern TLS implementations detect the ECDSA algo used to sign the X.509 cert and use it.

@boryspoplawski @kailun-qin What do you think? By the way, do we have a crypto-algos expert here?
</blockquote></details>

Yeah, I agree w/ most of the arguments. My only question is - are there any use cases that specifically ask for/support only RSA-based certs or need some sort of flexibility?

The original ask (from https://github.com/gramineproject/gramine/issues/156) for adding this support was beacause "MSFT CCF only supports ECDSA based client certs for mTLS" (similar statements may hold for RSA in some other cases maybe?). Besides compatiblity, RSA does provide generally faster PK operations (e.g., signature verification in this case) at common security levels in terms of performance, which may benefit some usages.

___


<!-- Sent from Reviewable.io -->

2022-10-05 15:39 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/748)* status: all files reviewed, 1 unresolved discussion (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/748#-NDZLbEK47jSUI_9rE1x:-NDclfxu7PM8uCuko3UU:b-gm4skg) (no related file):*
> are there any use cases that specifically ask for/support only RSA-based certs

I don't think so. The whole world is rather moving away from RSA to ECC than the other way.

> Besides compatiblity

You don't want backwards compatibility in crypto protocols, usually the more things you support the higher the chance of including something weak on the list.

> RSA does provide generally faster PK operations (e.g., signature verification in this case)

Are you sure? RSA even in the best case needs a few long multiplications and modulos. With CRT trick you can bring the size down to `bitsize(max(p,q))`, but it's still quite a lot. ECC requires more operations, but on shorter numbers.

___


<!-- Sent from Reviewable.io -->

2022-10-08 06:54 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/748)* status: all files reviewed, 1 unresolved discussion (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/748#-NDZLbEK47jSUI_9rE1x:-NDqIq4_0jVAwpKrpwYT:befsuip) (no related file):*
> Are you sure? RSA even in the best case needs a few long multiplications and modulos. With CRT trick you can bring the size down to bitsize(max(p,q)), but it's still quite a lot. ECC requires more operations, but on shorter numbers.

I was talking particularly about *public key* operations (e.g., *signature verification*) at *common security levels*. When small public exponents are used (e.g., 65537), generally fewer modular multiplications are needed for RSA. Pls kindly refer to https://wiki.segger.com/Digital_Signature_-_RSA_vs_ECDSA#Performance or https://cryptopp.com/benchmarks.html for some benchmark results.

___


<!-- Sent from Reviewable.io -->

2022-10-09 21:06 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/748)* status: all files reviewed, 1 unresolved discussion (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/748#-NDZLbEK47jSUI_9rE1x:-NDyW3ez5kSWLgQObN8k:b-1iex76) (no related file):*
> I was talking particularly about public key operations (e.g., signature verification) at common security levels. When small public exponents are used (e.g., 65537), generally fewer modular multiplications are needed for RSA.

Yeah, that's what I means by "a few". e=65537 still requires something around 5 long multiplications. And yes, this is less than ECDSA, but ECDSA works on much smaller numbers, so this offsets part of the difference (but not necessarily enough to make up for the difference).

> Pls kindly refer to https://wiki.segger.com/Digital_Signature_-_RSA_vs_ECDSA#Performance or https://cryptopp.com/benchmarks.html for some benchmark results.

These seem to use pretty old hardware, but unfortunately I couldn't find any benchmarks on more modern CPUs. Anyways, it seems that for smaller keys RSA is indeed faster, but ECC scales better with more bits of security picked.

___


<!-- Sent from Reviewable.io -->

2022-10-10 10:58 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/748)* status: all files reviewed, 1 unresolved discussion (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/748#-NDZLbEK47jSUI_9rE1x:-NE0Va9rCBTWb7mfyDw6:b-z7ztmw) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> I was talking particularly about public key operations (e.g., signature verification) at common security levels. When small public exponents are used (e.g., 65537), generally fewer modular multiplications are needed for RSA.

Yeah, that's what I means by "a few". e=65537 still requires something around 5 long multiplications. And yes, this is less than ECDSA, but ECDSA works on much smaller numbers, so this offsets part of the difference (but not necessarily enough to make up for the difference).

> Pls kindly refer to https://wiki.segger.com/Digital_Signature_-_RSA_vs_ECDSA#Performance or https://cryptopp.com/benchmarks.html for some benchmark results.

These seem to use pretty old hardware, but unfortunately I couldn't find any benchmarks on more modern CPUs. Anyways, it seems that for smaller keys RSA is indeed faster, but ECC scales better with more bits of security picked.
</blockquote></details>

@mkow After some googling, I couldn't find any *definitive* conclusion whether ECDSA is indeed better in all areas than RSA. I'm still unsure whether we should really remove RSA support completely.

What if we replace the default to ECDSA, but still keep RSA? We can decrease the number of supported ciphers to just two -- RSA-3072 and ECDSA-384, and make ECDSA-384 default. Would it be a good compromise?

___


<!-- Sent from Reviewable.io -->

2022-10-10 19:18 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/748)* status: all files reviewed, 1 unresolved discussion (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/748#-NDZLbEK47jSUI_9rE1x:-NE2KDkz12SyQH2wBgQB:b-km85kt) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@mkow After some googling, I couldn't find any *definitive* conclusion whether ECDSA is indeed better in all areas than RSA. I'm still unsure whether we should really remove RSA support completely.

What if we replace the default to ECDSA, but still keep RSA? We can decrease the number of supported ciphers to just two -- RSA-3072 and ECDSA-384, and make ECDSA-384 default. Would it be a good compromise?
</blockquote></details>

But then we'd still need to have this configurable and expose a new API?

___


<!-- Sent from Reviewable.io -->

2022-10-11 14:45 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/748)* status: all files reviewed, 1 unresolved discussion (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/748#-NDZLbEK47jSUI_9rE1x:-NE5hW2Z8bmaaZmNHtSl:b-m88hux) (no related file):*
> The cipher version should be ECDSA-284.

Warning for whoever will be implementing this: typo, should be ECDSA-384 ;)

> The attester can use whatever key in general case. So if OE SDK uses ECDSA-256 as the key format, the Gramine verifier will still understand this key (given the change that was introduced in this PR for `ra_tls_verify_common.c`).

Hmm, I think the verifier code can't be ported to any other SDK easily, because the protocols differ. So, probably we should also accept only ECDSA-384 there so the attackers have smaller attack surface to exploit?

___


<!-- Sent from Reviewable.io -->

2022-10-11 16:14 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/748)* status: all files reviewed, 1 unresolved discussion (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/748#-NDZLbEK47jSUI_9rE1x:-NE6oYVb1sBZ5xIvO338:bv33435) (no related file):*
> Hmm, I think the verifier code can't be ported to any other SDK easily, because the protocols differ.

There is an ongoing effort (currently a bit under the radar) to harmonize all RA-TLS-like implementations on different runtimes. So different runtimes/SDKs *will* have the same protocol.

___


<!-- Sent from Reviewable.io -->

2022-10-11 16:28 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/748)* status: all files reviewed, 1 unresolved discussion (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/748#-NDZLbEK47jSUI_9rE1x:-NE6rrSk0KbD5Fda12UB:b-9pr9vu) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

So, I'd add this feature together with adding that common protocol, as it probably will change the code significantly. I don't see any use for other encryption algos in the current verifier if Gramine doesn't support them.
</blockquote></details>

Fair enough. Then I would just add the comment to fix that part in `ra_tls_verify_common.c`, once Gramine supports more than one cipher scheme.

@kailun-qin Do you agree with this proposal to switch **solely to ECDSA-384**? If yes, will you create a new PR, or should I work on this?

___


<!-- Sent from Reviewable.io -->

2022-10-20 07:46 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/748)* status: all files reviewed, 1 unresolved discussion (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/748#-NDZLbEK47jSUI_9rE1x:-NEoLSsIBwiny-Z_e6VP:b-5lw9ka) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Fair enough. Then I would just add the comment to fix that part in `ra_tls_verify_common.c`, once Gramine supports more than one cipher scheme.

@kailun-qin Do you agree with this proposal to switch **solely to ECDSA-384**? If yes, will you create a new PR, or should I work on this?
</blockquote></details>

Created a new PR at https://github.com/gramineproject/gramine/pull/994 to switch solely to ECDSA-384.

___


<!-- Sent from Reviewable.io -->

2022-10-25 17:00 UTC, closed without merging