[Docs] Change "GSC" page to "Container integration"
gramineproject/gramine pull request #749
Opened 2022-07-12 09:19 UTC by dimakuv

## Description of the changes 

We now have not only GSC, but also the Gramine Docker image hosted on DockerHub. Update our documentation to mention both tools and prepare for more tools/workflows in the future. Also, GSC was split from the core repository a long time ago and there is no need to emphasize that, so we rephrase its description.

## How to test this PR? 

N/A.

2022-07-12 10:04 UTC, boryspoplawski requested changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/749)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`Documentation/container-integration.rst` line 20 at r1](https://reviewable.io/reviews/gramineproject/gramine/749#-N6lqISU3yfsWpjkQMko:-N6lqISU3yfsWpjkQMkp:b-760lzz) ([raw file](https://github.com/gramineproject/gramine/blob/82244dd7cca837294a748e63b25b262c85669298/Documentation/container-integration.rst#L20)):*
> ```reStructuredText
> applications under Gramine. The only currently available Gramine image is based
> on Ubuntu 20.04. The only requirement on the host system is a Linux kernel
> version 5.11 or higher (with the in-kernel SGX driver).
> ```

I would remove parens, this is actually the most important part - if somebody had in-kernel SGX driver in 5.0 (e.g. manual port) that would work too.
Or even rephrase to: `The only requirement on the host system is a Linux kernel with in-kernel SGX driver (available from version 5.11 onward).`
___
*[`Documentation/container-integration.rst` line 30 at r1](https://reviewable.io/reviews/gramineproject/gramine/749#-N6lr2QbEFhEiolyLCu9:-N6lr2QbEFhEiolyLCuA:b-xta723) ([raw file](https://github.com/gramineproject/gramine/blob/82244dd7cca837294a748e63b25b262c85669298/Documentation/container-integration.rst#L30)):*
> ```reStructuredText
> 
>     docker run --device /dev/sgx_enclave \
>         --security-opt seccomp=unconfined \
> ```

Recommended way is to download our seccomp profile and use it.
And if users do not intend to use Linux PAL (non SGX), then they can just use default docker seccomp profile.
___
*[`Documentation/container-integration.rst` line 31 at r1](https://reviewable.io/reviews/gramineproject/gramine/749#-N6lqynI5bAJ3pNppDZq:-N6lqynI5bAJ3pNppDZr:b-pcalj5) ([raw file](https://github.com/gramineproject/gramine/blob/82244dd7cca837294a748e63b25b262c85669298/Documentation/container-integration.rst#L31)):*
> ```reStructuredText
>     docker run --device /dev/sgx_enclave \
>         --security-opt seccomp=unconfined \
>         -it --entrypoint /bin/bash gramineproject/gramine
> ```

You can remove `--entrypoint /bin/bash` it's default in this image.


<!-- Sent from Reviewable.io -->

2022-07-12 12:07 UTC, boryspoplawski requested changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/749)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv and @mkow)

___
*[`Documentation/container-integration.rst` line 35 at r2](https://reviewable.io/reviews/gramineproject/gramine/749#-N6mH_K78TpR6kyTIYtK:-N6mH_K78TpR6kyTIYtL:bc82zp3) ([raw file](https://github.com/gramineproject/gramine/blob/ff1f2c25f7d22abf0011a38aaf6ae78b9b6eab44/Documentation/container-integration.rst#L35)):*
> ```reStructuredText
> See
> https://gramine.readthedocs.io/projects/gsc/en/latest/#execute-with-linux-pal-instead-of-linux-sgx-pal
> for details.
> ```

This is link to GSC which talks about some GSC specific details. I would just put:
```
If you want to run :program:`gramine-direct` in addition to command:`gramine-sgx`,
then you should run Docker with a our custom seccomp profile using `--security-opt seccomp=<profile_file>`.
You can download the profile file from https://github.com/gramineproject/gramine/blob/master/scripts/docker_seccomp.json.
Alternatively you can disable seccomp completely (`--security-opt seccomp=unconfined`).
```


<!-- Sent from Reviewable.io -->

2022-07-12 12:11 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/749)* status: 2 of 3 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[`Documentation/container-integration.rst` line 35 at r2](https://reviewable.io/reviews/gramineproject/gramine/749#-N6mH_K78TpR6kyTIYtK:-N6mJUT_33HaGSYZoO2l:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/ff1f2c25f7d22abf0011a38aaf6ae78b9b6eab44/Documentation/container-integration.rst#L35)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This is link to GSC which talks about some GSC specific details. I would just put:
```
If you want to run :program:`gramine-direct` in addition to command:`gramine-sgx`,
then you should run Docker with a our custom seccomp profile using `--security-opt seccomp=<profile_file>`.
You can download the profile file from https://github.com/gramineproject/gramine/blob/master/scripts/docker_seccomp.json.
Alternatively you can disable seccomp completely (`--security-opt seccomp=unconfined`).
```
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2022-07-12 12:18 UTC, boryspoplawski reviewed
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/749)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)



<!-- Sent from Reviewable.io -->

2022-07-12 14:25 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/749)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2022-08-04 07:49 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/749)* status: 2 of 3 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/749#-N6mG6YL2bFqzZeyFIsN:-N8boYKV4JFMXUUmp7BO:b-3mvq4v) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Let me block this PR until we have a proper Gramine Docker image available.
</blockquote></details>

And the proper Gramine Docker image is publicly available: https://hub.docker.com/r/gramineproject/gramine. Rebased, ready for merge.

___


<!-- Sent from Reviewable.io -->

2022-08-04 12:00 UTC, boryspoplawski approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/749)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-08-04 12:04 UTC, merged