[Pal/Linux-SGX] Add `libsgx_dcap_quoteverify.so` dependency to DCAP-based libs
gramineproject/gramine pull request #75
Opened 2021-09-21 15:22 UTC by dimakuv

## Description of the changes 

This PR adds `libsgx_dcap_quoteverify.so` dependency to DCAP-based libs. This was missed in the `[Pal/Linux-SGX] Compile SGX tools with Meson` commit, even though the dependency was already baked in one of the meson files.

As an aside, the `ra-tls-mbedtls` and `ra-tls-secret-prov` examples got a bit stale, so I updated them as well. Surprisingly, we had the bug with `LD_LIBRARY_PATH` in those manifests for a long time, and noone noticed.

## How to test this PR? 

CI is enough for `ra-tls` examples.

Unfortunately, we don't have DCAP-enabled SGX machines in our Jenkins CI, so we can't test DCAP-based libraries (that's why the bug was missed in the previous commits). If you want to test, do it manually on a DCAP-enabled machine.

2021-09-21 16:21 UTC, woju submitted a review, later dismissed
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/75)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2021-09-21 19:03 UTC, mkow requested changes
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/75)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required) (waiting on @dimakuv)

___
*[-- commits, line 6 at r1](https://reviewable.io/reviews/gramineproject/gramine/75#-Mk8i_Vn9QbCdFxd123h):*
`meson` -> `Meson`
___
*[-- commits, line 13 at r1](https://reviewable.io/reviews/gramineproject/gramine/75#-Mk8ibbZ075l_4z5iVkK):*
> ```
> Graphine
> ```

Half-graphene, half-gramine? ;)


<!-- Sent from Reviewable.io -->

2021-09-21 23:59 UTC, boryspoplawski reviewed
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/75)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required) (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2021-09-22 07:19 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/75)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[-- commits, line 6 at r1](https://reviewable.io/reviews/gramineproject/gramine/75#-Mk8i_Vn9QbCdFxd123h):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`meson` -> `Meson`
</blockquote></details>

Done.
___
*[-- commits, line 13 at r1](https://reviewable.io/reviews/gramineproject/gramine/75#-Mk8ibbZ075l_4z5iVkK):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> Graphine
> ```

Half-graphene, half-gramine? ;)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-09-22 11:41 UTC, veenasai2 reviewed
I tested this PR. Ra-tls-secret-prov sample works fine for dcap attestation. Also, no build errors that we found earlier with -Ddcap=enabled option. Thanks.

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/75#-:-MkCHkaV0Oni2kw8__Ol:b-wwk95h)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2021-09-22 12:08 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/75)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2021-09-22 13:06 UTC, woju approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/75)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-09-22 13:22 UTC, merged