[Docs] Improve and unify Doxygen comments, part 3
gramineproject/gramine pull request #751
Opened 2022-07-12 22:35 UTC by mkow

## Description of the changes 

Final (hopefully) part of #420 and #439.

## How to test this PR? 

No functional changes intended.

2022-07-13 08:29 UTC, dimakuv requested changes
> Reviewed 18 of 18 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/751)* status: all files reviewed, 15 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

___
*[`pal/src/host/linux-sgx/pal_linux.h` line 180 at r1](https://reviewable.io/reviews/gramineproject/gramine/751#-N6qeEBo7BjqHKLvuz-0:-N6qeEBo7BjqHKLvuz-1:bgrvnrp) ([raw file](https://github.com/gramineproject/gramine/blob/f90113aaf06810a66df952c5c989d346704ad8a1/pal/src/host/linux-sgx/pal_linux.h#L180)):*
> ```objc
>  * \param  stream           Stream handle for sending and receiving messages.
>  * \param  my_report_data   User-defined data to embed into outgoing SGX report.
>  * \param  peer_report_data User-defined data expected in the incoming SGX report.
> ```

No 2 spaces
___
*[`pal/src/host/linux-sgx/pal_linux.h` line 192 at r1](https://reviewable.io/reviews/gramineproject/gramine/751#-N6qeGhp7s_3QQDTWKq5:-N6qeGhp7s_3QQDTWKq6:bgrvnrp) ([raw file](https://github.com/gramineproject/gramine/blob/f90113aaf06810a66df952c5c989d346704ad8a1/pal/src/host/linux-sgx/pal_linux.h#L192)):*
> ```objc
>  * \param  stream           Stream handle for sending and receiving messages.
>  * \param  my_report_data   User-defined data to embed into outgoing SGX report.
>  * \param  peer_report_data User-defined data expected in the incoming SGX report.
> ```

No 2 spaces
___
*[`tools/sgx/common/util.h` line 74 at r1](https://reviewable.io/reviews/gramineproject/gramine/751#-N6qeet98arR76kMuQ9M:-N6qeet98arR76kMuQ9N:bsf3fsz) ([raw file](https://github.com/gramineproject/gramine/blob/f90113aaf06810a66df952c5c989d346704ad8a1/tools/sgx/common/util.h#L74)):*
> ```objc
>  * \returns On success, pointer to the data buffer. If \p buffer was NULL, caller should free it.
>  *          On failure, NULL.
>  * \details If \a buffer is not NULL, \a size must contain valid buffer size.
> ```

Don't we want to have an empty line here?
___
*[`tools/sgx/common/util.h` line 103 at r1](https://reviewable.io/reviews/gramineproject/gramine/751#-N6qej3G3_6O-t5QlX39:-N6qej3G3_6O-t5QlX3A:bsf3fsz) ([raw file](https://github.com/gramineproject/gramine/blob/f90113aaf06810a66df952c5c989d346704ad8a1/tools/sgx/common/util.h#L103)):*
> ```objc
>  *
>  * \returns 0 on success, otherwise -1.
>  * \details Unless the string contains exactly 2 * buffer_size hexdigits, an error will be raised.
> ```

Don't we want to have an empty line here?
___
*[`tools/sgx/ra-tls/ra_tls.h` line 67 at r1](https://reviewable.io/reviews/gramineproject/gramine/751#-N6qervU5ygLx-RYi_mz:-N6qervU5ygLx-RYi_n-:b31s8jv) ([raw file](https://github.com/gramineproject/gramine/blob/f90113aaf06810a66df952c5c989d346704ad8a1/tools/sgx/ra-tls/ra_tls.h#L67)):*
> ```objc
>  * callback to allow for user-specific checks on SGX measurements reported in the SGX quote. If no
>  * callback is registered (or registered as NULL), then RA-TLS defaults to verifying SGX
>  * measurements against `RA_TLS_*` environment variables (if any).
> ```

Sometimes we have this `details` text before params, sometimes after, sometimes with `\details`, sometimes without. What is the guideline? Let's unify.
___
*[`tools/sgx/ra-tls/ra_tls.h` line 84 at r1](https://reviewable.io/reviews/gramineproject/gramine/751#-N6qf7rGDNKH6tWLBT8p:-N6qf7rGDNKH6tWLBT8q:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/f90113aaf06810a66df952c5c989d346704ad8a1/tools/sgx/ra-tls/ra_tls.h#L84)):*
> ```objc
>  * This callback must be registered via mbedtls_ssl_conf_verify(). All parameters required for
>  * the SGX quote, IAS attestation report verification, and/or DCAP quote verification  must be
>  * passed in the corresponding RA-TLS environment variables.
> ```

ditto
___
*[`tools/sgx/ra-tls/ra_tls.h` line 103 at r1](https://reviewable.io/reviews/gramineproject/gramine/751#-N6qf9mcDnr8qpAMHCti:-N6qf9mcDnr8qpAMHCtj:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/f90113aaf06810a66df952c5c989d346704ad8a1/tools/sgx/ra-tls/ra_tls.h#L103)):*
> ```objc
>  * OpenSSL callback for SSL_CTX_set_cert_verify_callback(). All parameters required for the SGX
>  * quote, IAS attestation report verification, and/or DCAP quote verification must be passed in the
>  * corresponding RA-TLS environment variables.
> ```

ditto
___
*[`tools/sgx/ra-tls/ra_tls.h` line 119 at r1](https://reviewable.io/reviews/gramineproject/gramine/751#-N6qfB6A43MXJ5ZieAvA:-N6qfB6A43MXJ5ZieAvB:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/f90113aaf06810a66df952c5c989d346704ad8a1/tools/sgx/ra-tls/ra_tls.h#L119)):*
> ```objc
>  * the SHA256 hash over the generated public key and retrieves an SGX quote with report_data equal
>  * to the calculated hash (this ties the generated certificate key to the SGX quote). Finally, it
>  * generates the X.509 self-signed certificate with this key and the SGX quote embedded.
> ```

ditto
___
*[`tools/sgx/ra-tls/ra_tls.h` line 134 at r1](https://reviewable.io/reviews/gramineproject/gramine/751#-N6qfCRnCg96RyfCQZZo:-N6qfCRnCg96RyfCQZZp:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/f90113aaf06810a66df952c5c989d346704ad8a1/tools/sgx/ra-tls/ra_tls.h#L134)):*
> ```objc
>  * The function behaves the same as ra_tls_create_key_and_crt() but generates key and certificate
>  * in the DER format. The function allocates memory for key and certificate; user is expected to
>  * free them after use.
> ```

ditto
___
*[`tools/sgx/ra-tls/secret_prov.h` line 38 at r1](https://reviewable.io/reviews/gramineproject/gramine/751#-N6qfEzCEo5odGjaJWdR:-N6qfEzCEo5odGjaJWdS:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/f90113aaf06810a66df952c5c989d346704ad8a1/tools/sgx/ra-tls/secret_prov.h#L38)):*
> ```objc
>  *
>  * This function can be called after an RA-TLS session is established via client-side call to
>  * secret_provision_start() or in the server-side callback secret_provision_cb_t().
> ```

ditto
___
*[`tools/sgx/ra-tls/secret_prov.h` line 54 at r1](https://reviewable.io/reviews/gramineproject/gramine/751#-N6qfGuHBNqgAVnFbLU7:-N6qfGuHBNqgAVnFbLU8:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/f90113aaf06810a66df952c5c989d346704ad8a1/tools/sgx/ra-tls/secret_prov.h#L54)):*
> ```objc
>  *
>  * This function can be called after an RA-TLS session is established via client-side call to
>  * secret_provision_start() or in the server-side callback secret_provision_cb_t().
> ```

ditto
___
*[`tools/sgx/ra-tls/secret_prov.h` line 72 at r1](https://reviewable.io/reviews/gramineproject/gramine/751#-N6qfIFL6l4O3TCCTLN1:-N6qfIFL6l4O3TCCTLN2:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/f90113aaf06810a66df952c5c989d346704ad8a1/tools/sgx/ra-tls/secret_prov.h#L72)):*
> ```objc
>  * secret_provision_start() or in the server-side callback secret_provision_cb_t(). Typically,
>  * application-specific protocol to provision secrets is implemented via secret_provision_read()
>  * and secret_provision_write(), and this function is called to finish secret provisioning.
> ```

ditto
___
*[`tools/sgx/ra-tls/secret_prov.h` line 87 at r1](https://reviewable.io/reviews/gramineproject/gramine/751#-N6qfJZvBHWMW-Tc68kI:-N6qfJZvBHWMW-Tc68kJ:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/f90113aaf06810a66df952c5c989d346704ad8a1/tools/sgx/ra-tls/secret_prov.h#L87)):*
> ```objc
>  * provisioning via secret_provision_start() which will obtain the secret from the server and
>  * save it in enclave memory. After that, the client can call this function to retrieve the
>  * secret from memory.
> ```

ditto
___
*[`tools/sgx/ra-tls/secret_prov.h` line 114 at r1](https://reviewable.io/reviews/gramineproject/gramine/751#-N6qfKuQ8PcBk5E4n8eA:-N6qfKuQ8PcBk5E4n8eB:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/f90113aaf06810a [...]

2022-07-13 10:11 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/751)* status: 16 of 18 files reviewed, 15 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`pal/src/host/linux-sgx/pal_linux.h` line 180 at r1](https://reviewable.io/reviews/gramineproject/gramine/751#-N6qeEBo7BjqHKLvuz-0:-N6qzJW71N73QuQ-OrF7:b8f96ft) ([raw file](https://github.com/gramineproject/gramine/blob/f90113aaf06810a66df952c5c989d346704ad8a1/pal/src/host/linux-sgx/pal_linux.h#L180)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

No 2 spaces
</blockquote></details>

Nice, I missed this probably because it already has 2 spaces, but on the wrong side :)
___
*[`pal/src/host/linux-sgx/pal_linux.h` line 192 at r1](https://reviewable.io/reviews/gramineproject/gramine/751#-N6qeGhp7s_3QQDTWKq5:-N6r0bmk1AhDqmbp9-zd:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/f90113aaf06810a66df952c5c989d346704ad8a1/pal/src/host/linux-sgx/pal_linux.h#L192)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

No 2 spaces
</blockquote></details>

Done.
___
*[`tools/sgx/common/util.h` line 74 at r1](https://reviewable.io/reviews/gramineproject/gramine/751#-N6qeet98arR76kMuQ9M:-N6r0eRXAohE7HYUEZbG:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/f90113aaf06810a66df952c5c989d346704ad8a1/tools/sgx/common/util.h#L74)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Don't we want to have an empty line here?
</blockquote></details>

Done.
___
*[`tools/sgx/common/util.h` line 103 at r1](https://reviewable.io/reviews/gramineproject/gramine/751#-N6qej3G3_6O-t5QlX39:-N6r0idR1N7LubafxRi4:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/f90113aaf06810a66df952c5c989d346704ad8a1/tools/sgx/common/util.h#L103)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Don't we want to have an empty line here?
</blockquote></details>

Done.
___
*[`tools/sgx/ra-tls/ra_tls.h` line 67 at r1](https://reviewable.io/reviews/gramineproject/gramine/751#-N6qervU5ygLx-RYi_mz:-N6r0k9X7ybHWFXMpffv:b-f97itj) ([raw file](https://github.com/gramineproject/gramine/blob/f90113aaf06810a66df952c5c989d346704ad8a1/tools/sgx/ra-tls/ra_tls.h#L67)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Sometimes we have this `details` text before params, sometimes after, sometimes with `\details`, sometimes without. What is the guideline? Let's unify.
</blockquote></details>

Yeah, but not sure how. Any preferences about the order?
I think I prefer: brief, params, returns, details.


<!-- Sent from Reviewable.io -->

2022-07-13 11:13 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/751)* status: all files reviewed, 11 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`tools/sgx/ra-tls/ra_tls.h` line 67 at r1](https://reviewable.io/reviews/gramineproject/gramine/751#-N6qervU5ygLx-RYi_mz:-N6rFbJSCK2XwjrqCipR:b-fub3k2) ([raw file](https://github.com/gramineproject/gramine/blob/f90113aaf06810a66df952c5c989d346704ad8a1/tools/sgx/ra-tls/ra_tls.h#L67)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Yeah, but not sure how. Any preferences about the order?
I think I prefer: brief, params, returns, details.
</blockquote></details>

My preferences:
- Order: brief, params, returns, details (so, same as yours).
- Keywords: no `\details` keyword, just the text (like in this code snippet).


<!-- Sent from Reviewable.io -->

2022-07-13 15:02 UTC, boryspoplawski requested changes
> Reviewed 16 of 18 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/751)* status: all files reviewed, 27 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`common/src/protected_files/protected_files.h` line 116 at r2](https://reviewable.io/reviews/gramineproject/gramine/751#-N6s0wCbAcYviqLDmsDf:-N6s0wCbAcYviqLDmsDg:bjqh39e) ([raw file](https://github.com/gramineproject/gramine/blob/b40bcea19d482f5098f6ed07f8dc5dce0b3ed2c5/common/src/protected_files/protected_files.h#L116)):*
> ```objc
>  * \param      key         AES-GCM key.
>  * \param      input       Plaintext data.
>  * \param      input_size  Size of \a input in bytes.
> ```

Please use `\p` for uniformity with the rest of the code.
ditto below
___
*[`common/src/protected_files/protected_files.h` line 134 at r2](https://reviewable.io/reviews/gramineproject/gramine/751#-N6s18fR381fizNqtj-g:-N6s18fR381fizNqtj-h:bheopa8) ([raw file](https://github.com/gramineproject/gramine/blob/b40bcea19d482f5098f6ed07f8dc5dce0b3ed2c5/common/src/protected_files/protected_files.h#L134)):*
> ```objc
>  * \param      input_size  Size of \a input in bytes.
>  * \param[out] output      Buffer for encrypted data (size: \a input_size).
>  * \param[out] mac         MAC computed for \a input and \a aad.
> ```

ditto for the whole comment ('\p')
___
*[`common/src/protected_files/protected_files.h` line 151 at r2](https://reviewable.io/reviews/gramineproject/gramine/751#-N6s1CdyEhHF8ioSvqIn:-N6s1CdyEhHF8ioSvqIo:bheopa8) ([raw file](https://github.com/gramineproject/gramine/blob/b40bcea19d482f5098f6ed07f8dc5dce0b3ed2c5/common/src/protected_files/protected_files.h#L151)):*
> ```objc
>  * \param      input       Encrypted data.
>  * \param      input_size  Size of \a input in bytes.
>  * \param[out] output      Buffer for decrypted data (size: \a input_size).
> ```

ditto for the whole comment ('\p')
___
*[`common/src/protected_files/protected_files.h` line 164 at r2](https://reviewable.io/reviews/gramineproject/gramine/751#-N6s1EseEozYVc2EFl_Z:-N6s1EseEozYVc2EFl__:bkeskcw) ([raw file](https://github.com/gramineproject/gramine/blob/b40bcea19d482f5098f6ed07f8dc5dce0b3ed2c5/common/src/protected_files/protected_files.h#L164)):*
> ```objc
>  *
>  * \param[out] buffer  Buffer to fill with random bytes.
>  * \param      size    Size of \a buffer in bytes.
> ```

ditto ('\p')
___
*[`common/src/protected_files/protected_files.h` line 207 at r2](https://reviewable.io/reviews/gramineproject/gramine/751#-N6s1daR0DJumj3FbKY7:-N6s1daR0DJumj3FbKY8:bkeskcw) ([raw file](https://github.com/gramineproject/gramine/blob/b40bcea19d482f5098f6ed07f8dc5dce0b3ed2c5/common/src/protected_files/protected_files.h#L207)):*
> ```objc
>  *
>  * \param      handle           Open underlying file handle.
>  * \param      path             Path to the file. If NULL and \a create is false, don't check path
> ```

ditto ('\p')
___
*[`common/src/protected_files/protected_files.h` line 259 at r2](https://reviewable.io/reviews/gramineproject/gramine/751#-N6s1a-38DWAW6_dH15l:-N6s1a-38DWAW6_dH15m:bkeskcw) ([raw file](https://github.com/gramineproject/gramine/blob/b40bcea19d482f5098f6ed07f8dc5dce0b3ed2c5/common/src/protected_files/protected_files.h#L259)):*
> ```objc
>  *
>  * \param      pf    PF context.
>  * \param[out] size  Data size of \a pf.
> ```

ditto ('\p')
___
*[`tools/sgx/common/ias.h` line 55 at r2](https://reviewable.io/reviews/gramineproject/gramine/751#-N6s33BA9Pa0sq_cJQ8h:-N6s33BB4pRQX8eAmI6V:bhr84t6) ([raw file](https://github.com/gramineproject/gramine/blob/b40bcea19d482f5098f6ed07f8dc5dce0b3ed2c5/tools/sgx/common/ias.h#L55)):*
> ```objc
>  * \param context      IAS context returned by ias_init().
>  * \param quote        Binary quote data blob.
>  * \param quote_size   Size of \a quote.
> ```

ditto  ('\p')
___
*[`tools/sgx/common/ias.h` line 78 at r2](https://reviewable.io/reviews/gramineproject/gramine/751#-N6s35iCAtdzChsEOgc3:-N6s35iCAtdzChsEOgc4:bkeskcw) ([raw file](https://github.com/gramineproject/gramine/blob/b40bcea19d482f5098f6ed07f8dc5dce0b3ed2c5/tools/sgx/common/ias.h#L78)):*
> ```objc
>  * \param      context           IAS context returned by ias_init().
>  * \param      quote             Binary quote data blob.
>  * \param      quote_size        Size of \a quote.
> ```

ditto ('\p')
___
*[`tools/sgx/common/ias.h` line 91 at r2](https://reviewable.io/reviews/gramineproject/gramine/751#-N6s394H80PeEPALHPiT:-N6s394H80PeEPALHPiU:bheopa8) ([raw file](https://github.com/gramineproject/gramine/blob/b40bcea19d482f5098f6ed07f8dc5dce0b3ed2c5/tools/sgx/common/ias.h#L91)):*
> ```objc
>  * This version of the function is convenient for library usage. This function allocates buffers
>  * for IAS contents and passes them to caller via \a report_data_ptr, \a sig_data_ptr and
>  * \a cert_data_ptr. The caller is responsible for freeing them.
> ```

ditto for the whole comment ('\p')
___
*[`tools/sgx/common/ias.h` line 107 at r2](https://reviewable.io/reviews/gramineproject/gramine/751#-N6s2xxwDnC88Kui3O2J:-N6s2xxwDnC88Kui3O2K:bheopa8) ([raw file](https://github.com/gramineproject/gramine/blob/b40bcea19d482f5098f6ed07f8dc5dce0b3ed2c5/tools/sgx/common/ias.h#L107)):*
> ```objc
>  *
>  * \param ias_report           IAS attestation verification report.
>  * \param ias_report_size      Size of \a ias_report in bytes.
> ```

ditto for the whole comment ('\p')
___
*[`tools/sgx/common/ias.c` line 72 at r2](https://reviewable.io/reviews/gramineproject/gramine/751#-N6s2vbiDKXSJDDeSXZV:-N6s2vbiDKXSJDDeSXZW:bkeskcw) ([raw file](https://github.com/gramineproject/gramine/blob/b40bcea19d482f5098f6ed07f8dc5dce0b3ed2c5/tools/sgx/common/ias.c#L72)):*
> ```C
>  *
>  * \param      src  NULL-terminated URL-encoded input.
>  * \param[out] dst  Buffer to write decoded output to. Can be the same as \a src.
> ```

ditto ('\p')
___
*[`tools/sgx/common/ias.c` line 110 at r2](https://reviewable.io/reviews/gramineproject/gramine/751#-N6s3C6JDEhL1hNZr-8X:-N6s3C6JDEhL1hNZr-8Y:bheopa8) ([raw file](https://github.com/gramineproject/gramine/blob/b40bcea19d482f5098f6ed07f8dc5dce0b3ed2c5/tools/sgx/common/ias.c#L110)):*
> ```C
>  *
>  * \param buffer   Single HTTP header.
>  * \param size     Together with \a count a size of \a buffer.
> ```

ditto for the whole comment ('\p')
___
*[`tools/sgx/common/ias.c` line 169 at r2](https://reviewable.io/reviews/gramineproject/gramine/751#-N6s3DvU0524e2z0qfqO:-N6s3DvU0524e2z0qfqP:bheopa8) ([raw file](https://github.com/gramineproject/gramine/blob/b40bcea19d482f5098f6ed07f8dc5dce0b3ed2c5/tools/sgx/common/ias.c#L169)):*
> ```C
>  *
>  * \param buffer   Chunk containing HTTP body.
>  * \param size     Together with \a count a size of \a buffer.
> ```

ditto for the whole comment ('\p')
___
*[`tools/sgx/common/quote.h` line 18 at r2](https://reviewable.io/reviews/gramineproject/gramine/751#-N6s3GDw-uUU4E9UOhO9:-N6s3GDw-uUU4E9UOhOA:bkeskcw) ([raw file](https://github.com/gramineproject/gramine/blob/b40bcea19d482f5098f6ed07f8dc5dce0b3ed2c5/tools/sgx/common/quote.h#L18)):*
> ```objc
>  * \param quote_data  Buffer with quote data. This can be a full quote (sgx_quote_t) or a quote
>  *                    from IAS attestation report (which is missing signature fields).
>  * \param quote_size  Size of \a quote_data in bytes.
> ```

ditto ('\p')
___
*[`tools/sgx/common/util.h` line 75 at r2](https://reviewable.io/reviews/gramineproject/gramine/751#-N6s3QLk16eFBpzSpbcA:-N6s3QLk16eFBpzSpbcB:bheopa8) ([raw file](https://github.com/gramineproject/gramine/blob/b40bcea19d482f5098f6ed07f8dc5dce0b3ed2c5/tools/sgx/common/util.h#L75)):*
> ```objc
>  *          On failure, NULL.
>  *
>  * \details If \a buffer is not NULL, \a size must contain valid buffer size.
> ```

ditto for the whole comment ('\p' [...]

2022-07-14 19:16 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/751)* status: 5 of 21 files reviewed, 27 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[`common/src/protected_files/protected_files.h` line 116 at r2](https://reviewable.io/reviews/gramineproject/gramine/751#-N6s0wCbAcYviqLDmsDf:-N6wVRtq-bbLGFHtVtKb:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b40bcea19d482f5098f6ed07f8dc5dce0b3ed2c5/common/src/protected_files/protected_files.h#L116)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please use `\p` for uniformity with the rest of the code.
ditto below
</blockquote></details>

Done.
___
*[`common/src/protected_files/protected_files.h` line 134 at r2](https://reviewable.io/reviews/gramineproject/gramine/751#-N6s18fR381fizNqtj-g:-N6wVSvs6iRJNEX7m2n9:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b40bcea19d482f5098f6ed07f8dc5dce0b3ed2c5/common/src/protected_files/protected_files.h#L134)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto for the whole comment ('\p')
</blockquote></details>

Done.
___
*[`common/src/protected_files/protected_files.h` line 151 at r2](https://reviewable.io/reviews/gramineproject/gramine/751#-N6s1CdyEhHF8ioSvqIn:-N6wVTZa0WHztq1Yeexl:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b40bcea19d482f5098f6ed07f8dc5dce0b3ed2c5/common/src/protected_files/protected_files.h#L151)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto for the whole comment ('\p')
</blockquote></details>

Done.
___
*[`common/src/protected_files/protected_files.h` line 164 at r2](https://reviewable.io/reviews/gramineproject/gramine/751#-N6s1EseEozYVc2EFl_Z:-N6wVUCx4rGPe2ax4dzX:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b40bcea19d482f5098f6ed07f8dc5dce0b3ed2c5/common/src/protected_files/protected_files.h#L164)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto ('\p')
</blockquote></details>

Done.
___
*[`common/src/protected_files/protected_files.h` line 207 at r2](https://reviewable.io/reviews/gramineproject/gramine/751#-N6s1daR0DJumj3FbKY7:-N6wVUjb0kGCneQ444yN:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b40bcea19d482f5098f6ed07f8dc5dce0b3ed2c5/common/src/protected_files/protected_files.h#L207)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto ('\p')
</blockquote></details>

Done.
___
*[`common/src/protected_files/protected_files.h` line 259 at r2](https://reviewable.io/reviews/gramineproject/gramine/751#-N6s1a-38DWAW6_dH15l:-N6wVVGm2pM4BG_0gTSJ:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b40bcea19d482f5098f6ed07f8dc5dce0b3ed2c5/common/src/protected_files/protected_files.h#L259)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto ('\p')
</blockquote></details>

Done.
___
*[`tools/sgx/common/ias.h` line 55 at r2](https://reviewable.io/reviews/gramineproject/gramine/751#-N6s33BA9Pa0sq_cJQ8h:-N6wVWLN429Gt0WR1rAG:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b40bcea19d482f5098f6ed07f8dc5dce0b3ed2c5/tools/sgx/common/ias.h#L55)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto  ('\p')
</blockquote></details>

Done.
___
*[`tools/sgx/common/ias.h` line 78 at r2](https://reviewable.io/reviews/gramineproject/gramine/751#-N6s35iCAtdzChsEOgc3:-N6wVWsz6NabrcJ9chI7:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b40bcea19d482f5098f6ed07f8dc5dce0b3ed2c5/tools/sgx/common/ias.h#L78)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto ('\p')
</blockquote></details>

Done.
___
*[`tools/sgx/common/ias.h` line 91 at r2](https://reviewable.io/reviews/gramineproject/gramine/751#-N6s394H80PeEPALHPiT:-N6wVXpj3JItbryriFJv:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b40bcea19d482f5098f6ed07f8dc5dce0b3ed2c5/tools/sgx/common/ias.h#L91)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto for the whole comment ('\p')
</blockquote></details>

Done.
___
*[`tools/sgx/common/ias.h` line 107 at r2](https://reviewable.io/reviews/gramineproject/gramine/751#-N6s2xxwDnC88Kui3O2J:-N6wVYPt7IxmCiREGWvQ:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b40bcea19d482f5098f6ed07f8dc5dce0b3ed2c5/tools/sgx/common/ias.h#L107)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto for the whole comment ('\p')
</blockquote></details>

Done.
___
*[`tools/sgx/common/ias.c` line 72 at r2](https://reviewable.io/reviews/gramineproject/gramine/751#-N6s2vbiDKXSJDDeSXZV:-N6wVZ0FB_d64HQBbeqX:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b40bcea19d482f5098f6ed07f8dc5dce0b3ed2c5/tools/sgx/common/ias.c#L72)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto ('\p')
</blockquote></details>

Done.
___
*[`tools/sgx/common/ias.c` line 110 at r2](https://reviewable.io/reviews/gramineproject/gramine/751#-N6s3C6JDEhL1hNZr-8X:-N6wVZbo1xi0ez0hFQIn:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b40bcea19d482f5098f6ed07f8dc5dce0b3ed2c5/tools/sgx/common/ias.c#L110)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto for the whole comment ('\p')
</blockquote></details>

Done.
___
*[`tools/sgx/common/ias.c` line 169 at r2](https://reviewable.io/reviews/gramineproject/gramine/751#-N6s3DvU0524e2z0qfqO:-N6wV_qaDNZCtaFQJIIp:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b40bcea19d482f5098f6ed07f8dc5dce0b3ed2c5/tools/sgx/common/ias.c#L169)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto for the whole comment ('\p')
</blockquote></details>

Done.
___
*[`tools/sgx/common/quote.h` line 18 at r2](https://reviewable.io/reviews/gramineproject/gramine/751#-N6s3GDw-uUU4E9UOhO9:-N6wVd0s0qKf4AdLNLod:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b40bcea19d482f5098f6ed07f8dc5dce0b3ed2c5/tools/sgx/common/quote.h#L18)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto ('\p')
</blockquote></details>

Done.
___
*[`tools/sgx/common/util.h` line 75 at r2](https://reviewable.io/reviews/gramineproject/gramine/751#-N6s3QLk16eFBpzSpbcA:-N6wVdec9-9l_QRxydm5:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b40bcea19d482f5098f6ed07f8dc5dce0b3ed2c5/tools/sgx/common/util.h#L75)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto for the whole comment ('\p')
</blockquote></details>

Done.
___
*[`tools/sgx/ra-tls/ra_tls.h` line 67 at r1](https://reviewable.io/reviews/gramineproject/gramine/751#-N6qervU5ygLx-RYi_mz:-N6wVi7c3kfwM_lR1dwS:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/f90113aaf06810a66df952c5c989d346704ad8a1/tools/sgx/ra-tls/ra_tls.h#L67)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

+1 to @dimakuv (I prefer the same)
</blockquote></details>

Done.
___
*[`tools/sgx/ra-tls/ra_tls.h` line 84 at r1](https://reviewable.io/reviews/gramineproject/gramine/751#-N6qf7rGDNKH6tWLBT8p:-N6wVjO_5sQptys-Q2I9:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/f90113aaf06 [...]

2022-07-14 19:23 UTC, boryspoplawski submitted a review, later dismissed
> Reviewed 16 of 16 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/751)* status: all files reviewed, 11 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2022-07-15 06:46 UTC, dimakuv requested changes
> Reviewed 15 of 16 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/751)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`tools/sgx/common/quote.h` line 36 at r3](https://reviewable.io/reviews/gramineproject/gramine/751#-N7-abfgCjwWHpo0d5Qb:-N7-abfgCjwWHpo0d5Qc:bxdpprn) ([raw file](https://github.com/gramineproject/gramine/blob/aa66ca01b9f73dbb70f0349dd962e4fc833f2ffe/tools/sgx/common/quote.h#L36)):*
> ```objc
>  * If \p expected_as_str is true, then \p mr_signer, \p mr_enclave and \p report_data are treated
>  * as hex strings, and \p isv_prod_id and a isv_svn are treated as decimal strings. This is
>  * convenient for command-line utilities.
> ```

This should go after `\returns`.

Since this is the only comment, I can fix it during final rebase.


<!-- Sent from Reviewable.io -->

2022-07-15 06:55 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/751)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

___
*[`tools/sgx/common/quote.h` line 36 at r3](https://reviewable.io/reviews/gramineproject/gramine/751#-N7-abfgCjwWHpo0d5Qb:-N7-c4Re6dtxfo5xmsLo:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/aa66ca01b9f73dbb70f0349dd962e4fc833f2ffe/tools/sgx/common/quote.h#L36)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This should go after `\returns`.

Since this is the only comment, I can fix it during final rebase.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2022-07-15 12:22 UTC, boryspoplawski approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/751)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-07-15 12:49 UTC, merged