Override `argv[0]` with pathname in `execve`
gramineproject/gramine pull request #754
Opened 2022-07-13 17:37 UTC by aneessahib

`pathname` and `argv[0]` are supposed to identical. At times `pathname` carries the whole absolute path, while argv[0] only has the relative path, causing trouble to some interpreters like `/bin/sh` in correctly locating the executable. This fix will by default override `argv[0[` with `pathname`, and this is also coherent with manpages - https://man7.org/linux/man-pages/man2/execve.2.html

2022-07-13 18:14 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/754)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @aneessahib)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/754#-N6skupw4DDv1efQSKa1:-N6skupw4DDv1efQSKa2:bexmw1w) (no related file):*
1. Please read our coding guidelines.
2. This PR is incorrect. This is not how Linux works (it does something similar only for interpreter scripts).

___


<!-- Sent from Reviewable.io -->

2022-07-14 08:01 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/754)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/gramineproject/gramine/754#-N6vhh9bD4z3FI2QMdXd):*
This message is wrong. I would say this:
```
[LibOS] Override `argv[0]` with file pathname for interpreter scripts

According to POSIX, if the pathname argument of `execve()` specifies
an interpreter script, then interpreter will be invoked with the following
arguments:

    interpreter [optional-arg] pathname arg...

where `pathname` is the pathname of the file specified as the first argument of
`execve()`, and `arg...` is the series of words pointed to by the `argv` argument
of `execve()`, starting at `argv[1]`.
```
___
*[`-- commits` line 3 at r2](https://reviewable.io/reviews/gramineproject/gramine/754#-N6vhUSC91M_W8_XlLQf):*
You forgot to add your Signed-off-by.
___
*[`libos/src/libos_rtld.c` line 582 at r2](https://reviewable.io/reviews/gramineproject/gramine/754#-N6vgOow41NlzlAKcKss:-N6vgOow41NlzlAKcKst:brah06w) ([raw file](https://github.com/gramineproject/gramine/blob/7b303f9e34ef1bd353ceea8cc6cbe8911081c83a/libos/src/libos_rtld.c#L582)):*
> ```C
> /* Note that `**out_new_argv` is allocated as a single object -- a concatenation of all argv
>  * strings; caller of this function should do a single free(**out_new_argv). */
> static int load_and_check_shebang(struct libos_handle* file, char** argv,
> ```

We should also add a new argument here, `char* argv0` -- it will be used instead of `argv[0]`. See also my other comments.
___
*[`libos/src/libos_rtld.c` line 637 at r2](https://reviewable.io/reviews/gramineproject/gramine/754#-N6vfREl89XRic7iOvQJ:-N6vfREl89XRic7iOvQK:b-bbs3bw) ([raw file](https://github.com/gramineproject/gramine/blob/7b303f9e34ef1bd353ceea8cc6cbe8911081c83a/libos/src/libos_rtld.c#L637)):*
> ```C
>     }
>     for (char** a = argv; *a; a++) {
>         new_argv_bytes += strlen(*a) + 1;
> ```

You should move your logic here. Smth like:
```
        new_argv_bytes += strlen(new_argv_cnt == 0 ? argv0 : *a) + 1;
```
___
*[`libos/src/libos_rtld.c` line 666 at r2](https://reviewable.io/reviews/gramineproject/gramine/754#-N6vhG800CX5qnXUqM-x:-N6vhG800CX5qnXUqM-y:b7a2l0k) ([raw file](https://github.com/gramineproject/gramine/blob/7b303f9e34ef1bd353ceea8cc6cbe8911081c83a/libos/src/libos_rtld.c#L666)):*
> ```C
>     for (char** a = argv; *a; a++) {
>         size_t size = strlen(*a) + 1;
>         memcpy(new_argv_ptr, *a, size);
> ```

You should move your logic here. Smth like:
```
        size_t size = strlen(new_argv_idx == 0 ? argv0 : *a) + 1;
        memcpy(new_argv_ptr, new_argv_idx == 0 ? argv0 : *a, size);
```
___
*[`libos/src/libos_rtld.c` line 697 at r2](https://reviewable.io/reviews/gramineproject/gramine/754#-N6vh2jW9GzcX87LWqY7:-N6vh2jW9GzcX87LWqY8:b86wfq) ([raw file](https://github.com/gramineproject/gramine/blob/7b303f9e34ef1bd353ceea8cc6cbe8911081c83a/libos/src/libos_rtld.c#L697)):*
> ```C
>     size_t curr_argv_bytes = 0, curr_argv_cnt = 0;
>     for (const char** a = argv; *a; a++) {
>         curr_argv_bytes += strlen(curr_argv_cnt == 0 ? path: *a) + 1;
> ```

As Borys mentions, this is wrong. This special logic is only about shebangs (scripts), so it should be moved to another func.
___
*[`libos/src/libos_rtld.c` line 716 at r2](https://reviewable.io/reviews/gramineproject/gramine/754#-N6vhAgg4k7nzZ9PXtiM:-N6vhAgg4k7nzZ9PXtiN:b86wfq) ([raw file](https://github.com/gramineproject/gramine/blob/7b303f9e34ef1bd353ceea8cc6cbe8911081c83a/libos/src/libos_rtld.c#L716)):*
> ```C
>     for (const char** a = argv; *a; a++) {
>         size_t size = strlen(curr_argv_idx == 0 ? path: *a) + 1;
>         memcpy(curr_argv_ptr, curr_argv_idx == 0 ? path: *a, size);
> ```

As Borys mentions, this is wrong. This special logic is only about shebangs (scripts), so it should be moved to another func.
___
*[`libos/src/libos_rtld.c` line 756 at r2](https://reviewable.io/reviews/gramineproject/gramine/754#-N6vghcf71sk1__xzYsR:-N6vghcf71sk1__xzYsS:b-mu3rov) ([raw file](https://github.com/gramineproject/gramine/blob/7b303f9e34ef1bd353ceea8cc6cbe8911081c83a/libos/src/libos_rtld.c#L756)):*
> ```C
> 
>         char** new_argv = NULL;
>         ret = load_and_check_shebang(file, curr_argv, &new_argv);
> ```

You should introduce a new argument `argv0` (see my other comment).

And here you'll change like this: `load_and_check_shebang(file, depth > 1 ? curr_argv[0] : path, curr_argv, &new_argv)`


<!-- Sent from Reviewable.io -->

2022-07-14 18:19 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/754)* status: 0 of 1 files reviewed, 9 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/754#-N6skupw4DDv1efQSKa1:-N6xn0fuCIQAl9xIJlkm:b-896fix) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

1. Please read our coding guidelines.
2. This PR is incorrect. This is not how Linux works (it does something similar only for interpreter scripts).
</blockquote></details>

Done.

___
___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/gramineproject/gramine/754#-N6vhh9bD4z3FI2QMdXd):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This message is wrong. I would say this:
```
[LibOS] Override `argv[0]` with file pathname for interpreter scripts

According to POSIX, if the pathname argument of `execve()` specifies
an interpreter script, then interpreter will be invoked with the following
arguments:

    interpreter [optional-arg] pathname arg...

where `pathname` is the pathname of the file specified as the first argument of
`execve()`, and `arg...` is the series of words pointed to by the `argv` argument
of `execve()`, starting at `argv[1]`.
```
</blockquote></details>

Done.
___
*[`-- commits` line 3 at r2](https://reviewable.io/reviews/gramineproject/gramine/754#-N6vhUSC91M_W8_XlLQf):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You forgot to add your Signed-off-by.
</blockquote></details>

Done.
___
*[`libos/src/libos_rtld.c` line 582 at r2](https://reviewable.io/reviews/gramineproject/gramine/754#-N6vgOow41NlzlAKcKss:-N6xspnH3lHKA9ptOoPi:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/7b303f9e34ef1bd353ceea8cc6cbe8911081c83a/libos/src/libos_rtld.c#L582)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We should also add a new argument here, `char* argv0` -- it will be used instead of `argv[0]`. See also my other comments.
</blockquote></details>

Done.
___
*[`libos/src/libos_rtld.c` line 637 at r2](https://reviewable.io/reviews/gramineproject/gramine/754#-N6vfREl89XRic7iOvQJ:-N6xss2oC0w2QoXvonLI:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/7b303f9e34ef1bd353ceea8cc6cbe8911081c83a/libos/src/libos_rtld.c#L637)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You should move your logic here. Smth like:
```
        new_argv_bytes += strlen(new_argv_cnt == 0 ? argv0 : *a) + 1;
```
</blockquote></details>

Done.
___
*[`libos/src/libos_rtld.c` line 666 at r2](https://reviewable.io/reviews/gramineproject/gramine/754#-N6vhG800CX5qnXUqM-x:-N6xsstC1E8skrMPPoC4:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/7b303f9e34ef1bd353ceea8cc6cbe8911081c83a/libos/src/libos_rtld.c#L666)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You should move your logic here. Smth like:
```
        size_t size = strlen(new_argv_idx == 0 ? argv0 : *a) + 1;
        memcpy(new_argv_ptr, new_argv_idx == 0 ? argv0 : *a, size);
```
</blockquote></details>

Done.
___
*[`libos/src/libos_rtld.c` line 697 at r2](https://reviewable.io/reviews/gramineproject/gramine/754#-N6vh2jW9GzcX87LWqY7:-N6xstmd0pirfz9gzwDD:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/7b303f9e34ef1bd353ceea8cc6cbe8911081c83a/libos/src/libos_rtld.c#L697)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

As Borys mentions, this is wrong. This special logic is only about shebangs (scripts), so it should be moved to another func.
</blockquote></details>

Done.
___
*[`libos/src/libos_rtld.c` line 716 at r2](https://reviewable.io/reviews/gramineproject/gramine/754#-N6vhAgg4k7nzZ9PXtiM:-N6xsueE4FoX2H5kWmQR:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/7b303f9e34ef1bd353ceea8cc6cbe8911081c83a/libos/src/libos_rtld.c#L716)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

As Borys mentions, this is wrong. This special logic is only about shebangs (scripts), so it should be moved to another func.
</blockquote></details>

Done.
___
*[`libos/src/libos_rtld.c` line 756 at r2](https://reviewable.io/reviews/gramineproject/gramine/754#-N6vghcf71sk1__xzYsR:-N6xvxbw76heeLqvIvS9:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/7b303f9e34ef1bd353ceea8cc6cbe8911081c83a/libos/src/libos_rtld.c#L756)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You should introduce a new argument `argv0` (see my other comment).

And here you'll change like this: `load_and_check_shebang(file, depth > 1 ? curr_argv[0] : path, curr_argv, &new_argv)`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-14 20:08 UTC, boryspoplawski requested changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/754)* status: all files reviewed, 15 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib and @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/754#-N6skupw4DDv1efQSKa1:-N6yHXsvArnReii6gEcC:b507k3f) (no related file):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Also please test your changes before submitting them.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/754#-N6yH0kY52x1J3sn5uQP:-N6yH0kY52x1J3sn5uQQ:b5bjeiz) (no related file):*
Please modify `libos/test/regression/exec_script.c` test so that `argv[0]` differs from `pathname` to test this PR.

___
___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/gramineproject/gramine/754#-N6vhh9bD4z3FI2QMdXd):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done.
___
*[`libos/src/libos_rtld.c` line 583 at r3](https://reviewable.io/reviews/gramineproject/gramine/754#-N6yDHmQB5cpyL-NmWhM:-N6yDHmQB5cpyL-NmWhN:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/cbe1ee14a605eab0a2a0949ae3381f4ea1cea7c2/libos/src/libos_rtld.c#L583)):*
> ```C
>  * strings; caller of this function should do a single free(**out_new_argv). */
> static int load_and_check_shebang(struct libos_handle* file, char** argv,
>                                   const char* argv0, char*** out_new_argv) {
> ```





_Suggestion:_
```C
static int load_and_check_shebang(struct libos_handle* file, const char* pathname, char** argv,
                                  char*** out_new_argv) {
```
___
*[`libos/src/libos_rtld.c` line 637 at r3](https://reviewable.io/reviews/gramineproject/gramine/754#-N6yHOgo2HlZ88JpL7ba:-N6yHOgo2HlZ88JpL7bb:b-40kih8) ([raw file](https://github.com/gramineproject/gramine/blob/cbe1ee14a605eab0a2a0949ae3381f4ea1cea7c2/libos/src/libos_rtld.c#L637)):*
> ```C
>     }
>     for (char** a = argv; *a; a++) {
>         new_argv_bytes += strlen(new_argv_cnt == 0 ? argv0 : *a) + 1;
> ```

This is wrong



_Suggestion:_
```C
a == argv
```
___
*[`libos/src/libos_rtld.c` line 637 at r3](https://reviewable.io/reviews/gramineproject/gramine/754#-N6yJgIOCClEzf2IC1Ri:-N6yJgIOCClEzf2IC1Rj:bn1apgh) ([raw file](https://github.com/gramineproject/gramine/blob/cbe1ee14a605eab0a2a0949ae3381f4ea1cea7c2/libos/src/libos_rtld.c#L637)):*
> ```C
>     }
>     for (char** a = argv; *a; a++) {
>         new_argv_bytes += strlen(new_argv_cnt == 0 ? argv0 : *a) + 1;
> ```

This won't work if `*argv == NULL`
___
*[`libos/src/libos_rtld.c` line 665 at r3](https://reviewable.io/reviews/gramineproject/gramine/754#-N6yHfj-32_hsGsmSM9J:-N6yHfj-32_hsGsmSM9K:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/cbe1ee14a605eab0a2a0949ae3381f4ea1cea7c2/libos/src/libos_rtld.c#L665)):*
> ```C
>     }
>     for (char** a = argv; *a; a++) {
>         size_t size = strlen(new_argv_idx == 0 ? argv0 : *a) + 1;
> ```

ditto



_Suggestion:_
```C
a == argv
```
___
*[`libos/src/libos_rtld.c` line 666 at r3](https://reviewable.io/reviews/gramineproject/gramine/754#-N6yHjNW1zTpZBYyD7PL:-N6yHjNW1zTpZBYyD7PM:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/cbe1ee14a605eab0a2a0949ae3381f4ea1cea7c2/libos/src/libos_rtld.c#L666)):*
> ```C
>     for (char** a = argv; *a; a++) {
>         size_t size = strlen(new_argv_idx == 0 ? argv0 : *a) + 1;
>         memcpy(new_argv_ptr, new_argv_idx == 0 ? argv0 : *a, size);
> ```

ditto



_Suggestion:_
```C
a == argv
```
___
*[`libos/src/libos_rtld.c` line 756 at r3](https://reviewable.io/reviews/gramineproject/gramine/754#-N6yFY6Z85ffuPcMN4eV:-N6yFY6Z85ffuPcMN4eW:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/cbe1ee14a605eab0a2a0949ae3381f4ea1cea7c2/libos/src/libos_rtld.c#L756)):*
> ```C
> 
>         char** new_argv = NULL;
>         ret = load_and_check_shebang(file, curr_argv, depth > 1? curr_argv[0] : path, &new_argv);
> ```





_Suggestion:_
```C
1 ?
```


<!-- Sent from Reviewable.io -->

2022-07-15 07:27 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/754)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @aneessahib and @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/754#-N6yH0kY52x1J3sn5uQP:-N7-jLIKC7lFnlSxEgKC:b-u95i85) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please modify `libos/test/regression/exec_script.c` test so that `argv[0]` differs from `pathname` to test this PR.
</blockquote></details>

+1, good idea

___
___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/gramineproject/gramine/754#-N6vhh9bD4z3FI2QMdXd):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Not done.
</blockquote></details>

@boryspoplawski Why not done? Looks done. But maybe your comment became stale already.
___
*[`libos/src/libos_rtld.c` line 637 at r3](https://reviewable.io/reviews/gramineproject/gramine/754#-N6yJgIOCClEzf2IC1Ri:-N7-k6CG2iYX-jPKnpFW:b-j0r35o) ([raw file](https://github.com/gramineproject/gramine/blob/cbe1ee14a605eab0a2a0949ae3381f4ea1cea7c2/libos/src/libos_rtld.c#L637)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This won't work if `*argv == NULL`
</blockquote></details>

@boryspoplawski What do you mean? If `*argv == NULL`, then we don't get into this FOR loop.


<!-- Sent from Reviewable.io -->

2022-07-15 07:37 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/754)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/gramineproject/gramine/754#-N6vhh9bD4z3FI2QMdXd):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@boryspoplawski Why not done? Looks done. But maybe your comment became stale already.
</blockquote></details>

I  pushed a set of changes  - but the commit message had to force pushed. 
___
*[`libos/src/libos_rtld.c` line 583 at r3](https://reviewable.io/reviews/gramineproject/gramine/754#-N6yDHmQB5cpyL-NmWhM:-N7-mMNa7mrUmuJsi2kg:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/cbe1ee14a605eab0a2a0949ae3381f4ea1cea7c2/libos/src/libos_rtld.c#L583)):*
> ```C
>  * strings; caller of this function should do a single free(**out_new_argv). */
> static int load_and_check_shebang(struct libos_handle* file, char** argv,
>                                   const char* argv0, char*** out_new_argv) {
> ```

Done.
___
*[`libos/src/libos_rtld.c` line 637 at r3](https://reviewable.io/reviews/gramineproject/gramine/754#-N6yHOgo2HlZ88JpL7ba:-N7-mN8jBmZvLZlYDzut:b48kerl) ([raw file](https://github.com/gramineproject/gramine/blob/cbe1ee14a605eab0a2a0949ae3381f4ea1cea7c2/libos/src/libos_rtld.c#L637)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This is wrong
</blockquote></details>

ahh.. beauty!
___
*[`libos/src/libos_rtld.c` line 665 at r3](https://reviewable.io/reviews/gramineproject/gramine/754#-N6yHfj-32_hsGsmSM9J:-N7-mTqJ8LNwwwn84MuB:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/cbe1ee14a605eab0a2a0949ae3381f4ea1cea7c2/libos/src/libos_rtld.c#L665)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`libos/src/libos_rtld.c` line 666 at r3](https://reviewable.io/reviews/gramineproject/gramine/754#-N6yHjNW1zTpZBYyD7PL:-N7-mU9e2hYbdB9m382o:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/cbe1ee14a605eab0a2a0949ae3381f4ea1cea7c2/libos/src/libos_rtld.c#L666)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`libos/src/libos_rtld.c` line 756 at r3](https://reviewable.io/reviews/gramineproject/gramine/754#-N6yFY6Z85ffuPcMN4eV:-N7-mUec6pLvFX8KQQg8:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/cbe1ee14a605eab0a2a0949ae3381f4ea1cea7c2/libos/src/libos_rtld.c#L756)):*
> ```C
> 
>         char** new_argv = NULL;
>         ret = load_and_check_shebang(file, curr_argv, depth > 1? curr_argv[0] : path, &new_argv);
> ```

Done.


<!-- Sent from Reviewable.io -->

2022-07-15 09:35 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/754)* status: 1 of 2 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/754#-N6yH0kY52x1J3sn5uQP:-N70CehQ5tfJNVJD6sUa:b-896fix) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

+1, good idea
</blockquote></details>

Done.

___


<!-- Sent from Reviewable.io -->

2022-07-15 09:59 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/754)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib and @boryspoplawski)

___
*[`libos/test/regression/exec_script.c` line 6 at r5](https://reviewable.io/reviews/gramineproject/gramine/754#-N70HRMkDcrtOPdaHwAs:-N70HRMl7aq_VndXGrnC:b-klie6i) ([raw file](https://github.com/gramineproject/gramine/blob/00fb5567ad47b197f7b2fc8458c6e31b24ab4a5b/libos/test/regression/exec_script.c#L6)):*
> ```C
> 
> int main(void) {
>     char* const argv[] = {(char*)"foo.sh", (char*)"STRING FROM EXECVE", NULL};
> ```

Please add a comment that we have this discrepancy on purpose:
```
/* the pathname arg to `execv()` differs from `argv[0]` on purpose: we want to test
   the corner case where `argv[0]` is overridden by the file pathname for interpreter
   scripts in execve family of syscalls */
```


<!-- Sent from Reviewable.io -->

2022-07-15 12:11 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/754)* status: 1 of 2 files reviewed, 9 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[`libos/test/regression/exec_script.c` line 6 at r5](https://reviewable.io/reviews/gramineproject/gramine/754#-N70HRMkDcrtOPdaHwAs:-N70lEDJEvaGO06vsN1B:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/00fb5567ad47b197f7b2fc8458c6e31b24ab4a5b/libos/test/regression/exec_script.c#L6)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add a comment that we have this discrepancy on purpose:
```
/* the pathname arg to `execv()` differs from `argv[0]` on purpose: we want to test
   the corner case where `argv[0]` is overridden by the file pathname for interpreter
   scripts in execve family of syscalls */
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-15 16:08 UTC, boryspoplawski requested changes
> Reviewed 1 of 1 files at r4, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/754)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib and @dimakuv)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/gramineproject/gramine/754#-N6vhh9bD4z3FI2QMdXd):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

I  pushed a set of changes  - but the commit message had to force pushed. 
</blockquote></details>

@dimakuv Commit message changes were missing (when I posted "Not done")

@aneessahib You can add a squash commit with a new commit message, no need for force pushes
___
*[`-- commits` line 32 at r6](https://reviewable.io/reviews/gramineproject/gramine/754#-N71actW0ryAyB7i0SfY):*
This commit message is a mess. We will clean it up before merging.
___
*[`libos/src/libos_rtld.c` line 583 at r3](https://reviewable.io/reviews/gramineproject/gramine/754#-N6yDHmQB5cpyL-NmWhM:-N71aqoB26htow2aO1Lx:bjoex7c) ([raw file](https://github.com/gramineproject/gramine/blob/cbe1ee14a605eab0a2a0949ae3381f4ea1cea7c2/libos/src/libos_rtld.c#L583)):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Please fix wrapping
___
*[`libos/src/libos_rtld.c` line 637 at r3](https://reviewable.io/reviews/gramineproject/gramine/754#-N6yJgIOCClEzf2IC1Ri:-N71aysp8ykvn0WY3hOo:b-n5l3ld) ([raw file](https://github.com/gramineproject/gramine/blob/cbe1ee14a605eab0a2a0949ae3381f4ea1cea7c2/libos/src/libos_rtld.c#L637)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@boryspoplawski What do you mean? If `*argv == NULL`, then we don't get into this FOR loop.
</blockquote></details>

Exactly. And `argv[0]` won't get overwritten with `pathname`. Basically this function should translate argv like this: `{ NULL }` -> `{ pathname, NULL}`
___
*[`libos/test/regression/exec_script.c` line 8 at r6](https://reviewable.io/reviews/gramineproject/gramine/754#-N71_yiBAtgbJa2ckDuC:-N71_yiBAtgbJa2ckDuD:b-nu07m0) ([raw file](https://github.com/gramineproject/gramine/blob/64278a625edfe7e8b54a31da5096e8a9d81285b5/libos/test/regression/exec_script.c#L8)):*
> ```C
>     char* const argv[] = {(char*)"foo.sh", (char*)"STRING FROM EXECVE", NULL};
> 
>     /* the pathname arg to `execv()` differs from `argv[0]` on purpose: we want to test
> ```

Also please add `.` at the end and fix wrapping (to 100 chars).



_Suggestion:_
```C
The
```


<!-- Sent from Reviewable.io -->

2022-07-18 07:04 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/754)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib and @boryspoplawski)

___
*[`libos/src/libos_rtld.c` line 637 at r3](https://reviewable.io/reviews/gramineproject/gramine/754#-N6yJgIOCClEzf2IC1Ri:-N7F4d6zEEACa1XWO5b8:b4rk7q6) ([raw file](https://github.com/gramineproject/gramine/blob/cbe1ee14a605eab0a2a0949ae3381f4ea1cea7c2/libos/src/libos_rtld.c#L637)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Exactly. And `argv[0]` won't get overwritten with `pathname`. Basically this function should translate argv like this: `{ NULL }` -> `{ pathname, NULL}`
</blockquote></details>

An interesting corner case. It is indeed so, I just wrote a quick test to verify this behavior.

This corner case only happens when we find the shebang (the interpreter script), but it doesn't happen when we use ELF binaries. Very interesting. @boryspoplawski How did you know about this? I skimmed through https://elixir.bootlin.com/linux/latest/source/fs/exec.c but didn't find an immediate code snippet where this logic is enforced.
___
*[`libos/src/libos_rtld.c` line 639 at r6](https://reviewable.io/reviews/gramineproject/gramine/754#-N7F5bILBuZn7z2S2kRp:-N7F5bILBuZn7z2S2kRq:bdgn05q) ([raw file](https://github.com/gramineproject/gramine/blob/64278a625edfe7e8b54a31da5096e8a9d81285b5/libos/src/libos_rtld.c#L639)):*
> ```C
>         new_argv_bytes += strlen(a == argv ? pathname : *a) + 1;
>         new_argv_cnt++;
>     }
> ```

As @boryspoplawski mentioned, we should handle a corner case of `{ NULL }` -> `{ pathname, NULL}` in this function (and only in this function, since this corner case happens only for shebangs).

I propose to add a code snippet like this at this line:
```
if (*argv == NULL) {
    /* corner case: if arg list is { NULL }, then must transform it to { pathname, NULL } */
    new_argv_bytes += strlen(pathname) + 1;
    new_argv_cnt++;
}
```
___
*[`libos/src/libos_rtld.c` line 670 at r6](https://reviewable.io/reviews/gramineproject/gramine/754#-N7F6Ikb-Nz2O8CAC3HQ:-N7F6Ikb-Nz2O8CAC3HR:br3mb5v) ([raw file](https://github.com/gramineproject/gramine/blob/64278a625edfe7e8b54a31da5096e8a9d81285b5/libos/src/libos_rtld.c#L670)):*
> ```C
>         new_argv_idx++;
>         new_argv_ptr += size;
>     }
> ```

As @boryspoplawski mentioned, we should handle a corner case of `{ NULL }` -> `{ pathname, NULL}` in this function (and only in this function, since this corner case happens only for shebangs).

I propose to add a code snippet like this immediately-after this line:
```
if (*argv == NULL) {
    /* corner case: if arg list is { NULL }, then must transform it to { pathname, NULL } */
    memcpy(new_argv_ptr, pathname, strlen(pathname) + 1);
    new_argv[new_argv_idx] = new_argv_ptr;
    new_argv_idx++;
}
```

(Notice that I left out `new_argv_ptr += size` because it is not necessary at this point anyway.)


<!-- Sent from Reviewable.io -->

2022-07-18 13:06 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/754)* status: 0 of 2 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @boryspoplawski, and @dimakuv)

___
*[`libos/src/libos_rtld.c` line 583 at r3](https://reviewable.io/reviews/gramineproject/gramine/754#-N6yDHmQB5cpyL-NmWhM:-N7GP2SAA3Fsjmku6pmN:b-6cwur4) ([raw file](https://github.com/gramineproject/gramine/blob/cbe1ee14a605eab0a2a0949ae3381f4ea1cea7c2/libos/src/libos_rtld.c#L583)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please fix wrapping
</blockquote></details>

What's wrong? Its wrapped to under 100 characters
___
*[`libos/src/libos_rtld.c` line 637 at r3](https://reviewable.io/reviews/gramineproject/gramine/754#-N6yJgIOCClEzf2IC1Ri:-N7GPeeu7O1X8cdEJPxF:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/cbe1ee14a605eab0a2a0949ae3381f4ea1cea7c2/libos/src/libos_rtld.c#L637)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

An interesting corner case. It is indeed so, I just wrote a quick test to verify this behavior.

This corner case only happens when we find the shebang (the interpreter script), but it doesn't happen when we use ELF binaries. Very interesting. @boryspoplawski How did you know about this? I skimmed through https://elixir.bootlin.com/linux/latest/source/fs/exec.c but didn't find an immediate code snippet where this logic is enforced.
</blockquote></details>

Done.
___
*[`libos/src/libos_rtld.c` line 639 at r6](https://reviewable.io/reviews/gramineproject/gramine/754#-N7F5bILBuZn7z2S2kRp:-N7GPUno39KY05VMBAJ3:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/64278a625edfe7e8b54a31da5096e8a9d81285b5/libos/src/libos_rtld.c#L639)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

As @boryspoplawski mentioned, we should handle a corner case of `{ NULL }` -> `{ pathname, NULL}` in this function (and only in this function, since this corner case happens only for shebangs).

I propose to add a code snippet like this at this line:
```
if (*argv == NULL) {
    /* corner case: if arg list is { NULL }, then must transform it to { pathname, NULL } */
    new_argv_bytes += strlen(pathname) + 1;
    new_argv_cnt++;
}
```
</blockquote></details>

Done.
___
*[`libos/src/libos_rtld.c` line 670 at r6](https://reviewable.io/reviews/gramineproject/gramine/754#-N7F6Ikb-Nz2O8CAC3HQ:-N7GPWRcE-YhxopFy91K:b-jivqf2) ([raw file](https://github.com/gramineproject/gramine/blob/64278a625edfe7e8b54a31da5096e8a9d81285b5/libos/src/libos_rtld.c#L670)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

As @boryspoplawski mentioned, we should handle a corner case of `{ NULL }` -> `{ pathname, NULL}` in this function (and only in this function, since this corner case happens only for shebangs).

I propose to add a code snippet like this immediately-after this line:
```
if (*argv == NULL) {
    /* corner case: if arg list is { NULL }, then must transform it to { pathname, NULL } */
    memcpy(new_argv_ptr, pathname, strlen(pathname) + 1);
    new_argv[new_argv_idx] = new_argv_ptr;
    new_argv_idx++;
}
```

(Notice that I left out `new_argv_ptr += size` because it is not necessary at this point anyway.)
</blockquote></details>

Yes agree. Done
___
*[`libos/test/regression/exec_script.c` line 8 at r6](https://reviewable.io/reviews/gramineproject/gramine/754#-N71_yiBAtgbJa2ckDuC:-N7GPZc89ASVnKt_eGDY:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/64278a625edfe7e8b54a31da5096e8a9d81285b5/libos/test/regression/exec_script.c#L8)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Also please add `.` at the end and fix wrapping (to 100 chars).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-18 13:39 UTC, dimakuv submitted a review, later dismissed
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/754)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @aneessahib and @boryspoplawski)

___
*[`libos/src/libos_rtld.c` line 583 at r3](https://reviewable.io/reviews/gramineproject/gramine/754#-N6yDHmQB5cpyL-NmWhM:-N7GWjrG5CloD8G2Isvm:byyzle7) ([raw file](https://github.com/gramineproject/gramine/blob/cbe1ee14a605eab0a2a0949ae3381f4ea1cea7c2/libos/src/libos_rtld.c#L583)):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

What's wrong? Its wrapped to under 100 characters
</blockquote></details>

Borys wants it to be wrapped like this:
```
static int load_and_check_shebang(struct libos_handle* file, const char* pathname, char** argv,
                                  char*** out_new_argv) {
```

Notice how the third argument (`argv`) is on the first line, because there is enough place to put it on the first line.
___
*[`libos/test/regression/exec_script.c` line 8 at r6](https://reviewable.io/reviews/gramineproject/gramine/754#-N71_yiBAtgbJa2ckDuC:-N7GX5SuBvqJVn7UIvlc:bpht8oq) ([raw file](https://github.com/gramineproject/gramine/blob/64278a625edfe7e8b54a31da5096e8a9d81285b5/libos/test/regression/exec_script.c#L8)):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You forgot the `.` at the end of the comment.


<!-- Sent from Reviewable.io -->

2022-07-19 04:22 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/754)* status: 0 of 2 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @boryspoplawski, and @dimakuv)

___
*[`libos/src/libos_rtld.c` line 583 at r3](https://reviewable.io/reviews/gramineproject/gramine/754#-N6yDHmQB5cpyL-NmWhM:-N7JfcQu-FQFiRXZnRdo:bfdl9fc) ([raw file](https://github.com/gramineproject/gramine/blob/cbe1ee14a605eab0a2a0949ae3381f4ea1cea7c2/libos/src/libos_rtld.c#L583)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Borys wants it to be wrapped like this:
```
static int load_and_check_shebang(struct libos_handle* file, const char* pathname, char** argv,
                                  char*** out_new_argv) {
```

Notice how the third argument (`argv`) is on the first line, because there is enough place to put it on the first line.
</blockquote></details>

Got it. Done
___
*[`libos/src/libos_rtld.c` line 644 at r7](https://reviewable.io/reviews/gramineproject/gramine/754#-N7GZl_x4Y8zX3IAMfS0:-N7JfoAcCgH-lPLK-s7O:b-7oj6o8) ([raw file](https://github.com/gramineproject/gramine/blob/e17dddac49adea7281aefcae4672d3bdd9a23a98/libos/src/libos_rtld.c#L644)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Maybe something like this? It's less of a corner case then.
</blockquote></details>

Ok. Done - But I have still put a comment (taking out the corner case mention). 
___
*[`libos/test/regression/exec_script.c` line 8 at r6](https://reviewable.io/reviews/gramineproject/gramine/754#-N71_yiBAtgbJa2ckDuC:-N7JgQoED4t3dSLK2_Mq:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/64278a625edfe7e8b54a31da5096e8a9d81285b5/libos/test/regression/exec_script.c#L8)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

And did not fix wrapping
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-19 08:02 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/754)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib and @boryspoplawski)

___
*[`libos/src/libos_rtld.c` line 676 at r8](https://reviewable.io/reviews/gramineproject/gramine/754#-N7KTPiiAjox5yyoOMeq:-N7KTPiiAjox5yyoOMer:b-3de0u2) ([raw file](https://github.com/gramineproject/gramine/blob/b8194d9e0502aadc61878c60b2b27074a859cc74/libos/src/libos_rtld.c#L676)):*
> ```C
>     new_argv_idx++;
>     new_argv_ptr += size;
>     for (char** a = argv + 1; *a; a++) {
> ```

You need to wrap this FOR loop in a `if (*argv) { ... }` body, just like you did above.


<!-- Sent from Reviewable.io -->

2022-07-19 08:47 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/754)* status: 1 of 2 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @boryspoplawski, and @dimakuv)

___
*[`libos/src/libos_rtld.c` line 676 at r8](https://reviewable.io/reviews/gramineproject/gramine/754#-N7KTPiiAjox5yyoOMeq:-N7KcnD053EG5Q0W1zQf:bgclz5u) ([raw file](https://github.com/gramineproject/gramine/blob/b8194d9e0502aadc61878c60b2b27074a859cc74/libos/src/libos_rtld.c#L676)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You need to wrap this FOR loop in a `if (*argv) { ... }` body, just like you did above.
</blockquote></details>

yikes. I did have it in mind all through, and ended up leaving it out!


<!-- Sent from Reviewable.io -->

2022-07-19 09:04 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/754)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @aneessahib and @boryspoplawski)

___
*[`libos/src/libos_rtld.c` line 676 at r8](https://reviewable.io/reviews/gramineproject/gramine/754#-N7KTPiiAjox5yyoOMeq:-N7KgqGB-rMNvG0U267b:b-b7vjst) ([raw file](https://github.com/gramineproject/gramine/blob/b8194d9e0502aadc61878c60b2b27074a859cc74/libos/src/libos_rtld.c#L676)):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

yikes. I did have it in mind all through, and ended up leaving it out!
</blockquote></details>

Happens :)


<!-- Sent from Reviewable.io -->

2022-07-19 09:05 UTC, dimakuv commented
Jenkins, test this please

2022-07-19 10:40 UTC, boryspoplawski submitted a review, later dismissed
> Reviewed 1 of 2 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/754)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @aneessahib)



<!-- Sent from Reviewable.io -->

2022-07-20 16:06 UTC, dimakuv submitted a review, later dismissed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/754)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski)

___
*[`-- commits` line 32 at r6](https://reviewable.io/reviews/gramineproject/gramine/754#-N71actW0ryAyB7i0SfY):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This commit message is a mess. We will clean it up before merging.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2022-07-20 16:16 UTC, boryspoplawski approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/754)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`-- commits` line 4 at r10](https://reviewable.io/reviews/gramineproject/gramine/754#-N7RO72g7WyzChGRGyT6):*
Ops, didn't notice before (so not blocking, it isn't so important).
We are emulating Linux not POSIX, so we do whatever Linux does. Also this is a (almost?) direct quotation of `man`, so we probably should mention that.


<!-- Sent from Reviewable.io -->

2022-07-20 16:24 UTC, dimakuv commented
Jenkins, test this please

2022-07-20 16:24 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/754)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[`-- commits` line 4 at r10](https://reviewable.io/reviews/gramineproject/gramine/754#-N7RO72g7WyzChGRGyT6):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Ops, didn't notice before (so not blocking, it isn't so important).
We are emulating Linux not POSIX, so we do whatever Linux does. Also this is a (almost?) direct quotation of `man`, so we probably should mention that.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-20 16:28 UTC, boryspoplawski approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/754)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-07-20 17:34 UTC, merged