[Pal/Linux] Assign an ephemeral port if port 0 was specified in `udp_bind`
gramineproject/gramine pull request #76
Opened 2021-09-22 08:45 UTC by sahason

Signed-off-by: Sonali Saha <sonali.saha@intel.com>

## Description of the changes 
Fixed the issue of an ephemeral port is not allocated when port number in a socket address is specified as 0 when calling bind.
Fixes gramineproject/graphene#2291

## How to test this PR? 
Follow the steps to reproduce mentioned in issue gramineproject/graphene#2291.

2021-09-22 09:11 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/76)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @sahason)

___
*[Pal/src/host/Linux/db_sockets.c, line 616 at r1](https://reviewable.io/reviews/gramineproject/gramine/76#-MkBlIMP7Uy8e19TsO6g:-MkBlIMP7Uy8e19TsO6h:bs94o8n) ([raw file](https://github.com/gramineproject/gramine/blob/025dd8e7de197368cba442cc86778ff16ac9f027/Pal/src/host/Linux/db_sockets.c#L616)):*
> ```C
>     if (ret < 0) {
>             ret = unix_to_pal_error(ret);
>             goto failed;
> ```

Too big indentation -- should be 4 spaces, not 8 spaces.


<!-- Sent from Reviewable.io -->

2021-09-22 09:54 UTC, sahason reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/76)* status: 0 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[Pal/src/host/Linux/db_sockets.c, line 616 at r1](https://reviewable.io/reviews/gramineproject/gramine/76#-MkBlIMP7Uy8e19TsO6g:-MkBvL-46R4Fjzzugwq3:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/025dd8e7de197368cba442cc86778ff16ac9f027/Pal/src/host/Linux/db_sockets.c#L616)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Too big indentation -- should be 4 spaces, not 8 spaces.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-09-22 12:34 UTC, dimakuv approved these changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/76)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-09-22 12:34 UTC, dimakuv commented
Jenkins, test this please

2021-09-23 17:43 UTC, boryspoplawski requested changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/76)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @sahason)

___
*[Pal/src/host/Linux/db_sockets.c, line 613 at r2](https://reviewable.io/reviews/gramineproject/gramine/76#-MkIkBhc3Km4CU_C3CIT:-MkIkBhd9IwaduV61baW:byr7hmw) ([raw file](https://github.com/gramineproject/gramine/blob/b3c50efefdc154f086a2698f4cd634d3843e4ba1/Pal/src/host/Linux/db_sockets.c#L613)):*
> ```C
>     }
> 
>     ret = DO_SYSCALL(getsockname, fd, bind_addr, &bind_addrlen);
> ```

Please add a comment here describing why we need this.


<!-- Sent from Reviewable.io -->

2021-09-24 11:17 UTC, sahason reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/76)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[Pal/src/host/Linux/db_sockets.c, line 613 at r2](https://reviewable.io/reviews/gramineproject/gramine/76#-MkIkBhc3Km4CU_C3CIT:-MkMWVD8-mpb4AxEslGG:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b3c50efefdc154f086a2698f4cd634d3843e4ba1/Pal/src/host/Linux/db_sockets.c#L613)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please add a comment here describing why we need this.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-09-24 15:20 UTC, boryspoplawski requested changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/76)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @sahason)

___
*[Pal/src/host/Linux/db_sockets.c, line 613 at r3](https://reviewable.io/reviews/gramineproject/gramine/76#-MkNO3cN1If3Tai1Wutk:-MkNO3cN1If3Tai1Wutl:b-i8yztg) ([raw file](https://github.com/gramineproject/gramine/blob/34870847d34d20fa7bc1ea04709ff389f7ac721f/Pal/src/host/Linux/db_sockets.c#L613)):*
> ```C
>     }
> 
>     /* call getsockname to update socket address when using bind with a port number of 0 */
> ```

But we call `getsockname` regardless of original port number being `0`.


<!-- Sent from Reviewable.io -->

2021-09-28 05:47 UTC, sahason reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/76)* status: 1 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[Pal/src/host/Linux/db_sockets.c, line 613 at r3](https://reviewable.io/reviews/gramineproject/gramine/76#-MkNO3cN1If3Tai1Wutk:-MkewTPzDeODLNBtM2c3:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/34870847d34d20fa7bc1ea04709ff389f7ac721f/Pal/src/host/Linux/db_sockets.c#L613)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

But we call `getsockname` regardless of original port number being `0`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-09-28 06:19 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/76)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @sahason)

___
*[Pal/src/host/Linux/db_sockets.c, line 613 at r3](https://reviewable.io/reviews/gramineproject/gramine/76#-MkNO3cN1If3Tai1Wutk:-Mkf2-x2-P9MN-8QWkeY:bepyns2) ([raw file](https://github.com/gramineproject/gramine/blob/34870847d34d20fa7bc1ea04709ff389f7ac721f/Pal/src/host/Linux/db_sockets.c#L613)):*
<details><summary><i>Previously, sahason wrote…</i></summary><blockquote>

Done.
</blockquote></details>

@boryspoplawski Do you mean that:
- The commit message is misleading? It says that `if port 0 was specified in udp_bind`, but here we just do `getsockname` always?
- Or you want an explicit check of `bind_addr` ("if port is 0, then call this func")?

We have this same snippet in other places in sockets code (I marked one of such places). It looks like Chia-Che simply forgot to add this code snippet to the UDP-bind case.

Also, I don't see any problem in calling this function `getsockname()` always -- we don't care about performance here, and we don't care about security in Linux PAL. If `bind_addr` is overwritten (with the same value), who cares.
___
*[Pal/src/host/Linux/db_sockets.c, line 330 at r4](https://reviewable.io/reviews/gramineproject/gramine/76#-Mkf1und9gvPAKZvO9ZC:-Mkf1und9gvPAKZvO9ZD:bawsvx1) ([raw file](https://github.com/gramineproject/gramine/blob/503ac9ba0a32d18a37dd48b0c78ab566f6b2ef9c/Pal/src/host/Linux/db_sockets.c#L330)):*
> ```C
> 
>     /* call getsockname to get socket address */
>     ret = DO_SYSCALL(getsockname, fd, bind_addr, &bind_addrlen);
> ```

@boryspoplawski Here is an example where we call `getsockname()` on TCP listen.


<!-- Sent from Reviewable.io -->

2021-09-28 19:13 UTC, boryspoplawski submitted a review, later dismissed
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/76)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @sahason)

___
*[Pal/src/host/Linux/db_sockets.c, line 613 at r3](https://reviewable.io/reviews/gramineproject/gramine/76#-MkNO3cN1If3Tai1Wutk:-MkhobdODJBPtFvHb7h2:b-olf46l) ([raw file](https://github.com/gramineproject/gramine/blob/34870847d34d20fa7bc1ea04709ff389f7ac721f/Pal/src/host/Linux/db_sockets.c#L613)):*
I meant the comment is misleading.

> we don't care about security in Linux PAL

Of course we do, the only difference from SGX PAL is we trust the host machine and OS.


<!-- Sent from Reviewable.io -->

2021-09-28 20:45 UTC, dimakuv commented
Jenkins, test this please

2021-09-29 08:45 UTC, dimakuv approved these changes
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/76)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2021-09-29 11:29 UTC, boryspoplawski approved these changes
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/76)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-09-29 11:29 UTC, boryspoplawski commented
Jenkins, retest this please

2021-09-29 11:54 UTC, merged