[Pal] Always allocate `file.realpath` and `dir.realpath` in separate memory locations
gramineproject/gramine pull request #764
Opened 2022-07-18 07:58 UTC by yao-ji

## Description of the changes 

Previously in `file_open`, `file.realpath` is allocated [together with the handle](https://github.com/gramineproject/gramine/blob/85078de3222367da4d0aaa14793c218648a94659/pal/src/host/linux/pal_files.c#L42). But in `file_rename`, it is allocated to a [separate memory location](https://github.com/gramineproject/gramine/blob/85078de3222367da4d0aaa14793c218648a94659/pal/src/host/linux/pal_files.c#L219). After this change, `file.realpath` is also allocated separately in `file_open`, and there is no need to [check the address of the pointer](https://github.com/gramineproject/gramine/blob/85078de3222367da4d0aaa14793c218648a94659/pal/src/host/linux/pal_files.c#L116) when doing free inside `file_close`. We also set the pointer to `NULL` after free to avoid double free. Same for `dir.realpath`.

In addition, we copy `dir.realpath` before doing `dir_close` inside `dir_delete` to avoid using after free of this pointer.

Fixes #758 

## How to test this PR? 
This PR add test cases in `pal/regression/Directory.c`. You can use this branch to rebuild Gramine and do regression test.

2022-07-18 09:18 UTC, guzongmin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/764)* status: 0 of 4 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @yao-ji)

___
*[`pal/src/host/linux/pal_files.c` line 235 at r1](https://reviewable.io/reviews/gramineproject/gramine/764#-N7F_IlcCMSD_GI66p_r:-N7F_IlcCMSD_GI66p_s:b-19prdv) ([raw file](https://github.com/gramineproject/gramine/blob/177e71bc42f4d4996469b470bd6f4966008ddb6b/pal/src/host/linux/pal_files.c#L235)):*
> ```C
> 
>     if (handle->file.realpath) {
>         free((void*)handle->file.realpath);
> ```

Do you need to set the "realpath" to NULL?
___
*[`pal/src/host/linux/pal_files.c` line 469 at r1](https://reviewable.io/reviews/gramineproject/gramine/764#-N7Fa52KCnxNvsXJh956:-N7Fa52KCnxNvsXJh957:bt1zgyk) ([raw file](https://github.com/gramineproject/gramine/blob/177e71bc42f4d4996469b470bd6f4966008ddb6b/pal/src/host/linux/pal_files.c#L469)):*
> ```C
> 
>     if (handle->dir.realpath) {
>         free((void*)handle->dir.realpath);
> ```

Please set the realpath to NULL after the free.
___
*[`pal/src/host/linux-sgx/pal_files.c` line 466 at r1](https://reviewable.io/reviews/gramineproject/gramine/764#-N7FaKb36S5RfPSp03Wy:-N7FaKb36S5RfPSp03Wz:b-kpyj1s) ([raw file](https://github.com/gramineproject/gramine/blob/177e71bc42f4d4996469b470bd6f4966008ddb6b/pal/src/host/linux-sgx/pal_files.c#L466)):*
> ```C
> 
>     if (handle->file.realpath) {
>         free((void*)handle->file.realpath);
> ```

Please set realpath to NULL.
___
*[`pal/src/host/linux-sgx/pal_files.c` line 695 at r1](https://reviewable.io/reviews/gramineproject/gramine/764#-N7FaZ2R93wGr0sFttn3:-N7FaZ2R93wGr0sFttn4:b-kpyj1s) ([raw file](https://github.com/gramineproject/gramine/blob/177e71bc42f4d4996469b470bd6f4966008ddb6b/pal/src/host/linux-sgx/pal_files.c#L695)):*
> ```C
> 
>     if (handle->dir.realpath) {
>         free((void*)handle->dir.realpath);
> ```

Please set realpath to NULL.


<!-- Sent from Reviewable.io -->

2022-07-19 01:52 UTC, yao-ji commented
*[`pal/src/host/linux/pal_files.c` line 235 at r1](https://reviewable.io/reviews/gramineproject/gramine/764#-N7F_IlcCMSD_GI66p_r:-N7J7qE36yQBcpCX6Kcp:b-c7jaes) ([raw file](https://github.com/gramineproject/gramine/blob/177e71bc42f4d4996469b470bd6f4966008ddb6b/pal/src/host/linux/pal_files.c#L235)):*
<details><summary><i>Previously, guzongmin (Zongmin.Gu) wrote…</i></summary><blockquote>

Do you need to set the "realpath" to NULL?
</blockquote></details>

Since `handle->file.realpath` directly points to another memory location in the next line, I think we can skip this step. Same as all the others.


<!-- Sent from Reviewable.io -->

2022-07-19 02:38 UTC, guzongmin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/764)* status: 0 of 4 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @yao-ji)

___
*[`pal/src/host/linux/pal_files.c` line 235 at r1](https://reviewable.io/reviews/gramineproject/gramine/764#-N7F_IlcCMSD_GI66p_r:-N7JI9jy-LahqdGbNMEm:b-tp0ijf) ([raw file](https://github.com/gramineproject/gramine/blob/177e71bc42f4d4996469b470bd6f4966008ddb6b/pal/src/host/linux/pal_files.c#L235)):*
<details><summary><i>Previously, yao-ji wrote…</i></summary><blockquote>

Since `handle->file.realpath` directly points to another memory location in the next line, I think we can skip this step. Same as all the others.
</blockquote></details>

My opinion is that we should always follow secure programming guidelines. The following code may change in the bug fix or new feature implementations; the new developer may have no idea that "he must set something to the realpath." So I think you'd better set the point to NULL after free it. 


<!-- Sent from Reviewable.io -->

2022-07-19 06:03 UTC, yao-ji reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/764)* status: 0 of 4 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @guzongmin)

___
*[`pal/src/host/linux/pal_files.c` line 235 at r1](https://reviewable.io/reviews/gramineproject/gramine/764#-N7F_IlcCMSD_GI66p_r:-N7K1sZ7CufoMwckAsXD:b-tldtzb) ([raw file](https://github.com/gramineproject/gramine/blob/177e71bc42f4d4996469b470bd6f4966008ddb6b/pal/src/host/linux/pal_files.c#L235)):*
<details><summary><i>Previously, guzongmin (Zongmin.Gu) wrote…</i></summary><blockquote>

My opinion is that we should always follow secure programming guidelines. The following code may change in the bug fix or new feature implementations; the new developer may have no idea that "he must set something to the realpath." So I think you'd better set the point to NULL after free it. 
</blockquote></details>

Agreed. Changes are done. Thanks.
___
*[`pal/src/host/linux/pal_files.c` line 469 at r1](https://reviewable.io/reviews/gramineproject/gramine/764#-N7Fa52KCnxNvsXJh956:-N7K20Oj3NeSanLwfV-R:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/177e71bc42f4d4996469b470bd6f4966008ddb6b/pal/src/host/linux/pal_files.c#L469)):*
<details><summary><i>Previously, guzongmin (Zongmin.Gu) wrote…</i></summary><blockquote>

Please set the realpath to NULL after the free.
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/pal_files.c` line 466 at r1](https://reviewable.io/reviews/gramineproject/gramine/764#-N7FaKb36S5RfPSp03Wy:-N7K2Ikj8JEjzv9zzn7u:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/177e71bc42f4d4996469b470bd6f4966008ddb6b/pal/src/host/linux-sgx/pal_files.c#L466)):*
<details><summary><i>Previously, guzongmin (Zongmin.Gu) wrote…</i></summary><blockquote>

Please set realpath to NULL.
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/pal_files.c` line 695 at r1](https://reviewable.io/reviews/gramineproject/gramine/764#-N7FaZ2R93wGr0sFttn3:-N7K2JEV4XNZ1olKDsBo:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/177e71bc42f4d4996469b470bd6f4966008ddb6b/pal/src/host/linux-sgx/pal_files.c#L695)):*
<details><summary><i>Previously, guzongmin (Zongmin.Gu) wrote…</i></summary><blockquote>

Please set realpath to NULL.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-19 09:01 UTC, dimakuv requested changes
> Reviewed 2 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/764)* status: all files reviewed, 17 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @guzongmin and @yao-ji)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/gramineproject/gramine/764#-N7Ka4OfCVM17Nywuq2g):*
I suggest to make it more succinct:
```
[PAL] Allocate `file.realpath` and `dir.realpath` as separate buffers
```

@yao-ji No need for you to do anything, we can fix it during final rebase.
___
*[`-- commits` line 4 at r2](https://reviewable.io/reviews/gramineproject/gramine/764#-N7KaPDYCiFI0BWzva38):*
@yao-ji For the future, please wrap (split) lines to 72-char limit in git-commit messages.

@yao-ji No need for you to do anything, we can wrap the lines correctly during final rebase.

I will also fix the wording slighty.
___
*[`pal/src/host/linux/pal_files.c` line 235 at r1](https://reviewable.io/reviews/gramineproject/gramine/764#-N7F_IlcCMSD_GI66p_r:-N7KcD6J35bardg-njDv:b-idtv9l) ([raw file](https://github.com/gramineproject/gramine/blob/177e71bc42f4d4996469b470bd6f4966008ddb6b/pal/src/host/linux/pal_files.c#L235)):*
This is not justified. The shorter the code, the better -- it is more readable, there is less "why did they do this?".

1. We perform `rename(handle->file.realpath, ...)` syscall above, so at this point we know that `handle->file.realpath` is for sure not NULL. So there is no need for the IF check.
2. We set `handle->file.realpath = tmp` right below. So there is no need for setting it to NULL here.

In the end, the code snippet should be as simple as:
```
    free((void*)handle->file.realpath);
    handle->file.realpath = tmp;
    return 0;
```

> The following code may change in the bug fix or new feature implementations; the new developer may have no idea that "he must set something to the realpath."

But the new developer will not just blindly change the code without looking at it first. It is impossible not to notice that the very next line updates the same variable. Even if the new developer makes such a mistake, we have a review process to point out this mistake.
___
*[`pal/src/host/linux/pal_files.c` line 469 at r1](https://reviewable.io/reviews/gramineproject/gramine/764#-N7Fa52KCnxNvsXJh956:-N7KfLOd0q-CXojxPAxP:b-w002fu) ([raw file](https://github.com/gramineproject/gramine/blob/177e71bc42f4d4996469b470bd6f4966008ddb6b/pal/src/host/linux/pal_files.c#L469)):*
<details><summary><i>Previously, yao-ji wrote…</i></summary><blockquote>

Done.
</blockquote></details>

ditto (see my other comment, I don't think this complexity is needed here)
___
*[`pal/src/host/linux/pal_files.c` line 51 at r2](https://reviewable.io/reviews/gramineproject/gramine/764#-N7KbU6478beDTAe33Pd:-N7KbU6478beDTAe33Pe:bi2iedd) ([raw file](https://github.com/gramineproject/gramine/blob/55507290112cdf8935620f0f2d82d8c38a2f35e1/pal/src/host/linux/pal_files.c#L51)):*
> ```C
>     hdl->flags |= PAL_HANDLE_FD_READABLE | PAL_HANDLE_FD_WRITABLE;
>     hdl->file.fd = ret;
>     char* path = malloc(uri_size);
> ```

Please add an empty line before this one, to visually separate this block of code.
___
*[`pal/src/host/linux/pal_files.c` line 56 at r2](https://reviewable.io/reviews/gramineproject/gramine/764#-N7KbY636BJciQ7lS4aZ:-N7KbY636BJciQ7lS4a_:b-9eywpc) ([raw file](https://github.com/gramineproject/gramine/blob/55507290112cdf8935620f0f2d82d8c38a2f35e1/pal/src/host/linux/pal_files.c#L56)):*
> ```C
>         free(hdl);
>         return -PAL_ERROR_NOMEM;
>     }
> ```

Please add an empty line after this one, to visually separate this block of code.
___
*[`pal/src/host/linux/pal_files.c` line 60 at r2](https://reviewable.io/reviews/gramineproject/gramine/764#-N7Kbb9e3kzSrohbEn0p:-N7Kbb9e3kzSrohbEn0q:b-5rm6ey) ([raw file](https://github.com/gramineproject/gramine/blob/55507290112cdf8935620f0f2d82d8c38a2f35e1/pal/src/host/linux/pal_files.c#L60)):*
> ```C
>     if (ret < 0) {
>         DO_SYSCALL(close, hdl->file.fd);
>         free(hdl);
> ```

You also need to `free(path)`
___
*[`pal/src/host/linux/pal_files.c` line 70 at r2](https://reviewable.io/reviews/gramineproject/gramine/764#-N7KbeSl6nDMfQ9JH7fl:-N7KbeSl6nDMfQ9JH7fm:b-5rm6ey) ([raw file](https://github.com/gramineproject/gramine/blob/55507290112cdf8935620f0f2d82d8c38a2f35e1/pal/src/host/linux/pal_files.c#L70)):*
> ```C
>     if (ret < 0) {
>         DO_SYSCALL(close, hdl->file.fd);
>         free(hdl);
> ```

You also need to `free(path)`
___
*[`pal/src/host/linux/pal_files.c` line 305 at r2](https://reviewable.io/reviews/gramineproject/gramine/764#-N7KdnbO7_TQd2OFHzVJ:-N7KdnbO7_TQd2OFHzVK:b-3x8nv9) ([raw file](https://github.com/gramineproject/gramine/blob/55507290112cdf8935620f0f2d82d8c38a2f35e1/pal/src/host/linux/pal_files.c#L305)):*
> ```C
>         return unix_to_pal_error(fd);
> 
>     size_t len = strlen(uri);
> ```

I would re-write it similarly to `file_open()`. So this:
```
    size_t len = strlen(uri);
```
is changed to this:
```
    size_t uri_size = strlen(uri) + 1;
```

And then below you don't need to write `+ 1` anywhere.
___
*[`pal/src/host/linux/pal_files.c` line 317 at r2](https://reviewable.io/reviews/gramineproject/gramine/764#-N7KeAxA0sNvUPzisGCn:-N7KeAxBCw_LI7-D3Otr:b-331pu3) ([raw file](https://github.com/gramineproject/gramine/blob/55507290112cdf8935620f0f2d82d8c38a2f35e1/pal/src/host/linux/pal_files.c#L317)):*
> ```C
>     hdl->dir.fd = fd;
> 
>     char* path = malloc(len + 1);
> ```

Actually, instead of this `malloc + memcpy`, you could just use `strdup()`.
___
*[`pal/src/host/linux/pal_files.c` line 435 at r2](https://reviewable.io/reviews/gramineproject/gramine/764#-N7KeqW6CEf5lHY_7Neb:-N7KeqW6CEf5lHY_7Nec:bmpj9p1) ([raw file](https://github.com/gramineproject/gramine/blob/55507290112cdf8935620f0f2d82d8c38a2f35e1/pal/src/host/linux/pal_files.c#L435)):*
> ```C
> 
> /* 'delete' operation of directory streams */
> static int dir_delete(PAL_HANDLE handle, enum pal_delete_mode delete_mode) {
> ```

Now that I look at this function, it doesn't look right.

I see no reason why `dir_delete()` should call `dir_close()`. This function should do only one action -- unlink (rmdir) the directory on the host. There is no need to close the dir handle. (If you look at `file_delete()`, you'll notice that that function doesn't close the file handle.)

@yao-ji Could you revert to the previous code, and remove dir_close(handle)` line? I think that's the correct fix for the bug.
___
*[`pal/src/host/linux-sgx/pal_files.c` line 466 at r1](https://reviewable.io/reviews/gramineproject/gramine/764#-N7FaKb36S5RfPSp03Wy:-N7KfwAk4rw1UZH_7Z3Y:b-lvrsk9) ([raw file](https://github.com/gramineproject/gramine/blob/177e71bc42f4d4996469b470bd6f4966008ddb6b/pal/src/host/linux-sgx/pal_files.c#L466)):*
<details><summary><i>Previously, yao-ji wrote…</i></summary><blockquote>

Done.
</blockquote></details>

ditto (I disagree)
___
*[`pal/src/host/linux-sgx/pal_files.c` line 695 at r1](https://reviewable.io/reviews/gramineproject/gramine/764#-N7FaZ2R93wGr0sFttn3:-N7KgCbw4XKkk9jMX_xc:b-lvrsk9) ([raw file](https://github.com/gramineproject/gramine/blob/177e71bc42f4d4996469b470bd6f4966008ddb6b/pal/src/host/linux-sgx/pal_files.c#L695)):*
<details><summary><i>Previously, yao-ji wrote…</i></summary><blockquote>

Done.
</blockquote></details>

ditto (I disagree)
___
*[`pal/src/host/linux-sgx/pal_files.c` line 160 at r2](https://reviewable.io/reviews/gramineproject/gramine/764#-N7Kfj8jEjO8iw9uclJ_:-N7Kfj8jEjO8iw9uclJa:boc3gfz) ([raw file](https://github.com/gramineproject/gramine/blob/55507290112cdf8935620f0f2d82d8c38a2f35e1/pal/src/host/linux-sgx/pal_files.c#L160)):*
> ```C
>     if (hdl->file.realpath) {
>         free((void*)hdl->file.realpath);
>         hdl->file.realpath = NULL;
> ```

This line is  [...]

2022-07-20 06:41 UTC, yao-ji reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/764)* status: 2 of 4 files reviewed, 17 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @guzongmin)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/gramineproject/gramine/764#-N7Ka4OfCVM17Nywuq2g):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I suggest to make it more succinct:
```
[PAL] Allocate `file.realpath` and `dir.realpath` as separate buffers
```

@yao-ji No need for you to do anything, we can fix it during final rebase.
</blockquote></details>

Thanks.
___
*[`-- commits` line 4 at r2](https://reviewable.io/reviews/gramineproject/gramine/764#-N7KaPDYCiFI0BWzva38):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@yao-ji For the future, please wrap (split) lines to 72-char limit in git-commit messages.

@yao-ji No need for you to do anything, we can wrap the lines correctly during final rebase.

I will also fix the wording slighty.
</blockquote></details>

Acknowledged. Thanks.
___
*[`pal/src/host/linux/pal_files.c` line 235 at r1](https://reviewable.io/reviews/gramineproject/gramine/764#-N7F_IlcCMSD_GI66p_r:-N7PJKwVB97xrqJlLXHY:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/177e71bc42f4d4996469b470bd6f4966008ddb6b/pal/src/host/linux/pal_files.c#L235)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This is not justified. The shorter the code, the better -- it is more readable, there is less "why did they do this?".

1. We perform `rename(handle->file.realpath, ...)` syscall above, so at this point we know that `handle->file.realpath` is for sure not NULL. So there is no need for the IF check.
2. We set `handle->file.realpath = tmp` right below. So there is no need for setting it to NULL here.

In the end, the code snippet should be as simple as:
```
    free((void*)handle->file.realpath);
    handle->file.realpath = tmp;
    return 0;
```

> The following code may change in the bug fix or new feature implementations; the new developer may have no idea that "he must set something to the realpath."

But the new developer will not just blindly change the code without looking at it first. It is impossible not to notice that the very next line updates the same variable. Even if the new developer makes such a mistake, we have a review process to point out this mistake.
</blockquote></details>

Done.
___
*[`pal/src/host/linux/pal_files.c` line 469 at r1](https://reviewable.io/reviews/gramineproject/gramine/764#-N7Fa52KCnxNvsXJh956:-N7PK-8P43xyXqY2ex2v:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/177e71bc42f4d4996469b470bd6f4966008ddb6b/pal/src/host/linux/pal_files.c#L469)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto (see my other comment, I don't think this complexity is needed here)
</blockquote></details>

Done.
___
*[`pal/src/host/linux/pal_files.c` line 51 at r2](https://reviewable.io/reviews/gramineproject/gramine/764#-N7KbU6478beDTAe33Pd:-N7PJH2kDalpdEzW8STL:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/55507290112cdf8935620f0f2d82d8c38a2f35e1/pal/src/host/linux/pal_files.c#L51)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add an empty line before this one, to visually separate this block of code.
</blockquote></details>

Done.
___
*[`pal/src/host/linux/pal_files.c` line 56 at r2](https://reviewable.io/reviews/gramineproject/gramine/764#-N7KbY636BJciQ7lS4aZ:-N7PJHjGBaEfU7mlwEma:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/55507290112cdf8935620f0f2d82d8c38a2f35e1/pal/src/host/linux/pal_files.c#L56)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add an empty line after this one, to visually separate this block of code.
</blockquote></details>

Done.
___
*[`pal/src/host/linux/pal_files.c` line 60 at r2](https://reviewable.io/reviews/gramineproject/gramine/764#-N7Kbb9e3kzSrohbEn0p:-N7PJIRXCZFpMUmkJoO9:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/55507290112cdf8935620f0f2d82d8c38a2f35e1/pal/src/host/linux/pal_files.c#L60)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You also need to `free(path)`
</blockquote></details>

Done.
___
*[`pal/src/host/linux/pal_files.c` line 70 at r2](https://reviewable.io/reviews/gramineproject/gramine/764#-N7KbeSl6nDMfQ9JH7fl:-N7PJIqG4QD8HEr8E2Q_:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/55507290112cdf8935620f0f2d82d8c38a2f35e1/pal/src/host/linux/pal_files.c#L70)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You also need to `free(path)`
</blockquote></details>

Done.
___
*[`pal/src/host/linux/pal_files.c` line 305 at r2](https://reviewable.io/reviews/gramineproject/gramine/764#-N7KdnbO7_TQd2OFHzVJ:-N7PJP2u3lTMp8mq3DuL:b-xjkal0) ([raw file](https://github.com/gramineproject/gramine/blob/55507290112cdf8935620f0f2d82d8c38a2f35e1/pal/src/host/linux/pal_files.c#L305)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I would re-write it similarly to `file_open()`. So this:
```
    size_t len = strlen(uri);
```
is changed to this:
```
    size_t uri_size = strlen(uri) + 1;
```

And then below you don't need to write `+ 1` anywhere.
</blockquote></details>

Removed this. Since after changing to `strdup`, it is not used.
___
*[`pal/src/host/linux/pal_files.c` line 317 at r2](https://reviewable.io/reviews/gramineproject/gramine/764#-N7KeAxA0sNvUPzisGCn:-N7PJtQm4g1nn45V2caD:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/55507290112cdf8935620f0f2d82d8c38a2f35e1/pal/src/host/linux/pal_files.c#L317)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Actually, instead of this `malloc + memcpy`, you could just use `strdup()`.
</blockquote></details>

Done.
___
*[`pal/src/host/linux/pal_files.c` line 435 at r2](https://reviewable.io/reviews/gramineproject/gramine/764#-N7KeqW6CEf5lHY_7Neb:-N7PJxtg3yEKb7432SgT:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/55507290112cdf8935620f0f2d82d8c38a2f35e1/pal/src/host/linux/pal_files.c#L435)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Now that I look at this function, it doesn't look right.

I see no reason why `dir_delete()` should call `dir_close()`. This function should do only one action -- unlink (rmdir) the directory on the host. There is no need to close the dir handle. (If you look at `file_delete()`, you'll notice that that function doesn't close the file handle.)

@yao-ji Could you revert to the previous code, and remove dir_close(handle)` line? I think that's the correct fix for the bug.
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/pal_files.c` line 466 at r1](https://reviewable.io/reviews/gramineproject/gramine/764#-N7FaKb36S5RfPSp03Wy:-N7PK4PX6hXZyQ8SKyYf:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/177e71bc42f4d4996469b470bd6f4966008ddb6b/pal/src/host/linux-sgx/pal_files.c#L466)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto (I disagree)
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/pal_files.c` line 695 at r1](https://reviewable.io/reviews/gramineproject/gramine/764#-N7FaZ2R93wGr0sFttn3:-N7PKP9m0HXKyg17zphY:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/177e71bc42f4d4996469b470bd6f4966008ddb6b/pal/src/host/linux-sgx/pal_files.c#L69 [...]

2022-07-20 07:45 UTC, dimakuv approved these changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/764)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @guzongmin)

___
*[`pal/src/host/linux/pal_files.c` line 305 at r2](https://reviewable.io/reviews/gramineproject/gramine/764#-N7KdnbO7_TQd2OFHzVJ:-N7PYSosCetE91-9e3GY:b-fa5k8p) ([raw file](https://github.com/gramineproject/gramine/blob/55507290112cdf8935620f0f2d82d8c38a2f35e1/pal/src/host/linux/pal_files.c#L305)):*
<details><summary><i>Previously, yao-ji wrote…</i></summary><blockquote>

Removed this. Since after changing to `strdup`, it is not used.
</blockquote></details>

You are right, thanks.
___
*[`pal/src/host/linux/pal_files.c` line 435 at r2](https://reviewable.io/reviews/gramineproject/gramine/764#-N7KeqW6CEf5lHY_7Neb:-N7PZFjFCDlcPRkkJsQT:b-5s5ywo) ([raw file](https://github.com/gramineproject/gramine/blob/55507290112cdf8935620f0f2d82d8c38a2f35e1/pal/src/host/linux/pal_files.c#L435)):*
<details><summary><i>Previously, yao-ji wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Just a sanity check: did you verify that the bug you reported in #758 doesn't appear with this new revision of your PR?


<!-- Sent from Reviewable.io -->

2022-07-20 08:38 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/764)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @guzongmin)

___
*[`pal/src/host/linux/pal_files.c` line 435 at r2](https://reviewable.io/reviews/gramineproject/gramine/764#-N7KeqW6CEf5lHY_7Neb:-N7PkZZQ7Pm64x_3j5B_:b-6mhyx0) ([raw file](https://github.com/gramineproject/gramine/blob/55507290112cdf8935620f0f2d82d8c38a2f35e1/pal/src/host/linux/pal_files.c#L435)):*
<details><summary><i>Previously, yao-ji wrote…</i></summary><blockquote>

Yes, I have verified.
</blockquote></details>

Great, thanks!


<!-- Sent from Reviewable.io -->

2022-07-20 08:38 UTC, dimakuv commented
Jenkins, test this please

2022-07-20 12:44 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/764)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @guzongmin, and @yao-ji)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/764#-N7QcZLhAf-LgmjtdRkk:-N7QcZLhAf-LgmjtdRkl:byoxarz) (no related file):*
`gramine-direct ./bash -c "ls"` failed with:
```
assert failed ../common/include/slabmgr.h:347 (mobj)->__list.prev->__list.next == (mobj)
```

Please use the `debug` build of Gramine and try to run the Bash example. You'll see this failure. Please debug it. Your PR introduced some bug/memory corruption (on `gramine-direct`, in other words, on Linux PAL).

___


<!-- Sent from Reviewable.io -->

2022-07-20 14:31 UTC, boryspoplawski requested changes
> Reviewed 2 of 4 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/764)* status: all files reviewed, 20 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @guzongmin, and @yao-ji)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/764#-N7QcZLhAf-LgmjtdRkk:-N7Qz1aN8nu3UVdy9BLR:blguxw8) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`gramine-direct ./bash -c "ls"` failed with:
```
assert failed ../common/include/slabmgr.h:347 (mobj)->__list.prev->__list.next == (mobj)
```

Please use the `debug` build of Gramine and try to run the Bash example. You'll see this failure. Please debug it. Your PR introduced some bug/memory corruption (on `gramine-direct`, in other words, on Linux PAL).
</blockquote></details>

I don't think it did.

@yao-ji You didn't check all usages of `file.realpath` and `dir.realpath`, e.g. you need to fix `pal/src/host/linux/pal_streams.c`

___
___
*[`-- commits` line 6 at r3](https://reviewable.io/reviews/gramineproject/gramine/764#-N7QzHxD5nZKs4tqcu7X):*
What is this comment about? Stale from some intermediate version?
___
*[`pal/regression/Directory.c` line 104 at r3](https://reviewable.io/reviews/gramineproject/gramine/764#-N7QuO9bCRdgSR5mMps9:-N7QuO9bCRdgSR5mMpsA:b-ctpbuk) ([raw file](https://github.com/gramineproject/gramine/blob/4be842efab365bd43a15fa7bfebcba8087657b76/pal/regression/Directory.c#L104)):*
> ```C
>         ret = PalStreamChangeName(dir8, "dir:dir_rename_delete.tmp");
>         if (ret < 0) {
>             pal_printf("PalStreamChangeName failed\n");
> ```

Please print `ret` value here
___
*[`pal/regression/Directory.c` line 109 at r3](https://reviewable.io/reviews/gramineproject/gramine/764#-N7QuPuQ1gzYRm5L-0OC:-N7QuPuQ1gzYRm5L-0OD:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/4be842efab365bd43a15fa7bfebcba8087657b76/pal/regression/Directory.c#L109)):*
> ```C
>         ret = PalStreamDelete(dir8, PAL_DELETE_ALL);
>         if (ret < 0) {
>             pal_printf("PalStreamDelete failed\n");
> ```

ditto
___
*[`pal/src/host/linux/pal_files.c` line 127 at r3](https://reviewable.io/reviews/gramineproject/gramine/764#-N7Qvhpd8-HNVqndbBZf:-N7Qvhpd8-HNVqndbBZg:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/4be842efab365bd43a15fa7bfebcba8087657b76/pal/src/host/linux/pal_files.c#L127)):*
> ```C
>         free((void*)handle->file.realpath);
>         handle->file.realpath = NULL;
>     }
> ```





_Suggestion:_
```C
    free(handle->file.realpath);
```
___
*[`pal/src/host/linux/pal_files.c` line 238 at r3](https://reviewable.io/reviews/gramineproject/gramine/764#-N7Qw7_8DmOXb2EmkhjP:-N7Qw7_8DmOXb2EmkhjQ:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/4be842efab365bd43a15fa7bfebcba8087657b76/pal/src/host/linux/pal_files.c#L238)):*
> ```C
>     }
> 
>     free((void*)handle->file.realpath);
> ```





_Suggestion:_
```C
free(handle->file.realpath);
```
___
*[`pal/src/host/linux/pal_files.c` line 424 at r3](https://reviewable.io/reviews/gramineproject/gramine/764#-N7QxVZK-o4zYzeVPyvY:-N7QxVZK-o4zYzeVPyvZ:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/4be842efab365bd43a15fa7bfebcba8087657b76/pal/src/host/linux/pal_files.c#L424)):*
> ```C
>         free((void*)handle->dir.realpath);
>         handle->dir.realpath = NULL;
>     }
> ```





_Suggestion:_
```C
    free(handle->dir.realpath);
```
___
*[`pal/src/host/linux/pal_files.c` line 456 at r3](https://reviewable.io/reviews/gramineproject/gramine/764#-N7Qy28R7JWm5wSu91em:-N7Qy28R7JWm5wSu91en:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/4be842efab365bd43a15fa7bfebcba8087657b76/pal/src/host/linux/pal_files.c#L456)):*
> ```C
>     }
> 
>     free((void*)handle->dir.realpath);
> ```





_Suggestion:_
```C
free(handle->dir.realpath);
```
___
*[`pal/src/host/linux-sgx/pal_files.c` line 160 at r3](https://reviewable.io/reviews/gramineproject/gramine/764#-N7R-6oA4wEoBk8s9R10:-N7R-6oA4wEoBk8s9R11:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/4be842efab365bd43a15fa7bfebcba8087657b76/pal/src/host/linux-sgx/pal_files.c#L160)):*
> ```C
>     if (hdl->file.realpath) {
>         free((void*)hdl->file.realpath);
>     }
> ```





_Suggestion:_
```C
    free(hdl->file.realpath);
```
___
*[`pal/src/host/linux-sgx/pal_files.c` line 239 at r3](https://reviewable.io/reviews/gramineproject/gramine/764#-N7R-IbB4hT6r7-anXir:-N7R-IbB4hT6r7-anXis:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/4be842efab365bd43a15fa7bfebcba8087657b76/pal/src/host/linux-sgx/pal_files.c#L239)):*
> ```C
>         free((void*)handle->file.realpath);
>         handle->file.realpath = NULL;
>     }
> ```





_Suggestion:_
```C
    free(handle->file.realpath);
```
___
*[`pal/src/host/linux-sgx/pal_files.c` line 464 at r3](https://reviewable.io/reviews/gramineproject/gramine/764#-N7R-XFH7LZ-EgL3SNx9:-N7R-XFH7LZ-EgL3SNxA:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/4be842efab365bd43a15fa7bfebcba8087657b76/pal/src/host/linux-sgx/pal_files.c#L464)):*
> ```C
>     }
> 
>     free((void*)handle->file.realpath);
> ```





_Suggestion:_
```C
free(handle->file.realpath);
```
___
*[`pal/src/host/linux-sgx/pal_files.c` line 542 at r3](https://reviewable.io/reviews/gramineproject/gramine/764#-N7R-jOTANoXz5dlr-nH:-N7R-jOTANoXz5dlr-nI:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/4be842efab365bd43a15fa7bfebcba8087657b76/pal/src/host/linux-sgx/pal_files.c#L542)):*
> ```C
>     hdl->dir.fd = fd;
> 
>     char* path  = strdup(uri);
> ```





_Suggestion:_
```C
char* path = strdup(uri);
```
___
*[`pal/src/host/linux-sgx/pal_files.c` line 653 at r3](https://reviewable.io/reviews/gramineproject/gramine/764#-N7R-xEYD0BhhCAdJWfM:-N7R-xEYD0BhhCAdJWfN:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/4be842efab365bd43a15fa7bfebcba8087657b76/pal/src/host/linux-sgx/pal_files.c#L653)):*
> ```C
>         free((void*)handle->dir.realpath);
>         handle->dir.realpath = NULL;
>     }
> ```





_Suggestion:_
```C
    free(handle->dir.realpath);
```
___
*[`pal/src/host/linux-sgx/pal_files.c` line 682 at r3](https://reviewable.io/reviews/gramineproject/gramine/764#-N7R0LE97_aPbDUiR3rI:-N7R0LE97_aPbDUiR3rJ:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/4be842efab365bd43a15fa7bfebcba8087657b76/pal/src/host/linux-sgx/pal_files.c#L682)):*
> ```C
>     }
> 
>     free((void*)handle->dir.realpath);
> ```





_Suggestion:_
```C
free(handle->dir.realpath);
```


<!-- Sent from Reviewable.io -->

2022-07-20 14:39 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/764)* status: all files reviewed, 20 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @guzongmin, and @yao-ji)

___
*[`pal/src/host/linux/pal_files.c` line 235 at r1](https://reviewable.io/reviews/gramineproject/gramine/764#-N7F_IlcCMSD_GI66p_r:-N7R0teDE2oatrIzPVpb:b-uf00h4) ([raw file](https://github.com/gramineproject/gramine/blob/177e71bc42f4d4996469b470bd6f4966008ddb6b/pal/src/host/linux/pal_files.c#L235)):*
> So I think you'd better set the point to NULL after free it.

Overall I like this pattern, but you should use it when it's actually worth it - in complex functions, where it's not obvious what happens later with that pointer. It makes no sense if it's overwritten right on the next line and it only makes this function look weird :)

> we know that `handle->file.realpath` is for sure not NULL

Even without this knowledge the `if` doesn't make sense here - `free()` is defined to be a no-op for `NULL`, and it's a common idiom in C to skip that unneeded check.


<!-- Sent from Reviewable.io -->

2022-07-22 05:46 UTC, yao-ji reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/764)* status: 1 of 6 files reviewed, 20 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @guzongmin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/764#-N7QcZLhAf-LgmjtdRkk:-N7ZLMOB4l4dUJIQEPSL:b4sli1v) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I don't think it did.

@yao-ji You didn't check all usages of `file.realpath` and `dir.realpath`, e.g. you need to fix `pal/src/host/linux/pal_streams.c`
</blockquote></details>

The failure is reproduced in the Bash example, but using the second command in the Readme `gramine-direct ./bash -c "cd scripts && bash bash_test.sh 2"`, not the first one, @dimakuv. Failure also exists in `gramine-sgx`. 

And yes, @boryspoplawski is right, problem is in the `pal_stream.c`. `file.realpath` and `dir.realpath` also need to be changed in the `handle_deserialize()`. Please review the fixup commit.

___
___
*[`-- commits` line 6 at r3](https://reviewable.io/reviews/gramineproject/gramine/764#-N7QzHxD5nZKs4tqcu7X):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

What is this comment about? Stale from some intermediate version?
</blockquote></details>

Yes, this comment can be discarded. Same as the sentence "We also set the pointer to `NULL` after free to avoid double free." in the last paragraph.
___
*[`pal/regression/Directory.c` line 104 at r3](https://reviewable.io/reviews/gramineproject/gramine/764#-N7QuO9bCRdgSR5mMps9:-N7ZOKgKBleLYs7xYmCV:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/4be842efab365bd43a15fa7bfebcba8087657b76/pal/regression/Directory.c#L104)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please print `ret` value here
</blockquote></details>

Done.
___
*[`pal/regression/Directory.c` line 109 at r3](https://reviewable.io/reviews/gramineproject/gramine/764#-N7QuPuQ1gzYRm5L-0OC:-N7ZOMnECIhNo34BldBa:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/4be842efab365bd43a15fa7bfebcba8087657b76/pal/regression/Directory.c#L109)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`pal/src/host/linux/pal_files.c` line 127 at r3](https://reviewable.io/reviews/gramineproject/gramine/764#-N7Qvhpd8-HNVqndbBZf:-N7ZOOljAt-1qjzd45HK:bb1tr6s) ([raw file](https://github.com/gramineproject/gramine/blob/4be842efab365bd43a15fa7bfebcba8087657b76/pal/src/host/linux/pal_files.c#L127)):*
> ```C
>         free((void*)handle->file.realpath);
>         handle->file.realpath = NULL;
>     }
> ```

`handle->file.realpath` is `const char*`. Typecast is needed.
___
*[`pal/src/host/linux/pal_files.c` line 238 at r3](https://reviewable.io/reviews/gramineproject/gramine/764#-N7Qw7_8DmOXb2EmkhjP:-N7ZP3La-7xFX4_m_Ams:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/4be842efab365bd43a15fa7bfebcba8087657b76/pal/src/host/linux/pal_files.c#L238)):*
> ```C
>     }
> 
>     free((void*)handle->file.realpath);
> ```

ditto
___
*[`pal/src/host/linux/pal_files.c` line 424 at r3](https://reviewable.io/reviews/gramineproject/gramine/764#-N7QxVZK-o4zYzeVPyvY:-N7ZP6ny66rHXycahAat:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/4be842efab365bd43a15fa7bfebcba8087657b76/pal/src/host/linux/pal_files.c#L424)):*
> ```C
>         free((void*)handle->dir.realpath);
>         handle->dir.realpath = NULL;
>     }
> ```

ditto
___
*[`pal/src/host/linux/pal_files.c` line 456 at r3](https://reviewable.io/reviews/gramineproject/gramine/764#-N7Qy28R7JWm5wSu91em:-N7ZPNA_1VUapv0d0iWe:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/4be842efab365bd43a15fa7bfebcba8087657b76/pal/src/host/linux/pal_files.c#L456)):*
> ```C
>     }
> 
>     free((void*)handle->dir.realpath);
> ```

ditto
___
*[`pal/src/host/linux-sgx/pal_files.c` line 160 at r3](https://reviewable.io/reviews/gramineproject/gramine/764#-N7R-6oA4wEoBk8s9R10:-N7ZPOiG04wuQuCwwubw:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/4be842efab365bd43a15fa7bfebcba8087657b76/pal/src/host/linux-sgx/pal_files.c#L160)):*
> ```C
>     if (hdl->file.realpath) {
>         free((void*)hdl->file.realpath);
>     }
> ```

ditto
___
*[`pal/src/host/linux-sgx/pal_files.c` line 239 at r3](https://reviewable.io/reviews/gramineproject/gramine/764#-N7R-IbB4hT6r7-anXir:-N7ZPR418Cm6i-wKpPXq:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/4be842efab365bd43a15fa7bfebcba8087657b76/pal/src/host/linux-sgx/pal_files.c#L239)):*
> ```C
>         free((void*)handle->file.realpath);
>         handle->file.realpath = NULL;
>     }
> ```

ditto
___
*[`pal/src/host/linux-sgx/pal_files.c` line 464 at r3](https://reviewable.io/reviews/gramineproject/gramine/764#-N7R-XFH7LZ-EgL3SNx9:-N7ZPUhv5R9ojknE0NNA:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/4be842efab365bd43a15fa7bfebcba8087657b76/pal/src/host/linux-sgx/pal_files.c#L464)):*
> ```C
>     }
> 
>     free((void*)handle->file.realpath);
> ```

ditto
___
*[`pal/src/host/linux-sgx/pal_files.c` line 542 at r3](https://reviewable.io/reviews/gramineproject/gramine/764#-N7R-jOTANoXz5dlr-nH:-N7ZRKRH72kGNr85lnnz:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/4be842efab365bd43a15fa7bfebcba8087657b76/pal/src/host/linux-sgx/pal_files.c#L542)):*
> ```C
>     hdl->dir.fd = fd;
> 
>     char* path  = strdup(uri);
> ```

Done.
___
*[`pal/src/host/linux-sgx/pal_files.c` line 653 at r3](https://reviewable.io/reviews/gramineproject/gramine/764#-N7R-xEYD0BhhCAdJWfM:-N7ZRLUX1CCQ9jTE-__N:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/4be842efab365bd43a15fa7bfebcba8087657b76/pal/src/host/linux-sgx/pal_files.c#L653)):*
> ```C
>         free((void*)handle->dir.realpath);
>         handle->dir.realpath = NULL;
>     }
> ```

ditto
___
*[`pal/src/host/linux-sgx/pal_files.c` line 682 at r3](https://reviewable.io/reviews/gramineproject/gramine/764#-N7R0LE97_aPbDUiR3rI:-N7ZRN4p6-jwQJOEWyLr:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/4be842efab365bd43a15fa7bfebcba8087657b76/pal/src/host/linux-sgx/pal_files.c#L682)):*
> ```C
>     }
> 
>     free((void*)handle->dir.realpath);
> ```

ditto


<!-- Sent from Reviewable.io -->

2022-07-22 05:56 UTC, guzongmin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/764)* status: 1 of 6 files reviewed, 23 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @guzongmin, and @yao-ji)

___
*[`pal/src/host/linux-sgx/pal_streams.c` line 122 at r4](https://reviewable.io/reviews/gramineproject/gramine/764#-N7ZRmJS7DJQX4IFrTws:-N7ZRmJS7DJQX4IFrTwt:b2h68nb) ([raw file](https://github.com/gramineproject/gramine/blob/8db56fc99d837bbb039ff86d604b6c67cc60d88a/pal/src/host/linux-sgx/pal_streams.c#L122)):*
> ```C
>     PAL_HANDLE hdl = NULL;
>     size_t hdlsz = handle_size((PAL_HANDLE)data);
>     void* d = NULL;
> ```

Can you please use a more meaningful name?
___
*[`pal/src/host/linux-sgx/pal_streams.c` line 151 at r4](https://reviewable.io/reviews/gramineproject/gramine/764#-N7ZS3NU8BNef9LCM1yh:-N7ZS3NU8BNef9LCM1yi:brpzn3k) ([raw file](https://github.com/gramineproject/gramine/blob/8db56fc99d837bbb039ff86d604b6c67cc60d88a/pal/src/host/linux-sgx/pal_streams.c#L151)):*
> ```C
>     switch (PAL_GET_TYPE(hdl)) {
>         case PAL_TYPE_FILE:
>             hdl->file.realpath = hdl->file.realpath ? (const char*)d : NULL;
> ```

Is it a memory leak if the hdl->file.realpath is not NULL?
___
*[`pal/src/host/linux-sgx/pal_streams.c` line 197 at r4](https://reviewable.io/reviews/gramineproject/gramine/764#-N7ZSuev44nuc1iyVh4y:-N7ZSuev44nuc1iyVh4z:bau7qox) ([raw file](https://github.com/gramineproject/gramine/blob/8db56fc99d837bbb039ff86d604b6c67cc60d88a/pal/src/host/linux-sgx/pal_streams.c#L197)):*
> ```C
>     }
> 
>     *handle = hdl;
> ```

Do you need to do something for "d"? In some cases, the "d" referenced buffer is not used.


<!-- Sent from Reviewable.io -->

2022-07-22 06:13 UTC, yao-ji reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/764)* status: 1 of 6 files reviewed, 23 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @guzongmin)

___
*[`pal/src/host/linux-sgx/pal_streams.c` line 122 at r4](https://reviewable.io/reviews/gramineproject/gramine/764#-N7ZRmJS7DJQX4IFrTws:-N7ZVpnk-7a87zPap0XF:beicu0x) ([raw file](https://github.com/gramineproject/gramine/blob/8db56fc99d837bbb039ff86d604b6c67cc60d88a/pal/src/host/linux-sgx/pal_streams.c#L122)):*
<details><summary><i>Previously, guzongmin (Zongmin.Gu) wrote…</i></summary><blockquote>

Can you please use a more meaningful name?
</blockquote></details>

It is aligned with the name used in the `handle_serialize()` function.
___
*[`pal/src/host/linux-sgx/pal_streams.c` line 151 at r4](https://reviewable.io/reviews/gramineproject/gramine/764#-N7ZS3NU8BNef9LCM1yh:-N7ZW4pP3yRJINXb9adR:b-5n0aw4) ([raw file](https://github.com/gramineproject/gramine/blob/8db56fc99d837bbb039ff86d604b6c67cc60d88a/pal/src/host/linux-sgx/pal_streams.c#L151)):*
<details><summary><i>Previously, guzongmin (Zongmin.Gu) wrote…</i></summary><blockquote>

Is it a memory leak if the hdl->file.realpath is not NULL?
</blockquote></details>

`hdl` comes from the serialized data buffer. So if `hdl->file.realpath` is not `NULL`, it will be pointing to a meaningless address and must be reassigned to a new meaningful address.
___
*[`pal/src/host/linux-sgx/pal_streams.c` line 197 at r4](https://reviewable.io/reviews/gramineproject/gramine/764#-N7ZSuev44nuc1iyVh4y:-N7ZVQIL9OLbG1QyFdwq:br2u8n8) ([raw file](https://github.com/gramineproject/gramine/blob/8db56fc99d837bbb039ff86d604b6c67cc60d88a/pal/src/host/linux-sgx/pal_streams.c#L197)):*
<details><summary><i>Previously, guzongmin (Zongmin.Gu) wrote…</i></summary><blockquote>

Do you need to do something for "d"? In some cases, the "d" referenced buffer is not used.
</blockquote></details>

If `d` is not used, it will remain `NULL`, otherwise `d` is handled in the switch cases above.


<!-- Sent from Reviewable.io -->

2022-07-22 07:17 UTC, yao-ji reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/764)* status: 1 of 6 files reviewed, 23 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @guzongmin)

___
*[`pal/src/host/linux-sgx/pal_streams.c` line 197 at r4](https://reviewable.io/reviews/gramineproject/gramine/764#-N7ZSuev44nuc1iyVh4y:-N7ZkedR1AieARKM67ik:b-6ac5lf) ([raw file](https://github.com/gramineproject/gramine/blob/8db56fc99d837bbb039ff86d604b6c67cc60d88a/pal/src/host/linux-sgx/pal_streams.c#L197)):*
<details><summary><i>Previously, yao-ji wrote…</i></summary><blockquote>

If `d` is not used, it will remain `NULL`, otherwise `d` is handled in the switch cases above.
</blockquote></details>

Revised in the new fixup commit. `d` is only allocated in the `file` and `dir` type handle.


<!-- Sent from Reviewable.io -->

2022-07-22 07:48 UTC, guzongmin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/764)* status: 1 of 6 files reviewed, 21 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @guzongmin, and @yao-ji)

___
*[`pal/src/host/linux-sgx/pal_streams.c` line 127 at r5](https://reviewable.io/reviews/gramineproject/gramine/764#-N7Zs-gm4G7a-8eACHzm:-N7Zs-gm4G7a-8eACHzn:b-iq3r0u) ([raw file](https://github.com/gramineproject/gramine/blob/6768098fadbc5256280f1d2e194ce346c020deb8/pal/src/host/linux-sgx/pal_streams.c#L127)):*
> ```C
>     if (size > hdlsz) {
>         dsz = size - hdlsz;
>         size = hdlsz;
> ```

I prefer to use a new local variable instead of modifying the incoming parameter "size."


<!-- Sent from Reviewable.io -->

2022-07-22 08:25 UTC, dimakuv requested changes
> Reviewed 3 of 5 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/764)* status: all files reviewed, 26 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @guzongmin, @mkow, and @yao-ji)

___
*[`pal/regression/Directory.c` line 104 at r3](https://reviewable.io/reviews/gramineproject/gramine/764#-N7QuO9bCRdgSR5mMps9:-N7ZwLPbAFcWnq_KW481:b-pjses8) ([raw file](https://github.com/gramineproject/gramine/blob/4be842efab365bd43a15fa7bfebcba8087657b76/pal/regression/Directory.c#L104)):*
<details><summary><i>Previously, yao-ji wrote…</i></summary><blockquote>

Done.
</blockquote></details>

`,` -> `:`
___
*[`pal/regression/Directory.c` line 109 at r3](https://reviewable.io/reviews/gramineproject/gramine/764#-N7QuPuQ1gzYRm5L-0OC:-N7ZwMwr2-VpvD33KhC0:b-pjses8) ([raw file](https://github.com/gramineproject/gramine/blob/4be842efab365bd43a15fa7bfebcba8087657b76/pal/regression/Directory.c#L109)):*
<details><summary><i>Previously, yao-ji wrote…</i></summary><blockquote>

Done.
</blockquote></details>

`,` -> `:`
___
*[`pal/src/host/linux/pal_files.c` line 127 at r3](https://reviewable.io/reviews/gramineproject/gramine/764#-N7Qvhpd8-HNVqndbBZf:-N7ZwdgDCRE411qw25Dy:bk9rc6r) ([raw file](https://github.com/gramineproject/gramine/blob/4be842efab365bd43a15fa7bfebcba8087657b76/pal/src/host/linux/pal_files.c#L127)):*
<details><summary><i>Previously, yao-ji wrote…</i></summary><blockquote>

`handle->file.realpath` is `const char*`. Typecast is needed.
</blockquote></details>

Hm, I wonder how to resolve such issues. For all practical purposes, `handle.file.realpath` is `const char*` (immutable). Only at the point of actual close/deletion of the handle, it should be freed. So to me, it seems reasonable to keep the current `const char*` type, and use explicit typecast at these `free()` points. @mkow @boryspoplawski @guzongmin What do you think?

I see there are some holy wars about this topic: https://stackoverflow.com/questions/2819535/unable-to-free-const-pointers-in-c (read the comments also, they are interesting).
___
*[`pal/src/host/linux/pal_streams.c` line 53 at r5](https://reviewable.io/reviews/gramineproject/gramine/764#-N7_-TWjE69-4uSr-Tsq:-N7_-TWjE69-4uSr-Tsr:bun6ffa) ([raw file](https://github.com/gramineproject/gramine/blob/6768098fadbc5256280f1d2e194ce346c020deb8/pal/src/host/linux/pal_streams.c#L53)):*
> ```C
> }
> 
> int handle_serialize(PAL_HANDLE handle, void** data) {
> ```

These `handle_serialize()` and `handle_deserialize()` functions are really old and ugly. Someone should refactor them (in a follow-up PR) to make them more readable, and also fix that XXX comment below.
___
*[`pal/src/host/linux/pal_streams.c` line 104 at r5](https://reviewable.io/reviews/gramineproject/gramine/764#-N7_-OX16B64z4swF1Qy:-N7_-OX23jTXQ2X1Rz32:b-toapz8) ([raw file](https://github.com/gramineproject/gramine/blob/6768098fadbc5256280f1d2e194ce346c020deb8/pal/src/host/linux/pal_streams.c#L104)):*
> ```C
> 
> int handle_deserialize(PAL_HANDLE* handle, const void* data, size_t size) {
>     PAL_HANDLE hdl = NULL;
> ```

See my comments for `linux-sgx/` and apply them here as well.
___
*[`pal/src/host/linux-sgx/pal_streams.c` line 122 at r4](https://reviewable.io/reviews/gramineproject/gramine/764#-N7ZRmJS7DJQX4IFrTws:-N7ZzNm91vBRllXuNRq8:b9xudmt) ([raw file](https://github.com/gramineproject/gramine/blob/8db56fc99d837bbb039ff86d604b6c67cc60d88a/pal/src/host/linux-sgx/pal_streams.c#L122)):*
<details><summary><i>Previously, yao-ji wrote…</i></summary><blockquote>

It is aligned with the name used in the `handle_serialize()` function.
</blockquote></details>

I suggest to remove `d` from here and define it directly inside each switch-case. Also, for each of those switch-cases, please use a better name than `d`. For example, for `PAL_TYPE_FILE` and `PAL_TYPE_DIR` you better name it `path`.
___
*[`pal/src/host/linux-sgx/pal_streams.c` line 121 at r5](https://reviewable.io/reviews/gramineproject/gramine/764#-N7ZzDisCGi-d0zeUR0T:-N7ZzDisCGi-d0zeUR0U:b-qtyr18) ([raw file](https://github.com/gramineproject/gramine/blob/6768098fadbc5256280f1d2e194ce346c020deb8/pal/src/host/linux-sgx/pal_streams.c#L121)):*
> ```C
>     int ret;
>     PAL_HANDLE hdl = NULL;
>     size_t hdlsz = handle_size((PAL_HANDLE)data);
> ```

Please rename to `hdl_size`
___
*[`pal/src/host/linux-sgx/pal_streams.c` line 127 at r5](https://reviewable.io/reviews/gramineproject/gramine/764#-N7Zs-gm4G7a-8eACHzm:-N7ZzhWb1Z0biIoBSVC4:bp5l2sa) ([raw file](https://github.com/gramineproject/gramine/blob/6768098fadbc5256280f1d2e194ce346c020deb8/pal/src/host/linux-sgx/pal_streams.c#L127)):*
<details><summary><i>Previously, guzongmin (Zongmin.Gu) wrote…</i></summary><blockquote>

I prefer to use a new local variable instead of modifying the incoming parameter "size."
</blockquote></details>

+1 to @guzongmin. Let's just use `hdlsz` (actually, I suggest to rename it to `hdl_size`) everywhere below in the code, rather than overriding the `size` value.
___
*[`pal/src/host/linux-sgx/pal_streams.c` line 128 at r5](https://reviewable.io/reviews/gramineproject/gramine/764#-N7_--qt0HTsB_RIaJfW:-N7_--qt0HTsB_RIaJfX:b97eipf) ([raw file](https://github.com/gramineproject/gramine/blob/6768098fadbc5256280f1d2e194ce346c020deb8/pal/src/host/linux-sgx/pal_streams.c#L128)):*
> ```C
>         dsz = size - hdlsz;
>         size = hdlsz;
>     }
> ```

I would remove this whole code snippet about `dsz` and just move the logic inside each switch-case.
___
*[`pal/src/host/linux-sgx/pal_streams.c` line 185 at r5](https://reviewable.io/reviews/gramineproject/gramine/764#-N7_-DbcB34r0coiAG1u:-N7_-Dbd8_FQ79ewyJjc:bwpurff) ([raw file](https://github.com/gramineproject/gramine/blob/6768098fadbc5256280f1d2e194ce346c020deb8/pal/src/host/linux-sgx/pal_streams.c#L185)):*
> ```C
>             ret = _PalStreamSecureInit(hdl, hdl->process.is_server, &hdl->process.session_key,
>                                        (LIB_SSL_CONTEXT**)&hdl->process.ssl_ctx,
>                                        (const uint8_t*)data + hdlsz, dsz);
> ```

I suggest to revert this `dsz` and keep the original `size - hdlsz`.

But the change from `hdl` -> `data` sounds good.


<!-- Sent from Reviewable.io -->

2022-07-22 13:23 UTC, boryspoplawski requested changes
> Reviewed 3 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/764)* status: all files reviewed, 26 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @guzongmin, @mkow, and @yao-ji)

___
*[`pal/src/host/linux/pal_files.c` line 127 at r3](https://reviewable.io/reviews/gramineproject/gramine/764#-N7Qvhpd8-HNVqndbBZf:-N7a-vV5CMRu9je1wQSt:bbo3lig) ([raw file](https://github.com/gramineproject/gramine/blob/4be842efab365bd43a15fa7bfebcba8087657b76/pal/src/host/linux/pal_files.c#L127)):*
The general problem is `const` in C have really two meanings:
- object pointed by this reference is immutable (e.g. in ro memory)
- this reference cannot change the object

(here reference = pointer)
Unfortunately we have to live with this.

> So to me, it seems reasonable to keep the current const char* type,

You could then do stuff like `handle->x = "CONST STRING"`, which would be obviously wrong and I can see that happening for some constant files (idk, `/dev/sgx` or something)

There is really no right or wrong here, but we need to decide which `const` interpretation we use (and then we cannot use it for the other one). I would stick to the first one, imo it's less error prone and simpler (and we cannot gain much from the 2nd, because, well, C).
___
*[`pal/src/host/linux/pal_streams.c` line 104 at r5](https://reviewable.io/reviews/gramineproject/gramine/764#-N7a33io5VD9YSN7Fs18:-N7a33ip7xXr6U1GrYUm:b-adxjkd) ([raw file](https://github.com/gramineproject/gramine/blob/6768098fadbc5256280f1d2e194ce346c020deb8/pal/src/host/linux/pal_streams.c#L104)):*
> ```C
> 
> int handle_deserialize(PAL_HANDLE* handle, const void* data, size_t size) {
>     PAL_HANDLE hdl = NULL;
> ```

Please move the declaration to the allocation line
___
*[`pal/src/host/linux/pal_streams.c` line 106 at r5](https://reviewable.io/reviews/gramineproject/gramine/764#-N7a38wRBjAjlgGrJxjj:-N7a38wRBjAjlgGrJxjk:b-bhouow) ([raw file](https://github.com/gramineproject/gramine/blob/6768098fadbc5256280f1d2e194ce346c020deb8/pal/src/host/linux/pal_streams.c#L106)):*
> ```C
>     PAL_HANDLE hdl = NULL;
>     size_t hdlsz = handle_size((PAL_HANDLE)data);
>     void* d = NULL;
> ```

What are these names? Please use something more meaningful (`d`, `dsz`, `hdlsz`)
___
*[`pal/src/host/linux/pal_streams.c` line 106 at r5](https://reviewable.io/reviews/gramineproject/gramine/764#-N7a3WP-9OKSzQ98ELQ0:-N7a3WP-9OKSzQ98ELQ1:b-ooi23x) ([raw file](https://github.com/gramineproject/gramine/blob/6768098fadbc5256280f1d2e194ce346c020deb8/pal/src/host/linux/pal_streams.c#L106)):*
> ```C
>     PAL_HANDLE hdl = NULL;
>     size_t hdlsz = handle_size((PAL_HANDLE)data);
>     void* d = NULL;
> ```

Why are these defined in the function scope? They are only used by specific blocks in `case`, just define them there (with proper names)


<!-- Sent from Reviewable.io -->

2022-07-23 19:06 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/764)* status: all files reviewed, 26 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @guzongmin, and @yao-ji)

___
*[`pal/src/host/linux/pal_files.c` line 127 at r3](https://reviewable.io/reviews/gramineproject/gramine/764#-N7Qvhpd8-HNVqndbBZf:-N7gPfsmEXcIpdgozb4H:b-8akep9) ([raw file](https://github.com/gramineproject/gramine/blob/4be842efab365bd43a15fa7bfebcba8087657b76/pal/src/host/linux/pal_files.c#L127)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

The general problem is `const` in C have really two meanings:
- object pointed by this reference is immutable (e.g. in ro memory)
- this reference cannot change the object

(here reference = pointer)
Unfortunately we have to live with this.

> So to me, it seems reasonable to keep the current const char* type,

You could then do stuff like `handle->x = "CONST STRING"`, which would be obviously wrong and I can see that happening for some constant files (idk, `/dev/sgx` or something)

There is really no right or wrong here, but we need to decide which `const` interpretation we use (and then we cannot use it for the other one). I would stick to the first one, imo it's less error prone and simpler (and we cannot gain much from the 2nd, because, well, C).
</blockquote></details>

To be a bit more accurate, in C the meaning of `const` is defined as  "object is immutable" for variable definitions, and as "this reference cannot change the object" for pointers. What Borys proposes is (I think) adding a convention to our codebase that const pointers have additional, purely conventional meaning: that you object pointed to by const pointers is immutable.
I'm not sure if we want to use this convention, it sounds problematic for many cases, e.g. our `strstartswith()` takes `const char*` arguments, but it doesn't mean that they are immutable, only that the function won't change them, and we rather don't want to remove consts and thus break this function for literal strings used as arguments.

Anyways, in this particular case I'm fine with both changing the field to `char*` and with casting on `free()`.


<!-- Sent from Reviewable.io -->

2022-07-23 20:07 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/764)* status: all files reviewed, 26 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @guzongmin, and @yao-ji)

___
*[`pal/src/host/linux/pal_files.c` line 127 at r3](https://reviewable.io/reviews/gramineproject/gramine/764#-N7Qvhpd8-HNVqndbBZf:-N7geBbiEq6qC042hSV9:b1rj91s) ([raw file](https://github.com/gramineproject/gramine/blob/4be842efab365bd43a15fa7bfebcba8087657b76/pal/src/host/linux/pal_files.c#L127)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

To be a bit more accurate, in C the meaning of `const` is defined as  "object is immutable" for variable definitions, and as "this reference cannot change the object" for pointers. What Borys proposes is (I think) adding a convention to our codebase that const pointers have additional, purely conventional meaning: that you object pointed to by const pointers is immutable.
I'm not sure if we want to use this convention, it sounds problematic for many cases, e.g. our `strstartswith()` takes `const char*` arguments, but it doesn't mean that they are immutable, only that the function won't change them, and we rather don't want to remove consts and thus break this function for literal strings used as arguments.

Anyways, in this particular case I'm fine with both changing the field to `char*` and with casting on `free()`.
</blockquote></details>

Yeah, I was too quick with such proposal, ignore it.

As for this case (where we want the content to be immutable once initiated): I prefer to use `char*` - I think it's easier to accidentally overwrite the pointer itself (e.g. `handle->x = "STR"`) than the content of the pointer (`handle->x[1] = 'a'`), and using `char*` prevents the former (using `const char*` would prevent the latter).


<!-- Sent from Reviewable.io -->

2022-07-25 06:46 UTC, yao-ji reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/764)* status: 3 of 6 files reviewed, 26 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @guzongmin, and @yao-ji)

___
*[`pal/regression/Directory.c` line 104 at r3](https://reviewable.io/reviews/gramineproject/gramine/764#-N7QuO9bCRdgSR5mMps9:-N7o4LdEB9EnEHeWRjQl:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/4be842efab365bd43a15fa7bfebcba8087657b76/pal/regression/Directory.c#L104)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`,` -> `:`
</blockquote></details>

Done.
___
*[`pal/regression/Directory.c` line 109 at r3](https://reviewable.io/reviews/gramineproject/gramine/764#-N7QuPuQ1gzYRm5L-0OC:-N7o4OSu38Q4IJkeTFmV:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/4be842efab365bd43a15fa7bfebcba8087657b76/pal/regression/Directory.c#L109)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`,` -> `:`
</blockquote></details>

Done.
___
*[`pal/src/host/linux/pal_streams.c` line 104 at r5](https://reviewable.io/reviews/gramineproject/gramine/764#-N7_-OX16B64z4swF1Qy:-N7o4js87kTo4OTtxfQ0:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/6768098fadbc5256280f1d2e194ce346c020deb8/pal/src/host/linux/pal_streams.c#L104)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

See my comments for `linux-sgx/` and apply them here as well.
</blockquote></details>

Done.
___
*[`pal/src/host/linux/pal_streams.c` line 104 at r5](https://reviewable.io/reviews/gramineproject/gramine/764#-N7a33io5VD9YSN7Fs18:-N7o4mfeAnJpqWnro90v:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/6768098fadbc5256280f1d2e194ce346c020deb8/pal/src/host/linux/pal_streams.c#L104)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please move the declaration to the allocation line
</blockquote></details>

Done.
___
*[`pal/src/host/linux/pal_streams.c` line 106 at r5](https://reviewable.io/reviews/gramineproject/gramine/764#-N7a38wRBjAjlgGrJxjj:-N7o53Eg7v6M3lfRH_hj:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/6768098fadbc5256280f1d2e194ce346c020deb8/pal/src/host/linux/pal_streams.c#L106)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

What are these names? Please use something more meaningful (`d`, `dsz`, `hdlsz`)
</blockquote></details>

Done.
___
*[`pal/src/host/linux/pal_streams.c` line 106 at r5](https://reviewable.io/reviews/gramineproject/gramine/764#-N7a3WP-9OKSzQ98ELQ0:-N7o53YYDL21xxN8v0NG:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/6768098fadbc5256280f1d2e194ce346c020deb8/pal/src/host/linux/pal_streams.c#L106)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why are these defined in the function scope? They are only used by specific blocks in `case`, just define them there (with proper names)
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/pal_streams.c` line 121 at r5](https://reviewable.io/reviews/gramineproject/gramine/764#-N7ZzDisCGi-d0zeUR0T:-N7o5GJo5RIbkLaROc2x:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/6768098fadbc5256280f1d2e194ce346c020deb8/pal/src/host/linux-sgx/pal_streams.c#L121)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please rename to `hdl_size`
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/pal_streams.c` line 127 at r5](https://reviewable.io/reviews/gramineproject/gramine/764#-N7Zs-gm4G7a-8eACHzm:-N7o5Pzv5HKRAatgXiY8:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/6768098fadbc5256280f1d2e194ce346c020deb8/pal/src/host/linux-sgx/pal_streams.c#L127)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

+1 to @guzongmin. Let's just use `hdlsz` (actually, I suggest to rename it to `hdl_size`) everywhere below in the code, rather than overriding the `size` value.
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/pal_streams.c` line 128 at r5](https://reviewable.io/reviews/gramineproject/gramine/764#-N7_--qt0HTsB_RIaJfW:-N7o5SNU9QDDfSgfzwFv:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/6768098fadbc5256280f1d2e194ce346c020deb8/pal/src/host/linux-sgx/pal_streams.c#L128)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I would remove this whole code snippet about `dsz` and just move the logic inside each switch-case.
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/pal_streams.c` line 185 at r5](https://reviewable.io/reviews/gramineproject/gramine/764#-N7_-DbcB34r0coiAG1u:-N7o5kd650ssUREW-b1I:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/6768098fadbc5256280f1d2e194ce346c020deb8/pal/src/host/linux-sgx/pal_streams.c#L185)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I suggest to revert this `dsz` and keep the original `size - hdlsz`.

But the change from `hdl` -> `data` sounds good.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-25 08:24 UTC, dimakuv reviewed
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/764)* status: all files reviewed, 22 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @guzongmin, and @yao-ji)

___
*[`pal/src/host/linux/pal_files.c` line 127 at r3](https://reviewable.io/reviews/gramineproject/gramine/764#-N7Qvhpd8-HNVqndbBZf:-N7oQy0W0bHZz_eOL0PE:b886lxy) ([raw file](https://github.com/gramineproject/gramine/blob/4be842efab365bd43a15fa7bfebcba8087657b76/pal/src/host/linux/pal_files.c#L127)):*
I can follow this discussion, but I don't get this last phrase from @boryspoplawski :

> using `char*` prevents the former

How does it prevent the former case (= `handle->x = "STR"`)? This type doesn't prevent anything. Or did you advocate for `char const*`? But then we're back to square one and we can't use `free()` (and many other standard funcs) without explicit typecast.


<!-- Sent from Reviewable.io -->

2022-07-25 11:21 UTC, boryspoplawski requested changes
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/764)* status: all files reviewed, 19 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @guzongmin, and @yao-ji)

___
*[`pal/src/host/linux/pal_files.c` line 127 at r3](https://reviewable.io/reviews/gramineproject/gramine/764#-N7Qvhpd8-HNVqndbBZf:-N7oz9pKAm0ZfJtrR7nN:b-22u3cl) ([raw file](https://github.com/gramineproject/gramine/blob/4be842efab365bd43a15fa7bfebcba8087657b76/pal/src/host/linux/pal_files.c#L127)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I can follow this discussion, but I don't get this last phrase from @boryspoplawski :

> using `char*` prevents the former

How does it prevent the former case (= `handle->x = "STR"`)? This type doesn't prevent anything. Or did you advocate for `char const*`? But then we're back to square one and we can't use `free()` (and many other standard funcs) without explicit typecast.
</blockquote></details>

`typeof("STR") == const char*` (because we request that from compiler), so it does prevent such assignment.
___
*[`pal/src/host/linux/pal_streams.c` line 113 at r6](https://reviewable.io/reviews/gramineproject/gramine/764#-N7p429B0SZMkMRJkT1O:-N7p429B0SZMkMRJkT1P:b-xlkvjp) ([raw file](https://github.com/gramineproject/gramine/blob/e141b6a87b75baf1c8e4857e4f876ecee15210af/pal/src/host/linux/pal_streams.c#L113)):*
> ```C
>     /* update handle fields to point to correct contents */
>     switch (PAL_GET_TYPE(hdl)) {
>         case PAL_TYPE_FILE: {
> ```

Please add `assert(hdl_size < size);`
___
*[`pal/src/host/linux-sgx/pal_streams.c` line 130 at r6](https://reviewable.io/reviews/gramineproject/gramine/764#-N7p4-sN7tooP-H-HJs6:-N7p4-sN7tooP-H-HJs7:b-xlkvjp) ([raw file](https://github.com/gramineproject/gramine/blob/e141b6a87b75baf1c8e4857e4f876ecee15210af/pal/src/host/linux-sgx/pal_streams.c#L130)):*
> ```C
>     /* update handle fields to point to correct contents */
>     switch (PAL_GET_TYPE(hdl)) {
>         case PAL_TYPE_FILE: {
> ```

Please add `assert(hdl_size < size);`


<!-- Sent from Reviewable.io -->

2022-07-25 12:32 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/764)* status: all files reviewed, 19 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @guzongmin, and @yao-ji)

___
*[`pal/src/host/linux/pal_files.c` line 127 at r3](https://reviewable.io/reviews/gramineproject/gramine/764#-N7Qvhpd8-HNVqndbBZf:-N7pKodo9DC1yEv4Eg20:bj1i7t2) ([raw file](https://github.com/gramineproject/gramine/blob/4be842efab365bd43a15fa7bfebcba8087657b76/pal/src/host/linux/pal_files.c#L127)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`typeof("STR") == const char*` (because we request that from compiler), so it does prevent such assignment.
</blockquote></details>

Ah, now I see.

Then we seem to have reached a consensus: `handle->file.realpath` should have a type `char*` (and the same for `dir` handle). @yao-ji Please change.


<!-- Sent from Reviewable.io -->

2022-07-26 02:44 UTC, yao-ji reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/764)* status: 2 of 8 files reviewed, 19 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @guzongmin)

___
*[`pal/src/host/linux/pal_files.c` line 127 at r3](https://reviewable.io/reviews/gramineproject/gramine/764#-N7Qvhpd8-HNVqndbBZf:-N7sKt1zE3DZJBa4magI:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/4be842efab365bd43a15fa7bfebcba8087657b76/pal/src/host/linux/pal_files.c#L127)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ah, now I see.

Then we seem to have reached a consensus: `handle->file.realpath` should have a type `char*` (and the same for `dir` handle). @yao-ji Please change.
</blockquote></details>

Done.
___
*[`pal/src/host/linux/pal_files.c` line 238 at r3](https://reviewable.io/reviews/gramineproject/gramine/764#-N7Qw7_8DmOXb2EmkhjP:-N7sL-cy0E6RAWgvtehq:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/4be842efab365bd43a15fa7bfebcba8087657b76/pal/src/host/linux/pal_files.c#L238)):*
<details><summary><i>Previously, yao-ji wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`pal/src/host/linux/pal_files.c` line 424 at r3](https://reviewable.io/reviews/gramineproject/gramine/764#-N7QxVZK-o4zYzeVPyvY:-N7sL4N74lFlZQc9Jn_A:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/4be842efab365bd43a15fa7bfebcba8087657b76/pal/src/host/linux/pal_files.c#L424)):*
<details><summary><i>Previously, yao-ji wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`pal/src/host/linux/pal_files.c` line 456 at r3](https://reviewable.io/reviews/gramineproject/gramine/764#-N7Qy28R7JWm5wSu91em:-N7sL8Pv2y915HLq8b4e:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/4be842efab365bd43a15fa7bfebcba8087657b76/pal/src/host/linux/pal_files.c#L456)):*
<details><summary><i>Previously, yao-ji wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`pal/src/host/linux/pal_streams.c` line 53 at r5](https://reviewable.io/reviews/gramineproject/gramine/764#-N7_-TWjE69-4uSr-Tsq:-N7sLXsp-quFGay7jpAn:beq5a9n) ([raw file](https://github.com/gramineproject/gramine/blob/6768098fadbc5256280f1d2e194ce346c020deb8/pal/src/host/linux/pal_streams.c#L53)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

These `handle_serialize()` and `handle_deserialize()` functions are really old and ugly. Someone should refactor them (in a follow-up PR) to make them more readable, and also fix that XXX comment below.
</blockquote></details>

I can also do it.
___
*[`pal/src/host/linux/pal_streams.c` line 113 at r6](https://reviewable.io/reviews/gramineproject/gramine/764#-N7p429B0SZMkMRJkT1O:-N7sLfKi-sbLb_DJlPxa:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/e141b6a87b75baf1c8e4857e4f876ecee15210af/pal/src/host/linux/pal_streams.c#L113)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please add `assert(hdl_size < size);`
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/pal_files.c` line 160 at r3](https://reviewable.io/reviews/gramineproject/gramine/764#-N7R-6oA4wEoBk8s9R10:-N7sLkHn94VbNYp-grHQ:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/4be842efab365bd43a15fa7bfebcba8087657b76/pal/src/host/linux-sgx/pal_files.c#L160)):*
<details><summary><i>Previously, yao-ji wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/pal_files.c` line 239 at r3](https://reviewable.io/reviews/gramineproject/gramine/764#-N7R-IbB4hT6r7-anXir:-N7sLmRVBlMJfA5_pNfp:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/4be842efab365bd43a15fa7bfebcba8087657b76/pal/src/host/linux-sgx/pal_files.c#L239)):*
<details><summary><i>Previously, yao-ji wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/pal_files.c` line 464 at r3](https://reviewable.io/reviews/gramineproject/gramine/764#-N7R-XFH7LZ-EgL3SNx9:-N7sMN2p-jMX0FShls2k:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/4be842efab365bd43a15fa7bfebcba8087657b76/pal/src/host/linux-sgx/pal_files.c#L464)):*
<details><summary><i>Previously, yao-ji wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/pal_files.c` line 653 at r3](https://reviewable.io/reviews/gramineproject/gramine/764#-N7R-xEYD0BhhCAdJWfM:-N7sMTjJ4TvD9gfGyXcF:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/4be842efab365bd43a15fa7bfebcba8087657b76/pal/src/host/linux-sgx/pal_files.c#L653)):*
<details><summary><i>Previously, yao-ji wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/pal_files.c` line 682 at r3](https://reviewable.io/reviews/gramineproject/gramine/764#-N7R0LE97_aPbDUiR3rI:-N7sMVKs1Y1jh4FRknz0:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/4be842efab365bd43a15fa7bfebcba8087657b76/pal/src/host/linux-sgx/pal_files.c#L682)):*
<details><summary><i>Previously, yao-ji wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/pal_streams.c` line 130 at r6](https://reviewable.io/reviews/gramineproject/gramine/764#-N7p4-sN7tooP-H-HJs6:-N7sMb7X5Bs8BrZuT4BN:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/e141b6a87b75baf1c8e4857e4f876ecee15210af/pal/src/host/linux-sgx/pal_streams.c#L130)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please add `assert(hdl_size < size);`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-26 06:33 UTC, dimakuv submitted a review, later dismissed
> Reviewed 6 of 6 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/764)* status: all files reviewed, 19 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @guzongmin, and @yao-ji)

___
*[`pal/src/host/linux/pal_streams.c` line 53 at r5](https://reviewable.io/reviews/gramineproject/gramine/764#-N7_-TWjE69-4uSr-Tsq:-N7tBkuI1R2Opg-dFKf8:b7w42g4) ([raw file](https://github.com/gramineproject/gramine/blob/6768098fadbc5256280f1d2e194ce346c020deb8/pal/src/host/linux/pal_streams.c#L53)):*
<details><summary><i>Previously, yao-ji wrote…</i></summary><blockquote>

I can also do it.
</blockquote></details>

Yes, please, after we merge this PR. Thanks!


<!-- Sent from Reviewable.io -->

2022-07-26 12:51 UTC, boryspoplawski approved these changes
> Reviewed 6 of 6 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/764)* status: all files reviewed, 8 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @guzongmin, and @yao-ji)



<!-- Sent from Reviewable.io -->

2022-07-26 13:23 UTC, dimakuv commented
Jenkins, test this please

2022-07-26 15:08 UTC, dimakuv reviewed
> Dismissed @guzongmin from 5 discussions.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/764)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2022-07-26 15:22 UTC, dimakuv approved these changes
> Reviewed 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/764)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/gramineproject/gramine/764#-N7Ka4OfCVM17Nywuq2g):*
<details><summary><i>Previously, yao-ji wrote…</i></summary><blockquote>

Thanks.
</blockquote></details>

Done
___
*[`-- commits` line 4 at r2](https://reviewable.io/reviews/gramineproject/gramine/764#-N7KaPDYCiFI0BWzva38):*
<details><summary><i>Previously, yao-ji wrote…</i></summary><blockquote>

Acknowledged. Thanks.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2022-07-26 15:23 UTC, dimakuv commented
Jenkins, test this please

2022-07-26 15:34 UTC, boryspoplawski approved these changes
> Reviewed 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/764)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-07-26 16:53 UTC, merged