[LibOS,PAL,common] Add `flags` line to `/proc/cpuinfo`
gramineproject/gramine pull request #768
Opened 2022-07-18 17:56 UTC by kailun-qin

Some workloads may require to parse the flags line in the pseudo-file
`/proc/cpuinfo`.

This patch
- removes `cpu_flags` from `pal_cpu_info` to keep the generality of PAL (i.e., to avoid emulating part of Linux-specific stuff in PAL, which should be done in LibOS instead)
- builds the `flags` line via performing `PalCpuIdRetrieve()` call when printing `/proc/cpuinfo`

Partially resolves https://github.com/gramineproject/gramine/issues/592.

2022-07-19 08:32 UTC, dimakuv requested changes
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/768)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @kailun-qin)

___
*[`common/include/arch/x86_64/cpu.h` line 107 at r1](https://reviewable.io/reviews/gramineproject/gramine/768#-N7KWm_G5HsrtOpS80A8:-N7KWm_G5HsrtOpS80A9:bvw5n5g) ([raw file](https://github.com/gramineproject/gramine/blob/8726998c049dfde241738006d5a99723407a9d67/common/include/arch/x86_64/cpu.h#L107)):*
> ```objc
> #define BPI  32
> #define POWER2(power) \
>     (1ULL << (power))
> ```

I would inline these two macros into `RIGHTMASK` and remove them. I don't even know what `BPI` is supposed to stand for (but logically it means "the upper limit for the bitmask to apply").
___
*[`common/include/arch/x86_64/cpu.h` line 111 at r1](https://reviewable.io/reviews/gramineproject/gramine/768#-N7KXosd0Kbb3KPNH1BT:-N7KXosd0Kbb3KPNH1BU:b-8b6fpl) ([raw file](https://github.com/gramineproject/gramine/blob/8726998c049dfde241738006d5a99723407a9d67/common/include/arch/x86_64/cpu.h#L111)):*
> ```objc
>     (((unsigned long)(width) >= BPI) ? ~0ULL : POWER2(width) - 1ULL)
> 
> #define BIT_EXTRACT_LE(value, start, after) \
> ```

The name of the macro is unreadable. What this macro does is "take a uin64_t value, and extract only the `[start, after)` bits from this value". I am unsure why it also has the suffix of "LE" (Little Endian), but ok.

So maybe rename to `EXTRACT_BITS_LE(value, start, end)`?

UPDATE: Hm, this is still used in the PAL code, so it will lead to too many changes. So, let's leave it as is. Ignore this comment.
___
*[`common/include/arch/x86_64/cpu.h` line 112 at r1](https://reviewable.io/reviews/gramineproject/gramine/768#-N7KUmFADFQ1XjCcFv1y:-N7KUmFB1KV4JaffLlzk:b-6h58sh) ([raw file](https://github.com/gramineproject/gramine/blob/8726998c049dfde241738006d5a99723407a9d67/common/include/arch/x86_64/cpu.h#L112)):*
> ```objc
> 
> #define BIT_EXTRACT_LE(value, start, after) \
>     (((unsigned long)(value) & RIGHTMASK(after)) >> start)
> ```

Could you re-format all these?

- They all can be put in one line (we have 100 char limit)
- `unsigned long` -> `uint64_t`
- `ULL` -> `UL`
___
*[`libos/include/arch/x86_64/libos_cpuid.h` line 5 at r1](https://reviewable.io/reviews/gramineproject/gramine/768#-N7KYeLp3a-VNFCKuOOZ:-N7KYeLp3a-VNFCKuOO_:b2d37u4) ([raw file](https://github.com/gramineproject/gramine/blob/8726998c049dfde241738006d5a99723407a9d67/libos/include/arch/x86_64/libos_cpuid.h#L5)):*
> ```objc
>  */
> 
> int libos_get_cpu_flags(const char** cpu_flags);
> ```

Could you add a quick comment that this function returns a new buffer with CPU flags, the caller is responsible to free it afterwards.
___
*[`libos/include/arch/x86_64/libos_cpuid.h` line 5 at r1](https://reviewable.io/reviews/gramineproject/gramine/768#-N7KYnif4EI36Dk03Fqz:-N7KYnif4EI36Dk03Fr-:bubcj0l) ([raw file](https://github.com/gramineproject/gramine/blob/8726998c049dfde241738006d5a99723407a9d67/libos/include/arch/x86_64/libos_cpuid.h#L5)):*
> ```objc
>  */
> 
> int libos_get_cpu_flags(const char** cpu_flags);
> ```

`cpu_flags` -> `out_cpu_flags` (by Gramine convention, all out-arguments are prefixed with `out_`)
___
*[`libos/src/arch/x86_64/fs_proc/info.c` line 52 at r1](https://reviewable.io/reviews/gramineproject/gramine/768#-N7KZRgoDTOSC-b0c7XU:-N7KZRgoDTOSC-b0c7XV:b-jtui73) ([raw file](https://github.com/gramineproject/gramine/blob/8726998c049dfde241738006d5a99723407a9d67/libos/src/arch/x86_64/fs_proc/info.c#L52)):*
> ```C
>     }
>     ADD_INFO("flags\t\t: %s\n", cpu_flags);
>     free((void*)cpu_flags);
> ```

Do you really need an explicit cast?
___
*[`pal/include/arch/x86_64/pal_arch.h` line 70 at r1](https://reviewable.io/reviews/gramineproject/gramine/768#-N7K_J0W7o6fnfxCQN0Q:-N7K_J0W7o6fnfxCQN0R:b7kowh9) ([raw file](https://github.com/gramineproject/gramine/blob/8726998c049dfde241738006d5a99723407a9d67/pal/include/arch/x86_64/pal_arch.h#L70)):*
> ```objc
>     uint64_t cpu_family;
>     uint64_t cpu_model;
>     uint64_t cpu_stepping;
> ```

I have a feeling that all these could also be moved away from PAL (except `cpu_bogomips` because it has special PAL-specific handling).

Would be good to move all these too, in a follow-up PR. Or are these variables used anywhere in PAL, so that they can't be moved? E.g., maybe we check `cpu_vendor` somewhere in our PAL logic...


<!-- Sent from Reviewable.io -->

2022-07-19 10:01 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/768)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

___
*[`common/include/arch/x86_64/cpu.h` line 107 at r1](https://reviewable.io/reviews/gramineproject/gramine/768#-N7KWm_G5HsrtOpS80A8:-N7KpTib94Gr7pvnIMoz:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/8726998c049dfde241738006d5a99723407a9d67/common/include/arch/x86_64/cpu.h#L107)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I would inline these two macros into `RIGHTMASK` and remove them. I don't even know what `BPI` is supposed to stand for (but logically it means "the upper limit for the bitmask to apply").
</blockquote></details>

Done.
___
*[`common/include/arch/x86_64/cpu.h` line 112 at r1](https://reviewable.io/reviews/gramineproject/gramine/768#-N7KUmFADFQ1XjCcFv1y:-N7KnykgCWeW9uSrqHh4:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/8726998c049dfde241738006d5a99723407a9d67/common/include/arch/x86_64/cpu.h#L112)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you re-format all these?

- They all can be put in one line (we have 100 char limit)
- `unsigned long` -> `uint64_t`
- `ULL` -> `UL`
</blockquote></details>

Done.
___
*[`libos/include/arch/x86_64/libos_cpuid.h` line 5 at r1](https://reviewable.io/reviews/gramineproject/gramine/768#-N7KYeLp3a-VNFCKuOOZ:-N7KpRM21g5b96C-kwRv:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/8726998c049dfde241738006d5a99723407a9d67/libos/include/arch/x86_64/libos_cpuid.h#L5)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you add a quick comment that this function returns a new buffer with CPU flags, the caller is responsible to free it afterwards.
</blockquote></details>

Done.
___
*[`libos/include/arch/x86_64/libos_cpuid.h` line 5 at r1](https://reviewable.io/reviews/gramineproject/gramine/768#-N7KYnif4EI36Dk03Fqz:-N7KpRao8wlLSEsznzao:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/8726998c049dfde241738006d5a99723407a9d67/libos/include/arch/x86_64/libos_cpuid.h#L5)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`cpu_flags` -> `out_cpu_flags` (by Gramine convention, all out-arguments are prefixed with `out_`)
</blockquote></details>

Done.
___
*[`libos/src/arch/x86_64/fs_proc/info.c` line 52 at r1](https://reviewable.io/reviews/gramineproject/gramine/768#-N7KZRgoDTOSC-b0c7XU:-N7KowoKCIih5rSEOmO5:b-yem71i) ([raw file](https://github.com/gramineproject/gramine/blob/8726998c049dfde241738006d5a99723407a9d67/libos/src/arch/x86_64/fs_proc/info.c#L52)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Do you really need an explicit cast?
</blockquote></details>

Yes, free is not allowed directly on a `const void*`.
___
*[`pal/include/arch/x86_64/pal_arch.h` line 70 at r1](https://reviewable.io/reviews/gramineproject/gramine/768#-N7K_J0W7o6fnfxCQN0Q:-N7Ko6oi16_0A0LB3avH:b-sxb7dy) ([raw file](https://github.com/gramineproject/gramine/blob/8726998c049dfde241738006d5a99723407a9d67/pal/include/arch/x86_64/pal_arch.h#L70)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I have a feeling that all these could also be moved away from PAL (except `cpu_bogomips` because it has special PAL-specific handling).

Would be good to move all these too, in a follow-up PR. Or are these variables used anywhere in PAL, so that they can't be moved? E.g., maybe we check `cpu_vendor` somewhere in our PAL logic...
</blockquote></details>

Yes, I think they can be also moved from PAL. I just followed the advice from mkow (https://github.com/gramineproject/gramine/pull/756#pullrequestreview-1042098578) to leave the others as they are in this PR.


<!-- Sent from Reviewable.io -->

2022-07-19 11:19 UTC, dimakuv approved these changes
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/768)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[`pal/include/arch/x86_64/pal_arch.h` line 70 at r1](https://reviewable.io/reviews/gramineproject/gramine/768#-N7K_J0W7o6fnfxCQN0Q:-N7LAe061eNVvL1_J19Z:bf9t8d6) ([raw file](https://github.com/gramineproject/gramine/blob/8726998c049dfde241738006d5a99723407a9d67/pal/include/arch/x86_64/pal_arch.h#L70)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Yes, I think they can be also moved from PAL. I just followed the advice from mkow (https://github.com/gramineproject/gramine/pull/756#pullrequestreview-1042098578) to leave the others as they are in this PR.
</blockquote></details>

Let's see what @mkow and @boryspoplawski will say on this. I'm not blocking.


<!-- Sent from Reviewable.io -->

2022-07-20 16:12 UTC, boryspoplawski requested changes
> Reviewed 5 of 8 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/768)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)

___
*[`common/include/arch/x86_64/cpu.h` line 111 at r1](https://reviewable.io/reviews/gramineproject/gramine/768#-N7KXosd0Kbb3KPNH1BT:-N7RGG4a7xxHRloL4GgH:bp3glw7) ([raw file](https://github.com/gramineproject/gramine/blob/8726998c049dfde241738006d5a99723407a9d67/common/include/arch/x86_64/cpu.h#L111)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

The name of the macro is unreadable. What this macro does is "take a uin64_t value, and extract only the `[start, after)` bits from this value". I am unsure why it also has the suffix of "LE" (Little Endian), but ok.

So maybe rename to `EXTRACT_BITS_LE(value, start, end)`?

UPDATE: Hm, this is still used in the PAL code, so it will lead to too many changes. So, let's leave it as is. Ignore this comment.
</blockquote></details>

But we shouldn't be exposing unreadable stuff just because it's already used somewhere.

Update: this is completely not needed, please remove it (i.e. leave it where it was before).
___
*[`common/include/arch/x86_64/cpu.h` line 105 at r2](https://reviewable.io/reviews/gramineproject/gramine/768#-N7RGeCq6__aXuVzli8e:-N7RGeCq6__aXuVzli8f:b6l6qyi) ([raw file](https://github.com/gramineproject/gramine/blob/98f2dcd9816a26e0e5f8783256e7aa86acc5d2bb/common/include/arch/x86_64/cpu.h#L105)):*
> ```objc
> #define WMB() __asm__ __volatile__("sfence" ::: "memory")
> 
> #define RIGHTMASK(width) (((uint64_t)(width) >= 32) ? ~0UL : (1UL << (width)) - 1UL)
> ```

What is this even supposed to do - why does it special case lengths `>= 32`?

Update: just remove it, see below.
___
*[`libos/src/arch/x86_64/libos_cpuid.c` line 44 at r2](https://reviewable.io/reviews/gramineproject/gramine/768#-N7RK4UGBCYXI9xg2ROE:-N7RK4UGBCYXI9xg2ROF:b-obkjgq) ([raw file](https://github.com/gramineproject/gramine/blob/98f2dcd9816a26e0e5f8783256e7aa86acc5d2bb/libos/src/arch/x86_64/libos_cpuid.c#L44)):*
> ```C
> };
> 
> int libos_get_cpu_flags(const char** out_cpu_flags) {
> ```

Returned string is not actually `const`.



_Suggestion:_
```C
int libos_get_cpu_flags(char** out_cpu_flags)
```
___
*[`libos/src/arch/x86_64/libos_cpuid.c` line 46 at r2](https://reviewable.io/reviews/gramineproject/gramine/768#-N7RLxCR09ElF6c7E2As:-N7RLxCR09ElF6c7E2At:b-ogxt15) ([raw file](https://github.com/gramineproject/gramine/blob/98f2dcd9816a26e0e5f8783256e7aa86acc5d2bb/libos/src/arch/x86_64/libos_cpuid.c#L46)):*
> ```C
> int libos_get_cpu_flags(const char** out_cpu_flags) {
>     unsigned int words[CPUID_WORD_NUM];
>     int rv = 0;
> ```

Compilers can spot all uninitialized usages, so let's leverage that.
I would also rename to `ret` for uniformity with rest of the codebase (but not insisting on that).



_Suggestion:_
```C
int rv;
```
___
*[`libos/src/arch/x86_64/libos_cpuid.c` line 47 at r2](https://reviewable.io/reviews/gramineproject/gramine/768#-N7RLp_LBzb0GvVfqlov:-N7RLp_M4MJ1AjhAAenr:bbtd70c) ([raw file](https://github.com/gramineproject/gramine/blob/98f2dcd9816a26e0e5f8783256e7aa86acc5d2bb/libos/src/arch/x86_64/libos_cpuid.c#L47)):*
> ```C
>     unsigned int words[CPUID_WORD_NUM];
>     int rv = 0;
>     char* flags = NULL;
> ```

Please move to the line with `malloc`
___
*[`libos/src/arch/x86_64/libos_cpuid.c` line 49 at r2](https://reviewable.io/reviews/gramineproject/gramine/768#-N7RMJe74ibYh_lmEVVB:-N7RMJe83jwtRWDZzQ09:b-8dykqo) ([raw file](https://github.com/gramineproject/gramine/blob/98f2dcd9816a26e0e5f8783256e7aa86acc5d2bb/libos/src/arch/x86_64/libos_cpuid.c#L49)):*
> ```C
>     char* flags = NULL;
> 
>     PalCpuIdRetrieve(1, 0, words);
> ```

Error checks missing.
___
*[`libos/src/arch/x86_64/libos_cpuid.c` line 63 at r2](https://reviewable.io/reviews/gramineproject/gramine/768#-N7RLPoBDdcJTsFW9Kll:-N7RLPoBDdcJTsFW9Klm:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/98f2dcd9816a26e0e5f8783256e7aa86acc5d2bb/libos/src/arch/x86_64/libos_cpuid.c#L63)):*
> ```C
>             continue;
> 
>         if (BIT_EXTRACT_LE(words[CPUID_WORD_EDX], i, i + 1)) {
> ```





_Suggestion:_
```C
if ((words[CPUID_WORD_EDX] >> i) & 1) {
```
___
*[`libos/src/arch/x86_64/fs_proc/info.c` line 52 at r1](https://reviewable.io/reviews/gramineproject/gramine/768#-N7KZRgoDTOSC-b0c7XU:-N7RHjDZCGLtOWBMntC6:boicd2c) ([raw file](https://github.com/gramineproject/gramine/blob/8726998c049dfde241738006d5a99723407a9d67/libos/src/arch/x86_64/fs_proc/info.c#L52)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Yes, free is not allowed directly on a `const void*`.
</blockquote></details>

Exactly. This should have never been `const` in the first place. If you ever end up doing `free` on `const` pointer, then there is something wrong with the code.



_Suggestion:_
```C
free(cpu_flags);
```
___
*[`pal/include/arch/x86_64/pal_arch.h` line 70 at r1](https://reviewable.io/reviews/gramineproject/gramine/768#-N7K_J0W7o6fnfxCQN0Q:-N7RI7z00-YFH205rBc-:b-kxjbch) ([raw file](https://github.com/gramineproject/gramine/blob/8726998c049dfde241738006d5a99723407a9d67/pal/include/arch/x86_64/pal_arch.h#L70)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Let's see what @mkow and @boryspoplawski will say on this. I'm not blocking.
</blockquote></details>

Well, it's hard question. Conceptually arch is different from host backed (PAL actually), but it's not completely orthogonal. It's good to have stuff separated from PAL if it makes sense (e.g. as it made with flags, which were retrieved using `cpuid`). On the other hand, if getting something is PAL specific (e.g. as getting `bogomips` is), then moving this from PAL would just require creating a getter function in PAL API, which is counter productive. So then there is a question - what do we split and why? Here we split flags because we now build them on demand, so it makes sense, but just moving stuff to common/LibOS might not.

Anyway, that's definitely not for this PR.


<!-- Sent from Reviewable.io -->

2022-07-20 16:30 UTC, dimakuv submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/768)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @kailun-qin)

___
*[`common/include/arch/x86_64/cpu.h` line 111 at r1](https://reviewable.io/reviews/gramineproject/gramine/768#-N7KXosd0Kbb3KPNH1BT:-N7RRFsYEFOTRN6W6dfn:b-pbdqz3) ([raw file](https://github.com/gramineproject/gramine/blob/8726998c049dfde241738006d5a99723407a9d67/common/include/arch/x86_64/cpu.h#L111)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

But we shouldn't be exposing unreadable stuff just because it's already used somewhere.

Update: this is completely not needed, please remove it (i.e. leave it where it was before).
</blockquote></details>

Agreed.
___
*[`common/include/arch/x86_64/cpu.h` line 105 at r2](https://reviewable.io/reviews/gramineproject/gramine/768#-N7RGeCq6__aXuVzli8e:-N7RQzp-6SyGAUyoIYvX:b-68wqrs) ([raw file](https://github.com/gramineproject/gramine/blob/98f2dcd9816a26e0e5f8783256e7aa86acc5d2bb/common/include/arch/x86_64/cpu.h#L105)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

What is this even supposed to do - why does it special case lengths `>= 32`?

Update: just remove it, see below.
</blockquote></details>

I think the only reason is because it is used for CPUID return values, and they are `uint32_t`. So this special case was like a defence from weird `width` values. But I agree, we can just replace these macros with a simpler bit twiddling that Borys proposed in another comment.


<!-- Sent from Reviewable.io -->

2022-07-21 04:24 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/768)* status: 3 of 8 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[`libos/src/arch/x86_64/libos_cpuid.c` line 44 at r2](https://reviewable.io/reviews/gramineproject/gramine/768#-N7RK4UGBCYXI9xg2ROE:-N7TvOjy6FuuLp-NAKLN:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/98f2dcd9816a26e0e5f8783256e7aa86acc5d2bb/libos/src/arch/x86_64/libos_cpuid.c#L44)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Returned string is not actually `const`.
</blockquote></details>

Done.
___
*[`libos/src/arch/x86_64/libos_cpuid.c` line 46 at r2](https://reviewable.io/reviews/gramineproject/gramine/768#-N7RLxCR09ElF6c7E2As:-N7TvQKQ-Nc8qnuOBvCD:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/98f2dcd9816a26e0e5f8783256e7aa86acc5d2bb/libos/src/arch/x86_64/libos_cpuid.c#L46)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Compilers can spot all uninitialized usages, so let's leverage that.
I would also rename to `ret` for uniformity with rest of the codebase (but not insisting on that).
</blockquote></details>

Done.
___
*[`libos/src/arch/x86_64/libos_cpuid.c` line 47 at r2](https://reviewable.io/reviews/gramineproject/gramine/768#-N7RLp_LBzb0GvVfqlov:-N7TvY9o7WX-SpEz7iHr:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/98f2dcd9816a26e0e5f8783256e7aa86acc5d2bb/libos/src/arch/x86_64/libos_cpuid.c#L47)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please move to the line with `malloc`
</blockquote></details>

Done.
___
*[`libos/src/arch/x86_64/libos_cpuid.c` line 49 at r2](https://reviewable.io/reviews/gramineproject/gramine/768#-N7RMJe74ibYh_lmEVVB:-N7TwlM96oOKOgKDjOFp:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/98f2dcd9816a26e0e5f8783256e7aa86acc5d2bb/libos/src/arch/x86_64/libos_cpuid.c#L49)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Error checks missing.
</blockquote></details>

Done.
___
*[`libos/src/arch/x86_64/libos_cpuid.c` line 63 at r2](https://reviewable.io/reviews/gramineproject/gramine/768#-N7RLPoBDdcJTsFW9Kll:-N7TvyHb4E2M2V_XnYNh:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/98f2dcd9816a26e0e5f8783256e7aa86acc5d2bb/libos/src/arch/x86_64/libos_cpuid.c#L63)):*
> ```C
>             continue;
> 
>         if (BIT_EXTRACT_LE(words[CPUID_WORD_EDX], i, i + 1)) {
> ```

Done.
___
*[`libos/src/arch/x86_64/fs_proc/info.c` line 52 at r1](https://reviewable.io/reviews/gramineproject/gramine/768#-N7KZRgoDTOSC-b0c7XU:-N7Tw0Yw9e5qk4FsPQ0y:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/8726998c049dfde241738006d5a99723407a9d67/libos/src/arch/x86_64/fs_proc/info.c#L52)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Exactly. This should have never been `const` in the first place. If you ever end up doing `free` on `const` pointer, then there is something wrong with the code.
</blockquote></details>

Done.
___
*[`common/include/arch/x86_64/cpu.h` line 111 at r1](https://reviewable.io/reviews/gramineproject/gramine/768#-N7KXosd0Kbb3KPNH1BT:-N7TvNbq-JFzqBlS-OVS:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/8726998c049dfde241738006d5a99723407a9d67/common/include/arch/x86_64/cpu.h#L111)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Agreed.
</blockquote></details>

Done.
___
*[`common/include/arch/x86_64/cpu.h` line 105 at r2](https://reviewable.io/reviews/gramineproject/gramine/768#-N7RGeCq6__aXuVzli8e:-N7TvMPgDlXEJtBfIEoB:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/98f2dcd9816a26e0e5f8783256e7aa86acc5d2bb/common/include/arch/x86_64/cpu.h#L105)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I think the only reason is because it is used for CPUID return values, and they are `uint32_t`. So this special case was like a defence from weird `width` values. But I agree, we can just replace these macros with a simpler bit twiddling that Borys proposed in another comment.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-21 07:55 UTC, dimakuv approved these changes
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/768)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)



<!-- Sent from Reviewable.io -->

2022-07-21 07:55 UTC, dimakuv commented
Jenkins, test this please

2022-07-21 08:44 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/768)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @kailun-qin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/768#-N7UvGdC8dcaeWfTaz39:-N7UvGdD65u6taLi0etO:bdbpii3) (no related file):*
Please fix this failure:
```
10:24:52  _______________________ TC_01_Bootstrap.test_102_cpuinfo _______________________
10:24:52  test_pal.py:121: in test_102_cpuinfo
10:24:52      self.assertIn('CPU flags: {[flags]}'.format(cpuinfo), stderr)
10:24:52  E   AssertionError: 'CPU flags: ' not found in 'User Program Started\n# of Arguments: 1\nargv[0] = Bootstrap\nParent Process: 0\nWritten to Debug Stream\nAllocation Alignment: 4096\nUser Address Range: 0x10000 - 0x7ffff7dd6000\nUser Address Range OK\nCPU num: 8\nCPU vendor: GenuineIntel\nCPU brand: Intel(R) Xeon(R) CPU           X5560  @ 2.80GHz\nCPU family: 6\nCPU model: 26\nCPU stepping: 5\n'
10:24:52  ----------------------------- Captured stderr call -----------------------------
10:24:52  [0.002] User Program Started
10:24:52  [0.002] # of Arguments: 1
10:24:52  [0.002] argv[0] = Bootstrap
10:24:52  [0.002] Parent Process: 0
10:24:52  [0.002] Written to Debug Stream
10:24:52  [0.002] Allocation Alignment: 4096
10:24:52  [0.002] User Address Range: 0x10000 - 0x7ffff7dd6000
10:24:52  [0.002] User Address Range OK
10:24:52  [0.002] CPU num: 8
10:24:52  [0.002] CPU vendor: GenuineIntel
10:24:52  [0.002] CPU brand: Intel(R) Xeon(R) CPU           X5560  @ 2.80GHz
10:24:52  [0.002] CPU family: 6
10:24:52  [0.002] CPU model: 26
10:24:52  [0.002] CPU stepping: 5
```

This is in PAL regression tests. Looks like you forgot to remove the corresponding flags-related code from the PAL test code (and `test_pal.py` script).

___


<!-- Sent from Reviewable.io -->

2022-07-21 09:43 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/768)* status: 8 of 10 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/768#-N7UvGdC8dcaeWfTaz39:-N7V7wzP2d2RQHUcQ9A7:b-896fix) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please fix this failure:
```
10:24:52  _______________________ TC_01_Bootstrap.test_102_cpuinfo _______________________
10:24:52  test_pal.py:121: in test_102_cpuinfo
10:24:52      self.assertIn('CPU flags: {[flags]}'.format(cpuinfo), stderr)
10:24:52  E   AssertionError: 'CPU flags: ' not found in 'User Program Started\n# of Arguments: 1\nargv[0] = Bootstrap\nParent Process: 0\nWritten to Debug Stream\nAllocation Alignment: 4096\nUser Address Range: 0x10000 - 0x7ffff7dd6000\nUser Address Range OK\nCPU num: 8\nCPU vendor: GenuineIntel\nCPU brand: Intel(R) Xeon(R) CPU           X5560  @ 2.80GHz\nCPU family: 6\nCPU model: 26\nCPU stepping: 5\n'
10:24:52  ----------------------------- Captured stderr call -----------------------------
10:24:52  [0.002] User Program Started
10:24:52  [0.002] # of Arguments: 1
10:24:52  [0.002] argv[0] = Bootstrap
10:24:52  [0.002] Parent Process: 0
10:24:52  [0.002] Written to Debug Stream
10:24:52  [0.002] Allocation Alignment: 4096
10:24:52  [0.002] User Address Range: 0x10000 - 0x7ffff7dd6000
10:24:52  [0.002] User Address Range OK
10:24:52  [0.002] CPU num: 8
10:24:52  [0.002] CPU vendor: GenuineIntel
10:24:52  [0.002] CPU brand: Intel(R) Xeon(R) CPU           X5560  @ 2.80GHz
10:24:52  [0.002] CPU family: 6
10:24:52  [0.002] CPU model: 26
10:24:52  [0.002] CPU stepping: 5
```

This is in PAL regression tests. Looks like you forgot to remove the corresponding flags-related code from the PAL test code (and `test_pal.py` script).
</blockquote></details>

Done.

___


<!-- Sent from Reviewable.io -->

2022-07-21 10:00 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/768)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @kailun-qin)

___
*[`libos/test/regression/proc_cpuinfo.c` line 19 at r4](https://reviewable.io/reviews/gramineproject/gramine/768#-N7VAs6pAv8CcprUecoA:-N7VAs6pAv8CcprUecoB:bcrk77w) ([raw file](https://github.com/gramineproject/gramine/blob/702ed961734e903797682205edbf4406c1369157/libos/test/regression/proc_cpuinfo.c#L19)):*
> ```C
>     int core_id;
>     int cpu_cores;
>     char flags[1000];
> ```

1. 1000 is not enough. I suggest 8KB (as a new macro `FLAGS_BUF_SIZE`). On my newer Intel CPUs, I observe >1000 chars in flags.
2. This will be allocated on stack, I don't like it, especially when we increase the size. I suggest to use `char* flags` and do `cpuinfo->flags = malloc(FLAGS_BUF_SIZE)` in the main function.
3. We don't currently test `flags` in any way. I suggest to add an x86-64-specific check in `check_cpuinfo()` with smth like `strstr(cpuinfo->flags, "fpu")` and maybe a couple other flags (`msr` and `apic` are too good examples).


<!-- Sent from Reviewable.io -->

2022-07-21 10:45 UTC, boryspoplawski requested changes
> Reviewed 5 of 5 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/768)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

___
*[`libos/src/arch/x86_64/libos_cpuid.c` line 83 at r2](https://reviewable.io/reviews/gramineproject/gramine/768#-N7RNASf0XW5KWCPmTXQ:-N7RNASf0XW5KWCPmTXR:b-348u8m) ([raw file](https://github.com/gramineproject/gramine/blob/98f2dcd9816a26e0e5f8783256e7aa86acc5d2bb/libos/src/arch/x86_64/libos_cpuid.c#L83)):*
> ```C
> 
>     flags[flen ? flen - 1 : 0] = 0;
>     log_error("flags: %s", flags);
> ```

???
(debugging print left? for that I recommend `log_always` :) )
___
*[`pal/regression/test_pal.py` line 121 at r4](https://reviewable.io/reviews/gramineproject/gramine/768#-N7VM-kf1koiNj_mswWS:-N7VM-kf1koiNj_mswWT:b-2nhxul) ([raw file](https://github.com/gramineproject/gramine/blob/931487a9e9931c403215c01095a7f824e772dd3d/pal/regression/test_pal.py#L121)):*
> ```Python
>         self.assertIn('CPU model: {[model]}'.format(cpuinfo), stderr)
>         self.assertIn('CPU stepping: {[stepping]}'.format(cpuinfo), stderr)
>         self.assertIn('CPU flags: {[flags]}'.format(cpuinfo), stderr)
> ```

We definitely need some flags testing (here or in the `.c` test itself)
___
*[`pal/src/arch/x86_64/pal_cpuid.c` line 6 at r4](https://reviewable.io/reviews/gramineproject/gramine/768#-N7VLp9D1HmncN93rm7F:-N7VLp9D1HmncN93rm7G:bdem702) ([raw file](https://github.com/gramineproject/gramine/blob/702ed961734e903797682205edbf4406c1369157/pal/src/arch/x86_64/pal_cpuid.c#L6)):*
> ```C
>  */
> 
> #include "cpu.h"
> ```

Do we need this include or leftover from intermediate version?


<!-- Sent from Reviewable.io -->

2022-07-21 12:12 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/768)* status: 8 of 10 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[`libos/src/arch/x86_64/libos_cpuid.c` line 83 at r2](https://reviewable.io/reviews/gramineproject/gramine/768#-N7RNASf0XW5KWCPmTXQ:-N7VdS_Y2_Xg7x7zmHjK:bvtk9z4) ([raw file](https://github.com/gramineproject/gramine/blob/98f2dcd9816a26e0e5f8783256e7aa86acc5d2bb/libos/src/arch/x86_64/libos_cpuid.c#L83)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

???
(debugging print left? for that I recommend `log_always` :) )
</blockquote></details>

Thanks ;)
___
*[`libos/test/regression/proc_cpuinfo.c` line 19 at r4](https://reviewable.io/reviews/gramineproject/gramine/768#-N7VAs6pAv8CcprUecoA:-N7VeVpSD0AI2cEilvff:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/702ed961734e903797682205edbf4406c1369157/libos/test/regression/proc_cpuinfo.c#L19)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

1. 1000 is not enough. I suggest 8KB (as a new macro `FLAGS_BUF_SIZE`). On my newer Intel CPUs, I observe >1000 chars in flags.
2. This will be allocated on stack, I don't like it, especially when we increase the size. I suggest to use `char* flags` and do `cpuinfo->flags = malloc(FLAGS_BUF_SIZE)` in the main function.
3. We don't currently test `flags` in any way. I suggest to add an x86-64-specific check in `check_cpuinfo()` with smth like `strstr(cpuinfo->flags, "fpu")` and maybe a couple other flags (`msr` and `apic` are too good examples).
</blockquote></details>

Done.
___
*[`pal/regression/test_pal.py` line 121 at r4](https://reviewable.io/reviews/gramineproject/gramine/768#-N7VM-kf1koiNj_mswWS:-N7Vdw-0-sLLqZRC4OpS:b3y5202) ([raw file](https://github.com/gramineproject/gramine/blob/931487a9e9931c403215c01095a7f824e772dd3d/pal/regression/test_pal.py#L121)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

We definitely need some flags testing (here or in the `.c` test itself)
</blockquote></details>

The flags testing has been added to the LibOS test.
___
*[`pal/src/arch/x86_64/pal_cpuid.c` line 6 at r4](https://reviewable.io/reviews/gramineproject/gramine/768#-N7VLp9D1HmncN93rm7F:-N7VeSmz-3Dz_-MCBJSR:bss4a2b) ([raw file](https://github.com/gramineproject/gramine/blob/702ed961734e903797682205edbf4406c1369157/pal/src/arch/x86_64/pal_cpuid.c#L6)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Do we need this include or leftover from intermediate version?
</blockquote></details>

Removed.


<!-- Sent from Reviewable.io -->

2022-07-21 12:25 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/768)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @kailun-qin)

___
*[`libos/test/regression/proc_cpuinfo.c` line 6 at r5](https://reviewable.io/reviews/gramineproject/gramine/768#-N7VhnTO4P9y7-O1gY71:-N7VhnTO4P9y7-O1gY72:b-jx1eae) ([raw file](https://github.com/gramineproject/gramine/blob/d777deb43b9ef90ef87696a83c2b536336c360b8/libos/test/regression/proc_cpuinfo.c#L6)):*
> ```C
> 
> #define CPUINFO_FILE   "/proc/cpuinfo"
> #define BUFFSIZE       (10 * 1024) /* 10KB */
> ```

Since we're here, can we rename to `BUF_SIZE`?
___
*[`libos/test/regression/proc_cpuinfo.c` line 10 at r5](https://reviewable.io/reviews/gramineproject/gramine/768#-N7VhRmq8j2-euSjHlBx:-N7VhRmq8j2-euSjHlBy:bltusyb) ([raw file](https://github.com/gramineproject/gramine/blob/d777deb43b9ef90ef87696a83c2b536336c360b8/libos/test/regression/proc_cpuinfo.c#L10)):*
> ```C
> #define NUM_TEST_FLAGS 3
> 
> static const char* const g_test_cpu_flags[NUM_TEST_FLAGS] = { "fpu", "msr", "apic" };
> ```

This should also be hidden under `#if defined(__x86_64__)`
___
*[`libos/test/regression/proc_cpuinfo.c` line 10 at r5](https://reviewable.io/reviews/gramineproject/gramine/768#-N7VhwaQCqFdT8huIWar:-N7VhwaQCqFdT8huIWas:b-2m23qe) ([raw file](https://github.com/gramineproject/gramine/blob/d777deb43b9ef90ef87696a83c2b536336c360b8/libos/test/regression/proc_cpuinfo.c#L10)):*
> ```C
> #define NUM_TEST_FLAGS 3
> 
> static const char* const g_test_cpu_flags[NUM_TEST_FLAGS] = { "fpu", "msr", "apic" };
> ```

Can you add a comment that this subset of flags is picked for testing, chosen to be available on any modern x86-64 CPU?
___
*[`libos/test/regression/proc_cpuinfo.c` line 159 at r5](https://reviewable.io/reviews/gramineproject/gramine/768#-N7VhgHR5BTRWHCSh5mr:-N7VhgHS-DQNYR-aCHYa:banhi3i) ([raw file](https://github.com/gramineproject/gramine/blob/d777deb43b9ef90ef87696a83c2b536336c360b8/libos/test/regression/proc_cpuinfo.c#L159)):*
> ```C
>     fclose(fp);
>     free(ci.flags);
>     ci.flags = NULL;
> ```

Who cares? I would just remove this line.


<!-- Sent from Reviewable.io -->

2022-07-21 12:28 UTC, boryspoplawski requested changes
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/768)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

___
*[`libos/test/regression/proc_cpuinfo.c` line 19 at r4](https://reviewable.io/reviews/gramineproject/gramine/768#-N7VAs6pAv8CcprUecoA:-N7VhtNgC-tGC6vYE0Lw:b4eix5s) ([raw file](https://github.com/gramineproject/gramine/blob/702ed961734e903797682205edbf4406c1369157/libos/test/regression/proc_cpuinfo.c#L19)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

But if you do dynamic allocation, then why not embed flags here and allocate whole struct? Current version is confusing a bit...
___
*[`libos/test/regression/proc_cpuinfo.c` line 8 at r5](https://reviewable.io/reviews/gramineproject/gramine/768#-N7ViRcH0Ok6y5AGfgSD:-N7ViRcH0Ok6y5AGfgSE:b-289xhh) ([raw file](https://github.com/gramineproject/gramine/blob/d777deb43b9ef90ef87696a83c2b536336c360b8/libos/test/regression/proc_cpuinfo.c#L8)):*
> ```C
> #define BUFFSIZE       (10 * 1024) /* 10KB */
> #define FLAGS_BUF_SIZE (8 * 1024) /* 8KB */
> #define NUM_TEST_FLAGS 3
> ```

This is not needed
___
*[`libos/test/regression/proc_cpuinfo.c` line 10 at r5](https://reviewable.io/reviews/gramineproject/gramine/768#-N7ViPgy-y5-yFWuTLH6:-N7ViPgzAUlR5WQ1Rc7e:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/d777deb43b9ef90ef87696a83c2b536336c360b8/libos/test/regression/proc_cpuinfo.c#L10)):*
> ```C
> #define NUM_TEST_FLAGS 3
> 
> static const char* const g_test_cpu_flags[NUM_TEST_FLAGS] = { "fpu", "msr", "apic" };
> ```





_Suggestion:_
```C
g_test_cpu_flags[]
```
___
*[`libos/test/regression/proc_cpuinfo.c` line 110 at r5](https://reviewable.io/reviews/gramineproject/gramine/768#-N7Vic9y7i6xHzrUWpyr:-N7Vic9y7i6xHzrUWpys:b-o8eftr) ([raw file](https://github.com/gramineproject/gramine/blob/d777deb43b9ef90ef87696a83c2b536336c360b8/libos/test/regression/proc_cpuinfo.c#L110)):*
> ```C
> #endif
> #if defined(__x86_64__)
>     for (int i = 0; i < NUM_TEST_FLAGS; i++) {
> ```

and include "common.h"



_Suggestion:_
```C
for (size_t i = 0; i < ARRAY_LEN(g_test_cpu_flags); i++) 
```
___
*[`libos/test/regression/proc_cpuinfo.c` line 159 at r5](https://reviewable.io/reviews/gramineproject/gramine/768#-N7Vhg8fAdRPecOA9PuA:-N7Vhg8g4jH7eAGd9SSG:b-7wo6hk) ([raw file](https://github.com/gramineproject/gramine/blob/d777deb43b9ef90ef87696a83c2b536336c360b8/libos/test/regression/proc_cpuinfo.c#L159)):*
> ```C
>     fclose(fp);
>     free(ci.flags);
>     ci.flags = NULL;
> ```

What's the point of this line?


<!-- Sent from Reviewable.io -->

2022-07-21 12:45 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/768)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @kailun-qin)

___
*[`libos/test/regression/proc_cpuinfo.c` line 19 at r4](https://reviewable.io/reviews/gramineproject/gramine/768#-N7VAs6pAv8CcprUecoA:-N7VkLUnB2ylD3gRQNL9:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/702ed961734e903797682205edbf4406c1369157/libos/test/regression/proc_cpuinfo.c#L19)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

But if you do dynamic allocation, then why not embed flags here and allocate whole struct? Current version is confusing a bit...
</blockquote></details>

Done.
___
*[`libos/test/regression/proc_cpuinfo.c` line 6 at r5](https://reviewable.io/reviews/gramineproject/gramine/768#-N7VhnTO4P9y7-O1gY71:-N7VjMtA5tfZVdcI8Yq6:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d777deb43b9ef90ef87696a83c2b536336c360b8/libos/test/regression/proc_cpuinfo.c#L6)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Since we're here, can we rename to `BUF_SIZE`?
</blockquote></details>

Done.
___
*[`libos/test/regression/proc_cpuinfo.c` line 8 at r5](https://reviewable.io/reviews/gramineproject/gramine/768#-N7ViRcH0Ok6y5AGfgSD:-N7VjmbGAnge0D6yxwZe:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d777deb43b9ef90ef87696a83c2b536336c360b8/libos/test/regression/proc_cpuinfo.c#L8)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This is not needed
</blockquote></details>

Done.
___
*[`libos/test/regression/proc_cpuinfo.c` line 10 at r5](https://reviewable.io/reviews/gramineproject/gramine/768#-N7VhRmq8j2-euSjHlBx:-N7VjPTq8kqpLZjDBTLL:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d777deb43b9ef90ef87696a83c2b536336c360b8/libos/test/regression/proc_cpuinfo.c#L10)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This should also be hidden under `#if defined(__x86_64__)`
</blockquote></details>

Done.
___
*[`libos/test/regression/proc_cpuinfo.c` line 10 at r5](https://reviewable.io/reviews/gramineproject/gramine/768#-N7VhwaQCqFdT8huIWar:-N7VjQ-lDhUMProWTMVP:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d777deb43b9ef90ef87696a83c2b536336c360b8/libos/test/regression/proc_cpuinfo.c#L10)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can you add a comment that this subset of flags is picked for testing, chosen to be available on any modern x86-64 CPU?
</blockquote></details>

Done.
___
*[`libos/test/regression/proc_cpuinfo.c` line 110 at r5](https://reviewable.io/reviews/gramineproject/gramine/768#-N7Vic9y7i6xHzrUWpyr:-N7VkKnnBHvwOap7w-8J:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d777deb43b9ef90ef87696a83c2b536336c360b8/libos/test/regression/proc_cpuinfo.c#L110)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

and include "common.h"
</blockquote></details>

Done.
___
*[`libos/test/regression/proc_cpuinfo.c` line 159 at r5](https://reviewable.io/reviews/gramineproject/gramine/768#-N7VhgHR5BTRWHCSh5mr:-N7VjaXB6evRKnj5cgQK:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d777deb43b9ef90ef87696a83c2b536336c360b8/libos/test/regression/proc_cpuinfo.c#L159)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Who cares? I would just remove this line.
</blockquote></details>

Done.
___
*[`libos/test/regression/proc_cpuinfo.c` line 159 at r5](https://reviewable.io/reviews/gramineproject/gramine/768#-N7Vhg8fAdRPecOA9PuA:-N7VjakBEgXvwhTaeDPe:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d777deb43b9ef90ef87696a83c2b536336c360b8/libos/test/regression/proc_cpuinfo.c#L159)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

What's the point of this line?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-21 12:59 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/768)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @kailun-qin)

___
*[`libos/test/regression/proc_cpuinfo.c` line 159 at r5](https://reviewable.io/reviews/gramineproject/gramine/768#-N7VhgHR5BTRWHCSh5mr:-N7Vpigo-8tyND9rcgRG:b84s5u4) ([raw file](https://github.com/gramineproject/gramine/blob/d777deb43b9ef90ef87696a83c2b536336c360b8/libos/test/regression/proc_cpuinfo.c#L159)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Why did you remove everything? Me and Borys were talking purely about the line `ci.flags = NULL;`. We still need to do memory cleanup via:
```
free(line);
free(ci);
```


<!-- Sent from Reviewable.io -->

2022-07-21 13:02 UTC, boryspoplawski requested changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/768)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

___
*[`libos/test/regression/proc_cpuinfo.c` line 42 at r6](https://reviewable.io/reviews/gramineproject/gramine/768#-N7Vq7sg9348ci-iRtsF:-N7Vq7sg9348ci-iRtsG:b45h) ([raw file](https://github.com/gramineproject/gramine/blob/bfd523ed18e8c31d1b31c208ab1e53f78b21004d/libos/test/regression/proc_cpuinfo.c#L42)):*
> ```C
>     ci->core_id   = -1;
>     ci->cpu_cores = -1;
>     memset(ci->flags, 0, FLAGS_BUF_SIZE);
> ```





_Suggestion:_
```C
sizeof(ci->flags)
```
___
*[`libos/test/regression/proc_cpuinfo.c` line 88 at r6](https://reviewable.io/reviews/gramineproject/gramine/768#-N7VqD4Y5RJ3HVoau8VD:-N7VqD4Y5RJ3HVoau8VE:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/bfd523ed18e8c31d1b31c208ab1e53f78b21004d/libos/test/regression/proc_cpuinfo.c#L88)):*
> ```C
>         snprintf(ci->model_name, sizeof(ci->model_name), "%s", v);
>     } else if (!strcmp(k, "flags")) {
>         snprintf(ci->flags, FLAGS_BUF_SIZE, "%s", v);
> ```





_Suggestion:_
```C
sizeof(ci->flags)
```


<!-- Sent from Reviewable.io -->

2022-07-21 13:08 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/768)* status: 9 of 10 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @kailun-qin)

___
*[`libos/test/regression/proc_cpuinfo.c` line 159 at r5](https://reviewable.io/reviews/gramineproject/gramine/768#-N7VhgHR5BTRWHCSh5mr:-N7Vr6e-0WHtR7_UTUdY:b86aqum) ([raw file](https://github.com/gramineproject/gramine/blob/d777deb43b9ef90ef87696a83c2b536336c360b8/libos/test/regression/proc_cpuinfo.c#L159)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why did you remove everything? Me and Borys were talking purely about the line `ci.flags = NULL;`. We still need to do memory cleanup via:
```
free(line);
free(ci);
```
</blockquote></details>

oops... I mistakenly thoght that you may really don't care about such free in the tests as it exits anyway... Added back.


<!-- Sent from Reviewable.io -->

2022-07-21 13:14 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/768)* status: 9 of 10 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[`libos/test/regression/proc_cpuinfo.c` line 42 at r6](https://reviewable.io/reviews/gramineproject/gramine/768#-N7Vq7sg9348ci-iRtsF:-N7VspRaEPWOErAfEsBT:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/bfd523ed18e8c31d1b31c208ab1e53f78b21004d/libos/test/regression/proc_cpuinfo.c#L42)):*
> ```C
>     ci->core_id   = -1;
>     ci->cpu_cores = -1;
>     memset(ci->flags, 0, FLAGS_BUF_SIZE);
> ```

Done.
___
*[`libos/test/regression/proc_cpuinfo.c` line 88 at r6](https://reviewable.io/reviews/gramineproject/gramine/768#-N7VqD4Y5RJ3HVoau8VD:-N7Vsp2WEwjRKZFmVwFO:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/bfd523ed18e8c31d1b31c208ab1e53f78b21004d/libos/test/regression/proc_cpuinfo.c#L88)):*
> ```C
>         snprintf(ci->model_name, sizeof(ci->model_name), "%s", v);
>     } else if (!strcmp(k, "flags")) {
>         snprintf(ci->flags, FLAGS_BUF_SIZE, "%s", v);
> ```

Done.


<!-- Sent from Reviewable.io -->

2022-07-21 13:19 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/768)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)



<!-- Sent from Reviewable.io -->

2022-07-21 13:24 UTC, boryspoplawski approved these changes
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/768)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

___
*[`libos/test/regression/proc_cpuinfo.c` line 159 at r5](https://reviewable.io/reviews/gramineproject/gramine/768#-N7VhgHR5BTRWHCSh5mr:-N7VvWHI78BNkDwJ42Hq:bmxc3gm) ([raw file](https://github.com/gramineproject/gramine/blob/d777deb43b9ef90ef87696a83c2b536336c360b8/libos/test/regression/proc_cpuinfo.c#L159)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

oops... I mistakenly thoght that you may really don't care about such free in the tests as it exits anyway... Added back.
</blockquote></details>

Well, I do not really care (but the initial comment was as @dimakuv described only about one line)


<!-- Sent from Reviewable.io -->

2022-07-21 13:24 UTC, boryspoplawski commented
Jenkins, test this please

2022-07-22 21:46 UTC, mkow requested changes
> Reviewed 4 of 8 files at r1, 4 of 5 files at r3, 1 of 2 files at r4, 1 of 2 files at r5, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/768)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/768#-N7bll499GGEWjMN_FKJ:-N7bll4A7LbOWQMdeCQU:b7dwu3f) (no related file):*
> Partially resolves #592.

Why only partially? What's missing here?

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/768#-N7bp8PfDmcCJBWmt5of:-N7bp8PfDmcCJBWmt5og:b-8zk8y6) (no related file):*
@stefanberger: You may want to do something similar in your ppc64 port ;)

___
___
*[`-- commits` line 7 at r8](https://reviewable.io/reviews/gramineproject/gramine/768#-N7blz4I3Zm6VVyVRVpM):*
(to fix during rebase)



_Suggestion:_
```
This patch:
```
___
*[`libos/src/arch/x86_64/libos_cpuid.c` line 74 at r8](https://reviewable.io/reviews/gramineproject/gramine/768#-N7brXiR7lRAcW8I5U7r:-N7brXiR7lRAcW8I5U7s:b-4kcj4s) ([raw file](https://github.com/gramineproject/gramine/blob/88cd7e3feabb0372f3b3186a484140689b76453a/libos/src/arch/x86_64/libos_cpuid.c#L74)):*
> ```C
>                     goto out_err;
>                 }
>                 memcpy(new_flags, flags, flen);
> ```

Please add a TODO here to use realloc once we implement it (after we finally do it we want to be able to easily find all such places in the code to simplify).
___
*[`libos/test/regression/proc_cpuinfo.c` line 115 at r8](https://reviewable.io/reviews/gramineproject/gramine/768#-N7bpctp9JDgQQ16FHDp:-N7bpctp9JDgQQ16FHDq:b-r80ul7) ([raw file](https://github.com/gramineproject/gramine/blob/88cd7e3feabb0372f3b3186a484140689b76453a/libos/test/regression/proc_cpuinfo.c#L115)):*
> ```C
> #if defined(__x86_64__)
>     for (size_t i = 0; i < ARRAY_LEN(g_test_cpu_flags); i++) {
>         if (!strstr(ci->flags, g_test_cpu_flags[i])) {
> ```

This is bad and may bite us later when changing the test. Notice that some flags are substrings of others - e.g. with this code you'll find `ss` ("self snoop") feature enabled when actually only `sse` is enabled.


<!-- Sent from Reviewable.io -->

2022-07-23 05:13 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/768)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)

___
*[`-- commits` line 7 at r8](https://reviewable.io/reviews/gramineproject/gramine/768#-N7blz4I3Zm6VVyVRVpM):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

(to fix during rebase)
</blockquote></details>

Thanks!
___
*[`libos/src/arch/x86_64/libos_cpuid.c` line 74 at r8](https://reviewable.io/reviews/gramineproject/gramine/768#-N7brXiR7lRAcW8I5U7r:-N7dMyCe6o-ztCp3QoiY:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/88cd7e3feabb0372f3b3186a484140689b76453a/libos/src/arch/x86_64/libos_cpuid.c#L74)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please add a TODO here to use realloc once we implement it (after we finally do it we want to be able to easily find all such places in the code to simplify).
</blockquote></details>

Done.
___
*[`libos/test/regression/proc_cpuinfo.c` line 115 at r8](https://reviewable.io/reviews/gramineproject/gramine/768#-N7bpctp9JDgQQ16FHDp:-N7dNDrc7zlRgt2Qstmf:b-xoch2t) ([raw file](https://github.com/gramineproject/gramine/blob/88cd7e3feabb0372f3b3186a484140689b76453a/libos/test/regression/proc_cpuinfo.c#L115)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This is bad and may bite us later when changing the test. Notice that some flags are substrings of others - e.g. with this code you'll find `ss` ("self snoop") feature enabled when actually only `sse` is enabled.
</blockquote></details>

Tried another approach, PTAL.


<!-- Sent from Reviewable.io -->

2022-07-23 05:17 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/768)* status: 8 of 11 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/768#-N7bll499GGEWjMN_FKJ:-N7dTZGZ20sGrNL-OxUk:byki1zq) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> Partially resolves #592.

Why only partially? What's missing here?
</blockquote></details>

The original requirement from https://github.com/gramineproject/gramine/issues/592 specifically asks for `AVX2`, well it's still not supported in this PR. However, as aligned previously (in https://github.com/gramineproject/gramine/pull/756), this will be done via a 2nd PR to support more CPU feature flags.

___


<!-- Sent from Reviewable.io -->

2022-07-23 18:18 UTC, mkow requested changes
> Reviewed 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/768)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/768#-N7bll499GGEWjMN_FKJ:-N7gCG5x05oMl0nj7pwB:bidg2th) (no related file):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

The original requirement from https://github.com/gramineproject/gramine/issues/592 specifically asks for `AVX2`, well it's still not supported in this PR. However, as aligned previously (in https://github.com/gramineproject/gramine/pull/756), this will be done via a 2nd PR to support more CPU feature flags.
</blockquote></details>

Ah, right, sounds good.

___
___
*[`libos/test/regression/proc_cpuinfo.c` line 115 at r8](https://reviewable.io/reviews/gramineproject/gramine/768#-N7bpctp9JDgQQ16FHDp:-N7gFfFu-BKjUk8c_Xzb:b-uj6nq8) ([raw file](https://github.com/gramineproject/gramine/blob/88cd7e3feabb0372f3b3186a484140689b76453a/libos/test/regression/proc_cpuinfo.c#L115)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Tried another approach, PTAL.
</blockquote></details>

Looks good. Could be simplified a bit with `strdup()` + `strcpy()` instead of `calloc()` + `snprintf()` + `memset()` + hardcoded buffer size limit, although I won't block on this.
___
*[`libos/test/regression/proc_cpuinfo.c` line 2 at r9](https://reviewable.io/reviews/gramineproject/gramine/768#-N7gCrCJ8abM_Ca5oRrc:-N7gCrCJ8abM_Ca5oRrd:bfur1f3) ([raw file](https://github.com/gramineproject/gramine/blob/85182f7e5a3c40d6e909f02550aecb9a131f3e5d/libos/test/regression/proc_cpuinfo.c#L2)):*
> ```C
> #include <stdio.h>
> #include <stdbool.h>
> ```

please sort
___
*[`libos/test/regression/proc_cpuinfo.c` line 157 at r9](https://reviewable.io/reviews/gramineproject/gramine/768#-N7gFAcE-97ueq5T81Uz:-N7gFAcE-97ueq5T81V-:b6nu43o) ([raw file](https://github.com/gramineproject/gramine/blob/85182f7e5a3c40d6e909f02550aecb9a131f3e5d/libos/test/regression/proc_cpuinfo.c#L157)):*
> ```C
>     }
> #if defined(__i386__) || defined(__x86_64__)
>     g_test_cpu_flags = argv[1];
> ```

This test will explode in weird ways (memory corruption, probably?) if we don't get into this `ifdef`.
___
*[`libos/test/regression/test_libos.py` line 975 at r9](https://reviewable.io/reviews/gramineproject/gramine/768#-N7gDy4jAAIyFyBPVTdW:-N7gDy4jAAIyFyBPVTdX:b-x6gb2o) ([raw file](https://github.com/gramineproject/gramine/blob/85182f7e5a3c40d6e909f02550aecb9a131f3e5d/libos/test/regression/test_libos.py#L975)):*
> ```Python
>         cpuinfo = dict(map(str.strip, line.split(':'))
>             for line in cpuinfo.split('\n'))
>         if 'flags' in cpuinfo:
> ```

This `if` makes little sense, if it's not taken then `cpuinfo['flags']` below will throw an exception.


<!-- Sent from Reviewable.io -->

2022-07-23 20:10 UTC, boryspoplawski requested changes
> Reviewed 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/768)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)

___
*[`libos/test/regression/proc_cpuinfo.c` line 11 at r9](https://reviewable.io/reviews/gramineproject/gramine/768#-N7eYJAU9El84FFcvPX7:-N7eYJAU9El84FFcvPX8:bqygyx7) ([raw file](https://github.com/gramineproject/gramine/blob/85182f7e5a3c40d6e909f02550aecb9a131f3e5d/libos/test/regression/proc_cpuinfo.c#L11)):*
> ```C
> 
> #if defined(__i386__) || defined(__x86_64__)
> static char* g_test_cpu_flags = NULL;
> ```

What's x86 specific in this line?
___
*[`libos/test/regression/proc_cpuinfo.c` line 118 at r9](https://reviewable.io/reviews/gramineproject/gramine/768#-N7eYZX9-Slf4MNLWde1:-N7eYZX9-Slf4MNLWde2:bf89d4g) ([raw file](https://github.com/gramineproject/gramine/blob/85182f7e5a3c40d6e909f02550aecb9a131f3e5d/libos/test/regression/proc_cpuinfo.c#L118)):*
> ```C
>     }
> 
>     char* test_flag = strtok(g_test_cpu_flags, " ");
> ```

Please don't pass function arguments via global variables
___
*[`libos/test/regression/proc_cpuinfo.c` line 157 at r9](https://reviewable.io/reviews/gramineproject/gramine/768#-N7eYH304dq01mhhm45x:-N7eYH304dq01mhhm45y:bqygyx7) ([raw file](https://github.com/gramineproject/gramine/blob/85182f7e5a3c40d6e909f02550aecb9a131f3e5d/libos/test/regression/proc_cpuinfo.c#L157)):*
> ```C
>     }
> #if defined(__i386__) || defined(__x86_64__)
>     g_test_cpu_flags = argv[1];
> ```

What's x86 specific in this line?
___
*[`libos/test/regression/test_libos.py` line 975 at r9](https://reviewable.io/reviews/gramineproject/gramine/768#-N7eZWzZ4oUNuF5do-NZ:-N7eZWzZ4oUNuF5do-N_:b9tqrfv) ([raw file](https://github.com/gramineproject/gramine/blob/85182f7e5a3c40d6e909f02550aecb9a131f3e5d/libos/test/regression/test_libos.py#L975)):*
> ```Python
>         cpuinfo = dict(map(str.strip, line.split(':'))
>             for line in cpuinfo.split('\n'))
>         if 'flags' in cpuinfo:
> ```

You assume below that this is the case (in `self.run_binary`). Please just assert then.


<!-- Sent from Reviewable.io -->

2022-07-23 20:12 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/768)* status: all files reviewed, 11 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)

___
*[`libos/test/regression/proc_cpuinfo.c` line 118 at r9](https://reviewable.io/reviews/gramineproject/gramine/768#-N7gfyFH60G5zzXrV1NB:-N7gfyFH60G5zzXrV1NC:b-1qprh8) ([raw file](https://github.com/gramineproject/gramine/blob/85182f7e5a3c40d6e909f02550aecb9a131f3e5d/libos/test/regression/proc_cpuinfo.c#L118)):*
> ```C
>     }
> 
>     char* test_flag = strtok(g_test_cpu_flags, " ");
> ```

`strtok` destroys the first argument, so this function can be only run once. I don't like this, but if you keep this version, then please at least document this.
___
*[`libos/test/regression/proc_cpuinfo.c` line 134 at r9](https://reviewable.io/reviews/gramineproject/gramine/768#-N7gg6_K1UJCjFaVQBaF:-N7gg6_K1UJCjFaVQBaG:bfuzg9v) ([raw file](https://github.com/gramineproject/gramine/blob/85182f7e5a3c40d6e909f02550aecb9a131f3e5d/libos/test/regression/proc_cpuinfo.c#L134)):*
> ```C
> 
>         if (!found) {
>             fprintf(stderr, "Could not get cpu flag: %s\n", test_flag);
> ```

`free(flags)` missing


<!-- Sent from Reviewable.io -->

2022-07-24 03:48 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/768)* status: 9 of 11 files reviewed, 11 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[`libos/test/regression/proc_cpuinfo.c` line 115 at r8](https://reviewable.io/reviews/gramineproject/gramine/768#-N7bpctp9JDgQQ16FHDp:-N7iIMeD55FsWQmV5BbL:bflm6f3) ([raw file](https://github.com/gramineproject/gramine/blob/88cd7e3feabb0372f3b3186a484140689b76453a/libos/test/regression/proc_cpuinfo.c#L115)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Looks good. Could be simplified a bit with `strdup()` + `strcpy()` instead of `calloc()` + `snprintf()` + `memset()` + hardcoded buffer size limit, although I won't block on this.
</blockquote></details>

Switched to`strdup()` + `strcpy()`. Also, did some more testing and fixed some issues.
___
*[`libos/test/regression/proc_cpuinfo.c` line 2 at r9](https://reviewable.io/reviews/gramineproject/gramine/768#-N7gCrCJ8abM_Ca5oRrc:-N7iIFOt00nqw6zOkgQ3:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/85182f7e5a3c40d6e909f02550aecb9a131f3e5d/libos/test/regression/proc_cpuinfo.c#L2)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

please sort
</blockquote></details>

Done.
___
*[`libos/test/regression/proc_cpuinfo.c` line 11 at r9](https://reviewable.io/reviews/gramineproject/gramine/768#-N7eYJAU9El84FFcvPX7:-N7iIGjG706jsg6VYTtL:bss4a2b) ([raw file](https://github.com/gramineproject/gramine/blob/85182f7e5a3c40d6e909f02550aecb9a131f3e5d/libos/test/regression/proc_cpuinfo.c#L11)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

What's x86 specific in this line?
</blockquote></details>

Removed.
___
*[`libos/test/regression/proc_cpuinfo.c` line 118 at r9](https://reviewable.io/reviews/gramineproject/gramine/768#-N7eYZX9-Slf4MNLWde1:-N7iIImGDZPGOGkwsnW7:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/85182f7e5a3c40d6e909f02550aecb9a131f3e5d/libos/test/regression/proc_cpuinfo.c#L118)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please don't pass function arguments via global variables
</blockquote></details>

Done.
___
*[`libos/test/regression/proc_cpuinfo.c` line 118 at r9](https://reviewable.io/reviews/gramineproject/gramine/768#-N7gfyFH60G5zzXrV1NB:-N7iIKKz5Y-_GoW32FQb:b-suxt5a) ([raw file](https://github.com/gramineproject/gramine/blob/85182f7e5a3c40d6e909f02550aecb9a131f3e5d/libos/test/regression/proc_cpuinfo.c#L118)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`strtok` destroys the first argument, so this function can be only run once. I don't like this, but if you keep this version, then please at least document this.
</blockquote></details>

Used another local string for `test_flags`.
___
*[`libos/test/regression/proc_cpuinfo.c` line 134 at r9](https://reviewable.io/reviews/gramineproject/gramine/768#-N7gg6_K1UJCjFaVQBaF:-N7iJTzn4HIVHAw2SJzX:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/85182f7e5a3c40d6e909f02550aecb9a131f3e5d/libos/test/regression/proc_cpuinfo.c#L134)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`free(flags)` missing
</blockquote></details>

Done.
___
*[`libos/test/regression/proc_cpuinfo.c` line 157 at r9](https://reviewable.io/reviews/gramineproject/gramine/768#-N7gFAcE-97ueq5T81Uz:-N7iIiPI-oJQcXdhySKd:bss4a2b) ([raw file](https://github.com/gramineproject/gramine/blob/85182f7e5a3c40d6e909f02550aecb9a131f3e5d/libos/test/regression/proc_cpuinfo.c#L157)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This test will explode in weird ways (memory corruption, probably?) if we don't get into this `ifdef`.
</blockquote></details>

Removed.
___
*[`libos/test/regression/proc_cpuinfo.c` line 157 at r9](https://reviewable.io/reviews/gramineproject/gramine/768#-N7eYH304dq01mhhm45x:-N7iIjC54VYc3a9BKLcS:bss4a2b) ([raw file](https://github.com/gramineproject/gramine/blob/85182f7e5a3c40d6e909f02550aecb9a131f3e5d/libos/test/regression/proc_cpuinfo.c#L157)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

What's x86 specific in this line?
</blockquote></details>

Removed.
___
*[`libos/test/regression/test_libos.py` line 975 at r9](https://reviewable.io/reviews/gramineproject/gramine/768#-N7gDy4jAAIyFyBPVTdW:-N7iInYNBTDLiwyUpodu:b-1gzkfj) ([raw file](https://github.com/gramineproject/gramine/blob/85182f7e5a3c40d6e909f02550aecb9a131f3e5d/libos/test/regression/test_libos.py#L975)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This `if` makes little sense, if it's not taken then `cpuinfo['flags']` below will throw an exception.
</blockquote></details>

Exactly, changed to another version.
___
*[`libos/test/regression/test_libos.py` line 975 at r9](https://reviewable.io/reviews/gramineproject/gramine/768#-N7eZWzZ4oUNuF5do-NZ:-N7iIo_9-j5H4vttc5U6:b-x3wi1l) ([raw file](https://github.com/gramineproject/gramine/blob/85182f7e5a3c40d6e909f02550aecb9a131f3e5d/libos/test/regression/test_libos.py#L975)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

You assume below that this is the case (in `self.run_binary`). Please just assert then.
</blockquote></details>

I do not intend to assume that we always have cpuinfo['flags'], updated to another version.


<!-- Sent from Reviewable.io -->

2022-07-24 11:11 UTC, boryspoplawski requested changes
> Reviewed 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/768)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)

___
*[`libos/test/regression/proc_cpuinfo.c` line 118 at r9](https://reviewable.io/reviews/gramineproject/gramine/768#-N7eYZX9-Slf4MNLWde1:-N7jrRKO3pF-0yIvXm2L:bgwff71) ([raw file](https://github.com/gramineproject/gramine/blob/85182f7e5a3c40d6e909f02550aecb9a131f3e5d/libos/test/regression/proc_cpuinfo.c#L118)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done - you just moved it to line above. Please add an argument to this function instead of using a global variable
___
*[`libos/test/regression/proc_cpuinfo.c` line 110 at r10](https://reviewable.io/reviews/gramineproject/gramine/768#-N7jrzPj8MizHjGXYoYv:-N7jrzPj8MizHjGXYoYw:bgjrk23) ([raw file](https://github.com/gramineproject/gramine/blob/90c582470641ee42dac85b219f547a44484b299a/libos/test/regression/proc_cpuinfo.c#L110)):*
> ```C
>         return -1;
>     }
> ```

Why everything below is under `x64` ifdef? What's arch specific in this code?
___
*[`libos/test/regression/proc_cpuinfo.c` line 113 at r10](https://reviewable.io/reviews/gramineproject/gramine/768#-N7jtAiH3l3stycwn3wQ:-N7jtAiH3l3stycwn3wR:b57kuwv) ([raw file](https://github.com/gramineproject/gramine/blob/90c582470641ee42dac85b219f547a44484b299a/libos/test/regression/proc_cpuinfo.c#L113)):*
> ```C
>     char* flags;
>     char* state_flags;
>     char* test_flags;
> ```

None of these are initialized - if the first allocation fails you get a `free(test_flags=uniinitialized_pointer)`
___
*[`libos/test/regression/proc_cpuinfo.c` line 114 at r10](https://reviewable.io/reviews/gramineproject/gramine/768#-N7jssk56LZ9AENvTyw_:-N7jssk56LZ9AENvTywa:b-9k71fr) ([raw file](https://github.com/gramineproject/gramine/blob/90c582470641ee42dac85b219f547a44484b299a/libos/test/regression/proc_cpuinfo.c#L114)):*
> ```C
>     char* state_flags;
>     char* test_flags;
>     char* state_test_flags;
> ```

`strtok_r` might require the last arg to be `NULL` initialized
___
*[`libos/test/regression/proc_cpuinfo.c` line 134 at r10](https://reviewable.io/reviews/gramineproject/gramine/768#-N7jt_gQ6KBFH3ancSSV:-N7jt_gQ6KBFH3ancSSW:b-rdjzy) ([raw file](https://github.com/gramineproject/gramine/blob/90c582470641ee42dac85b219f547a44484b299a/libos/test/regression/proc_cpuinfo.c#L134)):*
> ```C
>         bool found = false;
> 
>         /* Strip the trailing `\n` in `flags` so that the last token splitted by `strtok_r()` can
> ```

How about we store `flags` without the trailing `\n` instead?


<!-- Sent from Reviewable.io -->

2022-07-24 12:45 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/768)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[`libos/test/regression/proc_cpuinfo.c` line 118 at r9](https://reviewable.io/reviews/gramineproject/gramine/768#-N7eYZX9-Slf4MNLWde1:-N7k4ggdCSuO3SBOUigk:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/85182f7e5a3c40d6e909f02550aecb9a131f3e5d/libos/test/regression/proc_cpuinfo.c#L118)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Not done - you just moved it to line above. Please add an argument to this function instead of using a global variable
</blockquote></details>

Done.
___
*[`libos/test/regression/proc_cpuinfo.c` line 110 at r10](https://reviewable.io/reviews/gramineproject/gramine/768#-N7jrzPj8MizHjGXYoYv:-N7k88cx63yDPMrOyhin:b1y381x) ([raw file](https://github.com/gramineproject/gramine/blob/90c582470641ee42dac85b219f547a44484b299a/libos/test/regression/proc_cpuinfo.c#L110)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why everything below is under `x64` ifdef? What's arch specific in this code?
</blockquote></details>

Moved out of the ifdef. Just curious, what's arch specific in some other fields (e.g., core_id etc.)?
___
*[`libos/test/regression/proc_cpuinfo.c` line 113 at r10](https://reviewable.io/reviews/gramineproject/gramine/768#-N7jtAiH3l3stycwn3wQ:-N7k4D4MAFu30IaItnL8:bv6f7kj) ([raw file](https://github.com/gramineproject/gramine/blob/90c582470641ee42dac85b219f547a44484b299a/libos/test/regression/proc_cpuinfo.c#L113)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

None of these are initialized - if the first allocation fails you get a `free(test_flags=uniinitialized_pointer)`
</blockquote></details>

Good catch, thanks! Done.
___
*[`libos/test/regression/proc_cpuinfo.c` line 114 at r10](https://reviewable.io/reviews/gramineproject/gramine/768#-N7jssk56LZ9AENvTyw_:-N7k4DIw6J5KLaYOJ32d:bziwbi) ([raw file](https://github.com/gramineproject/gramine/blob/90c582470641ee42dac85b219f547a44484b299a/libos/test/regression/proc_cpuinfo.c#L114)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`strtok_r` might require the last arg to be `NULL` initialized
</blockquote></details>

From man page - the value of `*saveptr` is ignored on the first call to `strtok_r()` and the man page example does not initialize it. However, looks like it's better to initialize it to NULL for better portability (some implementations may require it to be NULL.
___
*[`libos/test/regression/proc_cpuinfo.c` line 134 at r10](https://reviewable.io/reviews/gramineproject/gramine/768#-N7jt_gQ6KBFH3ancSSV:-N7k8gdU38DU7odOKMWC:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/90c582470641ee42dac85b219f547a44484b299a/libos/test/regression/proc_cpuinfo.c#L134)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

How about we store `flags` without the trailing `\n` instead?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-24 13:29 UTC, boryspoplawski requested changes
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/768)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)

___
*[`libos/test/regression/proc_cpuinfo.c` line 110 at r10](https://reviewable.io/reviews/gramineproject/gramine/768#-N7jrzPj8MizHjGXYoYv:-N7kLt0BAfxFNrCnaoQm:b98qb9v) ([raw file](https://github.com/gramineproject/gramine/blob/90c582470641ee42dac85b219f547a44484b299a/libos/test/regression/proc_cpuinfo.c#L110)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Moved out of the ifdef. Just curious, what's arch specific in some other fields (e.g., core_id etc.)?
</blockquote></details>

I don't know exact details, but some archs have different layout and/or different fields in `/proc/cpuinfo`. (history: https://github.com/gramineproject/graphene/pull/1611)
___
*[`libos/test/regression/proc_cpuinfo.c` line 114 at r10](https://reviewable.io/reviews/gramineproject/gramine/768#-N7jssk56LZ9AENvTyw_:-N7kNKR57YXLU3XZqjS-:bosmojj) ([raw file](https://github.com/gramineproject/gramine/blob/90c582470641ee42dac85b219f547a44484b299a/libos/test/regression/proc_cpuinfo.c#L114)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

From man page - the value of `*saveptr` is ignored on the first call to `strtok_r()` and the man page example does not initialize it. However, looks like it's better to initialize it to NULL for better portability (some implementations may require it to be NULL.
</blockquote></details>

And from the man page: `On some implementations, *saveptr is required to be NULL on the first call to strtok_r() that is being used to parse str`
___
*[`libos/test/regression/proc_cpuinfo.c` line 95 at r11](https://reviewable.io/reviews/gramineproject/gramine/768#-N7kLnjyBK9nHyGn87O3:-N7kLnjyBK9nHyGn87O4:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/0767abb7e65d51db2b2cc0fbbfcadcf5de0e804e/libos/test/regression/proc_cpuinfo.c#L95)):*
> ```C
> };
> 
> static int check_cpuinfo(struct cpuinfo* ci, const char* const test_cpu_flags) {
> ```





_Suggestion:_
```C
const char* test_cpu_flags)
```


<!-- Sent from Reviewable.io -->

2022-07-24 13:41 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/768)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[`libos/test/regression/proc_cpuinfo.c` line 110 at r10](https://reviewable.io/reviews/gramineproject/gramine/768#-N7jrzPj8MizHjGXYoYv:-N7kQoNP0X_OAxmuDNCn:bejtycu) ([raw file](https://github.com/gramineproject/gramine/blob/90c582470641ee42dac85b219f547a44484b299a/libos/test/regression/proc_cpuinfo.c#L110)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I don't know exact details, but some archs have different layout and/or different fields in `/proc/cpuinfo`. (history: https://github.com/gramineproject/graphene/pull/1611)
</blockquote></details>

OK. Thanks for the pointer!
___
*[`libos/test/regression/proc_cpuinfo.c` line 114 at r10](https://reviewable.io/reviews/gramineproject/gramine/768#-N7jssk56LZ9AENvTyw_:-N7kR8VfAl-oFQCpzb-f:b-qxf04q) ([raw file](https://github.com/gramineproject/gramine/blob/90c582470641ee42dac85b219f547a44484b299a/libos/test/regression/proc_cpuinfo.c#L114)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

And from the man page: `On some implementations, *saveptr is required to be NULL on the first call to strtok_r() that is being used to parse str`
</blockquote></details>

Yep, indeed.
___
*[`libos/test/regression/proc_cpuinfo.c` line 95 at r11](https://reviewable.io/reviews/gramineproject/gramine/768#-N7kLnjyBK9nHyGn87O3:-N7kQcrN-nrZXEtN9ykJ:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/0767abb7e65d51db2b2cc0fbbfcadcf5de0e804e/libos/test/regression/proc_cpuinfo.c#L95)):*
> ```C
> };
> 
> static int check_cpuinfo(struct cpuinfo* ci, const char* const test_cpu_flags) {
> ```

Done.


<!-- Sent from Reviewable.io -->

2022-07-24 14:08 UTC, mkow requested changes
> Reviewed 1 of 2 files at r10, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/768)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @kailun-qin, and @mkow)

___
*[`libos/test/regression/proc_cpuinfo.c` line 86 at r11](https://reviewable.io/reviews/gramineproject/gramine/768#-N7kLnXO7hoHQPKfmJ1r:-N7kLnXO7hoHQPKfmJ1s:b-4pkyzw) ([raw file](https://github.com/gramineproject/gramine/blob/0767abb7e65d51db2b2cc0fbbfcadcf5de0e804e/libos/test/regression/proc_cpuinfo.c#L86)):*
> ```C
>         snprintf(ci->flags, sizeof(ci->flags), "%s", v);
>         /* Store `ci->flags` without the trailing `\n` for easier proper splitting */
>         ci->flags[strlen(ci->flags) - 1] = '\0';
> ```

You'll corrupt memory if there are no flags.


<!-- Sent from Reviewable.io -->

2022-07-24 14:38 UTC, boryspoplawski requested changes
> Reviewed 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/768)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)



<!-- Sent from Reviewable.io -->

2022-07-24 14:59 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/768)* status: 10 of 11 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[`libos/test/regression/proc_cpuinfo.c` line 86 at r11](https://reviewable.io/reviews/gramineproject/gramine/768#-N7kLnXO7hoHQPKfmJ1r:-N7ki36e8_ZEcppymeO9:bt2vr1b) ([raw file](https://github.com/gramineproject/gramine/blob/0767abb7e65d51db2b2cc0fbbfcadcf5de0e804e/libos/test/regression/proc_cpuinfo.c#L86)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

You'll corrupt memory if there are no flags.
</blockquote></details>

Fixed.


<!-- Sent from Reviewable.io -->

2022-07-24 15:24 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/768)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)



<!-- Sent from Reviewable.io -->

2022-07-24 16:06 UTC, boryspoplawski submitted a review, later dismissed
> Reviewed 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/768)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2022-07-25 07:20 UTC, dimakuv approved these changes
> Reviewed 1 of 3 files at r9, 1 of 2 files at r10, 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/768)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2022-07-25 07:22 UTC, dimakuv commented
Jenkins, test this please

2022-07-25 14:25 UTC, mkow commented
Jenkins, retest this please

2022-07-25 14:26 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/768)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/768#-N7pft2wDsOqQBGr_CBk:-N7pft2wDsOqQBGr_CBl:b7qinbt) (no related file):*
FYI: I had to change "Partially resolves https://github.com/gramineproject/gramine/issues/592" in the description, because otherwise it would close #592 on merge.

___
___
*[`-- commits` line 7 at r8](https://reviewable.io/reviews/gramineproject/gramine/768#-N7blz4I3Zm6VVyVRVpM):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Thanks!
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-25 14:28 UTC, boryspoplawski approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/768)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2022-07-25 14:53 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/768)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-07-25 15:04 UTC, merged