[tools/sgx,curl,Docs] Link all dependencies of `tools/sgx` statically
gramineproject/gramine pull request #773
Opened 2022-07-20 01:57 UTC by kailun-qin

Previously, we built `libsgx_util` as a shared library which is linked into RA-TLS, Secret Provisioning libraries and some other tools.

This patch
- builds `libsgx_util` into a static library
- builds and minimizes `curl` into a static library (leveraging
  `mbedtls` as the TLS backend)
- links all dependencies of `tools/sgx ` statically to avoid pulling in
  a lot of dependencies.

See https://github.com/gramineproject/gramine/pull/740 and https://github.com/gramineproject/gramine/pull/730 for some previous discussions.

2022-07-20 12:49 UTC, dimakuv requested changes
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/773)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/773#-N7PVHxK-eRDhbde5asb:-N7QdMb41VLeKXam2NtK:b6gh35a) (no related file):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Well noted, thanks.
</blockquote></details>

Could you create such a PR now?

___


<!-- Sent from Reviewable.io -->

2022-07-20 12:56 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/773)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/773#-N7QfRJD1nmZcqXn2AL1:-N7QfRJECzcRUpShhzPK:bmv9rno) (no related file):*
Just tested it: works like charm! No more crazy Curl dependencies. Thanks, this is a great PR!

___


<!-- Sent from Reviewable.io -->

2022-07-20 13:55 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/773)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/773#-N7QpjnI8RCn59lzTaMe:-N7QpjnI8RCn59lzTaMf:b-n8w7eq) (no related file):*
1. Why do we pull in another subproject? This is not something we want to do, unless there is no other option. Why cannot we build e.g. against host `libcurl` (statically)?
2. Didn't we want to build only stuff that's go into the enclave statically and urts tools dynamically?

Actually, could you summarize what exact problem is this PR solving?

___


<!-- Sent from Reviewable.io -->

2022-07-20 14:14 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/773)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @kailun-qin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/773#-N7PVHxK-eRDhbde5asb:-N7Qx4fO6TrYcCOEk-XQ:b-xxvmi6) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you create such a PR now?
</blockquote></details>

Done, created at https://github.com/gramineproject/gsc/pull/81.

___


<!-- Sent from Reviewable.io -->

2022-07-20 14:25 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/773)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @kailun-qin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/773#-N7PVHxK-eRDhbde5asb:-N7QzxT82YAqNV7EkBEF:b-ucfknh) (no related file):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Done, created at https://github.com/gramineproject/gsc/pull/81.
</blockquote></details>

Thanks!

___


<!-- Sent from Reviewable.io -->

2022-07-20 15:35 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/773)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @kailun-qin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/773#-N7QpjnI8RCn59lzTaMe:-N7RDqgv2KYxjdSF5JbB:bhzko2v) (no related file):*
> RA-TLS libs link against the same libsgx_util.so

Maybe this is a problem - why do everything links against a lib incorporating unrelated features? Why don't we just build `.o` and use them wherever necessary?

> we would like to use the minimal version of libcurl, not some monstrosity.

If you build statically only used stuff will be pulled into the final binary.

___


<!-- Sent from Reviewable.io -->

2022-07-20 18:36 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/773)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @kailun-qin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/773#-N7QpjnI8RCn59lzTaMe:-N7RrjVtAZzKV4jb8nGK:b-4nuo5r) (no related file):*
> Well, that's the same as using a static library. Yes, there is a static version of libcurl 

I meant `lib_sgx_utils` here, we can link only necessary parts and decide whether we link deps statically or dynamically depending on the target.
Putting this in different words: why `sgx_utils` is a `.so` not a series of `.o` we just link to specific tools? Though if we use static library, this question is kind of orthogonal to the dependencies.

> But this static library is only curl 

So? Other libs also have static versions we can use.

___


<!-- Sent from Reviewable.io -->

2022-07-21 05:07 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/773)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @kailun-qin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/773#-N7QpjnI8RCn59lzTaMe:-N7U12Fl9sVCxN4aIaH_:b9v1iz2) (no related file):*
> Though if we use static library, this question is kind of orthogonal to the dependencies.

I agree, it's kind of orthogonal.

> So? Other libs also have static versions we can use.

That may introduce the preparation of the static version libs (i.e., `-dev` pkg installation or thru other ways) for all the dependencies (e.g., in my current env: -lnghttp2 -lidn2 -lrtmp -lssh -lpsl -lgssapi_krb5 -lkrb5 -lk5crypto -lcom_err -llber -lldap -lbrotlidec -lz -lpthread). Is this something that we would expect?

___


<!-- Sent from Reviewable.io -->

2022-07-21 08:07 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/773)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @kailun-qin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/773#-N7QpjnI8RCn59lzTaMe:-N7Ukfht2u82bZrvridz:b-d32cxm) (no related file):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

> Though if we use static library, this question is kind of orthogonal to the dependencies.

I agree, it's kind of orthogonal.

> So? Other libs also have static versions we can use.

That may introduce the preparation of the static version libs (i.e., `-dev` pkg installation or thru other ways) for all the dependencies (e.g., in my current env: -lnghttp2 -lidn2 -lrtmp -lssh -lpsl -lgssapi_krb5 -lkrb5 -lk5crypto -lcom_err -llber -lldap -lbrotlidec -lz -lpthread). Is this something that we would expect?
</blockquote></details>

I understand @boryspoplawski points, but I'm still in favor of the approach in this PR.

My reasoning is like this:
1. RA-TLS lib (and to lesser extent Secret Provisioning lib) is an *important and integral* part of any Gramine SGX enclave. To date, the vast majority of use cases of Gramine that I know of use our RA-TLS library.
2. The minimal viable product using Gramine SGX should have both properties:
    - remote attestation (via RA-TLS)
    - minimality and *reproducibility* of enclave code (via well-known versions and configs)
3. So, RA-TLS should be considered a part of Gramine core and should be treated as the rest of Gramine.
4. libcurl is a huge beast (and I vehemently dislike its philosophy of "let's use 100 million dependencies, and which dep is used for what nobody understands"), it should be tamed. The only reasonable way to make libcurl "reproducable and minimal" is to build it ourselves (also, this is what the official documentation of Curl recommends).

Yes, we can of course use whatever version of Curl for stand-alone tools like `gramine-sgx-pf-crypt` or `gramine-sgx-ias-verify-report`, I don't care much about them. But for RA-TLS, I definitely prefer the "we build minimal libcurl ourselves, and we retain control over its configuration" logic. (Purely for simplicity, this PR builds all libraries and tools against our own static libcurl, because who cares, it's easier this way.)

___


<!-- Sent from Reviewable.io -->

2022-07-21 10:34 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/773)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/773#-N7QpjnI8RCn59lzTaMe:-N7VIihi2vePVx8DXjRa:bs8f5i0) (no related file):*
> Is this something that we would expect?

Ok, I see your point now. The actual problem is not with static vs dynamic linking, but the sheer amount of dependencies libcurl has, which we can greatly reduce by building it ourselves. I would definitely describe this in the commit message.

___


<!-- Sent from Reviewable.io -->

2022-07-21 11:54 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/773)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/773#-N7QpjnI8RCn59lzTaMe:-N7VatoW2CjPI6hGyOE1:b4lf1g7) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

> Is this something that we would expect?

Ok, I see your point now. The actual problem is not with static vs dynamic linking, but the sheer amount of dependencies libcurl has, which we can greatly reduce by building it ourselves. I would definitely describe this in the commit message.
</blockquote></details>

Agreed. I proposed some text to the commit message.

___
___
*[`-- commits` line 5 at r2](https://reviewable.io/reviews/gramineproject/gramine/773#-N7V_RJpCoekH5TLrMM3):*
As pointed out by @boryspoplawski, we need to give more explanations in this commit message. I suggest to add this:
```
...other tools. This library relies on libcurl, taken from the host platform. However, libcurl
has a high number of dependencies itself, most of which are not required by
Gramine, only consume space and are hard to track and reason about. This is
especially pronounced for the RA-TLS/SecretProv libs because they typically
run inside SGX enclaves and therefore must be minimal and reproducible.

This patch:
... same text ...
```


<!-- Sent from Reviewable.io -->

2022-07-21 12:06 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/773)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @kailun-qin)

___
*[`-- commits` line 5 at r2](https://reviewable.io/reviews/gramineproject/gramine/773#-N7V_RJpCoekH5TLrMM3):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

As pointed out by @boryspoplawski, we need to give more explanations in this commit message. I suggest to add this:
```
...other tools. This library relies on libcurl, taken from the host platform. However, libcurl
has a high number of dependencies itself, most of which are not required by
Gramine, only consume space and are hard to track and reason about. This is
especially pronounced for the RA-TLS/SecretProv libs because they typically
run inside SGX enclaves and therefore must be minimal and reproducible.

This patch:
... same text ...
```
</blockquote></details>

I would also change the one liner, to reflect the core change


<!-- Sent from Reviewable.io -->

2022-07-21 13:01 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/773)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "squash! " found in commit messages' one-liners (waiting on @dimakuv and @kailun-qin)

___
*[`-- commits` line 5 at r2](https://reviewable.io/reviews/gramineproject/gramine/773#-N7V_RJpCoekH5TLrMM3):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I would also change the one liner, to reflect the core change
</blockquote></details>

Added a squash commit to update both.


<!-- Sent from Reviewable.io -->

2022-07-22 08:42 UTC, dimakuv reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/773)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "squash! " found in commit messages' one-liners (waiting on @kailun-qin)



<!-- Sent from Reviewable.io -->

2022-07-25 21:13 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/773)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "squash! " found in commit messages' one-liners (waiting on @woju)

___
*[`subprojects/curl-7.84.0.wrap` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/773#-N7PW7mmBJ4R91DKwXSR:-N7rAX_hCPNIA5zNNk0h:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/0b5d190ae40dd900cdb56e6feafc3f0e830f1045/subprojects/curl-7.84.0.wrap#L4)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@woju Could we add this file?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-26 06:16 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/773)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "squash! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2022-07-26 15:38 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/773)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2022-07-26 15:39 UTC, dimakuv commented
Jenkins, test this please

2022-07-26 16:19 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/773)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/773#-N7vI_7q-3nTTSbUQaUi:-N7vI_7q-3nTTSbUQaUj:bdbx876) (no related file):*
SGX pipelines failed with this:
```
17:50:21    File "/usr/local/lib/python3.6/dist-packages/mesonbuild/build.py", line 1113, in link
17:50:21      if isinstance(self, StaticLibrary) and self.need_install and t.is_internal():
17:50:21  AttributeError: 'CustomTarget' object has no attribute 'is_internal'
```

I don't really understand what this error means...

___


<!-- Sent from Reviewable.io -->

2022-07-26 16:22 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/773)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)



<!-- Sent from Reviewable.io -->

2022-07-27 02:32 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/773)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/773#-N7vI_7q-3nTTSbUQaUi:-N7xRkqq-7TEe64PKhLZ:byg8sji) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

SGX pipelines failed with this:
```
17:50:21    File "/usr/local/lib/python3.6/dist-packages/mesonbuild/build.py", line 1113, in link
17:50:21      if isinstance(self, StaticLibrary) and self.need_install and t.is_internal():
17:50:21  AttributeError: 'CustomTarget' object has no attribute 'is_internal'
```

I don't really understand what this error means...
</blockquote></details>

The issue may be related w/ https://github.com/mesonbuild/meson/issues/6365 which was fixed by https://github.com/mesonbuild/meson/pull/7769 and is available since meson 0.56. I've reproduced the issue w/ meson 0.55.0 and verified w/ meson 0.56.0 the issue's gone.

As our doc requires "meson>=0.55" and our CI explicitly requires "meson>=0.55,<0.56", the issue can be seen in CI SGX pipelines. One straightforward fix is to upgrade meson 0.56.0. I can upgrade via another PR but would like to check first - is this something make sense to you?

___


<!-- Sent from Reviewable.io -->

2022-07-27 07:40 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/773)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/773#-N7vI_7q-3nTTSbUQaUi:-N7ya7--EtOIaiC67_kt:bh1ad70) (no related file):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

The issue may be related w/ https://github.com/mesonbuild/meson/issues/6365 which was fixed by https://github.com/mesonbuild/meson/pull/7769 and is available since meson 0.56. I've reproduced the issue w/ meson 0.55.0 and verified w/ meson 0.56.0 the issue's gone.

As our doc requires "meson>=0.55" and our CI explicitly requires "meson>=0.55,<0.56", the issue can be seen in CI SGX pipelines. One straightforward fix is to upgrade meson 0.56.0. I can upgrade via another PR but would like to check first - is this something make sense to you?
</blockquote></details>

Then we definitely need to move to 0.56. I will be all in favor of requiring `meson>=0.56`. Please submit a separate PR.

The only thing I'm afraid of is this version of Meson may not be available in some repos. On the other side, we currently use `pip install` anyway for Meson, so we can just continue using it. @woju @mkow @boryspoplawski Are there any downsides to upgrading Meson?

___


<!-- Sent from Reviewable.io -->

2022-07-27 08:28 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/773)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/773#-N7vI_7q-3nTTSbUQaUi:-N7ykbmF-JnAKRr6EZnN:b9qnxs6) (no related file):*
> Please submit a separate PR.

Done.

> The only thing I'm afraid of is this version of Meson may not be available in some repos. On the other side, we currently use pip install anyway for Meson, so we can just continue using it.

Indeed, for instance, ubuntu 20.04 by default provides meson 0.53.2. Well, as said, we're currently using `pip install` anyway.

___


<!-- Sent from Reviewable.io -->

2022-07-27 10:45 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/773)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/773#-N7vI_7q-3nTTSbUQaUi:-N7zFQn-203yOg4nfgbz:b413q03) (no related file):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

> Please submit a separate PR.

Done.

> The only thing I'm afraid of is this version of Meson may not be available in some repos. On the other side, we currently use pip install anyway for Meson, so we can just continue using it.

Indeed, for instance, ubuntu 20.04 by default provides meson 0.53.2. Well, as said, we're currently using `pip install` anyway.
</blockquote></details>

The potential downside would be if Ubuntu 22.04 had Meson 0.55. No idea if that's the case

___


<!-- Sent from Reviewable.io -->

2022-07-27 11:10 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/773)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/773#-N7vI_7q-3nTTSbUQaUi:-N7zLMen35nwI4yp0No0:b-rgol3r) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

The potential downside would be if Ubuntu 22.04 had Meson 0.55. No idea if that's the case
</blockquote></details>

It's meson 0.61.2-1 for Ubuntu 22.04.

___


<!-- Sent from Reviewable.io -->

2022-07-27 11:26 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/773)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/773#-N7vI_7q-3nTTSbUQaUi:-N7zOrnh3dfov_ugYj55:bvpmx18) (no related file):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

It's meson 0.61.2-1 for Ubuntu 22.04.
</blockquote></details>

Yep, there should be no problem with Ubuntu 22.04.

___


<!-- Sent from Reviewable.io -->

2022-08-01 13:31 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/773)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/773#-N7vI_7q-3nTTSbUQaUi:-N8OaSY_5GRy9eTeJv5e:byyhogf) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yep, there should be no problem with Ubuntu 22.04.
</blockquote></details>

Just a reminder, this PR is blocking on https://github.com/gramineproject/gramine/pull/799. That PR will be merged today, and then this PR can be rebased on top of it (there are no other blocking comments).

___


<!-- Sent from Reviewable.io -->

2022-08-01 17:01 UTC, woju requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/773)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin, @mkow, and @woju)

___
*[`meson.build` line 266 at r4](https://reviewable.io/reviews/gramineproject/gramine/773#-N8PJmD6-PFIN7Lms7nJ:-N8PJmD72AlY_6Fv_Z6w:b-mnwg16) ([raw file](https://github.com/gramineproject/gramine/blob/cf8095d83b634f37d2c5f33a4d9a7881a11432bc/meson.build#L266)):*
> ```Meson
>     threads_dep = dependency('threads')
> 
>     libcurl_dep = dependency('libcurl', version: '>=7.58.0')
> ```

`dependency()` has `static:` argument, there's also `cc.find_library(..., static: true)`. `libcurl4-openssl-dev` provides `.a` library, coudn't we use that instead of adding another subproject?


<!-- Sent from Reviewable.io -->

2022-08-01 17:10 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/773)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow and @woju)

___
*[`meson.build` line 266 at r4](https://reviewable.io/reviews/gramineproject/gramine/773#-N8PJmD6-PFIN7Lms7nJ:-N8PN4Jw4NrG6DTtLfXZ:bdqr1pm) ([raw file](https://github.com/gramineproject/gramine/blob/cf8095d83b634f37d2c5f33a4d9a7881a11432bc/meson.build#L266)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

`dependency()` has `static:` argument, there's also `cc.find_library(..., static: true)`. `libcurl4-openssl-dev` provides `.a` library, coudn't we use that instead of adding another subproject?
</blockquote></details>

@woju I provided the main argument against using the packaged version of `libcurl` in this comment: https://github.com/gramineproject/gramine/pull/773#pullrequestreview-1046110891

The short explanation is that the `libcurl` code will be inside SGX enclaves (almost every production Gramine-SGX enclave really). And we want to have the minimal reproducible well-known-to-us configuration of `libcurl` inside the SGX enclave.


<!-- Sent from Reviewable.io -->

2022-08-01 17:10 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/773)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/773#-N7vI_7q-3nTTSbUQaUi:-N8PNi5K8kEsORG2xaHa:b-krhyce) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Just a reminder, this PR is blocking on https://github.com/gramineproject/gramine/pull/799. That PR will be merged today, and then this PR can be rebased on top of it (there are no other blocking comments).
</blockquote></details>

@kailun-qin #799 was merged just now. Could you rebase your PR on top of the latest master (+ verify that it still works correctly)?

___


<!-- Sent from Reviewable.io -->

2022-08-01 17:28 UTC, woju submitted a review, later dismissed
> Reviewed 8 of 10 files at r1, 3 of 4 files at r2, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/773)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`meson.build` line 266 at r4](https://reviewable.io/reviews/gramineproject/gramine/773#-N8PJmD6-PFIN7Lms7nJ:-N8PPaOdE4h0z-HAN0rT:b33m7cp) ([raw file](https://github.com/gramineproject/gramine/blob/cf8095d83b634f37d2c5f33a4d9a7881a11432bc/meson.build#L266)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@woju I provided the main argument against using the packaged version of `libcurl` in this comment: https://github.com/gramineproject/gramine/pull/773#pullrequestreview-1046110891

The short explanation is that the `libcurl` code will be inside SGX enclaves (almost every production Gramine-SGX enclave really). And we want to have the minimal reproducible well-known-to-us configuration of `libcurl` inside the SGX enclave.
</blockquote></details>

Ah, OK. Sorry, I've missed it, this was part of a closed discussion, which I've now read. Yes, that's correct. So (non-blocking) I'd suggest to name the variables `curl_minimal_*`, not `static`, per @boryspoplawski's comment.


<!-- Sent from Reviewable.io -->

2022-08-01 17:51 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/773)* status: all files reviewed, 2 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @kailun-qin, and @mkow)

___
*[`meson.build` line 266 at r4](https://reviewable.io/reviews/gramineproject/gramine/773#-N8PJmD6-PFIN7Lms7nJ:-N8PXANI7PXQ5RYq8lQZ:b-f0ed8z) ([raw file](https://github.com/gramineproject/gramine/blob/cf8095d83b634f37d2c5f33a4d9a7881a11432bc/meson.build#L266)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Ah, OK. Sorry, I've missed it, this was part of a closed discussion, which I've now read. Yes, that's correct. So (non-blocking) I'd suggest to name the variables `curl_minimal_*`, not `static`, per @boryspoplawski's comment.
</blockquote></details>

+1 to `curl_minimal_*`, I'm blocking on this change. @kailun-qin Please do it.


<!-- Sent from Reviewable.io -->

2022-08-02 13:14 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/773)* status: 5 of 12 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski, @dimakuv, @mkow, and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/773#-N7vI_7q-3nTTSbUQaUi:-N8Tf65sCXvO7xPYinaM:b8ggxu8) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@kailun-qin #799 was merged just now. Could you rebase your PR on top of the latest master (+ verify that it still works correctly)?
</blockquote></details>

Rebased on top of the latest master. Found some issues when 1) incompatible versions of mbedTLS are installed; or 2) no mbedTLS is installed on system.

We have to force mbedTLS as the curl backend when building it - however this incurs some hacks. Pls kindly see the changes in `subprojects/packagefiles/curl-7.84.0/compile.sh` below.

___
___
*[`meson.build` line 266 at r4](https://reviewable.io/reviews/gramineproject/gramine/773#-N8PJmD6-PFIN7Lms7nJ:-N8QypahBCmPKS3WD-RJ:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/cf8095d83b634f37d2c5f33a4d9a7881a11432bc/meson.build#L266)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

+1 to `curl_minimal_*`, I'm blocking on this change. @kailun-qin Please do it.
</blockquote></details>

Done.
___
*[`subprojects/packagefiles/curl-7.84.0/compile.sh` line 83 at r5](https://reviewable.io/reviews/gramineproject/gramine/773#-N8Tfuue19F8-1JdyYg9:-N8Tfuue19F8-1JdyYgA:blk6q96) ([raw file](https://github.com/gramineproject/gramine/blob/c4e664a24244f4c2d9e90c3de9cbbb782d1616e8/subprojects/packagefiles/curl-7.84.0/compile.sh#L83)):*
> ```Shell
>         >>"$BUILD_LOG" 2>&1
> 
>     # HACK: We need to configure libcurl with mbedTLS and should not build the curl executable to
> ```

I dislike it. But sorry that I didn't think of a better way for it. Let me know if any suggestion.


<!-- Sent from Reviewable.io -->

2022-08-02 15:01 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/773)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski, @dimakuv, @kailun-qin, and @mkow)

___
*[`-- commits` line 2 at r5](https://reviewable.io/reviews/gramineproject/gramine/773#-N8TjfdMC2i-Hil3Weee):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This is too long. Maybe something like:
</blockquote></details>

Done.
___
*[`-- commits` line 11 at r5](https://reviewable.io/reviews/gramineproject/gramine/773#-N8TjqPoAx2FON4sePBv):*
Done.
___
*[`-- commits` line 15 at r5](https://reviewable.io/reviews/gramineproject/gramine/773#-N8Tk_Ol2ev1aX8q7UTx):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Shouldn't this be `libcurl`?
</blockquote></details>

Done.
___
*[`subprojects/packagefiles/curl-7.84.0/compile.sh` line 33 at r5](https://reviewable.io/reviews/gramineproject/gramine/773#-N8TmdSB-QEdGVFyQ3vl:-N8TxOf80LE6khk2jgbP:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/c4e664a24244f4c2d9e90c3de9cbbb782d1616e8/subprojects/packagefiles/curl-7.84.0/compile.sh#L33)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Hmm, could you sort this list?
</blockquote></details>

Done.
___
*[`subprojects/packagefiles/curl-7.84.0/compile.sh` line 80 at r5](https://reviewable.io/reviews/gramineproject/gramine/773#-N8TpRh9B2aLujbV1lFE:-N8Trz-j9WRo25ZbtyNS:b-totikz) ([raw file](https://github.com/gramineproject/gramine/blob/c4e664a24244f4c2d9e90c3de9cbbb782d1616e8/subprojects/packagefiles/curl-7.84.0/compile.sh#L80)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Wait, you build this against **host** mbedtls, not our own subproject. You need to specify `--with-mbedtls=path_to_our_mbedtls`, but that would require a dependency of subprojects (see the other discussion about it)
</blockquote></details>

Yes and no, actully we can even use `--withous-ssl` as it's overwritten (anyway) by the hack (in this current version).

There are several concerns (reasons why I introduced that hack):
1. `--with-mbedtls=path_to_our_mbedtls` would require a dependency of subprojects (which needs to be ready before building `curl`). Given mbedtls now servers both Gramine and curl, it's kind of complicated for Meson I imagine.
2. Even 1) is addressed by some Meson tricks (probably using some other nested hierachies), it won't work until we additionally generate specific ones (w/o `_pal` suffiexes) for `curl` so that they can be detected; otherwise a hack into curl build system may be still needed. This is because `--with-mbedtls=<path>` will try to search `-lmbedtls -lmbedx509 -lmbedcrypto` specifically and has other requirements like the header is placed at `path/include` and libraries are placed at `path/lib` (as it's assuming that it's a path where mbedtls is installed - Meson usually doesn't install at this phase - then another concern).
3. Even 1) and 2) are done, we still have to disable the building of the curl executable as we don't really want it (also don't want it to link w/ our configured mbedtls, it'll probably fail as well).
___
*[`subprojects/packagefiles/curl-7.84.0/compile.sh` line 83 at r5](https://reviewable.io/reviews/gramineproject/gramine/773#-N8TpiG8AKSdr19nwB3t:-N8Ty25U5lLkUnktJTgN:bppa6w) ([raw file](https://github.com/gramineproject/gramine/blob/c4e664a24244f4c2d9e90c3de9cbbb782d1616e8/subprojects/packagefiles/curl-7.84.0/compile.sh#L83)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

1) I don't understand this comment.
2) What's the point of this? Shouldn't this be handled by `--with-mbedtls`? Maybe the problem was that you used host mbedtls (see above), it was not present and `configure` failed?
</blockquote></details>

(I agree that the comment can be confusing...) Pls kindly see my comments above. For a successful `configure`, we may introduce too many changes/hacks.


<!-- Sent from Reviewable.io -->

2022-08-02 15:33 UTC, boryspoplawski requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/773)* status: 11 of 12 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @kailun-qin, and @mkow)

___
*[`subprojects/packagefiles/curl-7.84.0/compile.sh` line 80 at r5](https://reviewable.io/reviews/gramineproject/gramine/773#-N8TpRh9B2aLujbV1lFE:-N8U7-0Y-r2RI3Ttc9rt:bmqnt7v) ([raw file](https://github.com/gramineproject/gramine/blob/c4e664a24244f4c2d9e90c3de9cbbb782d1616e8/subprojects/packagefiles/curl-7.84.0/compile.sh#L80)):*
> Yes and no, actully we can even use --withous-ssl as it's overwritten (anyway) by the hack (in this current version).

But I wanted to remove the hack, so let's talk about a version without it.

Anyway I believe the current version is using host mbedtls, isn't it? It's definitely not using the one we build. So I don't understand the point of these hacks at all.

> 1. --with-mbedtls=path_to_our_mbedtls would require a dependency of subprojects (which needs to be ready before building curl). Given mbedtls now servers both Gramine and curl, it's kind of complicated for Meson I imagine.

This is probably something we need to tackle anyway.

> 2.  Even 1) is addressed by some Meson tricks (probably using some other nested hierachies), it won't work until we additionally generate specific ones (w/o _pal suffiexes) for curl so that they can be detected; otherwise a hack into curl build system may be still needed. This is because --with-mbedtls=<path> will try to search -lmbedtls -lmbedx509 -lmbedcrypto specifically and has other requirements like the header is placed at path/include and libraries are placed at path/lib (as it's assuming that it's a path where mbedtls is installed - Meson usually doesn't install at this phase - then another concern).

Well, yeah, we would have to build mbedtls with correct name.

> 3. Even 1) and 2) are done, we still have to disable the building of the curl executable as we don't really want it (also don't want it to link w/ our configured mbedtls, it'll probably fail as well).

That's not a problem, we can build it and just not install. Or we can work around it with less hacks - just do `cd lib ; make ...` instead of just `make ...`


<!-- Sent from Reviewable.io -->

2022-08-02 15:58 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/773)* status: 11 of 12 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @kailun-qin, and @mkow)

___
*[`subprojects/packagefiles/curl-7.84.0/compile.sh` line 80 at r5](https://reviewable.io/reviews/gramineproject/gramine/773#-N8TpRh9B2aLujbV1lFE:-N8UDZrjE1FTz7LmUZSX:b-wchqvs) ([raw file](https://github.com/gramineproject/gramine/blob/c4e664a24244f4c2d9e90c3de9cbbb782d1616e8/subprojects/packagefiles/curl-7.84.0/compile.sh#L80)):*
> But I wanted to remove the hack, so let's talk about a version without it.

Sure.

> Anyway I believe the current version is using host mbedtls, isn't it? It's definitely not using the one we build. So I don't understand the point of these hacks at all.

Pls correct me if I'm wrong - I don't think it's using host mbedtls, i.e., it should work even w/o host mbedtls (none installed). As we specified CPPFLAGS here: https://github.com/gramineproject/gramine/blob/99f2a4765d394ea1805e3894fa3afa47802537d7/subprojects/packagefiles/curl-7.84.0/compile.sh#L31, libcurl will use our mbedtls 3.x declarations at the compile stage. While at the link stage in `tools/sgx`, it will use still link to the mbedtls we build (and others) (https://github.com/gramineproject/gramine/blob/99f2a4765d394ea1805e3894fa3afa47802537d7/tools/sgx/common/meson.build#L23).

> Well, yeah, we would have to build mbedtls with correct name.
> That's not a problem, we can build it and just not install. Or we can work around it with less hacks - just do cd lib ; make ... instead of just make ...

Looks good! Then only 1) is the major blocker here.


<!-- Sent from Reviewable.io -->

2022-08-02 16:50 UTC, boryspoplawski requested changes
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/773)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @kailun-qin, @mkow, and @woju)

___
*[`subprojects/packagefiles/curl-7.84.0/compile.sh` line 80 at r5](https://reviewable.io/reviews/gramineproject/gramine/773#-N8TpRh9B2aLujbV1lFE:-N8UJslC7gC3G3XJO89n:b3z5fv2) ([raw file](https://github.com/gramineproject/gramine/blob/c4e664a24244f4c2d9e90c3de9cbbb782d1616e8/subprojects/packagefiles/curl-7.84.0/compile.sh#L80)):*
> ls correct me if I'm wrong - I don't think it's using host mbedtls, i.e., it should work even w/o host mbedtls (none installed). As we specified CPPFLAGS here: 

Ah, we build a static library, forgot about that.

Ok, I've taken a look at curl's configure and indeed we have a very limited options:
1) Install mbedtls on host and use it to build here - meh.
2) Build mbedtls with soname and fs layout so that it passes all check in configure - sounds a bit PITA.
3) Manually change configuration like currently.
4) Patch `configure` so that it does not perform the check / check always passes (should be simple `s/no/yes/` in one line).

I think options 3 and 4 are viable, but everything is hacky in some way. cc @dimakuv @mkow @woju 


<!-- Sent from Reviewable.io -->

2022-08-03 13:19 UTC, dimakuv requested changes
> Reviewed 2 of 7 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/773)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @kailun-qin, @mkow, and @woju)

___
*[`subprojects/packagefiles/curl-7.84.0/compile.sh` line 80 at r5](https://reviewable.io/reviews/gramineproject/gramine/773#-N8TpRh9B2aLujbV1lFE:-N8YqKY0CQDe5XsqTt_P:b8r42qe) ([raw file](https://github.com/gramineproject/gramine/blob/c4e664a24244f4c2d9e90c3de9cbbb782d1616e8/subprojects/packagefiles/curl-7.84.0/compile.sh#L80)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

> ls correct me if I'm wrong - I don't think it's using host mbedtls, i.e., it should work even w/o host mbedtls (none installed). As we specified CPPFLAGS here: 

Ah, we build a static library, forgot about that.

Ok, I've taken a look at curl's configure and indeed we have a very limited options:
1) Install mbedtls on host and use it to build here - meh.
2) Build mbedtls with soname and fs layout so that it passes all check in configure - sounds a bit PITA.
3) Manually change configuration like currently.
4) Patch `configure` so that it does not perform the check / check always passes (should be simple `s/no/yes/` in one line).

I think options 3 and 4 are viable, but everything is hacky in some way. cc @dimakuv @mkow @woju 
</blockquote></details>

For option 4, we'll still need to modify the Makefile to disable building the curl executable, right? So it's not like we'll have less hacks with this option.

I vote for option 3, since this was already implemented and tested.

But yes, if there is a way to re-use Meson subprojects in each other, this would be the best solution. But I'm afraid I know the answer to this...
___
*[`subprojects/packagefiles/curl-7.84.0/compile.sh` line 85 at r6](https://reviewable.io/reviews/gramineproject/gramine/773#-N8Yr1znE1XoF9ft9d0p:-N8Yr1znE1XoF9ft9d0q:b7f1yhf) ([raw file](https://github.com/gramineproject/gramine/blob/99f2a4765d394ea1805e3894fa3afa47802537d7/subprojects/packagefiles/curl-7.84.0/compile.sh#L85)):*
> ```Shell
>     # avoid it being linked with the mbedTLS library.
>     # To achieve this, overriding the curl config to force using mbedTLS (even if curl does not
>     # detects it) and disabling in Makefile (which is not supported by curl autotools) the building
> ```

`detect it`
___
*[`subprojects/packagefiles/curl-7.84.0/compile.sh` line 89 at r6](https://reviewable.io/reviews/gramineproject/gramine/773#-N8YplLF-U16bDmA1EoP:-N8YplLF-U16bDmA1EoQ:b1iza3w) ([raw file](https://github.com/gramineproject/gramine/blob/99f2a4765d394ea1805e3894fa3afa47802537d7/subprojects/packagefiles/curl-7.84.0/compile.sh#L89)):*
> ```Shell
>     BDL_PATH='\"\/etc\/ssl\/certs\/ca-certificates\.crt\"'
>     sed -i "s|/\* #undef USE_MBEDTLS \*/|#define USE_MBEDTLS 1|" lib/curl_config.h
>     sed -i "s|/\* #undef CURL_CA_BUNDLE \*/|#define CURL_CA_BUNDLE $BDL_PATH|" lib/curl_config.h
> ```

Why do we need to modify this? Why does configure `undef`s it?
___
*[`subprojects/packagefiles/curl-7.84.0/compile.sh` line 90 at r6](https://reviewable.io/reviews/gramineproject/gramine/773#-N8Ypvae1xXupX9ZyliO:-N8Ypvae1xXupX9ZyliP:b-wadwqq) ([raw file](https://github.com/gramineproject/gramine/blob/99f2a4765d394ea1805e3894fa3afa47802537d7/subprojects/packagefiles/curl-7.84.0/compile.sh#L90)):*
> ```Shell
>     sed -i "s|/\* #undef USE_MBEDTLS \*/|#define USE_MBEDTLS 1|" lib/curl_config.h
>     sed -i "s|/\* #undef CURL_CA_BUNDLE \*/|#define CURL_CA_BUNDLE $BDL_PATH|" lib/curl_config.h
>     sed -i "s/SUBDIRS = lib src/SUBDIRS = lib # src/" Makefile
> ```

Why not just remove `src` instead of commenting it out?


<!-- Sent from Reviewable.io -->

2022-08-03 14:12 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/773)* status: 11 of 12 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @kailun-qin, @mkow, and @woju)

___
*[`subprojects/packagefiles/curl-7.84.0/compile.sh` line 85 at r6](https://reviewable.io/reviews/gramineproject/gramine/773#-N8Yr1znE1XoF9ft9d0p:-N8Z1g29DK--Hzq7dbWG:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/99f2a4765d394ea1805e3894fa3afa47802537d7/subprojects/packagefiles/curl-7.84.0/compile.sh#L85)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`detect it`
</blockquote></details>

Done.
___
*[`subprojects/packagefiles/curl-7.84.0/compile.sh` line 89 at r6](https://reviewable.io/reviews/gramineproject/gramine/773#-N8YplLF-U16bDmA1EoP:-N8Z1hRZ9XMl8jp6WF3W:bb6o65n) ([raw file](https://github.com/gramineproject/gramine/blob/99f2a4765d394ea1805e3894fa3afa47802537d7/subprojects/packagefiles/curl-7.84.0/compile.sh#L89)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do we need to modify this? Why does configure `undef`s it?
</blockquote></details>

If none mbedTLS is installed - in which case configure cannot find SSL, it will `undef` it. With an SSL backend successfully detected, it will be set (so that we need to force it to be set).
___
*[`subprojects/packagefiles/curl-7.84.0/compile.sh` line 90 at r6](https://reviewable.io/reviews/gramineproject/gramine/773#-N8Ypvae1xXupX9ZyliO:-N8Z1h6N0aTtxO_VkQnv:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/99f2a4765d394ea1805e3894fa3afa47802537d7/subprojects/packagefiles/curl-7.84.0/compile.sh#L90)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why not just remove `src` instead of commenting it out?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-03 14:19 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/773)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @kailun-qin, @mkow, and @woju)

___
*[`subprojects/packagefiles/curl-7.84.0/compile.sh` line 89 at r6](https://reviewable.io/reviews/gramineproject/gramine/773#-N8YplLF-U16bDmA1EoP:-N8Z3_mvD5JnBp1dnOW-:b66ebw5) ([raw file](https://github.com/gramineproject/gramine/blob/99f2a4765d394ea1805e3894fa3afa47802537d7/subprojects/packagefiles/curl-7.84.0/compile.sh#L89)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

If none mbedTLS is installed - in which case configure cannot find SSL, it will `undef` it. With an SSL backend successfully detected, it will be set (so that we need to force it to be set).
</blockquote></details>

Got it. I thought to put it in a comment initially, but it is such a hack that explaining it is too much :) I'm fine with the current comment.


<!-- Sent from Reviewable.io -->

2022-08-03 14:41 UTC, boryspoplawski requested changes
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/773)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @kailun-qin, @mkow, and @woju)

___
*[`subprojects/packagefiles/curl-7.84.0/compile.sh` line 80 at r5](https://reviewable.io/reviews/gramineproject/gramine/773#-N8TpRh9B2aLujbV1lFE:-N8Z8S1D0Bcfeb2FScJF:b-d2c61b) ([raw file](https://github.com/gramineproject/gramine/blob/c4e664a24244f4c2d9e90c3de9cbbb782d1616e8/subprojects/packagefiles/curl-7.84.0/compile.sh#L80)):*
> For option 4, we'll still need to modify the Makefile to disable building the curl executable, right? So it's not like we'll have less hacks with this option.

No, we can just `cd lib; make` instead of doing `make` in top-level dir (basically equivalent to the current patch, which disables building `src`). Or we can build the executable, why is that such a big deal to you?


<!-- Sent from Reviewable.io -->

2022-08-03 14:45 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/773)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @kailun-qin, @mkow, and @woju)

___
*[`subprojects/packagefiles/curl-7.84.0/compile.sh` line 80 at r5](https://reviewable.io/reviews/gramineproject/gramine/773#-N8TpRh9B2aLujbV1lFE:-N8Z9Fxk0OEyiQKiIk7k:bf38ylb) ([raw file](https://github.com/gramineproject/gramine/blob/c4e664a24244f4c2d9e90c3de9cbbb782d1616e8/subprojects/packagefiles/curl-7.84.0/compile.sh#L80)):*
>  Or we can build the executable, why is that such a big deal to you?

As @kailun-qin mentioned above, building the `curl` executable requires a linking stage which will fail if there is no mbedTLS installed on the host (there are no static mbedTLS libs to get from).

Or do you mean that we'll have our mbedTLS already built, as a dependency for this Curl build? And so the executable will link against our mbedTLS? Then yes, I don't care about skipping the `curl` executable building step.


<!-- Sent from Reviewable.io -->

2022-08-03 16:41 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/773)* status: 11 of 12 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @kailun-qin, @mkow, and @woju)

___
*[`subprojects/packagefiles/curl-7.84.0/compile.sh` line 80 at r5](https://reviewable.io/reviews/gramineproject/gramine/773#-N8TpRh9B2aLujbV1lFE:-N8Z_-ex6-EU2zyP8NaO:buu026u) ([raw file](https://github.com/gramineproject/gramine/blob/c4e664a24244f4c2d9e90c3de9cbbb782d1616e8/subprojects/packagefiles/curl-7.84.0/compile.sh#L80)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

>  Or we can build the executable, why is that such a big deal to you?

As @kailun-qin mentioned above, building the `curl` executable requires a linking stage which will fail if there is no mbedTLS installed on the host (there are no static mbedTLS libs to get from).

Or do you mean that we'll have our mbedTLS already built, as a dependency for this Curl build? And so the executable will link against our mbedTLS? Then yes, I don't care about skipping the `curl` executable building step.
</blockquote></details>

Switching to opt#4, pls kindly see if it's less hacky for you.


<!-- Sent from Reviewable.io -->

2022-08-03 16:52 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/773)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @kailun-qin, @mkow, and @woju)



<!-- Sent from Reviewable.io -->

2022-08-03 18:17 UTC, boryspoplawski requested changes
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/773)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin, @mkow, and @woju)

___
*[`subprojects/packagefiles/curl-7.84.0/compile.sh` line 80 at r5](https://reviewable.io/reviews/gramineproject/gramine/773#-N8TpRh9B2aLujbV1lFE:-N8Zuy1o-RYhZEXXt3RL:bxp1rfr) ([raw file](https://github.com/gramineproject/gramine/blob/c4e664a24244f4c2d9e90c3de9cbbb782d1616e8/subprojects/packagefiles/curl-7.84.0/compile.sh#L80)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Switching to opt#4, pls kindly see if it's less hacky for you.
</blockquote></details>

Now we change something that is a part of curl source, so we can use a patch file and apply it here (just like we do with other subprojects). I think it would be a better approach - easier to see what it does and harder to mess once we update curl to a newer version.

But overall I prefer this option than 3.


<!-- Sent from Reviewable.io -->

2022-08-04 03:56 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/773)* status: 11 of 13 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @kailun-qin, @mkow, and @woju)

___
*[`subprojects/packagefiles/curl-7.84.0/compile.sh` line 80 at r5](https://reviewable.io/reviews/gramineproject/gramine/773#-N8TpRh9B2aLujbV1lFE:-N8azg7t4wdCR2yziyeo:b4ubxqy) ([raw file](https://github.com/gramineproject/gramine/blob/c4e664a24244f4c2d9e90c3de9cbbb782d1616e8/subprojects/packagefiles/curl-7.84.0/compile.sh#L80)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Now we change something that is a part of curl source, so we can use a patch file and apply it here (just like we do with other subprojects). I think it would be a better approach - easier to see what it does and harder to mess once we update curl to a newer version.

But overall I prefer this option than 3.
</blockquote></details>

Using a patch file now, thanks!


<!-- Sent from Reviewable.io -->

2022-08-04 07:03 UTC, dimakuv approved these changes
> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/773)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin, @mkow, and @woju)



<!-- Sent from Reviewable.io -->

2022-08-04 07:03 UTC, dimakuv commented
Jenkins, test this please

2022-08-04 09:24 UTC, woju requested changes
> Reviewed 3 of 7 files at r5.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/773)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @woju)

___
*[`subprojects/packagefiles/curl-7.84.0/meson.build` line 6 at r5](https://reviewable.io/reviews/gramineproject/gramine/773#-N8TlDOg08Z-gOZy28D4:-N8c58w_9Yci7qXvR0Jb:btopo1a) ([raw file](https://github.com/gramineproject/gramine/blob/c4e664a24244f4c2d9e90c3de9cbbb782d1616e8/subprojects/packagefiles/curl-7.84.0/meson.build#L6)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Ugh, this is bad, when we change mbedtls version this will break. How do you create deps between subprojects?
Summon @woju
</blockquote></details>

I see two options:
- `meson.override_dependency('mbedtls_gramine', mbedtls_gramine_dep)` (https://mesonbuild.com/Reference-manual_builtin_meson.html#mesonoverride_dependency; unless something breaks, I suggest this option). I don't know how strictly you need to keep the order of things (first `subproject('mbedtls')` and extract dep, then `meson.override_dependency()`, then `subproject('curl')`? didn't test). You can also `override_dependency()` from the subproject itself, but from parent project pov this would be kinda magic (and I also don't know what would happen if you reversed the order).
- Instead of a single `subprojects/` directory, you can have subproject of a subproject. If you also need the grandchild in the grandparent project, you can reexport the project/dependency as a variable in the middle project. This theoretically always works (unless you have dependency cycle), but is ugly and require manual linearisation of dependencies. I already have flashbacks from `__mro__`.

I'm blocking until this is resolved.


<!-- Sent from Reviewable.io -->

2022-08-04 12:01 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/773)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @woju)

___
*[`subprojects/packagefiles/curl-7.84.0/meson.build` line 6 at r5](https://reviewable.io/reviews/gramineproject/gramine/773#-N8TlDOg08Z-gOZy28D4:-N8cdyoE8V-654nYk6Q1:b-cvhbwg) ([raw file](https://github.com/gramineproject/gramine/blob/c4e664a24244f4c2d9e90c3de9cbbb782d1616e8/subprojects/packagefiles/curl-7.84.0/meson.build#L6)):*
> meson.override_dependency

Sorry that I still don't quite get how the opt#1 works. We override the `mbedtls_proj` with `mbedtls_pal_dep` (a declared dep) so that whenever `dependency()` with `mbedtls_proj` is used (e.g., before `subproject('curl')`), Meson will return `mbedtls_pal_dep` - this is fine. But how can we guarantee while building curl subproject/custom_target w/ ninja, the output of `mbedtls_pal` cutom_target are already available/generated?

As for opt#2, just feel like it's a bit too complicated.


<!-- Sent from Reviewable.io -->

2022-08-04 12:41 UTC, boryspoplawski requested changes
> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/773)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @woju)

___
*[`subprojects/packagefiles/curl-7.84.0/curl-7.84.0.patch` line 21 at r9](https://reviewable.io/reviews/gramineproject/gramine/773#-N8cr7tX6p6HJ3_x2_nu:-N8cr7tX6p6HJ3_x2_nv:b-9c9lw) ([raw file](https://github.com/gramineproject/gramine/blob/5111eec297f57c083d50b450f9fe94a0bb36cc26/subprojects/packagefiles/curl-7.84.0/curl-7.84.0.patch#L21)):*
> ```Diff
>        check_for_ca_bundle=1
>  
> -      LIBS="-lmbedtls -lmbedx509 -lmbedcrypto $LIBS"
> ```

Actually, why do we need this? Don't we skip linking step completely?
___
*[`subprojects/packagefiles/curl-7.84.0/meson.build` line 6 at r5](https://reviewable.io/reviews/gramineproject/gramine/773#-N8TlDOg08Z-gOZy28D4:-N8crVCdEOoJqhocvypP:b84orwo) ([raw file](https://github.com/gramineproject/gramine/blob/c4e664a24244f4c2d9e90c3de9cbbb782d1616e8/subprojects/packagefiles/curl-7.84.0/meson.build#L6)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

> meson.override_dependency

Sorry that I still don't quite get how the opt#1 works. We override the `mbedtls_proj` with `mbedtls_pal_dep` (a declared dep) so that whenever `dependency()` with `mbedtls_proj` is used (e.g., before `subproject('curl')`), Meson will return `mbedtls_pal_dep` - this is fine. But how can we guarantee while building curl subproject/custom_target w/ ninja, the output of `mbedtls_pal` cutom_target are already available/generated?

As for opt#2, just feel like it's a bit too complicated.
</blockquote></details>

Yeah, I don't like 2 either.

A for 1: @woju the problem we are having here is we need to use one subproject (as dependency) in another, which creates an ordering on subproject and requires passing output (dep object) from one to another


<!-- Sent from Reviewable.io -->

2022-08-04 14:10 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/773)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @woju)

___
*[`subprojects/packagefiles/curl-7.84.0/curl-7.84.0.patch` line 21 at r9](https://reviewable.io/reviews/gramineproject/gramine/773#-N8cr7tX6p6HJ3_x2_nu:-N8dAA-jDnvQ3DUZYXz2:b-4tnaqa) ([raw file](https://github.com/gramineproject/gramine/blob/5111eec297f57c083d50b450f9fe94a0bb36cc26/subprojects/packagefiles/curl-7.84.0/curl-7.84.0.patch#L21)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Actually, why do we need this? Don't we skip linking step completely?
</blockquote></details>

Yes, we do skip linking step completely. We need to remove this simply because curl will check the availability of them based on this information at the configure stage. W/o this will lead to a configure error - "one or more libs available at link-time are not available run-time. Libs used at link-time: -lmbedtls -lmbedx509 -lmbedcrypto".


<!-- Sent from Reviewable.io -->

2022-08-04 17:59 UTC, woju requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/773)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[`subprojects/packagefiles/curl-7.84.0/meson.build` line 6 at r5](https://reviewable.io/reviews/gramineproject/gramine/773#-N8TlDOg08Z-gOZy28D4:-N8dzmLsEEILB8N2v21L:b-xhuizd) ([raw file](https://github.com/gramineproject/gramine/blob/c4e664a24244f4c2d9e90c3de9cbbb782d1616e8/subprojects/packagefiles/curl-7.84.0/meson.build#L6)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Yeah, I don't like 2 either.

A for 1: @woju the problem we are having here is we need to use one subproject (as dependency) in another, which creates an ordering on subproject and requires passing output (dep object) from one to another
</blockquote></details>

Minimal example is 8 files, so I can't paste it here: https://github.com/woju/testmesoninterdep. Please note how `proj2` gets `proj1` dependency in top `meson.build` and `subprojects/proj2/meson.build`:

https://github.com/woju/testmesoninterdep/blob/6749cc0b49b4e595e7b901fbf678c9f8518ac068/meson.build#L3-L5

https://github.com/woju/testmesoninterdep/blob/6749cc0b49b4e595e7b901fbf678c9f8518ac068/subprojects/proj2/meson.build#L3

Is this what you meant by "passing output (dep object) from one to another"?


<!-- Sent from Reviewable.io -->

2022-08-05 02:07 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/773)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @woju)

___
*[`subprojects/packagefiles/curl-7.84.0/meson.build` line 6 at r5](https://reviewable.io/reviews/gramineproject/gramine/773#-N8TlDOg08Z-gOZy28D4:-N8fXpg55Hpky8naqfkY:b-tpkf3l) ([raw file](https://github.com/gramineproject/gramine/blob/c4e664a24244f4c2d9e90c3de9cbbb782d1616e8/subprojects/packagefiles/curl-7.84.0/meson.build#L6)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Minimal example is 8 files, so I can't paste it here: https://github.com/woju/testmesoninterdep. Please note how `proj2` gets `proj1` dependency in top `meson.build` and `subprojects/proj2/meson.build`:

https://github.com/woju/testmesoninterdep/blob/6749cc0b49b4e595e7b901fbf678c9f8518ac068/meson.build#L3-L5

https://github.com/woju/testmesoninterdep/blob/6749cc0b49b4e595e7b901fbf678c9f8518ac068/subprojects/proj2/meson.build#L3

Is this what you meant by "passing output (dep object) from one to another"?
</blockquote></details>

Thanks @woju!

I did a quick try following your approach: https://github.com/kailun-qin/gramine/commit/850244703ec248d9dcfcb13a3c01aa489fad1bb3, where I:
- firstly made a new `mbedtls_curl_libs` custom_target (running a script which made a hacky make install based on the requirements of curl) and a new `mbedtls_curl_dep` dep obj
- then overrided at the top level `meson.override_dependency('mbedtls_proj', mbedtls_curl_dep)`
- following by "passing" the dep obj to curl subproject w/ `mbedtls_gramine = dependency('mbedtls_proj')`
- and tried to make it as a dependecy of `curl` via `depends: libmbedtls` (here, I had to make another trick to make an extra dependency and chain it, as 'depends' requires `BuildTarget | CustomTarget` whereas `dependency('mbedtls_proj')` in our case is an `InternalDependency`).

But still, this didn't work - `mbedtls_curl_libs` is generated later than `curl` (it's configure phase). Anything I made wrong here?


<!-- Sent from Reviewable.io -->

2022-08-16 12:25 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/773)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @woju)

___
*[`subprojects/packagefiles/curl-7.84.0/meson.build` line 6 at r5](https://reviewable.io/reviews/gramineproject/gramine/773#-N8TlDOg08Z-gOZy28D4:-N9abOGE4fFI-h9SpJUZ:b90nbmk) ([raw file](https://github.com/gramineproject/gramine/blob/c4e664a24244f4c2d9e90c3de9cbbb782d1616e8/subprojects/packagefiles/curl-7.84.0/meson.build#L6)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Thanks @woju!

I did a quick try following your approach: https://github.com/kailun-qin/gramine/commit/850244703ec248d9dcfcb13a3c01aa489fad1bb3, where I:
- firstly made a new `mbedtls_curl_libs` custom_target (running a script which made a hacky make install based on the requirements of curl) and a new `mbedtls_curl_dep` dep obj
- then overrided at the top level `meson.override_dependency('mbedtls_proj', mbedtls_curl_dep)`
- following by "passing" the dep obj to curl subproject w/ `mbedtls_gramine = dependency('mbedtls_proj')`
- and tried to make it as a dependecy of `curl` via `depends: libmbedtls` (here, I had to make another trick to make an extra dependency and chain it, as 'depends' requires `BuildTarget | CustomTarget` whereas `dependency('mbedtls_proj')` in our case is an `InternalDependency`).

But still, this didn't work - `mbedtls_curl_libs` is generated later than `curl` (it's configure phase). Anything I made wrong here?
</blockquote></details>

@woju @boryspoplawski Any way we can proceed here? We are blocked on this "subproject is a depedency of another subproject".


<!-- Sent from Reviewable.io -->

2022-08-16 16:55 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/773)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @woju)

___
*[`subprojects/packagefiles/curl-7.84.0/meson.build` line 6 at r5](https://reviewable.io/reviews/gramineproject/gramine/773#-N8TlDOg08Z-gOZy28D4:-N9b_5kP6DfYOa4JfjZP:b-gnkep) ([raw file](https://github.com/gramineproject/gramine/blob/c4e664a24244f4c2d9e90c3de9cbbb782d1616e8/subprojects/packagefiles/curl-7.84.0/meson.build#L6)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@woju @boryspoplawski Any way we can proceed here? We are blocked on this "subproject is a depedency of another subproject".
</blockquote></details>

I'm not that familiar with meosn, I would have to play with it myself. @woju should be better suited to answer here


<!-- Sent from Reviewable.io -->

2022-08-26 11:42 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/773)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @woju)

___
*[`subprojects/packagefiles/curl-7.84.0/meson.build` line 6 at r5](https://reviewable.io/reviews/gramineproject/gramine/773#-N8TlDOg08Z-gOZy28D4:-NAOxSFk558M5c_exYVb:brzpqz8) ([raw file](https://github.com/gramineproject/gramine/blob/c4e664a24244f4c2d9e90c3de9cbbb782d1616e8/subprojects/packagefiles/curl-7.84.0/meson.build#L6)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I'm not that familiar with meosn, I would have to play with it myself. @woju should be better suited to answer here
</blockquote></details>

@woju ping


<!-- Sent from Reviewable.io -->

2022-09-01 16:20 UTC, woju commented
*[`subprojects/packagefiles/curl-7.84.0/meson.build` line 6 at r5](https://reviewable.io/reviews/gramineproject/gramine/773#-N8TlDOg08Z-gOZy28D4:-NAtqcCZEZrJtZLiIwE3:b-n1jisb) ([raw file](https://github.com/gramineproject/gramine/blob/c4e664a24244f4c2d9e90c3de9cbbb782d1616e8/subprojects/packagefiles/curl-7.84.0/meson.build#L6)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@woju ping
</blockquote></details>

Hi, sorry for the delay. I'll look into it tomorrow or on Monday.


<!-- Sent from Reviewable.io -->

2022-09-06 00:28 UTC, woju requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/773)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[`subprojects/packagefiles/curl-7.84.0/meson.build` line 6 at r5](https://reviewable.io/reviews/gramineproject/gramine/773#-N8TlDOg08Z-gOZy28D4:-NBEzd6dCvYt__EIoWNB:b-ei6zjz) ([raw file](https://github.com/gramineproject/gramine/blob/c4e664a24244f4c2d9e90c3de9cbbb782d1616e8/subprojects/packagefiles/curl-7.84.0/meson.build#L6)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Hi, sorry for the delay. I'll look into it tomorrow or on Monday.
</blockquote></details>

OK, so the wrong thing is that meson (and by extension, ninja) do not see those configured `.h` files, because those are not declared as outputs from mbedtls and inputs to curl. They usually shoudn't be, because this configuration typically happens during, well, configuration, which for us is `meson setup`. Instead, it sees static libraries (`mbed*.a`) as outputs, and because those aren't needed to generate another static library (`libcurl.a`), it deduces that it can run them in any order (the only constraint being, both mbedtls and curl need to finish before linking actual executable). I think I've fixed it by generating empty `.h` file and propagating it as part of the inter-subproject dependency. My current WIP is in `woju/test-meson-for-kailun-qin` branch, @kailun-qin please check if it works for you.

(Meson treats `.h` in a funny way, they're considered "sources", but not passed as command-line arguments to cc. This makes them suitable as sentries for enforcing compile order, at least the first time. I'm not sure what happens when dependencies from `.d` depfiles kick in.)

The dummy intermediate dependency from kailun-qin@8502447 to fix for `InternalDependency` indeed appears to be necessary, I've reproduced the problem and didn't find a way around it.

Also re: commit from `kailun-qin/test-meson`: Can please someone reread https://github.com/curl/curl/blob/curl-7_84_0/m4/curl-mbedtls.m4#L99? Does it mean that argument to `--with-mbedtls=PATH` is added *after* system-wide paths? So if you have system-wide mbedtls installed, then you're always using distro's mbedtls? If so, this needs patching. (Blocking until fixed or confirmed). Either way, even after reversing order if needed, this seems risky, because we for some reason fail to install (like, the dependencies won't work and ninja will reorder things), the we might get link to system's mbedtls after all. The only thing I can think of to fix this reliably is to have a configure-time check in our `meson.build` to see if system has mbedtls installed and if so, error out of `meson setup`, but this will be very unplesant for people who compile other projects on the same machine. I don't want to do this.


<!-- Sent from Reviewable.io -->

2022-09-06 04:49 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/773)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @woju)

___
*[`subprojects/packagefiles/curl-7.84.0/meson.build` line 6 at r5](https://reviewable.io/reviews/gramineproject/gramine/773#-N8TlDOg08Z-gOZy28D4:-NBFrVt-1bxz8OXPFj17:b9jluhz) ([raw file](https://github.com/gramineproject/gramine/blob/c4e664a24244f4c2d9e90c3de9cbbb782d1616e8/subprojects/packagefiles/curl-7.84.0/meson.build#L6)):*
Thanks a lot @woju for the solution and detailed explanation! I've tested it, it works like a charm w/ the empty `.h` file.

> Can please someone reread https://github.com/curl/curl/blob/curl-7_84_0/m4/curl-mbedtls.m4#L99? Does it mean that argument to --with-mbedtls=PATH is added after system-wide paths? So if you have system-wide mbedtls installed, then you're always using distro's mbedtls? If so, this needs patching. (Blocking until fixed or confirmed).

No, I think here this simply means when `$mbedtlslib` is not empty, it'll be added to `CURL_LIBRARY_PATH` which is further used in `LD_LIBRARY_PATH` for shared lib cases (and anyway having precedence over the system-wide one): https://github.com/curl/curl/blob/curl-7_84_0/m4/curl-functions.m4#L6524-L6526. However in our case, we are specifying `--with-mbedtls` to the specific PATH w/ mbedtls_gramine static libs. This is used for curl configure to check against: https://github.com/curl/curl/blob/curl-7_84_0/m4/curl-mbedtls.m4#L72 and eventually linked with: https://github.com/curl/curl/blob/curl-7_84_0/m4/curl-mbedtls.m4#L91.

I also tested in an env where it has system-wide mbedtls installed (v2.16.4). It will always use/link against our mbedtls (v3.2.1) specified by `--with-mbedtls=PATH` (actually, otherwise this won't even build due to missing definitions in v2.x).


<!-- Sent from Reviewable.io -->

2022-09-06 09:35 UTC, woju requested changes
> Reviewed 2 of 7 files at r5, 7 of 7 files at r10.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/773)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @kailun-qin)

___
*[`-- commits` line 70 at r10](https://reviewable.io/reviews/gramineproject/gramine/773#-NBH8YgbERPGi1R_1b5C):*
Somewhere there it probably needs my `Signed-off-by:`, which you can paste from my WIP commit.
___
*[`subprojects/packagefiles/curl-7.84.0/meson.build` line 6 at r5](https://reviewable.io/reviews/gramineproject/gramine/773#-N8TlDOg08Z-gOZy28D4:-NBH7GJj2hXUO84T-eRW:bsjh9c0) ([raw file](https://github.com/gramineproject/gramine/blob/c4e664a24244f4c2d9e90c3de9cbbb782d1616e8/subprojects/packagefiles/curl-7.84.0/meson.build#L6)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Thanks a lot @woju for the solution and detailed explanation! I've tested it, it works like a charm w/ the empty `.h` file.

> Can please someone reread https://github.com/curl/curl/blob/curl-7_84_0/m4/curl-mbedtls.m4#L99? Does it mean that argument to --with-mbedtls=PATH is added after system-wide paths? So if you have system-wide mbedtls installed, then you're always using distro's mbedtls? If so, this needs patching. (Blocking until fixed or confirmed).

No, I think here this simply means when `$mbedtlslib` is not empty, it'll be added to `CURL_LIBRARY_PATH` which is further used in `LD_LIBRARY_PATH` for shared lib cases (and anyway having precedence over the system-wide one): https://github.com/curl/curl/blob/curl-7_84_0/m4/curl-functions.m4#L6524-L6526. However in our case, we are specifying `--with-mbedtls` to the specific PATH w/ mbedtls_gramine static libs. This is used for curl configure to check against: https://github.com/curl/curl/blob/curl-7_84_0/m4/curl-mbedtls.m4#L72 and eventually linked with: https://github.com/curl/curl/blob/curl-7_84_0/m4/curl-mbedtls.m4#L91.

I also tested in an env where it has system-wide mbedtls installed (v2.16.4). It will always use/link against our mbedtls (v3.2.1) specified by `--with-mbedtls=PATH` (actually, otherwise this won't even build due to missing definitions in v2.x).

</blockquote></details>

OK, so if it works, then OK. I'm not an expert in autotools.
___
*[`subprojects/packagefiles/mbedtls/compile-curl.sh` line 13 at r10](https://reviewable.io/reviews/gramineproject/gramine/773#-NBH86Xf1BMRXPpc7Ike:-NBH86Xf1BMRXPpc7Ikf:b-irpeip) ([raw file](https://github.com/gramineproject/gramine/blob/fd7dbc99fbd5330dcef1c4777752e5f06e5de8b2/subprojects/packagefiles/mbedtls/compile-curl.sh#L13)):*
> ```Shell
> shift 5
> 
> OUTPUTS=""
> ```

`OUTPUTS` look unused?
___
*[`subprojects/packagefiles/mbedtls/meson.build` line 128 at r10](https://reviewable.io/reviews/gramineproject/gramine/773#-NBH8EFO31wRmnGS-6Be:-NBH8EFP7SYlY2j3nOtp:b-dnpfuy) ([raw file](https://github.com/gramineproject/gramine/blob/fd7dbc99fbd5330dcef1c4777752e5f06e5de8b2/subprojects/packagefiles/mbedtls/meson.build#L128)):*
> ```Meson
>     # multiple outputs; however, it allows picking the outputs one by one.
>     link_with: [mbedtls_curl_libs[0], mbedtls_curl_libs[1], mbedtls_curl_libs[2]],
>     sources: [mbedtls_curl_libs[3]],
> ```

I feel like this `sources:` hack also needs a comment.


<!-- Sent from Reviewable.io -->

2022-09-06 10:26 UTC, dimakuv requested changes
> Reviewed 7 of 7 files at r10, all commit messages.
> Dismissed @kailun-qin from a discussion.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/773)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @kailun-qin, and @woju)

___
*[`meson.build` line 260 at r10](https://reviewable.io/reviews/gramineproject/gramine/773#-NBHKLV4DVSQyTWJSYBE:-NBHKLV4DVSQyTWJSYBF:b456gl2) ([raw file](https://github.com/gramineproject/gramine/blob/fd7dbc99fbd5330dcef1c4777752e5f06e5de8b2/meson.build#L260)):*
> ```Meson
> mbedtls_pal_dep = mbedtls_proj.get_variable('mbedtls_pal_dep')
> mbedtls_curl_dep = mbedtls_proj.get_variable('mbedtls_curl_dep')
> meson.override_dependency('mbedtls_curl', mbedtls_curl_dep)
> ```

Why is this here? How does it work?
___
*[`subprojects/packagefiles/curl-7.84.0/meson.build` line 6 at r10](https://reviewable.io/reviews/gramineproject/gramine/773#-NBHKQKcEX3eop1wkylJ:-NBHKQKcEX3eop1wkylK:b-pwvrs8) ([raw file](https://github.com/gramineproject/gramine/blob/fd7dbc99fbd5330dcef1c4777752e5f06e5de8b2/subprojects/packagefiles/curl-7.84.0/meson.build#L6)):*
> ```Meson
> 
> # This dummy target is needed, because custom_target(depends:) needs a "target", not a "dependency"
> mbedtls_dummy_tgt = static_library('dummy', 'dummy.c', dependencies: mbedtls_gramine)
> ```

`tgt` -> `target`
___
*[`subprojects/packagefiles/mbedtls/meson.build` line 95 at r10](https://reviewable.io/reviews/gramineproject/gramine/773#-NBHJCF5DmfYWBuLUd1r:-NBHJCF5DmfYWBuLUd1s:b-i1cz1y) ([raw file](https://github.com/gramineproject/gramine/blob/fd7dbc99fbd5330dcef1c4777752e5f06e5de8b2/subprojects/packagefiles/mbedtls/meson.build#L95)):*
> ```Meson
>         '@OUTPUT@',
>         '--',
>         'SUFFIX=\'\'',
> ```

What's the point in this empty suffix?
___
*[`subprojects/packagefiles/mbedtls/meson.build` line 128 at r10](https://reviewable.io/reviews/gramineproject/gramine/773#-NBH8EFO31wRmnGS-6Be:-NBHJS266vYdex7-f7ca:b32v57) ([raw file](https://github.com/gramineproject/gramine/blob/fd7dbc99fbd5330dcef1c4777752e5f06e5de8b2/subprojects/packagefiles/mbedtls/meson.build#L128)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

I feel like this `sources:` hack also needs a comment.
</blockquote></details>

+1


<!-- Sent from Reviewable.io -->

2022-09-06 12:22 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/773)* status: 12 of 16 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @woju)

___
*[`-- commits` line 70 at r10](https://reviewable.io/reviews/gramineproject/gramine/773#-NBH8YgbERPGi1R_1b5C):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Somewhere there it probably needs my `Signed-off-by:`, which you can paste from my WIP commit.
</blockquote></details>

Added, thanks!
___
*[`meson.build` line 260 at r10](https://reviewable.io/reviews/gramineproject/gramine/773#-NBHKLV4DVSQyTWJSYBE:-NBHj4Ib5f39-s1nJQwB:b-f8sf1p) ([raw file](https://github.com/gramineproject/gramine/blob/fd7dbc99fbd5330dcef1c4777752e5f06e5de8b2/meson.build#L260)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why is this here? How does it work?
</blockquote></details>

Added a comment.
___
*[`subprojects/packagefiles/curl-7.84.0/meson.build` line 6 at r10](https://reviewable.io/reviews/gramineproject/gramine/773#-NBHKQKcEX3eop1wkylJ:-NBHj8mnDx0VjrMxLknG:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/fd7dbc99fbd5330dcef1c4777752e5f06e5de8b2/subprojects/packagefiles/curl-7.84.0/meson.build#L6)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`tgt` -> `target`
</blockquote></details>

Done.
___
*[`subprojects/packagefiles/mbedtls/compile-curl.sh` line 13 at r10](https://reviewable.io/reviews/gramineproject/gramine/773#-NBH86Xf1BMRXPpc7Ike:-NBHjABOEcysRidCedIz:b-njzfzr) ([raw file](https://github.com/gramineproject/gramine/blob/fd7dbc99fbd5330dcef1c4777752e5f06e5de8b2/subprojects/packagefiles/mbedtls/compile-curl.sh#L13)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

`OUTPUTS` look unused?
</blockquote></details>

Removed, thanks!
___
*[`subprojects/packagefiles/mbedtls/meson.build` line 95 at r10](https://reviewable.io/reviews/gramineproject/gramine/773#-NBHJCF5DmfYWBuLUd1r:-NBHiofk18H_efWnoR35:bo63ly3) ([raw file](https://github.com/gramineproject/gramine/blob/fd7dbc99fbd5330dcef1c4777752e5f06e5de8b2/subprojects/packagefiles/mbedtls/meson.build#L95)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What's the point in this empty suffix?
</blockquote></details>

This is needed due to https://github.com/gramineproject/gramine/blob/7e7e31b1ac9cd94636245ba3c89f6f79c8c0dcc8/subprojects/packagefiles/mbedtls/gramine.patch#L103. Well, I changed to hardcode it into the script.
___
*[`subprojects/packagefiles/mbedtls/meson.build` line 128 at r10](https://reviewable.io/reviews/gramineproject/gramine/773#-NBH8EFO31wRmnGS-6Be:-NBHj-ltAlCvL0Vp4d1c:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/fd7dbc99fbd5330dcef1c4777752e5f06e5de8b2/subprojects/packagefiles/mbedtls/meson.build#L128)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-09-06 14:52 UTC, woju requested changes
> Reviewed 4 of 4 files at r11.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/773)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @kailun-qin, and @woju)

___
*[`meson.build` line 260 at r10](https://reviewable.io/reviews/gramineproject/gramine/773#-NBHKLV4DVSQyTWJSYBE:-NBIF4a22RKJzm8GzeUx:bdlg6yh) ([raw file](https://github.com/gramineproject/gramine/blob/fd7dbc99fbd5330dcef1c4777752e5f06e5de8b2/meson.build#L260)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Added a comment.
</blockquote></details>

This works so that anytime you attempt `dependency()` discovery (which normally tries to discover system-wide dependency via various mechanisms like pkg-config, cmake etc.), instead of that system thinks, you'll really get what is provided here. The important part is, this works across subprojects without passing explicit reference. (We do it to link two subprojects together.)
___
*[`subprojects/packagefiles/mbedtls/compile-curl.sh` line 13 at r10](https://reviewable.io/reviews/gramineproject/gramine/773#-NBH86Xf1BMRXPpc7Ike:-NBIGwXE9aH__3GH7p1A:b-36rous) ([raw file](https://github.com/gramineproject/gramine/blob/fd7dbc99fbd5330dcef1c4777752e5f06e5de8b2/subprojects/packagefiles/mbedtls/compile-curl.sh#L13)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Removed, thanks!
</blockquote></details>

No, I mean, why `lib*.a` weren't output as prescribed by `custom_target(output:)`? We need to output those files where meson expects them.
___
*[`subprojects/packagefiles/mbedtls/compile-curl.sh` line 23 at r11](https://reviewable.io/reviews/gramineproject/gramine/773#-NBIGfEBBphUWXm4Rbi4:-NBIGfEBBphUWXm4Rbi5:b-hr53q7) ([raw file](https://github.com/gramineproject/gramine/blob/c7a75aac80d6b59512f8e0c263756a7d983c8de2/subprojects/packagefiles/mbedtls/compile-curl.sh#L23)):*
> ```Shell
> 
> make -C "$PRIVATE_DIR" lib SUFFIX="''" install DESTDIR="$MBEDTLS_CURL_DIR"
> touch "$MBEDTLS_CURL_DIR"/mbedtls-curl-dummy.h
> ```

This also looks wrong. The file should be placed in the build directory corresponding to `meson.build` which executed `compile-curl.sh`.


<!-- Sent from Reviewable.io -->

2022-09-06 16:51 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/773)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @kailun-qin, and @woju)

___
*[`subprojects/packagefiles/mbedtls/compile-curl.sh` line 13 at r10](https://reviewable.io/reviews/gramineproject/gramine/773#-NBH86Xf1BMRXPpc7Ike:-NBIen6eALDUVGnMnEM1:b-btl8bt) ([raw file](https://github.com/gramineproject/gramine/blob/fd7dbc99fbd5330dcef1c4777752e5f06e5de8b2/subprojects/packagefiles/mbedtls/compile-curl.sh#L13)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

No, I mean, why `lib*.a` weren't output as prescribed by `custom_target(output:)`? We need to output those files where meson expects them.
</blockquote></details>

It's unused simply because we're doing directly a `make install DESTDIR=` below: https://github.com/gramineproject/gramine/blob/c7a75aac80d6b59512f8e0c263756a7d983c8de2/subprojects/packagefiles/mbedtls/compile-curl.sh#L22. Note that using `make install` rather than `make` + `manual cp outputs` is due to that curl is expecting `--with-mbedtld=PATH` to be following the exact same folder hierachy/structure as `make install`.

Do we still want to output them to the current build dir (even it's not used anywhere)?


<!-- Sent from Reviewable.io -->

2022-09-06 16:57 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/773)* status: 15 of 16 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @woju)

___
*[`subprojects/packagefiles/mbedtls/compile-curl.sh` line 23 at r11](https://reviewable.io/reviews/gramineproject/gramine/773#-NBIGfEBBphUWXm4Rbi4:-NBIj6eBAidnsklDs9OL:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/c7a75aac80d6b59512f8e0c263756a7d983c8de2/subprojects/packagefiles/mbedtls/compile-curl.sh#L23)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

This also looks wrong. The file should be placed in the build directory corresponding to `meson.build` which executed `compile-curl.sh`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-09-06 17:23 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/773)* status: 14 of 16 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @woju)

___
*[`subprojects/packagefiles/mbedtls/compile-curl.sh` line 13 at r10](https://reviewable.io/reviews/gramineproject/gramine/773#-NBH86Xf1BMRXPpc7Ike:-NBIocrP8kLfdp6fHWqU:b2ibeos) ([raw file](https://github.com/gramineproject/gramine/blob/fd7dbc99fbd5330dcef1c4777752e5f06e5de8b2/subprojects/packagefiles/mbedtls/compile-curl.sh#L13)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

It's unused simply because we're doing directly a `make install DESTDIR=` below: https://github.com/gramineproject/gramine/blob/c7a75aac80d6b59512f8e0c263756a7d983c8de2/subprojects/packagefiles/mbedtls/compile-curl.sh#L22. Note that using `make install` rather than `make` + `manual cp outputs` is due to that curl is expecting `--with-mbedtld=PATH` to be following the exact same folder hierachy/structure as `make install`.

Do we still want to output them to the current build dir (even it's not used anywhere)?
</blockquote></details>

Well, I'm anyway outputing those files. Pls kindly let me know if it's sth you'd expect.
___
*[`subprojects/packagefiles/mbedtls/meson.build` line 95 at r10](https://reviewable.io/reviews/gramineproject/gramine/773#-NBHJCF5DmfYWBuLUd1r:-NBIouFu6VrR0dvYezYL:bqje4z) ([raw file](https://github.com/gramineproject/gramine/blob/fd7dbc99fbd5330dcef1c4777752e5f06e5de8b2/subprojects/packagefiles/mbedtls/meson.build#L95)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

This is needed due to https://github.com/gramineproject/gramine/blob/7e7e31b1ac9cd94636245ba3c89f6f79c8c0dcc8/subprojects/packagefiles/mbedtls/gramine.patch#L103. Well, I changed to hardcode it into the script.
</blockquote></details>

Update: reverting back to passing the empty SUFFIX. Pls kindly let me know if any concern.


<!-- Sent from Reviewable.io -->

2022-09-07 07:06 UTC, dimakuv approved these changes
> Reviewed 2 of 4 files at r11, 2 of 2 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/773)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @kailun-qin, and @woju)

___
*[`-- commits` line 76 at r13](https://reviewable.io/reviews/gramineproject/gramine/773#-NBLkLVJ2iNnXZayiXjz):*
Blocking myself to not forget to add this sign-off of Wojtek during the final rebase.


<!-- Sent from Reviewable.io -->

2022-09-16 12:58 UTC, woju approved these changes
> Reviewed 2 of 2 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/773)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @kailun-qin)

___
*[`subprojects/packagefiles/mbedtls/compile-curl.sh` line 13 at r10](https://reviewable.io/reviews/gramineproject/gramine/773#-NBH86Xf1BMRXPpc7Ike:-NC5N-YvEBcnwUIgBfPB:b-qgq2qx) ([raw file](https://github.com/gramineproject/gramine/blob/fd7dbc99fbd5330dcef1c4777752e5f06e5de8b2/subprojects/packagefiles/mbedtls/compile-curl.sh#L13)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Well, I'm anyway outputing those files. Pls kindly let me know if it's sth you'd expect.
</blockquote></details>

Now looks OK.


<!-- Sent from Reviewable.io -->

2022-10-10 23:35 UTC, boryspoplawski requested changes
> Reviewed 3 of 7 files at r10, 2 of 4 files at r11, 2 of 2 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/773)* status: all files reviewed, 6 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @woju)

___
*[`-- commits` line 76 at r13](https://reviewable.io/reviews/gramineproject/gramine/773#-NBLkLVJ2iNnXZayiXjz):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Blocking myself to not forget to add this sign-off of Wojtek during the final rebase.
</blockquote></details>

Hm, but why is @woju signoff here? He's not added as co-author (so either it's not needed or the latter is missing, I didn't follow the history of this PR, so I don't know which is the case).
___
*[`subprojects/packagefiles/curl-7.84.0/compile.sh` line 31 at r13](https://reviewable.io/reviews/gramineproject/gramine/773#-NE2xNbk1ml8UnrnEoMW:-NE2xNbk1ml8UnrnEoMX:bqf74sp) ([raw file](https://github.com/gramineproject/gramine/blob/65bba7ab9afabe84ae4ad813ee4e482eb95df6f9/subprojects/packagefiles/curl-7.84.0/compile.sh#L31)):*
> ```Shell
>     # The list of configure options is selected based on:
>     # https://github.com/curl/curl/blob/curl-7_84_0/docs/INSTALL.md#reducing-size
>         ./configure                                 \
> ```

Indented too much



_Suggestion:_
```Shell
    ./configure                                 \
```
___
*[`subprojects/packagefiles/mbedtls/compile-curl.sh` line 4 at r13](https://reviewable.io/reviews/gramineproject/gramine/773#-NE38YUp2_qPmGWiowTc:-NE38YUp2_qPmGWiowTd:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/65bba7ab9afabe84ae4ad813ee4e482eb95df6f9/subprojects/packagefiles/mbedtls/compile-curl.sh#L4)):*
> ```Shell
> 
> set -x
> set -e
> ```





_Suggestion:_
```Shell
set -ex
```
___
*[`subprojects/packagefiles/mbedtls/compile-curl.sh` line 31 at r13](https://reviewable.io/reviews/gramineproject/gramine/773#-NE3ALaBDzxNu61rqHW9:-NE3ALaBDzxNu61rqHWA:b-rsjqyy) ([raw file](https://github.com/gramineproject/gramine/blob/65bba7ab9afabe84ae4ad813ee4e482eb95df6f9/subprojects/packagefiles/mbedtls/compile-curl.sh#L31)):*
> ```Shell
> patch -p1 --directory "$PRIVATE_DIR" <"$CURRENT_SOURCE_DIR"/fcntl.patch
> 
> make -C "$PRIVATE_DIR" lib "$@" install DESTDIR="$SUBPROJ_ROOT"/mbedtls-curl
> ```

Is it worth having these scans for `--` just to pass `SUFFIX=''` here? What does it do? can we hardcode it?
___
*[`subprojects/packagefiles/mbedtls/meson.build` line 125 at r13](https://reviewable.io/reviews/gramineproject/gramine/773#-NE3DIy185f1N5m6JZv2:-NE3DIy185f1N5m6JZv3:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/65bba7ab9afabe84ae4ad813ee4e482eb95df6f9/subprojects/packagefiles/mbedtls/meson.build#L125)):*
> ```Meson
> )
> mbedtls_curl_dep = declare_dependency(
>     # HACK: Apparently Meson considers the `mbedtls_pal_libs` to be "not linkable", because it has
> ```





_Suggestion:_
```Meson
mbedtls_curl_libs
```
___
*[`subprojects/packagefiles/mbedtls/meson.build` line 128 at r13](https://reviewable.io/reviews/gramineproject/gramine/773#-NE3Dr3h3rVK-TNY8_u7:-NE3Dr3iEmM3e16aLk7a:b-gv11d2) ([raw file](https://github.com/gramineproject/gramine/blob/65bba7ab9afabe84ae4ad813ee4e482eb95df6f9/subprojects/packagefiles/mbedtls/meson.build#L128)):*
> ```Meson
>     # multiple outputs; however, it allows picking the outputs one by one.
>     link_with: [mbedtls_curl_libs[0], mbedtls_curl_libs[1], mbedtls_curl_libs[2]],
>     # HACK: Meson treats ".h" as "sources", but not passed as command-line arguments to cc. This
> ```

Why do we even need this? Isn't the fact that this is an explicit dependency not enough?


<!-- Sent from Reviewable.io -->

2022-10-11 08:37 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/773)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @woju)

___
*[`-- commits` line 76 at r13](https://reviewable.io/reviews/gramineproject/gramine/773#-NBLkLVJ2iNnXZayiXjz):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Hm, but why is @woju signoff here? He's not added as co-author (so either it's not needed or the latter is missing, I didn't follow the history of this PR, so I don't know which is the case).
</blockquote></details>

The "Co-authored-by" line should be also added, obviously. We just forgot about it.


<!-- Sent from Reviewable.io -->

2022-10-20 05:05 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/773)* status: 13 of 17 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @woju)

___
*[`subprojects/packagefiles/curl-7.84.0/compile.sh` line 31 at r13](https://reviewable.io/reviews/gramineproject/gramine/773#-NE2xNbk1ml8UnrnEoMW:-NEnFyX64e292MT-Rk9j:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/65bba7ab9afabe84ae4ad813ee4e482eb95df6f9/subprojects/packagefiles/curl-7.84.0/compile.sh#L31)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Indented too much
</blockquote></details>

Done.
___
*[`subprojects/packagefiles/mbedtls/compile-curl.sh` line 4 at r13](https://reviewable.io/reviews/gramineproject/gramine/773#-NE38YUp2_qPmGWiowTc:-NEnGAyU2tkcTVsCDNPJ:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/65bba7ab9afabe84ae4ad813ee4e482eb95df6f9/subprojects/packagefiles/mbedtls/compile-curl.sh#L4)):*
> ```Shell
> 
> set -x
> set -e
> ```

Done.
___
*[`subprojects/packagefiles/mbedtls/compile-curl.sh` line 31 at r13](https://reviewable.io/reviews/gramineproject/gramine/773#-NE3ALaBDzxNu61rqHW9:-NEnJLsp5Dk3AfIBRaR2:b-o85xi8) ([raw file](https://github.com/gramineproject/gramine/blob/65bba7ab9afabe84ae4ad813ee4e482eb95df6f9/subprojects/packagefiles/mbedtls/compile-curl.sh#L31)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Is it worth having these scans for `--` just to pass `SUFFIX=''` here? What does it do? can we hardcode it?
</blockquote></details>

Yeah, it's not worth it and I indeed hardcoded it before... Fixed, thanks!
___
*[`subprojects/packagefiles/mbedtls/meson.build` line 125 at r13](https://reviewable.io/reviews/gramineproject/gramine/773#-NE3DIy185f1N5m6JZv2:-NEnGkmH0oWb5TU1x5V5:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/65bba7ab9afabe84ae4ad813ee4e482eb95df6f9/subprojects/packagefiles/mbedtls/meson.build#L125)):*
> ```Meson
> )
> mbedtls_curl_dep = declare_dependency(
>     # HACK: Apparently Meson considers the `mbedtls_pal_libs` to be "not linkable", because it has
> ```

Done.
___
*[`subprojects/packagefiles/mbedtls/meson.build` line 128 at r13](https://reviewable.io/reviews/gramineproject/gramine/773#-NE3Dr3h3rVK-TNY8_u7:-NEnHgvnEZgrTTOsC0kw:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/65bba7ab9afabe84ae4ad813ee4e482eb95df6f9/subprojects/packagefiles/mbedtls/meson.build#L128)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why do we even need this? Isn't the fact that this is an explicit dependency not enough?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-10-21 09:25 UTC, dimakuv approved these changes
> Reviewed 3 of 7 files at r5, 4 of 4 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/773)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @woju)



<!-- Sent from Reviewable.io -->

2022-10-21 11:19 UTC, boryspoplawski requested changes
> Reviewed 4 of 4 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/773)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @woju)

___
*[`subprojects/packagefiles/mbedtls/compile-curl.sh` line 17 at r14](https://reviewable.io/reviews/gramineproject/gramine/773#-NEuF_2y4klccZVTVOcE:-NEuF_2y4klccZVTVOcF:bwn701h) ([raw file](https://github.com/gramineproject/gramine/blob/862640e747a75929f32f43851842ed86beef9ed3/subprojects/packagefiles/mbedtls/compile-curl.sh#L17)):*
> ```Shell
>     OUTPUTS="$OUTPUTS $1"
>     shift
> done
> ```

Isn't this just `$@`?



_Code quote:_
```Shell
OUTPUTS=""
while test "$#" -gt 0
do
    OUTPUTS="$OUTPUTS $1"
    shift
done
```
___
*[`subprojects/packagefiles/mbedtls/meson.build` line 128 at r13](https://reviewable.io/reviews/gramineproject/gramine/773#-NE3Dr3h3rVK-TNY8_u7:-NEuG-nI1FZwZJPwVep-:bwtvqkl) ([raw file](https://github.com/gramineproject/gramine/blob/65bba7ab9afabe84ae4ad813ee4e482eb95df6f9/subprojects/packagefiles/mbedtls/meson.build#L128)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I meant the whole hack, not the comment.


<!-- Sent from Reviewable.io -->

2022-10-21 11:52 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/773)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @woju)

___
*[`subprojects/packagefiles/mbedtls/compile-curl.sh` line 17 at r14](https://reviewable.io/reviews/gramineproject/gramine/773#-NEuF_2y4klccZVTVOcE:-NEuJT3PA8f8gj0wjZCE:bves986) ([raw file](https://github.com/gramineproject/gramine/blob/862640e747a75929f32f43851842ed86beef9ed3/subprojects/packagefiles/mbedtls/compile-curl.sh#L17)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Isn't this just `$@`?
</blockquote></details>

Good catch! Fixed.
___
*[`subprojects/packagefiles/mbedtls/meson.build` line 128 at r13](https://reviewable.io/reviews/gramineproject/gramine/773#-NE3Dr3h3rVK-TNY8_u7:-NEuN0Wr2o7TeKhBe2Tw:bxom5ff) ([raw file](https://github.com/gramineproject/gramine/blob/65bba7ab9afabe84ae4ad813ee4e482eb95df6f9/subprojects/packagefiles/mbedtls/meson.build#L128)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I meant the whole hack, not the comment.
</blockquote></details>

The hack is needed. The explict dependency (described here: https://github.com/gramineproject/gramine/pull/773#pullrequestreview-1062765122) doesn't work, we have to generate an `empty.h` file and propogate it as part of the inter-subproject dependencyas to enforce the compile order (as said in the comment), pls kindly find the detailed explanations by @woju here: https://github.com/gramineproject/gramine/pull/773#pullrequestreview-1096815884.


<!-- Sent from Reviewable.io -->

2022-10-21 12:21 UTC, boryspoplawski approved these changes
> Reviewed 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/773)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @woju)

___
*[`subprojects/packagefiles/mbedtls/meson.build` line 128 at r13](https://reviewable.io/reviews/gramineproject/gramine/773#-NE3Dr3h3rVK-TNY8_u7:-NEuUFqJ8LS2RTDGkL4Y:b43x4r) ([raw file](https://github.com/gramineproject/gramine/blob/65bba7ab9afabe84ae4ad813ee4e482eb95df6f9/subprojects/packagefiles/mbedtls/meson.build#L128)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

The hack is needed. The explict dependency (described here: https://github.com/gramineproject/gramine/pull/773#pullrequestreview-1062765122) doesn't work, we have to generate an `empty.h` file and propogate it as part of the inter-subproject dependencyas to enforce the compile order (as said in the comment), pls kindly find the detailed explanations by @woju here: https://github.com/gramineproject/gramine/pull/773#pullrequestreview-1096815884.
</blockquote></details>

I guess I was just lucky when I've tested it and it worked without this hack


<!-- Sent from Reviewable.io -->

2022-10-21 12:21 UTC, boryspoplawski commented
Jenkins, test this please

2022-10-21 16:34 UTC, mkow reviewed
> Reviewed 4 of 7 files at r5, 2 of 7 files at r10, 2 of 4 files at r11, 3 of 4 files at r14, 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/773)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @woju)

___
*[`subprojects/packagefiles/mbedtls/meson.build` line 124 at r15](https://reviewable.io/reviews/gramineproject/gramine/773#-NEvNMBnEYIsj43fIJDS:-NEvNMBnEYIsj43fIJDT:b-mtcayo) ([raw file](https://github.com/gramineproject/gramine/blob/cbb23985a1cff833bf036ec96a8f69c2423b96bd/subprojects/packagefiles/mbedtls/meson.build#L124)):*
> ```
> # HACK: Apparently Meson considers the `mbedtls_curl_libs` to be "not linkable", because it has
> # multiple outputs; however, it allows picking the outputs one by one.
> ```

@eli-schwartz: Maybe you would know a better solution to this? (and the other hack below)


<!-- Sent from Reviewable.io -->

2022-10-21 17:20 UTC, eli-schwartz commented
For the not linkable custom target, I'm guessing the problem is that if you try to link to the entire list of outputs it would attempt to pass a `*.h` file to the linker, which is not allowed, so Meson refuses to generate a ninja build file that would attempt it. I think this is probably expected.

What do you need the dummy header for? What happens if you try to compile (but not link) things that depend on mbedtls_curl, before those libs are built? This should usually be acceptable during parallel builds.

It sounds like that build step ***also*** emits a header that you do need, so maybe that should be one of the outputs, instead of the dummy header?

2022-10-24 01:28 UTC, kailun-qin reviewed
> What do you need the dummy header for?

It's used as sentries for enforcing compile order, at least the first time. We use the generated dummy header and propagate it as part of the inter-subproject dependency to make sure that `mbedtls_curl_libs` are ready before `libcurl` is compiling, which is required by configuring to build `libcurl` w/ `--with-mbedtls=path_to_our_mbedtls`.

> What happens if you try to compile (but not link) things that depend on mbedtls_curl, before those libs are built? This should usually be acceptable during parallel builds.

Then either `libcurl` is built w/o SSL (mbedtls) configured or the compliation will simply fail due to that another (incompatible) version of libmbedtls was installed on host.

> It sounds like that build step also emits a header that you do need, so maybe that should be one of the outputs, instead of the dummy header?

I'm not sure whether the build step of mbedtls `emits` a header (but liibs). Which header are you refering to? Thanks!

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/773#-:-NF6TVTTDn_2aa-JBuqF:b-1vx28p)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @woju)



<!-- Sent from Reviewable.io -->

2022-10-24 08:16 UTC, dimakuv reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/773)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @woju)



<!-- Sent from Reviewable.io -->

2022-10-26 08:48 UTC, dimakuv reviewed
@eli-schwartz Could you check the reply? Is the trick meaningful, or is there another way of doing this?

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/773#-:-NFITW_94OSWXsbLDnr8:b8m40k8)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @woju)



<!-- Sent from Reviewable.io -->

2022-10-26 17:06 UTC, boryspoplawski requested changes
> What do you need the dummy header for? What happens if you try to compile (but not link) things that depend on mbedtls_curl, before those libs are built? This should usually be acceptable during parallel builds.
> It sounds like that build step also emits a header that you do need, so maybe that should be one of the outputs, instead of the dummy header?

`mbedtls_curl` has headers that `libcurl` depends on. Those headers are present in the downloaded tar ball, then possibly patched (though I don't think it's the case, we probably only patch source), then build. Which leads me to believe that indeed this PR is missing something.

> which is required by configuring to build libcurl w/ --with-mbedtls=path_to_our_mbedtls.

Then either that step doesn't need mbedtls headers and something is weird (would be good if you provides some errors that happen when compilation fails - why does it not compile exactly) or it does need them and those headers should be put as outputs of `mbedtls_curl`, just as @eli-schwartz suggested.

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/773#-:-NFKE1pO1J4cMVq42uQ2:bun1mba)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @woju)



<!-- Sent from Reviewable.io -->

2022-10-27 02:47 UTC, kailun-qin reviewed
> mbedtls_curl has headers that libcurl depends on.

Below are some of the headers that `libcurl` depends on. They are probably unpatched.
```
#include <mbedtls/version.h>
#if MBEDTLS_VERSION_NUMBER >= 0x02040000
#include <mbedtls/net_sockets.h>
#else
#include <mbedtls/net.h>
#endif
#include <mbedtls/ssl.h>
#include <mbedtls/x509.h>

#include <mbedtls/error.h>
#include <mbedtls/entropy.h>
#include <mbedtls/ctr_drbg.h>
#include <mbedtls/sha256.h>
```

> would be good if you provides some errors that happen when compilation fails - why does it not compile exactly
> or it does need them and those headers should be put as outputs of mbedtls_curl

At the configure stage, `libcurl` will try to check wheter `mbedtls_ssl_init()` (which is from `ssl.h`) exists in `-lmbedtls` to decide whether mbedtls is detected.

At the compile stage, `libcurl` will fail w/ `` (which is from `sha256.h`) if a incompatible version of mbedtls is installed on host.

These headers are not **emitted** by mbedtls (they exist always but just are copied to the install directory during the install phase).

If you really want to get rid of the dummy header file created - we can just rename https://github.com/gramineproject/gramine/blob/cbb23985a1cff833bf036ec96a8f69c2423b96bd/subprojects/packagefiles/mbedtls/meson.build#L102 to whatever the name we want (e.g., `ssl.h`), then remove the dummy header to be created: https://github.com/gramineproject/gramine/blob/cbb23985a1cff833bf036ec96a8f69c2423b96bd/subprojects/packagefiles/mbedtls/compile-curl.sh#L20 and hack the `$@` to ignore it from the `$OUTPUTS` or just fix it to `$PRIVATE_DIR/include/mbedtls/ssl.h`...

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/773#-:-NFMBdEf-8kyKVpNZE1D:buvpp5r)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @woju)



<!-- Sent from Reviewable.io -->

2022-10-27 10:28 UTC, boryspoplawski reviewed
> At the configure stage, libcurl will try to check wheter mbedtls_ssl_init() (which is from ssl.h) exists in -lmbedtls to decide whether mbedtls is detected.

And does it fail? For me it worked (without dummy headers).
We have this `include_directories: mbedtls_inc,` in `mbedtls_curl_dep`, which should be enough

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/773#-:-NFNxsn00CVNMvtO9QUM:b-x5w0si)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @woju)



<!-- Sent from Reviewable.io -->

2022-10-28 03:52 UTC, kailun-qin reviewed
> And does it fail? For me it worked (without dummy headers).

I suspect your env does not have any host-level `libmbedtls` installed. So it won't fail the compile but the configure stage is still incorrect. And this will lead to a problem/error if an incompatible version of `libmbedtls` was installed on host.

Would you pls kindly take a look at the build log of curl (`build/subprojects/curl-7.84.0/curl-build.log`)? - seaching for `ssl`/`mbedtls`, is `libcurl` successfully configured with `mbedtls` or any SSL?

Also would you pls kindly
1. `sudo apt install libmbedtls-dev` on your host
2. and `rm -rf build/ subprojects/mbedtls-mbedtls-3.2.1 subprojects/curl-7.84.0` for a clean setup

to take another try (with `sources: [mbedtls_curl_libs[3]]` removed)?

On e.g., ubuntu 20.04, it'll be `libmbedtls-dev_2.16.4` installed, and you should be able to see some compilation errors like:
```
/usr/local/bin/ld: subprojects/curl-7.84.0/libcurl.a(libcurl_la-mbedtls.o): in function 'mbedtls_sha256sum': mbedtls.c:(.text+0x4b): undefined reference to 'mbedtls_sha256_ret'
```
.

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/773#-:-NFRdjOPBWL6cDWYPMMK:bdas8lz)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @woju)



<!-- Sent from Reviewable.io -->

2022-10-28 15:41 UTC, boryspoplawski requested changes
I just tried that. I have `libmbedtls-dev:amd64 2.16.4-1ubuntu2` installed, Ubuntu 20.04. Freshly cloned repo, this PR, with patch applied:
```
diff --git a/subprojects/packagefiles/mbedtls/compile-curl.sh b/subprojects/packagefiles/mbedtls/compile-curl.sh
index 23b9c591..0d7c0803 100644
--- a/subprojects/packagefiles/mbedtls/compile-curl.sh
+++ b/subprojects/packagefiles/mbedtls/compile-curl.sh
@@ -17,7 +17,6 @@ patch -p1 --directory "$PRIVATE_DIR" <"$CURRENT_SOURCE_DIR"/gramine.patch
 patch -p1 --directory "$PRIVATE_DIR" <"$CURRENT_SOURCE_DIR"/fcntl.patch
 
 make -C "$PRIVATE_DIR" lib SUFFIX="''" install DESTDIR="$SUBPROJ_ROOT"/mbedtls-curl
-touch "$PRIVATE_DIR"/library/mbedtls-curl-dummy.h
 
 for output in $@
 do
diff --git a/subprojects/packagefiles/mbedtls/meson.build b/subprojects/packagefiles/mbedtls/meson.build
index 198953eb..7c3b9836 100644
--- a/subprojects/packagefiles/mbedtls/meson.build
+++ b/subprojects/packagefiles/mbedtls/meson.build
@@ -99,7 +99,6 @@ mbedtls_curl_libs = custom_target('mbedtls_curl',
         'libmbedcrypto.a',
         'libmbedtls.a',
         'libmbedx509.a',
-        'mbedtls-curl-dummy.h'
     ],
 
     build_by_default: true,
@@ -123,10 +122,6 @@ mbedtls_curl_dep = declare_dependency(
     # HACK: Apparently Meson considers the `mbedtls_curl_libs` to be "not linkable", because it has
     # multiple outputs; however, it allows picking the outputs one by one.
     link_with: [mbedtls_curl_libs[0], mbedtls_curl_libs[1], mbedtls_curl_libs[2]],
-    # HACK: Use the generated empty ".h" file and propagate it as part of the inter-subproject
-    # dependency to enforce compile order, i.e., to make sure `mbedtls_curl_libs` are ready before
-    # `libcurl` is compiling.
-    sources: [mbedtls_curl_libs[3]],
     include_directories: mbedtls_inc,
     compile_args: '-DMBEDTLS_CONFIG_FILE="mbedtls/config-pal.h"',
 )
```
in curl build log I have `configure: Added (...)/build/subprojects/mbedtls-curl/lib to CURL_LIBRARY_PATH`.
Everything builds and works correctly.

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/773#-:-NFUAys-2XoHeBj-5v7i:b-gn9rvc)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @woju)



<!-- Sent from Reviewable.io -->

2022-10-28 17:38 UTC, kailun-qin reviewed
Thanks a lot for the effort!

I also did some tests - on some machines I indeed have everything works w/ your patch applied (i.e., w/o the dummy header), but some may fail as I described previously.

This really depends, pls kindly have a try - if you add some delay e.g. `sleep 3` or `sleep 5` here: https://github.com/gramineproject/gramine/blob/cbb23985a1cff833bf036ec96a8f69c2423b96bd/subprojects/packagefiles/mbedtls/compile-curl.sh#L18
to simulate that in some cases when `libcurl` is built a bit later than `mbedtls_curl` is ready, you will encounter the error. But w/ the dummy header to guarantee the compile order, we are safe here.

Also, another angle to show this is that when you have NO `libmbedtls-dev` on host and pls check again the curl build log, `configure: Added (...)/build/subprojects/mbedtls-curl/lib to CURL_LIBRARY_PATH` shouldn't be found.

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/773#-:-NFUcBXt-eS7op50cfs2:b5b84af)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @woju)



<!-- Sent from Reviewable.io -->

2022-10-28 18:05 UTC, kailun-qin reviewed
> in some cases when libcurl is built a bit later than mbedtls_curl is ready

Excuse me for my typo, it should be when `libcurl` is built a bit **earlier** than `mbedtls_curl` is ready (not the contrary...)

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/773#-:-NFUkkAJ7FJ6mfLi0mBg:bv0ef8j)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @woju)



<!-- Sent from Reviewable.io -->

2022-10-28 22:38 UTC, boryspoplawski approved these changes
So, `libcurl` itself is built without errors, but linking of `tools/sgx/*` fails. I have no idea why and no time to dig deeper.

Actually, I see that `Generating subprojects/mbedtls-mbedtls-3.2.1/mbedtls_curl` is printer after `libcurl` is built, which indeed indicates the dependencies failed.

> Also, another angle to show this is that when you have NO libmbedtls-dev on host and pls check again the curl build log, configure: Added (...)/build/subprojects/mbedtls-curl/lib to CURL_LIBRARY_PATH shouldn't be found.

The correct path was always there, even when linking failed.

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/773#-:-NFVhOGd5bVSTt-kUCm-:b-onklaj)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @woju)



<!-- Sent from Reviewable.io -->

2022-10-31 08:14 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r15.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/773)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @woju)



<!-- Sent from Reviewable.io -->

2022-11-01 10:04 UTC, dimakuv submitted a review, later dismissed
> Reviewed 5 of 5 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/773)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @woju)

___
*[`-- commits` line 76 at r13](https://reviewable.io/reviews/gramineproject/gramine/773#-NBLkLVJ2iNnXZayiXjz):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

The "Co-authored-by" line should be also added, obviously. We just forgot about it.
</blockquote></details>

Done.
___
*[`CI-Examples/ra-tls-secret-prov/Makefile` line 57 at r16](https://reviewable.io/reviews/gramineproject/gramine/773#-NFmdT5ACnLtx1oEWZsc:-NFmdT5ACnLtx1oEWZsd:brhacre) ([raw file](https://github.com/gramineproject/gramine/blob/c15ca888f3e7090841e9a97b2e21be223b178026/CI-Examples/ra-tls-secret-prov/Makefile#L57)):*
> ```Makefile
> GRAMINEDIR ?= ../..
> CFLAGS += -Wall -std=c11 -I$(GRAMINEDIR)/tools/sgx/ra-tls
> LDFLAGS += -Wl,--enable-new-dtags $(shell pkg-config --libs mbedtls_gramine)
> ```

FYI: `sgx_util` doesn't exist anymore.
___
*[`subprojects/packagefiles/mbedtls/meson.build` line 124 at r15](https://reviewable.io/reviews/gramineproject/gramine/773#-NEvNMBnEYIsj43fIJDS:-NFmaJqB16u-VP1uriNx:bi5d86) ([raw file](https://github.com/gramineproject/gramine/blob/cbb23985a1cff833bf036ec96a8f69c2423b96bd/subprojects/packagefiles/mbedtls/meson.build#L124)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> # HACK: Apparently Meson considers the `mbedtls_curl_libs` to be "not linkable", because it has
> # multiple outputs; however, it allows picking the outputs one by one.
> ```

@eli-schwartz: Maybe you would know a better solution to this? (and the other hack below)
</blockquote></details>

Unfortunately, no reply from Eli. Let's hope this is the best solution that we have here.


<!-- Sent from Reviewable.io -->

2022-11-01 10:04 UTC, dimakuv commented
Jenkins, test this please

2022-11-01 15:49 UTC, boryspoplawski reviewed
> Reviewed 5 of 5 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/773)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @woju)



<!-- Sent from Reviewable.io -->

2022-11-01 15:49 UTC, boryspoplawski approved these changes
> Reviewed 1 of 5 files at r16.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/773)* status: all files reviewed, 1 unresolved discussion (waiting on @woju)



<!-- Sent from Reviewable.io -->

2022-11-01 16:12 UTC, eli-schwartz commented
Aside: has anyone taken a look at https://mesonbuild.com/External-Project-module.html

2022-11-01 16:49 UTC, kailun-qin reviewed
> perhaps: `depends: subproject('mbedtls-mbedtls-3.2.1').get_variable('mbedtls_curl_libs')`

We've tried something similar before but it didn't work, please kindly see the attempt here: https://github.com/gramineproject/gramine/pull/773#pullrequestreview-1062765122 and the discussions here: https://github.com/gramineproject/gramine/pull/773#pullrequestreview-1096815884.

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/773#-:-NFo1Py1BS08X9__hmDZ:b-33ango)* status: all files reviewed, 1 unresolved discussion (waiting on @woju)



<!-- Sent from Reviewable.io -->

2022-11-01 17:00 UTC, eli-schwartz commented
If curl is being generated via a shell script running as a custom_target then none of this should matter. The entirety of the `mbedtls_curl` overridden dependency is being exclusively used for one thing:

producing a dummy.c static library to pass as a depends kwarg to 

```meson
custom_target('curl', command: [find_program('compile.sh'), ...], ...)
```

But I really don't see why you need this. You just need to ensure that the `*.a` files are built on time, and custom_targets don't have a multi-stage runtime.

2022-11-01 18:08 UTC, mkow reviewed
> Reviewed 4 of 5 files at r16, 3 of 3 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/773)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2022-11-01 18:15 UTC, kailun-qin reviewed
Update: w/ `depends: subproject('mbedtls-mbedtls-3.2.1').get_variable('mbedtls_curl_libs')` as @eli-schwartz suggested, it looks like we can remove the other hack (to force compile order) too.

Please kindly help take another look or make/trigger another test. Thanks! 

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/773#-:-NFoOJP643X_mhsqHqrL:b-r0c6me)* status: 16 of 18 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)



<!-- Sent from Reviewable.io -->

2022-11-01 18:20 UTC, eli-schwartz commented
> This was following @woju's previous suggestion to create deps between subprojects: [#773 (review)](https://github.com/gramineproject/gramine/pull/773#pullrequestreview-1061568999).

It seems like this arose out of a dissatisfaction with `mbedtls-mbedtls-3.2.1` as the subproject name being subject to change. Any reason you cannot just... simplify the wrap filename?

2022-11-01 18:28 UTC, kailun-qin reviewed
> Any reason you cannot just... simplify the wrap filename?

It's just following the convention of other subprojects. It may not be that relevant to this PR, but I suppose @dimakuv @mkow @boryspoplawski can give more inputs here.

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/773#-:-NFoRJQ74CSofS3nOHdB:b-bh489x)* status: 16 of 18 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)



<!-- Sent from Reviewable.io -->

2022-11-01 18:37 UTC, mkow reviewed
AFAIR the reason we are adding version numbers to the subproject names was to force rebuild after a dependency was updated. Without this if you pull the repo and a subproject update happened in the meantime Meson wouldn't notice this and generate a broken build without any clear message what's the cause. So, it's a workaround for this to not confuse users.

(but I'm not sure if I remember correctly, others may know better)

> Reviewed 2 of 2 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/773#-:-NFoT8LO9ZoS7p2bYJ81:b-lu1kmu)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2022-11-01 18:48 UTC, eli-schwartz commented
I think that's only conditional on the `directory =` key/value setting inside the wrap, not the stem of the `*.wrap` file itself.

That being said, you might find https://github.com/mesonbuild/meson/commit/004575874ffdb77ee997f9c19e0a041d144994d6 interesting.

2022-11-03 10:45 UTC, dimakuv approved these changes
> It seems like this arose out of a dissatisfaction with mbedtls-mbedtls-3.2.1 as the subproject name being subject to change. Any reason you cannot just... simplify the wrap filename?

Some additional history on these version numbers: the real important part with version numbers is that there are two moving parts:
1. The version of the dependency itself (e.g. `glibc-2.35` or `mbedtls-3.2.1`).
2. The version of Gramine's patches on top of the dependency (e.g. `glibc-2.35`, `glibc-2.35-1` and `glibc-2.35-2` differ in Gramine's patch on top of Glibc code).

So we need to combine both these versions, otherwise when a user/developer jumps between Gramine commits, we could end up with as the directory name. In that case, there may have been Glibc 2.33 built with Gramine patch 1 in some old commit, and now we switch to a newer commit that uses Glibc 2.35 (also with Gramine patch 1), so the name is exactly the same, and Meson *incorrectly doesn't rebuild the sub-project*. This leads to a seemingly benign build, but then Gramine fails at runtime.

Btw, mesonbuild/meson@0045758 would definitely help to identify such issues :) But is it only a warning? Can it be set as a hard error? Otherwise in Gramine we have so many log lines, that this will be barried and noone will care to look into the log.

> I think that's only conditional on the `directory =` key/value setting inside the wrap, not the stem of the `*.wrap` file itself.

Now this is good to know! I don't think we thought about this before (that the basename of the `.wrap` file plays no role in determining whether to rebuild or not). But it makes sense.

So what this means is that we can rename all our `.wrap` subproject files to have clean & short names (`glibc`, `mbedtls`). And use these names in `meson.build` rules (e.g. `depends: subproject('mbedtls')`). I don't see any downsides to this (assuming that it actually works). @mkow @woju @boryspoplawski Should we do it, in a follow-up PR?

I like the current solution in this PR (much simpler than with that ordering hack) and I would go forward with it. What do others think?

> Reviewed 2 of 3 files at r17, 2 of 2 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/773#-:-NFx0NSCCI-8KBSIvD_H:b-f6azmr)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2022-11-03 10:46 UTC, dimakuv commented
Jenkins, test this please

2022-11-06 23:08 UTC, eli-schwartz commented
> Btw, [mesonbuild/meson@0045758](https://github.com/mesonbuild/meson/commit/0045758) would definitely help to identify such issues :) But is it only a warning? Can it be set as a hard error? Otherwise in Gramine we have so many log lines, that this will be barried and noone will care to look into the log.

Meson doesn't have a general mechanism to mark specific warnings as errors. There is `meson setup --fatal-meson-warnings`, which makes *all* warnings into hard errors.

2022-11-10 18:16 UTC, mkow reviewed
Too bad. It's always better than nothing, but a warning won't solve the problem entirely for us (hard to notice in the logs, so in practice it won't prevent people from accidentally running incorrectly built code).

Anyways, should we ship the current version then?

> So what this means is that we can rename all our `.wrap` subproject files to have clean & short names (`glibc`, `mbedtls`). And use these names in `meson.build` rules (e.g. `depends: subproject('mbedtls')`). I don't see any downsides to this (assuming that it actually works). @mkow @woju @boryspoplawski Should we do it, in a follow-up PR?

Sounds like a good idea to me.

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/773#-:-NGXjrcJBtajNfEbGgqV:b-c9u0k3)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2022-11-10 18:29 UTC, eli-schwartz commented
I had a thought at the time to make the warning available when running `ninja` as well. But I'm not sure what that would look like, precisely. Probably a build_always_stale command that gets generated whenever wrap files are in play, but I'm not sure whether people would want that penalty to be generally paid on a no-op build. It could also just run once and produce a stamp file, but then will people necessarily notice it in the ninja log? (At least ninja collapses output for build edges without warnings...)

2022-11-23 17:52 UTC, woju approved these changes
> Reviewed 1 of 4 files at r14, 4 of 5 files at r16, 3 of 3 files at r17, 2 of 2 files at r18.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/773)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2022-11-24 08:09 UTC, dimakuv approved these changes
> Reviewed 3 of 3 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/773)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2022-11-24 08:12 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/773)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2022-11-24 12:04 UTC, mkow approved these changes
> Reviewed 3 of 3 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/773)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-11-24 12:34 UTC, merged