[PAL] Diabled child processes attestation flow
gramineproject/gramine pull request #774
Opened 2022-07-21 05:57 UTC by billionairiam

Signed-off-by: Liang Ma <liang3.ma@intel.com>

## Description of the changes 
Only the initial process should be possible to attest remotely (otherwise various security properties break) - we need to disable doing this in children.

2022-07-21 07:13 UTC, dimakuv requested changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/774)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @billionairiam)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/774#-N7UaJvN9zV1aQZyPFjO:-N7UaJvOEnOdYcriquxZ:b-3zyqq3) (no related file):*
Generally looks correct.

But now I wonder -- do we really want this restriction? Imagine that we have a Bash script that becomes the first process, and all this Bash script does is to set up some envvars and then calls the real workload. E.g., this is the case for the Redis Docker image.

With this PR, Redis (which is the child enclave) won't be able to perform remote attestation. And asking Bash to perform remote attestation is ridiculous... @mkow @boryspoplawski I think this was the idea from ITL, could you comment on this?

___
___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/774#-N7UZRbW3UEUqQsLzAMB):*
I suggest: `[PAL] Disable attestation flows in child enclaves`
___
*[`Documentation/attestation.rst` line 25 at r1](https://reviewable.io/reviews/gramineproject/gramine/774#-N7UZuIIE2M3o_DKtPVj:-N7UZuIIE2M3o_DKtPVk:bhc1w8l) ([raw file](https://github.com/gramineproject/gramine/blob/03f3a92d094231fb8e1807cfbd18f86e54e0210d/Documentation/attestation.rst#L25)):*
> ```reStructuredText
> In many cases, the user also wants :term:`Secret Provisioning` to transparently
> provision secret keys and other sensitive data to the remote TEE.
> ```

I would move the added sentence to a separate paragraph and mark it as a `note`. So like this:
```
.. note::
   In Gramine, only the initial process can perform remote attestation; child processes
   have no access to remote-attestation flows.
```
___
*[`pal/src/host/linux-sgx/host_main.c` line 957 at r1](https://reviewable.io/reviews/gramineproject/gramine/774#-N7U_jUq8kzIEAKPs6A3:-N7U_jUq8kzIEAKPs6A4:b-1272mb) ([raw file](https://github.com/gramineproject/gramine/blob/03f3a92d094231fb8e1807cfbd18f86e54e0210d/pal/src/host/linux-sgx/host_main.c#L957)):*
> ```C
>     sgx_target_info_t qe_targetinfo = {0};
>     if (enclave->attestation_type != SGX_ATTESTATION_NONE && parent_stream_fd < 0) {
>         /* initialize communication with Quoting Enclave only if app requests attestation */
> ```

Please append the following in this comment: `... and this is the first process (child processes are forbidden to perform attestation)`

Don't forget to re-wrap the comment to 100-chars-per-line limit.
___
*[`pal/src/host/linux-sgx/pal_main.c` line 631 at r1](https://reviewable.io/reviews/gramineproject/gramine/774#-N7U_tCQ80T4W_NLSj2l:-N7U_tCQ80T4W_NLSj2m:b85c30z) ([raw file](https://github.com/gramineproject/gramine/blob/03f3a92d094231fb8e1807cfbd18f86e54e0210d/pal/src/host/linux-sgx/pal_main.c#L631)):*
> ```C
>     }
> 
>     enum sgx_attestation_type attestation_type=SGX_ATTESTATION_NONE;
> ```

Please add spaces around `=`
___
*[`pal/src/host/linux-sgx/pal_main.c` line 632 at r1](https://reviewable.io/reviews/gramineproject/gramine/774#-N7U_xX85BKzdeKMekaC:-N7U_xX85BKzdeKMekaD:b-sciv00) ([raw file](https://github.com/gramineproject/gramine/blob/03f3a92d094231fb8e1807cfbd18f86e54e0210d/pal/src/host/linux-sgx/pal_main.c#L632)):*
> ```C
> 
>     enum sgx_attestation_type attestation_type=SGX_ATTESTATION_NONE;
>     if(parent_stream_fd < 0){
> ```

Please add a comment before `ret = parse_attestation_type(...)`:
```
/* allow remote attestation only if this is the first process (child processes are forbidden
 * to perform remote attestation) */
```

Don't forget to re-wrap the comment to 100-chars-per-line limit.


<!-- Sent from Reviewable.io -->

2022-07-21 07:19 UTC, billionairiam commented
> > Reviewed 3 of 3 files at r1, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/774)_ status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @billionairiam)
> 
> _[a discussion](https://reviewable.io/reviews/gramineproject/gramine/774#-N7UaJvN9zV1aQZyPFjO:-N7UaJvOEnOdYcriquxZ:b-3zyqq3) (no related file):_ Generally looks correct.
> 
> But now I wonder -- do we really want this restriction? Imagine that we have a Bash script that becomes the first process, and all this Bash script does is to set up some envvars and then calls the real workload. E.g., this is the case for the Redis Docker image.
> 
> With this PR, Redis (which is the child enclave) won't be able to perform remote attestation. And asking Bash to perform remote attestation is ridiculous... @mkow @boryspoplawski I think this was the idea from ITL, could you comment on this?
> 
> _[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/774#-N7UZRbW3UEUqQsLzAMB):_ I suggest: `[PAL] Disable attestation flows in child enclaves`
> 
> _[`Documentation/attestation.rst` line 25 at r1](https://reviewable.io/reviews/gramineproject/gramine/774#-N7UZuIIE2M3o_DKtPVj:-N7UZuIIE2M3o_DKtPVk:bhc1w8l) ([raw file](https://github.com/gramineproject/gramine/blob/03f3a92d094231fb8e1807cfbd18f86e54e0210d/Documentation/attestation.rst#L25)):_
> 
> > ```
> > In many cases, the user also wants :term:`Secret Provisioning` to transparently
> > provision secret keys and other sensitive data to the remote TEE.
> > ```
> 
> I would move the added sentence to a separate paragraph and mark it as a `note`. So like this:
> 
> ```
> .. note::
>    In Gramine, only the initial process can perform remote attestation; child processes
>    have no access to remote-attestation flows.
> ```
> 
> _[`pal/src/host/linux-sgx/host_main.c` line 957 at r1](https://reviewable.io/reviews/gramineproject/gramine/774#-N7U_jUq8kzIEAKPs6A3:-N7U_jUq8kzIEAKPs6A4:b-1272mb) ([raw file](https://github.com/gramineproject/gramine/blob/03f3a92d094231fb8e1807cfbd18f86e54e0210d/pal/src/host/linux-sgx/host_main.c#L957)):_
> 
> > ```c
> >     sgx_target_info_t qe_targetinfo = {0};
> >     if (enclave->attestation_type != SGX_ATTESTATION_NONE && parent_stream_fd < 0) {
> >         /* initialize communication with Quoting Enclave only if app requests attestation */
> > ```
> 
> Please append the following in this comment: `... and this is the first process (child processes are forbidden to perform attestation)`
> 
> Don't forget to re-wrap the comment to 100-chars-per-line limit.
> 
> _[`pal/src/host/linux-sgx/pal_main.c` line 631 at r1](https://reviewable.io/reviews/gramineproject/gramine/774#-N7U_tCQ80T4W_NLSj2l:-N7U_tCQ80T4W_NLSj2m:b85c30z) ([raw file](https://github.com/gramineproject/gramine/blob/03f3a92d094231fb8e1807cfbd18f86e54e0210d/pal/src/host/linux-sgx/pal_main.c#L631)):_
> 
> > ```c
> >     }
> > 
> >     enum sgx_attestation_type attestation_type=SGX_ATTESTATION_NONE;
> > ```
> 
> Please add spaces around `=`
> 
> _[`pal/src/host/linux-sgx/pal_main.c` line 632 at r1](https://reviewable.io/reviews/gramineproject/gramine/774#-N7U_xX85BKzdeKMekaC:-N7U_xX85BKzdeKMekaD:b-sciv00) ([raw file](https://github.com/gramineproject/gramine/blob/03f3a92d094231fb8e1807cfbd18f86e54e0210d/pal/src/host/linux-sgx/pal_main.c#L632)):_
> 
> > ```c
> >     enum sgx_attestation_type attestation_type=SGX_ATTESTATION_NONE;
> >     if(parent_stream_fd < 0){
> > ```
> 
> Please add a comment before `ret = parse_attestation_type(...)`:
> 
> ```
> /* allow remote attestation only if this is the first process (child processes are forbidden
>  * to perform remote attestation) */
> ```
> 
> Don't forget to re-wrap the comment to 100-chars-per-line limit.

Well, Just now my colleagues discussed these issues carefully, they think that the current implementation is no problem, so there is no need to commit this PR. I will send you a letter to illustrate our discussion details.

2022-07-22 00:39 UTC, mkow requested changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/774)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @billionairiam, @dimakuv, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/774#-N7UaJvN9zV1aQZyPFjO:-N7WSUC_Es9XcHlsqd5A:b-vbfutw) (no related file):*
> But now I wonder -- do we really want this restriction?

It's not that we want it, we unfortunately _need_ it, or at least needed it back when I implemented https://github.com/gramineproject/graphene/pull/2050. That design was based on assumption that you won't provision secrets to the children, only to the first process and it will pass them to the children after local attestation.

I need to think a bit more what was exactly the problem and whether we've changed something since then which made this requirement obsolete, because right now I can't see what's wrong with RA on children.

> With this PR, Redis (which is the child enclave) won't be able to perform remote attestation. And asking Bash to perform remote attestation is ridiculous...

Is this actually a big problem? It's not the Bash script doing the attestation, but RA-TLS, working transparently and then the secrets get passed via env (at least in `LD_PRELOAD` mode).

___
___
*[`Documentation/attestation.rst` line 13 at r1](https://reviewable.io/reviews/gramineproject/gramine/774#-N7XrEPJDUxAfj0uIDYH:-N7XrEPJDUxAfj0uIDYI:b-xke549) ([raw file](https://github.com/gramineproject/gramine/blob/03f3a92d094231fb8e1807cfbd18f86e54e0210d/Documentation/attestation.rst#L13)):*
> ```reStructuredText
> :term:`Remote Attestation`. Local attestation is used when two TEEs run on the
> same physical machine and remote attestation is used when a user attests a TEE
> running on a remote physical machine. Only initial process in Gramine can 
> ```

trailing space
please fix in the whole PR
___
*[`pal/src/host/linux-sgx/pal_main.c` line 632 at r1](https://reviewable.io/reviews/gramineproject/gramine/774#-N7XqXF8A7kIW6u9M8e3:-N7XqXFH0U5vB2rum2Cs:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/03f3a92d094231fb8e1807cfbd18f86e54e0210d/pal/src/host/linux-sgx/pal_main.c#L632)):*
> ```C
> 
>     enum sgx_attestation_type attestation_type=SGX_ATTESTATION_NONE;
>     if(parent_stream_fd < 0){
> ```





_Suggestion:_
```C
if (parent_stream_fd < 0) {
```


<!-- Sent from Reviewable.io -->

2022-07-22 08:03 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/774)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @billionairiam, @dimakuv, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/774#-N7UaJvN9zV1aQZyPFjO:-N7ZuMdgAenegs016x2R:b2ji7dn) (no related file):*
> I need to think a bit more what was exactly the problem and whether we've changed something since then which made this requirement obsolete, because right now I can't see what's wrong with RA on children.

Yes, maybe the requirement got obsolete. Please check/think about whether we still need smth like this PR.

> It's not the Bash script doing the attestation, but RA-TLS, working transparently and then the secrets get passed via env (at least in LD_PRELOAD mode).

You're mixing different components here:
1. RA-TLS library doesn't work transparently -- it requires to modify the app (e.g. Redis) to call a special `ra_tls_create_key_and_crt_der()` function to create the SGX-augmented X.509 certificate, and also to register a callback `ra_tls_verify_callback_der()`.
2. Secret Prov library *can* work transparently but doesn't have to. For it to work transparently, the user can specify `loader.env.SECRET_PROVISION_CONSTRUCTOR = "1"` in the manifest file. Without it, the user must modify the application to call `secret_provision_start()`.

So only one out of three flows works transparently and using the `LD_PRELOAD` trick -- the SecretProv library started with `SECRET_PROVISION_CONSTRUCTOR` envvar. The other two flows require modifications to the app, and are not limited to "get secrets and pass them via env".

So for these two other flows, we **can't** simply say "Well, the first process (e.g., Bash) is augmented with transparent and automatic Secret Provisioning, you shouldn't care about establishing RA secure channels in the children".

Some refs:
- https://github.com/gramineproject/gramine/blob/master/tools/sgx/ra-tls/ra_tls.h
- https://github.com/gramineproject/gramine/blob/master/tools/sgx/ra-tls/secret_prov.h
- https://github.com/gramineproject/gramine/blob/master/CI-Examples/ra-tls-secret-prov/src/secret_prov_client.c

___


<!-- Sent from Reviewable.io -->

2022-08-31 08:10 UTC, dimakuv commented
I'm currently closing this PR as this requirement doesn't seem to be relevant anymore.

2022-08-31 08:10 UTC, closed without merging