[LibOS] Use proper const qualifiers for `argv` and `envp`
gramineproject/gramine pull request #777
Opened 2022-07-21 15:29 UTC by dimakuv

## Description of the changes 

Previously, LibOS codebase used incorrect types:
- `const char** argv`
- `const char** envp`

In reality, the types must be "arrays of constant pointers". So the correct types should be:
- `char* const* argv` (array of constant ptrs to data)
- `const char* const* envp` (array of constant ptrs to constant data)

Notice that argv items point to non-constant data: this is because argv list is modified in LibOS -- both the pointers and the strings. On the other hand, envvars are not modified so they have const qualifiers in both places.

Good references:
- https://pubs.opengroup.org/onlinepubs/9699919799/functions/exec.html -- read RATIONALE
- https://github.com/gramineproject/gramine/pull/459 -- for some initial discussions
- https://c-faq.com/ansi/constmismatch.html
- https://stackoverflow.com/a/40090931/6325371
- https://stackoverflow.com/questions/18950010/why-does-memcpy-need-a-const-void-pointer

Split from #722.

## How to test this PR? 

Compiler in our CI is enough.

2022-07-21 15:50 UTC, mkow submitted a review, later dismissed
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/777)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2022-07-21 16:20 UTC, boryspoplawski requested changes
> Reviewed 4 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/777)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @dimakuv)

___
*[`libos/include/libos_internal.h` line 20 at r1](https://reviewable.io/reviews/gramineproject/gramine/777#-N7WRZ6S6slB7cougSA7:-N7WRZ6S6slB7cougSA8:butu68l) ([raw file](https://github.com/gramineproject/gramine/blob/e89b2be603eae2b5fb69a030011364e0151edbbc/libos/include/libos_internal.h#L20)):*
> ```objc
> #include "pal_error.h"
> 
> noreturn void libos_init(int argc, char* const* argv, const char* const* envp);
> ```

Hmm, this probably could be `const char* const*` as well?
Update: ok, I see the issue in `execve_rtld`. Maybe add a cast there? `char**` -> `const char* const*` is safe to do, I believe.


<!-- Sent from Reviewable.io -->

2022-07-22 07:38 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/777)* status: 3 of 8 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[`-- commits` line 11 at r1](https://reviewable.io/reviews/gramineproject/gramine/777#-N7ZpCcB9kYIpazj-Q6I):*
Will need to modify like this:
```
  In reality, the types must be "arrays of constant pointers to constant data".
  So the correct types should be:
  - `const char* const* argv`
  - `const char* const* envp`
```
___
*[`-- commits` line 16 at r1](https://reviewable.io/reviews/gramineproject/gramine/777#-N7ZpJMl8zsj66UVxE68):*
Will need to remove this paragraph completely, since now both `argv` and `envp` are constant-constant.
___
*[`libos/include/libos_internal.h` line 20 at r1](https://reviewable.io/reviews/gramineproject/gramine/777#-N7WRZ6S6slB7cougSA7:-N7ZoG9I0MKH2IKCvdBh:b-nx3h98) ([raw file](https://github.com/gramineproject/gramine/blob/e89b2be603eae2b5fb69a030011364e0151edbbc/libos/include/libos_internal.h#L20)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Hmm, this probably could be `const char* const*` as well?
Update: ok, I see the issue in `execve_rtld`. Maybe add a cast there? `char**` -> `const char* const*` is safe to do, I believe.
</blockquote></details>

Done. Indeed, that's what I wanted to do first, but then turned out we have an type-incompatible caller -- `execve_rtld()`.

But I agree, since we don't have any other pointers into the `argv` array, it is actually safe to pass `char** argv` as `const char* const*`. So I added an explicit typecast as you requested.


<!-- Sent from Reviewable.io -->

2022-07-22 12:43 UTC, mkow requested changes
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/777)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[`libos/src/sys/libos_exec.c` line 127 at r2](https://reviewable.io/reviews/gramineproject/gramine/777#-N7_vbcC98nL9biAJLIf:-N7_vbcD38pbkmnNiycA:b-tpzgef) ([raw file](https://github.com/gramineproject/gramine/blob/bfaecf8480508f650337f590523c06b045a943fe/libos/src/sys/libos_exec.c#L127)):*
> ```C
> 
>     /* note the typecast of argv here: the C standard disallows implicit conversion of `char**` ->
>      * `const char* const*`, but in our case it is safe to do */
> ```

But it's safe in all cases, not only in ours?



_Code quote:_
```C
but in our case it is safe to do
```


<!-- Sent from Reviewable.io -->

2022-07-22 18:38 UTC, boryspoplawski requested changes
> Reviewed 1 of 8 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/777)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`libos/src/sys/libos_exec.c` line 127 at r2](https://reviewable.io/reviews/gramineproject/gramine/777#-N7_vbcC98nL9biAJLIf:-N7bBcsd75pOcLiiMBE9:b2nhtan) ([raw file](https://github.com/gramineproject/gramine/blob/bfaecf8480508f650337f590523c06b045a943fe/libos/src/sys/libos_exec.c#L127)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

But it's safe in all cases, not only in ours?
</blockquote></details>

Yup


<!-- Sent from Reviewable.io -->

2022-07-25 06:56 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/777)* status: 7 of 8 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[`libos/src/sys/libos_exec.c` line 127 at r2](https://reviewable.io/reviews/gramineproject/gramine/777#-N7_vbcC98nL9biAJLIf:-N7o79Mc-B5KgpHSG9FE:bhkyd5b) ([raw file](https://github.com/gramineproject/gramine/blob/bfaecf8480508f650337f590523c06b045a943fe/libos/src/sys/libos_exec.c#L127)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Yup
</blockquote></details>

Ok, looking a bit more at https://c-faq.com/ansi/constmismatch.html, I understand the situation as follows:
1. Casting `char**` to `const char**` is dangereous and correctly prohibited by the C standard (see the link for an example)
2. Casting `char**` to `const char* const*` is safe, but due to "weak rules" in the C standard, the compiler simply looks at the first level of constness (interestingly, this cast is allowed in C++)

So we have a situation 2 here -- we need to typecast but it is indeed always safe to do so.


<!-- Sent from Reviewable.io -->

2022-07-25 10:47 UTC, boryspoplawski approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/777)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)



<!-- Sent from Reviewable.io -->

2022-07-25 13:11 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/777)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2022-07-25 17:48 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/777)* status: 7 of 8 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski and @mkow)

___
*[`-- commits` line 11 at r1](https://reviewable.io/reviews/gramineproject/gramine/777#-N7ZpCcB9kYIpazj-Q6I):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Will need to modify like this:
```
  In reality, the types must be "arrays of constant pointers to constant data".
  So the correct types should be:
  - `const char* const* argv`
  - `const char* const* envp`
```
</blockquote></details>

Done
___
*[`-- commits` line 16 at r1](https://reviewable.io/reviews/gramineproject/gramine/777#-N7ZpJMl8zsj66UVxE68):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Will need to remove this paragraph completely, since now both `argv` and `envp` are constant-constant.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2022-07-25 18:10 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/777)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2022-07-25 18:20 UTC, boryspoplawski approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/777)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-07-25 20:55 UTC, merged