[LibOS] Remove `migrated_envp`
gramineproject/gramine pull request #781
Opened 2022-07-22 09:43 UTC by dimakuv

## Description of the changes 

This variable is wrong and shouldn't be used.

But also see https://github.com/gramineproject/graphene/issues/2081 and the TODOs in this PR.

## How to test this PR? 

CI is enough. I modified `sigprocmask_pending` LibOS regression test, otherwise (if `envp = {NULL}`) it failed with:
```
sigprocmask_pending: error while loading shared libraries: libpthread.so.0: cannot open shared object file: No such file or directory
```

2022-07-22 09:45 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/781)* status: 0 of 4 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[`libos/src/sys/libos_exec.c` line 141 at r1](https://reviewable.io/reviews/gramineproject/gramine/781#-N7_Hhz0Albm0mJf99zZ:-N7_Hhz0Albm0mJf99z_:bbh51gf) ([raw file](https://github.com/gramineproject/gramine/blob/0fe57f145d04d3a155819c7c67b83c565ae5fd61/libos/src/sys/libos_exec.c#L141)):*
> ```C
> /*
>  * TODO: Linux treats argv == NULL and envp == NULL as `argv = {NULL}` and `envp = {NULL}`.
>  *       Gramine currently doesn't implement this corner case.
> ```

FYI: I didn't want to introduce a fix for this in this PR. Though the fix should be rather trivial.

I wonder if any real-world app relies on this non-standard behavior...
___
*[`libos/src/sys/libos_exec.c` line 165 at r1](https://reviewable.io/reviews/gramineproject/gramine/781#-N7_Hrez592iE4cuy6JX:-N7_Hrez592iE4cuy6JY:b4kmrf0) ([raw file](https://github.com/gramineproject/gramine/blob/0fe57f145d04d3a155819c7c67b83c565ae5fd61/libos/src/sys/libos_exec.c#L165)):*
> ```C
>      *
>      *       See https://github.com/gramineproject/graphene/issues/2081 for details.
>      */
> ```

FYI: I honestly don't think we can/should do any better than this... If the user removes `LD_LIBRARY_PATH` from the envvars, then the user is on her own... Re-adding `LD_LIBRARY_PATH` sounds totally wrong.


<!-- Sent from Reviewable.io -->

2022-07-22 09:46 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/781)* status: 0 of 4 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[`libos/src/sys/libos_exec.c` line 165 at r1](https://reviewable.io/reviews/gramineproject/gramine/781#-N7_Hrez592iE4cuy6JX:-N7_IBLo8yEYwVzKVQfZ:b-c7hl06) ([raw file](https://github.com/gramineproject/gramine/blob/0fe57f145d04d3a155819c7c67b83c565ae5fd61/libos/src/sys/libos_exec.c#L165)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

FYI: I honestly don't think we can/should do any better than this... If the user removes `LD_LIBRARY_PATH` from the envvars, then the user is on her own... Re-adding `LD_LIBRARY_PATH` sounds totally wrong.
</blockquote></details>

What about apps which uses `clearenv(3)`?


<!-- Sent from Reviewable.io -->

2022-07-22 11:34 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/781)* status: 0 of 4 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[`libos/src/sys/libos_exec.c` line 165 at r1](https://reviewable.io/reviews/gramineproject/gramine/781#-N7_Hrez592iE4cuy6JX:-N7_frMQ5nwi-WrMeTvU:b51votk) ([raw file](https://github.com/gramineproject/gramine/blob/0fe57f145d04d3a155819c7c67b83c565ae5fd61/libos/src/sys/libos_exec.c#L165)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

What about apps which uses `clearenv(3)`?
</blockquote></details>

@oshogbo Do any apps actually do it? I guess some do... Yeah, maybe this "your-app-is-stupid" fix is wrong. How should we fix it then?


<!-- Sent from Reviewable.io -->

2022-07-22 13:04 UTC, mkow requested changes
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/781)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv and @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/781#-N7_z8-U9z6umz5DzWdH:-N7_z8-U9z6umz5DzWdI:b-ue7c6h) (no related file):*
Any volunteer to finally fix gramineproject/graphene#2081 ? Should be rather simple :)

___
___
*[`libos/src/sys/libos_exec.c` line 141 at r1](https://reviewable.io/reviews/gramineproject/gramine/781#-N7_Hhz0Albm0mJf99zZ:-N7_zUWH7GR_U7YYBQ46:b-93lqum) ([raw file](https://github.com/gramineproject/gramine/blob/0fe57f145d04d3a155819c7c67b83c565ae5fd61/libos/src/sys/libos_exec.c#L141)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

FYI: I didn't want to introduce a fix for this in this PR. Though the fix should be rather trivial.

I wonder if any real-world app relies on this non-standard behavior...
</blockquote></details>

Could you create an issue for this? Seems easy to fix, so it will be good for new developers to pick up.
___
*[`libos/src/sys/libos_exec.c` line 165 at r1](https://reviewable.io/reviews/gramineproject/gramine/781#-N7_Hrez592iE4cuy6JX:-N7_zo6IAOiyGfEUfxmL:b62e433) ([raw file](https://github.com/gramineproject/gramine/blob/0fe57f145d04d3a155819c7c67b83c565ae5fd61/libos/src/sys/libos_exec.c#L165)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@oshogbo Do any apps actually do it? I guess some do... Yeah, maybe this "your-app-is-stupid" fix is wrong. How should we fix it then?
</blockquote></details>

But why not just implement the `execve` logic identically to Linux? (i.e. to fall back to some hardcoded dirs when it's missing)
___
*[`libos/test/regression/sigprocmask_pending.c` line 149 at r1](https://reviewable.io/reviews/gramineproject/gramine/781#-N7_yeCcDGDi5IPEtA1t:-N7_yeCd0zhAYy0vrJ3y:b-tzoosi) ([raw file](https://github.com/gramineproject/gramine/blob/0fe57f145d04d3a155819c7c67b83c565ae5fd61/libos/test/regression/sigprocmask_pending.c#L149)):*
> ```C
>     char ld_library_path_envvar[512];
>     strcpy(ld_library_path_envvar, "LD_LIBRARY_PATH=");
>     strcat(ld_library_path_envvar, ld_library_path_value);
> ```

I don't like this, I know it's just a test, but `ld_library_path_value` is externally controlled and may corrupt memory on some configurations.


<!-- Sent from Reviewable.io -->

2022-07-22 19:16 UTC, boryspoplawski requested changes
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/781)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv and @mkow)

___
*[`libos/src/sys/libos_exec.c` line 165 at r1](https://reviewable.io/reviews/gramineproject/gramine/781#-N7_Hrez592iE4cuy6JX:-N7bGxQDETNDlBhKvhyn:b8k7pbr) ([raw file](https://github.com/gramineproject/gramine/blob/0fe57f145d04d3a155819c7c67b83c565ae5fd61/libos/src/sys/libos_exec.c#L165)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

But why not just implement the `execve` logic identically to Linux? (i.e. to fall back to some hardcoded dirs when it's missing)
</blockquote></details>

I think you got the problem wrong. There is no logic in `execve` that is related to this env var. It's just `ld.so` that has some defaults. 
There are three (potential) problems:
1) (I believe we've fixed this already) mounting our patched libc at some path that is default in `ld.so` - we do it in `/lib` so I guess it's already ok. Update: well, see the point 3, it's not ok.
2) Clash of libcs. There could be host glibc mounted at different path - we must make sure that our glibc is prioritized.
3) Wrong paths. When we build glibc and ld.so, we forward libdir and prefix from meson. These paths are then hardcoded as defaults in `ld.so` search algorithm - in most testing cases (like CI) these are some custom paths like `/home/user/gramine/install` and are not re-created in Gramine virtual FS, so `ld.so` is not able to find the glibc. 
___
*[`libos/test/regression/sigprocmask_pending.c` line 149 at r1](https://reviewable.io/reviews/gramineproject/gramine/781#-N7_yeCcDGDi5IPEtA1t:-N7bKA3ADc68UwNHnR2P:bwofjmm) ([raw file](https://github.com/gramineproject/gramine/blob/0fe57f145d04d3a155819c7c67b83c565ae5fd61/libos/test/regression/sigprocmask_pending.c#L149)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I don't like this, I know it's just a test, but `ld_library_path_value` is externally controlled and may corrupt memory on some configurations.
</blockquote></details>

+1, just use `strdup`. Or even better: `execve` -> `execv`. This test doesn't depend on passing empty env. We should add such test once we fix other issues.


<!-- Sent from Reviewable.io -->

2022-07-22 19:17 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/781)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/781#-N7bKpr6DkKqq49MhGwY:-N7bKpr6DkKqq49MhGwZ:b4insgv) (no related file):*
All non sgx pipelines failed

___


<!-- Sent from Reviewable.io -->

2022-07-22 21:50 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/781)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`libos/src/sys/libos_exec.c` line 165 at r1](https://reviewable.io/reviews/gramineproject/gramine/781#-N7_Hrez592iE4cuy6JX:-N7bsMh4-I56_44OpnvI:b6r09hl) ([raw file](https://github.com/gramineproject/gramine/blob/0fe57f145d04d3a155819c7c67b83c565ae5fd61/libos/src/sys/libos_exec.c#L165)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I think you got the problem wrong. There is no logic in `execve` that is related to this env var. It's just `ld.so` that has some defaults. 
There are three (potential) problems:
1) (I believe we've fixed this already) mounting our patched libc at some path that is default in `ld.so` - we do it in `/lib` so I guess it's already ok. Update: well, see the point 3, it's not ok.
2) Clash of libcs. There could be host glibc mounted at different path - we must make sure that our glibc is prioritized.
3) Wrong paths. When we build glibc and ld.so, we forward libdir and prefix from meson. These paths are then hardcoded as defaults in `ld.so` search algorithm - in most testing cases (like CI) these are some custom paths like `/home/user/gramine/install` and are not re-created in Gramine virtual FS, so `ld.so` is not able to find the glibc. 
</blockquote></details>

Ok, seems I was fooled by [this comment](https://github.com/gramineproject/graphene/issues/2081#issuecomment-759981673) saying that Linux does this :P

3\. sounds quite bad, and I'm not sure how to fix it...


<!-- Sent from Reviewable.io -->

2022-07-22 21:54 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/781)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`libos/src/sys/libos_exec.c` line 165 at r1](https://reviewable.io/reviews/gramineproject/gramine/781#-N7_Hrez592iE4cuy6JX:-N7btjhB01fAOaXWXYnq:bypkizn) ([raw file](https://github.com/gramineproject/gramine/blob/0fe57f145d04d3a155819c7c67b83c565ae5fd61/libos/src/sys/libos_exec.c#L165)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Ok, seems I was fooled by [this comment](https://github.com/gramineproject/graphene/issues/2081#issuecomment-759981673) saying that Linux does this :P

3\. sounds quite bad, and I'm not sure how to fix it...
</blockquote></details>

We should stop using meson configured prefix and use our own hardcoded one (basically change prefix of these paths).


<!-- Sent from Reviewable.io -->

2022-07-26 10:10 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/781)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`libos/src/sys/libos_exec.c` line 165 at r1](https://reviewable.io/reviews/gramineproject/gramine/781#-N7_Hrez592iE4cuy6JX:-N7tyQKNCd-URTEMuc2j:boqzjqa) ([raw file](https://github.com/gramineproject/gramine/blob/0fe57f145d04d3a155819c7c67b83c565ae5fd61/libos/src/sys/libos_exec.c#L165)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

We should stop using meson configured prefix and use our own hardcoded one (basically change prefix of these paths).
</blockquote></details>

@boryspoplawski Where did you get this information about point 3? I don't see any hard-coded paths in our `ld.so` (I did `strings` on it on my `gramine/build-debug/blabla` directory, so I would expect to see this hard-coded path).

Looking at these:
- https://unix.stackexchange.com/a/367682
- https://man7.org/linux/man-pages/man8/ld.so.8.html

And observing what I have on my local Ubuntu 20.04, I can see that the actual problematic paths are under `/etc/ld.so.conf`. That's what I have:
```
$ cat /etc/ld.so.conf
include /etc/ld.so.conf.d/*.conf

$ cat /etc/ld.so.conf.d/*.conf
/usr/lib/x86_64-linux-gnu/libfakeroot
# libc default configuration
/usr/local/lib
# Multiarch support
/usr/local/lib/x86_64-linux-gnu
/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu
# Legacy biarch compatibility support
/lib32
/usr/lib32
# Legacy biarch compatibility support
/libx32
/usr/libx32
```

But in Gramine, we typically do not allow these `/etc/*.conf` files. So we can't really recreate the `ld`'s logic of "I will search for libs in these dirs"...


<!-- Sent from Reviewable.io -->

2022-07-26 13:33 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/781)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski, @dimakuv, and @oshogbo)

___
*[`libos/src/sys/libos_exec.c` line 165 at r1](https://reviewable.io/reviews/gramineproject/gramine/781#-N7_Hrez592iE4cuy6JX:-N7uhPCNELcMBQIEAfHU:bw4g9lk) ([raw file](https://github.com/gramineproject/gramine/blob/0fe57f145d04d3a155819c7c67b83c565ae5fd61/libos/src/sys/libos_exec.c#L165)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

What was `--prefix` to meson when you build it? If it was default then you wouldn't see it - that what happens when you install Gramine systemwide.

Steps to reproduce:
1. Configure meson with custom installation prefix
2. Build Gramine
3. Build regression tests and their manifests
4. Remove `LD_LIBRARY_PATH` from `bootstrap.manifest`, add `all` log level
5. Observe the paths where the program looks for `libc.so` and fails to find it.
</blockquote></details>

I build with a local-dir prefix (`build-debug/`). But I think you're talking about a different point...

My point is -- if we want to emulate the exact host behavior, then we need to do something about `/etc/*.conf` files.


<!-- Sent from Reviewable.io -->

2022-07-26 13:38 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/781)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski, @dimakuv, @mkow, and @oshogbo)

___
*[`libos/src/sys/libos_exec.c` line 141 at r1](https://reviewable.io/reviews/gramineproject/gramine/781#-N7_Hhz0Albm0mJf99zZ:-N7uigkTBjzUgVIra5Uk:b-sowhtb) ([raw file](https://github.com/gramineproject/gramine/blob/0fe57f145d04d3a155819c7c67b83c565ae5fd61/libos/src/sys/libos_exec.c#L141)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you create an issue for this? Seems easy to fix, so it will be good for new developers to pick up.
</blockquote></details>

Done https://github.com/gramineproject/gramine/issues/794


<!-- Sent from Reviewable.io -->

2022-07-26 14:30 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/781)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv and @mkow)

___
*[`libos/src/sys/libos_exec.c` line 165 at r1](https://reviewable.io/reviews/gramineproject/gramine/781#-N7_Hrez592iE4cuy6JX:-N7uuPJe3sLzeNIQHwz0:b-uxlxqe) ([raw file](https://github.com/gramineproject/gramine/blob/0fe57f145d04d3a155819c7c67b83c565ae5fd61/libos/src/sys/libos_exec.c#L165)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I build with a local-dir prefix (`build-debug/`). But I think you're talking about a different point...

My point is -- if we want to emulate the exact host behavior, then we need to do something about `/etc/*.conf` files.
</blockquote></details>

We don't, they are just extensions. The problem is if you mount them from host (e.g. mount whole `/etc`) - you should not do that.


<!-- Sent from Reviewable.io -->

2022-10-19 09:34 UTC, dimakuv commented
This PR went nowhere. I'll close it for now since it has very low priority.

2022-10-19 09:34 UTC, closed without merging