[tools/sgx] Fix `pf_crypt` to run within an enclave
gramineproject/gramine pull request #787
Opened 2022-07-26 00:38 UTC by vijaydhanraj

## Description of the changes 
The current implementation of the `pf_crypt` uses `fstat` to find the wrap_key length. But `fstat` implementation in Gramine sgx doesn't support reporting the size field. So, use `lseek` to determine the length of the file when running within the enclave.

## How to test this PR? 
Please run LibOS, PAL, fs regression tests. Also, please try encrypting and decrpting using `gramine-sgx-pf-crypt`  tool.

2022-07-26 06:43 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/787)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @vijaydhanraj)

___
*[`-- commits` line 6 at r1](https://reviewable.io/reviews/gramineproject/gramine/787#-N7tChPo2lBzDIa4Fy3f):*
`Gramine sgx` -> `Gramine` (it is not specific to SGX)
___
*[`-- commits` line 6 at r1](https://reviewable.io/reviews/gramineproject/gramine/787#-N7tCopX7BONSLEMDWxG):*
`...doesn't support reporting the size field` -> `...doesn't report the size field for /dev pseudo-files` 
___
*[`tools/sgx/common/util.c` line 57 at r1](https://reviewable.io/reviews/gramineproject/gramine/787#-N7tDMQP-JeIeyf7sLhg:-N7tDMQP-JeIeyf7sLhh:bc1ej7u) ([raw file](https://github.com/gramineproject/gramine/blob/673020ce23c661f3d4cd6d9d3b2f19a8035a5079/tools/sgx/common/util.c#L57)):*
> ```C
> 
> /* return -1 on error */
>  uint64_t get_file_size(int fd) {
> ```

Now we can change to `ssize_t` and remove the weird `(uint64_t)-1` conversion. Also please modify the callers of this function to correctly verify the return value.
___
*[`tools/sgx/common/util.c` line 62 at r1](https://reviewable.io/reviews/gramineproject/gramine/787#-N7tDWDv6b4R0bXKcdMc:-N7tDWDv6b4R0bXKcdMd:b-u3yuao) ([raw file](https://github.com/gramineproject/gramine/blob/673020ce23c661f3d4cd6d9d3b2f19a8035a5079/tools/sgx/common/util.c#L62)):*
> ```C
>         return (uint64_t)-1;
> 
>     off_t reset_pos = lseek(fd, 0L, SEEK_SET);
> ```

This is wrong. You're overriding the offset of the file that was before this function. What if the file was opened and pointed somewhere in the middle of the file contents, and then this function is called? After the call, the file offset will be `0`. So this func will have weird side effects.

You should do something like this:
```
cur_pos = lseek(fd, 0L, SEEK_CUR);
pos = lseek(fd, 0L, SEEK_END);
reset_pos = lseek(fd, cur_pos, SEEK_SET);
```


<!-- Sent from Reviewable.io -->

2022-07-26 14:55 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/787)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

___
*[`-- commits` line 6 at r1](https://reviewable.io/reviews/gramineproject/gramine/787#-N7tChPo2lBzDIa4Fy3f):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`Gramine sgx` -> `Gramine` (it is not specific to SGX)
</blockquote></details>

Yes, you are right, blocking myself and will fix this during the final rebase.
___
*[`-- commits` line 6 at r1](https://reviewable.io/reviews/gramineproject/gramine/787#-N7tCopX7BONSLEMDWxG):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`...doesn't support reporting the size field` -> `...doesn't report the size field for /dev pseudo-files` 
</blockquote></details>

Blocking myself, will fix during final rebase.
___
*[`tools/sgx/common/util.c` line 57 at r1](https://reviewable.io/reviews/gramineproject/gramine/787#-N7tDMQP-JeIeyf7sLhg:-N7uv6JTALa2-c2Xc2S_:b-83g3zx) ([raw file](https://github.com/gramineproject/gramine/blob/673020ce23c661f3d4cd6d9d3b2f19a8035a5079/tools/sgx/common/util.c#L57)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Now we can change to `ssize_t` and remove the weird `(uint64_t)-1` conversion. Also please modify the callers of this function to correctly verify the return value.
</blockquote></details>

I think using `ssize_t` will be a little tricky esp. here, as it can be a `UB`.
https://github.com/gramineproject/gramine/blob/master/tools/sgx/common/util.c#L83
https://github.com/gramineproject/gramine/blob/master/tools/sgx/common/util.c#L89

Also, since this is size, the callers assume it is unsigned and so we may need to typecast at the caller sites. So prefer we return `size_t` instead of `ssize_t` this way all casting is contained within the function.
___
*[`tools/sgx/common/util.c` line 62 at r1](https://reviewable.io/reviews/gramineproject/gramine/787#-N7tDWDv6b4R0bXKcdMc:-N7uwuXGBqQ4nNNbxJmQ:bpdbugr) ([raw file](https://github.com/gramineproject/gramine/blob/673020ce23c661f3d4cd6d9d3b2f19a8035a5079/tools/sgx/common/util.c#L62)):*
> What if the file was opened and pointed somewhere in the middle of the file contents, and then this function is called? 

Do we have this situation here?

I might be wrong, but it looks like each call site opens, gets the file size, and closes the `fd` and felt this was not needed. But open to adding the `cur_pos` check.


<!-- Sent from Reviewable.io -->

2022-07-26 15:31 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/787)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @vijaydhanraj)

___
*[`tools/sgx/common/util.c` line 57 at r1](https://reviewable.io/reviews/gramineproject/gramine/787#-N7tDMQP-JeIeyf7sLhg:-N7v7Gx0ApeMl1LPMrSg:b-dw944t) ([raw file](https://github.com/gramineproject/gramine/blob/673020ce23c661f3d4cd6d9d3b2f19a8035a5079/tools/sgx/common/util.c#L57)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

I think using `ssize_t` will be a little tricky esp. here, as it can be a `UB`.
https://github.com/gramineproject/gramine/blob/master/tools/sgx/common/util.c#L83
https://github.com/gramineproject/gramine/blob/master/tools/sgx/common/util.c#L89

Also, since this is size, the callers assume it is unsigned and so we may need to typecast at the caller sites. So prefer we return `size_t` instead of `ssize_t` this way all casting is contained within the function.



</blockquote></details>

This is weird but used in this file everywhere, so whatever, I'm unblocking. Let's keep as is for now.
___
*[`tools/sgx/common/util.c` line 62 at r1](https://reviewable.io/reviews/gramineproject/gramine/787#-N7tDWDv6b4R0bXKcdMc:-N7v7Pw87W61e_f6Yw_8:bixh5dq) ([raw file](https://github.com/gramineproject/gramine/blob/673020ce23c661f3d4cd6d9d3b2f19a8035a5079/tools/sgx/common/util.c#L62)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

> What if the file was opened and pointed somewhere in the middle of the file contents, and then this function is called? 

Do we have this situation here?

I might be wrong, but it looks like each call site opens, gets the file size, and closes the `fd` and felt this was not needed. But open to adding the `cur_pos` check.
</blockquote></details>

But you're introducing an implicit assumption. Just change this function to be more generic.


<!-- Sent from Reviewable.io -->

2022-07-26 16:50 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/787)* status: 0 of 1 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`tools/sgx/common/util.c` line 62 at r1](https://reviewable.io/reviews/gramineproject/gramine/787#-N7tDWDv6b4R0bXKcdMc:-N7vEDsO2iP367DhnX5E:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/673020ce23c661f3d4cd6d9d3b2f19a8035a5079/tools/sgx/common/util.c#L62)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

But you're introducing an implicit assumption. Just change this function to be more generic.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-26 18:11 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/787)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2022-07-26 18:12 UTC, dimakuv commented
Jenkins, test this please

2022-07-26 19:31 UTC, boryspoplawski requested changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/787)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @vijaydhanraj)

___
*[`-- commits` line 6 at r1](https://reviewable.io/reviews/gramineproject/gramine/787#-N7tCopX7BONSLEMDWxG):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Blocking myself, will fix during final rebase.
</blockquote></details>

`/dev` -> `"/dev"`
___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/gramineproject/gramine/787#-N7vyZyS17FkcsQzi7iz):*




_Suggestion:_
```
to be runnable
```
___
*[`-- commits` line 5 at r2](https://reviewable.io/reviews/gramineproject/gramine/787#-N7vyk6i4z7zaM-ycLHd):*




_Suggestion:_
```
`wrap_key`
```
___
*[`tools/sgx/common/util.c` line 58 at r2](https://reviewable.io/reviews/gramineproject/gramine/787#-N7vz7i16PnhT7BWAM9i:-N7vz7i16PnhT7BWAM9j:b8w9pn3) ([raw file](https://github.com/gramineproject/gramine/blob/99b1327cfae360a924a28e7c03454788689e925a/tools/sgx/common/util.c#L58)):*
> ```C
> 
> /* return -1 on error */
>  uint64_t get_file_size(int fd) {
> ```

You added a single space at the beginning of this line...


<!-- Sent from Reviewable.io -->

2022-07-26 20:21 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/787)* status: 0 of 1 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski and @dimakuv)

___
*[`-- commits` line 6 at r1](https://reviewable.io/reviews/gramineproject/gramine/787#-N7tChPo2lBzDIa4Fy3f):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Yes, you are right, blocking myself and will fix this during the final rebase.
</blockquote></details>

Done. 
Please note, I merged the fixups and did a force push.
___
*[`-- commits` line 6 at r1](https://reviewable.io/reviews/gramineproject/gramine/787#-N7tCopX7BONSLEMDWxG):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`/dev` -> `"/dev"`
</blockquote></details>

Done.
___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/gramineproject/gramine/787#-N7vyZyS17FkcsQzi7iz):*
Done.
___
*[`-- commits` line 5 at r2](https://reviewable.io/reviews/gramineproject/gramine/787#-N7vyk6i4z7zaM-ycLHd):*
Done.
___
*[`tools/sgx/common/util.c` line 58 at r2](https://reviewable.io/reviews/gramineproject/gramine/787#-N7vz7i16PnhT7BWAM9i:-N7w9LceEk_dCpkhtLO3:bxsqqq) ([raw file](https://github.com/gramineproject/gramine/blob/99b1327cfae360a924a28e7c03454788689e925a/tools/sgx/common/util.c#L58)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

You added a single space at the beginning of this line...
</blockquote></details>

ah, good catch. Done.


<!-- Sent from Reviewable.io -->

2022-07-26 20:25 UTC, boryspoplawski submitted a review, later dismissed
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/787)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2022-07-27 07:38 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/787)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2022-07-27 07:41 UTC, dimakuv commented
Jenkins, test this please

2022-07-28 14:56 UTC, mkow requested changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/787)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required) (waiting on @vijaydhanraj)

___
*[`-- commits` line 7 at r3](https://reviewable.io/reviews/gramineproject/gramine/787#-N84Ez0Z2lLndzP9D7C-):*
> So, use `lseek` to determine the length of the file when running within the enclave.

This is misleading, this PR makes the tool always use `lseek`, not only inside the enclave.
___
*[`tools/sgx/common/util.c` line 69 at r3](https://reviewable.io/reviews/gramineproject/gramine/787#-N84IcF91W4KhJ4-tYC-:-N84IcF91W4KhJ4-tYC0:blnsyjb) ([raw file](https://github.com/gramineproject/gramine/blob/7feba673670b4b8575ee69bcadec6d34c057044b/tools/sgx/common/util.c#L69)):*
> ```C
>     off_t reset_pos = lseek(fd, cur_pos, SEEK_SET);
>     if (reset_pos < 0)
>          return (uint64_t)-1;
> ```

accidental indentation?
___
*[`tools/sgx/common/util.c` line 72 at r3](https://reviewable.io/reviews/gramineproject/gramine/787#-N84IYHR-r_1Xrh35sdM:-N84IYHR-r_1Xrh35sdN:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/7feba673670b4b8575ee69bcadec6d34c057044b/tools/sgx/common/util.c#L72)):*
> ```C
> 
>    return (uint64_t)pos;
>  }
> ```

ditto


<!-- Sent from Reviewable.io -->

2022-07-28 15:52 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/787)* status: 0 of 1 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[`-- commits` line 7 at r3](https://reviewable.io/reviews/gramineproject/gramine/787#-N84Ez0Z2lLndzP9D7C-):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> So, use `lseek` to determine the length of the file when running within the enclave.

This is misleading, this PR makes the tool always use `lseek`, not only inside the enclave.
</blockquote></details>

I see your point. How about we do this change?
`So, use lseek to determine the length of the file when running within the enclave.` -> `So this commit replaces the use of fstat with lseek to determine the length of the file when running in Gramine`
___
*[`tools/sgx/common/util.c` line 69 at r3](https://reviewable.io/reviews/gramineproject/gramine/787#-N84IcF91W4KhJ4-tYC-:-N84UHLAAhV29UgUy_qO:b-z8i6ic) ([raw file](https://github.com/gramineproject/gramine/blob/7feba673670b4b8575ee69bcadec6d34c057044b/tools/sgx/common/util.c#L69)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

accidental indentation?
</blockquote></details>

ah, done.
___
*[`tools/sgx/common/util.c` line 72 at r3](https://reviewable.io/reviews/gramineproject/gramine/787#-N84IYHR-r_1Xrh35sdM:-N84UO0O99MS8tOLD-Xb:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/7feba673670b4b8575ee69bcadec6d34c057044b/tools/sgx/common/util.c#L72)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-29 06:48 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/787)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`-- commits` line 7 at r3](https://reviewable.io/reviews/gramineproject/gramine/787#-N84Ez0Z2lLndzP9D7C-):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

I see your point. How about we do this change?
`So, use lseek to determine the length of the file when running within the enclave.` -> `So this commit replaces the use of fstat with lseek to determine the length of the file when running in Gramine`
</blockquote></details>

`when running in Gramine` -> `to make it run in Gramine`.
___
*[`tools/sgx/common/util.c` line 69 at r3](https://reviewable.io/reviews/gramineproject/gramine/787#-N84IcF91W4KhJ4-tYC-:-N87hcM-2EJSqbDlBTRJ:bs74h4z) ([raw file](https://github.com/gramineproject/gramine/blob/7feba673670b4b8575ee69bcadec6d34c057044b/tools/sgx/common/util.c#L69)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

ah, done.
</blockquote></details>

I still don't understand how Michal can notice such things :)


<!-- Sent from Reviewable.io -->

2022-07-29 06:48 UTC, dimakuv commented
Jenkins, test this please

2022-07-29 09:36 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/787)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`-- commits` line 7 at r3](https://reviewable.io/reviews/gramineproject/gramine/787#-N84Ez0Z2lLndzP9D7C-):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`when running in Gramine` -> `to make it run in Gramine`.
</blockquote></details>

Sounds ok if you also apply Dmitrii's fix.
___
*[`tools/sgx/common/util.c` line 69 at r3](https://reviewable.io/reviews/gramineproject/gramine/787#-N84IcF91W4KhJ4-tYC-:-N88INh-1_tadMAAWvVi:be304j3) ([raw file](https://github.com/gramineproject/gramine/blob/7feba673670b4b8575ee69bcadec6d34c057044b/tools/sgx/common/util.c#L69)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I still don't understand how Michal can notice such things :)
</blockquote></details>

![ocd](https://i.redd.it/6bune18k9hs11.jpg)


<!-- Sent from Reviewable.io -->

2022-07-29 20:37 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/787)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @mkow)

___
*[`-- commits` line 7 at r3](https://reviewable.io/reviews/gramineproject/gramine/787#-N84Ez0Z2lLndzP9D7C-):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Sounds ok if you also apply Dmitrii's fix.
</blockquote></details>

Done. 
Also, merged the fixups and rebased to the latest master.


<!-- Sent from Reviewable.io -->

2022-08-01 06:41 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/787)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2022-08-01 06:42 UTC, dimakuv commented
Jenkins, test this please

2022-08-01 09:37 UTC, boryspoplawski approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/787)* status: all files reviewed, 1 unresolved discussion (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2022-08-01 12:10 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/787)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-08-01 12:33 UTC, merged