[LibOS] Support more CPU feature flags in `/proc/cpuinfo`
gramineproject/gramine pull request #789
Opened 2022-07-26 03:26 UTC by kailun-qin

Some workloads may depend on the specific CPU feature flags in the `flags` line of the pseudo-file `/proc/cpuinfo` (e.g.,
intel-extension-for-pytorch looks for the `avx2` flag). However, currently Gramine only supports a subset of them (e.g., `avx2` is not included).

This patch extends support for more CPU feature flags in `proc/cpuinfo` by performing a bunch of `PalCpuIdRetrieve()` calls, finding the currently enabled HW features, and adding the corresponding flag-descriptions.

2022-07-26 03:41 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/789)* status: 0 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: )

___
*[`libos/test/regression/test_libos.py` line 1013 at r1](https://reviewable.io/reviews/gramineproject/gramine/789#-N7sZS-L7Vhlfx2OXUvd:-N7sZS-L7Vhlfx2OXUve:b5sf89r) ([raw file](https://github.com/gramineproject/gramine/blob/1908f377066b00e57d9c6ab680ecadabcddded50/libos/test/regression/test_libos.py#L1013)):*
> ```Python
>             for line in cpuinfo.split('\n'))
>         if 'flags' in cpuinfo:
>             cpuinfo['flags'] = ' '.join(flag for flag in cpuinfo['flags'].split()
> ```

This was a legacy issue (when the `flags` field was still in PAL: https://github.com/gramineproject/gramine/blob/07b5c62ccf40a19fc2b039f17667de56f771716c/pal/regression/test_pal.py#L109). Sorry that I should have noticed earlier.

`cpuinfo['flags']` is a `str` so the `for` loop actually doesn't work (`cpuinfo['flags'] = ''` after it), in which case `self.assertIn('CPU flags: {[flags]}'.format(cpuinfo), stderr)` is always true.


<!-- Sent from Reviewable.io -->

2022-07-26 07:09 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/789)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @kailun-qin)

___
*[`libos/src/arch/x86_64/libos_cpuid.c` line 238 at r1](https://reviewable.io/reviews/gramineproject/gramine/789#-N7tJ8G16Sws9dBdr3eD:-N7tJ8G16Sws9dBdr3eE:b-vsspof) ([raw file](https://github.com/gramineproject/gramine/blob/1908f377066b00e57d9c6ab680ecadabcddded50/libos/src/arch/x86_64/libos_cpuid.c#L238)):*
> ```C
>     [30] = "3dnowext", /* AMD 3DNow extensions */
>     [31] = "3dnow",    /* 3DNow */
> };
> ```

FYI: I verified the list against https://github.com/gramineproject/gramine/pull/756, looks the same. Since I reviewed that previous PR thouroughly, I consider this a complete and correct list.
___
*[`libos/src/arch/x86_64/libos_cpuid.c` line 339 at r1](https://reviewable.io/reviews/gramineproject/gramine/789#-N7tJSzdDAkuMfu58gnD:-N7tJSzdDAkuMfu58gnE:b-f03j7n) ([raw file](https://github.com/gramineproject/gramine/blob/1908f377066b00e57d9c6ab680ecadabcddded50/libos/src/arch/x86_64/libos_cpuid.c#L339)):*
> ```C
>     unsigned int max_supported_extended_cpuid_leaf = words[CPUID_WORD_EAX];
>     if (max_supported_extended_cpuid_leaf < 0x80000004) {
>         goto out_err;
> ```

This is not really meaningful here. You're not using leafs `0x80000002`, `0x80000003` or `0x80000004` here (you use them in PAL).

So here I'd just use the same logic as in other places:
```
/* Extended processor info and feature flags: level 0x80000001 */
if (max_supported_extended_cpuid_leaf >= 0x80000001) {
    RETRIEVE_CPUID(0x80000001, 0);

    EXTEND_CAP_FLAGS(g_cpu_flags_cpuid_8000_0001_ecx, CPUID_WORD_ECX);
    EXTEND_CAP_FLAGS(g_cpu_flags_cpuid_8000_0001_edx, CPUID_WORD_EDX);
}
```
___
*[`libos/test/regression/test_libos.py` line 55 at r1](https://reviewable.io/reviews/gramineproject/gramine/789#-N7tJqqqAN9YcKjxQUyO:-N7tJqqqAN9YcKjxQUyP:b-rd2s0i) ([raw file](https://github.com/gramineproject/gramine/blob/1908f377066b00e57d9c6ab680ecadabcddded50/libos/test/regression/test_libos.py#L55)):*
> ```Python
> 
>     'syscall', 'mp', 'nx', 'mmxext', 'fxsr_opt', 'pdpe1gb', 'rdtscp', 'lm',
>     '3dnowext', '3dnow',
> ```

I see no point in this monstrous list... I would cherry-pick 5 to 10 flags, and remove the rest. Let's see what other reviewers think.

My suggested list:
```
'xsave', 'xsaveopt', 'avx', 'sse', 'sse2', 'avx512cd', 'sgx_lc', 'amx_tile', 'avx_vnni', 'mwaitx', 'rdtscp', 'syscall'
```


<!-- Sent from Reviewable.io -->

2022-07-26 07:24 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/789)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

___
*[`libos/src/arch/x86_64/libos_cpuid.c` line 238 at r1](https://reviewable.io/reviews/gramineproject/gramine/789#-N7tJ8G16Sws9dBdr3eD:-N7tMz-z6ZllW6MTktPV:b-yz3wij) ([raw file](https://github.com/gramineproject/gramine/blob/1908f377066b00e57d9c6ab680ecadabcddded50/libos/src/arch/x86_64/libos_cpuid.c#L238)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

FYI: I verified the list against https://github.com/gramineproject/gramine/pull/756, looks the same. Since I reviewed that previous PR thouroughly, I consider this a complete and correct list.
</blockquote></details>

FYI, it's directly copied from https://github.com/gramineproject/gramine/pull/756.
___
*[`libos/src/arch/x86_64/libos_cpuid.c` line 339 at r1](https://reviewable.io/reviews/gramineproject/gramine/789#-N7tJSzdDAkuMfu58gnD:-N7tN7So0sCDw4KBfISt:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/1908f377066b00e57d9c6ab680ecadabcddded50/libos/src/arch/x86_64/libos_cpuid.c#L339)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This is not really meaningful here. You're not using leafs `0x80000002`, `0x80000003` or `0x80000004` here (you use them in PAL).

So here I'd just use the same logic as in other places:
```
/* Extended processor info and feature flags: level 0x80000001 */
if (max_supported_extended_cpuid_leaf >= 0x80000001) {
    RETRIEVE_CPUID(0x80000001, 0);

    EXTEND_CAP_FLAGS(g_cpu_flags_cpuid_8000_0001_ecx, CPUID_WORD_ECX);
    EXTEND_CAP_FLAGS(g_cpu_flags_cpuid_8000_0001_edx, CPUID_WORD_EDX);
}
```
</blockquote></details>

Done.
___
*[`libos/test/regression/test_libos.py` line 55 at r1](https://reviewable.io/reviews/gramineproject/gramine/789#-N7tJqqqAN9YcKjxQUyO:-N7tN9qB5r51SNoodh_R:btyfvku) ([raw file](https://github.com/gramineproject/gramine/blob/1908f377066b00e57d9c6ab680ecadabcddded50/libos/test/regression/test_libos.py#L55)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I see no point in this monstrous list... I would cherry-pick 5 to 10 flags, and remove the rest. Let's see what other reviewers think.

My suggested list:
```
'xsave', 'xsaveopt', 'avx', 'sse', 'sse2', 'avx512cd', 'sgx_lc', 'amx_tile', 'avx_vnni', 'mwaitx', 'rdtscp', 'syscall'
```
</blockquote></details>

Agree, just not certain about which ones to pick here... I'll leave this open for now and add a fixup if everyone is OK w/ the suggested list.


<!-- Sent from Reviewable.io -->

2022-07-26 07:35 UTC, dimakuv reviewed
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/789)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2022-07-26 07:43 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/789)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`libos/test/regression/test_libos.py` line 55 at r1](https://reviewable.io/reviews/gramineproject/gramine/789#-N7tJqqqAN9YcKjxQUyO:-N7tRmlI9Iv7_KbnoHj5:b-nrk81j) ([raw file](https://github.com/gramineproject/gramine/blob/1908f377066b00e57d9c6ab680ecadabcddded50/libos/test/regression/test_libos.py#L55)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Agree, just not certain about which ones to pick here... I'll leave this open for now and add a fixup if everyone is OK w/ the suggested list.
</blockquote></details>

Maybe better to also add some flags that are commonly available on any modern x86-64 CPU (e.g., `fpu`, `msr`, `apic`).


<!-- Sent from Reviewable.io -->

2022-07-26 12:01 UTC, mkow reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/789)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @kailun-qin)

___
*[`libos/src/arch/x86_64/libos_cpuid.c` line 11 at r2](https://reviewable.io/reviews/gramineproject/gramine/789#-N7u7flc7Pg6-NAB4xPy:-N7u7fldCMtsMERv5G1q:b-30xi7o) ([raw file](https://github.com/gramineproject/gramine/blob/88fba5386a0bc77a8f498a93a506cb73f21aa78a/libos/src/arch/x86_64/libos_cpuid.c#L11)):*
> ```C
> 
> /*
>  *  List of x86 CPU feature flags. This list was last revised in July 2022, see below for details:
> ```

The date doesn't matter, what matters is on which Linux version it was based.



_Code quote:_
```C
This list was last revised in July 2022
```
___
*[`libos/test/regression/test_libos.py` line 55 at r1](https://reviewable.io/reviews/gramineproject/gramine/789#-N7tJqqqAN9YcKjxQUyO:-N7uNDo2DQbhk8Ckpodz:bh8cvm) ([raw file](https://github.com/gramineproject/gramine/blob/1908f377066b00e57d9c6ab680ecadabcddded50/libos/test/regression/test_libos.py#L55)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Maybe better to also add some flags that are commonly available on any modern x86-64 CPU (e.g., `fpu`, `msr`, `apic`).
</blockquote></details>

I'm neutral on this, hard to say if having so many of them have any pros (actually helps any app) or cons (security-wise).


<!-- Sent from Reviewable.io -->

2022-07-26 14:00 UTC, boryspoplawski approved these changes
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/789)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @kailun-qin)



<!-- Sent from Reviewable.io -->

2022-07-26 14:36 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/789)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`libos/src/arch/x86_64/libos_cpuid.c` line 11 at r2](https://reviewable.io/reviews/gramineproject/gramine/789#-N7u7flc7Pg6-NAB4xPy:-N7utre9AApU0zr0U2vM:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/88fba5386a0bc77a8f498a93a506cb73f21aa78a/libos/src/arch/x86_64/libos_cpuid.c#L11)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

The date doesn't matter, what matters is on which Linux version it was based.
</blockquote></details>

Done.
___
*[`libos/test/regression/test_libos.py` line 55 at r1](https://reviewable.io/reviews/gramineproject/gramine/789#-N7tJqqqAN9YcKjxQUyO:-N7uuiwo68Qk1uPwosvy:b-4zp0kr) ([raw file](https://github.com/gramineproject/gramine/blob/1908f377066b00e57d9c6ab680ecadabcddded50/libos/test/regression/test_libos.py#L55)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'm neutral on this, hard to say if having so many of them have any pros (actually helps any app) or cons (security-wise).
</blockquote></details>

Changing to @dimakuv's suggested list (adding w/ `fpu`, `msr`, `apic`) as no objection so far. Feel free to let me know if any further concerns.


<!-- Sent from Reviewable.io -->

2022-07-26 14:44 UTC, boryspoplawski approved these changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/789)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @kailun-qin, and @mkow)



<!-- Sent from Reviewable.io -->

2022-07-26 15:40 UTC, dimakuv submitted a review, later dismissed
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/789)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)



<!-- Sent from Reviewable.io -->

2022-07-26 15:41 UTC, dimakuv commented
Jenkins, test this please

2022-07-28 14:59 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/789)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

___
*[`libos/test/regression/test_libos.py` line 55 at r1](https://reviewable.io/reviews/gramineproject/gramine/789#-N7tJqqqAN9YcKjxQUyO:-N84JDXd1j3_nUSyEj5C:bo9tb0y) ([raw file](https://github.com/gramineproject/gramine/blob/1908f377066b00e57d9c6ab680ecadabcddded50/libos/test/regression/test_libos.py#L55)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Changing to @dimakuv's suggested list (adding w/ `fpu`, `msr`, `apic`) as no objection so far. Feel free to let me know if any further concerns.
</blockquote></details>

Ah, right, I thought @dimakuv's comment was about the whole list of forwarded flags, not only about this test.


<!-- Sent from Reviewable.io -->

2022-07-28 15:18 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/789)* status: 1 of 2 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @kailun-qin, and @mkow)

___
*[`libos/src/arch/x86_64/libos_cpuid.c` line 276 at r3](https://reviewable.io/reviews/gramineproject/gramine/789#-N84JwPgA_AgXT3QVITB:-N84Muzf9nZodyzhKe34:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/fa9b69ad270d18d8aacb79b5219bd167b33d01f7/libos/src/arch/x86_64/libos_cpuid.c#L276)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please remove the last backslash, you can accidentally add something to the macro this way when refactoring.
</blockquote></details>

Done.
___
*[`libos/src/arch/x86_64/libos_cpuid.c` line 283 at r3](https://reviewable.io/reviews/gramineproject/gramine/789#-N84K1RI9ZxlWufrKT3_:-N84MvYZ9ovLWJGsWNWT:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/fa9b69ad270d18d8aacb79b5219bd167b33d01f7/libos/src/arch/x86_64/libos_cpuid.c#L283)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`libos/test/regression/test_libos.py` line 55 at r1](https://reviewable.io/reviews/gramineproject/gramine/789#-N7tJqqqAN9YcKjxQUyO:-N84MzevA0tR6M3T21rJ:b-jfe1su) ([raw file](https://github.com/gramineproject/gramine/blob/1908f377066b00e57d9c6ab680ecadabcddded50/libos/test/regression/test_libos.py#L55)):*
I think @dimakuv was basically commenting on the test flags. As the initial idea was to support as many flags as possible (see https://github.com/gramineproject/gramine/issues/592#issuecomment-1170201576).

> I'm neutral on this, hard to say if having so many of them have any pros (actually helps any app) or cons (security-wise).

Anyway, I agree on this, but I would prefer the potential CPUID sanitization to address security concerns.


<!-- Sent from Reviewable.io -->

2022-07-28 15:20 UTC, mkow reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/789)* status: 1 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @kailun-qin)



<!-- Sent from Reviewable.io -->

2022-07-28 16:16 UTC, boryspoplawski approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/789)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)



<!-- Sent from Reviewable.io -->

2022-07-29 06:55 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> Dismissed @kailun-qin from a discussion.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/789)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

___
*[`libos/test/regression/test_libos.py` line 55 at r1](https://reviewable.io/reviews/gramineproject/gramine/789#-N7tJqqqAN9YcKjxQUyO:-N87iarVDONg9T--SIkr:bx64f56) ([raw file](https://github.com/gramineproject/gramine/blob/1908f377066b00e57d9c6ab680ecadabcddded50/libos/test/regression/test_libos.py#L55)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

I think @dimakuv was basically commenting on the test flags. As the initial idea was to support as many flags as possible (see https://github.com/gramineproject/gramine/issues/592#issuecomment-1170201576).

> I'm neutral on this, hard to say if having so many of them have any pros (actually helps any app) or cons (security-wise).

Anyway, I agree on this, but I would prefer the potential CPUID sanitization to address security concerns.
</blockquote></details>

Yes, I was commenting purely on this test (that we shouldn't bother testing *all* known flags).

We should forward as many flags to the app as possible, because we never know what the next failing app will rely on in the CPUID bits. I mean, at least at the LibOS level (as this PR does) we need to try to forward all known flags. As @kailun-qin mentioned, at the level of PAL, we can rely on CPUID sanitization to omit some flags if we will consider them security-critical.


<!-- Sent from Reviewable.io -->

2022-07-29 07:29 UTC, dimakuv commented
Jenkins, test this please

2022-07-29 10:04 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/789)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2022-07-29 10:06 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/789)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2022-07-29 10:06 UTC, dimakuv commented
Jenkins, test this please

2022-07-29 10:29 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/789)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2022-07-29 11:50 UTC, boryspoplawski approved these changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/789)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-07-29 12:26 UTC, merged