[mbedtls,tools/sgx,CI-Examples,common] Upgrade mbedTLS to version 3.2.1
gramineproject/gramine pull request #796
Opened 2022-07-26 15:44 UTC by kailun-qin

2022-07-26 17:31 UTC, mkow requested changes
> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/796)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @kailun-qin)

___
*[`CI-Examples/ra-tls-mbedtls/src/client.c` line 8 at r1](https://reviewable.io/reviews/gramineproject/gramine/796#-N7vTkPN3GHW2OigVu5B:-N7vTkPN3GHW2OigVu5C:b-y8excr) ([raw file](https://github.com/gramineproject/gramine/blob/72a00411ab0e8ad96843ebaa5799445edadecd6b/CI-Examples/ra-tls-mbedtls/src/client.c#L8)):*
> ```C
> /*
>  * SSL client demonstration program (with RA-TLS).
>  * This program is heavily based on an mbedTLS 3.2.1 example ssl_client1.c
> ```

@dimakuv, @kailun-qin: Could you diff this example carefully between 2.26.0 and 3.2.1 and check if anything has changed there?



_Code quote:_
```C
This program is heavily based on an mbedTLS 3.2.1 example ssl_client1.c
```
___
*[`CI-Examples/ra-tls-mbedtls/src/server.c` line 8 at r1](https://reviewable.io/reviews/gramineproject/gramine/796#-N7vTzn22wwYhS-FMAYR:-N7vTzn30_r236bhoEi8:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/72a00411ab0e8ad96843ebaa5799445edadecd6b/CI-Examples/ra-tls-mbedtls/src/server.c#L8)):*
> ```C
> /*
>  * SSL server demonstration program (with RA-TLS)
>  * This program is heavily based on an mbedTLS 3.2.1 example ssl_server.c
> ```

ditto



_Code quote:_
```C
This program is heavily based on an mbedTLS 3.2.1 example ssl_server.c
```
___
*[`common/src/crypto/adapters/mbedtls_adapter.c` line 464 at r1](https://reviewable.io/reviews/gramineproject/gramine/796#-N7vYvbo1FBbSCak7T-Z:-N7vYvbo1FBbSCak7T-_:b-11rk94) ([raw file](https://github.com/gramineproject/gramine/blob/72a00411ab0e8ad96843ebaa5799445edadecd6b/common/src/crypto/adapters/mbedtls_adapter.c#L464)):*
> ```C
>         return -PAL_ERROR_INVAL;
> 
>     int ret = mbedtls_dhm_make_public(context, (int)mbedtls_dhm_get_len(context), public, public_size,
> ```

please fix wrapping
___
*[`subprojects/mbedtls-mbedtls-3.2.1.wrap` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/796#-N7vWvox5hbU6LRemWLT:-N7vWvox5hbU6LRemWLU:bx9wmok) ([raw file](https://github.com/gramineproject/gramine/blob/72a00411ab0e8ad96843ebaa5799445edadecd6b/subprojects/mbedtls-mbedtls-3.2.1.wrap#L4)):*
> ```
> directory = mbedtls-mbedtls-3.2.1
> source_url = https://github.com/ARMmbed/mbedtls/archive/mbedtls-3.2.1.tar.gz
> source_fallback_url = https://packages.gramineproject.io/distfiles/mbedtls-3.2.1.tar.gz
> ```

@boryspoplawski: Please host this file.



_Code quote:_
```
https://packages.gramineproject.io/distfiles/mbedtls-3.2.1.tar.gz
```
___
*[`subprojects/packagefiles/mbedtls/gramine.patch` line 138 at r1](https://reviewable.io/reviews/gramineproject/gramine/796#-N7vXL-P69dE1mabYiRs:-N7vXL-P69dE1mabYiRt:bq1p4lo) ([raw file](https://github.com/gramineproject/gramine/blob/72a00411ab0e8ad96843ebaa5799445edadecd6b/subprojects/packagefiles/mbedtls/gramine.patch#L138)):*
> ```Diff
>  	echo "  LD    $@"
> -	$(CC) -shared -Wl,-soname,$@ -o $@ $(OBJS_TLS) -L. -lmbedx509 -lmbedcrypto $(LOCAL_LDFLAGS) $(LDFLAGS)
> +	$(CC) -shared -Wl,-soname,$@ -o $@ $(OBJS_TLS) -L. -lmbedcrypto$(SUFFIX) -lmbedx509$(SUFFIX) $(LOCAL_LDFLAGS) $(LDFLAGS)
> ```

This is wrong, please preserve the original linking order in the patch.
___
*[`subprojects/packagefiles/mbedtls/gramine.patch` line 192 at r1](https://reviewable.io/reviews/gramineproject/gramine/796#-N7vX_iHDynEuE8yAKU7:-N7vX_iHDynEuE8yAKU8:b-w1kj8h) ([raw file](https://github.com/gramineproject/gramine/blob/72a00411ab0e8ad96843ebaa5799445edadecd6b/subprojects/packagefiles/mbedtls/gramine.patch#L192)):*
> ```Diff
>  	ln -sf $< $@
>  
> ```

Why adding an empty line here? I think the patch file was already terminated with '\n' byte, and now you have two of them?


<!-- Sent from Reviewable.io -->

2022-07-26 17:32 UTC, mkow commented
Jenkins, retest this please

2022-07-26 18:57 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/796)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @kailun-qin and @mkow)

___
*[`subprojects/mbedtls-mbedtls-3.2.1.wrap` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/796#-N7vWvox5hbU6LRemWLT:-N7vra8u5q02jIF8A3B2:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/72a00411ab0e8ad96843ebaa5799445edadecd6b/subprojects/mbedtls-mbedtls-3.2.1.wrap#L4)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

@boryspoplawski: Please host this file.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-26 19:05 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/796)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @kailun-qin and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/796#-N7vtCHK3D9GIhnqknx3:-N7vtCHL3eVwLdFGucq_:be7i2ru) (no related file):*
Seems it doesn't even compile in CI:
```
19:39:01  FAILED: libos/src/libsysdb.so.p/.._.._common_src_crypto_adapters_mbedtls_adapter.c.o 
19:39:01  cc -Ilibos/src/libsysdb.so.p -Ilibos/src -I../libos/src -Ilibos/include -I../libos/include -I../libos/include/arch/x86_64 -Ipal/include -I../pal/include -I../pal/include/pal -I../pal/include/elf -I../pal/include/arch/x86_64 -I../pal/include/arch/x86_64/linux -Icommon/include -I../common/include -I../common/include/arch/x86_64 -Isubprojects/uthash-2.1.0/src -I../subprojects/uthash-2.1.0/src -Isubprojects/tomlc99-208203af46bdbdb29ba199660ed78d09c220b6c5 -I../subprojects/tomlc99-208203af46bdbdb29ba199660ed78d09c220b6c5 -I../subprojects/mbedtls-mbedtls-3.2.1/include -I../subprojects/mbedtls-mbedtls-3.2.1/mbedtls-mbedtls-3.2.1/include -Icommon/src/protected_files -I../common/src/protected_files -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Werror -std=c11 -O3 -Wa,--noexecstack -Wall -Wextra -Wmissing-prototypes -Wstrict-prototypes -Wwrite-strings -Wtrampolines -Wnull-dereference -fPIC '-DMBEDTLS_CONFIG_FILE="mbedtls/config-pal.h"' -DCRYPTO_USE_MBEDTLS -fno-builtin -DIN_LIBOS -Wno-null-dereference -mfxsr -mxsave -fno-stack-protector -MD -MQ libos/src/libsysdb.so.p/.._.._common_src_crypto_adapters_mbedtls_adapter.c.o -MF libos/src/libsysdb.so.p/.._.._common_src_crypto_adapters_mbedtls_adapter.c.o.d -o libos/src/libsysdb.so.p/.._.._common_src_crypto_adapters_mbedtls_adapter.c.o -c ../common/src/crypto/adapters/mbedtls_adapter.c
19:39:01  In file included from /usr/include/errno.h:25:0,
19:39:01                   from ../common/src/crypto/adapters/mbedtls_adapter.c:6:
19:39:01  ../common/include/api_fortified.h:53:45: error: expected declaration specifiers or ‘...’ before numeric constant
19:39:01       __builtin___snprintf_chk(buf, buf_size, __USE_FORTIFY_LEVEL - 1, __api_bos(buf), fmt)
19:39:01                                               ^
19:39:01  ../subprojects/mbedtls-mbedtls-3.2.1/include/mbedtls/config-pal.h:57:5: note: in expansion of macro ‘snprintf’
19:39:01   int snprintf(char* buf, size_t buf_size, const char* fmt, ...)
19:39:01       ^~~~~~~~
19:39:01  In file included from ../common/include/api.h:463:0,
19:39:01                   from ../common/src/crypto/adapters/mbedtls_adapter.c:10:
19:39:01  ../common/include/api_fortified.h:38:24: error: expected declaration specifiers or ‘...’ before ‘__builtin_object_size’
19:39:01   #define __api_bos(ptr) __builtin_object_size(ptr, __USE_FORTIFY_LEVEL > 1)
19:39:01                          ^
19:39:01  ../common/include/api_fortified.h:53:70: note: in expansion of macro ‘__api_bos’
19:39:01       __builtin___snprintf_chk(buf, buf_size, __USE_FORTIFY_LEVEL - 1, __api_bos(buf), fmt)
19:39:01                                                                        ^~~~~~~~~
19:39:01  ../subprojects/mbedtls-mbedtls-3.2.1/include/mbedtls/config-pal.h:57:5: note: in expansion of macro ‘snprintf’
19:39:01   int snprintf(char* buf, size_t buf_size, const char* fmt, ...)
19:39:01       ^~~~~~~~
```

___


<!-- Sent from Reviewable.io -->

2022-07-27 01:52 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/796)* status: 14 of 17 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/796#-N7vtCHK3D9GIhnqknx3:-N7xJjqzAvw4yyAy_g1y:b9wbngn) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Seems it doesn't even compile in CI:
```
19:39:01  FAILED: libos/src/libsysdb.so.p/.._.._common_src_crypto_adapters_mbedtls_adapter.c.o 
19:39:01  cc -Ilibos/src/libsysdb.so.p -Ilibos/src -I../libos/src -Ilibos/include -I../libos/include -I../libos/include/arch/x86_64 -Ipal/include -I../pal/include -I../pal/include/pal -I../pal/include/elf -I../pal/include/arch/x86_64 -I../pal/include/arch/x86_64/linux -Icommon/include -I../common/include -I../common/include/arch/x86_64 -Isubprojects/uthash-2.1.0/src -I../subprojects/uthash-2.1.0/src -Isubprojects/tomlc99-208203af46bdbdb29ba199660ed78d09c220b6c5 -I../subprojects/tomlc99-208203af46bdbdb29ba199660ed78d09c220b6c5 -I../subprojects/mbedtls-mbedtls-3.2.1/include -I../subprojects/mbedtls-mbedtls-3.2.1/mbedtls-mbedtls-3.2.1/include -Icommon/src/protected_files -I../common/src/protected_files -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Werror -std=c11 -O3 -Wa,--noexecstack -Wall -Wextra -Wmissing-prototypes -Wstrict-prototypes -Wwrite-strings -Wtrampolines -Wnull-dereference -fPIC '-DMBEDTLS_CONFIG_FILE="mbedtls/config-pal.h"' -DCRYPTO_USE_MBEDTLS -fno-builtin -DIN_LIBOS -Wno-null-dereference -mfxsr -mxsave -fno-stack-protector -MD -MQ libos/src/libsysdb.so.p/.._.._common_src_crypto_adapters_mbedtls_adapter.c.o -MF libos/src/libsysdb.so.p/.._.._common_src_crypto_adapters_mbedtls_adapter.c.o.d -o libos/src/libsysdb.so.p/.._.._common_src_crypto_adapters_mbedtls_adapter.c.o -c ../common/src/crypto/adapters/mbedtls_adapter.c
19:39:01  In file included from /usr/include/errno.h:25:0,
19:39:01                   from ../common/src/crypto/adapters/mbedtls_adapter.c:6:
19:39:01  ../common/include/api_fortified.h:53:45: error: expected declaration specifiers or ‘...’ before numeric constant
19:39:01       __builtin___snprintf_chk(buf, buf_size, __USE_FORTIFY_LEVEL - 1, __api_bos(buf), fmt)
19:39:01                                               ^
19:39:01  ../subprojects/mbedtls-mbedtls-3.2.1/include/mbedtls/config-pal.h:57:5: note: in expansion of macro ‘snprintf’
19:39:01   int snprintf(char* buf, size_t buf_size, const char* fmt, ...)
19:39:01       ^~~~~~~~
19:39:01  In file included from ../common/include/api.h:463:0,
19:39:01                   from ../common/src/crypto/adapters/mbedtls_adapter.c:10:
19:39:01  ../common/include/api_fortified.h:38:24: error: expected declaration specifiers or ‘...’ before ‘__builtin_object_size’
19:39:01   #define __api_bos(ptr) __builtin_object_size(ptr, __USE_FORTIFY_LEVEL > 1)
19:39:01                          ^
19:39:01  ../common/include/api_fortified.h:53:70: note: in expansion of macro ‘__api_bos’
19:39:01       __builtin___snprintf_chk(buf, buf_size, __USE_FORTIFY_LEVEL - 1, __api_bos(buf), fmt)
19:39:01                                                                        ^~~~~~~~~
19:39:01  ../subprojects/mbedtls-mbedtls-3.2.1/include/mbedtls/config-pal.h:57:5: note: in expansion of macro ‘snprintf’
19:39:01   int snprintf(char* buf, size_t buf_size, const char* fmt, ...)
19:39:01       ^~~~~~~~
```
</blockquote></details>

Fixed. This was due to the trick here https://github.com/gramineproject/gramine/blob/a36b39d798fcc4195bfa8575723455d079fb0636/subprojects/packagefiles/mbedtls/include/mbedtls/config-pal.h#L54 to prevent the declarations from colliding with `api_fortified.h` which redefines a number of functions as macros is not correctly applied. As it happens only when _FORTIFY_SOURCE is enabled, and gcc doesn't enable it at optimization level 0 (in my env), excuse me for not having noticed that.

___
___
*[`CI-Examples/ra-tls-mbedtls/src/client.c` line 8 at r1](https://reviewable.io/reviews/gramineproject/gramine/796#-N7vTkPN3GHW2OigVu5B:-N7xJvCB81AaaPCOwyv_:b-lpwky) ([raw file](https://github.com/gramineproject/gramine/blob/72a00411ab0e8ad96843ebaa5799445edadecd6b/CI-Examples/ra-tls-mbedtls/src/client.c#L8)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

@dimakuv, @kailun-qin: Could you diff this example carefully between 2.26.0 and 3.2.1 and check if anything has changed there?
</blockquote></details>

Yes, I've diffed the two versions of examples. The changes are basically applied here. I'll let @dimakuv to have another look if I missed anything.
___
*[`CI-Examples/ra-tls-mbedtls/src/server.c` line 8 at r1](https://reviewable.io/reviews/gramineproject/gramine/796#-N7vTzn22wwYhS-FMAYR:-N7xJuKwDpC4Gei4ZWjI:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/72a00411ab0e8ad96843ebaa5799445edadecd6b/CI-Examples/ra-tls-mbedtls/src/server.c#L8)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`common/src/crypto/adapters/mbedtls_adapter.c` line 464 at r1](https://reviewable.io/reviews/gramineproject/gramine/796#-N7vYvbo1FBbSCak7T-Z:-N7xJs0v37yQhxkc1w-0:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/72a00411ab0e8ad96843ebaa5799445edadecd6b/common/src/crypto/adapters/mbedtls_adapter.c#L464)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

please fix wrapping
</blockquote></details>

Done.
___
*[`subprojects/packagefiles/mbedtls/gramine.patch` line 138 at r1](https://reviewable.io/reviews/gramineproject/gramine/796#-N7vXL-P69dE1mabYiRs:-N7xJpjw53VnC8w_Ybv8:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/72a00411ab0e8ad96843ebaa5799445edadecd6b/subprojects/packagefiles/mbedtls/gramine.patch#L138)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This is wrong, please preserve the original linking order in the patch.
</blockquote></details>

Done.
___
*[`subprojects/packagefiles/mbedtls/gramine.patch` line 192 at r1](https://reviewable.io/reviews/gramineproject/gramine/796#-N7vX_iHDynEuE8yAKU7:-N7xJojPCaz2vcrfG8oJ:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/72a00411ab0e8ad96843ebaa5799445edadecd6b/subprojects/packagefiles/mbedtls/gramine.patch#L192)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why adding an empty line here? I think the patch file was already terminated with '\n' byte, and now you have two of them?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-27 08:39 UTC, dimakuv requested changes
> Reviewed 14 of 16 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/796)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)

___
*[`CI-Examples/ra-tls-mbedtls/src/client.c` line 8 at r1](https://reviewable.io/reviews/gramineproject/gramine/796#-N7vTkPN3GHW2OigVu5B:-N7ylrv11JucUjGbbixm:b-oaplnr) ([raw file](https://github.com/gramineproject/gramine/blob/72a00411ab0e8ad96843ebaa5799445edadecd6b/CI-Examples/ra-tls-mbedtls/src/client.c#L8)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Yes, I've diffed the two versions of examples. The changes are basically applied here. I'll let @dimakuv to have another look if I missed anything.
</blockquote></details>

Why do we care to update the version? We can keep v2.26.0. Or we can just completely delete this sentence, since there were so many changes to this file that it barely resembles the original `ssl_client1.c` that I took (like 2-3 years ago) as a basis.
___
*[`CI-Examples/ra-tls-mbedtls/src/server.c` line 8 at r1](https://reviewable.io/reviews/gramineproject/gramine/796#-N7vTzn22wwYhS-FMAYR:-N7ymAwi-O191-eaqG6n:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/72a00411ab0e8ad96843ebaa5799445edadecd6b/CI-Examples/ra-tls-mbedtls/src/server.c#L8)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

ditto
___
*[`CI-Examples/ra-tls-mbedtls/src/server.c` line 219 at r2](https://reviewable.io/reviews/gramineproject/gramine/796#-N7ymLae51JZHjutkfPD:-N7ymLaf4_Y7e37xwfhD:b-3924eb) ([raw file](https://github.com/gramineproject/gramine/blob/a36b39d798fcc4195bfa8575723455d079fb0636/CI-Examples/ra-tls-mbedtls/src/server.c#L219)):*
> ```C
> 
>         ret = mbedtls_pk_parse_keyfile(&pkey, SRV_KEY_PATH, NULL,
>                                        mbedtls_ctr_drbg_random, &ctr_drbg);
> ```

I think the whole line will fit into 100 chars? Please rewrap.
___
*[`common/include/api.h` line 6 at r2](https://reviewable.io/reviews/gramineproject/gramine/796#-N7ymXgS-tkczkhnus8Q:-N7ymXgS-tkczkhnus8R:b7523ze) ([raw file](https://github.com/gramineproject/gramine/blob/a36b39d798fcc4195bfa8575723455d079fb0636/common/include/api.h#L6)):*
> ```objc
> #pragma once
> 
> #define API_H
> ```

Beh. Now this looks weird. I suggest to rename to smth like `GRAMINE_API_HEADER_USED` here and in the users.


<!-- Sent from Reviewable.io -->

2022-07-27 09:44 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/796)* status: 13 of 17 files reviewed, 9 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`CI-Examples/ra-tls-mbedtls/src/client.c` line 8 at r1](https://reviewable.io/reviews/gramineproject/gramine/796#-N7vTkPN3GHW2OigVu5B:-N7z0uCY8V6qrKab1j9R:b-d539gq) ([raw file](https://github.com/gramineproject/gramine/blob/72a00411ab0e8ad96843ebaa5799445edadecd6b/CI-Examples/ra-tls-mbedtls/src/client.c#L8)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do we care to update the version? We can keep v2.26.0. Or we can just completely delete this sentence, since there were so many changes to this file that it barely resembles the original `ssl_client1.c` that I took (like 2-3 years ago) as a basis.
</blockquote></details>

I don't think we need to care about the version. My point is that I've verified the logic/API updates to make sure it works w/ v3.2.1.

Changed the wording a bit, PTAL, thanks.
___
*[`CI-Examples/ra-tls-mbedtls/src/server.c` line 219 at r2](https://reviewable.io/reviews/gramineproject/gramine/796#-N7ymLae51JZHjutkfPD:-N7z17iqAnuE5FSJIXSd:babay09) ([raw file](https://github.com/gramineproject/gramine/blob/a36b39d798fcc4195bfa8575723455d079fb0636/CI-Examples/ra-tls-mbedtls/src/server.c#L219)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I think the whole line will fit into 100 chars? Please rewrap.
</blockquote></details>

Sorry, it can't. But still re-wrapped to avoid confusions.
___
*[`common/include/api.h` line 6 at r2](https://reviewable.io/reviews/gramineproject/gramine/796#-N7ymXgS-tkczkhnus8Q:-N7z1E5fD0QUz9VlEYqP:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/a36b39d798fcc4195bfa8575723455d079fb0636/common/include/api.h#L6)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Beh. Now this looks weird. I suggest to rename to smth like `GRAMINE_API_HEADER_USED` here and in the users.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-27 09:48 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/796)* status: 13 of 17 files reviewed, 9 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`CI-Examples/ra-tls-mbedtls/src/client.c` line 8 at r1](https://reviewable.io/reviews/gramineproject/gramine/796#-N7vTkPN3GHW2OigVu5B:-N7z1z0h6ui4xa9ssHDC:bxd4pl5) ([raw file](https://github.com/gramineproject/gramine/blob/72a00411ab0e8ad96843ebaa5799445edadecd6b/CI-Examples/ra-tls-mbedtls/src/client.c#L8)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

I don't think we need to care about the version. My point is that I've verified the logic/API updates to make sure it works w/ v3.2.1.

Changed the wording a bit, PTAL, thanks.
</blockquote></details>

Emm... Just to stress that the example in this PR would only work w/ 3.x due to API updates. Not sure if we need to mention the version here.


<!-- Sent from Reviewable.io -->

2022-07-27 09:55 UTC, dimakuv requested changes
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/796)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)

___
*[`CI-Examples/ra-tls-mbedtls/src/client.c` line 8 at r1](https://reviewable.io/reviews/gramineproject/gramine/796#-N7vTkPN3GHW2OigVu5B:-N7z3fOs4bhj4sIXWoBn:bdd3yv7) ([raw file](https://github.com/gramineproject/gramine/blob/72a00411ab0e8ad96843ebaa5799445edadecd6b/CI-Examples/ra-tls-mbedtls/src/client.c#L8)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Emm... Just to stress that the example in this PR would only work w/ 3.x due to API updates. Not sure if we need to mention the version here.
</blockquote></details>

Ah, yes, this we should mention, that this program builds against mbedTLS 3.x.
___
*[`CI-Examples/ra-tls-mbedtls/src/server.c` line 8 at r1](https://reviewable.io/reviews/gramineproject/gramine/796#-N7vTzn22wwYhS-FMAYR:-N7z3mQJ2IXdfrH1KdqY:bwykx9d) ([raw file](https://github.com/gramineproject/gramine/blob/72a00411ab0e8ad96843ebaa5799445edadecd6b/CI-Examples/ra-tls-mbedtls/src/server.c#L8)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

We should mention, that this program builds against mbedTLS 3.x.
___
*[`common/include/api.h` line 13 at r3](https://reviewable.io/reviews/gramineproject/gramine/796#-N7z45UR8jJLUc5ROmsV:-N7z45UR8jJLUc5ROmsW:b-6e76ef) ([raw file](https://github.com/gramineproject/gramine/blob/6354250052b9a437a3f47c358bf5e0259ef0b78a/common/include/api.h#L13)):*
> ```objc
> #include <stdint.h>
> 
> #define INSIDE_API_H
> ```

Oops, sorry, we already have this one. Please remove `GRAMINE_API_HEADER_USED` and use this macro in that mbedTLS header.


<!-- Sent from Reviewable.io -->

2022-07-27 10:00 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/796)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`common/include/api.h` line 13 at r3](https://reviewable.io/reviews/gramineproject/gramine/796#-N7z45UR8jJLUc5ROmsV:-N7z4vh09Ho_M-596O9x:b8kpc5) ([raw file](https://github.com/gramineproject/gramine/blob/6354250052b9a437a3f47c358bf5e0259ef0b78a/common/include/api.h#L13)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Oops, sorry, we already have this one. Please remove `GRAMINE_API_HEADER_USED` and use this macro in that mbedTLS header.
</blockquote></details>

This will be undef, see: https://github.com/gramineproject/gramine/blob/master/common/include/api.h#L466, and the name is also a bit confusing.


<!-- Sent from Reviewable.io -->

2022-07-27 10:13 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/796)* status: 15 of 17 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`CI-Examples/ra-tls-mbedtls/src/client.c` line 8 at r1](https://reviewable.io/reviews/gramineproject/gramine/796#-N7vTkPN3GHW2OigVu5B:-N7z8O0M46H1iOFcZRSe:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/72a00411ab0e8ad96843ebaa5799445edadecd6b/CI-Examples/ra-tls-mbedtls/src/client.c#L8)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ah, yes, this we should mention, that this program builds against mbedTLS 3.x.
</blockquote></details>

Done.
___
*[`CI-Examples/ra-tls-mbedtls/src/server.c` line 8 at r1](https://reviewable.io/reviews/gramineproject/gramine/796#-N7vTzn22wwYhS-FMAYR:-N7z8PJc7WtghP1sjAm6:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/72a00411ab0e8ad96843ebaa5799445edadecd6b/CI-Examples/ra-tls-mbedtls/src/server.c#L8)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We should mention, that this program builds against mbedTLS 3.x.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-27 11:29 UTC, dimakuv approved these changes
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/796)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`common/include/api.h` line 13 at r3](https://reviewable.io/reviews/gramineproject/gramine/796#-N7z45UR8jJLUc5ROmsV:-N7zPamuDUiHnyVxhxby:b2gxq1e) ([raw file](https://github.com/gramineproject/gramine/blob/6354250052b9a437a3f47c358bf5e0259ef0b78a/common/include/api.h#L13)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

This will be undef, see: https://github.com/gramineproject/gramine/blob/master/common/include/api.h#L466, and the name is also a bit confusing.
</blockquote></details>

Ok... We have some complicated logic here.


<!-- Sent from Reviewable.io -->

2022-07-27 11:29 UTC, dimakuv commented
Jenkins, test this please

2022-07-27 17:02 UTC, mkow requested changes
> Reviewed 2 of 3 files at r2, 2 of 4 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/796)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)

___
*[`CI-Examples/ra-tls-mbedtls/src/client.c` line 8 at r1](https://reviewable.io/reviews/gramineproject/gramine/796#-N7vTkPN3GHW2OigVu5B:-N8-_F136HxdpD9xD2xt:btoxw4c) ([raw file](https://github.com/gramineproject/gramine/blob/72a00411ab0e8ad96843ebaa5799445edadecd6b/CI-Examples/ra-tls-mbedtls/src/client.c#L8)):*
> Why do we care to update the version?

1. This was a major version update, the API might have changed (not always in compiler-noticeable ways).
2. It might have fixed bugs or simplified some parts of the example.
3. The old example might be using now-deprecated APIs.

So, @dimakuv, please also take a look at the changes between the old and the new example (i.e. without RA-TLS changes, and then check this example against that diff).


<!-- Sent from Reviewable.io -->

2022-07-28 07:58 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/796)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/796#-N82kTo37JT9h1uL1bkL:-N82kTo45vZ0MlE1SuPt:b-cyahxu) (no related file):*
What is this file: https://github.com/gramineproject/gramine/blob/master/common/src/crypto/config.h ? Looks like this should be removed.

___
___
*[`CI-Examples/ra-tls-mbedtls/src/client.c` line 8 at r1](https://reviewable.io/reviews/gramineproject/gramine/796#-N7vTkPN3GHW2OigVu5B:-N82_gXE9Ov3LPQ7p228:b6s3xoj) ([raw file](https://github.com/gramineproject/gramine/blob/72a00411ab0e8ad96843ebaa5799445edadecd6b/CI-Examples/ra-tls-mbedtls/src/client.c#L8)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> Why do we care to update the version?

1. This was a major version update, the API might have changed (not always in compiler-noticeable ways).
2. It might have fixed bugs or simplified some parts of the example.
3. The old example might be using now-deprecated APIs.

So, @dimakuv, please also take a look at the changes between the old and the new example (i.e. without RA-TLS changes, and then check this example against that diff).
</blockquote></details>

Ok, done. Let me dump all the details here.

I obtained the diff like this: `git diff --no-index ssl_client1.2.26.0.c ssl_client1.3.2.1.c` (the files were taken from corresponding mbedTLS sources).

```diff
diff --git a/ssl_client1.2.26.0.c b/ssl_client1.3.2.1.c
@@ -17,11 +17,7 @@
  *  limitations under the License.
  */

-#if !defined(MBEDTLS_CONFIG_FILE)
-#include "mbedtls/config.h"
-#else
-#include MBEDTLS_CONFIG_FILE
-#endif
+#include "mbedtls/build_info.h"

 #if defined(MBEDTLS_PLATFORM_C)
 #include "mbedtls/platform.h"
@@ -37,11 +33,11 @@
 #define MBEDTLS_EXIT_FAILURE    EXIT_FAILURE
 #endif /* MBEDTLS_PLATFORM_C */

-#if !defined(MBEDTLS_BIGNUM_C) || !defined(MBEDTLS_ENTROPY_C) ||  \
-    !defined(MBEDTLS_SSL_TLS_C) || !defined(MBEDTLS_SSL_CLI_C) || \
-    !defined(MBEDTLS_NET_C) || !defined(MBEDTLS_RSA_C) ||         \
-    !defined(MBEDTLS_CERTS_C) || !defined(MBEDTLS_PEM_PARSE_C) || \
-    !defined(MBEDTLS_CTR_DRBG_C) || !defined(MBEDTLS_X509_CRT_PARSE_C)
+#if !defined(MBEDTLS_BIGNUM_C) || !defined(MBEDTLS_ENTROPY_C) ||     \
+    !defined(MBEDTLS_SSL_TLS_C) || !defined(MBEDTLS_SSL_CLI_C) ||    \
+    !defined(MBEDTLS_NET_C) || !defined(MBEDTLS_RSA_C) ||            \
+    !defined(MBEDTLS_PEM_PARSE_C) || !defined(MBEDTLS_CTR_DRBG_C) || \
+    !defined(MBEDTLS_X509_CRT_PARSE_C)
 int main( void )
 {
     mbedtls_printf("MBEDTLS_BIGNUM_C and/or MBEDTLS_ENTROPY_C and/or "
@@ -59,7 +55,7 @@ int main( void )
 #include "mbedtls/entropy.h"
 #include "mbedtls/ctr_drbg.h"
 #include "mbedtls/error.h"
-#include "mbedtls/certs.h"
+#include "test/certs.h"

 #include <string.h>

@@ -216,13 +212,17 @@ int main( void )
     /* In real life, we probably want to bail out when ret != 0 */
     if( ( flags = mbedtls_ssl_get_verify_result( &ssl ) ) != 0 )
     {
+#if !defined(MBEDTLS_X509_REMOVE_INFO)
         char vrfy_buf[512];
+#endif

         mbedtls_printf( " failed\n" );

+#if !defined(MBEDTLS_X509_REMOVE_INFO)
         mbedtls_x509_crt_verify_info( vrfy_buf, sizeof( vrfy_buf ), "  ! ", flags );

         mbedtls_printf( "%s\n", vrfy_buf );
+#endif
     }
     else
         mbedtls_printf( " ok\n" );
@@ -305,14 +305,8 @@ exit:
     mbedtls_ctr_drbg_free( &ctr_drbg );
     mbedtls_entropy_free( &entropy );

-#if defined(_WIN32)
-    mbedtls_printf( "  + Press Enter to exit this program.\n" );
-    fflush( stdout ); getchar();
-#endif
-
     mbedtls_exit( exit_code );
 }
 #endif /* MBEDTLS_BIGNUM_C && MBEDTLS_ENTROPY_C && MBEDTLS_SSL_TLS_C &&
           MBEDTLS_SSL_CLI_C && MBEDTLS_NET_C && MBEDTLS_RSA_C &&
-          MBEDTLS_CERTS_C && MBEDTLS_PEM_PARSE_C && MBEDTLS_CTR_DRBG_C &&
-          MBEDTLS_X509_CRT_PARSE_C */
+          MBEDTLS_PEM_PARSE_C && MBEDTLS_CTR_DRBG_C && MBEDTLS_X509_CRT_PARSE_C */
(END)
```

Changes:
1. `mbedtls/config.h` -> `mbedtls/build_info.h`. Reflected in this PR.
2. `!defined(MBEDTLS_CERTS_C)` -> removed. Not relevant to this PR, because we switched to using our own certs some time ago, see https://github.com/gramineproject/gramine/pull/451
3. `mbedtls/certs.h` -> `test/certs.h`. Not relevant to this PR, same as above.
4. [nothing] -> add check for `MBEDTLS_X509_REMOVE_INFO`. Not reflected in this PR, because this code relies on the fact this macro is undefined (which is true for normal mbedTLS). See more info about this macro here: https://newreleases.io/project/github/Mbed-TLS/mbedtls/release/v3.0.0
5. `defined(_WIN32)` -> removed. Not relevant to this PR.

Summary: all is good. The APIs didn't change. No bugs fixed or anything. No now-deprecated APIs are used.
___
*[`CI-Examples/ra-tls-mbedtls/src/server.c` line 8 at r1](https://reviewable.io/reviews/gramineproject/gramine/796#-N7vTzn22wwYhS-FMAYR:-N82c5vc6d2xyhhWswh7:b1f7nx7) ([raw file](https://github.com/gramineproject/gramine/blob/72a00411ab0e8ad96843ebaa5799445edadecd6b/CI-Examples/ra-tls-mbedtls/src/server.c#L8)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Similar analysis as for the client.

I obtained the diff like this: `git diff --no-index ssl_server.2.26.0.c ssl_server.3.2.1.c` (the files were taken from corresponding mbedTLS sources).

```diff
diff --git a/ssl_server.2.26.0.c b/ssl_server.3.2.1.c
@@ -17,11 +17,7 @@
  *  limitations under the License.
  */

-#if !defined(MBEDTLS_CONFIG_FILE)
-#include "mbedtls/config.h"
-#else
-#include MBEDTLS_CONFIG_FILE
-#endif
+#include "mbedtls/build_info.h"

 #if defined(MBEDTLS_PLATFORM_C)
 #include "mbedtls/platform.h"
@@ -37,15 +33,14 @@
 #define MBEDTLS_EXIT_FAILURE    EXIT_FAILURE
 #endif

-#if !defined(MBEDTLS_BIGNUM_C) || !defined(MBEDTLS_CERTS_C) ||    \
-    !defined(MBEDTLS_ENTROPY_C) || !defined(MBEDTLS_SSL_TLS_C) || \
-    !defined(MBEDTLS_SSL_SRV_C) || !defined(MBEDTLS_NET_C) ||     \
-    !defined(MBEDTLS_RSA_C) || !defined(MBEDTLS_CTR_DRBG_C) ||    \
-    !defined(MBEDTLS_X509_CRT_PARSE_C) || !defined(MBEDTLS_FS_IO) || \
-    !defined(MBEDTLS_PEM_PARSE_C)
+#if !defined(MBEDTLS_BIGNUM_C) || !defined(MBEDTLS_PEM_PARSE_C) || \
+    !defined(MBEDTLS_ENTROPY_C) || !defined(MBEDTLS_SSL_TLS_C) ||  \
+    !defined(MBEDTLS_SSL_SRV_C) || !defined(MBEDTLS_NET_C) ||      \
+    !defined(MBEDTLS_RSA_C) || !defined(MBEDTLS_CTR_DRBG_C) ||     \
+    !defined(MBEDTLS_X509_CRT_PARSE_C) || !defined(MBEDTLS_FS_IO)
 int main( void )
 {
-    mbedtls_printf("MBEDTLS_BIGNUM_C and/or MBEDTLS_CERTS_C and/or MBEDTLS_ENTROPY_C "
+    mbedtls_printf("MBEDTLS_BIGNUM_C and/or MBEDTLS_ENTROPY_C "
            "and/or MBEDTLS_SSL_TLS_C and/or MBEDTLS_SSL_SRV_C and/or "
            "MBEDTLS_NET_C and/or MBEDTLS_RSA_C and/or "
            "MBEDTLS_CTR_DRBG_C and/or MBEDTLS_X509_CRT_PARSE_C "
@@ -63,12 +58,12 @@ int main( void )

 #include "mbedtls/entropy.h"
 #include "mbedtls/ctr_drbg.h"
-#include "mbedtls/certs.h"
 #include "mbedtls/x509.h"
 #include "mbedtls/ssl.h"
 #include "mbedtls/net_sockets.h"
 #include "mbedtls/error.h"
 #include "mbedtls/debug.h"
+#include "test/certs.h"

 #if defined(MBEDTLS_SSL_CACHE_C)
 #include "mbedtls/ssl_cache.h"
@@ -126,7 +121,23 @@ int main( void )
 #endif

     /*
-     * 1. Load the certificates and private RSA key
+     * 1. Seed the RNG
+     */
+    mbedtls_printf( "  . Seeding the random number generator..." );
+    fflush( stdout );
+
+    if( ( ret = mbedtls_ctr_drbg_seed( &ctr_drbg, mbedtls_entropy_func, &entropy,
+                               (const unsigned char *) pers,
+                               strlen( pers ) ) ) != 0 )
+    {
+      [...]

2022-07-28 10:02 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/796)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @kailun-qin, and @mkow)

___
*[`subprojects/packagefiles/mbedtls/include/mbedtls/config-pal.h` line 65 at r4](https://reviewable.io/reviews/gramineproject/gramine/796#-N82mhsn0LEMqRJWFkRw:-N83FDX04Hga2lZ0RMeU:bj27p55) ([raw file](https://github.com/gramineproject/gramine/blob/4ff84e1f5e9b6a7b4e012d5b347b85cf98f82ba4/subprojects/packagefiles/mbedtls/include/mbedtls/config-pal.h#L65)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I looked at mbedTLS v3.2.1 sources (in particular at `mbedtls_config.h` and `platform.h`), and I think we're overcomplicating things here. The way I understand what we need to do is like this:
```
...
#define MBEDTLS_SSL_SRV_C
#define MBEDTLS_SSL_TLS_C

#define MBEDTLS_PLATFORM_C
#define MBEDTLS_PLATFORM_NO_STD_FUNCTIONS
#define MBEDTLS_PLATFORM_MEMORY
MBEDTLS_PLATFORM_STD_MEM_HDR "api.h"
#define MBEDTLS_PLATFORM_CALLOC_MACRO   calloc
#define MBEDTLS_PLATFORM_FREE_MACRO     free
#define MBEDTLS_PLATFORM_SNPRINTF_MACRO snprintf
```

Note the `"api.h"` macro -- this guarantees that Gramine-specific `api.h` is included before mbedTLS starts finding `calloc`, `free` and `snrpintf`.

Please try it out. We need to make it right this time, it's some weird mess currently.
</blockquote></details>

This will at least need hardcode the "api.h" path here or patch the Makefile of mbedtls to find the header. Is this sth we would expect?


<!-- Sent from Reviewable.io -->

2022-07-28 11:43 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/796)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)

___
*[`subprojects/packagefiles/mbedtls/include/mbedtls/config-pal.h` line 65 at r4](https://reviewable.io/reviews/gramineproject/gramine/796#-N82mhsn0LEMqRJWFkRw:-N83bGCsBk1dxkl6ciJD:b5287uc) ([raw file](https://github.com/gramineproject/gramine/blob/4ff84e1f5e9b6a7b4e012d5b347b85cf98f82ba4/subprojects/packagefiles/mbedtls/include/mbedtls/config-pal.h#L65)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

This will at least need hardcode the "api.h" path here or patch the Makefile of mbedtls to find the header. Is this sth we would expect?
</blockquote></details>

Why would we require to hardcode `api.h` in mbedTLS? Isn't this header (and this PAL-specific version of mbedTLS) is *not* built separately, but rather built together with the PAL binary?

Or am I misrerembering how it works, and PAL-specific mbedTLS is still built (as a static library) separately from PAL?


<!-- Sent from Reviewable.io -->

2022-07-28 13:29 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/796)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @kailun-qin, and @mkow)

___
*[`subprojects/packagefiles/mbedtls/include/mbedtls/config-pal.h` line 65 at r4](https://reviewable.io/reviews/gramineproject/gramine/796#-N82mhsn0LEMqRJWFkRw:-N83zMjv4n2U7igTElNn:bvskgq1) ([raw file](https://github.com/gramineproject/gramine/blob/4ff84e1f5e9b6a7b4e012d5b347b85cf98f82ba4/subprojects/packagefiles/mbedtls/include/mbedtls/config-pal.h#L65)):*
> Or am I misrerembering how it works, and PAL-specific mbedTLS is still built (as a static library) separately from PAL?

Yes, I think so. Pls kindly see https://github.com/gramineproject/gramine/blob/master/subprojects/packagefiles/mbedtls/meson.build#L12-L14 and https://github.com/gramineproject/gramine/blob/master/subprojects/packagefiles/mbedtls/meson.build#L88.


<!-- Sent from Reviewable.io -->

2022-07-28 13:37 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/796)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @kailun-qin)

___
*[`CI-Examples/ra-tls-mbedtls/src/client.c` line 8 at r1](https://reviewable.io/reviews/gramineproject/gramine/796#-N7vTkPN3GHW2OigVu5B:-N840KMDBr57HzkEZKyV:bqjamnz) ([raw file](https://github.com/gramineproject/gramine/blob/72a00411ab0e8ad96843ebaa5799445edadecd6b/CI-Examples/ra-tls-mbedtls/src/client.c#L8)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ok, done. Let me dump all the details here.

I obtained the diff like this: `git diff --no-index ssl_client1.2.26.0.c ssl_client1.3.2.1.c` (the files were taken from corresponding mbedTLS sources).

```diff
diff --git a/ssl_client1.2.26.0.c b/ssl_client1.3.2.1.c
@@ -17,11 +17,7 @@
  *  limitations under the License.
  */

-#if !defined(MBEDTLS_CONFIG_FILE)
-#include "mbedtls/config.h"
-#else
-#include MBEDTLS_CONFIG_FILE
-#endif
+#include "mbedtls/build_info.h"

 #if defined(MBEDTLS_PLATFORM_C)
 #include "mbedtls/platform.h"
@@ -37,11 +33,11 @@
 #define MBEDTLS_EXIT_FAILURE    EXIT_FAILURE
 #endif /* MBEDTLS_PLATFORM_C */

-#if !defined(MBEDTLS_BIGNUM_C) || !defined(MBEDTLS_ENTROPY_C) ||  \
-    !defined(MBEDTLS_SSL_TLS_C) || !defined(MBEDTLS_SSL_CLI_C) || \
-    !defined(MBEDTLS_NET_C) || !defined(MBEDTLS_RSA_C) ||         \
-    !defined(MBEDTLS_CERTS_C) || !defined(MBEDTLS_PEM_PARSE_C) || \
-    !defined(MBEDTLS_CTR_DRBG_C) || !defined(MBEDTLS_X509_CRT_PARSE_C)
+#if !defined(MBEDTLS_BIGNUM_C) || !defined(MBEDTLS_ENTROPY_C) ||     \
+    !defined(MBEDTLS_SSL_TLS_C) || !defined(MBEDTLS_SSL_CLI_C) ||    \
+    !defined(MBEDTLS_NET_C) || !defined(MBEDTLS_RSA_C) ||            \
+    !defined(MBEDTLS_PEM_PARSE_C) || !defined(MBEDTLS_CTR_DRBG_C) || \
+    !defined(MBEDTLS_X509_CRT_PARSE_C)
 int main( void )
 {
     mbedtls_printf("MBEDTLS_BIGNUM_C and/or MBEDTLS_ENTROPY_C and/or "
@@ -59,7 +55,7 @@ int main( void )
 #include "mbedtls/entropy.h"
 #include "mbedtls/ctr_drbg.h"
 #include "mbedtls/error.h"
-#include "mbedtls/certs.h"
+#include "test/certs.h"

 #include <string.h>

@@ -216,13 +212,17 @@ int main( void )
     /* In real life, we probably want to bail out when ret != 0 */
     if( ( flags = mbedtls_ssl_get_verify_result( &ssl ) ) != 0 )
     {
+#if !defined(MBEDTLS_X509_REMOVE_INFO)
         char vrfy_buf[512];
+#endif

         mbedtls_printf( " failed\n" );

+#if !defined(MBEDTLS_X509_REMOVE_INFO)
         mbedtls_x509_crt_verify_info( vrfy_buf, sizeof( vrfy_buf ), "  ! ", flags );

         mbedtls_printf( "%s\n", vrfy_buf );
+#endif
     }
     else
         mbedtls_printf( " ok\n" );
@@ -305,14 +305,8 @@ exit:
     mbedtls_ctr_drbg_free( &ctr_drbg );
     mbedtls_entropy_free( &entropy );

-#if defined(_WIN32)
-    mbedtls_printf( "  + Press Enter to exit this program.\n" );
-    fflush( stdout ); getchar();
-#endif
-
     mbedtls_exit( exit_code );
 }
 #endif /* MBEDTLS_BIGNUM_C && MBEDTLS_ENTROPY_C && MBEDTLS_SSL_TLS_C &&
           MBEDTLS_SSL_CLI_C && MBEDTLS_NET_C && MBEDTLS_RSA_C &&
-          MBEDTLS_CERTS_C && MBEDTLS_PEM_PARSE_C && MBEDTLS_CTR_DRBG_C &&
-          MBEDTLS_X509_CRT_PARSE_C */
+          MBEDTLS_PEM_PARSE_C && MBEDTLS_CTR_DRBG_C && MBEDTLS_X509_CRT_PARSE_C */
(END)
```

Changes:
1. `mbedtls/config.h` -> `mbedtls/build_info.h`. Reflected in this PR.
2. `!defined(MBEDTLS_CERTS_C)` -> removed. Not relevant to this PR, because we switched to using our own certs some time ago, see https://github.com/gramineproject/gramine/pull/451
3. `mbedtls/certs.h` -> `test/certs.h`. Not relevant to this PR, same as above.
4. [nothing] -> add check for `MBEDTLS_X509_REMOVE_INFO`. Not reflected in this PR, because this code relies on the fact this macro is undefined (which is true for normal mbedTLS). See more info about this macro here: https://newreleases.io/project/github/Mbed-TLS/mbedtls/release/v3.0.0
5. `defined(_WIN32)` -> removed. Not relevant to this PR.

Summary: all is good. The APIs didn't change. No bugs fixed or anything. No now-deprecated APIs are used.
</blockquote></details>

Nice, thanks for the verification!
___
*[`CI-Examples/ra-tls-mbedtls/src/server.c` line 8 at r1](https://reviewable.io/reviews/gramineproject/gramine/796#-N7vTzn22wwYhS-FMAYR:-N840XyODnYILQ2F7Vq7:b-ucfknh) ([raw file](https://github.com/gramineproject/gramine/blob/72a00411ab0e8ad96843ebaa5799445edadecd6b/CI-Examples/ra-tls-mbedtls/src/server.c#L8)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Similar analysis as for the client.

I obtained the diff like this: `git diff --no-index ssl_server.2.26.0.c ssl_server.3.2.1.c` (the files were taken from corresponding mbedTLS sources).

```diff
diff --git a/ssl_server.2.26.0.c b/ssl_server.3.2.1.c
@@ -17,11 +17,7 @@
  *  limitations under the License.
  */

-#if !defined(MBEDTLS_CONFIG_FILE)
-#include "mbedtls/config.h"
-#else
-#include MBEDTLS_CONFIG_FILE
-#endif
+#include "mbedtls/build_info.h"

 #if defined(MBEDTLS_PLATFORM_C)
 #include "mbedtls/platform.h"
@@ -37,15 +33,14 @@
 #define MBEDTLS_EXIT_FAILURE    EXIT_FAILURE
 #endif

-#if !defined(MBEDTLS_BIGNUM_C) || !defined(MBEDTLS_CERTS_C) ||    \
-    !defined(MBEDTLS_ENTROPY_C) || !defined(MBEDTLS_SSL_TLS_C) || \
-    !defined(MBEDTLS_SSL_SRV_C) || !defined(MBEDTLS_NET_C) ||     \
-    !defined(MBEDTLS_RSA_C) || !defined(MBEDTLS_CTR_DRBG_C) ||    \
-    !defined(MBEDTLS_X509_CRT_PARSE_C) || !defined(MBEDTLS_FS_IO) || \
-    !defined(MBEDTLS_PEM_PARSE_C)
+#if !defined(MBEDTLS_BIGNUM_C) || !defined(MBEDTLS_PEM_PARSE_C) || \
+    !defined(MBEDTLS_ENTROPY_C) || !defined(MBEDTLS_SSL_TLS_C) ||  \
+    !defined(MBEDTLS_SSL_SRV_C) || !defined(MBEDTLS_NET_C) ||      \
+    !defined(MBEDTLS_RSA_C) || !defined(MBEDTLS_CTR_DRBG_C) ||     \
+    !defined(MBEDTLS_X509_CRT_PARSE_C) || !defined(MBEDTLS_FS_IO)
 int main( void )
 {
-    mbedtls_printf("MBEDTLS_BIGNUM_C and/or MBEDTLS_CERTS_C and/or MBEDTLS_ENTROPY_C "
+    mbedtls_printf("MBEDTLS_BIGNUM_C and/or MBEDTLS_ENTROPY_C "
            "and/or MBEDTLS_SSL_TLS_C and/or MBEDTLS_SSL_SRV_C and/or "
            "MBEDTLS_NET_C and/or MBEDTLS_RSA_C and/or "
            "MBEDTLS_CTR_DRBG_C and/or MBEDTLS_X509_CRT_PARSE_C "
@@ -63,12 +58,12 @@ int main( void )

 #include "mbedtls/entropy.h"
 #include "mbedtls/ctr_drbg.h"
-#include "mbedtls/certs.h"
 #include "mbedtls/x509.h"
 #include "mbedtls/ssl.h"
 #include "mbedtls/net_sockets.h"
 #include "mbedtls/error.h"
 #include "mbedtls/debug.h"
+#include "test/certs.h"

 #if defined(MBEDTLS_SSL_CACHE_C)
 #include "mbedtls/ssl_cache.h"
@@ -126,7 +121,23 @@ int main( void )
 #endif

     /*
-     * 1. Load the certificates and private RSA key
+     * 1. Seed the RNG
+     */
+    mbedtls_printf( "  . Seeding the random number generator..." );
+    fflush( stdout );
+
+    if( ( ret = mbedtls_ctr_drbg_seed( &ctr_drbg, mbedtls_entropy_func, &entropy,
+                               (const unsigned char *) pers,
+                               strlen( pers ) ) ) != 0 )
+    {
+        mbedtls_printf( " failed\n  ! mbedtls_ctr_drbg_seed returned %d\n", ret );
+        goto exit;
+    }
+
+    mbedtls_printf( " ok\n" );
+
+    /*
+     * 2. Load the certificates and private RSA key
      */
     mbedtls_printf( "\n  . Loading the server cert. and key..." );
     fflush( stdout );
@@ -153,7 +164,8 @@ int main( void )
     }

     ret =  mbedtls_pk_parse_key( &pkey, (const unsigned char *) mbedtls_test_srv_key,
-                         mbedtls_test_srv_key_len, NULL, 0 );
+                         mbedtls_test_srv_key_len, NULL, 0,
+                         mbedtls_ctr_drbg_random, &ctr_drbg );
     if( ret != 0 )
     {
         mbedtls_printf( " failed\n  !  mbedtls_pk_parse_ [...]

2022-07-28 13:50 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/796)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/796#-N82kTo37JT9h1uL1bkL:-N843gBW8kwyqkHtXW6o:b996h3o) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What is this file: https://github.com/gramineproject/gramine/blob/master/common/src/crypto/config.h ? Looks like this should be removed.
</blockquote></details>

@kailun-qin Can you check this file?

___
___
*[`subprojects/packagefiles/mbedtls/include/mbedtls/config-pal.h` line 65 at r4](https://reviewable.io/reviews/gramineproject/gramine/796#-N82mhsn0LEMqRJWFkRw:-N843-hb6XXQKlHc7vcX:bbrqucr) ([raw file](https://github.com/gramineproject/gramine/blob/4ff84e1f5e9b6a7b4e012d5b347b85cf98f82ba4/subprojects/packagefiles/mbedtls/include/mbedtls/config-pal.h#L65)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

> Or am I misrerembering how it works, and PAL-specific mbedTLS is still built (as a static library) separately from PAL?

Yes, I think so. Pls kindly see https://github.com/gramineproject/gramine/blob/master/subprojects/packagefiles/mbedtls/meson.build#L12-L14 and https://github.com/gramineproject/gramine/blob/master/subprojects/packagefiles/mbedtls/meson.build#L88.
</blockquote></details>

Thanks Kailun. I remembered it wrong. So we actually build a static lib, and thus we need to have these `calloc`, `free` and `snprintf` func/macro declarations.

This is a bit ugly, but I don't see a simple way around this.


<!-- Sent from Reviewable.io -->

2022-07-28 14:12 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/796)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/796#-N82kTo37JT9h1uL1bkL:-N846Fpz-lAS97pu2v9Z:bmhukav) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@kailun-qin Can you check this file?
</blockquote></details>

This file was previously used in https://github.com/gramineproject/gramine/blob/1c486c9213de9b162eee4f443440c448c3a4a6bb/common/src/Makefile#L97. However as we completely moved to Meson, this Makefile was removed by https://github.com/gramineproject/gramine/commit/3319b7a91827ae55683d24deb47dc5b38c7e1d7c so this was just a legacy not used anywhere today.

___


<!-- Sent from Reviewable.io -->

2022-07-28 15:09 UTC, dimakuv submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/796)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/796#-N82kTo37JT9h1uL1bkL:-N84LZ0h37OQjG1HvV2r:b8urdj8) (no related file):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

This file was previously used in https://github.com/gramineproject/gramine/blob/1c486c9213de9b162eee4f443440c448c3a4a6bb/common/src/Makefile#L97. However as we completely moved to Meson, this Makefile was removed by https://github.com/gramineproject/gramine/commit/3319b7a91827ae55683d24deb47dc5b38c7e1d7c so this was just a legacy not used anywhere today.
</blockquote></details>

Oh, sorry, I didn't notice that you already removed this file in this PR. Sorry for confusion. And I was wondering why you're telling me all this information without actually removing the file in the PR :)

___


<!-- Sent from Reviewable.io -->

2022-07-28 15:20 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/796)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/796#-N82kTo37JT9h1uL1bkL:-N84NxQYATVFpFieNwja:b-r3wlce) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Oh, sorry, I didn't notice that you already removed this file in this PR. Sorry for confusion. And I was wondering why you're telling me all this information without actually removing the file in the PR :)
</blockquote></details>

No worries :) Also to double confirm for myself.

___


<!-- Sent from Reviewable.io -->

2022-07-28 17:01 UTC, boryspoplawski requested changes
> Reviewed 11 of 16 files at r1, 2 of 3 files at r2, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/796)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

___
*[`CI-Examples/ra-tls-mbedtls/src/server.c` line 218 at r4](https://reviewable.io/reviews/gramineproject/gramine/796#-N84bbQlEG6baoqhWUZA:-N84bbQlEG6baoqhWUZB:bdbh9nw) ([raw file](https://github.com/gramineproject/gramine/blob/4ff84e1f5e9b6a7b4e012d5b347b85cf98f82ba4/CI-Examples/ra-tls-mbedtls/src/server.c#L218)):*
> ```C
>         }
> 
>         ret = mbedtls_pk_parse_keyfile(&pkey, SRV_KEY_PATH, NULL, mbedtls_ctr_drbg_random,
> ```

Why did you remove the name comment (`/*password=*/`)?



_Code quote:_
```C
 NULL,
```
___
*[`common/src/crypto/adapters/mbedtls_adapter.c` line 464 at r4](https://reviewable.io/reviews/gramineproject/gramine/796#-N84caicCbJOemVIf3Jt:-N84caid-L1QSLu9sGfl:bxvo0fi) ([raw file](https://github.com/gramineproject/gramine/blob/4ff84e1f5e9b6a7b4e012d5b347b85cf98f82ba4/common/src/crypto/adapters/mbedtls_adapter.c#L464)):*
> ```C
>         return -PAL_ERROR_INVAL;
> 
>     int ret = mbedtls_dhm_make_public(context, (int)mbedtls_dhm_get_len(context), public,
> ```

Why do we need this cast?



_Code quote:_
```C
(int)
```
___
*[`subprojects/packagefiles/mbedtls/include/mbedtls/config-pal.h` line 39 at r4](https://reviewable.io/reviews/gramineproject/gramine/796#-N84e9U3A-fDWTTuojaG:-N84e9U3A-fDWTTuojaH:bdd97ht) ([raw file](https://github.com/gramineproject/gramine/blob/4ff84e1f5e9b6a7b4e012d5b347b85cf98f82ba4/subprojects/packagefiles/mbedtls/include/mbedtls/config-pal.h#L39)):*
> ```objc
> #define MBEDTLS_PLATFORM_C
> #define MBEDTLS_RSA_C
> #define MBEDTLS_SHA224_C
> ```

Why do we now need sha224?
___
*[`subprojects/packagefiles/mbedtls/include/mbedtls/config-pal.h` line 57 at r4](https://reviewable.io/reviews/gramineproject/gramine/796#-N84iH_k11D7kNZf0fc0:-N84iH_k11D7kNZf0fc1:bgrvmbu) ([raw file](https://github.com/gramineproject/gramine/blob/4ff84e1f5e9b6a7b4e012d5b347b85cf98f82ba4/subprojects/packagefiles/mbedtls/include/mbedtls/config-pal.h#L57)):*
> ```objc
> void* calloc(size_t num, size_t size);
> void free(void*);
> int snprintf(char* buf, size_t buf_size, const char* fmt, ...)
> ```

So how did this work before (without this declaration)?
___
*[`subprojects/packagefiles/mbedtls/include/mbedtls/config-pal.h` line 63 at r4](https://reviewable.io/reviews/gramineproject/gramine/796#-N84kDUm2BuSEVa1dxYy:-N84kDUm2BuSEVa1dxYz:b-2s6gb4) ([raw file](https://github.com/gramineproject/gramine/blob/4ff84e1f5e9b6a7b4e012d5b347b85cf98f82ba4/subprojects/packagefiles/mbedtls/include/mbedtls/config-pal.h#L63)):*
> ```objc
> #define MBEDTLS_PLATFORM_MEMORY
> #define MBEDTLS_PLATFORM_SNPRINTF_ALT
> #define MBEDTLS_PLATFORM_STD_CALLOC   calloc
> ```

Actually, what is even the point of these macros? Afaik this just substitutes `calloc` for `calloc`, which is pointless?


<!-- Sent from Reviewable.io -->

2022-07-29 02:35 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/796)* status: 16 of 17 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[`CI-Examples/ra-tls-mbedtls/src/server.c` line 218 at r4](https://reviewable.io/reviews/gramineproject/gramine/796#-N84bbQlEG6baoqhWUZA:-N86h9YuAdagLKrD0X_M:bm6agoa) ([raw file](https://github.com/gramineproject/gramine/blob/4ff84e1f5e9b6a7b4e012d5b347b85cf98f82ba4/CI-Examples/ra-tls-mbedtls/src/server.c#L218)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why did you remove the name comment (`/*password=*/`)?
</blockquote></details>

I was intending to align w/ the `mbedtls_pk_parse_key()`. Updated both.
___
*[`common/src/crypto/adapters/mbedtls_adapter.c` line 464 at r4](https://reviewable.io/reviews/gramineproject/gramine/796#-N84caicCbJOemVIf3Jt:-N86hLkv1jWvHyj3PXHO:b-g9ihe9) ([raw file](https://github.com/gramineproject/gramine/blob/4ff84e1f5e9b6a7b4e012d5b347b85cf98f82ba4/common/src/crypto/adapters/mbedtls_adapter.c#L464)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why do we need this cast?
</blockquote></details>

`mbedtls_dhm_get_len()` returns `size_t` (https://github.com/Mbed-TLS/mbedtls/blob/3304f253d7aa4b5b18e772c455b2113f7af29ca5/include/mbedtls/dhm.h#L319) while `mbedtls_dhm_make_public()` takes an `int` (https://github.com/Mbed-TLS/mbedtls/blob/3304f253d7aa4b5b18e772c455b2113f7af29ca5/include/mbedtls/dhm.h#L265). I think it's needed?
___
*[`subprojects/packagefiles/mbedtls/include/mbedtls/config-pal.h` line 39 at r4](https://reviewable.io/reviews/gramineproject/gramine/796#-N84e9U3A-fDWTTuojaG:-N86iEQABfKb9YB9ws5g:bnsz2er) ([raw file](https://github.com/gramineproject/gramine/blob/4ff84e1f5e9b6a7b4e012d5b347b85cf98f82ba4/subprojects/packagefiles/mbedtls/include/mbedtls/config-pal.h#L39)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why do we now need sha224?
</blockquote></details>

This is a prerequisite of sha256 (https://github.com/Mbed-TLS/mbedtls/blob/v3.2.1/include/mbedtls/check_config.h#L711) for 3.x. In 2.26.0, there is no such check (well, actually we didn't even leverage `check_config.h` actually, see below).
___
*[`subprojects/packagefiles/mbedtls/include/mbedtls/config-pal.h` line 57 at r4](https://reviewable.io/reviews/gramineproject/gramine/796#-N84iH_k11D7kNZf0fc0:-N86k2cfCtYCnP7v2juj:b-7zhdfs) ([raw file](https://github.com/gramineproject/gramine/blob/4ff84e1f5e9b6a7b4e012d5b347b85cf98f82ba4/subprojects/packagefiles/mbedtls/include/mbedtls/config-pal.h#L57)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

So how did this work before (without this declaration)?
</blockquote></details>

We did not leverage/use `check_config.h` of mbedtls before (not explicitly include `check_config.h`), i.e., no checks on the config dependencies.

However, since 3.x, `config.h` was split into `build_info.h` and `mbedtls_config.h` where it's not needed to include `check_config.h` any more (see https://github.com/Mbed-TLS/mbedtls/blob/v3.2.1/docs/3.0-migration-guide.md#introduce-a-level-of-indirection-and-versioning-in-the-config-files) as it's included in `build_info.h` anyway (https://github.com/Mbed-TLS/mbedtls/blob/v3.2.1/include/mbedtls/build_info.h#L84).
`
Thus before, we didn't define `MBEDTLS_PLATFORM_SNPRINTF_ALT` (and it was not checked). But now`MBEDTLS_PLATFORM_SNPRINTF_ALT` is defined, which will eventually goes to the expansion of `mbedtls_snprintf` -> `MBEDTLS_PLATFORM_STD_SNPRINTF` -> `snprintf` thus it won't work w/o this (no declaration).
___
*[`subprojects/packagefiles/mbedtls/include/mbedtls/config-pal.h` line 63 at r4](https://reviewable.io/reviews/gramineproject/gramine/796#-N84kDUm2BuSEVa1dxYy:-N86j0MoCBsITg_DQhHM:b-ljug5r) ([raw file](https://github.com/gramineproject/gramine/blob/4ff84e1f5e9b6a7b4e012d5b347b85cf98f82ba4/subprojects/packagefiles/mbedtls/include/mbedtls/config-pal.h#L63)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Actually, what is even the point of these macros? Afaik this just substitutes `calloc` for `calloc`, which is pointless?
</blockquote></details>

These are needed to avoid implicit declaration warnings on `mbedtls_calloc` and `mbedtls_xxx` expansions. This is also a general practice when using together w/ `MBEDTLS_PLATFORM_NO_STD_FUNCTIONS` (see https://github.com/Mbed-TLS/mbedtls/blob/v3.2.1/include/mbedtls/mbedtls_config.h#L193-L196).


<!-- Sent from Reviewable.io -->

2022-07-29 06:46 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/796)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[`common/src/crypto/adapters/mbedtls_adapter.c` line 464 at r4](https://reviewable.io/reviews/gramineproject/gramine/796#-N84caicCbJOemVIf3Jt:-N87g3aYBYZN6NhdnM8a:b-qm9yae) ([raw file](https://github.com/gramineproject/gramine/blob/4ff84e1f5e9b6a7b4e012d5b347b85cf98f82ba4/common/src/crypto/adapters/mbedtls_adapter.c#L464)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

`mbedtls_dhm_get_len()` returns `size_t` (https://github.com/Mbed-TLS/mbedtls/blob/3304f253d7aa4b5b18e772c455b2113f7af29ca5/include/mbedtls/dhm.h#L319) while `mbedtls_dhm_make_public()` takes an `int` (https://github.com/Mbed-TLS/mbedtls/blob/3304f253d7aa4b5b18e772c455b2113f7af29ca5/include/mbedtls/dhm.h#L265). I think it's needed?
</blockquote></details>

Indeed. mbedTLS is famous for its incompatible types :)
___
*[`subprojects/packagefiles/mbedtls/include/mbedtls/config-pal.h` line 63 at r4](https://reviewable.io/reviews/gramineproject/gramine/796#-N84kDUm2BuSEVa1dxYy:-N87gUaq7DLDIebr3ZYe:b5qvtv6) ([raw file](https://github.com/gramineproject/gramine/blob/4ff84e1f5e9b6a7b4e012d5b347b85cf98f82ba4/subprojects/packagefiles/mbedtls/include/mbedtls/config-pal.h#L63)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

These are needed to avoid implicit declaration warnings on `mbedtls_calloc` and `mbedtls_xxx` expansions. This is also a general practice when using together w/ `MBEDTLS_PLATFORM_NO_STD_FUNCTIONS` (see https://github.com/Mbed-TLS/mbedtls/blob/v3.2.1/include/mbedtls/mbedtls_config.h#L193-L196).
</blockquote></details>

+1 to what @kailun-qin said. mbedTLS requires these macros, otherwise it may not use any functions at all and wait for the user to register them via `platform_set_xxx()` at runtime.

See for example this remark: https://github.com/Mbed-TLS/mbedtls/blob/v3.2.1/include/mbedtls/mbedtls_config.h#L171-L174

Btw, when I was investigating this yesterday, I couldn't understand the difference between `MBEDTLS_PLATFORM_STD_XXX` and `MBEDTLS_PLATFORM_XXX_MACRO`. For example:
- https://github.com/Mbed-TLS/mbedtls/blob/869298bffeea13b205343361b7a7daf2b210e33d/include/mbedtls/mbedtls_config.h#L3330
- https://github.com/Mbed-TLS/mbedtls/blob/869298bffeea13b205343361b7a7daf2b210e33d/include/mbedtls/mbedtls_config.h#L3347

These two macros for `calloc` seem to be exactly the same, and I have no idea why there are two different macros for the same... I also didn't find any explanation by googling.


<!-- Sent from Reviewable.io -->

2022-07-29 08:31 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/796)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[`subprojects/packagefiles/mbedtls/include/mbedtls/config-pal.h` line 63 at r4](https://reviewable.io/reviews/gramineproject/gramine/796#-N84kDUm2BuSEVa1dxYy:-N87x00BEjBdCBs94cdt:b-8m1n98) ([raw file](https://github.com/gramineproject/gramine/blob/4ff84e1f5e9b6a7b4e012d5b347b85cf98f82ba4/subprojects/packagefiles/mbedtls/include/mbedtls/config-pal.h#L63)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

+1 to what @kailun-qin said. mbedTLS requires these macros, otherwise it may not use any functions at all and wait for the user to register them via `platform_set_xxx()` at runtime.

See for example this remark: https://github.com/Mbed-TLS/mbedtls/blob/v3.2.1/include/mbedtls/mbedtls_config.h#L171-L174

Btw, when I was investigating this yesterday, I couldn't understand the difference between `MBEDTLS_PLATFORM_STD_XXX` and `MBEDTLS_PLATFORM_XXX_MACRO`. For example:
- https://github.com/Mbed-TLS/mbedtls/blob/869298bffeea13b205343361b7a7daf2b210e33d/include/mbedtls/mbedtls_config.h#L3330
- https://github.com/Mbed-TLS/mbedtls/blob/869298bffeea13b205343361b7a7daf2b210e33d/include/mbedtls/mbedtls_config.h#L3347

These two macros for `calloc` seem to be exactly the same, and I have no idea why there are two different macros for the same... I also didn't find any explanation by googling.
</blockquote></details>

These two macros are both for providing alternatives at compile time. They should not be specified simultaneously (checked by https://github.com/Mbed-TLS/mbedtls/blob/v3.2.1/include/mbedtls/check_config.h#L467).

However, there will be a precedence defined here: https://github.com/Mbed-TLS/mbedtls/blob/v3.2.1/library/platform.c#L28-L78.
- If `MBEDTLS_PLATFORM_CALLOC_MACRO` is specified, `mbedtls_calloc()` will be set to it (https://github.com/Mbed-TLS/mbedtls/blob/v3.2.1/include/mbedtls/platform.h#L136) and it will take precedence over all the others (`MBEDTLS_PLATFORM_STD_CALLOC` and the runtime configs).
- If not, depending on whether `MBEDTLS_PLATFORM_STD_CALLOC` is set, `mbedtls_calloc()` will be set to `MBEDTLS_PLATFORM_STD_CALLOC` or a func pointer of a dummy impl. Also, users seems still able to call `mbedtls_platform_set_calloc_free()` for runtime config/override.

So when (either is) specified, `MBEDTLS_PLATFORM_CALLOC_MACRO` and `MBEDTLS_PLATFORM_STD_CALLOC` function identically, except that using `MBEDTLS_PLATFORM_CALLOC_MACRO` will not even allow users to provide alternatives at runtime. When not specified, a dummy impl. will be set and it will rely on the runtime config to set the alternative.


<!-- Sent from Reviewable.io -->

2022-07-29 08:55 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/796)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[`subprojects/packagefiles/mbedtls/include/mbedtls/config-pal.h` line 63 at r4](https://reviewable.io/reviews/gramineproject/gramine/796#-N84kDUm2BuSEVa1dxYy:-N889Sct55rpSiu58yOn:b-bzopdk) ([raw file](https://github.com/gramineproject/gramine/blob/4ff84e1f5e9b6a7b4e012d5b347b85cf98f82ba4/subprojects/packagefiles/mbedtls/include/mbedtls/config-pal.h#L63)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

These two macros are both for providing alternatives at compile time. They should not be specified simultaneously (checked by https://github.com/Mbed-TLS/mbedtls/blob/v3.2.1/include/mbedtls/check_config.h#L467).

However, there will be a precedence defined here: https://github.com/Mbed-TLS/mbedtls/blob/v3.2.1/library/platform.c#L28-L78.
- If `MBEDTLS_PLATFORM_CALLOC_MACRO` is specified, `mbedtls_calloc()` will be set to it (https://github.com/Mbed-TLS/mbedtls/blob/v3.2.1/include/mbedtls/platform.h#L136) and it will take precedence over all the others (`MBEDTLS_PLATFORM_STD_CALLOC` and the runtime configs).
- If not, depending on whether `MBEDTLS_PLATFORM_STD_CALLOC` is set, `mbedtls_calloc()` will be set to `MBEDTLS_PLATFORM_STD_CALLOC` or a func pointer of a dummy impl. Also, users seems still able to call `mbedtls_platform_set_calloc_free()` for runtime config/override.

So when (either is) specified, `MBEDTLS_PLATFORM_CALLOC_MACRO` and `MBEDTLS_PLATFORM_STD_CALLOC` function identically, except that using `MBEDTLS_PLATFORM_CALLOC_MACRO` will not even allow users to provide alternatives at runtime. When not specified, a dummy impl. will be set and it will rely on the runtime config to set the alternative.
</blockquote></details>

Thanks @kailun-qin for the awesome explanation! (Yeah, I was too lazy to look at the `.c` files; I hoped that the mbedTLS documentation and comments are enough.)


<!-- Sent from Reviewable.io -->

2022-07-29 12:18 UTC, boryspoplawski requested changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/796)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @kailun-qin)

___
*[`common/src/crypto/adapters/mbedtls_adapter.c` line 464 at r4](https://reviewable.io/reviews/gramineproject/gramine/796#-N84caicCbJOemVIf3Jt:-N88oVWr5Ef6U2IsWrXB:bos1ze5) ([raw file](https://github.com/gramineproject/gramine/blob/4ff84e1f5e9b6a7b4e012d5b347b85cf98f82ba4/common/src/crypto/adapters/mbedtls_adapter.c#L464)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Indeed. mbedTLS is famous for its incompatible types :)
</blockquote></details>

No, it's implicitly cast and not needed
___
*[`subprojects/packagefiles/mbedtls/include/mbedtls/config-pal.h` line 39 at r4](https://reviewable.io/reviews/gramineproject/gramine/796#-N84e9U3A-fDWTTuojaG:-N88ozH5-xjojUn--hkN:bq3u6kc) ([raw file](https://github.com/gramineproject/gramine/blob/4ff84e1f5e9b6a7b4e012d5b347b85cf98f82ba4/subprojects/packagefiles/mbedtls/include/mbedtls/config-pal.h#L39)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

This is a prerequisite of sha256 (https://github.com/Mbed-TLS/mbedtls/blob/v3.2.1/include/mbedtls/check_config.h#L711) for 3.x. In 2.26.0, there is no such check (well, actually we didn't even leverage `check_config.h` actually, see below).
</blockquote></details>

Huh, weird. Any idea why you must include both?
(unblocked)
___
*[`subprojects/packagefiles/mbedtls/include/mbedtls/config-pal.h` line 57 at r4](https://reviewable.io/reviews/gramineproject/gramine/796#-N84iH_k11D7kNZf0fc0:-N88pUhK-ka5MZqRf4jM:b-e5lxh4) ([raw file](https://github.com/gramineproject/gramine/blob/4ff84e1f5e9b6a7b4e012d5b347b85cf98f82ba4/subprojects/packagefiles/mbedtls/include/mbedtls/config-pal.h#L57)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

We did not leverage/use `check_config.h` of mbedtls before (not explicitly include `check_config.h`), i.e., no checks on the config dependencies.

However, since 3.x, `config.h` was split into `build_info.h` and `mbedtls_config.h` where it's not needed to include `check_config.h` any more (see https://github.com/Mbed-TLS/mbedtls/blob/v3.2.1/docs/3.0-migration-guide.md#introduce-a-level-of-indirection-and-versioning-in-the-config-files) as it's included in `build_info.h` anyway (https://github.com/Mbed-TLS/mbedtls/blob/v3.2.1/include/mbedtls/build_info.h#L84).
`
Thus before, we didn't define `MBEDTLS_PLATFORM_SNPRINTF_ALT` (and it was not checked). But now`MBEDTLS_PLATFORM_SNPRINTF_ALT` is defined, which will eventually goes to the expansion of `mbedtls_snprintf` -> `MBEDTLS_PLATFORM_STD_SNPRINTF` -> `snprintf` thus it won't work w/o this (no declaration).
</blockquote></details>

Okey, so what's wrong with removing both `SNPRINTF` macros from here? IIUC this was the effect of the missing declaration before, wasn't it?
___
*[`subprojects/packagefiles/mbedtls/include/mbedtls/config-pal.h` line 63 at r4](https://reviewable.io/reviews/gramineproject/gramine/796#-N84kDUm2BuSEVa1dxYy:-N88q7NU5DcSghy3wUV_:b-lam6j1) ([raw file](https://github.com/gramineproject/gramine/blob/4ff84e1f5e9b6a7b4e012d5b347b85cf98f82ba4/subprojects/packagefiles/mbedtls/include/mbedtls/config-pal.h#L63)):*
> +1 to what @kailun-qin said. mbedTLS requires these macros, otherwise it may not use any functions at all and wait for the user to register them via platform_set_xxx() at runtime.
> See for example this remark: https://github.com/Mbed-TLS/mbedtls/blob/v3.2.1/include/mbedtls/mbedtls_config.h#L171-L174


But why cannot we ommit them alltogether? It doesn't make sense, we are just redefining from `free` to `free`, what's the point?

Update: I've verified, this patch works:
```
diff --git a/subprojects/packagefiles/mbedtls/include/mbedtls/config-pal.h b/subprojects/packagefiles/mbedtls/include/mbedtls/config-pal.h
index 3966bb36..7e77ec9d 100644
--- a/subprojects/packagefiles/mbedtls/include/mbedtls/config-pal.h
+++ b/subprojects/packagefiles/mbedtls/include/mbedtls/config-pal.h
@@ -44,22 +44,3 @@
 #define MBEDTLS_SSL_PROTO_TLS1_2
 #define MBEDTLS_SSL_SRV_C
 #define MBEDTLS_SSL_TLS_C
-
-#define MBEDTLS_PLATFORM_NO_STD_FUNCTIONS
-
-#include <limits.h>
-#include <stddef.h>
-
-/* Prevent conflict with `api_fortified.h` which might redefine `snprintf` as macro */
-#ifndef GRAMINE_API_HEADER_USED
-void* calloc(size_t num, size_t size);
-void free(void*);
-int snprintf(char* buf, size_t buf_size, const char* fmt, ...)
-    __attribute__((format(printf, 3, 4)));
-#endif
-
-#define MBEDTLS_PLATFORM_MEMORY
-#define MBEDTLS_PLATFORM_SNPRINTF_ALT
-#define MBEDTLS_PLATFORM_STD_CALLOC   calloc
-#define MBEDTLS_PLATFORM_STD_FREE     free
-#define MBEDTLS_PLATFORM_STD_SNPRINTF snprintf
```


<!-- Sent from Reviewable.io -->

2022-07-29 14:37 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/796)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @kailun-qin)

___
*[`common/src/crypto/adapters/mbedtls_adapter.c` line 464 at r4](https://reviewable.io/reviews/gramineproject/gramine/796#-N84caicCbJOemVIf3Jt:-N89JikD5A6cfplu3ci3:bgjbl82) ([raw file](https://github.com/gramineproject/gramine/blob/4ff84e1f5e9b6a7b4e012d5b347b85cf98f82ba4/common/src/crypto/adapters/mbedtls_adapter.c#L464)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

No, it's implicitly cast and not needed
</blockquote></details>

Here, we'd like to pass the value in `size_t` to a function that takes an `int` - which might be an unsafe type conversion? So I guess it would be better we explicitly cast here (not C expert... but for Rust it shouldn't compile w/o explicit cast)?
___
*[`subprojects/packagefiles/mbedtls/include/mbedtls/config-pal.h` line 39 at r4](https://reviewable.io/reviews/gramineproject/gramine/796#-N84e9U3A-fDWTTuojaG:-N89LBNyDSqeFprP14qv:b-6o74tx) ([raw file](https://github.com/gramineproject/gramine/blob/4ff84e1f5e9b6a7b4e012d5b347b85cf98f82ba4/subprojects/packagefiles/mbedtls/include/mbedtls/config-pal.h#L39)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Huh, weird. Any idea why you must include both?
(unblocked)
</blockquote></details>

Previously, SHA-224 and SHA-256 were combined in one option that is `MBEDTLS_SHA256_C`. mbedTLS thus made a separation via https://github.com/Mbed-TLS/mbedtls/commit/e3c48b4a883e8812214a4c57c319d005f34b7ccc#diff-f781da22676e488056bc0453f79e0e4dee75eb68433a7ae66e257d17e50cfd89. However, as these options are still dependant on each other, this separation is just an intermediate step. Cryptographically speaking, SHA-224 requires SHA-256 is kind of reasonable as it's basically SHA-256 with a different IV and with 32 of the output bits thrown away.
___
*[`subprojects/packagefiles/mbedtls/include/mbedtls/config-pal.h` line 63 at r4](https://reviewable.io/reviews/gramineproject/gramine/796#-N84kDUm2BuSEVa1dxYy:-N89NQeVE5xi6jLcPt1_:b-jn859x) ([raw file](https://github.com/gramineproject/gramine/blob/4ff84e1f5e9b6a7b4e012d5b347b85cf98f82ba4/subprojects/packagefiles/mbedtls/include/mbedtls/config-pal.h#L63)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

> +1 to what @kailun-qin said. mbedTLS requires these macros, otherwise it may not use any functions at all and wait for the user to register them via platform_set_xxx() at runtime.
> See for example this remark: https://github.com/Mbed-TLS/mbedtls/blob/v3.2.1/include/mbedtls/mbedtls_config.h#L171-L174


But why cannot we ommit them alltogether? It doesn't make sense, we are just redefining from `free` to `free`, what's the point?

Update: I've verified, this patch works:
```
diff --git a/subprojects/packagefiles/mbedtls/include/mbedtls/config-pal.h b/subprojects/packagefiles/mbedtls/include/mbedtls/config-pal.h
index 3966bb36..7e77ec9d 100644
--- a/subprojects/packagefiles/mbedtls/include/mbedtls/config-pal.h
+++ b/subprojects/packagefiles/mbedtls/include/mbedtls/config-pal.h
@@ -44,22 +44,3 @@
 #define MBEDTLS_SSL_PROTO_TLS1_2
 #define MBEDTLS_SSL_SRV_C
 #define MBEDTLS_SSL_TLS_C
-
-#define MBEDTLS_PLATFORM_NO_STD_FUNCTIONS
-
-#include <limits.h>
-#include <stddef.h>
-
-/* Prevent conflict with `api_fortified.h` which might redefine `snprintf` as macro */
-#ifndef GRAMINE_API_HEADER_USED
-void* calloc(size_t num, size_t size);
-void free(void*);
-int snprintf(char* buf, size_t buf_size, const char* fmt, ...)
-    __attribute__((format(printf, 3, 4)));
-#endif
-
-#define MBEDTLS_PLATFORM_MEMORY
-#define MBEDTLS_PLATFORM_SNPRINTF_ALT
-#define MBEDTLS_PLATFORM_STD_CALLOC   calloc
-#define MBEDTLS_PLATFORM_STD_FREE     free
-#define MBEDTLS_PLATFORM_STD_SNPRINTF snprintf
```
</blockquote></details>

Thanks @boryspoplawski. Yes, I know this would work. But this uses std functions - is this sth we expect?


<!-- Sent from Reviewable.io -->

2022-07-29 15:01 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/796)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @kailun-qin)

___
*[`common/src/crypto/adapters/mbedtls_adapter.c` line 464 at r4](https://reviewable.io/reviews/gramineproject/gramine/796#-N84caicCbJOemVIf3Jt:-N89RZ233iuZO_tX045d:bmj60km) ([raw file](https://github.com/gramineproject/gramine/blob/4ff84e1f5e9b6a7b4e012d5b347b85cf98f82ba4/common/src/crypto/adapters/mbedtls_adapter.c#L464)):*
> Here, we'd like to pass the value in size_t to a function that takes an int

Yes, I know

> which might be an unsafe type conversion?

Explicit cast doesn't change anything and integers are implicitly converted
___
*[`subprojects/packagefiles/mbedtls/include/mbedtls/config-pal.h` line 39 at r4](https://reviewable.io/reviews/gramineproject/gramine/796#-N84e9U3A-fDWTTuojaG:-N89S6Cx6hf2-Kwpz3zA:b-6sjmsl) ([raw file](https://github.com/gramineproject/gramine/blob/4ff84e1f5e9b6a7b4e012d5b347b85cf98f82ba4/subprojects/packagefiles/mbedtls/include/mbedtls/config-pal.h#L39)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Previously, SHA-224 and SHA-256 were combined in one option that is `MBEDTLS_SHA256_C`. mbedTLS thus made a separation via https://github.com/Mbed-TLS/mbedtls/commit/e3c48b4a883e8812214a4c57c319d005f34b7ccc#diff-f781da22676e488056bc0453f79e0e4dee75eb68433a7ae66e257d17e50cfd89. However, as these options are still dependant on each other, this separation is just an intermediate step. Cryptographically speaking, SHA-224 requires SHA-256 is kind of reasonable as it's basically SHA-256 with a different IV and with 32 of the output bits thrown away.
</blockquote></details>

Sure, I just don't understand why sha256 requires sha224 (other way makes sense)
___
*[`subprojects/packagefiles/mbedtls/include/mbedtls/config-pal.h` line 63 at r4](https://reviewable.io/reviews/gramineproject/gramine/796#-N84kDUm2BuSEVa1dxYy:-N89SCyY8B1bDAB-32U-:b1roofs) ([raw file](https://github.com/gramineproject/gramine/blob/4ff84e1f5e9b6a7b4e012d5b347b85cf98f82ba4/subprojects/packagefiles/mbedtls/include/mbedtls/config-pal.h#L63)):*
And if you `define MBEDTLS_PLATFORM_STD_CALLOC calloc` you think what happens? Exactly the same thing as if you do not define it, because it's default. It doesn't affect what function is used, because here we literally just tell it to use `calloc`.

> But this uses std functions 

So? If you define these macros it uses them as well. We provide them (some of them, like `calloc`, `free`, etc) in PAL.


<!-- Sent from Reviewable.io -->

2022-07-29 16:15 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/796)* status: 14 of 17 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @kailun-qin, and @mkow)

___
*[`common/src/crypto/adapters/mbedtls_adapter.c` line 464 at r4](https://reviewable.io/reviews/gramineproject/gramine/796#-N84caicCbJOemVIf3Jt:-N89hlxqEdi2aGyLnTAc:b-f099h) ([raw file](https://github.com/gramineproject/gramine/blob/4ff84e1f5e9b6a7b4e012d5b347b85cf98f82ba4/common/src/crypto/adapters/mbedtls_adapter.c#L464)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

> Here, we'd like to pass the value in size_t to a function that takes an int

Yes, I know

> which might be an unsafe type conversion?

Explicit cast doesn't change anything and integers are implicitly converted
</blockquote></details>

Removed the cast.
___
*[`subprojects/packagefiles/mbedtls/include/mbedtls/config-pal.h` line 39 at r4](https://reviewable.io/reviews/gramineproject/gramine/796#-N84e9U3A-fDWTTuojaG:-N89hoyz8ekUYMdXd48o:b-cepxd) ([raw file](https://github.com/gramineproject/gramine/blob/4ff84e1f5e9b6a7b4e012d5b347b85cf98f82ba4/subprojects/packagefiles/mbedtls/include/mbedtls/config-pal.h#L39)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Sure, I just don't understand why sha256 requires sha224 (other way makes sense)
</blockquote></details>

Yes, it's indeed confusing (probably a tight coupling at this moment).
___
*[`subprojects/packagefiles/mbedtls/include/mbedtls/config-pal.h` line 63 at r4](https://reviewable.io/reviews/gramineproject/gramine/796#-N84kDUm2BuSEVa1dxYy:-N89i5cS3HpYxXH8aWDP:b-o5py03) ([raw file](https://github.com/gramineproject/gramine/blob/4ff84e1f5e9b6a7b4e012d5b347b85cf98f82ba4/subprojects/packagefiles/mbedtls/include/mbedtls/config-pal.h#L63)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

And if you `define MBEDTLS_PLATFORM_STD_CALLOC calloc` you think what happens? Exactly the same thing as if you do not define it, because it's default. It doesn't affect what function is used, because here we literally just tell it to use `calloc`.

> But this uses std functions 

So? If you define these macros it uses them as well. We provide them (some of them, like `calloc`, `free`, etc) in PAL.
</blockquote></details>

Sorry for the confusions, I missed one word - I intended to say this would use default std function (declarations). Checked and it looks the same, so it seems make sense to just omit them altogether.


<!-- Sent from Reviewable.io -->

2022-07-29 17:00 UTC, boryspoplawski requested changes
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/796)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

___
*[`subprojects/packagefiles/mbedtls/include/mbedtls/config-pal.h` line 63 at r4](https://reviewable.io/reviews/gramineproject/gramine/796#-N84kDUm2BuSEVa1dxYy:-N89rork4mH-qkZZ9CYL:b30sn8q) ([raw file](https://github.com/gramineproject/gramine/blob/4ff84e1f5e9b6a7b4e012d5b347b85cf98f82ba4/subprojects/packagefiles/mbedtls/include/mbedtls/config-pal.h#L63)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Sorry for the confusions, I missed one word - I intended to say this would use default std function (declarations). Checked and it looks the same, so it seems make sense to just omit them altogether.
</blockquote></details>

Yeah, I think this feature is intended for cases like `define MBEDTLS_PLATFORM_STD_CALLOC my_custom_calloc_with_different_name`
___
*[`subprojects/packagefiles/mbedtls/include/mbedtls/config-pal.h` line 37 at r6](https://reviewable.io/reviews/gramineproject/gramine/796#-N89taKb1pPcUh1cltbU:-N89taKc9DOFlRBoxJcB:b-6sw28a) ([raw file](https://github.com/gramineproject/gramine/blob/64b004bb59a237ea2486ef791fd970519888c638/subprojects/packagefiles/mbedtls/include/mbedtls/config-pal.h#L37)):*
> ```objc
> #define MBEDTLS_PKCS1
> #define MBEDTLS_PKCS1_V15
> #define MBEDTLS_PLATFORM_C
> ```

Why did you remove this? It causes `mbedtls` to use host headers, we don't want to do this.



_Code quote:_
```objc
 MBEDTLS_PLATFORM_C
```


<!-- Sent from Reviewable.io -->

2022-07-29 17:31 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/796)* status: 16 of 17 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[`subprojects/packagefiles/mbedtls/include/mbedtls/config-pal.h` line 63 at r4](https://reviewable.io/reviews/gramineproject/gramine/796#-N84kDUm2BuSEVa1dxYy:-N89zqVJBw3EP6R7SJgq:btih660) ([raw file](https://github.com/gramineproject/gramine/blob/4ff84e1f5e9b6a7b4e012d5b347b85cf98f82ba4/subprojects/packagefiles/mbedtls/include/mbedtls/config-pal.h#L63)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Yeah, I think this feature is intended for cases like `define MBEDTLS_PLATFORM_STD_CALLOC my_custom_calloc_with_different_name`
</blockquote></details>

Yes, exactly.
___
*[`subprojects/packagefiles/mbedtls/include/mbedtls/config-pal.h` line 37 at r6](https://reviewable.io/reviews/gramineproject/gramine/796#-N89taKb1pPcUh1cltbU:-N8A-5pl0g8MVI9QKoSL:bn15a6c) ([raw file](https://github.com/gramineproject/gramine/blob/64b004bb59a237ea2486ef791fd970519888c638/subprojects/packagefiles/mbedtls/include/mbedtls/config-pal.h#L37)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why did you remove this? It causes `mbedtls` to use host headers, we don't want to do this.
</blockquote></details>

oops, removed by accident (due to a previous test)... thanks!


<!-- Sent from Reviewable.io -->

2022-07-29 17:38 UTC, boryspoplawski approved these changes
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/796)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2022-07-29 17:39 UTC, boryspoplawski commented
Jenkins, test this please

2022-08-01 06:51 UTC, dimakuv submitted a review, later dismissed
> Reviewed 2 of 3 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/796)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

___
*[`subprojects/packagefiles/mbedtls/include/mbedtls/config-pal.h` line 63 at r4](https://reviewable.io/reviews/gramineproject/gramine/796#-N84kDUm2BuSEVa1dxYy:-N8N9-Ef3lC0P3eJNxl8:b-hcwd51) ([raw file](https://github.com/gramineproject/gramine/blob/4ff84e1f5e9b6a7b4e012d5b347b85cf98f82ba4/subprojects/packagefiles/mbedtls/include/mbedtls/config-pal.h#L63)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Yes, exactly.
</blockquote></details>

I'm not particularly happy with the removal of these macros, because now there is no hint that we're asking mbedTLS to use our implementations of `calloc`, `free` and `snprintf`.

On the other hand, we (the Gramine maintainers) know about this pecularity and can remember about it when e.g. we rename `snprintf` to something else (for whatever reason). So I'm fine with this change.


<!-- Sent from Reviewable.io -->

2022-08-01 09:45 UTC, boryspoplawski submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/796)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

___
*[`subprojects/packagefiles/mbedtls/include/mbedtls/config-pal.h` line 63 at r4](https://reviewable.io/reviews/gramineproject/gramine/796#-N84kDUm2BuSEVa1dxYy:-N8Nmn4z13aqHVB6J4wc:bk6i5vc) ([raw file](https://github.com/gramineproject/gramine/blob/4ff84e1f5e9b6a7b4e012d5b347b85cf98f82ba4/subprojects/packagefiles/mbedtls/include/mbedtls/config-pal.h#L63)):*
> because now there is no hint that we're asking mbedTLS to use our implementations of calloc, free and snprintf

What else could it use? I do not understand the concern...


<!-- Sent from Reviewable.io -->

2022-08-01 12:36 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/796)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2022-08-01 12:37 UTC, dimakuv commented
Jenkins, test this please

2022-08-01 12:44 UTC, boryspoplawski approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/796)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-08-01 13:22 UTC, merged