[CI-Examples] Add SGX measurements verification code to ra-tls-secret…
gramineproject/gramine pull request #802
Opened 2022-07-28 12:20 UTC by veenasai2

…-prov server

Signed-off-by: Veena Saini <veena.saini@intel.com>

## Description of the changes 
Currently the [CI-Examples/ra-tls-secret-prov/](https://github.com/gramineproject/gramine/tree/master/CI-Examples/ra-tls-secret-prov) server code just [prints](https://github.com/gramineproject/gramine/blob/master/CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c#L43-L48) the SGX measurements received by the client. This PR incorporates SGX measurements verification code with ra-tls-secret-prov server code (just the way it done for [ra-tls-mbedtls](https://github.com/gramineproject/gramine/blob/master/CI-Examples/ra-tls-mbedtls/src/client.c#L99-L113) code.

## How to test this PR? 
**Step 1:** `$ cd gramine/CI-Examples/ra-tls-secret-prov`
**Step 2:** `$ make app dcap files/input.txt RA_TYPE=dcap`

### Flow 1
**Step 1.1:** ` $ RA_TLS_ALLOW_DEBUG_ENCLAVE_INSECURE=1 \
             RA_TLS_ALLOW_OUTDATED_TCB_INSECURE=1 \
             ./secret_prov_server_dcap 0 0 0 0 & `
**Step 1.2:** `$ gramine-sgx ./secret_prov_min_client`  // client should receive a secret (this test should pass for other clients too)
**Step 1.3:** Kill the server 

### Flow 2
**Step 2.1:** `$ RA_TLS_ALLOW_DEBUG_ENCLAVE_INSECURE=1 RA_TLS_ALLOW_OUTDATED_TCB_INSECURE=1 \
    ./secret_prov_server_dcap &`
**Step 2.2:** `$ gramine-sgx ./secret_prov_client`  // client should receive a secret (this test should pass for other clients too)
**Step 2.3:** Kill the server
### Flow 3
**Step 3.1** `RA_TLS_ALLOW_DEBUG_ENCLAVE_INSECURE=1 RA_TLS_ALLOW_OUTDATED_TCB_INSECURE=1 \
    ./secret_prov_server_dcap \
    <MRENCLAVE of the min client enclave> \
    <MRSIGNER of the min client enclave> \
    <ISV_PROD_ID of the min client enclave> \
    <ISV_SVN of the min client enclave> &
`
**Step 3.2** `$ gramine-sgx ./secret_prov_min_client`  // client should receive a secret (as the server is expecting min client's measurements)
**Step 3.3** `$ gramine-sgx ./secret_prov_client`  // client should **not** receive a secret and also at the server side one error message will be printed
**Step 3.4** `$ gramine-sgx ./secret_prov_pf_client`  // client should **not** receive a secret and also at the server side one error message will be printed

### Flow 4
Similar to DCAP , EPID flow can also be tested.

2022-07-29 07:29 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/802)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @veenasai2)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/802#-N87qi8CCJcgePudTZpv:-N87qi8CCJcgePudTZpw:b-by9bm4) (no related file):*
@veenasai2 What about Flow 5, with `RA_TLS_ALLOW_DEBUG_ENCLAVE_INSECURE=1 RA_TLS_ALLOW_OUTDATED_TCB_INSECURE=1 \ 
RA_TLS_MRENCLAVE=... RA_TLS_MRSIGNER=...  ./secret_prov_server_dcap`?

Please verify that this flow also works correctly.

___
___
*[`CI-Examples/ra-tls-secret-prov/README.md` line 29 at r1](https://reviewable.io/reviews/gramineproject/gramine/802#-N87qGV6D0uDW1ac-dsZ:-N87qGV6D0uDW1ac-ds_:b-6qd4bx) ([raw file](https://github.com/gramineproject/gramine/blob/a814a5c68dac4f2a81662e0ed45ef1e7811cf15b/CI-Examples/ra-tls-secret-prov/README.md#L29)):*
> ```Markdown
> them links against the corresponding EPID/DCAP secret-provisioning library at
> build time.
> ```

Please add this paragraph (taken from `ra-tls-mbedtls` and slightly modified):
```
If the server is run without additional command-line arguments, it uses the default
RA-TLS verification logic that compares `MRENCLAVE`, `MRSIGNER`,
`ISV_PROD_ID` and `ISV_SVN` against the corresonding `RA_TLS_*` environment
variables. To run the server with its own verification logic, execute it with
four additional command-line arguments (see the examples below).
```

Please also re-align the above text to 80-char-per-line.
___
*[`CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c` line 60 at r1](https://reviewable.io/reviews/gramineproject/gramine/802#-N87noCx8sY25bSsnmaU:-N87noCy9-KXckoKmE5a:b-vvyzt2) ([raw file](https://github.com/gramineproject/gramine/blob/a814a5c68dac4f2a81662e0ed45ef1e7811cf15b/CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c#L60)):*
> ```C
> static bool g_verify_mrsigner    = false;
> static bool g_verify_isv_prod_id = false;
> static bool g_verify_isv_svn     = false;
> ```

FYI: I verified that this code snippet is exactly the same as in `ra-tls-mbedtls`
___
*[`CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c` line 77 at r1](https://reviewable.io/reviews/gramineproject/gramine/802#-N87oAtc-PHor150_Yv4:-N87oAtc-PHor150_Yv5:b-qmc1vr) ([raw file](https://github.com/gramineproject/gramine/blob/a814a5c68dac4f2a81662e0ed45ef1e7811cf15b/CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c#L77)):*
> ```C
>     if (g_verify_mrenclave &&
>             memcmp(mrenclave, g_expected_mrenclave, sizeof(g_expected_mrenclave))){
> 	    puts("Error: MRENCLAVE mismatch");
> ```

You cannot print a message without a `g_print_lock` taken. This is because this function runs in a separate thread (Secret Prov example is multi-threaded), so there is a possibility of a mish-mash if two SGX enclaves are simulteneously verified by this Secret Prov server.

So you should do like this:
```
    ...
    printf("  - ISV_PROD_ID: %hu\n", *((uint16_t*)isv_prod_id));
    printf("  - ISV_SVN:     %hu\n", *((uint16_t*)isv_svn));

    if (g_verify_mrenclave &&
            memcmp(mrenclave, g_expected_mrenclave, sizeof(g_expected_mrenclave))){
        puts("Error: MRENCLAVE mismatch");
        goto fail;
    }

    ... each of the other verifications same as above ...

    pthread_mutex_unlock(&g_print_lock);
    return 0;

fail:
    pthread_mutex_unlock(&g_print_lock);
    return -1;

```
___
*[`CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c` line 77 at r1](https://reviewable.io/reviews/gramineproject/gramine/802#-N87owL8CE0JJn2fZQ6L:-N87owL8CE0JJn2fZQ6M:b-js215g) ([raw file](https://github.com/gramineproject/gramine/blob/a814a5c68dac4f2a81662e0ed45ef1e7811cf15b/CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c#L77)):*
> ```C
>     if (g_verify_mrenclave &&
>             memcmp(mrenclave, g_expected_mrenclave, sizeof(g_expected_mrenclave))){
> 	    puts("Error: MRENCLAVE mismatch");
> ```

Please replace a tab with 4 spaces
___
*[`CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c` line 82 at r1](https://reviewable.io/reviews/gramineproject/gramine/802#-N87oyOL8KGkh0qpXu08:-N87oyOM6ZIQ56FtEmJv:b-js215g) ([raw file](https://github.com/gramineproject/gramine/blob/a814a5c68dac4f2a81662e0ed45ef1e7811cf15b/CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c#L82)):*
> ```C
>     if (g_verify_mrsigner &&
>             memcmp(mrsigner, g_expected_mrsigner, sizeof(g_expected_mrsigner))){
> 	    puts("Error: MRSIGNER mismatch");
> ```

Please replace a tab with 4 spaces
___
*[`CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c` line 87 at r1](https://reviewable.io/reviews/gramineproject/gramine/802#-N87oyp77IeerFKcPnQ5:-N87oyp77IeerFKcPnQ6:b-js215g) ([raw file](https://github.com/gramineproject/gramine/blob/a814a5c68dac4f2a81662e0ed45ef1e7811cf15b/CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c#L87)):*
> ```C
>     if (g_verify_isv_prod_id &&
>             memcmp(isv_prod_id, g_expected_isv_prod_id, sizeof(g_expected_isv_prod_id))){
> 	    puts("Error: ISV_PROD_ID mismatch");
> ```

Please replace a tab with 4 spaces
___
*[`CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c` line 92 at r1](https://reviewable.io/reviews/gramineproject/gramine/802#-N87ozD57xLeqSkPfKaJ:-N87ozD57xLeqSkPfKaK:b-js215g) ([raw file](https://github.com/gramineproject/gramine/blob/a814a5c68dac4f2a81662e0ed45ef1e7811cf15b/CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c#L92)):*
> ```C
>     if (g_verify_isv_svn &&
>             memcmp(isv_svn, g_expected_isv_svn, sizeof(g_expected_isv_svn))){
> 	    puts("Error: ISV_SVN mismatch");
> ```

Please replace a tab with 4 spaces
___
*[`CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c` line 156 at r1](https://reviewable.io/reviews/gramineproject/gramine/802#-N87pME_EOvU-a9Zdyzr:-N87pME_EOvU-a9Zdyzs:b-dqnrw3) ([raw file](https://github.com/gramineproject/gramine/blob/a814a5c68dac4f2a81662e0ed45ef1e7811cf15b/CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c#L156)):*
> ```C
> 
>         printf("[ using our own SGX-measurement verification callback"
>                        " (via command line options) ]\n");
> ```

Please re-indent:
```
        printf("[ using our own SGX-measurement verification callback"
               " (via command line options) ]\n");

```
___
*[`CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c` line 206 at r1](https://reviewable.io/reviews/gramineproject/gramine/802#-N87ptYT65ZuZShd2uao:-N87ptYT65ZuZShd2uap:bbfvoc5) ([raw file](https://github.com/gramineproject/gramine/blob/a814a5c68dac4f2a81662e0ed45ef1e7811cf15b/CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c#L206)):*
> ```C
>     } else {
>         printf("[ using default SGX-measurement verification callback"
>                        " (via RA_TLS_* environment variables) ]\n");
> ```

Please re-indent
___
*[`CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c` line 207 at r1](https://reviewable.io/reviews/gramineproject/gramine/802#-N87q0tR8WMN3G8M-3YD:-N87q0tR8WMN3G8M-3YE:b-vvyzt2) ([raw file](https://github.com/gramineproject/gramine/blob/a814a5c68dac4f2a81662e0ed45ef1e7811cf15b/CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c#L207)):*
> ```C
>         printf("[ using default SGX-measurement verification callback"
>                        " (via RA_TLS_* environment variables) ]\n");
>     }
> ```

FYI: I verified that this code snippet is exactly the same as in `ra-tls-mbedtls`
___
*[`CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c` line 209 at r1](https://reviewable.io/reviews/gramineproject/gramine/802#-N87pxEh-sRbfs2siE-m:-N87pxEh-sRbfs2siE-n:b-pgw2f9) ([raw file](https://github.com/gramineproject/gramine/blob/a814a5c68dac4f2a81662e0ed45ef1e7811cf15b/CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c#L209)):*
> ```C
>     }
>  [...]

2022-07-29 09:38 UTC, veenasai2 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/802)* status: 0 of 2 files reviewed, 10 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/802#-N87qi8CCJcgePudTZpv:-N88InCL5qMvlC1YhiWj:b-fyy3dl) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@veenasai2 What about Flow 5, with `RA_TLS_ALLOW_DEBUG_ENCLAVE_INSECURE=1 RA_TLS_ALLOW_OUTDATED_TCB_INSECURE=1 \ 
RA_TLS_MRENCLAVE=... RA_TLS_MRSIGNER=...  ./secret_prov_server_dcap`?

Please verify that this flow also works correctly.
</blockquote></details>

@dimakuv  Currently this flow falls in the category of "using default SGX-measurement verification callback" and passes for all the clients irrespective of whichever client's  value I give as RA_TLS_MRENCLAVE (which is not expected, it should pass only for one client). I will fix this and push the changes soon. Thanks.

___
___
*[`CI-Examples/ra-tls-secret-prov/README.md` line 29 at r1](https://reviewable.io/reviews/gramineproject/gramine/802#-N87qGV6D0uDW1ac-dsZ:-N88EzDO-8RraEH-gDiI:b-r18wie) ([raw file](https://github.com/gramineproject/gramine/blob/a814a5c68dac4f2a81662e0ed45ef1e7811cf15b/CI-Examples/ra-tls-secret-prov/README.md#L29)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add this paragraph (taken from `ra-tls-mbedtls` and slightly modified):
```
If the server is run without additional command-line arguments, it uses the default
RA-TLS verification logic that compares `MRENCLAVE`, `MRSIGNER`,
`ISV_PROD_ID` and `ISV_SVN` against the corresonding `RA_TLS_*` environment
variables. To run the server with its own verification logic, execute it with
four additional command-line arguments (see the examples below).
```

Please also re-align the above text to 80-char-per-line.
</blockquote></details>

done, thanks.
___
*[`CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c` line 60 at r1](https://reviewable.io/reviews/gramineproject/gramine/802#-N87noCx8sY25bSsnmaU:-N88Czhf0JPcZXIm_7u7:b-fkkjou) ([raw file](https://github.com/gramineproject/gramine/blob/a814a5c68dac4f2a81662e0ed45ef1e7811cf15b/CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c#L60)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

FYI: I verified that this code snippet is exactly the same as in `ra-tls-mbedtls`
</blockquote></details>

thanks for verifying. 
___
*[`CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c` line 77 at r1](https://reviewable.io/reviews/gramineproject/gramine/802#-N87oAtc-PHor150_Yv4:-N88CpRF02AFmfQtFZ7y:b-lhs69o) ([raw file](https://github.com/gramineproject/gramine/blob/a814a5c68dac4f2a81662e0ed45ef1e7811cf15b/CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c#L77)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You cannot print a message without a `g_print_lock` taken. This is because this function runs in a separate thread (Secret Prov example is multi-threaded), so there is a possibility of a mish-mash if two SGX enclaves are simulteneously verified by this Secret Prov server.

So you should do like this:
```
    ...
    printf("  - ISV_PROD_ID: %hu\n", *((uint16_t*)isv_prod_id));
    printf("  - ISV_SVN:     %hu\n", *((uint16_t*)isv_svn));

    if (g_verify_mrenclave &&
            memcmp(mrenclave, g_expected_mrenclave, sizeof(g_expected_mrenclave))){
        puts("Error: MRENCLAVE mismatch");
        goto fail;
    }

    ... each of the other verifications same as above ...

    pthread_mutex_unlock(&g_print_lock);
    return 0;

fail:
    pthread_mutex_unlock(&g_print_lock);
    return -1;

```
</blockquote></details>

done, thanks
___
*[`CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c` line 77 at r1](https://reviewable.io/reviews/gramineproject/gramine/802#-N87owL8CE0JJn2fZQ6L:-N88D83v82kDCf27jxOc:b-lhs69o) ([raw file](https://github.com/gramineproject/gramine/blob/a814a5c68dac4f2a81662e0ed45ef1e7811cf15b/CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c#L77)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please replace a tab with 4 spaces
</blockquote></details>

done, thanks
___
*[`CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c` line 82 at r1](https://reviewable.io/reviews/gramineproject/gramine/802#-N87oyOL8KGkh0qpXu08:-N88DDwFEFkUkNC1Ek08:b-lhs69o) ([raw file](https://github.com/gramineproject/gramine/blob/a814a5c68dac4f2a81662e0ed45ef1e7811cf15b/CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c#L82)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please replace a tab with 4 spaces
</blockquote></details>

done, thanks
___
*[`CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c` line 87 at r1](https://reviewable.io/reviews/gramineproject/gramine/802#-N87oyp77IeerFKcPnQ5:-N88DH4-7WHbvazE50Lv:b-lhs69o) ([raw file](https://github.com/gramineproject/gramine/blob/a814a5c68dac4f2a81662e0ed45ef1e7811cf15b/CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c#L87)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please replace a tab with 4 spaces
</blockquote></details>

done, thanks
___
*[`CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c` line 92 at r1](https://reviewable.io/reviews/gramineproject/gramine/802#-N87ozD57xLeqSkPfKaJ:-N88DILB3O5xKiOOdMrx:b-lhs69o) ([raw file](https://github.com/gramineproject/gramine/blob/a814a5c68dac4f2a81662e0ed45ef1e7811cf15b/CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c#L92)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please replace a tab with 4 spaces
</blockquote></details>

done, thanks
___
*[`CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c` line 156 at r1](https://reviewable.io/reviews/gramineproject/gramine/802#-N87pME_EOvU-a9Zdyzr:-N888i-36DNAP5Y8_7Nl:b-lhs69o) ([raw file](https://github.com/gramineproject/gramine/blob/a814a5c68dac4f2a81662e0ed45ef1e7811cf15b/CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c#L156)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please re-indent:
```
        printf("[ using our own SGX-measurement verification callback"
               " (via command line options) ]\n");

```
</blockquote></details>

done, thanks
___
*[`CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c` line 206 at r1](https://reviewable.io/reviews/gramineproject/gramine/802#-N87ptYT65ZuZShd2uao:-N888jCu-IRr_YndUbR_:b-lhs69o) ([raw file](https://github.com/gramineproject/gramine/blob/a814a5c68dac4f2a81662e0ed45ef1e7811cf15b/CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c#L206)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please re-indent
</blockquote></details>

done, thanks
___
*[`CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c` line 207 at r1](https://reviewable.io/reviews/gramineproject/gramine/802#-N87q0tR8WMN3G8M-3YD:-N8889M73hVWaqBSql-T:bk4ayrk) ([raw file](https://github.com/gramineproject/gramine/blob/a814a5c68dac4f2a81662e0ed45ef1e7811cf15b/CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c#L207)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

FYI: I verified that this code snippet is exactly the same as in `ra-tls-mbedtls`
</blockquote></details>

thanks for verifying 
___
*[`CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c` line 209 at r1](https://reviewable.io/reviews/gramineproject/gramine/802#-N87pxEh-sRbfs2siE-m:-N8887uBEBPhtdag1ALf:b-lhs69o) ([raw file [...]

2022-07-29 10:10 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/802)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @veenasai2)

___
*[`CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c` line 103 at r2](https://reviewable.io/reviews/gramineproject/gramine/802#-N88QeFNEe09csB9P-6h:-N88QeFO1Qmk9AYUIw1S:b-zc4pfx) ([raw file](https://github.com/gramineproject/gramine/blob/a4cace9509ab16ae7e0a737318a2424dc4ed24f3/CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c#L103)):*
> ```C
>     fail:
>          pthread_mutex_unlock(&g_print_lock);
>          return -1;
> ```

Please unindent these three lines by 4 spaces (i.e., `fail:` should start at the very beginning of the line).
___
*[`CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c` line 153 at r2](https://reviewable.io/reviews/gramineproject/gramine/802#-N88QpU01HHZ2322vIE-:-N88QpU01HHZ2322vIE0:be636ow) ([raw file](https://github.com/gramineproject/gramine/blob/a4cace9509ab16ae7e0a737318a2424dc4ed24f3/CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c#L153)):*
> ```C
> 
> int main(int argc, char** argv) {
>     int ret;
> ```

Please add a new empty line after `int ret;`. Otherwise it's hard to read.


<!-- Sent from Reviewable.io -->

2022-07-29 10:28 UTC, veenasai2 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/802)* status: 1 of 2 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c` line 103 at r2](https://reviewable.io/reviews/gramineproject/gramine/802#-N88QeFNEe09csB9P-6h:-N88UhuXEcQoeO9WNyF2:b-r18wie) ([raw file](https://github.com/gramineproject/gramine/blob/a4cace9509ab16ae7e0a737318a2424dc4ed24f3/CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c#L103)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please unindent these three lines by 4 spaces (i.e., `fail:` should start at the very beginning of the line).
</blockquote></details>

done, thanks.
___
*[`CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c` line 153 at r2](https://reviewable.io/reviews/gramineproject/gramine/802#-N88QpU01HHZ2322vIE-:-N88UehAB0BIkyWJtoOO:b-r18wie) ([raw file](https://github.com/gramineproject/gramine/blob/a4cace9509ab16ae7e0a737318a2424dc4ed24f3/CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c#L153)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add a new empty line after `int ret;`. Otherwise it's hard to read.
</blockquote></details>

done, thanks.


<!-- Sent from Reviewable.io -->

2022-07-29 10:57 UTC, veenasai2 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/802)* status: 1 of 2 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/802#-N87qi8CCJcgePudTZpv:-N88_YBI29S_Ni8LEYz5:bycg9du) (no related file):*
<details><summary><i>Previously, veenasai2 (Veena Saini) wrote…</i></summary><blockquote>

@dimakuv  Currently this flow falls in the category of "using default SGX-measurement verification callback" and passes for all the clients irrespective of whichever client's  value I give as RA_TLS_MRENCLAVE (which is not expected, it should pass only for one client). I will fix this and push the changes soon. Thanks.
</blockquote></details>

@dimakuv as per ra-tls-mbedtls design by default [g_verify_mrenclave](https://github.com/gramineproject/gramine/blob/master/CI-Examples/ra-tls-mbedtls/src/client.c#L89) value is **false**. That means when using default measurements [this code](https://github.com/gramineproject/gramine/blob/master/CI-Examples/ra-tls-mbedtls/src/client.c#L100) never got executed.

In short, Flow 1, Flow 2, and Flow 5 give same output and SGX measurements verification never actually happens.  Please let me know if we need to fix this. 

___


<!-- Sent from Reviewable.io -->

2022-07-29 11:21 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/802)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @veenasai2)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/802#-N87qi8CCJcgePudTZpv:-N88e_Yc9vub7iMlvWwt:b-owbi3j) (no related file):*
@veenasai2 You seem to misunderstand how it works. The `g_verify_mrenclave` variable is set to **true** if the user supplies MRENCLAVE in the command-line argument (and it is not `0`).

> That means when using default measurements this code never got executed.

No, the `my_verify_measurements()` code is not executed when there are **no** command-line arguments. This is because this line is not executed which installs this `my_verify_measurements()` callback: https://github.com/gramineproject/gramine/blob/42434c583b10dc9d33a32485b6c95695e4bb72cb/CI-Examples/ra-tls-mbedtls/src/client.c#L253

Please also see my other comment.

___
___
*[`CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c` line 265 at r3](https://reviewable.io/reviews/gramineproject/gramine/802#-N88fOSD0t8689AzQyuN:-N88fOSD0t8689AzQyuO:boquw7o) ([raw file](https://github.com/gramineproject/gramine/blob/bc917e5815f67b8be3ad38dd2b965d60d1be0052/CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c#L265)):*
> ```C
>     ret = secret_provision_start_server((uint8_t*)g_secret_pf_key_hex, sizeof(g_secret_pf_key_hex),
>                                         "4433", SRV_CRT_PATH, SRV_KEY_PATH,
>                                         verify_measurements_callback,
> ```

@veenasai2 That's why the Flow 5 (with `RA_TLS_MRENCLAVE` and others) doesn't work. Because we unconditionally specify the callback as the argument here. See the description of this function: https://github.com/gramineproject/gramine/blob/master/tools/sgx/ra-tls/secret_prov.h#L134-L164

Pay attention to this comment: https://github.com/gramineproject/gramine/blob/42434c583b10dc9d33a32485b6c95695e4bb72cb/tools/sgx/ra-tls/secret_prov.h#L144

So what you need to do is to check "Do we have `argc > 1`, if yes, then we set `verify_measurements_callback` in this arg; if not, then we set  NULL this arg". Basically:
```
                                        argc > 1 ? verify_measurements_callback : NULL,
```


<!-- Sent from Reviewable.io -->

2022-07-29 12:12 UTC, veenasai2 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/802)* status: 1 of 2 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/802#-N87qi8CCJcgePudTZpv:-N88rXtq36Wi1g_ThjHT:b2kd3k) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@veenasai2 You seem to misunderstand how it works. The `g_verify_mrenclave` variable is set to **true** if the user supplies MRENCLAVE in the command-line argument (and it is not `0`).

> That means when using default measurements this code never got executed.

No, the `my_verify_measurements()` code is not executed when there are **no** command-line arguments. This is because this line is not executed which installs this `my_verify_measurements()` callback: https://github.com/gramineproject/gramine/blob/42434c583b10dc9d33a32485b6c95695e4bb72cb/CI-Examples/ra-tls-mbedtls/src/client.c#L253

Please also see my other comment.
</blockquote></details>

@dimakuv thanks for clarification. 

___
___
*[`CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c` line 265 at r3](https://reviewable.io/reviews/gramineproject/gramine/802#-N88fOSD0t8689AzQyuN:-N88rcVI-sr_fErwoTr1:b-uxgafe) ([raw file](https://github.com/gramineproject/gramine/blob/bc917e5815f67b8be3ad38dd2b965d60d1be0052/CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c#L265)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@veenasai2 That's why the Flow 5 (with `RA_TLS_MRENCLAVE` and others) doesn't work. Because we unconditionally specify the callback as the argument here. See the description of this function: https://github.com/gramineproject/gramine/blob/master/tools/sgx/ra-tls/secret_prov.h#L134-L164

Pay attention to this comment: https://github.com/gramineproject/gramine/blob/42434c583b10dc9d33a32485b6c95695e4bb72cb/tools/sgx/ra-tls/secret_prov.h#L144

So what you need to do is to check "Do we have `argc > 1`, if yes, then we set `verify_measurements_callback` in this arg; if not, then we set  NULL this arg". Basically:
```
                                        argc > 1 ? verify_measurements_callback : NULL,
```
</blockquote></details>

@dimakuv  Now I have better clarity, thanks. This change is done.


<!-- Sent from Reviewable.io -->

2022-07-29 12:25 UTC, veenasai2 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/802)* status: 1 of 2 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/802#-N87qi8CCJcgePudTZpv:-N88ufzi02AqY-K5LUf_:bpjlycd) (no related file):*
<details><summary><i>Previously, veenasai2 (Veena Saini) wrote…</i></summary><blockquote>

@dimakuv thanks for clarification. 
</blockquote></details>

After your suggested changes, flow 5 as well working.  Thanks.

___


<!-- Sent from Reviewable.io -->

2022-08-01 06:24 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/802)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2022-08-01 06:24 UTC, dimakuv commented
Jenkins, test this please

2022-08-12 12:47 UTC, mkow requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/802)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @veenasai2)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/802#-N9H3INJD8GpeWsc6LXk:-N9H3INK0lIHF9T3rP8I:beqny3l) (no related file):*
In the future, please create PRs from branches in `<your-nick>/<change-descr>` format, even if it's from your private repo - this makes it a bit easier for us to pull and rebase it before merging without polluting our local branch namespaces.

___
___
*[`CI-Examples/ra-tls-secret-prov/README.md` line 112 at r4](https://reviewable.io/reviews/gramineproject/gramine/802#-N9H4toH8FlKd-RUM-p6:-N9H4toI-j2NPVC2YSI5:b-cszpep) ([raw file](https://github.com/gramineproject/gramine/blob/bc90ce3d578365150d740d869b44163cc4fa0ef9/CI-Examples/ra-tls-secret-prov/README.md#L112)):*
> ```Markdown
>     <MRSIGNER of the client enclave> \
>     <ISV_PROD_ID of the client enclave> \
>     <ISV_SVN of the client enclave> &
> ```

Why `secret_prov_server_epid` gets this information through env and `secret_prov_server_dcap` through argv?


<!-- Sent from Reviewable.io -->

2022-08-16 11:13 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/802)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`CI-Examples/ra-tls-secret-prov/README.md` line 112 at r4](https://reviewable.io/reviews/gramineproject/gramine/802#-N9H4toH8FlKd-RUM-p6:-N9aLDwVAOrUvMsRiNyx:b8zg5zs) ([raw file](https://github.com/gramineproject/gramine/blob/bc90ce3d578365150d740d869b44163cc4fa0ef9/CI-Examples/ra-tls-secret-prov/README.md#L112)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why `secret_prov_server_epid` gets this information through env and `secret_prov_server_dcap` through argv?
</blockquote></details>

@mkow This is purely for show-casing  two different types of giving arguments. We already have the same logic in another of our examples (`ra-tls-mbedtls`) https://github.com/gramineproject/gramine/tree/master/CI-Examples/ra-tls-mbedtls.

Why do we have two different types? Because the first one (through env) uses the default, generic RA-TLS library callback. The second one (through argv) uses the app-specific callback (in this case, the RA-TLS library ignores its default callback and gives control to the user-defined callback).


<!-- Sent from Reviewable.io -->

2022-08-17 03:10 UTC, veenasai2 commented
> > Reviewed all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/802)_ status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @veenasai2)
> 
> _[a discussion](https://reviewable.io/reviews/gramineproject/gramine/802#-N9H3INJD8GpeWsc6LXk:-N9H3INK0lIHF9T3rP8I:beqny3l) (no related file):_ In the future, please create PRs from branches in `<your-nick>/<change-descr>` format, even if it's from your private repo - this makes it a bit easier for us to pull and rebase it before merging without polluting our local branch namespaces.

>  @mkow , I will take care of this point. Thanks.

2022-08-17 03:11 UTC, veenasai2 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/802)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`CI-Examples/ra-tls-secret-prov/README.md` line 112 at r4](https://reviewable.io/reviews/gramineproject/gramine/802#-N9H4toH8FlKd-RUM-p6:-N9dm6av-4ZJxUjw2fg5:b-l9mefz) ([raw file](https://github.com/gramineproject/gramine/blob/bc90ce3d578365150d740d869b44163cc4fa0ef9/CI-Examples/ra-tls-secret-prov/README.md#L112)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@mkow This is purely for show-casing  two different types of giving arguments. We already have the same logic in another of our examples (`ra-tls-mbedtls`) https://github.com/gramineproject/gramine/tree/master/CI-Examples/ra-tls-mbedtls.

Why do we have two different types? Because the first one (through env) uses the default, generic RA-TLS library callback. The second one (through argv) uses the app-specific callback (in this case, the RA-TLS library ignores its default callback and gives control to the user-defined callback).


</blockquote></details>

@dimakuv  thanks for this explanation.


<!-- Sent from Reviewable.io -->

2022-08-29 05:26 UTC, veenasai2 commented
@aneessahib adding you, to keep you in the loop. Thanks.

2022-10-28 13:58 UTC, mkow commented
This PR needs a complete rewrite after https://github.com/gramineproject/gramine/pull/884 got merged, so I'm closing it.
@veenasai2: If you want to pursue this change further then please rewrite and resubmit it.

2022-10-28 13:58 UTC, closed without merging