[LibOS] Fix memory leaks detected by Klocwork
gramineproject/gramine pull request #810
Opened 2022-08-01 15:39 UTC by vijaydhanraj

## Description of the changes 

Klocwork detected memory leaks due to non-freeing of memory resources in the event of `PalThreadGetCpuAffinity` failure. This commit fixes the three leaks reported by Klocwork.

## How to test this PR? 
Regular CI test suite.

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/810)

2022-08-01 15:47 UTC, boryspoplawski requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/810)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @vijaydhanraj)

___
*[`-- commits` line 6 at r1](https://reviewable.io/reviews/gramineproject/gramine/810#-N8P4EWVC6S-FOnsGT4d):*
It's rather one missing `put_thread`, not 3 memory leaks (why 3?)



_Suggestion:_
```
- a03df0b: [LibOS] Add missing `put_thread` in `init_main_thread`

  Klocwork detected memory leaks due to missing thread release in case
  of `PalThreadGetCpuAffinity` failure.
```


<!-- Sent from Reviewable.io -->

2022-08-01 16:06 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/810)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski)

___
*[`-- commits` line 6 at r1](https://reviewable.io/reviews/gramineproject/gramine/810#-N8P4EWVC6S-FOnsGT4d):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

It's rather one missing `put_thread`, not 3 memory leaks (why 3?)
</blockquote></details>

+1 to Borys. There are three data blobs leaking (the thread object itself, signal dispositions and the CPU affinity mask), but the result is the same. We'll use Borys's text during final rebase.


<!-- Sent from Reviewable.io -->

2022-08-01 16:08 UTC, dimakuv commented
Jenkins, test this please

2022-08-01 16:16 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/810)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski and @dimakuv)

___
*[`-- commits` line 6 at r1](https://reviewable.io/reviews/gramineproject/gramine/810#-N8P4EWVC6S-FOnsGT4d):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

+1 to Borys. There are three data blobs leaking (the thread object itself, signal dispositions and the CPU affinity mask), but the result is the same. We'll use Borys's text during final rebase.
</blockquote></details>

Yes, agree it is just one leak but `Klocwork` reports it as three issues. @boryspoplawski suggestion looks good to me.
Thanks @dimakuv for taking care of this at rebase.


<!-- Sent from Reviewable.io -->

2022-08-04 13:59 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/810)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski and @dimakuv)



<!-- Sent from Reviewable.io -->

2022-08-04 15:18 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/810)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski)

___
*[`-- commits` line 6 at r1](https://reviewable.io/reviews/gramineproject/gramine/810#-N8P4EWVC6S-FOnsGT4d):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Yes, agree it is just one leak but `Klocwork` reports it as three issues. @boryspoplawski suggestion looks good to me.
Thanks @dimakuv for taking care of this at rebase.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2022-08-04 15:19 UTC, dimakuv commented
Jenkins, test this please

2022-08-04 15:19 UTC, boryspoplawski approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/810)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2022-08-04 23:01 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/810)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-08-04 23:03 UTC, merged