[PAL/Linux-SGX] Bump the max number of enclave threads to 4096
gramineproject/gramine pull request #812
Opened 2022-08-02 11:32 UTC by dimakuv

## Description of the changes 

Modern Intel CPUs have a large number of cores, and modern workloads (such as PyTorch) allocate a large number of threads (e.g., 4 threads per each CPU core). This exceeds the previous limit on the number of threads (1024) and leads to boostrap errors like this:

    error: There are no available TCS pages left for a new thread!
    Please try to increase sgx.thread_num in the manifest.

This PR bumps the limit to 4096 and fixes several potential stack-overflow issues along the way.

## How to test this PR? 

CI. Plus I tested several large workloads manually (testing with different `sgx.enclave_thread` settings).

2022-08-02 11:36 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/812)* status: 0 of 3 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[`pal/src/host/linux-sgx/host_main.c` line 670 at r1](https://reviewable.io/reviews/gramineproject/gramine/812#-N8TKavW7NdtrA2ewYjt:-N8TKavW7NdtrA2ewYju:b-byksv7) ([raw file](https://github.com/gramineproject/gramine/blob/f91a2c18370858701a33c00620b0c7954f6779bf/pal/src/host/linux-sgx/host_main.c#L670)):*
> ```C
>                     "to be 1");
>         enclave_info->thread_num = 1;
>     }
> ```

FYI: I found this useless. First of all, I've never seen a case where this is triggered. Second, `log_warning()` won't print anything because at this point we still have `log_level = error` because we haven't yet parsed the corresponding manifest option. So this just felt useless.
___
*[`pal/src/host/linux-sgx/gdb_integration/sgx_gdb.h` line 5 at r1](https://reviewable.io/reviews/gramineproject/gramine/812#-N8TKogXAWRqkUP2R91y:-N8TKogXAWRqkUP2R91z:b-td6y40) ([raw file](https://github.com/gramineproject/gramine/blob/01bce3f7d94eaf163840d11394ce7489609743fa/pal/src/host/linux-sgx/gdb_integration/sgx_gdb.h#L5)):*
> ```objc
> #include <stdint.h>
> 
> #define MAX_DBG_THREADS 4096
> ```

FYI: The new limit `4096` is kinda random.


<!-- Sent from Reviewable.io -->

2022-08-02 13:26 UTC, boryspoplawski requested changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/812)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`pal/src/host/linux-sgx/host_main.c` line 339 at r1](https://reviewable.io/reviews/gramineproject/gramine/812#-N8Ti2AQ8ayf-63TiUQb:-N8Ti2AQ8ayf-63TiUQc:b-tssl9s) ([raw file](https://github.com/gramineproject/gramine/blob/01bce3f7d94eaf163840d11394ce7489609743fa/pal/src/host/linux-sgx/host_main.c#L339)):*
> ```C
>      * + enclave->thread_num for signal stack
>      */
>     areas_size = ALIGN_UP_POW2(sizeof(*areas) * (10 + enclave->thread_num * 2), PRESET_PAGESIZE);
> ```

You can remove this `ALIGN_UP`, it's not needed (but not blocking)
___
*[`pal/src/host/linux-sgx/host_main.c` line 343 at r1](https://reviewable.io/reviews/gramineproject/gramine/812#-N8Thh3nB3AHEo00woqH:-N8Thh3nB3AHEo00woqI:b-gvsc3a) ([raw file](https://github.com/gramineproject/gramine/blob/01bce3f7d94eaf163840d11394ce7489609743fa/pal/src/host/linux-sgx/host_main.c#L343)):*
> ```C
>                                          MAP_PRIVATE | MAP_ANONYMOUS, -1, 0);
>     if (IS_PTR_ERR(areas)) {
>         log_error("Allocating memory failed");
> ```

Please also print the error value (`PTR_ERR(areas)`?)
___
*[`pal/src/host/linux-sgx/gdb_integration/sgx_gdb.c` line 44 at r1](https://reviewable.io/reviews/gramineproject/gramine/812#-N8TifBy9HgDWWpMmMMx:-N8TifBy9HgDWWpMmMMy:bne7fhd) ([raw file](https://github.com/gramineproject/gramine/blob/01bce3f7d94eaf163840d11394ce7489609743fa/pal/src/host/linux-sgx/gdb_integration/sgx_gdb.c#L44)):*
> ```C
> } g_memdevs[32];
> 
> /* this object may overflow the stack, so we allocate it in BSS; it is safe to use a single global
> ```

I don't like this. Cannot we use dynamically allocated memory?
___
*[`pal/src/host/linux-sgx/gdb_integration/sgx_gdb.c` line 47 at r1](https://reviewable.io/reviews/gramineproject/gramine/812#-N8Tip9u97cT1yxwgPfW:-N8Tip9v5PROfjoRTsH6:bcp95uu) ([raw file](https://github.com/gramineproject/gramine/blob/01bce3f7d94eaf163840d11394ce7489609743fa/pal/src/host/linux-sgx/gdb_integration/sgx_gdb.c#L47)):*
> ```C
>  * object because GDB itself is single-threaded so no races can occur */
> static struct enclave_dbginfo g_ei_tmp;
> static_assert(sizeof(g_ei_tmp) % sizeof(long) == 0, "Unsupported size");
> ```

Please move this assert to where it was before, it makes no sense here.


<!-- Sent from Reviewable.io -->

2022-08-02 17:11 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/812)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski and @dimakuv)

___
*[`pal/src/host/linux-sgx/gdb_integration/sgx_gdb.c` line 44 at r1](https://reviewable.io/reviews/gramineproject/gramine/812#-N8TifBy9HgDWWpMmMMx:-N8UXTr1ASnOZaeQEpLl:b-44192f) ([raw file](https://github.com/gramineproject/gramine/blob/01bce3f7d94eaf163840d11394ce7489609743fa/pal/src/host/linux-sgx/gdb_integration/sgx_gdb.c#L44)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I don't like this. Cannot we use dynamically allocated memory?
</blockquote></details>

I'm a bit concerned that using `malloc()` in a GDB plugin may blow up. I can try and test a bit. Have you ever tried smth like this?


<!-- Sent from Reviewable.io -->

2022-08-02 17:25 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/812)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`pal/src/host/linux-sgx/gdb_integration/sgx_gdb.c` line 44 at r1](https://reviewable.io/reviews/gramineproject/gramine/812#-N8TifBy9HgDWWpMmMMx:-N8U_5pE2-pmWx18N_Ak:brxbt0z) ([raw file](https://github.com/gramineproject/gramine/blob/01bce3f7d94eaf163840d11394ce7489609743fa/pal/src/host/linux-sgx/gdb_integration/sgx_gdb.c#L44)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I'm a bit concerned that using `malloc()` in a GDB plugin may blow up. I can try and test a bit. Have you ever tried smth like this?
</blockquote></details>

No, I did not. Also this is not really a plugin, it's pure `LD_PRELOAD` of `.so`.
But why wouldn't it work? Also you can use `syscall(mmap)` since this is a rather big struc (a few pages?)


<!-- Sent from Reviewable.io -->

2022-08-03 13:00 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/812)* status: 1 of 3 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[`pal/src/host/linux-sgx/host_main.c` line 343 at r1](https://reviewable.io/reviews/gramineproject/gramine/812#-N8Thh3nB3AHEo00woqH:-N8YiEiq4g1RmL9BLFph:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/01bce3f7d94eaf163840d11394ce7489609743fa/pal/src/host/linux-sgx/host_main.c#L343)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please also print the error value (`PTR_ERR(areas)`?)
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/gdb_integration/sgx_gdb.c` line 44 at r1](https://reviewable.io/reviews/gramineproject/gramine/812#-N8TifBy9HgDWWpMmMMx:-N8YkfFU652cApIBufIh:bp60vie) ([raw file](https://github.com/gramineproject/gramine/blob/01bce3f7d94eaf163840d11394ce7489609743fa/pal/src/host/linux-sgx/gdb_integration/sgx_gdb.c#L44)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

No, I did not. Also this is not really a plugin, it's pure `LD_PRELOAD` of `.so`.
But why wouldn't it work? Also you can use `syscall(mmap)` since this is a rather big struc (a few pages?)
</blockquote></details>

Done. `malloc()` works fine.
___
*[`pal/src/host/linux-sgx/gdb_integration/sgx_gdb.c` line 47 at r1](https://reviewable.io/reviews/gramineproject/gramine/812#-N8Tip9u97cT1yxwgPfW:-N8YkepI0rsA5RiJY0-q:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/01bce3f7d94eaf163840d11394ce7489609743fa/pal/src/host/linux-sgx/gdb_integration/sgx_gdb.c#L47)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please move this assert to where it was before, it makes no sense here.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-03 14:22 UTC, boryspoplawski requested changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/812)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`pal/src/host/linux-sgx/gdb_integration/sgx_gdb.c` line 392 at r2](https://reviewable.io/reviews/gramineproject/gramine/812#-N8Z4CzYEkl1eEB4h3d-:-N8Z4CzZ81aMeCHM86Qr:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/341ba32986f2ad5723e16468a70a9c5d05bbe4e6/pal/src/host/linux-sgx/gdb_integration/sgx_gdb.c#L392)):*
> ```C
>     }
> 
>     struct enclave_dbginfo* g_ei_tmp = malloc(sizeof(*g_ei_tmp));
> ```





_Suggestion:_
```C
ei_tmp
```
___
*[`pal/src/host/linux-sgx/gdb_integration/sgx_gdb.c` line 398 at r2](https://reviewable.io/reviews/gramineproject/gramine/812#-N8Z3wfoCcciu6ocLp1b:-N8Z3wfoCcciu6ocLp1c:b-2r4359) ([raw file](https://github.com/gramineproject/gramine/blob/341ba32986f2ad5723e16468a70a9c5d05bbe4e6/pal/src/host/linux-sgx/gdb_integration/sgx_gdb.c#L398)):*
> ```C
>         goto out;
>     }
>     memset(g_ei_tmp, 0, sizeof(*g_ei_tmp));
> ```

Nitpick: maybe just `calloc` then? It has some optimizations (e.g. mmaped memory is already zeroed)
___
*[`pal/src/host/linux-sgx/gdb_integration/sgx_gdb.c` line 412 at r2](https://reviewable.io/reviews/gramineproject/gramine/812#-N8Z4MXe0UmEQwyHrrAM:-N8Z4MXe0UmEQwyHrrAN:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/341ba32986f2ad5723e16468a70a9c5d05bbe4e6/pal/src/host/linux-sgx/gdb_integration/sgx_gdb.c#L412)):*
> ```C
>         }
> 
>         memcpy((void*)g_ei_tmp + off, &val, sizeof(val));
> ```





_Suggestion:_
```C
(char*)g_ei_tmp 
```


<!-- Sent from Reviewable.io -->

2022-08-03 14:29 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/812)* status: 2 of 3 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[`pal/src/host/linux-sgx/gdb_integration/sgx_gdb.c` line 392 at r2](https://reviewable.io/reviews/gramineproject/gramine/812#-N8Z4CzYEkl1eEB4h3d-:-N8Z5Xc84SdG2gIN-fAo:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/341ba32986f2ad5723e16468a70a9c5d05bbe4e6/pal/src/host/linux-sgx/gdb_integration/sgx_gdb.c#L392)):*
> ```C
>     }
> 
>     struct enclave_dbginfo* g_ei_tmp = malloc(sizeof(*g_ei_tmp));
> ```

Done.
___
*[`pal/src/host/linux-sgx/gdb_integration/sgx_gdb.c` line 398 at r2](https://reviewable.io/reviews/gramineproject/gramine/812#-N8Z3wfoCcciu6ocLp1b:-N8Z5bPb4xI1aPGPUAM8:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/341ba32986f2ad5723e16468a70a9c5d05bbe4e6/pal/src/host/linux-sgx/gdb_integration/sgx_gdb.c#L398)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Nitpick: maybe just `calloc` then? It has some optimizations (e.g. mmaped memory is already zeroed)
</blockquote></details>

Done
___
*[`pal/src/host/linux-sgx/gdb_integration/sgx_gdb.c` line 412 at r2](https://reviewable.io/reviews/gramineproject/gramine/812#-N8Z4MXe0UmEQwyHrrAM:-N8Z5jwzEOdHe6EQokVN:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/341ba32986f2ad5723e16468a70a9c5d05bbe4e6/pal/src/host/linux-sgx/gdb_integration/sgx_gdb.c#L412)):*
> ```C
>         }
> 
>         memcpy((void*)g_ei_tmp + off, &val, sizeof(val));
> ```

Done.


<!-- Sent from Reviewable.io -->

2022-08-03 14:38 UTC, boryspoplawski submitted a review, later dismissed
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/812)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2022-08-08 23:31 UTC, mkow requested changes
> Reviewed 1 of 3 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/812)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`pal/src/host/linux-sgx/host_main.c` line 671 at r3](https://reviewable.io/reviews/gramineproject/gramine/812#-N8zmms312uLpnU9FXJv:-N8zmms312uLpnU9FXJw:bon4qlh) ([raw file](https://github.com/gramineproject/gramine/blob/15b87eeb7f25d93caa3584d6aad7a89391796a93/pal/src/host/linux-sgx/host_main.c#L671)):*
> ```C
> 
>     if (thread_num_int64 <= 0) {
>         log_error("Non-positive 'sgx.thread_num' is impossible");
> ```

Hmm, but now if someone would omit `sgx.thread_num` then they'll get the error "Non-positive 'sgx.thread_num' is impossible", which is confusing and doesn't make sense. I'd just default to 1.
___
*[`pal/src/host/linux-sgx/gdb_integration/sgx_gdb.c` line 392 at r3](https://reviewable.io/reviews/gramineproject/gramine/812#-N8zky5TE0lrHGcJ8NSq:-N8zky5UCYLUte5joZIE:b-3u1v2n) ([raw file](https://github.com/gramineproject/gramine/blob/15b87eeb7f25d93caa3584d6aad7a89391796a93/pal/src/host/linux-sgx/gdb_integration/sgx_gdb.c#L392)):*
> ```C
>     }
> 
>     struct enclave_dbginfo* ei_tmp = calloc(1, sizeof(*ei_tmp));
> ```

Why did you add that `_tmp` suffix?


<!-- Sent from Reviewable.io -->

2022-08-17 09:49 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/812)* status: 1 of 3 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[`pal/src/host/linux-sgx/host_main.c` line 671 at r3](https://reviewable.io/reviews/gramineproject/gramine/812#-N8zmms312uLpnU9FXJv:-N9f9vzz0X6k6hEg2m0M:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/15b87eeb7f25d93caa3584d6aad7a89391796a93/pal/src/host/linux-sgx/host_main.c#L671)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Hmm, but now if someone would omit `sgx.thread_num` then they'll get the error "Non-positive 'sgx.thread_num' is impossible", which is confusing and doesn't make sense. I'd just default to 1.
</blockquote></details>

Done
___
*[`pal/src/host/linux-sgx/gdb_integration/sgx_gdb.c` line 392 at r3](https://reviewable.io/reviews/gramineproject/gramine/812#-N8zky5TE0lrHGcJ8NSq:-N9fARyD-WeNtE8V_v1c:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/15b87eeb7f25d93caa3584d6aad7a89391796a93/pal/src/host/linux-sgx/gdb_integration/sgx_gdb.c#L392)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why did you add that `_tmp` suffix?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-17 11:27 UTC, mkow approved these changes
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/812)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2022-08-17 12:02 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/812)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-08-17 12:14 UTC, boryspoplawski approved these changes
> Reviewed 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/812)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`pal/src/host/linux-sgx/host_main.c` line 676 at r5](https://reviewable.io/reviews/gramineproject/gramine/812#-N9fhov72qKZ_VpiNFJ4:-N9fhov72qKZ_VpiNFJ5:b-yp5go4) ([raw file](https://github.com/gramineproject/gramine/blob/cf43bbca4c48456378b34621a1a271c6b3bd8148/pal/src/host/linux-sgx/host_main.c#L676)):*
> ```C
>     }
> 
>     enclave_info->thread_num = thread_num_int64 ?: 1;
> ```

This has one small issue that if user specifies `thread_num = 0` it will be silently overwritten.
But I don't think any sane user will do it (also what would they expect to achieve with that), so it should be fine. Maybe worth documenting in .rst? Not blocking.


<!-- Sent from Reviewable.io -->

2022-08-17 12:39 UTC, merged