[tools/sgx] Improve public API of Secret Prov lib
gramineproject/gramine pull request #813
Opened 2022-08-02 17:01 UTC by dimakuv

## Description of the changes 

This is a breaking change that modifies the API of the Secret Prov lib as follows:

- `secret_provision_start()` allocates a context that should be supplied to all other Secret Prov APIs and must be closed afterwards.

- `secret_provision_get()` requires a context as the first argument, and extracts the secret that is associated with this context. Thus, it allows for several secrets being delivered in parallel from different remote parties (previously, the secret was a global variable).

- `secret_provision_destroy()` is removed. Instead, users should call `secret_provision_close()` that will both close the session and destroy the secret.

With these changes, the context ceases to be global, and the library becomes thread-safe. Also, leaks of mbedTLS resources are prevented.

As a small side fix, the library always returns normal POSIX error codes (previously, the library could return mbedTLS error codes).

Fixes #646. Supersedes #647.

## How to test this PR? 

CI should be enough. But also see manual way in #647 to test resource/memory leaks.

2022-08-02 17:06 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/813)* status: 0 of 5 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/813#-N8UVwWFBZGBJxIRv4ez:-N8UVwWFBZGBJxIRv4f-:b-xli39m) (no related file):*
@mkow @boryspoplawski You were the original reviewers of #647. Hopefully this new PR will be easier to review.

Sorry for creating a new PR, but the scope changed drastically in comparison to #647. Now we're changing the APIs.

___
___
*[`tools/sgx/ra-tls/secret_prov_verify.c` line 186 at r1](https://reviewable.io/reviews/gramineproject/gramine/813#-N8UWH20E0UQ8L0YJeoj:-N8UWH20E0UQ8L0YJeok:be1cajr) ([raw file](https://github.com/gramineproject/gramine/blob/71fa466c2ac054387aa55c762643379bb6312544/tools/sgx/ra-tls/secret_prov_verify.c#L186)):*
> ```C
>                                 (const uint8_t*)pers, strlen(pers));
>     if (ret < 0) {
>         ret = -EPERM;
> ```

FYI: This is not optimal, but mbedTLS functions return mbedTLS-specific error codes, and there is no way to translate them to UNIX error codes (unless I write my own function that does it). Do we care?


<!-- Sent from Reviewable.io -->

2022-08-04 06:19 UTC, liangintel commented
after changing API, cross-language-framework solution can work well on this PR.
https://github.com/intel/confidential-computing-zoo/tree/main/cczoo/cross_lang_framework

2022-08-04 07:01 UTC, dimakuv reviewed
@liangintel Thanks for checking!

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/813#-:-N8be2rK39chRZOaSSns:b-k8xliz)* status: 0 of 5 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2022-08-05 12:45 UTC, boryspoplawski requested changes
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/813)* status: all files reviewed, 21 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`CI-Examples/ra-tls-secret-prov/src/secret_prov_client.c` line 35 at r1](https://reviewable.io/reviews/gramineproject/gramine/813#-N8hqGvb3lSdZcMi_9h4:-N8hqGvb3lSdZcMi_9h5:brgxtab) ([raw file](https://github.com/gramineproject/gramine/blob/71fa466c2ac054387aa55c762643379bb6312544/CI-Examples/ra-tls-secret-prov/src/secret_prov_client.c#L35)):*
> ```C
> 
>     if (!is_constructor) {
>         /* secret provisioning was not run as part of initialization, run it now */
> ```

How this is supposed to work? `ctx` is a local variable, global constructor couldn't have possibly initialized it.
___
*[`CI-Examples/ra-tls-secret-prov/src/secret_prov_client.c` line 44 at r1](https://reviewable.io/reviews/gramineproject/gramine/813#-N8hyw_H6pCZPHFDR95j:-N8hyw_H6pCZPHFDR95k:boj406j) ([raw file](https://github.com/gramineproject/gramine/blob/71fa466c2ac054387aa55c762643379bb6312544/CI-Examples/ra-tls-secret-prov/src/secret_prov_client.c#L44)):*
> ```C
>     }
> 
>     ret = secret_provision_get(ctx, &secret1, &secret1_size);
> ```

This is now wrong in case of `is_constructor == true`
___
*[`tools/sgx/ra-tls/secret_prov.h` line 79 at r1](https://reviewable.io/reviews/gramineproject/gramine/813#-N8hsx1UE_Bb9dU64RxJ:-N8hsx1UE_Bb9dU64RxK:bnrjnzp) ([raw file](https://github.com/gramineproject/gramine/blob/71fa466c2ac054387aa55c762643379bb6312544/tools/sgx/ra-tls/secret_prov.h#L79)):*
> ```objc
>  */
> __attribute__ ((visibility("default")))
> int secret_provision_close(struct ra_tls_ctx* ctx);
> ```

Please also add a comment that this function must not be called again even if it returns an error and `ctx` is always freed (semantics similar to `close` syscall on Linux).
___
*[`tools/sgx/ra-tls/secret_prov.h` line 96 at r1](https://reviewable.io/reviews/gramineproject/gramine/813#-N8htOSA4AopqUSxRS4r:-N8htOSA4AopqUSxRS4s:b1iszsu) ([raw file](https://github.com/gramineproject/gramine/blob/71fa466c2ac054387aa55c762643379bb6312544/tools/sgx/ra-tls/secret_prov.h#L96)):*
> ```objc
>  */
> __attribute__ ((visibility("default")))
> int secret_provision_get(struct ra_tls_ctx* ctx, uint8_t** out_secret, size_t* out_secret_size);
> ```

This API is weird. This gets a reference to the underlying buffer, not a copy. Doing
```c
secret_provision_get(ctx, &buf, &size);
secret_provision_close(ctx);
use(buf);
```
is highly illegal.
___
*[`tools/sgx/ra-tls/secret_prov_attest.c` line 55 at r1](https://reviewable.io/reviews/gramineproject/gramine/813#-N8hrmWC2HyytPtyB7Nu:-N8hrmWC2HyytPtyB7Nv:b-5ohzel) ([raw file](https://github.com/gramineproject/gramine/blob/71fa466c2ac054387aa55c762643379bb6312544/tools/sgx/ra-tls/secret_prov_attest.c#L55)):*
> ```C
> extern int secret_provision_common_write(mbedtls_ssl_context* ssl, const uint8_t* buf, size_t size);
> extern int secret_provision_common_read(mbedtls_ssl_context* ssl, uint8_t* buf, size_t size);
> extern int secret_provision_common_close(mbedtls_ssl_context* ssl);
> ```

Or maybe a header?



_Suggestion:_
```C
int secret_provision_common_write(mbedtls_ssl_context* ssl, const uint8_t* buf, size_t size);
int secret_provision_common_read(mbedtls_ssl_context* ssl, uint8_t* buf, size_t size);
int secret_provision_common_close(mbedtls_ssl_context* ssl);
```
___
*[`tools/sgx/ra-tls/secret_prov_attest.c` line 58 at r1](https://reviewable.io/reviews/gramineproject/gramine/813#-N8hs2xIDJQVJ_MNoE6a:-N8hs2xIDJQVJ_MNoE6b:b2oj4yp) ([raw file](https://github.com/gramineproject/gramine/blob/71fa466c2ac054387aa55c762643379bb6312544/tools/sgx/ra-tls/secret_prov_attest.c#L58)):*
> ```C
> 
> int secret_provision_write(struct ra_tls_ctx* ctx, const uint8_t* buf, size_t size) {
>     mbedtls_ssl_context* ssl = (mbedtls_ssl_context*)ctx->ssl;
> ```

Why the cast? Why the immediate variable?
___
*[`tools/sgx/ra-tls/secret_prov_attest.c` line 63 at r1](https://reviewable.io/reviews/gramineproject/gramine/813#-N8hs4LU-R9PuqYVngiX:-N8hs4LU-R9PuqYVngiY:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/71fa466c2ac054387aa55c762643379bb6312544/tools/sgx/ra-tls/secret_prov_attest.c#L63)):*
> ```C
> 
> int secret_provision_read(struct ra_tls_ctx* ctx, uint8_t* buf, size_t size) {
>     mbedtls_ssl_context* ssl = (mbedtls_ssl_context*)ctx->ssl;
> ```

ditto
___
*[`tools/sgx/ra-tls/secret_prov_attest.c` line 136 at r1](https://reviewable.io/reviews/gramineproject/gramine/813#-N8hvhvv4iAm38fFBLWj:-N8hvhvv4iAm38fFBLWk:b-9lfj8b) ([raw file](https://github.com/gramineproject/gramine/blob/71fa466c2ac054387aa55c762643379bb6312544/tools/sgx/ra-tls/secret_prov_attest.c#L136)):*
> ```C
>                                 (const uint8_t*)pers, strlen(pers));
>     if (ret < 0) {
>         ret = -EPERM;
> ```

Maybe print an error message with original mbedtls error code here?
ditto all other places
___
*[`tools/sgx/ra-tls/secret_prov_attest.c` line 252 at r1](https://reviewable.io/reviews/gramineproject/gramine/813#-N8hwa-bAK8rbjpA-0yH:-N8hwa-bAK8rbjpA-0yI:bdzqeqf) ([raw file](https://github.com/gramineproject/gramine/blob/71fa466c2ac054387aa55c762643379bb6312544/tools/sgx/ra-tls/secret_prov_attest.c#L252)):*
> ```C
>             goto out;
>         }
>     }
> ```

It was already this way, but I couldn't look at it :(



_Suggestion:_
```C
    do {
        ret = mbedtls_ssl_handshake(ssl);
    } while (ret == MBEDTLS_ERR_SSL_WANT_READ || ret == MBEDTLS_ERR_SSL_WANT_WRITE);
    if (ret < 0) {
        ret = -EPERM;
        goto out;
    }
```
___
*[`tools/sgx/ra-tls/secret_prov_attest.c` line 309 at r1](https://reviewable.io/reviews/gramineproject/gramine/813#-N8huerECfggy0OWc8_5:-N8huerECfggy0OWc8_6:b-gzdsza) ([raw file](https://github.com/gramineproject/gramine/blob/71fa466c2ac054387aa55c762643379bb6312544/tools/sgx/ra-tls/secret_prov_attest.c#L309)):*
> ```C
>     }
> 
>     ctx = malloc(sizeof(*ctx));
> ```

Why not create this at the top together with the rest of objects?
___
*[`tools/sgx/ra-tls/secret_prov_attest.c` line 324 at r1](https://reviewable.io/reviews/gramineproject/gramine/813#-N8hunBWAdE8yvEAgHSy:-N8hunBWAdE8yvEAgHSz:b-fk0t1l) ([raw file](https://github.com/gramineproject/gramine/blob/71fa466c2ac054387aa55c762643379bb6312544/tools/sgx/ra-tls/secret_prov_attest.c#L324)):*
> ```C
>     ret = 0;
> out:
>     if (ret < 0) {
> ```

If you'd created `ctx` at the top you could just `secret_priviosion_close(ctx)` here, instead of duplicating this cleanup.
___
*[`tools/sgx/ra-tls/secret_prov_attest.c` line 325 at r1](https://reviewable.io/reviews/gramineproject/gramine/813#-N8huNXt-dvs39oA5-4a:-N8huNXt-dvs39oA5-4b:b-oa1ffk) ([raw file](https://github.com/gramineproject/gramine/blob/71fa466c2ac054387aa55c762643379bb6312544/tools/sgx/ra-tls/secret_prov_attest.c#L325)):*
> ```C
> out:
>     if (ret < 0) {
>         secret_provision_common_close(ssl);
> ```

Lack of error checks.
___
*[`tools/sgx/ra-tls/secret_prov_common.c` line 19 at r1](https://reviewable.io/reviews/gramineproject/gramine/813#-N8hzIaF9jZOYuWaTVmW:-N8hzIaF9jZOYuWaTVmX:bia26w7) ([raw file](https://github.com/gramineproject/gramine/blob/71fa466c2ac054387aa55c762643379bb6312544/tools/sgx/ra-tls/secret_prov_common.c#L19)):*
> ```C
> #include "secret_prov.h"
> 
> int secret_provision_common_write(mbedtls_ssl_context* ssl, const uint8_t* buf, size_t size);
> ```

Well, just create a header please
___
*[`tools/sgx/ra-tls/secret_prov_common.c` line 41 at r1](https://reviewable.io/reviews/gramineproject/gramine/813#-N8hzfio6KbhM9MSppp4:-N8hzfio6KbhM9MSppp5:b-vvlvg8) ([raw file](https://github.com/gramineproject/gramine/blob/71fa466c2ac054387aa55c762643379bb6312544/tools/sgx/ra-tls/secret_prov_common.c#L41)):*
> ```C
>     }
>     assert(written == size); [...]

2022-08-17 09:35 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/813)* status: all files reviewed, 21 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski and @dimakuv)

___
*[`CI-Examples/ra-tls-secret-prov/src/secret_prov_client.c` line 35 at r1](https://reviewable.io/reviews/gramineproject/gramine/813#-N8hqGvb3lSdZcMi_9h4:-N9f8tWmB4ZS2MKLL_tU:btp6de8) ([raw file](https://github.com/gramineproject/gramine/blob/71fa466c2ac054387aa55c762643379bb6312544/CI-Examples/ra-tls-secret-prov/src/secret_prov_client.c#L35)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

How this is supposed to work? `ctx` is a local variable, global constructor couldn't have possibly initialized it.
</blockquote></details>

Very good question. Let me take a look at this example code. It probably only runs one of these flows (the no-constructor flow) ever, so I'll remove the other flow.
___
*[`tools/sgx/ra-tls/secret_prov.h` line 96 at r1](https://reviewable.io/reviews/gramineproject/gramine/813#-N8htOSA4AopqUSxRS4r:-N9f7BET-ZoR8SCwNc_a:b3ao9ko) ([raw file](https://github.com/gramineproject/gramine/blob/71fa466c2ac054387aa55c762643379bb6312544/tools/sgx/ra-tls/secret_prov.h#L96)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This API is weird. This gets a reference to the underlying buffer, not a copy. Doing
```c
secret_provision_get(ctx, &buf, &size);
secret_provision_close(ctx);
use(buf);
```
is highly illegal.
</blockquote></details>

Just to clarify before I change this API: you suggest to always return a *copy* of the secret here, right?
___
*[`tools/sgx/ra-tls/secret_prov_attest.c` line 252 at r1](https://reviewable.io/reviews/gramineproject/gramine/813#-N8hwa-bAK8rbjpA-0yH:-N9f7ZXC-QZAA9kZKP1Z:b69xxpk) ([raw file](https://github.com/gramineproject/gramine/blob/71fa466c2ac054387aa55c762643379bb6312544/tools/sgx/ra-tls/secret_prov_attest.c#L252)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

It was already this way, but I couldn't look at it :(
</blockquote></details>

There is a weird `null` line in your code change, I'll just ignore it. Just a typo?
___
*[`tools/sgx/ra-tls/secret_prov_common.c` line 19 at r1](https://reviewable.io/reviews/gramineproject/gramine/813#-N8hzIaF9jZOYuWaTVmW:-N9f7nr6-i4882SoUZCw:b-3cuc7z) ([raw file](https://github.com/gramineproject/gramine/blob/71fa466c2ac054387aa55c762643379bb6312544/tools/sgx/ra-tls/secret_prov_common.c#L19)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Well, just create a header please
</blockquote></details>

A new internal header? Like `secret_prov_internal.h`?
___
*[`tools/sgx/ra-tls/secret_prov_verify.c` line 145 at r1](https://reviewable.io/reviews/gramineproject/gramine/813#-N8i1--372JtNBf2s6ev:-N9f8I8k6JU_7GvgpKS-:bji42y) ([raw file](https://github.com/gramineproject/gramine/blob/71fa466c2ac054387aa55c762643379bb6312544/tools/sgx/ra-tls/secret_prov_verify.c#L145)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

It's not really `caller`, we pass it to the callback. Caller cannot take the ownership of this objects, because it's local to this scope.
Why not do this and relieve the callback from the need of calling close?
</blockquote></details>

Yeah, agreed. I wanted to have a symmetry in the code of the secret-prov-verify user: first `secret_provision_start_server(&client_connection_callback)` and then `secret_provision_close()`.

But I agree that it's only confusing and cumbersome for users. Will change.


<!-- Sent from Reviewable.io -->

2022-08-17 13:30 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/813)* status: all files reviewed, 21 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski and @dimakuv)

___
*[`tools/sgx/ra-tls/secret_prov.h` line 96 at r1](https://reviewable.io/reviews/gramineproject/gramine/813#-N8htOSA4AopqUSxRS4r:-N9fz1Y07HmHP8JMqtR-:bbkrp2d) ([raw file](https://github.com/gramineproject/gramine/blob/71fa466c2ac054387aa55c762643379bb6312544/tools/sgx/ra-tls/secret_prov.h#L96)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Just to clarify before I change this API: you suggest to always return a *copy* of the secret here, right?
</blockquote></details>

I guess? I don't know what's the best solution, but even the comment suggests that it's a copy `Pointer to buffer with secret (allocated by the library).`
___
*[`tools/sgx/ra-tls/secret_prov_attest.c` line 252 at r1](https://reviewable.io/reviews/gramineproject/gramine/813#-N8hwa-bAK8rbjpA-0yH:-N9fzOVS1sWC7op_eCrh:b-2s85m9) ([raw file](https://github.com/gramineproject/gramine/blob/71fa466c2ac054387aa55c762643379bb6312544/tools/sgx/ra-tls/secret_prov_attest.c#L252)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

There is a weird `null` line in your code change, I'll just ignore it. Just a typo?
</blockquote></details>

Turn off the diff (i.e. look at the resulting code), looks like a reviewable bug
___
*[`tools/sgx/ra-tls/secret_prov_common.c` line 19 at r1](https://reviewable.io/reviews/gramineproject/gramine/813#-N8hzIaF9jZOYuWaTVmW:-N9fzbR9ANxz6FOkJSJ-:b-qazz8z) ([raw file](https://github.com/gramineproject/gramine/blob/71fa466c2ac054387aa55c762643379bb6312544/tools/sgx/ra-tls/secret_prov_common.c#L19)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

A new internal header? Like `secret_prov_internal.h`?
</blockquote></details>

Or `secret_prov_common.h`? I don't mind the name, but redefining this everywhere is annoying


<!-- Sent from Reviewable.io -->

2022-08-17 14:33 UTC, liangintel commented on tools/sgx/ra-tls/secret_prov_attest.c
> +int secret_provision_close(struct ra_tls_ctx* ctx) {
crash happened. please add if(!ctx) return ...
similar in secret_provision_get

2022-08-18 08:15 UTC, dimakuv reviewed
> Reviewed 1 of 5 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/813)* status: all files reviewed, 24 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @liangintel, and @mkow)

___
*[`-- commits` line 11 at r1](https://reviewable.io/reviews/gramineproject/gramine/813#-N9jt1CMBdpv0Q9xLMUy):*
I need to add here that `secret_provision_get()` returns a copy now.
___
*[`-- commits` line 20 at r1](https://reviewable.io/reviews/gramineproject/gramine/813#-N9jt5J_1BcfmkAaN4pM):*
...But also prints the original mbedTLS error.
___
*[`CI-Examples/ra-tls-secret-prov/src/secret_prov_client.c` line 35 at r1](https://reviewable.io/reviews/gramineproject/gramine/813#-N8hqGvb3lSdZcMi_9h4:-N9jhahdEp7gUXcP5skl:bv6zqno) ([raw file](https://github.com/gramineproject/gramine/blob/71fa466c2ac054387aa55c762643379bb6312544/CI-Examples/ra-tls-secret-prov/src/secret_prov_client.c#L35)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Very good question. Let me take a look at this example code. It probably only runs one of these flows (the no-constructor flow) ever, so I'll remove the other flow.
</blockquote></details>

Done. Turns out the `is_constructor == true` flow never executed (because there is no `SECRET_PROVISION_CONSTRUCTOR` in the manifest). So I just removed it.
___
*[`CI-Examples/ra-tls-secret-prov/src/secret_prov_client.c` line 44 at r1](https://reviewable.io/reviews/gramineproject/gramine/813#-N8hyw_H6pCZPHFDR95j:-N9jhjePC8zF1hIX9CUi:b-kynmpj) ([raw file](https://github.com/gramineproject/gramine/blob/71fa466c2ac054387aa55c762643379bb6312544/CI-Examples/ra-tls-secret-prov/src/secret_prov_client.c#L44)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This is now wrong in case of `is_constructor == true`
</blockquote></details>

Done. Not applicable.
___
*[`tools/sgx/ra-tls/secret_prov.h` line 79 at r1](https://reviewable.io/reviews/gramineproject/gramine/813#-N8hsx1UE_Bb9dU64RxJ:-N9jiJn01mTBz7cgvdah:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/71fa466c2ac054387aa55c762643379bb6312544/tools/sgx/ra-tls/secret_prov.h#L79)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please also add a comment that this function must not be called again even if it returns an error and `ctx` is always freed (semantics similar to `close` syscall on Linux).
</blockquote></details>

Done.
___
*[`tools/sgx/ra-tls/secret_prov.h` line 96 at r1](https://reviewable.io/reviews/gramineproject/gramine/813#-N8htOSA4AopqUSxRS4r:-N9jkUcBCbGaE5oaPmWQ:b6ac6ee) ([raw file](https://github.com/gramineproject/gramine/blob/71fa466c2ac054387aa55c762643379bb6312544/tools/sgx/ra-tls/secret_prov.h#L96)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I guess? I don't know what's the best solution, but even the comment suggests that it's a copy `Pointer to buffer with secret (allocated by the library).`
</blockquote></details>

Done. Now we allocate a copy.
___
*[`tools/sgx/ra-tls/secret_prov_attest.c` line 55 at r1](https://reviewable.io/reviews/gramineproject/gramine/813#-N8hrmWC2HyytPtyB7Nu:-N9jlcrS9yxyji7ChcWU:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/71fa466c2ac054387aa55c762643379bb6312544/tools/sgx/ra-tls/secret_prov_attest.c#L55)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Or maybe a header?
</blockquote></details>

Done.
___
*[`tools/sgx/ra-tls/secret_prov_attest.c` line 58 at r1](https://reviewable.io/reviews/gramineproject/gramine/813#-N8hs2xIDJQVJ_MNoE6a:-N9jlqz33vMDekEl2azp:b-o3jhuf) ([raw file](https://github.com/gramineproject/gramine/blob/71fa466c2ac054387aa55c762643379bb6312544/tools/sgx/ra-tls/secret_prov_attest.c#L58)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why the cast? Why the immediate variable?
</blockquote></details>

Done. Remnant from the old version of the code.
___
*[`tools/sgx/ra-tls/secret_prov_attest.c` line 63 at r1](https://reviewable.io/reviews/gramineproject/gramine/813#-N8hs4LU-R9PuqYVngiX:-N9jlszi1MQzcpHh5q8i:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/71fa466c2ac054387aa55c762643379bb6312544/tools/sgx/ra-tls/secret_prov_attest.c#L63)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`tools/sgx/ra-tls/secret_prov_attest.c` line 67 at r1](https://reviewable.io/reviews/gramineproject/gramine/813#-N8UVSjO5eysjSOv8Oky-r1-67:-N9juUAK3LAcq3C54Ykm:bf69lv) ([raw file](https://github.com/gramineproject/gramine/blob/71fa466c2ac054387aa55c762643379bb6312544/tools/sgx/ra-tls/secret_prov_attest.c#L67)):*
<details><summary><i>Previously, liangintel (Liang Fang) wrote…</i></summary><blockquote>

crash happened. please add if(!ctx) return ...
similar in secret_provision_get
</blockquote></details>

Done. Added this sanity check to all user-facing (API) functions.
___
*[`tools/sgx/ra-tls/secret_prov_attest.c` line 136 at r1](https://reviewable.io/reviews/gramineproject/gramine/813#-N8hvhvv4iAm38fFBLWj:-N9jyVaH9Ot6lEXIWsBN:b-2o8a80) ([raw file](https://github.com/gramineproject/gramine/blob/71fa466c2ac054387aa55c762643379bb6312544/tools/sgx/ra-tls/secret_prov_attest.c#L136)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Maybe print an error message with original mbedtls error code here?
ditto all other places
</blockquote></details>

Done. @mkow will hopefully be happy, he complained about the lack of any printouts recently. Now on errors smth like this is printed:
```
secret_provision_start: Secret Provisioning could not connect to any of the servers specified in SECRET_PROVISION_SERVERS
secret_provision_common_close: Secret Provisioning failed during connection close with mbedTLS error -28928
WARNING: Closing the secret-prov context failed with error -1.
secret_provision_constructor: Secret provisioning failed, terminating the whole process
```
___
*[`tools/sgx/ra-tls/secret_prov_attest.c` line 252 at r1](https://reviewable.io/reviews/gramineproject/gramine/813#-N8hwa-bAK8rbjpA-0yH:-N9jmGvu38hcpMx_piFj:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/71fa466c2ac054387aa55c762643379bb6312544/tools/sgx/ra-tls/secret_prov_attest.c#L252)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Turn off the diff (i.e. look at the resulting code), looks like a reviewable bug
</blockquote></details>

Done.
___
*[`tools/sgx/ra-tls/secret_prov_attest.c` line 309 at r1](https://reviewable.io/reviews/gramineproject/gramine/813#-N8huerECfggy0OWc8_5:-N9jsuWO1yorOUIbs5Sc:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/71fa466c2ac054387aa55c762643379bb6312544/tools/sgx/ra-tls/secret_prov_attest.c#L309)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why not create this at the top together with the rest of objects?
</blockquote></details>

Done.
___
*[`tools/sgx/ra-tls/secret_prov_attest.c` line 324 at r1](https://reviewable.io/reviews/gramineproject/gramine/813#-N8hunBWAdE8yvEAgHSy:-N9josoM5d7boZM7LBMM:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/71fa466c2ac054387aa55c762643379bb6312544/tools/sgx/ra-tls/secret_prov_attest.c#L324)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

If you'd created `ctx` at the top you could just `secret_priviosion_close(ctx)` here, instead o [...]

2022-08-18 12:22 UTC, mkow requested changes
> Reviewed 1 of 5 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/813)* status: all files reviewed, 29 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @liangintel)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/813#-N9hNMiRC3MZ5j9EqPkV:-N9hNMiRC3MZ5j9EqPkW:be6rtsq) (no related file):*
@liangintel: Please use Reviewable, that's the tool we use as a project for reviews.

___
___
*[`CI-Examples/ra-tls-secret-prov/src/secret_prov_client.c` line 22 at r2](https://reviewable.io/reviews/gramineproject/gramine/813#-N9k99yD5GoJuMhWweVB:-N9k99yE92F8XRiRne6J:b-6epr5h) ([raw file](https://github.com/gramineproject/gramine/blob/01542442d573bee0764f1f21c6b3a2a29fb05602/CI-Examples/ra-tls-secret-prov/src/secret_prov_client.c#L22)):*
> ```C
> 
>     uint8_t* secret1    = NULL;
>     size_t secret1_size = 0;
> ```

Please pick one of these: (same with `secret2`)



_Suggestion (i):_
```C
    uint8_t* secret1 = NULL;
    size_t secret1_size = 0;
```



_Suggestion (ii):_
```C
    uint8_t* secret1      = NULL;
    size_t   secret1_size = 0;
```
___
*[`CI-Examples/ra-tls-secret-prov/src/secret_prov_client.c` line 63 at r2](https://reviewable.io/reviews/gramineproject/gramine/813#-N9kEDXECfUc_NEb_h_r:-N9kEDXECfUc_NEb_h_s:bz0pquv) ([raw file](https://github.com/gramineproject/gramine/blob/01542442d573bee0764f1f21c6b3a2a29fb05602/CI-Examples/ra-tls-secret-prov/src/secret_prov_client.c#L63)):*
> ```C
> out:
>     if (secret1) {
>         memset(secret1, 0, secret1_size);
> ```

This is a bad thing to showcase to users, compiler will delete this `memset()` anyways. Better not to showcase fake security, just delete it :)
___
*[`tools/sgx/ra-tls/secret_prov.h` line 82 at r2](https://reviewable.io/reviews/gramineproject/gramine/813#-N9kipVN5S6Iah7Zosf1:-N9kipVOCFr0r7y0Miv2:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/01542442d573bee0764f1f21c6b3a2a29fb05602/tools/sgx/ra-tls/secret_prov.h#L82)):*
> ```objc
>  * This function zeroes out the memory where provisioned secret is stored and frees it.
>  *
>  * This function must not be called again even if it returns an error. \p ctx is always freed.
> ```





_Suggestion:_
```objc
if it returned an error
```
___
*[`tools/sgx/ra-tls/secret_prov.h` line 99 at r2](https://reviewable.io/reviews/gramineproject/gramine/813#-N9kjdWX8FG1bLopgFqo:-N9kjdWYC-D6AUp8SH_v:b86a79t) ([raw file](https://github.com/gramineproject/gramine/blob/01542442d573bee0764f1f21c6b3a2a29fb05602/tools/sgx/ra-tls/secret_prov.h#L99)):*
> ```objc
>  * provisioning via secret_provision_start() which will obtain the secret from the server and
>  * save it in enclave memory. After that, the client can call this function to retrieve the
>  * copy of the secret from memory. The client must erase the memory of the retrieved copy of the
> ```

I wouldn't say "must", it's not really required nor making much sense.



_Code quote:_
```objc
The client must erase the memory of the retrieved copy
```
___
*[`tools/sgx/ra-tls/secret_prov_attest.c` line 136 at r1](https://reviewable.io/reviews/gramineproject/gramine/813#-N8hvhvv4iAm38fFBLWj:-N9kmrB44S2e0FhPiNoU:b48fpd6) ([raw file](https://github.com/gramineproject/gramine/blob/71fa466c2ac054387aa55c762643379bb6312544/tools/sgx/ra-tls/secret_prov_attest.c#L136)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. @mkow will hopefully be happy, he complained about the lack of any printouts recently. Now on errors smth like this is printed:
```
secret_provision_start: Secret Provisioning could not connect to any of the servers specified in SECRET_PROVISION_SERVERS
secret_provision_common_close: Secret Provisioning failed during connection close with mbedTLS error -28928
WARNING: Closing the secret-prov context failed with error -1.
secret_provision_constructor: Secret provisioning failed, terminating the whole process
```
</blockquote></details>

Yeah, better now :) Although in the future it would be better to print mbedtls errors decoded to strings, not just numbers (same for Linux and PAL errnos).
___
*[`tools/sgx/ra-tls/secret_prov_attest.c` line 308 at r2](https://reviewable.io/reviews/gramineproject/gramine/813#-N9kpwwICRPOc-HXvM1S:-N9kpwwICRPOc-HXvM1T:b-sll0v) ([raw file](https://github.com/gramineproject/gramine/blob/01542442d573bee0764f1f21c6b3a2a29fb05602/tools/sgx/ra-tls/secret_prov_attest.c#L308)):*
> ```C
>     memset(buf, 0, sizeof(buf));
>     ret = secret_provision_common_read(ssl, buf, sizeof(SECRET_PROVISION_RESPONSE) +
>                                                   sizeof(secret_size));
> ```

(or 4 spaces, just not _one_ :P)



_Suggestion:_
```C
    ret = secret_provision_common_read(ssl, buf, sizeof(SECRET_PROVISION_RESPONSE) +
                                                 sizeof(secret_size));
```


<!-- Sent from Reviewable.io -->

2022-08-18 12:45 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/813)* status: 4 of 7 files reviewed, 28 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @liangintel, and @mkow)

___
*[`CI-Examples/ra-tls-secret-prov/src/secret_prov_client.c` line 22 at r2](https://reviewable.io/reviews/gramineproject/gramine/813#-N9k99yD5GoJuMhWweVB:-N9kxRy-3t0ykeBf-7ny:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/01542442d573bee0764f1f21c6b3a2a29fb05602/CI-Examples/ra-tls-secret-prov/src/secret_prov_client.c#L22)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please pick one of these: (same with `secret2`)
</blockquote></details>

Done.
___
*[`CI-Examples/ra-tls-secret-prov/src/secret_prov_client.c` line 63 at r2](https://reviewable.io/reviews/gramineproject/gramine/813#-N9kEDXECfUc_NEb_h_r:-N9kxWuf4XKbubHu71xi:b7a30tx) ([raw file](https://github.com/gramineproject/gramine/blob/01542442d573bee0764f1f21c6b3a2a29fb05602/CI-Examples/ra-tls-secret-prov/src/secret_prov_client.c#L63)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This is a bad thing to showcase to users, compiler will delete this `memset()` anyways. Better not to showcase fake security, just delete it :)
</blockquote></details>

Done. Yeah, I was wondering if I should copy-paste this: https://github.com/gramineproject/gramine/blob/a014bc685bbb3cb8b37f90b482e6ab5de620be56/tools/sgx/ra-tls/secret_prov_attest.c#L61-L65

But I guess let's just leave the "proper memory erasing" to users.
___
*[`tools/sgx/ra-tls/secret_prov.h` line 82 at r2](https://reviewable.io/reviews/gramineproject/gramine/813#-N9kipVN5S6Iah7Zosf1:-N9kxnoVDJUE4JfOxzZC:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/01542442d573bee0764f1f21c6b3a2a29fb05602/tools/sgx/ra-tls/secret_prov.h#L82)):*
> ```objc
>  * This function zeroes out the memory where provisioned secret is stored and frees it.
>  *
>  * This function must not be called again even if it returns an error. \p ctx is always freed.
> ```

Done.
___
*[`tools/sgx/ra-tls/secret_prov.h` line 99 at r2](https://reviewable.io/reviews/gramineproject/gramine/813#-N9kjdWX8FG1bLopgFqo:-N9kxxd05GRR0xsvnLMG:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/01542442d573bee0764f1f21c6b3a2a29fb05602/tools/sgx/ra-tls/secret_prov.h#L99)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I wouldn't say "must", it's not really required nor making much sense.
</blockquote></details>

Done.
___
*[`tools/sgx/ra-tls/secret_prov_attest.c` line 136 at r1](https://reviewable.io/reviews/gramineproject/gramine/813#-N8hvhvv4iAm38fFBLWj:-N9kylE11NeW5DmE_ljb:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/71fa466c2ac054387aa55c762643379bb6312544/tools/sgx/ra-tls/secret_prov_attest.c#L136)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Yeah, better now :) Although in the future it would be better to print mbedtls errors decoded to strings, not just numbers (same for Linux and PAL errnos).
</blockquote></details>

Done.
___
*[`tools/sgx/ra-tls/secret_prov_attest.c` line 308 at r2](https://reviewable.io/reviews/gramineproject/gramine/813#-N9kpwwICRPOc-HXvM1S:-N9kytPtCzm_M16DKM9K:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/01542442d573bee0764f1f21c6b3a2a29fb05602/tools/sgx/ra-tls/secret_prov_attest.c#L308)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

(or 4 spaces, just not _one_ :P)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-18 13:57 UTC, mkow requested changes
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/813)* status: all files reviewed, 14 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @liangintel)

___
*[`tools/sgx/ra-tls/secret_prov_attest.c` line 308 at r2](https://reviewable.io/reviews/gramineproject/gramine/813#-N9kpwwICRPOc-HXvM1S:-N9lEemmEFJjYi1xtWIA:b-80bnvp) ([raw file](https://github.com/gramineproject/gramine/blob/01542442d573bee0764f1f21c6b3a2a29fb05602/tools/sgx/ra-tls/secret_prov_attest.c#L308)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Also we place operators in the new line in such situations, afaik
</blockquote></details>

True.
___
*[`tools/sgx/ra-tls/secret_prov_attest.c` line 60 at r3](https://reviewable.io/reviews/gramineproject/gramine/813#-N9l9VOX2D2wWo0AwOFx:-N9lEKre0fOUkQHqiBNQ:b-6l2n63) ([raw file](https://github.com/gramineproject/gramine/blob/40f7ed0a03f4571895c84423f7770a2a190fec90/tools/sgx/ra-tls/secret_prov_attest.c#L60)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This doesn't make much sense to me...
Why you only check `ctx == NULL` and not the rest of the arguments?
</blockquote></details>

I don't like these checks, why would `ctx == NULL` be allowed if it's not explicitly documented as such?
But it's a public API, so I won't block on this.


<!-- Sent from Reviewable.io -->

2022-08-18 14:27 UTC, dimakuv reviewed
> Reviewed 2 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/813)* status: 4 of 7 files reviewed, 14 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @liangintel, and @mkow)

___
*[`CI-Examples/ra-tls-secret-prov/src/secret_prov_client.c` line 64 at r3](https://reviewable.io/reviews/gramineproject/gramine/813#-N9l7DXq3g-wgr3XlPxW:-N9lHMv64xTwgLKMlQ4y:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/40f7ed0a03f4571895c84423f7770a2a190fec90/CI-Examples/ra-tls-secret-prov/src/secret_prov_client.c#L64)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please do not return negative errno codes from main.
</blockquote></details>

Done.
___
*[`CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c` line 55 at r3](https://reviewable.io/reviews/gramineproject/gramine/813#-N9l7zuPC8dSz_O3qzeN:-N9lHeyS65i_7krzhR8q:b-rmkr0c) ([raw file](https://github.com/gramineproject/gramine/blob/40f7ed0a03f4571895c84423f7770a2a190fec90/CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c#L55)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why would there be a reason to call it? I don't understand this comment.
</blockquote></details>

Done. Felt that users will see `_read` and `_write` function calls, and will automatically assume there needs to be a finalizing `_close` call. But maybe I'm just thinking nonsense.
___
*[`CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c` line 63 at r3](https://reviewable.io/reviews/gramineproject/gramine/813#-N9l8KTw56Ee4hZRyCtW:-N9lI-3IBH40r0-lPAMd:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/40f7ed0a03f4571895c84423f7770a2a190fec90/CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c#L63)):*
> ```C
> 
>     /* let's send another secret (just to show communication with secret-awaiting client) */
>     uint8_t buf[128] = {0};
> ```

Done.
___
*[`CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c` line 65 at r3](https://reviewable.io/reviews/gramineproject/gramine/813#-N9l8Pg440lBwtCLTcUk:-N9lI-PY4Gae61ZdeOE6:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/40f7ed0a03f4571895c84423f7770a2a190fec90/CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c#L65)):*
> ```C
>     uint8_t buf[128] = {0};
> 
>     ret = secret_provision_read(ctx, buf, sizeof(EXPECTED_STRING));
> ```

Done.
___
*[`tools/sgx/ra-tls/secret_prov.h` line 99 at r3](https://reviewable.io/reviews/gramineproject/gramine/813#-N9l8vXP7lrnYYqu3Dtb:-N9lIAeq-48-4qHlTQHH:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/40f7ed0a03f4571895c84423f7770a2a190fec90/tools/sgx/ra-tls/secret_prov.h#L99)):*
> ```objc
>  * provisioning via secret_provision_start() which will obtain the secret from the server and
>  * save it in enclave memory. After that, the client can call this function to retrieve the
>  * copy of the secret from memory. The client must free the copied-secret buffer afterwards.
> ```

Done.
___
*[`tools/sgx/ra-tls/secret_prov_attest.c` line 308 at r2](https://reviewable.io/reviews/gramineproject/gramine/813#-N9kpwwICRPOc-HXvM1S:-N9lKDY137mk5u4S00It:b-7qxs5k) ([raw file](https://github.com/gramineproject/gramine/blob/01542442d573bee0764f1f21c6b3a2a29fb05602/tools/sgx/ra-tls/secret_prov_attest.c#L308)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

True.
</blockquote></details>

Done. I guess this version is the most correct now :)
___
*[`tools/sgx/ra-tls/secret_prov_attest.c` line 60 at r3](https://reviewable.io/reviews/gramineproject/gramine/813#-N9l9VOX2D2wWo0AwOFx:-N9lIMtj754Sh4puC9ZF:bc92pj3) ([raw file](https://github.com/gramineproject/gramine/blob/40f7ed0a03f4571895c84423f7770a2a190fec90/tools/sgx/ra-tls/secret_prov_attest.c#L60)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I don't like these checks, why would `ctx == NULL` be allowed if it's not explicitly documented as such?
But it's a public API, so I won't block on this.
</blockquote></details>

Done. I'm adding these checks because this is a public API, so we should have some protection against dummy usage.
___
*[`tools/sgx/ra-tls/secret_prov_attest.c` line 134 at r3](https://reviewable.io/reviews/gramineproject/gramine/813#-N9lBGdWBNqtatOn5d_5:-N9lIfu8-K2rTD1c9STR:bsw6ze8) ([raw file](https://github.com/gramineproject/gramine/blob/40f7ed0a03f4571895c84423f7770a2a190fec90/tools/sgx/ra-tls/secret_prov_attest.c#L134)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`secret_size` is not set and could be garbage.
</blockquote></details>

Done. This is not strictly nesserary -- I'm only setting `secret` to NULL so that `free(ctx->secret)` doesn't break. But added just for sanity.
___
*[`tools/sgx/ra-tls/secret_prov_attest.c` line 159 at r3](https://reviewable.io/reviews/gramineproject/gramine/813#-N9l9wxk0x0uHVGdKl7t:-N9lIuDA3AyPbDeZAbdx:bxj84z0) ([raw file](https://github.com/gramineproject/gramine/blob/40f7ed0a03f4571895c84423f7770a2a190fec90/tools/sgx/ra-tls/secret_prov_attest.c#L159)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why this isn't `goto out`?
</blockquote></details>

Done. It was a bug.
___
*[`tools/sgx/ra-tls/secret_prov_attest.c` line 198 at r3](https://reviewable.io/reviews/gramineproject/gramine/813#-N9lANDk-79DPC6E89jN:-N9lK3BS3Z7rAmjvtSMj:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/40f7ed0a03f4571895c84423f7770a2a190fec90/tools/sgx/ra-tls/secret_prov_attest.c#L198)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This is bad, we mix mbedtls error codes with POSIX errno (`ECONNREFUXED` above)
</blockquote></details>

Done.
___
*[`tools/sgx/ra-tls/secret_prov_attest.c` line 204 at r3](https://reviewable.io/reviews/gramineproject/gramine/813#-N9lAByU0WUMPLH2IjGo:-N9lK47W3rArZ6ywzV2X:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/40f7ed0a03f4571895c84423f7770a2a190fec90/tools/sgx/ra-tls/secret_prov_attest.c#L204)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why this special casing? It's also wrong, it could have same value as some mbedtls error
</blockquote></details>

Done.
___
*[`tools/sgx/ra-tls/secret_prov_attest.c` line 187 at r4](https://reviewable.io/reviews/gramineproject/gramine/813#-N9lLI1g8IAGxxgTEyeE:-N9lLI1g8IAGxxgTEyeF:b-q3o4ss) ([raw file](https://github.com/gramineproject/gramine/blob/5b6710e3808501d57cd79c57a0c43bfc3cac1593/tools/sgx/ra-tls/secret_prov_attest.c#L187)):*
> ```C
>     char* str1;
>     for (str1 = servers; /*no condition*/; str1 = NULL) {
>         ret = MBEDTLS_ERR_NET_CONNECT_FAILED;
> ```

FYI: https://os.mbed.com/teams/sandbox/code/mbedtls/docs/tip/net_8h_source.html (line 38)


<!-- Sent from Reviewable.io -->

2022-08-18 14:30 UTC, boryspoplawski requested changes
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/813)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @liangintel, and @mkow)

___
*[`CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c` line 55 at r3](https://reviewable.io/reviews/gramineproject/gramine/813#-N9l7zuPC8dSz_O3qzeN:-N9lL_w90ZmbKpzH4dY1:b-9uvkr6) ([raw file](https://github.com/gramineproject/gramine/blob/40f7ed0a03f4571895c84423f7770a2a190fec90/CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c#L55)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. Felt that users will see `_read` and `_write` function calls, and will automatically assume there needs to be a finalizing `_close` call. But maybe I'm just thinking nonsense.
</blockquote></details>

I would say that if there is no open/create/init why would there be close?
___
*[`tools/sgx/ra-tls/secret_prov_attest.c` line 60 at r4](https://reviewable.io/reviews/gramineproject/gramine/813#-N9lLmaa5LSCv87YeO1C:-N9lLmaa5LSCv87YeO1D:b-buh0fz) ([raw file](https://github.com/gramineproject/gramine/blob/5b6710e3808501d57cd79c57a0c43bfc3cac1593/tools/sgx/ra-tls/secret_prov_attest.c#L60)):*
> ```C
> 
> int secret_provision_write(struct ra_tls_ctx* ctx, const uint8_t* buf, size_t size) {
>     if (!ctx || !buf)
> ```

What if `size == 0`? Isn't `but == NULL` valid then?
___
*[`tools/sgx/ra-tls/secret_prov_verify.c` line 135 at r4](https://reviewable.io/reviews/gramineproject/gramine/813#-N9lMBFiAUSWtczSHNpA:-N9lMBFiAUSWtczSHNpB:b-pb4i4k) ([raw file](https://github.com/gramineproject/gramine/blob/5b6710e3808501d57cd79c57a0c43bfc3cac1593/tools/sgx/ra-tls/secret_prov_verify.c#L135)):*
> ```C
> 
>     ret = secret_provision_common_write(&ssl, buf, sizeof(SECRET_PROVISION_RESPONSE)
>                                                        + sizeof(send_secret_size));
> ```

Why the 4 spaces? Not really blocking, but we never used such convention before


<!-- Sent from Reviewable.io -->

2022-08-18 14:59 UTC, dimakuv reviewed
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/813)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @liangintel, and @mkow)

___
*[`CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c` line 55 at r3](https://reviewable.io/reviews/gramineproject/gramine/813#-N9l7zuPC8dSz_O3qzeN:-N9lMcI00GMbDFlwnsyI:bgeo3n0) ([raw file](https://github.com/gramineproject/gramine/blob/40f7ed0a03f4571895c84423f7770a2a190fec90/CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c#L55)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I would say that if there is no open/create/init why would there be close?
</blockquote></details>

Yeah, I have weird thoughts.
___
*[`tools/sgx/ra-tls/secret_prov_attest.c` line 60 at r4](https://reviewable.io/reviews/gramineproject/gramine/813#-N9lLmaa5LSCv87YeO1C:-N9lPzLJC3PR_C92XYP9:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/5b6710e3808501d57cd79c57a0c43bfc3cac1593/tools/sgx/ra-tls/secret_prov_attest.c#L60)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

What if `size == 0`? Isn't `but == NULL` valid then?
</blockquote></details>

Done.
___
*[`tools/sgx/ra-tls/secret_prov_verify.c` line 135 at r4](https://reviewable.io/reviews/gramineproject/gramine/813#-N9lMBFiAUSWtczSHNpA:-N9lPyFN4HsYjQxU9nNW:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/5b6710e3808501d57cd79c57a0c43bfc3cac1593/tools/sgx/ra-tls/secret_prov_verify.c#L135)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why the 4 spaces? Not really blocking, but we never used such convention before
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2022-08-18 15:02 UTC, dimakuv reviewed
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/813)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @liangintel, and @mkow)

___
*[`CI-Examples/ra-tls-secret-prov/src/secret_prov_client.c` line 64 at r6](https://reviewable.io/reviews/gramineproject/gramine/813#-N9lTNiT1gs1FYedi6cp:-N9lTNiT1gs1FYedi6cq:b9y8rwt) ([raw file](https://github.com/gramineproject/gramine/blob/fe3bec45c344fbd236c5f764ecda204014101999/CI-Examples/ra-tls-secret-prov/src/secret_prov_client.c#L64)):*
> ```C
>     free(secret1);
>     secret_provision_close(ctx);
>     return ret == 0 ? 0 : 1;
> ```

FYI: This was my blooper.


<!-- Sent from Reviewable.io -->

2022-08-18 15:02 UTC, mkow submitted a review, later dismissed
> Reviewed 3 of 5 files at r4, 2 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/813)* status: all files reviewed, 4 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @liangintel)

___
*[`CI-Examples/ra-tls-secret-prov/src/secret_prov_client.c` line 64 at r3](https://reviewable.io/reviews/gramineproject/gramine/813#-N9l7DXq3g-wgr3XlPxW:-N9lSh3r1Q-Hp6jLURmt:b-17k1nv) ([raw file](https://github.com/gramineproject/gramine/blob/40f7ed0a03f4571895c84423f7770a2a190fec90/CI-Examples/ra-tls-secret-prov/src/secret_prov_client.c#L64)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Aren't you always returning 1 now?

Update: seems you fixed this before I finished the review :)



_Code quote:_
```C
return ret == 0 ?: 1;
```


<!-- Sent from Reviewable.io -->

2022-08-18 15:17 UTC, boryspoplawski submitted a review, later dismissed
> Reviewed 2 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/813)* status: all files reviewed, 3 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @liangintel)



<!-- Sent from Reviewable.io -->

2022-08-19 00:29 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r7, all commit messages.
> Dismissed @liangintel from a discussion.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/813)* status: all files reviewed, 2 unresolved discussions (waiting on @dimakuv)

___
*[`-- commits` line 11 at r1](https://reviewable.io/reviews/gramineproject/gramine/813#-N9jt1CMBdpv0Q9xLMUy):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I need to add here that `secret_provision_get()` returns a copy now.
</blockquote></details>

Done.
___
*[`-- commits` line 20 at r1](https://reviewable.io/reviews/gramineproject/gramine/813#-N9jt5J_1BcfmkAaN4pM):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

...But also prints the original mbedTLS error.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-19 00:35 UTC, boryspoplawski approved these changes
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/813)* status: all files reviewed, 2 unresolved discussions (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2022-08-19 06:41 UTC, dimakuv reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/813)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-08-19 06:58 UTC, merged