[tools/sgx] Enhance RA-TLS DCAP quote verification logic
gramineproject/gramine pull request #815
Opened 2022-08-03 06:09 UTC by kailun-qin

This patch adds/fixes the following in `ra_tls_verify_callback()` for DCAP:
- checking and warning `collateral_expiration_status` when the collateral is out-of-date
- failing fast when `verification_result` is considered a failure (i.e., not continuing the verification of other information, which is incorrect in such case)

2022-08-03 12:21 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/815)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @kailun-qin)

___
*[`tools/sgx/ra-tls/ra_tls_verify_dcap.c` line 138 at r1](https://reviewable.io/reviews/gramineproject/gramine/815#-N8Yd4AW2TIKG8s7lcFa:-N8Yd4AX9RpotXKz_KjO:bs9gdoh) ([raw file](https://github.com/gramineproject/gramine/blob/238fdb6211b7cd86bba30c1cd8ddc288dd687f10/tools/sgx/ra-tls/ra_tls_verify_dcap.c#L138)):*
> ```C
>     sgx_ql_qv_result_t verification_result = SGX_QL_QV_RESULT_UNSPECIFIED;
> 
>     /* call into libsgx_dcap_quoteverify to verify ECDSA/based SGX quote */
> ```

`ECDSA-based`
___
*[`tools/sgx/ra-tls/ra_tls_verify_dcap.c` line 150 at r1](https://reviewable.io/reviews/gramineproject/gramine/815#-N8YdYKY7HEduSuu037N:-N8YdYKY7HEduSuu037O:b-mbepro) ([raw file](https://github.com/gramineproject/gramine/blob/238fdb6211b7cd86bba30c1cd8ddc288dd687f10/tools/sgx/ra-tls/ra_tls_verify_dcap.c#L150)):*
> ```C
>     switch (verification_result) {
>         case SGX_QL_QV_RESULT_OK:
>             if (collateral_expiration_status != 0) {
> ```

FYI: For other reviewers, please read about this here: https://download.01.org/intel-sgx/latest/dcap-latest/linux/docs/Intel_SGX_ECDSA_QuoteLibReference_DCAP_API.pdf, page 33
___
*[`tools/sgx/ra-tls/ra_tls_verify_dcap.c` line 170 at r1](https://reviewable.io/reviews/gramineproject/gramine/815#-N8YdcyH2KfICX_PJ9KO:-N8YdcyI98wlzDaioxcv:blm05n9) ([raw file](https://github.com/gramineproject/gramine/blob/238fdb6211b7cd86bba30c1cd8ddc288dd687f10/tools/sgx/ra-tls/ra_tls_verify_dcap.c#L170)):*
> ```C
>     }
>     if (ret < 0) {
>         goto out;
> ```

FYI: What a stupid mistake...


<!-- Sent from Reviewable.io -->

2022-08-03 13:02 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/815)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2022-08-03 13:03 UTC, dimakuv commented
Jenkins, test this please

2022-08-03 22:59 UTC, boryspoplawski requested changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/815)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

___
*[`tools/sgx/ra-tls/ra_tls_verify_dcap.c` line 151 at r2](https://reviewable.io/reviews/gramineproject/gramine/815#-N8_vkUNE0BlSDx1WFyh:-N8_vkUNE0BlSDx1WFyi:b-baof69) ([raw file](https://github.com/gramineproject/gramine/blob/e7df634944404b9909fd12b6813c58e3e958ec0a/tools/sgx/ra-tls/ra_tls_verify_dcap.c#L151)):*
> ```C
>         case SGX_QL_QV_RESULT_OK:
>             if (collateral_expiration_status != 0) {
>                 INFO("WARNING: The collateral is out of date.\n");
> ```

Shouldnt this be a fatal error?


<!-- Sent from Reviewable.io -->

2022-08-04 04:05 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/815)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[`tools/sgx/ra-tls/ra_tls_verify_dcap.c` line 151 at r2](https://reviewable.io/reviews/gramineproject/gramine/815#-N8_vkUNE0BlSDx1WFyh:-N8b-Li--60QzYeS8sgO:bt3vzar) ([raw file](https://github.com/gramineproject/gramine/blob/e7df634944404b9909fd12b6813c58e3e958ec0a/tools/sgx/ra-tls/ra_tls_verify_dcap.c#L151)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Shouldnt this be a fatal error?
</blockquote></details>

The non-zero value of `collateral_expiration_status` just indicates one (or more) of the input collaterals has expired according to the input `expiration_check_date` (which is `current_time` in our case). I think generating a warning is fine, it depends on the policy (as mentioned/did in the DCAP sample: https://github.com/intel/SGXDataCenterAttestationPrimitives/blob/master/SampleCode/QuoteVerificationSample/App/App.cpp#L330-L341).


<!-- Sent from Reviewable.io -->

2022-08-04 04:12 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/815)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[`tools/sgx/ra-tls/ra_tls_verify_dcap.c` line 151 at r2](https://reviewable.io/reviews/gramineproject/gramine/815#-N8_vkUNE0BlSDx1WFyh:-N8b1Y7mB2eEt7tGsO96:b-4zs8sw) ([raw file](https://github.com/gramineproject/gramine/blob/e7df634944404b9909fd12b6813c58e3e958ec0a/tools/sgx/ra-tls/ra_tls_verify_dcap.c#L151)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

The non-zero value of `collateral_expiration_status` just indicates one (or more) of the input collaterals has expired according to the input `expiration_check_date` (which is `current_time` in our case). I think generating a warning is fine, it depends on the policy (as mentioned/did in the DCAP sample: https://github.com/intel/SGXDataCenterAttestationPrimitives/blob/master/SampleCode/QuoteVerificationSample/App/App.cpp#L330-L341).
</blockquote></details>

We can add some kind of optional env like `RA_TLS_ALLOW_OUTDATED_COLLATERAL_INSECURE` - is this sth you'd expect?


<!-- Sent from Reviewable.io -->

2022-08-04 04:16 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/815)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[`tools/sgx/ra-tls/ra_tls_verify_dcap.c` line 151 at r2](https://reviewable.io/reviews/gramineproject/gramine/815#-N8_vkUNE0BlSDx1WFyh:-N8b3OHs5mpDVct3V6V7:bv39wbn) ([raw file](https://github.com/gramineproject/gramine/blob/e7df634944404b9909fd12b6813c58e3e958ec0a/tools/sgx/ra-tls/ra_tls_verify_dcap.c#L151)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

We can add some kind of optional env like `RA_TLS_ALLOW_OUTDATED_COLLATERAL_INSECURE` - is this sth you'd expect?
</blockquote></details>

Well, it'll be a DCAP specifc option.


<!-- Sent from Reviewable.io -->

2022-08-04 06:58 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/815)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[`tools/sgx/ra-tls/ra_tls_verify_dcap.c` line 151 at r2](https://reviewable.io/reviews/gramineproject/gramine/815#-N8_vkUNE0BlSDx1WFyh:-N8bctOD8vX1LaTVbLXU:b-cs0em9) ([raw file](https://github.com/gramineproject/gramine/blob/e7df634944404b9909fd12b6813c58e3e958ec0a/tools/sgx/ra-tls/ra_tls_verify_dcap.c#L151)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Well, it'll be a DCAP specifc option.
</blockquote></details>

I think the warning is fine here. In SGX, we don't have a trusted time source (at least currently), so the attacker can always tweak the output of `time()` above so that we don't even hit case. So generally, relying on this expiration status is brittle.

We can add a TODO/FIXME comment here, but I'm also not sure it's worth it.

I don't like introducing another envvar for it, it just hides the real problem (of missing trusted time source).


<!-- Sent from Reviewable.io -->

2022-08-04 11:39 UTC, boryspoplawski submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/815)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @kailun-qin)

___
*[`tools/sgx/ra-tls/ra_tls_verify_dcap.c` line 151 at r2](https://reviewable.io/reviews/gramineproject/gramine/815#-N8_vkUNE0BlSDx1WFyh:-N8cdY_k9BQQU0HAHXKj:b-7xhyry) ([raw file](https://github.com/gramineproject/gramine/blob/e7df634944404b9909fd12b6813c58e3e958ec0a/tools/sgx/ra-tls/ra_tls_verify_dcap.c#L151)):*
>  In SGX, we don't have a trusted time source (at least currently), so the attacker can always tweak the output of time() above so that we don't even hit case.

But this is verification tool, which you (in most cases) use on a trusted machine (with trusted time)?

Unblocking anyway. 


<!-- Sent from Reviewable.io -->

2022-08-04 11:45 UTC, dimakuv submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/815)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

___
*[`tools/sgx/ra-tls/ra_tls_verify_dcap.c` line 151 at r2](https://reviewable.io/reviews/gramineproject/gramine/815#-N8_vkUNE0BlSDx1WFyh:-N8cezHm95jlUUBfzxU7:b-th64nc) ([raw file](https://github.com/gramineproject/gramine/blob/e7df634944404b9909fd12b6813c58e3e958ec0a/tools/sgx/ra-tls/ra_tls_verify_dcap.c#L151)):*
> But this is verification tool, which you (in most cases) use on a trusted machine (with trusted time)?

Yes, true, this is a good point. However, sometimes (e.g. mutual authentication) verification is also run inside the SGX enclave.


<!-- Sent from Reviewable.io -->

2022-08-10 10:18 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/815)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2022-08-15 22:01 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/815)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2022-08-15 22:03 UTC, mkow commented
Jenkins, retest this please

2022-08-16 06:07 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/815)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-08-16 06:08 UTC, merged