[LibOS] Release POSIX file locks on fds with `CLOEXEC` flag on `execve`
gramineproject/gramine pull request #837
Opened 2022-08-11 15:00 UTC by kailun-qin

Quickly adapted from a previous PR.

Resolves https://github.com/gramineproject/gramine/issues/836.

2022-08-11 15:24 UTC, boryspoplawski requested changes
> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/837)* status: 1 of 3 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @kailun-qin)

___
*[`libos/src/sys/libos_exec.c` line 21 at r1](https://reviewable.io/reviews/gramineproject/gramine/837#-N9CUskKCPp2p-XbjGwV:-N9CUskKCPp2p-XbjGwW:bo4o75f) ([raw file](https://github.com/gramineproject/gramine/blob/b5d69d69d4dddca22255201c37bd978cba270c5d/libos/src/sys/libos_exec.c#L21)):*
> ```C
>     if (fd_hdl->flags & FD_CLOEXEC) {
>         struct libos_handle* hdl = __detach_fd_handle(fd_hdl, NULL, map);
>         clear_posix_locks(hdl);
> ```

Is this safe to do? We are holding `map->lock` here and `posix_lock_set` takes some locks internally and can also sleep on IPC requests.


<!-- Sent from Reviewable.io -->

2022-08-11 15:43 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/837)* status: 1 of 3 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski)

___
*[`libos/src/sys/libos_exec.c` line 21 at r1](https://reviewable.io/reviews/gramineproject/gramine/837#-N9CUskKCPp2p-XbjGwV:-N9CWh5L590yt0fOT9s0:bowsvig) ([raw file](https://github.com/gramineproject/gramine/blob/b5d69d69d4dddca22255201c37bd978cba270c5d/libos/src/sys/libos_exec.c#L21)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Is this safe to do? We are holding `map->lock` here and `posix_lock_set` takes some locks internally and can also sleep on IPC requests.
</blockquote></details>

Just remembered that you seemed to have asked this before - it acutally depends on the order when locks are aquired, but this is usually fragile (i.e., better to avoid). Q: isn't `put_handle()` a similar case here?


<!-- Sent from Reviewable.io -->

2022-08-11 20:39 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/837)* status: 1 of 3 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @kailun-qin)

___
*[`libos/src/sys/libos_exec.c` line 21 at r1](https://reviewable.io/reviews/gramineproject/gramine/837#-N9CUskKCPp2p-XbjGwV:-N9DbwV_7f-LYrNmeZ28:bbnncb3) ([raw file](https://github.com/gramineproject/gramine/blob/b5d69d69d4dddca22255201c37bd978cba270c5d/libos/src/sys/libos_exec.c#L21)):*
> it acutally depends on the order when locks are aquired, but this is usually fragile (i.e., better to avoid). 

Yes. These are a) multiple locks b) they are all unrelated so it hard to define a order on them and maintain it through the whole codebase. We should rather avoid the problem (i.e. design the solution so we never have to take all of them).

> Q: isn't put_handle() a similar case here?

No, `put_handle` only decreases refcount and possibly releases an object. There is no (need for) locking there.


<!-- Sent from Reviewable.io -->

2022-08-17 10:20 UTC, dimakuv submitted a review, later dismissed
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/837)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski)

___
*[`libos/src/sys/libos_exec.c` line 21 at r1](https://reviewable.io/reviews/gramineproject/gramine/837#-N9CUskKCPp2p-XbjGwV:-N9fHl_cE90EBayHc-B8:b-iryrzj) ([raw file](https://github.com/gramineproject/gramine/blob/b5d69d69d4dddca22255201c37bd978cba270c5d/libos/src/sys/libos_exec.c#L21)):*
> can also sleep on IPC requests.

I don't think it is true: https://github.com/gramineproject/gramine/blob/2e700c1b795dd2430f0cec68ec9d2a1bd1099c18/libos/include/libos_fs_lock.h#L67-L68

> We should rather avoid the problem (i.e. design the solution so we never have to take all of them).

At this point (when we are in `close_on_exec()`), there is a single thread left that called into `exec()` syscall. I am fairly certain that the implementation of FS locks will never try to acquire `map->lock`. I'm also fairly certain that the `exec()` code here will never touch FS-lock-internal locks. So I feel that we are safe with the current PR. So maybe we could put a comment here explaining our rationale that no deadlocks can happen?

But I agree that this is brittle. But also, doesn't `detach_fd_handle()` and its callers have the exact same problem (of unrelated locks being taken in arbitrary order)?


<!-- Sent from Reviewable.io -->

2022-08-17 13:22 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/837)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv and @kailun-qin)

___
*[`libos/src/sys/libos_exec.c` line 21 at r1](https://reviewable.io/reviews/gramineproject/gramine/837#-N9CUskKCPp2p-XbjGwV:-N9fwO0J8f-6epZyN8Cp:b-3fuhvw) ([raw file](https://github.com/gramineproject/gramine/blob/b5d69d69d4dddca22255201c37bd978cba270c5d/libos/src/sys/libos_exec.c#L21)):*
>> can also sleep on IPC requests.
>> 
> I don't think it is true: 

Ok, the IPC operation will be finalized eventually, but sill make take a lot of time (this is not a blocker though).

> But also, doesn't detach_fd_handle() and its callers have the exact same problem (of unrelated locks being taken in arbitrary order)?

We don't call `detach_fd_handle` with any locks taken (except in `libos/src/fs/pipe/fs.c`, but i's also a hack).


<!-- Sent from Reviewable.io -->

2022-08-17 14:55 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/837)* status: 2 of 3 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[`libos/src/sys/libos_exec.c` line 21 at r1](https://reviewable.io/reviews/gramineproject/gramine/837#-N9CUskKCPp2p-XbjGwV:-N9gIF-fBtS88pg7diME:b-9rw3hu) ([raw file](https://github.com/gramineproject/gramine/blob/b5d69d69d4dddca22255201c37bd978cba270c5d/libos/src/sys/libos_exec.c#L21)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

>> can also sleep on IPC requests.
>> 
> I don't think it is true: 

Ok, the IPC operation will be finalized eventually, but sill make take a lot of time (this is not a blocker though).

> But also, doesn't detach_fd_handle() and its callers have the exact same problem (of unrelated locks being taken in arbitrary order)?

We don't call `detach_fd_handle` with any locks taken (except in `libos/src/fs/pipe/fs.c`, but i's also a hack).
</blockquote></details>

Thanks for checking! Added some comments for explanation.


<!-- Sent from Reviewable.io -->

2022-08-18 12:54 UTC, dimakuv reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/837)* status: 2 of 3 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`libos/src/sys/libos_exec.c` line 21 at r1](https://reviewable.io/reviews/gramineproject/gramine/837#-N9CUskKCPp2p-XbjGwV:-N9l-nbk8wb-cVGdufBQ:b-jnku0t) ([raw file](https://github.com/gramineproject/gramine/blob/b5d69d69d4dddca22255201c37bd978cba270c5d/libos/src/sys/libos_exec.c#L21)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I'm still against this solution. While this might work in the current state of affairs, we might accidentally break it (and debugging such issues is no fun). I would say we should stick to the old rules of either defining an ordering on locks or never taking them together and do not create any precedents.

cc @mkow we might need a tie-breaker

> At this point (when we are in close_on_exec()), there is a single thread left that called into exec() syscall. 

Single user app thread. There are also IPC worker and async helper thread (or whatever it's called).
</blockquote></details>

So what if we introduce a `walk_handle_map_no_locking()` version of the function? And we can call it in `close_cloexec_handle()`. In this case, there will be no `map->lock` held, and we won't need a lengthy comment that @kailun-qin added now.

This introduced version of the function may even be embedded here, because this is the only place where it's currently needed. @boryspoplawski ?


<!-- Sent from Reviewable.io -->

2022-08-18 14:26 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/837)* status: 2 of 3 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`libos/src/sys/libos_exec.c` line 21 at r1](https://reviewable.io/reviews/gramineproject/gramine/837#-N9CUskKCPp2p-XbjGwV:-N9lJ8yh0XUp0g58e31p:borjar8) ([raw file](https://github.com/gramineproject/gramine/blob/b5d69d69d4dddca22255201c37bd978cba270c5d/libos/src/sys/libos_exec.c#L21)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

So what if we introduce a `walk_handle_map_no_locking()` version of the function? And we can call it in `close_cloexec_handle()`. In this case, there will be no `map->lock` held, and we won't need a lengthy comment that @kailun-qin added now.

This introduced version of the function may even be embedded here, because this is the only place where it's currently needed. @boryspoplawski ?
</blockquote></details>

Yeah, that would probably work. I would just move `close_cloexec_handles` into `libos/src/bookkeep/libos_handle.c` and inline the loop in there.


<!-- Sent from Reviewable.io -->

2022-08-18 15:12 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/837)* status: 0 of 3 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[`libos/src/sys/libos_exec.c` line 21 at r1](https://reviewable.io/reviews/gramineproject/gramine/837#-N9CUskKCPp2p-XbjGwV:-N9lVaxG6cyb4ITvpe5o:bsmrizv) ([raw file](https://github.com/gramineproject/gramine/blob/b5d69d69d4dddca22255201c37bd978cba270c5d/libos/src/sys/libos_exec.c#L21)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Yeah, that would probably work. I would just move `close_cloexec_handles` into `libos/src/bookkeep/libos_handle.c` and inline the loop in there.
</blockquote></details>

Updated, PTAL if it's sth you'd expect.


<!-- Sent from Reviewable.io -->

2022-08-18 15:24 UTC, boryspoplawski requested changes
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/837)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

___
*[`libos/include/libos_handle.h` line 271 at r3](https://reviewable.io/reviews/gramineproject/gramine/837#-N9lX9QG3tE9fC3q6zIH:-N9lX9QG3tE9fC3q6zII:b1wk7yr) ([raw file](https://github.com/gramineproject/gramine/blob/43e365b80cc0885a1d9e0fb2af3a8badec3666fb/libos/include/libos_handle.h#L271)):*
> ```objc
>                                         struct libos_handle_map* map);
> struct libos_handle* detach_fd_handle(uint32_t fd, int* flags, struct libos_handle_map* map);
> void clear_posix_locks(struct libos_handle* handle);
> ```

This is not needed.
___
*[`libos/include/libos_handle.h` line 272 at r3](https://reviewable.io/reviews/gramineproject/gramine/837#-N9lX5KQ1g7b6TXXDKVX:-N9lX5KQ1g7b6TXXDKVY:b-t1vsyb) ([raw file](https://github.com/gramineproject/gramine/blob/43e365b80cc0885a1d9e0fb2af3a8badec3666fb/libos/include/libos_handle.h#L272)):*
> ```objc
> struct libos_handle* detach_fd_handle(uint32_t fd, int* flags, struct libos_handle_map* map);
> void clear_posix_locks(struct libos_handle* handle);
> void close_cloexec_handle(struct libos_handle_map* map);
> ```

`handles` (plural)
___
*[`libos/src/bookkeep/libos_handle.c` line 263 at r3](https://reviewable.io/reviews/gramineproject/gramine/837#-N9lXE8943XUKZQ67MY9:-N9lXE8943XUKZQ67MYA:brynr1l) ([raw file](https://github.com/gramineproject/gramine/blob/90f8b9d7eacfa1c9bc07089d9d00ea774888435f/libos/src/bookkeep/libos_handle.c#L263)):*
> ```C
> struct libos_handle* __detach_fd_handle(struct libos_fd_handle* fd, int* flags,
>                                         struct libos_handle_map* map) {
>     assert(locked(&map->lock));
> ```

Why did you remove this assert? It should be here
___
*[`libos/src/bookkeep/libos_handle.c` line 292 at r3](https://reviewable.io/reviews/gramineproject/gramine/837#-N9lXpQ798O7nRCq4vYq:-N9lXpQ8EcsNFrUcXZ74:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/43e365b80cc0885a1d9e0fb2af3a8badec3666fb/libos/src/bookkeep/libos_handle.c#L292)):*
> ```C
> }
> 
> void clear_posix_locks(struct libos_handle* handle) {
> ```





_Suggestion:_
```C
static void clear_posix_locks(struct libos_handle* handle) {
```
___
*[`libos/src/bookkeep/libos_handle.c` line 673 at r3](https://reviewable.io/reviews/gramineproject/gramine/837#-N9lY798AAZjTuCCOk9x:-N9lY798AAZjTuCCOk9y:b-qlupit) ([raw file](https://github.com/gramineproject/gramine/blob/43e365b80cc0885a1d9e0fb2af3a8badec3666fb/libos/src/bookkeep/libos_handle.c#L673)):*
> ```C
> 
> void close_cloexec_handle(struct libos_handle_map* map) {
>     for (uint32_t i = 0; map->fd_top != FD_NULL && i <= map->fd_top; i++) {
> ```

Where is locking? You need to take `map->lock`
___
*[`libos/src/bookkeep/libos_handle.c` line 681 at r3](https://reviewable.io/reviews/gramineproject/gramine/837#-N9lYHmK5plgicpk4NVW:-N9lYHmL578EMh-muvHa:b-tgi05a) ([raw file](https://github.com/gramineproject/gramine/blob/43e365b80cc0885a1d9e0fb2af3a8badec3666fb/libos/src/bookkeep/libos_handle.c#L681)):*
> ```C
>         if (fd_hdl->flags & FD_CLOEXEC) {
>             struct libos_handle* hdl = __detach_fd_handle(fd_hdl, NULL, map);
>             clear_posix_locks(hdl);
> ```

The idea is that you release lock here, but make sure that when you reaquire it, it's still safe to continue iteration (i.e. that nothing gets stale)


<!-- Sent from Reviewable.io -->

2022-08-18 16:01 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/837)* status: 0 of 3 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[`libos/include/libos_handle.h` line 271 at r3](https://reviewable.io/reviews/gramineproject/gramine/837#-N9lX9QG3tE9fC3q6zIH:-N9l_LCQBi_5okclE2ji:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/43e365b80cc0885a1d9e0fb2af3a8badec3666fb/libos/include/libos_handle.h#L271)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This is not needed.
</blockquote></details>

Done.
___
*[`libos/include/libos_handle.h` line 272 at r3](https://reviewable.io/reviews/gramineproject/gramine/837#-N9lX5KQ1g7b6TXXDKVX:-N9l_LZ0CsQHtPo5pxRA:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/43e365b80cc0885a1d9e0fb2af3a8badec3666fb/libos/include/libos_handle.h#L272)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`handles` (plural)
</blockquote></details>

Done.
___
*[`libos/src/bookkeep/libos_handle.c` line 263 at r3](https://reviewable.io/reviews/gramineproject/gramine/837#-N9lXE8943XUKZQ67MY9:-N9laDXDDEq6YHpuX1hj:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/90f8b9d7eacfa1c9bc07089d9d00ea774888435f/libos/src/bookkeep/libos_handle.c#L263)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why did you remove this assert? It should be here
</blockquote></details>

Done.
___
*[`libos/src/bookkeep/libos_handle.c` line 292 at r3](https://reviewable.io/reviews/gramineproject/gramine/837#-N9lXpQ798O7nRCq4vYq:-N9l_NsBBLaNPhE69rx4:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/43e365b80cc0885a1d9e0fb2af3a8badec3666fb/libos/src/bookkeep/libos_handle.c#L292)):*
> ```C
> }
> 
> void clear_posix_locks(struct libos_handle* handle) {
> ```

Done.
___
*[`libos/src/bookkeep/libos_handle.c` line 673 at r3](https://reviewable.io/reviews/gramineproject/gramine/837#-N9lY798AAZjTuCCOk9x:-N9l_jMRA2hh31kc7RsU:bipbblu) ([raw file](https://github.com/gramineproject/gramine/blob/43e365b80cc0885a1d9e0fb2af3a8badec3666fb/libos/src/bookkeep/libos_handle.c#L673)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Where is locking? You need to take `map->lock`
</blockquote></details>

Isn't `walk_handle_map_no_locking()` suggested (where `no map->lock` is held)?
___
*[`libos/src/bookkeep/libos_handle.c` line 681 at r3](https://reviewable.io/reviews/gramineproject/gramine/837#-N9lYHmK5plgicpk4NVW:-N9lcB7l69AWUwIbIWRV:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/43e365b80cc0885a1d9e0fb2af3a8badec3666fb/libos/src/bookkeep/libos_handle.c#L681)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

The idea is that you release lock here, but make sure that when you reaquire it, it's still safe to continue iteration (i.e. that nothing gets stale)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-18 16:09 UTC, boryspoplawski requested changes
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/837)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

___
*[`libos/src/bookkeep/libos_handle.c` line 673 at r3](https://reviewable.io/reviews/gramineproject/gramine/837#-N9lY798AAZjTuCCOk9x:-N9lh2hf-AGNpSua_Zg0:b3oovnw) ([raw file](https://github.com/gramineproject/gramine/blob/43e365b80cc0885a1d9e0fb2af3a8badec3666fb/libos/src/bookkeep/libos_handle.c#L673)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Isn't `walk_handle_map_no_locking()` suggested (where `no map->lock` is held)?
</blockquote></details>

I think the suggestion was that the callback is called without any locks.
___
*[`libos/src/bookkeep/libos_handle.c` line 294 at r4](https://reviewable.io/reviews/gramineproject/gramine/837#-N9lh_MJ4zicplbKMf7X:-N9lh_MJ4zicplbKMf7Y:b2pm316) ([raw file](https://github.com/gramineproject/gramine/blob/15c2af9ef4c0dc7cccdf192b4b439f0cd402dc16/libos/src/bookkeep/libos_handle.c#L294)):*
> ```C
> }
> 
> static void clear_posix_locks(struct libos_handle* handle) {
> ```

Actually, this function should return errors. 
___
*[`libos/src/bookkeep/libos_handle.c` line 690 at r4](https://reviewable.io/reviews/gramineproject/gramine/837#-N9lhG7oB77CP8lO4DDY:-N9lhG7p0sodTIFYWYxH:b9i09e) ([raw file](https://github.com/gramineproject/gramine/blob/15c2af9ef4c0dc7cccdf192b4b439f0cd402dc16/libos/src/bookkeep/libos_handle.c#L690)):*
> ```C
>             lock(&map->lock);
> 
>             put_handle(hdl);
> ```

Please move this before `lock`


<!-- Sent from Reviewable.io -->

2022-08-18 16:19 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/837)* status: 2 of 3 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[`libos/src/bookkeep/libos_handle.c` line 673 at r3](https://reviewable.io/reviews/gramineproject/gramine/837#-N9lY798AAZjTuCCOk9x:-N9ljtty8GEBH7JXokeV:b-3b3mqc) ([raw file](https://github.com/gramineproject/gramine/blob/43e365b80cc0885a1d9e0fb2af3a8badec3666fb/libos/src/bookkeep/libos_handle.c#L673)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I think the suggestion was that the callback is called without any locks.
</blockquote></details>

OK, got it. I misunderstood that...
___
*[`libos/src/bookkeep/libos_handle.c` line 294 at r4](https://reviewable.io/reviews/gramineproject/gramine/837#-N9lh_MJ4zicplbKMf7X:-N9ljr-CAGzQQM4NTgoC:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/15c2af9ef4c0dc7cccdf192b4b439f0cd402dc16/libos/src/bookkeep/libos_handle.c#L294)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Actually, this function should return errors. 
</blockquote></details>

Done.
___
*[`libos/src/bookkeep/libos_handle.c` line 690 at r4](https://reviewable.io/reviews/gramineproject/gramine/837#-N9lhG7oB77CP8lO4DDY:-N9lk4QX9z861rIxmE3E:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/15c2af9ef4c0dc7cccdf192b4b439f0cd402dc16/libos/src/bookkeep/libos_handle.c#L690)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please move this before `lock`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-18 17:15 UTC, boryspoplawski requested changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/837)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

___
*[`libos/src/bookkeep/libos_handle.c` line 673 at r3](https://reviewable.io/reviews/gramineproject/gramine/837#-N9lY798AAZjTuCCOk9x:-N9lw7yXAHbkFpyFvHC0:b-rhev3p) ([raw file](https://github.com/gramineproject/gramine/blob/43e365b80cc0885a1d9e0fb2af3a8badec3666fb/libos/src/bookkeep/libos_handle.c#L673)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

OK, got it. I misunderstood that...
</blockquote></details>

Yeah, the function name was mislading
___
*[`libos/src/bookkeep/libos_handle.c` line 329 at r5](https://reviewable.io/reviews/gramineproject/gramine/837#-N9lwd2096aox4TxloPs:-N9lwKMU4pB-fgyyhSdf:b-egnfbp) ([raw file](https://github.com/gramineproject/gramine/blob/f3eee8652a75b7aa0a8465763fb758d5dad5f050/libos/src/bookkeep/libos_handle.c#L329)):*
> ```C
>     unlock(&handle_map->lock);
> 
>     clear_posix_locks(handle);
> ```

I'm not sure what to do here. The previous code did not check for errors here and there's no easy way to do that, but I feel like we should handle it somehow?
___
*[`libos/src/bookkeep/libos_handle.c` line 691 at r5](https://reviewable.io/reviews/gramineproject/gramine/837#-N9lwDiQDw7-lKQayd-S:-N9lwDiQDw7-lKQayd-T:b-dw3cqm) ([raw file](https://github.com/gramineproject/gramine/blob/f3eee8652a75b7aa0a8465763fb758d5dad5f050/libos/src/bookkeep/libos_handle.c#L691)):*
> ```C
> 
>             unlock(&map->lock);
>             clear_posix_locks(hdl);
> ```

Please add error checking


<!-- Sent from Reviewable.io -->

2022-08-19 00:13 UTC, mkow requested changes
> Reviewed 2 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/837)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/837#-N9nMPsnBmWQfRtyMUqY:-N9nMPsnBmWQfRtyMUqZ:bn67dh2) (no related file):*
Could you add a test for this? (or change some existing, related one, to test this flow)

___
___
*[`libos/src/bookkeep/libos_handle.c` line 329 at r5](https://reviewable.io/reviews/gramineproject/gramine/837#-N9lwd2096aox4TxloPs:-N9nMzaW7rvjwdAHF2Vk:b42welt) ([raw file](https://github.com/gramineproject/gramine/blob/f3eee8652a75b7aa0a8465763fb758d5dad5f050/libos/src/bookkeep/libos_handle.c#L329)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I'm not sure what to do here. The previous code did not check for errors here and there's no easy way to do that, but I feel like we should handle it somehow?
</blockquote></details>

Please at least ignore the result more explicitly, i.e. with `(void)` cast.
___
*[`libos/src/bookkeep/libos_handle.c` line 681 at r5](https://reviewable.io/reviews/gramineproject/gramine/837#-N9nOV606gt4VZcsOANc:-N9nOV606gt4VZcsOANd:b71vvhr) ([raw file](https://github.com/gramineproject/gramine/blob/f3eee8652a75b7aa0a8465763fb758d5dad5f050/libos/src/bookkeep/libos_handle.c#L681)):*
> ```C
>     lock(&map->lock);
> 
>     for (uint32_t i = 0; map->fd_top != FD_NULL && i <= map->fd_top; i++) {
> ```

FYI/warning for reviewers: This way of iteration is dangerous, although currently I don't any direct bug resulting from it.
I think it's possible to reach `map->fd_top == UINT32_MAX`, in which case this loop will deallocate everything, and then start again from 0. This isn't a problem, because either `map->fd_top != FD_NULL` or `HANDLE_ALLOCATED(fd_hdl)` checks will stop it from doing anything on freed FDs.
Anyways, this quirk is probably hard to notice, and IMO it's risky to leave it like this, without a warning comment?


<!-- Sent from Reviewable.io -->

2022-08-19 00:34 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/837)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

___
*[`libos/src/bookkeep/libos_handle.c` line 681 at r5](https://reviewable.io/reviews/gramineproject/gramine/837#-N9nOV606gt4VZcsOANc:-N9nWEp0-OO1meTPnhDY:bwqgld1) ([raw file](https://github.com/gramineproject/gramine/blob/f3eee8652a75b7aa0a8465763fb758d5dad5f050/libos/src/bookkeep/libos_handle.c#L681)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

FYI/warning for reviewers: This way of iteration is dangerous, although currently I don't any direct bug resulting from it.
I think it's possible to reach `map->fd_top == UINT32_MAX`, in which case this loop will deallocate everything, and then start again from 0. This isn't a problem, because either `map->fd_top != FD_NULL` or `HANDLE_ALLOCATED(fd_hdl)` checks will stop it from doing anything on freed FDs.
Anyways, this quirk is probably hard to notice, and IMO it's risky to leave it like this, without a warning comment?
</blockquote></details>

I think `FD_NULL == UINT32_MAX` and it's done this way exactly to support cases like htis


<!-- Sent from Reviewable.io -->

2022-08-19 00:55 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/837)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/837#-N9nMPsnBmWQfRtyMUqY:-N9n_oSD1P2MMvpOnkbv:b-6c5jmj) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you add a test for this? (or change some existing, related one, to test this flow)
</blockquote></details>

I think the flow can be covered by the exisiting one: [pipe_ocloexec](https://github.com/gramineproject/gramine/blob/a014bc685bbb3cb8b37f90b482e6ab5de620be56/libos/test/regression/pipe_ocloexec.c). WDYT?

___
___
*[`libos/src/bookkeep/libos_handle.c` line 329 at r5](https://reviewable.io/reviews/gramineproject/gramine/837#-N9lwd2096aox4TxloPs:-N9nZCLPDzfD-YhpQlfG:bd8qhui) ([raw file](https://github.com/gramineproject/gramine/blob/f3eee8652a75b7aa0a8465763fb758d5dad5f050/libos/src/bookkeep/libos_handle.c#L329)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please at least ignore the result more explicitly, i.e. with `(void)` cast.
</blockquote></details>

What would you expect as the right behavior on errors? Currently, we simply warn w/ log on clear lock failures (in this introduced function, also here: https://github.com/gramineproject/gramine/blob/2e700c1b795dd2430f0cec68ec9d2a1bd1099c18/libos/src/sys/libos_exit.c#L99-L101).

I assume explicitly ignore the result should be OK?


<!-- Sent from Reviewable.io -->

2022-08-19 00:59 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/837)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[`libos/src/bookkeep/libos_handle.c` line 329 at r5](https://reviewable.io/reviews/gramineproject/gramine/837#-N9lwd2096aox4TxloPs:-N9nb0qS9laBxkbRH7d6:b-bpkrpn) ([raw file](https://github.com/gramineproject/gramine/blob/f3eee8652a75b7aa0a8465763fb758d5dad5f050/libos/src/bookkeep/libos_handle.c#L329)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

What would you expect as the right behavior on errors? Currently, we simply warn w/ log on clear lock failures (in this introduced function, also here: https://github.com/gramineproject/gramine/blob/2e700c1b795dd2430f0cec68ec9d2a1bd1099c18/libos/src/sys/libos_exit.c#L99-L101).

I assume explicitly ignore the result should be OK?
</blockquote></details>

Done by explicitly ignoring. Let me know if you really want to handle it in some way.
___
*[`libos/src/bookkeep/libos_handle.c` line 691 at r5](https://reviewable.io/reviews/gramineproject/gramine/837#-N9lwDiQDw7-lKQayd-S:-N9nb-4m6BiOhXP8uFar:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/f3eee8652a75b7aa0a8465763fb758d5dad5f050/libos/src/bookkeep/libos_handle.c#L691)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please add error checking
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-19 07:32 UTC, dimakuv requested changes
> Reviewed 1 of 3 files at r4, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/837)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/837#-N9nMPsnBmWQfRtyMUqY:-N9p-HO194tTeu8pFsCB:b-fxq4xv) (no related file):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

I think the flow can be covered by the exisiting one: [pipe_ocloexec](https://github.com/gramineproject/gramine/blob/a014bc685bbb3cb8b37f90b482e6ab5de620be56/libos/test/regression/pipe_ocloexec.c). WDYT?
</blockquote></details>

@kailun-qin I guess you can take `pipe_ocloexec.c` flow as an example, but you should create a new test. The test will open some tmp file (with CLOEXEC), then it will perform a fork, then a child process will acquire a lock and then perform a dummy `execve` (to close the tmp file and thus to release the taken lock), and the parent process will wait until the child is done and check whether it can acquire the same lock (the parent should succeed, otherwise the POSIX lock was not released on CLOEXEC).

Some primitives and operations can be peeked from here: https://github.com/gramineproject/gramine/blob/master/libos/test/regression/fcntl_lock.c

I would also verify first that the above test indeed fails on current master, and then verify that your PR fixes this test.

___


<!-- Sent from Reviewable.io -->

2022-08-19 10:26 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/837)* status: 3 of 5 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/837#-N9nMPsnBmWQfRtyMUqY:-N9pcsiS3_jRzRsaSXZB:b8kcmhk) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@kailun-qin I guess you can take `pipe_ocloexec.c` flow as an example, but you should create a new test. The test will open some tmp file (with CLOEXEC), then it will perform a fork, then a child process will acquire a lock and then perform a dummy `execve` (to close the tmp file and thus to release the taken lock), and the parent process will wait until the child is done and check whether it can acquire the same lock (the parent should succeed, otherwise the POSIX lock was not released on CLOEXEC).

Some primitives and operations can be peeked from here: https://github.com/gramineproject/gramine/blob/master/libos/test/regression/fcntl_lock.c

I would also verify first that the above test indeed fails on current master, and then verify that your PR fixes this test.
</blockquote></details>

Added a test, PTAL, thanks.

___


<!-- Sent from Reviewable.io -->

2022-08-19 10:52 UTC, boryspoplawski requested changes
> Reviewed 1 of 1 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/837)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @kailun-qin, and @mkow)

___
*[`libos/test/regression/fcntl_lock.c` line 441 at r7](https://reviewable.io/reviews/gramineproject/gramine/837#-N9pihmxB_539wUzEyY7:-N9pihmxB_539wUzEyY8:b-weawbo) ([raw file](https://github.com/gramineproject/gramine/blob/9a6ef2902fb6459ea221c79a45b9c078c3992d6a/libos/test/regression/fcntl_lock.c#L441)):*
> ```C
>     if (kill(pid, SIGKILL) < 0) {
>         err(1, "kill");
>     }
> ```

wait missing (I think this test has a wrapper for it)


<!-- Sent from Reviewable.io -->

2022-08-19 11:08 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/837)* status: 4 of 5 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[`libos/test/regression/fcntl_lock.c` line 441 at r7](https://reviewable.io/reviews/gramineproject/gramine/837#-N9pihmxB_539wUzEyY7:-N9pmc-H7tV8UGzI1rRq:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9a6ef2902fb6459ea221c79a45b9c078c3992d6a/libos/test/regression/fcntl_lock.c#L441)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

wait missing (I think this test has a wrapper for it)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-19 11:22 UTC, boryspoplawski approved these changes
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/837)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)



<!-- Sent from Reviewable.io -->

2022-08-19 13:32 UTC, dimakuv requested changes
> Reviewed 1 of 3 files at r4, 1 of 2 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/837)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/837#-N9nMPsnBmWQfRtyMUqY:-N9qIPSb6AIwB8nXS81m:brobcbv) (no related file):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Added a test, PTAL, thanks.
</blockquote></details>

Awesome test!

Did you verify that the newly added test indeed fails on the master branch of Gramine? Just for sanity.

___


<!-- Sent from Reviewable.io -->

2022-08-19 14:06 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/837)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/837#-N9nMPsnBmWQfRtyMUqY:-N9qPkJq5M5vWiikONIW:b-b0bgva) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Awesome test!

Did you verify that the newly added test indeed fails on the master branch of Gramine? Just for sanity.
</blockquote></details>

Yes, I've verified it against our lastest master (that it indeed fails) .

___


<!-- Sent from Reviewable.io -->

2022-08-19 22:13 UTC, mkow requested changes
Just one wording of a log message, otherwise looks good.

> Reviewed 1 of 1 files at r6, 1 of 2 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/837#-:-N9s9gA7BOh4EAHulVDu:ba6typ)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @kailun-qin)

___
*[`libos/src/bookkeep/libos_handle.c` line 681 at r5](https://reviewable.io/reviews/gramineproject/gramine/837#-N9nOV606gt4VZcsOANc:-N9s6mzOBClJgiJxWLvG:b568pco) ([raw file](https://github.com/gramineproject/gramine/blob/f3eee8652a75b7aa0a8465763fb758d5dad5f050/libos/src/bookkeep/libos_handle.c#L681)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I think `FD_NULL == UINT32_MAX` and it's done this way exactly to support cases like htis
</blockquote></details>

Ah, right, so that's how it works...
___
*[`libos/test/regression/fcntl_lock.c` line 406 at r8](https://reviewable.io/reviews/gramineproject/gramine/837#-N9s8gzb6v67sV-2Qlpt:-N9s8gzb6v67sV-2Qlpu:b-hoyihv) ([raw file](https://github.com/gramineproject/gramine/blob/c73ba5d25560039e7ccd5f44d0d4ac100a76622b/libos/test/regression/fcntl_lock.c#L406)):*
> ```C
> /* Test: parent waits for child to close a FD (thus release a lock) on exec. */
> static void test_parent_wait_child_cloexec(void) {
>     printf("testing parent wait child cloexec...\n");
> ```

This is so ungrammatical that I really wouldn't understand what's happening here without reading the source. It's just 5 nouns now glued together... ;)



_Code quote:_
```C
testing parent wait child cloexec
```


<!-- Sent from Reviewable.io -->

2022-08-20 00:13 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/837)* status: 4 of 5 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[`libos/test/regression/fcntl_lock.c` line 406 at r8](https://reviewable.io/reviews/gramineproject/gramine/837#-N9s8gzb6v67sV-2Qlpt:-N9s_zvY7MMkCqJwq4Ua:b-pmso9w) ([raw file](https://github.com/gramineproject/gramine/blob/c73ba5d25560039e7ccd5f44d0d4ac100a76622b/libos/test/regression/fcntl_lock.c#L406)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This is so ungrammatical that I really wouldn't understand what's happening here without reading the source. It's just 5 nouns now glued together... ;)
</blockquote></details>

;) Updated the wording, hope it's a bit better.


<!-- Sent from Reviewable.io -->

2022-08-22 07:49 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/837)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`libos/test/regression/fcntl_lock.c` line 406 at r8](https://reviewable.io/reviews/gramineproject/gramine/837#-N9s8gzb6v67sV-2Qlpt:-NA3WPhh1bDEK7Jg8QRS:b-y2o7ab) ([raw file](https://github.com/gramineproject/gramine/blob/c73ba5d25560039e7ccd5f44d0d4ac100a76622b/libos/test/regression/fcntl_lock.c#L406)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

;) Updated the wording, hope it's a bit better.
</blockquote></details>

But that string with 5 keywords explained the test perfectly with no redundancy :)


<!-- Sent from Reviewable.io -->

2022-08-22 07:49 UTC, dimakuv commented
Jenkins, test this please

2022-08-23 11:41 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/837)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

___
*[`libos/test/regression/fcntl_lock.c` line 406 at r8](https://reviewable.io/reviews/gramineproject/gramine/837#-N9s8gzb6v67sV-2Qlpt:-NA9UdgoA664GqhMe5mK:b-ucct20) ([raw file](https://github.com/gramineproject/gramine/blob/c73ba5d25560039e7ccd5f44d0d4ac100a76622b/libos/test/regression/fcntl_lock.c#L406)):*
> But that string with 5 keywords explained the test perfectly with no redundancy :)

I couldn't understand it, it was just 5 English nouns glued together without even any prepositions, which didn't parse to any meaningful sentence ¯\\\_(ツ)\_/¯ Maybe if you knew what the test does before reading this text you could understand it, but that's not how describing something works ;)


<!-- Sent from Reviewable.io -->

2022-08-24 08:27 UTC, dimakuv approved these changes
> Reviewed 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/837)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2022-08-24 08:27 UTC, dimakuv commented
Jenkins, test this please

2022-08-24 11:59 UTC, boryspoplawski approved these changes
> Reviewed 1 of 1 files at r9, 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/837)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-08-24 12:13 UTC, merged