[LibOS,PAL] Bookkeep PAL memory in LibOS
gramineproject/gramine pull request #839
Opened 2022-08-12 01:43 UTC by boryspoplawski

## Description of the changes 
This commit adds bookkeeping of PAL memory in LibOS which allows for removal of `loader.pal_internal_mem_size` manifest option and its hacky implementation.

I'm not particularly happy with the design and this code, but I couldn't think of anything better.

2022-08-12 01:58 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/839)* status: 0 of 83 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

___
*[`pal/include/pal/pal.h` line 149 at r1](https://reviewable.io/reviews/gramineproject/gramine/839#-N9EiDjc3H-dI9aC2QKt:-N9EiDjc3H-dI9aC2QKu:b-g4kz8j) ([raw file](https://github.com/gramineproject/gramine/blob/90f8b9d7eacfa1c9bc07089d9d00ea774888435f/pal/include/pal/pal.h#L149)):*
> ```objc
> /*! memory allocation flags */
> typedef uint32_t pal_alloc_flags_t; /* bitfield */
> #define PAL_ALLOC_RESERVE  0x1 /*!< Only reserve the memory */
> ```

FYI: this flag was never used.
___
*[`pal/include/pal/pal.h` line 150 at r1](https://reviewable.io/reviews/gramineproject/gramine/839#-N9EiFmoAFNQbf4nma6l:-N9EiFmp65f0VIlyhB3K:b5snb2a) ([raw file](https://github.com/gramineproject/gramine/blob/90f8b9d7eacfa1c9bc07089d9d00ea774888435f/pal/include/pal/pal.h#L150)):*
> ```objc
> typedef uint32_t pal_alloc_flags_t; /* bitfield */
> #define PAL_ALLOC_RESERVE  0x1 /*!< Only reserve the memory */
> #define PAL_ALLOC_INTERNAL 0x2 /*!< Allocate for PAL (valid only if #IN_PAL) */
> ```

FYI: since we now have correct bookkeeping of PAL memory this flag becomes obsolete and with it this whole type.
___
*[`pal/include/pal/pal.h` line 171 at r1](https://reviewable.io/reviews/gramineproject/gramine/839#-N9EiTzY7uTsmmxpGEYH:-N9EiTzY7uTsmmxpGEYI:buxku7y) ([raw file](https://github.com/gramineproject/gramine/blob/e31f1d10d5a8d6adcbb1e5660c3fb999cb5c2ad0/pal/include/pal/pal.h#L171)):*
> ```objc
>  * This function must not dynamically allocate any internal memory (must not use `malloc`)!
>  */
> int PalVirtualMemoryAlloc(void* addr, size_t size, pal_prot_flags_t prot);
> ```

FYI: I've changes the signature (and semantics?) of this function - it now must be provided with the actual address to be mapped. I think it's a good change - now the PAL API is simpler (the implementation of this function).


<!-- Sent from Reviewable.io -->

2022-08-15 23:36 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/839)* status: 0 of 86 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

___
*[`libos/src/bookkeep/libos_vma.c` line 1460 at r2](https://reviewable.io/reviews/gramineproject/gramine/839#-N9Yqaj65tFq-BHJwTqD:-N9Yqaj71DaMVM034zNg:b-38tm7l) ([raw file](https://github.com/gramineproject/gramine/blob/b4291e661b1e24094b4934518ca01c19c4859b59/libos/src/bookkeep/libos_vma.c#L1460)):*
> ```C
>         }
> 
>         // TODO:
> ```

There are 2 options:
1) leave it as it is (i.e. dummy memory ranges) (then add a comment here explaining how it works)
2) add another special checkpointing thingy (like now handles and memory content are), which would be a list/arary of memory ranges, sent before everything else and bookkeeped in child process. Effectively just split these dummy mem entries into dedicated structure and send/manage it separately
___
*[`pal/src/host/linux-common/file_utils.c` line 104 at r2](https://reviewable.io/reviews/gramineproject/gramine/839#-N9YrIuj28h1-6R0C59-:-N9YrIuj28h1-6R0C590:bb7p543) ([raw file](https://github.com/gramineproject/gramine/blob/b4291e661b1e24094b4934518ca01c19c4859b59/pal/src/host/linux-common/file_utils.c#L104)):*
> ```C
> }
> 
> // TODO: what do we do about it? leave it as? create another function which would get the buffer and have 2 versions?
> ```

this


<!-- Sent from Reviewable.io -->

2022-08-16 22:14 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/839)* status: 0 of 86 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

___
*[`pal/include/pal/pal.h` line 226 at r3](https://reviewable.io/reviews/gramineproject/gramine/839#-N9chpC61lrxRRQxaCcK:-N9chpC70w2vUQOrKdi7:bh1y9t3) ([raw file](https://github.com/gramineproject/gramine/blob/10e4d6629c3dcd5df72651a7a722cae123dd47be/pal/include/pal/pal.h#L226)):*
> ```objc
>  * TODO: `args` is only used by PAL regression tests, and should be removed at some point.
>  */
> int PalProcessCreate(const char** args, uintptr_t (*reserved_mem_ranges)[2],
> ```

What's the problem here? 
```                                                                                                                                                                                                                    
Documentation/pal/host-abi.rst:: WARNING: c:type reference target not found: reserved_mem_ranges
```
I have no idea what sphinx does not like here.
cc @woju 


<!-- Sent from Reviewable.io -->

2022-08-19 10:14 UTC, dimakuv requested changes
> Reviewed 4 of 83 files at r1, 2 of 16 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/839)* status: 6 of 86 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/839#-N9pVIFb8Ljp7AiqpO2o:-N9pVIFc3g7PJOyzDb4s:b52y94s) (no related file):*
Just for my own understanding: if there is a lot of nesting (one process creates a child, which creates another child, which creates another child...), then:
- the total amount of memory is not increasing, i.e. there is no inherent memory leakage -- because the childs will free some of the memory regions during their lifetime and thus some VMAs will disappear from the set-of-VMAs during the checkpointing.
- but there is a risk of memory fragmentation.

If there is indeed memory fragmentation inherent in this approach, do we care enough to do smth about it?

(I'm asking because previously PAL just reserved a huge chunk of memory and allocated all its internal objects in that chunk, both in parents and in childs. But with this PR, PAL may allocate arbitrary memory regions,  interleaved with LibOS memory regions -- sounds like a fragmentation problem.)

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/839#-N9p_zcr7akZrPDGUun8:-N9p_zcr7akZrPDGUun9:bn8vhx7) (no related file):*
FYI: Pushing my partial review now, just to not lose these comments accidentally. I will continue reviewing later.

___
___
*[`libos/include/libos_checkpoint.h` line 23 at r3](https://reviewable.io/reviews/gramineproject/gramine/839#-N9pZm5L1dUvTKkyPUyU:-N9pZm5L1dUvTKkyPUyV:b-kbs9s4) ([raw file](https://github.com/gramineproject/gramine/blob/10e4d6629c3dcd5df72651a7a722cae123dd47be/libos/include/libos_checkpoint.h#L23)):*
> ```objc
> extern char __migratable_end;
> 
> extern bool g_received_user_memory;
> ```

This need a lot of explanation. I currently don't understand this trick.

So you have this boolean that allows to learn whether we are in the very-early LibOS init logic in the child or we are already past the checkpoint restore logic.

In the very-early LibOS init logic, LibOS allocations are restricted by `[early_libos_mem_range_start, early_libos_mem_range_end)`. However, I don't understand -- there are only `-ENOMEM` failures if LibOS tries to allocate out of this range, and I see no code that hints LibOS to allocate in this range... What am I missing?

I guess it is important to have this "allowed range for early LibOS allocations" -- otherwise LibOS could allocate some internal objects anywhere and override received-from-parent memory (or that memory would override these internal objects, whatever). So I understand the rationale for this change.

By the way, how could it work before? I don't remember some limitations for LibOS on allocating memory during early init. Did it work by chance?
___
*[`libos/include/libos_checkpoint.h` line 61 at r3](https://reviewable.io/reviews/gramineproject/gramine/839#-N9pRW0d2OLYcjwgUV0N:-N9pRW0e8QEIvyQ4U-3F:b-uru78c) ([raw file](https://github.com/gramineproject/gramine/blob/10e4d6629c3dcd5df72651a7a722cae123dd47be/libos/include/libos_checkpoint.h#L61)):*
> ```objc
>     size_t size;
>     pal_prot_flags_t prot; /* combination of PAL_PROT_* flags */
>     bool dummy;
> ```

Took me some time to understand how this works. Please correct me if I'm wrong.

All LibOS VMAs in the current parent process are put in the checkpoint twice:
1. First as a `dummy=true` entry. In this case the memory contents are *not* sent during the checkpoint in the parent and are *only bookkept* during the restore in the child. Absolutely all VMAs are added this way (even those VMAs that do not have backing memory contents, like beyond-file-offset file-backed VMAs).
2. Then as a `dummy=false` entry. In this case the memory contents are sent during the checkpoint in the parent and are restored + bookkept during the restore in the child. Not all VMAs are added (e.g., beyond-file-offset file-backed VMAs are skipped).

The set of `dummy=true` entries is collected during the checkpoint in the parent and sent in the checkpoint, but also they are given to the PAL -- so that the PAL startup phase in the child process can reserve all these memory ranges (via host `mmap`).

All these shenanigans are done with a single purpose -- force the child process to reserve the same memory regions as in the parent, so that the child process (during the PAL init and LibOS init phases) does *not* accidentally re-use these memory regions for its own Gramine-internal objects.

---

Also, if I understand correctly, this `dummy` thingy is not directly related to the "PAL uses upcalls into LibOS for memory bookkeeping" change, which is the main point of this PR. This `dummy` thingy is only for this corner case of "don't accidentally re-use the already-used memory regions" (which allows to get rid of our dirty hack of `loader.pal_internal_mem_size`).

Is this understanding correct?
___
*[`libos/include/libos_vma.h` line 96 at r3](https://reviewable.io/reviews/gramineproject/gramine/839#-N9pWNDsArc8S0ZPlCmE:-N9pWNDt0gdz3voaiSFl:b2avt8s) ([raw file](https://github.com/gramineproject/gramine/blob/10e4d6629c3dcd5df72651a7a722cae123dd47be/libos/include/libos_vma.h#L96)):*
> ```objc
> 
> /* Shorthand for `bkeep_mmap_any_in_range` with the range
>  * [`g_pal_public_state->memory_address_start`, `g_pal_public_state->memory_address_end`). */
> ```

Some changes could be moved to separate PRs, like this one. It's a bit annoying to review this PR. Do we care enough to split this into a series of PRs?
___
*[`libos/src/libos_checkpoint.c` line 319 at r3](https://reviewable.io/reviews/gramineproject/gramine/839#-N9pWiRw9YaHcdjLr0qc:-N9pWiRw9YaHcdjLr0qd:b-t53vrl) ([raw file](https://github.com/gramineproject/gramine/blob/10e4d6629c3dcd5df72651a7a722cae123dd47be/libos/src/libos_checkpoint.c#L319)):*
> ```C
>             if (entry->dummy) {
>                 /* Allocate temporary VMA - it will be overwritten when actual VMA is restored from
>                  * the checkpointed data. */
> ```

Why do we care to bookkeep this memory region at this point? Won't it be like *immediately* overwritten in this same function, in some next iteration of this for loop?


<!-- Sent from Reviewable.io -->

2022-08-19 11:53 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/839)* status: 6 of 86 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/839#-N9pVIFb8Ljp7AiqpO2o:-N9pq5pc7JEoN3MuT7ao:b-ydv1jn) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Just for my own understanding: if there is a lot of nesting (one process creates a child, which creates another child, which creates another child...), then:
- the total amount of memory is not increasing, i.e. there is no inherent memory leakage -- because the childs will free some of the memory regions during their lifetime and thus some VMAs will disappear from the set-of-VMAs during the checkpointing.
- but there is a risk of memory fragmentation.

If there is indeed memory fragmentation inherent in this approach, do we care enough to do smth about it?

(I'm asking because previously PAL just reserved a huge chunk of memory and allocated all its internal objects in that chunk, both in parents and in childs. But with this PR, PAL may allocate arbitrary memory regions,  interleaved with LibOS memory regions -- sounds like a fragmentation problem.)
</blockquote></details>

I don't think it's that bad. After each fork the child process will start allocating from the highest address and fill all holes. Note that the PAL and LibOS memory is not checkpointed, so even if it ends up fragmented in the parent process it's not carried to the child. There is also user memory fragmentation, but it doesn't change that much with this PR - I would say that most of the internal memory comes from LibOS, not PAL, and that was already interleaved with user allocations before.

___
___
*[`libos/include/libos_checkpoint.h` line 23 at r3](https://reviewable.io/reviews/gramineproject/gramine/839#-N9pZm5L1dUvTKkyPUyU:-N9prPQv-dnHeIEPfcvb:bs6r35j) ([raw file](https://github.com/gramineproject/gramine/blob/10e4d6629c3dcd5df72651a7a722cae123dd47be/libos/include/libos_checkpoint.h#L23)):*
> This need a lot of explanation. I currently don't understand this trick.

Yeah, this deserves a comment for sure. Please point me out to such other places, which are not documented - this PR turned out much bigger than expected (hence took longer to prepare), so I did not comment the code until I was sure it's the final version and it ended up underdocumented.

> So you have this boolean that allows to learn whether we are in the very-early LibOS init logic in the child or we are already past the checkpoint restore logic.

Correct.

> In the very-early LibOS init logic, LibOS allocations are restricted by [early_libos_mem_range_start, early_libos_mem_range_end). However, I don't understand -- there are only -ENOMEM failures if LibOS tries to allocate out of this range, and I see no code that hints LibOS to allocate in this range... What am I missing?

LibOS does not try to allocate memory at fixed address (except for the checkpointing blob) - why would it? You can check `bkeep_mmap_any_in_range` - it literally has an if early_init and needs_internal_mem -> only allocate in this range.

> By the way, how could it work before? I don't remember some limitations for LibOS on allocating memory during early init. Did it work by chance?

Sheer luck, I guess.
___
*[`libos/include/libos_checkpoint.h` line 61 at r3](https://reviewable.io/reviews/gramineproject/gramine/839#-N9pRW0d2OLYcjwgUV0N:-N9ptElD3OZbk-AZV3xg:b-sv7zdu) ([raw file](https://github.com/gramineproject/gramine/blob/10e4d6629c3dcd5df72651a7a722cae123dd47be/libos/include/libos_checkpoint.h#L61)):*
I think this is the worst part of this PR. There's also a question whether we want to leave it as is or change to something else, there's a discussion about it somewhere in this PR.

> The set of dummy=true entries is collected during the checkpoint in the parent and sent in the checkpoint, but also they are given to the PAL -- so that the PAL startup phase in the child process can reserve all these memory ranges (via host mmap).

Correct, except PAL does not mmap them, it just doesn't allocate anything in these ranges (it just has this reserved ranges array).

> Also, if I understand correctly, this dummy thingy is not directly related to the "PAL uses upcalls into LibOS for memory bookkeeping" change, which is the main point of this PR. This dummy thingy is only for this corner case of "don't accidentally re-use the already-used memory regions" (which allows to get rid of our dirty hack of loader.pal_internal_mem_size).

Not really. The only purpose of this - let's be clear - hack is to introduce an ordering in checkpointing logic: VMAs list -> actual user memory content -> rest of objects. Actually the last two points does not need to be ordered, but it was already present in the checkpointing subsystem. How did it even work before, without such order, you might ask. The answer is I have no slightest clue. Gramine previously first received all user memory, without it being bookkept and only then received internal objects, including VMAs, which were bookkept only as they arrived. How did we survive that and no internal allocation overwrote the already received user memory? I guess we will never know.
___
*[`libos/include/libos_vma.h` line 96 at r3](https://reviewable.io/reviews/gramineproject/gramine/839#-N9pWNDsArc8S0ZPlCmE:-N9pvyYZ0jbaCDvv8UZL:b-drnbxk) ([raw file](https://github.com/gramineproject/gramine/blob/10e4d6629c3dcd5df72651a7a722cae123dd47be/libos/include/libos_vma.h#L96)):*
But this change doesn't make sense alone. Previously this range was indeed for user app memory, now it's for all kinds (including PAL internal memory). That's why I've changed the name.

> Some changes

Anything else? Please point me to them, maybe something is possible to be split.
___
*[`libos/src/libos_checkpoint.c` line 319 at r3](https://reviewable.io/reviews/gramineproject/gramine/839#-N9pWiRw9YaHcdjLr0qc:-N9pwSiP3GNNTdwYUm9t:bpkktuk) ([raw file](https://github.com/gramineproject/gramine/blob/10e4d6629c3dcd5df72651a7a722cae123dd47be/libos/src/libos_checkpoint.c#L319)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do we care to bookkeep this memory region at this point? Won't it be like *immediately* overwritten in this same function, in some next iteration of this for loop?
</blockquote></details>

Do you see any other bookkeeping in this function? No, because there is none and it all worked by an accident. See the comment above, where I've tried to explain this in details.
___
*[`libos/src/bookkeep/libos_vma.c` line 1460 at r2](https://reviewable.io/reviews/gramineproject/gramine/839#-N9Yqaj65tFq-BHJwTqD:-N9pwoqb40qZ_SZrOWD8:by7fand) ([raw file](https://github.com/gramineproject/gramine/blob/b4291e661b1e24094b4934518ca01c19c4859b59/libos/src/bookkeep/libos_vma.c#L1460)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

There are 2 options:
1) leave it as it is (i.e. dummy memory ranges) (then add a comment here explaining how it works)
2) add another special checkpointing thingy (like now handles and memory content are), which would be a list/arary of memory ranges, sent before everything else and bookkeeped in child process. Effectively just split these dummy mem entries into dedicated structure and send/manage it separately
</blockquote></details>

@dimakuv this is the comment with alternative approach


<!-- Sent from Reviewable.io -->

2022-08-19 13:25 UTC, dimakuv requested changes
> Reviewed 16 of 83 files at r1, 10 of 16 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/839)* status: 33 of 86 files reviewed, 40 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[`libos/src/libos_checkpoint.c` line 498 at r3](https://reviewable.io/reviews/gramineproject/gramine/839#-N9poiH4BlYKbd_AY7Jv:-N9poiH4BlYKbd_AY7Jw:b-yy5e99) ([raw file](https://github.com/gramineproject/gramine/blob/10e4d6629c3dcd5df72651a7a722cae123dd47be/libos/src/libos_checkpoint.c#L498)):*
> ```C
>     }
> 
>     /* Save the list in reversed oreder. */
> ```

`order`

Also, could you add a small comment as to why it matters?
___
*[`libos/src/libos_checkpoint.c` line 627 at r3](https://reviewable.io/reviews/gramineproject/gramine/839#-N9pq7LfB1MkPT3pNXvK:-N9pq7LfB1MkPT3pNXvL:brzubh9) ([raw file](https://github.com/gramineproject/gramine/blob/10e4d6629c3dcd5df72651a7a722cae123dd47be/libos/src/libos_checkpoint.c#L627)):*
> ```C
>         BUG();
>     }
>     bkeep_remove_tmp_vma(tmp_vma);
> ```

It was already like this, but don't we leak memory on failures? We allocate `cpstore.base`, but we only deallocate it here in the benign case.
___
*[`libos/src/bookkeep/libos_vma.c` line 1460 at r2](https://reviewable.io/reviews/gramineproject/gramine/839#-N9Yqaj65tFq-BHJwTqD:-N9ptlPc7SoHCWKMn9xY:b-4ftly1) ([raw file](https://github.com/gramineproject/gramine/blob/b4291e661b1e24094b4934518ca01c19c4859b59/libos/src/bookkeep/libos_vma.c#L1460)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

There are 2 options:
1) leave it as it is (i.e. dummy memory ranges) (then add a comment here explaining how it works)
2) add another special checkpointing thingy (like now handles and memory content are), which would be a list/arary of memory ranges, sent before everything else and bookkeeped in child process. Effectively just split these dummy mem entries into dedicated structure and send/manage it separately
</blockquote></details>

I am fine with the current version (option 1). This is, if I understood how it all works correctly (see my other comment).

Option 2 sounds like a lot of additional code for something anyhow obscure. So the comment is better.
___
*[`libos/src/bookkeep/libos_vma.c` line 1116 at r3](https://reviewable.io/reviews/gramineproject/gramine/839#-N9ptY4OA3B48bTbZYyf:-N9ptY4OA3B48bTbZYyg:bsvh0i0) ([raw file](https://github.com/gramineproject/gramine/blob/10e4d6629c3dcd5df72651a7a722cae123dd47be/libos/src/bookkeep/libos_vma.c#L1116)):*
> ```C
> 
> static int pal_mem_bkeep_alloc(size_t size, uintptr_t* out_addr) {
>     int ret;
> ```

No reason to have this separate variable declaration.
___
*[`libos/src/bookkeep/libos_vma.c` line 1121 at r3](https://reviewable.io/reviews/gramineproject/gramine/839#-N9ptGZ0E0kvtmaAfVu6:-N9ptGZ0E0kvtmaAfVu7:b-wp7ksw) ([raw file](https://github.com/gramineproject/gramine/blob/10e4d6629c3dcd5df72651a7a722cae123dd47be/libos/src/bookkeep/libos_vma.c#L1121)):*
> ```C
>                          /*file=*/NULL, /*offset=*/0, "pal internal memory", &addr);
>     if (ret < 0) {
>         return ret;
> ```

This returns UNIX error codes, but is used by the PAL. Is this normal? I see that in the PAL, you don't really use these error codes and return some hard-coded PAL error codes. But still, this is a mismatch.
___
*[`libos/src/bookkeep/libos_vma.c` line 1131 at r3](https://reviewable.io/reviews/gramineproject/gramine/839#-N9ptRmZ5ONivynfwZJ5:-N9ptRmZ5ONivynfwZJ6:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/10e4d6629c3dcd5df72651a7a722cae123dd47be/libos/src/bookkeep/libos_vma.c#L1131)):*
> ```C
>     int ret = bkeep_munmap((void*)addr, size, /*is_internal=*/true, &tmp_vma);
>     if (ret < 0) {
>         return ret;
> ```

ditto
___
*[`libos/src/bookkeep/libos_vma.c` line 1516 at r3](https://reviewable.io/reviews/gramineproject/gramine/839#-N9puEst7NiNeo_bcNZV:-N9puEst7NiNeo_bcNZW:b-360ky8) ([raw file](https://github.com/gramineproject/gramine/blob/10e4d6629c3dcd5df72651a7a722cae123dd47be/libos/src/bookkeep/libos_vma.c#L1516)):*
> ```C
>     }
> 
>     /* Checkpoint VMAs in descending order - checkpointing code requires it. */
> ```

Why exactly?
___
*[`libos/src/bookkeep/libos_vma.c` line 1517 at r3](https://reviewable.io/reviews/gramineproject/gramine/839#-N9puClZ-Ur2KukJk1Bq:-N9puClZ-Ur2KukJk1Br:b-6dy3zj) ([raw file](https://github.com/gramineproject/gramine/blob/10e4d6629c3dcd5df72651a7a722cae123dd47be/libos/src/bookkeep/libos_vma.c#L1517)):*
> ```C
> 
>     /* Checkpoint VMAs in descending order - checkpointing code requires it. */
>     for (struct libos_vma_info* vma = &vmas[count - 1];; vma--) {
> ```

`;;` -> `;`
___
*[`libos/src/sys/libos_clone.c` line 465 at r3](https://reviewable.io/reviews/gramineproject/gramine/839#-N9puqaF1nligQgKeeTv:-N9puqaF1nligQgKeeTw:b1ugbqg) ([raw file](https://github.com/gramineproject/gramine/blob/10e4d6629c3dcd5df72651a7a722cae123dd47be/libos/src/sys/libos_clone.c#L465)):*
> ```C
>     while (!__atomic_load_n(&new_args.is_thread_initialized, __ATOMIC_ACQUIRE)) {
>         CPU_RELAX();
>     }
> ```

But why? We already have a sync primitive in `new_args.initialize_event`. What does this `is_thread_initialized` bring additionally?
___
*[`pal/include/pal_internal.h` line 276 at r3](https://reviewable.io/reviews/gramineproject/gramine/839#-N9pvUzK4Cv5J54TfHqT:-N9pvUzK4Cv5J54TfHqU:b-ctff4j) ([raw file](https://github.com/gramineproject/gramine/blob/10e4d6629c3dcd5df72651a7a722cae123dd47be/pal/include/pal_internal.h#L276)):*
> ```objc
>     } while (0)
> 
> void pal_read_one_reserved_range(uintptr_t* last_range_start, uintptr_t* last_range_end);
> ```

Shouldn't arguments have `out_` prefix?
___
*[`pal/include/pal_internal.h` line 278 at r3](https://reviewable.io/reviews/gramineproject/gramine/839#-N9pvelZ4ac1BvnHf-Lc:-N9pvelZ4ac1BvnHf-Ld:b-5cpa6p) ([raw file](https://github.com/gramineproject/gramine/blob/10e4d6629c3dcd5df72651a7a722cae123dd47be/pal/include/pal_internal.h#L278)):*
> ```objc
> void pal_read_one_reserved_range(uintptr_t* last_range_start, uintptr_t* last_range_end);
> int pal_add_initial_range(uintptr_t addr, size_t size, pal_prot_flags_t prot, const char* comment);
> int pal_internal_memory_alloc(size_t size, void** out_ptr);
> ```

`out_ptr` -> `out_addr` (for uniformity with other places)
___
*[`pal/include/arch/x86_64/linux/pal_host_arch.h` line 29 at r3](https://reviewable.io/reviews/gramineproject/gramine/839#-N9pwCSb1Vpe-Wo6JqvJ:-N9pwCSc01HjA6smGTmN:bcn7yqg) ([raw file](https://github.com/gramineproject/gramine/blob/10e4d6629c3dcd5df72651a7a722cae123dd47be/pal/include/arch/x86_64/linux/pal_host_arch.h#L29)):*
> ```objc
> #endif
> 
> #define ARCH_HIGHEST_ADDR ((1ul << 47) - PAGE_SIZE)
> ```

What's the need for this macro? Just for sanity?
___
*[`pal/include/pal/pal.h` line 171 at r1](https://reviewable.io/reviews/gramineproject/gramine/839#-N9EiTzY7uTsmmxpGEYH:-N9py4Xi8MMdnEpIVeNk:b6mugz0) ([raw file](https://github.com/gramineproject/gramine/blob/e31f1d10d5a8d6adcbb1e5660c3fb999cb5c2ad0/pal/include/pal/pal.h#L171)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

FYI: I've changes the signature (and semantics?) of this function - it now must be provided with the actual address to be mapped. I think it's a good change - now the PAL API is simpler (the implementation of this function).
</blockquote></details>

Agreed, good change.
___
*[`pal/include/pal/pal.h` line 113 at r3](https://reviewable.io/reviews/gramineproject/gramine/839#-N9pwVGjCGVrIKCWWW4B:-N9pwVGjCGVrIKCWWW4C:b-oug12y) ([raw file](https://github.com/gramineproject/gramine/blob/10e4d6629c3dcd5df72651a7a722cae123dd47be/pal/include/pal/pal.h#L113 [...]

2022-08-21 16:32 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/839)* status: 26 of 88 files reviewed, 40 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[`libos/include/libos_checkpoint.h` line 23 at r3](https://reviewable.io/reviews/gramineproject/gramine/839#-N9pZm5L1dUvTKkyPUyU:-N9qRvXzDKLZkcVX7-TN:b-9m27dt) ([raw file](https://github.com/gramineproject/gramine/blob/10e4d6629c3dcd5df72651a7a722cae123dd47be/libos/include/libos_checkpoint.h#L23)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

> This need a lot of explanation. I currently don't understand this trick.

Yeah, this deserves a comment for sure. Please point me out to such other places, which are not documented - this PR turned out much bigger than expected (hence took longer to prepare), so I did not comment the code until I was sure it's the final version and it ended up underdocumented.

> So you have this boolean that allows to learn whether we are in the very-early LibOS init logic in the child or we are already past the checkpoint restore logic.

Correct.

> In the very-early LibOS init logic, LibOS allocations are restricted by [early_libos_mem_range_start, early_libos_mem_range_end). However, I don't understand -- there are only -ENOMEM failures if LibOS tries to allocate out of this range, and I see no code that hints LibOS to allocate in this range... What am I missing?

LibOS does not try to allocate memory at fixed address (except for the checkpointing blob) - why would it? You can check `bkeep_mmap_any_in_range` - it literally has an if early_init and needs_internal_mem -> only allocate in this range.

> By the way, how could it work before? I don't remember some limitations for LibOS on allocating memory during early init. Did it work by chance?

Sheer luck, I guess.
</blockquote></details>

Added a comment, let me know if and how can I expand it.
___
*[`libos/src/libos_checkpoint.c` line 498 at r3](https://reviewable.io/reviews/gramineproject/gramine/839#-N9poiH4BlYKbd_AY7Jv:-N9qWtIl5A1gPpPozsRl:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/10e4d6629c3dcd5df72651a7a722cae123dd47be/libos/src/libos_checkpoint.c#L498)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`order`

Also, could you add a small comment as to why it matters?
</blockquote></details>

Done.
___
*[`libos/src/libos_checkpoint.c` line 627 at r3](https://reviewable.io/reviews/gramineproject/gramine/839#-N9pq7LfB1MkPT3pNXvK:-N9qYKxj1INtwc5zSuB4:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/10e4d6629c3dcd5df72651a7a722cae123dd47be/libos/src/libos_checkpoint.c#L627)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

It was already like this, but don't we leak memory on failures? We allocate `cpstore.base`, but we only deallocate it here in the benign case.
</blockquote></details>

Done.
___
*[`libos/src/bookkeep/libos_vma.c` line 1460 at r2](https://reviewable.io/reviews/gramineproject/gramine/839#-N9Yqaj65tFq-BHJwTqD:-N9qZrsB8kaYnFEErgVE:b-c71xa9) ([raw file](https://github.com/gramineproject/gramine/blob/b4291e661b1e24094b4934518ca01c19c4859b59/libos/src/bookkeep/libos_vma.c#L1460)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I am fine with the current version (option 1). This is, if I understood how it all works correctly (see my other comment).

Option 2 sounds like a lot of additional code for something anyhow obscure. So the comment is better.
</blockquote></details>

Well, we create the array anyway, so it's not really that much additional code.
___
*[`libos/src/bookkeep/libos_vma.c` line 1116 at r3](https://reviewable.io/reviews/gramineproject/gramine/839#-N9ptY4OA3B48bTbZYyf:-N9qYcjg4Ry96pEUH70S:by0a7ln) ([raw file](https://github.com/gramineproject/gramine/blob/10e4d6629c3dcd5df72651a7a722cae123dd47be/libos/src/bookkeep/libos_vma.c#L1116)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

No reason to have this separate variable declaration.
</blockquote></details>

I think I did this because it didn't fit the line length limit, but whatever
___
*[`libos/src/bookkeep/libos_vma.c` line 1121 at r3](https://reviewable.io/reviews/gramineproject/gramine/839#-N9ptGZ0E0kvtmaAfVu6:-N9qZD43AHjiFOtARvjD:b3xr9ez) ([raw file](https://github.com/gramineproject/gramine/blob/10e4d6629c3dcd5df72651a7a722cae123dd47be/libos/src/bookkeep/libos_vma.c#L1121)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This returns UNIX error codes, but is used by the PAL. Is this normal? I see that in the PAL, you don't really use these error codes and return some hard-coded PAL error codes. But still, this is a mismatch.
</blockquote></details>

Well, this is LibOS code, so I think it should return LibOS (POSIX) error codes.
___
*[`libos/src/bookkeep/libos_vma.c` line 1131 at r3](https://reviewable.io/reviews/gramineproject/gramine/839#-N9ptRmZ5ONivynfwZJ5:-N9qZjOj9BGid9ApeHz5:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/10e4d6629c3dcd5df72651a7a722cae123dd47be/libos/src/bookkeep/libos_vma.c#L1131)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

ditto
___
*[`libos/src/bookkeep/libos_vma.c` line 1516 at r3](https://reviewable.io/reviews/gramineproject/gramine/839#-N9puEst7NiNeo_bcNZV:-N9q_Cqe4m_hGA3PhaAZ:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/10e4d6629c3dcd5df72651a7a722cae123dd47be/libos/src/bookkeep/libos_vma.c#L1516)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why exactly?
</blockquote></details>

Done.
___
*[`libos/src/bookkeep/libos_vma.c` line 1517 at r3](https://reviewable.io/reviews/gramineproject/gramine/839#-N9puClZ-Ur2KukJk1Bq:-N9q_D8Q6RVWTp-mq_Am:bvarjrt) ([raw file](https://github.com/gramineproject/gramine/blob/10e4d6629c3dcd5df72651a7a722cae123dd47be/libos/src/bookkeep/libos_vma.c#L1517)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`;;` -> `;`
</blockquote></details>

No, this is an empty loop condition. It was like that before, but let me make it cleaner.
___
*[`libos/src/sys/libos_clone.c` line 465 at r3](https://reviewable.io/reviews/gramineproject/gramine/839#-N9puqaF1nligQgKeeTv:-N9q_GLZ5XGlcHAtOwCv:brmc9ms) ([raw file](https://github.com/gramineproject/gramine/blob/10e4d6629c3dcd5df72651a7a722cae123dd47be/libos/src/sys/libos_clone.c#L465)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

But why? We already have a sync primitive in `new_args.initialize_event`. What does this `is_thread_initialized` bring additionally?
</blockquote></details>

Oh, this was supposed to go into a separate PR (added here only because it was triggered by this PR and I was verifying the fix works), but I forgot. Let me do that now (the explanation will be there).
PR: https://github.com/gramineproject/gramine/pull/852
I did not remove it from here - will do it at rebase - since it triggers on this PR.
___
*[`pal/include/pal_internal.h` line 276 at r3](https://reviewable.io/reviews/gramineproject/gramine/839#-N9pvUzK4Cv5J54TfHqT:-N9r2BDq0YXzjgegTfSu:b-5fb4e2) ([raw file](https://github.com/gramineproject/gramine/blob/10e4d6629c3dcd5df72651a7a722cae123dd47be/pal/include/pal_internal.h#L276)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Shouldn't arguments have `out_` prefix?
</blockquote></details>

These are in/out args, so no
___
*[`pal/include/pal [...]

2022-08-22 11:34 UTC, dimakuv requested changes
> Reviewed 27 of 83 files at r1, 2 of 16 files at r2, 5 of 12 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/839)* status: 60 of 88 files reviewed, 56 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[`pal/include/pal_internal.h` line 276 at r3](https://reviewable.io/reviews/gramineproject/gramine/839#-N9pvUzK4Cv5J54TfHqT:-NA3svd9-JK0RektEScI:bad6vqt) ([raw file](https://github.com/gramineproject/gramine/blob/10e4d6629c3dcd5df72651a7a722cae123dd47be/pal/include/pal_internal.h#L276)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

These are in/out args, so no
</blockquote></details>

This function signature is weird to me. Now that I looked at its source code, I understand how it works. But wouldn't it be better to have four arguments? Then it would be very clear, at the cost of just small modifications to the users of this func:
```
void pal_read_one_reserved_range(uintptr_t last_range_start, uintptr_t last_range_end,
                                  uintptr_t* out_range_start, uintptr_t* out_range_end);
```

Also maybe rename `pal_read_one_reserved_range` -> `pal_read_next_reserved_range`?
___
*[`pal/src/host/linux/pal_main.c` line 145 at r4](https://reviewable.io/reviews/gramineproject/gramine/839#-NA3l3YFEuXxHhk4brmB:-NA3l3YFEuXxHhk4brmC:blad6hb) ([raw file](https://github.com/gramineproject/gramine/blob/5091236738af030296f9d4454241cfae7e2337c7/pal/src/host/linux/pal_main.c#L145)):*
> ```C
>         INIT_FAIL("_PalSystemTimeQuery() failed: %d", ret);
> 
>     call_init_array();
> ```

FYI: A side note. I noticed this function and wondered what's the point. 

This func calls the constructors (`.init_array` funcs), and this is used to setup AddressSanitizer. ASan puts its own helper functions as constructors with priority 1. So we need to call these constructors (and we're not running as a normal Glibc executable, so we have to do this dirty work ourselves).
___
*[`pal/src/host/linux/pal_main.c` line 255 at r4](https://reviewable.io/reviews/gramineproject/gramine/839#-NA3n1g32K8jtrHq9Y0t:-NA3n1g32K8jtrHq9Y0u:biz0zwk) ([raw file](https://github.com/gramineproject/gramine/blob/90f8b9d7eacfa1c9bc07089d9d00ea774888435f/pal/src/host/linux/pal_main.c#L255)):*
> ```C
> #ifdef ASAN
>     ret = add_preloaded_range(ASAN_SHADOW_START, ASAN_SHADOW_START + ASAN_SHADOW_LENGTH,
>                               "asan_shadow");
> ```

We can remove this `ASAN_SHADOW` memory range addition because we already allocated this memory in the above `setup_asan()`, and `init_initial_memory_ranges()` finds this ASan memory range while traversing `/proc/maps`, right?

Same question for vDSO and vVar.
___
*[`pal/src/host/linux/pal_memory.c` line 62 at r4](https://reviewable.io/reviews/gramineproject/gramine/839#-NA3oDAbAaUQDujyXABg:-NA3oDAbAaUQDujyXABh:b-e3jfle) ([raw file](https://github.com/gramineproject/gramine/blob/90f8b9d7eacfa1c9bc07089d9d00ea774888435f/pal/src/host/linux/pal_memory.c#L62)):*
> ```C
>         assert(IS_ALIGNED(g_pal_internal_mem_used, g_page_size));
>         spinlock_unlock(&g_pal_internal_mem_lock);
>     }
> ```

FYI: I can't believe we got away with this amazing allocator for so long.
___
*[`pal/src/host/linux/pal_memory.c` line 66 at r4](https://reviewable.io/reviews/gramineproject/gramine/839#-NA3oT9W852VSGBgC00b:-NA3oT9W852VSGBgC00c:b-qev9j2) ([raw file](https://github.com/gramineproject/gramine/blob/90f8b9d7eacfa1c9bc07089d9d00ea774888435f/pal/src/host/linux/pal_memory.c#L66)):*
> ```C
>     assert(addr);
> 
>     int flags = PAL_MEM_FLAGS_TO_LINUX(alloc_type, prot | PAL_PROT_WRITECOPY);
> ```

What was the deal with this `PAL_PROT_WRITECOPY`? We just always forced everything to be `MAP_PRIVATE` allocated. Interesting.
___
*[`pal/src/host/linux/pal_memory.c` line 129 at r4](https://reviewable.io/reviews/gramineproject/gramine/839#-NA3pl0V1bg_hdXV7tBh:-NA3pl0V1bg_hdXV7tBi:b18vyst) ([raw file](https://github.com/gramineproject/gramine/blob/5091236738af030296f9d4454241cfae7e2337c7/pal/src/host/linux/pal_memory.c#L129)):*
> ```C
> 
> struct parsed_ranges {
>     uintptr_t vdso_start;
> ```

Maybe we should add a comment why we care about the vDSO range? It's because it contains the allowed-to-be-issued-to-host raw syscalls for our BPF filter.

Otherwise it's confusing to see that the vDSO range is here, but not all other ranges. Also, maybe we should state that the vDSO range is *also* added to the `g_initial_mem_ranges` so that LibOS doesn't stamp over it.
___
*[`pal/src/host/linux/pal_memory.c` line 132 at r4](https://reviewable.io/reviews/gramineproject/gramine/839#-NA3p5yuEJ2eVMOC1NBk:-NA3p5yuEJ2eVMOC1NBl:b-iblaif) ([raw file](https://github.com/gramineproject/gramine/blob/5091236738af030296f9d4454241cfae7e2337c7/pal/src/host/linux/pal_memory.c#L132)):*
> ```C
>     uintptr_t vdso_end;
>     uintptr_t highest_addr;
> };
> ```

Can we rename it to `parsed_ranges_metadata` or `parsed_ranges_info`? Now that we have `g_initial_mem_ranges`, I confuse these two.
___
*[`pal/src/host/linux/pal_memory.c` line 151 at r4](https://reviewable.io/reviews/gramineproject/gramine/839#-NA3rHOT5WEkZVEpxxL9:-NA3rHOT5WEkZVEpxxLA:b-sfo56h) ([raw file](https://github.com/gramineproject/gramine/blob/5091236738af030296f9d4454241cfae7e2337c7/pal/src/host/linux/pal_memory.c#L151)):*
> ```C
> }
> 
> int init_initial_memory_ranges(void) {
> ```

Maybe `init_memory_ranges`? It's not only about initial memory ranges (extracted from `/proc/self/maps`), but also about the overall available address space and the special vDSO handling.

Not blocking though.
___
*[`pal/src/host/linux-common/file_utils.c` line 104 at r2](https://reviewable.io/reviews/gramineproject/gramine/839#-N9YrIuj28h1-6R0C59-:-NA47q9v9jWSI8uXLyy6:b-ilo9jm) ([raw file](https://github.com/gramineproject/gramine/blob/b4291e661b1e24094b4934518ca01c19c4859b59/pal/src/host/linux-common/file_utils.c#L104)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

this
</blockquote></details>

I would just keep as-is. Currently it is only used to parse `/proc/self/maps` and `.map` (debugging symbols) files. 512 symbols per line in file sounds reasonable. No need for another version of this func.

Another option would be to have a static buffer here, and put a comment that this func is thread-unsafe. But this is a much worse variant.
___
*[`pal/src/host/linux-sgx/enclave_ocalls.c` line 984 at r4](https://reviewable.io/reviews/gramineproject/gramine/839#-NA491gj2a1TYjpULnNs:-NA491gj2a1TYjpULnNt:bxg4iun) ([raw file](https://github.com/gramineproject/gramine/blob/5091236738af030296f9d4454241cfae7e2337c7/pal/src/host/linux-sgx/enclave_ocalls.c#L984)):*
> ```C
> 
> int ocall_create_process(size_t nargs, const char** args, uintptr_t (*reserved_mem_ranges)[2],
>                          size_t reserved_mem_ranges_len, int* stream_fd) {
> ```

`out_stream_fd`
___
*[`pal/src/host/linux-sgx/enclave_pages.c` line 1 at r4](https://reviewable.io/reviews/gramineproject/gramine/839#-NA4A6l8EQ1mo9jCugFb:-NA4A6l8EQ1mo9jCugFc:b-2yyvvd) ([raw file](https://github.com/gramineproject/gramine/blob/90f8b9d7eacfa1c9bc07089d9d00ea774888435f/pal/src/host/linux-sgx/enclave_pages.c#L1)):*
> ```C
> #include "enclave_pages.h"
> ```

I was quite proud of this code. (Btw, we didn't have SPDX license text here? Bad.) RIP.
___
*[`pal/src/host/linux-sgx/host_ecalls.h` line 1 at r4](https://reviewable.io/reviews/gramineproject/gramine/839#-NA4AKp268_9sldBtc4N:-NA4AKp268_9sldBtc4O:b-1iy4vv) ([raw file](https://github.com/gramineproject/gramine/blob/5091236738af030296f9d4454241cfae7e2337c7/pal/src/host/linux-sgx/host_ecalls.h#L1)):*
> ```objc
> #pragma once
> ```

Add SPDX license here?
___
*[`pal [...]

2022-08-22 12:57 UTC, dimakuv requested changes
> Reviewed 7 of 12 files at r4.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/839)* status: 67 of 88 files reviewed, 37 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/839#-N9pVIFb8Ljp7AiqpO2o:-NA4OUY1Dql2RZzaJD4-:b-gxnet4) (no related file):*
>  I would say that most of the internal memory comes from LibOS, not PAL, and that was already interleaved with user allocations before

Good point. Yes, agreed, this PR doesn't increase the level of fragmentation.

___
___
*[`libos/include/libos_checkpoint.h` line 61 at r3](https://reviewable.io/reviews/gramineproject/gramine/839#-N9pRW0d2OLYcjwgUV0N:-NA4RtWU4GN5P2u0X1Fh:b2fz89r) ([raw file](https://github.com/gramineproject/gramine/blob/10e4d6629c3dcd5df72651a7a722cae123dd47be/libos/include/libos_checkpoint.h#L61)):*
> How did we survive that and no internal allocation overwrote the already received user memory? I guess we will never know.

The only explanation that comes to mind is that LibOS allocated a sufficiently large region for LibOS-internal memory at the very beginning, so all internal allocations were served from this region. And since this happened in the parent process, the first (highest) user-app memory range was created below this LibOS-internal memory range, and this "low-enough" user-app memory range was forwarded to children.

I'm fine with the current approach (as I also mention in the other comment).
___
*[`libos/include/libos_checkpoint.h` line 26 at r4](https://reviewable.io/reviews/gramineproject/gramine/839#-NA4PPq893LEhg0FVVpS:-NA4PPq893LEhg0FVVpT:b-cwzyvh) ([raw file](https://github.com/gramineproject/gramine/blob/5091236738af030296f9d4454241cfae7e2337c7/libos/include/libos_checkpoint.h#L26)):*
> ```objc
>  * Marks whether we have bookkeeped all user memory that is received during checkpointing. If there
>  * is no parent process it's always `true`.
>  * While this is set to `false`, LibOS is allwowed to allocate internal memory only in special range
> ```

`allowed`
___
*[`libos/include/libos_checkpoint.h` line 27 at r4](https://reviewable.io/reviews/gramineproject/gramine/839#-NA4QlwL-MFFQuz5NTnR:-NA4QlwL-MFFQuz5NTnS:b-n7znql) ([raw file](https://github.com/gramineproject/gramine/blob/5091236738af030296f9d4454241cfae7e2337c7/libos/include/libos_checkpoint.h#L27)):*
> ```objc
>  * is no parent process it's always `true`.
>  * While this is set to `false`, LibOS is allwowed to allocate internal memory only in special range
>  * `[early_libos_mem_range_start, early_libos_mem_range_end)`, which is will not overlap any user
> ```

`which is will not` -> `which is guaranteed to not`
___
*[`libos/include/libos_checkpoint.h` line 28 at r4](https://reviewable.io/reviews/gramineproject/gramine/839#-NA4QsUGD-foE5euNd4Y:-NA4QsUGD-foE5euNd4Z:b-q7b82b) ([raw file](https://github.com/gramineproject/gramine/blob/5091236738af030296f9d4454241cfae7e2337c7/libos/include/libos_checkpoint.h#L28)):*
> ```objc
>  * While this is set to `false`, LibOS is allwowed to allocate internal memory only in special range
>  * `[early_libos_mem_range_start, early_libos_mem_range_end)`, which is will not overlap any user
>  * memory that is checkpointed. If for some reason this range overlaps user memroy (e.g. a bug or
> ```

`user memory` -> `user-app memory` (or smth like this, I dislike the phrase "user memory")
___
*[`libos/include/libos_checkpoint.h` line 29 at r4](https://reviewable.io/reviews/gramineproject/gramine/839#-NA4RC_REpNk3uXOtsX4:-NA4RC_REpNk3uXOtsX5:b-8dxmr0) ([raw file](https://github.com/gramineproject/gramine/blob/5091236738af030296f9d4454241cfae7e2337c7/libos/include/libos_checkpoint.h#L29)):*
> ```objc
>  * `[early_libos_mem_range_start, early_libos_mem_range_end)`, which is will not overlap any user
>  * memory that is checkpointed. If for some reason this range overlaps user memroy (e.g. a bug or
>  * a malicious host), Gramine will terminate the child process (because checkpointing will fail).
> ```

Why would checkpointing fail? I don't see what exact code enforces this. Could you point to it?

UPDATE: You explained it in `pal_disable_early_memory_bookkeeping`.
___
*[`libos/include/libos_vma.h` line 96 at r3](https://reviewable.io/reviews/gramineproject/gramine/839#-N9pWNDsArc8S0ZPlCmE:-NA4SdVp6tQKS5f0DtWS:b-5sxihb) ([raw file](https://github.com/gramineproject/gramine/blob/10e4d6629c3dcd5df72651a7a722cae123dd47be/libos/include/libos_vma.h#L96)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

But this change doesn't make sense alone. Previously this range was indeed for user app memory, now it's for all kinds (including PAL internal memory). That's why I've changed the name.

> Some changes

Anything else? Please point me to them, maybe something is possible to be split.
</blockquote></details>

Actually, I changed my mind. After reviewing this amount of code, I don't want to re-review it :)
___
*[`libos/src/libos_checkpoint.c` line 319 at r3](https://reviewable.io/reviews/gramineproject/gramine/839#-N9pWiRw9YaHcdjLr0qc:-NA4UMWmABhHYye96NZD:b-1h1j15) ([raw file](https://github.com/gramineproject/gramine/blob/10e4d6629c3dcd5df72651a7a722cae123dd47be/libos/src/libos_checkpoint.c#L319)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Do you see any other bookkeeping in this function? No, because there is none and it all worked by an accident. See the comment above, where I've tried to explain this in details.
</blockquote></details>

Ok, I got it now. In this func, there is no VMA bookkeeping. The VMAs will be bookkeeped in one of the next functions (`restore_checkpoint()`) which in turn will get VMA internal objects and only then do the actual bookkeeping (in `BEGIN_RS_FUNC(vma)` func).

But in-between these two places in code, LibOS still needs to allocate some internal memory. And that's why we need this temporary bookkeeping -- otherwise LibOS internal allocs may override received user-app memory ranges.
___
*[`libos/src/libos_checkpoint.c` line 498 at r4](https://reviewable.io/reviews/gramineproject/gramine/839#-NA4VG401ScmRlLuJz-8:-NA4VG401ScmRlLuJz-9:b-3vusgv) ([raw file](https://github.com/gramineproject/gramine/blob/5091236738af030296f9d4454241cfae7e2337c7/libos/src/libos_checkpoint.c#L498)):*
> ```C
>     }
> 
>     /* Save the list in reversed order - PAL expect this list in descending order. See
> ```

`expects`
___
*[`libos/src/bookkeep/libos_vma.c` line 1460 at r2](https://reviewable.io/reviews/gramineproject/gramine/839#-N9Yqaj65tFq-BHJwTqD:-NA4W4sF348ecyxTwtLT:b20nat) ([raw file](https://github.com/gramineproject/gramine/blob/b4291e661b1e24094b4934518ca01c19c4859b59/libos/src/bookkeep/libos_vma.c#L1460)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Well, we create the array anyway, so it's not really that much additional code.
</blockquote></details>

I'm fine with option 1. The less code we change now, the easier it is to review.
___
*[`libos/src/bookkeep/libos_vma.c` line 1013 at r4](https://reviewable.io/reviews/gramineproject/gramine/839#-NA4QQp66ikYaENqG8IW:-NA4QQp66ikYaENqG8IX:b-d1okfy) ([raw file](https://github.com/gramineproject/gramine/blob/5091236738af030296f9d4454241cfae7e2337c7/libos/src/bookkeep/libos_vma.c#L1013)):*
> ```C
> 
>     if (!g_received_user_memory && flags & VMA_INTERNAL) {
>         /* Early init code must not overlap memory that will be restored during checkpointing. */
> ```

Maybe a more verbose comment?
```
/* Early LibOS init code must allocate memory only in [early_libos_mem_range_start, arly_libos_mem_range_end)
   (to not overlap memory that will be restored during checkpointing). */
```
 [...]

2022-08-22 13:25 UTC, dimakuv requested changes
> Reviewed 19 of 83 files at r1, 2 of 16 files at r2.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/839)* status: all files reviewed, 45 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @woju)

___
*[`pal/regression/memory.c` line 125 at r4](https://reviewable.io/reviews/gramineproject/gramine/839#-NA4iDpF3QIVmK_s-NyR:-NA4iDpF3QIVmK_s-NyS:b2pdt9i) ([raw file](https://github.com/gramineproject/gramine/blob/5091236738af030296f9d4454241cfae7e2337c7/pal/regression/memory.c#L125)):*
> ```C
>     COMPILER_BARRIER();
>     if (!g_write_failed) {
>         log_error("write to R mem at %p succeeded", addr2);
> ```

Maybe `unexpectedly succeeded`? So that it's clear that this is wrong.
___
*[`pal/regression/memory.c` line 151 at r4](https://reviewable.io/reviews/gramineproject/gramine/839#-NA4iO_-8lpheSRUCgg4:-NA4iO_-8lpheSRUCgg5:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/5091236738af030296f9d4454241cfae7e2337c7/pal/regression/memory.c#L151)):*
> ```C
>     COMPILER_BARRIER();
>     if (!g_write_failed) {
>         log_error("write to mem with no permissions at %p succeeded", addr3);
> ```

ditto
___
*[`pal/regression/memory.c` line 160 at r4](https://reviewable.io/reviews/gramineproject/gramine/839#-NA4iRIX2VWsmAHp5nA2:-NA4iRIX2VWsmAHp5nA3:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/5091236738af030296f9d4454241cfae7e2337c7/pal/regression/memory.c#L160)):*
> ```C
>     COMPILER_BARRIER();
>     if (!g_read_failed) {
>         log_error("read from mem with no permissions at %p succeeded", addr3);
> ```

ditto
___
*[`pal/regression/memory.c` line 163 at r4](https://reviewable.io/reviews/gramineproject/gramine/839#-NA4iTM63o1rPQpCNinu:-NA4iTM63o1rPQpCNinv:b-tpmj8f) ([raw file](https://github.com/gramineproject/gramine/blob/5091236738af030296f9d4454241cfae7e2337c7/pal/regression/memory.c#L163)):*
> ```C
>         PalProcessExit(1);
>     }
> ```

Don't you want to check that `x == 0`?
___
*[`pal/regression/memory_management.c` line 14 at r4](https://reviewable.io/reviews/gramineproject/gramine/839#-NA4gC4E9b42pgGNnm2G:-NA4gC4E9b42pgGNnm2H:b-xpg29y) ([raw file](https://github.com/gramineproject/gramine/blob/5091236738af030296f9d4454241cfae7e2337c7/pal/regression/memory_management.c#L14)):*
> ```C
> };
> 
> static struct vma g_vmas[0x100];
> ```

Please add a comment that this array is always kept in descending order
___
*[`pal/regression/memory_management.c` line 31 at r4](https://reviewable.io/reviews/gramineproject/gramine/839#-NA4gZf_3SSTJbxCqK4R:-NA4gZf_3SSTJbxCqK4S:b-89rdvw) ([raw file](https://github.com/gramineproject/gramine/blob/5091236738af030296f9d4454241cfae7e2337c7/pal/regression/memory_management.c#L31)):*
> ```C
>         assert(g_vmas[i - 1].begin >= g_vmas[i].end);
>         if (g_vmas[i - 1].begin - g_vmas[i].end >= size) {
>             assert(g_vmas_len + 1 <= ARRAY_LEN(g_vmas));
> ```

This assert looks useless since you already have an IF check at the beginning of this func
___
*[`pal/regression/memory_management.c` line 56 at r4](https://reviewable.io/reviews/gramineproject/gramine/839#-NA4hL-a315HQ1hGbT2_:-NA4hL-a315HQ1hGbT2a:btwdd5n) ([raw file](https://github.com/gramineproject/gramine/blob/5091236738af030296f9d4454241cfae7e2337c7/pal/regression/memory_management.c#L56)):*
> ```C
>             g_vmas_len--;
>             return 0;
>         } else if (!(end <= g_vmas[i].begin || g_vmas[i].end <= addr)) {
> ```

What's the point in the second expression?
___
*[`pal/regression/test_pal.py` line 345 at r4](https://reviewable.io/reviews/gramineproject/gramine/839#-NA4dh5N33KBedB8GArx:-NA4dh5N33KBedB8GAry:b-imjtzg) ([raw file](https://github.com/gramineproject/gramine/blob/5091236738af030296f9d4454241cfae7e2337c7/pal/regression/test_pal.py#L345)):*
> ```Python
>             # SGX1 does not support unmapping a page or changing its permission after enclave init.
>             # Therefore the memory protection and deallocation tests will fail. By utilizing SGX2
>             # it's possibile to fix this.
> ```

`possible`


<!-- Sent from Reviewable.io -->

2022-08-23 06:43 UTC, dimakuv requested changes
> Reviewed 20 of 20 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/839)* status: all files reviewed, 11 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/839#-NA4XYus1oIFhe4TtMxS:-NA8LyQKDsq2Mx_y16iC:buq4qsk) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I've just notice a big problem we have with this PR on Linux PAL. Because we only look at initial `/proc/self/maps`, we only get the initial stack size, but in theory the stack can grow. Since we do not take that into account, we mmap memory just above the stack (actually at the stack guard page), which can lead to nasty bugs if we ever deplete the initial stack space. I don't expect that to ever happen (we neither have huge nesting of calls, nor we allocate big objects on stack), but this is something we have to address.
I believe that what Linux does is that it never allocates memory in range `[stack_top - stack_limit; stack_top)`.
This wasn't a problem without this PR (well, it kind of was, but much smaller), because Gramine used to put PAL binary's address as max possible address. Usually (on most common kernel builds) the PAL binary is above stack (at lower addresses), so this effectively mitigated the problem, but that doesn't have to always be the case. And who knows what happens on non x64 archs...
</blockquote></details>

First of all, this sounds very unlikely to happen in practice.

But second, what about we do this at the very beginning of PAL startup:
1. Get the `stack_limit` value from Linux (I assume there is a way to get this constant)
2. Probe the stack until we reach this `stack_limit` -- i.e., grow the main-thread stack to the maximum.

Then `/proc/self/maps` will show the "final" stack size.

___
___
*[`libos/include/libos_checkpoint.h` line 28 at r4](https://reviewable.io/reviews/gramineproject/gramine/839#-NA4QsUGD-foE5euNd4Y:-NA8MmtMEOBPEmo5EKxZ:bnel8y0) ([raw file](https://github.com/gramineproject/gramine/blob/5091236738af030296f9d4454241cfae7e2337c7/libos/include/libos_checkpoint.h#L28)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

What's wrong with `user memory`? I dislike `user app memory`, mainly because it says the same, but is longer :)

cc @mkow  wdyt?
</blockquote></details>

I won't insist on this, but at least fix the typo: `memroy` -> `memory`
___
*[`libos/include/libos_vma.h` line 96 at r3](https://reviewable.io/reviews/gramineproject/gramine/839#-N9pWNDsArc8S0ZPlCmE:-NA8N-pPExSSBG46OZF2:b9lib63) ([raw file](https://github.com/gramineproject/gramine/blob/10e4d6629c3dcd5df72651a7a722cae123dd47be/libos/include/libos_vma.h#L96)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

All right, and for the future? :)
</blockquote></details>

For the future obviously, the smaller each PR, the better.
___
*[`libos/src/bookkeep/libos_vma.c` line 1460 at r2](https://reviewable.io/reviews/gramineproject/gramine/839#-N9Yqaj65tFq-BHJwTqD:-NA8NGVk19zBYm1TDz2H:b9kpki0) ([raw file](https://github.com/gramineproject/gramine/blob/b4291e661b1e24094b4934518ca01c19c4859b59/libos/src/bookkeep/libos_vma.c#L1460)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Yeah, but we can always leave a TODO or create a follow-up PR
</blockquote></details>

Sure, then please write a TODO comment.
___
*[`pal/regression/memory_management.c` line 14 at r5](https://reviewable.io/reviews/gramineproject/gramine/839#-NA8NhXWBUgCN2Lj60uM:-NA8NhXWBUgCN2Lj60uN:b8stfte) ([raw file](https://github.com/gramineproject/gramine/blob/d19099391877be89b5b57357f42254c436380475/pal/regression/memory_management.c#L14)):*
> ```C
> };
> 
> /* Array of allocated memroy ranges. Always kept sorted in descending order. */
> ```

You really like this word `memroy` :) Please change to `memory`
___
*[`pal/src/pal_memory.c` line 189 at r3](https://reviewable.io/reviews/gramineproject/gramine/839#-N9q88ek6TSkRLOUxCrW:-NA8OiYM7d1h5-W43ul7:b-h5q1yr) ([raw file](https://github.com/gramineproject/gramine/blob/10e4d6629c3dcd5df72651a7a722cae123dd47be/pal/src/pal_memory.c#L189)):*
> How about `find_non_reserved_range_below`?

Yes, this will be the most clear for me.
___
*[`pal/src/pal_memory.c` line 45 at r4](https://reviewable.io/reviews/gramineproject/gramine/839#-NA4_hgw894i2NKuy2hJ:-NA8O9jk7rjGx3DoM4zd:be2g70b) ([raw file](https://github.com/gramineproject/gramine/blob/5091236738af030296f9d4454241cfae7e2337c7/pal/src/pal_memory.c#L45)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

But it's not the case. In This phase even LibOS doesn't allocate anything. It's before `PalSetMemoryBookkeepingUpcalls` is called.
</blockquote></details>

Then I'm missing something. What happens in this phase then? LibOS surely does some `malloc`s. How are they served?

Ah, I think we misunderstood each other. Your whole comment here is purely about "PAL internal memory". In this case yes, there are no allocations in PAL internal memory. I'm unblocking.
___
*[`pal/src/host/linux/pal_memory.c` line 129 at r4](https://reviewable.io/reviews/gramineproject/gramine/839#-NA3pl0V1bg_hdXV7tBh:-NA8P-7c8wKS1huwvxr4:b-xcb2mg) ([raw file](https://github.com/gramineproject/gramine/blob/5091236738af030296f9d4454241cfae7e2337c7/pal/src/host/linux/pal_memory.c#L129)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Is it still applicable after the rename?
</blockquote></details>

It's ok now.
___
*[`pal/src/host/linux/pal_memory.c` line 151 at r4](https://reviewable.io/reviews/gramineproject/gramine/839#-NA3rHOT5WEkZVEpxxL9:-NA8PCy8EVH0a1wDi2ct:by8t3vl) ([raw file](https://github.com/gramineproject/gramine/blob/5091236738af030296f9d4454241cfae7e2337c7/pal/src/host/linux/pal_memory.c#L151)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Hmm, maybe `init_memory_bookkeeping()` or `init_memory_subsystem()` or something? I feel like the problem here is not with `initial` but with `memory_ranges`
</blockquote></details>

I like `init_memory_bookkeeping()`.
___
*[`pal/src/host/linux-sgx/host_ecalls.h` line 1 at r4](https://reviewable.io/reviews/gramineproject/gramine/839#-NA4AKp268_9sldBtc4N:-NA8QzdR7xf0Vz0LNass:b-nec2kw) ([raw file](https://github.com/gramineproject/gramine/blob/5091236738af030296f9d4454241cfae7e2337c7/pal/src/host/linux-sgx/host_ecalls.h#L1)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

It's a header without any implementation, but sure we could. I won't do this in this PR though, it's already big and the license is missing from half of stuff in `host/linux_sgx`
</blockquote></details>

Ok, makes sense.
___
*[`pal/src/host/linux-sgx/host_process.c` line 28 at r4](https://reviewable.io/reviews/gramineproject/gramine/839#-NA4B79g820kva1Agvkx:-NA8PefQ6I7x_8GpDqk_:b-r3ta8c) ([raw file](https://github.com/gramineproject/gramine/blob/5091236738af030296f9d4454241cfae7e2337c7/pal/src/host/linux-sgx/host_process.c#L28)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

1. No idea, I didn't write this code.
2. How would you imagine it? We could only have `char application_path[];` at the end, we cannot have `manifest`, since `application_path` is variable length array...
</blockquote></details>

Unblocking as this is not important anyway.

C doesn't allow two VLAs in a struct? Too lazy to check.
___
*[`pal/src/host/linux-sgx/pal_memory.c` li [...]

2022-08-24 08:45 UTC, dimakuv requested changes
> Reviewed 8 of 8 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/839)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/839#-NA4XYus1oIFhe4TtMxS:-NADyF_j3QT4_NcXLVv5:b-9j27l7) (no related file):*
> secondly because the stack could be unlimited.

Oh, unlimited stack... Then just some reasonable limit, like 2MB?

___
___
*[`libos/include/libos_vma.h` line 96 at r3](https://reviewable.io/reviews/gramineproject/gramine/839#-N9pWNDsArc8S0ZPlCmE:-NADzYg1BFbptPFu-xuQ:b-j7zkbl) ([raw file](https://github.com/gramineproject/gramine/blob/10e4d6629c3dcd5df72651a7a722cae123dd47be/libos/include/libos_vma.h#L96)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Yeah, but my question was which parts of this PR could be split into separate PRs
</blockquote></details>

Things that could be split in separate PRs:

1. Removal of unused arguments in PAL functions (as follow up)
2. `g_pal_public_state->user_address_end` -> `g_pal_public_state->memory_address_end` (as follow up)
3. `is_thread_initialized` -- you already did this
4. Pal regression `crt_init` (as follow up) -- you could call the `memory_init` func in the already-existing `.S` asm for now

That's all I could find.
___
*[`libos/src/bookkeep/libos_vma.c` line 1463 at r6](https://reviewable.io/reviews/gramineproject/gramine/839#-NADyk1n75TMrWtCFj5Z:-NADyk1n75TMrWtCFj5_:brk8y8t) ([raw file](https://github.com/gramineproject/gramine/blob/7b773414f8962f6d452a735d483244f74bab30f2/libos/src/bookkeep/libos_vma.c#L1463)):*
> ```C
> 
>         /*
>          * Add a dummy memory region, to the checkpoint. The content of this memory won't be
> ```

Remove `,`
___
*[`libos/src/bookkeep/libos_vma.c` line 1466 at r6](https://reviewable.io/reviews/gramineproject/gramine/839#-NADyfIUBVFFYWlpV5mD:-NADyfIUBVFFYWlpV5mE:b-3wvvbc) ([raw file](https://github.com/gramineproject/gramine/blob/7b773414f8962f6d452a735d483244f74bab30f2/libos/src/bookkeep/libos_vma.c#L1466)):*
> ```C
>          * actually sent, just this metadata. See `receive_memory_on_stream` for more info.
>          * This must come after all other `DO_CP_SIZE(memory, ...)` in this function, to maintain
>          * proper ordering (memory entries are appended to the beginning of a list in
> ```

`appended` -> `prepended`
___
*[`pal/src/host/linux-sgx/host_process.c` line 28 at r4](https://reviewable.io/reviews/gramineproject/gramine/839#-NA4B79g820kva1Agvkx:-NADz7NX7G3JIGNLx0I0:bxj6eln) ([raw file](https://github.com/gramineproject/gramine/blob/5091236738af030296f9d4454241cfae7e2337c7/pal/src/host/linux-sgx/host_process.c#L28)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

How would that work? How would this compile?
```
struct A {
    char x[];
    char y[];
};
struct A* a;
printf("%p", &a->y);
```
If you change both arrays to have size `char [0]` then it would compile, but `&a->x == &a->y` which is not what we want.
</blockquote></details>

Yeah, you're right.


<!-- Sent from Reviewable.io -->

2022-08-24 18:04 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/839)* status: 85 of 93 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/839#-NA4XYus1oIFhe4TtMxS:-NAG0Us83oVAbIeuQSWD:b-93dxyr) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> secondly because the stack could be unlimited.

Oh, unlimited stack... Then just some reasonable limit, like 2MB?
</blockquote></details>

I just added stack probing up to the limit of other threads stack  + a guard page. Hopefully enough.

___
___
*[`libos/include/libos_vma.h` line 96 at r3](https://reviewable.io/reviews/gramineproject/gramine/839#-N9pWNDsArc8S0ZPlCmE:-NAErFU2DZ1IoRE3WIxJ:b-47y14z) ([raw file](https://github.com/gramineproject/gramine/blob/10e4d6629c3dcd5df72651a7a722cae123dd47be/libos/include/libos_vma.h#L96)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Things that could be split in separate PRs:

1. Removal of unused arguments in PAL functions (as follow up)
2. `g_pal_public_state->user_address_end` -> `g_pal_public_state->memory_address_end` (as follow up)
3. `is_thread_initialized` -- you already did this
4. Pal regression `crt_init` (as follow up) -- you could call the `memory_init` func in the already-existing `.S` asm for now

That's all I could find.
</blockquote></details>

1. True, this I could have done, but it's just 1 argument to 1 function - probably less than 10 lines of changes...
2. As already said, I believe this change is tied to this PR and should be done here.
3. Yeah, blunder on my side, it was never supposed to be in this PR, sorry.
4. You are right, this could have been another PR. This is not a big change, but it's unrelated, should have been split.
___
*[`libos/src/bookkeep/libos_vma.c` line 1463 at r6](https://reviewable.io/reviews/gramineproject/gramine/839#-NADyk1n75TMrWtCFj5Z:-NAEsIOK57ihdS6ZghBN:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/7b773414f8962f6d452a735d483244f74bab30f2/libos/src/bookkeep/libos_vma.c#L1463)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Remove `,`
</blockquote></details>

Done.
___
*[`libos/src/bookkeep/libos_vma.c` line 1466 at r6](https://reviewable.io/reviews/gramineproject/gramine/839#-NADyfIUBVFFYWlpV5mD:-NAEsMa0CkDTHMBqH-2b:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/7b773414f8962f6d452a735d483244f74bab30f2/libos/src/bookkeep/libos_vma.c#L1466)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`appended` -> `prepended`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-24 21:04 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/839)* status: 84 of 93 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[`pal/include/pal/pal.h` line 226 at r3](https://reviewable.io/reviews/gramineproject/gramine/839#-N9chpC61lrxRRQxaCcK:-NAGeyEQ0PPhz3H1yUAZ:b3h7x39) ([raw file](https://github.com/gramineproject/gramine/blob/10e4d6629c3dcd5df72651a7a722cae123dd47be/pal/include/pal/pal.h#L226)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Pinging @woju again.
</blockquote></details>

Ok, this is something really wrong, but at least I've silenced the error


<!-- Sent from Reviewable.io -->

2022-08-25 07:59 UTC, dimakuv requested changes
> Reviewed 8 of 8 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/839)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[`libos/include/libos_vma.h` line 96 at r3](https://reviewable.io/reviews/gramineproject/gramine/839#-N9pWNDsArc8S0ZPlCmE:-NAIwXMO1qMgbkdy7a4B:b-8rwl36) ([raw file](https://github.com/gramineproject/gramine/blob/10e4d6629c3dcd5df72651a7a722cae123dd47be/libos/include/libos_vma.h#L96)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

1. True, this I could have done, but it's just 1 argument to 1 function - probably less than 10 lines of changes...
2. As already said, I believe this change is tied to this PR and should be done here.
3. Yeah, blunder on my side, it was never supposed to be in this PR, sorry.
4. You are right, this could have been another PR. This is not a big change, but it's unrelated, should have been split.
</blockquote></details>

These things that could be split are small in size, but for example the first one is one-liners in a dozen files. It's just very cumbersome to scroll through 100 files in one PR.

But it's more about me being scared of your big PRs, and I start grumbling :) In the end, there were indeed very few things that could be split without hurting the readability of this PR.
___
*[`pal/src/host/linux/pal_memory.c` line 166 at r8](https://reviewable.io/reviews/gramineproject/gramine/839#-NAIxrSQ-Rk3jXR65V1j:-NAIxrSQ-Rk3jXR65V1k:b-s16uoe) ([raw file](https://github.com/gramineproject/gramine/blob/5271ad6b75a9f78b7e2ba97f3637082f7bba8724/pal/src/host/linux/pal_memory.c#L166)):*
> ```C
>     }
> 
> #ifdef __hppa__
> ```

Wait what? Are we talking about https://en.wikipedia.org/wiki/PA-RISC? Is this an easter egg, or am I missing something?
___
*[`pal/src/host/linux/pal_memory.c` line 169 at r8](https://reviewable.io/reviews/gramineproject/gramine/839#-NAIyERN80db-jUbrxWX:-NAIyERN80db-jUbrxWY:b7kswve) ([raw file](https://github.com/gramineproject/gramine/blob/5271ad6b75a9f78b7e2ba97f3637082f7bba8724/pal/src/host/linux/pal_memory.c#L169)):*
> ```C
> #error "Your arch grows stack upwards, this is not supported."
> #endif
>     /* Allocate a guard page above the stack. We do not support further stack auto growth. */
> ```

Actually, how does Linux react to this artifical guard page? Linux will not overwrite this guard-page mapping? In other words, will this guard page truly stop Linux from auto-increasing the stack?
___
*[`pal/src/host/linux/pal_memory.c` line 176 at r8](https://reviewable.io/reviews/gramineproject/gramine/839#-NAIyWfq8Urzaf-EsxwX:-NAIyWfq8Urzaf-EsxwY:b-346uwy) ([raw file](https://github.com/gramineproject/gramine/blob/5271ad6b75a9f78b7e2ba97f3637082f7bba8724/pal/src/host/linux/pal_memory.c#L176)):*
> ```C
>         ret = PTR_TO_ERR(ptr);
>         log_error("failed to map a stack guard page: %d", ret);
>         return ret;
> ```

Aren't we supposed to return PAL error codes?
___
*[`pal/src/host/linux/pal_memory.c` line 178 at r8](https://reviewable.io/reviews/gramineproject/gramine/839#-NAIylLaEMroyv2W18JY:-NAIylLaEMroyv2W18JZ:bu964k3) ([raw file](https://github.com/gramineproject/gramine/blob/5271ad6b75a9f78b7e2ba97f3637082f7bba8724/pal/src/host/linux/pal_memory.c#L178)):*
> ```C
>         return ret;
>     }
>     ret = pal_add_initial_range((uintptr_t)ptr, PAGE_SIZE, /*prot=*/0, "stack guard");
> ```

Wouldn't it make more sense to perform `mmap(guard page)` before `parse_proc_maps()`, and then we won't need to call this explicitly?

Also, maybe move `probe_stack()` into this func `init_memory_bookkeeping()`? I'm not sure where it logically belongs though. Maybe it's better to keep it in the "main init" logic.
___
*[`pal/src/host/linux-common/arch/x86_64/stack_probe.nasm` line 8 at r8](https://reviewable.io/reviews/gramineproject/gramine/839#-NAJ-GZC6j5Cu6cAL72p:-NAJ-GZC6j5Cu6cAL72q:b-74g8v4) ([raw file](https://github.com/gramineproject/gramine/blob/5271ad6b75a9f78b7e2ba97f3637082f7bba8724/pal/src/host/linux-common/arch/x86_64/stack_probe.nasm#L8)):*
> ```Assembly
> section .text
> 
> ; void probe_stack(size_t size)
> ```

I just noticed that this function starts probing from *somewhere inside the stack* (whatever RSP currently points to), not from the beginning of the stack. It doesn't matter much, so I'm not blocking.
___
*[`pal/src/host/linux-sgx/host_main.c` line 1008 at r8](https://reviewable.io/reviews/gramineproject/gramine/839#-NAJ-eS67BvdS1R-pOBR:-NAJ-eS67BvdS1R-pOBS:b-8is1mu) ([raw file](https://github.com/gramineproject/gramine/blob/5271ad6b75a9f78b7e2ba97f3637082f7bba8724/pal/src/host/linux-sgx/host_main.c#L1008)):*
> ```C
> static void force_linux_to_grow_stack(void) {
>     probe_stack(THREAD_STACK_SIZE);
> }
> ```

Maybe remove the func `force_linux_to_grow_stack()`? And move this func's comment (+ possibly remove some unnecessary details) to the actual place in code where we call probe the stack.


<!-- Sent from Reviewable.io -->

2022-08-25 12:43 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/839)* status: 88 of 93 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[`libos/include/libos_vma.h` line 96 at r3](https://reviewable.io/reviews/gramineproject/gramine/839#-N9pWNDsArc8S0ZPlCmE:-NAJuWhZDIiiaaVPoGgd:b-shc1h0) ([raw file](https://github.com/gramineproject/gramine/blob/10e4d6629c3dcd5df72651a7a722cae123dd47be/libos/include/libos_vma.h#L96)):*
> but for example the first one is one-liners in a dozen files. It's just very cumbersome to scroll through 100 files in one PR.

It wouldn't help - we change other parameters in these functions anyway (so in fact this would actually double the diff, because you would have these 100 files in 2 PRs :smile: )

> But it's more about me being scared of your big PRs, and I start grumbling :) In the end, there were indeed very few things that could be split without hurting the readability of this PR.

Well, I should be splitting them. It's just that I usually don't know what will be needed and I end up stashing everything in one branch until it works. I guess I should then start going through changes and checking what can be split, it shouldn't be that hard
___
*[`pal/src/host/linux/pal_memory.c` line 166 at r8](https://reviewable.io/reviews/gramineproject/gramine/839#-NAIxrSQ-Rk3jXR65V1j:-NAJvN6j1L2Niu1Wjm19:btaam4c) ([raw file](https://github.com/gramineproject/gramine/blob/5271ad6b75a9f78b7e2ba97f3637082f7bba8724/pal/src/host/linux/pal_memory.c#L166)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Wait what? Are we talking about https://en.wikipedia.org/wiki/PA-RISC? Is this an easter egg, or am I missing something?
</blockquote></details>

Yes, PARISC. It's the only arch on Linux that has stack growing upwards (at least I think so). I couldn't find any other way of asserting such property (that our stack grows downwards).
___
*[`pal/src/host/linux/pal_memory.c` line 169 at r8](https://reviewable.io/reviews/gramineproject/gramine/839#-NAIyERN80db-jUbrxWX:-NAJvbhvALYSAY_2NPsO:b-dlv5p1) ([raw file](https://github.com/gramineproject/gramine/blob/5271ad6b75a9f78b7e2ba97f3637082f7bba8724/pal/src/host/linux/pal_memory.c#L169)):*
> Actually, how does Linux react to this artifical guard page? 

Not sure what you mean.

> Linux will not overwrite this guard-page mapping?

Linux will not overwrite any page. What if this was a dynamic library?

> In other words, will this guard page truly stop Linux from auto-increasing the stack?

Linux doesn't know if it's a guard page or whatever - it's just some user memory mapped. If you have a sane compiler that does stack probing (if it needs to allocate over a page size on stack), it will all work good.

Just for further explanation:
Stack growth works, on x64, this way (at least I believe so :smile:): if a page fault happens, Linux checks if the faulting address is above some VMA which grows down (i.e. the address belongs to no VMA and the next VMA has MAP_GROWSDOWN) and extends that mapping if allowed. I think it also used to check that `rsp` points somewhere into that VMA (or the faulting address), but my local experiments show it isn't the case, maybe something was changed.
___
*[`pal/src/host/linux/pal_memory.c` line 176 at r8](https://reviewable.io/reviews/gramineproject/gramine/839#-NAIyWfq8Urzaf-EsxwX:-NAJywfO-EK9DSnZybpX:bd4a1xc) ([raw file](https://github.com/gramineproject/gramine/blob/5271ad6b75a9f78b7e2ba97f3637082f7bba8724/pal/src/host/linux/pal_memory.c#L176)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Aren't we supposed to return PAL error codes?
</blockquote></details>

Yes we are
___
*[`pal/src/host/linux/pal_memory.c` line 178 at r8](https://reviewable.io/reviews/gramineproject/gramine/839#-NAIylLaEMroyv2W18JY:-NAJzHt1EF9TTA5G-XTu:b-cq3ivy) ([raw file](https://github.com/gramineproject/gramine/blob/5271ad6b75a9f78b7e2ba97f3637082f7bba8724/pal/src/host/linux/pal_memory.c#L178)):*
> Wouldn't it make more sense to perform mmap(guard page) before parse_proc_maps(), and then we won't need to call this explicitly?

It would. But how do I find the address for the guard page without `parse_proc_maps()`?
___
*[`pal/src/host/linux-common/arch/x86_64/stack_probe.nasm` line 8 at r8](https://reviewable.io/reviews/gramineproject/gramine/839#-NAJ-GZC6j5Cu6cAL72p:-NAJzdqC7GNic_GFCLyk:b-g22nn7) ([raw file](https://github.com/gramineproject/gramine/blob/5271ad6b75a9f78b7e2ba97f3637082f7bba8724/pal/src/host/linux-common/arch/x86_64/stack_probe.nasm#L8)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I just noticed that this function starts probing from *somewhere inside the stack* (whatever RSP currently points to), not from the beginning of the stack. It doesn't matter much, so I'm not blocking.
</blockquote></details>

Why would it matter at all? Semantics are "probe N pages" (assuming size is page aligned, actually let me change the signature).
___
*[`pal/src/host/linux-sgx/host_main.c` line 1008 at r8](https://reviewable.io/reviews/gramineproject/gramine/839#-NAJ-eS67BvdS1R-pOBR:-NAK-hDI9O4qcb3Bg9Y3:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/5271ad6b75a9f78b7e2ba97f3637082f7bba8724/pal/src/host/linux-sgx/host_main.c#L1008)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Maybe remove the func `force_linux_to_grow_stack()`? And move this func's comment (+ possibly remove some unnecessary details) to the actual place in code where we call probe the stack.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-26 08:28 UTC, dimakuv approved these changes
> Reviewed 5 of 5 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/839)* status: all files reviewed, 3 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[`pal/src/host/linux/pal_memory.c` line 166 at r8](https://reviewable.io/reviews/gramineproject/gramine/839#-NAIxrSQ-Rk3jXR65V1j:-NAOF-_lE8FQ6k5xEOLJ:b-mphya5) ([raw file](https://github.com/gramineproject/gramine/blob/5271ad6b75a9f78b7e2ba97f3637082f7bba8724/pal/src/host/linux/pal_memory.c#L166)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Yes, PARISC. It's the only arch on Linux that has stack growing upwards (at least I think so). I couldn't find any other way of asserting such property (that our stack grows downwards).
</blockquote></details>

Weeell. Whatever. I guess it helps to understand the assumption we have.
___
*[`pal/src/host/linux/pal_memory.c` line 169 at r8](https://reviewable.io/reviews/gramineproject/gramine/839#-NAIyERN80db-jUbrxWX:-NAOFTzy3j1fYBl7LYpJ:b-wsvas3) ([raw file](https://github.com/gramineproject/gramine/blob/5271ad6b75a9f78b7e2ba97f3637082f7bba8724/pal/src/host/linux/pal_memory.c#L169)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

> Actually, how does Linux react to this artifical guard page? 

Not sure what you mean.

> Linux will not overwrite this guard-page mapping?

Linux will not overwrite any page. What if this was a dynamic library?

> In other words, will this guard page truly stop Linux from auto-increasing the stack?

Linux doesn't know if it's a guard page or whatever - it's just some user memory mapped. If you have a sane compiler that does stack probing (if it needs to allocate over a page size on stack), it will all work good.

Just for further explanation:
Stack growth works, on x64, this way (at least I believe so :smile:): if a page fault happens, Linux checks if the faulting address is above some VMA which grows down (i.e. the address belongs to no VMA and the next VMA has MAP_GROWSDOWN) and extends that mapping if allowed. I think it also used to check that `rsp` points somewhere into that VMA (or the faulting address), but my local experiments show it isn't the case, maybe something was changed.
</blockquote></details>

Thanks for the explanation.
___
*[`pal/src/host/linux/pal_memory.c` line 178 at r8](https://reviewable.io/reviews/gramineproject/gramine/839#-NAIylLaEMroyv2W18JY:-NAOFlinD3Nz9NekIbmR:b-3mfsss) ([raw file](https://github.com/gramineproject/gramine/blob/5271ad6b75a9f78b7e2ba97f3637082f7bba8724/pal/src/host/linux/pal_memory.c#L178)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

> Wouldn't it make more sense to perform mmap(guard page) before parse_proc_maps(), and then we won't need to call this explicitly?

It would. But how do I find the address for the guard page without `parse_proc_maps()`?
</blockquote></details>

Lol, fair enough
___
*[`pal/src/host/linux-common/arch/x86_64/stack_probe.nasm` line 8 at r8](https://reviewable.io/reviews/gramineproject/gramine/839#-NAJ-GZC6j5Cu6cAL72p:-NAOFu9k-JshaREwYvL6:b-xf5l7r) ([raw file](https://github.com/gramineproject/gramine/blob/5271ad6b75a9f78b7e2ba97f3637082f7bba8724/pal/src/host/linux-common/arch/x86_64/stack_probe.nasm#L8)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why would it matter at all? Semantics are "probe N pages" (assuming size is page aligned, actually let me change the signature).
</blockquote></details>

With the changed signature, it's more logical what this func does. Thanks.


<!-- Sent from Reviewable.io -->

2022-10-05 06:56 UTC, dimakuv submitted a review, later dismissed
> Reviewed 44 of 44 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/839)* status: all files reviewed, 3 unresolved discussions (waiting on @boryspoplawski and @mkow)



<!-- Sent from Reviewable.io -->

2022-10-13 20:31 UTC, mkow requested changes
> Reviewed 33 of 83 files at r1, 1 of 12 files at r4, 5 of 20 files at r5, 4 of 8 files at r6, 3 of 8 files at r7, 1 of 1 files at r8, 2 of 5 files at r9, 44 of 44 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/839)* status: all files reviewed, 26 unresolved discussions (waiting on @boryspoplawski)

___
*[`libos/include/libos_checkpoint.h` line 28 at r4](https://reviewable.io/reviews/gramineproject/gramine/839#-NA4QsUGD-foE5euNd4Y:-NDdt6n36zJc0lTnq4Lb:brali4j) ([raw file](https://github.com/gramineproject/gramine/blob/5091236738af030296f9d4454241cfae7e2337c7/libos/include/libos_checkpoint.h#L28)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I won't insist on this, but at least fix the typo: `memroy` -> `memory`
</blockquote></details>

I'm fine with both ;)
___
*[`libos/include/libos_checkpoint.h` line 70 at r10](https://reviewable.io/reviews/gramineproject/gramine/839#-NDdtWw6-JaAVIEln3DE:-NDdtWw6-JaAVIEln3DF:b7df4k) ([raw file](https://github.com/gramineproject/gramine/blob/0ecc2e23f5f0be641e628c5ff42bc7ae45d96803/libos/include/libos_checkpoint.h#L70)):*
> ```objc
>     size_t size;
>     pal_prot_flags_t prot; /* combination of PAL_PROT_* flags */
>     bool dummy;
> ```

This deserves a comment IMO. Also, maybe something like "reserved" would be better?
___
*[`libos/src/bookkeep/libos_vma.c` line 1460 at r2](https://reviewable.io/reviews/gramineproject/gramine/839#-N9Yqaj65tFq-BHJwTqD:-NDeBqy-1eBgDZMeinjr:b-5lfske) ([raw file](https://github.com/gramineproject/gramine/blob/b4291e661b1e24094b4934518ca01c19c4859b59/libos/src/bookkeep/libos_vma.c#L1460)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Ok, done.
cc @mkow check this discussion, we decided to leave it as it is (and potentially change in the future)
</blockquote></details>

I'm fine with keeping it as-is and fixing it someday later, it doesn't seem too bad.
___
*[`pal/include/pal/pal.h` line 149 at r10](https://reviewable.io/reviews/gramineproject/gramine/839#-NDyzms2-SLWvk4wuthh:-NDyzms37O6hRXOHaQW4:b-luk0yw) ([raw file](https://github.com/gramineproject/gramine/blob/0ecc2e23f5f0be641e628c5ff42bc7ae45d96803/pal/include/pal/pal.h#L149)):*
> ```objc
>     uintptr_t early_libos_mem_range_end;    /*!< end of memory usable before checkpoint restore */
> 
>     struct pal_initial_mem_range* initial_mem_ranges; /*!< array of initial memory ranges */
> ```

Maybe you could explain here what are these initial memory ranges for?
___
*[`pal/include/pal/pal.h` line 205 at r10](https://reviewable.io/reviews/gramineproject/gramine/839#-NDz0eYdAXHuKMno1LzY:-NDz0eYdAXHuKMno1LzZ:b-gbo07c) ([raw file](https://github.com/gramineproject/gramine/blob/0ecc2e23f5f0be641e628c5ff42bc7ae45d96803/pal/include/pal/pal.h#L205)):*
> ```objc
>  * \brief Allocate virtual memory and zero it out.
>  *
>  * \param  addr  Requested address. Must be aligned and non-NULL.
> ```

Only one space after `\param`.
___
*[`pal/include/pal/pal.h` line 239 at r10](https://reviewable.io/reviews/gramineproject/gramine/839#-NDzBGwn6V5xydVXy0L8:-NDzBGwoC0UL7XcaIBaU:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/0ecc2e23f5f0be641e628c5ff42bc7ae45d96803/pal/include/pal/pal.h#L239)):*
> ```objc
>  * \brief Set upcalls for memory bookkeeping
>  *
>  * \param alloc  Function to call to get a memmory range.
> ```





_Suggestion:_
```objc
memory
```
___
*[`pal/include/pal/pal.h` line 257 at r10](https://reviewable.io/reviews/gramineproject/gramine/839#-NDzFamwA7YxfdinKGNd:-NDzFamx9wMYmBWW4DSO:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/0ecc2e23f5f0be641e628c5ff42bc7ae45d96803/pal/include/pal/pal.h#L257)):*
> ```objc
>  *                                      process.
>  * \param      reserved_mem_ranges      List of memory ranges that should not be used by the child
>  *                                      process until app memory is checkpointed. Must be sorted in
> ```





_Suggestion:_
```objc
app memory is restored from a checkpoint
```
___
*[`pal/regression/Memory.c` line 2 at r10](https://reviewable.io/reviews/gramineproject/gramine/839#-NDzJZIb6LQrWNVQr5yI:-NDzJZIc7D2PDY9JYLTC:blfc1cu) ([raw file](https://github.com/gramineproject/gramine/blob/def3704f2a177226902274f7af317d5159c57db5/pal/regression/Memory.c#L2)):*
> ```C
> /* XXX: What on earth is this supposed to be, an attempt to fit most UBs in one file?
>  * XXX: +1, please someone rm rf this file. */
> ```

finally
___
*[`pal/regression/memory.c` line 53 at r10](https://reviewable.io/reviews/gramineproject/gramine/839#-NE2tVtNEN0mexl3YPZg:-NE2tVtNEN0mexl3YPZh:bmihzft) ([raw file](https://github.com/gramineproject/gramine/blob/0ecc2e23f5f0be641e628c5ff42bc7ae45d96803/pal/regression/memory.c#L53)):*
> ```C
> 
> #else
> #error Unsupported architecture
> ```

CC: @stefanberger
___
*[`pal/regression/memory_management.c` line 67 at r10](https://reviewable.io/reviews/gramineproject/gramine/839#-NE3HW6fAGewHDHIynvG:-NE3HW6gCdlBvm2c-iUS:b-ybsalf) ([raw file](https://github.com/gramineproject/gramine/blob/0ecc2e23f5f0be641e628c5ff42bc7ae45d96803/pal/regression/memory_management.c#L67)):*
> ```C
> void init_memory_management(void) {
>     struct pal_public_state* pal_public_state = PalGetPalPublicState();
>     /* This dummy range is never freed. */
> ```

Why do we need it in the first place? Please explain in a comment.
___
*[`pal/regression/memory_management.c` line 93 at r10](https://reviewable.io/reviews/gramineproject/gramine/839#-NE3HXN2B4XXb1FA1QUC:-NE3HXN2B4XXb1FA1QUD:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/0ecc2e23f5f0be641e628c5ff42bc7ae45d96803/pal/regression/memory_management.c#L93)):*
> ```C
>         }
>     }
>     /* This dummy range is never freed. */
> ```

ditto
___
*[`pal/src/pal_main.c` line 21 at r10](https://reviewable.io/reviews/gramineproject/gramine/839#-NE6k0GO5lejaGSLLnFd:-NE6k0GP4SyfOM5rHMep:biau27s) ([raw file](https://github.com/gramineproject/gramine/blob/0ecc2e23f5f0be641e628c5ff42bc7ae45d96803/pal/src/pal_main.c#L21)):*
> ```C
> struct pal_common_state g_pal_common_state;
> 
> extern struct pal_initial_mem_range g_initial_mem_ranges[];
> ```

Why not just inline this array in `struct pal_public_state`?
___
*[`pal/src/pal_memory.c` line 58 at r10](https://reviewable.io/reviews/gramineproject/gramine/839#-NE6pujDB-SPnGL1o--c:-NE6pujDB-SPnGL1o--d:b9y8c6q) ([raw file](https://github.com/gramineproject/gramine/blob/0ecc2e23f5f0be641e628c5ff42bc7ae45d96803/pal/src/pal_memory.c#L58)):*
> ```
> * Because reserved ranges can be arbitrarily long and due to the fact that we cannot really
> * allocate memory without first inspecting them (so we do not map on top of them), we go through
> * them only once.
> ```

Hmm, reading only this comment block I don't see why we can go through them only once (i.e. why this follows from "reserved ranges can be arbitrarily long and due to the fact that we cannot really allocate memory without first inspecting them").
___
*[`pal/src/pal_memory.c` line 91 at r10](https://reviewable.io/reviews/gramineproject/gramine/839#-NE6vUXn7hfe6M11OfI1:-NE6vUXn7hfe6M11OfI2:b3v50kn) ([raw file](https://github.com/gramineproject/gramine/blob/0ecc2e23f5f0be641e628c5ff42bc7ae45d96803/pal/src/pal_memory.c#L91)):*
> ```C
>     };
>     memcpy(&g_initial_mem_ranges[idx].comment, comment,
>            MIN(sizeof(g_initial_mem_ranges[idx].comment) - 1, strlen(comment)));
> ```

Hmm, this assumes that the structural assignment above zeroes unlisted fields, right?



_Code quote:_
```C
MIN(sizeof(g_initial_mem_ranges[idx].comment) - 1, strlen(comment))
```
___
*[`pal/src/pal_memory.c` line 104 at r10](https://reviewable.io/reviews/gramineproject/gramine/839#-NE6x3Xs3almHWxyHcGf:-NE6x3Xs3almHWxyHcGg:b-ew9psv) ([raw file](https://github.com/gramineproject/gramine/blob/0ecc2e23f5f0be641e628c5ff42bc7ae45d96803/pal/src/pal [...]

2022-10-18 03:43 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/839)* status: 87 of 93 files reviewed, 23 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`libos/include/libos_checkpoint.h` line 70 at r10](https://reviewable.io/reviews/gramineproject/gramine/839#-NDdtWw6-JaAVIEln3DE:-NEcf_FD1t49XSIqpqGh:b-iv9jk8) ([raw file](https://github.com/gramineproject/gramine/blob/0ecc2e23f5f0be641e628c5ff42bc7ae45d96803/libos/include/libos_checkpoint.h#L70)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This deserves a comment IMO. Also, maybe something like "reserved" would be better?
</blockquote></details>

Done.
It's not really `reserved` (actual memory content for this range will be restored form **some** checkpointing entry). Unfortunately no better name comes to my mind.
___
*[`pal/include/pal/pal.h` line 149 at r10](https://reviewable.io/reviews/gramineproject/gramine/839#-NDyzms2-SLWvk4wuthh:-NEd8qAi8ymtaPmp_zeK:b-1rack4) ([raw file](https://github.com/gramineproject/gramine/blob/0ecc2e23f5f0be641e628c5ff42bc7ae45d96803/pal/include/pal/pal.h#L149)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Maybe you could explain here what are these initial memory ranges for?
</blockquote></details>

Note sure what to put here
___
*[`pal/include/pal/pal.h` line 205 at r10](https://reviewable.io/reviews/gramineproject/gramine/839#-NDz0eYdAXHuKMno1LzY:-NEchjBACu-Mnc7CasoJ:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/0ecc2e23f5f0be641e628c5ff42bc7ae45d96803/pal/include/pal/pal.h#L205)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Only one space after `\param`.
</blockquote></details>

Done.
___
*[`pal/include/pal/pal.h` line 239 at r10](https://reviewable.io/reviews/gramineproject/gramine/839#-NDzBGwn6V5xydVXy0L8:-NEchtVi9ZXCvim0YMYC:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/0ecc2e23f5f0be641e628c5ff42bc7ae45d96803/pal/include/pal/pal.h#L239)):*
> ```objc
>  * \brief Set upcalls for memory bookkeeping
>  *
>  * \param alloc  Function to call to get a memmory range.
> ```

Done.
___
*[`pal/include/pal/pal.h` line 257 at r10](https://reviewable.io/reviews/gramineproject/gramine/839#-NDzFamwA7YxfdinKGNd:-NEci64F0c7pmg9Wp8LP:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/0ecc2e23f5f0be641e628c5ff42bc7ae45d96803/pal/include/pal/pal.h#L257)):*
> ```objc
>  *                                      process.
>  * \param      reserved_mem_ranges      List of memory ranges that should not be used by the child
>  *                                      process until app memory is checkpointed. Must be sorted in
> ```

Done.
___
*[`pal/regression/memory_management.c` line 67 at r10](https://reviewable.io/reviews/gramineproject/gramine/839#-NE3HW6fAGewHDHIynvG:-NEckLMgDSSjYXseTHw8:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/0ecc2e23f5f0be641e628c5ff42bc7ae45d96803/pal/regression/memory_management.c#L67)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why do we need it in the first place? Please explain in a comment.
</blockquote></details>

Done.
___
*[`pal/regression/memory_management.c` line 93 at r10](https://reviewable.io/reviews/gramineproject/gramine/839#-NE3HXN2B4XXb1FA1QUC:-NEckLdR-WLrXeUOTYPd:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/0ecc2e23f5f0be641e628c5ff42bc7ae45d96803/pal/regression/memory_management.c#L93)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`pal/src/pal_main.c` line 21 at r10](https://reviewable.io/reviews/gramineproject/gramine/839#-NE6k0GO5lejaGSLLnFd:-NEckjhY98mZhcYI2dKw:bvgxgfd) ([raw file](https://github.com/gramineproject/gramine/blob/0ecc2e23f5f0be641e628c5ff42bc7ae45d96803/pal/src/pal_main.c#L21)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why not just inline this array in `struct pal_public_state`?
</blockquote></details>

We have never asserted or said anywhere explicitly that `struct pal_public_state` is a singleton, so I didn't want to add a potentially big array in that struct. Also initially `g_initial_mem_ranges` was private to `pal_memory.c`, exported later.
___
*[`pal/src/pal_memory.c` line 58 at r10](https://reviewable.io/reviews/gramineproject/gramine/839#-NE6pujDB-SPnGL1o--c:-NEcm88V19slzQuhsTS3:b-lmd8h7) ([raw file](https://github.com/gramineproject/gramine/blob/0ecc2e23f5f0be641e628c5ff42bc7ae45d96803/pal/src/pal_memory.c#L58)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> * Because reserved ranges can be arbitrarily long and due to the fact that we cannot really
> * allocate memory without first inspecting them (so we do not map on top of them), we go through
> * them only once.
> ```

Hmm, reading only this comment block I don't see why we can go through them only once (i.e. why this follows from "reserved ranges can be arbitrarily long and due to the fact that we cannot really allocate memory without first inspecting them").
</blockquote></details>

This explains why "we have to", not why "we can" go through them once.
___
*[`pal/src/pal_memory.c` line 91 at r10](https://reviewable.io/reviews/gramineproject/gramine/839#-NE6vUXn7hfe6M11OfI1:-NEcnawO2wDMyv71f2q3:bmoxetd) ([raw file](https://github.com/gramineproject/gramine/blob/0ecc2e23f5f0be641e628c5ff42bc7ae45d96803/pal/src/pal_memory.c#L91)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Hmm, this assumes that the structural assignment above zeroes unlisted fields, right?
</blockquote></details>

Yes, but it does zero them.
___
*[`pal/src/pal_memory.c` line 104 at r10](https://reviewable.io/reviews/gramineproject/gramine/839#-NE6x3Xs3almHWxyHcGf:-NEcqRnp5sSFTkukcOnY:b-z6it1h) ([raw file](https://github.com/gramineproject/gramine/blob/0ecc2e23f5f0be641e628c5ff42bc7ae45d96803/pal/src/pal_memory.c#L104)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you also assert out ranges with size == 0? They can break sorting here.
</blockquote></details>

How would they break it?
___
*[`pal/src/pal_memory.c` line 117 at r10](https://reviewable.io/reviews/gramineproject/gramine/839#-NE6ySOC7zT-5jjqKvtJ:-NEcsjKfCI5q6cB__2gF:begw0lt) ([raw file](https://github.com/gramineproject/gramine/blob/0ecc2e23f5f0be641e628c5ff42bc7ae45d96803/pal/src/pal_memory.c#L117)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I spent a few minutes here and still don't understand the exact logic here. Could you explain in a comment what is moved where? Is `move_idx` the index you preserve and delete other ranges? Which ones exactly? (relative to `idx` and `move_idx`)
</blockquote></details>

How about now?
___
*[`pal/src/pal_memory.c` line 155 at r10](https://reviewable.io/reviews/gramineproject/gramine/839#-NE8CXFx8AvK0NQsOCYK:-NEctQNq8tG9d-tA_-xv:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/0ecc2e23f5f0be641e628c5ff42bc7ae45d96803/pal/src/pal_memory.c#L155)):*
> ```C
> 
> static bool find_free_range(size_t size, uintptr_t* out_addr) {
>     size_t idx = g_pal_public_state.initial_mem_ranges_len;
> ```

Done.
___
*[`pal/src/pal_memory.c` line 317 at r10](https://reviewable.io/reviews/gramineproject/gramine/839#-NE8I9-jAm6D2W-Wuh3h:-NEctk9R8K--XtCQ_zII:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/0ecc2e23f5f0be641e628c5ff42bc7ae45d96803/pal/src/pal_memory.c#L317)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wro [...]

2022-10-18 07:10 UTC, dimakuv requested changes
> Reviewed 6 of 6 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/839)* status: all files reviewed, 24 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[`pal/src/pal_memory.c` line 116 at r11](https://reviewable.io/reviews/gramineproject/gramine/839#-NEduMjM1U_IqL47j4hU:-NEduMjM1U_IqL47j4hV:b-flfukb) ([raw file](https://github.com/gramineproject/gramine/blob/01fd0c89ff35e1ea8777c8f8c28713eb3fb7ca63/pal/src/pal_memory.c#L116)):*
> ```C
>     g_initial_mem_ranges[idx].is_free = true;
> 
>     /* Remove `ranges_to_rm_count` ranges stating at `rm_start_idx`. */
> ```

`starting`
___
*[`pal/src/host/linux-common/file_utils.c` line 104 at r2](https://reviewable.io/reviews/gramineproject/gramine/839#-N9YrIuj28h1-6R0C59-:-NEdvCaU97nzMYScnjBG:bi4oj8y) ([raw file](https://github.com/gramineproject/gramine/blob/b4291e661b1e24094b4934518ca01c19c4859b59/pal/src/host/linux-common/file_utils.c#L104)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

But then we need to decide whether we want to have the current version (hence remove this TODO) or we want to fix it in the future (hence we want a TODO, but stating what the ideal version would look like). I took @dimakuv comment as in favor of the former and @mkow of the latter.
</blockquote></details>

I would remove the TODO line completely.


<!-- Sent from Reviewable.io -->

2022-10-18 15:17 UTC, mkow requested changes
> Reviewed 6 of 6 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/839)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[`pal/include/pal/pal.h` line 149 at r10](https://reviewable.io/reviews/gramineproject/gramine/839#-NDyzms2-SLWvk4wuthh:-NEfPq6r61Bw8zRT0P0e:b-bl1gpv) ([raw file](https://github.com/gramineproject/gramine/blob/0ecc2e23f5f0be641e628c5ff42bc7ae45d96803/pal/include/pal/pal.h#L149)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Note sure what to put here
</blockquote></details>

that reference you added should do the work IMO
___
*[`pal/src/pal_memory.c` line 58 at r10](https://reviewable.io/reviews/gramineproject/gramine/839#-NE6pujDB-SPnGL1o--c:-NEfSCMM6igOKnJhp4tr:b-vak0za) ([raw file](https://github.com/gramineproject/gramine/blob/0ecc2e23f5f0be641e628c5ff42bc7ae45d96803/pal/src/pal_memory.c#L58)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This explains why "we have to", not why "we can" go through them once.
</blockquote></details>

Yes, that's what I meant. "why we can go through them only once" == "why we have to go through them only zero or one time" (that "only" makes the difference).
___
*[`pal/src/pal_memory.c` line 91 at r10](https://reviewable.io/reviews/gramineproject/gramine/839#-NE6vUXn7hfe6M11OfI1:-NEfSpHSA9iQERmegUGk:b-1f9t5o) ([raw file](https://github.com/gramineproject/gramine/blob/0ecc2e23f5f0be641e628c5ff42bc7ae45d96803/pal/src/pal_memory.c#L91)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Yes, but it does zero them.
</blockquote></details>

Ok, just wanted to ensure that this is what you intended.
___
*[`pal/src/pal_memory.c` line 104 at r10](https://reviewable.io/reviews/gramineproject/gramine/839#-NE6x3Xs3almHWxyHcGf:-NEfVLCm8z4XvDZTMYJu:bemqanz) ([raw file](https://github.com/gramineproject/gramine/blob/0ecc2e23f5f0be641e628c5ff42bc7ae45d96803/pal/src/pal_memory.c#L104)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

How would they break it?
</blockquote></details>

Ok, it actually works in this case, sorry. Got lost with the descending order and didn't flip at one part of my quick analysis :)
___
*[`pal/src/pal_memory.c` line 117 at r10](https://reviewable.io/reviews/gramineproject/gramine/839#-NE6ySOC7zT-5jjqKvtJ:-NEfWdYn6jhzzw8w7puS:b-tv4x6t) ([raw file](https://github.com/gramineproject/gramine/blob/0ecc2e23f5f0be641e628c5ff42bc7ae45d96803/pal/src/pal_memory.c#L117)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

How about now?
</blockquote></details>

Much better now :)
___
*[`pal/src/pal_memory.c` line 343 at r10](https://reviewable.io/reviews/gramineproject/gramine/839#-NE8K13T-x27hn4mFbx9:-NEfa3yJ7t-_hqjaWVo2:b-imesl1) ([raw file](https://github.com/gramineproject/gramine/blob/0ecc2e23f5f0be641e628c5ff42bc7ae45d96803/pal/src/pal_memory.c#L343)):*
> Manifest is loaded by PAL, not LibOS.

Ah, right, it's not being loaded twice anymore, I forgot we fixed this.

> Done. Mounted whole `/usr` as trusted, ~225k files. Signing manifest took a minute, resulting size: 37MB. Everything works (albeit slow as... very slowly).

Thanks! Sounds good.
___
*[`pal/src/pal_memory.c` line 123 at r11](https://reviewable.io/reviews/gramineproject/gramine/839#-NEfY0fy7JVFgoZZZOXK:-NEfY0fy7JVFgoZZZOXL:bec36f2) ([raw file](https://github.com/gramineproject/gramine/blob/01fd0c89ff35e1ea8777c8f8c28713eb3fb7ca63/pal/src/pal_memory.c#L123)):*
> ```C
>         /* Next range is also free and aligned to the one being freed now, we can merge them. */
>         g_initial_mem_ranges[idx].start = g_initial_mem_ranges[idx + 1].start;
>         rm_start_idx = idx + 1;
> ```

not just `idx`?



_Code quote:_
```C
idx + 1
```
___
*[`pal/src/pal_memory.c` line 130 at r11](https://reviewable.io/reviews/gramineproject/gramine/839#-NEfY4PdAXkXu8qCqtPn:-NEfY4PeDen0FEMv7XLM:bm5jywq) ([raw file](https://github.com/gramineproject/gramine/blob/01fd0c89ff35e1ea8777c8f8c28713eb3fb7ca63/pal/src/pal_memory.c#L130)):*
> ```C
>         /* Previous range is also free and aligned to the one being freed now, we can merge them. */
>         g_initial_mem_ranges[idx - 1].start = g_initial_mem_ranges[idx].start;
>         rm_start_idx = idx;
> ```

Not `idx - 1`? Here `g_initial_mem_ranges[idx - 1]` is mergable with `g_initial_mem_ranges[idx]`, so we can delete 2 or 3 ranges starting from `idx - 1`?



_Code quote:_
```C
rm_start_idx = idx;
```
___
*[`pal/src/slab.c` line 31 at r10](https://reviewable.io/reviews/gramineproject/gramine/839#-NEDBkyj1wgRkvjuenRL:-NEfaiGU9HbuS5UOYcUo:b5dsg1s) ([raw file](https://github.com/gramineproject/gramine/blob/0ecc2e23f5f0be641e628c5ff42bc7ae45d96803/pal/src/slab.c#L31)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This `__malloc` is used by `slabmgr.h`, it's used to serve allocations it requests (which are basically memory for each slab). We do waste some memory, because it usually request sizes like `0x4020`. But this is a problem with `slabmgr.h`, which we should fix at some point.
</blockquote></details>

Could you describe it in a comment here? Because on its own it looks really bad and it makes sense only knowing that it's used only for bigger chunks for slabs and nothing else (the function name suggest that it's used as normal malloc, i.e. for small sizes also).
___
*[`pal/src/host/linux/pal_memory.c` line 74 at r10](https://reviewable.io/reviews/gramineproject/gramine/839#-NEDpjmo-O-affmUDOBd:-NEfbCSP-inxJJQalPcZ:b-oh5gn8) ([raw file](https://github.com/gramineproject/gramine/blob/def3704f2a177226902274f7af317d5159c57db5/pal/src/host/linux/pal_memory.c#L74)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

?
</blockquote></details>

Hmm, it's actually not relevant anymore. I must have misread the code, sorry.
___
*[`pal/src/host/linux/pal_memory.c` line 193 at r10](https://reviewable.io/reviews/gramineproject/gramine/839#-NEH7f8KAlk0jc9i2Ou-:-NEfbzO8B3uo6IpGE2Gb:b-9iiv5c) ([raw file](https://github.com/gramineproject/gramine/blob/0ecc2e23f5f0be641e628c5ff42bc7ae45d96803/pal/src/host/linux/pal_memory.c#L193)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

It doesn't depend on distro, but on host kernel (note that we use docker in CI, but it's host kernel that matters). It's supported since kernel 4.17 and I don't have older one to verify what happens there. I checked source and it seems mmap ignores unknown flags.
Added a check just in case.
</blockquote></details>

Yeah, I know, but AFAIR 18.04 is being shipped with a kernel without this flag. At least that's what my notes say.
Anyways, the failsafe check looks ok.
___
*[`pal/src/host/linux-common/file_utils.c` line 104 at r2](https://reviewable.io/reviews/gramineproject/gramine/839#-N9YrIuj28h1-6R0C59-:-NEfcmKm4t2xP46ZgdNv:b8tn1n2) ([raw file](https://github.com/gramineproject/gramine/blob/b4291e661b1e24094b4934518ca01c19c4859b59/pal/src/host/linux-common/file_utils.c#L104)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I would remove the TODO line completely.
</blockquote></details>

I'm fine with removing it.
___
*[`pal/src/host/linux-sgx/host_process.c` line 202 at r11](https://reviewable.io/reviews/gramineproject/gramine/839#-NEfdqKy3ZXiE5JXq0t5:-NEfdqKy3ZXiE5JXq0t6:b-11w539) ([raw file](https://github.com/gramineproject/gramine/blob/01fd0c89ff35e1ea8777c8f8c28713eb3fb7ca63/pal/src/host/linux-s [...]

2022-10-18 17:02 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/839)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`pal/src/pal_memory.c` line 58 at r10](https://reviewable.io/reviews/gramineproject/gramine/839#-NE6pujDB-SPnGL1o--c:-NEfwcJgBqliQvjhd1QI:b-wz5zg9) ([raw file](https://github.com/gramineproject/gramine/blob/0ecc2e23f5f0be641e628c5ff42bc7ae45d96803/pal/src/pal_memory.c#L58)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Yes, that's what I meant. "why we can go through them only once" == "why we have to go through them only zero or one time" (that "only" makes the difference).
</blockquote></details>

I don't understand your comment and I disagree on that `==` sign there. `why we can go through them only once` ==  `why we don't have to go through them two or more times` != `why we have to go through them only zero or one time`. The left sentence allows for any amount, the right only for `0` and `1`.
Anyway, this sentence is supposed to explain, why we go through that list once, it doesn't state we cannot go more times. The reason is going on each allocation (i.e. multiple times) would be super slow (list can be quite big) and we cannot use any search efficient structure (like a tree) because to create it we need to allocate memory, which we cannot do without inspecting this list first.
___
*[`pal/src/pal_memory.c` line 104 at r10](https://reviewable.io/reviews/gramineproject/gramine/839#-NE6x3Xs3almHWxyHcGf:-NEfyWBjAJe1GVVKvlXK:b6sw84h) ([raw file](https://github.com/gramineproject/gramine/blob/0ecc2e23f5f0be641e628c5ff42bc7ae45d96803/pal/src/pal_memory.c#L104)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Ok, it actually works in this case, sorry. Got lost with the descending order and didn't flip at one part of my quick analysis :)
</blockquote></details>

Yeah, I'm not proud of this code, I think it's too complicated, but didn't come up with anything better.
___
*[`pal/src/pal_memory.c` line 116 at r11](https://reviewable.io/reviews/gramineproject/gramine/839#-NEduMjM1U_IqL47j4hU:-NEfypYiBpzZwWywNU43:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/01fd0c89ff35e1ea8777c8f8c28713eb3fb7ca63/pal/src/pal_memory.c#L116)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`starting`
</blockquote></details>

Done.
___
*[`pal/src/pal_memory.c` line 123 at r11](https://reviewable.io/reviews/gramineproject/gramine/839#-NEfY0fy7JVFgoZZZOXK:-NEfyvcx0Z3YzoPXB_68:bp9i23e) ([raw file](https://github.com/gramineproject/gramine/blob/01fd0c89ff35e1ea8777c8f8c28713eb3fb7ca63/pal/src/pal_memory.c#L123)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

not just `idx`?
</blockquote></details>

No. We merge to the left, which means `idx` becomes union of `range[idx]` and `range[idx+1]`, so we remove `idx + 1`. Also see below.
___
*[`pal/src/pal_memory.c` line 130 at r11](https://reviewable.io/reviews/gramineproject/gramine/839#-NEfY4PdAXkXu8qCqtPn:-NEfzHdIBgxMO0CBUmzj:b-bideru) ([raw file](https://github.com/gramineproject/gramine/blob/01fd0c89ff35e1ea8777c8f8c28713eb3fb7ca63/pal/src/pal_memory.c#L130)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Not `idx - 1`? Here `g_initial_mem_ranges[idx - 1]` is mergable with `g_initial_mem_ranges[idx]`, so we can delete 2 or 3 ranges starting from `idx - 1`?
</blockquote></details>

No, we need to leave one of them. We do not delete free ranges, we just mark them as freed (`.is_free = true`). This code just merges free ranges occurring in a row into one, because for free ranges only `start` and `end` matter, so we can merge.
___
*[`pal/src/slab.c` line 31 at r10](https://reviewable.io/reviews/gramineproject/gramine/839#-NEDBkyj1wgRkvjuenRL:-NEg0HI-AkXnU0IGMiCf:bjwt4ms) ([raw file](https://github.com/gramineproject/gramine/blob/0ecc2e23f5f0be641e628c5ff42bc7ae45d96803/pal/src/slab.c#L31)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you describe it in a comment here? Because on its own it looks really bad and it makes sense only knowing that it's used only for bigger chunks for slabs and nothing else (the function name suggest that it's used as normal malloc, i.e. for small sizes also).
</blockquote></details>

How about changing the name? (1 less UB as a bonus).
___
*[`pal/src/host/linux/pal_memory.c` line 193 at r10](https://reviewable.io/reviews/gramineproject/gramine/839#-NEH7f8KAlk0jc9i2Ou-:-NEg-Q1t3DCWNBjdXrAS:bnq6k1m) ([raw file](https://github.com/gramineproject/gramine/blob/0ecc2e23f5f0be641e628c5ff42bc7ae45d96803/pal/src/host/linux/pal_memory.c#L193)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Yeah, I know, but AFAIR 18.04 is being shipped with a kernel without this flag. At least that's what my notes say.
Anyways, the failsafe check looks ok.
</blockquote></details>

Idk, my local VM with 18.04 has kernel 5.4, which seems to be the same as 20.04? Not sure what happened here, as I don't remember updating the kernel manually (so maybe it was done automatically at some point?)
___
*[`pal/src/host/linux-common/file_utils.c` line 104 at r2](https://reviewable.io/reviews/gramineproject/gramine/839#-N9YrIuj28h1-6R0C59-:-NEg-yn_6piig4d1FEat:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b4291e661b1e24094b4934518ca01c19c4859b59/pal/src/host/linux-common/file_utils.c#L104)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'm fine with removing it.
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/host_process.c` line 202 at r11](https://reviewable.io/reviews/gramineproject/gramine/839#-NEfdqKy3ZXiE5JXq0t5:-NEg1VDD6ZArYukbJM-M:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/01fd0c89ff35e1ea8777c8f8c28713eb3fb7ca63/pal/src/host/linux-sgx/host_process.c#L202)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`munmap` returns `-EINVAL` for `len == 0`. It doesn't matter much, but I guess we better skip it in this case (for `proc_args.reserved_mem_ranges_size == 0` we do `munmap(NULL, 0)`) for the sake of less bogus errors in strace when debugging.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-10-18 17:22 UTC, dimakuv submitted a review, later dismissed
> Reviewed 4 of 4 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/839)* status: all files reviewed, 6 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2022-10-18 17:39 UTC, mkow requested changes
> Reviewed 4 of 4 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/839)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[`pal/src/pal_memory.c` line 58 at r10](https://reviewable.io/reviews/gramineproject/gramine/839#-NE6pujDB-SPnGL1o--c:-NEg5lZ9DXu4g4agHhdP:bgtds7k) ([raw file](https://github.com/gramineproject/gramine/blob/0ecc2e23f5f0be641e628c5ff42bc7ae45d96803/pal/src/pal_memory.c#L58)):*
> I don't understand your comment and I disagree on that `==` sign there. `why we can go through them only once` ==  `why we don't have to go through them two or more times` != `why we have to go through them only zero or one time`. The left sentence allows for any amount, the right only for `0` and `1`.

Ah, I see that it can be parsed in two ways (and I think both parsings are correct, so my sentence was ambiguous).

>  Anyway, this sentence is supposed to explain, why we go through that list once, it doesn't state we cannot go more times.

Huh, I read this comment differently - that going through the list twice is illegal for some reason, not that this is just an optimization.

> The reason is going on each allocation (i.e. multiple times) would be super slow (list can be quite big) and we cannot use any search efficient structure (like a tree) because to create it we need to allocate memory, which we cannot do without inspecting this list first.

Ok, with this context the comment is clear to me. Could you add the above somewhere into the comment?
___
*[`pal/src/pal_memory.c` line 123 at r11](https://reviewable.io/reviews/gramineproject/gramine/839#-NEfY0fy7JVFgoZZZOXK:-NEg7lEQ1wMJGIPmonER:b-2t6wj6) ([raw file](https://github.com/gramineproject/gramine/blob/01fd0c89ff35e1ea8777c8f8c28713eb3fb7ca63/pal/src/pal_memory.c#L123)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

No. We merge to the left, which means `idx` becomes union of `range[idx]` and `range[idx+1]`, so we remove `idx + 1`. Also see below.
</blockquote></details>

Ahhh, I see now. Could you add a comment saying that we're merging adjacent free ranges to the left? I got lost in this logic.
___
*[`pal/src/slab.c` line 31 at r10](https://reviewable.io/reviews/gramineproject/gramine/839#-NEDBkyj1wgRkvjuenRL:-NEg87ec3Q0-KOD4XbdW:b-vpohlm) ([raw file](https://github.com/gramineproject/gramine/blob/0ecc2e23f5f0be641e628c5ff42bc7ae45d96803/pal/src/slab.c#L31)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

How about changing the name? (1 less UB as a bonus).
</blockquote></details>

that's much better!
___
*[`pal/src/host/linux/pal_memory.c` line 193 at r10](https://reviewable.io/reviews/gramineproject/gramine/839#-NEH7f8KAlk0jc9i2Ou-:-NEg8Fx0Bj3Gkn1G4-0q:b-hr7gq1) ([raw file](https://github.com/gramineproject/gramine/blob/0ecc2e23f5f0be641e628c5ff42bc7ae45d96803/pal/src/host/linux/pal_memory.c#L193)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Idk, my local VM with 18.04 has kernel 5.4, which seems to be the same as 20.04? Not sure what happened here, as I don't remember updating the kernel manually (so maybe it was done automatically at some point?)
</blockquote></details>

Interesting, I wouldn't expect such an old LTS to do such a big kernel update.


<!-- Sent from Reviewable.io -->

2022-10-18 18:30 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/839)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`pal/src/pal_memory.c` line 58 at r10](https://reviewable.io/reviews/gramineproject/gramine/839#-NE6pujDB-SPnGL1o--c:-NEgLx2A1qL37Mr72I5F:b-gb51bu) ([raw file](https://github.com/gramineproject/gramine/blob/0ecc2e23f5f0be641e628c5ff42bc7ae45d96803/pal/src/pal_memory.c#L58)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> I don't understand your comment and I disagree on that `==` sign there. `why we can go through them only once` ==  `why we don't have to go through them two or more times` != `why we have to go through them only zero or one time`. The left sentence allows for any amount, the right only for `0` and `1`.

Ah, I see that it can be parsed in two ways (and I think both parsings are correct, so my sentence was ambiguous).

>  Anyway, this sentence is supposed to explain, why we go through that list once, it doesn't state we cannot go more times.

Huh, I read this comment differently - that going through the list twice is illegal for some reason, not that this is just an optimization.

> The reason is going on each allocation (i.e. multiple times) would be super slow (list can be quite big) and we cannot use any search efficient structure (like a tree) because to create it we need to allocate memory, which we cannot do without inspecting this list first.

Ok, with this context the comment is clear to me. Could you add the above somewhere into the comment?

</blockquote></details>

Is this enough? I don't know how to incorporate this whole sentence without repeating stuff.
___
*[`pal/src/pal_memory.c` line 123 at r11](https://reviewable.io/reviews/gramineproject/gramine/839#-NEfY0fy7JVFgoZZZOXK:-NEgKscvA7v5S918RHch:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/01fd0c89ff35e1ea8777c8f8c28713eb3fb7ca63/pal/src/pal_memory.c#L123)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Ahhh, I see now. Could you add a comment saying that we're merging adjacent free ranges to the left? I got lost in this logic.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-10-18 19:04 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/839)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

___
*[`pal/src/pal_memory.c` line 58 at r10](https://reviewable.io/reviews/gramineproject/gramine/839#-NE6pujDB-SPnGL1o--c:-NEgTfS60X4RroOHNxSs:b89wahq) ([raw file](https://github.com/gramineproject/gramine/blob/0ecc2e23f5f0be641e628c5ff42bc7ae45d96803/pal/src/pal_memory.c#L58)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Is this enough? I don't know how to incorporate this whole sentence without repeating stuff.
</blockquote></details>

Yup, should be clear now.


<!-- Sent from Reviewable.io -->

2022-10-18 20:48 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r13, 21 of 21 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/839)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-10-18 21:21 UTC, merged