[CI-Examples]Modify ra_tls_mbedtls' Makefile to enable it in Anolis OS
gramineproject/gramine pull request #843
Opened 2022-08-16 01:34 UTC by billionairiam

Signed-off-by: Liang, Ma <liang3.ma@intel.com>

## Description of the changes 

1. When we configure gramine in [Anolis OS](https://openanolis.cn/), The[ ra_tls_mbedtls](https://github.com/gramineproject/gramine/tree/master/CI-Examples/ra-tls-mbedtls) under CI-Example can't work correctly. This is caused by the [Makefile](https://github.com/gramineproject/gramine/blob/master/CI-Examples/ra-tls-mbedtls/Makefile) is debian/ubuntu specific, so I think we can modify it to fit different operating systems.
2. In ubuntu the `ARCH_LIBDIR ?= /lib/$(shell $(CC) -dumpmachine)`, while in Anolis OS it should be `/usr/lib64`

2022-08-16 12:07 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/843)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @billionairiam)

___
*[`CI-Examples/ra-tls-mbedtls/Makefile` line 13 at r1](https://reviewable.io/reviews/gramineproject/gramine/843#-N9aXrfk2T5Y0xcSjEkM:-N9aXrfl6vRVXPdnAcz0:bbc9dzh) ([raw file](https://github.com/gramineproject/gramine/blob/ce974a4b0b11249493bf0b4f2ffaf6d9348b87ef/CI-Examples/ra-tls-mbedtls/Makefile#L13)):*
> ```Makefile
> echo "Unsupported operation system!"
> endif
> endif
> ```

I veto this change. We will actually need to change **all** our Makefiles, not just this one.

We need to come up with a better way of specifying the paths based on the OS distro. Unfortunately, I do not know of better ways...

I think we had this conversation before with @mkow and @woju, and didn't come up with a better way.


<!-- Sent from Reviewable.io -->

2022-08-16 16:34 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/843)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow and @woju)

___
*[`CI-Examples/ra-tls-mbedtls/Makefile` line 13 at r1](https://reviewable.io/reviews/gramineproject/gramine/843#-N9aXrfk2T5Y0xcSjEkM:-N9bV9OR7omhsJ9gqngk:b-2kimvl) ([raw file](https://github.com/gramineproject/gramine/blob/ce974a4b0b11249493bf0b4f2ffaf6d9348b87ef/CI-Examples/ra-tls-mbedtls/Makefile#L13)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I veto this change. We will actually need to change **all** our Makefiles, not just this one.

We need to come up with a better way of specifying the paths based on the OS distro. Unfortunately, I do not know of better ways...

I think we had this conversation before with @mkow and @woju, and didn't come up with a better way.
</blockquote></details>

These are only examples, what's the problem with them not working on some OSes? For a production env you need to pass all these files (that are in ARCH_DIR) together with the app anyway (easiest way being docker with Gramine or GSC)


<!-- Sent from Reviewable.io -->

2022-08-17 13:10 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/843)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow and @woju)

___
*[`CI-Examples/ra-tls-mbedtls/Makefile` line 13 at r1](https://reviewable.io/reviews/gramineproject/gramine/843#-N9aXrfk2T5Y0xcSjEkM:-N9fv97T6ZsjvjnW5u5g:br8jrfs) ([raw file](https://github.com/gramineproject/gramine/blob/ce974a4b0b11249493bf0b4f2ffaf6d9348b87ef/CI-Examples/ra-tls-mbedtls/Makefile#L13)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

These are only examples, what's the problem with them not working on some OSes? For a production env you need to pass all these files (that are in ARCH_DIR) together with the app anyway (easiest way being docker with Gramine or GSC)
</blockquote></details>

Sure, but then why do we modify only this one example?

And if we modify *all* examples like this, then we introduced 10 identical lines repeated X times... I dislike it very much.


<!-- Sent from Reviewable.io -->

2022-08-17 13:37 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/843)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow and @woju)

___
*[`CI-Examples/ra-tls-mbedtls/Makefile` line 13 at r1](https://reviewable.io/reviews/gramineproject/gramine/843#-N9aXrfk2T5Y0xcSjEkM:-N9g0IEs5isslevEuA96:bdm0ja3) ([raw file](https://github.com/gramineproject/gramine/blob/ce974a4b0b11249493bf0b4f2ffaf6d9348b87ef/CI-Examples/ra-tls-mbedtls/Makefile#L13)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Sure, but then why do we modify only this one example?

And if we modify *all* examples like this, then we introduced 10 identical lines repeated X times... I dislike it very much.
</blockquote></details>

No, my point was to modify nothing - these examples are only usable on ubuntu/debian. Other users are on their own.


<!-- Sent from Reviewable.io -->

2022-08-18 12:48 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/843)* status: 0 of 1 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @billionairiam, @mkow, and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/843#-N9kzZWY2kiCSLG9e5a_:-N9kzZWY2kiCSLG9e5aa:bxeb4hs) (no related file):*
@billionairiam What was the reason for this PR? Do you think it would be possible for Anolis OS users to run the build like this:
```
SGX=1 GRAMINE_PKGLIBDIR=/usr/lib64/gramine ARCH_LIBDIR=/lib64 make
```

(This is what users of CentOS/RHEL/Fedora do currently anyway. Anolis users could do the same.)

As mentioned in the other comment, we don't think we won't such changes in our examples. They are purely for Debian/Ubuntu, and we don't want to complicate the examples.

___
___
*[`CI-Examples/ra-tls-mbedtls/Makefile` line 13 at r1](https://reviewable.io/reviews/gramineproject/gramine/843#-N9aXrfk2T5Y0xcSjEkM:-N9kzXia0qFUIF9eQvA7:b-pbdqz3) ([raw file](https://github.com/gramineproject/gramine/blob/ce974a4b0b11249493bf0b4f2ffaf6d9348b87ef/CI-Examples/ra-tls-mbedtls/Makefile#L13)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

No, my point was to modify nothing - these examples are only usable on ubuntu/debian. Other users are on their own.
</blockquote></details>

Agreed.


<!-- Sent from Reviewable.io -->

2022-08-23 02:13 UTC, closed without merging