[LibOS] Support `/sys/devices/system/node/nodeX/meminfo` files
gramineproject/gramine pull request #847
Opened 2022-08-17 06:30 UTC by kailun-qin

Gramine currently doesn't emulate `/sys/devices/system/node/nodeX/meminfo` files. This will lead to some workload failures due to these missing NUMA node meminfo files.

This patch adds basic support for the above usage.

Resolves https://github.com/gramineproject/gramine/issues/364.

2022-08-17 13:20 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/847)* status: 0 of 11 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @kailun-qin)

___
*[`pal/src/host/linux/pal_memory.c` line 22 at r1](https://reviewable.io/reviews/gramineproject/gramine/847#-N9fxXg1A4byAgR5iFMZ:-N9fxXg1A4byAgR5iFM_:bk3ae91) ([raw file](https://github.com/gramineproject/gramine/blob/e09846281b0fac4e304f6cf96e17927a8e51c762/pal/src/host/linux/pal_memory.c#L22)):*
> ```C
> 
> #define PROC_MEMINFO_PATH "/proc/meminfo"
> #define SYS_NODE_MEMINFO_PATH_PREFIX "/sys/devices/system/node/node"
> ```

You defined it but forgot to use it. Irrelevant anyway since I suggest to remove this whole thing in Linux PAL.
___
*[`pal/src/host/linux-sgx/pal_memory.c` line 107 at r1](https://reviewable.io/reviews/gramineproject/gramine/847#-N9fwmkBEVkl5MYPo64w:-N9fwmkBEVkl5MYPo64x:b-uzxlsx) ([raw file](https://github.com/gramineproject/gramine/blob/e09846281b0fac4e304f6cf96e17927a8e51c762/pal/src/host/linux-sgx/pal_memory.c#L107)):*
> ```C
>     __UNUSED(node_id);
> 
>     return _PalMemoryAvailableQuota();
> ```

This defeats the purpose of all the complexity that you introduced for the Linux PAL.

I think there is absolutely no way of determining the amount of available *SGX enclave memory* on a NUMA node, so we shouldn't even try? I mean, the main usage of Gramine is with SGX, so having a proper support for the Linux PAL but *not* for the Linux-SGX PAL makes no sense.

I suggest to simply "mimic" a more or less typical environment: each NUMA node returns:
- `NodeMemTotal = PalMemTotal / numa_nodes_cnt`
- `NodeMemFree = PalMemAvailable / numa_nodes_cnt`


<!-- Sent from Reviewable.io -->

2022-08-17 14:33 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/847)* status: 0 of 11 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

___
*[`pal/src/host/linux/pal_memory.c` line 22 at r1](https://reviewable.io/reviews/gramineproject/gramine/847#-N9fxXg1A4byAgR5iFMZ:-N9gCT41AtbMzJCREXj5:bss4a2b) ([raw file](https://github.com/gramineproject/gramine/blob/e09846281b0fac4e304f6cf96e17927a8e51c762/pal/src/host/linux/pal_memory.c#L22)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You defined it but forgot to use it. Irrelevant anyway since I suggest to remove this whole thing in Linux PAL.
</blockquote></details>

Removed.
___
*[`pal/src/host/linux-sgx/pal_memory.c` line 107 at r1](https://reviewable.io/reviews/gramineproject/gramine/847#-N9fwmkBEVkl5MYPo64w:-N9gCWgcAspYXVPfQ__0:bkoz9ou) ([raw file](https://github.com/gramineproject/gramine/blob/e09846281b0fac4e304f6cf96e17927a8e51c762/pal/src/host/linux-sgx/pal_memory.c#L107)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This defeats the purpose of all the complexity that you introduced for the Linux PAL.

I think there is absolutely no way of determining the amount of available *SGX enclave memory* on a NUMA node, so we shouldn't even try? I mean, the main usage of Gramine is with SGX, so having a proper support for the Linux PAL but *not* for the Linux-SGX PAL makes no sense.

I suggest to simply "mimic" a more or less typical environment: each NUMA node returns:
- `NodeMemTotal = PalMemTotal / numa_nodes_cnt`
- `NodeMemFree = PalMemAvailable / numa_nodes_cnt`
</blockquote></details>

Yeah, my intention was to not even try. Introduced this complex attempt for Linux PAL just for helping w/ the discussions. Updated to the "mimic" scheme, thanks.


<!-- Sent from Reviewable.io -->

2022-08-18 13:16 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/847)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @kailun-qin)

___
*[`pal/src/host/linux-sgx/pal_memory.c` line 107 at r1](https://reviewable.io/reviews/gramineproject/gramine/847#-N9fwmkBEVkl5MYPo64w:-N9l4xv43C4NSgnqKUcM:b6l601g) ([raw file](https://github.com/gramineproject/gramine/blob/e09846281b0fac4e304f6cf96e17927a8e51c762/pal/src/host/linux-sgx/pal_memory.c#L107)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

https://github.com/torvalds/linux/commit/50468e4313355b161cac8a5155a45832995b7f25

Actually, Linux 5.17+ seems to have `NodeMemTotal` these days. Just FYI.
</blockquote></details>

Even more interesting, there will be also `NodeMemFree` implemented in the future Linux releases: https://lore.kernel.org/linux-sgx/f25d95e6-e129-597b-5d93-d7264feae8b8@intel.com/ (at least that's the plan)


<!-- Sent from Reviewable.io -->

2022-08-18 14:17 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/847)* status: 10 of 11 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`libos/src/fs/sys/node_info.c` line 128 at r2](https://reviewable.io/reviews/gramineproject/gramine/847#-N9l3LOb19Dm2WVy0oBG:-N9lHGrLDfaJvdQ14-34:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/83ceb5fc853dca628ef52eb388d51ed3b013e367/libos/src/fs/sys/node_info.c#L128)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I think we prefer to use `elixir`? So it should be
`https://elixir.bootlin.com/linux/v5.19/source/drivers/base/node.c#L369`
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/pal_memory.c` line 107 at r1](https://reviewable.io/reviews/gramineproject/gramine/847#-N9fwmkBEVkl5MYPo64w:-N9lHLbhCPCBh2iQ1TVY:b-oauny1) ([raw file](https://github.com/gramineproject/gramine/blob/e09846281b0fac4e304f6cf96e17927a8e51c762/pal/src/host/linux-sgx/pal_memory.c#L107)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Even more interesting, there will be also `NodeMemFree` implemented in the future Linux releases: https://lore.kernel.org/linux-sgx/f25d95e6-e129-597b-5d93-d7264feae8b8@intel.com/ (at least that's the plan)
</blockquote></details>

Interesting... Thanks for the info!
Q: Would we use these stats for Gramine SGX (in the future)? The current meminfo and node meminfo in Gramine SGX are both based on `PalMemTotal/Available`.


<!-- Sent from Reviewable.io -->

2022-08-18 14:31 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/847)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

___
*[`pal/src/host/linux-sgx/pal_memory.c` line 107 at r1](https://reviewable.io/reviews/gramineproject/gramine/847#-N9fwmkBEVkl5MYPo64w:-N9lM6lGCJvlwEy_5SI9:bqn0ghu) ([raw file](https://github.com/gramineproject/gramine/blob/e09846281b0fac4e304f6cf96e17927a8e51c762/pal/src/host/linux-sgx/pal_memory.c#L107)):*
> Q: Would we use these stats for Gramine SGX (in the future)?

Yeah, we probably should do it. This would be more correct. But in some really distant future, since we still need to support older Linux kernels (and I don't think any SGX app cares at this point about truly correct values).


<!-- Sent from Reviewable.io -->

2022-08-18 14:31 UTC, dimakuv commented
Jenkins, test this please

2022-08-19 07:01 UTC, dimakuv commented
Jenkins, retest Jenkins-18.04 please

Two LTP tests failed, seems unrelated:
```
test-direct / libos.test.ltp.test_ltp.test_ltp[fcntl14_64]
test-direct / libos.test.ltp.test_ltp.test_ltp[fdatasync01]
```

2022-09-01 20:55 UTC, boryspoplawski requested changes
> Reviewed 2 of 11 files at r1, 8 of 9 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/847)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

___
*[`-- commits` line 6 at r3](https://reviewable.io/reviews/gramineproject/gramine/847#-NAudQnXDcqhXEnEPX-v):*
Either change this to past tense or remove the whole para (I guess it's obvious that it didn't emulate them since this commit adds it)



_Code quote:_
```
  Gramine currently doesn't emulate
  `/sys/devices/system/node/nodeX/meminfo` files. This will lead to some
  workload failures due to these missing NUMA node meminfo files.
```
___
*[`libos/src/fs/sys/node_info.c` line 106 at r3](https://reviewable.io/reviews/gramineproject/gramine/847#-NAulwM0CWr-gET0mKot:-NAulwM0CWr-gET0mKou:b-qum5f1) ([raw file](https://github.com/gramineproject/gramine/blob/3e90bb3d915a657f0e737be63174446979cff537/libos/src/fs/sys/node_info.c#L106)):*
> ```C
>     size_t numa_nodes_cnt = g_pal_public_state->topo_info.numa_nodes_cnt;
>     /* Simply "mimic" a typical environment: each NUMA node returns the same proportion of
>      * `MemTotal` and `MemFree` */
> ```

I feel like `proportion` is part of something bigger, like ratio, so this reads weirdly to me. Maybe:



_Suggestion:_
```C
    /* Simply "mimic" a typical environment: split memory evenly between each NUMA node */
```
___
*[`libos/src/fs/sys/node_info.c` line 114 at r3](https://reviewable.io/reviews/gramineproject/gramine/847#-NAumk5qAkXhcXezjNU4:-NAumk5qAkXhcXezjNU5:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/3e90bb3d915a657f0e737be63174446979cff537/libos/src/fs/sys/node_info.c#L114)):*
> ```C
>     int ret;
>     unsigned int node_id;
>     ret = sys_resource_find(dent, "node", &node_id);
> ```





_Suggestion:_
```C
    unsigned int node_id;
    int ret = sys_resource_find(dent, "node", &node_id);
```
___
*[`libos/src/fs/sys/node_info.c` line 119 at r3](https://reviewable.io/reviews/gramineproject/gramine/847#-NAuoTW0D8hf4tAyhlyG:-NAuoTW0D8hf4tAyhlyH:b-5rdbwi) ([raw file](https://github.com/gramineproject/gramine/blob/3e90bb3d915a657f0e737be63174446979cff537/libos/src/fs/sys/node_info.c#L119)):*
> ```C
> 
>     size_t size = 0, max = 256;
>     size_t i = 0;
> ```

Please move this to first usage.
___
*[`libos/src/fs/sys/node_info.c` line 125 at r3](https://reviewable.io/reviews/gramineproject/gramine/847#-NAuoJu2DjRVz8VAoNrw:-NAuoJu2DjRVz8VAoNrx:bxfxx40) ([raw file](https://github.com/gramineproject/gramine/blob/3e90bb3d915a657f0e737be63174446979cff537/libos/src/fs/sys/node_info.c#L125)):*
> ```C
> 
>     /*
>      * Enumerate minimum set of node meminfo stats. This set is based on Linux v5.19, see below for
> ```

In what sense it's minimum set?



_Code quote:_
```C
minimum set
```
___
*[`libos/src/fs/sys/node_info.c` line 135 at r3](https://reviewable.io/reviews/gramineproject/gramine/847#-NAunzFLA1PJuI_Zh4nV:-NAunzFLA1PJuI_Zh4nW:byfrelq) ([raw file](https://github.com/gramineproject/gramine/blob/3e90bb3d915a657f0e737be63174446979cff537/libos/src/fs/sys/node_info.c#L135)):*
> ```C
>         unsigned long val;
>     } meminfo[] = {
>         { "Node %d MemTotal:       %8lu kB\n", node_mem_total / 1024 },
> ```

ditto for all lines



_Suggestion:_
```C
%u 
```
___
*[`libos/src/fs/sys/node_info.c` line 139 at r3](https://reviewable.io/reviews/gramineproject/gramine/847#-NAuo2G83Zts132vJDVE:-NAuo2G83Zts132vJDVF:bq1k2yp) ([raw file](https://github.com/gramineproject/gramine/blob/3e90bb3d915a657f0e737be63174446979cff537/libos/src/fs/sys/node_info.c#L139)):*
> ```C
>         { "Node %d MemUsed:        %8lu kB\n", (node_mem_total - node_mem_free) / 1024 },
>         { "Node %d SwapCached:     %8lu kB\n", /*dummy value=*/0 },
>         { "Node %d Active:         %8lu kB\n", /*dummy value=*/0 },
> ```

What's the point in having all these dummy entries? Does anything uses them? Some of them don't even make sense, like this one (`Active: 0 kB`).
___
*[`libos/src/fs/sys/node_info.c` line 165 at r3](https://reviewable.io/reviews/gramineproject/gramine/847#-NAupZYhCbdizTTZdUIo:-NAupZYhCbdizTTZdUIp:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/3e90bb3d915a657f0e737be63174446979cff537/libos/src/fs/sys/node_info.c#L165)):*
> ```C
> 
>     while (i < ARRAY_SIZE(meminfo)) {
>         int ret = snprintf(str + size, max - size, meminfo[i].fmt, node_id, meminfo[i].val);
> ```




<!-- Sent from Reviewable.io -->

2022-09-02 02:09 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/847)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[`-- commits` line 6 at r3](https://reviewable.io/reviews/gramineproject/gramine/847#-NAudQnXDcqhXEnEPX-v):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Either change this to past tense or remove the whole para (I guess it's obvious that it didn't emulate them since this commit adds it)
</blockquote></details>

Removed the whole para.
___
*[`libos/src/fs/sys/node_info.c` line 106 at r3](https://reviewable.io/reviews/gramineproject/gramine/847#-NAulwM0CWr-gET0mKot:-NAvqmjKAkZyyhTGm48E:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/3e90bb3d915a657f0e737be63174446979cff537/libos/src/fs/sys/node_info.c#L106)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I feel like `proportion` is part of something bigger, like ratio, so this reads weirdly to me. Maybe:
</blockquote></details>

Done.
___
*[`libos/src/fs/sys/node_info.c` line 114 at r3](https://reviewable.io/reviews/gramineproject/gramine/847#-NAumk5qAkXhcXezjNU4:-NAvqnrE568GDCSQMeLO:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/3e90bb3d915a657f0e737be63174446979cff537/libos/src/fs/sys/node_info.c#L114)):*
> ```C
>     int ret;
>     unsigned int node_id;
>     ret = sys_resource_find(dent, "node", &node_id);
> ```

Done.
___
*[`libos/src/fs/sys/node_info.c` line 119 at r3](https://reviewable.io/reviews/gramineproject/gramine/847#-NAuoTW0D8hf4tAyhlyG:-NAvrFpL0aYRiNWHATzR:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/3e90bb3d915a657f0e737be63174446979cff537/libos/src/fs/sys/node_info.c#L119)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please move this to first usage.
</blockquote></details>

Done.
___
*[`libos/src/fs/sys/node_info.c` line 125 at r3](https://reviewable.io/reviews/gramineproject/gramine/847#-NAuoJu2DjRVz8VAoNrw:-NAvuEqfE-8YmXVLm3R8:bsp4p6r) ([raw file](https://github.com/gramineproject/gramine/blob/3e90bb3d915a657f0e737be63174446979cff537/libos/src/fs/sys/node_info.c#L125)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

In what sense it's minimum set?
</blockquote></details>

It's the "built-in/default" stats (w/o specific `#ifdef CONFIG_xxx`) in `https://elixir.bootlin.com/linux/v5.19/source/drivers/base/node.c#L369`.
___
*[`libos/src/fs/sys/node_info.c` line 135 at r3](https://reviewable.io/reviews/gramineproject/gramine/847#-NAunzFLA1PJuI_Zh4nV:-NAvs-Rh3216qcSVOJgs:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/3e90bb3d915a657f0e737be63174446979cff537/libos/src/fs/sys/node_info.c#L135)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto for all lines
</blockquote></details>

Done.
___
*[`libos/src/fs/sys/node_info.c` line 139 at r3](https://reviewable.io/reviews/gramineproject/gramine/847#-NAuo2G83Zts132vJDVE:-NAvswUW2lH1P8dCe7rH:b-f2me0p) ([raw file](https://github.com/gramineproject/gramine/blob/3e90bb3d915a657f0e737be63174446979cff537/libos/src/fs/sys/node_info.c#L139)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

What's the point in having all these dummy entries? Does anything uses them? Some of them don't even make sense, like this one (`Active: 0 kB`).
</blockquote></details>

Maybe not needed... Well, it's just following what's done in `/proc/meminfo`: https://github.com/gramineproject/gramine/blob/f1e1d22d29a08c05a6cf19188aa0241787608371/libos/src/fs/proc/info.c#L44.
___
*[`libos/src/fs/sys/node_info.c` line 165 at r3](https://reviewable.io/reviews/gramineproject/gramine/847#-NAupZYhCbdizTTZdUIo:-NAvsG381UW7V1A1LJBs:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/3e90bb3d915a657f0e737be63174446979cff537/libos/src/fs/sys/node_info.c#L165)):*
> ```C
> 
>     while (i < ARRAY_SIZE(meminfo)) {
>         int ret = snprintf(str + size, max - size, meminfo[i].fmt, node_id, meminfo[i].val);
> ```

Done.


<!-- Sent from Reviewable.io -->

2022-09-02 07:23 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/847)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " and "squash! " found in commit messages' one-liners (waiting on @boryspoplawski and @kailun-qin)

___
*[`-- commits` line 32 at r4](https://reviewable.io/reviews/gramineproject/gramine/847#-NAx2GXg-Isz2KFDjKAz):*
`for the above usage` -> `for meminfo files`
___
*[`libos/src/fs/sys/node_info.c` line 125 at r3](https://reviewable.io/reviews/gramineproject/gramine/847#-NAuoJu2DjRVz8VAoNrw:-NAx2TIE1SmuGzkI7joN:by909l3) ([raw file](https://github.com/gramineproject/gramine/blob/3e90bb3d915a657f0e737be63174446979cff537/libos/src/fs/sys/node_info.c#L125)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

It's the "built-in/default" stats (w/o specific `#ifdef CONFIG_xxx`) in `https://elixir.bootlin.com/linux/v5.19/source/drivers/base/node.c#L369`.
</blockquote></details>

Please add this explanation to the text:
```
* Enumerate minimum set of node meminfo stats (the default stats in Linux, without specific `#ifdef CONFIG_xxx`).
* This set is based ...
```
___
*[`libos/src/fs/sys/node_info.c` line 139 at r3](https://reviewable.io/reviews/gramineproject/gramine/847#-NAuo2G83Zts132vJDVE:-NAx2qD579jbFaE9fSoh:b-7ne3t6) ([raw file](https://github.com/gramineproject/gramine/blob/3e90bb3d915a657f0e737be63174446979cff537/libos/src/fs/sys/node_info.c#L139)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Maybe not needed... Well, it's just following what's done in `/proc/meminfo`: https://github.com/gramineproject/gramine/blob/f1e1d22d29a08c05a6cf19188aa0241787608371/libos/src/fs/proc/info.c#L44.
</blockquote></details>

@boryspoplawski Sometimes applications have logic that checks that the expected entries indeed exist. Here is a random example I found: https://github.com/eminence/procfs/blob/fc91e469cfafc07007385d006f4fd928e4538bb7/src/meminfo.rs#L385

This example checks that all "expected" values were found and were removed from the temporary `map`, otherwise this crate fails. In this example of course we have an assert, so this is only relevant for debug builds. But I remember hitting this bug, which prevented some Rust app to run.

So I would keep these dummy entries, simply because many applications assume that if there is no entry, then there is a bug or a too-old Linux kernel. The applications may never use these entries, but the checks are there...


<!-- Sent from Reviewable.io -->

2022-09-02 07:31 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/847)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " and "squash! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[`-- commits` line 32 at r4](https://reviewable.io/reviews/gramineproject/gramine/847#-NAx2GXg-Isz2KFDjKAz):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`for the above usage` -> `for meminfo files`
</blockquote></details>

Done.
___
*[`libos/src/fs/sys/node_info.c` line 125 at r3](https://reviewable.io/reviews/gramineproject/gramine/847#-NAuoJu2DjRVz8VAoNrw:-NAx5Aht-dNttq5zJOt3:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/3e90bb3d915a657f0e737be63174446979cff537/libos/src/fs/sys/node_info.c#L125)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add this explanation to the text:
```
* Enumerate minimum set of node meminfo stats (the default stats in Linux, without specific `#ifdef CONFIG_xxx`).
* This set is based ...
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-09-02 07:44 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/847)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " and "squash! " found in commit messages' one-liners (waiting on @boryspoplawski and @kailun-qin)

___
*[`libos/src/fs/sys/node_info.c` line 122 at r5](https://reviewable.io/reviews/gramineproject/gramine/847#-NAx9A0N-GADyD8ni73F:-NAx9A0N-GADyD8ni73G:b6cq05d) ([raw file](https://github.com/gramineproject/gramine/blob/85e10d2b4b0c37ff087f56dd099c1d8a4d838e65/libos/src/fs/sys/node_info.c#L122)):*
> ```C
> 
>     /*
>      * Enumerate minimum set of node meminfo stats (the default stats in Linux, without specific `#ifdef CONFIG_xxx`).
> ```

Please re-wrap to 100 chars per line


<!-- Sent from Reviewable.io -->

2022-09-02 07:54 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/847)* status: 10 of 11 files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[`libos/src/fs/sys/node_info.c` line 122 at r5](https://reviewable.io/reviews/gramineproject/gramine/847#-NAx9A0N-GADyD8ni73F:-NAxBKEs6kDt-qTf1DkC:b-dtkds3) ([raw file](https://github.com/gramineproject/gramine/blob/85e10d2b4b0c37ff087f56dd099c1d8a4d838e65/libos/src/fs/sys/node_info.c#L122)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please re-wrap to 100 chars per line
</blockquote></details>

Done, thanks!


<!-- Sent from Reviewable.io -->

2022-09-02 08:49 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/847)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)



<!-- Sent from Reviewable.io -->

2022-09-02 13:57 UTC, boryspoplawski approved these changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/847)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @kailun-qin)

___
*[`libos/src/fs/sys/node_info.c` line 139 at r3](https://reviewable.io/reviews/gramineproject/gramine/847#-NAuo2G83Zts132vJDVE:-NAyUBO9BGkm3Urcnhyw:bmp8zok) ([raw file](https://github.com/gramineproject/gramine/blob/3e90bb3d915a657f0e737be63174446979cff537/libos/src/fs/sys/node_info.c#L139)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@boryspoplawski Sometimes applications have logic that checks that the expected entries indeed exist. Here is a random example I found: https://github.com/eminence/procfs/blob/fc91e469cfafc07007385d006f4fd928e4538bb7/src/meminfo.rs#L385

This example checks that all "expected" values were found and were removed from the temporary `map`, otherwise this crate fails. In this example of course we have an assert, so this is only relevant for debug builds. But I remember hitting this bug, which prevented some Rust app to run.

So I would keep these dummy entries, simply because many applications assume that if there is no entry, then there is a bug or a too-old Linux kernel. The applications may never use these entries, but the checks are there...
</blockquote></details>

But then we would have to add everything for such apps to work, while we skip some fields (hidden behind `ifdef CONFIG_...` in Linux kernel).


<!-- Sent from Reviewable.io -->

2022-09-05 07:58 UTC, dimakuv submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/847)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @kailun-qin)

___
*[`libos/src/fs/sys/node_info.c` line 139 at r3](https://reviewable.io/reviews/gramineproject/gramine/847#-NAuo2G83Zts132vJDVE:-NBBdsA_0KkJBBtUyt7n:b-8wlzmi) ([raw file](https://github.com/gramineproject/gramine/blob/3e90bb3d915a657f0e737be63174446979cff537/libos/src/fs/sys/node_info.c#L139)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

But then we would have to add everything for such apps to work, while we skip some fields (hidden behind `ifdef CONFIG_...` in Linux kernel).
</blockquote></details>

Technically yes. But these apps use a subset of (most frequently used/relevant) fields, and hopefully they don't use the "hidden" fields.


<!-- Sent from Reviewable.io -->

2022-09-05 07:59 UTC, dimakuv commented
Jenkins, test this please

2022-09-15 15:31 UTC, mkow approved these changes
> Reviewed 2 of 11 files at r1, 8 of 9 files at r2, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/847)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @kailun-qin)



<!-- Sent from Reviewable.io -->

2022-09-15 16:05 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/847)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2022-09-15 16:06 UTC, dimakuv commented
Jenkins, test this please

2022-09-15 16:07 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/847)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-09-15 16:14 UTC, boryspoplawski approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/847)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-09-15 17:02 UTC, merged