First iteration of  `etc` passthrough
gramineproject/gramine pull request #850
Opened 2022-08-17 16:42 UTC by oshogbo

## Description of the changes 

The first `etc` passthrough file is the `/etc/hostname`. Gramine reads the option to global PAL state, and LibOS uses it to create a pseudo file with its content. Gramine sanitizes hostname. It requires that it is a valid domain. This is a difference from Linux, as Linux accepts any hostname value. That said, Linux doesn't assume that the root user tries to exploit it through hostname, and Gramine should.

Gramine uses pseudofs for `etc` passthrough.

From what I can see, most applications use the `uname(2)` syscall to obtain a current hostname, for example: [gethostame](https://code.woboq.org/userspace/glibc/sysdeps/posix/gethostname.c.html). 
The `/etc/hostname` is read during startup, and the `sethostname(2)` is called. For example, this is done on Ubuntu 20.04 with `/etc/init/hostname.conf` script. 

This change doesn't address the support of the `sethostname(2)`. The value in `/etc/hostname` and hostname may differ (on Linux  `sethostname(2)` syscall changes only kernel value but not the value in `/etc/hostname`). We probably should separately propagate the current value of the hostname. We are also missing a mechanism for propagating the hostname across multiple processes. We might also decide just to remove `sethostname(2)` completely. My understanding is that we have it only to enable LTP tests.

## Issue

https://github.com/gramineproject/gramine/issues/689

## Next step

* Add support for `resolv.conf`

## How to test this PR?

New tests added.

2022-08-18 11:50 UTC, dimakuv requested changes
> Reviewed 30 of 30 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/850)* status: all files reviewed, 48 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @oshogbo)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/850#-N9kGW1tD-ToHXrU8Ks9):*
I'd prefer the name of the file in the one-liner. So maybe append ` (currently only 'hostname')`
___
*[`-- commits` line 5 at r1](https://reviewable.io/reviews/gramineproject/gramine/850#-N9kGkcH3HKRI9PFZOLI):*
`the option` -> `the host file`
___
*[`Documentation/manifest-syntax.rst` line 152 at r1](https://reviewable.io/reviews/gramineproject/gramine/850#-N9kHAvC44BborO-iSI2:-N9kHAvC44BborO-iSI3:b-ycw6wi) ([raw file](https://github.com/gramineproject/gramine/blob/859723bdce536e4f3f53b46845b36ed8a72e9011/Documentation/manifest-syntax.rst#L152)):*
> ```reStructuredText
> 
> - ``/etc/hostname``
> ```

We should also add what happens if the user specifies `/etc/hostname` through this manifest option and through e.g. `sgx.trusted_files` (iiuc, the new manifest option wins and overrides the host file).
___
*[`libos/include/libos_internal.h` line 156 at r1](https://reviewable.io/reviews/gramineproject/gramine/850#-N9kHf_p08GxTAGYRpfI:-N9kHf_p08GxTAGYRpfJ:b-nlurnn) ([raw file](https://github.com/gramineproject/gramine/blob/859723bdce536e4f3f53b46845b36ed8a72e9011/libos/include/libos_internal.h#L156)):*
> ```objc
> long pal_to_unix_errno(long err);
> 
> long libos_set_hostname(char* name, size_t len);
> ```

I would prefer `set_hostname()`. We don't add `libos_` prefix to any functions other than syscall-entrypoint functions, so the current name is confusing to me.
___
*[`libos/src/libos_init.c` line 427 at r1](https://reviewable.io/reviews/gramineproject/gramine/850#-N9kJkkj5T1gCHM_89AX:-N9kJkkj5T1gCHM_89AY:b-luirjt) ([raw file](https://github.com/gramineproject/gramine/blob/859723bdce536e4f3f53b46845b36ed8a72e9011/libos/src/libos_init.c#L427)):*
> ```C
>     RUN_INIT(init_mount);
>     RUN_INIT(init_std_handles);
>     RUN_INIT(init_mount_etc);
> ```

It's important that `init_mount_etc` goes after `init_mount`, right? This forces the override of `/etc/hostname` even if the user specified it in `fs.mounts` manifest option. I would add a quick comment about this.
___
*[`libos/src/fs/libos_fs.c` line 78 at r1](https://reviewable.io/reviews/gramineproject/gramine/850#-N9kI8kj7dAXomaZd6__:-N9kI8kj7dAXomaZd6_a:b-iqyl6f) ([raw file](https://github.com/gramineproject/gramine/blob/859723bdce536e4f3f53b46845b36ed8a72e9011/libos/src/fs/libos_fs.c#L78)):*
> ```C
>         goto err;
> 
>     if ((ret = init_etc()) < 0)
> ```

Why not `init_etcfs` for uniformity with the above functions?
___
*[`libos/src/fs/etc/fs.c` line 7 at r1](https://reviewable.io/reviews/gramineproject/gramine/850#-N9kIzG-83jpYHk7JIaq:-N9kIzG-83jpYHk7JIar:bmmo2j8) ([raw file](https://github.com/gramineproject/gramine/blob/859723bdce536e4f3f53b46845b36ed8a72e9011/libos/src/fs/etc/fs.c#L7)):*
> ```C
> 
> /*
>  * This file contains the implementation of `etc` passthrough.
> ```

`passthrough` -> `FS`?

Here, at this LibOS FS layer, it seems strange to talk about "passthrough" since here the files are not backed by anything from the host, but rather backed by the PAL-state objects.

I would also add that LibOS assumes that contents of all etc files were already sanitized.
___
*[`libos/src/fs/etc/fs.c` line 28 at r1](https://reviewable.io/reviews/gramineproject/gramine/850#-N9kKw4P9cO8bbuiYeuU:-N9kKw4P9cO8bbuiYeuV:b-8e6d0w) ([raw file](https://github.com/gramineproject/gramine/blob/859723bdce536e4f3f53b46845b36ed8a72e9011/libos/src/fs/etc/fs.c#L28)):*
> ```C
> 
> int init_etc(void) {
>     pseudo_add_str(NULL, "hostname", &provide_etc_hostname);
> ```

What kind of magic is this? How can the `parent_node == NULL` (first argument)? What does this actually do?

And how is this connected to `init_mount_etc()`? 

UPDATE: It seems that this creates a "parentless" `hostname` pseudo-file that can be used as a backing storage for `/etc/hostname` in the below function. I'm still struggling to find the exact place in the FS code where this connection happens.
___
*[`libos/src/fs/etc/fs.c` line 28 at r1](https://reviewable.io/reviews/gramineproject/gramine/850#-N9kM5ll0sp9kpW_JmYV:-N9kM5ll0sp9kpW_JmYW:bpcmu20) ([raw file](https://github.com/gramineproject/gramine/blob/859723bdce536e4f3f53b46845b36ed8a72e9011/libos/src/fs/etc/fs.c#L28)):*
> ```C
> 
> int init_etc(void) {
>     pseudo_add_str(NULL, "hostname", &provide_etc_hostname);
> ```

Why do we do this unconditionally? shouldn't we check for `g_pal_public_state->passthrough_etc_files`? Or we don't care about creating an unused pseudo-file?
___
*[`libos/src/fs/etc/fs.c` line 41 at r1](https://reviewable.io/reviews/gramineproject/gramine/850#-N9kKMWE8UJbVxQvsdDK:-N9kKMWE8UJbVxQvsdDL:b-yx5xdo) ([raw file](https://github.com/gramineproject/gramine/blob/859723bdce536e4f3f53b46845b36ed8a72e9011/libos/src/fs/etc/fs.c#L41)):*
> ```C
>         .type = "pseudo",
>         .path = "/etc/hostname",
>         .uri = "hostname",
> ```

What is this URI? Is it useless? I would just call it `"dummy"` then, or set it to NULL (if possible).

UPDATE: Apparently it's not useless, but even after looking at the code, I still don't get the connection between this and "parentless" `hostname` pseudo-file above.
___
*[`libos/src/fs/etc/fs.c` line 56 at r1](https://reviewable.io/reviews/gramineproject/gramine/850#-N9kMWn2A0APQduSH0hz:-N9kMWn2A0APQduSH0i-:bhfvlac) ([raw file](https://github.com/gramineproject/gramine/blob/859723bdce536e4f3f53b46845b36ed8a72e9011/libos/src/fs/etc/fs.c#L56)):*
> ```C
>     /* Propagate hostname */
>     size_t off = ADD_CP_OFFSET(sizeof(g_pal_public_state->hostname) +
>                                sizeof(g_pal_public_state->passthrough_etc_files));
> ```

Why do you need to propagate the boolean `g_pal_public_state->passthrough_etc_files`? It can never change in the child, as it is read from the same manifest file (which cannot be changed).
___
*[`libos/src/sys/libos_uname.c` line 21 at r1](https://reviewable.io/reviews/gramineproject/gramine/850#-N9kNW8x9yD-0VhqQygb:-N9kNW8x9yD-0VhqQygc:b-1t25yf) ([raw file](https://github.com/gramineproject/gramine/blob/859723bdce536e4f3f53b46845b36ed8a72e9011/libos/src/sys/libos_uname.c#L21)):*
> ```C
>  * effects of set{host,domain}name in process A will not be visible in process B.
>  * These syscalls are rarely used and are implemented in Gramine mainly to enable LTP to test
>  * our `uname` implementation. */
> ```

This comment is not exactly correct now. `nodename` is propagated to the child on fork (though not synchronized afterwards). Maybe put a comment about this in a separate paragraph.
___
*[`libos/src/sys/libos_uname.c` line 44 at r1](https://reviewable.io/reviews/gramineproject/gramine/850#-N9kOjBW0KGD3h-rfmSb:-N9kOjBW0KGD3h-rfmSc:b-3tofz0) ([raw file](https://github.com/gramineproject/gramine/blob/859723bdce536e4f3f53b46845b36ed8a72e9011/libos/src/sys/libos_uname.c#L44)):*
> ```C
> 
> long libos_set_hostname(char* name, size_t len) {
>     if (len >= sizeof(g_current_uname.nodename))
> ```

Why `=`? From what I read in the man pages, nodename doesn't need to be null-terminated.
___
*[`libos/src/sys/libos_uname.c` line 54 at r1](https://reviewable.io/reviews/gramineproject/gramine/850#-N9kP9Ht62Ra8ktnpQGQ:-N9kP9Ht62Ra8ktnpQGR:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/859723bdce536e4f3f53b46845b36ed8a72e9011/libos/src/sys/libos_uname.c#L54)):*
> ```C
> 
> long libos_syscall_sethostname(char* name, int len) {
>     if (len < 0 || (size_t)len >= sizeof(g_current_uname.nodename))
> ```

ditto
___
*[`libos/test/regression/hostname.c` line 3 at r1](https://reviewable.io/reviews/gramineproject/gramine/850#-N9kPFWw36TvkpfjaTHY:-N9kP [...]

2022-08-19 08:49 UTC, dimakuv requested changes
> Reviewed 20 of 18 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/850)* status: all files reviewed, 14 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "squash! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @oshogbo)

___
*[`Documentation/manifest-syntax.rst` line 153 at r2](https://reviewable.io/reviews/gramineproject/gramine/850#-N9pBVb23FRLGJM3YV3f:-N9pBVb37zisvKDD3jGz:b-mxsaj3) ([raw file](https://github.com/gramineproject/gramine/blob/1cf2d0bfccdc0a5e08d1d941942f6926e7283181/Documentation/manifest-syntax.rst#L153)):*
> ```reStructuredText
> - ``/etc/hostname``
> 
> This option takes precedence over ``fs.mount``.
> ```

`fs.mounts` (forgot `s`)
___
*[`Documentation/manifest-syntax.rst` line 154 at r2](https://reviewable.io/reviews/gramineproject/gramine/850#-N9pB_o4DO9iAnR0EfvK:-N9pB_o4DO9iAnR0EfvL:b-bjvirj) ([raw file](https://github.com/gramineproject/gramine/blob/1cf2d0bfccdc0a5e08d1d941942f6926e7283181/Documentation/manifest-syntax.rst#L154)):*
> ```reStructuredText
> 
> This option takes precedence over ``fs.mount``.
> This means that files provided in it will be overridden with the ones
> ```

`files provided in it` -> `etc files provided via fs.mounts`
___
*[`libos/src/libos_init.c` line 427 at r2](https://reviewable.io/reviews/gramineproject/gramine/850#-N9pBqHY79E_V08fjEaL:-N9pBqHY79E_V08fjEaM:b-nug6l1) ([raw file](https://github.com/gramineproject/gramine/blob/1cf2d0bfccdc0a5e08d1d941942f6926e7283181/libos/src/libos_init.c#L427)):*
> ```C
>     RUN_INIT(init_mount);
>     RUN_INIT(init_std_handles);
>     /* The init_mount_etcfs takes precedence over users fs.mounts, and because of that,
> ```

`users` -> `user's`
___
*[`libos/src/fs/etc/fs.c` line 28 at r1](https://reviewable.io/reviews/gramineproject/gramine/850#-N9kKw4P9cO8bbuiYeuU:-N9pCPnwBMBBEe9RaL4Q:b-gx6fsw) ([raw file](https://github.com/gramineproject/gramine/blob/859723bdce536e4f3f53b46845b36ed8a72e9011/libos/src/fs/etc/fs.c#L28)):*
> And during lookup for a given mountpoint we are doing:
> lookup function->pseudo_lookup->pseudo_find->pseudo_find_root, we find "hostname" pseudofile.

Ah, that's the sequence I was missing! So this "rootless" file is actually a "root-by-itself", and thus will be found during the lookup over pseudo-files.

Just to be sure, @pwmarcz, was that the intention with such "rootless" pseudo-files? Or are we abusing the implementation?
___
*[`libos/src/fs/etc/fs.c` line 41 at r1](https://reviewable.io/reviews/gramineproject/gramine/850#-N9kKMWE8UJbVxQvsdDK:-N9pCtuH3IhMj0LCDTFx:b-eluz0s) ([raw file](https://github.com/gramineproject/gramine/blob/859723bdce536e4f3f53b46845b36ed8a72e9011/libos/src/fs/etc/fs.c#L41)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

The path is where we will mount the file, and the uri is the file we want to mount.
In this case we are mounting a file `hostname` from the `pseudofs` which we just created in `init_etc` function.
</blockquote></details>

Yes, now I get it. Though the `uri` field name is misleading here -- URIs are supposed to be always PAL (host) backed objects, not objects emulated inside the LibOS. But whatever.
___
*[`libos/src/fs/etc/fs.c` line 56 at r1](https://reviewable.io/reviews/gramineproject/gramine/850#-N9kMWn2A0APQduSH0hz:-N9pD7fL9mLpDfTMyL7X:b-qwwvkw) ([raw file](https://github.com/gramineproject/gramine/blob/859723bdce536e4f3f53b46845b36ed8a72e9011/libos/src/fs/etc/fs.c#L56)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

I assumed that in theory we don't know if it the same manifest, and we don't trust the host.
Or we are reading somehow exactly the same manifest file?
</blockquote></details>

Yes, the child reads the same manifest file.

That's because the child has the same MRENCLAVE as the parent. And MRENCLAVE reflects the complete manifest file. And the parent and the child perform mutual SGX-based attestation during fork, so that they make sure that their peer's MRENCLAVE is the same as their own.

In the end, this chain of reasoning leads to the claim that "parent and child enclaves are guaranteed to use the exact same manifest file".

So you don't need to bother about this boolean.
___
*[`libos/src/sys/libos_uname.c` line 21 at r1](https://reviewable.io/reviews/gramineproject/gramine/850#-N9kNW8x9yD-0VhqQygb:-N9pE9-w2aOvnb3w_VTG:b4q3nh9) ([raw file](https://github.com/gramineproject/gramine/blob/859723bdce536e4f3f53b46845b36ed8a72e9011/libos/src/sys/libos_uname.c#L21)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Not really. Please notice that if you do `sethostname`, and fork the hostname will be different in child and parent after fork (this is described detailed in PR description). This is one of the issues the value of `/etc/hostname` is not corresponding to the current name of hostname.
</blockquote></details>

Ah, yes, you're right. I confused the two objects:
- On LibOS initialization, we set hostname to the value of `g_pal_public_state->hostname` (which is inited by PAL in main process or inherited in checkpoint in child processes)
- On `sethostname()`, we update hostname via `g_current_uname.nodename` (this object is not tied to the above one, and not checkpointed).

So the parent process may have updated `g_current_uname.nodename` (which is the source for `gethostname`) but this change is not reflected in `g_pal_public_state->hostname`. And the child received the latter string in the checkpoint, so the child returns this unchanged string in `gethostname`. So here's a discrepancy.

Meh, this is a mess with `sethostname()`. Whatever, no sane app should use it anyway, and we already have a comment about this wrong behavior.
___
*[`libos/src/sys/libos_uname.c` line 44 at r1](https://reviewable.io/reviews/gramineproject/gramine/850#-N9kOjBW0KGD3h-rfmSb:-N9pFMG49VTdMqbzMqsV:b-vc0kud) ([raw file](https://github.com/gramineproject/gramine/blob/859723bdce536e4f3f53b46845b36ed8a72e9011/libos/src/sys/libos_uname.c#L44)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

I don't know to be honest.
This was introduced by @mkow in bcca3915f177507587b9d581da78d3d92258d6f9.
</blockquote></details>

Let's wait for @mkow's review then.
___
*[`libos/test/regression/hostname_pass_etc.manifest.template` line 10 at r2](https://reviewable.io/reviews/gramineproject/gramine/850#-N9pFqVl2T9hfbEmkvzc:-N9pFqVl2T9hfbEmkvzd:bgo1th1) ([raw file](https://github.com/gramineproject/gramine/blob/1cf2d0bfccdc0a5e08d1d941942f6926e7283181/libos/test/regression/hostname_pass_etc.manifest.template#L10)):*
> ```
>   { path = "/lib", uri = "file:{{ gramine.runtimedir(libc) }}" },
>   { path = "/hostname", uri = "file:{{ binary_dir }}/hostname" },
>   # dummy file to check that `libos.passthrough_etc_files` overrides
> ```

`...overrides /etc/hostname unconditionally`
___
*[`libos/test/regression/test_libos.py` line 1124 at r2](https://reviewable.io/reviews/gramineproject/gramine/850#-N9pG9HG0HYBFHtjMTsb:-N9pG9HG0HYBFHtjMTsc:b-8wf5ah) ([raw file](https://github.com/gramineproject/gramine/blob/1cf2d0bfccdc0a5e08d1d941942f6926e7283181/libos/test/regression/test_libos.py#L1124)):*
> ```Python
> 
>     def test_070_hostname_localhost(self):
>         # The manifest doesn't contain etc passthrough.
> ```

`The manifest` -> `The generic manifest (manifest.template)`
___
*[`pal/src/host/linux/pal_main.c` line 424 at r1](https://reviewable.io/reviews/gramineproject/gramine/850#-N9kgSIi4A3WFtDrgunq:-N9pGZAP3gE5Fi6IFyz0:b-5xk3bx) ([raw file](https://github.com/gramineproject/gramine/blob/859723bdce536e4f3f53b46845b36ed8a72e9011/pal/src/host/linux/pal_main.c#L424)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockq [...]

2022-08-19 14:47 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/850)* status: all files reviewed, 14 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "squash! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @oshogbo)

___
*[`libos/src/fs/etc/fs.c` line 28 at r1](https://reviewable.io/reviews/gramineproject/gramine/850#-N9kKw4P9cO8bbuiYeuU:-N9qX0w4ECrUwinZEfz5:b-3q03kw) ([raw file](https://github.com/gramineproject/gramine/blob/859723bdce536e4f3f53b46845b36ed8a72e9011/libos/src/fs/etc/fs.c#L28)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> And during lookup for a given mountpoint we are doing:
> lookup function->pseudo_lookup->pseudo_find->pseudo_find_root, we find "hostname" pseudofile.

Ah, that's the sequence I was missing! So this "rootless" file is actually a "root-by-itself", and thus will be found during the lookup over pseudo-files.

Just to be sure, @pwmarcz, was that the intention with such "rootless" pseudo-files? Or are we abusing the implementation?
</blockquote></details>

Yes, that was the intended use. But I can see how that might be hard to find out.

The problem, I guess, is that the pseudo-fs abuses node name as an identifier by which you mount a node.

One way to modify this would be to add an explicit "register" step:

```c
struct pseudo_node* hostname = pseudo_add_str(NULL, "hostname", &provide_etc_hostname);
pseudo_add_root("etc-hostname", hostname);

...

ret = mount_fs(&(struct libos_mount_params){
    .type = "pseudo",
    .path = "/etc/hostname",
    .uri = "etc-hostname",
});
```

Then, the pseudo-filesystem would maintain an explicit identifier-to-node mapping. More verbose, but perhaps less confusing. I'm not sure.


<!-- Sent from Reviewable.io -->

2022-08-21 18:19 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/850)* status: 23 of 30 files reviewed, 14 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @oshogbo)

___
*[`Documentation/manifest-syntax.rst` line 153 at r2](https://reviewable.io/reviews/gramineproject/gramine/850#-N9pBVb23FRLGJM3YV3f:-N9phECIEtXBjc9Xrpsh:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/1cf2d0bfccdc0a5e08d1d941942f6926e7283181/Documentation/manifest-syntax.rst#L153)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`fs.mounts` (forgot `s`)
</blockquote></details>

Done.
___
*[`Documentation/manifest-syntax.rst` line 154 at r2](https://reviewable.io/reviews/gramineproject/gramine/850#-N9pB_o4DO9iAnR0EfvK:-N9phDjpChoPdLcd-rbn:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/1cf2d0bfccdc0a5e08d1d941942f6926e7283181/Documentation/manifest-syntax.rst#L154)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`files provided in it` -> `etc files provided via fs.mounts`
</blockquote></details>

Done.
___
*[`libos/src/libos_init.c` line 427 at r2](https://reviewable.io/reviews/gramineproject/gramine/850#-N9pBqHY79E_V08fjEaL:-N9phDYS8Jjdr_bpyAX5:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/1cf2d0bfccdc0a5e08d1d941942f6926e7283181/libos/src/libos_init.c#L427)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`users` -> `user's`
</blockquote></details>

Done.
___
*[`libos/src/fs/etc/fs.c` line 56 at r1](https://reviewable.io/reviews/gramineproject/gramine/850#-N9kMWn2A0APQduSH0hz:-NA0VE4g7gSFKJFfsGlp:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/859723bdce536e4f3f53b46845b36ed8a72e9011/libos/src/fs/etc/fs.c#L56)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, the child reads the same manifest file.

That's because the child has the same MRENCLAVE as the parent. And MRENCLAVE reflects the complete manifest file. And the parent and the child perform mutual SGX-based attestation during fork, so that they make sure that their peer's MRENCLAVE is the same as their own.

In the end, this chain of reasoning leads to the claim that "parent and child enclaves are guaranteed to use the exact same manifest file".

So you don't need to bother about this boolean.
</blockquote></details>

Done.
___
*[`libos/src/sys/libos_uname.c` line 21 at r1](https://reviewable.io/reviews/gramineproject/gramine/850#-N9kNW8x9yD-0VhqQygb:-N9phMXp-E4yywCSQUra:b29hiv5) ([raw file](https://github.com/gramineproject/gramine/blob/859723bdce536e4f3f53b46845b36ed8a72e9011/libos/src/sys/libos_uname.c#L21)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ah, yes, you're right. I confused the two objects:
- On LibOS initialization, we set hostname to the value of `g_pal_public_state->hostname` (which is inited by PAL in main process or inherited in checkpoint in child processes)
- On `sethostname()`, we update hostname via `g_current_uname.nodename` (this object is not tied to the above one, and not checkpointed).

So the parent process may have updated `g_current_uname.nodename` (which is the source for `gethostname`) but this change is not reflected in `g_pal_public_state->hostname`. And the child received the latter string in the checkpoint, so the child returns this unchanged string in `gethostname`. So here's a discrepancy.

Meh, this is a mess with `sethostname()`. Whatever, no sane app should use it anyway, and we already have a comment about this wrong behavior.
</blockquote></details>

Yes, Borys was suggesting to remove `sethostname(2)`, but I guess we have to discuss this further.
___
*[`libos/test/regression/hostname_pass_etc.manifest.template` line 10 at r2](https://reviewable.io/reviews/gramineproject/gramine/850#-N9pFqVl2T9hfbEmkvzc:-N9phkt03r854qiKirVG:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/1cf2d0bfccdc0a5e08d1d941942f6926e7283181/libos/test/regression/hostname_pass_etc.manifest.template#L10)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`...overrides /etc/hostname unconditionally`
</blockquote></details>

Done.
___
*[`libos/test/regression/test_libos.py` line 1124 at r2](https://reviewable.io/reviews/gramineproject/gramine/850#-N9pG9HG0HYBFHtjMTsb:-N9phwIkBU5BZTx75ee9:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/1cf2d0bfccdc0a5e08d1d941942f6926e7283181/libos/test/regression/test_libos.py#L1124)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`The manifest` -> `The generic manifest (manifest.template)`
</blockquote></details>

Done.
___
*[`pal/src/host/linux/pal_main.c` line 424 at r1](https://reviewable.io/reviews/gramineproject/gramine/850#-N9kgSIi4A3WFtDrgunq:-N9pij8B3JEIxGHc-Ria:b-jsqx58) ([raw file](https://github.com/gramineproject/gramine/blob/859723bdce536e4f3f53b46845b36ed8a72e9011/pal/src/host/linux/pal_main.c#L424)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can we move it back? In the future, when we'll look at this commit, we'll scratch our heads -- why did we move this?
</blockquote></details>

Oh, duh- Now I remember why I move it :)
I move `get_host_info` to be after we initialise `manifest.root`.
Topology don't need any information from `manifest` so it could be before it, but the etc passthrough requires it.
___
*[`pal/src/host/linux-sgx/pal_main.c` line 250 at r1](https://reviewable.io/reviews/gramineproject/gramine/850#-N9kk5o80nI0pPxCieit:-N9pjm6O6AnTOk6zvXWD:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/859723bdce536e4f3f53b46845b36ed8a72e9011/pal/src/host/linux-sgx/pal_main.c#L250)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add the "rules I have applied" list as the top-level comment. And please add the links you provided in the same comment.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-22 07:46 UTC, dimakuv requested changes
> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/850)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @oshogbo)

___
*[`libos/src/fs/etc/fs.c` line 28 at r1](https://reviewable.io/reviews/gramineproject/gramine/850#-N9kKw4P9cO8bbuiYeuU:-NA3SVEL8jZESS8LlN8r:b-twzapg) ([raw file](https://github.com/gramineproject/gramine/blob/859723bdce536e4f3f53b46845b36ed8a72e9011/libos/src/fs/etc/fs.c#L28)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Yes, that was the intended use. But I can see how that might be hard to find out.

The problem, I guess, is that the pseudo-fs abuses node name as an identifier by which you mount a node.

One way to modify this would be to add an explicit "register" step:

```c
struct pseudo_node* hostname = pseudo_add_str(NULL, "hostname", &provide_etc_hostname);
pseudo_add_root("etc-hostname", hostname);

...

ret = mount_fs(&(struct libos_mount_params){
    .type = "pseudo",
    .path = "/etc/hostname",
    .uri = "etc-hostname",
});
```

Then, the pseudo-filesystem would maintain an explicit identifier-to-node mapping. More verbose, but perhaps less confusing. I'm not sure.
</blockquote></details>

Thanks for explanations. I don't think the proposed code snippet helps that much. Anyway, now at least two people know how it works :)
___
*[`pal/include/host/linux-common/host_info.h` line 11 at r1](https://reviewable.io/reviews/gramineproject/gramine/850#-N9kexJK-w2pNqz1DIG1:-NA3TuZK9OFlqDh8qoK3:b-fa2yaw) ([raw file](https://github.com/gramineproject/gramine/blob/859723bdce536e4f3f53b46845b36ed8a72e9011/pal/include/host/linux-common/host_info.h#L11)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Yes, I will add here rest of functions corresponding to host_info (like resolv.conf ect.).
</blockquote></details>

Ok, then you shouldn't move stuff from `topo_info.h` into here. Resolving.
___
*[`pal/src/host/linux-common/host_info.c` line 23 at r1](https://reviewable.io/reviews/gramineproject/gramine/850#-N9khT-DCbWjXRIowysz:-NA3UXkb5uRiR3mbWpDC:bjcvql4) ([raw file](https://github.com/gramineproject/gramine/blob/859723bdce536e4f3f53b46845b36ed8a72e9011/pal/src/host/linux-common/host_info.c#L23)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

You mean return value or `errno`?
</blockquote></details>

No, `errno` is not available here. The `DO_SYSCALL()` macro calls the raw syscall, not the Glibc wrapper around it (recall that the Glibc wrapper moves the error code from the raw syscall result to `errno` global variable).

So you should simply do like this:
```
    int ret = DO_SYSCALL(uname, &c_uname);
    if (ret < 0)
        return ret;
```


<!-- Sent from Reviewable.io -->

2022-08-22 09:24 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/850)* status: 29 of 30 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @oshogbo)

___
*[`pal/src/host/linux-common/host_info.c` line 23 at r1](https://reviewable.io/reviews/gramineproject/gramine/850#-N9khT-DCbWjXRIowysz:-NA3qkX-0NXJHwiMqXRq:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/859723bdce536e4f3f53b46845b36ed8a72e9011/pal/src/host/linux-common/host_info.c#L23)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

No, `errno` is not available here. The `DO_SYSCALL()` macro calls the raw syscall, not the Glibc wrapper around it (recall that the Glibc wrapper moves the error code from the raw syscall result to `errno` global variable).

So you should simply do like this:
```
    int ret = DO_SYSCALL(uname, &c_uname);
    if (ret < 0)
        return ret;
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-22 11:51 UTC, dimakuv reviewed
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/850)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @oshogbo)



<!-- Sent from Reviewable.io -->

2022-08-22 13:10 UTC, mkow requested changes
> Reviewed 2 of 30 files at r1, 6 of 18 files at r2, 3 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/850)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @oshogbo, and @pwmarcz)

___
*[`-- commits` line 27 at r4](https://reviewable.io/reviews/gramineproject/gramine/850#-NA4NEvx1bxAZTeK_X_y):*
I'd rephrase this whole section when rebasing, all these super short sentences read weirdly to me.
___
*[`Documentation/manifest-syntax.rst` line 139 at r4](https://reviewable.io/reviews/gramineproject/gramine/850#-NA4OMpf37rLkUHS_GWU:-NA4OMpf37rLkUHS_GWV:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/971d215eda6fe59256bbeac9ed2f0ee38f11adc7/Documentation/manifest-syntax.rst#L139)):*
> ```reStructuredText
> manifest, the application will get ``argv = [ <libos.entrypoint value> ]``.
> 
> etc passthrough
> ```





_Suggestion:_
```reStructuredText
``/etc``
```
___
*[`Documentation/manifest-syntax.rst` line 147 at r4](https://reviewable.io/reviews/gramineproject/gramine/850#-NA4ODBe3k9Rc2iduAH3:-NA4ODBe3k9Rc2iduAH4:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/971d215eda6fe59256bbeac9ed2f0ee38f11adc7/Documentation/manifest-syntax.rst#L147)):*
> ```reStructuredText
>     (Default: false)
> 
> This specifies whether to passthrough extra runtime files from ``/etc``.
> ```





_Suggestion:_
```reStructuredText
from host's ``/etc``
```
___
*[`Documentation/manifest-syntax.rst` line 147 at r4](https://reviewable.io/reviews/gramineproject/gramine/850#-NA4P28VD_THuKHVBpLg:-NA4P28VD_THuKHVBpLh:bualq62) ([raw file](https://github.com/gramineproject/gramine/blob/971d215eda6fe59256bbeac9ed2f0ee38f11adc7/Documentation/manifest-syntax.rst#L147)):*
> ```reStructuredText
>     (Default: false)
> 
> This specifies whether to passthrough extra runtime files from ``/etc``.
> ```

Just a note: this will need to be rephrased after we start supporting non-Linux hosts (it'll be generated there based on host configs).



_Code quote:_
```reStructuredText
This specifies whether to passthrough extra runtime files from ``/etc``.
```
___
*[`libos/include/libos_internal.h` line 156 at r4](https://reviewable.io/reviews/gramineproject/gramine/850#-NA4PVFK9KELQ9ykDoj_:-NA4PVFK9KELQ9ykDoja:b-ceczux) ([raw file](https://github.com/gramineproject/gramine/blob/971d215eda6fe59256bbeac9ed2f0ee38f11adc7/libos/include/libos_internal.h#L156)):*
> ```objc
> long pal_to_unix_errno(long err);
> 
> long set_hostname(char* name, size_t len);
> ```

We return error codes via `int` in our codebase



_Suggestion:_
```objc
int set_hostname
```
___
*[`libos/src/fs/etc/fs.c` line 28 at r1](https://reviewable.io/reviews/gramineproject/gramine/850#-N9kKw4P9cO8bbuiYeuU:-NA4X03b6yd7Dx4MR--W:b-eo21gv) ([raw file](https://github.com/gramineproject/gramine/blob/859723bdce536e4f3f53b46845b36ed8a72e9011/libos/src/fs/etc/fs.c#L28)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Thanks for explanations. I don't think the proposed code snippet helps that much. Anyway, now at least two people know how it works :)
</blockquote></details>

So, do I understand correctly, that right now `"hostname"` string passed to `pseudo_add_str()` is both the filename _and_ a global identifier by which you can mount this node?
If that's the case, then I really like the idea with explicit registration, as the filenames can collide quite easily after we add support for more files, plus the current way is quite confusing.
___
*[`libos/src/fs/etc/fs.c` line 41 at r1](https://reviewable.io/reviews/gramineproject/gramine/850#-N9kKMWE8UJbVxQvsdDK:-NA4eeyBAikBdYETGnat:bc0jg95) ([raw file](https://github.com/gramineproject/gramine/blob/859723bdce536e4f3f53b46845b36ed8a72e9011/libos/src/fs/etc/fs.c#L41)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, now I get it. Though the `uri` field name is misleading here -- URIs are supposed to be always PAL (host) backed objects, not objects emulated inside the LibOS. But whatever.
</blockquote></details>

+1, this was also confusing to me, but see the other discussion.
___
*[`libos/src/sys/libos_uname.c` line 44 at r1](https://reviewable.io/reviews/gramineproject/gramine/850#-N9kOjBW0KGD3h-rfmSb:-N9sJnKr0YvLYPmpn45g:bxn7ljw) ([raw file](https://github.com/gramineproject/gramine/blob/859723bdce536e4f3f53b46845b36ed8a72e9011/libos/src/sys/libos_uname.c#L44)):*
> nodename doesn't need to be null-terminated

But that's exactly why we need `>=`? We need to have space in the buffer to append that NULL byte ourselves. If `len == sizeof(g_current_uname.nodename)` then the `memset` below will overflow the buffer.


<!-- Sent from Reviewable.io -->

2022-08-22 13:31 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/850)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @oshogbo)

___
*[`libos/src/fs/etc/fs.c` line 28 at r1](https://reviewable.io/reviews/gramineproject/gramine/850#-N9kKw4P9cO8bbuiYeuU:-NA4jTo47AIayD9-ZKAD:bci3gvm) ([raw file](https://github.com/gramineproject/gramine/blob/859723bdce536e4f3f53b46845b36ed8a72e9011/libos/src/fs/etc/fs.c#L28)):*
>  both the filename and a global identifier

No, it's only a global identifier. I don't know what you mean exactly by "the filename". Actually, it could be anything, we can rename `"hostname"` -> `"hostname_backing_pseudo_file"`. And then use this renamed string in `init_mount_etcfs()` below. Well, maybe we should do it?
___
*[`libos/src/sys/libos_uname.c` line 44 at r1](https://reviewable.io/reviews/gramineproject/gramine/850#-N9kOjBW0KGD3h-rfmSb:-NA4jz5I3qCzoO-oEId2:b-m5sfop) ([raw file](https://github.com/gramineproject/gramine/blob/859723bdce536e4f3f53b46845b36ed8a72e9011/libos/src/sys/libos_uname.c#L44)):*
> We need to have space in the buffer to append that NULL byte ourselves

Why do we need to append the NULL byte? We're emulating `sethostname()` syscall, and it may return a non-NULL-terminated string.


<!-- Sent from Reviewable.io -->

2022-08-22 16:03 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/850)* status: 26 of 30 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @oshogbo)

___
*[`Documentation/manifest-syntax.rst` line 139 at r4](https://reviewable.io/reviews/gramineproject/gramine/850#-NA4OMpf37rLkUHS_GWU:-NA5GiSX-7qOYSJ4ep4o:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/971d215eda6fe59256bbeac9ed2f0ee38f11adc7/Documentation/manifest-syntax.rst#L139)):*
> ```reStructuredText
> manifest, the application will get ``argv = [ <libos.entrypoint value> ]``.
> 
> etc passthrough
> ```

Done.
___
*[`Documentation/manifest-syntax.rst` line 147 at r4](https://reviewable.io/reviews/gramineproject/gramine/850#-NA4ODBe3k9Rc2iduAH3:-NA5GoHf4L9J0cgA17O7:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/971d215eda6fe59256bbeac9ed2f0ee38f11adc7/Documentation/manifest-syntax.rst#L147)):*
> ```reStructuredText
>     (Default: false)
> 
> This specifies whether to passthrough extra runtime files from ``/etc``.
> ```

Done.
___
*[`libos/include/libos_internal.h` line 156 at r4](https://reviewable.io/reviews/gramineproject/gramine/850#-NA4PVFK9KELQ9ykDoj_:-NA5H1A0DGlgr05jlRba:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/971d215eda6fe59256bbeac9ed2f0ee38f11adc7/libos/include/libos_internal.h#L156)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

We return error codes via `int` in our codebase
</blockquote></details>

Done.
___
*[`libos/src/fs/etc/fs.c` line 28 at r1](https://reviewable.io/reviews/gramineproject/gramine/850#-N9kKw4P9cO8bbuiYeuU:-NA5H4Rm0i7t5cplnWfF:b-z8i8bh) ([raw file](https://github.com/gramineproject/gramine/blob/859723bdce536e4f3f53b46845b36ed8a72e9011/libos/src/fs/etc/fs.c#L28)):*
> hostname_backing_pseudo_file
Maybe something like that?


<!-- Sent from Reviewable.io -->

2022-08-23 06:18 UTC, dimakuv reviewed
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/850)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @oshogbo)

___
*[`libos/src/fs/etc/fs.c` line 28 at r1](https://reviewable.io/reviews/gramineproject/gramine/850#-N9kKw4P9cO8bbuiYeuU:-NA8LSdk-Hd_No3C5sZp:bnouszc) ([raw file](https://github.com/gramineproject/gramine/blob/859723bdce536e4f3f53b46845b36ed8a72e9011/libos/src/fs/etc/fs.c#L28)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

> hostname_backing_pseudo_file
Maybe something like that?
</blockquote></details>

I'm fine with this rename.


<!-- Sent from Reviewable.io -->

2022-08-23 13:57 UTC, mkow requested changes
> Reviewed 5 of 30 files at r1, 3 of 18 files at r2, 3 of 7 files at r3, 1 of 1 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/850)* status: all files reviewed, 21 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @oshogbo)

___
*[`Documentation/manifest-syntax.rst` line 139 at r4](https://reviewable.io/reviews/gramineproject/gramine/850#-NA4OMpf37rLkUHS_GWU:-NA9i7XQ-n5_vuTlc1hY:bjz7bjv) ([raw file](https://github.com/gramineproject/gramine/blob/971d215eda6fe59256bbeac9ed2f0ee38f11adc7/Documentation/manifest-syntax.rst#L139)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

What about the slash?
___
*[`libos/src/fs/etc/fs.c` line 28 at r1](https://reviewable.io/reviews/gramineproject/gramine/850#-N9kKw4P9cO8bbuiYeuU:-NA5D17Y31tbutQcLnXx:b10ufqk) ([raw file](https://github.com/gramineproject/gramine/blob/859723bdce536e4f3f53b46845b36ed8a72e9011/libos/src/fs/etc/fs.c#L28)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I'm fine with this rename.
</blockquote></details>

Ah, I misread the call below, the mount path specifies the file name. Then I'm fine with the current version.
___
*[`libos/src/sys/libos_uname.c` line 44 at r1](https://reviewable.io/reviews/gramineproject/gramine/850#-N9kOjBW0KGD3h-rfmSb:-NA9ko8o5dzdXNn8iMLs:bgoyyuu) ([raw file](https://github.com/gramineproject/gramine/blob/859723bdce536e4f3f53b46845b36ed8a72e9011/libos/src/sys/libos_uname.c#L44)):*
> Why do we need to append the NULL byte?

Because that's what Linux does, although the implementation is a bit obfuscated: https://elixir.bootlin.com/linux/v5.19.3/source/kernel/sys.c#L1355

> it may return a non-NULL-terminated string.

It can't.
___
*[`libos/test/regression/hostname.c` line 43 at r5](https://reviewable.io/reviews/gramineproject/gramine/850#-NA9pxK2DCRtTybH6YfW:-NA9pxK2DCRtTybH6YfX:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/9dfc0952a02e96523df5cb9db7001ae0ad95273f/libos/test/regression/hostname.c#L43)):*
> ```C
> 
>     if (strcmp(buf, expected_name) != 0) {
>         errx(1, "%s gethostname doesn't match hostname (expected: %s, got: %s)",
> ```





_Suggestion:_
```C
gethostname result doesn't
```
___
*[`libos/test/regression/hostname.c` line 44 at r5](https://reviewable.io/reviews/gramineproject/gramine/850#-NA9psZ04CS45utlXtCw:-NA9psZ04CS45utlXtCx:b-2y6s2h) ([raw file](https://github.com/gramineproject/gramine/blob/9dfc0952a02e96523df5cb9db7001ae0ad95273f/libos/test/regression/hostname.c#L44)):*
> ```C
>     if (strcmp(buf, expected_name) != 0) {
>         errx(1, "%s gethostname doesn't match hostname (expected: %s, got: %s)",
>                tag, expected_name, buf);
> ```

please fix alignment
___
*[`libos/test/regression/hostname.c` line 55 at r5](https://reviewable.io/reviews/gramineproject/gramine/850#-NA9qMSX62NbLIIqHOET:-NA9qMSX62NbLIIqHOEU:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/9dfc0952a02e96523df5cb9db7001ae0ad95273f/libos/test/regression/hostname.c#L55)):*
> ```C
> 
>     /*
>      * If the etc expected name was not provided, assume that etc shouldn't exist.
> ```





_Suggestion:_
```C
assume that /etc/hostname shouldn't exist
```
___
*[`libos/test/regression/hostname.c` line 68 at r5](https://reviewable.io/reviews/gramineproject/gramine/850#-NA9qWKpCvbRVJfEat3i:-NA9qWKpCvbRVJfEat3j:b-h43apy) ([raw file](https://github.com/gramineproject/gramine/blob/9dfc0952a02e96523df5cb9db7001ae0ad95273f/libos/test/regression/hostname.c#L68)):*
> ```C
>     }
> 
>     int ret = read(fd, buf, sizeof(buf));
> ```

Missing proper retval checks
___
*[`libos/test/regression/hostname.c` line 74 at r5](https://reviewable.io/reviews/gramineproject/gramine/850#-NA9qj0cC2qtnjgTntK7:-NA9qj0cC2qtnjgTntK8:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/9dfc0952a02e96523df5cb9db7001ae0ad95273f/libos/test/regression/hostname.c#L74)):*
> ```C
> 
>     /*
>      * Sometimes etc hostname might have a trailing '\n', gramine is removing it,
> ```





_Suggestion:_
```C
/etc/hostname
```
___
*[`libos/test/regression/hostname.c` line 74 at r5](https://reviewable.io/reviews/gramineproject/gramine/850#-NA9qo9EDfJZJJiVE5Td:-NA9qo9EDfJZJJiVE5Te:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/9dfc0952a02e96523df5cb9db7001ae0ad95273f/libos/test/regression/hostname.c#L74)):*
> ```C
> 
>     /*
>      * Sometimes etc hostname might have a trailing '\n', gramine is removing it,
> ```





_Suggestion:_
```C
Gramine
```
___
*[`libos/test/regression/hostname.c` line 84 at r5](https://reviewable.io/reviews/gramineproject/gramine/850#-NA9r-MD207ftWJZ-Msv:-NA9r-MD207ftWJZ-Msw:b-2y6s2h) ([raw file](https://github.com/gramineproject/gramine/blob/9dfc0952a02e96523df5cb9db7001ae0ad95273f/libos/test/regression/hostname.c#L84)):*
> ```C
>     if (strcmp(buf, expected_name) != 0) {
>         err(1, "%s /etc/hostname don't have a expected value (expected: %s, got: %s)",
>                tag, expected_name, buf);
> ```

please fix alignment
___
*[`libos/test/regression/hostname_pass_etc.manifest.template` line 11 at r5](https://reviewable.io/reviews/gramineproject/gramine/850#-NA9uKr_12SNUxFHJeV6:-NA9uKr_12SNUxFHJeV7:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/9dfc0952a02e96523df5cb9db7001ae0ad95273f/libos/test/regression/hostname_pass_etc.manifest.template#L11)):*
> ```
>   { path = "/hostname", uri = "file:{{ binary_dir }}/hostname" },
>   # dummy file to check that `libos.passthrough_etc_files` overrides
>   # /etc/hosntame unconditionally
> ```





_Suggestion:_
```
hostname
```
___
*[`pal/src/pal_main.c` line 24 at r5](https://reviewable.io/reviews/gramineproject/gramine/850#-NA9vDVg4Dskp64FD5JZ:-NA9vDVg4Dskp64FD5J_:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/9dfc0952a02e96523df5cb9db7001ae0ad95273f/pal/src/pal_main.c#L24)):*
> ```C
>     /* Enable log to catch early initialization errors; it will be overwritten in pal_main(). */
>     .log_level = PAL_LOG_DEFAULT_LEVEL,
>     .hostname = "localhost"
> ```





_Suggestion:_
```C
.hostname = "localhost",
```
___
*[`pal/src/host/linux/pal_main.c` line 424 at r1](https://reviewable.io/reviews/gramineproject/gramine/850#-N9kgSIi4A3WFtDrgunq:-NA9wkBI3dUvyvMBBqOZ:b-i3w9rx) ([raw file](https://github.com/gramineproject/gramine/blob/859723bdce536e4f3f53b46845b36ed8a72e9011/pal/src/host/linux/pal_main.c#L424)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Oh, duh- Now I remember why I move it :)
I move `get_host_info` to be after we initialise `manifest.root`.
Topology don't need any information from `manifest` so it could be before it, but the etc passthrough requires it.
</blockquote></details>

Uh, this is quite a bold move :)
@oshogbo, @dimakuv: Please verify that this is correct, i.e. none of the initializations in those 100 lines between the old and new positions relies on topology info being already initialized. I didn't find any place, but it looks dangerous, so we need to be very careful with it.
___
*[`pal/src/host/linux/pal_main.c` line 135 at r5](https://reviewable.io/reviews/gramineproject/gramine/850#-NA9xC-93Urzn4DmTNiC:-NA9xC-A842AE24OSldu:b-1a5mt0) ([raw file](https://github.com/gramineproject/gramine/blob/9dfc0952a02e96523df5cb9db7001ae0ad95273f/pal/src/host/linux/pal_main.c#L135)):*
> ```C
>     /* Get host information only for the first process. This information will be
>      * checkpointed and restored during forking of the child process(es). */
>     if (!first_process) {
> ```

Why not move this to the top of this function?
___
*[`pal/src/host/linux/pal_mai [...]

2022-08-23 15:31 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/850)* status: all files reviewed, 21 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @oshogbo)

___
*[`Documentation/manifest-syntax.rst` line 139 at r4](https://reviewable.io/reviews/gramineproject/gramine/850#-NA4OMpf37rLkUHS_GWU:-NAA2ZW64zbtLxRogApu:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/971d215eda6fe59256bbeac9ed2f0ee38f11adc7/Documentation/manifest-syntax.rst#L139)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What about the slash?
</blockquote></details>

Done.
___
*[`libos/test/regression/hostname.c` line 43 at r5](https://reviewable.io/reviews/gramineproject/gramine/850#-NA9pxK2DCRtTybH6YfW:-NAA2fL95hAieUlNH5it:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9dfc0952a02e96523df5cb9db7001ae0ad95273f/libos/test/regression/hostname.c#L43)):*
> ```C
> 
>     if (strcmp(buf, expected_name) != 0) {
>         errx(1, "%s gethostname doesn't match hostname (expected: %s, got: %s)",
> ```

Done.
___
*[`libos/test/regression/hostname.c` line 44 at r5](https://reviewable.io/reviews/gramineproject/gramine/850#-NA9psZ04CS45utlXtCw:-NAA2j1M28IVrMNW_q1r:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9dfc0952a02e96523df5cb9db7001ae0ad95273f/libos/test/regression/hostname.c#L44)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

please fix alignment
</blockquote></details>

Done.
___
*[`libos/test/regression/hostname.c` line 55 at r5](https://reviewable.io/reviews/gramineproject/gramine/850#-NA9qMSX62NbLIIqHOET:-NAA2p1o0eHYqY4NsETn:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9dfc0952a02e96523df5cb9db7001ae0ad95273f/libos/test/regression/hostname.c#L55)):*
> ```C
> 
>     /*
>      * If the etc expected name was not provided, assume that etc shouldn't exist.
> ```

Done.
___
*[`libos/test/regression/hostname.c` line 68 at r5](https://reviewable.io/reviews/gramineproject/gramine/850#-NA9qWKpCvbRVJfEat3i:-NAA8g4DAef4RtuK_GKi:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9dfc0952a02e96523df5cb9db7001ae0ad95273f/libos/test/regression/hostname.c#L68)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Missing proper retval checks
</blockquote></details>

Done.
___
*[`libos/test/regression/hostname.c` line 74 at r5](https://reviewable.io/reviews/gramineproject/gramine/850#-NA9qj0cC2qtnjgTntK7:-NAA2xvLA2T1Xl7ejA6u:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9dfc0952a02e96523df5cb9db7001ae0ad95273f/libos/test/regression/hostname.c#L74)):*
> ```C
> 
>     /*
>      * Sometimes etc hostname might have a trailing '\n', gramine is removing it,
> ```

Done.
___
*[`libos/test/regression/hostname.c` line 74 at r5](https://reviewable.io/reviews/gramineproject/gramine/850#-NA9qo9EDfJZJJiVE5Td:-NAA2zqn-tekmmB85QTi:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9dfc0952a02e96523df5cb9db7001ae0ad95273f/libos/test/regression/hostname.c#L74)):*
> ```C
> 
>     /*
>      * Sometimes etc hostname might have a trailing '\n', gramine is removing it,
> ```

Done.
___
*[`libos/test/regression/hostname.c` line 84 at r5](https://reviewable.io/reviews/gramineproject/gramine/850#-NA9r-MD207ftWJZ-Msv:-NAA30wNAvzJEXN0ujJ5:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9dfc0952a02e96523df5cb9db7001ae0ad95273f/libos/test/regression/hostname.c#L84)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

please fix alignment
</blockquote></details>

Done.
___
*[`libos/test/regression/hostname_pass_etc.manifest.template` line 11 at r5](https://reviewable.io/reviews/gramineproject/gramine/850#-NA9uKr_12SNUxFHJeV6:-NAA35fsA16t2BStFqOU:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9dfc0952a02e96523df5cb9db7001ae0ad95273f/libos/test/regression/hostname_pass_etc.manifest.template#L11)):*
> ```
>   { path = "/hostname", uri = "file:{{ binary_dir }}/hostname" },
>   # dummy file to check that `libos.passthrough_etc_files` overrides
>   # /etc/hosntame unconditionally
> ```

Done.
___
*[`pal/src/pal_main.c` line 24 at r5](https://reviewable.io/reviews/gramineproject/gramine/850#-NA9vDVg4Dskp64FD5JZ:-NAA3DhK0002s_Y2iIiq:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9dfc0952a02e96523df5cb9db7001ae0ad95273f/pal/src/pal_main.c#L24)):*
> ```C
>     /* Enable log to catch early initialization errors; it will be overwritten in pal_main(). */
>     .log_level = PAL_LOG_DEFAULT_LEVEL,
>     .hostname = "localhost"
> ```

Done.
___
*[`pal/src/host/linux/pal_main.c` line 135 at r5](https://reviewable.io/reviews/gramineproject/gramine/850#-NA9xC-93Urzn4DmTNiC:-NAA3GXq2_6sWr-sxLFK:b9md5s9) ([raw file](https://github.com/gramineproject/gramine/blob/9dfc0952a02e96523df5cb9db7001ae0ad95273f/pal/src/host/linux/pal_main.c#L135)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why not move this to the top of this function?
</blockquote></details>

Because @dimakuv asked me to not propagate the `libos.passthrough_etc_files` to the child through checkpoint mechanisms, and get it from manifest file. I think that this value should be synced between the process.
___
*[`pal/src/host/linux/pal_main.c` line 147 at r5](https://reviewable.io/reviews/gramineproject/gramine/850#-NA9vdgr1c8WkYnLxhrU:-NAA3gnV02zVMnqAREFC:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9dfc0952a02e96523df5cb9db7001ae0ad95273f/pal/src/host/linux/pal_main.c#L147)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

please fix alignment
</blockquote></details>

Done.
___
*[`pal/include/host/linux-common/etc_host_info.h` line 10 at r5](https://reviewable.io/reviews/gramineproject/gramine/850#-NA9uvjY8yjoxMTZdniu:-NAA38zQ5yZL4UOYTewg:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9dfc0952a02e96523df5cb9db7001ae0ad95273f/pal/include/host/linux-common/etc_host_info.h#L10)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd skip this comment, it's literally what the function name already says ;)
</blockquote></details>

Done.
___
*[`pal/src/host/linux-common/etc_host_info.c` line 13 at r5](https://reviewable.io/reviews/gramineproject/gramine/850#-NA9xvq_-66SSDCEVhMJ:-NAA4gXF4_ND3ejZBbir:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9dfc0952a02e96523df5cb9db7001ae0ad95273f/pal/src/host/linux-common/etc_host_info.c#L13)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

this should be in the first, separate include group
</blockquote></details>

Done.
___
*[`pal/src/host/linux-common/etc_host_info.c` line 19 at r5](https://reviewable.io/reviews/gramineproject/gramine/850#-NA9yFDvCpJxuqoOtOld:-NAA4gtL1mANAk1iPFoj:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9dfc0952a02e96523df5cb9db7001ae0ad95273f/pal/src/host/linux-common/etc_host_info.c#L19)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd drop this, there's no point in this check
</blockquote></details>

Done.
___
*[`pal/src/host/linux-common/etc_host_info.c` line 20 at r5](https://reviewable.io/reviews/gramineproject/gramine/850#-NA9yAtpAIFniagOe8Sx:-NAA4HjSE5h7J0T96IxY:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9dfc0952a02e96523df5cb9db7001ae0ad95273f/pal/src/host/linux-common/etc_host_info.c#L20)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please move this to right befor [...]

2022-08-23 17:32 UTC, oshogbo reviewed
The failed tests dsoen't seem to be related to recent changes:
```
test_ltp.py:196: in test_ltp
    returncode, stdout, _stderr = run_command(full_cmd, timeout=timeout, can_fail=True)
../../../usr/lib/python3.6/site-packages/graminelibos/regression.py:148: in run_command
    raise AssertionError('Command {} timed out after {} s'.format(cmd, timeout))
E   AssertionError: Command ['gramine-direct', 'fdatasync01'] timed out after 30 s
```

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/850#-:-NAAkZzKDZ_wJkH3wAVh:b-2w19xc)* status: 23 of 30 files reviewed, 21 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @oshogbo)



<!-- Sent from Reviewable.io -->

2022-08-23 20:56 UTC, boryspoplawski requested changes
> Reviewed 4 of 30 files at r1, 5 of 18 files at r2, 1 of 7 files at r3, 3 of 4 files at r5, 4 of 7 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/850)* status: 27 of 30 files reviewed, 41 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/850#-NAAkLsfAAwA7AwAWlT9:-NAAkLsfAAwA7AwAWlTA:b-ltppuh) (no related file):*
Why this whole PR talks about `passthrough`, where in fact we just expose some well defined structs on PAL level and emulate `/etc` completely in LibOS?

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/850#-NAAlkenEocN-JWr3JMN:-NAAlkenEocN-JWr3JMO:bftsov5) (no related file):*
Actually why do we even emulate `/etc/hostname`? What uses it? From what I understand this is just a configuration file for early init scripts on a system, not runtime network configuration (like `/etc/resolv.conf`)

___
___
*[`-- commits` line 27 at r4](https://reviewable.io/reviews/gramineproject/gramine/850#-NA4NEvx1bxAZTeK_X_y):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd rephrase this whole section when rebasing, all these super short sentences read weirdly to me.
</blockquote></details>

+1
___
*[`-- commits` line 20 at r6](https://reviewable.io/reviews/gramineproject/gramine/850#-NAAhs8l-kajqEx4BwyY):*




_Suggestion:_
```
"/etc"
```
___
*[`Documentation/manifest-syntax.rst` line 147 at r4](https://reviewable.io/reviews/gramineproject/gramine/850#-NA4P28VD_THuKHVBpLg:-NAAiObw6VGOIhep6W3c:b-qkjq2v) ([raw file](https://github.com/gramineproject/gramine/blob/971d215eda6fe59256bbeac9ed2f0ee38f11adc7/Documentation/manifest-syntax.rst#L147)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Just a note: this will need to be rephrased after we start supporting non-Linux hosts (it'll be generated there based on host configs).
</blockquote></details>

Why don't we  name it accordingly from the beginning? Like this is not a passthrough, it's just an emulated "pseudo file" (which is a bit different from Linux `/etc/hostname` which is just a simple file).
___
*[`libos/src/libos_init.c` line 428 at r6](https://reviewable.io/reviews/gramineproject/gramine/850#-NABPk-H8Ga76DWsf86N:-NABPk-H8Ga76DWsf86O:b-r34817) ([raw file](https://github.com/gramineproject/gramine/blob/3c3c3006c4bb50c082dd3e4c2e40a5c0dcb82432/libos/src/libos_init.c#L428)):*
> ```C
>     RUN_INIT(init_std_handles);
>     /* The init_mount_etcfs takes precedence over user's fs.mounts, and because of that,
>      * it has to be called after init_mount. */
> ```

Why it's not called inside `init_mount()`? Now you mount over /etc/hostname in child even though it's already mounted (mounts are checkpointed), this stacks with each child...
Please rename this to `mount_etcfs()` and call in `init_mount()` (at the end probably) 
___
*[`libos/src/libos_init.c` line 493 at r6](https://reviewable.io/reviews/gramineproject/gramine/850#-NABTHGY6kPmOpj_3tnM:-NABTHGY6kPmOpj_3tnN:b-ts3bl1) ([raw file](https://github.com/gramineproject/gramine/blob/3c3c3006c4bb50c082dd3e4c2e40a5c0dcb82432/libos/src/libos_init.c#L493)):*
> ```C
>     RUN_INIT(init_sync_client);
> 
>     RUN_INIT(set_hostname, g_pal_public_state->hostname,
> ```

I don't like this - we should be keeping the list of global init functions as small as possible, it's already PITA to work with this code.
Unfortunately I don't know a good place for this initialization...
___
*[`libos/src/libos_init.c` line 493 at r6](https://reviewable.io/reviews/gramineproject/gramine/850#-NABT_7_94bRRWlnujhY:-NABT_7_94bRRWlnujhZ:b-7fq4zo) ([raw file](https://github.com/gramineproject/gramine/blob/3c3c3006c4bb50c082dd3e4c2e40a5c0dcb82432/libos/src/libos_init.c#L493)):*
> ```C
>     RUN_INIT(init_sync_client);
> 
>     RUN_INIT(set_hostname, g_pal_public_state->hostname,
> ```

Shouldn't this be done only in the first process?
___
*[`libos/src/libos_init.c` line 494 at r6](https://reviewable.io/reviews/gramineproject/gramine/850#-NABRXtF8ZpZedytPKlS:-NABRXtF8ZpZedytPKlT:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/3c3c3006c4bb50c082dd3e4c2e40a5c0dcb82432/libos/src/libos_init.c#L494)):*
> ```C
> 
>     RUN_INIT(set_hostname, g_pal_public_state->hostname,
>              strlen(g_pal_public_state->hostname) + 1);
> ```





_Suggestion:_
```C
 )
```
___
*[`libos/src/fs/etc/fs.c` line 8 at r6](https://reviewable.io/reviews/gramineproject/gramine/850#-NAB9StB9SkXJ1v9dE9n:-NAB9StB9SkXJ1v9dE9o:b-10f5sc) ([raw file](https://github.com/gramineproject/gramine/blob/3c3c3006c4bb50c082dd3e4c2e40a5c0dcb82432/libos/src/fs/etc/fs.c#L8)):*
> ```C
> /*
>  * This file contains the implementation of `etc` FS.
>  * LibOS assumes that contents of all etc files were already sanitized.
> ```

Why do we even have a notion of `etc files` here. We get info from PAL in the for of our choice, it has nothing to do with Linux `/etc` files.
___
*[`libos/src/fs/etc/fs.c` line 18 at r6](https://reviewable.io/reviews/gramineproject/gramine/850#-NABSQSw4Uv-aLe6zj9K:-NABSQSxCHmAMMc_5pOI:beuk2k) ([raw file](https://github.com/gramineproject/gramine/blob/3c3c3006c4bb50c082dd3e4c2e40a5c0dcb82432/libos/src/fs/etc/fs.c#L18)):*
> ```C
>     __UNUSED(dent);
>     /* Use the string (without null terminator) as file data */
>     size_t size = strlen(g_pal_public_state->hostname);
> ```

Why we read this not `g_current_uname->nodeinfo`?
___
*[`libos/src/fs/etc/fs.c` line 28 at r6](https://reviewable.io/reviews/gramineproject/gramine/850#-NABB9XWC6y7GDgfsgPb:-NABB9XWC6y7GDgfsgPc:b-f9i5dv) ([raw file](https://github.com/gramineproject/gramine/blob/3c3c3006c4bb50c082dd3e4c2e40a5c0dcb82432/libos/src/fs/etc/fs.c#L28)):*
> ```C
> }
> 
> int init_etcfs(void) {
> ```

Why this is a separate step from `init_mount_etcfs()`?
___
*[`libos/src/fs/etc/fs.c` line 29 at r6](https://reviewable.io/reviews/gramineproject/gramine/850#-NABFhmDBBnX6wyWjm48:-NABFhmDBBnX6wyWjm49:bdopdhz) ([raw file](https://github.com/gramineproject/gramine/blob/3c3c3006c4bb50c082dd3e4c2e40a5c0dcb82432/libos/src/fs/etc/fs.c#L29)):*
> ```C
> 
> int init_etcfs(void) {
>     pseudo_add_str(NULL, "etc-passthrough-hostname", &provide_etc_hostname);
> ```

Ok, I've read the other discussion, so now I know how this works, but is it really the intended way of mounting single pseudo files? Looks like an abuse to me (especially since the list is called `g_pseudo_roots`)... But it all seems to be working correctly.
(Not blocking, this is not really related to this PR).
___
*[`libos/src/fs/etc/fs.c` line 39 at r6](https://reviewable.io/reviews/gramineproject/gramine/850#-NABKdLa22kJg3zHCWmS:-NABKdLbBCiydZfmxDpT:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/3c3c3006c4bb50c082dd3e4c2e40a5c0dcb82432/libos/src/fs/etc/fs.c#L39)):*
> ```C
>         return 0;
> 
>     ret = mount_fs(&(struct libos_mount_params){
> ```





_Suggestion:_
```C
return mount_fs
```
___
*[`libos/src/fs/etc/fs.c` line 56 at r6](https://reviewable.io/reviews/gramineproject/gramine/850#-NABAudy9ZVFWA3BJH_m:-NABAiAE0mAv_Gl11iL1:baki0qh) ([raw file](https://github.com/gramineproject/gramine/blob/3c3c3006c4bb50c082dd3e4c2e40a5c0dcb82432/libos/src/fs/etc/fs.c#L56)):*
> ```C
> 
>     /* Propagate hostname */
>     size_t off = ADD_CP_OFFSET(sizeof(g_pal_public_state->hostname));
> ```

Why do you use `sizeof()` here and `strlen` in all other places?

Update: ok, I think I know - not to send the actual size in checkpoint.
___
*[`libos/src/fs/etc/fs.c` line 69 at r6](https://reviewable.io/reviews/gramineproject/gramine/850#-NABSW6r6aVh2d97lPwd:-NABSW6sDOKr-h6Z1_bK:b9y23x1) ([raw file](https://github.com/gramineproject/gramine/blob/3c3 [...]

2022-08-24 07:29 UTC, dimakuv approved these changes
The LTP failure looks unrelated indeed. Ignore it. We've seen it before.

> Reviewed 7 of 7 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/850#-:-NADhiLd6tMolgxq45hV:b-5qtzm9)* status: all files reviewed, 39 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/850#-NAAkLsfAAwA7AwAWlT9:-NADhoBbESkHrMRTZ-UX:b-eom4p8) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why this whole PR talks about `passthrough`, where in fact we just expose some well defined structs on PAL level and emulate `/etc` completely in LibOS?
</blockquote></details>

`passthrough` in the sense of "this file is directly passed from the host (and sanitized) to the app", no matter what is written in the manifest file.

The usage of this keyword conflicts a bit with our typical definition of "this file is directly passed without any sanitization from host to app, if this file is specified in the manifest file".

What would be the better term for this PR? `First iteration of etc sanitization`?

___
___
*[`libos/src/fs/etc/fs.c` line 29 at r6](https://reviewable.io/reviews/gramineproject/gramine/850#-NABFhmDBBnX6wyWjm48:-NADijjZ8J2tIZs8s0m6:b-m91iba) ([raw file](https://github.com/gramineproject/gramine/blob/3c3c3006c4bb50c082dd3e4c2e40a5c0dcb82432/libos/src/fs/etc/fs.c#L29)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Ok, I've read the other discussion, so now I know how this works, but is it really the intended way of mounting single pseudo files? Looks like an abuse to me (especially since the list is called `g_pseudo_roots`)... But it all seems to be working correctly.
(Not blocking, this is not really related to this PR).
</blockquote></details>

Indeed, everyone was confused by this :) Not related to this PR for sure.
___
*[`libos/src/sys/libos_uname.c` line 44 at r1](https://reviewable.io/reviews/gramineproject/gramine/850#-N9kOjBW0KGD3h-rfmSb:-NADix390quzyLkWNOvp:b-nh059o) ([raw file](https://github.com/gramineproject/gramine/blob/859723bdce536e4f3f53b46845b36ed8a72e9011/libos/src/sys/libos_uname.c#L44)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> Why do we need to append the NULL byte?

Because that's what Linux does, although the implementation is a bit obfuscated: https://elixir.bootlin.com/linux/v5.19.3/source/kernel/sys.c#L1355

> it may return a non-NULL-terminated string.

It can't.

</blockquote></details>

OK, got it
___
*[`pal/src/host/linux/pal_main.c` line 424 at r1](https://reviewable.io/reviews/gramineproject/gramine/850#-N9kgSIi4A3WFtDrgunq:-NADjQOg5eh43OKoCEvj:bfse427) ([raw file](https://github.com/gramineproject/gramine/blob/859723bdce536e4f3f53b46845b36ed8a72e9011/pal/src/host/linux/pal_main.c#L424)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

+1, please restore the old version. I don't see a reason for having a function for initializing both together (topo and hostname are quite unrelated). IMO just restore old topo init code and initialize hostname separately. 
</blockquote></details>

I'm fine with @boryspoplawski suggestion to split the code into two, leaving topo-initialization as is and adding hostname-initialization separately.
___
*[`pal/src/host/linux-sgx/pal_ecall_types.h` line 24 at r6](https://reviewable.io/reviews/gramineproject/gramine/850#-NAB8ReW1mDYSo3xujrM:-NADjx8_BfM9wQNalFhG:b9ymxv3) ([raw file](https://github.com/gramineproject/gramine/blob/3c3c3006c4bb50c082dd3e4c2e40a5c0dcb82432/pal/src/host/linux-sgx/pal_ecall_types.h#L24)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I don't like this stashing topo and etc together. This causes some unnecessary changes to topo code, weird splits of sanitization and generally seems unnecessary. Why not handle those two things together? You only save one `sgx_copy_to_enclave` with the current changes, but introduce other, unnecessary complexity.

cc @dimakuv @mkow 
</blockquote></details>

I don't mind either way.

If we decide to split, then we should split into `struct pal_topo_info* ms_topo_info` and `struct pal_etc_info* ms_etc_info`, where `struct pal_etc_info*` will currently contain only one `hostname` field. Later this new struct will be populated with more etc-related fields.


<!-- Sent from Reviewable.io -->

2022-08-24 08:53 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/850)* status: all files reviewed, 39 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @oshogbo)

___
*[`Documentation/manifest-syntax.rst` line 147 at r4](https://reviewable.io/reviews/gramineproject/gramine/850#-NA4P28VD_THuKHVBpLg:-NAE-LCM9Ez-X6SIN76S:b-11b2i9) ([raw file](https://github.com/gramineproject/gramine/blob/971d215eda6fe59256bbeac9ed2f0ee38f11adc7/Documentation/manifest-syntax.rst#L147)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why don't we  name it accordingly from the beginning? Like this is not a passthrough, it's just an emulated "pseudo file" (which is a bit different from Linux `/etc/hostname` which is just a simple file).
</blockquote></details>

@mkow, @dimakuv  What do you think? Do you want to change the name?
___
*[`libos/src/libos_init.c` line 428 at r6](https://reviewable.io/reviews/gramineproject/gramine/850#-NABPk-H8Ga76DWsf86N:-NADw0LtDlLnpWFlIlFK:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/3c3c3006c4bb50c082dd3e4c2e40a5c0dcb82432/libos/src/libos_init.c#L428)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why it's not called inside `init_mount()`? Now you mount over /etc/hostname in child even though it's already mounted (mounts are checkpointed), this stacks with each child...
Please rename this to `mount_etcfs()` and call in `init_mount()` (at the end probably) 
</blockquote></details>

Done.
___
*[`libos/src/libos_init.c` line 493 at r6](https://reviewable.io/reviews/gramineproject/gramine/850#-NABT_7_94bRRWlnujhY:-NADtH6aDUvf10OooCk-:b-rqfz7t) ([raw file](https://github.com/gramineproject/gramine/blob/3c3c3006c4bb50c082dd3e4c2e40a5c0dcb82432/libos/src/libos_init.c#L493)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Shouldn't this be done only in the first process?
</blockquote></details>

No, this also is called after the checkpoint is received, because of that we don't have to call this in checkpoint/restore function.
___
*[`libos/src/fs/etc/fs.c` line 8 at r6](https://reviewable.io/reviews/gramineproject/gramine/850#-NAB9StB9SkXJ1v9dE9n:-NADzxcw0-2VTfPBaJft:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/3c3c3006c4bb50c082dd3e4c2e40a5c0dcb82432/libos/src/fs/etc/fs.c#L8)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why do we even have a notion of `etc files` here. We get info from PAL in the for of our choice, it has nothing to do with Linux `/etc` files.
</blockquote></details>

Done.
___
*[`libos/src/fs/etc/fs.c` line 18 at r6](https://reviewable.io/reviews/gramineproject/gramine/850#-NABSQSw4Uv-aLe6zj9K:-NADt-_67HYzctn0VTLl:bwwbf1b) ([raw file](https://github.com/gramineproject/gramine/blob/3c3c3006c4bb50c082dd3e4c2e40a5c0dcb82432/libos/src/fs/etc/fs.c#L18)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why we read this not `g_current_uname->nodeinfo`?
</blockquote></details>

Because the status of `/etc/hostname` and status of `uname` are two diffrent things.
If you will call `sethostname` it won't change the value of `/etc/hostname`, but it will change the value of uname.
___
*[`libos/src/fs/etc/fs.c` line 28 at r6](https://reviewable.io/reviews/gramineproject/gramine/850#-NABB9XWC6y7GDgfsgPb:-NADtrmr6yKiCf9K-pEY:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/3c3c3006c4bb50c082dd3e4c2e40a5c0dcb82432/libos/src/fs/etc/fs.c#L28)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why this is a separate step from `init_mount_etcfs()`?
</blockquote></details>

Done.
___
*[`libos/src/fs/etc/fs.c` line 29 at r6](https://reviewable.io/reviews/gramineproject/gramine/850#-NABFhmDBBnX6wyWjm48:-NADtsK5BNxIAFoLBA6z:bctcolq) ([raw file](https://github.com/gramineproject/gramine/blob/3c3c3006c4bb50c082dd3e4c2e40a5c0dcb82432/libos/src/fs/etc/fs.c#L29)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Indeed, everyone was confused by this :) Not related to this PR for sure.
</blockquote></details>

Yes it was confirmed with Pawel.
Done.
___
*[`libos/src/fs/etc/fs.c` line 39 at r6](https://reviewable.io/reviews/gramineproject/gramine/850#-NABKdLa22kJg3zHCWmS:-NADwL7TDisJpRYdbLuw:bfz3b4o) ([raw file](https://github.com/gramineproject/gramine/blob/3c3c3006c4bb50c082dd3e4c2e40a5c0dcb82432/libos/src/fs/etc/fs.c#L39)):*
> ```C
>         return 0;
> 
>     ret = mount_fs(&(struct libos_mount_params){
> ```

There will be more files in these mount with next PRs, so I can change that if you really want but next PR will override this.
___
*[`libos/src/fs/etc/fs.c` line 69 at r6](https://reviewable.io/reviews/gramineproject/gramine/850#-NABSW6r6aVh2d97lPwd:-NADtz8M2doKaVlQOrGq:b4ibhkz) ([raw file](https://github.com/gramineproject/gramine/blob/3c3c3006c4bb50c082dd3e4c2e40a5c0dcb82432/libos/src/fs/etc/fs.c#L69)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Ughh, lets not overwrite `g_pal_public_state`. The fact that topology code does that is IMO a bad precedent, we shouldn't have done it that way...
Also this is not read by `uname`, so it's wrong.
</blockquote></details>

The state of `/etc/hostname` file is not the same as `uname`, so we have to save them separately.
Also the uname reads its later on in the init phase (via set_hostname).
___
*[`libos/src/sys/libos_uname.c` line 43 at r6](https://reviewable.io/reviews/gramineproject/gramine/850#-NABUVx_5i1NAEJSS6Uf:-NADx2gR1ZbCtJQJgQd3:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/3c3c3006c4bb50c082dd3e4c2e40a5c0dcb82432/libos/src/sys/libos_uname.c#L43)):*
> ```C
> }
> 
> int set_hostname(char* name, size_t len) {
> ```

Done.
___
*[`libos/src/sys/libos_uname.c` line 54 at r6](https://reviewable.io/reviews/gramineproject/gramine/850#-NABUL-eALRURU8whW3Y:-NADshBz6tNayOnJ4SVV:bcu1lx0) ([raw file](https://github.com/gramineproject/gramine/blob/3c3c3006c4bb50c082dd3e4c2e40a5c0dcb82432/libos/src/sys/libos_uname.c#L54)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This check is now redundant
</blockquote></details>

It's not, because of the order of checks.
If we will check this later we might return the -EFAULT error first which is not what LTP test expects us.
___
*[`pal/src/host/linux/pal_main.c` line 424 at r1](https://reviewable.io/reviews/gramineproject/gramine/850#-N9kgSIi4A3WFtDrgunq:-NADxVx213KshKBWBP_J:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/859723bdce536e4f3f53b46845b36ed8a72e9011/pal/src/host/linux/pal_main.c#L424)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I'm fine with @boryspoplawski suggestion to split the code into two, leaving topo-initialization as is and adding hostname-initialization separately.
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/pal_ecall_types.h` line 22 at r6](https://reviewable.io/reviews/gramineproject/gramine/850#-NAB8I2P5sOQ8SK5lwrz:-NADycel-btfPd37Wh-c:b-dl89ai) ([raw file](https://github.com/gramineproject/gramine/blob/3c3c3006c4bb50c082dd3e4c2e40a5c0dcb82432/pal/src/host/linux-sgx/pal_ecall_types.h#L22)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why this is part of an ecall? We can get that info from a trusted source inside enclave (measured manifest).
</blockquote></details>

I thought, we will just parse this information once, instead  [...]

2022-08-24 14:03 UTC, boryspoplawski requested changes
> Reviewed 8 of 8 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/850)* status: all files reviewed, 33 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/850#-NAAkLsfAAwA7AwAWlT9:-NAEu2ZG0QpU-rbJh3ya:b-h9j8h6) (no related file):*
> passthrough in the sense of "this file is directly passed from the host (and sanitized) to the app", no matter what is written in the manifest file.

But it's not directly passed, it's very indirect. We make a copy of that, possibly changing the format and doing sanitization. 

> What would be the better term for this PR? First iteration of etc sanitization?

I don't care that much about the commit/PR description. My problem is that `passthrough` is used in the code and comments.

___
___
*[`libos/src/libos_init.c` line 493 at r6](https://reviewable.io/reviews/gramineproject/gramine/850#-NABT_7_94bRRWlnujhY:-NAF9OB6CFXHq3Gy2Kqc:b-ylhhvl) ([raw file](https://github.com/gramineproject/gramine/blob/3c3c3006c4bb50c082dd3e4c2e40a5c0dcb82432/libos/src/libos_init.c#L493)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

No, this also is called after the checkpoint is received, because of that we don't have to call this in checkpoint/restore function.
</blockquote></details>

But if we ever add checkpointing of `uname` info, this will break it.
___
*[`libos/src/fs/libos_fs.c` line 660 at r7](https://reviewable.io/reviews/gramineproject/gramine/850#-NAEv6dY4TkdkaiXEKrL:-NAEv6dY4TkdkaiXEKrM:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/c2491bf1a408bcac56f92501f10f02a1307ac139/libos/src/fs/libos_fs.c#L660)):*
> ```C
>     mount_etcfs();
> 
>     return 0;
> ```





_Suggestion:_
```C
    return mount_etcfs();
```
___
*[`libos/src/fs/etc/fs.c` line 28 at r6](https://reviewable.io/reviews/gramineproject/gramine/850#-NABB9XWC6y7GDgfsgPb:-NAEvjTWDgL6dmfYK1vU:b3kre) ([raw file](https://github.com/gramineproject/gramine/blob/3c3c3006c4bb50c082dd3e4c2e40a5c0dcb82432/libos/src/fs/etc/fs.c#L28)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

?
___
*[`libos/src/fs/etc/fs.c` line 39 at r6](https://reviewable.io/reviews/gramineproject/gramine/850#-NABKdLa22kJg3zHCWmS:-NAEvvYaDckShmLB-qXC:baxxu3a) ([raw file](https://github.com/gramineproject/gramine/blob/3c3c3006c4bb50c082dd3e4c2e40a5c0dcb82432/libos/src/fs/etc/fs.c#L39)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

There will be more files in these mount with next PRs, so I can change that if you really want but next PR will override this.
</blockquote></details>

Yes, let other PRs change that if they need it. It doesn't make sense as is here.
___
*[`libos/src/fs/etc/fs.c` line 69 at r6](https://reviewable.io/reviews/gramineproject/gramine/850#-NABSW6r6aVh2d97lPwd:-NAEzRe60BWAL0-oIelu:bo4dg5e) ([raw file](https://github.com/gramineproject/gramine/blob/3c3c3006c4bb50c082dd3e4c2e40a5c0dcb82432/libos/src/fs/etc/fs.c#L69)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

The state of `/etc/hostname` file is not the same as `uname`, so we have to save them separately.
Also the uname reads its later on in the init phase (via set_hostname).
</blockquote></details>

Ok, still, I don't like adding another place writing over `g_pal_public_state`, which was supposed to be constant and read-only.
___
*[`libos/src/sys/libos_uname.c` line 54 at r6](https://reviewable.io/reviews/gramineproject/gramine/850#-NABUL-eALRURU8whW3Y:-NAEzo9q6ZMgYn83JOb2:bxbtgws) ([raw file](https://github.com/gramineproject/gramine/blob/3c3c3006c4bb50c082dd3e4c2e40a5c0dcb82432/libos/src/sys/libos_uname.c#L54)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

It's not, because of the order of checks.
If we will check this later we might return the -EFAULT error first which is not what LTP test expects us.
</blockquote></details>

We do not care about such useless LTP tests, but whatever.
___
*[`pal/src/host/linux/pal_main.c` line 147 at r5](https://reviewable.io/reviews/gramineproject/gramine/850#-NA9vdgr1c8WkYnLxhrU:-NAF-keE5nsJYI83Sohm:b-lkpp83) ([raw file](https://github.com/gramineproject/gramine/blob/9dfc0952a02e96523df5cb9db7001ae0ad95273f/pal/src/host/linux/pal_main.c#L147)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

This fits into one line
___
*[`pal/src/host/linux/pal_main.c` line 124 at r7](https://reviewable.io/reviews/gramineproject/gramine/850#-NAF0Zq54DsFhPiOEYOb:-NAF0Zq54DsFhPiOEYOc:b8vk4xp) ([raw file](https://github.com/gramineproject/gramine/blob/c2491bf1a408bcac56f92501f10f02a1307ac139/pal/src/host/linux/pal_main.c#L124)):*
> ```C
> }
> 
> static void get_host_info(bool first_process) {
> ```

This is a very ambiguous name...



_Code quote:_
```C
get_host_info
```
___
*[`pal/src/host/linux/pal_main.c` line 128 at r7](https://reviewable.io/reviews/gramineproject/gramine/850#-NAF0AMq973LNrox7HDP:-NAF0AMq973LNrox7HDQ:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/c2491bf1a408bcac56f92501f10f02a1307ac139/pal/src/host/linux/pal_main.c#L128)):*
> ```C
> 
>     ret = toml_bool_in(g_pal_public_state.manifest_root, "libos.passthrough_etc_files",
>                        false, &g_pal_public_state.passthrough_etc_files);
> ```





_Suggestion:_
```C
    int ret = toml_bool_in(g_pal_public_state.manifest_root, "libos.passthrough_etc_files", false,
                           &g_pal_public_state.passthrough_etc_files);
```
___
*[`pal/src/host/linux/pal_main.c` line 431 at r7](https://reviewable.io/reviews/gramineproject/gramine/850#-NAF-WIh56Kzi_fzVfx0:-NAF-WIh56Kzi_fzVfx1:be0klh2) ([raw file](https://github.com/gramineproject/gramine/blob/c2491bf1a408bcac56f92501f10f02a1307ac139/pal/src/host/linux/pal_main.c#L431)):*
> ```C
>     }
> 
>     get_host_info(first_process);
> ```

Why not



_Suggestion:_
```C
if (first_process)
    get_host_info();
```
___
*[`pal/src/host/linux-sgx/pal_ecall_types.h` line 22 at r6](https://reviewable.io/reviews/gramineproject/gramine/850#-NAB8I2P5sOQ8SK5lwrz:-NAF41P38gb0J_ZcDIZy:b-376p64) ([raw file](https://github.com/gramineproject/gramine/blob/3c3c3006c4bb50c082dd3e4c2e40a5c0dcb82432/pal/src/host/linux-sgx/pal_ecall_types.h#L22)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

I thought, we will just parse this information once, instead of doing this multiple time.
</blockquote></details>

But then you need to sanitize it and you need to make sure it's the same in child as it is in parent. Pointless.
(also the whole manifest is parsed anyway, so we save on one look up time, rather than parsing)
___
*[`pal/src/host/linux-sgx/pal_ecall_types.h` line 24 at r6](https://reviewable.io/reviews/gramineproject/gramine/850#-NAB8ReW1mDYSo3xujrM:-NAF5b3Q6EuQ9nEY5FZy:b-ba7v2z) ([raw file](https://github.com/gramineproject/gramine/blob/3c3c3006c4bb50c082dd3e4c2e40a5c0dcb82432/pal/src/host/linux-sgx/pal_ecall_types.h#L24)):*
> I just assumed that this is a logical group, as topo is also a "host_information" 

But they are/might be quite different (topo vs etc) w.r.t. layout, copying and sanitization, especially when etc gets extended.

> and I didn't want to grow the number of parameters in ecall.

In ecall it's wrapped in a struct anyway. You just added a nesting level instead of another argument, overall number of parameters increased anyway.
___
*[`pal/src/host/linux-common/etc_host_info.c` line 13 at r5](https://reviewable.io/reviews/gra [...]

2022-08-25 07:23 UTC, dimakuv approved these changes
> Reviewed 6 of 8 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/850)* status: all files reviewed, 33 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/850#-NAAkLsfAAwA7AwAWlT9:-NAIq6NoBtXAJuIa0CpE:bmbvjj) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

> passthrough in the sense of "this file is directly passed from the host (and sanitized) to the app", no matter what is written in the manifest file.

But it's not directly passed, it's very indirect. We make a copy of that, possibly changing the format and doing sanitization. 

> What would be the better term for this PR? First iteration of etc sanitization?

I don't care that much about the commit/PR description. My problem is that `passthrough` is used in the code and comments.
</blockquote></details>

So about `passthrough` -> `sanitization`?

___
___
*[`Documentation/manifest-syntax.rst` line 147 at r4](https://reviewable.io/reviews/gramineproject/gramine/850#-NA4P28VD_THuKHVBpLg:-NAIqHVq8arbywvaZ8kn:b-idykzf) ([raw file](https://github.com/gramineproject/gramine/blob/971d215eda6fe59256bbeac9ed2f0ee38f11adc7/Documentation/manifest-syntax.rst#L147)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

@mkow, @dimakuv  What do you think? Do you want to change the name?
</blockquote></details>

Yeah, I'm fine with changing the name. But I still don't know what is suggested instead. I would be ok with `libos.sanitize_etc_files` or `libos.expose_etc_files`.
___
*[`libos/src/libos_init.c` line 493 at r6](https://reviewable.io/reviews/gramineproject/gramine/850#-NABT_7_94bRRWlnujhY:-NAIqbeI3x-mj-C759O_:bto3cax) ([raw file](https://github.com/gramineproject/gramine/blob/3c3c3006c4bb50c082dd3e4c2e40a5c0dcb82432/libos/src/libos_init.c#L493)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

But if we ever add checkpointing of `uname` info, this will break it.
</blockquote></details>

Maybe just put a comment explaining this, and add checkpointing of `uname` in a follow up PR?
___
*[`libos/src/fs/etc/fs.c` line 69 at r6](https://reviewable.io/reviews/gramineproject/gramine/850#-NABSW6r6aVh2d97lPwd:-NAIrJ235Mnxl6yJrRRA:b8hylfu) ([raw file](https://github.com/gramineproject/gramine/blob/3c3c3006c4bb50c082dd3e4c2e40a5c0dcb82432/libos/src/fs/etc/fs.c#L69)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Ok, still, I don't like adding another place writing over `g_pal_public_state`, which was supposed to be constant and read-only.
</blockquote></details>

@boryspoplawski What do you suggest? To have a copy of `g_pal_public_state->hostname` in the LibOS, and initialize this copy in the first process and then checkpoint-restore this copy (instead of overwriting `g_pal_public_state->hostname`)? And use this copy everywhere where we currently use `g_pal_public_state->hostname` as the source of hostname?

I'd be fine with this approach.
___
*[`pal/src/host/linux-common/etc_host_info.c` line 13 at r5](https://reviewable.io/reviews/gramineproject/gramine/850#-NA9xvq_-66SSDCEVhMJ:-NAIsFyV2TWa-gu7EtzV:bhrlgjt) ([raw file](https://github.com/gramineproject/gramine/blob/9dfc0952a02e96523df5cb9db7001ae0ad95273f/pal/src/host/linux-common/etc_host_info.c#L13)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

> Matching .h header for .c files.

Huh, I wasn't aware of this rule.

TBH it makes no sense to me, at least in most cases, in some it might, but minority. I would remove it. This is unrelated to this PR, but I think it will still take some time to merge, so we can discuss it while we are here.
@dimakuv @mkow 

Why I'm saying it doesn't make sense to me is cases like: https://github.com/gramineproject/gramine/blob/master/libos/src/bookkeep/libos_vma.c#L25 which I believe is the majority of cases. I don't think moving this header on top of that file is better than what we have now.
</blockquote></details>

I also wasn't aware of this rule :)

I don't think we follow this rule closely. I would remove it as well.


<!-- Sent from Reviewable.io -->

2022-08-25 11:28 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/850)* status: all files reviewed, 33 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/850#-NAAkLsfAAwA7AwAWlT9:-NAJiEtaCk4FVinrHiEC:b26smcn) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

So about `passthrough` -> `sanitization`?
</blockquote></details>

Rather `emulation`. We do not pass&sanitize a file, we gather info in the PAL (it doesn't have to read `/etc` and definitely could on e.g. Windows) and use that info to emulate `/etc/*` files in LibOS.

___
___
*[`Documentation/manifest-syntax.rst` line 147 at r4](https://reviewable.io/reviews/gramineproject/gramine/850#-NA4P28VD_THuKHVBpLg:-NAJivwFDBwU8xcoEw30:b-oqqj2p) ([raw file](https://github.com/gramineproject/gramine/blob/971d215eda6fe59256bbeac9ed2f0ee38f11adc7/Documentation/manifest-syntax.rst#L147)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yeah, I'm fine with changing the name. But I still don't know what is suggested instead. I would be ok with `libos.sanitize_etc_files` or `libos.expose_etc_files`.
</blockquote></details>

Both are not what we actually do. `emulate_etc_files` maybe? Though something better is preferred :)
___
*[`libos/src/libos_init.c` line 493 at r6](https://reviewable.io/reviews/gramineproject/gramine/850#-NABT_7_94bRRWlnujhY:-NAJjSi80qMXjkc_D6vV:b32wtd) ([raw file](https://github.com/gramineproject/gramine/blob/3c3c3006c4bb50c082dd3e4c2e40a5c0dcb82432/libos/src/libos_init.c#L493)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Maybe just put a comment explaining this, and add checkpointing of `uname` in a follow up PR?
</blockquote></details>

ok
___
*[`libos/src/fs/etc/fs.c` line 69 at r6](https://reviewable.io/reviews/gramineproject/gramine/850#-NABSW6r6aVh2d97lPwd:-NAJjkWD1FqHg70GR-iZ:b-yw4e2p) ([raw file](https://github.com/gramineproject/gramine/blob/3c3c3006c4bb50c082dd3e4c2e40a5c0dcb82432/libos/src/fs/etc/fs.c#L69)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@boryspoplawski What do you suggest? To have a copy of `g_pal_public_state->hostname` in the LibOS, and initialize this copy in the first process and then checkpoint-restore this copy (instead of overwriting `g_pal_public_state->hostname`)? And use this copy everywhere where we currently use `g_pal_public_state->hostname` as the source of hostname?

I'd be fine with this approach.
</blockquote></details>

Ok, I guess we can leave it as it is, because it will be trivial to fix if we ever want to.

But we should discuss what we do with this problem in general - information that comes from the host (possibly untrusted) and is used by LibOS + checkpointed by LibOS (so it is the same in the child process). Currently we stash it ingo `g_pal_public_state` and LibOS overwrites it.


<!-- Sent from Reviewable.io -->

2022-08-26 08:19 UTC, dimakuv requested changes
> Reviewed 2 of 8 files at r7.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/850)* status: all files reviewed, 33 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/850#-NAAkLsfAAwA7AwAWlT9:-NAOC_-e5J3EZwIiAl4M:bl18wka) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Rather `emulation`. We do not pass&sanitize a file, we gather info in the PAL (it doesn't have to read `/etc` and definitely could on e.g. Windows) and use that info to emulate `/etc/*` files in LibOS.
</blockquote></details>

+1 to `emulation`

___
___
*[`Documentation/manifest-syntax.rst` line 147 at r4](https://reviewable.io/reviews/gramineproject/gramine/850#-NA4P28VD_THuKHVBpLg:-NAOCehV-ZtXBQsSLjy6:b-mr7tj) ([raw file](https://github.com/gramineproject/gramine/blob/971d215eda6fe59256bbeac9ed2f0ee38f11adc7/Documentation/manifest-syntax.rst#L147)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Both are not what we actually do. `emulate_etc_files` maybe? Though something better is preferred :)
</blockquote></details>

I'm fine with emulate
___
*[`libos/src/fs/etc/fs.c` line 69 at r6](https://reviewable.io/reviews/gramineproject/gramine/850#-NABSW6r6aVh2d97lPwd:-NAOCx5_-kzpcxPLdRKB:b61kkoj) ([raw file](https://github.com/gramineproject/gramine/blob/3c3c3006c4bb50c082dd3e4c2e40a5c0dcb82432/libos/src/fs/etc/fs.c#L69)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Ok, I guess we can leave it as it is, because it will be trivial to fix if we ever want to.

But we should discuss what we do with this problem in general - information that comes from the host (possibly untrusted) and is used by LibOS + checkpointed by LibOS (so it is the same in the child process). Currently we stash it ingo `g_pal_public_state` and LibOS overwrites it.
</blockquote></details>

Probably split into two objects? `g_pal_public_state` (guaranteed to be constant) and `g_pal_public_initial_state` (only used by the parent and copied into LibOS object, which is later checkpointed).


<!-- Sent from Reviewable.io -->

2022-08-26 17:56 UTC, mkow requested changes
> Reviewed 5 of 30 files at r1, 1 of 18 files at r2, 1 of 7 files at r3, 7 of 7 files at r6, 8 of 8 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/850)* status: all files reviewed, 28 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/850#-NAAkLsfAAwA7AwAWlT9:-NAPhmaWAvQxMZaquZXN:b6w1e1y) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

+1 to `emulation`
</blockquote></details>

I didn't complain about this naming because IMO both `passthrough` and `emulation` are not really correct here, it's something in between. The contents are passed through, but the file/data format is emulated. So, I'm fine with both names.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/850#-NAAlkenEocN-JWr3JMN:-NAPiJsx4v0wtVYhyXmA:bq9ju12) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Actually why do we even emulate `/etc/hostname`? What uses it? From what I understand this is just a configuration file for early init scripts on a system, not runtime network configuration (like `/etc/resolv.conf`)
</blockquote></details>

I'm not sure either, but AFAIR the idea of @oshogbo approach was to first implement a simpler file and get the review feedback, and then `resolv.conf`.
@dimakuv is the reporter of https://github.com/gramineproject/gramine/issues/689, so let's wait for his opinion on this.

___
___
*[`Documentation/manifest-syntax.rst` line 147 at r4](https://reviewable.io/reviews/gramineproject/gramine/850#-NA4P28VD_THuKHVBpLg:-NAPis0GBsa9A4F3YeAR:b-o964xf) ([raw file](https://github.com/gramineproject/gramine/blob/971d215eda6fe59256bbeac9ed2f0ee38f11adc7/Documentation/manifest-syntax.rst#L147)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I'm fine with emulate
</blockquote></details>

I'm fine with `emulate_etc_files` (although see my comment in a similar discussion above).
___
*[`libos/src/fs/etc/fs.c` line 69 at r6](https://reviewable.io/reviews/gramineproject/gramine/850#-NABSW6r6aVh2d97lPwd:-NAPlilx8-GAiDcQ-hmX:b-wzdtmz) ([raw file](https://github.com/gramineproject/gramine/blob/3c3c3006c4bb50c082dd3e4c2e40a5c0dcb82432/libos/src/fs/etc/fs.c#L69)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Probably split into two objects? `g_pal_public_state` (guaranteed to be constant) and `g_pal_public_initial_state` (only used by the parent and copied into LibOS object, which is later checkpointed).
</blockquote></details>

Dima's proposal sounds good, although this should be separate from this PR (and probably low-prio?).
___
*[`libos/test/regression/hostname.c` line 68 at r5](https://reviewable.io/reviews/gramineproject/gramine/850#-NA9qWKpCvbRVJfEat3i:-NAAQGucAT1-7VW20Q5G:b-852in4) ([raw file](https://github.com/gramineproject/gramine/blob/9dfc0952a02e96523df5cb9db7001ae0ad95273f/libos/test/regression/hostname.c#L68)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Hmm, I see that other tests have their own copies of such code wrapped into `read_all()`. Could you try moving it to a `common.c` or something and deduplicate?
___
*[`pal/src/host/linux/pal_main.c` line 135 at r5](https://reviewable.io/reviews/gramineproject/gramine/850#-NA9xC-93Urzn4DmTNiC:-NAAQhL5CDuV2CG-g4Bp:br82sln) ([raw file](https://github.com/gramineproject/gramine/blob/9dfc0952a02e96523df5cb9db7001ae0ad95273f/pal/src/host/linux/pal_main.c#L135)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Because @dimakuv asked me to not propagate the `libos.passthrough_etc_files` to the child through checkpoint mechanisms, and get it from manifest file. I think that this value should be synced between the process.
</blockquote></details>

Ah, ok, makes sense.
___
*[`pal/src/host/linux/pal_main.c` line 124 at r7](https://reviewable.io/reviews/gramineproject/gramine/850#-NAF0Zq54DsFhPiOEYOb:-NAPoHmMBfWjzWzCOpAO:b-5yhtnz) ([raw file](https://github.com/gramineproject/gramine/blob/c2491bf1a408bcac56f92501f10f02a1307ac139/pal/src/host/linux/pal_main.c#L124)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This is a very ambiguous name...
</blockquote></details>

I think if we keep the corresponding `pal_host_info` struct then it makes sense. Any suggestion for something better?
___
*[`pal/src/host/linux/pal_main.c` line 431 at r7](https://reviewable.io/reviews/gramineproject/gramine/850#-NAF-WIh56Kzi_fzVfx0:-NAPq2uaE_6qVGct6fFC:b32v57) ([raw file](https://github.com/gramineproject/gramine/blob/c2491bf1a408bcac56f92501f10f02a1307ac139/pal/src/host/linux/pal_main.c#L431)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why not
</blockquote></details>

+1
___
*[`pal/src/host/linux-sgx/host_main.c` line 908 at r7](https://reviewable.io/reviews/gramineproject/gramine/850#-NAPsymPDgNYi_35EoBc:-NAPsymPDgNYi_35EoBd:bfqqisv) ([raw file](https://github.com/gramineproject/gramine/blob/c2491bf1a408bcac56f92501f10f02a1307ac139/pal/src/host/linux-sgx/host_main.c#L908)):*
> ```C
> }
> 
> static int get_host_info(pal_host_info_t* host_info, int parent_stream_fd) {
> ```

ditto - I like Borys' suggestion to move that `if` outside



_Code quote:_
```C
int parent_stream_fd
```
___
*[`pal/src/host/linux-sgx/pal_ecall_types.h` line 22 at r6](https://reviewable.io/reviews/gramineproject/gramine/850#-NAB8I2P5sOQ8SK5lwrz:-NAPtzBEDo7Bu1bBH6uu:b-3nga1z) ([raw file](https://github.com/gramineproject/gramine/blob/3c3c3006c4bb50c082dd3e4c2e40a5c0dcb82432/pal/src/host/linux-sgx/pal_ecall_types.h#L22)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

But then you need to sanitize it and you need to make sure it's the same in child as it is in parent. Pointless.
(also the whole manifest is parsed anyway, so we save on one look up time, rather than parsing)
</blockquote></details>

Good point, this should be taken from trusted source, because it's possible to do so.
___
*[`pal/src/host/linux-sgx/pal_ecall_types.h` line 24 at r6](https://reviewable.io/reviews/gramineproject/gramine/850#-NAB8ReW1mDYSo3xujrM:-NAPuGZa3NRA8_GvXFdX:bahhq75) ([raw file](https://github.com/gramineproject/gramine/blob/3c3c3006c4bb50c082dd3e4c2e40a5c0dcb82432/pal/src/host/linux-sgx/pal_ecall_types.h#L24)):*
> If we decide to split, then we should split into `struct pal_topo_info* ms_topo_info`

What does `ms_` mean and why would we use it there?

> I just assumed that this is a logical group

+1, although we'll probably change it later anyways, when moving this to `g_pal_public_initial_state`?
___
*[`pal/src/host/linux-sgx/pal_ecall_types.h` line 24 at r7](https://reviewable.io/reviews/gramineproject/gramine/850#-NAQ2RvdDNFxBHJntSEV:-NAQ2RvdDNFxBHJntSEW:b-iwc7te) ([raw file](https://github.com/gramineproject/gramine/blob/c2491bf1a408bcac56f92501f10f02a1307ac139/pal/src/host/linux-sgx/pal_ecall_types.h#L24)):*
> ```objc
>     bool                  passthrough_etc;
>     char                  hostname[PAL_HOSTNAME_MAX];
> } pal_host_info_t;
> ```

I think we don't use tagged structures in new code?

CC: @boryspoplawski, @dimakuv



_Code quote:_
```objc
pal_host_info_t
```
___
*[`pal/src/host/linux-sgx/pal_main.c` line 269 at r7](https://reviewable.io/reviews/gramineproject/gramine/850#-NAQG38-4EJpIb1Vhf3m:-NAQG38-4EJpIb1Vhf3n:b-np8818) ([raw file](https://github.com/gramineproject/gramine/blob/c2491bf1a408b [...]

2022-08-26 21:31 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/850)* status: all files reviewed, 28 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/850#-NAAkLsfAAwA7AwAWlT9:-NAR0wuF8UVh4hxs7vDJ:b3ahm1x) (no related file):*
> The contents are passed through

Content of what? It's just on Linux PAL that this is content of some `/etc/` files, other PALs can get this info from somewhere else (different files, syscalls/api calls, whatever). IMO emulation fits - we emulate these files out of some data we get from PAL.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/850#-NAAlkenEocN-JWr3JMN:-NAR1REpEYnu1IvU4YBd:b9rkijp) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'm not sure either, but AFAIR the idea of @oshogbo approach was to first implement a simpler file and get the review feedback, and then `resolv.conf`.
@dimakuv is the reporter of https://github.com/gramineproject/gramine/issues/689, so let's wait for his opinion on this.
</blockquote></details>

Sure, but why this file? I would say we should never have this file emulated at all.

___
___
*[`libos/src/fs/etc/fs.c` line 69 at r6](https://reviewable.io/reviews/gramineproject/gramine/850#-NABSW6r6aVh2d97lPwd:-NAR1ibN4lald8THzpj-:b-ilfi39) ([raw file](https://github.com/gramineproject/gramine/blob/3c3c3006c4bb50c082dd3e4c2e40a5c0dcb82432/libos/src/fs/etc/fs.c#L69)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Dima's proposal sounds good, although this should be separate from this PR (and probably low-prio?).
</blockquote></details>

Yes, definitely not in this PR.
___
*[`pal/src/host/linux/pal_main.c` line 124 at r7](https://reviewable.io/reviews/gramineproject/gramine/850#-NAF0Zq54DsFhPiOEYOb:-NAR1xv-2-Xp6vF3utJh:bpqlhhu) ([raw file](https://github.com/gramineproject/gramine/blob/c2491bf1a408bcac56f92501f10f02a1307ac139/pal/src/host/linux/pal_main.c#L124)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I think if we keep the corresponding `pal_host_info` struct then it makes sense. Any suggestion for something better?
</blockquote></details>

My point is that host info is a very broad term, whereas here we will probably just get some network related configuration. I don't have a good name in mind, but I feel like we should somehow point this is network related config.
___
*[`pal/src/host/linux-sgx/pal_ecall_types.h` line 24 at r7](https://reviewable.io/reviews/gramineproject/gramine/850#-NAQ2RvdDNFxBHJntSEV:-NAR30DiBUXHimfB-8oi:by0xaa3) ([raw file](https://github.com/gramineproject/gramine/blob/c2491bf1a408bcac56f92501f10f02a1307ac139/pal/src/host/linux-sgx/pal_ecall_types.h#L24)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I think we don't use tagged structures in new code?

CC: @boryspoplawski, @dimakuv
</blockquote></details>

True, we don't, please just use `struct X`.


<!-- Sent from Reviewable.io -->

2022-08-26 22:53 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/850)* status: all files reviewed, 28 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/850#-NAAkLsfAAwA7AwAWlT9:-NARIvFC8sPTvlmclrJj:bqp29vo) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

> The contents are passed through

Content of what? It's just on Linux PAL that this is content of some `/etc/` files, other PALs can get this info from somewhere else (different files, syscalls/api calls, whatever). IMO emulation fits - we emulate these files out of some data we get from PAL.
</blockquote></details>

By "contents" I meant the values we get from the host, e.g. in next PRs we'll add the list of predefined DNS translations (`/etc/hosts` on Linux, `system32/something_I_forgot/hosts` on Windows, etc., doesn't matter) - we don't really emulate these contents, we don't even really process them - only ensure that they look ok-ish and encode them into Linux etc files format.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/850#-NAAlkenEocN-JWr3JMN:-NARKgmq1PppsdecbBuA:birs9i1) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Sure, but why this file? I would say we should never have this file emulated at all.
</blockquote></details>

Not saying we need to merge this one if it's not actually needed, I just explained the context.
Other PRs should be very similar, so it's worth reviewing this one and arriving at a good version even if we won't merge it in the end.

___
___
*[`pal/src/host/linux/pal_main.c` line 124 at r7](https://reviewable.io/reviews/gramineproject/gramine/850#-NAF0Zq54DsFhPiOEYOb:-NARL7pa8IDmzLEDI8Bf:b-h5j8pm) ([raw file](https://github.com/gramineproject/gramine/blob/c2491bf1a408bcac56f92501f10f02a1307ac139/pal/src/host/linux/pal_main.c#L124)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

My point is that host info is a very broad term, whereas here we will probably just get some network related configuration. I don't have a good name in mind, but I feel like we should somehow point this is network related config.
</blockquote></details>

Ah, wait, topology is actually not processed here. Then maybe just `get_host_etc_configs`?


<!-- Sent from Reviewable.io -->

2022-08-26 23:17 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/850)* status: all files reviewed, 28 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/850#-NAAkLsfAAwA7AwAWlT9:-NARPnTy80yeMEnVPtEG:bz2zt6d) (no related file):*
> By "contents" I meant the values we get from the host.

Exactly, that's the point - we get them, they don't have to come from `/etc`, it could very well be some parsed output of some command.

> we don't really emulate these contents,

We provide `/etc` files which expose certain information. We do not provide real files there, just some pseudo,  so IMO we DO emulate their contents - we take a data structure of our choice and turn that into a pseudo file in `/etc`.

> we don't even really process them - only ensure that they look ok-ish and encode them into Linux etc files format.

We do process them, especially on SGX PAL, where we have to sanitize them. That will be especially true with proposed format of parsing Linux's `/etc/resolv.conf` where we parse the content into an arbitrary struct of our choice.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/850#-NAAlkenEocN-JWr3JMN:-NARQzZy7MOOz3c89MOu:bteru1m) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Not saying we need to merge this one if it's not actually needed, I just explained the context.
Other PRs should be very similar, so it's worth reviewing this one and arriving at a good version even if we won't merge it in the end.
</blockquote></details>

We most likely want to merge most of this PR anyway, because it establishes some ground for all others. Let's hear from @oshogbo why this file was picked as starter

___
___
*[`pal/src/host/linux/pal_main.c` line 124 at r7](https://reviewable.io/reviews/gramineproject/gramine/850#-NAF0Zq54DsFhPiOEYOb:-NARRKjx9QpU3-hxGWGm:bc0bp9r) ([raw file](https://github.com/gramineproject/gramine/blob/c2491bf1a408bcac56f92501f10f02a1307ac139/pal/src/host/linux/pal_main.c#L124)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Ah, wait, topology is actually not processed here. Then maybe just `get_host_etc_configs`?
</blockquote></details>

I guess, should work


<!-- Sent from Reviewable.io -->

2022-08-26 23:33 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/850)* status: all files reviewed, 28 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/850#-NAAkLsfAAwA7AwAWlT9:-NART0bk3lVwT99G6psM:bhhkyuq) (no related file):*
> Exactly, that's the point - we get them, they don't have to come from /etc, it could very well be some parsed output of some command.

Yes, I know, see "doesn't matter" in the reply above.

> We provide `/etc` files which expose certain information. We do not provide real files there, just some pseudo, so IMO we DO emulate their contents - we take a data structure of our choice and turn that into a pseudo file in `/etc`.

What I mean is the contents / information from these structures is passed through, not emulated. We emulate only the specific representation of these data (in Linux etc files format).

> We do process them, especially on SGX PAL, where we have to sanitize them. That will be especially true with proposed format of parsing Linux's `/etc/resolv.conf` where we parse the content into an arbitrary struct of our choice.

Yeah, but still, the _meaning_ / contents are passed through, not emulated. Same with topology - I wouldn't say that we emulate topology info, rather that we're passing it through the host with sanitization.

___


<!-- Sent from Reviewable.io -->

2022-08-27 00:02 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/850)* status: all files reviewed, 28 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/850#-NAAkLsfAAwA7AwAWlT9:-NAR_zBeE_V-zz1JTnfQ:b-m8ecu0) (no related file):*
In that sense whole Gramine is just one big passthrough, yet I wouldn't got so far to call it this way.

> What I mean is the contents / information from these structures is passed through, not emulated. We emulate only the specific representation of these data (in Linux etc files format).

Agreed. That's why proposed option was `emulate_etc_files`, not `emulate_network_config`

___


<!-- Sent from Reviewable.io -->

2022-08-31 13:54 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/850)* status: all files reviewed, 27 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/850#-NAAlkenEocN-JWr3JMN:-NAnX5tH9kkLYEC9L434:b-4lzza9) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

We most likely want to merge most of this PR anyway, because it establishes some ground for all others. Let's hear from @oshogbo why this file was picked as starter
</blockquote></details>

Like @mkow mentioned I'm a new in Gramine community, so I wanted to start from something that will be most Gramine specific, and less functional specific. I wanted to understand fs layer and so on and establish ground for this project. And not discuss the parser semantic and so on.

Like I mentioned in PR I think this is how the `/etc/hostname` is used, however it was still requested in the https://github.com/gramineproject/gramine/issues/689 .

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/850#-NAAkLsfAAwA7AwAWlT9:-NAo9Vw-EtxgVkB3dWll:b-896fix) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

In that sense whole Gramine is just one big passthrough, yet I wouldn't got so far to call it this way.

> What I mean is the contents / information from these structures is passed through, not emulated. We emulate only the specific representation of these data (in Linux etc files format).

Agreed. That's why proposed option was `emulate_etc_files`, not `emulate_network_config`
</blockquote></details>

Done.

___
___
*[`-- commits` line 20 at r6](https://reviewable.io/reviews/gramineproject/gramine/850#-NAAhs8l-kajqEx4BwyY):*
Done.
___
*[`Documentation/manifest-syntax.rst` line 147 at r4](https://reviewable.io/reviews/gramineproject/gramine/850#-NA4P28VD_THuKHVBpLg:-NAnYrXB7OLIKX5d1CbR:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/971d215eda6fe59256bbeac9ed2f0ee38f11adc7/Documentation/manifest-syntax.rst#L147)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'm fine with `emulate_etc_files` (although see my comment in a similar discussion above).
</blockquote></details>

Done.
___
*[`libos/src/libos_init.c` line 493 at r6](https://reviewable.io/reviews/gramineproject/gramine/850#-NABT_7_94bRRWlnujhY:-NAFatno1z0tsZt_Tika:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/3c3c3006c4bb50c082dd3e4c2e40a5c0dcb82432/libos/src/libos_init.c#L493)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ok
</blockquote></details>

Done.
___
*[`libos/src/fs/libos_fs.c` line 660 at r7](https://reviewable.io/reviews/gramineproject/gramine/850#-NAEv6dY4TkdkaiXEKrL:-NAnZK7KB4yFWcYxFwo9:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/c2491bf1a408bcac56f92501f10f02a1307ac139/libos/src/fs/libos_fs.c#L660)):*
> ```C
>     mount_etcfs();
> 
>     return 0;
> ```

Done.
___
*[`libos/src/fs/etc/fs.c` line 28 at r6](https://reviewable.io/reviews/gramineproject/gramine/850#-NABB9XWC6y7GDgfsgPb:-NAFYIEu8Fvg9QIpVVcS:bhpe6iv) ([raw file](https://github.com/gramineproject/gramine/blob/3c3c3006c4bb50c082dd3e4c2e40a5c0dcb82432/libos/src/fs/etc/fs.c#L28)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

?
</blockquote></details>

I just marked this as done, because you left an comment that you figure this out, sorry it was my misunderstanding. 

All file systems has this as a separate code.
First you have to register a pseudo file/fs, because otherwise the checkpoint mechanisms wont work.
And the mount code happens afterwords or don't happen at all (if I understand correctly).
___
*[`libos/src/fs/etc/fs.c` line 39 at r6](https://reviewable.io/reviews/gramineproject/gramine/850#-NABKdLa22kJg3zHCWmS:-NAnZYnV9x0uQrdGimg0:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/3c3c3006c4bb50c082dd3e4c2e40a5c0dcb82432/libos/src/fs/etc/fs.c#L39)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Yes, let other PRs change that if they need it. It doesn't make sense as is here.
</blockquote></details>

Done.
___
*[`libos/test/regression/hostname.c` line 68 at r5](https://reviewable.io/reviews/gramineproject/gramine/850#-NA9qWKpCvbRVJfEat3i:-NAndfmM13z-0n0ILy5z:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9dfc0952a02e96523df5cb9db7001ae0ad95273f/libos/test/regression/hostname.c#L68)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Hmm, I see that other tests have their own copies of such code wrapped into `read_all()`. Could you try moving it to a `common.c` or something and deduplicate?
</blockquote></details>

Done.
___
*[`pal/src/host/linux/pal_main.c` line 147 at r5](https://reviewable.io/reviews/gramineproject/gramine/850#-NA9vdgr1c8WkYnLxhrU:-NAneJWT0M55NbqOC_fn:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9dfc0952a02e96523df5cb9db7001ae0ad95273f/pal/src/host/linux/pal_main.c#L147)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This fits into one line
</blockquote></details>

Done.
___
*[`pal/src/host/linux/pal_main.c` line 124 at r7](https://reviewable.io/reviews/gramineproject/gramine/850#-NAF0Zq54DsFhPiOEYOb:-NAne1i128782M-W6X2m:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/c2491bf1a408bcac56f92501f10f02a1307ac139/pal/src/host/linux/pal_main.c#L124)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I guess, should work
</blockquote></details>

Done.
___
*[`pal/src/host/linux/pal_main.c` line 128 at r7](https://reviewable.io/reviews/gramineproject/gramine/850#-NAF0AMq973LNrox7HDP:-NAneAT98rxmK2s2dI_d:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/c2491bf1a408bcac56f92501f10f02a1307ac139/pal/src/host/linux/pal_main.c#L128)):*
> ```C
> 
>     ret = toml_bool_in(g_pal_public_state.manifest_root, "libos.passthrough_etc_files",
>                        false, &g_pal_public_state.passthrough_etc_files);
> ```

Done.
___
*[`pal/src/host/linux/pal_main.c` line 431 at r7](https://reviewable.io/reviews/gramineproject/gramine/850#-NAF-WIh56Kzi_fzVfx0:-NAneNam4sH2Ea3BR-4B:by59zyj) ([raw file](https://github.com/gramineproject/gramine/blob/c2491bf1a408bcac56f92501f10f02a1307ac139/pal/src/host/linux/pal_main.c#L431)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Because we always read first the `emulate_etc_files`.
@dimakuv  asked not to propagate this with checkpoints, and I would like to have the same global state in every process.
I also like the idea to parse the toml inside. But as this isn't obvious and we should move the toml  parsing outside this function.
___
*[`pal/src/host/linux-sgx/host_main.c` line 908 at r7](https://reviewable.io/reviews/gramineproject/gramine/850#-NAPsymPDgNYi_35EoBc:-NAnfYhM2CylsJXye-qK:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/c2491bf1a408bcac56f92501f10f02a1307ac139/pal/src/host/linux-sgx/host_main.c#L908)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto - I like Borys' suggestion to move that `if` outside
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/pal_ecall_types.h` line 22 at r6](https://reviewable.io/reviews/gramineproject/gramine/850#-NAB8I2P5sOQ8SK5lwrz:-NAoAUXv6lIBTrzQP4Nj:b-896fix) ([raw file](h [...]

2022-08-31 16:31 UTC, boryspoplawski requested changes
> Reviewed 7 of 19 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/850)* status: 19 of 31 files reviewed, 21 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "squash! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/850#-NAAlkenEocN-JWr3JMN:-NAodhqQBcXOQUBB4gg0:bk6dgq1) (no related file):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Like @mkow mentioned I'm a new in Gramine community, so I wanted to start from something that will be most Gramine specific, and less functional specific. I wanted to understand fs layer and so on and establish ground for this project. And not discuss the parser semantic and so on.

Like I mentioned in PR I think this is how the `/etc/hostname` is used, however it was still requested in the https://github.com/gramineproject/gramine/issues/689 .
</blockquote></details>

The fact that something is requested doesn't mean we actually need it. Or that it's even useful at all. In that RFC issue it was present in a list of files that Docker shadows/emulates - this is because Docker is different from Graimne, it can set up networking stuff if it wants to (it has a separate network namespace), in Gramine this doesn't make sense.

___
___
*[`Documentation/manifest-syntax.rst` line 148 at r8](https://reviewable.io/reviews/gramineproject/gramine/850#-NAoeZ9_DqEFiZrjkXPz:-NAoeZ9_DqEFiZrjkXQ-:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/0890f7eff4d0e93b2a9c8c26e97c804f7997641e/Documentation/manifest-syntax.rst#L148)):*
> ```reStructuredText
> 
> This specifies whether to emulate runtime files under ``/etc``.
> In the case of SGX on Linux, this is achieved by taking the host's ``/etc``
> ```





_Suggestion:_
```reStructuredText
Linux SGX PAL
```
___
*[`libos/test/regression/rename_unlink.c` line 39 at r8](https://reviewable.io/reviews/gramineproject/gramine/850#-NAogW8F9qzWNsFEuL0w:-NAogW8F9qzWNsFEuL0x:b-1znjp3) ([raw file](https://github.com/gramineproject/gramine/blob/90f8b9d7eacfa1c9bc07089d9d00ea774888435f/libos/test/regression/rename_unlink.c#L39)):*
> ```C
>             warn("write");
>             return -1;
>         }
> ```

What's with this change, how's that related to the PR?
disclaimer: I've not yet reviewed the test part of this PR
___
*[`pal/src/host/linux/pal_main.c` line 431 at r7](https://reviewable.io/reviews/gramineproject/gramine/850#-NAF-WIh56Kzi_fzVfx0:-NAohSbK4WuN9NVKMDdn:b-5ygk9k) ([raw file](https://github.com/gramineproject/gramine/blob/c2491bf1a408bcac56f92501f10f02a1307ac139/pal/src/host/linux/pal_main.c#L431)):*
> I also like the idea to parse the toml inside. But as this isn't obvious and we should move the toml  parsing outside this function.

Parse error.
Anyway, I think we should move toml parsing outside - it doesn't even match this function name (`get_host_etc...`)
___
*[`pal/src/host/linux-sgx/pal_ecall_types.h` line 24 at r6](https://reviewable.io/reviews/gramineproject/gramine/850#-NAB8ReW1mDYSo3xujrM:-NAoj2YK5np72MyoaUqg:b-a71mvr) ([raw file](https://github.com/gramineproject/gramine/blob/3c3c3006c4bb50c082dd3e4c2e40a5c0dcb82432/pal/src/host/linux-sgx/pal_ecall_types.h#L24)):*
> +1, although we'll probably change it later anyways, when moving this to g_pal_public_initial_state?

What does it have to do with this? `g_pal_public_initial_state` is a trusted struct inside PAL, this is ecall interface
___
*[`pal/src/host/linux-sgx/pal_ecall_types.h` line 34 at r8](https://reviewable.io/reviews/gramineproject/gramine/850#-NAoiVMP8dc47ZccHEUI:-NAoiVMP8dc47ZccHEUJ:b-l9uql7) ([raw file](https://github.com/gramineproject/gramine/blob/0890f7eff4d0e93b2a9c8c26e97c804f7997641e/pal/src/host/linux-sgx/pal_ecall_types.h#L34)):*
> ```objc
>     int                     ms_parent_stream_fd;
>     sgx_target_info_t*      ms_qe_targetinfo;
>     struct pal_host_info*   ms_host_info;
> ```

Why did you add more spaces?



_Suggestion:_
```objc
struct pal_host_info* ms_host_info;
```
___
*[`pal/src/host/linux-common/etc_host_info.c` line 13 at r5](https://reviewable.io/reviews/gramineproject/gramine/850#-NA9xvq_-66SSDCEVhMJ:-NARRU0C4OeMyTkmMjWP:b-rycewt) ([raw file](https://github.com/gramineproject/gramine/blob/9dfc0952a02e96523df5cb9db7001ae0ad95273f/pal/src/host/linux-common/etc_host_info.c#L13)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I actually like it, easier to notice if the matching header was included, but it's not a strong preference.
Some historical context: We inherited it from [Google C++ styleguide](https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes).
</blockquote></details>

@oshogbo please fix, as we merged the PR removing this rule


<!-- Sent from Reviewable.io -->

2022-09-01 06:58 UTC, dimakuv requested changes
> Reviewed 19 of 19 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/850)* status: all files reviewed, 21 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "squash! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/850#-NAAlkenEocN-JWr3JMN:-NArl8KC28JrQFGrDM61:b-4ih98t) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

The fact that something is requested doesn't mean we actually need it. Or that it's even useful at all. In that RFC issue it was present in a list of files that Docker shadows/emulates - this is because Docker is different from Graimne, it can set up networking stuff if it wants to (it has a separate network namespace), in Gramine this doesn't make sense.
</blockquote></details>

@boryspoplawski But why do you say that emulating `/etc/hostname` is useless?

If we choose to not emulate `/etc/hostname`, then we have two arguments:
1. No applications use this file.
2. When applications use this file, the file contents can be hard-coded on any system (via `sgx.trusted_files = "file:/etc/hostname"`)

Which of these arguments is true in your opinion? How can we be sure in argument 1? How can we be sure in argument 2?

Or maybe there is argument 3?

Otherwise, if we cannot say for sure that `/etc/hostname` is never used (or never changes from one system to the other), then we *must* have this PR, right?

___
___
*[`Documentation/manifest-syntax.rst` line 148 at r8](https://reviewable.io/reviews/gramineproject/gramine/850#-NAoeZ9_DqEFiZrjkXPz:-NArmAU4EDVnm-JNB_gf:buxly5f) ([raw file](https://github.com/gramineproject/gramine/blob/0890f7eff4d0e93b2a9c8c26e97c804f7997641e/Documentation/manifest-syntax.rst#L148)):*
> ```reStructuredText
> 
> This specifies whether to emulate runtime files under ``/etc``.
> In the case of SGX on Linux, this is achieved by taking the host's ``/etc``
> ```

`Linux-SGX PAL`, that's the most correct name.
___
*[`Documentation/manifest-syntax.rst` line 149 at r8](https://reviewable.io/reviews/gramineproject/gramine/850#-NArmFuFCrTVRS0D7Nj0:-NArmFuFCrTVRS0D7Nj1:bu13apr) ([raw file](https://github.com/gramineproject/gramine/blob/0890f7eff4d0e93b2a9c8c26e97c804f7997641e/Documentation/manifest-syntax.rst#L149)):*
> ```reStructuredText
> This specifies whether to emulate runtime files under ``/etc``.
> In the case of SGX on Linux, this is achieved by taking the host's ``/etc``
> files, filter supported options, and sanitize them.
> ```

`filtering`, `sanitizing`
___
*[`libos/src/fs/etc/fs.c` line 69 at r6](https://reviewable.io/reviews/gramineproject/gramine/850#-NABSW6r6aVh2d97lPwd:-NArnblo0jofSYmqhLjL:banrudh) ([raw file](https://github.com/gramineproject/gramine/blob/3c3c3006c4bb50c082dd3e4c2e40a5c0dcb82432/libos/src/fs/etc/fs.c#L69)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Yes, definitely not in this PR.
</blockquote></details>

I created a GitHub issue for this: https://github.com/gramineproject/gramine/issues/872
___
*[`libos/test/regression/rename_unlink.c` line 39 at r8](https://reviewable.io/reviews/gramineproject/gramine/850#-NAogW8F9qzWNsFEuL0w:-NAro0Z-CdE0k09AfNNJ:b-7btpgj) ([raw file](https://github.com/gramineproject/gramine/blob/90f8b9d7eacfa1c9bc07089d9d00ea774888435f/libos/test/regression/rename_unlink.c#L39)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

What's with this change, how's that related to the PR?
disclaimer: I've not yet reviewed the test part of this PR
</blockquote></details>

Same question from me -- can we split this into a separate PR? And why `write_all()` is not replaced by a func from `rw_file.h`?
___
*[`pal/src/host/linux/pal_main.c` line 431 at r7](https://reviewable.io/reviews/gramineproject/gramine/850#-NAF-WIh56Kzi_fzVfx0:-NAroTF24I3dTX1x7_Pd:bjb0u42) ([raw file](https://github.com/gramineproject/gramine/blob/c2491bf1a408bcac56f92501f10f02a1307ac139/pal/src/host/linux/pal_main.c#L431)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

> I also like the idea to parse the toml inside. But as this isn't obvious and we should move the toml  parsing outside this function.

Parse error.
Anyway, I think we should move toml parsing outside - it doesn't even match this function name (`get_host_etc...`)

</blockquote></details>

I'm fine with Borys's proposal to move the parsing of `libos.emulate_etc_files` boolean outside of the `get_host_etc_configs()` file.
___
*[`pal/src/host/linux-sgx/pal_main.c` line 316 at r7](https://reviewable.io/reviews/gramineproject/gramine/850#-NAQHxv42mKymcFPZujj:-NArpYcyCGqIVNlwQWJD:biulmjn) ([raw file](https://github.com/gramineproject/gramine/blob/c2491bf1a408bcac56f92501f10f02a1307ac139/pal/src/host/linux-sgx/pal_main.c#L316)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

We are reading the data before verifying is it first process or not, as some parts aren't checkpointed.
</blockquote></details>

I think the suggestion is to move `libos.emulate_etc_files` parsing outside anyway, and then you can also move `first_process` check outside as well. Similar as requested in Linux PAL.


<!-- Sent from Reviewable.io -->

2022-09-01 12:04 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/850)* status: all files reviewed, 21 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "squash! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/850#-NAAlkenEocN-JWr3JMN:-NAst7D8-8NxeQ4H8KS7:b-cwpyvr) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@boryspoplawski But why do you say that emulating `/etc/hostname` is useless?

If we choose to not emulate `/etc/hostname`, then we have two arguments:
1. No applications use this file.
2. When applications use this file, the file contents can be hard-coded on any system (via `sgx.trusted_files = "file:/etc/hostname"`)

Which of these arguments is true in your opinion? How can we be sure in argument 1? How can we be sure in argument 2?

Or maybe there is argument 3?

Otherwise, if we cannot say for sure that `/etc/hostname` is never used (or never changes from one system to the other), then we *must* have this PR, right?
</blockquote></details>

`/etc/hostname` is an initial hostname to set - think of it as a way of permanently setting hostname that survives reboots. Temporary changes are done by `sethostname` syscall, which ofc does not change `/etc/hostname`. Now what could possibly be changing `/etc/hostname`? Either
1) manual user change - irrelevant to us,
2) some platform bootstrapping / setup scripts - nothing like that should be run in Gramine.
Now what could be reading it?
1) Early init script to call `sethostname` on that name. Generally I don't think such scripts are runnable in Gramine (e.g. systemd :smile:)
2) Everything else should use `gethostname` as it can differ from `/etc/hostname`.

The argument slightly changes when we mix namespaces, but we do not support them.

All of the above is my thinking, it could be inaccurate or plain wrong.

___


<!-- Sent from Reviewable.io -->

2022-09-01 12:11 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/850)* status: all files reviewed, 21 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "squash! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/850#-NAAlkenEocN-JWr3JMN:-NAsx6lA409Pezz4p4dp:btk8xf0) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`/etc/hostname` is an initial hostname to set - think of it as a way of permanently setting hostname that survives reboots. Temporary changes are done by `sethostname` syscall, which ofc does not change `/etc/hostname`. Now what could possibly be changing `/etc/hostname`? Either
1) manual user change - irrelevant to us,
2) some platform bootstrapping / setup scripts - nothing like that should be run in Gramine.
Now what could be reading it?
1) Early init script to call `sethostname` on that name. Generally I don't think such scripts are runnable in Gramine (e.g. systemd :smile:)
2) Everything else should use `gethostname` as it can differ from `/etc/hostname`.

The argument slightly changes when we mix namespaces, but we do not support them.

All of the above is my thinking, it could be inaccurate or plain wrong.
</blockquote></details>

@boryspoplawski I'm not talking about *changing* `/etc/hostname`.

Let me rephrase -- you write a manifest file, and you expect this manifest file to run on 100s of different machines (you prepared the Gramine app distribution once, and then you run it on different cloud machines and client machines). Assuming that your application reads `/etc/hostname` (at least once, during init) -- how do we enable this file in Gramine?

From what I understand, there is no good way of solving the above scenario currently. This PR allows this scenario.

___


<!-- Sent from Reviewable.io -->

2022-09-01 12:13 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/850)* status: all files reviewed, 21 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "squash! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/850#-NAAlkenEocN-JWr3JMN:-NAsxscC4Ws2ry2nKPAk:b-cw20bm) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@boryspoplawski I'm not talking about *changing* `/etc/hostname`.

Let me rephrase -- you write a manifest file, and you expect this manifest file to run on 100s of different machines (you prepared the Gramine app distribution once, and then you run it on different cloud machines and client machines). Assuming that your application reads `/etc/hostname` (at least once, during init) -- how do we enable this file in Gramine?

From what I understand, there is no good way of solving the above scenario currently. This PR allows this scenario.
</blockquote></details>

Just to reiterate: we want to run some Gramine app on multiple machines, and these machines may have different hostnames (which is reflected in `/etc/hostname`).

___


<!-- Sent from Reviewable.io -->

2022-09-01 12:29 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/850)* status: all files reviewed, 21 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "squash! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/850#-NAAlkenEocN-JWr3JMN:-NAt0TSq3AB7-_5Gr2gD:bnuqfi0) (no related file):*
No, it's not reflected in `/etc/hostname` it's reflected in `gethostname` output.

> Assuming that your application reads /etc/hostname (at least once, during init) -- how do we enable this file in Gramine?

Ideally your application does the correct thing and uses `gethostname`.

___


<!-- Sent from Reviewable.io -->

2022-09-01 12:33 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/850)* status: all files reviewed, 21 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "squash! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/850#-NAAlkenEocN-JWr3JMN:-NAt1JSx25MFe77VazdJ:bhblpn2) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

No, it's not reflected in `/etc/hostname` it's reflected in `gethostname` output.

> Assuming that your application reads /etc/hostname (at least once, during init) -- how do we enable this file in Gramine?

Ideally your application does the correct thing and uses `gethostname`.
</blockquote></details>

Ok, so you say that "No applications use this file".

How can we verify this theory? And do we want to be on the safe side and in this case use this PR (which allows safe use of `/etc/hostname`)?

___


<!-- Sent from Reviewable.io -->

2022-09-01 17:00 UTC, mkow requested changes
> Reviewed 19 of 19 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/850)* status: all files reviewed, 15 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "squash! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/850#-NAAkLsfAAwA7AwAWlT9:-NAtSSj57_GsUNfhf1Zc:b-loqew1) (no related file):*
> In that sense whole Gramine is just one big passthrough, yet I wouldn't got so far to call it this way.

I think that's quite a big jump...

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/850#-NAAlkenEocN-JWr3JMN:-NAtSsZv7Jfhf-vxzv20:brqvanl) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ok, so you say that "No applications use this file".

How can we verify this theory? And do we want to be on the safe side and in this case use this PR (which allows safe use of `/etc/hostname`)?
</blockquote></details>

I see at least two argument in favor of "No applications use this file":
- Debian doesn't have this file.
- `gethostname()` doesn't use it (it uses `uname` syscall instead), so an app would need to manually read `/etc/hostname`.

But of course software may be more broken than we think :)

___
___
*[`-- commits` line 59 at r8](https://reviewable.io/reviews/gramineproject/gramine/850#-NAtUDb2ESCp319ce7kq):*
I don't like commit messages in this tense/grammar form, because it's not clear whether you're describing the state before this commit (to make an introduction to the changes described later) or actually the changes in this commit.
___
*[`-- commits` line 61 at r8](https://reviewable.io/reviews/gramineproject/gramine/850#-NAtUa3d0kOUw4Hnubx-):*
This is even more misleading than the above :) You used past tense here, so it seems that you're describing what Gramine did before this commit.



_Code quote:_
```
Gramine expected
```
___
*[`libos/src/libos_init.c` line 490 at r8](https://reviewable.io/reviews/gramineproject/gramine/850#-NAtVCmw5SHaIrSfeHNb:-NAtVCmw5SHaIrSfeHNc:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/0890f7eff4d0e93b2a9c8c26e97c804f7997641e/libos/src/libos_init.c#L490)):*
> ```C
>     RUN_INIT(init_sync_client);
> 
>     /* XXX: this will break uname checkpointing. */
> ```





_Suggestion:_
```C
this will break uname checkpointing (if we implement it)
```
___
*[`libos/test/regression/rename_unlink.c` line 39 at r8](https://reviewable.io/reviews/gramineproject/gramine/850#-NAogW8F9qzWNsFEuL0w:-NAtYY8m84yemsKwLteE:b-yf53lg) ([raw file](https://github.com/gramineproject/gramine/blob/90f8b9d7eacfa1c9bc07089d9d00ea774888435f/libos/test/regression/rename_unlink.c#L39)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Same question from me -- can we split this into a separate PR? And why `write_all()` is not replaced by a func from `rw_file.h`?
</blockquote></details>

I asked about this, because @oshogbo added another copy of this code to `hostname.c` test. It's just a test code, so IMO it can stay in this PR to not complicate things (but if it was in the main code then it should rather get split).
___
*[`pal/src/host/linux-sgx/host_main.c` line 619 at r8](https://reviewable.io/reviews/gramineproject/gramine/850#-NAt_V_k4Zzd4ibvrU5E:-NAt_V_l3mBLj1M1drLB:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/0890f7eff4d0e93b2a9c8c26e97c804f7997641e/pal/src/host/linux-sgx/host_main.c#L619)):*
> ```C
> /* Parses only the information needed by the untrusted PAL to correctly initialize the enclave. */
> static int parse_loader_config(char* manifest, struct pal_enclave* enclave_info,
>                                bool *emulate_etc) {
> ```





_Suggestion:_
```C
bool* emulate_etc
```
___
*[`pal/src/host/linux-sgx/pal_ecall_types.h` line 24 at r6](https://reviewable.io/reviews/gramineproject/gramine/850#-NAB8ReW1mDYSo3xujrM:-NAtw2kH8c1Qlle-j8Tf:bhuec31) ([raw file](https://github.com/gramineproject/gramine/blob/3c3c3006c4bb50c082dd3e4c2e40a5c0dcb82432/pal/src/host/linux-sgx/pal_ecall_types.h#L24)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

> +1, although we'll probably change it later anyways, when moving this to g_pal_public_initial_state?

What does it have to do with this? `g_pal_public_initial_state` is a trusted struct inside PAL, this is ecall interface
</blockquote></details>

Oh, this is ecall. Sorry, I misread it, I thought it's some global struct. Maybe we should prefix ecall arg structs with `ecall_`?
___
*[`pal/src/host/linux-sgx/pal_main.c` line 316 at r7](https://reviewable.io/reviews/gramineproject/gramine/850#-NAQHxv42mKymcFPZujj:-NAtxXqb9gDAG2gNTZt3:b-7xtei2) ([raw file](https://github.com/gramineproject/gramine/blob/c2491bf1a408bcac56f92501f10f02a1307ac139/pal/src/host/linux-sgx/pal_main.c#L316)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I think the suggestion is to move `libos.emulate_etc_files` parsing outside anyway, and then you can also move `first_process` check outside as well. Similar as requested in Linux PAL.
</blockquote></details>

Yeah.
___
*[`pal/src/host/linux-sgx/pal_main.c` line 647 at r7](https://reviewable.io/reviews/gramineproject/gramine/850#-NAQGl4D7NtTYl2DzBVQ:-NAtxzSj8PWhBbI2irRy:b-4rwa82) ([raw file](https://github.com/gramineproject/gramine/blob/c2491bf1a408bcac56f92501f10f02a1307ac139/pal/src/host/linux-sgx/pal_main.c#L647)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Checking validity of `pal_linux_main` call.
</blockquote></details>

It's not really checking anything, it's just an assert which doesn't land in release builds. And even if it was a real check, then it still makes little sense:
- Why check for a NULL specifically? `-1` is also for sure invalid, but you don't check for it. And misaligned pointers. And many more.
- In terms of security, you have `sgx_copy_to_enclave()` call right underneath which can't do any insecure copying.
___
*[`pal/src/host/linux-sgx/pal_main.c` line 649 at r7](https://reviewable.io/reviews/gramineproject/gramine/850#-NAQG_r2EeB6zD4aO5jO:-NAtyk5c5XSFhqPCFfQe:bpijfz7) ([raw file](https://github.com/gramineproject/gramine/blob/c2491bf1a408bcac56f92501f10f02a1307ac139/pal/src/host/linux-sgx/pal_main.c#L649)):*
> I don't see such assert.

There's `usize > maxsize` comparison inside it.
___
*[`pal/src/host/linux-sgx/pal_main.c` line 289 at r8](https://reviewable.io/reviews/gramineproject/gramine/850#-NAtz7pFCfiOEFnqv9Dq:-NAtz7pFCfiOEFnqv9Dr:b-41ig72) ([raw file](https://github.com/gramineproject/gramine/blob/0890f7eff4d0e93b2a9c8c26e97c804f7997641e/pal/src/host/linux-sgx/pal_main.c#L289)):*
> ```C
>     }
> 
>     if (ptr - hostname >= PAL_HOSTNAME_MAX)
> ```

Please add a comment inside the body of this `if`: `/* Missing NULL termination */`


<!-- Sent from Reviewable.io -->

2022-09-01 18:09 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/850)* status: all files reviewed, 15 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "squash! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @oshogbo)

___
*[`libos/test/regression/rename_unlink.c` line 39 at r8](https://reviewable.io/reviews/gramineproject/gramine/850#-NAogW8F9qzWNsFEuL0w:-NAuDRAXEHgpK0I5RS--:b-3lk71t) ([raw file](https://github.com/gramineproject/gramine/blob/90f8b9d7eacfa1c9bc07089d9d00ea774888435f/libos/test/regression/rename_unlink.c#L39)):*
> I asked about this, because @oshogbo added another copy of this code to hostname.c test.

And how's this related? We already had abstractions for such functions.
___
*[`pal/src/host/linux-sgx/pal_ecall_types.h` line 24 at r6](https://reviewable.io/reviews/gramineproject/gramine/850#-NAB8ReW1mDYSo3xujrM:-NAuDrfk2Z5s9RF44aWF:bqfoc0k) ([raw file](https://github.com/gramineproject/gramine/blob/3c3c3006c4bb50c082dd3e4c2e40a5c0dcb82432/pal/src/host/linux-sgx/pal_ecall_types.h#L24)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Oh, this is ecall. Sorry, I misread it, I thought it's some global struct. Maybe we should prefix ecall arg structs with `ecall_`?
</blockquote></details>

But it's not passed into ecall directly it's embedded in another struct that already has `ecall_` prefix.
This is another argument for not holding these together - currently this struct IMO makes no sense and should be inlined. We can have a struct once we actually have something to put in there.


<!-- Sent from Reviewable.io -->

2022-09-01 22:55 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/850)* status: all files reviewed, 15 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "squash! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @oshogbo)

___
*[`libos/test/regression/rename_unlink.c` line 39 at r8](https://reviewable.io/reviews/gramineproject/gramine/850#-NAogW8F9qzWNsFEuL0w:-NAvFXV3CVZHSYxTtq4Y:b-u4xuzl) ([raw file](https://github.com/gramineproject/gramine/blob/90f8b9d7eacfa1c9bc07089d9d00ea774888435f/libos/test/regression/rename_unlink.c#L39)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

> I asked about this, because @oshogbo added another copy of this code to hostname.c test.

And how's this related? We already had abstractions for such functions.
</blockquote></details>

It's not really related, but also not a big change. But if you want we can split it out into a separate PR/commit.
___
*[`pal/src/host/linux-sgx/pal_ecall_types.h` line 24 at r6](https://reviewable.io/reviews/gramineproject/gramine/850#-NAB8ReW1mDYSo3xujrM:-NAvFtBs9HUO2RKvK7wf:bfcelyt) ([raw file](https://github.com/gramineproject/gramine/blob/3c3c3006c4bb50c082dd3e4c2e40a5c0dcb82432/pal/src/host/linux-sgx/pal_ecall_types.h#L24)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

But it's not passed into ecall directly it's embedded in another struct that already has `ecall_` prefix.
This is another argument for not holding these together - currently this struct IMO makes no sense and should be inlined. We can have a struct once we actually have something to put in there.
</blockquote></details>

Ok, let's inline it then.


<!-- Sent from Reviewable.io -->

2022-09-02 06:54 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/850)* status: all files reviewed, 15 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "squash! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/850#-NAAlkenEocN-JWr3JMN:-NAwxMOv0dXkoyClyid1:b-i6tt0x) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I see at least two argument in favor of "No applications use this file":
- Debian doesn't have this file.
- `gethostname()` doesn't use it (it uses `uname` syscall instead), so an app would need to manually read `/etc/hostname`.

But of course software may be more broken than we think :)
</blockquote></details>

Ok, so then we need to agree on the next steps now. Looks like two maintainers who know this area best (Borys and Michal) agree that we do *not* need to emulate `/etc/hostname`.

So looks like we need to do the following things:
1. Close this PR (the parts of it will be used in the two new PRs described below).
2. Create a first PR that will initialize `uname.domainname` in `g_current_uname`: https://github.com/gramineproject/gramine/blob/f1e1d22d29a08c05a6cf19188aa0241787608371/libos/src/sys/libos_uname.c#L32?plain=1
    - This should use the `uname` host syscall in PAL and propagate the value of `uname.domainname` to LibOS
    - LibOS should sanitize this value, similar to how it is done in the current PR
3. Create a second PR that will emulate the file `/etc/resolv.conf`. A lot of the pseudo-files scaffolding should be taken from the current PR.

@mkow @boryspoplawski @oshogbo Does this sound correct?

___


<!-- Sent from Reviewable.io -->

2022-09-02 12:54 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/850)* status: all files reviewed, 15 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "squash! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/850#-NAAlkenEocN-JWr3JMN:-NAyB5N98fu7xwvhOubA:bkbesf3) (no related file):*
> Debian doesn't have this file.

@mkow What? Even debian wiki says you need to update this file when you change hostname. I don't have any debian at hand to check, but this doesn't feel right.

How about `/etc/hosts` before `/etc/resolv.conf`? It sounds much easier to add and would be mostly the same as this PR (so there 's even a change we could reuse it completely)

___


<!-- Sent from Reviewable.io -->

2022-09-04 19:20 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/850)* status: all files reviewed, 15 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "squash! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/850#-NAAlkenEocN-JWr3JMN:-NB8wLsm9TAHoRsrlpvG:b-igqtx0) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

> Debian doesn't have this file.

@mkow What? Even debian wiki says you need to update this file when you change hostname. I don't have any debian at hand to check, but this doesn't feel right.

How about `/etc/hosts` before `/etc/resolv.conf`? It sounds much easier to add and would be mostly the same as this PR (so there 's even a change we could reuse it completely)
</blockquote></details>

@dimakuv: Sounds good.
@boryspoplawski: Maybe it's because it comes from Qubes OS Debian template and they've changed something? Dunno.

___


<!-- Sent from Reviewable.io -->

2022-09-06 18:33 UTC, closed without merging