[PAL] Introduce `loader.argv` manifest option
gramineproject/gramine pull request #858
Opened 2022-08-24 17:52 UTC by oshogbo

## Description of the changes 

This PR implements the `loader.argv` described in #761. In this issue @mkow raises the question about `loader.argv0_override` , however this option was recently removed by @dimakuv in f91a2c18370858701a33c00620b0c7954f6779bf.
The whole section was converted to use the table. This was done because currently Gramine version of tomlc99 doesn't support dot notation in `toml_array_in`.

## How to test this PR? 

New tests was added.

2022-08-25 08:20 UTC, dimakuv requested changes
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/858)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/858#-NAJ47he9Vu9zoVzmMpt:-NAJ47he9Vu9zoVzmMpu:b-pdhel8) (no related file):*
@oshogbo Please check why ASan failed.

___
___
*[`Documentation/manifest-syntax.rst` line 143 at r1](https://reviewable.io/reviews/gramineproject/gramine/858#-NAJ0N-0DwK7zZqOX2ua:-NAJ0N-0DwK7zZqOX2ub:b-a67cmc) ([raw file](https://github.com/gramineproject/gramine/blob/4c18b890207d8779c695224609e468d74baf7616/Documentation/manifest-syntax.rst#L143)):*
> ```reStructuredText
> 
> The ``loader.insecure__use_cmdline_argv``, ``loader.argv``, and
> ``loader.argv_src_file`` are mutually exclusive.
> ```

`are mutually exclusive` -> `options are mutually exclusive`
___
*[`libos/test/regression/argv.manifest.template` line 13 at r1](https://reviewable.io/reviews/gramineproject/gramine/858#-NAJ0kuz3M4ShlsILYSp:-NAJ0kuz3M4ShlsILYSq:bqymhhg) ([raw file](https://github.com/gramineproject/gramine/blob/4c18b890207d8779c695224609e468d74baf7616/libos/test/regression/argv.manifest.template#L13)):*
> ```
>   "TO",
>   "THE",
>   "APP ",
> ```

Please add a comment `# note the trailing space (app should see this trailing space in its argv[5])`
___
*[`libos/test/regression/argv.manifest.template` line 26 at r1](https://reviewable.io/reviews/gramineproject/gramine/858#-NAJ0d652mkk-k2N4XYO:-NAJ0d652mkk-k2N4XYP:b-sg26sw) ([raw file](https://github.com/gramineproject/gramine/blob/4c18b890207d8779c695224609e468d74baf7616/libos/test/regression/argv.manifest.template#L26)):*
> ```
> sgx.allowed_files = [
>   "file:argv_test_input",
> ]
> ```

What is this? Looks redundant (and wrong)
___
*[`pal/src/pal_main.c` line 423 at r1](https://reviewable.io/reviews/gramineproject/gramine/858#-NAJ1RJG6W99ep2K2n9y:-NAJ1RJG6W99ep2K2n9z:b-2jy0y6) ([raw file](https://github.com/gramineproject/gramine/blob/4c18b890207d8779c695224609e468d74baf7616/pal/src/pal_main.c#L423)):*
> ```C
>     char* argv_src_file = NULL;
>     ret = toml_string_in(manifest_loader, "argv_src_file",
>                          &argv_src_file);
> ```

Please wrap these 2 lines into 1 line
___
*[`pal/src/pal_main.c` line 432 at r1](https://reviewable.io/reviews/gramineproject/gramine/858#-NAJ2Kpe-gFy21lnvyWQ:-NAJ2Kpe-gFy21lnvyWR:bl20xzq) ([raw file](https://github.com/gramineproject/gramine/blob/4c18b890207d8779c695224609e468d74baf7616/pal/src/pal_main.c#L432)):*
> ```C
>         argv_option_cnt = toml_array_nelem(argv_option);
>         if (argv_option_cnt < 0)
>             INIT_FAIL_MANIFEST("Cannot parse 'loader.argv'");
> ```

Actually, what does it mean to specify `loader.argv = [ ]`? I don't think we want to support no-arguments invocations.

So I would add:
```
if (argv_option_cnt == 0)
    INIT_FAIL_MANIFEST("'loader.argv' has no arguments, this is unsupported");
```

If we won't have smth like this, I think Gramine will fail somewhere below if the manifest has `loader.argv = [ ]`?
___
*[`pal/src/pal_main.c` line 448 at r1](https://reviewable.io/reviews/gramineproject/gramine/858#-NAJ1ujM1VQ8GP9cRRCI:-NAJ1ujM1VQ8GP9cRRCJ:b-2jy0y6) ([raw file](https://github.com/gramineproject/gramine/blob/4c18b890207d8779c695224609e468d74baf7616/pal/src/pal_main.c#L448)):*
> ```C
>         /* possible in e.g. PAL regression tests, in this case use loader.entrypoint */
>         ret = toml_string_in(manifest_loader, "entrypoint",
>                              &argv0_override);
> ```

Please wrap these 2 lines into 1 line
___
*[`pal/src/pal_main.c` line 453 at r1](https://reviewable.io/reviews/gramineproject/gramine/858#-NAJ3LRh3ff_O1SXaw4W:-NAJ3LRh3ff_O1SXaw4X:b-yfgn5v) ([raw file](https://github.com/gramineproject/gramine/blob/3d23397e242786db9bbf903f0a803d5f7376ad47/pal/src/pal_main.c#L453)):*
> ```C
>             if (arguments[0] && arguments[1])
>                 log_error("Discarding cmdline arguments (%s %s [...]) because loader.argv_src_file "
>                           "was specified in the manifest.", arguments[0], arguments[1]);
> ```

Why did you remove this info message? I think it's useful so that users know that their accidental incorrect invocation like `gramine-sgx argv blablabla ...` discards this `blablabla ...` stuff in favor of hard-coded argv from the manifest.

I would print this info message for both `argv_option_cnt > 0` and `argv_src_file`.
___
*[`pal/src/pal_main.c` line 475 at r1](https://reviewable.io/reviews/gramineproject/gramine/858#-NAJ4U8G55OEpoPOUBm-:-NAJ4U8G55OEpoPOUBm0:bgo8hlq) ([raw file](https://github.com/gramineproject/gramine/blob/4c18b890207d8779c695224609e468d74baf7616/pal/src/pal_main.c#L475)):*
> ```C
>                 INIT_FAIL("Cannot parse argv[%zd]", i);
>             }
>             new_args[i] = toml_arg.u.s;
> ```

Is this safe to do? Your `new_args` contain pointers somewhere into the parsed TOML manifest object. I would feel safer if we would perform copies of those strings.
___
*[`pal/src/pal_main.c` line 502 at r1](https://reviewable.io/reviews/gramineproject/gramine/858#-NAJ3yxNDdWm9sLWz7nG:-NAJ3yxNDdWm9sLWz7nH:b-959r1p) ([raw file](https://github.com/gramineproject/gramine/blob/4c18b890207d8779c695224609e468d74baf7616/pal/src/pal_main.c#L502)):*
> ```C
>     bool use_host_env;
>     ret = toml_bool_in(manifest_loader, "insecure__use_host_env",
>                        /*defaultval=*/false, &use_host_env);
> ```

Please re-wrap


<!-- Sent from Reviewable.io -->

2022-08-25 08:21 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/858)* status: all files reviewed, 11 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/858#-NAJ4jxf1wrE7VP0wbSD:-NAJ4jxg4UGAXmff7RS7:b-7lx8lr) (no related file):*
Please add `Fixes #761` in PR description.

___


<!-- Sent from Reviewable.io -->

2022-08-25 13:19 UTC, oshogbo reviewed
Jenkins, retest Jenkins-SGX-18.04-apps

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/858#-:-NAK99gO38Ahu8drUe-m:b-9aj5yu)* status: 3 of 6 files reviewed, 11 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/858#-NAJ47he9Vu9zoVzmMpt:-NAK98kqCTRzHbZBUXwp:b-896fix) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@oshogbo Please check why ASan failed.
</blockquote></details>

Done.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/858#-NAJ4jxf1wrE7VP0wbSD:-NAK997yDX-EMIEXtft_:b-896fix) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add `Fixes #761` in PR description.
</blockquote></details>

Done.

___
___
*[`Documentation/manifest-syntax.rst` line 143 at r1](https://reviewable.io/reviews/gramineproject/gramine/858#-NAJ0N-0DwK7zZqOX2ua:-NAJQoC140azYcakXvJR:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/4c18b890207d8779c695224609e468d74baf7616/Documentation/manifest-syntax.rst#L143)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`are mutually exclusive` -> `options are mutually exclusive`
</blockquote></details>

Done.
___
*[`libos/test/regression/argv.manifest.template` line 13 at r1](https://reviewable.io/reviews/gramineproject/gramine/858#-NAJ0kuz3M4ShlsILYSp:-NAJQvOG4EOYazh2oLmd:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/4c18b890207d8779c695224609e468d74baf7616/libos/test/regression/argv.manifest.template#L13)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add a comment `# note the trailing space (app should see this trailing space in its argv[5])`
</blockquote></details>

Done.
___
*[`libos/test/regression/argv.manifest.template` line 26 at r1](https://reviewable.io/reviews/gramineproject/gramine/858#-NAJ0d652mkk-k2N4XYO:-NAJQxIdCNVn1CngpEiG:bw4f7n6) ([raw file](https://github.com/gramineproject/gramine/blob/4c18b890207d8779c695224609e468d74baf7616/libos/test/regression/argv.manifest.template#L26)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What is this? Looks redundant (and wrong)
</blockquote></details>

It was copied by mistake from other test (`argv_from_file.manifest.template`).
___
*[`pal/src/pal_main.c` line 423 at r1](https://reviewable.io/reviews/gramineproject/gramine/858#-NAJ1RJG6W99ep2K2n9y:-NAJRL8k2S12sc89pqBQ:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/4c18b890207d8779c695224609e468d74baf7616/pal/src/pal_main.c#L423)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please wrap these 2 lines into 1 line
</blockquote></details>

Done.
___
*[`pal/src/pal_main.c` line 432 at r1](https://reviewable.io/reviews/gramineproject/gramine/858#-NAJ2Kpe-gFy21lnvyWQ:-NAJRQ5w7SLgebItTU4w:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/4c18b890207d8779c695224609e468d74baf7616/pal/src/pal_main.c#L432)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Actually, what does it mean to specify `loader.argv = [ ]`? I don't think we want to support no-arguments invocations.

So I would add:
```
if (argv_option_cnt == 0)
    INIT_FAIL_MANIFEST("'loader.argv' has no arguments, this is unsupported");
```

If we won't have smth like this, I think Gramine will fail somewhere below if the manifest has `loader.argv = [ ]`?
</blockquote></details>

Done.
___
*[`pal/src/pal_main.c` line 448 at r1](https://reviewable.io/reviews/gramineproject/gramine/858#-NAJ1ujM1VQ8GP9cRRCI:-NAJRUFR--ISYgcwSvws:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/4c18b890207d8779c695224609e468d74baf7616/pal/src/pal_main.c#L448)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please wrap these 2 lines into 1 line
</blockquote></details>

Done.
___
*[`pal/src/pal_main.c` line 453 at r1](https://reviewable.io/reviews/gramineproject/gramine/858#-NAJ3LRh3ff_O1SXaw4W:-NAJPEmd0GqtTmuCQyjc:bh4a2us) ([raw file](https://github.com/gramineproject/gramine/blob/3d23397e242786db9bbf903f0a803d5f7376ad47/pal/src/pal_main.c#L453)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why did you remove this info message? I think it's useful so that users know that their accidental incorrect invocation like `gramine-sgx argv blablabla ...` discards this `blablabla ...` stuff in favor of hard-coded argv from the manifest.

I would print this info message for both `argv_option_cnt > 0` and `argv_src_file`.
</blockquote></details>

I didn't think this is useful, as I assumed that if somebody specified these values in manifest or provide the file with them.
But I won't argue here.

Done.
___
*[`pal/src/pal_main.c` line 475 at r1](https://reviewable.io/reviews/gramineproject/gramine/858#-NAJ4U8G55OEpoPOUBm-:-NAJOxCaAjKtBkjHUMLp:bbckfay) ([raw file](https://github.com/gramineproject/gramine/blob/4c18b890207d8779c695224609e468d74baf7616/pal/src/pal_main.c#L475)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Is this safe to do? Your `new_args` contain pointers somewhere into the parsed TOML manifest object. I would feel safer if we would perform copies of those strings.
</blockquote></details>

According to toml (https://github.com/cktan/tomlc99):
```
** IMPORTANT: if the accessed value is a string or a timestamp, you must call free(datum.u.s) or free(datum.u.ts) respectively after usage. **
```
So from my understanding it allocates new buffers, and we are responsible for freeing them, so we can safely use them here.
___
*[`pal/src/pal_main.c` line 502 at r1](https://reviewable.io/reviews/gramineproject/gramine/858#-NAJ3yxNDdWm9sLWz7nG:-NAJRjpl2qlqSIvzo8q9:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/4c18b890207d8779c695224609e468d74baf7616/pal/src/pal_main.c#L502)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please re-wrap
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-25 13:20 UTC, oshogbo reviewed
Jenkins, retest Jenkins-SGX-20.04 please

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/858#-:-NAK9Ecl4VxX_bJ6qG3T:b4tamj0)* status: 3 of 6 files reviewed, 11 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2022-08-25 13:21 UTC, oshogbo commented
Jenkins, retest Jenkins-SGX-20.04 please

2022-08-26 09:01 UTC, dimakuv requested changes
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/858)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/858#-NAJ47he9Vu9zoVzmMpt:-NAOLd_q58pbQUzA-vAV:b1ptpbu) (no related file):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

What was the reason for the failure? Because you forgot to add the finalizing `NULL` arg in the case of `loader.argv`?

___
___
*[`pal/src/pal_main.c` line 475 at r1](https://reviewable.io/reviews/gramineproject/gramine/858#-NAJ4U8G55OEpoPOUBm-:-NAOMD-MB0BCA1c0TtNs:b-eb0dj0) ([raw file](https://github.com/gramineproject/gramine/blob/4c18b890207d8779c695224609e468d74baf7616/pal/src/pal_main.c#L475)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

According to toml (https://github.com/cktan/tomlc99):
```
** IMPORTANT: if the accessed value is a string or a timestamp, you must call free(datum.u.s) or free(datum.u.ts) respectively after usage. **
```
So from my understanding it allocates new buffers, and we are responsible for freeing them, so we can safely use them here.
</blockquote></details>

Ah, you are right, perfect.


<!-- Sent from Reviewable.io -->

2022-08-29 13:13 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/858)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/858#-NAJ47he9Vu9zoVzmMpt:-NAdiwQq6JhsU6lYpsm1:b-5jew67) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What was the reason for the failure? Because you forgot to add the finalizing `NULL` arg in the case of `loader.argv`?
</blockquote></details>

Yes, thats the case. We expect the argv to be ended with NULL, this is also defined by POSIX so its my bad.

___


<!-- Sent from Reviewable.io -->

2022-08-29 13:42 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/858)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2022-08-29 16:40 UTC, boryspoplawski requested changes
> Reviewed 3 of 6 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/858)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @oshogbo)

___
*[`Documentation/manifest-syntax.rst` line 119 at r2](https://reviewable.io/reviews/gramineproject/gramine/858#-NAeInksBc97tHpeWAy0:-NAeInksBc97tHpeWAy1:b-m004ba) ([raw file](https://github.com/gramineproject/gramine/blob/2b2af06a6608a583b89bc0f0463deee2db28acf7/Documentation/manifest-syntax.rst#L119)):*
> ```reStructuredText
> ::
> 
>    loader.argv = ["arg0", "arg1", "arg2"]
> ```

Maybe something like this? Just to indicate the list could have different length.



_Suggestion:_
```reStructuredText
["arg0", "arg1", "arg2", ...]
```
___
*[`libos/test/regression/argv.manifest.template` line 1 at r2](https://reviewable.io/reviews/gramineproject/gramine/858#-NAeKMkU6GvD_e5Jg8Df:-NAeKMkU6GvD_e5Jg8Dg:b-aholer) ([raw file](https://github.com/gramineproject/gramine/blob/2b2af06a6608a583b89bc0f0463deee2db28acf7/libos/test/regression/argv.manifest.template#L1)):*
> ```
> {% set entrypoint = "bootstrap" -%}
> ```

Maybe let's name this test `argv_from_manifest` to be uniform with the other (`argv_from_file`) and indicate what this test is actually about?
___
*[`libos/test/regression/test_libos.py` line 174 at r2](https://reviewable.io/reviews/gramineproject/gramine/858#-NAeJPkC57mv1wZcs6fe:-NAeJPkC57mv1wZcs6ff:bqud1h5) ([raw file](https://github.com/gramineproject/gramine/blob/2b2af06a6608a583b89bc0f0463deee2db28acf7/libos/test/regression/test_libos.py#L174)):*
> ```Python
> 
>     def test_111_argv(self):
>         args = ['bootstrap', 'THIS', 'SHOULD GO', 'TO', 'THE', 'APP ']
> ```

Please change the name to something else, at first I thought you pass this to app directly. Maybe something like `args_in_manifest` or `expected_argv`?
___
*[`libos/test/regression/test_libos.py` line 176 at r2](https://reviewable.io/reviews/gramineproject/gramine/858#-NAeJie4Bfph2Q4KoYnY:-NAeJie4Bfph2Q4KoYnZ:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/2b2af06a6608a583b89bc0f0463deee2db28acf7/libos/test/regression/test_libos.py#L176)):*
> ```Python
>         args = ['bootstrap', 'THIS', 'SHOULD GO', 'TO', 'THE', 'APP ']
>         stdout, _ = self.run_binary(['argv'])
>         self.assertIn('# of arguments: %d\n' % len(args), stdout)
> ```





_Suggestion:_
```Python
f'# of arguments: {len(args)}\n'
```
___
*[`libos/test/regression/test_libos.py` line 178 at r2](https://reviewable.io/reviews/gramineproject/gramine/858#-NAeJpIK1k_9guNaaxUf:-NAeJpILAaIRSvdAu7sJ:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/2b2af06a6608a583b89bc0f0463deee2db28acf7/libos/test/regression/test_libos.py#L178)):*
> ```Python
>         self.assertIn('# of arguments: %d\n' % len(args), stdout)
>         for i, arg in enumerate(args):
>             self.assertIn('argv[%d] = %s\n' % (i, arg), stdout)
> ```





_Suggestion:_
```Python
f'argv[{i}] = {arg}\n'
```
___
*[`pal/src/pal_main.c` line 426 at r2](https://reviewable.io/reviews/gramineproject/gramine/858#-NAeNfa60TjvZVTV-hu-:-NAeNfa60TjvZVTV-hu0:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/2b2af06a6608a583b89bc0f0463deee2db28acf7/pal/src/pal_main.c#L426)):*
> ```C
>         INIT_FAIL_MANIFEST("Cannot parse 'loader.argv_src_file'");
> 
>     ssize_t argv_option_cnt = 0;
> ```





_Suggestion:_
```C
size_t
```
___
*[`pal/src/pal_main.c` line 427 at r2](https://reviewable.io/reviews/gramineproject/gramine/858#-NAeNVwdACSNiLdiDYE_:-NAeNVwdACSNiLdiDYEa:b-7v94o7) ([raw file](https://github.com/gramineproject/gramine/blob/2b2af06a6608a583b89bc0f0463deee2db28acf7/pal/src/pal_main.c#L427)):*
> ```C
> 
>     ssize_t argv_option_cnt = 0;
>     toml_array_t* argv_option = toml_array_in(manifest_loader, "argv");
> ```

Not blocking, but I have another idea for this variable name: `manifest_argv`. Up to you which one is better.
___
*[`pal/src/pal_main.c` line 429 at r2](https://reviewable.io/reviews/gramineproject/gramine/858#-NAeNicUE82fgSe6y6dX:-NAeNicUE82fgSe6y6dY:buj0l7j) ([raw file](https://github.com/gramineproject/gramine/blob/2b2af06a6608a583b89bc0f0463deee2db28acf7/pal/src/pal_main.c#L429)):*
> ```C
>     toml_array_t* argv_option = toml_array_in(manifest_loader, "argv");
>     if (argv_option) {
>         argv_option_cnt = toml_array_nelem(argv_option);
> ```

Please read this to temporary variable (of correct type  - `int`) and then overwrite the outer scope one, after verifying.
___
*[`pal/src/pal_main.c` line 432 at r2](https://reviewable.io/reviews/gramineproject/gramine/858#-NAeOA7XCT3YniTC8WA0:-NAeOA7XCT3YniTC8WA1:b-rt4vvk) ([raw file](https://github.com/gramineproject/gramine/blob/2b2af06a6608a583b89bc0f0463deee2db28acf7/pal/src/pal_main.c#L432)):*
> ```C
>         if (argv_option_cnt < 0)
>             INIT_FAIL_MANIFEST("Cannot parse 'loader.argv'");
>         if (argv_option_cnt == 0)
> ```

Well, I don't see a reason for not supporting this. Will Gramine fail then? I guess it will, so not blocking. If so, maybe add a TODO to remove this one we support `argc == 0`?
___
*[`pal/src/pal_main.c` line 436 at r2](https://reviewable.io/reviews/gramineproject/gramine/858#-NAeOW66CDn9SGCtNTPC:-NAeOW66CDn9SGCtNTPD:bwkfnmr) ([raw file](https://github.com/gramineproject/gramine/blob/2b2af06a6608a583b89bc0f0463deee2db28acf7/pal/src/pal_main.c#L436)):*
> ```C
>     }
> 
>     if ((use_cmdline_argv ? 1 : 0) + (argv_option_cnt > 0 ? 1 : 0) + (argv_src_file ? 1 : 0) > 1) {
> ```

1. Shouldn't this be `!= 1`? Update: ok, we allow for `0` (which means `argv = { entrypoint }`).
2. I think the first two `? 1 : 0` are not needed, since these are all bool values.
___
*[`pal/src/pal_main.c` line 457 at r2](https://reviewable.io/reviews/gramineproject/gramine/858#-NAePuEV3KI1NdwO6jln:-NAePuEV3KI1NdwO6jlo:blme5gb) ([raw file](https://github.com/gramineproject/gramine/blob/2b2af06a6608a583b89bc0f0463deee2db28acf7/pal/src/pal_main.c#L457)):*
> ```C
>     assert(argv0_override);
> 
>     if (use_cmdline_argv) {
> ```

Shouldn't this whole `if` be under another `if (!parent_process)`? We don't have to use all of these options then. Actually, I think the whole part about parsing arguments doesn't need to be done in child process - the question is whether rest of the code can handle this (`arguments = NULL` most likely no, but maybe `arguments = {  NULL }`?)
Not blocking this is mostly unrelated to this PR.
___
*[`pal/src/pal_main.c` line 476 at r2](https://reviewable.io/reviews/gramineproject/gramine/858#-NAeRuPj81zQwaIHlkWD:-NAeRuPj81zQwaIHlkWE:b-pb8480) ([raw file](https://github.com/gramineproject/gramine/blob/2b2af06a6608a583b89bc0f0463deee2db28acf7/pal/src/pal_main.c#L476)):*
> ```C
>         }
> 
>         for (ssize_t i = 0; i < argv_option_cnt; i++) {
> ```

I know that `toml_string_at` requires `int`, but using `ssize_t` doesn't help with anything.



_Suggestion:_
```C
size_t
```


<!-- Sent from Reviewable.io -->

2022-08-31 10:11 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/858)* status: 0 of 6 files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[`Documentation/manifest-syntax.rst` line 119 at r2](https://reviewable.io/reviews/gramineproject/gramine/858#-NAeInksBc97tHpeWAy0:-NAnIaAA1ARbIph24xAh:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/2b2af06a6608a583b89bc0f0463deee2db28acf7/Documentation/manifest-syntax.rst#L119)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Maybe something like this? Just to indicate the list could have different length.
</blockquote></details>

Done.
___
*[`libos/test/regression/test_libos.py` line 174 at r2](https://reviewable.io/reviews/gramineproject/gramine/858#-NAeJPkC57mv1wZcs6fe:-NAnIw9z3lRU72DTAbVY:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/2b2af06a6608a583b89bc0f0463deee2db28acf7/libos/test/regression/test_libos.py#L174)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please change the name to something else, at first I thought you pass this to app directly. Maybe something like `args_in_manifest` or `expected_argv`?
</blockquote></details>

Done.
___
*[`libos/test/regression/test_libos.py` line 176 at r2](https://reviewable.io/reviews/gramineproject/gramine/858#-NAeJie4Bfph2Q4KoYnY:-NAnJ4BR2ZuOljirF-eV:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/2b2af06a6608a583b89bc0f0463deee2db28acf7/libos/test/regression/test_libos.py#L176)):*
> ```Python
>         args = ['bootstrap', 'THIS', 'SHOULD GO', 'TO', 'THE', 'APP ']
>         stdout, _ = self.run_binary(['argv'])
>         self.assertIn('# of arguments: %d\n' % len(args), stdout)
> ```

Done.
___
*[`libos/test/regression/test_libos.py` line 178 at r2](https://reviewable.io/reviews/gramineproject/gramine/858#-NAeJpIK1k_9guNaaxUf:-NAnJDgs5l0ttoCfW4si:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/2b2af06a6608a583b89bc0f0463deee2db28acf7/libos/test/regression/test_libos.py#L178)):*
> ```Python
>         self.assertIn('# of arguments: %d\n' % len(args), stdout)
>         for i, arg in enumerate(args):
>             self.assertIn('argv[%d] = %s\n' % (i, arg), stdout)
> ```

Done.
___
*[`pal/src/pal_main.c` line 426 at r2](https://reviewable.io/reviews/gramineproject/gramine/858#-NAeNfa60TjvZVTV-hu-:-NAnLNVO6qcK7KCPv431:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/2b2af06a6608a583b89bc0f0463deee2db28acf7/pal/src/pal_main.c#L426)):*
> ```C
>         INIT_FAIL_MANIFEST("Cannot parse 'loader.argv_src_file'");
> 
>     ssize_t argv_option_cnt = 0;
> ```

Done.
___
*[`pal/src/pal_main.c` line 427 at r2](https://reviewable.io/reviews/gramineproject/gramine/858#-NAeNVwdACSNiLdiDYE_:-NAnNZC849qwiHIYYc-Y:b-f1kj52) ([raw file](https://github.com/gramineproject/gramine/blob/2b2af06a6608a583b89bc0f0463deee2db28acf7/pal/src/pal_main.c#L427)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Not blocking, but I have another idea for this variable name: `manifest_argv`. Up to you which one is better.
</blockquote></details>

I like this name. Done.
___
*[`pal/src/pal_main.c` line 429 at r2](https://reviewable.io/reviews/gramineproject/gramine/858#-NAeNicUE82fgSe6y6dX:-NAnKPr97iKuJPm3Ug_P:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/2b2af06a6608a583b89bc0f0463deee2db28acf7/pal/src/pal_main.c#L429)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please read this to temporary variable (of correct type  - `int`) and then overwrite the outer scope one, after verifying.
</blockquote></details>

Done.
___
*[`pal/src/pal_main.c` line 436 at r2](https://reviewable.io/reviews/gramineproject/gramine/858#-NAeOW66CDn9SGCtNTPC:-NAnKRrJ2pXvn62J2BxC:bo44ryr) ([raw file](https://github.com/gramineproject/gramine/blob/2b2af06a6608a583b89bc0f0463deee2db28acf7/pal/src/pal_main.c#L436)):*
> I think the first two ? 1 : 0 are not needed, since these are all bool values.

They are boolean, I just figure out this will be the most readable approach, and you don't need to thing why we are doing it that way.
Dunno if you prefer indirect cast its fine with me.
___
*[`pal/src/pal_main.c` line 476 at r2](https://reviewable.io/reviews/gramineproject/gramine/858#-NAeRuPj81zQwaIHlkWD:-NAnKvNoAdFH0R4m1g7g:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/2b2af06a6608a583b89bc0f0463deee2db28acf7/pal/src/pal_main.c#L476)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I know that `toml_string_at` requires `int`, but using `ssize_t` doesn't help with anything.
</blockquote></details>

Done.
___
*[`libos/test/regression/argv.manifest.template` line 1 at r2](https://reviewable.io/reviews/gramineproject/gramine/858#-NAeKMkU6GvD_e5Jg8Df:-NAnIoFb2qKWg6P1Hfal:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/2b2af06a6608a583b89bc0f0463deee2db28acf7/libos/test/regression/argv.manifest.template#L1)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Maybe let's name this test `argv_from_manifest` to be uniform with the other (`argv_from_file`) and indicate what this test is actually about?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-31 11:07 UTC, dimakuv submitted a review, later dismissed
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/858)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[`pal/src/pal_main.c` line 436 at r2](https://reviewable.io/reviews/gramineproject/gramine/858#-NAeOW66CDn9SGCtNTPC:-NAnZwnS3IZyTzoR43aG:bgjw1wf) ([raw file](https://github.com/gramineproject/gramine/blob/2b2af06a6608a583b89bc0f0463deee2db28acf7/pal/src/pal_main.c#L436)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

> I think the first two ? 1 : 0 are not needed, since these are all bool values.

They are boolean, I just figure out this will be the most readable approach, and you don't need to thing why we are doing it that way.
Dunno if you prefer indirect cast its fine with me.
</blockquote></details>

I would keep it as is. Implicit cast of Bool values is not developer-friendly.
___
*[`pal/src/pal_main.c` line 457 at r2](https://reviewable.io/reviews/gramineproject/gramine/858#-NAePuEV3KI1NdwO6jln:-NAn_EX-4B0IuHBjkrMr:b-ttt6f5) ([raw file](https://github.com/gramineproject/gramine/blob/2b2af06a6608a583b89bc0f0463deee2db28acf7/pal/src/pal_main.c#L457)):*
>  Actually, I think the whole part about parsing arguments doesn't need to be done in child process 

Yes, I also think that the PAL initialization code should be re-written with two clearly separated code paths: one for main process, another for child processes. In some future PR...


<!-- Sent from Reviewable.io -->

2022-08-31 12:55 UTC, boryspoplawski submitted a review, later dismissed
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/858)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2022-08-31 13:55 UTC, boryspoplawski approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/858)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2022-08-31 14:10 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/858)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-08-31 15:08 UTC, merged