[tests] Fix retval checks
gramineproject/gramine pull request #859
Opened 2022-08-24 17:57 UTC by oshogbo

## Description of the changes 
All these functions use libc:
```
#0  __GI___libc_read (fd=3, buf=0x6c323d475010, nbytes=1048576) at ../sysdeps/unix/sysv/linux/read.c:25
#1  0x00006c323d8b1951 in read_fd (path=0x6c323d8f6ff4 "tmp/a", fd=3, buffer=0x6c323d475010, size=1048576) at ../libos/test/fs/common.c:32
#2  0x00006c323d8b1557 in read_write (file_path=0x6c323d8f6ff4 "tmp/a") at ../libos/test/fs/read_write.c:15
#3  0x00006c323d8b1741 in main (argc=3, argv=0x6c323d8f6ec8) at ../libos/test/fs/read_write.c:45
```

The return value for read(2)/write(2)/sendfile(2) should be -1 and errno should be set
to indicate the type of error.

Beside that:
- sendfile(2) should check if it wasn't interrupted,
- read(2) and write(2) aren't used with non-blocking fds, but because
  we are here, let's also verify the EAGAIN error.

## How to test this PR? 

```
gramine-test -C libos/test/fs pytest
gramine-test --sgx -C libos/test/fs pytest
```

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/859)

2022-08-24 18:29 UTC, boryspoplawski approved these changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/859)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @oshogbo)

___
*[`-- commits` line 6 at r1](https://reviewable.io/reviews/gramineproject/gramine/859#-NAG1rWx57tECYOjL4lI):*




_Suggestion:_
```
  All these functions use libc. In case of error the return value for
  read(2)/write(2)/sendfile(2) is `-1` and errno is set to indicate the
  type of error.
```
___
*[`-- commits` line 9 at r1](https://reviewable.io/reviews/gramineproject/gramine/859#-NAG5aRuBk4hPETynFne):*
It's not `sendfile`, but the caller, that checks it.
___
*[`-- commits` line 11 at r1](https://reviewable.io/reviews/gramineproject/gramine/859#-NAG6-niB5-QqSjt5QL6):*
I would have hard time understanding this sentence without looking at the implementation. What does it mean to "verify the EAGAIN error"? Maybe
```
- we do not use read(2) and write(2) with non-blocking fds, but it wouldn't
  hurt to loop on EAGAIN.
```
or something


<!-- Sent from Reviewable.io -->

2022-08-24 18:46 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/859)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[`-- commits` line 6 at r1](https://reviewable.io/reviews/gramineproject/gramine/859#-NAG1rWx57tECYOjL4lI):*
Done.
___
*[`-- commits` line 9 at r1](https://reviewable.io/reviews/gramineproject/gramine/859#-NAG5aRuBk4hPETynFne):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

It's not `sendfile`, but the caller, that checks it.
</blockquote></details>

Done.



_Code quote:_
```
  Beside that:
  - sendfile(2) should check if it wasn't interrupted,
```
___
*[`-- commits` line 11 at r1](https://reviewable.io/reviews/gramineproject/gramine/859#-NAG6-niB5-QqSjt5QL6):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I would have hard time understanding this sentence without looking at the implementation. What does it mean to "verify the EAGAIN error"? Maybe
```
- we do not use read(2) and write(2) with non-blocking fds, but it wouldn't
  hurt to loop on EAGAIN.
```
or something
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-24 20:15 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/859)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[`-- commits` line 16 at r2](https://reviewable.io/reviews/gramineproject/gramine/859#-NAGUbRY9IlJbtrhfMpT):*
This should be squash, leaving comment just to not lose that.


<!-- Sent from Reviewable.io -->

2022-08-24 21:44 UTC, boryspoplawski approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/859)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @oshogbo)



<!-- Sent from Reviewable.io -->

2022-08-25 07:38 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/859)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @oshogbo)

___
*[`-- commits` line 4 at r2](https://reviewable.io/reviews/gramineproject/gramine/859#-NAIv1rP1yF2Ag5nEWS7):*
Which `these`? I suggest `All helper functions for FS tests use libc.`


<!-- Sent from Reviewable.io -->

2022-08-25 10:50 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/859)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "squash! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[`-- commits` line 4 at r2](https://reviewable.io/reviews/gramineproject/gramine/859#-NAIv1rP1yF2Ag5nEWS7):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Which `these`? I suggest `All helper functions for FS tests use libc.`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-26 08:34 UTC, dimakuv submitted a review, later dismissed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/859)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "squash! " found in commit messages' one-liners (waiting on @boryspoplawski)



<!-- Sent from Reviewable.io -->

2022-08-26 11:10 UTC, boryspoplawski approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/859)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "squash! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2022-08-26 14:15 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/859)* status: all files reviewed, all discussions resolved, "squash! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2022-08-29 09:38 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/859)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2022-08-29 09:40 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/859)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2022-08-29 11:36 UTC, boryspoplawski approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/859)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-08-29 11:40 UTC, merged