[PAL] Remove `PAL_OPTION_CLOEXEC` flag
gramineproject/gramine pull request #866
Opened 2022-08-29 15:28 UTC by boryspoplawski

## Description of the changes 
This flag was used to control `CLOEXEC` flag of host OS fd, and as such, was Linux specific. It was also not really needed - Linux and Linux SGX PALs always set it on host fd anyway.
This commit also adds all missing `CLOEXEC` flag usages in Linux and Linux SGX PALs.

Fixes #864

## How to test this PR? 
Use test at #864. It was not added to repo as it's not really suitable to be run in CI.

2022-08-29 15:52 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/866)* status: 0 of 27 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/866#-NAeHuupAqdbu4l9wsi8:-NAeHuupAqdbu4l9wsi9:bhvzqf3) (no related file):*
I think it would be worth adding a test to CI, but I have no good idea on how to do that so it doesn't take too much time.
Maybe `ulimit` on host + some well calculated loop forking processes? Still, that would take some time on SGX PAL.

Well, I'll do that.

___


<!-- Sent from Reviewable.io -->

2022-08-29 17:32 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/866)* status: 0 of 30 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/866#-NAeHuupAqdbu4l9wsi8:-NAeeJ8TBM4lyOKKki2v:b7mgdod) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I think it would be worth adding a test to CI, but I have no good idea on how to do that so it doesn't take too much time.
Maybe `ulimit` on host + some well calculated loop forking processes? Still, that would take some time on SGX PAL.

Well, I'll do that.
</blockquote></details>

Ok, added a test to CI.

___


<!-- Sent from Reviewable.io -->

2022-08-30 07:00 UTC, dimakuv requested changes
> Reviewed 27 of 27 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/866)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[`-- commits` line 8 at r2](https://reviewable.io/reviews/gramineproject/gramine/866#-NAhTEaF55Aa7LXIJx7Y):*
Don't you want to add that this fixes FD leaks in nested-fork scenarios? This sounds like an important phrase to add here, for historial reasons.

Also, could we make it properly separate paragraphs? It deserves its own para (with an empty line in between).
___
*[`libos/test/regression/fdleak.c` line 46 at r2](https://reviewable.io/reviews/gramineproject/gramine/866#-NAhUrEo3UxRhd_XpZnj:-NAhUrEo3UxRhd_XpZnk:b-85p8kc) ([raw file](https://github.com/gramineproject/gramine/blob/ff2eabaf92f7c4e3de31f071d628f7e44b6edaaf/libos/test/regression/fdleak.c#L46)):*
> ```C
>                 /* Parent just exits. */
>                 exit(0);
>             }
> ```

Can you maybe add a comment after this `if (p != 0) { }`:
```
/* child continues the loop and will spawn another child (deeply nested fork) */
```

It took me a couple minutes to understand what happens here
___
*[`libos/test/regression/fdleak.c` line 62 at r2](https://reviewable.io/reviews/gramineproject/gramine/866#-NAhVZ9lBx3KjAzI6-06:-NAhVZ9lBx3KjAzI6-07:borer8y) ([raw file](https://github.com/gramineproject/gramine/blob/ff2eabaf92f7c4e3de31f071d628f7e44b6edaaf/libos/test/regression/fdleak.c#L62)):*
> ```C
>         errx(1, "confirmation message too short: %zd", ret);
>     }
>     CHECK(wait(NULL));
> ```

How are we guaranteed that at this point other (nested) children are finished? Or we just don't care whether they performed `exit(0)` already?
___
*[`libos/test/regression/fdleak.c` line 71 at r2](https://reviewable.io/reviews/gramineproject/gramine/866#-NAhTvUD5BfJl-GfjYqt:-NAhTvUD5BfJl-GfjYqu:b-ccczzj) ([raw file](https://github.com/gramineproject/gramine/blob/ff2eabaf92f7c4e3de31f071d628f7e44b6edaaf/libos/test/regression/fdleak.c#L71)):*
> ```C
> int main(int argc, char** argv) {
>     if (argc != 1) {
>         errx(1, "invalid argc: %d", argc);
> ```

Maybe print a message that says `test expects argc == 1 (received: %d)`?
___
*[`libos/test/regression/test_libos.py` line 1015 at r2](https://reviewable.io/reviews/gramineproject/gramine/866#-NAhWKiZ6KcsH6wcSEDc:-NAhWKiZ6KcsH6wcSEDd:b-hu0jqj) ([raw file](https://github.com/gramineproject/gramine/blob/ff2eabaf92f7c4e3de31f071d628f7e44b6edaaf/libos/test/regression/test_libos.py#L1015)):*
> ```Python
> 
>     def test_030_fdleak(self):
>         stdout, _ = self.run_binary(['fdleak'], timeout=10, open_fds_limit=50)
> ```

Oh, this `open_fds_limit` trick is cool!

But maybe we should add a comment explaining why we have such a high limit? (That Gramine internally creates several more FDs, so we can't use a tight bound like ~15).
___
*[`libos/test/regression/test_libos.py` line 1015 at r2](https://reviewable.io/reviews/gramineproject/gramine/866#-NAhWbrX8s-LTDJvOpay:-NAhWbrX8s-LTDJvOpaz:b78mvwk) ([raw file](https://github.com/gramineproject/gramine/blob/ff2eabaf92f7c4e3de31f071d628f7e44b6edaaf/libos/test/regression/test_libos.py#L1015)):*
> ```Python
> 
>     def test_030_fdleak(self):
>         stdout, _ = self.run_binary(['fdleak'], timeout=10, open_fds_limit=50)
> ```

How can the timeout be so small in the SGX case? You're creating 11 enclaves! Something feels wrong here.
___
*[`pal/src/host/linux/pal_memory.c` line 93 at r2](https://reviewable.io/reviews/gramineproject/gramine/866#-NAhXH81DL-tswd2FlEC:-NAhXH81DL-tswd2FlED:bn9tp7h) ([raw file](https://github.com/gramineproject/gramine/blob/ff2eabaf92f7c4e3de31f071d628f7e44b6edaaf/pal/src/host/linux/pal_memory.c#L93)):*
> ```C
> 
> static int read_proc_meminfo(const char* key, unsigned long* val) {
>     int fd = DO_SYSCALL(open, "/proc/meminfo", O_RDONLY | O_CLOEXEC, 0);
> ```

Why would it matter here?
___
*[`pal/src/host/linux/pal_streams.c` line 253 at r2](https://reviewable.io/reviews/gramineproject/gramine/866#-NAhXTsw9ng55mHMZ8tb:-NAhXTsw9ng55mHMZ8tc:b9rk2mw) ([raw file](https://github.com/gramineproject/gramine/blob/ae6cad8a5758acaf5f4fe8073234718c57cfd08f/pal/src/host/linux/pal_streams.c#L253)):*
> ```C
>         /* This check is to shield from a Iago attack. We know that sendmsg() in _PalSendHandle()
>          * transfers the message atomically, and that our recvmsg() receives it atomically. So
>          * the only valid values for ret must be zero or the size of the header. */
> ```

That's just not true because `ret == 0` should never happen?


<!-- Sent from Reviewable.io -->

2022-08-30 15:12 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/866)* status: 28 of 30 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`-- commits` line 8 at r2](https://reviewable.io/reviews/gramineproject/gramine/866#-NAhTEaF55Aa7LXIJx7Y):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Don't you want to add that this fixes FD leaks in nested-fork scenarios? This sounds like an important phrase to add here, for historial reasons.

Also, could we make it properly separate paragraphs? It deserves its own para (with an empty line in between).
</blockquote></details>

Something like:
```
[PAL] Remove `PAL_OPTION_CLOEXEC` flag                                   
                                                                         
This flag was used to control `CLOEXEC` flag of host OS fd and, as such, 
was Linux specific. It was also not really needed - Linux and Linux SGX  
PALs always set it on host fd anyway.                                    
                                                                         
This commit also adds all missing `CLOEXEC` flag usages in Linux and     
Linux SGX PALs, which fixes multiple fd leaks (all Linux PALs do `fork`  
+ `execve` when spawning a new process, which leaks fds without          
`CLOEXEC` flag).
```
?
___
*[`libos/test/regression/fdleak.c` line 46 at r2](https://reviewable.io/reviews/gramineproject/gramine/866#-NAhUrEo3UxRhd_XpZnj:-NAixS_XDnmSi_5Vn4qa:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/ff2eabaf92f7c4e3de31f071d628f7e44b6edaaf/libos/test/regression/fdleak.c#L46)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can you maybe add a comment after this `if (p != 0) { }`:
```
/* child continues the loop and will spawn another child (deeply nested fork) */
```

It took me a couple minutes to understand what happens here
</blockquote></details>

Done.
___
*[`libos/test/regression/fdleak.c` line 62 at r2](https://reviewable.io/reviews/gramineproject/gramine/866#-NAhVZ9lBx3KjAzI6-06:-NAixWEaA-xarq6TPpiv:bs5b8so) ([raw file](https://github.com/gramineproject/gramine/blob/ff2eabaf92f7c4e3de31f071d628f7e44b6edaaf/libos/test/regression/fdleak.c#L62)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

How are we guaranteed that at this point other (nested) children are finished? Or we just don't care whether they performed `exit(0)` already?
</blockquote></details>

We are not, but why would we care? There is no way of doing this without `PR_SET_CHILD_SUBREAPER`, which is not supported in Gramine. All we are is that we do enough nested forks, which we know happened, because we successfully read data from the pipe.
___
*[`libos/test/regression/fdleak.c` line 71 at r2](https://reviewable.io/reviews/gramineproject/gramine/866#-NAhTvUD5BfJl-GfjYqt:-NAiy6Zs4IqpklfD7rGF:b-iufoh4) ([raw file](https://github.com/gramineproject/gramine/blob/ff2eabaf92f7c4e3de31f071d628f7e44b6edaaf/libos/test/regression/fdleak.c#L71)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Maybe print a message that says `test expects argc == 1 (received: %d)`?
</blockquote></details>

If you want I can do this, but this is really just a sanity check...
___
*[`libos/test/regression/test_libos.py` line 1015 at r2](https://reviewable.io/reviews/gramineproject/gramine/866#-NAhWKiZ6KcsH6wcSEDc:-NAiylwe1JXUiRKegSf0:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/ff2eabaf92f7c4e3de31f071d628f7e44b6edaaf/libos/test/regression/test_libos.py#L1015)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Oh, this `open_fds_limit` trick is cool!

But maybe we should add a comment explaining why we have such a high limit? (That Gramine internally creates several more FDs, so we can't use a tight bound like ~15).
</blockquote></details>

Done.
___
*[`libos/test/regression/test_libos.py` line 1015 at r2](https://reviewable.io/reviews/gramineproject/gramine/866#-NAhWbrX8s-LTDJvOpay:-NAizXeJDN7FP9XT96jM:baid7bq) ([raw file](https://github.com/gramineproject/gramine/blob/ff2eabaf92f7c4e3de31f071d628f7e44b6edaaf/libos/test/regression/test_libos.py#L1015)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

How can the timeout be so small in the SGX case? You're creating 11 enclaves! Something feels wrong here.
</blockquote></details>

This is a very good question - this test takes 12s in debug mode on a decent (but not beefy) machine...
Update: ok, we take `max(timeout, DEFAULT_TIMEOUT)`, which is 20s for SGX.

I've increased timeout to 40, should be enough even for NUCs
___
*[`pal/src/host/linux/pal_memory.c` line 93 at r2](https://reviewable.io/reviews/gramineproject/gramine/866#-NAhXH81DL-tswd2FlEC:-NAjH4fqDDxjbxSe2vRT:bti14xy) ([raw file](https://github.com/gramineproject/gramine/blob/ff2eabaf92f7c4e3de31f071d628f7e44b6edaaf/pal/src/host/linux/pal_memory.c#L93)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why would it matter here?
</blockquote></details>

Why not? We don't want this to stay open after execve, so why would we state otherwise?
Also keep in mind that there always could be a concurrent thread doing fork at any moment, so the fact that a function always closes the fd is not enough.
___
*[`pal/src/host/linux/pal_streams.c` line 253 at r2](https://reviewable.io/reviews/gramineproject/gramine/866#-NAhXTsw9ng55mHMZ8tb:-NAjHPyT-4Nmti4QEeHe:b4mm98h) ([raw file](https://github.com/gramineproject/gramine/blob/ae6cad8a5758acaf5f4fe8073234718c57cfd08f/pal/src/host/linux/pal_streams.c#L253)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

That's just not true because `ret == 0` should never happen?
</blockquote></details>

This comment made no sense.
1) `ret == 0` could happen and we just return an error of our choice. I don't see a point in treating `0` in any special way.
2) This is Linux PAL, we trust the host OS.
3) Even if we didn't, we just check return value - this is normal, expected code, no need for fancy names.
4) I believe Iago attacks refer to malicious host returning wrong values, especially different/unexpected error codes and we already checked for `< 0` above, not here. Also I don't understand why this has a special name (which frankly speaking I've never heard before), this is nothing fancy/novel.


<!-- Sent from Reviewable.io -->

2022-08-31 08:01 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/866)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[`-- commits` line 8 at r2](https://reviewable.io/reviews/gramineproject/gramine/866#-NAhTEaF55Aa7LXIJx7Y):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Something like:
```
[PAL] Remove `PAL_OPTION_CLOEXEC` flag                                   
                                                                         
This flag was used to control `CLOEXEC` flag of host OS fd and, as such, 
was Linux specific. It was also not really needed - Linux and Linux SGX  
PALs always set it on host fd anyway.                                    
                                                                         
This commit also adds all missing `CLOEXEC` flag usages in Linux and     
Linux SGX PALs, which fixes multiple fd leaks (all Linux PALs do `fork`  
+ `execve` when spawning a new process, which leaks fds without          
`CLOEXEC` flag).
```
?
</blockquote></details>

Yes, this text is good.
___
*[`libos/test/regression/fdleak.c` line 62 at r2](https://reviewable.io/reviews/gramineproject/gramine/866#-NAhVZ9lBx3KjAzI6-06:-NAmtf2EEOJYe3gv2XyT:b-gxztsp) ([raw file](https://github.com/gramineproject/gramine/blob/ff2eabaf92f7c4e3de31f071d628f7e44b6edaaf/libos/test/regression/fdleak.c#L62)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

We are not, but why would we care? There is no way of doing this without `PR_SET_CHILD_SUBREAPER`, which is not supported in Gramine. All we are is that we do enough nested forks, which we know happened, because we successfully read data from the pipe.
</blockquote></details>

Fair enough.
___
*[`libos/test/regression/fdleak.c` line 71 at r2](https://reviewable.io/reviews/gramineproject/gramine/866#-NAhTvUD5BfJl-GfjYqt:-NAmtk34EXHroI09RqXK:b-17rccj) ([raw file](https://github.com/gramineproject/gramine/blob/ff2eabaf92f7c4e3de31f071d628f7e44b6edaaf/libos/test/regression/fdleak.c#L71)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

If you want I can do this, but this is really just a sanity check...
</blockquote></details>

Well, I frequently run LibOS tests manually, so this error could throw me off... So I'd want this.
___
*[`pal/src/host/linux/pal_memory.c` line 93 at r2](https://reviewable.io/reviews/gramineproject/gramine/866#-NAhXH81DL-tswd2FlEC:-NAmu7cbAXqaehfG7b_Q:b-qezkjt) ([raw file](https://github.com/gramineproject/gramine/blob/ff2eabaf92f7c4e3de31f071d628f7e44b6edaaf/pal/src/host/linux/pal_memory.c#L93)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why not? We don't want this to stay open after execve, so why would we state otherwise?
Also keep in mind that there always could be a concurrent thread doing fork at any moment, so the fact that a function always closes the fd is not enough.
</blockquote></details>

Ok, fair enough.
___
*[`pal/src/host/linux/pal_streams.c` line 253 at r2](https://reviewable.io/reviews/gramineproject/gramine/866#-NAhXTsw9ng55mHMZ8tb:-NAmuWc5E8P-b5l2JsEg:bxjhpoq) ([raw file](https://github.com/gramineproject/gramine/blob/ae6cad8a5758acaf5f4fe8073234718c57cfd08f/pal/src/host/linux/pal_streams.c#L253)):*
Ok, even item 2 is enough to explain this deletion.

> Also I don't understand why this has a special name

Do you mean the term "Iago attack"? I don't know the reason for such a name, but this is from a conference paper. And all conference papers introduce some new names, just because that's how conferences work...


<!-- Sent from Reviewable.io -->

2022-08-31 12:36 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/866)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[`libos/test/regression/fdleak.c` line 71 at r2](https://reviewable.io/reviews/gramineproject/gramine/866#-NAhTvUD5BfJl-GfjYqt:-NAntG7P06H5sU9Naxvq:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/ff2eabaf92f7c4e3de31f071d628f7e44b6edaaf/libos/test/regression/fdleak.c#L71)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Well, I frequently run LibOS tests manually, so this error could throw me off... So I'd want this.
</blockquote></details>

Done.
___
*[`pal/src/host/linux/pal_streams.c` line 253 at r2](https://reviewable.io/reviews/gramineproject/gramine/866#-NAhXTsw9ng55mHMZ8tb:-NAntVB_9SHK4bqP7N1c:b-juo85r) ([raw file](https://github.com/gramineproject/gramine/blob/ae6cad8a5758acaf5f4fe8073234718c57cfd08f/pal/src/host/linux/pal_streams.c#L253)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ok, even item 2 is enough to explain this deletion.

> Also I don't understand why this has a special name

Do you mean the term "Iago attack"? I don't know the reason for such a name, but this is from a conference paper. And all conference papers introduce some new names, just because that's how conferences work...
</blockquote></details>

Well, I'll just stick to the term "checking return values".


<!-- Sent from Reviewable.io -->

2022-08-31 13:08 UTC, dimakuv reviewed
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/866)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)



<!-- Sent from Reviewable.io -->

2022-08-31 13:17 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/866)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/866#-NAo22371GcshTU27Dr3:-NAo22371GcshTU27Dr4:b-pf1fdw) (no related file):*
Hmm, it would be good to document somewhere this requirement of having `CLOEXEC` on all host fds - the problem is that it's Linux and Linux SGX PALs specific (it's not PAL generic)

___


<!-- Sent from Reviewable.io -->

2022-09-01 07:03 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/866)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/866#-NAo22371GcshTU27Dr3:-NArqeoi7qssptNDTp3Y:b-eo8ac3) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Hmm, it would be good to document somewhere this requirement of having `CLOEXEC` on all host fds - the problem is that it's Linux and Linux SGX PALs specific (it's not PAL generic)
</blockquote></details>

We have our documentation on PAL: https://gramine.readthedocs.io/en/latest/pal/host-abi.html. But it's old and not good and nobody ever looks at it, so I wouldn't put there.

Maybe just a high-level comment here: https://github.com/gramineproject/gramine/blob/7b369de0787eab57b80a569604155fb6d0e598d3/pal/include/pal/pal.h#L6

Something like "All PAL implementations must create handles on the host that will be automatically closed when switching to a new process image. In case of Linux-backed PALs, this is achieved by adding `O_CLOEXEC` to all created host fds."

___


<!-- Sent from Reviewable.io -->

2022-09-01 12:18 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/866)* status: 29 of 30 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/866#-NAo22371GcshTU27Dr3:-NAszGZZDtkDVFPuaoU6:b-896fix) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We have our documentation on PAL: https://gramine.readthedocs.io/en/latest/pal/host-abi.html. But it's old and not good and nobody ever looks at it, so I wouldn't put there.

Maybe just a high-level comment here: https://github.com/gramineproject/gramine/blob/7b369de0787eab57b80a569604155fb6d0e598d3/pal/include/pal/pal.h#L6

Something like "All PAL implementations must create handles on the host that will be automatically closed when switching to a new process image. In case of Linux-backed PALs, this is achieved by adding `O_CLOEXEC` to all created host fds."
</blockquote></details>

Done.

___


<!-- Sent from Reviewable.io -->

2022-09-01 12:36 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/866)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/866#-NAo22371GcshTU27Dr3:-NAt2C5DCftFWTYNVoh4:bi8rkil) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Yes, my proposed text was incorrect. Yours is much better. Thanks.

___


<!-- Sent from Reviewable.io -->

2022-09-06 13:29 UTC, mkow approved these changes
> Reviewed 26 of 27 files at r1, 1 of 3 files at r2, 1 of 2 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/866)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)



<!-- Sent from Reviewable.io -->

2022-09-06 14:14 UTC, mkow approved these changes
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/866)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)



<!-- Sent from Reviewable.io -->

2022-09-06 14:30 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/866)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

___
*[`-- commits` line 8 at r2](https://reviewable.io/reviews/gramineproject/gramine/866#-NAhTEaF55Aa7LXIJx7Y):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, this text is good.
</blockquote></details>

@boryspoplawski The text was not updated?


<!-- Sent from Reviewable.io -->

2022-09-06 14:44 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/866)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

___
*[`-- commits` line 8 at r2](https://reviewable.io/reviews/gramineproject/gramine/866#-NAhTEaF55Aa7LXIJx7Y):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@boryspoplawski The text was not updated?
</blockquote></details>

Yes, that's why I prefer squash commits...


<!-- Sent from Reviewable.io -->

2022-09-06 14:48 UTC, dimakuv approved these changes
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/866)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-09-06 14:51 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/866)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-09-06 16:54 UTC, merged