[PAL/Linux-SGX] Introduce `sgx.cpu_features.[...]` manifest options
gramineproject/gramine pull request #877
Opened 2022-09-02 11:40 UTC by dimakuv

## Description of the changes 

Introduce `sgx.cpu_features.[...] = "[autodetect|required|disabled]"` instead of `sgx.require_[...] = true|false`.

Mapping of deprecated and new manifest options:
- `sgx.cpu_features.[...] = "autodetect"` -> `sgx.require_[...] = false`
- `sgx.cpu_features.[...] = "required"` -> `sgx.require_[...] = true`

`sgx.cpu_features.[...] = "disabled"` is new and it disables the corresponding CPU feature inside the SGX enclave even if this CPU
feature is available on the system: this may improve enclave performance because this CPU feature will *not* be saved and restored during enclave entry/exit.

This PR is a re-creation of https://github.com/gramineproject/gramine/pull/321 and https://github.com/gramineproject/gramine/pull/461, since it turned out to be useful for performance. Without disclosing any perf numbers, I performed a set of micro-benchmarks and they prove that disabling Intel AMX inside of the enclave (when it is available on the machine but is not needed by the app inside the enclave) gives a measurable performance boost (for the worst-case scenarios). So this change actually is beneficial.

## How to test this PR? 

I tested this PR manually on the AMX-enabled machine:
```bash
# with sgx.cpu_features.amx = "autodetect"
$ gramine-sgx helloworld
[::] debug: LibOS xsave_enabled 1, xsave_size 0x2b00(11008), xsave_features 0x600e7 

# with sgx.cpu_features.amx = "required"
$ gramine-sgx helloworld
[::] debug: LibOS xsave_enabled 1, xsave_size 0x2b00(11008), xsave_features 0x600e7

# with sgx.cpu_features.amx = "disabled"
$ gramine-sgx helloworld
[::] debug: LibOS xsave_enabled 1, xsave_size 0xa80(2688), xsave_features 0xe7
```

2022-09-02 12:09 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/877)* status: 0 of 7 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/877#-NAy5du--8IvWB49Owv-:-NAy5du--8IvWB49Owv0:b-1fsxm1) (no related file):*
FYI: I just tested on the AMX-enabled machine, everything works as expected.

The test I used is the same as before, `amxtest` microbenchmark from here: https://github.com/gramineproject/gramine/commit/1451bb6543e6e6af02668996261197b37644927e

___


<!-- Sent from Reviewable.io -->

2022-09-02 15:13 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/877)* status: 0 of 7 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/877#-NAyibNU74OEJqGevUrt:-NAyibNU74OEJqGevUru:b-oa8ccs) (no related file):*
FYI: One thing that I was made aware of (thanks to Borys) and that needs some explanation.

From the Section 38.7 in Intel SDM:

> Enclave developers can create their enclave to work with certain features and fallback to another code path in case those features aren't available (e.g., optimize for AVX and fallback to SSE). For this purpose Intel SGX provides the following fields in SIGSTRUCT: ATTRIBUTES, ATTRIBUTESMASK, MISCSELECT, and MISCMASK. EINIT ensures that
the final SECS.ATTRIBUTES and SECS.MISCSELECT comply with the enclave developer's requirements as follows:
`SIGSTRUCT.ATTRIBUTES & SIGSTRUCT.ATTRIBUTEMASK = SECS.ATTRIBUTES & SIGSTRUCT.ATTRIBUTEMASK`

So this means there are three cases of how the enclave is developed (and measured):
1. `SIGSTRUCT.ATTRIBUTEMASK[feature] = 0` and `SIGSTRUCT.ATTRIBUTES[feature] = <0/1>` -- the enclave developer doesn't enforce enablement/disablement of this feature. This is for the "fallback to another code" case described in the Intel SDM.
    1. If during enclave creation, the untrusted host sets `SECS.ATTRIBUTES[feature] = 0`, then the feature is disabled inside of the enclave. The app runs in an SGX environment that prohibits any instruction execution of this feature.
    2. If during enclave creation, the untrusted host sets `SECS.ATTRIBUTES[feature] = 1`, then the feature is enabled inside of the enclave. The app runs in an SGX environment that allows execution of this feature.
2. `SIGSTRUCT.ATTRIBUTEMASK[feature] = 1` and `SIGSTRUCT.ATTRIBUTES[feature] = 0` -- the enclave developer enforces disablement of this feature. The enclave won't start if the untrusted host sets `SECS.ATTRIBUTES[feature] = 1`. In other words, the untrusted host must disable this feature, and it will be disabled in the SGX environment for sure.
3. `SIGSTRUCT.ATTRIBUTEMASK[feature] = 1` and `SIGSTRUCT.ATTRIBUTES[feature] = 1` -- the enclave developer enforces enablement of this feature. The enclave won't start if the untrusted host sets `SECS.ATTRIBUTES[feature] = 0`. In other words, the untrusted host must enable this feature (and of course this feature must be available on the platform), and it will be enabled in the SGX environment for sure.

The current implementation in this PR does this:
1. `"autodetect"` = `SIGSTRUCT.ATTRIBUTEMASK[feature] = 0` and `SIGSTRUCT.ATTRIBUTES[feature] = 0`. The decision is on the untrusted host. It sets `SECS.ATTRIBUTES[feature] = 0` if it can't detect the feature on the platform, and `SECS.ATTRIBUTES[feature] = 1` otherwise.
2. `"required"` = `SIGSTRUCT.ATTRIBUTEMASK[feature] = 1` and `SIGSTRUCT.ATTRIBUTES[feature] = 1`.
3. `"disabled"` = `SIGSTRUCT.ATTRIBUTEMASK[feature] = 0` and `SIGSTRUCT.ATTRIBUTES[feature] = 1`. Actually, the `1` in ATTRIBUTES is irrelevant, everything is decided by the untrusted host. And it sets `SECS.ATTRIBUTES[feature] = 0` unconditionally.


So the new `"disabled"` option is *not security-enforcing*. It is only a hint to the untrusted host to disable the feature inside the SGX enclave. But a malicious host may choose to keep it enabled. I don't consider it relevant as it is only a performance optimization. But people may disagree, or they may consider this logic contrived. I can change it.

___


<!-- Sent from Reviewable.io -->

2022-09-02 16:43 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/877)* status: 0 of 7 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/877#-NAyibNU74OEJqGevUrt:-NAz3s-O3BM8K3Gb2Vi5:bicaifc) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

FYI: One thing that I was made aware of (thanks to Borys) and that needs some explanation.

From the Section 38.7 in Intel SDM:

> Enclave developers can create their enclave to work with certain features and fallback to another code path in case those features aren't available (e.g., optimize for AVX and fallback to SSE). For this purpose Intel SGX provides the following fields in SIGSTRUCT: ATTRIBUTES, ATTRIBUTESMASK, MISCSELECT, and MISCMASK. EINIT ensures that
the final SECS.ATTRIBUTES and SECS.MISCSELECT comply with the enclave developer's requirements as follows:
`SIGSTRUCT.ATTRIBUTES & SIGSTRUCT.ATTRIBUTEMASK = SECS.ATTRIBUTES & SIGSTRUCT.ATTRIBUTEMASK`

So this means there are three cases of how the enclave is developed (and measured):
1. `SIGSTRUCT.ATTRIBUTEMASK[feature] = 0` and `SIGSTRUCT.ATTRIBUTES[feature] = <0/1>` -- the enclave developer doesn't enforce enablement/disablement of this feature. This is for the "fallback to another code" case described in the Intel SDM.
    1. If during enclave creation, the untrusted host sets `SECS.ATTRIBUTES[feature] = 0`, then the feature is disabled inside of the enclave. The app runs in an SGX environment that prohibits any instruction execution of this feature.
    2. If during enclave creation, the untrusted host sets `SECS.ATTRIBUTES[feature] = 1`, then the feature is enabled inside of the enclave. The app runs in an SGX environment that allows execution of this feature.
2. `SIGSTRUCT.ATTRIBUTEMASK[feature] = 1` and `SIGSTRUCT.ATTRIBUTES[feature] = 0` -- the enclave developer enforces disablement of this feature. The enclave won't start if the untrusted host sets `SECS.ATTRIBUTES[feature] = 1`. In other words, the untrusted host must disable this feature, and it will be disabled in the SGX environment for sure.
3. `SIGSTRUCT.ATTRIBUTEMASK[feature] = 1` and `SIGSTRUCT.ATTRIBUTES[feature] = 1` -- the enclave developer enforces enablement of this feature. The enclave won't start if the untrusted host sets `SECS.ATTRIBUTES[feature] = 0`. In other words, the untrusted host must enable this feature (and of course this feature must be available on the platform), and it will be enabled in the SGX environment for sure.

The current implementation in this PR does this:
1. `"autodetect"` = `SIGSTRUCT.ATTRIBUTEMASK[feature] = 0` and `SIGSTRUCT.ATTRIBUTES[feature] = 0`. The decision is on the untrusted host. It sets `SECS.ATTRIBUTES[feature] = 0` if it can't detect the feature on the platform, and `SECS.ATTRIBUTES[feature] = 1` otherwise.
2. `"required"` = `SIGSTRUCT.ATTRIBUTEMASK[feature] = 1` and `SIGSTRUCT.ATTRIBUTES[feature] = 1`.
3. `"disabled"` = `SIGSTRUCT.ATTRIBUTEMASK[feature] = 0` and `SIGSTRUCT.ATTRIBUTES[feature] = 1`. Actually, the `1` in ATTRIBUTES is irrelevant, everything is decided by the untrusted host. And it sets `SECS.ATTRIBUTES[feature] = 0` unconditionally.


So the new `"disabled"` option is *not security-enforcing*. It is only a hint to the untrusted host to disable the feature inside the SGX enclave. But a malicious host may choose to keep it enabled. I don't consider it relevant as it is only a performance optimization. But people may disagree, or they may consider this logic contrived. I can change it.
</blockquote></details>

Wait, this makes no sense, with option 3 "disabled" the feature will be actually enabled (if CPU supports it).
IMO it should be 3. `"disabled"` = `SIGSTRUCT.ATTRIBUTEMASK[feature] = 1` and `SIGSTRUCT.ATTRIBUTES[feature] = 0`

___


<!-- Sent from Reviewable.io -->

2022-09-02 20:49 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/877)* status: 0 of 7 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/877#-NAyibNU74OEJqGevUrt:-NAzxCOx-u103cFMyfz-:biih9p) (no related file):*
> Wait, this makes no sense, with option 3 "disabled" the feature will be actually enabled (if CPU supports it).

No. If we talk about the benign case, then the benign untrusted host just forces `SECS.ATTRIBUTES[feature]` to zero in the "disabled" case.

(In the "autodetect" case, the benign untrusted host chooses `SECS.ATTRIBUTES[feature]` to be zero or one depending on the availability of the feature on the host.)

But in the malicious case, yes, we cannot make a difference between "disabled" and "autodetect" case. This is true, if that's what you meant.

Anyway, I now agree that `"disabled"` should be the actually-enforced-by-hardware option, which is `SIGSTRUCT.ATTRIBUTEMASK[feature] = 1` and `SIGSTRUCT.ATTRIBUTES[feature] = 0`. I'll update the PR accordingly. And I guess we'll need these technical explanations somewhere in the documentation or source code, otherwise people will be confused.

___


<!-- Sent from Reviewable.io -->

2022-09-02 20:59 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/877)* status: 0 of 7 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/877#-NAyibNU74OEJqGevUrt:-NAzzNnPDmwKCIzLPQC7:b-3pkc7n) (no related file):*
> No. If we talk about the benign case, then the benign untrusted host just forces SECS.ATTRIBUTES[feature] to zero in the "disabled" case.

No. https://github.com/gramineproject/gramine/blob/f1e1d22d29a08c05a6cf19188aa0241787608371/python/graminelibos/sgx_get_token.py#L39
In this "disabled" case mask == 0, so it will be enabled.

> And I guess we'll need these technical explanations somewhere in the documentation or source code, otherwise people will be confused.

IMO documenting in `Documentation` should be enough

___


<!-- Sent from Reviewable.io -->

2022-09-05 09:07 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/877)* status: 0 of 7 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/877#-NAyibNU74OEJqGevUrt:-NBBtbzE-X36ayVSRque:budi2gb) (no related file):*
> In this "disabled" case mask == 0, so it will be enabled.

Yeah, but this PR adds "disable not-security-critical HW features for XSAVE/AEX performance" logic in `host_framework.c`, right before ECREATEing the enclave, so that stuff from `sgx_get_token.py` is overwritten.

Anyway, I agree that the current logic is super-confusing, and I will fix it now.

___


<!-- Sent from Reviewable.io -->

2022-09-05 12:21 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/877)* status: 0 of 7 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/877#-NAyibNU74OEJqGevUrt:-NBCaBL8-FId187lyVqa:b-i1ysut) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> In this "disabled" case mask == 0, so it will be enabled.

Yeah, but this PR adds "disable not-security-critical HW features for XSAVE/AEX performance" logic in `host_framework.c`, right before ECREATEing the enclave, so that stuff from `sgx_get_token.py` is overwritten.

Anyway, I agree that the current logic is super-confusing, and I will fix it now.
</blockquote></details>

I implemented the more reasonable logic for `"disabled"` manifest option. The new PR is here: https://github.com/gramineproject/gramine/pull/881. I will close this PR.

___


<!-- Sent from Reviewable.io -->

2022-09-05 12:22 UTC, dimakuv commented
Superseded by https://github.com/gramineproject/gramine/pull/881. Closing.

2022-09-05 12:22 UTC, closed without merging