[tools/RA-TLS] Don't use insecure unhex and rework secret-prov examples
gramineproject/gramine pull request #884
Opened 2022-09-06 10:58 UTC by mkow

## Description of the changes 

The old version used straightforward unhex on an encoded secret, which may leak some information about it through memory access patterns.

This commit solves the issue by just sending the secret in raw binary. This change required the ra-tls-secret-prov to be cleaned up (previously, a single provisioning server was used by 3 different sub-examples).

## How to test this PR? 

CI + follow the readme in the example.

2022-09-06 12:47 UTC, dimakuv requested changes
> Reviewed 22 of 22 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/884)* status: all files reviewed, 40 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/884#-NBHdS-HDDI1RS7uKCct:-NBHdS-HDDI1RS7uKCcu:b-q0o3d6) (no related file):*
This is a breaking change, right? Because if the user doesn't update her `secret_prov_server`, then the server will send hex-encoded PF key but the client's `secret_prov` library in its constructor function will expect the PF key as raw binary. So there will be a failure.

We should somehow mark this as a breaking change...

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/884#-NBHnKdIAOxVhGVrNSPH:-NBHnKdJ9JeeCT6ojgFk:b-iw8l54) (no related file):*
Since you are anyhow changing `wrap-key` file name, can we remove this "wrap" (we don't use it anywhere now)? Maybe `encryption_key` or `enc_key` or `files_key`?

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/884#-NBHpFFk2l5A4RYUVlkX:-NBHpFFk2l5A4RYUVlkY:b-amt9y5) (no related file):*
This will need to be updated after this PR is merged: https://github.com/gramineproject/contrib/tree/master/Examples/aks-attestation. Created an issue: https://github.com/gramineproject/contrib/issues/8

___
___
*[`CI-Examples/ra-tls-secret-prov/.gitignore` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/884#-NBHe1XMEXfKuFm35VYv:-NBHe1XMEXfKuFm35VYw:b-v0spzc) ([raw file](https://github.com/gramineproject/gramine/blob/0537ac14dbffa7fb7449a8787a79f3ff11ee2384/CI-Examples/ra-tls-secret-prov/.gitignore#L2)):*
> ```ignore
> /OUTPUT
> /files/input.txt
> ```

This seems to be not used anymore?
___
*[`CI-Examples/ra-tls-secret-prov/Makefile` line 86 at r1](https://reviewable.io/reviews/gramineproject/gramine/884#-NBHeyTzBDQ52xW2jQ4S:-NBHeyTzBDQ52xW2jQ4T:bhfz0dy) ([raw file](https://github.com/gramineproject/gramine/blob/7e7e31b1ac9cd94636245ba3c89f6f79c8c0dcc8/CI-Examples/ra-tls-secret-prov/Makefile#L86)):*
> ```Makefile
> 
> # Make on Ubuntu <= 20.04 doesn't support "Rules with Grouped Targets" (`&:`),
> # see the helloworld example for details on this workaround.
> ```

Why did you remove from here?..
___
*[`CI-Examples/ra-tls-secret-prov/Makefile` line 110 at r1](https://reviewable.io/reviews/gramineproject/gramine/884#-NBHfFruC9k0whg_tjd3:-NBHfFruC9k0whg_tjd4:b-vpdwa4) ([raw file](https://github.com/gramineproject/gramine/blob/0537ac14dbffa7fb7449a8787a79f3ff11ee2384/CI-Examples/ra-tls-secret-prov/Makefile#L110)):*
> ```Makefile
> 	gramine-sgx-sign \
> 		--manifest client.manifest \
> 		--output client.manifest.sgx
> ```

Can you replace the hard-coded `client.` in these two lines with `notdir $<` like in the below cases?
___
*[`CI-Examples/ra-tls-secret-prov/Makefile` line 128 at r1](https://reviewable.io/reviews/gramineproject/gramine/884#-NBHf-in9dexuaQJBgM6:-NBHf-in9dexuaQJBgM7:bf47q4d) ([raw file](https://github.com/gramineproject/gramine/blob/0537ac14dbffa7fb7449a8787a79f3ff11ee2384/CI-Examples/ra-tls-secret-prov/Makefile#L128)):*
> ```Makefile
> 
> # Make on Ubuntu <= 20.04 doesn't support "Rules with Grouped Targets" (`&:`),
> # see the helloworld example for details on this workaround.
> ```

...and added here?
___
*[`CI-Examples/ra-tls-secret-prov/Makefile` line 142 at r1](https://reviewable.io/reviews/gramineproject/gramine/884#-NBHfk2Z1HmTHdCnd_33:-NBHfk2Z1HmTHdCnd_34:br1trk6) ([raw file](https://github.com/gramineproject/gramine/blob/0537ac14dbffa7fb7449a8787a79f3ff11ee2384/CI-Examples/ra-tls-secret-prov/Makefile#L142)):*
> ```Makefile
> 	gramine-sgx-get-token --output $@ --sig $<
> 
> ########################## PREPARE PROTECTED FILES ############################
> ```

I would move this section to after `PF CLIENT MANIFEST`, then we would have reasonable grouping of Makefile sections
___
*[`CI-Examples/ra-tls-secret-prov/Makefile` line 213 at r1](https://reviewable.io/reviews/gramineproject/gramine/884#-NBHgbyJ6OCfrGRgV418:-NBHgbyJ6OCfrGRgV419:b-clmm3e) ([raw file](https://github.com/gramineproject/gramine/blob/0537ac14dbffa7fb7449a8787a79f3ff11ee2384/CI-Examples/ra-tls-secret-prov/Makefile#L213)):*
> ```Makefile
> 
> .PHONY: check_dcap
> check_dcap: app dcap
> ```

Where are the `wrap_key` and `input.txt` targets (like in `check_epid`)?

I wonder how it worked for me when I tested manually. Probably I played with different targets and forgot to `make distclean`...
___
*[`CI-Examples/ra-tls-secret-prov/README.md` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/884#-NBHhGSu99VqPjA1OoSG:-NBHhGSv6IBBywlQf6AL:b-qnmzi9) ([raw file](https://github.com/gramineproject/gramine/blob/0537ac14dbffa7fb7449a8787a79f3ff11ee2384/CI-Examples/ra-tls-secret-prov/README.md#L4)):*
> ```Markdown
> 
> This directory contains a Makefile, template client manifests, and a few
> examples of server and clients written against the Secret Provisioning
> ```

`server` -> `servers`
___
*[`CI-Examples/ra-tls-secret-prov/README.md` line 9 at r1](https://reviewable.io/reviews/gramineproject/gramine/884#-NBHhIuNDij4mg6JP1v2:-NBHhIuNDij4mg6JP1v3:b-qnmzi9) ([raw file](https://github.com/gramineproject/gramine/blob/0537ac14dbffa7fb7449a8787a79f3ff11ee2384/CI-Examples/ra-tls-secret-prov/README.md#L9)):*
> ```Markdown
> These examples use the Secret Provisioning libraries `secret_prov_attest.so` for
> the clients and `secret_prov_verify_epid.so`/`secret_prov_verify_dcap.so` for
> the server. They are installed together with Gramine (but for DCAP version, you
> ```

`server` -> `servers`
___
*[`CI-Examples/ra-tls-secret-prov/README.md` line 9 at r1](https://reviewable.io/reviews/gramineproject/gramine/884#-NBHhMtIEG5xuTAl_BdL:-NBHhMtIEG5xuTAl_BdM:bxgpzd3) ([raw file](https://github.com/gramineproject/gramine/blob/0537ac14dbffa7fb7449a8787a79f3ff11ee2384/CI-Examples/ra-tls-secret-prov/README.md#L9)):*
> ```Markdown
> These examples use the Secret Provisioning libraries `secret_prov_attest.so` for
> the clients and `secret_prov_verify_epid.so`/`secret_prov_verify_dcap.so` for
> the server. They are installed together with Gramine (but for DCAP version, you
> ```

Maybe `They` -> `These libraries`? Otherwise confusing (libs or examples are installed?).
___
*[`CI-Examples/ra-tls-secret-prov/README.md` line 10 at r1](https://reviewable.io/reviews/gramineproject/gramine/884#-NBHhdVo0VS75LHw6090:-NBHhdVo0VS75LHw6091:be08xc1) ([raw file](https://github.com/gramineproject/gramine/blob/0537ac14dbffa7fb7449a8787a79f3ff11ee2384/CI-Examples/ra-tls-secret-prov/README.md#L10)):*
> ```Markdown
> the clients and `secret_prov_verify_epid.so`/`secret_prov_verify_dcap.so` for
> the server. They are installed together with Gramine (but for DCAP version, you
> need `meson setup ... -Ddcap=enabled`). Additionally, mbedTLS libraries are
> ```

Actually, this `but for DCAP version ...` is only confusing. We already have stable version (v1.2) built with DCAP, so maybe just remove this thing? Those who build Gramine from scratch will hopefully know/debug this quirk themselves.

If we decide to remove the sentence, the same should be done for the `ra-tls-mbedtls` example.
___
*[`CI-Examples/ra-tls-secret-prov/README.md` line 11 at r1](https://reviewable.io/reviews/gramineproject/gramine/884#-NBHhz_Z9Eh6bawToj7x:-NBHhz_Z9Eh6bawToj7y:b1m4u6y) ([raw file](https://github.com/gramineproject/gramine/blob/0537ac14dbffa7fb7449a8787a79f3ff11ee2384/CI-Examples/ra-tls-secret-prov/README.md#L11)):*
> ```Markdown
> the server. They are installed together with Gramine (but for DCAP version, you
> need `meson setup ... -Ddcap=enabled`). Additionally, mbedTLS libraries are
> required. For ECDSA/DCAP attestation, the DCAP software infrastructure must be
> ```

`Additionally, mbedTLS libraries ...` -- please remove. We don't have it an [...]

2022-09-06 14:39 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/884)* status: 13 of 23 files reviewed, 40 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/884#-NBHdS-HDDI1RS7uKCct:-NBHzqBY4vry3Ma2CSSa:b3hhxqb) (no related file):*
> This is a breaking change, right?

Yes.

> We should somehow mark this as a breaking change...

In the v1.3 release notes, probably?

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/884#-NBHnKdIAOxVhGVrNSPH:-NBI-0AJ4EmtMmTmSZru:bsh8swd) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Since you are anyhow changing `wrap-key` file name, can we remove this "wrap" (we don't use it anywhere now)? Maybe `encryption_key` or `enc_key` or `files_key`?
</blockquote></details>

I wanted to, but then noticed how many things I'd need to change, including all pf cmdline tools which use this name for that argument. So, this is IMO for another PR.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/884#-NBHpFFk2l5A4RYUVlkX:-NBI-GsM4kw6jlR-AyBj:b2nha9w) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This will need to be updated after this PR is merged: https://github.com/gramineproject/contrib/tree/master/Examples/aks-attestation. Created an issue: https://github.com/gramineproject/contrib/issues/8
</blockquote></details>

ACK

___
___
*[`CI-Examples/ra-tls-secret-prov/.gitignore` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/884#-NBHe1XMEXfKuFm35VYv:-NBI-LXv4OfLqfXqJu6v:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/0537ac14dbffa7fb7449a8787a79f3ff11ee2384/CI-Examples/ra-tls-secret-prov/.gitignore#L2)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This seems to be not used anymore?
</blockquote></details>

Done.
___
*[`CI-Examples/ra-tls-secret-prov/Makefile` line 86 at r1](https://reviewable.io/reviews/gramineproject/gramine/884#-NBHeyTzBDQ52xW2jQ4S:-NBI-d5C1zotJm4K3YV_:bkslc9m) ([raw file](https://github.com/gramineproject/gramine/blob/7e7e31b1ac9cd94636245ba3c89f6f79c8c0dcc8/CI-Examples/ra-tls-secret-prov/Makefile#L86)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why did you remove from here?..
</blockquote></details>

I moved this block of code together with the comment (but the diff doesn't show this nicely). This comment makes more sense at the first occurrence of that problem, so I moved it up.
___
*[`CI-Examples/ra-tls-secret-prov/Makefile` line 110 at r1](https://reviewable.io/reviews/gramineproject/gramine/884#-NBHfFruC9k0whg_tjd3:-NBI0WHQ2D7Q65-4CiEh:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/0537ac14dbffa7fb7449a8787a79f3ff11ee2384/CI-Examples/ra-tls-secret-prov/Makefile#L110)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can you replace the hard-coded `client.` in these two lines with `notdir $<` like in the below cases?
</blockquote></details>

Done.
___
*[`CI-Examples/ra-tls-secret-prov/Makefile` line 128 at r1](https://reviewable.io/reviews/gramineproject/gramine/884#-NBHf-in9dexuaQJBgM6:-NBI0Xh9AcMEBCFBYiK4:b-fe9b9j) ([raw file](https://github.com/gramineproject/gramine/blob/0537ac14dbffa7fb7449a8787a79f3ff11ee2384/CI-Examples/ra-tls-secret-prov/Makefile#L128)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

...and added here?
</blockquote></details>

See above, fixed.
___
*[`CI-Examples/ra-tls-secret-prov/Makefile` line 142 at r1](https://reviewable.io/reviews/gramineproject/gramine/884#-NBHfk2Z1HmTHdCnd_33:-NBI0mcFEdaBXIRN_yaO:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/0537ac14dbffa7fb7449a8787a79f3ff11ee2384/CI-Examples/ra-tls-secret-prov/Makefile#L142)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I would move this section to after `PF CLIENT MANIFEST`, then we would have reasonable grouping of Makefile sections
</blockquote></details>

Done.
___
*[`CI-Examples/ra-tls-secret-prov/Makefile` line 213 at r1](https://reviewable.io/reviews/gramineproject/gramine/884#-NBHgbyJ6OCfrGRgV418:-NBI0vq4E1hu_C3eUcir:b-jvvn5g) ([raw file](https://github.com/gramineproject/gramine/blob/0537ac14dbffa7fb7449a8787a79f3ff11ee2384/CI-Examples/ra-tls-secret-prov/Makefile#L213)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Where are the `wrap_key` and `input.txt` targets (like in `check_epid`)?

I wonder how it worked for me when I tested manually. Probably I played with different targets and forgot to `make distclean`...
</blockquote></details>

I moved them to `epid` and `dcap` deps, as you asked on Gitter? Or maybe I misunderstood what you asked for?
___
*[`CI-Examples/ra-tls-secret-prov/README.md` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/884#-NBHhGSu99VqPjA1OoSG:-NBI18Mk9YWuZKFyDp0N:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/0537ac14dbffa7fb7449a8787a79f3ff11ee2384/CI-Examples/ra-tls-secret-prov/README.md#L4)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`server` -> `servers`
</blockquote></details>

Done.
___
*[`CI-Examples/ra-tls-secret-prov/README.md` line 9 at r1](https://reviewable.io/reviews/gramineproject/gramine/884#-NBHhIuNDij4mg6JP1v2:-NBI1DHYCzafpnpLW-nl:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/0537ac14dbffa7fb7449a8787a79f3ff11ee2384/CI-Examples/ra-tls-secret-prov/README.md#L9)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`server` -> `servers`
</blockquote></details>

Done.
___
*[`CI-Examples/ra-tls-secret-prov/README.md` line 9 at r1](https://reviewable.io/reviews/gramineproject/gramine/884#-NBHhMtIEG5xuTAl_BdL:-NBI1I_l2TwqLf2szNUy:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/0537ac14dbffa7fb7449a8787a79f3ff11ee2384/CI-Examples/ra-tls-secret-prov/README.md#L9)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Maybe `They` -> `These libraries`? Otherwise confusing (libs or examples are installed?).
</blockquote></details>

Done.
___
*[`CI-Examples/ra-tls-secret-prov/README.md` line 10 at r1](https://reviewable.io/reviews/gramineproject/gramine/884#-NBHhdVo0VS75LHw6090:-NBI1U6k00TCNxbENmx9:b-8v10dd) ([raw file](https://github.com/gramineproject/gramine/blob/0537ac14dbffa7fb7449a8787a79f3ff11ee2384/CI-Examples/ra-tls-secret-prov/README.md#L10)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Actually, this `but for DCAP version ...` is only confusing. We already have stable version (v1.2) built with DCAP, so maybe just remove this thing? Those who build Gramine from scratch will hopefully know/debug this quirk themselves.

If we decide to remove the sentence, the same should be done for the `ra-tls-mbedtls` example.
</blockquote></details>

I'd rather leave it, AFAIR it wasn't trivial to find out what's wrong when you built without it? (for non-Gramine-developers)
___
*[`CI-Examples/ra-tls-secret-prov/README.md` line 11 at r1](https://reviewable.io/reviews/gramineproject/gramine/884#-NBHhz_Z9Eh6bawToj7x:-NBI1ss4BopLjeDjTNyT:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/0537ac14dbffa7fb7449a8787a79f3ff11ee2384/CI-Examples/ra-tls-secret-prov/README.md#L11)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`Additionally [...]

2022-09-06 18:04 UTC, dimakuv requested changes
> Reviewed 10 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/884)* status: all files reviewed, 11 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/884#-NBHdS-HDDI1RS7uKCct:-NBIkCwA8oVLSaPMQ4ct:b4gcv2v) (no related file):*
> In the v1.3 release notes, probably?

How do we track these changes now? Can we make a draft? UPDATE: I created a draft in which I put all the breaking changes from v1.2 to v1.3 that I could think of.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/884#-NBHnKdIAOxVhGVrNSPH:-NBIlD0PBfz84X6C65N8:b32w0x) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I wanted to, but then noticed how many things I'd need to change, including all pf cmdline tools which use this name for that argument. So, this is IMO for another PR.
</blockquote></details>

OK

___
___
*[`CI-Examples/ra-tls-secret-prov/Makefile` line 213 at r1](https://reviewable.io/reviews/gramineproject/gramine/884#-NBHgbyJ6OCfrGRgV418:-NBIlfEZ5czWIsKRgvY0:bt0uhhb) ([raw file](https://github.com/gramineproject/gramine/blob/0537ac14dbffa7fb7449a8787a79f3ff11ee2384/CI-Examples/ra-tls-secret-prov/Makefile#L213)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I moved them to `epid` and `dcap` deps, as you asked on Gitter? Or maybe I misunderstood what you asked for?
</blockquote></details>

OK. See my other comment on `check_epid`
___
*[`CI-Examples/ra-tls-secret-prov/Makefile` line 112 at r2](https://reviewable.io/reviews/gramineproject/gramine/884#-NBIlOu9BKzIuI19FlPG:-NBIlOu9BKzIuI19FlPH:bli8b4q) ([raw file](https://github.com/gramineproject/gramine/blob/e0a4feb1aab9298a854b0540b89a9fb98d240a61/CI-Examples/ra-tls-secret-prov/Makefile#L112)):*
> ```Makefile
> 	gramine-sgx-sign \
> 		--manifest $(notdir $<) \
> 		--output $(notdir $<).sgx
> ```

This is slightly different from other places. In other places, you have `.sgx` inside notdir
___
*[`CI-Examples/ra-tls-secret-prov/Makefile` line 184 at r2](https://reviewable.io/reviews/gramineproject/gramine/884#-NBIlYaO1bOTz9-ecQRG:-NBIlYaO1bOTz9-ecQRH:b-1f1dpj) ([raw file](https://github.com/gramineproject/gramine/blob/e0a4feb1aab9298a854b0540b89a9fb98d240a61/CI-Examples/ra-tls-secret-prov/Makefile#L184)):*
> ```Makefile
> 
> .PHONY: check_epid
> check_epid: app epid secret_prov_pf/wrap_key secret_prov_pf/enc_files/input.txt
> ```

Then `wrap_key` and `input.txt` should be removed from here.
___
*[`CI-Examples/ra-tls-secret-prov/README.md` line 18 at r1](https://reviewable.io/reviews/gramineproject/gramine/884#-NBHitiA-IJzqJBu8Qw9:-NBIlmPIE9UapOboNdZd:b7io5zg) ([raw file](https://github.com/gramineproject/gramine/blob/0537ac14dbffa7fb7449a8787a79f3ff11ee2384/CI-Examples/ra-tls-secret-prov/README.md#L18)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

How exactly? Describe each example separately?
</blockquote></details>

Yes, describe each of the three examples in `###` subsections or as a bullet list (under the `##` section with a title like "Three secret provisioning examples")
___
*[`CI-Examples/ra-tls-secret-prov/secret_prov_minimal/server.c` line 27 at r1](https://reviewable.io/reviews/gramineproject/gramine/884#-NBHlEZU1NOb09MCqhV_:-NBImhPA6s3gJ2GKy-KC:b5u2uby) ([raw file](https://github.com/gramineproject/gramine/blob/0537ac14dbffa7fb7449a8787a79f3ff11ee2384/CI-Examples/ra-tls-secret-prov/secret_prov_minimal/server.c#L27)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

The problem is that they are named just `m_cb` and `f_cb` in the original signature, which isn't helpful :/ If we use that `/*name=*/val` syntax, then it won't work after we finally enable this check in CI.
</blockquote></details>

Yeah, fair enough.
___
*[`Documentation/attestation.rst` line 480 at r1](https://reviewable.io/reviews/gramineproject/gramine/884#-NBHmfBpA-U_PDwwjXkk:-NBInAkOE-vn9Q7N755V:b-k0ryl8) ([raw file](https://github.com/gramineproject/gramine/blob/0537ac14dbffa7fb7449a8787a79f3ff11ee2384/Documentation/attestation.rst#L480)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why nowhere? It's directly after talking about provisioning secrets (which the enclave will need to decode somehow).
</blockquote></details>

What I'm trying to say that a casual user (e.g. some AI/ML scientist) won't have a clue what you're talking about. Do we want to have it that cryptic for normal users? Maybe at least a link?
___
*[`tools/sgx/ra-tls/secret_prov_attest.c` line 408 at r1](https://reviewable.io/reviews/gramineproject/gramine/884#-NBHo5IVCbfUuYiSbrlg:-NBIyA2s8IVEXsIWef1D:brp2bzp) ([raw file](https://github.com/gramineproject/gramine/blob/0537ac14dbffa7fb7449a8787a79f3ff11ee2384/tools/sgx/ra-tls/secret_prov_attest.c#L408)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Rather `sizeof(pf_key_t)` or `PF_KEY_SIZE`. But this would create a dependency between RA-TLS and PF (i.e. Gramine) internal headers. Not sure if we want this?
</blockquote></details>

Ah, ok. I'm fine.
___
*[`CI-Examples/ra-tls-secret-prov/secret_prov/client.manifest.template` line 18 at r1](https://reviewable.io/reviews/gramineproject/gramine/884#-NBHjy8y42mhFVyyaOJR:-NBIm1GNA8A0PvYpJ5AN:b-herish) ([raw file](https://github.com/gramineproject/gramine/blob/0537ac14dbffa7fb7449a8787a79f3ff11ee2384/CI-Examples/ra-tls-secret-prov/secret_prov/client.manifest.template#L18)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

But what trick? We just map that host file to `/ca.crt`, I don't see anything unexpected here...
</blockquote></details>

Well, that's a trick. Many people have a tough time understanding this logic in Gramine...
___
*[`CI-Examples/ra-tls-secret-prov/secret_prov_pf/client.c` line 14 at r1](https://reviewable.io/reviews/gramineproject/gramine/884#-NBHld6rBhCuNrARgVza:-NBImm-eCPRJ5Z0wO9lK:byegsj0) ([raw file](https://github.com/gramineproject/gramine/blob/0537ac14dbffa7fb7449a8787a79f3ff11ee2384/CI-Examples/ra-tls-secret-prov/secret_prov_pf/client.c#L14)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why a lie? That's exactly where it's mounted inside Gramine.
</blockquote></details>

But why so complicated? Why do we mount in `/files/`, not in `/`?
___
*[`CI-Examples/ra-tls-secret-prov/secret_prov_pf/client.manifest.template` line 22 at r1](https://reviewable.io/reviews/gramineproject/gramine/884#-NBHljzZCa60WDGbHB32:-NBImsxQ-ZuJDuc-Asaj:b64dib8) ([raw file](https://github.com/gramineproject/gramine/blob/0537ac14dbffa7fb7449a8787a79f3ff11ee2384/CI-Examples/ra-tls-secret-prov/secret_prov_pf/client.manifest.template#L22)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why a lie? Also, `files/` seems more appropriate IMO, as users will likely put more of them there when modifying this example.
</blockquote></details>

That's a weird argument to me. Are you sure that's better to have a pseudo-dir?


<!-- Sent from Reviewable.io -->

2022-09-07 00:24 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/884)* status: 21 of 23 files reviewed, 11 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/884#-NBHdS-HDDI1RS7uKCct:-NBKG_kO3FaNvZNvzes3:b4c9lyr) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> In the v1.3 release notes, probably?

How do we track these changes now? Can we make a draft? UPDATE: I created a draft in which I put all the breaking changes from v1.2 to v1.3 that I could think of.
</blockquote></details>

:thumbsup: 

___
___
*[`CI-Examples/ra-tls-secret-prov/Makefile` line 112 at r2](https://reviewable.io/reviews/gramineproject/gramine/884#-NBIlOu9BKzIuI19FlPG:-NBKGn3P92PsrrI8qJMQ:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/e0a4feb1aab9298a854b0540b89a9fb98d240a61/CI-Examples/ra-tls-secret-prov/Makefile#L112)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This is slightly different from other places. In other places, you have `.sgx` inside notdir
</blockquote></details>

Done.
___
*[`CI-Examples/ra-tls-secret-prov/Makefile` line 184 at r2](https://reviewable.io/reviews/gramineproject/gramine/884#-NBIlYaO1bOTz9-ecQRG:-NBKGrqs-DK25PPct2YX:byr4flj) ([raw file](https://github.com/gramineproject/gramine/blob/e0a4feb1aab9298a854b0540b89a9fb98d240a61/CI-Examples/ra-tls-secret-prov/Makefile#L184)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Then `wrap_key` and `input.txt` should be removed from here.
</blockquote></details>

Right.
___
*[`CI-Examples/ra-tls-secret-prov/README.md` line 18 at r1](https://reviewable.io/reviews/gramineproject/gramine/884#-NBHitiA-IJzqJBu8Qw9:-NBKI0il3O9tpU9MVl1E:b-sx1tyd) ([raw file](https://github.com/gramineproject/gramine/blob/0537ac14dbffa7fb7449a8787a79f3ff11ee2384/CI-Examples/ra-tls-secret-prov/README.md#L18)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, describe each of the three examples in `###` subsections or as a bullet list (under the `##` section with a title like "Three secret provisioning examples")
</blockquote></details>

Actually, I'm not sure how to do it. I'd need to copy paste this whole section between examples, or keep it deduplicated, but then we end up with what we have now.
___
*[`Documentation/attestation.rst` line 480 at r1](https://reviewable.io/reviews/gramineproject/gramine/884#-NBHmfBpA-U_PDwwjXkk:-NBKHsah2l2Q2qyplrrN:b4x748e) ([raw file](https://github.com/gramineproject/gramine/blob/0537ac14dbffa7fb7449a8787a79f3ff11ee2384/Documentation/attestation.rst#L480)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What I'm trying to say that a casual user (e.g. some AI/ML scientist) won't have a clue what you're talking about. Do we want to have it that cryptic for normal users? Maybe at least a link?
</blockquote></details>

Link to what? What do you propose to write here?
___
*[`CI-Examples/ra-tls-secret-prov/secret_prov/client.manifest.template` line 18 at r1](https://reviewable.io/reviews/gramineproject/gramine/884#-NBHjy8y42mhFVyyaOJR:-NBKGzlNA825J8UzZEWE:b-a7znlz) ([raw file](https://github.com/gramineproject/gramine/blob/0537ac14dbffa7fb7449a8787a79f3ff11ee2384/CI-Examples/ra-tls-secret-prov/secret_prov/client.manifest.template#L18)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Well, that's a trick. Many people have a tough time understanding this logic in Gramine...
</blockquote></details>

But this very line already contains both paths, it's IMO obvious that it makes them differ between host and Gramine.
/summon @boryspoplawski
___
*[`CI-Examples/ra-tls-secret-prov/secret_prov_pf/client.c` line 14 at r1](https://reviewable.io/reviews/gramineproject/gramine/884#-NBHld6rBhCuNrARgVza:-NBKHKnO-GOR2JEGs7uz:b-59zldz) ([raw file](https://github.com/gramineproject/gramine/blob/0537ac14dbffa7fb7449a8787a79f3ff11ee2384/CI-Examples/ra-tls-secret-prov/secret_prov_pf/client.c#L14)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

But why so complicated? Why do we mount in `/files/`, not in `/`?
</blockquote></details>

I expected that people will add more files as the first change in this example. And it showcases how to mount things nicely from the host.
___
*[`CI-Examples/ra-tls-secret-prov/secret_prov_pf/client.manifest.template` line 22 at r1](https://reviewable.io/reviews/gramineproject/gramine/884#-NBHljzZCa60WDGbHB32:-NBKHZkG9bruI_smvFMV:bfopl6q) ([raw file](https://github.com/gramineproject/gramine/blob/0537ac14dbffa7fb7449a8787a79f3ff11ee2384/CI-Examples/ra-tls-secret-prov/secret_prov_pf/client.manifest.template#L22)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

That's a weird argument to me. Are you sure that's better to have a pseudo-dir?
</blockquote></details>

What's wrong in having it? I really don't see any problem here - we're just taking a file from the host and specifying a path where to mount it inside Gramine.


<!-- Sent from Reviewable.io -->

2022-09-07 07:19 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/884)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[`CI-Examples/ra-tls-secret-prov/README.md` line 18 at r1](https://reviewable.io/reviews/gramineproject/gramine/884#-NBHitiA-IJzqJBu8Qw9:-NBLm26O8iPrF0-I7Xqs:bul9lnf) ([raw file](https://github.com/gramineproject/gramine/blob/0537ac14dbffa7fb7449a8787a79f3ff11ee2384/CI-Examples/ra-tls-secret-prov/README.md#L18)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Actually, I'm not sure how to do it. I'd need to copy paste this whole section between examples, or keep it deduplicated, but then we end up with what we have now.
</blockquote></details>

Well, here is another proposal.

Start this section with `There are three servers in this example:`. Then have a list with three items, describing how servers differ from each other. In other words, repeat the structure of `Secret Provisioning clients`.

Without this structure, the README has an effect of: we have some servers, and then some clients, and how they connect to each other is completely unspecified.
___
*[`CI-Examples/ra-tls-secret-prov/README.md` line 43 at r3](https://reviewable.io/reviews/gramineproject/gramine/884#-NBLmP3a6nDeZPbbE9zL:-NBLmP3a6nDeZPbbE9zM:b1ppob7) ([raw file](https://github.com/gramineproject/gramine/blob/dfc38652509698820d7275af93903097e5571b0a/CI-Examples/ra-tls-secret-prov/README.md#L43)):*
> ```Markdown
> There are three clients in this example:
> 
> 1. Minimal client. It relies on constructor-time secret provisioning and gets
> ```

For each of these clients, I would add
```
1. Minimal client (found under `secret_prov_minimal/`). It relies on ...
```
___
*[`Documentation/attestation.rst` line 480 at r1](https://reviewable.io/reviews/gramineproject/gramine/884#-NBHmfBpA-U_PDwwjXkk:-NBLnLnQ8mcHCRr_cKsd:b-dtwhjn) ([raw file](https://github.com/gramineproject/gramine/blob/0537ac14dbffa7fb7449a8787a79f3ff11ee2384/Documentation/attestation.rst#L480)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Link to what? What do you propose to write here?
</blockquote></details>

```
Provisioned secrets must be treated with utmost care, otherwise they could be
inadvertently leaked. For example, if a provisioned secret is a Base64 representation
of an encryption key, then the user should decode it from Base64 into binary using
side-channel-resistant functions (e.g., `mbedtls_base64_decode()`) instead of
non-crypto-safe functions (e.g., self-written decoding logic).
```
___
*[`CI-Examples/ra-tls-secret-prov/secret_prov_pf/client.c` line 14 at r1](https://reviewable.io/reviews/gramineproject/gramine/884#-NBHld6rBhCuNrARgVza:-NBLmp0sBDDMKE6mvc1u:b-org1ug) ([raw file](https://github.com/gramineproject/gramine/blob/0537ac14dbffa7fb7449a8787a79f3ff11ee2384/CI-Examples/ra-tls-secret-prov/secret_prov_pf/client.c#L14)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I expected that people will add more files as the first change in this example. And it showcases how to mount things nicely from the host.
</blockquote></details>

I feel like we're expecting too much from users of Gramine (yeah, I have a low bar). Summonning @boryspoplawski, we need a tie-breaker.


<!-- Sent from Reviewable.io -->

2022-09-07 09:16 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/884)* status: 21 of 23 files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[`CI-Examples/ra-tls-secret-prov/README.md` line 18 at r1](https://reviewable.io/reviews/gramineproject/gramine/884#-NBHitiA-IJzqJBu8Qw9:-NBM9BtM-O72A6SnWWpf:b-h43rks) ([raw file](https://github.com/gramineproject/gramine/blob/0537ac14dbffa7fb7449a8787a79f3ff11ee2384/CI-Examples/ra-tls-secret-prov/README.md#L18)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Well, here is another proposal.

Start this section with `There are three servers in this example:`. Then have a list with three items, describing how servers differ from each other. In other words, repeat the structure of `Secret Provisioning clients`.

Without this structure, the README has an effect of: we have some servers, and then some clients, and how they connect to each other is completely unspecified.
</blockquote></details>

Sounds good, done.
___
*[`CI-Examples/ra-tls-secret-prov/README.md` line 42 at r1](https://reviewable.io/reviews/gramineproject/gramine/884#-NBHjAoU7vpjnFbifKzO:-NBMAGVG-SGgo0wSzT7T:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/0537ac14dbffa7fb7449a8787a79f3ff11ee2384/CI-Examples/ra-tls-secret-prov/README.md#L42)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

See my comment above. It's not "three clients", it is "three examples".
</blockquote></details>

Done.
___
*[`CI-Examples/ra-tls-secret-prov/README.md` line 43 at r3](https://reviewable.io/reviews/gramineproject/gramine/884#-NBLmP3a6nDeZPbbE9zL:-NBMAZRsESCRf5FHP_jw:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/dfc38652509698820d7275af93903097e5571b0a/CI-Examples/ra-tls-secret-prov/README.md#L43)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

For each of these clients, I would add
```
1. Minimal client (found under `secret_prov_minimal/`). It relies on ...
```
</blockquote></details>

Done.
___
*[`Documentation/attestation.rst` line 480 at r1](https://reviewable.io/reviews/gramineproject/gramine/884#-NBHmfBpA-U_PDwwjXkk:-NBMCY8CDYsmyNNJKJKZ:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/0537ac14dbffa7fb7449a8787a79f3ff11ee2384/Documentation/attestation.rst#L480)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

```
Provisioned secrets must be treated with utmost care, otherwise they could be
inadvertently leaked. For example, if a provisioned secret is a Base64 representation
of an encryption key, then the user should decode it from Base64 into binary using
side-channel-resistant functions (e.g., `mbedtls_base64_decode()`) instead of
non-crypto-safe functions (e.g., self-written decoding logic).
```
</blockquote></details>

Done.
___
*[`CI-Examples/ra-tls-secret-prov/secret_prov_pf/client.c` line 14 at r1](https://reviewable.io/reviews/gramineproject/gramine/884#-NBHld6rBhCuNrARgVza:-NBMBD3t4CfLxoYnybpJ:bk6jlda) ([raw file](https://github.com/gramineproject/gramine/blob/0537ac14dbffa7fb7449a8787a79f3ff11ee2384/CI-Examples/ra-tls-secret-prov/secret_prov_pf/client.c#L14)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I feel like we're expecting too much from users of Gramine (yeah, I have a low bar). Summonning @boryspoplawski, we need a tie-breaker.
</blockquote></details>

One more note: This is analogous to how Docker works, so I'd say that it shouldn't be an unfamiliar concept for them.


<!-- Sent from Reviewable.io -->

2022-09-07 09:41 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/884)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[`CI-Examples/ra-tls-secret-prov/README.md` line 24 at r4](https://reviewable.io/reviews/gramineproject/gramine/884#-NBMJpM2CEWmt0gz_Mbg:-NBMJpM2CEWmt0gz_Mbh:b-1mxl8x) ([raw file](https://github.com/gramineproject/gramine/blob/40dd25de49f5d45ddd48c18a0f5ca3e824a6c3f6/CI-Examples/ra-tls-secret-prov/README.md#L24)):*
> ```Markdown
>    hardcoded secret.
> 2. More complex server (found under `secret_prov/`), which uses the negotiated
>    TLS connection to exchange more data with the enclave.
> ```

`with the enclave` -> `with the client enclave`
___
*[`CI-Examples/ra-tls-secret-prov/README.md` line 56 at r4](https://reviewable.io/reviews/gramineproject/gramine/884#-NBMJiCZ3RuhksqQmy5s:-NBMJiCZ3RuhksqQmy5t:b-bxv1pe) ([raw file](https://github.com/gramineproject/gramine/blob/40dd25de49f5d45ddd48c18a0f5ca3e824a6c3f6/CI-Examples/ra-tls-secret-prov/README.md#L56)):*
> ```Markdown
>    constructor-time secret provisioning and gets the first (and only) secret
>    from the environment variable `SECRET_PROVISION_SECRET_STRING`.
> 2. Feature-rich client (found under `secret_prov/`). It uses a programmatic C
> ```

`Feature-rich` -> `More complex` (for uniformity with the above text about servers)
___
*[`Documentation/attestation.rst` line 482 at r4](https://reviewable.io/reviews/gramineproject/gramine/884#-NBMJaqa7CAE_yp7Nsxs:-NBMJaqa7CAE_yp7Nsxt:b-vxt3cl) ([raw file](https://github.com/gramineproject/gramine/blob/40dd25de49f5d45ddd48c18a0f5ca3e824a6c3f6/Documentation/attestation.rst#L482)):*
> ```reStructuredText
>    base64-encoded encryption key, then the user should decode it from base64
>    into binary using side-channel-resistant functions (e.g.,
>    `mbedtls_base64_decode()`) instead of non-crypto-secure functions (e.g.,
> ```

Oops, this is RST, so we should have double-backticks.


<!-- Sent from Reviewable.io -->

2022-09-07 10:05 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/884)* status: 21 of 23 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[`CI-Examples/ra-tls-secret-prov/README.md` line 24 at r4](https://reviewable.io/reviews/gramineproject/gramine/884#-NBMJpM2CEWmt0gz_Mbg:-NBMOutqEMuDpYJdaF4b:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/40dd25de49f5d45ddd48c18a0f5ca3e824a6c3f6/CI-Examples/ra-tls-secret-prov/README.md#L24)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`with the enclave` -> `with the client enclave`
</blockquote></details>

Done.
___
*[`CI-Examples/ra-tls-secret-prov/README.md` line 56 at r4](https://reviewable.io/reviews/gramineproject/gramine/884#-NBMJiCZ3RuhksqQmy5s:-NBMP43-AgC_17K_he_3:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/40dd25de49f5d45ddd48c18a0f5ca3e824a6c3f6/CI-Examples/ra-tls-secret-prov/README.md#L56)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`Feature-rich` -> `More complex` (for uniformity with the above text about servers)
</blockquote></details>

Done.
___
*[`Documentation/attestation.rst` line 482 at r4](https://reviewable.io/reviews/gramineproject/gramine/884#-NBMJaqa7CAE_yp7Nsxs:-NBMOk4WBEL_bErAu_j2:bfv3b4d) ([raw file](https://github.com/gramineproject/gramine/blob/40dd25de49f5d45ddd48c18a0f5ca3e824a6c3f6/Documentation/attestation.rst#L482)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Oops, this is RST, so we should have double-backticks.
</blockquote></details>

Oops, good catch!


<!-- Sent from Reviewable.io -->

2022-09-07 10:34 UTC, dimakuv reviewed
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/884)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)



<!-- Sent from Reviewable.io -->

2022-09-10 00:27 UTC, boryspoplawski requested changes
> Reviewed 8 of 22 files at r1, 3 of 10 files at r2, 1 of 2 files at r3, 1 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/884)* status: all files reviewed, 13 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[`CI-Examples/ra-tls-secret-prov/Makefile` line 65 at r5](https://reviewable.io/reviews/gramineproject/gramine/884#-NBZVIL41nHmZE46eQVP:-NBZVIL41nHmZE46eQVQ:buey06b) ([raw file](https://github.com/gramineproject/gramine/blob/2154b23af2cb477581305d48943c454e4136941a/CI-Examples/ra-tls-secret-prov/Makefile#L65)):*
> ```Makefile
> 
> secret_prov_pf/server_epid: secret_prov_pf/server.c
> 	$(CC) $< $(CFLAGS) $(LDFLAGS) -lsecret_prov_verify_epid -pthread -o $@
> ```

Not blocking if you prefer to be super verbose, but these examples are mostly the same, so it makes sense to use only one rule for them



_Suggestion:_
```Makefile
%/server_epid: %/server.c
	$(CC) $< $(CFLAGS) $(LDFLAGS) -lsecret_prov_verify_epid -pthread -o $@
```
___
*[`CI-Examples/ra-tls-secret-prov/Makefile` line 77 at r5](https://reviewable.io/reviews/gramineproject/gramine/884#-NBZVlGw13hurFcuajbN:-NBZVlGw13hurFcuajbO:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/2154b23af2cb477581305d48943c454e4136941a/CI-Examples/ra-tls-secret-prov/Makefile#L77)):*
> ```Makefile
> 
> secret_prov_pf/server_dcap: secret_prov_pf/server.c
> 	$(CC) $< $(CFLAGS) $(LDFLAGS) -Wl,--no-as-needed -lsgx_urts -lsecret_prov_verify_dcap -pthread -o $@
> ```

ditto



_Suggestion:_
```Makefile
%/server_dcap: %/server.c
	$(CC) $< $(CFLAGS) $(LDFLAGS) -Wl,--no-as-needed -lsgx_urts -lsecret_prov_verify_dcap -pthread -o $@
```
___
*[`CI-Examples/ra-tls-secret-prov/Makefile` line 83 at r5](https://reviewable.io/reviews/gramineproject/gramine/884#-NBZWiWIA1Py-cZRteOh:-NBZWiWIA1Py-cZRteOi:btwasv4) ([raw file](https://github.com/gramineproject/gramine/blob/2154b23af2cb477581305d48943c454e4136941a/CI-Examples/ra-tls-secret-prov/Makefile#L83)):*
> ```Makefile
> 
> secret_prov_minimal/client: secret_prov_minimal/client.c
> 	$(CC) $< $(CFLAGS) $(LDFLAGS) -o $@
> ```

Why this and pf client below don't have to be linked with `secret_prov_attest`?
___
*[`CI-Examples/ra-tls-secret-prov/Makefile` line 93 at r5](https://reviewable.io/reviews/gramineproject/gramine/884#-NBZYDPU5ydnIPyaEH7I:-NBZYDPU5ydnIPyaEH7J:b-rzh6w) ([raw file](https://github.com/gramineproject/gramine/blob/2154b23af2cb477581305d48943c454e4136941a/CI-Examples/ra-tls-secret-prov/Makefile#L93)):*
> ```Makefile
> #       should be relative to the manifest, not to current dir) - drop `cd` and `notdir`.
> secret_prov_minimal/client.manifest: secret_prov_minimal/client.manifest.template
> 	cd secret_prov_minimal && \
> ```

You can do this V and have one rule for everything, if you're brave enough



_Suggestion:_
```Makefile
%/client.manifest: %/client.manifest.template
	cd $* && \
```
___
*[`CI-Examples/ra-tls-secret-prov/Makefile` line 100 at r5](https://reviewable.io/reviews/gramineproject/gramine/884#-NBZZGlS8UC-DKN-2fV3:-NBZZGlTDIAQTu5LJ0Tl:ba63m60) ([raw file](https://github.com/gramineproject/gramine/blob/2154b23af2cb477581305d48943c454e4136941a/CI-Examples/ra-tls-secret-prov/Makefile#L100)):*
> ```Makefile
> 		-Dra_client_spid=$(RA_CLIENT_SPID) \
> 		-Dra_client_linkable=$(RA_CLIENT_LINKABLE) \
> 		$(notdir $<) > $(notdir $@)
> ```

This is how we do it in make. Not blocking, since I guess `notdir` is obvious when read, and the proposed is arcane makefile knowledge.
ditto whole file



_Suggestion:_
```Makefile
$(<F) > $(@F)
```
___
*[`CI-Examples/ra-tls-secret-prov/Makefile` line 107 at r5](https://reviewable.io/reviews/gramineproject/gramine/884#-NBZYZ-12mPXSp7Td0WG:-NBZYZ-12mPXSp7Td0WH:b-pdxhn9) ([raw file](https://github.com/gramineproject/gramine/blob/2154b23af2cb477581305d48943c454e4136941a/CI-Examples/ra-tls-secret-prov/Makefile#L107)):*
> ```Makefile
> 	@:
> 
> .INTERMEDIATE: sgx_sign_secret_prov_minimal_client
> ```

But I have no idea how `.INTERMEDIATE` works with patterns (AD above comment), I guess there would have to be 3 of them explicitly listed anyway.
___
*[`CI-Examples/ra-tls-secret-prov/Makefile` line 173 at r5](https://reviewable.io/reviews/gramineproject/gramine/884#-NBZa5E21k_Q-j5oC9TH:-NBZa5E21k_Q-j5oC9TI:bdccmcb) ([raw file](https://github.com/gramineproject/gramine/blob/2154b23af2cb477581305d48943c454e4136941a/CI-Examples/ra-tls-secret-prov/Makefile#L173)):*
> ```Makefile
> 
> secret_prov_pf/enc_files/input.txt: secret_prov_pf/wrap_key secret_prov_pf/plain_files/input.txt
> 	cd secret_prov_pf && \
> ```

Why this `cd`?
___
*[`CI-Examples/ra-tls-secret-prov/Makefile` line 246 at r5](https://reviewable.io/reviews/gramineproject/gramine/884#-NBZeiGB1Cox6Bq6-rxa:-NBZeiGB1Cox6Bq6-rxb:bwn0qud) ([raw file](https://github.com/gramineproject/gramine/blob/2154b23af2cb477581305d48943c454e4136941a/CI-Examples/ra-tls-secret-prov/Makefile#L246)):*
> ```Makefile
> clean:
> 	$(RM) OUTPUT
> 	cd secret_prov_minimal; $(RM) client server_* *.token *.sig *.manifest.sgx *.manifest
> ```

Why these `cd`s?
___
*[`CI-Examples/ra-tls-secret-prov/README.md` line 7 at r5](https://reviewable.io/reviews/gramineproject/gramine/884#-NBZgn3g9ijz46FeIn1O:-NBZgn3g9ijz46FeIn1P:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/2154b23af2cb477581305d48943c454e4136941a/CI-Examples/ra-tls-secret-prov/README.md#L7)):*
> ```Markdown
> library.
> 
> These examples use the Secret Provisioning libraries `secret_prov_attest.so` for
> ```





_Suggestion:_
```Markdown
library
```
___
*[`CI-Examples/ra-tls-secret-prov/README.md` line 9 at r5](https://reviewable.io/reviews/gramineproject/gramine/884#-NBZh49N5v3iGdp_Xk3Q:-NBZh49OB5Sc871uxdQF:bq76u1d) ([raw file](https://github.com/gramineproject/gramine/blob/2154b23af2cb477581305d48943c454e4136941a/CI-Examples/ra-tls-secret-prov/README.md#L9)):*
> ```Markdown
> These examples use the Secret Provisioning libraries `secret_prov_attest.so` for
> the clients and `secret_prov_verify_epid.so`/`secret_prov_verify_dcap.so` for
> the servers. These libraries are installed together with Gramine (but for DCAP
> ```

Isn't it only one library?
___
*[`CI-Examples/ra-tls-secret-prov/README.md` line 27 at r5](https://reviewable.io/reviews/gramineproject/gramine/884#-NBZiKzlEwdp4zzEGjSn:-NBZiKzlEwdp4zzEGjSo:b-98xuh7) ([raw file](https://github.com/gramineproject/gramine/blob/2154b23af2cb477581305d48943c454e4136941a/CI-Examples/ra-tls-secret-prov/README.md#L27)):*
> ```Markdown
> 3. Encrypted files server (found under `secret_prov_pf/`) - similarly to the
>    minimal client, it sends only a single secret, but loads it from a file, with
>    intended purpose of provisioning the encrypted files key to client enclaves.
> ```

I don't think it's clear that the file actually contains the key. Maybe `... with intended purpose of the secret being a encrypted files key to be provisioned to client enclaves`?
___
*[`CI-Examples/ra-tls-secret-prov/secret_prov_minimal/server.c` line 12 at r5](https://reviewable.io/reviews/gramineproject/gramine/884#-NBZmJO8-qhm_0gf7qsG:-NBZmJO8-qhm_0gf7qsH:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/2154b23af2cb477581305d48943c454e4136941a/CI-Examples/ra-tls-secret-prov/secret_prov_minimal/server.c#L12)):*
> ```C
> #define SRV_KEY_PATH "../ssl/server.key"
> 
> int main() {
> ```





_Suggestion:_
```C
int main(void)
```
___
*[`CI-Examples/ra-tls-secret-prov/secret_prov_minimal/server.c` line 13 at r5](https://reviewable.io/reviews/gramineproject/gramine/884#-NBZmFRt0L7ytJF2tcPb:-NBZmFRt0L7ytJF2tcPc:b4q2s84) ([raw file](https://github.com/gramineproject/gramine/blob/2154b23af2cb477581305d48943c454e4136941a/CI-Examples/ra-tls-secret-prov/secret_prov_minimal/server.c#L13)):*
> ```C
> [...]

2022-09-10 14:50 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/884)* status: 17 of 23 files reviewed, 13 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[`CI-Examples/ra-tls-secret-prov/Makefile` line 65 at r5](https://reviewable.io/reviews/gramineproject/gramine/884#-NBZVIL41nHmZE46eQVP:-NBbnFpXDgTiaAfF3iHI:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/2154b23af2cb477581305d48943c454e4136941a/CI-Examples/ra-tls-secret-prov/Makefile#L65)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Not blocking if you prefer to be super verbose, but these examples are mostly the same, so it makes sense to use only one rule for them
</blockquote></details>

Done.
___
*[`CI-Examples/ra-tls-secret-prov/Makefile` line 77 at r5](https://reviewable.io/reviews/gramineproject/gramine/884#-NBZVlGw13hurFcuajbN:-NBbnU-2EdamOTLmIOU4:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/2154b23af2cb477581305d48943c454e4136941a/CI-Examples/ra-tls-secret-prov/Makefile#L77)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`CI-Examples/ra-tls-secret-prov/Makefile` line 83 at r5](https://reviewable.io/reviews/gramineproject/gramine/884#-NBZWiWIA1Py-cZRteOh:-NBbnrhADXwStJQM_GhR:b-9oilj2) ([raw file](https://github.com/gramineproject/gramine/blob/2154b23af2cb477581305d48943c454e4136941a/CI-Examples/ra-tls-secret-prov/Makefile#L83)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why this and pf client below don't have to be linked with `secret_prov_attest`?
</blockquote></details>

Because only `secret_prov` example is using C API provided by this library, others are just plain Linux binaries with some additional stuff being LD_PRELOADed.
___
*[`CI-Examples/ra-tls-secret-prov/Makefile` line 93 at r5](https://reviewable.io/reviews/gramineproject/gramine/884#-NBZYDPU5ydnIPyaEH7I:-NBbo7Y78asSqGpMO4Tm:bss6edp) ([raw file](https://github.com/gramineproject/gramine/blob/2154b23af2cb477581305d48943c454e4136941a/CI-Examples/ra-tls-secret-prov/Makefile#L93)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

You can do this V and have one rule for everything, if you're brave enough
</blockquote></details>

Yeah, I thought about using Make magic, but decided that it's too much here. I really don't like that in Make any two special characters combined mean something, it's unreadable to me ;)
___
*[`CI-Examples/ra-tls-secret-prov/Makefile` line 100 at r5](https://reviewable.io/reviews/gramineproject/gramine/884#-NBZZGlS8UC-DKN-2fV3:-NBboRYB8mz4ya4_Okvx:b-m3vp2i) ([raw file](https://github.com/gramineproject/gramine/blob/2154b23af2cb477581305d48943c454e4136941a/CI-Examples/ra-tls-secret-prov/Makefile#L100)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This is how we do it in make. Not blocking, since I guess `notdir` is obvious when read, and the proposed is arcane makefile knowledge.
ditto whole file
</blockquote></details>

That's too much for my taste :)
___
*[`CI-Examples/ra-tls-secret-prov/Makefile` line 173 at r5](https://reviewable.io/reviews/gramineproject/gramine/884#-NBZa5E21k_Q-j5oC9TH:-NBboZY0Ds8aS5U7zWyY:bp92wmw) ([raw file](https://github.com/gramineproject/gramine/blob/2154b23af2cb477581305d48943c454e4136941a/CI-Examples/ra-tls-secret-prov/Makefile#L173)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why this `cd`?
</blockquote></details>

The path encrypted inside the encrypted file header needs to match the in-Gramine mount path, and I think we still don't expose a cmdline switch to set it manually when encrypting a file.
___
*[`CI-Examples/ra-tls-secret-prov/Makefile` line 246 at r5](https://reviewable.io/reviews/gramineproject/gramine/884#-NBZeiGB1Cox6Bq6-rxa:-NBbopap89qan3NjnUn0:bs0dfgj) ([raw file](https://github.com/gramineproject/gramine/blob/2154b23af2cb477581305d48943c454e4136941a/CI-Examples/ra-tls-secret-prov/Makefile#L246)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why these `cd`s?
</blockquote></details>

Less copy-paste. Or maybe you mean that you prefer double-wildcards? (`$(RM) */client server_*`, etc.)
___
*[`CI-Examples/ra-tls-secret-prov/README.md` line 7 at r5](https://reviewable.io/reviews/gramineproject/gramine/884#-NBZgn3g9ijz46FeIn1O:-NBbpFbqDiX2SH8QwJKu:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/2154b23af2cb477581305d48943c454e4136941a/CI-Examples/ra-tls-secret-prov/README.md#L7)):*
> ```Markdown
> library.
> 
> These examples use the Secret Provisioning libraries `secret_prov_attest.so` for
> ```

Done.
___
*[`CI-Examples/ra-tls-secret-prov/README.md` line 9 at r5](https://reviewable.io/reviews/gramineproject/gramine/884#-NBZh49N5v3iGdp_Xk3Q:-NBbpKEC3R2fdIPfgXjz:bak0k74) ([raw file](https://github.com/gramineproject/gramine/blob/2154b23af2cb477581305d48943c454e4136941a/CI-Examples/ra-tls-secret-prov/README.md#L9)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Isn't it only one library?
</blockquote></details>

I think here we want to say that `secret_prov_attest.so` and `secret_prov_verify_{epid,dcap}.so` are installed?
___
*[`CI-Examples/ra-tls-secret-prov/README.md` line 27 at r5](https://reviewable.io/reviews/gramineproject/gramine/884#-NBZiKzlEwdp4zzEGjSn:-NBbplTT2fyoEZni6Lio:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/2154b23af2cb477581305d48943c454e4136941a/CI-Examples/ra-tls-secret-prov/README.md#L27)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I don't think it's clear that the file actually contains the key. Maybe `... with intended purpose of the secret being a encrypted files key to be provisioned to client enclaves`?
</blockquote></details>

Done.
___
*[`CI-Examples/ra-tls-secret-prov/secret_prov_minimal/server.c` line 12 at r5](https://reviewable.io/reviews/gramineproject/gramine/884#-NBZmJO8-qhm_0gf7qsG:-NBbqN-t5bB2JQSyEMsG:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/2154b23af2cb477581305d48943c454e4136941a/CI-Examples/ra-tls-secret-prov/secret_prov_minimal/server.c#L12)):*
> ```C
> #define SRV_KEY_PATH "../ssl/server.key"
> 
> int main() {
> ```

Done.
___
*[`CI-Examples/ra-tls-secret-prov/secret_prov_minimal/server.c` line 13 at r5](https://reviewable.io/reviews/gramineproject/gramine/884#-NBZmFRt0L7ytJF2tcPb:-NBbqObH0qwk8u1AR8Qd:b-t8fyss) ([raw file](https://github.com/gramineproject/gramine/blob/2154b23af2cb477581305d48943c454e4136941a/CI-Examples/ra-tls-secret-prov/secret_prov_minimal/server.c#L13)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Either make this global, or remove `g_`
</blockquote></details>

Oops. Fixed.
___
*[`CI-Examples/ra-tls-secret-prov/secret_prov/client.manifest.template` line 18 at r1](https://reviewable.io/reviews/gramineproject/gramine/884#-NBHjy8y42mhFVyyaOJR:-NBbpycg9jFBWciYkWPo:bxm0o19) ([raw file](https://github.com/gramineproject/gramine/blob/0537ac14dbffa7fb7449a8787a79f3ff11ee2384/CI-Examples/ra-tls-secret-prov/secret_prov/client.manifest.template#L18)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I'm confused. What "trick" are we talking about?
</blockquote></details>

I think @dimakuv considers `path` != `uri` being "a trick", which I don't see why :)


<!-- Sent from Reviewable.io -->

2022-09-10 21:08 UTC, boryspoplawski requested changes
> Reviewed 5 of 6 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/884)* status: 22 of 23 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[`CI-Examples/ra-tls-secret-prov/Makefile` line 83 at r5](https://reviewable.io/reviews/gramineproject/gramine/884#-NBZWiWIA1Py-cZRteOh:-NBd9kbq4at-d31tNXoS:b-84x09n) ([raw file](https://github.com/gramineproject/gramine/blob/2154b23af2cb477581305d48943c454e4136941a/CI-Examples/ra-tls-secret-prov/Makefile#L83)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Because only `secret_prov` example is using C API provided by this library, others are just plain Linux binaries with some additional stuff being LD_PRELOADed.
</blockquote></details>

Ah, magic LD_PRELOAD. So up to you, you can use one rule with every target having this `-l`, which will work and be shorter, but won't be clear why everything links to it. I guess it wouldn't make sense, so current version is fine.
___
*[`CI-Examples/ra-tls-secret-prov/Makefile` line 93 at r5](https://reviewable.io/reviews/gramineproject/gramine/884#-NBZYDPU5ydnIPyaEH7I:-NBdALsaEDLDcrBwDEPJ:b-rsv0cv) ([raw file](https://github.com/gramineproject/gramine/blob/2154b23af2cb477581305d48943c454e4136941a/CI-Examples/ra-tls-secret-prov/Makefile#L93)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Yeah, I thought about using Make magic, but decided that it's too much here. I really don't like that in Make any two special characters combined mean something, it's unreadable to me ;)
</blockquote></details>

I agree, it's something you have to get used to (if you use it often enough) otherwise it's just some unparsable magic you have to check against docs every time.
___
*[`CI-Examples/ra-tls-secret-prov/Makefile` line 107 at r5](https://reviewable.io/reviews/gramineproject/gramine/884#-NBZYZ-12mPXSp7Td0WG:-NBdBurxASCeb2KSf9M3:bnndmy9) ([raw file](https://github.com/gramineproject/gramine/blob/2154b23af2cb477581305d48943c454e4136941a/CI-Examples/ra-tls-secret-prov/Makefile#L107)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

But I have no idea how `.INTERMEDIATE` works with patterns (AD above comment), I guess there would have to be 3 of them explicitly listed anyway.
</blockquote></details>

Since you used patters in other targets, how about this?
___
*[`CI-Examples/ra-tls-secret-prov/Makefile` line 173 at r5](https://reviewable.io/reviews/gramineproject/gramine/884#-NBZa5E21k_Q-j5oC9TH:-NBdAtKf0mKVv9bg1ZIT:ba69gw0) ([raw file](https://github.com/gramineproject/gramine/blob/2154b23af2cb477581305d48943c454e4136941a/CI-Examples/ra-tls-secret-prov/Makefile#L173)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

The path encrypted inside the encrypted file header needs to match the in-Gramine mount path, and I think we still don't expose a cmdline switch to set it manually when encrypting a file.
</blockquote></details>

This is one big usability oof. Or maybe not, we need some rules for handling host paths, and actually `cwd` makes sense (on paths that are not explicitly global). Relative to manifest is also fine, or even better, doesn't matter here.
___
*[`CI-Examples/ra-tls-secret-prov/Makefile` line 246 at r5](https://reviewable.io/reviews/gramineproject/gramine/884#-NBZeiGB1Cox6Bq6-rxa:-NBdBRFO0cGHpN8t_xY2:bafzal1) ([raw file](https://github.com/gramineproject/gramine/blob/2154b23af2cb477581305d48943c454e4136941a/CI-Examples/ra-tls-secret-prov/Makefile#L246)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Less copy-paste. Or maybe you mean that you prefer double-wildcards? (`$(RM) */client server_*`, etc.)
</blockquote></details>

Idk, wildcards are ugly, `cd` is ugly, we are doomed.
___
*[`CI-Examples/ra-tls-secret-prov/Makefile` line 102 at r6](https://reviewable.io/reviews/gramineproject/gramine/884#-NBdC1SpAtwHol-Lq84b:-NBdC1SpAtwHol-Lq84c:b-yjg231) ([raw file](https://github.com/gramineproject/gramine/blob/cd267fdc72a281bf3fd04e47e5bd40620ef1efea/CI-Examples/ra-tls-secret-prov/Makefile#L102)):*
> ```Makefile
> 		--output $(notdir $<.sgx)
> 
> secret_prov_minimal/client.token: secret_prov_minimal/client.sig
> ```

and this?
___
*[`CI-Examples/ra-tls-secret-prov/README.md` line 9 at r5](https://reviewable.io/reviews/gramineproject/gramine/884#-NBZh49N5v3iGdp_Xk3Q:-NBdCGG78I5f5_QIBt_z:b9xxg9e) ([raw file](https://github.com/gramineproject/gramine/blob/2154b23af2cb477581305d48943c454e4136941a/CI-Examples/ra-tls-secret-prov/README.md#L9)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I think here we want to say that `secret_prov_attest.so` and `secret_prov_verify_{epid,dcap}.so` are installed?
</blockquote></details>

Ah, if read this way (which I guess is the obvious one) it makes sense.
___
*[`CI-Examples/ra-tls-secret-prov/secret_prov/client.manifest.template` line 18 at r1](https://reviewable.io/reviews/gramineproject/gramine/884#-NBHjy8y42mhFVyyaOJR:-NBdCitk3aWyqpKPFq4A:b-ajf3iv) ([raw file](https://github.com/gramineproject/gramine/blob/0537ac14dbffa7fb7449a8787a79f3ff11ee2384/CI-Examples/ra-tls-secret-prov/secret_prov/client.manifest.template#L18)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I think @dimakuv considers `path` != `uri` being "a trick", which I don't see why :)
</blockquote></details>

If that's the case, then I do agree that's not a trick, but normal usage. In most cases these paths will be different (except for gsc and such, where they will be the same).


<!-- Sent from Reviewable.io -->

2022-09-10 23:15 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/884)* status: 22 of 23 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[`CI-Examples/ra-tls-secret-prov/Makefile` line 83 at r5](https://reviewable.io/reviews/gramineproject/gramine/884#-NBZWiWIA1Py-cZRteOh:-NBdeaFH-V49hSRYBYa0:b8ta1g9) ([raw file](https://github.com/gramineproject/gramine/blob/2154b23af2cb477581305d48943c454e4136941a/CI-Examples/ra-tls-secret-prov/Makefile#L83)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Ah, magic LD_PRELOAD. So up to you, you can use one rule with every target having this `-l`, which will work and be shorter, but won't be clear why everything links to it. I guess it wouldn't make sense, so current version is fine.
</blockquote></details>

Yeah, I prefer the current version.
___
*[`CI-Examples/ra-tls-secret-prov/Makefile` line 93 at r5](https://reviewable.io/reviews/gramineproject/gramine/884#-NBZYDPU5ydnIPyaEH7I:-NBdeiEM9foJZh5yj21L:br5tk4c) ([raw file](https://github.com/gramineproject/gramine/blob/2154b23af2cb477581305d48943c454e4136941a/CI-Examples/ra-tls-secret-prov/Makefile#L93)):*
> some unparsable magic you have to check against docs every time

That's exactly what I do each time I use Make, despite using it from time to time since like 10 years... You just can't learn this syntax and always need to google it.
___
*[`CI-Examples/ra-tls-secret-prov/Makefile` line 107 at r5](https://reviewable.io/reviews/gramineproject/gramine/884#-NBZYZ-12mPXSp7Td0WG:-NBdexS6-PgClW4IFEay:b-kn6yh1) ([raw file](https://github.com/gramineproject/gramine/blob/2154b23af2cb477581305d48943c454e4136941a/CI-Examples/ra-tls-secret-prov/Makefile#L107)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Since you used patters in other targets, how about this?
</blockquote></details>

I'm not sure if it works with this weird workaround for missing `:&` and I'm not brave enough to try ;)
___
*[`CI-Examples/ra-tls-secret-prov/Makefile` line 246 at r5](https://reviewable.io/reviews/gramineproject/gramine/884#-NBZeiGB1Cox6Bq6-rxa:-NBdfY9L0xtqDyAE21BX:bkglepv) ([raw file](https://github.com/gramineproject/gramine/blob/2154b23af2cb477581305d48943c454e4136941a/CI-Examples/ra-tls-secret-prov/Makefile#L246)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Idk, wildcards are ugly, `cd` is ugly, we are doomed.
</blockquote></details>

¯\\\_(ツ)\_/¯
___
*[`CI-Examples/ra-tls-secret-prov/Makefile` line 102 at r6](https://reviewable.io/reviews/gramineproject/gramine/884#-NBdC1SpAtwHol-Lq84b:-NBdf8VZAHzyhSZnHgR0:b2xao7n) ([raw file](https://github.com/gramineproject/gramine/blob/cd267fdc72a281bf3fd04e47e5bd40620ef1efea/CI-Examples/ra-tls-secret-prov/Makefile#L102)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

and this?
</blockquote></details>

I would either wildcard all clients together or none, not just some part of its build outputs.


<!-- Sent from Reviewable.io -->

2022-09-11 19:30 UTC, boryspoplawski requested changes
> Reviewed 3 of 22 files at r1, 5 of 10 files at r2, 1 of 2 files at r5, 1 of 6 files at r6.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/884)* status: all files reviewed, 14 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`CI-Examples/ra-tls-secret-prov/Makefile` line 107 at r5](https://reviewable.io/reviews/gramineproject/gramine/884#-NBZYZ-12mPXSp7Td0WG:-NBggYojACdoH9xLUn3s:b4lr4wh) ([raw file](https://github.com/gramineproject/gramine/blob/2154b23af2cb477581305d48943c454e4136941a/CI-Examples/ra-tls-secret-prov/Makefile#L107)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'm not sure if it works with this weird workaround for missing `:&` and I'm not brave enough to try ;)
</blockquote></details>

You would just need 3 `.INTERMEDIATE` lines, the target rule itself should work
___
*[`CI-Examples/ra-tls-secret-prov/Makefile` line 102 at r6](https://reviewable.io/reviews/gramineproject/gramine/884#-NBdC1SpAtwHol-Lq84b:-NBggmNV03MPv-vM-TX7:bmw79ou) ([raw file](https://github.com/gramineproject/gramine/blob/cd267fdc72a281bf3fd04e47e5bd40620ef1efea/CI-Examples/ra-tls-secret-prov/Makefile#L102)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I would either wildcard all clients together or none, not just some part of its build outputs.
</blockquote></details>

Actually, for tokens would could have a general rune, there are no options you can change when generating one.
___
*[`CI-Examples/ra-tls-secret-prov/secret_prov/server.c` line 5 at r6](https://reviewable.io/reviews/gramineproject/gramine/884#-NBhtEHx43D8hUvc7256:-NBhtEHx43D8hUvc7257:bbf56uu) ([raw file](https://github.com/gramineproject/gramine/blob/cd267fdc72a281bf3fd04e47e5bd40620ef1efea/CI-Examples/ra-tls-secret-prov/secret_prov/server.c#L5)):*
> ```C
> 
> #include <assert.h>
> #include <errno.h>
> ```

Not needed? Please clean up the whole list
___
*[`CI-Examples/ra-tls-secret-prov/secret_prov/server.c` line 21 at r6](https://reviewable.io/reviews/gramineproject/gramine/884#-NBhl-yg9RjPAfp4Q22y:-NBhl-yg9RjPAfp4Q22z:b-crh0jd) ([raw file](https://github.com/gramineproject/gramine/blob/cd267fdc72a281bf3fd04e47e5bd40620ef1efea/CI-Examples/ra-tls-secret-prov/secret_prov/server.c#L21)):*
> ```C
> #define PORT "4433"
> #define EXPECTED_STRING "MORE"
> #define SECOND_STRING "42" /* answer to ultimate question of life, universe, and everything */
> ```

I don't like this name. Where is `FIRST_STRING`? We only have some local variable in `main` which has `FIRST_SECRET` as a content.
___
*[`CI-Examples/ra-tls-secret-prov/secret_prov/server.c` line 94 at r6](https://reviewable.io/reviews/gramineproject/gramine/884#-NBhkgRxCtxOEqsjHTt_:-NBhkgRxCtxOEqsjHTta:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/cd267fdc72a281bf3fd04e47e5bd40620ef1efea/CI-Examples/ra-tls-secret-prov/secret_prov/server.c#L94)):*
> ```C
>         return ret;
> 
>     uint8_t g_secret[] = "FIRST_SECRET";
> ```





_Suggestion:_
```C
secret
```
___
*[`Documentation/tutorials/pytorch/index.rst` line 414 at r6](https://reviewable.io/reviews/gramineproject/gramine/884#-NBhwGHf7BkyepwOm91l:-NBhwGHf7BkyepwOm91m:b-jjbs7n) ([raw file](https://github.com/gramineproject/gramine/blob/cd267fdc72a281bf3fd04e47e5bd40620ef1efea/Documentation/tutorials/pytorch/index.rst#L414)):*
> ```reStructuredText
> 
> The user must encrypt all input files: ``input.jpg``, ``classes.txt``, and
> ``alexnet-pretrained.pt``. For simplicity, we re-use the already-existing
> ```

Don't we now generate the key in `make`? It's not already-existing then...
___
*[`libos/src/fs/libos_fs_encrypted.c` line 198 at r6](https://reviewable.io/reviews/gramineproject/gramine/884#-NBhyjbe-feczWL8cCO7:-NBhyjbe-feczWL8cCO8:byrf3uv) ([raw file](https://github.com/gramineproject/gramine/blob/cd267fdc72a281bf3fd04e47e5bd40620ef1efea/libos/src/fs/libos_fs_encrypted.c#L198)):*
> ```C
> }
> 
> /* Used only in debug code / by deprecated options, no need to be side-channel-resistant. */
> ```

Is it ok that a deprecated option is insecure? We don't mark them as insecure anywhere.
___
*[`tools/sgx/ra-tls/secret_prov_attest.c` line 415 at r6](https://reviewable.io/reviews/gramineproject/gramine/884#-NBi0B0e7YFdCghkHdPe:-NBi0B0e7YFdCghkHdPf:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/cd267fdc72a281bf3fd04e47e5bd40620ef1efea/tools/sgx/ra-tls/secret_prov_attest.c#L415)):*
> ```C
> 
>             char path_buf[256];
>             if (snprintf(path_buf, 256, "/dev/attestation/keys/%s", key_name) >= 256) {
> ```





_Suggestion:_
```C
if (snprintf(path_buf, sizeof(path_buf), "/dev/attestation/keys/%s", key_name) >= sizeof(path_buf)) {
```
___
*[`CI-Examples/ra-tls-secret-prov/secret_prov_pf/client.c` line 14 at r1](https://reviewable.io/reviews/gramineproject/gramine/884#-NBHld6rBhCuNrARgVza:-NBhmmuqClCd09M5cCrj:b-qxllgs) ([raw file](https://github.com/gramineproject/gramine/blob/0537ac14dbffa7fb7449a8787a79f3ff11ee2384/CI-Examples/ra-tls-secret-prov/secret_prov_pf/client.c#L14)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

One more note: This is analogous to how Docker works, so I'd say that it shouldn't be an unfamiliar concept for them.
</blockquote></details>

I'm not sure what options we have here, but FWIW I like the idea of having one mounted directory with all input encrypted files, which I guess this `files/` is
___
*[`CI-Examples/ra-tls-secret-prov/secret_prov_pf/client.manifest.template` line 24 at r6](https://reviewable.io/reviews/gramineproject/gramine/884#-NBhqn_Z3f7qQvf2S_L0:-NBhqn_Z3f7qQvf2S_L1:bwtl90o) ([raw file](https://github.com/gramineproject/gramine/blob/cd267fdc72a281bf3fd04e47e5bd40620ef1efea/CI-Examples/ra-tls-secret-prov/secret_prov_pf/client.manifest.template#L24)):*
> ```
>   { path = "/client", uri = "file:client" },
>   { path = "/ca.crt", uri = "file:../ssl/ca.crt" },
>   { path = "/files/input.txt", uri = "file:enc_files/input.txt", type = "encrypted" },
> ```

Shouldn't this be



_Suggestion:_
```
{ path = "/files/", uri = "file:enc_files/", type = "encrypted" }
```
___
*[`CI-Examples/ra-tls-secret-prov/secret_prov_pf/server.c` line 50 at r1](https://reviewable.io/reviews/gramineproject/gramine/884#-NBHlukP9lC1qQXvLa4u:-NBhterH-sl83cP_Vtbh:brotpca) ([raw file](https://github.com/gramineproject/gramine/blob/0537ac14dbffa7fb7449a8787a79f3ff11ee2384/CI-Examples/ra-tls-secret-prov/secret_prov_pf/server.c#L50)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

To lie next to the array, and I don't want to make the array global, it's ugly.
</blockquote></details>

Still, why not have this define at the top and array here as local?


<!-- Sent from Reviewable.io -->

2022-09-12 00:11 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/884)* status: 20 of 23 files reviewed, 14 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[`CI-Examples/ra-tls-secret-prov/Makefile` line 107 at r5](https://reviewable.io/reviews/gramineproject/gramine/884#-NBZYZ-12mPXSp7Td0WG:-NBiwMyr2Tg9o_-htsBW:b-tenwdt) ([raw file](https://github.com/gramineproject/gramine/blob/2154b23af2cb477581305d48943c454e4136941a/CI-Examples/ra-tls-secret-prov/Makefile#L107)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

You would just need 3 `.INTERMEDIATE` lines, the target rule itself should work
</blockquote></details>

Yeah, but see the other discussion.
___
*[`CI-Examples/ra-tls-secret-prov/Makefile` line 102 at r6](https://reviewable.io/reviews/gramineproject/gramine/884#-NBdC1SpAtwHol-Lq84b:-NBiwEqZ92iXgqRACwW-:bh4mz0x) ([raw file](https://github.com/gramineproject/gramine/blob/cd267fdc72a281bf3fd04e47e5bd40620ef1efea/CI-Examples/ra-tls-secret-prov/Makefile#L102)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Actually, for tokens would could have a general rune, there are no options you can change when generating one.
</blockquote></details>

Yeah, but I don't like the idea of building all the clients partially separately, but also partially by some shared pattern-generated rules. Right now you have a small copy-paste, but all clients have their own, independent sections in the Makefile.
___
*[`CI-Examples/ra-tls-secret-prov/secret_prov/server.c` line 5 at r6](https://reviewable.io/reviews/gramineproject/gramine/884#-NBhtEHx43D8hUvc7256:-NBiwmcw2Uxy6hFcs0gj:bgi6n0d) ([raw file](https://github.com/gramineproject/gramine/blob/cd267fdc72a281bf3fd04e47e5bd40620ef1efea/CI-Examples/ra-tls-secret-prov/secret_prov/server.c#L5)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Not needed? Please clean up the whole list
</blockquote></details>

What about `ECONNRESET` and other constants?
___
*[`CI-Examples/ra-tls-secret-prov/secret_prov/server.c` line 21 at r6](https://reviewable.io/reviews/gramineproject/gramine/884#-NBhl-yg9RjPAfp4Q22y:-NBix7UhE5VT0SXw8Ivz:b51mkc0) ([raw file](https://github.com/gramineproject/gramine/blob/cd267fdc72a281bf3fd04e47e5bd40620ef1efea/CI-Examples/ra-tls-secret-prov/secret_prov/server.c#L21)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I don't like this name. Where is `FIRST_STRING`? We only have some local variable in `main` which has `FIRST_SECRET` as a content.
</blockquote></details>

No idea how to rename it, I didn't touch this part in this PR. But I also don't like this name.
___
*[`CI-Examples/ra-tls-secret-prov/secret_prov/server.c` line 94 at r6](https://reviewable.io/reviews/gramineproject/gramine/884#-NBhkgRxCtxOEqsjHTt_:-NBixMnU231cRHEMfQ9D:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/cd267fdc72a281bf3fd04e47e5bd40620ef1efea/CI-Examples/ra-tls-secret-prov/secret_prov/server.c#L94)):*
> ```C
>         return ret;
> 
>     uint8_t g_secret[] = "FIRST_SECRET";
> ```

Done.
___
*[`Documentation/tutorials/pytorch/index.rst` line 414 at r6](https://reviewable.io/reviews/gramineproject/gramine/884#-NBhwGHf7BkyepwOm91l:-NBiz0FBB1M2qEL13IGh:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/cd267fdc72a281bf3fd04e47e5bd40620ef1efea/Documentation/tutorials/pytorch/index.rst#L414)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Don't we now generate the key in `make`? It's not already-existing then...
</blockquote></details>

Done.
___
*[`libos/src/fs/libos_fs_encrypted.c` line 198 at r6](https://reviewable.io/reviews/gramineproject/gramine/884#-NBhyjbe-feczWL8cCO7:-NBiz7ZZCkX1SgfJ61n6:b-80hkka) ([raw file](https://github.com/gramineproject/gramine/blob/cd267fdc72a281bf3fd04e47e5bd40620ef1efea/libos/src/fs/libos_fs_encrypted.c#L198)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Is it ok that a deprecated option is insecure? We don't mark them as insecure anywhere.
</blockquote></details>

To be honest, I just didn't care about this case, because:
- it's a deprecated option
- the leak is rather negligible unless you get _super_ unlucky with the compilation
- it's not trivial to fix it for the old API
___
*[`tools/sgx/ra-tls/secret_prov_attest.c` line 415 at r6](https://reviewable.io/reviews/gramineproject/gramine/884#-NBi0B0e7YFdCghkHdPe:-NBizy3l2SpNiQitXoSw:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/cd267fdc72a281bf3fd04e47e5bd40620ef1efea/tools/sgx/ra-tls/secret_prov_attest.c#L415)):*
> ```C
> 
>             char path_buf[256];
>             if (snprintf(path_buf, 256, "/dev/attestation/keys/%s", key_name) >= 256) {
> ```

Done.
___
*[`CI-Examples/ra-tls-secret-prov/secret_prov_pf/client.manifest.template` line 24 at r6](https://reviewable.io/reviews/gramineproject/gramine/884#-NBhqn_Z3f7qQvf2S_L0:-NBixToxDLZ1M6y2DWiZ:btu3tlo) ([raw file](https://github.com/gramineproject/gramine/blob/cd267fdc72a281bf3fd04e47e5bd40620ef1efea/CI-Examples/ra-tls-secret-prov/secret_prov_pf/client.manifest.template#L24)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Shouldn't this be
</blockquote></details>

Both are correct. No preferences on my side, so let's wait for @dimakuv to also comment.
___
*[`CI-Examples/ra-tls-secret-prov/secret_prov_pf/server.c` line 50 at r1](https://reviewable.io/reviews/gramineproject/gramine/884#-NBHlukP9lC1qQXvLa4u:-NBixhV1DGZaeG3kXSB9:b71i9rq) ([raw file](https://github.com/gramineproject/gramine/blob/0537ac14dbffa7fb7449a8787a79f3ff11ee2384/CI-Examples/ra-tls-secret-prov/secret_prov_pf/server.c#L50)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Still, why not have this define at the top and array here as local?
</blockquote></details>

As I said, I prefer to declare things close to places where they are used, especially if they are local. Normally I'd use `const size_t SECRET_KEY_SIZE = 16` here, but `const`s in C are half-baked, so you need to use defines for them.
Moving it out seems to me like making a local variable global without any reason.


<!-- Sent from Reviewable.io -->

2022-09-12 07:56 UTC, dimakuv requested changes
> Reviewed 1 of 6 files at r6, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/884)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[`CI-Examples/ra-tls-secret-prov/Makefile` line 102 at r6](https://reviewable.io/reviews/gramineproject/gramine/884#-NBdC1SpAtwHol-Lq84b:-NBkev7M9etkobkK-ULc:b-j3s0fo) ([raw file](https://github.com/gramineproject/gramine/blob/cd267fdc72a281bf3fd04e47e5bd40620ef1efea/CI-Examples/ra-tls-secret-prov/Makefile#L102)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Yeah, but I don't like the idea of building all the clients partially separately, but also partially by some shared pattern-generated rules. Right now you have a small copy-paste, but all clients have their own, independent sections in the Makefile.
</blockquote></details>

I agree with Michal, let's be slightly more verbose but readable.
___
*[`CI-Examples/ra-tls-secret-prov/secret_prov/server.c` line 21 at r6](https://reviewable.io/reviews/gramineproject/gramine/884#-NBhl-yg9RjPAfp4Q22y:-NBkfkbt6exygaZZejUH:bd545ys) ([raw file](https://github.com/gramineproject/gramine/blob/cd267fdc72a281bf3fd04e47e5bd40620ef1efea/CI-Examples/ra-tls-secret-prov/secret_prov/server.c#L21)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

No idea how to rename it, I didn't touch this part in this PR. But I also don't like this name.
</blockquote></details>

Well, we have `FIRST_SECRET` string in `main()`. We can move it here as a macro, and rename this one to `SECOND_SECRET`.

Or we can inline this `SECOND_STRING` in the function itself. Let's do one of these options, I agree that the current version looks weird.
___
*[`libos/src/fs/libos_fs_encrypted.c` line 198 at r6](https://reviewable.io/reviews/gramineproject/gramine/884#-NBhyjbe-feczWL8cCO7:-NBkgeIt9q0tSJOB19qz:bos58gh) ([raw file](https://github.com/gramineproject/gramine/blob/cd267fdc72a281bf3fd04e47e5bd40620ef1efea/libos/src/fs/libos_fs_encrypted.c#L198)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

To be honest, I just didn't care about this case, because:
- it's a deprecated option
- the leak is rather negligible unless you get _super_ unlucky with the compilation
- it's not trivial to fix it for the old API
</blockquote></details>

I agree, I also wouldn't care about it
___
*[`tools/sgx/ra-tls/secret_prov_attest.c` line 416 at r7](https://reviewable.io/reviews/gramineproject/gramine/884#-NBkgmtf9_f7CzUscjrz:-NBkgmtf9_f7CzUscjs-:byblt6y) ([raw file](https://github.com/gramineproject/gramine/blob/9f067c8d02d82ce34ef61986bff865be4c6ae4f5/tools/sgx/ra-tls/secret_prov_attest.c#L416)):*
> ```C
>             char path_buf[256];
>             ret = snprintf(path_buf, sizeof(path_buf), "/dev/attestation/keys/%s", key_name);
>             if (ret < 0 || (size_t)ret >= (ssize_t)sizeof(path_buf)) {
> ```

Why do you cast to different types?
___
*[`CI-Examples/ra-tls-secret-prov/secret_prov/client.manifest.template` line 18 at r1](https://reviewable.io/reviews/gramineproject/gramine/884#-NBHjy8y42mhFVyyaOJR:-NBkf7v3A83N49l0MNMa:bchlsrm) ([raw file](https://github.com/gramineproject/gramine/blob/0537ac14dbffa7fb7449a8787a79f3ff11ee2384/CI-Examples/ra-tls-secret-prov/secret_prov/client.manifest.template#L18)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

If that's the case, then I do agree that's not a trick, but normal usage. In most cases these paths will be different (except for gsc and such, where they will be the same).
</blockquote></details>

Ok. Just to reiterate: 95% of users do **not** understand our syntax of "host -> in-Gramine" mapping of directories and files. I'm tired of explaining this to users, and try to avoid the remapping in our examples.

Maybe we should just have good documentation/tutorial to explain this.
___
*[`CI-Examples/ra-tls-secret-prov/secret_prov_pf/client.c` line 14 at r1](https://reviewable.io/reviews/gramineproject/gramine/884#-NBHld6rBhCuNrARgVza:-NBkg3e22Utoe-6Gw3oK:b-22jvkn) ([raw file](https://github.com/gramineproject/gramine/blob/0537ac14dbffa7fb7449a8787a79f3ff11ee2384/CI-Examples/ra-tls-secret-prov/secret_prov_pf/client.c#L14)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I'm not sure what options we have here, but FWIW I like the idea of having one mounted directory with all input encrypted files, which I guess this `files/` is
</blockquote></details>

OK, I'm a minority here. Resolving.
___
*[`CI-Examples/ra-tls-secret-prov/secret_prov_pf/client.manifest.template` line 24 at r6](https://reviewable.io/reviews/gramineproject/gramine/884#-NBhqn_Z3f7qQvf2S_L0:-NBkgD7D1HuXDwtmD-V3:bpxtryo) ([raw file](https://github.com/gramineproject/gramine/blob/cd267fdc72a281bf3fd04e47e5bd40620ef1efea/CI-Examples/ra-tls-secret-prov/secret_prov_pf/client.manifest.template#L24)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Both are correct. No preferences on my side, so let's wait for @dimakuv to also comment.
</blockquote></details>

Borys's version looks more correct to me, so yes, let's change.


<!-- Sent from Reviewable.io -->

2022-09-12 12:22 UTC, boryspoplawski requested changes
> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/884)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`CI-Examples/ra-tls-secret-prov/secret_prov/server.c` line 5 at r6](https://reviewable.io/reviews/gramineproject/gramine/884#-NBhtEHx43D8hUvc7256:-NBl_lsA8M3Mk2x3Z4Fx:b-2agioq) ([raw file](https://github.com/gramineproject/gramine/blob/cd267fdc72a281bf3fd04e47e5bd40620ef1efea/CI-Examples/ra-tls-secret-prov/secret_prov/server.c#L5)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What about `ECONNRESET` and other constants?
</blockquote></details>

They should be in scope if you also have a function that can return them (`connect` for example), but that might be a wishful thinking from me, so not blocking.
___
*[`CI-Examples/ra-tls-secret-prov/secret_prov/server.c` line 21 at r6](https://reviewable.io/reviews/gramineproject/gramine/884#-NBhl-yg9RjPAfp4Q22y:-NBlansa1QFICkig4_Mw:b21adzv) ([raw file](https://github.com/gramineproject/gramine/blob/cd267fdc72a281bf3fd04e47e5bd40620ef1efea/CI-Examples/ra-tls-secret-prov/secret_prov/server.c#L21)):*
> I didn't touch this part in this PR.

You renamed it from `SECRET_STRING` to `SECOND_STRING`.

As @dimakuv outline, let's have both constants as defines if you want to keep `FIRST_` and `SECOND_` prefixes.
___
*[`tools/sgx/ra-tls/secret_prov_attest.c` line 416 at r7](https://reviewable.io/reviews/gramineproject/gramine/884#-NBkgmtf9_f7CzUscjrz:-NBldbPyAq5R308IYhMz:b1yknl8) ([raw file](https://github.com/gramineproject/gramine/blob/9f067c8d02d82ce34ef61986bff865be4c6ae4f5/tools/sgx/ra-tls/secret_prov_attest.c#L416)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do you cast to different types?
</blockquote></details>

Why does it even compile? We have warnings for these...
___
*[`CI-Examples/ra-tls-secret-prov/secret_prov/client.manifest.template` line 18 at r1](https://reviewable.io/reviews/gramineproject/gramine/884#-NBHjy8y42mhFVyyaOJR:-NBl_3KL9sjmkzUnW5js:bs00r27) ([raw file](https://github.com/gramineproject/gramine/blob/0537ac14dbffa7fb7449a8787a79f3ff11ee2384/CI-Examples/ra-tls-secret-prov/secret_prov/client.manifest.template#L18)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ok. Just to reiterate: 95% of users do **not** understand our syntax of "host -> in-Gramine" mapping of directories and files. I'm tired of explaining this to users, and try to avoid the remapping in our examples.

Maybe we should just have good documentation/tutorial to explain this.
</blockquote></details>

Maybe we should have better names, `uri` is weird IMO. If we supported `ftp://` or `http://` there, then sure, but currently it's just always `file://` with host FS path.

@dimakuv I guess you can tell those people it's the same as `--mount` option in Docker.
___
*[`CI-Examples/ra-tls-secret-prov/secret_prov_pf/client.manifest.template` line 24 at r6](https://reviewable.io/reviews/gramineproject/gramine/884#-NBhqn_Z3f7qQvf2S_L0:-NBlbGL35aBPRn5qMwPy:bafzbm0) ([raw file](https://github.com/gramineproject/gramine/blob/cd267fdc72a281bf3fd04e47e5bd40620ef1efea/CI-Examples/ra-tls-secret-prov/secret_prov_pf/client.manifest.template#L24)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Borys's version looks more correct to me, so yes, let's change.
</blockquote></details>

Yes, both are correct, but since we argued in other places that we want to encourage people of using one directory, then this fits more this narrative :)
___
*[`CI-Examples/ra-tls-secret-prov/secret_prov_pf/server.c` line 50 at r1](https://reviewable.io/reviews/gramineproject/gramine/884#-NBHlukP9lC1qQXvLa4u:-NBlcq2x8A4vJXy-5VDC:b-e7l1td) ([raw file](https://github.com/gramineproject/gramine/blob/0537ac14dbffa7fb7449a8787a79f3ff11ee2384/CI-Examples/ra-tls-secret-prov/secret_prov_pf/server.c#L50)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

As I said, I prefer to declare things close to places where they are used, especially if they are local. Normally I'd use `const size_t SECRET_KEY_SIZE = 16` here, but `const`s in C are half-baked, so you need to use defines for them.
Moving it out seems to me like making a local variable global without any reason.
</blockquote></details>

Then why `SRV_CRT_PATH`, `SRV_KEY_PATH` and `g_print_lock` are all global?


<!-- Sent from Reviewable.io -->

2022-09-12 14:26 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/884)* status: 20 of 23 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[`CI-Examples/ra-tls-secret-prov/secret_prov/server.c` line 5 at r6](https://reviewable.io/reviews/gramineproject/gramine/884#-NBhtEHx43D8hUvc7256:-NBlzVCF7WaoexJhd9-0:bno0nw8) ([raw file](https://github.com/gramineproject/gramine/blob/cd267fdc72a281bf3fd04e47e5bd40620ef1efea/CI-Examples/ra-tls-secret-prov/secret_prov/server.c#L5)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

They should be in scope if you also have a function that can return them (`connect` for example), but that might be a wishful thinking from me, so not blocking.
</blockquote></details>

In nice languages/libraries yes, but for C it's IMO quite a bold assumption :) The return type is just `int` or `size_t`, so there's no hard enforcement to have these includes there.
___
*[`CI-Examples/ra-tls-secret-prov/secret_prov/server.c` line 21 at r6](https://reviewable.io/reviews/gramineproject/gramine/884#-NBhl-yg9RjPAfp4Q22y:-NBlzrB88X55EIYFU-Ja:b-94mccf) ([raw file](https://github.com/gramineproject/gramine/blob/cd267fdc72a281bf3fd04e47e5bd40620ef1efea/CI-Examples/ra-tls-secret-prov/secret_prov/server.c#L21)):*
> You renamed it from `SECRET_STRING` to `SECOND_STRING`.

Oh, right, I forgot that I actually did this.

Done.
___
*[`tools/sgx/ra-tls/secret_prov_attest.c` line 416 at r7](https://reviewable.io/reviews/gramineproject/gramine/884#-NBkgmtf9_f7CzUscjrz:-NBm1g_U9D8IFC-jUXzk:bsnm5s4) ([raw file](https://github.com/gramineproject/gramine/blob/9f067c8d02d82ce34ef61986bff865be4c6ae4f5/tools/sgx/ra-tls/secret_prov_attest.c#L416)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why does it even compile? We have warnings for these...
</blockquote></details>

Oops, sorry, stupid mistake. It shouldn't compile, but it does, weird... Maybe because the signed side is compile-time-known?
___
*[`CI-Examples/ra-tls-secret-prov/secret_prov/client.manifest.template` line 18 at r1](https://reviewable.io/reviews/gramineproject/gramine/884#-NBHjy8y42mhFVyyaOJR:-NBlyzvu5lCaPF6iqBrg:b3b0m7z) ([raw file](https://github.com/gramineproject/gramine/blob/0537ac14dbffa7fb7449a8787a79f3ff11ee2384/CI-Examples/ra-tls-secret-prov/secret_prov/client.manifest.template#L18)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Maybe we should have better names, `uri` is weird IMO. If we supported `ftp://` or `http://` there, then sure, but currently it's just always `file://` with host FS path.

@dimakuv I guess you can tell those people it's the same as `--mount` option in Docker.
</blockquote></details>

Yes, I think the reason is bad naming of these fields, not that this is some "magic trick". I think we even had a proposal to change it in one of the FS/manifest RFCs.
___
*[`CI-Examples/ra-tls-secret-prov/secret_prov_pf/client.manifest.template` line 24 at r6](https://reviewable.io/reviews/gramineproject/gramine/884#-NBhqn_Z3f7qQvf2S_L0:-NBm0AjB018MMBtSdbvD:baoe4ji) ([raw file](https://github.com/gramineproject/gramine/blob/cd267fdc72a281bf3fd04e47e5bd40620ef1efea/CI-Examples/ra-tls-secret-prov/secret_prov_pf/client.manifest.template#L24)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Yes, both are correct, but since we argued in other places that we want to encourage people of using one directory, then this fits more this narrative :)
</blockquote></details>

Done. Interestingly, for some reason this syntax doesn't work with trailing slashes (e.g. `path = "/files/"`), seems to be a bug.
___
*[`CI-Examples/ra-tls-secret-prov/secret_prov_pf/server.c` line 50 at r1](https://reviewable.io/reviews/gramineproject/gramine/884#-NBHlukP9lC1qQXvLa4u:-NBm0Ul30Yzlhoxl8jbK:b-hshrw0) ([raw file](https://github.com/gramineproject/gramine/blob/0537ac14dbffa7fb7449a8787a79f3ff11ee2384/CI-Examples/ra-tls-secret-prov/secret_prov_pf/server.c#L50)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Then why `SRV_CRT_PATH`, `SRV_KEY_PATH` and `g_print_lock` are all global?
</blockquote></details>

`g_print_lock` is global because it's used in both `main()` and `verify_measurements_callback()`, so it's a different case.

`SRV_CRT_PATH` and `SRV_KEY_PATH` are user-configurable, so they are global defines (ideally, if this example was more fully fledged, then they should be passed as cmdline arguments).

`SECRET_KEY_SIZE` doesn't match any of these cases, it's just "16" with a name added, used only here, locally. As I said, think of it as just `const size_t SECRET_KEY_SIZE = 16`, with a difference that C sucks and we have to use defines instead.


<!-- Sent from Reviewable.io -->

2022-09-12 14:59 UTC, boryspoplawski requested changes
> Reviewed 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/884)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`CI-Examples/ra-tls-secret-prov/secret_prov/server.c` line 95 at r8](https://reviewable.io/reviews/gramineproject/gramine/884#-NBm9H39EX2mhRXSN4MS:-NBm9H39EX2mhRXSN4MT:bbp4pji) ([raw file](https://github.com/gramineproject/gramine/blob/fc2478b3ef8e3ece85ca5e4000751cd15dc661fd/CI-Examples/ra-tls-secret-prov/secret_prov/server.c#L95)):*
> ```C
> 
>     puts("--- Starting the Secret Provisioning server on port " PORT " ---");
>     ret = secret_provision_start_server((uint8_t*)FIRST_SECRET, sizeof(FIRST_SECRET),
> ```

I'm a bit uneasy with this cast removing `const`, but this functions internally saves the reference, passes it to a subthread, and ownership is unclear...
Not sure if we want to fix it here, but otoh for now adding `const` everywhere should work.
___
*[`tools/sgx/ra-tls/secret_prov_attest.c` line 416 at r7](https://reviewable.io/reviews/gramineproject/gramine/884#-NBkgmtf9_f7CzUscjrz:-NBmCLKE-INtD1rQ89Wo:b-p52o02) ([raw file](https://github.com/gramineproject/gramine/blob/9f067c8d02d82ce34ef61986bff865be4c6ae4f5/tools/sgx/ra-tls/secret_prov_attest.c#L416)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Oops, sorry, stupid mistake. It shouldn't compile, but it does, weird... Maybe because the signed side is compile-time-known?
</blockquote></details>

Yea, seems that the type doesn't matter for those
___
*[`CI-Examples/ra-tls-secret-prov/secret_prov_pf/client.manifest.template` line 24 at r6](https://reviewable.io/reviews/gramineproject/gramine/884#-NBhqn_Z3f7qQvf2S_L0:-NBmA7sPDmCJmdDCyMMG:b48jj16) ([raw file](https://github.com/gramineproject/gramine/blob/cd267fdc72a281bf3fd04e47e5bd40620ef1efea/CI-Examples/ra-tls-secret-prov/secret_prov_pf/client.manifest.template#L24)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Done. Interestingly, for some reason this syntax doesn't work with trailing slashes (e.g. `path = "/files/"`), seems to be a bug.
</blockquote></details>

IMO it should work, I would even encourage such trailing `/`, to indicate it's a dir we are mounting here. Could you investigate or create an issue, so we do not forget?
___
*[`CI-Examples/ra-tls-secret-prov/secret_prov_pf/server.c` line 50 at r1](https://reviewable.io/reviews/gramineproject/gramine/884#-NBHlukP9lC1qQXvLa4u:-NBmAXuB1wPYUPFQyNxO:b-44i5uk) ([raw file](https://github.com/gramineproject/gramine/blob/0537ac14dbffa7fb7449a8787a79f3ff11ee2384/CI-Examples/ra-tls-secret-prov/secret_prov_pf/server.c#L50)):*
> g_print_lock is global because it's used in both main() and verify_measurements_callback(), so it's a different case.

No, in main it's only initialized, but this should actually be `= PTHREAD_MUTEX_INITIALIZER` on definition line.

> SECRET_KEY_SIZE doesn't match any of these cases, it's just "16" with a name added, used only here, locally

Given how this example works, it could be anything of any size, it's just first secret passed to `secret_provision_start_server`. It's only in the client code, where this matters, because it's used as PF key.


<!-- Sent from Reviewable.io -->

2022-09-12 17:24 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/884)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[`CI-Examples/ra-tls-secret-prov/secret_prov/server.c` line 95 at r8](https://reviewable.io/reviews/gramineproject/gramine/884#-NBm9H39EX2mhRXSN4MS:-NBmfcmG5ucmX5dgfyYS:b-r3pysh) ([raw file](https://github.com/gramineproject/gramine/blob/fc2478b3ef8e3ece85ca5e4000751cd15dc661fd/CI-Examples/ra-tls-secret-prov/secret_prov/server.c#L95)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I'm a bit uneasy with this cast removing `const`, but this functions internally saves the reference, passes it to a subthread, and ownership is unclear...
Not sure if we want to fix it here, but otoh for now adding `const` everywhere should work.
</blockquote></details>

Let's wait for @dimakuv to comment about the intended ownership here and of other arguments.
___
*[`CI-Examples/ra-tls-secret-prov/secret_prov_pf/client.manifest.template` line 24 at r6](https://reviewable.io/reviews/gramineproject/gramine/884#-NBhqn_Z3f7qQvf2S_L0:-NBmhPv13S9rdAshZPQA:bt8rs4p) ([raw file](https://github.com/gramineproject/gramine/blob/cd267fdc72a281bf3fd04e47e5bd40620ef1efea/CI-Examples/ra-tls-secret-prov/secret_prov_pf/client.manifest.template#L24)):*
> I would even encourage such trailing `/`

Yes, guess how I noticed that it doesn't work ;)

Done: https://github.com/gramineproject/gramine/issues/904.
___
*[`CI-Examples/ra-tls-secret-prov/secret_prov_pf/server.c` line 50 at r1](https://reviewable.io/reviews/gramineproject/gramine/884#-NBHlukP9lC1qQXvLa4u:-NBmhgNwE_K9S5Clc_4D:b8qknrk) ([raw file](https://github.com/gramineproject/gramine/blob/0537ac14dbffa7fb7449a8787a79f3ff11ee2384/CI-Examples/ra-tls-secret-prov/secret_prov_pf/server.c#L50)):*
> > g_print_lock is global because it's used in both main() and verify_measurements_callback(), so it's a different case.
> 
> No, in main it's only initialized, but this should actually be `= PTHREAD_MUTEX_INITIALIZER` on definition line.

With that change it could be moved to a local variable. I don't see how's that relevant to the case we're discussing.

> It's only in the client code, where this matters, because it's used as PF key.

I don't really agree, this whole example is named to indicate that it's a encrypted/protected files example, so it has to be 16. With this PR all the servers are paired and bound to specific clients.


<!-- Sent from Reviewable.io -->

2022-09-12 18:28 UTC, boryspoplawski submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/884)* status: all files reviewed, 3 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`CI-Examples/ra-tls-secret-prov/secret_prov_pf/server.c` line 50 at r1](https://reviewable.io/reviews/gramineproject/gramine/884#-NBHlukP9lC1qQXvLa4u:-NBmx4w27a6twA_uFHhK:b-u5wwws) ([raw file](https://github.com/gramineproject/gramine/blob/0537ac14dbffa7fb7449a8787a79f3ff11ee2384/CI-Examples/ra-tls-secret-prov/secret_prov_pf/server.c#L50)):*
> With that change it could be moved to a local variable. I don't see how's that relevant to the case we're discussing.

Because you said that "Moving it out seems to me like making a local variable global without any reason." and I didn't understand why this is the case only for `SECRET_KEY_SIZE`.


<!-- Sent from Reviewable.io -->

2022-09-13 09:09 UTC, dimakuv requested changes
> Reviewed 2 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/884)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`CI-Examples/ra-tls-secret-prov/secret_prov/server.c` line 95 at r8](https://reviewable.io/reviews/gramineproject/gramine/884#-NBm9H39EX2mhRXSN4MS:-NBq4mdTC9KDlzdbU0AJ:bxcs8w3) ([raw file](https://github.com/gramineproject/gramine/blob/fc2478b3ef8e3ece85ca5e4000751cd15dc661fd/CI-Examples/ra-tls-secret-prov/secret_prov/server.c#L95)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Let's wait for @dimakuv to comment about the intended ownership here and of other arguments.
</blockquote></details>

@boryspoplawski is right, this seems to be a bug. The first argument should have a `const` qualifier, and instead of this: https://github.com/gramineproject/gramine/blob/bd6305696e146005dd7c9ff78eb45f76fe070392/tools/sgx/ra-tls/secret_prov_verify.c#L267

we should actually have `malloc` + `memcpy`. In other words, instead of the reference, we should grab a copy. Currently this bug allows the caller to `free(secret-arg)`, and the Secret Prov library (in a new thread) will read `ti->secret` which is garbage, in this line: https://github.com/gramineproject/gramine/blob/bd6305696e146005dd7c9ff78eb45f76fe070392/tools/sgx/ra-tls/secret_prov_verify.c#L140

Please fix it:
1. Add `const` to the function signature's first arg
2. Add `malloc` + `memcpy` for the first arg (copy the secret buffer)

Sorry that we found this bug only now :(
___
*[`CI-Examples/ra-tls-secret-prov/secret_prov_pf/client.manifest.template` line 24 at r6](https://reviewable.io/reviews/gramineproject/gramine/884#-NBhqn_Z3f7qQvf2S_L0:-NBq5f_zAqwLQJPLYkh5:b-hv6xsb) ([raw file](https://github.com/gramineproject/gramine/blob/cd267fdc72a281bf3fd04e47e5bd40620ef1efea/CI-Examples/ra-tls-secret-prov/secret_prov_pf/client.manifest.template#L24)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> I would even encourage such trailing `/`

Yes, guess how I noticed that it doesn't work ;)

Done: https://github.com/gramineproject/gramine/issues/904.
</blockquote></details>

Looks like smth we'd like to fix sooner than later... Anyone has free cycles?


<!-- Sent from Reviewable.io -->

2022-09-13 12:02 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/884)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`CI-Examples/ra-tls-secret-prov/secret_prov/server.c` line 95 at r8](https://reviewable.io/reviews/gramineproject/gramine/884#-NBm9H39EX2mhRXSN4MS:-NBqiF213IFouuJw1761:b45pora) ([raw file](https://github.com/gramineproject/gramine/blob/fc2478b3ef8e3ece85ca5e4000751cd15dc661fd/CI-Examples/ra-tls-secret-prov/secret_prov/server.c#L95)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@boryspoplawski is right, this seems to be a bug. The first argument should have a `const` qualifier, and instead of this: https://github.com/gramineproject/gramine/blob/bd6305696e146005dd7c9ff78eb45f76fe070392/tools/sgx/ra-tls/secret_prov_verify.c#L267

we should actually have `malloc` + `memcpy`. In other words, instead of the reference, we should grab a copy. Currently this bug allows the caller to `free(secret-arg)`, and the Secret Prov library (in a new thread) will read `ti->secret` which is garbage, in this line: https://github.com/gramineproject/gramine/blob/bd6305696e146005dd7c9ff78eb45f76fe070392/tools/sgx/ra-tls/secret_prov_verify.c#L140

Please fix it:
1. Add `const` to the function signature's first arg
2. Add `malloc` + `memcpy` for the first arg (copy the secret buffer)

Sorry that we found this bug only now :(
</blockquote></details>

Can I do it in a separate PR? It's quite unrelated to this one and not exposed by it.


<!-- Sent from Reviewable.io -->

2022-09-13 12:43 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/884)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

___
*[`CI-Examples/ra-tls-secret-prov/secret_prov/server.c` line 95 at r8](https://reviewable.io/reviews/gramineproject/gramine/884#-NBm9H39EX2mhRXSN4MS:-NBqrxB_5Cn_SZPQCZnK:b32w0x) ([raw file](https://github.com/gramineproject/gramine/blob/fc2478b3ef8e3ece85ca5e4000751cd15dc661fd/CI-Examples/ra-tls-secret-prov/secret_prov/server.c#L95)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Can I do it in a separate PR? It's quite unrelated to this one and not exposed by it.
</blockquote></details>

OK


<!-- Sent from Reviewable.io -->

2022-09-13 12:57 UTC, dimakuv approved these changes
> Reviewed 3 of 6 files at r6, 1 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/884)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-09-13 13:01 UTC, boryspoplawski approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/884)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`CI-Examples/ra-tls-secret-prov/secret_prov/server.c` line 95 at r8](https://reviewable.io/reviews/gramineproject/gramine/884#-NBm9H39EX2mhRXSN4MS:-NBquu5J9xhgmm15CKKh:b-7h2pl0) ([raw file](https://github.com/gramineproject/gramine/blob/fc2478b3ef8e3ece85ca5e4000751cd15dc661fd/CI-Examples/ra-tls-secret-prov/secret_prov/server.c#L95)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

OK
</blockquote></details>

1. Yes, separate PR please.
2. I don't think we need to copy the contents. As long as this function uses the reference while it's running, doesn't save it somewhere "for later" we are all good. This function is basically `noreturn` (except for some early errors), so even though it saves the pointer for a subthread to use, this reference is also reclaimed before return.


<!-- Sent from Reviewable.io -->

2022-09-13 13:24 UTC, merged