[LibOS] Use unlinkat instead of rmdir
gramineproject/gramine pull request #886
Opened 2022-09-06 17:21 UTC by stefanberger

## Description of the changes 

Unlinkat() implements a superset of functionality of rmdir() and we can use it for rmdir() and remove duplicate code. First, though, fix an error return code of unlinkat() when a directory is to be removed and -EACCES is expected to be returned in a test case.

## How to test this PR? 

Run test cases.

2022-09-06 21:19 UTC, boryspoplawski requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/886)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @stefanberger)

___
*[`-- commits` line 5 at r1](https://reviewable.io/reviews/gramineproject/gramine/886#-NBJda-_3ktgrh9M4eul):*
I'm kind of confused about this commit message as it seem to partially talk about the other commit. I think we could merge both of them into one, but let's resolve other issues first.
___
*[`libos/src/sys/libos_file.c` line 71 at r1](https://reviewable.io/reviews/gramineproject/gramine/886#-NBJdPOF9qM9w0WKgE0V:-NBJdPOF9qM9w0WKgE0W:b2grb54) ([raw file](https://github.com/gramineproject/gramine/blob/83039a97ea275e0d1aebee1a06f436225e779a7a/libos/src/sys/libos_file.c#L71)):*
> ```C
>             goto out;
>         }
>     } else {
> ```

I don't understand this change. Why would it return `EACCES` if fs offers no unlink?
___
*[`libos/test/regression/synthetic.c` line 52 at r1](https://reviewable.io/reviews/gramineproject/gramine/886#-NBJdrSY84O2LGGB-ETF:-NBJdrSY84O2LGGB-ETG:bgga6ef) ([raw file](https://github.com/gramineproject/gramine/blob/83039a97ea275e0d1aebee1a06f436225e779a7a/libos/test/regression/synthetic.c#L52)):*
> ```C
>     test_list(path, subpath);
> 
>     if (unlinkat(AT_FDCWD, path, AT_REMOVEDIR) != -1 || errno != EACCES)
> ```

Is this even correct? Shouldn't it return `ENOTEMPTY`?


<!-- Sent from Reviewable.io -->

2022-09-06 22:03 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/886)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski and @stefanberger)

___
*[`libos/src/sys/libos_file.c` line 71 at r1](https://reviewable.io/reviews/gramineproject/gramine/886#-NBJdPOF9qM9w0WKgE0V:-NBJotyg6gPpSzWbQEWc:bnu1qql) ([raw file](https://github.com/gramineproject/gramine/blob/83039a97ea275e0d1aebee1a06f436225e779a7a/libos/src/sys/libos_file.c#L71)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I don't understand this change. Why would it return `EACCES` if fs offers no unlink?
</blockquote></details>

This is from rmdir:

    struct libos_fs* fs = dent->inode->fs;
    if (!fs || !fs->d_ops || !fs->d_ops->unlink) {
        ret = -EACCES;
        goto out;
    }

Similar story there...



_Code quote:_
```C
    struct libos_fs* fs = dent->inode->fs;
    if (!fs || !fs->d_ops || !fs->d_ops->unlink) {
        ret = -EACCES;
        goto out;
    }
```


<!-- Sent from Reviewable.io -->

2022-09-06 22:04 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/886)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski and @stefanberger)

___
*[`-- commits` line 5 at r1](https://reviewable.io/reviews/gramineproject/gramine/886#-NBJda-_3ktgrh9M4eul):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I'm kind of confused about this commit message as it seem to partially talk about the other commit. I think we could merge both of them into one, but let's resolve other issues first.
</blockquote></details>

It's justification  for replacing rmdir with unlinkat() on the user program level.


<!-- Sent from Reviewable.io -->

2022-09-06 22:10 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/886)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski)

___
*[`libos/test/regression/synthetic.c` line 52 at r1](https://reviewable.io/reviews/gramineproject/gramine/886#-NBJdrSY84O2LGGB-ETF:-NBJqX8DDeKE8OgWh8s4:baykpxx) ([raw file](https://github.com/gramineproject/gramine/blob/83039a97ea275e0d1aebee1a06f436225e779a7a/libos/test/regression/synthetic.c#L52)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Is this even correct? Shouldn't it return `ENOTEMPTY`?
</blockquote></details>

From what I can see when running the test case 'natively' it is correct in this case.


<!-- Sent from Reviewable.io -->

2022-09-07 07:52 UTC, dimakuv requested changes
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/886)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski, @pwmarcz, and @stefanberger)

___
*[`-- commits` line 5 at r1](https://reviewable.io/reviews/gramineproject/gramine/886#-NBJda-_3ktgrh9M4eul):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

It's justification  for replacing rmdir with unlinkat() on the user program level.
</blockquote></details>

First of all, I don't understand why we're changing the test case at all.

Second of all, I agree with Borys that this PR should contain only one commit, not two.
___
*[`libos/src/sys/libos_file.c` line 44 at r1](https://reviewable.io/reviews/gramineproject/gramine/886#-NBLupYAAAAvQrAdvYb5:-NBLupYAAAAvQrAdvYb6:bcc5q4w) ([raw file](https://github.com/gramineproject/gramine/blob/83039a97ea275e0d1aebee1a06f436225e779a7a/libos/src/sys/libos_file.c#L44)):*
> ```C
> 
>     lock(&g_dcache_lock);
>     ret = path_lookupat(dir, pathname, LOOKUP_NO_FOLLOW, &dent);
> ```

The `rmdir` emulation also had ` | LOOKUP_DIRECTORY`. Looks important, what does this flag do? Shouldn't we add this flag when `flag & AT_REMOVEDIR`?
___
*[`libos/src/sys/libos_file.c` line 71 at r1](https://reviewable.io/reviews/gramineproject/gramine/886#-NBJdPOF9qM9w0WKgE0V:-NBLv1IRCViKU4_RcFr7:bp4lxbq) ([raw file](https://github.com/gramineproject/gramine/blob/83039a97ea275e0d1aebee1a06f436225e779a7a/libos/src/sys/libos_file.c#L71)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

This is from rmdir:

    struct libos_fs* fs = dent->inode->fs;
    if (!fs || !fs->d_ops || !fs->d_ops->unlink) {
        ret = -EACCES;
        goto out;
    }

Similar story there...
</blockquote></details>

I'm also unclear here. If the FS doesn't have a FS-specific `unlink` operation, then it means there are no additional things to be done, and we shouldn't fail...

Maybe it was a bug in the previous `rmdir` code?

@pwmarcz Can we summon you here?
___
*[`libos/test/regression/synthetic.c` line 52 at r1](https://reviewable.io/reviews/gramineproject/gramine/886#-NBJdrSY84O2LGGB-ETF:-NBLvWXt54bWwbGN-8Tc:b-1vo1d) ([raw file](https://github.com/gramineproject/gramine/blob/83039a97ea275e0d1aebee1a06f436225e779a7a/libos/test/regression/synthetic.c#L52)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

From what I can see when running the test case 'natively' it is correct in this case.
</blockquote></details>

Why do we even change this test?


<!-- Sent from Reviewable.io -->

2022-09-07 10:58 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/886)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski, @dimakuv, and @pwmarcz)

___
*[`-- commits` line 5 at r1](https://reviewable.io/reviews/gramineproject/gramine/886#-NBJda-_3ktgrh9M4eul):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

First of all, I don't understand why we're changing the test case at all.

Second of all, I agree with Borys that this PR should contain only one commit, not two.
</blockquote></details>

I have change the test case in patch 1 because it helps fix the errno that unlinkat() needs to return for as long as only patch 1 is applied.
___
*[`libos/src/sys/libos_file.c` line 44 at r1](https://reviewable.io/reviews/gramineproject/gramine/886#-NBLupYAAAAvQrAdvYb5:-NBMW4CN5zDpPGxiSg92:bpu2qpz) ([raw file](https://github.com/gramineproject/gramine/blob/83039a97ea275e0d1aebee1a06f436225e779a7a/libos/src/sys/libos_file.c#L44)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

The `rmdir` emulation also had ` | LOOKUP_DIRECTORY`. Looks important, what does this flag do? Shouldn't we add this flag when `flag & AT_REMOVEDIR`?
</blockquote></details>

I set this flag now in a fixup patch. The flag filters out directory versus files in the `path_lookup()` call and returns -ENOTDIR if LOOKUP_DIRECTORY is set but the dentry is not a directory.  Regression tests for libos and ltp are all passing with the flag set.


From lookup_enter_dentry:

```
    } else if (lookup->dent->inode->type != S_IFDIR) {
        /*
         * The file exists, but is not a directory. We expect a directory (and need to fail with
         * -ENOTDIR) in the following cases:
         *
         * - if this is an intermediate path segment,
         * - if this is the final path segment, but the path ends with a slash,
         * - if LOOKUP_DIRECTORY is set.
         */
        if (!is_final || has_slash || (lookup->flags & LOOKUP_DIRECTORY)) {
            return -ENOTDIR;
        }
    }
```

However, later on in libos_syscall_unlinkat() there's also a check that may then be redundant:

```
   if (flag & AT_REMOVEDIR) {
        if (dent->inode->type != S_IFDIR) {
            ret = -ENOTDIR;
            goto out;
        }
    } else {
        if (dent->inode->type == S_IFDIR) {
            ret = -EISDIR;
            goto out;
        }
    }
```



What may make the fine difference is this part here:

```
    ret = path_lookupat(dir, pathname, flags, &dent);
    if (ret < 0)
        goto out;

    if (!dent->parent) {
        ret = -EACCES;
        goto out;
    }
```

Is there a reason to get back a dent, even if the dentry is not a directory if it should be one, and have that dent->parent check done to return -EACCES?
___
*[`libos/test/regression/synthetic.c` line 52 at r1](https://reviewable.io/reviews/gramineproject/gramine/886#-NBJdrSY84O2LGGB-ETF:-NBM_SaF-AIYsTj2_Tlo:bivu5q2) ([raw file](https://github.com/gramineproject/gramine/blob/83039a97ea275e0d1aebee1a06f436225e779a7a/libos/test/regression/synthetic.c#L52)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do we even change this test?
</blockquote></details>

At the time when only patch 1 is applied this change is a way to trigger the fix for the correct errno to returned by unlinkat(). With patch 2 on top of it it doesn't matter anymore.


<!-- Sent from Reviewable.io -->

2022-09-07 12:25 UTC, boryspoplawski requested changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/886)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @pwmarcz)

___
*[`-- commits` line 5 at r1](https://reviewable.io/reviews/gramineproject/gramine/886#-NBJda-_3ktgrh9M4eul):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

I have change the test case in patch 1 because it helps fix the errno that unlinkat() needs to return for as long as only patch 1 is applied.
</blockquote></details>

 > Unlinkat() implements a superset of functionality of rmdir() and can be
 > used to replace rmdir().

How is that justification? The fact that something is a superset doesn't mean we have to use it.
The real justification is that we don't test `unlinkat(AT_REMOVEDIR)` anywhere, so it's nice to have it (and we do have `rmdir` in a few other places). (cc @dimakuv that was my reasoning)
___
*[`libos/src/sys/libos_file.c` line 44 at r1](https://reviewable.io/reviews/gramineproject/gramine/886#-NBLupYAAAAvQrAdvYb5:-NBMsED41XBwM3qDTJus:b-9b1wsd) ([raw file](https://github.com/gramineproject/gramine/blob/83039a97ea275e0d1aebee1a06f436225e779a7a/libos/src/sys/libos_file.c#L44)):*
This new change is not needed, as you pointed out we verify that below anyway.

> Is there a reason to get back a dent, even if the dentry is not a directory if it should be one, and have that dent->parent check done to return -EACCES?

I'm not sure I understand this. I believe the code without the latest change was perfectly fine (except for other outlined issues, but they are unrelated to this change).
___
*[`libos/src/sys/libos_file.c` line 71 at r1](https://reviewable.io/reviews/gramineproject/gramine/886#-NBJdPOF9qM9w0WKgE0V:-NBMtMpcD1BYshKaQWvY:bylyptv) ([raw file](https://github.com/gramineproject/gramine/blob/83039a97ea275e0d1aebee1a06f436225e779a7a/libos/src/sys/libos_file.c#L71)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I'm also unclear here. If the FS doesn't have a FS-specific `unlink` operation, then it means there are no additional things to be done, and we shouldn't fail...

Maybe it was a bug in the previous `rmdir` code?

@pwmarcz Can we summon you here?
</blockquote></details>

@stefanberger The fact that we have something in Gramine doesn't make it correct :)
___
*[`libos/test/regression/synthetic.c` line 52 at r1](https://reviewable.io/reviews/gramineproject/gramine/886#-NBJdrSY84O2LGGB-ETF:-NBMtxRN4Q8_w3gsBEse:b-d0zgit) ([raw file](https://github.com/gramineproject/gramine/blob/83039a97ea275e0d1aebee1a06f436225e779a7a/libos/test/regression/synthetic.c#L52)):*
But this is not correct errno.

> From what I can see when running the test case 'natively' it is correct in this case.

By 'natively' you mean without Gramine? And you had a non-empty `/mnt` owned by the current user?


<!-- Sent from Reviewable.io -->

2022-09-07 13:18 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/886)* status: 0 of 2 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @pwmarcz)

___
*[`-- commits` line 5 at r1](https://reviewable.io/reviews/gramineproject/gramine/886#-NBJda-_3ktgrh9M4eul):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

 > Unlinkat() implements a superset of functionality of rmdir() and can be
 > used to replace rmdir().

How is that justification? The fact that something is a superset doesn't mean we have to use it.
The real justification is that we don't test `unlinkat(AT_REMOVEDIR)` anywhere, so it's nice to have it (and we do have `rmdir` in a few other places). (cc @dimakuv that was my reasoning)
</blockquote></details>

Justification is 'running through a different code path.' Either way, I now reverted the change to the test case since the 2nd patch makes rmdir use unlinkat in all cases.
___
*[`libos/src/sys/libos_file.c` line 44 at r1](https://reviewable.io/reviews/gramineproject/gramine/886#-NBLupYAAAAvQrAdvYb5:-NBN3Wl98JSgQK4QjXM3:b-m1253k) ([raw file](https://github.com/gramineproject/gramine/blob/83039a97ea275e0d1aebee1a06f436225e779a7a/libos/src/sys/libos_file.c#L44)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This new change is not needed, as you pointed out we verify that below anyway.

> Is there a reason to get back a dent, even if the dentry is not a directory if it should be one, and have that dent->parent check done to return -EACCES?

I'm not sure I understand this. I believe the code without the latest change was perfectly fine (except for other outlined issues, but they are unrelated to this change).
</blockquote></details>

I reverted the fixup patch now.
___
*[`libos/src/sys/libos_file.c` line 71 at r1](https://reviewable.io/reviews/gramineproject/gramine/886#-NBJdPOF9qM9w0WKgE0V:-NBN3psd96Y_SU4GXqPq:blnttul) ([raw file](https://github.com/gramineproject/gramine/blob/83039a97ea275e0d1aebee1a06f436225e779a7a/libos/src/sys/libos_file.c#L71)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

@stefanberger The fact that we have something in Gramine doesn't make it correct :)
</blockquote></details>

I did have some trust in it... :-/
___
*[`libos/test/regression/synthetic.c` line 52 at r1](https://reviewable.io/reviews/gramineproject/gramine/886#-NBJdrSY84O2LGGB-ETF:-NBN43oP3SEWHkHSdDBB:btqqu5l) ([raw file](https://github.com/gramineproject/gramine/blob/83039a97ea275e0d1aebee1a06f436225e779a7a/libos/test/regression/synthetic.c#L52)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

But this is not correct errno.

> From what I can see when running the test case 'natively' it is correct in this case.

By 'natively' you mean without Gramine? And you had a non-empty `/mnt` owned by the current user?
</blockquote></details>

Correct.


<!-- Sent from Reviewable.io -->

2022-09-07 13:30 UTC, boryspoplawski requested changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/886)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @pwmarcz, and @stefanberger)

___
*[`libos/test/regression/synthetic.c` line 52 at r1](https://reviewable.io/reviews/gramineproject/gramine/886#-NBJdrSY84O2LGGB-ETF:-NBN7X5GB-Qw-fLBZyiL:bu4lop3) ([raw file](https://github.com/gramineproject/gramine/blob/83039a97ea275e0d1aebee1a06f436225e779a7a/libos/test/regression/synthetic.c#L52)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

Correct.
</blockquote></details>

```c
    const char* path = "/mnt";
    int x;
    errno = 0;
    if (!strcmp(argv[1], "r")) {
        x = rmdir(path);
    } else if (!strcmp(argv[1], "u")) {
        x = unlinkat(AT_FDCWD, path, AT_REMOVEDIR);
    }
    printf("%d %d %m\n", x, errno);
```

```
# ./a.out r
-1 39 Directory not empty
# ./a.out u
-1 39 Directory not empty
```
___
*[`libos/test/regression/synthetic.c` line 52 at r1](https://reviewable.io/reviews/gramineproject/gramine/886#-NBN81si9C0-rbSiyZvw:-NBN81sjC4KsBNm5iTb3:b-ahig4) ([raw file](https://github.com/gramineproject/gramine/blob/83039a97ea275e0d1aebee1a06f436225e779a7a/libos/test/regression/synthetic.c#L52)):*
> ```C
>     test_list(path, subpath);
> 
>     if (unlinkat(AT_FDCWD, path, AT_REMOVEDIR) != -1 || errno != EACCES)
> ```

Why revert this change? I think it's good to test this combination somewhere


<!-- Sent from Reviewable.io -->

2022-09-07 13:55 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/886)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @pwmarcz)

___
*[`libos/test/regression/synthetic.c` line 52 at r1](https://reviewable.io/reviews/gramineproject/gramine/886#-NBN81si9C0-rbSiyZvw:-NBNDcd3CtyTt7PekPFb:b-guf8uf) ([raw file](https://github.com/gramineproject/gramine/blob/83039a97ea275e0d1aebee1a06f436225e779a7a/libos/test/regression/synthetic.c#L52)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why revert this change? I think it's good to test this combination somewhere
</blockquote></details>

rmdir and unlinkat(AT_FDCWD, ..., AT_REMOVEDIR)  become the same on the level of Gramine once the 2nd patch is applied...


<!-- Sent from Reviewable.io -->

2022-09-07 14:02 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/886)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @pwmarcz, and @stefanberger)

___
*[`libos/test/regression/synthetic.c` line 52 at r1](https://reviewable.io/reviews/gramineproject/gramine/886#-NBN81si9C0-rbSiyZvw:-NBNFXhA1uokdXeOUEMA:b-3tki4a) ([raw file](https://github.com/gramineproject/gramine/blob/83039a97ea275e0d1aebee1a06f436225e779a7a/libos/test/regression/synthetic.c#L52)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

rmdir and unlinkat(AT_FDCWD, ..., AT_REMOVEDIR)  become the same on the level of Gramine once the 2nd patch is applied...
</blockquote></details>

Tests aren't supposed to assume what is the internal implementation of syscalls...


<!-- Sent from Reviewable.io -->

2022-09-07 16:04 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/886)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @pwmarcz)

___
*[`libos/test/regression/synthetic.c` line 52 at r1](https://reviewable.io/reviews/gramineproject/gramine/886#-NBJdrSY84O2LGGB-ETF:-NBNgCvi1Iaa7NzsmuRh:bwh6ghj) ([raw file](https://github.com/gramineproject/gramine/blob/83039a97ea275e0d1aebee1a06f436225e779a7a/libos/test/regression/synthetic.c#L52)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

```c
    const char* path = "/mnt";
    int x;
    errno = 0;
    if (!strcmp(argv[1], "r")) {
        x = rmdir(path);
    } else if (!strcmp(argv[1], "u")) {
        x = unlinkat(AT_FDCWD, path, AT_REMOVEDIR);
    }
    printf("%d %d %m\n", x, errno);
```

```
# ./a.out r
-1 39 Directory not empty
# ./a.out u
-1 39 Directory not empty
```
</blockquote></details>

```
diff --git a/libos/test/regression/synthetic.c b/libos/test/regression/synthetic.c
index db9feeed..3e2cd5be 100644
--- a/libos/test/regression/synthetic.c
+++ b/libos/test/regression/synthetic.c
@@ -51,6 +51,7 @@ int main(void) {

     if (rmdir(path) != -1 || errno != EACCES)
         err(1, "rmdir should return EACCES");
+printf("ERRNO: %d [%d]\n", errno, EACCES);

     if (stat(path, &statbuf) == -1)
         err(1, "stat");
```

$ ls -l /mnt/
total 0
-rw-r--r-- 1 stefanb stefanb 0 Sep  6 18:09 tmpfs
$ /usr/local/lib/x86_64-linux-gnu/gramine/tests/libos/regression/synthetic
dirent: .
dirent: ..
dirent: tmpfs
ERRNO: 13 [13]
TEST OK
___
*[`libos/test/regression/synthetic.c` line 52 at r1](https://reviewable.io/reviews/gramineproject/gramine/886#-NBN81si9C0-rbSiyZvw:-NBNgNwh7cL7tGBUbzqz:b-wuua7k) ([raw file](https://github.com/gramineproject/gramine/blob/83039a97ea275e0d1aebee1a06f436225e779a7a/libos/test/regression/synthetic.c#L52)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Tests aren't supposed to assume what is the internal implementation of syscalls...
</blockquote></details>

From the other comments I had the impression the change to the test case was not acceptable, so I reverted the change


<!-- Sent from Reviewable.io -->

2022-09-07 16:34 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/886)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @pwmarcz)

___
*[`libos/test/regression/synthetic.c` line 52 at r1](https://reviewable.io/reviews/gramineproject/gramine/886#-NBN81si9C0-rbSiyZvw:-NBNn1Q91SfZcOG8dDS5:b-qejy52) ([raw file](https://github.com/gramineproject/gramine/blob/83039a97ea275e0d1aebee1a06f436225e779a7a/libos/test/regression/synthetic.c#L52)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

From the other comments I had the impression the change to the test case was not acceptable, so I reverted the change
</blockquote></details>

We had mixed opinion, @dimakuv didn't want it, I did. Though for different reasons then you, I believe
___
*[`libos/test/regression/synthetic.c` line 52 at r1](https://reviewable.io/reviews/gramineproject/gramine/886#-NBJdrSY84O2LGGB-ETF:-NBNnBNV8jfPsYFo3Vmf:b-tnwshz) ([raw file](https://github.com/gramineproject/gramine/blob/83039a97ea275e0d1aebee1a06f436225e779a7a/libos/test/regression/synthetic.c#L52)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

```
diff --git a/libos/test/regression/synthetic.c b/libos/test/regression/synthetic.c
index db9feeed..3e2cd5be 100644
--- a/libos/test/regression/synthetic.c
+++ b/libos/test/regression/synthetic.c
@@ -51,6 +51,7 @@ int main(void) {

     if (rmdir(path) != -1 || errno != EACCES)
         err(1, "rmdir should return EACCES");
+printf("ERRNO: %d [%d]\n", errno, EACCES);

     if (stat(path, &statbuf) == -1)
         err(1, "stat");
```

$ ls -l /mnt/
total 0
-rw-r--r-- 1 stefanb stefanb 0 Sep  6 18:09 tmpfs
$ /usr/local/lib/x86_64-linux-gnu/gramine/tests/libos/regression/synthetic
dirent: .
dirent: ..
dirent: tmpfs
ERRNO: 13 [13]
TEST OK


</blockquote></details>

and `ls -ld /mnt` ?


<!-- Sent from Reviewable.io -->

2022-09-07 17:23 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/886)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @pwmarcz)

___
*[`libos/test/regression/synthetic.c` line 52 at r1](https://reviewable.io/reviews/gramineproject/gramine/886#-NBJdrSY84O2LGGB-ETF:-NBNyGvM7-_ZXIIa897w:b6jks1h) ([raw file](https://github.com/gramineproject/gramine/blob/83039a97ea275e0d1aebee1a06f436225e779a7a/libos/test/regression/synthetic.c#L52)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

and `ls -ld /mnt` ?
</blockquote></details>

```
 ls -ld /mnt
drwxr-xr-x 2 stefanb stefanb 4096 Sep  6 18:09 /mnt
```
___
*[`libos/test/regression/synthetic.c` line 52 at r1](https://reviewable.io/reviews/gramineproject/gramine/886#-NBN81si9C0-rbSiyZvw:-NBNyS5_-RirtmQGS0y2:b7z19iv) ([raw file](https://github.com/gramineproject/gramine/blob/83039a97ea275e0d1aebee1a06f436225e779a7a/libos/test/regression/synthetic.c#L52)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

We had mixed opinion, @dimakuv didn't want it, I did. Though for different reasons then you, I believe
</blockquote></details>

So you want me to revert the current top patch ?


<!-- Sent from Reviewable.io -->

2022-09-07 17:42 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/886)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @pwmarcz)

___
*[`libos/test/regression/synthetic.c` line 52 at r1](https://reviewable.io/reviews/gramineproject/gramine/886#-NBN81si9C0-rbSiyZvw:-NBO0D6CCOd-I-xIE_ww:b-cgy07w) ([raw file](https://github.com/gramineproject/gramine/blob/83039a97ea275e0d1aebee1a06f436225e779a7a/libos/test/regression/synthetic.c#L52)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

So you want me to revert the current top patch ?
</blockquote></details>

I was just talking about this change.
Let's have consensus first, no point in changing back and forth.
@dimakuv ?
___
*[`libos/test/regression/synthetic.c` line 52 at r1](https://reviewable.io/reviews/gramineproject/gramine/886#-NBJdrSY84O2LGGB-ETF:-NBO1k8o4ySImlfhCE-l:bgcchjd) ([raw file](https://github.com/gramineproject/gramine/blob/83039a97ea275e0d1aebee1a06f436225e779a7a/libos/test/regression/synthetic.c#L52)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

```
 ls -ld /mnt
drwxr-xr-x 2 stefanb stefanb 4096 Sep  6 18:09 /mnt
```
</blockquote></details>

Ah, sry, it was supposed to be `ls -ld /`, it's the containing directory (of the removed item) permissions that matter


<!-- Sent from Reviewable.io -->

2022-09-07 17:49 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/886)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @pwmarcz)

___
*[`libos/test/regression/synthetic.c` line 52 at r1](https://reviewable.io/reviews/gramineproject/gramine/886#-NBJdrSY84O2LGGB-ETF:-NBO3QpO1KCLCaOuUJQ4:beezy9v) ([raw file](https://github.com/gramineproject/gramine/blob/83039a97ea275e0d1aebee1a06f436225e779a7a/libos/test/regression/synthetic.c#L52)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Ah, sry, it was supposed to be `ls -ld /`, it's the containing directory (of the removed item) permissions that matter
</blockquote></details>

I am running this on the host:
```
$ ls -ld /
drwxr-xr-x 24 root root 4096 Sep  6 12:41 /
```


<!-- Sent from Reviewable.io -->

2022-09-07 17:54 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/886)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @pwmarcz)

___
*[`libos/test/regression/synthetic.c` line 52 at r1](https://reviewable.io/reviews/gramineproject/gramine/886#-NBJdrSY84O2LGGB-ETF:-NBO4LdK8cQsMuhYRThF:b-51wytz) ([raw file](https://github.com/gramineproject/gramine/blob/83039a97ea275e0d1aebee1a06f436225e779a7a/libos/test/regression/synthetic.c#L52)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

I am running this on the host:
```
$ ls -ld /
drwxr-xr-x 24 root root 4096 Sep  6 12:41 /
```
</blockquote></details>

So this makes sense - you don't have permissions to modify the content of `/` (here removing an item - directory), hence you get `EACCES`.
This is different in Gramine, because both `/` and `/mnt` are owned by the user doing `rmdir`/`unlinkat`


<!-- Sent from Reviewable.io -->

2022-09-07 18:19 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/886)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @pwmarcz)

___
*[`libos/test/regression/synthetic.c` line 52 at r1](https://reviewable.io/reviews/gramineproject/gramine/886#-NBJdrSY84O2LGGB-ETF:-NBO9HFo72CClFwgAz3U:bii3ijk) ([raw file](https://github.com/gramineproject/gramine/blob/83039a97ea275e0d1aebee1a06f436225e779a7a/libos/test/regression/synthetic.c#L52)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

So this makes sense - you don't have permissions to modify the content of `/` (here removing an item - directory), hence you get `EACCES`.
This is different in Gramine, because both `/` and `/mnt` are owned by the user doing `rmdir`/`unlinkat`
</blockquote></details>

I guess we would need this then as a separate patch to correct the error code.
```
index b902a9bb..f6285495 100644
--- a/libos/src/sys/libos_file.c
+++ b/libos/src/sys/libos_file.c
@@ -69,8 +69,8 @@ long libos_syscall_unlinkat(int dfd, const char* pathname, int flag) {
             goto out;
         }
     } else {
-        if (flag & AT_REMOVEDIR) {
-            ret = -EACCES;
+        if ((flag & AT_REMOVEDIR) && dent->nchildren > 0) {
+            ret = -ENOTEMPTY;
             goto out;
         }
     }
diff --git a/libos/test/regression/synthetic.c b/libos/test/regression/synthetic.c
index db9feeed..019e617c 100644
--- a/libos/test/regression/synthetic.c
+++ b/libos/test/regression/synthetic.c
@@ -49,8 +49,8 @@ int main(void) {

     test_list(path, subpath);

-    if (rmdir(path) != -1 || errno != EACCES)
-        err(1, "rmdir should return EACCES");
+    if (rmdir(path) != -1 || errno != ENOTEMPTY)
+        err(1, "rmdir should return ENOTEMPTY");

     if (stat(path, &statbuf) == -1)
         err(1, "stat");
```


<!-- Sent from Reviewable.io -->

2022-09-07 18:27 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/886)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @pwmarcz)

___
*[`libos/test/regression/synthetic.c` line 52 at r1](https://reviewable.io/reviews/gramineproject/gramine/886#-NBJdrSY84O2LGGB-ETF:-NBOCC9ZCKKIcsO_-YMv:bue9ewv) ([raw file](https://github.com/gramineproject/gramine/blob/83039a97ea275e0d1aebee1a06f436225e779a7a/libos/test/regression/synthetic.c#L52)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

I guess we would need this then as a separate patch to correct the error code.
```
index b902a9bb..f6285495 100644
--- a/libos/src/sys/libos_file.c
+++ b/libos/src/sys/libos_file.c
@@ -69,8 +69,8 @@ long libos_syscall_unlinkat(int dfd, const char* pathname, int flag) {
             goto out;
         }
     } else {
-        if (flag & AT_REMOVEDIR) {
-            ret = -EACCES;
+        if ((flag & AT_REMOVEDIR) && dent->nchildren > 0) {
+            ret = -ENOTEMPTY;
             goto out;
         }
     }
diff --git a/libos/test/regression/synthetic.c b/libos/test/regression/synthetic.c
index db9feeed..019e617c 100644
--- a/libos/test/regression/synthetic.c
+++ b/libos/test/regression/synthetic.c
@@ -49,8 +49,8 @@ int main(void) {

     test_list(path, subpath);

-    if (rmdir(path) != -1 || errno != EACCES)
-        err(1, "rmdir should return EACCES");
+    if (rmdir(path) != -1 || errno != ENOTEMPTY)
+        err(1, "rmdir should return ENOTEMPTY");

     if (stat(path, &statbuf) == -1)
         err(1, "stat");
```
</blockquote></details>

better:

```
index b902a9bb..f34f09d5 100644
--- a/libos/src/sys/libos_file.c
+++ b/libos/src/sys/libos_file.c
@@ -55,6 +55,10 @@ long libos_syscall_unlinkat(int dfd, const char* pathname, int flag) {
             ret = -ENOTDIR;
             goto out;
         }
+        if (dent->nchildren > 0) {
+            ret = -ENOTEMPTY;
+            goto out;
+        }
     } else {
         if (dent->inode->type == S_IFDIR) {
             ret = -EISDIR;
```


<!-- Sent from Reviewable.io -->

2022-09-08 11:05 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/886)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @pwmarcz)

___
*[`libos/test/regression/synthetic.c` line 52 at r1](https://reviewable.io/reviews/gramineproject/gramine/886#-NBJdrSY84O2LGGB-ETF:-NBRlAa43zx29cJv42fF:bw93jr2) ([raw file](https://github.com/gramineproject/gramine/blob/83039a97ea275e0d1aebee1a06f436225e779a7a/libos/test/regression/synthetic.c#L52)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

better:

```
index b902a9bb..f34f09d5 100644
--- a/libos/src/sys/libos_file.c
+++ b/libos/src/sys/libos_file.c
@@ -55,6 +55,10 @@ long libos_syscall_unlinkat(int dfd, const char* pathname, int flag) {
             ret = -ENOTDIR;
             goto out;
         }
+        if (dent->nchildren > 0) {
+            ret = -ENOTEMPTY;
+            goto out;
+        }
     } else {
         if (dent->inode->type == S_IFDIR) {
             ret = -EISDIR;
```
</blockquote></details>

No, this is not enough, e.g. look at tmpfs unlink - there might be child dentries without inodes (effectively empty). I think this should be handled by fs unlink callback. Generally speaking I think there is a lot to change here and you won't be able to fix it with a simple 4lines change


<!-- Sent from Reviewable.io -->

2022-09-08 12:41 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/886)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @pwmarcz)

___
*[`libos/test/regression/synthetic.c` line 52 at r1](https://reviewable.io/reviews/gramineproject/gramine/886#-NBJdrSY84O2LGGB-ETF:-NBS6K573ipK5UMF4XIs:b1ht9cg) ([raw file](https://github.com/gramineproject/gramine/blob/83039a97ea275e0d1aebee1a06f436225e779a7a/libos/test/regression/synthetic.c#L52)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

No, this is not enough, e.g. look at tmpfs unlink - there might be child dentries without inodes (effectively empty). I think this should be handled by fs unlink callback. Generally speaking I think there is a lot to change here and you won't be able to fix it with a simple 4lines change
</blockquote></details>

Right, the 'synthetic' filesystem is work-in-progress and is missing the unlink implementation.


<!-- Sent from Reviewable.io -->

2022-09-15 17:24 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/886)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @pwmarcz)

___
*[`libos/test/regression/synthetic.c` line 52 at r1](https://reviewable.io/reviews/gramineproject/gramine/886#-NBN81si9C0-rbSiyZvw:-NC1AOk-5ttE80LmEepE:b9nv8wo) ([raw file](https://github.com/gramineproject/gramine/blob/83039a97ea275e0d1aebee1a06f436225e779a7a/libos/test/regression/synthetic.c#L52)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I was just talking about this change.
Let's have consensus first, no point in changing back and forth.
@dimakuv ?
</blockquote></details>

how do we want to proceed?


<!-- Sent from Reviewable.io -->

2022-09-16 07:09 UTC, dimakuv commented
Let's put this PR on hold. We are very busy with preparing for the new release of Gramine.

2022-10-19 20:46 UTC, stefanberger reviewed
Any suggestions on how to go about this patch now?

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/886#-:-NElzia346pkeSYND949:bzauqty)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @pwmarcz)



<!-- Sent from Reviewable.io -->

2022-10-20 07:31 UTC, dimakuv reviewed
To be honest, this has very low priority for us, and I would just close this PR as it doesn't add much value to real-world apps. We spent too much energy on this.

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/886#-:-NEoIKFJ1bflX3YK8ndY:biinl68)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @pwmarcz)



<!-- Sent from Reviewable.io -->

2022-10-20 10:17 UTC, closed without merging