[LibOS] Add missing rlimit check on newfd to dup3()
gramineproject/gramine pull request #887
Opened 2022-09-06 17:30 UTC by stefanberger

## Description of the changes 

Add missing rlimit check on newfd to dup3().

Also see here: https://elixir.bootlin.com/linux/latest/source/fs/file.c#L1217

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/887)

2022-09-06 21:02 UTC, boryspoplawski approved these changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/887)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/887#-NBJamax-cMmUAeKN0d4:-NBJamay8mpQqqtxZ82l:bduscgg) (no related file):*
One thing to keep in mind is that limits in Gramine are rather loosely implemented and barely enforced (and don't make much sense, since we are not and never will be a sandbox).
Having said that, the change is fine, so let's merge it.

___


<!-- Sent from Reviewable.io -->

2022-09-06 21:02 UTC, boryspoplawski commented
Jenkins, test this please

2022-09-07 07:27 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/887)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @stefanberger)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/887#-NBLplyb2tdWxJsLRs3_:-NBLplyb2tdWxJsLRs3a:b-rrnb8v) (no related file):*
CI failed with:
```
23:07:27  ../libos/src/sys/libos_dup.c: In function ‘libos_syscall_dup3’:
23:07:27  ../libos/src/sys/libos_dup.c:60:18: error: implicit declaration of function ‘getrlimit_cur’; did you mean ‘get_rlimit_cur’? [-Werror=implicit-function-declaration]
23:07:27       if (newfd >= getrlimit_cur(RLIMIT_NOFILE))
23:07:27                    ^~~~~~~~~~~~~
23:07:27                    get_rlimit_cur
23:07:27  ../libos/src/sys/libos_dup.c:60:15: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
23:07:27       if (newfd >= getrlimit_cur(RLIMIT_NOFILE))
```

___
___
*[`libos/src/sys/libos_dup.c` line 61 at r1](https://reviewable.io/reviews/gramineproject/gramine/887#-NBLq4oo1pSj5x2h3ONN:-NBLq4oo1pSj5x2h3ONO:b-ex3hl6) ([raw file](https://github.com/gramineproject/gramine/blob/7b18a539ee4fbadcd5c997e5aec111fde5166732/libos/src/sys/libos_dup.c#L61)):*
> ```C
> 
>     if (newfd >= getrlimit_cur(RLIMIT_NOFILE))
>         return -EBADF;
> ```

Maybe this unblocks any LTP `dup3` test? Could you check?


<!-- Sent from Reviewable.io -->

2022-09-07 10:24 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/887)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/887#-NBLplyb2tdWxJsLRs3_:-NBMT3PO3k9azhLR0u1h:bv7jgj8) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

CI failed with:
```
23:07:27  ../libos/src/sys/libos_dup.c: In function ‘libos_syscall_dup3’:
23:07:27  ../libos/src/sys/libos_dup.c:60:18: error: implicit declaration of function ‘getrlimit_cur’; did you mean ‘get_rlimit_cur’? [-Werror=implicit-function-declaration]
23:07:27       if (newfd >= getrlimit_cur(RLIMIT_NOFILE))
23:07:27                    ^~~~~~~~~~~~~
23:07:27                    get_rlimit_cur
23:07:27  ../libos/src/sys/libos_dup.c:60:15: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
23:07:27       if (newfd >= getrlimit_cur(RLIMIT_NOFILE))
```
</blockquote></details>

Done. [oops...]

___
___
*[`libos/src/sys/libos_dup.c` line 61 at r1](https://reviewable.io/reviews/gramineproject/gramine/887#-NBLq4oo1pSj5x2h3ONN:-NBMTTqR4EOAp8uOYx8g:b-xdkr8p) ([raw file](https://github.com/gramineproject/gramine/blob/7b18a539ee4fbadcd5c997e5aec111fde5166732/libos/src/sys/libos_dup.c#L61)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Maybe this unblocks any LTP `dup3` test? Could you check?
</blockquote></details>

It looks like all dup3 tests were already running.


<!-- Sent from Reviewable.io -->

2022-09-07 11:37 UTC, boryspoplawski approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/887)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2022-09-07 11:38 UTC, boryspoplawski commented
Jenkins, test this please

2022-09-07 12:58 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/887)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2022-09-14 11:18 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/887)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2022-09-14 14:15 UTC, dimakuv commented
Jenkins, test this please

2022-09-14 14:17 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/887)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-09-15 06:38 UTC, merged