[LibOS,PAL,Docs] Introduce `etc` emulation (currently only 'resolv.conf')
gramineproject/gramine pull request #889
Opened 2022-09-06 18:47 UTC by oshogbo

## Description of the changes 

The first `etc` passthrough file is the `/etc/hostname`. Gramine reads the option to global PAL state, and LibOS uses it to create a pseudo file with its content. Gramine sanitizes hostname. 

In case of `nameserver` we support only IPv4 in canonical form and with skipped zeros (eg. 8.8, 8, 8.8.8), and IPv6 in abbreviations (`::1`, `ff::1:2`) and full IP addresses.
In case of `search` we expects a valid hostname.

## Issue

https://github.com/gramineproject/gramine/issues/689

## Next step

* Add support for `hostname`

## How to test this PR?

Check if `/etc/resolv.conf` is exists with the valid content.

2022-09-07 10:34 UTC, dimakuv requested changes
> Reviewed 7 of 19 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/889)* status: 7 of 19 files reviewed, 21 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/889#-NBLwQun6_EV79lcXpqk:-NBLwQun6_EV79lcXpql:b-xn4da) (no related file):*
The PR description is wrong? Why does it talk about the hostname?

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/889#-NBMNI_W3G6xQTKtC2ux:-NBMNI_W3G6xQTKtC2uy:bhmfpxn) (no related file):*
On a range of my local machines, I checked `/etc/resolv.conf`. The range of machines included:
- Docker containers
- My local dev machine with Ubuntu 20.04
- My local perf machine with CentOS 8
- My private Azure VM

I did *not* find `sortlist` keyword in any of the files. So unless others find it on their deployments, it seems fine to **ignore this keyword**.

However, I found the following `options` keywords on my Azure VM:
```bash
dimakuv@accvm:~$ cat /etc/resolv.conf
nameserver 127.0.0.53
options edns0 trust-ad    # note this!
search anxjiuxym1nefegvxud0s5rhfb.bx.internal.cloudapp.net
```

I haven't checked this PR yet, but I would do the following with the options:
- `edns0` -- recognize it and propagate into Gramine
- `trust-ad` -- recognize it but *do not propagate* into Gramine

___
___
*[`Documentation/manifest-syntax.rst` line 158 at r1](https://reviewable.io/reviews/gramineproject/gramine/889#-NBML3Ri6MFKovAaNJ1J:-NBML3Rj3J9cWqdz2M7C:bt8uoxg) ([raw file](https://github.com/gramineproject/gramine/blob/de0734e7b190ebbfdee8b7980841db442cb62787/Documentation/manifest-syntax.rst#L158)):*
> ```reStructuredText
> This specifies whether to emulate runtime files under ``/etc``.
> In the case of Linux-SGX PAL, this is achieved by taking the host's ``/etc``
> files, filter supported options, and sanitize them.
> ```

And in case of other PALs (e.g. Linux)? This description is ambigious.

I think we need to write something like this:
```
This is achieved by taking the host's ``/etc`` files, parsing them, and re-creating them
inside Gramine's file system. For security-enforcing modes (such as SGX), Gramine
additionally sanitizes the contents of these files, failing if any of the files is
incorrectly formatted.

Note that Gramine's parsers for these files support only a subset of the corresponding
specifications. See below for the list of supported keywords/formats for each file.

The set of extra runtime files ...
```
___
*[`Documentation/manifest-syntax.rst` line 158 at r1](https://reviewable.io/reviews/gramineproject/gramine/889#-NBMM7KRB_LShXE27Tmk:-NBMM7KRB_LShXE27Tml:b-pc7qmm) ([raw file](https://github.com/gramineproject/gramine/blob/de0734e7b190ebbfdee8b7980841db442cb62787/Documentation/manifest-syntax.rst#L158)):*
> ```reStructuredText
> This specifies whether to emulate runtime files under ``/etc``.
> In the case of Linux-SGX PAL, this is achieved by taking the host's ``/etc``
> files, filter supported options, and sanitize them.
> ```

What do you mean by `filter supported options`? Does Gramine **fail** if it finds an unsupported option, or simply **removes it** from the in-Gramine representation?
___
*[`Documentation/manifest-syntax.rst` line 166 at r1](https://reviewable.io/reviews/gramineproject/gramine/889#-NBMOkZDBhYTdBVMkOTa:-NBMOkZDBhYTdBVMkOTb:b-m0jb5r) ([raw file](https://github.com/gramineproject/gramine/blob/de0734e7b190ebbfdee8b7980841db442cb62787/Documentation/manifest-syntax.rst#L166)):*
> ```reStructuredText
>    - ``nameserver``
>    - ``search``
>    - ``options`` (``inet6`` | ``rotate``)
> ```

I feel like `ndots:n` may be important to parse & propagate to Gramine?
___
*[`Documentation/manifest-syntax.rst` line 166 at r1](https://reviewable.io/reviews/gramineproject/gramine/889#-NBMPFtNE0aqpuKnCIOB:-NBMPFtO0GmsXGxaVh4J:bczvd04) ([raw file](https://github.com/gramineproject/gramine/blob/de0734e7b190ebbfdee8b7980841db442cb62787/Documentation/manifest-syntax.rst#L166)):*
> ```reStructuredText
>    - ``nameserver``
>    - ``search``
>    - ``options`` (``inet6`` | ``rotate``)
> ```

I see no problem in supporting `use-vc` option, but not blocking
___
*[`libos/src/fs/etc/fs.c` line 15 at r1](https://reviewable.io/reviews/gramineproject/gramine/889#-NBMRBrN9YjuJkS9hbOY:-NBMRBrN9YjuJkS9hbOZ:bb07ljd) ([raw file](https://github.com/gramineproject/gramine/blob/de0734e7b190ebbfdee8b7980841db442cb62787/libos/src/fs/etc/fs.c#L15)):*
> ```C
> #include "libos_fs_pseudo.h"
> 
> static int put_string(char** buf, ssize_t* bufsize, const char* fmt, ...) {
> ```

Why `ssize_t`? Simply `size_t`
___
*[`libos/src/fs/etc/fs.c` line 21 at r1](https://reviewable.io/reviews/gramineproject/gramine/889#-NBMQM_w13kkIUSQt_Jq:-NBMQM_w13kkIUSQt_Jr:b-gsp1wg) ([raw file](https://github.com/gramineproject/gramine/blob/de0734e7b190ebbfdee8b7980841db442cb62787/libos/src/fs/etc/fs.c#L21)):*
> ```C
>     va_end(ap);
>     if (ret < 0)
>         return ret;
> ```

I think you should also fail when truncation happened:
```
if (ret >= *bufsize)
    return -EOVERFLOW;
```

And you can remove the below assert.
___
*[`libos/src/fs/etc/fs.c` line 26 at r1](https://reviewable.io/reviews/gramineproject/gramine/889#-NBMR-i88me-moU3UbSg:-NBMR-i88me-moU3UbSh:bpbvvk5) ([raw file](https://github.com/gramineproject/gramine/blob/de0734e7b190ebbfdee8b7980841db442cb62787/libos/src/fs/etc/fs.c#L26)):*
> ```C
>     *buf += ret;
> 
>     return ret;
> ```

Please simply `return 0`.
___
*[`libos/src/fs/etc/fs.c` line 29 at r1](https://reviewable.io/reviews/gramineproject/gramine/889#-NBMVOm4EQNL-_EATo0E:-NBMVOm4EQNL-_EATo0F:bbft6u1) ([raw file](https://github.com/gramineproject/gramine/blob/de0734e7b190ebbfdee8b7980841db442cb62787/libos/src/fs/etc/fs.c#L29)):*
> ```C
> }
> 
> static int provide_etc_resolv(struct libos_dentry* dent, char** out_data, size_t* out_size) {
> ```

I'd rename to `provide_etc_resolv_conf`, so it is clear to what file it refers to
___
*[`libos/src/fs/etc/fs.c` line 32 at r1](https://reviewable.io/reviews/gramineproject/gramine/889#-NBMRFTqCsIcO28GH3Tr:-NBMRFTqCsIcO28GH3Ts:bb07ljd) ([raw file](https://github.com/gramineproject/gramine/blob/de0734e7b190ebbfdee8b7980841db442cb62787/libos/src/fs/etc/fs.c#L32)):*
> ```C
>     __UNUSED(dent);
> 
>     ssize_t size = 0;
> ```

Why `ssize_t`? Simply `size_t`
___
*[`libos/src/fs/etc/fs.c` line 39 at r1](https://reviewable.io/reviews/gramineproject/gramine/889#-NBMRz4RBlr_xCBQiu_B:-NBMRz4RBlr_xCBQiu_C:b-pn0238) ([raw file](https://github.com/gramineproject/gramine/blob/de0734e7b190ebbfdee8b7980841db442cb62787/libos/src/fs/etc/fs.c#L39)):*
> ```C
>     /* search - lets assume maximum length of entries, plus a new line and white spaces */
>     size += strlen("search") + 1;
>     size += g_pal_public_state->dns_host.dnsrch_count * (PAL_HOSTNAME_MAX + 1);
> ```

I assume that `+ 1` here is for the whitespace between local domain names?
___
*[`libos/src/fs/etc/fs.c` line 39 at r1](https://reviewable.io/reviews/gramineproject/gramine/889#-NBMU6XzAFM7D34FQwCD:-NBMU6XzAFM7D34FQwCE:b-nc79kw) ([raw file](https://github.com/gramineproject/gramine/blob/de0734e7b190ebbfdee8b7980841db442cb62787/libos/src/fs/etc/fs.c#L39)):*
> ```C
>     /* search - lets assume maximum length of entries, plus a new line and white spaces */
>     size += strlen("search") + 1;
>     size += g_pal_public_state->dns_host.dnsrch_count * (PAL_HOSTNAME_MAX + 1);
> ```

Shouldn't you `size += 1;` for the newline of the `search ...` line?
___
*[`libos/src/fs/etc/fs.c` line 41 at r1](https://reviewable.io/reviews/gramineproject/gramine/889#-NBMSFy276Y8sxqo_alF:-NBMSFy276Y8sxqo_alG:b-9bpo9j) ([raw file](https://github.com/gramineproject/gramine/blob/de0734e7b190ebbfdee8b7980841db442cb62787/libos/src/fs/etc/fs.c#L41)):*
> ```C
>     size += g_pal_public_state->dns_host [...]

2022-09-07 11:41 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/889)* status: 5 of 19 files reviewed, 21 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/889#-NBLwQun6_EV79lcXpqk:-NBMdRKhA2RUgzybZYW3:bq782g7) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

The PR description is wrong? Why does it talk about the hostname?
</blockquote></details>

Yes, my bad.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/889#-NBMNI_W3G6xQTKtC2ux:-NBMdbmkBe27Ixo6IP0E:bacuc8i) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

On a range of my local machines, I checked `/etc/resolv.conf`. The range of machines included:
- Docker containers
- My local dev machine with Ubuntu 20.04
- My local perf machine with CentOS 8
- My private Azure VM

I did *not* find `sortlist` keyword in any of the files. So unless others find it on their deployments, it seems fine to **ignore this keyword**.

However, I found the following `options` keywords on my Azure VM:
```bash
dimakuv@accvm:~$ cat /etc/resolv.conf
nameserver 127.0.0.53
options edns0 trust-ad    # note this!
search anxjiuxym1nefegvxud0s5rhfb.bx.internal.cloudapp.net
```

I haven't checked this PR yet, but I would do the following with the options:
- `edns0` -- recognize it and propagate into Gramine
- `trust-ad` -- recognize it but *do not propagate* into Gramine
</blockquote></details>

So I proposed more extensive list of it, but Borys suggested in issue to limit it to minimum (https://github.com/gramineproject/gramine/issues/689).

```
Do you think it's worth implementing so many options initially? I would say most common ones (name server and search) would be enough for start? (disclaimer: I'm no sysadmin)
```

Adding new options is very simple so not sure what to do.
So maybe for now lets not discuss in this PR which options should or should not be supported, because there are very easy to add and lets focus on the reset.

___
___
*[`Documentation/manifest-syntax.rst` line 158 at r1](https://reviewable.io/reviews/gramineproject/gramine/889#-NBMM7KRB_LShXE27Tmk:-NBMchXm6teezn83Ql3P:b-pakvaj) ([raw file](https://github.com/gramineproject/gramine/blob/de0734e7b190ebbfdee8b7980841db442cb62787/Documentation/manifest-syntax.rst#L158)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What do you mean by `filter supported options`? Does Gramine **fail** if it finds an unsupported option, or simply **removes it** from the in-Gramine representation?
</blockquote></details>

Just ignores it.
___
*[`Documentation/manifest-syntax.rst` line 158 at r1](https://reviewable.io/reviews/gramineproject/gramine/889#-NBML3Ri6MFKovAaNJ1J:-NBMiIk61FxPFeGMV6fb:b-adp60) ([raw file](https://github.com/gramineproject/gramine/blob/de0734e7b190ebbfdee8b7980841db442cb62787/Documentation/manifest-syntax.rst#L158)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

And in case of other PALs (e.g. Linux)? This description is ambigious.

I think we need to write something like this:
```
This is achieved by taking the host's ``/etc`` files, parsing them, and re-creating them
inside Gramine's file system. For security-enforcing modes (such as SGX), Gramine
additionally sanitizes the contents of these files, failing if any of the files is
incorrectly formatted.

Note that Gramine's parsers for these files support only a subset of the corresponding
specifications. See below for the list of supported keywords/formats for each file.

The set of extra runtime files ...
```
</blockquote></details>

We don't really fails, if the files are wrongly formated, we will just print errors/warnings.
___
*[`Documentation/manifest-syntax.rst` line 166 at r1](https://reviewable.io/reviews/gramineproject/gramine/889#-NBMOkZDBhYTdBVMkOTa:-NBMcj138svaSWHKljRq:bs4q9op) ([raw file](https://github.com/gramineproject/gramine/blob/de0734e7b190ebbfdee8b7980841db442cb62787/Documentation/manifest-syntax.rst#L166)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I feel like `ndots:n` may be important to parse & propagate to Gramine?
</blockquote></details>

Ditto.
___
*[`Documentation/manifest-syntax.rst` line 166 at r1](https://reviewable.io/reviews/gramineproject/gramine/889#-NBMPFtNE0aqpuKnCIOB:-NBMdajv4DpLave6omdH:bs4q9op) ([raw file](https://github.com/gramineproject/gramine/blob/de0734e7b190ebbfdee8b7980841db442cb62787/Documentation/manifest-syntax.rst#L166)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I see no problem in supporting `use-vc` option, but not blocking
</blockquote></details>

Ditto.
___
*[`libos/src/fs/etc/fs.c` line 15 at r1](https://reviewable.io/reviews/gramineproject/gramine/889#-NBMRBrN9YjuJkS9hbOY:-NBMjaqa50Dw13E83lV7:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/de0734e7b190ebbfdee8b7980841db442cb62787/libos/src/fs/etc/fs.c#L15)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why `ssize_t`? Simply `size_t`
</blockquote></details>

Done.
___
*[`libos/src/fs/etc/fs.c` line 21 at r1](https://reviewable.io/reviews/gramineproject/gramine/889#-NBMQM_w13kkIUSQt_Jq:-NBMdsNw2xBPjygf0Kad:bcr097q) ([raw file](https://github.com/gramineproject/gramine/blob/de0734e7b190ebbfdee8b7980841db442cb62787/libos/src/fs/etc/fs.c#L21)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I think you should also fail when truncation happened:
```
if (ret >= *bufsize)
    return -EOVERFLOW;
```

And you can remove the below assert.
</blockquote></details>

Can it happend?
This is why we overestimate the size of buffer, and try just the assert it.
___
*[`libos/src/fs/etc/fs.c` line 26 at r1](https://reviewable.io/reviews/gramineproject/gramine/889#-NBMR-i88me-moU3UbSg:-NBMitoQ0bKiR0on014X:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/de0734e7b190ebbfdee8b7980841db442cb62787/libos/src/fs/etc/fs.c#L26)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please simply `return 0`.
</blockquote></details>

Done.
___
*[`libos/src/fs/etc/fs.c` line 29 at r1](https://reviewable.io/reviews/gramineproject/gramine/889#-NBMVOm4EQNL-_EATo0E:-NBMj-1tCat2NYaaEBRR:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/de0734e7b190ebbfdee8b7980841db442cb62787/libos/src/fs/etc/fs.c#L29)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I'd rename to `provide_etc_resolv_conf`, so it is clear to what file it refers to
</blockquote></details>

Done.
___
*[`libos/src/fs/etc/fs.c` line 32 at r1](https://reviewable.io/reviews/gramineproject/gramine/889#-NBMRFTqCsIcO28GH3Tr:-NBMj28qDncvSwcQcdsF:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/de0734e7b190ebbfdee8b7980841db442cb62787/libos/src/fs/etc/fs.c#L32)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why `ssize_t`? Simply `size_t`
</blockquote></details>

Done.
___
*[`libos/src/fs/etc/fs.c` line 39 at r1](https://reviewable.io/reviews/gramineproject/gramine/889#-NBMRz4RBlr_xCBQiu_B:-NBMcLbv0RB8sFkmaI76:b-4ib9fy) ([raw file](https://github.com/gramineproject/gramine/blob/de0734e7b190ebbfdee8b7980841db442cb62787/libos/src/fs/etc/fs.c#L39)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I assume that `+ 1` here is for the whitespace between local domain names?
</blockquote></details [...]

2022-09-07 13:12 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/889)* status: all files reviewed, 58 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/889#-NBMNI_W3G6xQTKtC2ux:-NBN21LLBV2dN2jG0Mug:b-xi3d4r) (no related file):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

So I proposed more extensive list of it, but Borys suggested in issue to limit it to minimum (https://github.com/gramineproject/gramine/issues/689).

```
Do you think it's worth implementing so many options initially? I would say most common ones (name server and search) would be enough for start? (disclaimer: I'm no sysadmin)
```

Adding new options is very simple so not sure what to do.
So maybe for now lets not discuss in this PR which options should or should not be supported, because there are very easy to add and lets focus on the reset.
</blockquote></details>

OK. I'm fine with this.

I think we'll need to create follow-up PRs with the following additional keywords immediately:
- `options edns0` -- propagate into Gramine
- `options trust-ad` -- ignore with some clear log message
- `ndots:n` -- propagate into Gramine
- `use-vc` -- propagate into Gramine

___
___
*[`Documentation/manifest-syntax.rst` line 161 at r2](https://reviewable.io/reviews/gramineproject/gramine/889#-NBN2dC8Ey1KPGmMF8l7:-NBN2dC8Ey1KPGmMF8l8:b-lrag2f) ([raw file](https://github.com/gramineproject/gramine/blob/bf3afd8741cdb79c6b83e5372f3a1feceec8e81f/Documentation/manifest-syntax.rst#L161)):*
> ```reStructuredText
> 
> Note that Gramine's parsers for these files support only a subset of the corresponding
> specifications. See below for the list of supported keywords/formats for each file.
> ```

Please re-wrap to 80 chars per limit (we use 80 for documentation, 100 for code)
___
*[`Documentation/manifest-syntax.rst` line 161 at r2](https://reviewable.io/reviews/gramineproject/gramine/889#-NBN2vPg7MRQnNqKODsk:-NBN2vPg7MRQnNqKODsl:b-dqrxrl) ([raw file](https://github.com/gramineproject/gramine/blob/bf3afd8741cdb79c6b83e5372f3a1feceec8e81f/Documentation/manifest-syntax.rst#L161)):*
> ```reStructuredText
> 
> Note that Gramine's parsers for these files support only a subset of the corresponding
> specifications. See below for the list of supported keywords/formats for each file.
> ```

Please add a sentence that all other keywords/formats are ignored, with warning messages.
___
*[`libos/src/fs/etc/fs.c` line 21 at r1](https://reviewable.io/reviews/gramineproject/gramine/889#-NBMQM_w13kkIUSQt_Jq:-NBN3CszBHqbMZPhE-Mh:bwyuydx) ([raw file](https://github.com/gramineproject/gramine/blob/de0734e7b190ebbfdee8b7980841db442cb62787/libos/src/fs/etc/fs.c#L21)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Can it happend?
This is why we overestimate the size of buffer, and try just the assert it.
</blockquote></details>

I mean, it can if there is a very-very long option name that doesn't fit into 32 chars. This overestimation is not precise and may not cover all cases in the real world, and we end up with buffer overflows in production mode of Gramine.
___
*[`libos/src/fs/etc/fs.c` line 39 at r1](https://reviewable.io/reviews/gramineproject/gramine/889#-NBMU6XzAFM7D34FQwCD:-NBN3aW1BwzZCX-33DaG:b-obe4k0) ([raw file](https://github.com/gramineproject/gramine/blob/de0734e7b190ebbfdee8b7980841db442cb62787/libos/src/fs/etc/fs.c#L39)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

It is ther:
`size += strlen("search") + 1;` // search + new_line
`dns_host.dnsrch_count * (PAL_HOSTNAME_MAX + 1)` -> size of hostname + 1 whitespace
</blockquote></details>

Ah, this way. Got it.
___
*[`libos/src/fs/etc/fs.c` line 41 at r1](https://reviewable.io/reviews/gramineproject/gramine/889#-NBMSFy276Y8sxqo_alF:-NBN3h768TGDefgk_pgi:bqo2r46) ([raw file](https://github.com/gramineproject/gramine/blob/de0734e7b190ebbfdee8b7980841db442cb62787/libos/src/fs/etc/fs.c#L41)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

32 is covering all of it here, but I will do this more explicate maybe.
</blockquote></details>

Yes, please, make it more explicit.
___
*[`libos/src/fs/etc/fs.c` line 83 at r1](https://reviewable.io/reviews/gramineproject/gramine/889#-NBMUTja2DPh8ahtjib9:-NBN3xQd-PLAyW4pzNma:bkt5zvp) ([raw file](https://github.com/gramineproject/gramine/blob/de0734e7b190ebbfdee8b7980841db442cb62787/libos/src/fs/etc/fs.c#L83)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

This is correct formatting, and I think it is easier to generate it.
But If you really want I can change it.

</blockquote></details>

How are you sure that this is correct formatting? Could you give me a link to the spec or e.g. Glibc resolver code?


<!-- Sent from Reviewable.io -->

2022-09-07 18:20 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/889)* status: all files reviewed, 58 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @oshogbo)

___
*[`Documentation/manifest-syntax.rst` line 161 at r2](https://reviewable.io/reviews/gramineproject/gramine/889#-NBN2dC8Ey1KPGmMF8l7:-NBNjf3WEi242aOYCbF8:bivh0t2) ([raw file](https://github.com/gramineproject/gramine/blob/bf3afd8741cdb79c6b83e5372f3a1feceec8e81f/Documentation/manifest-syntax.rst#L161)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please re-wrap to 80 chars per limit (we use 80 for documentation, 100 for code)
</blockquote></details>

Oh, I was mislead because `log level` section is a little bit longer.
Sorry for that.
___
*[`Documentation/manifest-syntax.rst` line 161 at r2](https://reviewable.io/reviews/gramineproject/gramine/889#-NBN2vPg7MRQnNqKODsk:-NBNkA1ZCQLmDtFnzLVy:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/bf3afd8741cdb79c6b83e5372f3a1feceec8e81f/Documentation/manifest-syntax.rst#L161)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add a sentence that all other keywords/formats are ignored, with warning messages.
</blockquote></details>

Done.
___
*[`libos/src/fs/etc/fs.c` line 21 at r1](https://reviewable.io/reviews/gramineproject/gramine/889#-NBMQM_w13kkIUSQt_Jq:-NBNfKDI-IWWCNBUSBDQ:bc78siq) ([raw file](https://github.com/gramineproject/gramine/blob/de0734e7b190ebbfdee8b7980841db442cb62787/libos/src/fs/etc/fs.c#L21)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I mean, it can if there is a very-very long option name that doesn't fit into 32 chars. This overestimation is not precise and may not cover all cases in the real world, and we end up with buffer overflows in production mode of Gramine.
</blockquote></details>

Yea, but there isn't any very-very long option name, because it is fixed list. 32 chars are defined for inet6 (14 characters) and rotate (15 characters), so when you add new option you still have to add space for it and you can add 32 chars or 128 chars or whatever size you need, as this is a boolean filed. Besides the HOSTNAME, which we check during the  pal we don't paste anything direct from user, every option length (at least for now is controlled by us this is why I check this with assert).

Please check current version, maybe it is more readable.
___
*[`libos/src/fs/etc/fs.c` line 41 at r1](https://reviewable.io/reviews/gramineproject/gramine/889#-NBMSFy276Y8sxqo_alF:-NBNiYjT9nPB5reBnZDJ:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/de0734e7b190ebbfdee8b7980841db442cb62787/libos/src/fs/etc/fs.c#L41)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, please, make it more explicit.
</blockquote></details>

Done.
___
*[`libos/src/fs/etc/fs.c` line 83 at r1](https://reviewable.io/reviews/gramineproject/gramine/889#-NBMUTja2DPh8ahtjib9:-NBNIbU_DjprSuu7vGic:b-93djsh) ([raw file](https://github.com/gramineproject/gramine/blob/de0734e7b190ebbfdee8b7980841db442cb62787/libos/src/fs/etc/fs.c#L83)):*
> Glibc resolver code
Sure.

https://elixir.bootlin.com/glibc/latest/source/resolv/res_init.c#L508

getline is called for each loop, and the setoptions are not clearing previous options.
___
*[`pal/include/pal/pal.h` line 37 at r1](https://reviewable.io/reviews/gramineproject/gramine/889#-NBMgVuf9_Or7Und_OeR:-NBNinex3jh3BnK_uWfR:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/de0734e7b190ebbfdee8b7980841db442cb62787/pal/include/pal/pal.h#L37)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

maybe, `..., used in resolv.conf emulation`
</blockquote></details>

Done.
___
*[`pal/include/pal/pal.h` line 38 at r1](https://reviewable.io/reviews/gramineproject/gramine/889#-NBMgKqhCAsKfQA4pCh_:-NBNipKJ-_ZbmcaGAZh0:brycvqo) ([raw file](https://github.com/gramineproject/gramine/blob/de0734e7b190ebbfdee8b7980841db442cb62787/pal/include/pal/pal.h#L38)):*
> namespace

I took the names from the `libresolv`, but maybe we just call it PAL_MAN_NAMESPACE, and make it obvious without comment.
___
*[`pal/include/pal/pal.h` line 39 at r1](https://reviewable.io/reviews/gramineproject/gramine/889#-NBMgOVk2fMBh14yamgm:-NBNj3YI8yQUdr1JeZO4:b-rqxvo7) ([raw file](https://github.com/gramineproject/gramine/blob/de0734e7b190ebbfdee8b7980841db442cb62787/pal/include/pal/pal.h#L39)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I would add a comment that this is the max number of `search` local domain names
</blockquote></details>

ditto.
___
*[`pal/include/pal/pal.h` line 107 at r1](https://reviewable.io/reviews/gramineproject/gramine/889#-NBMgzWODk1P-QO43LAS:-NBNj9418fDNHpwgrLMK:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/de0734e7b190ebbfdee8b7980841db442cb62787/pal/include/pal/pal.h#L107)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I would add a top comment here `/* Used in resolv.conf emulation */`
</blockquote></details>

Done.
___
*[`pal/src/host/linux/pal_main.c` line 130 at r1](https://reviewable.io/reviews/gramineproject/gramine/889#-NBMhMKK8HPKYDmmCgaz:-NBNjRrICxuFjvqCm7nW:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/de0734e7b190ebbfdee8b7980841db442cb62787/pal/src/host/linux/pal_main.c#L130)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I would prefer the full name `/etc/resolv.conf`

Also, maybe `get` -> `parse`?
</blockquote></details>

Done.



_Code quote:_
```C
get_resolv_conf
```
___
*[`pal/src/host/linux/pal_main.c` line 423 at r1](https://reviewable.io/reviews/gramineproject/gramine/889#-NBMhZLe57Jkv0vykN8A:-NBNjVil3zzblbZuttDz:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/de0734e7b190ebbfdee8b7980841db442cb62787/pal/src/host/linux/pal_main.c#L423)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please align to the beginning of the first arg.
</blockquote></details>

Done.
___
*[`pal/src/host/linux/pal_main.c` line 428 at r1](https://reviewable.io/reviews/gramineproject/gramine/889#-NBMheTK8_LGsqvgZ7fM:-NBNjabJ7ac9wV0ORfu2:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/de0734e7b190ebbfdee8b7980841db442cb62787/pal/src/host/linux/pal_main.c#L428)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`Get host information` -> `Get host /etc information`
</blockquote></details>

Done.
___
*[`pal/src/host/linux-common/etc_host_info.c` line 7 at r1](https://reviewable.io/reviews/gramineproject/gramine/889#-NBMnmHN4jAmH225oZo3:-NBNkKnr8L0S0Eyd-vKd:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/de0734e7b190ebbfdee8b7980841db442cb62787/pal/src/host/linux-common/etc_host_info.c#L7)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I would add smth like this:
```
/*
 * This file contains the APIs to expose host information:
 *   - parses host file `/etc/resolv.conf` into `struct pal_dns_host_conf`
```

And in follow up PRs (if any), add more items to this list
</blockquote></details>

Done.
___
*[`pal/src/host/linux-common/etc_host_info.c` line 10 at r1](https://reviewable.io/reviews/gramineproject/gramine/889#-NBMo7Qa4eaeQEdndQ0X:-NBNkL7j4vNb64cQgd-v:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/de0734e7b190ebbfdee8b7980841db442cb62787/pal/src/host/linux-common/etc_host_info.c#L10)):*
<details><summary><i>Previously, dimak [...]

2022-09-07 21:07 UTC, mkow requested changes
> Reviewed 5 of 19 files at r1, 2 of 13 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/889)* status: 8 of 19 files reviewed, 65 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @oshogbo)

___
*[`-- commits` line 2 at r3](https://reviewable.io/reviews/gramineproject/gramine/889#-NBO_aTSAvmQ-pzQYu4x):*
I'd drop "Docs", it's implied by the change itself - i.e. when we add a feature to e.g. LibOS then we don't say that we modified LibOS and Docs, just LibOS ;) (and use "Docs" only for documentation-only commits)



_Suggestion:_
```
[LibOS,PAL]
```
___
*[`-- commits` line 4 at r3](https://reviewable.io/reviews/gramineproject/gramine/889#-NBO_yXQ8E6mLUWyR87b):*




_Suggestion:_
```
from the host
```
___
*[`Documentation/manifest-syntax.rst` line 156 at r3](https://reviewable.io/reviews/gramineproject/gramine/889#-NBObm4t7fQoqjOOuuGK:-NBObm4t7fQoqjOOuuGL:b-lze70i) ([raw file](https://github.com/gramineproject/gramine/blob/7b26e658f93d0952a53742adf1c1c33f24862d53/Documentation/manifest-syntax.rst#L156)):*
> ```reStructuredText
>     (Default: false)
> 
> This is achieved by taking the host's ``/etc`` files, parsing them, and
> ```

This reads weirdly, what is achieved by this? First sentence / paragraph should be about that "this" which implementation you describe here. I.e. start with saying that this enables emulation of \<list here\> files under etc.



_Code quote:_
```reStructuredText
This is achieved by
```
___
*[`Documentation/manifest-syntax.rst` line 156 at r3](https://reviewable.io/reviews/gramineproject/gramine/889#-NBOcmcA5zOJgcZFQ3gQ:-NBOcmcA5zOJgcZFQ3gR:brk62vs) ([raw file](https://github.com/gramineproject/gramine/blob/7b26e658f93d0952a53742adf1c1c33f24862d53/Documentation/manifest-syntax.rst#L156)):*
> ```reStructuredText
>     (Default: false)
> 
> This is achieved by taking the host's ``/etc`` files, parsing them, and
> ```

This is valid only assuming Linux PALs, on other PALs it will work differently (query a different OS API to gather this info).



_Code quote:_
```reStructuredText
by taking the host's ``/etc`` files
```
___
*[`Documentation/manifest-syntax.rst` line 178 at r3](https://reviewable.io/reviews/gramineproject/gramine/889#-NBOd4uo6otG0-91F2iG:-NBOd4uo6otG0-91F2iH:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/7b26e658f93d0952a53742adf1c1c33f24862d53/Documentation/manifest-syntax.rst#L178)):*
> ```reStructuredText
> This option takes precedence over ``fs.mounts``.
> This means that etc files provided via ``fs.mounts`` will be overridden with
> the ones sanitized by LibOS.
> ```





_Suggestion:_
```reStructuredText
the ones added via this option
```
___
*[`libos/src/fs/etc/fs.c` line 21 at r1](https://reviewable.io/reviews/gramineproject/gramine/889#-NBMQM_w13kkIUSQt_Jq:-NBOfOCU78hOarqFh_jh:b-tsy0o2) ([raw file](https://github.com/gramineproject/gramine/blob/de0734e7b190ebbfdee8b7980841db442cb62787/libos/src/fs/etc/fs.c#L21)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Yea, but there isn't any very-very long option name, because it is fixed list. 32 chars are defined for inet6 (14 characters) and rotate (15 characters), so when you add new option you still have to add space for it and you can add 32 chars or 128 chars or whatever size you need, as this is a boolean filed. Besides the HOSTNAME, which we check during the  pal we don't paste anything direct from user, every option length (at least for now is controlled by us this is why I check this with assert).

Please check current version, maybe it is more readable.
</blockquote></details>

I think I understand @oshogbo's point, but it still seems a bit dangerous for me if we miscalculate something. We have that assert, but it can only detect the inputs which we actually test.
IMO making this assert an `if` cost nothing and makes this code less error prone.
___
*[`libos/src/fs/etc/fs.c` line 83 at r1](https://reviewable.io/reviews/gramineproject/gramine/889#-NBMUTja2DPh8ahtjib9:-NBOkC_6DiAhUlMei2JF:beq7cia) ([raw file](https://github.com/gramineproject/gramine/blob/de0734e7b190ebbfdee8b7980841db442cb62787/libos/src/fs/etc/fs.c#L83)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

> Glibc resolver code
Sure.

https://elixir.bootlin.com/glibc/latest/source/resolv/res_init.c#L508

getline is called for each loop, and the setoptions are not clearing previous options.
</blockquote></details>

[The docs](https://man7.org/linux/man-pages/man5/resolv.conf.5.html) are unclear on this, but on the other hand it makes the code much simpler. No strong preferences from my side.
___
*[`libos/src/fs/etc/fs.c` line 46 at r3](https://reviewable.io/reviews/gramineproject/gramine/889#-NBOgK_VAI3LbYRX4bv3:-NBOgK_VAI3LbYRX4bv4:b-olbctr) ([raw file](https://github.com/gramineproject/gramine/blob/7b26e658f93d0952a53742adf1c1c33f24862d53/libos/src/fs/etc/fs.c#L46)):*
> ```C
>     size += (g_pal_public_state->dns_host.inet6 ? strlen(OPTION_INET6) : 0) +
>             (g_pal_public_state->dns_host.rotate ? strlen(OPTION_ROTATE) : 0);
>     /* snprintf adds the terminating character */
> ```

`snprintf` has nothing to do here, this is just a standard C string NULL termination? The size until now didn't accommodate for it, so we needed to add 1.



_Code quote:_
```C
snprintf adds the terminating character
```
___
*[`libos/src/fs/etc/fs.c` line 116 at r3](https://reviewable.io/reviews/gramineproject/gramine/889#-NBOl4Ou7PClVLd83xlp:-NBOl4OvEPnvoktrLgqQ:b-psldru) ([raw file](https://github.com/gramineproject/gramine/blob/7b26e658f93d0952a53742adf1c1c33f24862d53/libos/src/fs/etc/fs.c#L116)):*
> ```C
> 
> int init_etcfs(void) {
>     pseudo_add_str(NULL, "emulate-etc-resolv-conf", &provide_etc_resolv_conf);
> ```

(this is an object name, not a function name)



_Suggestion:_
```C
"emulated-etc-resolv-conf"
```


<!-- Sent from Reviewable.io -->

2022-09-08 10:06 UTC, dimakuv requested changes
> Reviewed 6 of 13 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/889)* status: 12 of 19 files reviewed, 30 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @oshogbo)

___
*[`libos/src/fs/etc/fs.c` line 21 at r1](https://reviewable.io/reviews/gramineproject/gramine/889#-NBMQM_w13kkIUSQt_Jq:-NBRSJKq9TDALHbjXv-5:bh5qgx3) ([raw file](https://github.com/gramineproject/gramine/blob/de0734e7b190ebbfdee8b7980841db442cb62787/libos/src/fs/etc/fs.c#L21)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I think I understand @oshogbo's point, but it still seems a bit dangerous for me if we miscalculate something. We have that assert, but it can only detect the inputs which we actually test.
IMO making this assert an `if` cost nothing and makes this code less error prone.
</blockquote></details>

I agree with @mkow, I would feel safer with an `if` check.
___
*[`libos/src/fs/etc/fs.c` line 83 at r1](https://reviewable.io/reviews/gramineproject/gramine/889#-NBMUTja2DPh8ahtjib9:-NBRStieDScrApE2U1hC:bkxz38u) ([raw file](https://github.com/gramineproject/gramine/blob/de0734e7b190ebbfdee8b7980841db442cb62787/libos/src/fs/etc/fs.c#L83)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

[The docs](https://man7.org/linux/man-pages/man5/resolv.conf.5.html) are unclear on this, but on the other hand it makes the code much simpler. No strong preferences from my side.
</blockquote></details>

Thanks @oshogbo for the link. I'm satisfied now.
___
*[`pal/include/pal/pal.h` line 38 at r1](https://reviewable.io/reviews/gramineproject/gramine/889#-NBMgKqhCAsKfQA4pCh_:-NBRT7pW2A0x4tzWMN3p:buvdwvk) ([raw file](https://github.com/gramineproject/gramine/blob/de0734e7b190ebbfdee8b7980841db442cb62787/pal/include/pal/pal.h#L38)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

> namespace

I took the names from the `libresolv`, but maybe we just call it PAL_MAN_NAMESPACE, and make it obvious without comment.
</blockquote></details>

+1 for a better name
___
*[`pal/include/pal/pal.h` line 39 at r1](https://reviewable.io/reviews/gramineproject/gramine/889#-NBMgOVk2fMBh14yamgm:-NBRT9Ax40MCS17MxeUb:buvdwvk) ([raw file](https://github.com/gramineproject/gramine/blob/de0734e7b190ebbfdee8b7980841db442cb62787/pal/include/pal/pal.h#L39)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

ditto.
</blockquote></details>

+1 for a better name
___
*[`pal/src/host/linux-common/etc_host_info.c` line 40 at r1](https://reviewable.io/reviews/gramineproject/gramine/889#-NBMqlM76eGR-V3SCS_L:-NBRTc0S-NpkcaUj-24B:b-owao0v) ([raw file](https://github.com/gramineproject/gramine/blob/de0734e7b190ebbfdee8b7980841db442cb62787/pal/src/host/linux-common/etc_host_info.c#L40)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I see that you you still update `*pptr` (buffer-pointer) in this function instead of in the caller. Any particular reason? Well, I'm ok with it.
___
*[`pal/src/host/linux-common/etc_host_info.c` line 45 at r1](https://reviewable.io/reviews/gramineproject/gramine/889#-NBMonLXEBucF83Wfr43:-NBRTnYU1UB7qxPKS7QA:b-ckh8sg) ([raw file](https://github.com/gramineproject/gramine/blob/de0734e7b190ebbfdee8b7980841db442cb62787/pal/src/host/linux-common/etc_host_info.c#L45)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Sorry I don't understand.
</blockquote></details>

Ignore me, I didn't realize we use `i` after the for loop
___
*[`pal/src/host/linux-common/etc_host_info.c` line 50 at r1](https://reviewable.io/reviews/gramineproject/gramine/889#-NBMuzfH-d538dhBB2lE:-NBRUYDxEpEq-nqvN227:b-7z781t) ([raw file](https://github.com/gramineproject/gramine/blob/de0734e7b190ebbfdee8b7980841db442cb62787/pal/src/host/linux-common/etc_host_info.c#L50)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

No, after failed and succeed parsing we still jump to the end of line no matters what.
This is useful; if you have multiple options in single line, here doesn't matter so much, but I wanted to be coherent.
</blockquote></details>

Ah, right. I suggested to add the comment that "we still jump to the end of line no matter what" in that place in code, please add it. Resolving here.
___
*[`pal/src/host/linux-common/etc_host_info.c` line 66 at r1](https://reviewable.io/reviews/gramineproject/gramine/889#-NBMpiovAKjITZoPn283:-NBRVFbr8P-iz4_rRtn_:bma0sm3) ([raw file](https://github.com/gramineproject/gramine/blob/de0734e7b190ebbfdee8b7980841db442cb62787/pal/src/host/linux-common/etc_host_info.c#L66)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

https://linux.die.net/man/3/inet_aton
```
a.b.c.d
Each of the four numeric parts specifies a byte of the address; the bytes are assigned in left-to-right order to produce the binary address.

a.b.c

Parts a and b specify the first two bytes of the binary address. Part c is interpreted as a 16-bit value that defines the rightmost two bytes of the binary address. This notation is suitable for specifying (outmoded) Class B network addresses.

a.b

Part a specifies the first byte of the binary address. Part b is interpreted as a 24-bit value that defines the rightmost three bytes of the binary address. This notation is suitable for specifying (outmoded) Class C network addresses.

a

The value a is interpreted as a 32-bit value that is stored directly into the binary address without any byte rearrangement.
```

Easy way to test it:
```
$ ping 8
PING 8 (0.0.0.8): 56 data bytes
$ ping 8.8
PING 8.8 (8.0.0.8): 56 data bytes
$ ping 8.8.8
PING 8.8.8 (8.8.0.8): 56 data bytes
$ ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8): 56 data bytes
```
</blockquote></details>

Thanks! I didn't know this.
___
*[`pal/src/host/linux-common/etc_host_info.c` line 90 at r1](https://reviewable.io/reviews/gramineproject/gramine/889#-NBMs3nR0dLIbNCopkcM:-NBRW9h67VOlP3wrB99h:b-f38rj8) ([raw file](https://github.com/gramineproject/gramine/blob/de0734e7b190ebbfdee8b7980841db442cb62787/pal/src/host/linux-common/etc_host_info.c#L90)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Not sure, what you mean.
</blockquote></details>

You've done it for `twocomas` already, thanks. And regarding `i`, it was my mistake (I thought that `i` was used only inside the for loop)
___
*[`pal/src/host/linux-common/etc_host_info.c` line 106 at r1](https://reviewable.io/reviews/gramineproject/gramine/889#-NBMsTzI0UJRxyzeKDxP:-NBRXDJQ7LhvWnqiPZDx:b-qttfe) ([raw file](https://github.com/gramineproject/gramine/blob/de0734e7b190ebbfdee8b7980841db442cb62787/pal/src/host/linux-common/etc_host_info.c#L106)):*
> Yes, the i might become negative here.

How is this safe? So we can legitimately have `i = -1`, and then below we have `addr[i] = part;`. What prevents your logic from having a buffer overflow?
___
*[`pal/src/host/linux-common/etc_host_info.c` line 130 at r1](https://reviewable.io/reviews/gramineproject/gramine/889#-NBMtb63CvhS6uWyx1WN:-NBRXc3hBuasf3QwnZUe:b-mm88hq) ([raw file](https://github.com/gramineproject/gramine/blob/de0734e7b190ebbfdee8b7980841db442cb62787/pal/src/host/linux-common/etc_host_info.c#L130)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

7 or 8 (we can end the for loop with 8 as the for loop is (i < 8)).
</blockquote></details>

But `i == 8` should be impossible, no? Because for well-formed IPv6 addresses, we'll trigger `if (is_end_of_word(*next))  break;`, so the for loop will no [...]

2022-09-08 11:05 UTC, dimakuv requested changes
> Reviewed 7 of 13 files at r3.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/889)* status: all files reviewed, 26 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @oshogbo)

___
*[`pal/src/host/linux-sgx/host_main.c` line 632 at r1](https://reviewable.io/reviews/gramineproject/gramine/889#-NBMjlnd3_85Vgth5FRW:-NBRjtF9-DckzE86hRHB:b-comge5) ([raw file](https://github.com/gramineproject/gramine/blob/de0734e7b190ebbfdee8b7980841db442cb62787/pal/src/host/linux-sgx/host_main.c#L632)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You understood me wrong :)

I meant to change the arg name `emulated_etc` -> `out_emulated_etc`, not the function name.

But actually, `out_emulate_etc` is also wrong here -- we add `out_` prefix for those objects that are *created* inside the function (like strings). Sorry for the confusion, please revert all these renames back.
___
*[`pal/src/host/linux-sgx/pal_main.c` line 301 at r1](https://reviewable.io/reviews/gramineproject/gramine/889#-NBMmKs18RSc0eyiYytV:-NBRk_9M6J7OewW1AWlb:b-qa0dg9) ([raw file](https://github.com/gramineproject/gramine/blob/de0734e7b190ebbfdee8b7980841db442cb62787/pal/src/host/linux-sgx/pal_main.c#L301)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Yes, but it doesn't point out also that these data has to be sanitized (like boolean values for example) ?
</blockquote></details>

You modified this function anyway, so now my comment is irrelevant.
___
*[`pal/src/host/linux-sgx/pal_main.c` line 303 at r1](https://reviewable.io/reviews/gramineproject/gramine/889#-NBMmU_L5ZrjEqPC-S1v:-NBRkfly93DOCybx7tp7:ba7z2o3) ([raw file](https://github.com/gramineproject/gramine/blob/de0734e7b190ebbfdee8b7980841db442cb62787/pal/src/host/linux-sgx/pal_main.c#L303)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

I used long names, and this code looks very messy and confusing, especially with `memcpy`:
```
memcpy(&g_pal_public_state.dns_host->nsaddr_list[i].ipv6, &shallow_host_info->dns_host->nsaddr_list[i].ipv6, sizeof(g_pal_public_state.dns_host->nsaddr_list[i].ipv6));
```
Then I decided to use these helpers. 
We use similar helpers in topo code.
But if you really want, I can change that.
</blockquote></details>

Ok, you're right, looks ugly.
___
*[`pal/src/host/linux-sgx/pal_main.c` line 334 at r1](https://reviewable.io/reviews/gramineproject/gramine/889#-NBMmvw72jHdGmvLtEaV:-NBRl5iwBDWBmmXDVNxD:b-tylyu8) ([raw file](https://github.com/gramineproject/gramine/blob/de0734e7b190ebbfdee8b7980841db442cb62787/pal/src/host/linux-sgx/pal_main.c#L334)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

`The search entire` -> `The search domain name`

(Or I misunderstood what you wanted to say in this message?)
___
*[`pal/src/host/linux-sgx/pal_main.c` line 320 at r3](https://reviewable.io/reviews/gramineproject/gramine/889#-NBRkoPy0u9qXHyq4ktV:-NBRkoPy0u9qXHyq4ktW:b-mbjsna) ([raw file](https://github.com/gramineproject/gramine/blob/7b26e658f93d0952a53742adf1c1c33f24862d53/pal/src/host/linux-sgx/pal_main.c#L320)):*
> ```C
>                              sizeof(*uptr_dns_conf))) {
>         log_error("Unable to read host info");
>         ocall_exit(1, /*is_exitgroup=*/true);
> ```

You should `return -EINVAL;` instead.
___
*[`pal/src/host/linux-sgx/pal_main.c` line 324 at r3](https://reviewable.io/reviews/gramineproject/gramine/889#-NBRkvie08EkiOXAdyKa:-NBRkvie08EkiOXAdyKb:b-tzdy4t) ([raw file](https://github.com/gramineproject/gramine/blob/7b26e658f93d0952a53742adf1c1c33f24862d53/pal/src/host/linux-sgx/pal_main.c#L324)):*
> ```C
> 
>     if (shallow_dns.nsaddr_list_count > PAL_MAXNS) {
>         log_error("To many nameservers provided");
> ```

`To` -> `Too`
___
*[`pal/src/host/linux-sgx/pal_main.c` line 343 at r3](https://reviewable.io/reviews/gramineproject/gramine/889#-NBRl-Th2ze_qHtJgoVQ:-NBRl-Th2ze_qHtJgoVR:b-tzdy4t) ([raw file](https://github.com/gramineproject/gramine/blob/7b26e658f93d0952a53742adf1c1c33f24862d53/pal/src/host/linux-sgx/pal_main.c#L343)):*
> ```C
> 
>     if (shallow_dns.dnsrch_count > PAL_MAXDNSRCH) {
>         log_error("To many search entries provided");
> ```

`To` -> `Too`
___
*[`pal/src/host/linux-sgx/pal_main.c` line 690 at r3](https://reviewable.io/reviews/gramineproject/gramine/889#-NBRlQXD5-iyklnjsJVw:-NBRlQXD5-iyklnjsJVx:bot4ivr) ([raw file](https://github.com/gramineproject/gramine/blob/7b26e658f93d0952a53742adf1c1c33f24862d53/pal/src/host/linux-sgx/pal_main.c#L690)):*
> ```C
>         ret = import_and_sanitize_topo_info(uptr_topo_info);
>         if (ret < 0) {
>             log_error("Failed to copy and sanitize topology information");
> ```

Please add the error code itself: `...: %d", ret);`
___
*[`pal/src/host/linux-sgx/pal_main.c` line 754 at r3](https://reviewable.io/reviews/gramineproject/gramine/889#-NBRlWYh6KjvvEHUnuC1:-NBRlWYh6KjvvEHUnuC2:bot4ivr) ([raw file](https://github.com/gramineproject/gramine/blob/7b26e658f93d0952a53742adf1c1c33f24862d53/pal/src/host/linux-sgx/pal_main.c#L754)):*
> ```C
>     if (parent_stream_fd < 0) {
>         if ((ret = import_and_init_emulation_etc_files(uptr_dns_conf)) < 0) {
>             log_error("Failed to initialize host info");
> ```

Please add the error code itself: `...: %d", ret);`


<!-- Sent from Reviewable.io -->

2022-09-08 15:19 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/889)* status: 12 of 19 files reviewed, 50 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "squash! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @oshogbo)

___
*[`-- commits` line 2 at r3](https://reviewable.io/reviews/gramineproject/gramine/889#-NBO_aTSAvmQ-pzQYu4x):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd drop "Docs", it's implied by the change itself - i.e. when we add a feature to e.g. LibOS then we don't say that we modified LibOS and Docs, just LibOS ;) (and use "Docs" only for documentation-only commits)
</blockquote></details>

Done.
___
*[`-- commits` line 4 at r3](https://reviewable.io/reviews/gramineproject/gramine/889#-NBO_yXQ8E6mLUWyR87b):*
Done.
___
*[`Documentation/manifest-syntax.rst` line 156 at r3](https://reviewable.io/reviews/gramineproject/gramine/889#-NBObm4t7fQoqjOOuuGK:-NBSFUSPBt6fHBRideAA:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/7b26e658f93d0952a53742adf1c1c33f24862d53/Documentation/manifest-syntax.rst#L156)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This reads weirdly, what is achieved by this? First sentence / paragraph should be about that "this" which implementation you describe here. I.e. start with saying that this enables emulation of \<list here\> files under etc.
</blockquote></details>

Done.
___
*[`Documentation/manifest-syntax.rst` line 156 at r3](https://reviewable.io/reviews/gramineproject/gramine/889#-NBOcmcA5zOJgcZFQ3gQ:-NBSFUhkElIwjoZUWsGP:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/7b26e658f93d0952a53742adf1c1c33f24862d53/Documentation/manifest-syntax.rst#L156)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This is valid only assuming Linux PALs, on other PALs it will work differently (query a different OS API to gather this info).
</blockquote></details>

Done.
___
*[`Documentation/manifest-syntax.rst` line 178 at r3](https://reviewable.io/reviews/gramineproject/gramine/889#-NBOd4uo6otG0-91F2iG:-NBSFaBI2kbmawl0Gkxs:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/7b26e658f93d0952a53742adf1c1c33f24862d53/Documentation/manifest-syntax.rst#L178)):*
> ```reStructuredText
> This option takes precedence over ``fs.mounts``.
> This means that etc files provided via ``fs.mounts`` will be overridden with
> the ones sanitized by LibOS.
> ```

Done.
___
*[`libos/src/fs/etc/fs.c` line 21 at r1](https://reviewable.io/reviews/gramineproject/gramine/889#-NBMQM_w13kkIUSQt_Jq:-NBSFg606YNswo1Oa2dq:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/de0734e7b190ebbfdee8b7980841db442cb62787/libos/src/fs/etc/fs.c#L21)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I agree with @mkow, I would feel safer with an `if` check.
</blockquote></details>

Done.
___
*[`libos/src/fs/etc/fs.c` line 46 at r3](https://reviewable.io/reviews/gramineproject/gramine/889#-NBOgK_VAI3LbYRX4bv3:-NBSFnCC-bSzt5xxyItS:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/7b26e658f93d0952a53742adf1c1c33f24862d53/libos/src/fs/etc/fs.c#L46)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`snprintf` has nothing to do here, this is just a standard C string NULL termination? The size until now didn't accommodate for it, so we needed to add 1.
</blockquote></details>

Done.
___
*[`libos/src/fs/etc/fs.c` line 116 at r3](https://reviewable.io/reviews/gramineproject/gramine/889#-NBOl4Ou7PClVLd83xlp:-NBSFrAG1we4A9yACdaL:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/7b26e658f93d0952a53742adf1c1c33f24862d53/libos/src/fs/etc/fs.c#L116)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

(this is an object name, not a function name)
</blockquote></details>

Done.
___
*[`pal/include/pal/pal.h` line 38 at r1](https://reviewable.io/reviews/gramineproject/gramine/889#-NBMgKqhCAsKfQA4pCh_:-NBSOhvx-qGepnPlKBpz:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/de0734e7b190ebbfdee8b7980841db442cb62787/pal/include/pal/pal.h#L38)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`PAL_MAN_NAMESPACE` -> `PAL_MAX_NAMESPACES`
</blockquote></details>

Done.
___
*[`pal/include/pal/pal.h` line 39 at r1](https://reviewable.io/reviews/gramineproject/gramine/889#-NBMgOVk2fMBh14yamgm:-NBSOiCZ1BlUaWomev-n:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/de0734e7b190ebbfdee8b7980841db442cb62787/pal/include/pal/pal.h#L39)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

+1 for a better name
</blockquote></details>

Done.
___
*[`pal/include/pal/pal.h` line 110 at r3](https://reviewable.io/reviews/gramineproject/gramine/889#-NBReZXgA0K401Tf6DT-:-NBSOp1VCi1Q1dcEVVU8:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/7b26e658f93d0952a53742adf1c1c33f24862d53/pal/include/pal/pal.h#L110)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd unindent this, looks too weird to me :)
</blockquote></details>

Done.
___
*[`pal/src/host/linux/pal_main.c` line 130 at r3](https://reviewable.io/reviews/gramineproject/gramine/889#-NBRf2nv0xkxTW6ZlOQu:-NBSOs61DQyjbap4xrmY:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/7b26e658f93d0952a53742adf1c1c33f24862d53/pal/src/host/linux/pal_main.c#L130)):*
> ```C
> 
>     if (parse_resolv_conf(&g_pal_public_state.dns_host) < 0) {
>         INIT_FAIL("Unable to get /etc/resolv.conf");
> ```

Done.
___
*[`pal/src/host/linux-common/etc_host_info.c` line 66 at r1](https://reviewable.io/reviews/gramineproject/gramine/889#-NBMpiovAKjITZoPn283:-NBSUo3XAgL_F7uFTrWF:b-ioy3eh) ([raw file](https://github.com/gramineproject/gramine/blob/de0734e7b190ebbfdee8b7980841db442cb62787/pal/src/host/linux-common/etc_host_info.c#L66)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> Part b is interpreted as a 24-bit value that defines the rightmost three bytes of the binary address.

The current code doesn't seem to match this? Ditto below.
</blockquote></details>

Ugh you are right.
Nice catch.
Which code is better the committed one or this one:
```
    int j;
    uint32_t bits = 0xFFFFFFFF;
    for (j = 0; j < i; j++) {
        if (addr[j] > 0xFF)
            return false;
        result |= addr[j] << (24 - j * 8); 
        bits >>= 8;
    }   
    if (addr[i] > bits)
        return false;
    result |= addr[i];

```
This is a raw idea, I haven't tested the code above (I have tested the committed code).
___
*[`pal/src/host/linux-common/etc_host_info.c` line 106 at r1](https://reviewable.io/reviews/gramineproject/gramine/889#-NBMsTzI0UJRxyzeKDxP:-NBSQDB8EtZkbdDsR_dw:b2snu1p) ([raw file](https://github.com/gramineproject/gramine/blob/de0734e7b190ebbfdee8b7980841db442cb62787/pal/src/host/linux-common/etc_host_info.c#L106)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> Yes, the i might become negative here.

How is this safe? So we can legitimately have `i = -1`, and then below we have `addr[i] = part;`. What prevents your logic from having a buffer overflow?
</blockquote></details>

We continue, so we do i++ and we back to 0.
___
*[`pal/src/host/linux-common/etc_host_info.c` line 130 at r1](https://reviewable.io/reviews/gramineproject/gramine/889#-NBMtb63CvhS6uWyx1WN:-NBSQJ9J5GELes2zbJ8t:b-u40816) ([raw file](https://github.com/gramineproject/gramine/blob/de0734e7b190ebbfdee8b7980841db442cb62787/pal/src/host/linux-common/etc_host_info.c#L130)):*
<de [...]

2022-09-08 15:30 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/889)* status: 12 of 19 files reviewed, 50 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "squash! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @oshogbo)

___
*[`pal/src/host/linux-common/etc_host_info.c` line 296 at r1](https://reviewable.io/reviews/gramineproject/gramine/889#-NBMi_uY65siouejBVgJ:-NBSgAkw-WxtpWXnG44R:bv1c45i) ([raw file](https://github.com/gramineproject/gramine/blob/de0734e7b190ebbfdee8b7980841db442cb62787/pal/src/host/linux-common/etc_host_info.c#L296)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> they can be thrown away by PAL later

What do you mean? Why would it throw them out?
</blockquote></details>

So if I understand correctly, @dimakuv his idea is to thrown an error if the /etc/resolv.conf on the host is empty or that we didn't parse any variable data.

First, I don't think that's a problem - some machines might not have a resolv.conf, and etc emulation might get other useful files (when we will support more of them).
Second, I don't think that's a proper place to do it. For example, we can parse only search keywords, and here we think that we have meaningful data. Later the Pal/SGX-Linux will sanitize it, and decides that domain in search keyword isn't really a domain - this is what I mean by "throw them out".
And we again might end up with empty `/etc/resolv.conf`. So probably best place would be `libos/src/fs/etc/fs.c` .

But what if this is actually a valid configuration that `/etc/resolv.conf` is empty?


<!-- Sent from Reviewable.io -->

2022-09-08 15:44 UTC, boryspoplawski requested changes
> Reviewed 6 of 19 files at r1, 10 of 13 files at r3, 1 of 7 files at r4.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/889)* status: 13 of 19 files reviewed, 69 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "squash! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/889#-NBMNI_W3G6xQTKtC2ux:-NBRzTPvBT-0rCo6oRIw:b72mc9e) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

OK. I'm fine with this.

I think we'll need to create follow-up PRs with the following additional keywords immediately:
- `options edns0` -- propagate into Gramine
- `options trust-ad` -- ignore with some clear log message
- `ndots:n` -- propagate into Gramine
- `use-vc` -- propagate into Gramine
</blockquote></details>

@dimakuv why the last two files? They were not mentioned before.
Also FWIW this is the list I've found on all servers I had access to (the sum of all seen options):
- `search`,
- `domain`,
- `nameserver`,
- `options ends0 trust-ad`

___
___
*[`-- commits` line 2 at r3](https://reviewable.io/reviews/gramineproject/gramine/889#-NBO_aTSAvmQ-pzQYu4x):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd drop "Docs", it's implied by the change itself - i.e. when we add a feature to e.g. LibOS then we don't say that we modified LibOS and Docs, just LibOS ;) (and use "Docs" only for documentation-only commits)
</blockquote></details>

+1, for some reason many people started doing this lately, I wonder why
___
*[`Documentation/manifest-syntax.rst` line 156 at r3](https://reviewable.io/reviews/gramineproject/gramine/889#-NBOcmcA5zOJgcZFQ3gQ:-NBS1kZ29FFTfQj52eXg:b-n8d17i) ([raw file](https://github.com/gramineproject/gramine/blob/7b26e658f93d0952a53742adf1c1c33f24862d53/Documentation/manifest-syntax.rst#L156)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This is valid only assuming Linux PALs, on other PALs it will work differently (query a different OS API to gather this info).
</blockquote></details>

+1, I have the same stipulation
IMO this should document the manifest syntax + what users get through it, i.e. what is exposed by LibOS to the user app.
___
*[`Documentation/manifest-syntax.rst` line 160 at r3](https://reviewable.io/reviews/gramineproject/gramine/889#-NBS4cQt7R2B1a14-Pg5:-NBS4cQt7R2B1a14-Pg6:b-o7v5y) ([raw file](https://github.com/gramineproject/gramine/blob/7b26e658f93d0952a53742adf1c1c33f24862d53/Documentation/manifest-syntax.rst#L160)):*
> ```reStructuredText
> modes (such as SGX), Gramine additionally sanitizes the contents of these files.
> 
> Note that Gramine's parsers for these files support only a subset of
> ```

It's not the parsers, it's whole Gramine. Also some potential PALs might not have any parsers at all.
___
*[`libos/src/fs/etc/fs.c` line 21 at r1](https://reviewable.io/reviews/gramineproject/gramine/889#-NBMQM_w13kkIUSQt_Jq:-NBS7X3N8t6F9DHc21ym:b32v57) ([raw file](https://github.com/gramineproject/gramine/blob/de0734e7b190ebbfdee8b7980841db442cb62787/libos/src/fs/etc/fs.c#L21)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I agree with @mkow, I would feel safer with an `if` check.
</blockquote></details>

+1
___
*[`libos/src/fs/etc/fs.c` line 100 at r1](https://reviewable.io/reviews/gramineproject/gramine/889#-NBMVAy3DZH3tT5Rh2JL:-NBSFs8KBfCv5n_W9h0i:bpbexf7) ([raw file](https://github.com/gramineproject/gramine/blob/de0734e7b190ebbfdee8b7980841db442cb62787/libos/src/fs/etc/fs.c#L100)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

`<` since `data` must be null terminated
___
*[`libos/src/fs/etc/fs.c` line 16 at r3](https://reviewable.io/reviews/gramineproject/gramine/889#-NBS7FY_AyQMbwjLuLMa:-NBS7FY_AyQMbwjLuLMb:bke02dz) ([raw file](https://github.com/gramineproject/gramine/blob/7b26e658f93d0952a53742adf1c1c33f24862d53/libos/src/fs/etc/fs.c#L16)):*
> ```C
> 
> #define OPTION_INET6    "options inet6\n"
> #define OPTION_ROTATE   "options rotate\n"
> ```

What's with these weird indents?
___
*[`libos/src/fs/etc/fs.c` line 16 at r3](https://reviewable.io/reviews/gramineproject/gramine/889#-NBSAgKq1GtcKk3JX745:-NBSAgKq1GtcKk3JX746:bhegpvw) ([raw file](https://github.com/gramineproject/gramine/blob/7b26e658f93d0952a53742adf1c1c33f24862d53/libos/src/fs/etc/fs.c#L16)):*
> ```C
> 
> #define OPTION_INET6    "options inet6\n"
> #define OPTION_ROTATE   "options rotate\n"
> ```

Do we want to keep these newlines here? Looks weird to me... Also other entries add `\n` manually
___
*[`libos/src/fs/etc/fs.c` line 39 at r3](https://reviewable.io/reviews/gramineproject/gramine/889#-NBS8p8B2XBwvHUCkSkR:-NBS8p8B2XBwvHUCkSkS:b-nmudgp) ([raw file](https://github.com/gramineproject/gramine/blob/7b26e658f93d0952a53742adf1c1c33f24862d53/libos/src/fs/etc/fs.c#L39)):*
> ```C
>     /* Estimate the size of buffer: */
>     /* nameservers - lets assume all entries will be IPv6 plus a new line */
>     size += g_pal_public_state->dns_host.nsaddr_list_count * (strlen("nameserver ") + 40 + 1);
> ```

Please change `40` to some define, like `MAX_IPV6_ADDR_LEN` or something.
___
*[`libos/src/fs/etc/fs.c` line 39 at r3](https://reviewable.io/reviews/gramineproject/gramine/889#-NBS8uIa30Ll70Bh17to:-NBS8uIa30Ll70Bh17tp:bop1ghk) ([raw file](https://github.com/gramineproject/gramine/blob/7b26e658f93d0952a53742adf1c1c33f24862d53/libos/src/fs/etc/fs.c#L39)):*
> ```C
>     /* Estimate the size of buffer: */
>     /* nameservers - lets assume all entries will be IPv6 plus a new line */
>     size += g_pal_public_state->dns_host.nsaddr_list_count * (strlen("nameserver ") + 40 + 1);
> ```

Could you remove the space from the string and just `+1`? 
Maybe that would be cleaner only for me, so not blocking
___
*[`libos/src/fs/etc/fs.c` line 41 at r3](https://reviewable.io/reviews/gramineproject/gramine/889#-NBSA2NY5l768P-DoYIP:-NBSA2NY5l768P-DoYIQ:bafdo3s) ([raw file](https://github.com/gramineproject/gramine/blob/7b26e658f93d0952a53742adf1c1c33f24862d53/libos/src/fs/etc/fs.c#L41)):*
> ```C
>     size += g_pal_public_state->dns_host.nsaddr_list_count * (strlen("nameserver ") + 40 + 1);
>     /* search - lets assume maximum length of entries, plus a new line and white spaces */
>     size += strlen("search") + 1;
> ```

Let's move this `+1` to separate line at the end of this section, so it's clear what it accounts for (a new line, which is after all `dnsrch` entries). Also IMO it would be good to match the order of accounting to the order we print these chars.
___
*[`libos/src/fs/etc/fs.c` line 55 at r3](https://reviewable.io/reviews/gramineproject/gramine/889#-NBSB-vV3Yx6dwOxuYfr:-NBSB-vXC7oHOObiH631:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/7b26e658f93d0952a53742adf1c1c33f24862d53/libos/src/fs/etc/fs.c#L55)):*
> ```C
>     /* Generate data: */
>     char* ptr = data;
>     int ret = 0;
> ```





_Suggestion:_
```C
int ret;
```
___
*[`libos/src/fs/etc/fs.c` line 116 at r3](https://reviewable.io/reviews/gramineproject/gramine/889#-NBOl4Ou7PClVLd83xlp:-NBS6N1fAKBidsIRu4oQ:bn20c4m) ([raw file](https://github.com/gramineproject/gramine/blob/7b26e658f93d0952a53742adf1c1c33f24862d53/libos/src/fs/etc/fs.c#L116)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

(this is an object name, not a function name)
</blockquote></details>

I think this is just internal name / key to use for `provide_etc_resolv_conf` function, i.g. it's not an object.
___
*[`pal/include/pal/pal.h` line 104 at r3](https://reviewable.io/reviews/gramineproject/gramine/889#-NBSI8T8Da2wJ-606ClF:-NBSI8T8Da2wJ-606ClG:undefin [...]

2022-09-09 00:42 UTC, boryspoplawski requested changes
> Reviewed 6 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/889)* status: all files reviewed, 92 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "squash! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @oshogbo)

___
*[`-- commits` line 21 at r4](https://reviewable.io/reviews/gramineproject/gramine/889#-NBTMuNc0a-4Y3mHHlWL):*
This is wrong.
___
*[`-- commits` line 31 at r4](https://reviewable.io/reviews/gramineproject/gramine/889#-NBTN4jZ2uPnvVnOCcxJ):*
2x sign-off
___
*[`pal/include/pal/pal.h` line 112 at r3](https://reviewable.io/reviews/gramineproject/gramine/889#-NBTOdY6-7qkpgldGsg0:-NBTOdY6-7qkpgldGsg1:bb3ptdb) ([raw file](https://github.com/gramineproject/gramine/blob/7b26e658f93d0952a53742adf1c1c33f24862d53/pal/include/pal/pal.h#L112)):*
> ```objc
>     size_t                        nsaddr_list_count;
> 
>     char   dnsrch[PAL_MAXDNSRCH][PAL_HOSTNAME_MAX];
> ```

If you don't indent, then do it everywhere :)
___
*[`pal/src/host/linux-common/etc_host_info.c` line 201 at r2](https://reviewable.io/reviews/gramineproject/gramine/889#-NBMzlG-6CbOilvzwM9j:-NBUcbXi0S2ZshQbEOUY:bve041h) ([raw file](https://github.com/gramineproject/gramine/blob/bf3afd8741cdb79c6b83e5372f3a1feceec8e81f/pal/src/host/linux-common/etc_host_info.c#L201)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ok, true.
</blockquote></details>

`%.1337s` should work
___
*[`pal/src/host/linux-common/etc_host_info.c` line 7 at r3](https://reviewable.io/reviews/gramineproject/gramine/889#-NBRg5lcEaGNqC4hwP6_:-NBTZpZA7wI4kDOZ4nQt:b-a3j1pg) ([raw file](https://github.com/gramineproject/gramine/blob/7b26e658f93d0952a53742adf1c1c33f24862d53/pal/src/host/linux-common/etc_host_info.c#L7)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Currently it is network, but I think there will be more then network.
</blockquote></details>

Why do you think so?
___
*[`pal/src/host/linux-common/etc_host_info.c` line 88 at r3](https://reviewable.io/reviews/gramineproject/gramine/889#-NBRlI2ABSruVe35YRz7:-NBUBTDC6gll6oe6Kx1k:b-8nyi3w) ([raw file](https://github.com/gramineproject/gramine/blob/7b26e658f93d0952a53742adf1c1c33f24862d53/pal/src/host/linux-common/etc_host_info.c#L88)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done
___
*[`pal/src/host/linux-common/etc_host_info.c` line 239 at r3](https://reviewable.io/reviews/gramineproject/gramine/889#-NBRo7pF3m3IpQWDq3wM:-NBUdBE_5I3hBjH0khE7:bz6fhqt) ([raw file](https://github.com/gramineproject/gramine/blob/7b26e658f93d0952a53742adf1c1c33f24862d53/pal/src/host/linux-common/etc_host_info.c#L239)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

We ignore unknown options, in this case we will print an error to unknown option.
</blockquote></details>

And that's bad because? Cannot we log unknown options?
___
*[`pal/src/host/linux-common/etc_host_info.c` line 38 at r4](https://reviewable.io/reviews/gramineproject/gramine/889#-NBU9YgZDhXtiG9EJNjX:-NBU9YgZDhXtiG9EJNjY:b-hfe0o6) ([raw file](https://github.com/gramineproject/gramine/blob/183e5cc8c4132f2b50775340df4afee6a4fb9e10/pal/src/host/linux-common/etc_host_info.c#L38)):*
> ```C
> 
> static bool parse_ip_addr_ipv4(const char** pptr, uint32_t* out_addr) {
>     long long octet;
> ```

Please move to usage
___
*[`pal/src/host/linux-common/etc_host_info.c` line 62 at r4](https://reviewable.io/reviews/gramineproject/gramine/889#-NBUA4xn8BzumlWQvgJh:-NBUA4xn8BzumlWQvgJi:be7jzd3) ([raw file](https://github.com/gramineproject/gramine/blob/183e5cc8c4132f2b50775340df4afee6a4fb9e10/pal/src/host/linux-common/etc_host_info.c#L62)):*
> ```C
>     if (!is_end_of_word(*next))
>         return false;
> ```

Please add `assert(i < 4);`
___
*[`pal/src/host/linux-common/etc_host_info.c` line 65 at r4](https://reviewable.io/reviews/gramineproject/gramine/889#-NBUAFCjEoUIs5bxlWst:-NBUAFCjEoUIs5bxlWsu:b-37wcl6) ([raw file](https://github.com/gramineproject/gramine/blob/183e5cc8c4132f2b50775340df4afee6a4fb9e10/pal/src/host/linux-common/etc_host_info.c#L65)):*
> ```C
>     uint32_t result = 0;
>     if (i == 0) {
>         /* Address A has to be converted to: A.A.A.A
> ```

What, this comment makes no sense. `8` is not converted to `8.8.8.8`.
Ditto for all other comments.
___
*[`pal/src/host/linux-common/etc_host_info.c` line 101 at r4](https://reviewable.io/reviews/gramineproject/gramine/889#-NBUIBaj6T9_eU5C_Mu_:-NBUIBaj6T9_eU5C_Mua:bb4tf) ([raw file](https://github.com/gramineproject/gramine/blob/183e5cc8c4132f2b50775340df4afee6a4fb9e10/pal/src/host/linux-common/etc_host_info.c#L101)):*
> ```C
>  *  - Abbreviations `::1`, `ff::1:2`
>  */
> static bool parse_ip_addr_ipv6(const char** pptr, uint16_t* out_addr) {
> ```

I don't think this function is correct. Things like:
- `1::\r\r\r+1`
- `1::0x12`
- `1::1:`

will be parsed.
Also I have a very hard time following this function, it's a bit convoluted.

I've tried to come up with something, but it turns out not to be so trivial, so I won't spend more time on this. Here is my attempt with some test cases: https://gist.github.com/boryspoplawski/644b8b6eded440ac259163dca0df0ec9 but as you can see it still fails some cases.
feel free to steal it, if you find it useful
___
*[`pal/src/host/linux-common/etc_host_info.c` line 102 at r4](https://reviewable.io/reviews/gramineproject/gramine/889#-NBUBhTq-_76dppX1xZE:-NBUBhTq-_76dppX1xZF:b-hfe0o6) ([raw file](https://github.com/gramineproject/gramine/blob/183e5cc8c4132f2b50775340df4afee6a4fb9e10/pal/src/host/linux-common/etc_host_info.c#L102)):*
> ```C
>  */
> static bool parse_ip_addr_ipv6(const char** pptr, uint16_t* out_addr) {
>     long part;
> ```

Please move to usage
___
*[`pal/src/host/linux-common/etc_host_info.c` line 188 at r4](https://reviewable.io/reviews/gramineproject/gramine/889#-NBU_eBq7dGd9o9xMqM_:-NBU_eBr2rnDBD30LCme:bf44555) ([raw file](https://github.com/gramineproject/gramine/blob/183e5cc8c4132f2b50775340df4afee6a4fb9e10/pal/src/host/linux-common/etc_host_info.c#L188)):*
> ```C
>     }
> 
>     /* If we haven't found ':' nor '.' it means it is IPv4 address. */
> ```

I think this should be before previous `while` loop.
___
*[`pal/src/host/linux-common/etc_host_info.c` line 280 at r4](https://reviewable.io/reviews/gramineproject/gramine/889#-NBUdcb66LQQgNgbPfe5:-NBUdcb66LQQgNgbPfe6:b-ggk9jg) ([raw file](https://github.com/gramineproject/gramine/blob/183e5cc8c4132f2b50775340df4afee6a4fb9e10/pal/src/host/linux-common/etc_host_info.c#L280)):*
> ```C
>     { "search",     resolv_search },
>     { "options",    resolv_options },
>     { NULL, 0 },
> ```

What's the point of this entry? You can loop until `i < ARRAY_LEN(resolv_keys)`.
___
*[`pal/src/host/linux-common/etc_host_info.c` line 287 at r4](https://reviewable.io/reviews/gramineproject/gramine/889#-NBUevfmCEcafqv5OS7s:-NBUevfmCEcafqv5OS7t:b-z7u0c5) ([raw file](https://github.com/gramineproject/gramine/blob/183e5cc8c4132f2b50775340df4afee6a4fb9e10/pal/src/host/linux-common/etc_host_info.c#L287)):*
> ```C
>     const char* startline = buf;
> 
>     while (*ptr != 0x00) {
> ```

This loop is weird. Literally every case ends with `continue` and most of them go to the end of line. Maybe just parse it line by line instead?
___
*[`pal/src/host/linux-common/etc_host_info.c` line 298 at r4](https://reviewable.io/reviews/gramineproject/gramine/889#-NBUe_e7AKABzzBxV_q_:-NBUe_e7AKABzzBxV_qa:b1anzki) ([raw file](https://github.com/gramineproject/gramine/blob/183e5cc8c4132f2b50775340df4afee6a4fb9e10/pal/src/host/linux-common/etc_host_info.c#L298)):*
> ```C
>         } else if ((ptr != startline) && (*ptr == ' ' || *ptr == '\t')) {
>             for (size_t i = 0 [...]

2022-09-09 08:07 UTC, dimakuv requested changes
> Reviewed 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/889)* status: all files reviewed, 86 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "squash! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/889#-NBMNI_W3G6xQTKtC2ux:-NBW6d5T3WIY4RE16rtM:b-6pvsma) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

@dimakuv why the last two files? They were not mentioned before.
Also FWIW this is the list I've found on all servers I had access to (the sum of all seen options):
- `search`,
- `domain`,
- `nameserver`,
- `options ends0 trust-ad`
</blockquote></details>

I just looked at all options that are possible in `resolv.conf`, and these two options sounded easy to implement and potentially useful. But I agree -- I also haven't seen these options in real-world files.

___
___
*[`Documentation/manifest-syntax.rst` line 175 at r4](https://reviewable.io/reviews/gramineproject/gramine/889#-NBW7QgM-QFbp1UZTAhq:-NBW7QgN3_gqOC5oUkfy:b-qnjqlp) ([raw file](https://github.com/gramineproject/gramine/blob/183e5cc8c4132f2b50775340df4afee6a4fb9e10/Documentation/manifest-syntax.rst#L175)):*
> ```reStructuredText
> the information gathered from the host.
> 
> Note that Gramine's parsers for the hosts information support only a subset
> ```

`the hosts information` -> `the host's information`
___
*[`pal/src/host/linux-common/etc_host_info.c` line 66 at r1](https://reviewable.io/reviews/gramineproject/gramine/889#-NBMpiovAKjITZoPn283:-NBW96hy78QuQ2jr0yeb:b4ncgse) ([raw file](https://github.com/gramineproject/gramine/blob/de0734e7b190ebbfdee8b7980841db442cb62787/pal/src/host/linux-common/etc_host_info.c#L66)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Yup, this code doesn't handle cases like `8.1024` == `8.0.4.0`.
</blockquote></details>

Wow. I didn't know things like `8.1024` are possible for IPv4. Whoever came up with these rules was evil.
___
*[`pal/src/host/linux-common/etc_host_info.c` line 106 at r1](https://reviewable.io/reviews/gramineproject/gramine/889#-NBMsTzI0UJRxyzeKDxP:-NBWFtiO5WuaOoDZeLoK:bxf5fhm) ([raw file](https://github.com/gramineproject/gramine/blob/de0734e7b190ebbfdee8b7980841db442cb62787/pal/src/host/linux-common/etc_host_info.c#L106)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

We continue, so we do i++ and we back to 0.
</blockquote></details>

Oof. I see. This code is scary, maybe Borys's suggestion would be better?
___
*[`pal/src/host/linux-common/etc_host_info.c` line 130 at r1](https://reviewable.io/reviews/gramineproject/gramine/889#-NBMtb63CvhS6uWyx1WN:-NBWG19s3pyEEhGmlrjL:bi4eiht) ([raw file](https://github.com/gramineproject/gramine/blob/de0734e7b190ebbfdee8b7980841db442cb62787/pal/src/host/linux-common/etc_host_info.c#L130)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Yes, that true, but i would prefer to lave this just in case.
</blockquote></details>

Why not add an assert then? That's what asserts are for.
___
*[`pal/src/host/linux-common/etc_host_info.c` line 296 at r1](https://reviewable.io/reviews/gramineproject/gramine/889#-NBMi_uY65siouejBVgJ:-NBWGclJ5A0b9_s8iKS7:b3zei32) ([raw file](https://github.com/gramineproject/gramine/blob/de0734e7b190ebbfdee8b7980841db442cb62787/pal/src/host/linux-common/etc_host_info.c#L296)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

So if I understand correctly, @dimakuv his idea is to thrown an error if the /etc/resolv.conf on the host is empty or that we didn't parse any variable data.

First, I don't think that's a problem - some machines might not have a resolv.conf, and etc emulation might get other useful files (when we will support more of them).
Second, I don't think that's a proper place to do it. For example, we can parse only search keywords, and here we think that we have meaningful data. Later the Pal/SGX-Linux will sanitize it, and decides that domain in search keyword isn't really a domain - this is what I mean by "throw them out".
And we again might end up with empty `/etc/resolv.conf`. So probably best place would be `libos/src/fs/etc/fs.c` .

But what if this is actually a valid configuration that `/etc/resolv.conf` is empty?
</blockquote></details>

I agree with Mariuzsh. I'm unblocking.
___
*[`pal/src/host/linux-common/etc_host_info.c` line 37 at r3](https://reviewable.io/reviews/gramineproject/gramine/889#-NBRgIO60VOb7j8U3Gab:-NBW8SzE5UE45Pxwe_Xd:bmzg90k) ([raw file](https://github.com/gramineproject/gramine/blob/7b26e658f93d0952a53742adf1c1c33f24862d53/pal/src/host/linux-common/etc_host_info.c#L37)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

@mkow Is this what we want to do? I thought that we use `out_` prefix only when we allocate an object inside the function. In other words, we add `out_` when we want to indicate that this object should be later deleted via `free()` or `put_...()`.

But in this function, we simply update the value pointed to by `paddr`...
___
*[`pal/src/host/linux-common/etc_host_info.c` line 190 at r3](https://reviewable.io/reviews/gramineproject/gramine/889#-NBRYHvA70od06yKMf8p:-NBWG7jkBrVqzVR-SNxR:b-5fyki5) ([raw file](https://github.com/gramineproject/gramine/blob/7b26e658f93d0952a53742adf1c1c33f24862d53/pal/src/host/linux-common/etc_host_info.c#L190)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

With the new name this is longer then 100 lines, not sure how I should split it.
</blockquote></details>

Yes, that's exactly the problem. Maybe a shorter name: `parse_values_one_line`?
___
*[`pal/src/host/linux-common/etc_host_info.c` line 65 at r4](https://reviewable.io/reviews/gramineproject/gramine/889#-NBUAFCjEoUIs5bxlWst:-NBW9Tnw9M2bVdAOwPfW:b-3mm2kl) ([raw file](https://github.com/gramineproject/gramine/blob/183e5cc8c4132f2b50775340df4afee6a4fb9e10/pal/src/host/linux-common/etc_host_info.c#L65)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

What, this comment makes no sense. `8` is not converted to `8.8.8.8`.
Ditto for all other comments.
</blockquote></details>

+1. I guess it should be smth like `A[31:24].A[23:16].A[15:8].A[7:0]`. Same for other places.
___
*[`pal/src/host/linux-common/etc_host_info.c` line 66 at r4](https://reviewable.io/reviews/gramineproject/gramine/889#-NBW9YsZ4mc_QUQOAuJt:-NBW9YsZ4mc_QUQOAuJu:bu55yns) ([raw file](https://github.com/gramineproject/gramine/blob/183e5cc8c4132f2b50775340df4afee6a4fb9e10/pal/src/host/linux-common/etc_host_info.c#L66)):*
> ```C
>     if (i == 0) {
>         /* Address A has to be converted to: A.A.A.A
>          * The value a is interpreted as a 32-bit. */
> ```

`a` -> `A`.
___
*[`pal/src/host/linux-common/etc_host_info.c` line 87 at r4](https://reviewable.io/reviews/gramineproject/gramine/889#-NBWAWxnDTknsePeE2Lc:-NBWAWxnDTknsePeE2Ld:b4tfjpp) ([raw file](https://github.com/gramineproject/gramine/blob/183e5cc8c4132f2b50775340df4afee6a4fb9e10/pal/src/host/linux-common/etc_host_info.c#L87)):*
> ```C
>                 return false;
>             result = result << 8 | addr[i];
>         }
> ```

Personal preference, but I would remove the for loop and just have explicit checks on each of the 4 numbers and an explicit `result = addr[0] << 24 | ...`.

One argument for my formatting is that this code snippet won't rely on `result = 0` (which I had to go scroll up and verify).
___
*[`pal/src/host/linux-sgx/pal_main.c` line 320 at r3](https://reviewable.io/reviews/gra [...]

2022-09-11 00:00 UTC, mkow requested changes
> Reviewed 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/889)* status: all files reviewed, 63 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "squash! " found in commit messages' one-liners (waiting on @boryspoplawski and @oshogbo)

___
*[`Documentation/manifest-syntax.rst` line 168 at r4](https://reviewable.io/reviews/gramineproject/gramine/889#-NBdgqRC6d8FpYiZAJ_0:-NBdgqRC6d8FpYiZAJ_1:b-xuilfz) ([raw file](https://github.com/gramineproject/gramine/blob/183e5cc8c4132f2b50775340df4afee6a4fb9e10/Documentation/manifest-syntax.rst#L168)):*
> taking the host's configuration via different APIs

different than what? I guess you meant "various"?
___
*[`libos/src/fs/etc/fs.c` line 39 at r3](https://reviewable.io/reviews/gramineproject/gramine/889#-NBS8uIa30Ll70Bh17to:-NBdhW5y1oT2Lek72qYd:be1jhnv) ([raw file](https://github.com/gramineproject/gramine/blob/7b26e658f93d0952a53742adf1c1c33f24862d53/libos/src/fs/etc/fs.c#L39)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Could you remove the space from the string and just `+1`? 
Maybe that would be cleaner only for me, so not blocking
</blockquote></details>

I prefer it inside the string ;)
___
*[`libos/src/fs/etc/fs.c` line 116 at r3](https://reviewable.io/reviews/gramineproject/gramine/889#-NBOl4Ou7PClVLd83xlp:-NBdhsQNAibIt_Q8o7Ie:b-vyprev) ([raw file](https://github.com/gramineproject/gramine/blob/7b26e658f93d0952a53742adf1c1c33f24862d53/libos/src/fs/etc/fs.c#L116)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I think this is just internal name / key to use for `provide_etc_resolv_conf` function, i.g. it's not an object.
</blockquote></details>

It's something like "filesystem id".
___
*[`pal/include/pal/pal.h` line 110 at r3](https://reviewable.io/reviews/gramineproject/gramine/889#-NBSHEYe7DaU9SVGlZMa:-NBdi7xKDsmnuM-qtSlK:b8xturi) ([raw file](https://github.com/gramineproject/gramine/blob/7b26e658f93d0952a53742adf1c1c33f24862d53/pal/include/pal/pal.h#L110)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I prefer `length` over `count` when talking about lists/arrays (because `count` of what, maybe `_items_counts`...)
As other reviewers didn't mention it I'm not blocking, maybe just personal preference.
</blockquote></details>

I prefer count. What's from with `_items_counts` interpretation? It's the count of items in the array?
___
*[`pal/include/pal/pal.h` line 39 at r4](https://reviewable.io/reviews/gramineproject/gramine/889#-NBdiM1h0jiH8IAlITV0:-NBdiM1h0jiH8IAlITV1:bcod4b1) ([raw file](https://github.com/gramineproject/gramine/blob/183e5cc8c4132f2b50775340df4afee6a4fb9e10/pal/include/pal/pal.h#L39)):*
> ```objc
> /* DNS limits, used in resolv.conf emulation */
> #define PAL_MAX_NAMESPACES 3
> #define PAL_MAX_DN_SEARCH  6
> ```

Or maybe that "DN" means something else?



_Suggestion:_
```objc
PAL_MAX_DNS_SEARCH
```
___
*[`pal/src/host/linux-common/etc_host_info.c` line 66 at r1](https://reviewable.io/reviews/gramineproject/gramine/889#-NBMpiovAKjITZoPn283:-NBdkP3PBjqE0A67BzzW:b-o86jik) ([raw file](https://github.com/gramineproject/gramine/blob/de0734e7b190ebbfdee8b7980841db442cb62787/pal/src/host/linux-common/etc_host_info.c#L66)):*
> Which code is better the committed one or this one:

I think I prefer the committed version.
___
*[`pal/src/host/linux-common/etc_host_info.c` line 296 at r1](https://reviewable.io/reviews/gramineproject/gramine/889#-NBMi_uY65siouejBVgJ:-NBdmDmi--s02t_rnMZz:bcotte) ([raw file](https://github.com/gramineproject/gramine/blob/de0734e7b190ebbfdee8b7980841db442cb62787/pal/src/host/linux-common/etc_host_info.c#L296)):*
> thrown an error if the /etc/resolv.conf on the host is empty or that we didn't parse any variable data.

But why merging both cases? Why empty config would be an error?

When we want to fail is after we found some option we recognize, but failed at parsing it.

> and decides that domain in search keyword isn't really a domain - this is what I mean by "throw them out".

We should fail then, not silently skip it.
___
*[`pal/src/host/linux-common/etc_host_info.c` line 27 at r3](https://reviewable.io/reviews/gramineproject/gramine/889#-NBS_BGxEaYReR6ivgPu:-NBdiiCnEYpc4jGQSp_4:bp3ixea) ([raw file](https://github.com/gramineproject/gramine/blob/7b26e658f93d0952a53742adf1c1c33f24862d53/pal/src/host/linux-common/etc_host_info.c#L27)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I didn't review the usages yet, but looking at other code around, shouldnt we also check for nullbyte?
</blockquote></details>

What do you mean? The current version will stop on a null byte, which seems correct and intended.
___
*[`pal/src/host/linux-common/etc_host_info.c` line 37 at r3](https://reviewable.io/reviews/gramineproject/gramine/889#-NBRgIO60VOb7j8U3Gab:-NBdivcP1b1iXWOx2s05:bj0kjja) ([raw file](https://github.com/gramineproject/gramine/blob/7b26e658f93d0952a53742adf1c1c33f24862d53/pal/src/host/linux-common/etc_host_info.c#L37)):*
> I thought that we use out_ prefix only when we allocate an object inside the function.

Ugh, no? `out_` is supposed to mean what its name says, _a return value returned via an argument_ (aka output argument).
___
*[`pal/src/host/linux-common/etc_host_info.c` line 239 at r3](https://reviewable.io/reviews/gramineproject/gramine/889#-NBRo7pF3m3IpQWDq3wM:-NBdl6Cs2XYFGKnBD09k:byfwzf3) ([raw file](https://github.com/gramineproject/gramine/blob/7b26e658f93d0952a53742adf1c1c33f24862d53/pal/src/host/linux-common/etc_host_info.c#L239)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

And that's bad because? Cannot we log unknown options?
</blockquote></details>

But this is not the case for unknown options, but for too long options (which shouldn't appear in normal usage except in cases where the user edited this config file and added some garbage? so, we want to fail loudly).
___
*[`pal/src/host/linux-common/etc_host_info.c` line 65 at r4](https://reviewable.io/reviews/gramineproject/gramine/889#-NBdjT_34ZIQZpogt9YQ:-NBdjT_34ZIQZpogt9YR:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/183e5cc8c4132f2b50775340df4afee6a4fb9e10/pal/src/host/linux-common/etc_host_info.c#L65)):*
> ```C
>     uint32_t result = 0;
>     if (i == 0) {
>         /* Address A has to be converted to: A.A.A.A
> ```





_Suggestion:_
```C
Address A has to be converted to A.A.A.A
```
___
*[`pal/src/host/linux-common/etc_host_info.c` line 69 at r4](https://reviewable.io/reviews/gramineproject/gramine/889#-NBdjsMM5vzEGTsm1rjb:-NBdjsMM5vzEGTsm1rjc:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/183e5cc8c4132f2b50775340df4afee6a4fb9e10/pal/src/host/linux-common/etc_host_info.c#L69)):*
> ```C
>         result = addr[0];
>     } else if (i == 1) {
>         /* Address A.B has to be converted to: A.B.B.B
> ```





_Suggestion:_
```C
Address A.B has to be converted to A.B.B.B
```
___
*[`pal/src/host/linux-common/etc_host_info.c` line 76 at r4](https://reviewable.io/reviews/gramineproject/gramine/889#-NBdjuUW4tnpAH8v0p-1:-NBdjuUW4tnpAH8v0p-2:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/183e5cc8c4132f2b50775340df4afee6a4fb9e10/pal/src/host/linux-common/etc_host_info.c#L76)):*
> ```C
>         result = addr[0] << 24 | addr[1];
>     } else if (i == 2) {
>         /* Address A.B.C has to be converted to: A.B.C.C
> ```





_Suggestion:_
```C
Address A.B.C has to be converted to A.B.C.C
```
___
*[`pal/src/host/linux-sgx/enclave_ecalls.c` line 102 at r3](https://reviewable.io/reviews/gramineproject/gramine/889#-NBRuhk-1tmgP25agGob:-NBdnHXQ2Ovaxzxg52Q0:bz1eiab) ([raw file](https://github.com/g [...]

2022-09-11 13:04 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/889)* status: all files reviewed, 62 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "squash! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @oshogbo)

___
*[`libos/src/fs/etc/fs.c` line 116 at r3](https://reviewable.io/reviews/gramineproject/gramine/889#-NBOl4Ou7PClVLd83xlp:-NBgZg1q9S1lnJF1X2m0:b-fe9rld) ([raw file](https://github.com/gramineproject/gramine/blob/7b26e658f93d0952a53742adf1c1c33f24862d53/libos/src/fs/etc/fs.c#L116)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

It's something like "filesystem id".
</blockquote></details>

Or rather "callback function id"?
___
*[`pal/include/pal/pal.h` line 110 at r3](https://reviewable.io/reviews/gramineproject/gramine/889#-NBSHEYe7DaU9SVGlZMa:-NBgZoK-137gEBmdFMG-:b-k9rq78) ([raw file](https://github.com/gramineproject/gramine/blob/7b26e658f93d0952a53742adf1c1c33f24862d53/pal/include/pal/pal.h#L110)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I prefer count. What's from with `_items_counts` interpretation? It's the count of items in the array?
</blockquote></details>

That was supposed to be `_items_count`.
`count` generally reads weirdly to me (for lists, it would make sense for e.g. a set), e.g. I've never seen a `count()` method on list/array/vector in any language, also I've never seen anybody talking about `list count`/`array count`, it's always length.
___
*[`pal/src/host/linux-common/etc_host_info.c` line 27 at r3](https://reviewable.io/reviews/gramineproject/gramine/889#-NBS_BGxEaYReR6ivgPu:-NBg_wDrABSI8iLQXdrn:bdcw6xx) ([raw file](https://github.com/gramineproject/gramine/blob/7b26e658f93d0952a53742adf1c1c33f24862d53/pal/src/host/linux-common/etc_host_info.c#L27)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What do you mean? The current version will stop on a null byte, which seems correct and intended.
</blockquote></details>

Idk, brain lag.
___
*[`pal/src/host/linux-common/etc_host_info.c` line 37 at r3](https://reviewable.io/reviews/gramineproject/gramine/889#-NBRgIO60VOb7j8U3Gab:-NBgaK5REOCCe2X3LwOS:b-t9kqk5) ([raw file](https://github.com/gramineproject/gramine/blob/7b26e658f93d0952a53742adf1c1c33f24862d53/pal/src/host/linux-common/etc_host_info.c#L37)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> I thought that we use out_ prefix only when we allocate an object inside the function.

Ugh, no? `out_` is supposed to mean what its name says, _a return value returned via an argument_ (aka output argument).
</blockquote></details>

@dimakuv is right in the sense that we only added `out_` prefix to double-starred arguments, not to output buffers, i.e. when we allocate object inside the function and return it via out-argument, now where we just fill the buffer provided by the caller.
I remember even a (short) discussion about it and managed to find it: https://reviewable.io/reviews/gramineproject/gramine/462#-MzS9EtL831ww-T6HbYg
___
*[`pal/src/host/linux-sgx/host_main.c` line 632 at r1](https://reviewable.io/reviews/gramineproject/gramine/889#-NBMjlnd3_85Vgth5FRW:-NBgd8Wc-jeMRoLAdo1v:bgvgnke) ([raw file](https://github.com/gramineproject/gramine/blob/de0734e7b190ebbfdee8b7980841db442cb62787/pal/src/host/linux-sgx/host_main.c#L632)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> we add `out_` prefix for those objects that are _created_ inside the function (like strings)

Waait, where did you get that rule from? See another discussion.
</blockquote></details>

ditto (it's not really that it wasn't created, but we do not use `out_` for output buffers we merely fill)


<!-- Sent from Reviewable.io -->

2022-09-11 15:37 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/889)* status: all files reviewed, 62 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "squash! " found in commit messages' one-liners (waiting on @boryspoplawski and @oshogbo)

___
*[`pal/include/pal/pal.h` line 110 at r3](https://reviewable.io/reviews/gramineproject/gramine/889#-NBSHEYe7DaU9SVGlZMa:-NBh8_s7Cx1rV-x-WvwF:bfdv7kz) ([raw file](https://github.com/gramineproject/gramine/blob/7b26e658f93d0952a53742adf1c1c33f24862d53/pal/include/pal/pal.h#L110)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

That was supposed to be `_items_count`.
`count` generally reads weirdly to me (for lists, it would make sense for e.g. a set), e.g. I've never seen a `count()` method on list/array/vector in any language, also I've never seen anybody talking about `list count`/`array count`, it's always length.
</blockquote></details>

Dunno, for me `count` seems more natural, but length is also acceptable, just not "size", which in C/C++ is ambiguous.
___
*[`pal/src/host/linux-common/etc_host_info.c` line 37 at r3](https://reviewable.io/reviews/gramineproject/gramine/889#-NBRgIO60VOb7j8U3Gab:-NBh9tF_2_meoH6bayb3:b-nnarv7) ([raw file](https://github.com/gramineproject/gramine/blob/7b26e658f93d0952a53742adf1c1c33f24862d53/pal/src/host/linux-common/etc_host_info.c#L37)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

@dimakuv is right in the sense that we only added `out_` prefix to double-starred arguments, not to output buffers, i.e. when we allocate object inside the function and return it via out-argument, now where we just fill the buffer provided by the caller.
I remember even a (short) discussion about it and managed to find it: https://reviewable.io/reviews/gramineproject/gramine/462#-MzS9EtL831ww-T6HbYg
</blockquote></details>

@boryspoplawski: I think you're confusing different cases. Quoting the thread you linked: "AFAIK, by convention we didn't label output buffers as out_, but mostly parameters that are double-star pointers.". This was about cases when an argument is a pointer to an array, not just a single variable passed by a pointer.

See e.g.:
- https://github.com/gramineproject/gramine/blob/5b160c68260eaa57a9342762b33dbff1e3c8fb5a/common/include/api.h#L218-L219
- https://github.com/gramineproject/gramine/blob/5b160c68260eaa57a9342762b33dbff1e3c8fb5a/common/include/api.h#L397
- https://github.com/gramineproject/gramine/blob/5b160c68260eaa57a9342762b33dbff1e3c8fb5a/common/src/asan.c#L107-L108
- https://github.com/gramineproject/gramine/blob/5b160c68260eaa57a9342762b33dbff1e3c8fb5a/common/src/path.c#L56

and many more examples, all from the code we recently wrote.


<!-- Sent from Reviewable.io -->

2022-09-11 17:43 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/889)* status: all files reviewed, 62 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "squash! " found in commit messages' one-liners (waiting on @boryspoplawski and @oshogbo)

___
*[`pal/src/host/linux-common/etc_host_info.c` line 37 at r3](https://reviewable.io/reviews/gramineproject/gramine/889#-NBRgIO60VOb7j8U3Gab:-NBhcBDN7PAqK6fAsNbu:bic1fc1) ([raw file](https://github.com/gramineproject/gramine/blob/7b26e658f93d0952a53742adf1c1c33f24862d53/pal/src/host/linux-common/etc_host_info.c#L37)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

@boryspoplawski: I think you're confusing different cases. Quoting the thread you linked: "AFAIK, by convention we didn't label output buffers as out_, but mostly parameters that are double-star pointers.". This was about cases when an argument is a pointer to an array, not just a single variable passed by a pointer.

See e.g.:
- https://github.com/gramineproject/gramine/blob/5b160c68260eaa57a9342762b33dbff1e3c8fb5a/common/include/api.h#L218-L219
- https://github.com/gramineproject/gramine/blob/5b160c68260eaa57a9342762b33dbff1e3c8fb5a/common/include/api.h#L397
- https://github.com/gramineproject/gramine/blob/5b160c68260eaa57a9342762b33dbff1e3c8fb5a/common/src/asan.c#L107-L108
- https://github.com/gramineproject/gramine/blob/5b160c68260eaa57a9342762b33dbff1e3c8fb5a/common/src/path.c#L56

and many more examples, all from the code we recently wrote.
</blockquote></details>

Sorry, I thought we were talking about `parse_ip_addr_ipv6`, where we have `uin16_t* out_addr` as an output buffer, my bad, sorry for confusion.

But the argument stands there - ipv6 has `out_` prefix for buffer output, we can move the discussion to there, or finalize it here. Note that this is most likely different case, from what @dimakuv raised issues about (and I mistakenly mixed them together).


<!-- Sent from Reviewable.io -->

2022-09-11 23:39 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/889)* status: all files reviewed, 62 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "squash! " found in commit messages' one-liners (waiting on @boryspoplawski and @oshogbo)

___
*[`pal/src/host/linux-common/etc_host_info.c` line 37 at r3](https://reviewable.io/reviews/gramineproject/gramine/889#-NBRgIO60VOb7j8U3Gab:-NBiuQpSC9oSq5gUKb_y:brli6vh) ([raw file](https://github.com/gramineproject/gramine/blob/7b26e658f93d0952a53742adf1c1c33f24862d53/pal/src/host/linux-common/etc_host_info.c#L37)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Sorry, I thought we were talking about `parse_ip_addr_ipv6`, where we have `uin16_t* out_addr` as an output buffer, my bad, sorry for confusion.

But the argument stands there - ipv6 has `out_` prefix for buffer output, we can move the discussion to there, or finalize it here. Note that this is most likely different case, from what @dimakuv raised issues about (and I mistakenly mixed them together).
</blockquote></details>

Yes, for IPv6 it's a different case, but there I'd still keep the `out_` prefix to be more similar to IPv4 function signature (and it's not _wrong_ to use it there, it's just that we don't add `out_` for brevity where it's obvious from types/signature - i.e. output buffers).


<!-- Sent from Reviewable.io -->

2022-09-12 07:46 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/889)* status: all files reviewed, 62 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "squash! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @oshogbo)

___
*[`libos/src/fs/etc/fs.c` line 39 at r3](https://reviewable.io/reviews/gramineproject/gramine/889#-NBS8uIa30Ll70Bh17to:-NBkbxRB-c7lnTSmcXvn:b-hc9nvl) ([raw file](https://github.com/gramineproject/gramine/blob/7b26e658f93d0952a53742adf1c1c33f24862d53/libos/src/fs/etc/fs.c#L39)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I prefer it inside the string ;)
</blockquote></details>

If we need a tiebreaker, then I also prefer it inside the string (so, as it is currently)
___
*[`libos/src/fs/etc/fs.c` line 116 at r3](https://reviewable.io/reviews/gramineproject/gramine/889#-NBOl4Ou7PClVLd83xlp:-NBkc6tzDOizeY6kCMbj:b-gv31is) ([raw file](https://github.com/gramineproject/gramine/blob/7b26e658f93d0952a53742adf1c1c33f24862d53/libos/src/fs/etc/fs.c#L116)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Or rather "callback function id"?
</blockquote></details>

Yeah, more like "callback function id".
___
*[`pal/src/host/linux-common/etc_host_info.c` line 37 at r3](https://reviewable.io/reviews/gramineproject/gramine/889#-NBRgIO60VOb7j8U3Gab:-NBkdBDZE5JgbvBrKxP8:b-qda3ti) ([raw file](https://github.com/gramineproject/gramine/blob/7b26e658f93d0952a53742adf1c1c33f24862d53/pal/src/host/linux-common/etc_host_info.c#L37)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Yes, for IPv6 it's a different case, but there I'd still keep the `out_` prefix to be more similar to IPv4 function signature (and it's not _wrong_ to use it there, it's just that we don't add `out_` for brevity where it's obvious from types/signature - i.e. output buffers).
</blockquote></details>

Ok, thanks for clarification. I will follow these rules from now on.
___
*[`pal/src/host/linux-sgx/host_main.c` line 632 at r1](https://reviewable.io/reviews/gramineproject/gramine/889#-NBMjlnd3_85Vgth5FRW:-NBkdsWG5BQXWKRvqk2x:b-gc52si) ([raw file](https://github.com/gramineproject/gramine/blob/de0734e7b190ebbfdee8b7980841db442cb62787/pal/src/host/linux-sgx/host_main.c#L632)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto (it's not really that it wasn't created, but we do not use `out_` for output buffers we merely fill)
</blockquote></details>

So looks like we *want* to have `emulated_etc` -> `out_emulated_etc` here :)

Meh, I still find it hard to understand when we use `out_` prefix and when we don't force it. Like in this case, it feels both natural (because it is indeed an out argument, i.e., it is modified by this func) and weird to add `out_` (because the type `bool*` already indicates that this will be modified) here. @mkow @boryspoplawski ?


<!-- Sent from Reviewable.io -->

2022-09-12 12:00 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/889)* status: all files reviewed, 62 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "squash! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @oshogbo)

___
*[`pal/src/host/linux-common/etc_host_info.c` line 37 at r3](https://reviewable.io/reviews/gramineproject/gramine/889#-NBRgIO60VOb7j8U3Gab:-NBlXBjT3kqb3FfygkFX:b-kmhnjy) ([raw file](https://github.com/gramineproject/gramine/blob/7b26e658f93d0952a53742adf1c1c33f24862d53/pal/src/host/linux-common/etc_host_info.c#L37)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ok, thanks for clarification. I will follow these rules from now on.
</blockquote></details>

The thing is the function signature is not the same, so making it look the same is misleading. Here we have a single value (`uint32_t`), there (in ipv6) we have a whole array (of constant len, so no additional parameter passed). Maybe we should juse use `uint16_t name[static N]` there?
___
*[`pal/src/host/linux-common/etc_host_info.c` line 87 at r4](https://reviewable.io/reviews/gramineproject/gramine/889#-NBWAWxnDTknsePeE2Lc:-NBlXe397Z_-oxmb2j77:b3456vc) ([raw file](https://github.com/gramineproject/gramine/blob/183e5cc8c4132f2b50775340df4afee6a4fb9e10/pal/src/host/linux-common/etc_host_info.c#L87)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Personal preference, but I would remove the for loop and just have explicit checks on each of the 4 numbers and an explicit `result = addr[0] << 24 | ...`.

One argument for my formatting is that this code snippet won't rely on `result = 0` (which I had to go scroll up and verify).
</blockquote></details>

I had similar thoughts, but the current version was also fine, so didn't comment. Now that I see others think alike, maybe it's better to change it?
___
*[`pal/src/host/linux-sgx/host_main.c` line 632 at r1](https://reviewable.io/reviews/gramineproject/gramine/889#-NBMjlnd3_85Vgth5FRW:-NBlYX1gAaEiXsJz13Oj:bv6dhr7) ([raw file](https://github.com/gramineproject/gramine/blob/de0734e7b190ebbfdee8b7980841db442cb62787/pal/src/host/linux-sgx/host_main.c#L632)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

So looks like we *want* to have `emulated_etc` -> `out_emulated_etc` here :)

Meh, I still find it hard to understand when we use `out_` prefix and when we don't force it. Like in this case, it feels both natural (because it is indeed an out argument, i.e., it is modified by this func) and weird to add `out_` (because the type `bool*` already indicates that this will be modified) here. @mkow @boryspoplawski ?
</blockquote></details>

I didn't like this prefix from the beginning and I don't know what were the exact rules you've set when merging such policy.
FWIW, the rules  I use are:
- `*out_name = X;` -> `out_name` **should** have `out_` prefix
- `memcpy(name, X, N);`/`name[i] = X;` -> **no** `out_` prefix

Note that in the first point it doesn't matter what type `X` is, i.e. whether it's a pointer to something allocated here or just a scalar value.


<!-- Sent from Reviewable.io -->

2022-09-12 13:36 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/889)* status: all files reviewed, 63 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "squash! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @oshogbo)

___
*[`pal/src/host/linux-common/etc_host_info.c` line 37 at r3](https://reviewable.io/reviews/gramineproject/gramine/889#-NBRgIO60VOb7j8U3Gab:-NBltuZzCAK9-OUNGlZk:b-ylu9fw) ([raw file](https://github.com/gramineproject/gramine/blob/7b26e658f93d0952a53742adf1c1c33f24862d53/pal/src/host/linux-common/etc_host_info.c#L37)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

The thing is the function signature is not the same, so making it look the same is misleading. Here we have a single value (`uint32_t`), there (in ipv6) we have a whole array (of constant len, so no additional parameter passed). Maybe we should juse use `uint16_t name[static N]` there?
</blockquote></details>

+1 to `[static N]` for IPv6
___
*[`pal/src/host/linux-common/etc_host_info.c` line 87 at r4](https://reviewable.io/reviews/gramineproject/gramine/889#-NBWAWxnDTknsePeE2Lc:-NBlu3Ix-UzY6TANWadz:b5pskf2) ([raw file](https://github.com/gramineproject/gramine/blob/183e5cc8c4132f2b50775340df4afee6a4fb9e10/pal/src/host/linux-common/etc_host_info.c#L87)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I had similar thoughts, but the current version was also fine, so didn't comment. Now that I see others think alike, maybe it's better to change it?
</blockquote></details>

I'm neutral on this.
___
*[`pal/src/host/linux-sgx/host_main.c` line 632 at r1](https://reviewable.io/reviews/gramineproject/gramine/889#-NBMjlnd3_85Vgth5FRW:-NBluCXa8VsoaRGbAXpI:b5s56mx) ([raw file](https://github.com/gramineproject/gramine/blob/de0734e7b190ebbfdee8b7980841db442cb62787/pal/src/host/linux-sgx/host_main.c#L632)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I didn't like this prefix from the beginning and I don't know what were the exact rules you've set when merging such policy.
FWIW, the rules  I use are:
- `*out_name = X;` -> `out_name` **should** have `out_` prefix
- `memcpy(name, X, N);`/`name[i] = X;` -> **no** `out_` prefix

Note that in the first point it doesn't matter what type `X` is, i.e. whether it's a pointer to something allocated here or just a scalar value.
</blockquote></details>

@dimakuv: As Borys said. But my general point for keeping this rule is that returning values via arguments is super obscure and we use it only because C is a terrible language. So, I want these places to be marked as visibly as possible.


<!-- Sent from Reviewable.io -->

2022-09-13 09:14 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/889)* status: all files reviewed, 63 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "squash! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @oshogbo)

___
*[`pal/src/host/linux-common/etc_host_info.c` line 87 at r4](https://reviewable.io/reviews/gramineproject/gramine/889#-NBWAWxnDTknsePeE2Lc:-NBq6YD0ARTKxbhHtRFW:bmjq0nb) ([raw file](https://github.com/gramineproject/gramine/blob/183e5cc8c4132f2b50775340df4afee6a4fb9e10/pal/src/host/linux-common/etc_host_info.c#L87)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'm neutral on this.
</blockquote></details>

Well, it's 2 for the change, 1 abstained. Let's change it then.
___
*[`pal/src/host/linux-sgx/host_main.c` line 632 at r1](https://reviewable.io/reviews/gramineproject/gramine/889#-NBMjlnd3_85Vgth5FRW:-NBq6vFK7pmGic0PE0Fm:b-5tmbak) ([raw file](https://github.com/gramineproject/gramine/blob/de0734e7b190ebbfdee8b7980841db442cb62787/pal/src/host/linux-sgx/host_main.c#L632)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

@dimakuv: As Borys said. But my general point for keeping this rule is that returning values via arguments is super obscure and we use it only because C is a terrible language. So, I want these places to be marked as visibly as possible.
</blockquote></details>

Got it. So in this particular case, please replace`emulate_etc` -> `out_emulate_etc`.


<!-- Sent from Reviewable.io -->

2022-09-13 09:16 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/889)* status: all files reviewed, 63 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "squash! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[`-- commits` line 2 at r3](https://reviewable.io/reviews/gramineproject/gramine/889#-NBO_aTSAvmQ-pzQYu4x):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

+1, for some reason many people started doing this lately, I wonder why
</blockquote></details>

Done.
___
*[`-- commits` line 21 at r4](https://reviewable.io/reviews/gramineproject/gramine/889#-NBTMuNc0a-4Y3mHHlWL):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This is wrong.
</blockquote></details>

Hym, I can't fix without force push, so lets this comment just hang here.
___
*[`-- commits` line 31 at r4](https://reviewable.io/reviews/gramineproject/gramine/889#-NBTN4jZ2uPnvVnOCcxJ):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

2x sign-off
</blockquote></details>

ditto.
___
*[`Documentation/manifest-syntax.rst` line 160 at r3](https://reviewable.io/reviews/gramineproject/gramine/889#-NBS4cQt7R2B1a14-Pg5:-NBmTCyw7AJ5kZHOsyYB:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/7b26e658f93d0952a53742adf1c1c33f24862d53/Documentation/manifest-syntax.rst#L160)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

It's not the parsers, it's whole Gramine. Also some potential PALs might not have any parsers at all.
</blockquote></details>

Done.
___
*[`Documentation/manifest-syntax.rst` line 168 at r4](https://reviewable.io/reviews/gramineproject/gramine/889#-NBdgqRC6d8FpYiZAJ_0:-NBmSzbKBAekmqQvb5vs:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/183e5cc8c4132f2b50775340df4afee6a4fb9e10/Documentation/manifest-syntax.rst#L168)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> taking the host's configuration via different APIs

different than what? I guess you meant "various"?
</blockquote></details>

Done.
___
*[`Documentation/manifest-syntax.rst` line 175 at r4](https://reviewable.io/reviews/gramineproject/gramine/889#-NBW7QgM-QFbp1UZTAhq:-NBmT4df8nih2xFkHzn0:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/183e5cc8c4132f2b50775340df4afee6a4fb9e10/Documentation/manifest-syntax.rst#L175)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`the hosts information` -> `the host's information`
</blockquote></details>

Done.
___
*[`libos/src/fs/etc/fs.c` line 21 at r1](https://reviewable.io/reviews/gramineproject/gramine/889#-NBMQM_w13kkIUSQt_Jq:-NBVt7xuA0fjcQ4Sm4Gl:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/de0734e7b190ebbfdee8b7980841db442cb62787/libos/src/fs/etc/fs.c#L21)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.
___
*[`libos/src/fs/etc/fs.c` line 100 at r1](https://reviewable.io/reviews/gramineproject/gramine/889#-NBMVAy3DZH3tT5Rh2JL:-NBmTmX81QUaFBLh5fDm:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/de0734e7b190ebbfdee8b7980841db442cb62787/libos/src/fs/etc/fs.c#L100)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`<` since `data` must be null terminated
</blockquote></details>

Done.
___
*[`libos/src/fs/etc/fs.c` line 16 at r3](https://reviewable.io/reviews/gramineproject/gramine/889#-NBS7FY_AyQMbwjLuLMa:-NBmTJOSEHvzF76He8al:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/7b26e658f93d0952a53742adf1c1c33f24862d53/libos/src/fs/etc/fs.c#L16)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

What's with these weird indents?
</blockquote></details>

Done.
___
*[`libos/src/fs/etc/fs.c` line 16 at r3](https://reviewable.io/reviews/gramineproject/gramine/889#-NBSAgKq1GtcKk3JX745:-NBVsvQkDWlrsHa016Ma:b-1ihbih) ([raw file](https://github.com/gramineproject/gramine/blob/7b26e658f93d0952a53742adf1c1c33f24862d53/libos/src/fs/etc/fs.c#L16)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Do we want to keep these newlines here? Looks weird to me... Also other entries add `\n` manually
</blockquote></details>

I think so, it doesn't make sense to add them explicite in all places (in `strlen` and then when we `memcpy`).
___
*[`libos/src/fs/etc/fs.c` line 39 at r3](https://reviewable.io/reviews/gramineproject/gramine/889#-NBS8p8B2XBwvHUCkSkR:-NBmTOx5D1kUXqGTYSOm:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/7b26e658f93d0952a53742adf1c1c33f24862d53/libos/src/fs/etc/fs.c#L39)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please change `40` to some define, like `MAX_IPV6_ADDR_LEN` or something.
</blockquote></details>

Done.
___
*[`libos/src/fs/etc/fs.c` line 41 at r3](https://reviewable.io/reviews/gramineproject/gramine/889#-NBSA2NY5l768P-DoYIP:-NBmTUzp8SN-vzKjHmUB:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/7b26e658f93d0952a53742adf1c1c33f24862d53/libos/src/fs/etc/fs.c#L41)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Let's move this `+1` to separate line at the end of this section, so it's clear what it accounts for (a new line, which is after all `dnsrch` entries). Also IMO it would be good to match the order of accounting to the order we print these chars.
</blockquote></details>

Done.
___
*[`libos/src/fs/etc/fs.c` line 55 at r3](https://reviewable.io/reviews/gramineproject/gramine/889#-NBSB-vV3Yx6dwOxuYfr:-NBmTiuJ71xd0eBoZbFJ:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/7b26e658f93d0952a53742adf1c1c33f24862d53/libos/src/fs/etc/fs.c#L55)):*
> ```C
>     /* Generate data: */
>     char* ptr = data;
>     int ret = 0;
> ```

Done.
___
*[`pal/include/pal/pal.h` line 104 at r3](https://reviewable.io/reviews/gramineproject/gramine/889#-NBSI8T8Da2wJ-606ClF:-NBmUEI6-wq3IxPoZ8_w:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/7b26e658f93d0952a53742adf1c1c33f24862d53/pal/include/pal/pal.h#L104)):*
> ```objc
>     bool     is_ipv6;
>     uint32_t ipv4;
>     uint16_t ipv6[8];
> ```

Done.
___
*[`pal/include/pal/pal.h` line 112 at r3](https://reviewable.io/reviews/gramineproject/gramine/889#-NBSHbqN6RqpqrF51fxJ:-NBmUIRu3nwsCHmpjnEa:b3l8722) ([raw file](https://github.com/gramineproject/gramine/blob/7b26e658f93d0952a53742adf1c1c33f24862d53/pal/include/pal/pal.h#L112)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Could we have some meaningful name? I broke my tongue on `dnsrch`. Like `dns_search` isn't even that long...
</blockquote></details>

Yea sure, I took this name from libresolv.
___
*[`pal/include/pal/pal.h` line 112 at r3](https://reviewable.io/reviews/gramineproject/gramine/889#-NBTOdY6-7qkpgldGsg0:-NBmV33u0N1qr-Cl0WZ1:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/7b26e658f93d0952a53742adf1c1c33f24862d53/pal/include/pal/pal.h#L112)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

If you don't indent, then do it everywhere :)
</blockquote></details>

Done.
___
*[`pal/include/pal/pal.h` line 39 at r4](https://reviewable.io/reviews/gramineproject/gramine/889#-NBdiM1h0jiH8IAlITV0:-NBmTqYw8jwEraim1XsS:bk8uij0) ([raw file](https://github.com/gramineproject/gramine/blob/183e5cc8c4132f2b50775340df4afee6a4fb9e10/pal/include/pal/pal.h#L39)):*
<details>< [...]

2022-09-13 11:58 UTC, mkow requested changes
> Reviewed 17 of 17 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/889)* status: all files reviewed, 67 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @oshogbo)

___
*[`pal/include/host/linux-common/etc_host_info_internal.h` line 9 at r5](https://reviewable.io/reviews/gramineproject/gramine/889#-NBqM0sT-UzwJ69yOkay:-NBqM0sT-UzwJ69yOkaz:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/f773b4ea7b33f7a0bad61c8b4f71d6a577ca8344/pal/include/host/linux-common/etc_host_info_internal.h#L9)):*
> ```objc
> 
> bool parse_ip_addr_ipv4(const char** pptr, uint32_t* out_addr);
> bool parse_ip_addr_ipv6(const char** pptr, uint16_t out_addr[8]);
> ```





_Suggestion:_
```objc
uint16_t out_addr[static 8]
```
___
*[`pal/include/pal/pal.h` line 39 at r4](https://reviewable.io/reviews/gramineproject/gramine/889#-NBdiM1h0jiH8IAlITV0:-NBqMi4X7qr3Jw-ReKzR:bk0ezuj) ([raw file](https://github.com/gramineproject/gramine/blob/183e5cc8c4132f2b50775340df4afee6a4fb9e10/pal/include/pal/pal.h#L39)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

DN stands for "Domain name" (this is for a `search` keyword).
</blockquote></details>

Ah, makes sense.
___
*[`pal/include/pal/pal.h` line 104 at r5](https://reviewable.io/reviews/gramineproject/gramine/889#-NBqYc6p2Xe9djN6fNDn:-NBqYc6q7wjCLBVM-IHu:bbdrbb) ([raw file](https://github.com/gramineproject/gramine/blob/f773b4ea7b33f7a0bad61c8b4f71d6a577ca8344/pal/include/pal/pal.h#L104)):*
> ```objc
> 
> struct pal_dns_host_conf_addr {
>     bool     is_ipv6;
> ```

Please fix alignment
___
*[`pal/regression/ipv4_parser.c` line 13 at r5](https://reviewable.io/reviews/gramineproject/gramine/889#-NBqNCw7APPeeO1UvTbe:-NBqNCw7APPeeO1UvTbf:b-i2btyy) ([raw file](https://github.com/gramineproject/gramine/blob/f773b4ea7b33f7a0bad61c8b4f71d6a577ca8344/pal/regression/ipv4_parser.c#L13)):*
> ```C
> #define TEST(x) \
>     if (x < 0)  \
>     return 1
> ```

I'd also move this macro to inside `main()`, it's only used there and it has a `return` inside, so better to have it next to where it's used.



_Suggestion:_
```C
    if (x < 0)  \
        return 1
```
___
*[`pal/regression/ipv4_parser.c` line 43 at r5](https://reviewable.io/reviews/gramineproject/gramine/889#-NBqONbA9Xwtg1-7lJjP:-NBqONbA9Xwtg1-7lJjQ:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/f773b4ea7b33f7a0bad61c8b4f71d6a577ca8344/pal/regression/ipv4_parser.c#L43)):*
> ```C
> 
>     if (parse_ip_addr_ipv4(&ptr, &addr)) {
>         pal_printf("We parsed %s successfully, but it is invalid IPv4 address\n", buf);
> ```





_Suggestion:_
```C
it's an invalid IPv4 address
```
___
*[`pal/regression/ipv6_parser.c` line 13 at r5](https://reviewable.io/reviews/gramineproject/gramine/889#-NBqOknS5Pidy7I7Yf8t:-NBqOknS5Pidy7I7Yf8u:b-tl63l7) ([raw file](https://github.com/gramineproject/gramine/blob/f773b4ea7b33f7a0bad61c8b4f71d6a577ca8344/pal/regression/ipv6_parser.c#L13)):*
> ```C
> #define TEST(x) \
>     if (x < 0)  \
>     return 1
> ```

ditto x2
___
*[`pal/regression/ipv6_parser.c` line 20 at r5](https://reviewable.io/reviews/gramineproject/gramine/889#-NBqOqBh2gfssmFez07n:-NBqOqBh2gfssmFez07o:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/f773b4ea7b33f7a0bad61c8b4f71d6a577ca8344/pal/regression/ipv6_parser.c#L20)):*
> ```C
> void read_text_file_to_cstr(void) {}
> 
> static int ipv6_valid(const char* buf, uint16_t reference_addr[8]) {
> ```





_Suggestion:_
```C
uint16_t reference_addr[static 8]
```
___
*[`pal/regression/ipv6_parser.c` line 49 at r5](https://reviewable.io/reviews/gramineproject/gramine/889#-NBqQH0A9VzTyV-_abPU:-NBqQH0A9VzTyV-_abPV:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/f773b4ea7b33f7a0bad61c8b4f71d6a577ca8344/pal/regression/ipv6_parser.c#L49)):*
> ```C
> 
>     if (parse_ip_addr_ipv6(&ptr, addr)) {
>         pal_printf("We parsed %s successfully, but it is invalid IPv6 address\n", buf);
> ```

ditto
___
*[`pal/regression/ipv6_parser.c` line 72 at r5](https://reviewable.io/reviews/gramineproject/gramine/889#-NBqR-6vEKevvqddk0jn:-NBqR-6vEKevvqddk0jo:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/f773b4ea7b33f7a0bad61c8b4f71d6a577ca8344/pal/regression/ipv6_parser.c#L72)):*
> ```C
>         {"1337:1:2:3:4:5:6:7", {0x1337, 0x1, 0x2, 0x3, 0x4, 0x5, 0x6, 0x7}},
>         {"1337:1:2:3:4:5:6:7 sufix", {0x1337, 0x1, 0x2, 0x3, 0x4, 0x5, 0x6, 0x7}},
>         {":: sufix", {0, 0, 0, 0, 0, 0, 0, 0}},
> ```





_Suggestion:_
```C
suffix
```
___
*[`pal/regression/ipv6_parser.c` line 73 at r5](https://reviewable.io/reviews/gramineproject/gramine/889#-NBqR-y4-M7jOHHMphnV:-NBqR-y4-M7jOHHMphnW:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/f773b4ea7b33f7a0bad61c8b4f71d6a577ca8344/pal/regression/ipv6_parser.c#L73)):*
> ```C
>         {"1337:1:2:3:4:5:6:7 sufix", {0x1337, 0x1, 0x2, 0x3, 0x4, 0x5, 0x6, 0x7}},
>         {":: sufix", {0, 0, 0, 0, 0, 0, 0, 0}},
>         {"::1 sufix", {0, 0, 0, 0, 0, 0, 0, 1}},
> ```

ditto
___
*[`pal/src/host/linux-common/etc_host_info.c` line 296 at r1](https://reviewable.io/reviews/gramineproject/gramine/889#-NBMi_uY65siouejBVgJ:-NBqeZkv3AK8Rp1iRa97:bqkw8fd) ([raw file](https://github.com/gramineproject/gramine/blob/de0734e7b190ebbfdee8b7980841db442cb62787/pal/src/host/linux-common/etc_host_info.c#L296)):*
> In case of the invalid hostname we wanted just to set a localhost as a default, we we want to fail on something that potentially user don't have impact on?

Hmm, but such cases should be rather impossible in real world? (except for hosts which try to attack Gramine) So, I think it's not dangerous to loudly fail, and may actually allow users to notice mistakes easier.
___
*[`pal/src/host/linux-common/etc_host_info.c` line 239 at r3](https://reviewable.io/reviews/gramineproject/gramine/889#-NBRo7pF3m3IpQWDq3wM:-NBqUViQ0I7ZsyydhV1n:b-u3psjw) ([raw file](https://github.com/gramineproject/gramine/blob/7b26e658f93d0952a53742adf1c1c33f24862d53/pal/src/host/linux-common/etc_host_info.c#L239)):*
> Fail or report it?

I'd say both. This should never really happen, and worst case users have many possibilities to circumvent this (e.g. by hardcoding `resolv.conf` in trusted files).
___
*[`pal/src/host/linux-common/etc_host_info.c` line 46 at r5](https://reviewable.io/reviews/gramineproject/gramine/889#-NBqRuNf5QnRwSHkAnAW:-NBqRuNf5QnRwSHkAnAX:b-4h0kdp) ([raw file](https://github.com/gramineproject/gramine/blob/f773b4ea7b33f7a0bad61c8b4f71d6a577ca8344/pal/src/host/linux-common/etc_host_info.c#L46)):*
> ```C
>     for (i = 0; i < 4; i++) {
>         /* NOTE: Gramine strtoll/strtol skips white spaces that are before the number, and doesn't
>          *       treat this as an error, this behavior is different from glibc.
> ```

Could you create an issue about this?
___
*[`pal/src/host/linux-common/etc_host_info.c` line 297 at r5](https://reviewable.io/reviews/gramineproject/gramine/889#-NBqe0kTBHBvZfrQa6zu:-NBqe0kTBHBvZfrQa6zv:bdnxld3) ([raw file](https://github.com/gramineproject/gramine/blob/f773b4ea7b33f7a0bad61c8b4f71d6a577ca8344/pal/src/host/linux-common/etc_host_info.c#L297)):*
> ```C
>      * From resolv.conf(5):
>      * The keyword and value must appear on a single line, and the
>      * keyword (e.g., nameserver) must start the line.  The value
> ```

We rather don't use this convention.



_Suggestion:_
```C
line. The
```
___
*[`pal/src/host/linux-common/etc_host_info.c` line 306 at r5](https://reviewable.io/reviews/gramineproject/gramine/889#-NBqeK8l2go_a2Jm61vw:-NBqeK8l2go_a2Jm61vx:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/f773b4ea7b33f7a0bad61c8b4f71d6a577ca8344/pal/src/host/linux-common/etc_host_inf [...]

2022-09-13 12:42 UTC, dimakuv requested changes
> Reviewed 17 of 17 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/889)* status: all files reviewed, 75 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @oshogbo)

___
*[`Documentation/manifest-syntax.rst` line 175 at r5](https://reviewable.io/reviews/gramineproject/gramine/889#-NBqfwWZ77ebNWH9USgp:-NBqfwWZ77ebNWH9USgq:bja4ds1) ([raw file](https://github.com/gramineproject/gramine/blob/f773b4ea7b33f7a0bad61c8b4f71d6a577ca8344/Documentation/manifest-syntax.rst#L175)):*
> ```reStructuredText
> the information gathered from the host.
> 
> Note that Gramine support only a subset of the corresponding options.
> ```

`supports`
___
*[`pal/regression/ipv4_parser.c` line 13 at r5](https://reviewable.io/reviews/gramineproject/gramine/889#-NBqq0GE3fHHKOmYD2-C:-NBqq0GE3fHHKOmYD2-D:b-ba06yl) ([raw file](https://github.com/gramineproject/gramine/blob/f773b4ea7b33f7a0bad61c8b4f71d6a577ca8344/pal/regression/ipv4_parser.c#L13)):*
> ```C
> #define TEST(x) \
>     if (x < 0)  \
>     return 1
> ```

We could simply use `CHECK()` macro?
___
*[`pal/regression/ipv4_parser.c` line 22 at r5](https://reviewable.io/reviews/gramineproject/gramine/889#-NBqpaLMB1a4fMwMna3B:-NBqpaLMB1a4fMwMna3C:b-wnzuin) ([raw file](https://github.com/gramineproject/gramine/blob/f773b4ea7b33f7a0bad61c8b4f71d6a577ca8344/pal/regression/ipv4_parser.c#L22)):*
> ```C
> static int ipv4_valid(const char* buf, uint32_t reference_addr) {
>     const char* ptr = buf;
>     uint32_t ourparser_addr;
> ```

For uniformity with the below func, can we have this:
```
    uint32_t addr;
    const char* ptr = buf;
```

In other words, (1) swap the lines, and (2) rename to simply `addr` -- it is obvious from this function that this is the addr from our parser.
___
*[`pal/regression/ipv6_parser.c` line 13 at r5](https://reviewable.io/reviews/gramineproject/gramine/889#-NBqqRj08rzobH11Q5BI:-NBqqRj08rzobH11Q5BJ:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/f773b4ea7b33f7a0bad61c8b4f71d6a577ca8344/pal/regression/ipv6_parser.c#L13)):*
> ```C
> #define TEST(x) \
>     if (x < 0)  \
>     return 1
> ```

ditto
___
*[`pal/regression/ipv6_parser.c` line 22 at r5](https://reviewable.io/reviews/gramineproject/gramine/889#-NBqqW-ODZvn3ocNdlUQ:-NBqqW-ODZvn3ocNdlUR:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/f773b4ea7b33f7a0bad61c8b4f71d6a577ca8344/pal/regression/ipv6_parser.c#L22)):*
> ```C
> static int ipv6_valid(const char* buf, uint16_t reference_addr[8]) {
>     const char* ptr = buf;
>     uint16_t ourparser_addr[8];
> ```

ditto
___
*[`pal/regression/ipv6_parser.c` line 78 at r5](https://reviewable.io/reviews/gramineproject/gramine/889#-NBqqxCi0jd6PbcwvK3d:-NBqqxCi0jd6PbcwvK3e:btgelul) ([raw file](https://github.com/gramineproject/gramine/blob/f773b4ea7b33f7a0bad61c8b4f71d6a577ca8344/pal/regression/ipv6_parser.c#L78)):*
> ```C
>     for (size_t i = 0; i < ARRAY_SIZE(valid_test_cases); i++) {
>         if (ipv6_valid(valid_test_cases[i].str, valid_test_cases[i].addr) < 0)
>             return 1;
> ```

Why not use `TEST` (or as I suggest `CHECK`) here?
___
*[`pal/regression/ipv6_parser.c` line 102 at r5](https://reviewable.io/reviews/gramineproject/gramine/889#-NBqrCom-BIByClhYuDL:-NBqrCom-BIByClhYuDM:b-97q23k) ([raw file](https://github.com/gramineproject/gramine/blob/f773b4ea7b33f7a0bad61c8b4f71d6a577ca8344/pal/regression/ipv6_parser.c#L102)):*
> ```C
>     TEST(ipv6_invalid("1::\r\r1"));
>     TEST(ipv6_invalid("1:\n:1"));
>     TEST(ipv6_invalid("1::1\r\r:1"));
> ```

Please add cases with two (or more) double-colons.
___
*[`pal/src/host/linux-common/etc_host_info.c` line 296 at r1](https://reviewable.io/reviews/gramineproject/gramine/889#-NBMi_uY65siouejBVgJ:-NBqnvF7DqrpCSr6qWFp:bujm76m) ([raw file](https://github.com/gramineproject/gramine/blob/de0734e7b190ebbfdee8b7980841db442cb62787/pal/src/host/linux-common/etc_host_info.c#L296)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> In case of the invalid hostname we wanted just to set a localhost as a default, we we want to fail on something that potentially user don't have impact on?

Hmm, but such cases should be rather impossible in real world? (except for hosts which try to attack Gramine) So, I think it's not dangerous to loudly fail, and may actually allow users to notice mistakes easier.
</blockquote></details>

I'm neutral on this. @boryspoplawski ?
___
*[`pal/src/host/linux-common/etc_host_info.c` line 101 at r4](https://reviewable.io/reviews/gramineproject/gramine/889#-NBUIBaj6T9_eU5C_Mu_:-NBqlYa24LSJ2Sab6lh4:br12lmj) ([raw file](https://github.com/gramineproject/gramine/blob/183e5cc8c4132f2b50775340df4afee6a4fb9e10/pal/src/host/linux-common/etc_host_info.c#L101)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

I steal parts of it, thanks - Done.
</blockquote></details>

This new version is very readable, thanks!
___
*[`pal/src/host/linux-common/etc_host_info.c` line 49 at r5](https://reviewable.io/reviews/gramineproject/gramine/889#-NBqhtsn2wqLxh6zX0WY:-NBqhtsn2wqLxh6zX0WZ:b-7zudck) ([raw file](https://github.com/gramineproject/gramine/blob/f773b4ea7b33f7a0bad61c8b4f71d6a577ca8344/pal/src/host/linux-common/etc_host_info.c#L49)):*
> ```C
>          */
>         if (*ptr == ' ' || *ptr == '\t' || *ptr == '+')
>             return false;
> ```

Wouldn't it be better to use `isdigit()` instead?
___
*[`pal/src/host/linux-common/etc_host_info.c` line 126 at r5](https://reviewable.io/reviews/gramineproject/gramine/889#-NBqiQ110ZkdFm0KJr81:-NBqiQ110ZkdFm0KJr82:b-l8f2ta) ([raw file](https://github.com/gramineproject/gramine/blob/f773b4ea7b33f7a0bad61c8b4f71d6a577ca8344/pal/src/host/linux-common/etc_host_info.c#L126)):*
> ```C
>         }
>         /* strtol skips 0x prefix, this prefix is invalid in IPv6 */
>         if (next - ptr >= 2 && !isxdigit(ptr[1]))
> ```

Why not move the check for `x` symbol above, to the not-hex-digit check:
```
        /* note that strtol skips 0x prefix, this prefix is invalid in IPv6 */
        if (!isxdigit(ptr[0]) || !isxdigit(ptr[1])) {
            return false;
        }
```
___
*[`pal/src/host/linux-common/etc_host_info.c` line 129 at r5](https://reviewable.io/reviews/gramineproject/gramine/889#-NBqikF7CvUBCC_kai4-:-NBqikF7CvUBCC_kai40:b-2ixb8h) ([raw file](https://github.com/gramineproject/gramine/blob/f773b4ea7b33f7a0bad61c8b4f71d6a577ca8344/pal/src/host/linux-common/etc_host_info.c#L129)):*
> ```C
>             return false;
>         addr[parts_seen] = val;
>         parts_seen++;
> ```

In such cases, I prefer: `addr[parts_seen++] = val;`. Not blocking.
___
*[`pal/src/host/linux-common/etc_host_info.c` line 156 at r5](https://reviewable.io/reviews/gramineproject/gramine/889#-NBqkOgU6TmSfWCfDlN_:-NBqkOgU6TmSfWCfDlNa:b-3mf9du) ([raw file](https://github.com/gramineproject/gramine/blob/f773b4ea7b33f7a0bad61c8b4f71d6a577ca8344/pal/src/host/linux-common/etc_host_info.c#L156)):*
> ```C
>             return false;
>         /* `addr` already correct. */
>     } else { /* double_colon_pos != -1 */
> ```

The comment is useless here :)
___
*[`pal/src/host/linux-common/etc_host_info.c` line 308 at r5](https://reviewable.io/reviews/gramineproject/gramine/889#-NBqmiS2Cp1iGSqeApop:-NBqmiS2Cp1iGSqeApoq:b-duvasg) ([raw file](https://github.com/gramineproject/gramine/blob/f773b4ea7b33f7a0bad61c8b4f71d6a577ca8344/pal/src/host/linux-common/etc_host_info.c#L308)):*
> ```C
>                      * verify that this is ent of word. */
>                     if (!is_end_of_word(*ptr))
>                         break;
> ```

Why do we break here instead of `continue`? Currently this is correct, but what if we'll have smth like in the future:
```
resolv_keys [...]

2022-09-13 13:47 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/889)* status: all files reviewed, 75 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @oshogbo)

___
*[`pal/src/host/linux-common/etc_host_info.c` line 156 at r5](https://reviewable.io/reviews/gramineproject/gramine/889#-NBqkOgU6TmSfWCfDlN_:-NBr5OeQ8UajeKVh6vO3:b4uyvdy) ([raw file](https://github.com/gramineproject/gramine/blob/f773b4ea7b33f7a0bad61c8b4f71d6a577ca8344/pal/src/host/linux-common/etc_host_info.c#L156)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

The comment is useless here :)
</blockquote></details>

I get why he did this, but IMO it's helpful only on larger cases (e.g. multiple if-else-if-else-if-else), but even then I prefer an assert for this instead of a comment.


<!-- Sent from Reviewable.io -->

2022-09-13 14:16 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/889)* status: 18 of 27 files reviewed, 75 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[`pal/src/host/linux-common/etc_host_info.c` line 46 at r5](https://reviewable.io/reviews/gramineproject/gramine/889#-NBqRuNf5QnRwSHkAnAW:-NBrCOSX6L-Tv9iXm6ia:b-hwihzp) ([raw file](https://github.com/gramineproject/gramine/blob/f773b4ea7b33f7a0bad61c8b4f71d6a577ca8344/pal/src/host/linux-common/etc_host_info.c#L46)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you create an issue about this?
</blockquote></details>

https://github.com/gramineproject/gramine/issues/907


<!-- Sent from Reviewable.io -->

2022-09-13 14:22 UTC, mkow requested changes
> Reviewed 9 of 9 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/889)* status: all files reviewed, 62 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[`pal/src/host/linux-common/etc_host_info.c` line 239 at r3](https://reviewable.io/reviews/gramineproject/gramine/889#-NBRo7pF3m3IpQWDq3wM:-NBrDDvr7WtjJOnfdd0v:b-goensb) ([raw file](https://github.com/gramineproject/gramine/blob/7b26e658f93d0952a53742adf1c1c33f24862d53/pal/src/host/linux-common/etc_host_info.c#L239)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

The issue is that the system ignores everything that is invalid - so user might not even be aware of this.
Dunno I have mixed feelings in any way...
</blockquote></details>

Huh, interesting. @boryspoplawski, @dimakuv: What do you think?
___
*[`pal/src/host/linux-common/etc_host_info.c` line 46 at r5](https://reviewable.io/reviews/gramineproject/gramine/889#-NBqRuNf5QnRwSHkAnAW:-NBrD0IG6CzldEW-kqhV:b-ucfknh) ([raw file](https://github.com/gramineproject/gramine/blob/f773b4ea7b33f7a0bad61c8b4f71d6a577ca8344/pal/src/host/linux-common/etc_host_info.c#L46)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

https://github.com/gramineproject/gramine/issues/907
</blockquote></details>

Thanks!


<!-- Sent from Reviewable.io -->

2022-09-13 16:59 UTC, dimakuv approved these changes
> Reviewed 9 of 9 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/889)* status: all files reviewed, 48 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[`pal/src/host/linux-common/etc_host_info.c` line 239 at r3](https://reviewable.io/reviews/gramineproject/gramine/889#-NBRo7pF3m3IpQWDq3wM:-NBrlOSmAq0TKSUiuLD0:b-h8lk35) ([raw file](https://github.com/gramineproject/gramine/blob/7b26e658f93d0952a53742adf1c1c33f24862d53/pal/src/host/linux-common/etc_host_info.c#L239)):*
> The issue is that the system ignores everything that is invalid - so user might not even be aware of this.

@oshogbo What system? I can't parse this sentence.

@mkow If we're discussing log or fail or both, I'd go with only log. Why do we want to fail on unknown options? I would ignore this (with some log message).
___
*[`pal/src/host/linux-common/etc_host_info.c` line 126 at r5](https://reviewable.io/reviews/gramineproject/gramine/889#-NBqiQ110ZkdFm0KJr81:-NBrl5LI00akw19vBP0Y:bobldsp) ([raw file](https://github.com/gramineproject/gramine/blob/f773b4ea7b33f7a0bad61c8b4f71d6a577ca8344/pal/src/host/linux-common/etc_host_info.c#L126)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

What is the case of `1:2:3...`? The second char is not a digit in any case, but it's a valid address.
</blockquote></details>

Yeah, my bad, ignore me.
___
*[`pal/src/host/linux-common/etc_host_info.c` line 129 at r5](https://reviewable.io/reviews/gramineproject/gramine/889#-NBqikF7CvUBCC_kai4-:-NBrlC065-zRtsxjHFTe:b32w0x) ([raw file](https://github.com/gramineproject/gramine/blob/f773b4ea7b33f7a0bad61c8b4f71d6a577ca8344/pal/src/host/linux-common/etc_host_info.c#L129)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

I don't like these hidden increments, so if it's not blocking, let's not change that.
</blockquote></details>

OK
___
*[`pal/src/host/linux-common/etc_host_info.c` line 308 at r5](https://reviewable.io/reviews/gramineproject/gramine/889#-NBqmiS2Cp1iGSqeApop:-NBrlwoO04XfMDDkmXLS:bswtpxf) ([raw file](https://github.com/gramineproject/gramine/blob/f773b4ea7b33f7a0bad61c8b4f71d6a577ca8344/pal/src/host/linux-common/etc_host_info.c#L308)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Yep, I wonder about that for a moment, a decision there aren't any known options with the same suffix, so I decided that if found a prefix with known words it's something smelly.
</blockquote></details>

Well... Fair enough. I don't think the keywords for `resolv.conf` will ever change in such a weird way. Resolving.


<!-- Sent from Reviewable.io -->

2022-09-13 20:02 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/889)* status: all files reviewed, 48 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[`pal/src/host/linux-common/etc_host_info.c` line 239 at r3](https://reviewable.io/reviews/gramineproject/gramine/889#-NBRo7pF3m3IpQWDq3wM:-NBsQwarAZATe9k583vf:b-m2da0l) ([raw file](https://github.com/gramineproject/gramine/blob/7b26e658f93d0952a53742adf1c1c33f24862d53/pal/src/host/linux-common/etc_host_info.c#L239)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> The issue is that the system ignores everything that is invalid - so user might not even be aware of this.

@oshogbo What system? I can't parse this sentence.

@mkow If we're discussing log or fail or both, I'd go with only log. Why do we want to fail on unknown options? I would ignore this (with some log message).
</blockquote></details>

But I don't want to fail for unknown options, only for options which seem to be corrupted (like here, super long, or where parsing failed). I.e. if I for some weird reason accidentaly end up with `/etc/passwd` mounted at `/etc/resolv.conf` I want a parsing error, not a message that everything is great :)


<!-- Sent from Reviewable.io -->

2022-09-13 21:35 UTC, boryspoplawski requested changes
> Reviewed 8 of 17 files at r5, 9 of 9 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/889)* status: all files reviewed, 23 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @oshogbo)

___
*[`-- commits` line 21 at r4](https://reviewable.io/reviews/gramineproject/gramine/889#-NBTMuNc0a-4Y3mHHlWL):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Hym, I can't fix without force push, so lets this comment just hang here.
</blockquote></details>

I think if you do a force push, which will **only** change this oneliner, it should be fine.
___
*[`Documentation/manifest-syntax.rst` line 175 at r6](https://reviewable.io/reviews/gramineproject/gramine/889#-NBrC83I8YpuvmTn2BZ1:-NBrC83I8YpuvmTn2BZ2:b4uidxc) ([raw file](https://github.com/gramineproject/gramine/blob/bc76c04f57356399c004ea2cf2ac202bddc072f2/Documentation/manifest-syntax.rst#L175)):*
> ```reStructuredText
> the information gathered from the host.
> 
> Note that Gramine supports only a subset of the corresponding options.
> ```

After the recent changes `corresponding` refers to `NULL`.
___
*[`libos/src/fs/etc/fs.c` line 16 at r3](https://reviewable.io/reviews/gramineproject/gramine/889#-NBSAgKq1GtcKk3JX745:-NBrKKwT5WulnMnPPE9R:ba4jgm1) ([raw file](https://github.com/gramineproject/gramine/blob/7b26e658f93d0952a53742adf1c1c33f24862d53/libos/src/fs/etc/fs.c#L16)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

I think so, it doesn't make sense to add them explicite in all places (in `strlen` and then when we `memcpy`).
</blockquote></details>

But we do that for most things, just these two are special.
___
*[`libos/src/fs/etc/fs.c` line 40 at r6](https://reviewable.io/reviews/gramineproject/gramine/889#-NBrLPG87D2YPNTRWfkH:-NBrLPG87D2YPNTRWfkI:bkxno97) ([raw file](https://github.com/gramineproject/gramine/blob/bc76c04f57356399c004ea2cf2ac202bddc072f2/libos/src/fs/etc/fs.c#L40)):*
> ```C
>     /* Estimate the size of buffer: */
>     /* nameservers - let's assume all entries will be IPv6 plus a new line */
>     size += g_pal_public_state->dns_host.nsaddr_list_count *
> ```

Please move to the next line



_Code quote:_
```C
 *
```
___
*[`pal/include/host/linux-common/etc_host_info_internal.h` line 7 at r6](https://reviewable.io/reviews/gramineproject/gramine/889#-NBrPxH03txetZy5bhYH:-NBrPxH03txetZy5bhYI:bkc1en3) ([raw file](https://github.com/gramineproject/gramine/blob/bc76c04f57356399c004ea2cf2ac202bddc072f2/pal/include/host/linux-common/etc_host_info_internal.h#L7)):*
> ```objc
> 
> #pragma once
> ```

Please add a comment why we have this header (and these functions as extern).
___
*[`pal/regression/ipv4_parser.c` line 14 at r6](https://reviewable.io/reviews/gramineproject/gramine/889#-NBrSg117MxdRQL8oPLS:-NBrSg117MxdRQL8oPLT:b6g4x9u) ([raw file](https://github.com/gramineproject/gramine/blob/bc76c04f57356399c004ea2cf2ac202bddc072f2/pal/regression/ipv4_parser.c#L14)):*
> ```C
>  * etc_host_info.c which we don't use here. */
> void read_text_file_to_cstr(void);
> void read_text_file_to_cstr(void) {}
> ```

Ughh, the linking we have here is already hacky, but this is too much for my taste. This doesn't even match the original signature. The ideal (well, assuming we leave the linking) would be to make this linked file self contained (most likely split it into two, or something). Alternatively, make this signature correct (and the implementation dummy, but at least correct).
___
*[`pal/regression/ipv4_parser.c` line 21 at r6](https://reviewable.io/reviews/gramineproject/gramine/889#-NBsSy6f29Y0IALhGIms:-NBsSy6f29Y0IALhGImt:b-n176zk) ([raw file](https://github.com/gramineproject/gramine/blob/bc76c04f57356399c004ea2cf2ac202bddc072f2/pal/regression/ipv4_parser.c#L21)):*
> ```C
> 
>     if (!parse_ip_addr_ipv4(&ptr, &addr)) {
>         pal_printf("Unable to parse %s\n", buf);
> ```

ditto whole file



_Suggestion:_
```C
\"%s\"
```
___
*[`pal/regression/ipv4_parser.c` line 86 at r6](https://reviewable.io/reviews/gramineproject/gramine/889#-NBsU17K2tEDBCwBjyBY:-NBsU17K2tEDBCwBjyBZ:b-7clyw) ([raw file](https://github.com/gramineproject/gramine/blob/bc76c04f57356399c004ea2cf2ac202bddc072f2/pal/regression/ipv4_parser.c#L86)):*
> ```C
>     CHECK(ipv4_invalid("8.8.-8.8"));
>     CHECK(ipv4_invalid("0x8.8.8.8"));
>     CHECK(ipv4_invalid("8.8.0x8.8"));
> ```

Hmm, both `ping` and `firefox` are able to parse these two addresses. Maybe they are valid? I don't know exact rules...
Actually, quoting `man inet_aton`:
`(...) components of the dotted address can be specified in decimal, octal (with a leading 0), or hexadecimal, with a leading 0X).`
Do we want to be compatible or do we just do what we do now?
___
*[`pal/regression/ipv4_parser.c` line 90 at r6](https://reviewable.io/reviews/gramineproject/gramine/889#-NBsUOVS8ZmBTS1y3cCF:-NBsUOVS8ZmBTS1y3cCG:b-bqfts5) ([raw file](https://github.com/gramineproject/gramine/blob/bc76c04f57356399c004ea2cf2ac202bddc072f2/pal/regression/ipv4_parser.c#L90)):*
> ```C
>     CHECK(ipv4_invalid("8.b1.8.8"));
>     CHECK(ipv4_invalid("8.0b1.8.8"));
>     CHECK(ipv4_invalid("b1.8.8.8"));
> ```

Please add `8.8.8.017` and `8.8.8.018`. IDK what should happen for both, especially under current rules. Ping threats `017` as octal and `018` as invalid (because it's invalid ocatal). Update: see above.
___
*[`pal/regression/ipv6_parser.c` line 14 at r6](https://reviewable.io/reviews/gramineproject/gramine/889#-NBsUoaz82Wm75lToyqY:-NBsUoaz82Wm75lToyqZ:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/bc76c04f57356399c004ea2cf2ac202bddc072f2/pal/regression/ipv6_parser.c#L14)):*
> ```C
>  * etc_host_info.c which we don't use here. */
> void read_text_file_to_cstr(void);
> void read_text_file_to_cstr(void) {}
> ```

ditto
___
*[`pal/regression/ipv6_parser.c` line 21 at r6](https://reviewable.io/reviews/gramineproject/gramine/889#-NBsUvZh5AP4EvS5h2jD:-NBsUvZh5AP4EvS5h2jE:b-n176zk) ([raw file](https://github.com/gramineproject/gramine/blob/bc76c04f57356399c004ea2cf2ac202bddc072f2/pal/regression/ipv6_parser.c#L21)):*
> ```C
> 
>     if (!parse_ip_addr_ipv6(&ptr, addr)) {
>         pal_printf("Unable to parse %s\n", buf);
> ```

ditto whole file



_Suggestion:_
```C
 \"%s\"
```
___
*[`pal/regression/ipv6_parser.c` line 32 at r6](https://reviewable.io/reviews/gramineproject/gramine/889#-NBsV70H-Da1KU7FTZty:-NBsV70H-Da1KU7FTZtz:b-kt52c3) ([raw file](https://github.com/gramineproject/gramine/blob/bc76c04f57356399c004ea2cf2ac202bddc072f2/pal/regression/ipv6_parser.c#L32)):*
> ```C
>             buf, reference_addr[0], reference_addr[1], reference_addr[2], reference_addr[3],
>             reference_addr[4], reference_addr[5], reference_addr[6], reference_addr[7],
>             addr[0], addr[1], addr[2], addr[3], addr[4], addr[5], addr[6], addr[7]);
> ```

Do we need this complex print? I'm not blocking, but we know both the input and the expected value from the file source, so no need to print...
___
*[`pal/regression/ipv6_parser.c` line 64 at r6](https://reviewable.io/reviews/gramineproject/gramine/889#-NBsVYPe-LeUKIIIDqJT:-NBsVYPe-LeUKIIIDqJU:b-hqwomw) ([raw file](https://github.com/gramineproject/gramine/blob/bc76c04f57356399c004ea2cf2ac202bddc072f2/pal/regression/ipv6_parser.c#L64)):*
> ```C
>         {"1:2:3:4:5:6::1", {1, 2, 3, 4, 5, 6, 0, 1}},
>         {"::1", {0, 0, 0, 0, 0, 0, 0, 1}},
>         {"::", {0, 0, 0, 0, 0, 0, 0, 0}},
> ```

Please also add `1::`
___
*[`pal/src/host/linux-common/etc_host_info.c` line 296 at r1](https://reviewable.io/reviews/gramineproject/gramine/889#-NBMi_uY65siouejBVgJ:-NBsgypC3S05HD8ux7XX:b-s5b4y2) ([raw file](https://github.com/gramineproject/gramine/blob/de0734e7b190ebbfdee8b7980841db442cb62787 [...]

2022-09-14 00:12 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/889)* status: all files reviewed, 23 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @oshogbo)

___
*[`pal/regression/ipv4_parser.c` line 86 at r6](https://reviewable.io/reviews/gramineproject/gramine/889#-NBsU17K2tEDBCwBjyBY:-NBtHkENA-lxJoOSy8-S:btfjcnd) ([raw file](https://github.com/gramineproject/gramine/blob/bc76c04f57356399c004ea2cf2ac202bddc072f2/pal/regression/ipv4_parser.c#L86)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Hmm, both `ping` and `firefox` are able to parse these two addresses. Maybe they are valid? I don't know exact rules...
Actually, quoting `man inet_aton`:
`(...) components of the dotted address can be specified in decimal, octal (with a leading 0), or hexadecimal, with a leading 0X).`
Do we want to be compatible or do we just do what we do now?
</blockquote></details>

Wow, that's a decently cursed syntax.
___
*[`pal/src/host/linux-common/etc_host_info.c` line 296 at r1](https://reviewable.io/reviews/gramineproject/gramine/889#-NBMi_uY65siouejBVgJ:-NBtIWMpCEYHsUQa-FXQ:br01s09) ([raw file](https://github.com/gramineproject/gramine/blob/de0734e7b190ebbfdee8b7980841db442cb62787/pal/src/host/linux-common/etc_host_info.c#L296)):*
> we cannot fail on weird domains - Linux allows them; while it's not ideal we don't follow Linux, I think it's worthwhile precaution

@boryspoplawski: I think you got lost with negations here. `cannot` -> `can`?

> untrusted host can pass whatever it wants in the parsed struct

ofc this is not something for security, it's to detect accidental errors in your configs instead of silently ignoring them
___
*[`pal/src/host/linux-sgx/pal_main.c` line 348 at r4](https://reviewable.io/reviews/gramineproject/gramine/889#-NBTXL0P5OvbriHEZ4d_:-NBtJ1lyE2RZH3gfdRMM:b-5wmp3u) ([raw file](https://github.com/gramineproject/gramine/blob/183e5cc8c4132f2b50775340df4afee6a4fb9e10/pal/src/host/linux-sgx/pal_main.c#L348)):*
> ``du.$(id)`id`pa`` is perfectly valid hostname

Hmm, I'm not sure about this, probably kernel accepts it, but most usermode will assume it's in a domain name format.


<!-- Sent from Reviewable.io -->

2022-09-14 00:19 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/889)* status: all files reviewed, 23 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @oshogbo)

___
*[`pal/src/host/linux-common/etc_host_info.c` line 296 at r1](https://reviewable.io/reviews/gramineproject/gramine/889#-NBMi_uY65siouejBVgJ:-NBtLQfE1JquRtQMAqow:b-t61mvv) ([raw file](https://github.com/gramineproject/gramine/blob/de0734e7b190ebbfdee8b7980841db442cb62787/pal/src/host/linux-common/etc_host_info.c#L296)):*
> @boryspoplawski: I think you got lost with negations here. cannot -> can?

No. I meant we cannot fail, because somebody might have set such a weird hostname.

> ofc this is not something for security, it's to detect accidental errors in your configs instead of silently ignoring them

But in most cases we cannot know if it's an error or exotic configuration.
___
*[`pal/src/host/linux-sgx/pal_main.c` line 348 at r4](https://reviewable.io/reviews/gramineproject/gramine/889#-NBTXL0P5OvbriHEZ4d_:-NBtM2n12tnnvUOYjtWh:bv6pswm) ([raw file](https://github.com/gramineproject/gramine/blob/183e5cc8c4132f2b50775340df4afee6a4fb9e10/pal/src/host/linux-sgx/pal_main.c#L348)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ``du.$(id)`id`pa`` is perfectly valid hostname

Hmm, I'm not sure about this, probably kernel accepts it, but most usermode will assume it's in a domain name format.
</blockquote></details>

Actually, why? I think I've once sent an SQLi via hostname :)


<!-- Sent from Reviewable.io -->

2022-09-14 00:32 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/889)* status: all files reviewed, 23 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @oshogbo)

___
*[`pal/src/host/linux-common/etc_host_info.c` line 296 at r1](https://reviewable.io/reviews/gramineproject/gramine/889#-NBMi_uY65siouejBVgJ:-NBtNljB8tUQGfbUEqn2:b-6swb5u) ([raw file](https://github.com/gramineproject/gramine/blob/de0734e7b190ebbfdee8b7980841db442cb62787/pal/src/host/linux-common/etc_host_info.c#L296)):*

> > @boryspoplawski: I think you got lost with negations here. cannot -> can?
> 
> No. I meant we cannot fail, because somebody might have set such a weird hostname.

You said: "we cannot fail on weird domains - Linux allows them, while it's not ideal we don't follow Linux, I think it's worthwhile precaution" - especially the last part sounded like you want us to not follow Linux and fail on them to be precautious.

> > ofc this is not something for security, it's to detect accidental errors in your configs instead of silently ignoring them
> 
> But in most cases we cannot know if it's an error or exotic configuration.

IMO no real-world system would have it configured this way other than by an accident.
___
*[`pal/src/host/linux-sgx/pal_main.c` line 348 at r4](https://reviewable.io/reviews/gramineproject/gramine/889#-NBTXL0P5OvbriHEZ4d_:-NBtOwM2DW1NBlG8USyB:b-ory85q) ([raw file](https://github.com/gramineproject/gramine/blob/183e5cc8c4132f2b50775340df4afee6a4fb9e10/pal/src/host/linux-sgx/pal_main.c#L348)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Actually, why? I think I've once sent an SQLi via hostname :)
</blockquote></details>

"why" what?


<!-- Sent from Reviewable.io -->

2022-09-14 07:27 UTC, dimakuv submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/889)* status: all files reviewed, 23 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @oshogbo)

___
*[`pal/regression/ipv4_parser.c` line 86 at r6](https://reviewable.io/reviews/gramineproject/gramine/889#-NBsU17K2tEDBCwBjyBY:-NBuqXJZA-5DvqRnUab9:bnjjwuy) ([raw file](https://github.com/gramineproject/gramine/blob/bc76c04f57356399c004ea2cf2ac202bddc072f2/pal/regression/ipv4_parser.c#L86)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Wow, that's a decently cursed syntax.
</blockquote></details>

This sounds like a pretty simple thing to add. I don't see why we should *not* add it, so let's do it.
___
*[`pal/src/host/linux-common/etc_host_info.c` line 296 at r1](https://reviewable.io/reviews/gramineproject/gramine/889#-NBMi_uY65siouejBVgJ:-NBustc868CYQOv45O9O:b-clesia) ([raw file](https://github.com/gramineproject/gramine/blob/de0734e7b190ebbfdee8b7980841db442cb62787/pal/src/host/linux-common/etc_host_info.c#L296)):*
> IMO no real-world system would have it configured this way other than by an accident.

...And then it will turn out that e.g. Azure or Alibaba clouds set exotic domain names.

I agree with @boryspoplawski on the rules he listed.
___
*[`pal/src/host/linux-common/etc_host_info.c` line 239 at r3](https://reviewable.io/reviews/gramineproject/gramine/889#-NBRo7pF3m3IpQWDq3wM:-NBuraLq2kcy09iJwh4X:b-8lg0c9) ([raw file](https://github.com/gramineproject/gramine/blob/7b26e658f93d0952a53742adf1c1c33f24862d53/pal/src/host/linux-common/etc_host_info.c#L239)):*
> But I don't want to fail for unknown options, only for options which seem to be corrupted (like here, super long

But maybe a super-long (>32 chars) option is just unknown. How do you distinguish between "clearly-wrong" and "unknown" options? Unless we have an assumption that no option names ever can be greater that 32 (but then we need at least a comment about it).
___
*[`pal/src/host/linux-common/etc_host_info.c` line 301 at r6](https://reviewable.io/reviews/gramineproject/gramine/889#-NBsgHQgDDOF6gT62nWL:-NBusC073dCaqZ3W-PLG:bygzq8o) ([raw file](https://github.com/gramineproject/gramine/blob/bc76c04f57356399c004ea2cf2ac202bddc072f2/pal/src/host/linux-common/etc_host_info.c#L301)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why do we bother with skipping these lines, if we do not skip e.g. ` # comment` (space at the beginning)? Is it worth it?
</blockquote></details>

@boryspoplawski Why do you say that we do *not* skip `# comment` lines? We do skip them -- after this IF, we immediately do `jmp_to_end_of_line()`


<!-- Sent from Reviewable.io -->

2022-09-14 10:49 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/889)* status: all files reviewed, 23 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @oshogbo)

___
*[`pal/regression/ipv4_parser.c` line 86 at r6](https://reviewable.io/reviews/gramineproject/gramine/889#-NBsU17K2tEDBCwBjyBY:-NBv__Oi0Gx5oVDxP9WD:b5z4tjp) ([raw file](https://github.com/gramineproject/gramine/blob/bc76c04f57356399c004ea2cf2ac202bddc072f2/pal/regression/ipv4_parser.c#L86)):*
> I don't see why we should not add it, 

Maybe official IPv4 rules don't allow for it and it's some weird `inet_aton` GNU extension. In such case I'm not so convinced we would want it
___
*[`pal/src/host/linux-common/etc_host_info.c` line 296 at r1](https://reviewable.io/reviews/gramineproject/gramine/889#-NBMi_uY65siouejBVgJ:-NBvauK8EoaImp3DJkpX:bx3bljv) ([raw file](https://github.com/gramineproject/gramine/blob/de0734e7b190ebbfdee8b7980841db442cb62787/pal/src/host/linux-common/etc_host_info.c#L296)):*
> we cannot fail on weird domains - Linux allows them; while it's not ideal we don't follow Linux, I think it's worthwhile precaution

@mkow Ok, this comment was confusing, I see. I meant that for hostname we replace it with `localhost` if the domain doesn't match our criteria (or intend to, I've seen @oshogbo saying something like that)
___
*[`pal/src/host/linux-common/etc_host_info.c` line 301 at r6](https://reviewable.io/reviews/gramineproject/gramine/889#-NBsgHQgDDOF6gT62nWL:-NBv_tb5351I47sktcD6:b-60ovsm) ([raw file](https://github.com/gramineproject/gramine/blob/bc76c04f57356399c004ea2cf2ac202bddc072f2/pal/src/host/linux-common/etc_host_info.c#L301)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@boryspoplawski Why do you say that we do *not* skip `# comment` lines? We do skip them -- after this IF, we immediately do `jmp_to_end_of_line()`
</blockquote></details>

Notice a ` ` (space) before `#`. Ok, you cannot notice it because it was trimmed by reviewable for some reason, my bad didn't notice.
My comment was about cases like:
```
     # comment line
```
(this time seems to be rendering as intended)
___
*[`pal/src/host/linux-sgx/pal_main.c` line 348 at r4](https://reviewable.io/reviews/gramineproject/gramine/889#-NBTXL0P5OvbriHEZ4d_:-NBvbKrLDLzHUIrjbwQu:bhkdzqt) ([raw file](https://github.com/gramineproject/gramine/blob/183e5cc8c4132f2b50775340df4afee6a4fb9e10/pal/src/host/linux-sgx/pal_main.c#L348)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

"why" what?
</blockquote></details>

Why "most usermode will assume it's in a domain name format."


<!-- Sent from Reviewable.io -->

2022-09-14 11:24 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/889)* status: all files reviewed, 22 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @oshogbo)

___
*[`pal/src/host/linux-common/etc_host_info.c` line 296 at r1](https://reviewable.io/reviews/gramineproject/gramine/889#-NBMi_uY65siouejBVgJ:-NBvijvS9CpFI40S1maX:b4sis1m) ([raw file](https://github.com/gramineproject/gramine/blob/de0734e7b190ebbfdee8b7980841db442cb62787/pal/src/host/linux-common/etc_host_info.c#L296)):*
> ...And then it will turn out that e.g. Azure or Alibaba clouds set exotic domain names.

They can't set domain names which doesn't match that domains RFC.

Anyways, seems I'm in minority here, so unblocking.
___
*[`pal/src/host/linux-common/etc_host_info.c` line 239 at r3](https://reviewable.io/reviews/gramineproject/gramine/889#-NBRo7pF3m3IpQWDq3wM:-NBviKAWA4gJLFb5qi-4:bh2dyht) ([raw file](https://github.com/gramineproject/gramine/blob/7b26e658f93d0952a53742adf1c1c33f24862d53/pal/src/host/linux-common/etc_host_info.c#L239)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> But I don't want to fail for unknown options, only for options which seem to be corrupted (like here, super long

But maybe a super-long (>32 chars) option is just unknown. How do you distinguish between "clearly-wrong" and "unknown" options? Unless we have an assumption that no option names ever can be greater that 32 (but then we need at least a comment about it).
</blockquote></details>

I think we can assume that a 32-chars long option is an accidental user mistake, not a real option, with pretty high confidence ;)
I just don't want to silently continue execution on complete garbage sent as input.
___
*[`pal/src/host/linux-sgx/pal_main.c` line 348 at r4](https://reviewable.io/reviews/gramineproject/gramine/889#-NBTXL0P5OvbriHEZ4d_:-NBvj-Tx205Q7DieRvM4:b-o6bpd6) ([raw file](https://github.com/gramineproject/gramine/blob/183e5cc8c4132f2b50775340df4afee6a4fb9e10/pal/src/host/linux-sgx/pal_main.c#L348)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why "most usermode will assume it's in a domain name format."
</blockquote></details>

I think that's its very purpose, even `man hostname` defines it as "system's DNS name". Or maybe cmdline `hostname` is different from that value set in kernel API?


<!-- Sent from Reviewable.io -->

2022-09-14 11:32 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/889)* status: all files reviewed, 22 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @oshogbo)

___
*[`pal/src/host/linux-sgx/pal_main.c` line 348 at r4](https://reviewable.io/reviews/gramineproject/gramine/889#-NBTXL0P5OvbriHEZ4d_:-NBvlEy_9PgRpJ5u5jiZ:b-nbm3b7) ([raw file](https://github.com/gramineproject/gramine/blob/183e5cc8c4132f2b50775340df4afee6a4fb9e10/pal/src/host/linux-sgx/pal_main.c#L348)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I think that's its very purpose, even `man hostname` defines it as "system's DNS name". Or maybe cmdline `hostname` is different from that value set in kernel API?
</blockquote></details>

Let's end the off-topic :)
Here we have search domains, which must be valid, so I still think we can fail here.


<!-- Sent from Reviewable.io -->

2022-09-15 11:00 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/889)* status: all files reviewed, 22 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @oshogbo)

___
*[`Documentation/manifest-syntax.rst` line 175 at r6](https://reviewable.io/reviews/gramineproject/gramine/889#-NBrC83I8YpuvmTn2BZ1:-NBv_2jE6lorPKlNjy5p:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/bc76c04f57356399c004ea2cf2ac202bddc072f2/Documentation/manifest-syntax.rst#L175)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

After the recent changes `corresponding` refers to `NULL`.
</blockquote></details>

Done.
___
*[`libos/src/fs/etc/fs.c` line 16 at r3](https://reviewable.io/reviews/gramineproject/gramine/889#-NBSAgKq1GtcKk3JX745:-NBv_6121W3t2R662lbS:bhhatn4) ([raw file](https://github.com/gramineproject/gramine/blob/7b26e658f93d0952a53742adf1c1c33f24862d53/libos/src/fs/etc/fs.c#L16)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

But we do that for most things, just these two are special.
</blockquote></details>

Is this blocking?
I would prefer as it is, but if you have really really strong opinion I will bend.
___
*[`libos/src/fs/etc/fs.c` line 40 at r6](https://reviewable.io/reviews/gramineproject/gramine/889#-NBrLPG87D2YPNTRWfkH:-NBv_dFCDQrhq6evTYML:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/bc76c04f57356399c004ea2cf2ac202bddc072f2/libos/src/fs/etc/fs.c#L40)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please move to the next line
</blockquote></details>

Done.
___
*[`pal/include/host/linux-common/etc_host_info_internal.h` line 7 at r6](https://reviewable.io/reviews/gramineproject/gramine/889#-NBrPxH03txetZy5bhYH:-NBvaWD90pmI9LUwYd_U:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/bc76c04f57356399c004ea2cf2ac202bddc072f2/pal/include/host/linux-common/etc_host_info_internal.h#L7)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please add a comment why we have this header (and these functions as extern).
</blockquote></details>

Done.
___
*[`pal/regression/ipv4_parser.c` line 14 at r6](https://reviewable.io/reviews/gramineproject/gramine/889#-NBrSg117MxdRQL8oPLS:-NBvaXD78b6anUFtd9z7:b-99y81w) ([raw file](https://github.com/gramineproject/gramine/blob/bc76c04f57356399c004ea2cf2ac202bddc072f2/pal/regression/ipv4_parser.c#L14)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Ughh, the linking we have here is already hacky, but this is too much for my taste. This doesn't even match the original signature. The ideal (well, assuming we leave the linking) would be to make this linked file self contained (most likely split it into two, or something). Alternatively, make this signature correct (and the implementation dummy, but at least correct).
</blockquote></details>

I didn't want to split the `ext_host_info.c` as it would need to be divided into three files to make it logical. As this is the test, I figure we won't care so much. I didn't want to do an original signature as we would need to trace this feature, and it seems pointless and in feature we can forgot to change this signature as compiler wont throw any error.

Maybe I would add a log and assert/exit if this would ever be called? 
___
*[`pal/regression/ipv4_parser.c` line 21 at r6](https://reviewable.io/reviews/gramineproject/gramine/889#-NBsSy6f29Y0IALhGIms:-NBvcP05BNj2_pSDFhyw:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/bc76c04f57356399c004ea2cf2ac202bddc072f2/pal/regression/ipv4_parser.c#L21)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto whole file
</blockquote></details>

Done.
___
*[`pal/regression/ipv4_parser.c` line 86 at r6](https://reviewable.io/reviews/gramineproject/gramine/889#-NBsU17K2tEDBCwBjyBY:-NBvbg0E40xDW6Aj9NEa:b-8lk6kf) ([raw file](https://github.com/gramineproject/gramine/blob/bc76c04f57356399c004ea2cf2ac202bddc072f2/pal/regression/ipv4_parser.c#L86)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

> I don't see why we should not add it, 

Maybe official IPv4 rules don't allow for it and it's some weird `inet_aton` GNU extension. In such case I'm not so convinced we would want it
</blockquote></details>

I added a comment about this.

But if we want to add them like @dimakuv suggested it won't be very hard.
Wiki states:
https://en.wikipedia.org/wiki/IPv4
```
IPv4 addresses may be represented in any notation expressing a 32-bit integer value. They are most often written in dot-decimal notation, which consists of four octets of the address expressed individually in decimal numbers and separated by periods.
```

Internet states:
https://stackoverflow.com/questions/38944670/why-is-ipv4-represented-in-base-10
```
Decimal is a de facto standard; string formatting for IPv4 addresses was never properly standardised. Almost all tools will only take decimal, dotted-quad, notation, but that's not universally true; any tools still using common implementations of inet_aton() are likely to handle alternative formats.
```

And Linux inet_aton:
```
In all of the above forms, components of the dotted address can be specified in decimal, octal (with a leading 0), or hexadecimal, with a leading 0X). Addresses in any of these forms are collectively termed IPV4 numbers-and-dots notation. The form that uses exactly four decimal numbers is referred to as IPv4 dotted-decimal notation (or sometimes: IPv4 dotted-quad notation).
```

And POSIX.1-2017:
```
All numbers supplied as parts in IPv4 dotted decimal notation may be decimal, octal, or hexadecimal, as specified in the ISO C standard (that is, a leading 0x or 0X implies hexadecimal; otherwise, a leading '0' implies octal; otherwise, the number is interpreted as decimal).
```
___
*[`pal/regression/ipv4_parser.c` line 90 at r6](https://reviewable.io/reviews/gramineproject/gramine/889#-NBsUOVS8ZmBTS1y3cCF:-NBvcH9W67OMa5i5QkH-:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/bc76c04f57356399c004ea2cf2ac202bddc072f2/pal/regression/ipv4_parser.c#L90)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please add `8.8.8.017` and `8.8.8.018`. IDK what should happen for both, especially under current rules. Ping threats `017` as octal and `018` as invalid (because it's invalid ocatal). Update: see above.
</blockquote></details>

Done.
___
*[`pal/regression/ipv6_parser.c` line 14 at r6](https://reviewable.io/reviews/gramineproject/gramine/889#-NBsUoaz82Wm75lToyqY:-NBvcIIo8YWDgZ8p4l0x:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/bc76c04f57356399c004ea2cf2ac202bddc072f2/pal/regression/ipv6_parser.c#L14)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

ditto
___
*[`pal/regression/ipv6_parser.c` line 21 at r6](https://reviewable.io/reviews/gramineproject/gramine/889#-NBsUvZh5AP4EvS5h2jD:-NC-dKMS68l37t_ovFmy:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/bc76c04f57356399c004ea2cf2ac202bddc072f2/pal/regression/ipv6_parser.c#L21)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto whole file
</blockquote></details>

Done.
___
*[`pal/regression/ipv6_parser.c` line 32 at r6](https://reviewable.io/reviews/gramineproject/gramine/889#-NBsV70H-Da1KU7FTZty:-NBvcQ8m1Ci1Ck8r5ax2:ba4gyd5) ([raw file](https://github.com/gramineproject/gramine/blob/bc76c04f57356399c [...]

2022-09-15 11:06 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/889)* status: 20 of 27 files reviewed, 22 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "squash! " and "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[`-- commits` line 21 at r4](https://reviewable.io/reviews/gramineproject/gramine/889#-NBTMuNc0a-4Y3mHHlWL):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I think if you do a force push, which will **only** change this oneliner, it should be fine.
</blockquote></details>

Done.
___
*[`-- commits` line 31 at r4](https://reviewable.io/reviews/gramineproject/gramine/889#-NBTN4jZ2uPnvVnOCcxJ):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

ditto.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-09-15 12:50 UTC, mkow reviewed
> Reviewed 7 of 7 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/889)* status: all files reviewed, 26 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "squash! " and "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @oshogbo)

___
*[`pal/regression/ipv4_parser.c` line 91 at r7](https://reviewable.io/reviews/gramineproject/gramine/889#-NC06MSFBYdhez8VoIFX:-NC06MSFBYdhez8VoIFY:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/651f9ce41026909e0d856bddaaf27d75263f4100/pal/regression/ipv4_parser.c#L91)):*
> ```C
> 
>     /* This addresses are valid ones, but (at least for now) we don't want to support other notions
>      * then decimal, because other notions are (probably) not used widdly besides situation where
> ```





_Suggestion:_
```C
than
```
___
*[`pal/regression/ipv4_parser.c` line 91 at r7](https://reviewable.io/reviews/gramineproject/gramine/889#-NC0AqDk8NFRidkK-tEI:-NC0AqDk8NFRidkK-tEJ:b3kre) ([raw file](https://github.com/gramineproject/gramine/blob/651f9ce41026909e0d856bddaaf27d75263f4100/pal/regression/ipv4_parser.c#L91)):*
> ```C
> 
>     /* This addresses are valid ones, but (at least for now) we don't want to support other notions
>      * then decimal, because other notions are (probably) not used widdly besides situation where
> ```

?



_Code quote:_
```C
widdly
```
___
*[`pal/regression/ipv4_parser.c` line 92 at r7](https://reviewable.io/reviews/gramineproject/gramine/889#-NC0At6q9OVvHVb8O2Xb:-NC0At6q9OVvHVb8O2Xc:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/651f9ce41026909e0d856bddaaf27d75263f4100/pal/regression/ipv4_parser.c#L92)):*
> ```C
>     /* This addresses are valid ones, but (at least for now) we don't want to support other notions
>      * then decimal, because other notions are (probably) not used widdly besides situation where
>      * attacker wants to omits some WAFs rules.
> ```





_Suggestion:_
```C
wants to omit
```
___
*[`pal/regression/ipv4_parser.c` line 92 at r7](https://reviewable.io/reviews/gramineproject/gramine/889#-NC0Av073GHrVe8JZG9W:-NC0Av073GHrVe8JZG9X:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/651f9ce41026909e0d856bddaaf27d75263f4100/pal/regression/ipv4_parser.c#L92)):*
> ```C
>     /* This addresses are valid ones, but (at least for now) we don't want to support other notions
>      * then decimal, because other notions are (probably) not used widdly besides situation where
>      * attacker wants to omits some WAFs rules.
> ```





_Suggestion:_
```C
WAF rules
```
___
*[`pal/src/host/linux-common/etc_host_info.c` line 239 at r3](https://reviewable.io/reviews/gramineproject/gramine/889#-NBRo7pF3m3IpQWDq3wM:-NC0BOfv3TcfC7pJt2M9:b-onk2mu) ([raw file](https://github.com/gramineproject/gramine/blob/7b26e658f93d0952a53742adf1c1c33f24862d53/pal/src/host/linux-common/etc_host_info.c#L239)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

> what system ignores everything invalid? What does it mean?

GNU/Linux (tested on Debian GNU/Linux 11 (bullseye)):
```
$ cat /etc/resolv.conf 
asd
asd
asd
rfgoinh3124124
nameserver asdasd
nameserver 999.999.999.999
nameserver 8.8.8.8
asdasda
root:x:0:0:root:/root:/bin/bash
daemon:x:1:1:daemon:/usr/sbin:/usr/sbin/nologin
bin:x:2:2:bin:/bin:/usr/sbin/nologin
$ ping google.pl
PING google.pl (142.250.203.195) 56(84) bytes of data.
64 bytes from waw02s22-in-f3.1e100.net (142.250.203.195): icmp_seq=1 ttl=63 time=4.73 ms
^C
--- google.pl ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 4.727/4.727/4.727/0.000 ms
```

When you remove `nameserver 8.8.8.8` and reset is garbage:
```
$ ping google.pl
ping: google.pl: Temporary failure in name resolution
```
</blockquote></details>

Huh, and no error in the logs?


<!-- Sent from Reviewable.io -->

2022-09-15 13:13 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/889)* status: all files reviewed, 26 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "squash! " and "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[`pal/regression/ipv4_parser.c` line 91 at r7](https://reviewable.io/reviews/gramineproject/gramine/889#-NC06MSFBYdhez8VoIFX:-NC0GfeF86srTVg3O2pK:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/651f9ce41026909e0d856bddaaf27d75263f4100/pal/regression/ipv4_parser.c#L91)):*
> ```C
> 
>     /* This addresses are valid ones, but (at least for now) we don't want to support other notions
>      * then decimal, because other notions are (probably) not used widdly besides situation where
> ```

Done.
___
*[`pal/regression/ipv4_parser.c` line 91 at r7](https://reviewable.io/reviews/gramineproject/gramine/889#-NC0AqDk8NFRidkK-tEI:-NC0GqbkBOxhBeWQylZM:b-irdl3v) ([raw file](https://github.com/gramineproject/gramine/blob/651f9ce41026909e0d856bddaaf27d75263f4100/pal/regression/ipv4_parser.c#L91)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

?
</blockquote></details>

widely
___
*[`pal/regression/ipv4_parser.c` line 92 at r7](https://reviewable.io/reviews/gramineproject/gramine/889#-NC0Av073GHrVe8JZG9W:-NC0GhmSCQy_6U0L0RFv:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/651f9ce41026909e0d856bddaaf27d75263f4100/pal/regression/ipv4_parser.c#L92)):*
> ```C
>     /* This addresses are valid ones, but (at least for now) we don't want to support other notions
>      * then decimal, because other notions are (probably) not used widdly besides situation where
>      * attacker wants to omits some WAFs rules.
> ```

Done.
___
*[`pal/regression/ipv4_parser.c` line 92 at r7](https://reviewable.io/reviews/gramineproject/gramine/889#-NC0At6q9OVvHVb8O2Xb:-NC0GiZ63mbSZUt38J8_:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/651f9ce41026909e0d856bddaaf27d75263f4100/pal/regression/ipv4_parser.c#L92)):*
> ```C
>     /* This addresses are valid ones, but (at least for now) we don't want to support other notions
>      * then decimal, because other notions are (probably) not used widdly besides situation where
>      * attacker wants to omits some WAFs rules.
> ```

Done.
___
*[`pal/src/host/linux-common/etc_host_info.c` line 239 at r3](https://reviewable.io/reviews/gramineproject/gramine/889#-NBRo7pF3m3IpQWDq3wM:-NC0G8qG5wdFc-7_DaVy:bqng2zx) ([raw file](https://github.com/gramineproject/gramine/blob/7b26e658f93d0952a53742adf1c1c33f24862d53/pal/src/host/linux-common/etc_host_info.c#L239)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Huh, and no error in the logs?
</blockquote></details>

No, and I check the glibc code - it doesn't print any:
https://elixir.bootlin.com/glibc/latest/source/resolv/res_init.c#L508


<!-- Sent from Reviewable.io -->

2022-09-15 14:07 UTC, boryspoplawski requested changes
> Reviewed 6 of 7 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/889)* status: all files reviewed, 16 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @oshogbo)

___
*[`libos/src/fs/etc/fs.c` line 16 at r3](https://reviewable.io/reviews/gramineproject/gramine/889#-NBSAgKq1GtcKk3JX745:-NC0-6T89dKpOW0h2Xxn:b-qtcckb) ([raw file](https://github.com/gramineproject/gramine/blob/7b26e658f93d0952a53742adf1c1c33f24862d53/libos/src/fs/etc/fs.c#L16)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Is this blocking?
I would prefer as it is, but if you have really really strong opinion I will bend.
</blockquote></details>

Since everyone else seems to be fine with the current version, I'm unblocking
___
*[`pal/regression/ipv4_parser.c` line 14 at r6](https://reviewable.io/reviews/gramineproject/gramine/889#-NBrSg117MxdRQL8oPLS:-NC0Pd8qAtuCOohGrc7f:b-oljwga) ([raw file](https://github.com/gramineproject/gramine/blob/bc76c04f57356399c004ea2cf2ac202bddc072f2/pal/regression/ipv4_parser.c#L14)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

I didn't want to split the `ext_host_info.c` as it would need to be divided into three files to make it logical. As this is the test, I figure we won't care so much. I didn't want to do an original signature as we would need to trace this feature, and it seems pointless and in feature we can forgot to change this signature as compiler wont throw any error.

Maybe I would add a log and assert/exit if this would ever be called? 
</blockquote></details>

Yeah, at list kill the whole process
___
*[`pal/regression/ipv4_parser.c` line 86 at r6](https://reviewable.io/reviews/gramineproject/gramine/889#-NBsU17K2tEDBCwBjyBY:-NC0Q22z7Sjcp-nudiSq:b-vybgsv) ([raw file](https://github.com/gramineproject/gramine/blob/bc76c04f57356399c004ea2cf2ac202bddc072f2/pal/regression/ipv4_parser.c#L86)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

I added a comment about this.

But if we want to add them like @dimakuv suggested it won't be very hard.
Wiki states:
https://en.wikipedia.org/wiki/IPv4
```
IPv4 addresses may be represented in any notation expressing a 32-bit integer value. They are most often written in dot-decimal notation, which consists of four octets of the address expressed individually in decimal numbers and separated by periods.
```

Internet states:
https://stackoverflow.com/questions/38944670/why-is-ipv4-represented-in-base-10
```
Decimal is a de facto standard; string formatting for IPv4 addresses was never properly standardised. Almost all tools will only take decimal, dotted-quad, notation, but that's not universally true; any tools still using common implementations of inet_aton() are likely to handle alternative formats.
```

And Linux inet_aton:
```
In all of the above forms, components of the dotted address can be specified in decimal, octal (with a leading 0), or hexadecimal, with a leading 0X). Addresses in any of these forms are collectively termed IPV4 numbers-and-dots notation. The form that uses exactly four decimal numbers is referred to as IPv4 dotted-decimal notation (or sometimes: IPv4 dotted-quad notation).
```

And POSIX.1-2017:
```
All numbers supplied as parts in IPv4 dotted decimal notation may be decimal, octal, or hexadecimal, as specified in the ISO C standard (that is, a leading 0x or 0X implies hexadecimal; otherwise, a leading '0' implies octal; otherwise, the number is interpreted as decimal).
```

</blockquote></details>

I don't mind adding the support or leaving it as it is, up to you
___
*[`pal/regression/ipv4_parser.c` line 97 at r8](https://reviewable.io/reviews/gramineproject/gramine/889#-NC0QWM760TIPDnPYPcw:-NC0QWM760TIPDnPYPcx:b-elyd3c) ([raw file](https://github.com/gramineproject/gramine/blob/2d093b1c70d49311b91c4b3a775d5ff6d0ab3955/pal/regression/ipv4_parser.c#L97)):*
> ```C
>     CHECK(ipv4_invalid("8.8.8.017"));
>     CHECK(ipv4_invalid("0x8.8.8.8"));
>     CHECK(ipv4_invalid("0b1.8.8.8"));
> ```

This one is not valid in `inet_aton`
___
*[`pal/src/host/linux-common/etc_host_info.c` line 160 at r6](https://reviewable.io/reviews/gramineproject/gramine/889#-NBsbkzg1STkaRAjkPY6:-NC0SRGf-m6nKlTZvC-H:b-74tje0) ([raw file](https://github.com/gramineproject/gramine/blob/bc76c04f57356399c004ea2cf2ac202bddc072f2/pal/src/host/linux-common/etc_host_info.c#L160)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Dunno, to be honest - I don't have any opinion here.
</blockquote></details>

cc @mkow @dimakuv 


<!-- Sent from Reviewable.io -->

2022-09-15 14:10 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/889)* status: all files reviewed, 16 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @oshogbo)

___
*[`pal/regression/ipv4_parser.c` line 92 at r8](https://reviewable.io/reviews/gramineproject/gramine/889#-NC0Qg-r6TJNSiDjwpil:-NC0UAcj1n_ltbo1egaL:b-i42z6i) ([raw file](https://github.com/gramineproject/gramine/blob/2d093b1c70d49311b91c4b3a775d5ff6d0ab3955/pal/regression/ipv4_parser.c#L92)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Am I the only one who doesn't know what WAF rules are? Googling this term shows a lot of unrelated stuff.
</blockquote></details>

https://en.wikipedia.org/wiki/Web_application_firewall


<!-- Sent from Reviewable.io -->

2022-09-15 15:23 UTC, mkow reviewed
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/889)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @oshogbo)

___
*[`pal/regression/ipv4_parser.c` line 92 at r8](https://reviewable.io/reviews/gramineproject/gramine/889#-NC0Qg-r6TJNSiDjwpil:-NC0ixEP59ei2zFB6lIH:b-ebonm5) ([raw file](https://github.com/gramineproject/gramine/blob/2d093b1c70d49311b91c4b3a775d5ff6d0ab3955/pal/regression/ipv4_parser.c#L92)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

But how is this relevant to the comment? I guess I miss some broader context here, but `besides situation where attacker wants to omit some WAF rules` makes no sense to me.
</blockquote></details>

I think it's a random trivia/commentary - these alternative forms are often used to circumvent poor WAFs which try to filter out incoming malicious requests.
I'm neutral whether to keep or remove it.
___
*[`pal/regression/ipv4_parser.c` line 97 at r8](https://reviewable.io/reviews/gramineproject/gramine/889#-NC0R2MC1A0uKg9BIwcn:-NC0jJbo7YQ-aNR74N5J:bofd42x) ([raw file](https://github.com/gramineproject/gramine/blob/2d093b1c70d49311b91c4b3a775d5ff6d0ab3955/pal/regression/ipv4_parser.c#L97)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This looks like a totally invalid address. Why is it in the "not yet supported" list?
</blockquote></details>

Because they are correctly parsed by `inet_aton()`, and there's no official specification what's a valid IPv4 format exactly.
___
*[`pal/src/host/linux-common/etc_host_info.c` line 239 at r3](https://reviewable.io/reviews/gramineproject/gramine/889#-NBRo7pF3m3IpQWDq3wM:-NC0ja47CtO33tezZGzT:b-n5pn0l) ([raw file](https://github.com/gramineproject/gramine/blob/7b26e658f93d0952a53742adf1c1c33f24862d53/pal/src/host/linux-common/etc_host_info.c#L239)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

No, and I check the glibc code - it doesn't print any:
https://elixir.bootlin.com/glibc/latest/source/resolv/res_init.c#L508
</blockquote></details>

Ugh, that's really bad of them. But ok, then I'm resolving.
___
*[`pal/src/host/linux-common/etc_host_info.c` line 160 at r6](https://reviewable.io/reviews/gramineproject/gramine/889#-NBsbkzg1STkaRAjkPY6:-NC0jVX01acQrta3qVo6:b-9habqp) ([raw file](https://github.com/gramineproject/gramine/blob/bc76c04f57356399c004ea2cf2ac202bddc072f2/pal/src/host/linux-common/etc_host_info.c#L160)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I was fine with this for loop.
</blockquote></details>

I'm neutral here.


<!-- Sent from Reviewable.io -->

2022-09-15 15:39 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/889)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @oshogbo)

___
*[`pal/regression/ipv4_parser.c` line 97 at r8](https://reviewable.io/reviews/gramineproject/gramine/889#-NC0R2MC1A0uKg9BIwcn:-NC0n06mCEi1RkYMBYoI:b-mofchq) ([raw file](https://github.com/gramineproject/gramine/blob/2d093b1c70d49311b91c4b3a775d5ff6d0ab3955/pal/regression/ipv4_parser.c#L97)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Because they are correctly parsed by `inet_aton()`, and there's no official specification what's a valid IPv4 format exactly.
</blockquote></details>

@mkow no, `0b1` is not valid.


<!-- Sent from Reviewable.io -->

2022-09-15 15:47 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/889)* status: 24 of 27 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[`pal/regression/ipv4_parser.c` line 14 at r6](https://reviewable.io/reviews/gramineproject/gramine/889#-NBrSg117MxdRQL8oPLS:-NC0nX2n31z_SYp3CGod:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/bc76c04f57356399c004ea2cf2ac202bddc072f2/pal/regression/ipv4_parser.c#L14)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Yeah, at list kill the whole process
</blockquote></details>

Done.
___
*[`pal/regression/ipv4_parser.c` line 90 at r8](https://reviewable.io/reviews/gramineproject/gramine/889#-NC0QSxZ0kcp0aCG35lh:-NC0ksT4DbIoSTwIOmSP:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/2d093b1c70d49311b91c4b3a775d5ff6d0ab3955/pal/regression/ipv4_parser.c#L90)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`These`
</blockquote></details>

Done.
___
*[`pal/regression/ipv4_parser.c` line 92 at r8](https://reviewable.io/reviews/gramineproject/gramine/889#-NC0Qg-r6TJNSiDjwpil:-NC0kvmm6FF9xiSz7arB:b2idskt) ([raw file](https://github.com/gramineproject/gramine/blob/2d093b1c70d49311b91c4b3a775d5ff6d0ab3955/pal/regression/ipv4_parser.c#L92)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I think it's a random trivia/commentary - these alternative forms are often used to circumvent poor WAFs which try to filter out incoming malicious requests.
I'm neutral whether to keep or remove it.
</blockquote></details>

I will drop this comment then.
___
*[`pal/regression/ipv4_parser.c` line 97 at r8](https://reviewable.io/reviews/gramineproject/gramine/889#-NC0QWM760TIPDnPYPcw:-NC0l7Br9RDd34jKURMs:b-equo5d) ([raw file](https://github.com/gramineproject/gramine/blob/2d093b1c70d49311b91c4b3a775d5ff6d0ab3955/pal/regression/ipv4_parser.c#L97)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This one is not valid in `inet_aton`
</blockquote></details>

Yes my bad.
___
*[`pal/regression/ipv4_parser.c` line 97 at r8](https://reviewable.io/reviews/gramineproject/gramine/889#-NC0R2MC1A0uKg9BIwcn:-NC0l7uT6UUAjDi86b63:b-l0pki8) ([raw file](https://github.com/gramineproject/gramine/blob/2d093b1c70d49311b91c4b3a775d5ff6d0ab3955/pal/regression/ipv4_parser.c#L97)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Because they are correctly parsed by `inet_aton()`, and there's no official specification what's a valid IPv4 format exactly.
</blockquote></details>

Yes these addresses are those "exotic" ones we discuss in other places.
___
*[`pal/src/host/linux-sgx/pal_main.c` line 348 at r4](https://reviewable.io/reviews/gramineproject/gramine/889#-NBTXL0P5OvbriHEZ4d_:-NC0oG_UDdmL0hEoD8u0:b-2dthws) ([raw file](https://github.com/gramineproject/gramine/blob/183e5cc8c4132f2b50775340df4afee6a4fb9e10/pal/src/host/linux-sgx/pal_main.c#L348)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Let's end the off-topic :)
Here we have search domains, which must be valid, so I still think we can fail here.
</blockquote></details>

@boryspoplawski @dimakuv @mkow 

So to sum this up:
So we can have garbage in `resolv.conf`. We don't verify a search keyword in untrusted pal as we would need to do it twice (in trusted in untrusted). Normal application ignores everything that is invalid. I wouldn't fail here, as again user might not have option to fix it by himself.


<!-- Sent from Reviewable.io -->

2022-09-15 16:12 UTC, dimakuv approved these changes
> Reviewed 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/889)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[`pal/src/host/linux-sgx/pal_main.c` line 348 at r4](https://reviewable.io/reviews/gramineproject/gramine/889#-NBTXL0P5OvbriHEZ4d_:-NC0ujDg5ntRraOoYS2y:by7hpfl) ([raw file](https://github.com/gramineproject/gramine/blob/183e5cc8c4132f2b50775340df4afee6a4fb9e10/pal/src/host/linux-sgx/pal_main.c#L348)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

@boryspoplawski @dimakuv @mkow 

So to sum this up:
So we can have garbage in `resolv.conf`. We don't verify a search keyword in untrusted pal as we would need to do it twice (in trusted in untrusted). Normal application ignores everything that is invalid. I wouldn't fail here, as again user might not have option to fix it by himself.
</blockquote></details>

Seeing that other apps/libs do *not* fail on garbage, I would also *not* fail in Gramine. Printing log messages is enough to my taste.


<!-- Sent from Reviewable.io -->

2022-09-15 16:13 UTC, mkow submitted a review, later dismissed
> Reviewed 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/889)* status: all files reviewed, 5 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[`pal/regression/ipv4_parser.c` line 97 at r8](https://reviewable.io/reviews/gramineproject/gramine/889#-NC0R2MC1A0uKg9BIwcn:-NC0uJpqErgplQAg4k7X:b-6w2ifm) ([raw file](https://github.com/gramineproject/gramine/blob/2d093b1c70d49311b91c4b3a775d5ff6d0ab3955/pal/regression/ipv4_parser.c#L97)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Yes these addresses are those "exotic" ones we discuss in other places.
</blockquote></details>

Hmm, for some reason I thought this comment was about the one address above (`0x8.`), sorry. Although @oshogbo seems to imply that this `0b1` is also parsed correctly by `inet_aton()`?
___
*[`pal/src/host/linux-sgx/pal_main.c` line 348 at r4](https://reviewable.io/reviews/gramineproject/gramine/889#-NBTXL0P5OvbriHEZ4d_:-NC0uvZT67y2Y7br1Cvx:bkabfcj) ([raw file](https://github.com/gramineproject/gramine/blob/183e5cc8c4132f2b50775340df4afee6a4fb9e10/pal/src/host/linux-sgx/pal_main.c#L348)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Seeing that other apps/libs do *not* fail on garbage, I would also *not* fail in Gramine. Printing log messages is enough to my taste.
</blockquote></details>

Ok, I'm not gonna die on this hill :)


<!-- Sent from Reviewable.io -->

2022-09-15 16:25 UTC, boryspoplawski approved these changes
> Reviewed 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/889)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[`pal/regression/ipv4_parser.c` line 97 at r8](https://reviewable.io/reviews/gramineproject/gramine/889#-NC0R2MC1A0uKg9BIwcn:-NC0xrnf3gouvSwk7o0L:bwdj7m2) ([raw file](https://github.com/gramineproject/gramine/blob/2d093b1c70d49311b91c4b3a775d5ff6d0ab3955/pal/regression/ipv4_parser.c#L97)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Hmm, for some reason I thought this comment was about the one address above (`0x8.`), sorry. Although @oshogbo seems to imply that this `0b1` is also parsed correctly by `inet_aton()`?
</blockquote></details>

No, it's not.
___
*[`pal/src/host/linux-sgx/pal_main.c` line 348 at r4](https://reviewable.io/reviews/gramineproject/gramine/889#-NBTXL0P5OvbriHEZ4d_:-NC0rn9rC1UkYNG-DdNG:btn54au) ([raw file](https://github.com/gramineproject/gramine/blob/183e5cc8c4132f2b50775340df4afee6a4fb9e10/pal/src/host/linux-sgx/pal_main.c#L348)):*
> So we can have garbage in resolv.conf

Yes, but this is a bit different. Here we validate a domain (argument to `search`), not an arbitrary line in `resolv.conf`

> as we would need to do it twice (in trusted in untrusted). 

Why? IMO trusted (i.e. here) is enough.

Since everybody else is fine, I'm unblocking.


<!-- Sent from Reviewable.io -->

2022-09-15 17:52 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/889)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

___
*[`pal/regression/ipv4_parser.c` line 97 at r8](https://reviewable.io/reviews/gramineproject/gramine/889#-NC0R2MC1A0uKg9BIwcn:-NC1GTd8BwpNEXxDY2kv:bczai0a) ([raw file](https://github.com/gramineproject/gramine/blob/2d093b1c70d49311b91c4b3a775d5ff6d0ab3955/pal/regression/ipv4_parser.c#L97)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

No, it's not.
</blockquote></details>

No 0b1 is not a valid one.
I was also thought this comments is about the one address above.


<!-- Sent from Reviewable.io -->

2022-09-15 19:49 UTC, mkow requested changes
> Reviewed 6 of 6 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/889)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/889#-NC1gNSr61ytTTCQZblX:-NC1gNSr61ytTTCQZblY:b-3iy5nu) (no related file):*
We should add this option to the manifest of some LibOS test or CI-Example (seems we missed this earlier).

___
___
*[`pal/regression/ipv4_parser.c` line 97 at r8](https://reviewable.io/reviews/gramineproject/gramine/889#-NC0R2MC1A0uKg9BIwcn:-NC1_KDA3Qc_7kTkohkk:brjk102) ([raw file](https://github.com/gramineproject/gramine/blob/2d093b1c70d49311b91c4b3a775d5ff6d0ab3955/pal/regression/ipv4_parser.c#L97)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

No 0b1 is not a valid one.
I was also thought this comments is about the one address above.
</blockquote></details>

Maybe the code here was moving around a bit between versions and thus the comment's position depended on which diff ranges we had selected.
___
*[`pal/src/host/linux-sgx/pal_main.c` line 292 at r10](https://reviewable.io/reviews/gramineproject/gramine/889#-NC1g4OWE57ERDmhiza-:-NC1g4OWE57ERDmhiza0:b-dbcjdi) ([raw file](https://github.com/gramineproject/gramine/blob/004f93ce13177c66313e813451a1a3797415a72b/pal/src/host/linux-sgx/pal_main.c#L292)):*
> ```C
>  * - RFC2181.
>  */
> static bool is_hostname_valid(const char* hostname) {
> ```

Please add a warning comment here that `hostname` contents are untrusted and may not be NULL-terminated (but the buffer it guaranteed to be at least of `PAL_HOSTNAME_MAX` bytes large).
___
*[`pal/src/host/linux-sgx/pal_main.c` line 369 at r10](https://reviewable.io/reviews/gramineproject/gramine/889#-NC1fbKsE5YgjbFZxUWx:-NC1fbKtAmcmGXtRxVUH:buhv3ez) ([raw file](https://github.com/gramineproject/gramine/blob/004f93ce13177c66313e813451a1a3797415a72b/pal/src/host/linux-sgx/pal_main.c#L369)):*
> ```C
>     for (size_t i = 0; i < untrusted_dns.dn_search_count; i++) {
>         if (!is_hostname_valid(untrusted_dns.dn_search[i])) {
>             log_warning("The search domain name %s is invalid, skipping it", untrusted_dns.dn_search[i]);
> ```

We can't print `untrusted_dns.dn_search[i]` here, it wasn't validated at this point (and thus, e.g., may not be NULL-terminated).


<!-- Sent from Reviewable.io -->

2022-09-15 20:52 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/889)* status: 26 of 32 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/889#-NC1gNSr61ytTTCQZblX:-NC1v3BT6z-l45g8gxYF:b-896fix) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

We should add this option to the manifest of some LibOS test or CI-Example (seems we missed this earlier).
</blockquote></details>

Done.

___
___
*[`pal/src/host/linux-sgx/pal_main.c` line 292 at r10](https://reviewable.io/reviews/gramineproject/gramine/889#-NC1g4OWE57ERDmhiza-:-NC1v54e73hOrrpqdcF1:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/004f93ce13177c66313e813451a1a3797415a72b/pal/src/host/linux-sgx/pal_main.c#L292)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please add a warning comment here that `hostname` contents are untrusted and may not be NULL-terminated (but the buffer it guaranteed to be at least of `PAL_HOSTNAME_MAX` bytes large).
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/pal_main.c` line 369 at r10](https://reviewable.io/reviews/gramineproject/gramine/889#-NC1fbKsE5YgjbFZxUWx:-NC1v7Au80BTDeSqM9MP:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/004f93ce13177c66313e813451a1a3797415a72b/pal/src/host/linux-sgx/pal_main.c#L369)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

We can't print `untrusted_dns.dn_search[i]` here, it wasn't validated at this point (and thus, e.g., may not be NULL-terminated).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-09-15 20:56 UTC, mkow requested changes
> Reviewed 6 of 6 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/889)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @oshogbo)

___
*[`pal/src/host/linux-sgx/pal_main.c` line 292 at r10](https://reviewable.io/reviews/gramineproject/gramine/889#-NC1g4OWE57ERDmhiza-:-NC1vkMe78PXaBFrpfYd:bjvjuop) ([raw file](https://github.com/gramineproject/gramine/blob/004f93ce13177c66313e813451a1a3797415a72b/pal/src/host/linux-sgx/pal_main.c#L292)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

But you added NULL termination to the callsite, so this comment (and this property of this function) are not needed anymore.
___
*[`pal/src/host/linux-sgx/pal_main.c` line 281 at r11](https://reviewable.io/reviews/gramineproject/gramine/889#-NC1vd_Y7pjOOXStxJvZ:-NC1vd_ZBzW2phFrHHvs:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/5fbe0b4e479eba9bfb53a935ee6272209746747b/pal/src/host/linux-sgx/pal_main.c#L281)):*
> ```C
> 
> /*
>  * This function analyze the untrusted buffer, before using it, please make sure
> ```





_Suggestion:_
```C
analyzes
```


<!-- Sent from Reviewable.io -->

2022-09-15 20:58 UTC, boryspoplawski reviewed
> Reviewed 6 of 6 files at r10, 6 of 6 files at r11.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/889)* status: 31 of 32 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @oshogbo)



<!-- Sent from Reviewable.io -->

2022-09-15 21:09 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/889)* status: 30 of 32 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @oshogbo)

___
*[`pal/src/host/linux-sgx/pal_main.c` line 292 at r10](https://reviewable.io/reviews/gramineproject/gramine/889#-NC1g4OWE57ERDmhiza-:-NC1wfCQCSl28JprQMJj:b-cfjngj) ([raw file](https://github.com/gramineproject/gramine/blob/004f93ce13177c66313e813451a1a3797415a72b/pal/src/host/linux-sgx/pal_main.c#L292)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

But you added NULL termination to the callsite, so this comment (and this property of this function) are not needed anymore.
</blockquote></details>

Hym, I was thinking that this is for further uses. I will drop it then.


<!-- Sent from Reviewable.io -->

2022-09-15 21:55 UTC, boryspoplawski requested changes
> Reviewed 2 of 2 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/889)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @oshogbo)

___
*[`libos/src/fs/etc/fs.c` line 36 at r13](https://reviewable.io/reviews/gramineproject/gramine/889#-NC27hH43H8KRsrytLcN:-NC27hH43H8KRsrytLcO:b-x8wviy) ([raw file](https://github.com/gramineproject/gramine/blob/91b3cf84da981e86a370513cdd122cf74b4f8ca5/libos/src/fs/etc/fs.c#L36)):*
> ```C
>     __UNUSED(dent);
> 
>     size_t space_left = 0;
> ```

what is this change? It makes no sense to me.
___
*[`libos/src/fs/etc/fs.c` line 38 at r13](https://reviewable.io/reviews/gramineproject/gramine/889#-NC27kbK4o0WUZSzA98Z:-NC27kbK4o0WUZSzA98_:b3kre) ([raw file](https://github.com/gramineproject/gramine/blob/91b3cf84da981e86a370513cdd122cf74b4f8ca5/libos/src/fs/etc/fs.c#L38)):*
> ```C
>     size_t space_left = 0;
> 
>     /* Estimate the space_left of buffer: */
> ```

?
___
*[`libos/src/fs/etc/fs.c` line 63 at r13](https://reviewable.io/reviews/gramineproject/gramine/889#-NC27qAiB9aJWoKR5A6K:-NC27qAiB9aJWoKR5A6L:b-u4txro) ([raw file](https://github.com/gramineproject/gramine/blob/91b3cf84da981e86a370513cdd122cf74b4f8ca5/libos/src/fs/etc/fs.c#L63)):*
> ```C
>         if (!g_pal_public_state->dns_host.nsaddr_list[i].is_ipv6) {
>             uint32_t addr = g_pal_public_state->dns_host.nsaddr_list[i].ipv4;
>             ret = put_string(&ptr, &space_left, "nameserver %u.%u.%u.%u\n",
> ```

I see, here it would make sense, but all previous usages make none. Please revert
___
*[`pal/src/host/linux-sgx/pal_main.c` line 292 at r10](https://reviewable.io/reviews/gramineproject/gramine/889#-NC1g4OWE57ERDmhiza-:-NC281QQDpK6CzdwvquJ:bpuyz8c) ([raw file](https://github.com/gramineproject/gramine/blob/004f93ce13177c66313e813451a1a3797415a72b/pal/src/host/linux-sgx/pal_main.c#L292)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Hym, I was thinking that this is for further uses. I will drop it then.
</blockquote></details>

Wait what? What was wrong with `This function analyze the untrusted buffer, before using it, please make sure that the buffer is NULL terminated.`?\* The callsite added nullbyte and the commet stated that it's required.

\* Except `NULL terminated` - NULL is for pointers.


<!-- Sent from Reviewable.io -->

2022-09-16 00:48 UTC, mkow reviewed
> Reviewed 2 of 2 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/889)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @oshogbo)

___
*[`libos/src/fs/etc/fs.c` line 106 at r11](https://reviewable.io/reviews/gramineproject/gramine/889#-NC2jHml7iSqZUAexyfN:-NC2jHml7iSqZUAexyfO:b-o29968) ([raw file](https://github.com/gramineproject/gramine/blob/5fbe0b4e479eba9bfb53a935ee6272209746747b/libos/src/fs/etc/fs.c#L106)):*
> ```C
>         goto out;
>     }
>     assert(finalsize < size);
> ```

@boryspoplawski: that's a proof the old name was confusing - this assert was incorrect, despite looking unsuspicious
___
*[`libos/src/fs/etc/fs.c` line 36 at r13](https://reviewable.io/reviews/gramineproject/gramine/889#-NC27hH43H8KRsrytLcN:-NC2j162Ew767bz0i-cM:b-uvtlm6) ([raw file](https://github.com/gramineproject/gramine/blob/91b3cf84da981e86a370513cdd122cf74b4f8ca5/libos/src/fs/etc/fs.c#L36)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

what is this change? It makes no sense to me.
</blockquote></details>

We discussed this on priv, the old version was quite confusing. But yeah, in the beginning this name doesn't make sense. Maybe just split into two variables then?
___
*[`pal/src/host/linux-sgx/pal_main.c` line 292 at r10](https://reviewable.io/reviews/gramineproject/gramine/889#-NC1g4OWE57ERDmhiza-:-NC2j_bC6z2ZXspP4Ndu:b-kds7pl) ([raw file](https://github.com/gramineproject/gramine/blob/004f93ce13177c66313e813451a1a3797415a72b/pal/src/host/linux-sgx/pal_main.c#L292)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Wait what? What was wrong with `This function analyze the untrusted buffer, before using it, please make sure that the buffer is NULL terminated.`?\* The callsite added nullbyte and the commet stated that it's required.

\* Except `NULL terminated` - NULL is for pointers.
</blockquote></details>

I think this sentence doesn't make sense. That the input buffer is untrusted is a property of the callsite, here we can only specify what we guarantee or not. If we want to say something here then just say that this function is guaranteed to work correctly even when contents of the input C-string are malicious.


<!-- Sent from Reviewable.io -->

2022-09-16 06:46 UTC, dimakuv requested changes
> Reviewed 5 of 6 files at r10, 5 of 6 files at r11, 2 of 2 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/889)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @oshogbo)

___
*[`CI-Examples/ra-tls-mbedtls/client.manifest.template` line 27 at r13](https://reviewable.io/reviews/gramineproject/gramine/889#-NC40tIn2Df67hd0KYf9:-NC40tIn2Df67hd0KYfA:b-qdgoy2) ([raw file](https://github.com/gramineproject/gramine/blob/91b3cf84da981e86a370513cdd122cf74b4f8ca5/CI-Examples/ra-tls-mbedtls/client.manifest.template#L27)):*
> ```
> sgx.debug = true
> sgx.enclave_size = "512M"
> sys.emulate_etc_files = true
> ```

Why is this new manifest option surrounded by `sgx.` ones? Please move it above all `sgx.` options, in a visually separate block, like this:
```
  ...
  { path = "/client", uri = "file:client" },
]

sys.emulate_etc_files = true

sgx.debug = true
sgx.enclave_size = "512M"
...
```
___
*[`CI-Examples/ra-tls-secret-prov/secret_prov/client.manifest.template` line 22 at r13](https://reviewable.io/reviews/gramineproject/gramine/889#-NC416dI3_gfwcX2mUq1:-NC416dI3_gfwcX2mUq2:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/91b3cf84da981e86a370513cdd122cf74b4f8ca5/CI-Examples/ra-tls-secret-prov/secret_prov/client.manifest.template#L22)):*
> ```
> 
> sgx.enclave_size = "512M"
> sys.emulate_etc_files = true
> ```

ditto
___
*[`CI-Examples/ra-tls-secret-prov/secret_prov_minimal/client.manifest.template` line 26 at r13](https://reviewable.io/reviews/gramineproject/gramine/889#-NC418QJ-sx9Oh6z4x_-:-NC418QJ-sx9Oh6z4x_0:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/91b3cf84da981e86a370513cdd122cf74b4f8ca5/CI-Examples/ra-tls-secret-prov/secret_prov_minimal/client.manifest.template#L26)):*
> ```
> 
> sgx.enclave_size = "512M"
> sys.emulate_etc_files = true
> ```

ditto
___
*[`CI-Examples/ra-tls-secret-prov/secret_prov_pf/client.manifest.template` line 28 at r13](https://reviewable.io/reviews/gramineproject/gramine/889#-NC41ATl-2bIily8w90J:-NC41ATm3NQJrMFx-5cn:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/91b3cf84da981e86a370513cdd122cf74b4f8ca5/CI-Examples/ra-tls-secret-prov/secret_prov_pf/client.manifest.template#L28)):*
> ```
> 
> sgx.enclave_size = "512M"
> sys.emulate_etc_files = true
> ```

ditto
___
*[`libos/src/fs/etc/fs.c` line 36 at r13](https://reviewable.io/reviews/gramineproject/gramine/889#-NC27hH43H8KRsrytLcN:-NC41Ow75FCXsH5cHgrF:bfoven7) ([raw file](https://github.com/gramineproject/gramine/blob/91b3cf84da981e86a370513cdd122cf74b4f8ca5/libos/src/fs/etc/fs.c#L36)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

We discussed this on priv, the old version was quite confusing. But yeah, in the beginning this name doesn't make sense. Maybe just split into two variables then?
</blockquote></details>

+1, let's make it two variables (`size` as before and a new one `space_left`)


<!-- Sent from Reviewable.io -->

2022-09-16 07:36 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/889)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[`CI-Examples/ra-tls-mbedtls/client.manifest.template` line 27 at r13](https://reviewable.io/reviews/gramineproject/gramine/889#-NC40tIn2Df67hd0KYf9:-NC4DCmG9HJrsGTnZvav:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/91b3cf84da981e86a370513cdd122cf74b4f8ca5/CI-Examples/ra-tls-mbedtls/client.manifest.template#L27)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why is this new manifest option surrounded by `sgx.` ones? Please move it above all `sgx.` options, in a visually separate block, like this:
```
  ...
  { path = "/client", uri = "file:client" },
]

sys.emulate_etc_files = true

sgx.debug = true
sgx.enclave_size = "512M"
...
```
</blockquote></details>

Done.
___
*[`CI-Examples/ra-tls-secret-prov/secret_prov/client.manifest.template` line 22 at r13](https://reviewable.io/reviews/gramineproject/gramine/889#-NC416dI3_gfwcX2mUq1:-NC4DCTD97pRhw00AZJ_:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/91b3cf84da981e86a370513cdd122cf74b4f8ca5/CI-Examples/ra-tls-secret-prov/secret_prov/client.manifest.template#L22)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`CI-Examples/ra-tls-secret-prov/secret_prov_minimal/client.manifest.template` line 26 at r13](https://reviewable.io/reviews/gramineproject/gramine/889#-NC418QJ-sx9Oh6z4x_-:-NC4DDbF2JsmkS-BaABY:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/91b3cf84da981e86a370513cdd122cf74b4f8ca5/CI-Examples/ra-tls-secret-prov/secret_prov_minimal/client.manifest.template#L26)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`CI-Examples/ra-tls-secret-prov/secret_prov_pf/client.manifest.template` line 28 at r13](https://reviewable.io/reviews/gramineproject/gramine/889#-NC41ATl-2bIily8w90J:-NC4DEh39UzUbJ6Qqpc2:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/91b3cf84da981e86a370513cdd122cf74b4f8ca5/CI-Examples/ra-tls-secret-prov/secret_prov_pf/client.manifest.template#L28)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`libos/src/fs/etc/fs.c` line 36 at r13](https://reviewable.io/reviews/gramineproject/gramine/889#-NC27hH43H8KRsrytLcN:-NC4DK-j9bCsbk5LioxO:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/91b3cf84da981e86a370513cdd122cf74b4f8ca5/libos/src/fs/etc/fs.c#L36)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

+1, let's make it two variables (`size` as before and a new one `space_left`)
</blockquote></details>

Done.
___
*[`libos/src/fs/etc/fs.c` line 38 at r13](https://reviewable.io/reviews/gramineproject/gramine/889#-NC27kbK4o0WUZSzA98Z:-NC4DLEh5FQsEEEUG1q-:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/91b3cf84da981e86a370513cdd122cf74b4f8ca5/libos/src/fs/etc/fs.c#L38)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-09-16 08:13 UTC, dimakuv requested changes
> Reviewed 5 of 5 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/889)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @oshogbo)

___
*[`CI-Examples/python/python.manifest.template` line 29 at r14](https://reviewable.io/reviews/gramineproject/gramine/889#-NC4LVvLCx9SJ_xpYvwU:-NC4LVvLCx9SJ_xpYvwV:b57i62p) ([raw file](https://github.com/gramineproject/gramine/blob/6e6d706e0f4edf9b3973ad00ea866caaa573bcd3/CI-Examples/python/python.manifest.template#L29)):*
> ```
> sgx.enclave_size = "512M"
> sys.stack.size = "2M"
> sys.emulate_etc_files = true
> ```

Oops, forgot to mark this one. Could you move these two `sys.` options in a separate part?


<!-- Sent from Reviewable.io -->

2022-09-16 08:28 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/889)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)



<!-- Sent from Reviewable.io -->

2022-09-16 10:12 UTC, mkow approved these changes
> Reviewed 5 of 5 files at r14, 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/889)* status: all files reviewed, 3 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)



<!-- Sent from Reviewable.io -->

2022-09-16 10:35 UTC, boryspoplawski approved these changes
> Reviewed 5 of 5 files at r14, 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/889)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2022-09-16 13:08 UTC, mkow requested changes
> Reviewed 11 of 11 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/889)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "squash! " found in commit messages' one-liners (waiting on @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/889#-NC5OiAVDFjS2gDA_0sM:-NC5OiAW91utrPU66Mo6:b9t2w37) (no related file):*
You kept `g_pal_public_state->emulate_etc_files`, was this intentional?

___


<!-- Sent from Reviewable.io -->

2022-09-16 13:17 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/889)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "squash! " found in commit messages' one-liners (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/889#-NC5OiAVDFjS2gDA_0sM:-NC5Q_1g2Gs4nyorVCWm:bvk4dd5) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

You kept `g_pal_public_state->emulate_etc_files`, was this intentional?
</blockquote></details>

No I have changed it to `extra_runtime_domain_names_conf`. Where you see `emulate_etc_files` ?

___
___
*[`CI-Examples/python/python.manifest.template` line 29 at r14](https://reviewable.io/reviews/gramineproject/gramine/889#-NC4LVvLCx9SJ_xpYvwU:-NC4NgxjEiUGkC7RLVtp:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/6e6d706e0f4edf9b3973ad00ea866caaa573bcd3/CI-Examples/python/python.manifest.template#L29)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Oops, forgot to mark this one. Could you move these two `sys.` options in a separate part?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-09-16 13:20 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/889)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "squash! " found in commit messages' one-liners

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/889#-NC5OiAVDFjS2gDA_0sM:-NC5SAxf0z0dfMWOi2Un:bsf2v1) (no related file):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

No I have changed it to `extra_runtime_domain_names_conf`. Where you see `emulate_etc_files` ?
</blockquote></details>

Interesting, seems like some caching problem in my editor, refreshing the cache fixed the search results :)

___


<!-- Sent from Reviewable.io -->

2022-09-16 13:45 UTC, boryspoplawski requested changes
> Reviewed 11 of 11 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/889)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "squash! " found in commit messages' one-liners (waiting on @oshogbo)

___
*[`pal/src/host/linux-sgx/pal_main.c` line 329 at r16](https://reviewable.io/reviews/gramineproject/gramine/889#-NC5XVTZAXoy5UcIyH01:-NC5XVTZAXoy5UcIyH02:b-vexecf) ([raw file](https://github.com/gramineproject/gramine/blob/08ad250cadf504c910381d61983ef52d76c0e9bb/pal/src/host/linux-sgx/pal_main.c#L329)):*
> ```C
> }
> 
> static int import_and_init_extra_runtime(struct pal_dns_host_conf* uptr_dns_conf) {
> ```

As previously, this is to broad, needs more specification (e.g. include `domain names` in the name)
___
*[`pal/src/host/linux-sgx/pal_main.c` line 778 at r16](https://reviewable.io/reviews/gramineproject/gramine/889#-NC5XnEz6tfAIICQdkuH:-NC5XnEz6tfAIICQdkuI:b-gj3cdp) ([raw file](https://github.com/gramineproject/gramine/blob/08ad250cadf504c910381d61983ef52d76c0e9bb/pal/src/host/linux-sgx/pal_main.c#L778)):*
> ```C
>     }
> 
>     /* Get host information for extra runtimes configuration only for the first process.
> ```

This sentence gives 0 information (after you removed "etc emulation"), what's the point of it


<!-- Sent from Reviewable.io -->

2022-09-16 13:54 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/889)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "squash! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[`pal/src/host/linux-sgx/pal_main.c` line 329 at r16](https://reviewable.io/reviews/gramineproject/gramine/889#-NC5XVTZAXoy5UcIyH01:-NC5ZxOo9DabzTg4T5gz:bjvorhk) ([raw file](https://github.com/gramineproject/gramine/blob/08ad250cadf504c910381d61983ef52d76c0e9bb/pal/src/host/linux-sgx/pal_main.c#L329)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

As previously, this is to broad, needs more specification (e.g. include `domain names` in the name)
</blockquote></details>

It is broad as I assumed we might want to have one function which take care of all extra runtimes, but I'm not so sure about this.
___
*[`pal/src/host/linux-sgx/pal_main.c` line 778 at r16](https://reviewable.io/reviews/gramineproject/gramine/889#-NC5XnEz6tfAIICQdkuH:-NC5Zqsd6sM9A6DTpvp-:b-vdpox9) ([raw file](https://github.com/gramineproject/gramine/blob/08ad250cadf504c910381d61983ef52d76c0e9bb/pal/src/host/linux-sgx/pal_main.c#L778)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This sentence gives 0 information (after you removed "etc emulation"), what's the point of it
</blockquote></details>

I assume that the "etc emulation" is know a part of the extra runtime features not a essential key here.


<!-- Sent from Reviewable.io -->

2022-09-16 13:58 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/889)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "squash! " found in commit messages' one-liners (waiting on @oshogbo)

___
*[`pal/src/host/linux-sgx/pal_main.c` line 329 at r16](https://reviewable.io/reviews/gramineproject/gramine/889#-NC5XVTZAXoy5UcIyH01:-NC5_YSB014wXkID_VK5:bfnhe8r) ([raw file](https://github.com/gramineproject/gramine/blob/08ad250cadf504c910381d61983ef52d76c0e9bb/pal/src/host/linux-sgx/pal_main.c#L329)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

It is broad as I assumed we might want to have one function which take care of all extra runtimes, but I'm not so sure about this.
</blockquote></details>

But what runtimes? We have nothing atm and no plans (at least not formulated concretely) of adding anything more (than network/dn conf).

Besides, this sounds like you would be importing some language runtime, whatever that would mean.
___
*[`pal/src/host/linux-sgx/pal_main.c` line 778 at r16](https://reviewable.io/reviews/gramineproject/gramine/889#-NC5XnEz6tfAIICQdkuH:-NC5_owE8I0I9fw8x2ER:b5rba04) ([raw file](https://github.com/gramineproject/gramine/blob/08ad250cadf504c910381d61983ef52d76c0e9bb/pal/src/host/linux-sgx/pal_main.c#L778)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

I assume that the "etc emulation" is know a part of the extra runtime features not a essential key here.
</blockquote></details>

But this sentence is basically "we do stuff" i.e. it doesn't explain anything.


<!-- Sent from Reviewable.io -->

2022-09-16 14:19 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/889)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "squash! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[`pal/src/host/linux-sgx/pal_main.c` line 329 at r16](https://reviewable.io/reviews/gramineproject/gramine/889#-NC5XVTZAXoy5UcIyH01:-NC5eT432AeseaG4MJeQ:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/08ad250cadf504c910381d61983ef52d76c0e9bb/pal/src/host/linux-sgx/pal_main.c#L329)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

But what runtimes? We have nothing atm and no plans (at least not formulated concretely) of adding anything more (than network/dn conf).

Besides, this sounds like you would be importing some language runtime, whatever that would mean.
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/pal_main.c` line 778 at r16](https://reviewable.io/reviews/gramineproject/gramine/889#-NC5XnEz6tfAIICQdkuH:-NC5eTVU0tftDnotCmzr:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/08ad250cadf504c910381d61983ef52d76c0e9bb/pal/src/host/linux-sgx/pal_main.c#L778)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

But this sentence is basically "we do stuff" i.e. it doesn't explain anything.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-09-16 14:37 UTC, boryspoplawski submitted a review, later dismissed
> Reviewed 1 of 1 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/889)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2022-09-16 20:35 UTC, dimakuv approved these changes
> Reviewed 10 of 11 files at r16, 1 of 1 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/889)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2022-09-18 15:05 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/889)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2022-09-18 18:49 UTC, mkow approved these changes
> Reviewed 2 of 2 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/889)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2022-09-18 20:26 UTC, boryspoplawski requested changes
> Reviewed 2 of 2 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/889)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @oshogbo)

___
*[`-- commits` line 2 at r18](https://reviewable.io/reviews/gramineproject/gramine/889#-NCHGrw3Ca1phsSFCjim):*
1. This one liner is too long
2. `/etc/resolv.conf`


<!-- Sent from Reviewable.io -->

2022-09-19 09:54 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/889)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

___
*[`-- commits` line 2 at r18](https://reviewable.io/reviews/gramineproject/gramine/889#-NCHGrw3Ca1phsSFCjim):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

1. This one liner is too long
2. `/etc/resolv.conf`
</blockquote></details>

This information in first line was requested by @dimakuv, and I don't think we can fit all this information without breaking line length.


<!-- Sent from Reviewable.io -->

2022-09-19 10:49 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/889)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

___
*[`-- commits` line 2 at r18](https://reviewable.io/reviews/gramineproject/gramine/889#-NCHGrw3Ca1phsSFCjim):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

This information in first line was requested by @dimakuv, and I don't think we can fit all this information without breaking line length.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-09-19 10:50 UTC, dimakuv submitted a review, later dismissed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/889)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski)

___
*[`-- commits` line 2 at r18](https://reviewable.io/reviews/gramineproject/gramine/889#-NCHGrw3Ca1phsSFCjim):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

@oshogbo Let's remove `(currently only 'resolv.conf')` phrase. And add the sentence to the commit message at the end, smth like this:
```
... a pseudo file (using pseudofs filesystem). Currently only
`/etc/resolv.conf` is introduced.
```

UPDATE: Mariusz updated before I finished this comment. I guess I'm fine with this version too.


<!-- Sent from Reviewable.io -->

2022-09-19 11:11 UTC, boryspoplawski approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/889)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`-- commits` line 2 at r18](https://reviewable.io/reviews/gramineproject/gramine/889#-NCHGrw3Ca1phsSFCjim):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@oshogbo Let's remove `(currently only 'resolv.conf')` phrase. And add the sentence to the commit message at the end, smth like this:
```
... a pseudo file (using pseudofs filesystem). Currently only
`/etc/resolv.conf` is introduced.
```

UPDATE: Mariusz updated before I finished this comment. I guess I'm fine with this version too.
</blockquote></details>

I would prefer to add the sentence mentioned by @dimakuv but not blocking.


<!-- Sent from Reviewable.io -->

2022-09-19 11:13 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/889)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2022-09-19 11:17 UTC, boryspoplawski approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/889)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2022-09-19 11:25 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/889)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-09-19 14:57 UTC, merged