[Doc] Fix minor issue for cloud deployment
gramineproject/gramine pull request #890
Opened 2022-09-06 19:56 UTC by enedellec

Running  sudo apt-get update is mandatory for both Ubuntu 18.04 and Ubuntu 20.04, and not for Ubuntu 18.04 only

2022-09-07 07:00 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/890)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @enedellec)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/890#-NBLjo9t20bTjuwlEN0k:-NBLjo9t20bTjuwlEN0l:b-27k7r2) (no related file):*
For the future: please do not push the changes from the `master` branch of your fork. The classic flow is to create a branch in your fork, and then push it here. Please see also https://gramine.readthedocs.io/en/latest/devel/contributing.html#branch-names

___
___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/890#-NBLjVQ5A0reX8YqHd_8):*
Could you please update this commit message with your Signed-Off-By? You can use `git commit --amend --signoff` for this. (But you'll need a proper GitHub name + email for this)


<!-- Sent from Reviewable.io -->

2022-09-07 19:52 UTC, enedellec commented
Sorry for the mistake regarding the rules for the branch, I will do better next time.
I rebased in order to add a "Signed-Off-By" in the commit message, as requested, and forced push on github.

2022-09-08 07:01 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/890)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @enedellec)



<!-- Sent from Reviewable.io -->

2022-09-08 07:01 UTC, dimakuv commented
Jenkins, test this please

2022-09-08 20:41 UTC, enedellec commented
Sorry, for the potential stupid question... Do you expect a specific action from my side?

2022-09-09 06:38 UTC, dimakuv commented
@enedellec You don't have to do anything. We're waiting for another reviewer to show up. But Gramine reviewers/developers have busy weeks currently, and this PR is low priority. (Each PR must be reviewed by at least two people.)

2022-09-14 10:50 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/890)* status: all files reviewed, 3 unresolved discussions (waiting on @enedellec)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/gramineproject/gramine/890#-NBvbI6k4D8KhCOiIAsl):*
(see https://gramine.readthedocs.io/en/latest/devel/contributing.html)



_Suggestion:_
```
[Docs]
```
___
*[`-- commits` line 4 at r2](https://reviewable.io/reviews/gramineproject/gramine/890#-NBvbSTl22HlV_HhsS42):*
This should be hard-wrapped, see https://commit.style.


<!-- Sent from Reviewable.io -->

2022-09-14 10:58 UTC, boryspoplawski requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/890)* status: all files reviewed, 4 unresolved discussions (waiting on @enedellec)

___
*[`Documentation/cloud-deployment.rst` line 45 at r2](https://reviewable.io/reviews/gramineproject/gramine/890#-NBvdWfy37_9RaU8yiIz:-NBvdWfzBdfnewGTUH_Y:b-49a25j) ([raw file](https://github.com/gramineproject/gramine/blob/695a65ab345e8d266e5e3e0c56b3e5fdcff7a418/Documentation/cloud-deployment.rst#L45)):*
> ```reStructuredText
> Install Gramine (in-kernel driver version) on Ubuntu 20.04::
> 
>    sudo apt-get update
> ```

Shouldn't this be actually part of adding the repos above, not part of installing Gramine?


<!-- Sent from Reviewable.io -->

2022-09-14 11:02 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/890)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski and @enedellec)

___
*[`Documentation/cloud-deployment.rst` line 45 at r2](https://reviewable.io/reviews/gramineproject/gramine/890#-NBvdWfy37_9RaU8yiIz:-NBveSnuEFFe4KI1Gbml:bfy4g4o) ([raw file](https://github.com/gramineproject/gramine/blob/695a65ab345e8d266e5e3e0c56b3e5fdcff7a418/Documentation/cloud-deployment.rst#L45)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Shouldn't this be actually part of adding the repos above, not part of installing Gramine?
</blockquote></details>

+1, I also think it makes more sense there.


<!-- Sent from Reviewable.io -->

2022-09-14 11:22 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/890)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski and @enedellec)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/890#-NBvis-C9fl4lnF2gocu:-NBvis-C9fl4lnF2gocv:b-olmk2x) (no related file):*
@enedellec Could you fix the comments from reviewers? Please use `git fixup` flow for new commits, and please use Reviewable to reply with "Done" or ask questions.

___


<!-- Sent from Reviewable.io -->

2022-09-18 19:40 UTC, enedellec reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/890)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski, @enedellec, and @mkow)

___
*[`Documentation/cloud-deployment.rst` line 45 at r2](https://reviewable.io/reviews/gramineproject/gramine/890#-NBvdWfy37_9RaU8yiIz:-NCH5j3HAWgF5fjzOZBe:b-a8hww9) ([raw file](https://github.com/gramineproject/gramine/blob/695a65ab345e8d266e5e3e0c56b3e5fdcff7a418/Documentation/cloud-deployment.rst#L45)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

+1, I also think it makes more sense there.
</blockquote></details>

Do you mean that you want that I move the "sudo apt-get update" command above in my next commit? Just below the line starting with "# (if you're on Ubuntu 18.04, [snip]", instead of having that line in both ubuntu 18.04 & ubuntu 20.4 sections?


<!-- Sent from Reviewable.io -->

2022-09-20 06:50 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/890)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski, @enedellec, and @mkow)

___
*[`Documentation/cloud-deployment.rst` line 45 at r2](https://reviewable.io/reviews/gramineproject/gramine/890#-NBvdWfy37_9RaU8yiIz:-NCOdy-RAmMaAd4M_vbQ:b5yw482) ([raw file](https://github.com/gramineproject/gramine/blob/695a65ab345e8d266e5e3e0c56b3e5fdcff7a418/Documentation/cloud-deployment.rst#L45)):*
<details><summary><i>Previously, enedellec (Erwan NEDELLEC) wrote…</i></summary><blockquote>

Do you mean that you want that I move the "sudo apt-get update" command above in my next commit? Just below the line starting with "# (if you're on Ubuntu 18.04, [snip]", instead of having that line in both ubuntu 18.04 & ubuntu 20.4 sections?
</blockquote></details>

@enedellec I would recommend to add a new paragraph alltogether, like this:
```
...
Add Intel SGX repository::

   curl -fsSL https://download.01.org/intel-sgx/sgx_repo/ubuntu/intel-sgx-deb.key | sudo apt-key add -
   echo 'deb [arch=amd64] https://download.01.org/intel-sgx/sgx_repo/ubuntu focal main' | sudo tee /etc/apt/sources.list.d/intel-sgx.list
   # (if you're on Ubuntu 18.04, write "bionic" instead of "focal" above)

Fetch the latest versions of package lists from the newly added repos::

   sudo apt-get update

Install Gramine (in-kernel driver version) on Ubuntu 20.04::

   sudo apt-get install gramine
...
```

Notice the new `Fetch the latest versions...` paragraph with the corresponding code snippet that I added.


<!-- Sent from Reviewable.io -->

2022-09-21 19:27 UTC, enedellec reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/890)* status: 0 of 1 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski, @dimakuv, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/890#-NBvis-C9fl4lnF2gocu:-NCWW63E3IqQlGNzcWEc:b-896fix) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@enedellec Could you fix the comments from reviewers? Please use `git fixup` flow for new commits, and please use Reviewable to reply with "Done" or ask questions.
</blockquote></details>

Done.

___
___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/gramineproject/gramine/890#-NBvbI6k4D8KhCOiIAsl):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

(see https://gramine.readthedocs.io/en/latest/devel/contributing.html)
</blockquote></details>

Done.
___
*[`-- commits` line 4 at r2](https://reviewable.io/reviews/gramineproject/gramine/890#-NBvbSTl22HlV_HhsS42):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This should be hard-wrapped, see https://commit.style.
</blockquote></details>

Done.
___
*[`Documentation/cloud-deployment.rst` line 45 at r2](https://reviewable.io/reviews/gramineproject/gramine/890#-NBvdWfy37_9RaU8yiIz:-NCWWH2U98eU2V---VTZ:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/695a65ab345e8d266e5e3e0c56b3e5fdcff7a418/Documentation/cloud-deployment.rst#L45)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@enedellec I would recommend to add a new paragraph alltogether, like this:
```
...
Add Intel SGX repository::

   curl -fsSL https://download.01.org/intel-sgx/sgx_repo/ubuntu/intel-sgx-deb.key | sudo apt-key add -
   echo 'deb [arch=amd64] https://download.01.org/intel-sgx/sgx_repo/ubuntu focal main' | sudo tee /etc/apt/sources.list.d/intel-sgx.list
   # (if you're on Ubuntu 18.04, write "bionic" instead of "focal" above)

Fetch the latest versions of package lists from the newly added repos::

   sudo apt-get update

Install Gramine (in-kernel driver version) on Ubuntu 20.04::

   sudo apt-get install gramine
...
```

Notice the new `Fetch the latest versions...` paragraph with the corresponding code snippet that I added.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-09-22 09:35 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/890)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski and @mkow)



<!-- Sent from Reviewable.io -->

2022-09-22 09:36 UTC, dimakuv commented
Jenkins, test this please

2022-09-25 19:29 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/890)* status: all files reviewed, 3 unresolved discussions (waiting on @boryspoplawski)



<!-- Sent from Reviewable.io -->

2022-09-25 19:44 UTC, boryspoplawski requested changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/890)* status: all files reviewed, 1 unresolved discussion (waiting on @enedellec)

___
*[`-- commits` line 4 at r3](https://reviewable.io/reviews/gramineproject/gramine/890#-NCqASzGCYflUeULc0Gw):*
NP: this shouldn't be indented 


<!-- Sent from Reviewable.io -->

2022-09-26 07:31 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/890)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski)

___
*[`-- commits` line 4 at r3](https://reviewable.io/reviews/gramineproject/gramine/890#-NCqASzGCYflUeULc0Gw):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I will fix it (and mend the text slightly) during final rebase.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2022-09-26 07:34 UTC, dimakuv commented
Jenkins, test this please

2022-09-26 08:29 UTC, dimakuv commented
Jenkins, retest Jenkins-20.04 please (`AssertionError: Command ['gramine-direct', 'fcntl14'] timed out after 60 s`, unrelated)

2022-09-26 11:11 UTC, boryspoplawski approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/890)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-09-27 12:24 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/890)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-09-27 17:23 UTC, dimakuv commented
Sorry @enedellec. In the meantime, we released v1.3 which requires significant changes to our documentation on packaging. So I created https://github.com/gramineproject/gramine/pull/935 which supersedes this PR. So I'm closing your PR now.

2022-09-27 17:23 UTC, closed without merging

2022-09-28 18:31 UTC, enedellec commented
No problem, that's fine.