[PAL/Linux-SGX] Mitigate CVE-2022-21233 aka INTEL-SA-00657
gramineproject/gramine pull request #894
Opened 2022-09-07 20:19 UTC by boryspoplawski

## Description of the changes 
If malicious host maps APIC registers in some untrusted memory (MMIO) and this memory is subsequently read by the enclave (e.g. when reading some results of an ocall) such read can potentially return some stale, enclave-originated data. Naturally aligned 8-byte reads are not affected by this vulnerability, so as software mitigation, this commit makes all untrusted memory accesses 8-byte wide and naturally aligned.

As a side effect the exitless ocalls feature becomes potentially insecure. It uses untrusted memory in some complex manner, which we did not bother changing for now, as the feature is not widely used.

Fixes #846

2022-09-07 22:05 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/894)* status: 0 of 13 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/894#-NBOz5JO5vhTIxi9VB3E:-NBOz5JO5vhTIxi9VB3F:b-z6wrsq) (no related file):*
I've debugged the failures, but still working on a fix

___


<!-- Sent from Reviewable.io -->

2022-09-08 04:26 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/894)* status: 0 of 13 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

___
*[`pal/src/host/linux-sgx/enclave_framework.c` line 153 at r2](https://reviewable.io/reviews/gramineproject/gramine/894#-NBQKOtM85IFSiF-wzVC:-NBQKOtM85IFSiF-wzVD:bw45wu9) ([raw file](https://github.com/gramineproject/gramine/blob/9fc3749bc6762a54be49df76883bd5d37ee8d956/pal/src/host/linux-sgx/enclave_framework.c#L153)):*
> ```C
> 
>     /*
>      * This should be simple `memcpy(ptr, uptr, size)`, but CVE-2022-21233 (INTEL-SA-00657).
> ```

Sentence not complete?



_Code quote:_
```C
but CVE-2022-21233 (INTEL-SA-00657)
```
___
*[`pal/src/host/linux-sgx/enclave_framework.c` line 188 at r2](https://reviewable.io/reviews/gramineproject/gramine/894#-NBQKVqjDSlcEI7WDdmP:-NBQKVqjDSlcEI7WDdmQ:b-8lxu07) ([raw file](https://github.com/gramineproject/gramine/blob/9fc3749bc6762a54be49df76883bd5d37ee8d956/pal/src/host/linux-sgx/enclave_framework.c#L188)):*
> ```C
>     if (suffix_misalignment) {
>         /* End of the copied range is misaligned. */
>         char suffix_val[8] = { 0 };
> ```

Q: is it worth having `prefix_val` and `suffix_val` in one buffer and saving one `memcpy()`?



_Code quote:_
```C
char suffix_val[8] = { 0 }
```
___
*[`pal/src/host/linux-sgx/pal_main.c` line 62 at r2](https://reviewable.io/reviews/gramineproject/gramine/894#-NBQH6R45J7_tCImLzNK:-NBQH6R45J7_tCImLzNL:bjz81tt) ([raw file](https://github.com/gramineproject/gramine/blob/9fc3749bc6762a54be49df76883bd5d37ee8d956/pal/src/host/linux-sgx/pal_main.c#L62)):*
> ```C
>     }
> 
>     if (!sgx_is_valid_untrusted_ptr(untrusted_rpc_queue, sizeof(*g_rpc_queue),
> ```

Q: should we make the check part earlier, e.g., before copying to the trusted rather than in `pal_linux_main()`, 
___
*[`pal/src/host/linux-sgx/pal_rpc_queue.h` line 5 at r2](https://reviewable.io/reviews/gramineproject/gramine/894#-NBQHzlQ1gk_reXKFfz_:-NBQHzlQ1gk_reXKFfza:bnpt6z3) ([raw file](https://github.com/gramineproject/gramine/blob/9fc3749bc6762a54be49df76883bd5d37ee8d956/pal/src/host/linux-sgx/pal_rpc_queue.h#L5)):*
> ```objc
>  * functions, like `spinlock_lock`, on that memory. Since we have to use 8-byte naturally aligned
>  * memory accesses to mitigate CVE-2022-21233, we must mark this feature as insecure until we
>  * rewrite it or that CVE is fully fixed in hardware or microcode.
> ```

The full fix in HW or ucode would be not exposing any stale data in XAPIC or disabling xAPIC completely (which maybe quite long-term). Then this "until" does not sound that useful in such case. Also, if fully fixed in HW or ucode, we'd also revert all our SW mitigations introduced in this PR.



_Code quote:_
```objc
or that CVE is fully fixed in hardware or microcode
```


<!-- Sent from Reviewable.io -->

2022-09-08 04:34 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/894)* status: 0 of 13 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

___
*[`-- commits` line 7 at r2](https://reviewable.io/reviews/gramineproject/gramine/894#-NBQMGuKAjJxF41issb1):*
Maybe it's better to also mention a subsequent unintentional write may leak that data, cited from the https://www.intel.com/content/www/us/en/developer/articles/technical/software-security-guidance/advisory-guidance/stale-data-read-from-xapic.html:
`The enclave may then unintentionally perform an operation that could allow an attacker to infer this data.`



_Code quote:_
```
  some results of an ocall) such read can potentially return some stale,
  enclave-originated data. Naturally aligned 8-byte reads are not affected
```
___
*[`-- commits` line 14 at r2](https://reviewable.io/reviews/gramineproject/gramine/894#-NBQN3XQ7n0v1wJw-o2O):*
Should we put the CVE and SA reference links here?


<!-- Sent from Reviewable.io -->

2022-09-08 08:19 UTC, dimakuv requested changes
> Reviewed 12 of 13 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/894)* status: all files reviewed, 15 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski and @kailun-qin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/894#-NBRAHULB_iptDerVpPw:-NBRAHULB_iptDerVpPx:b-q9pjjv) (no related file):*
I guess you made some analysis on the Exitless feature, right? Would be good to post the analysis (even if it was partial) here, in this PR's comments, just for the future reference. Maybe we'll *have to* fix Exitless in the future, and it would be good to have some starting point.

___
___
*[`-- commits` line 7 at r2](https://reviewable.io/reviews/gramineproject/gramine/894#-NBQMGuKAjJxF41issb1):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Maybe it's better to also mention a subsequent unintentional write may leak that data, cited from the https://www.intel.com/content/www/us/en/developer/articles/technical/software-security-guidance/advisory-guidance/stale-data-read-from-xapic.html:
`The enclave may then unintentionally perform an operation that could allow an attacker to infer this data.`
</blockquote></details>

+1, for completeness of description
___
*[`-- commits` line 14 at r2](https://reviewable.io/reviews/gramineproject/gramine/894#-NBQN3XQ7n0v1wJw-o2O):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Should we put the CVE and SA reference links here?
</blockquote></details>

I don't think we need this. We have the CVE and SA numbers in the title of this commit, so people can easily google them.
___
*[`-- commits` line 14 at r2](https://reviewable.io/reviews/gramineproject/gramine/894#-NBQyxVZ6rsuV01PeR1P):*
Maybe we should also have one paragraph that these changes can (will be?) reverted in some distant future, when all CPUs in the wild are patched against this vulnerability? Then e.g. we can move Exitless back to "secure" options.
___
*[`Documentation/manifest-syntax.rst` line 539 at r2](https://reviewable.io/reviews/gramineproject/gramine/894#-NBQzik4ETyJ7gwzf8ZU:-NBQzik4ETyJ7gwzf8ZV:b-8gr430) ([raw file](https://github.com/gramineproject/gramine/blob/9fc3749bc6762a54be49df76883bd5d37ee8d956/Documentation/manifest-syntax.rst#L539)):*
> ```reStructuredText
> 
> This feature is currently marked as insecure, because it reads untrusted memory
> in potentially insecure manner.
> ```

Maybe add `In particular, this feature is succeptible to the CVE-2022-21233 (aka INTEL-SA-00657) vulnerability.`
___
*[`Documentation/performance.rst` line 167 at r2](https://reviewable.io/reviews/gramineproject/gramine/894#-NBQzzEkBmi5Cizhhb6p:-NBQzzEkBmi5Cizhhb6q:b-8gr430) ([raw file](https://github.com/gramineproject/gramine/blob/9fc3749bc6762a54be49df76883bd5d37ee8d956/Documentation/performance.rst#L167)):*
> ```reStructuredText
> 
> Note this feature is currently insecure and not recommended for production
> usage.
> ```

Maybe add `In particular, this feature is succeptible to the CVE-2022-21233 (aka INTEL-SA-00657) vulnerability.`
___
*[`pal/src/host/linux-sgx/enclave_framework.c` line 153 at r2](https://reviewable.io/reviews/gramineproject/gramine/894#-NBQKOtM85IFSiF-wzVC:-NBR35PC6E07PGgNRbf1:bik4if2) ([raw file](https://github.com/gramineproject/gramine/blob/9fc3749bc6762a54be49df76883bd5d37ee8d956/pal/src/host/linux-sgx/enclave_framework.c#L153)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Sentence not complete?
</blockquote></details>

I think this was intended :) I don't mind this shortened sentence, it's clear that it means "but see CVE... for details"
___
*[`pal/src/host/linux-sgx/enclave_framework.c` line 180 at r2](https://reviewable.io/reviews/gramineproject/gramine/894#-NBR5D-sC_a5XMCvIiAK:-NBR5D-sC_a5XMCvIiAL:b2qztu0) ([raw file](https://github.com/gramineproject/gramine/blob/9fc3749bc6762a54be49df76883bd5d37ee8d956/pal/src/host/linux-sgx/enclave_framework.c#L180)):*
> ```C
>     copy_len = size - suffix_misalignment;
>     assert(copy_len % 8 == 0);
>     copy_u64s(ptr, uptr, copy_len / 8);
> ```

At this point, `copy_len` may be `0`. Do we want to move these 4 lines under `if (copy_len) { ... }`?

I know that this doesn't change anything semantically, but it will make more clear that there is such a special case possible ("the size to copy is less than 8 bytes, so we skip the middle logic of this function")
___
*[`pal/src/host/linux-sgx/enclave_framework.c` line 188 at r2](https://reviewable.io/reviews/gramineproject/gramine/894#-NBQKVqjDSlcEI7WDdmP:-NBR6BTxAmsqwQn09EzX:b3tqz0d) ([raw file](https://github.com/gramineproject/gramine/blob/9fc3749bc6762a54be49df76883bd5d37ee8d956/pal/src/host/linux-sgx/enclave_framework.c#L188)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Q: is it worth having `prefix_val` and `suffix_val` in one buffer and saving one `memcpy()`?
</blockquote></details>

I don't understand what @kailun-qin means. I don't see how we can safe one `memcpy()`. All the logic here seems correct and already minimal.
___
*[`pal/src/host/linux-sgx/pal_main.c` line 62 at r2](https://reviewable.io/reviews/gramineproject/gramine/894#-NBQH6R45J7_tCImLzNK:-NBR7Cru5xTQi3EPJr59:bemk6t) ([raw file](https://github.com/gramineproject/gramine/blob/9fc3749bc6762a54be49df76883bd5d37ee8d956/pal/src/host/linux-sgx/pal_main.c#L62)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Q: should we make the check part earlier, e.g., before copying to the trusted rather than in `pal_linux_main()`, 
</blockquote></details>

@kailun-qin I don't see a need for this. Who cares if we copied the "bad" pointer into the enclave? We'll check this "bad" pointer now and we will fail the whole Gramine process if it's really bad.

Also, I'm unclear what you mean by "before copying to the trusted". The only thing that we copy to the trusted enclave memory is the pointer value itself. Gramine never copies the RPC queue itself -- it is always outside of the enclave memory.
___
*[`pal/src/host/linux-sgx/pal_main.c` line 588 at r2](https://reviewable.io/reviews/gramineproject/gramine/894#-NBR7hXCBmVJZ66-hzaW:-NBR7hXD5xPfMt1Z8u7w:b-5zke8k) ([raw file](https://github.com/gramineproject/gramine/blob/9fc3749bc6762a54be49df76883bd5d37ee8d956/pal/src/host/linux-sgx/pal_main.c#L588)):*
> ```C
>     g_pal_common_state.raw_manifest_data = manifest_addr;
>     g_pal_public_state.manifest_root = manifest_root;
> ```

Please remove one empty line
___
*[`pal/src/host/linux-sgx/pal_main.c` line 592 at r2](https://reviewable.io/reviews/gramineproject/gramine/894#-NBR97pF2aO0VLbe8RRh:-NBR97pF2aO0VLbe8RRi:bd245wh) ([raw file](https://github.com/gramineproject/gramine/blob/9fc3749bc6762a54be49df76883bd5d37ee8d956/pal/src/host/linux-sgx/pal_main.c#L592)):*
> ```C
>     int64_t rpc_thread_num;
>     ret = toml_int_in(g_pal_public_state.manifest_root, "sgx.insecure__rpc_thread_num",
>                       /*defaultval=*/0, &rpc_thread_num);
> ```

Looks like you added this read-from-manifest to prevent the malicious host from lying about the RPC queue? This is good, we should have had it before, but we missed this...
___
*[`pal/src/host/linux-sgx/pal_rpc_queue.h` line 2 at r2](https://reviewable.io/reviews/gramineproject/gramine/894#-NBR9kWN8bmOzJ88gU6Q:-NBR9kWO0f2gEzKNdnT1:btmi0uf) ([raw file](https://github.com/gramineproject/gramine/blob/9fc3749bc6762a54be49df76883bd5d37ee8d956/pal/src/host/linux-sgx/pal_rpc_queue.h#L2)):*
> ```objc
> /*
>  * FIXME: This feature is currently insecure. It keeps most object in untrusted memory and uses some
> ```

`objects`
___
*[`pal/src/host/linux-sgx/pal_rpc_queue.h` line 4 at r2](https://reviewable.io/re [...]

2022-09-08 09:01 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/894)* status: all files reviewed, 13 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski, @dimakuv, and @kailun-qin)

___
*[`-- commits` line 14 at r2](https://reviewable.io/reviews/gramineproject/gramine/894#-NBQN3XQ7n0v1wJw-o2O):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't think we need this. We have the CVE and SA numbers in the title of this commit, so people can easily google them.
</blockquote></details>

Yeah, make sense, thanks!
___
*[`pal/src/host/linux-sgx/enclave_framework.c` line 153 at r2](https://reviewable.io/reviews/gramineproject/gramine/894#-NBQKOtM85IFSiF-wzVC:-NBRI77f1bVJGV0Tiad4:b-owq44j) ([raw file](https://github.com/gramineproject/gramine/blob/9fc3749bc6762a54be49df76883bd5d37ee8d956/pal/src/host/linux-sgx/enclave_framework.c#L153)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I think this was intended :) I don't mind this shortened sentence, it's clear that it means "but see CVE... for details"
</blockquote></details>

OK ;) I'm fine w/ it.
___
*[`pal/src/host/linux-sgx/enclave_framework.c` line 188 at r2](https://reviewable.io/reviews/gramineproject/gramine/894#-NBQKVqjDSlcEI7WDdmP:-NBRIAeC-JuiuUJ6ZFei:bmjjddj) ([raw file](https://github.com/gramineproject/gramine/blob/9fc3749bc6762a54be49df76883bd5d37ee8d956/pal/src/host/linux-sgx/enclave_framework.c#L188)):*
> I don't understand what @kailun-qin means. I don't see how we can safe one memcpy(). All the logic here seems correct and already minimal.

I was just thinking about having a `buf[16] = { 0 }` and having both `prefix` and `suffix` (or only one of them) copy into it, and then having one single `memcpy()` at the end.
___
*[`pal/src/host/linux-sgx/pal_main.c` line 62 at r2](https://reviewable.io/reviews/gramineproject/gramine/894#-NBQH6R45J7_tCImLzNK:-NBRJB2_BRIW3hmhbtZb:b8de42r) ([raw file](https://github.com/gramineproject/gramine/blob/9fc3749bc6762a54be49df76883bd5d37ee8d956/pal/src/host/linux-sgx/pal_main.c#L62)):*
> @kailun-qin I don't see a need for this. Who cares if we copied the "bad" pointer into the enclave? We'll check this "bad" pointer now and we will fail the whole Gramine process if it's really bad.

OK, make sense to me.

> Also, I'm unclear what you mean by "before copying to the trusted".

I was just thinking about moving this check before: https://github.com/gramineproject/gramine/blob/9fc3749bc6762a54be49df76883bd5d37ee8d956/pal/src/host/linux-sgx/enclave_ecalls.c#L97

as it seems that we had some assumptions here (though not exactly the same purpose):
https://github.com/gramineproject/gramine/blob/9fc3749bc6762a54be49df76883bd5d37ee8d956/pal/src/host/linux-sgx/enclave_framework.c#L145.


<!-- Sent from Reviewable.io -->

2022-09-08 09:10 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/894)* status: all files reviewed, 13 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski, @dimakuv, and @kailun-qin)

___
*[`pal/src/host/linux-sgx/enclave_framework.c` line 188 at r2](https://reviewable.io/reviews/gramineproject/gramine/894#-NBQKVqjDSlcEI7WDdmP:-NBRLyaR2f8K3ZzHFJAz:bfys4x3) ([raw file](https://github.com/gramineproject/gramine/blob/9fc3749bc6762a54be49df76883bd5d37ee8d956/pal/src/host/linux-sgx/enclave_framework.c#L188)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

> I don't understand what @kailun-qin means. I don't see how we can safe one memcpy(). All the logic here seems correct and already minimal.

I was just thinking about having a `buf[16] = { 0 }` and having both `prefix` and `suffix` (or only one of them) copy into it, and then having one single `memcpy()` at the end.
</blockquote></details>

Update: just rethink more thoroughly, yep, the logic here seems already minimal... Excuse me for the distraction here.


<!-- Sent from Reviewable.io -->

2022-09-08 10:35 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/894)* status: all files reviewed, 11 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @kailun-qin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/894#-NBRAHULB_iptDerVpPw:-NBRVqNHEIeGoMCd0P-D:b-r9cyj0) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I guess you made some analysis on the Exitless feature, right? Would be good to post the analysis (even if it was partial) here, in this PR's comments, just for the future reference. Maybe we'll *have to* fix Exitless in the future, and it would be good to have some starting point.
</blockquote></details>

I just looked at the code, if that's what you mean.
It touches untrusted memory in many places, most of them are not marked as such and hidden behind functions. So I guess there are two cases:
1) Normal untrusted memory access - would have to be changed to copying the value to local variable and only then using it, I guess. Doable, but very annoying.
2) Spinlocks on untrusted memory - I think easiest way to solve it would be to inline all of their code, change the underlying word to 64bits (it's `uint32_t` now) and make sure it's always 8bytes aligned.

Also there are other possible issues, e.g. some values are read multiple times and they are expected to stay the same. In the one place I looked at it was most likely fine (i.e. didn't result in any vulnerabilities), but I think we should just look closely at all of it, once we decide to bring it back. To speed things up I did not bother for now, because I got a green light on marking this insecure (at least temporarily). I think it's all fine, but wouldn't hurt to verify.

___
___
*[`-- commits` line 7 at r2](https://reviewable.io/reviews/gramineproject/gramine/894#-NBQMGuKAjJxF41issb1):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

+1, for completeness of description
</blockquote></details>

How about I add a sentence between these two (i.e. `...enclave-originated data. (here goes new sentence). Naturally aligned...`):
`This data may then be unintentionally leaked by the enclave, e.g. written back to untrusted part or handled in non-side-channel-secure manner.`
___
*[`-- commits` line 14 at r2](https://reviewable.io/reviews/gramineproject/gramine/894#-NBQN3XQ7n0v1wJw-o2O):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Yeah, make sense, thanks!
</blockquote></details>

Yes, I intentionally didn't want to put links, because they often get stale.
___
*[`-- commits` line 14 at r2](https://reviewable.io/reviews/gramineproject/gramine/894#-NBQyxVZ6rsuV01PeR1P):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Maybe we should also have one paragraph that these changes can (will be?) reverted in some distant future, when all CPUs in the wild are patched against this vulnerability? Then e.g. we can move Exitless back to "secure" options.
</blockquote></details>

Well, if somebody wants this feature, then we should fix it much sooner. If nobody uses it, then there is no point and we could completely deprecate it?
___
*[`Documentation/manifest-syntax.rst` line 539 at r2](https://reviewable.io/reviews/gramineproject/gramine/894#-NBQzik4ETyJ7gwzf8ZU:-NBRaxGzE1b8GB2kZzEi:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9fc3749bc6762a54be49df76883bd5d37ee8d956/Documentation/manifest-syntax.rst#L539)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Maybe add `In particular, this feature is succeptible to the CVE-2022-21233 (aka INTEL-SA-00657) vulnerability.`
</blockquote></details>

Done.
___
*[`Documentation/performance.rst` line 167 at r2](https://reviewable.io/reviews/gramineproject/gramine/894#-NBQzzEkBmi5Cizhhb6p:-NBRbDJo5Dvp0H-KNJTL:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9fc3749bc6762a54be49df76883bd5d37ee8d956/Documentation/performance.rst#L167)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Maybe add `In particular, this feature is succeptible to the CVE-2022-21233 (aka INTEL-SA-00657) vulnerability.`
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/enclave_framework.c` line 153 at r2](https://reviewable.io/reviews/gramineproject/gramine/894#-NBQKOtM85IFSiF-wzVC:-NBRbH-aEkgRPFF4wk-H:b-3pto2a) ([raw file](https://github.com/gramineproject/gramine/blob/9fc3749bc6762a54be49df76883bd5d37ee8d956/pal/src/host/linux-sgx/enclave_framework.c#L153)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

OK ;) I'm fine w/ it.
</blockquote></details>

Yes, this was intended
___
*[`pal/src/host/linux-sgx/enclave_framework.c` line 180 at r2](https://reviewable.io/reviews/gramineproject/gramine/894#-NBR5D-sC_a5XMCvIiAK:-NBRblG-0UJl-FkC0Hqd:b-k6yafu) ([raw file](https://github.com/gramineproject/gramine/blob/9fc3749bc6762a54be49df76883bd5d37ee8d956/pal/src/host/linux-sgx/enclave_framework.c#L180)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

At this point, `copy_len` may be `0`. Do we want to move these 4 lines under `if (copy_len) { ... }`?

I know that this doesn't change anything semantically, but it will make more clear that there is such a special case possible ("the size to copy is less than 8 bytes, so we skip the middle logic of this function")
</blockquote></details>

I don't mind either. This code works correctly for `copy_len == 0` and it's unclear to me which would be faster, an if or couple of adds/subs. So this would be purely visual / for code clarity change.
Let's hear from others which version they would prefer.
___
*[`pal/src/host/linux-sgx/pal_main.c` line 62 at r2](https://reviewable.io/reviews/gramineproject/gramine/894#-NBQH6R45J7_tCImLzNK:-NBRckhs-700IgCJ_lYo:b76rahe) ([raw file](https://github.com/gramineproject/gramine/blob/9fc3749bc6762a54be49df76883bd5d37ee8d956/pal/src/host/linux-sgx/pal_main.c#L62)):*
> I was just thinking about moving this check before: 

How do you check a pointer without actually having it (i.e. copying it into enclave - the pointer, not the underlying object)?

> as it seems that we had some assumptions here (though not exactly the same purpose):

I don't understand your point, this is exactly the same check.
___
*[`pal/src/host/linux-sgx/pal_main.c` line 588 at r2](https://reviewable.io/reviews/gramineproject/gramine/894#-NBR7hXCBmVJZ66-hzaW:-NBRdcwPDWyG4MUrUsIL:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9fc3749bc6762a54be49df76883bd5d37ee8d956/pal/src/host/linux-sgx/pal_main.c#L588)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please remove one empty line
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/pal_main.c` line 592 at r2](https://reviewable.io/reviews/gramineproject/gramine/894#-NBR97pF2aO0VLbe8RRh:-NBRdeoq-pSuywZIazis:b-hx0jjg) ([raw file](https://github.com/gramineproject/gramine/blob/9fc3749bc6762a54be49df76883bd5d37ee8d956/pal/src/host/linux-sgx/pal_main.c#L592)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Looks like you added this read-from-manifest to prevent the malicious host from lying about the RPC queue? This is good, we should have had it before, but we missed this...
</blockquote></details>

Correct. Before it wasn't required per se (assuming the implementation is correct, this could only impact performance), but now this is a must have.
___
*[`pal/src/host/linux-sgx/pal_rpc_queue.h` line 2 at r2](https://reviewable.io/reviews/gramineproject/gramine/894#-NBR9kWN8bmOzJ88gU6Q:-NBRe [...]

2022-09-08 11:14 UTC, dimakuv requested changes
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/894)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @kailun-qin, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/894#-NBRAHULB_iptDerVpPw:-NBRmVrz0lqpo5-YhYdu:b-1xms1w) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I just looked at the code, if that's what you mean.
It touches untrusted memory in many places, most of them are not marked as such and hidden behind functions. So I guess there are two cases:
1) Normal untrusted memory access - would have to be changed to copying the value to local variable and only then using it, I guess. Doable, but very annoying.
2) Spinlocks on untrusted memory - I think easiest way to solve it would be to inline all of their code, change the underlying word to 64bits (it's `uint32_t` now) and make sure it's always 8bytes aligned.

Also there are other possible issues, e.g. some values are read multiple times and they are expected to stay the same. In the one place I looked at it was most likely fine (i.e. didn't result in any vulnerabilities), but I think we should just look closely at all of it, once we decide to bring it back. To speed things up I did not bother for now, because I got a green light on marking this insecure (at least temporarily). I think it's all fine, but wouldn't hurt to verify.
</blockquote></details>

Thank you, this is exactly the analysis I wanted us to capture here.

___
___
*[`-- commits` line 7 at r2](https://reviewable.io/reviews/gramineproject/gramine/894#-NBQMGuKAjJxF41issb1):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

How about I add a sentence between these two (i.e. `...enclave-originated data. (here goes new sentence). Naturally aligned...`):
`This data may then be unintentionally leaked by the enclave, e.g. written back to untrusted part or handled in non-side-channel-secure manner.`
</blockquote></details>

Looks good to me.
___
*[`-- commits` line 14 at r2](https://reviewable.io/reviews/gramineproject/gramine/894#-NBQyxVZ6rsuV01PeR1P):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Well, if somebody wants this feature, then we should fix it much sooner. If nobody uses it, then there is no point and we could completely deprecate it?
</blockquote></details>

But my comment was generally about this commit, not about Exitless. Like, in 2 years from now, we won't need that contrived logic in `sgx_copy_to_enclave_verified()`, and it would make sense to remove it again. That's what I wanted to highlight in the commit text.
___
*[`pal/src/host/linux-sgx/enclave_framework.c` line 180 at r2](https://reviewable.io/reviews/gramineproject/gramine/894#-NBR5D-sC_a5XMCvIiAK:-NBRnnP28GhCOwnR9sDd:bcryzdf) ([raw file](https://github.com/gramineproject/gramine/blob/9fc3749bc6762a54be49df76883bd5d37ee8d956/pal/src/host/linux-sgx/enclave_framework.c#L180)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I don't mind either. This code works correctly for `copy_len == 0` and it's unclear to me which would be faster, an if or couple of adds/subs. So this would be purely visual / for code clarity change.
Let's hear from others which version they would prefer.
</blockquote></details>

The others are @mkow, let's ping him :)
___
*[`pal/src/host/linux-sgx/pal_main.c` line 62 at r2](https://reviewable.io/reviews/gramineproject/gramine/894#-NBQH6R45J7_tCImLzNK:-NBRnSgTCCNkh1sgbJ13:b-o47ab5) ([raw file](https://github.com/gramineproject/gramine/blob/9fc3749bc6762a54be49df76883bd5d37ee8d956/pal/src/host/linux-sgx/pal_main.c#L62)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

> I was just thinking about moving this check before: 

How do you check a pointer without actually having it (i.e. copying it into enclave - the pointer, not the underlying object)?

> as it seems that we had some assumptions here (though not exactly the same purpose):

I don't understand your point, this is exactly the same check.
</blockquote></details>

Yes, I agree with Borys. I don't see any problems here. And again -- we only copy and check the **pointer value**, not the **underlying object this pointer points to**.


<!-- Sent from Reviewable.io -->

2022-09-08 11:52 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/894)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @kailun-qin, and @mkow)

___
*[`-- commits` line 14 at r2](https://reviewable.io/reviews/gramineproject/gramine/894#-NBQyxVZ6rsuV01PeR1P):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

But my comment was generally about this commit, not about Exitless. Like, in 2 years from now, we won't need that contrived logic in `sgx_copy_to_enclave_verified()`, and it would make sense to remove it again. That's what I wanted to highlight in the commit text.
</blockquote></details>

So you want me to add a sentence saying something like "when this issues is fixed in HW we will remove our mitigations"?


<!-- Sent from Reviewable.io -->

2022-09-09 21:06 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/894)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @kailun-qin, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/894#-NBZ3Ua_-osReAv3b7dA:-NBZ3Ua_-osReAv3b7dB:b9rupzq) (no related file):*
TODO: add this to list of the breaking changes, if we merge this `insecure__` prefix addition

___


<!-- Sent from Reviewable.io -->

2022-09-13 10:14 UTC, mkow requested changes
> Reviewed 8 of 13 files at r1, 1 of 1 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/894)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @kailun-qin)

___
*[`-- commits` line 7 at r2](https://reviewable.io/reviews/gramineproject/gramine/894#-NBQMGuKAjJxF41issb1):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Looks good to me.
</blockquote></details>

+1 to the addition proposed by Borys.
___
*[`-- commits` line 13 at r3](https://reviewable.io/reviews/gramineproject/gramine/894#-NBqKI4b2GgzEHXweFyk):*
Could you also mention that there was a bug that untrusted host could force Gramine to use exitless, despite the app didn't want it? It's ofc not a security issue after we marked exitless as insecure, but IMO worth to mention this change here.
___
*[`pal/src/host/linux-sgx/enclave_framework.c` line 180 at r2](https://reviewable.io/reviews/gramineproject/gramine/894#-NBR5D-sC_a5XMCvIiAK:-NBo_Ei87gJfkMwC3jZi:bp7xq02) ([raw file](https://github.com/gramineproject/gramine/blob/9fc3749bc6762a54be49df76883bd5d37ee8d956/pal/src/host/linux-sgx/enclave_framework.c#L180)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

The others are @mkow, let's ping him :)
</blockquote></details>

I don't see why zero would be a special case here, it's a normal size and everything works correctly on it.
___
*[`pal/src/host/linux-sgx/enclave_framework.c` line 134 at r3](https://reviewable.io/reviews/gramineproject/gramine/894#-NBqBIn41aSfQmutGhQF:-NBqBIn599LBGvotjh3g:b-m722xp) ([raw file](https://github.com/gramineproject/gramine/blob/c05ea6c64f2b7c555f3ddc027b62b3a13fccf6d0/pal/src/host/linux-sgx/enclave_framework.c#L134)):*
> ```C
> static void copy_u64s(void* dst, const void* untrusted_src, size_t count) {
>     assert((uintptr_t)untrusted_src % 8 == 0);
>     /* The output operands are needed because we cannot specify the same register as both input and
> ```

I'd reword this to say it's just the GAS inline assembly syntax which doesn't support this, in this version it's unclear why we can't do this.



_Code quote:_
```C
we cannot specify
```
___
*[`pal/src/host/linux-sgx/enclave_framework.c` line 187 at r3](https://reviewable.io/reviews/gramineproject/gramine/894#-NBqIbmUETCcmvVska_A:-NBqIbmV20ONEMDeR2Gh:bp7br0o) ([raw file](https://github.com/gramineproject/gramine/blob/c05ea6c64f2b7c555f3ddc027b62b3a13fccf6d0/pal/src/host/linux-sgx/enclave_framework.c#L187)):*
> ```C
>     assert(size == suffix_misalignment);
>     if (suffix_misalignment) {
>         /* End of the copied range is misaligned. */
> ```

This case is actually different than `prefix_misalignment` - here the _length_ of the suffix is misaligned, not the end of the range. And currently you have this comment exactly the same as under `prefix_misalignment` case.



_Code quote:_
```C
/* End of the copied range is misaligned. */
```


<!-- Sent from Reviewable.io -->

2022-09-13 10:48 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/894)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @kailun-qin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/894#-NBZ3Ua_-osReAv3b7dA:-NBqSds6C-6vsLzeLNh_:bm26bt7) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

TODO: add this to list of the breaking changes, if we merge this `insecure__` prefix addition
</blockquote></details>

Done (in the draft version)

___
___
*[`pal/src/host/linux-sgx/enclave_framework.c` line 180 at r2](https://reviewable.io/reviews/gramineproject/gramine/894#-NBR5D-sC_a5XMCvIiAK:-NBqSWsq7G3Y9ZbyZLnN:b-wv7diu) ([raw file](https://github.com/gramineproject/gramine/blob/9fc3749bc6762a54be49df76883bd5d37ee8d956/pal/src/host/linux-sgx/enclave_framework.c#L180)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I don't see why zero would be a special case here, it's a normal size and everything works correctly on it.
</blockquote></details>

OK, then let's leave the code as is.


<!-- Sent from Reviewable.io -->

2022-09-13 13:51 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/894)* status: all files reviewed, 3 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL), "squash! " found in commit messages' one-liners (waiting on @dimakuv and @kailun-qin)

___
*[`pal/src/host/linux-sgx/enclave_framework.c` line 187 at r3](https://reviewable.io/reviews/gramineproject/gramine/894#-NBqIbmUETCcmvVska_A:-NBr6SNJ-9yVMNRa6FzV:b-oag90k) ([raw file](https://github.com/gramineproject/gramine/blob/c05ea6c64f2b7c555f3ddc027b62b3a13fccf6d0/pal/src/host/linux-sgx/enclave_framework.c#L187)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I'm confused. What's the difference? Here the start is aligned and the end is misaligned. Yes, this means that the length is misaligned (length of the suffix, not necessarily the total length).

> And currently you have this comment exactly the same as under prefix_misalignment case.

Yes, and I believe these cases are mostly the same (length < 8, being or end misaligned)
</blockquote></details>

Ahhh, by "end" here you mean the real end of the string. Somehow I read this as that "suffix chunk", my bad.


<!-- Sent from Reviewable.io -->

2022-09-13 16:46 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/894)* status: all files reviewed, 2 unresolved discussions, "squash! " found in commit messages' one-liners (waiting on @kailun-qin)



<!-- Sent from Reviewable.io -->

2022-09-13 17:22 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/894)* status: all files reviewed, 2 unresolved discussions (waiting on @kailun-qin)



<!-- Sent from Reviewable.io -->

2022-09-13 19:53 UTC, mkow approved these changes
> Reviewed all commit messages.
> Dismissed @kailun-qin from 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/894)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`-- commits` line 7 at r2](https://reviewable.io/reviews/gramineproject/gramine/894#-NBQMGuKAjJxF41issb1):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Dismissing @kailun-qin from this discussion because it was already fixed and he didn't reply since then (and he's not a maintainer to have veto rights ;) ).
___
*[`-- commits` line 14 at r2](https://reviewable.io/reviews/gramineproject/gramine/894#-NBQN3XQ7n0v1wJw-o2O):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Yes, I intentionally didn't want to put links, because they often get stale.
</blockquote></details>

ditto


<!-- Sent from Reviewable.io -->

2022-09-13 19:55 UTC, merged