[LibOS] Support umask
gramineproject/gramine pull request #90
Opened 2021-09-24 15:25 UTC by pwmarcz

## Description of the changes 

This change makes Gramine respect the process umask when creating new files using `open` and `mkdir`. It also initializes it correctly.

Fixes one of the issues in https://github.com/gramineproject/graphene/issues/2543.

## How to test this PR? 

LTP test `umask01` (which this PR unskips) checks umask support in `open(O_CREAT)`. As far as I can tell, there's no corresponding LTP test for `mkdir`, but I'm not sure if this is important enough to add one of our own.

Anyway, a manual test (to be run with `python` example) looks like this:

```python
import os

for umask in [0o000, 0o022, 0o077]:
    if os.path.exists('dir'):
        os.rmdir('dir')
    os.umask(umask)
    os.mkdir('dir', 0o777)
    print(oct(os.stat('dir').st_mode))  # should print 0o40777, 0o40755, 0o40700
```

2021-09-24 15:30 UTC, dimakuv submitted a review, later dismissed
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/90)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2021-09-24 15:42 UTC, boryspoplawski requested changes
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/90)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required) (waiting on @pwmarcz)

___
*[LibOS/shim/src/bookkeep/shim_process.c, line 46 at r1](https://reviewable.io/reviews/gramineproject/gramine/90#-MkNRsR-9EHlPOJLp9sQ:-MkNRsR0BdMNl-vnkaep:bl1rmci) ([raw file](https://github.com/gramineproject/gramine/blob/d698f825c88e45296fc2a739c6fed922900772b6/LibOS/shim/src/bookkeep/shim_process.c#L46)):*
> ```C
>     g_process.wait_queue = NULL;
> 
>     /* default Linux umask */
> ```

Is that what Linux kernel initializes umask to or is it what most of the `init` processes do?
___
*[LibOS/shim/src/sys/shim_file.c, line 96 at r1](https://reviewable.io/reviews/gramineproject/gramine/90#-MkNS6Dt-tOJJett_fFl:-MkNS6Dt-tOJJett_fFm:b-51dl8l) ([raw file](https://github.com/gramineproject/gramine/blob/d698f825c88e45296fc2a739c6fed922900772b6/LibOS/shim/src/sys/shim_file.c#L96)):*
> ```C
>     unlock(&g_process.fs_lock);
> 
>     mode &= ~umask & 0777;
> ```

This will clear all extra (like sticky bit) bits from mode. Is that intended? If yes then please add an explanation.
___
*[LibOS/shim/src/sys/shim_open.c, line 123 at r1](https://reviewable.io/reviews/gramineproject/gramine/90#-MkNSwOD7YKejywWmWAQ:-MkNSwOE9HnMh0Zg6v6K:b-zic8ss) ([raw file](https://github.com/gramineproject/gramine/blob/d698f825c88e45296fc2a739c6fed922900772b6/LibOS/shim/src/sys/shim_open.c#L123)):*
> ```C
>         unlock(&g_process.fs_lock);
> 
>         mode &= ~umask & 07777;
> ```

Could you split `& 07777` and leave a comment saying why it's done (clearing invalid bits)


<!-- Sent from Reviewable.io -->

2021-09-24 17:07 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/90)* status: 2 of 4 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[LibOS/shim/src/bookkeep/shim_process.c, line 46 at r1](https://reviewable.io/reviews/gramineproject/gramine/90#-MkNRsR-9EHlPOJLp9sQ:-MkNgWbDENJGJ5zJ3ugH:bn99yis) ([raw file](https://github.com/gramineproject/gramine/blob/d698f825c88e45296fc2a739c6fed922900772b6/LibOS/shim/src/bookkeep/shim_process.c#L46)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Is that what Linux kernel initializes umask to or is it what most of the `init` processes do?
</blockquote></details>

If I'm reading this correctly, Linux kernel initializes it this way for the init process ([init_fs](https://code.woboq.org/linux/linux/fs/fs_struct.c.html#init_fs), [init_task](https://code.woboq.org/linux/linux/init/init_task.c.html#init_task)).
___
*[LibOS/shim/src/sys/shim_file.c, line 96 at r1](https://reviewable.io/reviews/gramineproject/gramine/90#-MkNS6Dt-tOJJett_fFl:-MkNhElGDY_UB7jjueFH:b-vae5dx) ([raw file](https://github.com/gramineproject/gramine/blob/d698f825c88e45296fc2a739c6fed922900772b6/LibOS/shim/src/sys/shim_file.c#L96)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This will clear all extra (like sticky bit) bits from mode. Is that intended? If yes then please add an explanation.
</blockquote></details>

On closer look, it's actually 01777, i.e. permission bits and the sticky bit (see `man mkdirat`, and [Linux source](https://code.woboq.org/linux/linux/fs/namei.c.html#vfs_mkdir)). I fixed it and added an explanation.
___
*[LibOS/shim/src/sys/shim_open.c, line 123 at r1](https://reviewable.io/reviews/gramineproject/gramine/90#-MkNSwOD7YKejywWmWAQ:-MkNj9hp7Nyv_3cuoGbz:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d698f825c88e45296fc2a739c6fed922900772b6/LibOS/shim/src/sys/shim_open.c#L123)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Could you split `& 07777` and leave a comment saying why it's done (clearing invalid bits)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-09-24 20:08 UTC, boryspoplawski submitted a review, later dismissed
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/90)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-09-27 07:36 UTC, dimakuv submitted a review, later dismissed
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/90)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-09-27 12:59 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/90)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2021-09-27 13:02 UTC, boryspoplawski approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/90)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-09-27 13:42 UTC, merged