[LibOS,PAL] Extend extra runtime configuration to include hostname
gramineproject/gramine pull request #919
Opened 2022-09-19 15:36 UTC by oshogbo

## Description of the changes 

This is a continuation of the issue https://github.com/gramineproject/gramine/issues/689.

From what I can see, most applications use the uname(2) syscall to obtain a current hostname, for example, gethostame.
The /etc/hostname is read during startup, and the sethostname(2) is called. For example, this is done on Ubuntu 20.04 with /etc/init/hostname.conf script.

Because of that we decided not to create a `/etc/hostname` file but just to set the Gramine hostname to the host's hostname.

The Gramine hostname has to be a valid domain. This is a difference from Linux, as Linux accepts any hostname value. That said, Linux doesn't assume that the root user tries to exploit it through hostname, and Gramine should.

This change doesn't address the support of the sethostname(2). The hostname can change after initialisation, however new process (after fork inside Gramine) will inherit an initial value of hostname. We probably should separately propagate the current value of the hostname. We are also missing a mechanism for propagating the hostname across multiple processes. We might also decide just to remove sethostname(2) completely. My understanding is that we have it only to enable LTP tests.

## How to test this PR? 

New tests are added.

2022-09-19 15:51 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/919)* status: 0 of 20 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @oshogbo)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/919#-NCLOvbq-26f8qaEvhDb):*
`expects`
___
*[`libos/src/libos_init.c` line 490 at r1](https://reviewable.io/reviews/gramineproject/gramine/919#-NCLQvYIAJ6w9Dlg7kUV:-NCLQvYJ1rJ4qDi2hbtJ:b9vb0bn) ([raw file](https://github.com/gramineproject/gramine/blob/a048f94a2d8ef9661f506f1842a5595af1f8dfae/libos/src/libos_init.c#L490)):*
> ```C
>     RUN_INIT(init_sync_client);
> 
>     /* XXX: this will break uname checkpointing (if we implement it). */
> ```

Where we do actually have checkpointing of `g_pal_public_state->dns_host.hostname`?

I thought that in the previous iteration of this PR, you had some explicit checkpointing mechanism. But I don't see it in this PR. Is it because we already have some checkpointing mechanism (at the level of PAL) that forwards `g_pal_public_state` to the child?
___
*[`libos/test/regression/hostname.c` line 20 at r1](https://reviewable.io/reviews/gramineproject/gramine/919#-NCLPIj6-UQbDnPCLKqo:-NCLPIj6-UQbDnPCLKqp:btn62it) ([raw file](https://github.com/gramineproject/gramine/blob/a048f94a2d8ef9661f506f1842a5595af1f8dfae/libos/test/regression/hostname.c#L20)):*
> ```C
> 
>     if (pid == 0) {
>         f(tag, expected_name);
> ```

I see no sense in this indirection, you could just call `test_gethostname()` here directly. But not blocking.
___
*[`pal/src/host/linux-common/etc_host_info.c` line 362 at r1](https://reviewable.io/reviews/gramineproject/gramine/919#-NCLQWIb6S464a9ED9oK:-NCLQWIb6S464a9ED9oL:bip94eh) ([raw file](https://github.com/gramineproject/gramine/blob/a048f94a2d8ef9661f506f1842a5595af1f8dfae/pal/src/host/linux-common/etc_host_info.c#L362)):*
> ```C
>     return 0;
> }
> #endif
> ```

Please add `/* ifndef PARSERS_ONLY */`


<!-- Sent from Reviewable.io -->

2022-09-19 15:56 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/919)* status: 0 of 20 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @oshogbo)

___
*[`libos/src/libos_init.c` line 490 at r1](https://reviewable.io/reviews/gramineproject/gramine/919#-NCLQvYIAJ6w9Dlg7kUV:-NCLRiLx91o4NcnyyPsa:b-zbk4fq) ([raw file](https://github.com/gramineproject/gramine/blob/a048f94a2d8ef9661f506f1842a5595af1f8dfae/libos/src/libos_init.c#L490)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Where we do actually have checkpointing of `g_pal_public_state->dns_host.hostname`?

I thought that in the previous iteration of this PR, you had some explicit checkpointing mechanism. But I don't see it in this PR. Is it because we already have some checkpointing mechanism (at the level of PAL) that forwards `g_pal_public_state` to the child?
</blockquote></details>

We checkpoint dns_host, so we also checkpoint hostname as this is static buffer.
https://github.com/gramineproject/gramine/blob/master/libos/src/fs/etc/fs.c#L142

```
struct pal_dns_host_conf {
    struct pal_dns_host_conf_addr nsaddr_list[PAL_MAX_NAMESPACES];
    size_t nsaddr_list_count;

    char dn_search[PAL_MAX_DN_SEARCH][PAL_HOSTNAME_MAX];
    size_t dn_search_count;

    bool inet6;
    bool rotate;

    char hostname[PAL_HOSTNAME_MAX];
};
```
___
*[`pal/src/host/linux-common/etc_host_info.c` line 362 at r1](https://reviewable.io/reviews/gramineproject/gramine/919#-NCLQWIb6S464a9ED9oK:-NCLSBKk-R65rv7izW1d:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/a048f94a2d8ef9661f506f1842a5595af1f8dfae/pal/src/host/linux-common/etc_host_info.c#L362)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add `/* ifndef PARSERS_ONLY */`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-09-19 20:15 UTC, mkow requested changes
> Reviewed 19 of 20 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/919)* status: all files reviewed, 12 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @oshogbo)

___
*[`Documentation/manifest-syntax.rst` line 156 at r2](https://reviewable.io/reviews/gramineproject/gramine/919#-NCLVoYqBrWTxFHaHgK6:-NCLVoYqBrWTxFHaHgK7:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/094b89075779dcbc71cc3cd17dd7a62cfa59deae/Documentation/manifest-syntax.rst#L156)):*
> ```reStructuredText
>     (Default: false)
> 
> This option will generate following extra configuration:
> ```





_Suggestion:_
```reStructuredText
the following extra configuration:
```
___
*[`Documentation/manifest-syntax.rst` line 158 at r2](https://reviewable.io/reviews/gramineproject/gramine/919#-NCLVujBE_3LXAj8RW0Y:-NCLVujBE_3LXAj8RW0Z:bpks6yz) ([raw file](https://github.com/gramineproject/gramine/blob/094b89075779dcbc71cc3cd17dd7a62cfa59deae/Documentation/manifest-syntax.rst#L158)):*
> ```reStructuredText
> This option will generate following extra configuration:
> 
> - Set up the Gramine hostname to the host's hostname.
> ```

If you said in the previous sentence that you're listing configurations here, then the list should be made of things, not sentences. So, please either change the form of the sentence above or the entries.
___
*[`Documentation/manifest-syntax.rst` line 159 at r2](https://reviewable.io/reviews/gramineproject/gramine/919#-NCLYD1N5DomqI2JGcXv:-NCLYD1N5DomqI2JGcXw:bfs8c39) ([raw file](https://github.com/gramineproject/gramine/blob/094b89075779dcbc71cc3cd17dd7a62cfa59deae/Documentation/manifest-syntax.rst#L159)):*
> ```reStructuredText
> 
> - Set up the Gramine hostname to the host's hostname.
> - Generate ``/etc/resolv.conf``, with keywords
> ```

missing colon at the end (or maybe two, not sure about the precise reST rules, but the rendered version should have exactly one)
___
*[`Documentation/manifest-syntax.rst` line 173 at r2](https://reviewable.io/reviews/gramineproject/gramine/919#-NCLZegn3FXnd2Kh0osi:-NCLZegn3FXnd2Kh0osj:bdeo7mv) ([raw file](https://github.com/gramineproject/gramine/blob/094b89075779dcbc71cc3cd17dd7a62cfa59deae/Documentation/manifest-syntax.rst#L173)):*
> ```reStructuredText
> process configuration. For security-enforcing modes (such as SGX), Gramine
> additionally sanitizes the information gathered from the host. Invalid host's
> configuration is reported as an error (ex. invalid hostname, or invalid IPv4
> ```

(I guess?)



_Suggestion:_
```reStructuredText
e.g.
```
___
*[`libos/test/regression/hostname.c` line 53 at r2](https://reviewable.io/reviews/gramineproject/gramine/919#-NCLirtF9AV0XVeAiLhH:-NCLirtGCKw7Ghq4RGiZ:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/094b89075779dcbc71cc3cd17dd7a62cfa59deae/libos/test/regression/hostname.c#L53)):*
> ```C
> 
>     test_gethostname("normal", argv[1]);
>     test_fork("fork gethostname", argv[1], test_gethostname);
> ```





_Suggestion:_
```C
gethostname after fork
```
___
*[`pal/include/host/linux-common/etc_host_info.h` line 12 at r2](https://reviewable.io/reviews/gramineproject/gramine/919#-NCLjejD-jV_tYa9sdgi:-NCLjejD-jV_tYa9sdgj:b-65mpfz) ([raw file](https://github.com/gramineproject/gramine/blob/094b89075779dcbc71cc3cd17dd7a62cfa59deae/pal/include/host/linux-common/etc_host_info.h#L12)):*
> ```objc
> int parse_resolv_conf(struct pal_dns_host_conf* conf);
> 
> int get_hostname(char* hostname, size_t size);
> ```

This may get confused with another global function: `set_hostname()` - it sounds like it was its counterpart, while it does something completely different. I know one is in PAL and another in LibOS, but still, I'd make the names at least a bit more specific.



_Code quote (from libos/src/sys/libos_uname.c):_
```C
set_hostname
```
___
*[`pal/src/host/linux/pal_main.c` line 134 at r2](https://reviewable.io/reviews/gramineproject/gramine/919#-NCMLSg-7lyEVj4VxA60:-NCMLSg01_kJnaGZ11n7:b-bxtk7u) ([raw file](https://github.com/gramineproject/gramine/blob/094b89075779dcbc71cc3cd17dd7a62cfa59deae/pal/src/host/linux/pal_main.c#L134)):*
> ```C
> 
>     if (get_hostname(g_pal_public_state.dns_host.hostname,
>         sizeof(g_pal_public_state.dns_host.hostname)) < 0) {
> ```

+4 more spaces
___
*[`pal/src/host/linux-common/etc_host_info.c` line 9 at r2](https://reviewable.io/reviews/gramineproject/gramine/919#-NCMLbyuBjc2Nh9U2zFK:-NCMLbyuBjc2Nh9U2zFL:b-6folqj) ([raw file](https://github.com/gramineproject/gramine/blob/094b89075779dcbc71cc3cd17dd7a62cfa59deae/pal/src/host/linux-common/etc_host_info.c#L9)):*
> ```C
>  * This file contains the APIs to retrieve information from the host:
>  *   - parses host file `/etc/resolv.conf` into `struct pal_dns_host_conf`
>  *   - get host's hostname through uname syscall
> ```

grammar form doesn't match the previous point on the list here


<!-- Sent from Reviewable.io -->

2022-09-20 06:47 UTC, dimakuv commented
Jenkins, retest Jenkins-20.04 please (`AssertionError: Command ['gramine-direct', 'fcntl14_64'] timed out after 60 s`)

2022-09-20 07:26 UTC, dimakuv requested changes
> Reviewed 19 of 20 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/919)* status: all files reviewed, 20 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @oshogbo)

___
*[`-- commits` line 3 at r2](https://reviewable.io/reviews/gramineproject/gramine/919#-NCOeyhw-cV4jlGZOjv2):*
The commit message actually needs to explain a bit what it does. I suggest:
```
Gramine exposes hostname information to the app via `nodename` field returned
by the `uname` syscall. Note that currently Gramine does *not* create an
`/etc/hostname` file as no apps seem to read this file directly.

To expose the hostname, Gramine obtains it from the host, sanitizes it, and
stores it in the global PAL state.

The difference between ...
```
___
*[`-- commits` line 7 at r2](https://reviewable.io/reviews/gramineproject/gramine/919#-NCOenq302-ECT0NPyKL):*
I would put this last sentence in brackets: `(In the case of Linux, ... malicious hostname.)`
___
*[`Documentation/manifest-syntax.rst` line 158 at r2](https://reviewable.io/reviews/gramineproject/gramine/919#-NCLVujBE_3LXAj8RW0Y:-NCOg11OEiXzcztEboHW:b-gsjsw8) ([raw file](https://github.com/gramineproject/gramine/blob/094b89075779dcbc71cc3cd17dd7a62cfa59deae/Documentation/manifest-syntax.rst#L158)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

If you said in the previous sentence that you're listing configurations here, then the list should be made of things, not sentences. So, please either change the form of the sentence above or the entries.
</blockquote></details>

Yes, I would do like this:
```
This option will generate the following extra configuration:

- Hostname (obtained by apps via `nodename` field in `uname` syscall),
  set to the host's hostname at initialization.

- Pseudo-file ``/etc/resolv.conf``, with keywords:

      ...
```
___
*[`libos/src/libos_init.c` line 490 at r1](https://reviewable.io/reviews/gramineproject/gramine/919#-NCLQvYIAJ6w9Dlg7kUV:-NCOgthaEiIhKIwJTBan:bcr5s31) ([raw file](https://github.com/gramineproject/gramine/blob/a048f94a2d8ef9661f506f1842a5595af1f8dfae/libos/src/libos_init.c#L490)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

We checkpoint dns_host, so we also checkpoint hostname as this is static buffer.
https://github.com/gramineproject/gramine/blob/master/libos/src/fs/etc/fs.c#L142

```
struct pal_dns_host_conf {
    struct pal_dns_host_conf_addr nsaddr_list[PAL_MAX_NAMESPACES];
    size_t nsaddr_list_count;

    char dn_search[PAL_MAX_DN_SEARCH][PAL_HOSTNAME_MAX];
    size_t dn_search_count;

    bool inet6;
    bool rotate;

    char hostname[PAL_HOSTNAME_MAX];
};
```

</blockquote></details>

Got it, thanks.
___
*[`libos/src/sys/libos_uname.c` line 24 at r2](https://reviewable.io/reviews/gramineproject/gramine/919#-NCOjy6T3nh2IfKoVp_i:-NCOjy6T3nh2IfKoVp_j:b-rtri5a) ([raw file](https://github.com/gramineproject/gramine/blob/094b89075779dcbc71cc3cd17dd7a62cfa59deae/libos/src/sys/libos_uname.c#L24)):*
> ```C
> static struct new_utsname g_current_uname = {
>     .sysname  = "Linux",
>     .nodename = "localhost",
> ```

I don't like that we have some default here which is actually never used (it is immediately rewritten by the PAL-provided value, which is by default also `localhost`). What if we like this, to make it very explicit:
```
static struct new_utsname g_current_uname = {
    .sysname  = "Linux",
    .nodename = "(none)",  /* overwritten by PAL-provided value at startup */
    ...
```
___
*[`libos/test/regression/hostname.c` line 16 at r2](https://reviewable.io/reviews/gramineproject/gramine/919#-NCOh_wN8B-ccxLNvMJy:-NCOh_wN8B-ccxLNvMJz:b-v754yb) ([raw file](https://github.com/gramineproject/gramine/blob/094b89075779dcbc71cc3cd17dd7a62cfa59deae/libos/test/regression/hostname.c#L16)):*
> ```C
>     pid_t pid = fork();
>     if (pid == -1) {
>         err(1, "Unable to fork %s", tag);
> ```

`tag` should be the first thing printed. Also, the colon would visually help in the message. So like this:
```
        err(1, "%s: unable to fork", tag);
```

Here and in all other places, please.
___
*[`libos/test/regression/hostname.c` line 25 at r2](https://reviewable.io/reviews/gramineproject/gramine/919#-NCOhsz32Ud_GDwFiuRt:-NCOhsz32Ud_GDwFiuRu:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/094b89075779dcbc71cc3cd17dd7a62cfa59deae/libos/test/regression/hostname.c#L25)):*
> ```C
> 
>     if (wait(&status) == -1) {
>         err(1, "Wait failed %s", tag);
> ```

ditto
___
*[`libos/test/regression/hostname.c` line 29 at r2](https://reviewable.io/reviews/gramineproject/gramine/919#-NCOhtoA18oFp49kEOAz:-NCOhtoA18oFp49kEOB-:bkyttmn) ([raw file](https://github.com/gramineproject/gramine/blob/094b89075779dcbc71cc3cd17dd7a62cfa59deae/libos/test/regression/hostname.c#L29)):*
> ```C
> 
>     if (!WIFEXITED(status) || WEXITSTATUS(status) != 0) {
>         err(1, "Test failed %s", tag);
> ```

ditto + it should be `errx` + I would write a better message (`exit status of child is not zero`)
___
*[`libos/test/regression/hostname.c` line 37 at r2](https://reviewable.io/reviews/gramineproject/gramine/919#-NCOifSkDV-pxu69fxeF:-NCOifSkDV-pxu69fxeG:bptbjkl) ([raw file](https://github.com/gramineproject/gramine/blob/094b89075779dcbc71cc3cd17dd7a62cfa59deae/libos/test/regression/hostname.c#L37)):*
> ```C
> 
>     if (gethostname(buf, sizeof(buf)) != 0) {
>         err(1, "%s gethostname: failed", tag);
> ```

For uniformity, I would change the message to:
```
        err(1, "%s: gethostname failed", tag);
```
___
*[`libos/test/regression/hostname.c` line 42 at r2](https://reviewable.io/reviews/gramineproject/gramine/919#-NCOikmu1WbARFeae1i2:-NCOikmu1WbARFeae1i3:b-4rpz7f) ([raw file](https://github.com/gramineproject/gramine/blob/094b89075779dcbc71cc3cd17dd7a62cfa59deae/libos/test/regression/hostname.c#L42)):*
> ```C
>     if (strcmp(buf, expected_name) != 0) {
>         errx(1, "%s gethostname result doesn't match hostname (expected: %s, got: %s)",
>              tag, expected_name, buf);
> ```

ditto (colon after `%s`)
___
*[`libos/test/regression/test_libos.py` line 916 at r2](https://reviewable.io/reviews/gramineproject/gramine/919#-NCOjQx42yBIOXdQpw6a:-NCOjQx42yBIOXdQpw6b:b-4dbby3) ([raw file](https://github.com/gramineproject/gramine/blob/094b89075779dcbc71cc3cd17dd7a62cfa59deae/libos/test/regression/test_libos.py#L916)):*
> ```Python
>         self.assertIn('TEST OK', stdout)
> 
>     def test_120_gethostname_localhost(self):
> ```

Maybe rename from `_localhost` to `_default`? The fact that by default Gramine uses `localhost` doesn't need to be reflected in the name -- maybe we'll change the default value in the future.
___
*[`pal/include/host/linux-common/etc_host_info.h` line 12 at r2](https://reviewable.io/reviews/gramineproject/gramine/919#-NCLjejD-jV_tYa9sdgi:-NCOmIKb6y1VkF-OGYQQ:bunm7g0) ([raw file](https://github.com/gramineproject/gramine/blob/094b89075779dcbc71cc3cd17dd7a62cfa59deae/pal/include/host/linux-common/etc_host_info.h#L12)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This may get confused with another global function: `set_hostname()` - it sounds like it was its counterpart, while it does something completely different. I know one is in PAL and another in LibOS, but still, I'd make the names at least a bit more specific.
</blockquote></details>

Maybe `get_hostname_from_host`? It's a weird name, but it is clearly different from LibOS's `set_hostname`.

(I agree with Michal that current `get_hostname` and `set_hostname` look confusingly similar.)
___
*[`pal/src/host/linux-common/etc_host_info.c` line 9 at r2](https://reviewable.io/reviews/gramineproject/gramine/919#-NCML [...]

2022-09-20 13:40 UTC, dimakuv approved these changes
> Reviewed 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/919)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "squash! " found in commit messages' one-liners (waiting on @mkow)

___
*[`pal/include/host/linux-common/etc_host_info.h` line 12 at r2](https://reviewable.io/reviews/gramineproject/gramine/919#-NCLjejD-jV_tYa9sdgi:-NCQ79nN3Q1JbNCY2zfB:bfjktja) ([raw file](https://github.com/gramineproject/gramine/blob/094b89075779dcbc71cc3cd17dd7a62cfa59deae/pal/include/host/linux-common/etc_host_info.h#L12)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Maybe `get_hosts_hostname` ?
</blockquote></details>

The proposed version is fine with me too.


<!-- Sent from Reviewable.io -->

2022-09-20 13:54 UTC, dimakuv submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/919)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "squash! " found in commit messages' one-liners (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/919#-NCQ8gk8Bgm79XfJy-kd:-NCQ8gk8Bgm79XfJy-ke:b14izr1) (no related file):*
Verified this PR (and the previous one about `/etc/resolv.conf`) on three configurations:
1. My work corporate machine, bare metal.
2. My work corporate machine, in a Docker container.
3. Azure VM.

In all cases, I checked out this PR's branch, built Gramine, and ran `gramine-direct busybox sh` and `gramine-sgx busybox sh`. Once in the Busybox session, I used `ls /etc`, `cat /etc/resolv.conf` and `uname -n` to verify that the files/configs are propagated inside Gramine. I also played with different combinations of manifest options (enable/disable `sys.enable_extra_runtime_domain_names_conf`, enable/disable `/etc/` in `fs.mounts`).

Everything works as expected.

___


<!-- Sent from Reviewable.io -->

2022-09-20 14:34 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/919)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "squash! " found in commit messages' one-liners (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/919#-NCQ8gk8Bgm79XfJy-kd:-NCQJSoZ-G_GY92ILQeC:bcm9pox) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Verified this PR (and the previous one about `/etc/resolv.conf`) on three configurations:
1. My work corporate machine, bare metal.
2. My work corporate machine, in a Docker container.
3. Azure VM.

In all cases, I checked out this PR's branch, built Gramine, and ran `gramine-direct busybox sh` and `gramine-sgx busybox sh`. Once in the Busybox session, I used `ls /etc`, `cat /etc/resolv.conf` and `uname -n` to verify that the files/configs are propagated inside Gramine. I also played with different combinations of manifest options (enable/disable `sys.enable_extra_runtime_domain_names_conf`, enable/disable `/etc/` in `fs.mounts`).

Everything works as expected.
</blockquote></details>

That's amazing thank you :)

___
___
*[`pal/include/host/linux-common/etc_host_info.h` line 12 at r2](https://reviewable.io/reviews/gramineproject/gramine/919#-NCLjejD-jV_tYa9sdgi:-NCQJUz3EWl1Fxdo9xf0:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/094b89075779dcbc71cc3cd17dd7a62cfa59deae/pal/include/host/linux-common/etc_host_info.h#L12)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

The proposed version is fine with me too.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-09-20 16:57 UTC, mkow submitted a review, later dismissed
> Reviewed 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/919)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "squash! " found in commit messages' one-liners (waiting on @oshogbo)

___
*[`-- commits` line 23 at r3](https://reviewable.io/reviews/gramineproject/gramine/919#-NCQmnWp5Oa00ttuGgf6):*
It's not clear whether this sentence describes the state before or after this commit. You can fix this while doing the final rebase, but plz give me the proposed version before for review ;)



_Code quote:_
```
Gramine exposes hostname information to the app via `nodename` field returned
```


<!-- Sent from Reviewable.io -->

2022-09-20 19:41 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/919)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow)

___
*[`-- commits` line 23 at r3](https://reviewable.io/reviews/gramineproject/gramine/919#-NCQmnWp5Oa00ttuGgf6):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

It's not clear whether this sentence describes the state before or after this commit. You can fix this while doing the final rebase, but plz give me the proposed version before for review ;)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-09-20 20:02 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/919)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2022-09-20 20:24 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/919)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2022-09-20 20:51 UTC, boryspoplawski approved these changes
I did not review the PR, but trust other reviewers did it well (because PR is new so needs 3 approvals) ;)

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/919#-:-NCRbR5a-5m_bqxsys5k:b5v9je9)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-09-20 21:06 UTC, merged