[PAL] Initialize ret variable to avoid incorrect return value
gramineproject/gramine pull request #93
Opened 2021-09-27 07:23 UTC by aneessahib

Signed-off-by: aneessahib <anees.a.sahib@intel.com>

Fixes a Klocwork sighting. The function could return negative incorrectly even when there are no failures due to uninitialized return variable.

2021-09-27 07:24 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/93)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @aneessahib)

___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/93#-Mka7udy3Tu5bbVB4oHl):*
`[PAL]` -> `[Pal/Linux-SGX]`

We will fix it during the final rebase.
___
*[Pal/src/host/Linux-SGX/db_streams.c, line 164 at r1](https://reviewable.io/reviews/gramineproject/gramine/93#-Mka7z5_9VHPBMkoBACI:-Mka7z5_9VHPBMkoBACJ:bxbmsja) ([raw file](https://github.com/gramineproject/gramine/blob/f338e9dd5d3ae7dcdd58a5ad46457c7f9f6a6ff7/Pal/src/host/Linux-SGX/db_streams.c#L164)):*
> ```C
>     if (dsz2)
>         memcpy(buffer + hdlsz + dsz1, d2, dsz2);
>     
> ```

Please remove spaces.


<!-- Sent from Reviewable.io -->

2021-09-27 08:06 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/93)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/93#-Mka7udy3Tu5bbVB4oHl):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`[PAL]` -> `[Pal/Linux-SGX]`

We will fix it during the final rebase.
</blockquote></details>

fine.
___
*[Pal/src/host/Linux-SGX/db_streams.c, line 164 at r1](https://reviewable.io/reviews/gramineproject/gramine/93#-Mka7z5_9VHPBMkoBACI:-MkaAi199He-EiNuuQdb:bb7f2mf) ([raw file](https://github.com/gramineproject/gramine/blob/1f57f09a4474f1f457eb695115bab4293e93a520/Pal/src/host/Linux-SGX/db_streams.c#L164)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please remove spaces.
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2021-09-27 08:50 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/93)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2021-09-27 12:36 UTC, pwmarcz submitted a review, later dismissed
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/93)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2021-09-28 14:28 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/93)* status: all files reviewed, 2 unresolved discussions (waiting on @aneessahib and @dimakuv)

___
*[-- commits, line 2 at r2](https://reviewable.io/reviews/gramineproject/gramine/93#-MkgnDpR-WS8puC7J3Uy):*
Please add "in handle_serialize()", otherwise it's hard to say what part of code you actually changed (PAL is quite big).


<!-- Sent from Reviewable.io -->

2021-09-28 16:23 UTC, dimakuv submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/93)* status: all files reviewed, 2 unresolved discussions (waiting on @dimakuv and @mkow)

___
*[-- commits, line 2 at r2](https://reviewable.io/reviews/gramineproject/gramine/93#-MkgnDpR-WS8puC7J3Uy):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please add "in handle_serialize()", otherwise it's hard to say what part of code you actually changed (PAL is quite big).
</blockquote></details>

I will do it during final rebase


<!-- Sent from Reviewable.io -->

2021-09-28 16:39 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/93)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/93#-Mka7udy3Tu5bbVB4oHl):*
<details><summary><i>Previously, aneessahib wrote…</i></summary><blockquote>

fine.
</blockquote></details>

Done
___
*[-- commits, line 2 at r2](https://reviewable.io/reviews/gramineproject/gramine/93#-MkgnDpR-WS8puC7J3Uy):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I will do it during final rebase
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2021-09-28 16:39 UTC, dimakuv commented
Jenkins, test this please

2021-09-28 16:41 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/93)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2021-09-28 16:55 UTC, boryspoplawski approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/93)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-09-28 18:08 UTC, merged