[LibOS,PAL] Extend DNS runtime configuration
gramineproject/gramine pull request #932
Opened 2022-09-26 20:26 UTC by oshogbo

## Description of the changes 

This PR build upon the recent feature of domain name extra runtime configuration (aka emulating `/etc/resolv.conf`). In previous PR we emulated only two options: `inet6` and `rotate`.
@dimakuv in review to https://github.com/gramineproject/gramine/pull/889 proposed propagating fallowing options:
* `options edns0`
* `ndots:n`
* `use-vc`
This PR tries to address this request.

## Useful link

* [resolv.conf](https://man7.org/linux/man-pages/man5/resolv.conf.5.html)
* [Resolv GLIBC parser](https://elixir.bootlin.com/glibc/latest/source/resolv/res_init.c#L645)
* [Resolv GLIBC header limits](https://elixir.bootlin.com/glibc/latest/source/resolv/resolv.h#L69)

## Issue

https://github.com/gramineproject/gramine/issues/689

## How to test this PR? 

Check the value of `resolv.conf` with multiple different hosts configuration.

2022-09-26 21:45 UTC, boryspoplawski requested changes
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/932)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/932#-NCveanj54qGQ62UF-4p:-NCveanj54qGQ62UF-4q:b-sujxgu) (no related file):*
What's the point of `ndots:n` and `use-vs`? We've not seen them in any setup and the conclusion from #889 was unclear. I'm not saying we don't want them, but if nobody is going to ever use them, then we just increase attack surface...

___
___
*[`Documentation/manifest-syntax.rst` line 164 at r1](https://reviewable.io/reviews/gramineproject/gramine/932#-NCvgWD8EuVG873PB6O3:-NCvgWD8EuVG873PB6O4:b4vrl6r) ([raw file](https://github.com/gramineproject/gramine/blob/d5f04615a54a0238ff5d84e68a9843b566a4c042/Documentation/manifest-syntax.rst#L164)):*
> ```reStructuredText
>    - ``nameserver``
>    - ``search``
>    - ``options`` (``edns0`` | ``inet6`` | ``ndots:`` | ``rotate`` | ``use-vc``)
> ```

Noticed this now: doesn't `|` mean alternative, i.e. this would mean only one option is allowed?
___
*[`libos/src/fs/etc/fs.c` line 49 at r1](https://reviewable.io/reviews/gramineproject/gramine/932#-NCvhLSV3l7XesQsHyf4:-NCvhLSV3l7XesQsHyf5:b-8bv63g) ([raw file](https://github.com/gramineproject/gramine/blob/d5f04615a54a0238ff5d84e68a9843b566a4c042/libos/src/fs/etc/fs.c#L49)):*
> ```C
>     size += 1;
>     /* and let's add some space for each option */
>     size += (g_pal_public_state->dns_host.edns0 ? strlen(OPTION_EDNS0) : 0) +
> ```

We use `+` on new line
___
*[`libos/src/fs/etc/fs.c` line 54 at r1](https://reviewable.io/reviews/gramineproject/gramine/932#-NCvg2_E1wYfCm3s2cUM:-NCvg2_E1wYfCm3s2cUN:b-4jq1mw) ([raw file](https://github.com/gramineproject/gramine/blob/d5f04615a54a0238ff5d84e68a9843b566a4c042/libos/src/fs/etc/fs.c#L54)):*
> ```C
>             (g_pal_public_state->dns_host.use_vc ? strlen(OPTION_USE_VC) : 0);
>     if (g_pal_public_state->dns_host.ndots != 1) {
>         /* ndots option + space for two digit number + new line */
> ```

`%hhu` could be three digit
___
*[`libos/src/fs/etc/fs.c` line 55 at r1](https://reviewable.io/reviews/gramineproject/gramine/932#-NCvftNyEdh9cdwip1ij:-NCvftNyEdh9cdwip1ik:b1c610g) ([raw file](https://github.com/gramineproject/gramine/blob/d5f04615a54a0238ff5d84e68a9843b566a4c042/libos/src/fs/etc/fs.c#L55)):*
> ```C
>     if (g_pal_public_state->dns_host.ndots != 1) {
>         /* ndots option + space for two digit number + new line */
>         size += strlen("options ndots:") + 2 + 1;
> ```

Can we have this string as some define/constant? It's used in two places.
___
*[`libos/src/fs/etc/fs.c` line 120 at r1](https://reviewable.io/reviews/gramineproject/gramine/932#-NCvhXqn29PuewcFhQQ-:-NCvhXqn29PuewcFhQQ0:bh5j36q) ([raw file](https://github.com/gramineproject/gramine/blob/d5f04615a54a0238ff5d84e68a9843b566a4c042/libos/src/fs/etc/fs.c#L120)):*
> ```C
>     }
>     if (g_pal_public_state->dns_host.ndots != 1) {
>         ret = put_string(&ptr, &space_left, "options ndots:%hhu",
> ```

Lacks `\n`?
___
*[`pal/src/host/linux-common/etc_host_info.c` line 287 at r1](https://reviewable.io/reviews/gramineproject/gramine/932#-NCvhudy1riqX62tpk-Q:-NCvhudy1riqX62tpk-R:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/d5f04615a54a0238ff5d84e68a9843b566a4c042/pal/src/host/linux-common/etc_host_info.c#L287)):*
> ```C
>     } else if (strcmp(option, "inet6") == 0) {
>         conf->inet6 = true;
>     } else if (strncmp(option, "ndots:", sizeof("ndots:") - 1) == 0) {
> ```





_Suggestion:_
```C
strstartswith(option, "ndots:")
```
___
*[`pal/src/host/linux-common/etc_host_info.c` line 314 at r1](https://reviewable.io/reviews/gramineproject/gramine/932#-NCvkBlHBOCtfkjFDn56:-NCvkBlHBOCtfkjFDn57:b8kaai5) ([raw file](https://github.com/gramineproject/gramine/blob/d5f04615a54a0238ff5d84e68a9843b566a4c042/pal/src/host/linux-common/etc_host_info.c#L314)):*
> ```C
> };
> 
> static void conf_init_defaults_options(struct pal_dns_host_conf* conf) {
> ```

Hmm, but it does not set all options to defaults, only one. This assumes `conf` is already zeroed.


<!-- Sent from Reviewable.io -->

2022-09-26 22:20 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/932)* status: 3 of 5 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @oshogbo)

___
*[`Documentation/manifest-syntax.rst` line 164 at r1](https://reviewable.io/reviews/gramineproject/gramine/932#-NCvgWD8EuVG873PB6O3:-NCvr8QAB4w59W-GWhZ4:b-gjcxn0) ([raw file](https://github.com/gramineproject/gramine/blob/d5f04615a54a0238ff5d84e68a9843b566a4c042/Documentation/manifest-syntax.rst#L164)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Noticed this now: doesn't `|` mean alternative, i.e. this would mean only one option is allowed?
</blockquote></details>

What notion are you suggesting then?
`options [ends0] [inet6] ...` ?
___
*[`libos/src/fs/etc/fs.c` line 49 at r1](https://reviewable.io/reviews/gramineproject/gramine/932#-NCvhLSV3l7XesQsHyf4:-NCvrOBj3Slqnxuko901:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d5f04615a54a0238ff5d84e68a9843b566a4c042/libos/src/fs/etc/fs.c#L49)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

We use `+` on new line
</blockquote></details>

Done.
___
*[`libos/src/fs/etc/fs.c` line 54 at r1](https://reviewable.io/reviews/gramineproject/gramine/932#-NCvg2_E1wYfCm3s2cUM:-NCvrPb_6pKMI7FNut8-:bl9irxp) ([raw file](https://github.com/gramineproject/gramine/blob/d5f04615a54a0238ff5d84e68a9843b566a4c042/libos/src/fs/etc/fs.c#L54)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`%hhu` could be three digit
</blockquote></details>

We still limit it to two digit in pal.
___
*[`libos/src/fs/etc/fs.c` line 55 at r1](https://reviewable.io/reviews/gramineproject/gramine/932#-NCvftNyEdh9cdwip1ij:-NCvrmY90J9f-hkq1H-C:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d5f04615a54a0238ff5d84e68a9843b566a4c042/libos/src/fs/etc/fs.c#L55)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Can we have this string as some define/constant? It's used in two places.
</blockquote></details>

Done.



_Code quote:_
```C
options ndots:
```
___
*[`libos/src/fs/etc/fs.c` line 120 at r1](https://reviewable.io/reviews/gramineproject/gramine/932#-NCvhXqn29PuewcFhQQ-:-NCvrn691LxsSHiKK5yT:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d5f04615a54a0238ff5d84e68a9843b566a4c042/libos/src/fs/etc/fs.c#L120)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Lacks `\n`?
</blockquote></details>

Done.
___
*[`pal/src/host/linux-common/etc_host_info.c` line 287 at r1](https://reviewable.io/reviews/gramineproject/gramine/932#-NCvhudy1riqX62tpk-Q:-NCvru6w-8Qu2ZdD1lvD:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d5f04615a54a0238ff5d84e68a9843b566a4c042/pal/src/host/linux-common/etc_host_info.c#L287)):*
> ```C
>     } else if (strcmp(option, "inet6") == 0) {
>         conf->inet6 = true;
>     } else if (strncmp(option, "ndots:", sizeof("ndots:") - 1) == 0) {
> ```

Done.
___
*[`pal/src/host/linux-common/etc_host_info.c` line 314 at r1](https://reviewable.io/reviews/gramineproject/gramine/932#-NCvkBlHBOCtfkjFDn56:-NCvrzq0CSmns5DLlJhB:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d5f04615a54a0238ff5d84e68a9843b566a4c042/pal/src/host/linux-common/etc_host_info.c#L314)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Hmm, but it does not set all options to defaults, only one. This assumes `conf` is already zeroed.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-09-26 22:38 UTC, oshogbo reviewed
Seems like unrelated test failed:
```
AssertionError: Command ['/home/jenkins/workspace/graphene-debug-18.04/usr/lib/x86_64-linux-gnu/gramine/direct/loader', '/home/jenkins/workspace/graphene-debug-18.04/usr/lib/x86_64-linux-gnu/gramine/direct/libpal.so', 'init', 'truncate', 'tmp/output/1a', 'tmp/output/1b', '17'] timed out after 10 s
```

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/932#-:-NCvwjdq6luLZ93MT8eV:b5aew4k)* status: 3 of 5 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @oshogbo)



<!-- Sent from Reviewable.io -->

2022-09-27 08:05 UTC, dimakuv requested changes
> Reviewed 3 of 5 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/932)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/932#-NCveanj54qGQ62UF-4p:-NCxxSov5TuvDaQdZThK:bzbvl7v) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

What's the point of `ndots:n` and `use-vs`? We've not seen them in any setup and the conclusion from #889 was unclear. I'm not saying we don't want them, but if nobody is going to ever use them, then we just increase attack surface...
</blockquote></details>

I would vote for removing `ndots:n`. We haven't seen it anywhere, and its parsing is non-trivial (very simple, but still non-trivial).

I am not against `use-vs`. It's just a boolean, and it is super-simple to parse. I mean, it doesn't introduce any new logic to Gramine.

So, let's keep only `edns0` and `use-vc`. That's my take on it. Then the PR will be even more trivial.

___
___
*[`Documentation/manifest-syntax.rst` line 164 at r1](https://reviewable.io/reviews/gramineproject/gramine/932#-NCvgWD8EuVG873PB6O3:-NCxyEvh25yMd3nDwYaJ:b65warf) ([raw file](https://github.com/gramineproject/gramine/blob/d5f04615a54a0238ff5d84e68a9843b566a4c042/Documentation/manifest-syntax.rst#L164)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

What notion are you suggesting then?
`options [ends0] [inet6] ...` ?
</blockquote></details>

I like the proposed notion by @oshogbo 
___
*[`pal/src/host/linux-common/etc_host_info.c` line 314 at r1](https://reviewable.io/reviews/gramineproject/gramine/932#-NCvkBlHBOCtfkjFDn56:-NCxyaRH2R21mWj4f_Bn:b74cg7l) ([raw file](https://github.com/gramineproject/gramine/blob/d5f04615a54a0238ff5d84e68a9843b566a4c042/pal/src/host/linux-common/etc_host_info.c#L314)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

This function won't be needed when we remove `ndots`?


<!-- Sent from Reviewable.io -->

2022-09-27 09:22 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/932)* status: 0 of 5 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "squash! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/932#-NCveanj54qGQ62UF-4p:-NCyFNmr60OH6GzX8C0u:b-896fix) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I would vote for removing `ndots:n`. We haven't seen it anywhere, and its parsing is non-trivial (very simple, but still non-trivial).

I am not against `use-vs`. It's just a boolean, and it is super-simple to parse. I mean, it doesn't introduce any new logic to Gramine.

So, let's keep only `edns0` and `use-vc`. That's my take on it. Then the PR will be even more trivial.
</blockquote></details>

Done.

___
___
*[`Documentation/manifest-syntax.rst` line 164 at r1](https://reviewable.io/reviews/gramineproject/gramine/932#-NCvgWD8EuVG873PB6O3:-NCyDXMRBWCoOKzIy_ZG:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d5f04615a54a0238ff5d84e68a9843b566a4c042/Documentation/manifest-syntax.rst#L164)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I like the proposed notion by @oshogbo 
</blockquote></details>

Done.
___
*[`pal/src/host/linux-common/etc_host_info.c` line 314 at r1](https://reviewable.io/reviews/gramineproject/gramine/932#-NCvkBlHBOCtfkjFDn56:-NCy2ihH5VU611bA992l:bb77ufg) ([raw file](https://github.com/gramineproject/gramine/blob/d5f04615a54a0238ff5d84e68a9843b566a4c042/pal/src/host/linux-common/etc_host_info.c#L314)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This function won't be needed when we remove `ndots`?
</blockquote></details>

Yes.


<!-- Sent from Reviewable.io -->

2022-09-27 09:58 UTC, dimakuv submitted a review, later dismissed
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/932)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "squash! " found in commit messages' one-liners (waiting on @boryspoplawski)



<!-- Sent from Reviewable.io -->

2022-09-27 15:37 UTC, mkow approved these changes
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/932)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), "squash! " found in commit messages' one-liners (waiting on @boryspoplawski)



<!-- Sent from Reviewable.io -->

2022-09-27 15:49 UTC, boryspoplawski approved these changes
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/932)* status: all files reviewed, 1 unresolved discussion, "squash! " found in commit messages' one-liners (waiting on @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/932#-NCzboig1Ki9JN16MLSv:-NCzbjk-BFbBws466L-w:bhqd7uc) (no related file):*
> Seems like unrelated test failed:

How do you know it's unrelated? Did you try to reproduce it?
This PR adds/changes code that's run on each process/enclave startup, so every test could potentially be related.
Also, even if it was unrelated, we need to investigate it anyway. Since Jenkins RNG pointed at you PR (if it was really unrelated), you can have the privilege :)

___
___
*[`libos/src/fs/etc/fs.c` line 54 at r1](https://reviewable.io/reviews/gramineproject/gramine/932#-NCvg2_E1wYfCm3s2cUM:-NCzcUtPBqd1FwTohh1w:bfowlxe) ([raw file](https://github.com/gramineproject/gramine/blob/d5f04615a54a0238ff5d84e68a9843b566a4c042/libos/src/fs/etc/fs.c#L54)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

We still limit it to two digit in pal.
</blockquote></details>

But it wasn't obvious here, at least an assert was due.


<!-- Sent from Reviewable.io -->

2022-10-04 14:19 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/932)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @oshogbo)



<!-- Sent from Reviewable.io -->

2022-10-04 14:30 UTC, boryspoplawski requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/932)* status: all files reviewed, 1 unresolved discussion (waiting on @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/932#-NCzboig1Ki9JN16MLSv:-NDYOpHs1Vc-q3L2vlAl:b-isv2xe) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

> Seems like unrelated test failed:

How do you know it's unrelated? Did you try to reproduce it?
This PR adds/changes code that's run on each process/enclave startup, so every test could potentially be related.
Also, even if it was unrelated, we need to investigate it anyway. Since Jenkins RNG pointed at you PR (if it was really unrelated), you can have the privilege :)
</blockquote></details>

ping @oshogbo 

___


<!-- Sent from Reviewable.io -->

2022-10-04 14:32 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/932)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/932#-NCzboig1Ki9JN16MLSv:-NDYPKIvAJALidl5LL0i:bssehjg) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ping @oshogbo 
</blockquote></details>

Now I also block since we decided (offline) to debug this finally. Mariusz will debug this hopefully, once he's back.

___


<!-- Sent from Reviewable.io -->

2022-10-13 10:49 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/932)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski and @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/932#-NCzboig1Ki9JN16MLSv:-NEFx8gFAMnNZr-NLZ1L:bs59frg) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Now I also block since we decided (offline) to debug this finally. Mariusz will debug this hopefully, once he's back.
</blockquote></details>

Yes, I tried to reproduce it locally. The rerun of the tests is passing.
I assumes that this is related to file systems tests failing sometimes on Jenkins.
The test which failed doesn't even uses new functionality.
I don't think that this should block this PR.

That said I can investigate it, but I propose not to block this PR.

___


<!-- Sent from Reviewable.io -->

2022-10-13 11:43 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/932)* status: all files reviewed, 1 unresolved discussion (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/932#-NCzboig1Ki9JN16MLSv:-NEG8YbZ2W-df4mZPPNU:b-psbbie) (no related file):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Yes, I tried to reproduce it locally. The rerun of the tests is passing.
I assumes that this is related to file systems tests failing sometimes on Jenkins.
The test which failed doesn't even uses new functionality.
I don't think that this should block this PR.

That said I can investigate it, but I propose not to block this PR.
</blockquote></details>

Yes, I also tried to reproduce locally and gave up.

I'm unblocking this PR. But it would be good if @oshogbo could trigger this on CI (in some dummy testing PR) with some Gramine debug info and figure out what is the root cause of these.

___


<!-- Sent from Reviewable.io -->

2022-10-13 12:46 UTC, boryspoplawski approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/932)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-10-13 12:59 UTC, dimakuv approved these changes
> Reviewed 1 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/932)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2022-10-13 13:03 UTC, boryspoplawski approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/932)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-10-13 13:59 UTC, merged