Update the manifest defaults for importing numpy package
gramineproject/gramine pull request #938
Opened 2022-09-28 11:17 UTC by TejaswineeL

Signed-off-by: TejaswineeL <tejaswinee.ramdas.langhe@intel.com>

## Description of the changes 
-test_numpy.py executable imports a package called Numpy
-While executing test_numpy.py with SGX, it demands an extra space to load the package to enclave.
-Increase the enclave size to 1G and internal pal memory size to 128M (for manifest). This resolves the insufficient space issue.
-OMP_num_threads limits the number of Numpy threads creation.
-During runtime, SGX requests for python local installation path and in turn the Numpy package location. 
-Add the relevant path in the SGX trusted files.

## How to test this PR? 
-run test-numpy.py file from the python examples with "gramine-sgx ./python scripts/test-numpy.py"
-the .py file should successfully execute by importing numpy package with SGX

2022-09-28 14:48 UTC, boryspoplawski requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/938)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @TejaswineeL)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/938#-ND3X5emC9MCyY2h7aBO):*
https://gramine.readthedocs.io/en/stable/devel/contributing.html
___
*[`CI-Examples/python/python.manifest.template` line 12 at r1](https://reviewable.io/reviews/gramineproject/gramine/938#-ND3ZPzc6nEjQv-9WOR5:-ND3ZPzc6nEjQv-9WOR6:buxhc4j) ([raw file](https://github.com/gramineproject/gramine/blob/39665034218065dadf28bd0d9adbf9e5b144b3c4/CI-Examples/python/python.manifest.template#L12)):*
> ```
> loader.insecure__use_cmdline_argv = true
> 
> loader.env.OMP_NUM_THREADS = "4"
> ```

Why do we even need this?
___
*[`CI-Examples/python/python.manifest.template` line 14 at r1](https://reviewable.io/reviews/gramineproject/gramine/938#-ND3ZFYf-9JGIkvXXZvN:-ND3ZFYf-9JGIkvXXZvO:b3vxgjx) ([raw file](https://github.com/gramineproject/gramine/blob/39665034218065dadf28bd0d9adbf9e5b144b3c4/CI-Examples/python/python.manifest.template#L14)):*
> ```
> loader.env.OMP_NUM_THREADS = "4"
> 
> loader.pal_internal_mem_size = "128M"
> ```

Isn't `64` enough?
It works for me, but this depends solely on the number of python packages you have installed.
___
*[`CI-Examples/python/python.manifest.template` line 52 at r1](https://reviewable.io/reviews/gramineproject/gramine/938#-ND3ZSYT9DgMVPb6py3G:-ND3ZSYT9DgMVPb6py3H:b-7io0bq) ([raw file](https://github.com/gramineproject/gramine/blob/39665034218065dadf28bd0d9adbf9e5b144b3c4/CI-Examples/python/python.manifest.template#L52)):*
> ```
>   "file:/etc/mime.types",
>   "file:/etc/default/apport",
>   "file:{{ python.get_path('stdlib', vars={'installed_base': '/usr/local'}) }}/",
> ```

Why? `python.stdlib` is covered above, why it's not enough?


<!-- Sent from Reviewable.io -->

2022-09-29 07:12 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/938)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski and @TejaswineeL)

___
*[`CI-Examples/python/python.manifest.template` line 12 at r1](https://reviewable.io/reviews/gramineproject/gramine/938#-ND3ZPzc6nEjQv-9WOR5:-ND74KOQ0DhXx0vvQ8-r:b-wjwreg) ([raw file](https://github.com/gramineproject/gramine/blob/39665034218065dadf28bd0d9adbf9e5b144b3c4/CI-Examples/python/python.manifest.template#L12)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why do we even need this?
</blockquote></details>

This is actually useful. NumPy spawns as many threads as there are CPU cores. And each thread eats up some memory. On large machines, this results in a lot of enclave memory being eaten, which results in `512M` or `1G` not being enough.

This is the same problem as manifested here: https://github.com/gramineproject/examples/commit/f2c2d2599c9893a27ab2afc73c19a92dd2ed7661

Actually, this line is the only one that I consider useful in this PR. I would also recommend to **add a comment here**.
___
*[`CI-Examples/python/python.manifest.template` line 14 at r1](https://reviewable.io/reviews/gramineproject/gramine/938#-ND3ZFYf-9JGIkvXXZvN:-ND74HudDzxKV5fdoh9l:b55r5xc) ([raw file](https://github.com/gramineproject/gramine/blob/39665034218065dadf28bd0d9adbf9e5b144b3c4/CI-Examples/python/python.manifest.template#L14)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Isn't `64` enough?
It works for me, but this depends solely on the number of python packages you have installed.
</blockquote></details>

Works for me as well.
___
*[`CI-Examples/python/python.manifest.template` line 52 at r1](https://reviewable.io/reviews/gramineproject/gramine/938#-ND3ZSYT9DgMVPb6py3G:-ND736ODCjIX5KFx8MF-:b-p6qfkl) ([raw file](https://github.com/gramineproject/gramine/blob/39665034218065dadf28bd0d9adbf9e5b144b3c4/CI-Examples/python/python.manifest.template#L52)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why? `python.stdlib` is covered above, why it's not enough?
</blockquote></details>

Same question. The added path seems to be for the case of `numpy` being installed through `pip install`?

But our README instructs the user to install `numpy` through `apt install`: https://github.com/gramineproject/gramine/tree/master/CI-Examples/python#installing-prerequisites

So when NumPy is installed according to our README, we get it under `/usr/lib/python3/dist-packages/...`, see https://packages.ubuntu.com/focal/amd64/python3-numpy/filelist. And this is covered by `python.distlib`: https://gramine.readthedocs.io/en/latest/manpages/gramine-manifest.html#functions-and-constants-available-in-templates


<!-- Sent from Reviewable.io -->

2022-09-29 13:27 UTC, TejaswineeL commented
[CI-Examples/python/python.manifest.template line 52 at r1](https://reviewable.io/reviews/gramineproject/gramine/938#-ND3ZSYT9DgMVPb6py3G:-ND736ODCjIX5KFx8MF-:b-p6qfkl) ([raw file](https://github.com/gramineproject/gramine/blob/39665034218065dadf28bd0d9adbf9e5b144b3c4/CI-Examples/python/python.manifest.template#L52)):

When numpy package is installed using "sudo apt-get install python3-numpy", the package gets stored at /usr/lib/python3/dist-packages/. Also, when "import numpy" executes , it flashes an error because of some incompatibility :  "cannot import name 'multiarray' from 'numpy.core' (/usr/lib/python3/dist-packages/numpy/core/__init__.py)" [i made sure installed numpy package is not broken]

To solve the above error if we install numpy package using "pip install numpy" [which is a recommended way of installing a package], the package gets stored at "/usr/local/lib/python3.7/" 
That is where the newly added line to the trusted files comes to the picture.
the path -"file:{{ python.get_path('stdlib', vars={'installed_base': '/usr/local'}) }}/" **expands to** "/usr/local/lib/python3.7/"

[CI-Examples/python/python.manifest.template line 12 at r1](https://reviewable.io/reviews/gramineproject/gramine/938#-ND3ZPzc6nEjQv-9WOR5:-ND3ZPzc6nEjQv-9WOR6:buxhc4j) ([raw file](https://github.com/gramineproject/gramine/blob/39665034218065dadf28bd0d9adbf9e5b144b3c4/CI-Examples/python/python.manifest.template#L12)):

Numpy script is expected to work with the default configuration. 
without the line loader.env.OMP_NUM_THREADS = "4", we need to have bigger enclave size like 16G etc. as Threads spawned by Numpy go on consuming memory till a memory fault.

2022-09-29 16:10 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/938)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski, @dimakuv, and @TejaswineeL)

___
*[`CI-Examples/python/python.manifest.template` line 12 at r1](https://reviewable.io/reviews/gramineproject/gramine/938#-ND3ZPzc6nEjQv-9WOR5:-ND9-6On7wK3i-8vLT0o:bfryid6) ([raw file](https://github.com/gramineproject/gramine/blob/39665034218065dadf28bd0d9adbf9e5b144b3c4/CI-Examples/python/python.manifest.template#L12)):*
<details><summary><i>Previously, TejaswineeL wrote…</i></summary><blockquote>

Numpy script is expected to work with the default configuration. 
without the line loader.env.OMP_NUM_THREADS = "4", we need to have bigger enclave size like 16G etc. as Threads spawned by Numpy go on consuming memory till a memory fault.

</blockquote></details>

A comment is due then
___
*[`CI-Examples/python/python.manifest.template` line 52 at r1](https://reviewable.io/reviews/gramineproject/gramine/938#-ND3ZSYT9DgMVPb6py3G:-ND9-SDK3RyKpEh8xKsy:bjx4pq3) ([raw file](https://github.com/gramineproject/gramine/blob/39665034218065dadf28bd0d9adbf9e5b144b3c4/CI-Examples/python/python.manifest.template#L52)):*
> "pip install numpy"

But we don't have anything like that in the readme, so something must be fixed (either manifest or readme). I don't have time atm to dig into this example atm to see what we should do, so cannot recommend anything


<!-- Sent from Reviewable.io -->

2022-09-30 07:50 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/938)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski, @dimakuv, and @TejaswineeL)

___
*[`CI-Examples/python/python.manifest.template` line 52 at r1](https://reviewable.io/reviews/gramineproject/gramine/938#-ND3ZSYT9DgMVPb6py3G:-NDCMdrVCACyp9ffmObH:bkymjh9) ([raw file](https://github.com/gramineproject/gramine/blob/39665034218065dadf28bd0d9adbf9e5b144b3c4/CI-Examples/python/python.manifest.template#L52)):*
> When numpy package is installed using "sudo apt-get install python3-numpy", the package gets stored at /usr/lib/python3/dist-packages/. Also, when "import numpy" executes , it flashes an error because of some incompatibility :  "cannot import name 'multiarray' from 'numpy.core' (/usr/lib/python3/dist-packages/numpy/core/init.py)" [i made sure installed numpy package is not broken]

This error needs to be analyzed. This error doesn't make sense to me -- you're saying that the `python3-numpy` package is broken in official Ubuntu repository? I don't believe that.

Could you please dig deeper into this? On my local machine, this way of installing NumPy (`sudo apt-get install python3-numpy`) works fine. Please try with a fresh clean machine (a VM or a Docker container) and understand the root cause.


<!-- Sent from Reviewable.io -->

2022-10-04 11:44 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/938)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski and @TejaswineeL)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/938#-NDXnGQ94R20LngCQNU2:-NDXnGQADU8sWSRsmPqr:b-po3jvy) (no related file):*
@tejaswineel For the future, please do **not** use `git push --force` when we're in the middle of reviewing. Please use `git commit --fixup` flow. See https://gramine.readthedocs.io/en/stable/devel/onboarding.html#typical-gramine-development-flows, steps 8 and 9.

___
___
*[`CI-Examples/python/python.manifest.template` line 12 at r1](https://reviewable.io/reviews/gramineproject/gramine/938#-ND3ZPzc6nEjQv-9WOR5:-NDXnm4n7-UH9YvHi8zP:b8uoeal) ([raw file](https://github.com/gramineproject/gramine/blob/b8bd6d9c1a85f16c9a01216ae4dbb4959ad4f58b/CI-Examples/python/python.manifest.template#L12)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

A comment is due then
</blockquote></details>

@tejaswineel Will you add the comment?


<!-- Sent from Reviewable.io -->

2022-10-04 11:44 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/938)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski and @TejaswineeL)

___
*[`CI-Examples/python/python.manifest.template` line 12 at r2](https://reviewable.io/reviews/gramineproject/gramine/938#-NDXnvDHA7cbg_XRvdyf:-NDXnvDHA7cbg_XRvdyg:b-u96k0i) ([raw file](https://github.com/gramineproject/gramine/blob/36168d5a9543acd85760d4fdfd9cfdc66fb00152/CI-Examples/python/python.manifest.template#L12)):*
> ```
> loader.insecure__use_cmdline_argv = true
> 
> loader.env.OMP_NUM_THREADS = "4"
> ```

Also, please move this new line to right-after `loader.env.LD_LIBRARY_PATH` -- it's best to group environment variables together.


<!-- Sent from Reviewable.io -->

2022-10-04 15:12 UTC, boryspoplawski requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/938)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski, @dimakuv, and @TejaswineeL)

___
*[`CI-Examples/python/python.manifest.template` line 14 at r1](https://reviewable.io/reviews/gramineproject/gramine/938#-ND3ZFYf-9JGIkvXXZvN:-NDYYKwAELQyvVaVo_hK:bob7g42) ([raw file](https://github.com/gramineproject/gramine/blob/b8bd6d9c1a85f16c9a01216ae4dbb4959ad4f58b/CI-Examples/python/python.manifest.template#L14)):*
<details><summary><i>Previously, TejaswineeL (Tejaswinee) wrote…</i></summary><blockquote>

I have more number of packages installed, thats why i had to use pal_internal_mem_size as 128M.
As it works with 64M for you. I removed the line (as its default value is 64M)

</blockquote></details>

`pal_internal_mem_size` defaults to `0`, so it needs to stay here (just change it to 64)


<!-- Sent from Reviewable.io -->

2022-11-03 05:36 UTC, anjalirai-intel commented
Any ideas on merging this PR

2022-11-03 07:49 UTC, dimakuv reviewed
@anjalirai-intel We just need a comment to be added for `OMP_NUM_THREADS`. Other than that, the PR looks ok.

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/938#-:-NFwScXb3aDb5SM4YxmO:b1xlefk)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski and @TejaswineeL)



<!-- Sent from Reviewable.io -->

2022-11-15 07:54 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/938)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski and @TejaswineeL)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/938#-NGuGvcfEKy94kt09RsX:-NGuGvcgEjrcj05iiAet:b-bpvlyh) (no related file):*
So will anyone finish this PR, or should I take over?

My and Borys's comments are pending for several weeks already, and I see no updates from the original author.

___


<!-- Sent from Reviewable.io -->

2022-11-15 09:37 UTC, TejaswineeL commented
After the suggestions, I tried the CI-examples on a fresh system and found that we don't need to make any changes to the manifest template in order to run the examples with SGX

However, adding OMP_NUM_THREADS was considered useful during the conversation
@dimakuv   kindly, let me know if I should go ahead and add OMP_NUM_THREADS  line change or else we can cancel this PR

2022-11-15 09:38 UTC, anjalirai-intel commented
@TejaswineeL we need this changes for Ubuntu 22.04, CentOS and RHEL machines

2022-11-15 09:57 UTC, dimakuv reviewed
> let me know if I should go ahead and add OMP_NUM_THREADS line change

Yes, please. Also see @anjalirai-intel's reply.

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/938#-:-NGui8ug8vFvxv-AA2R4:b-pi2ev9)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski and @TejaswineeL)



<!-- Sent from Reviewable.io -->

2022-11-15 10:26 UTC, TejaswineeL commented
https://github.com/gramineproject/gramine/pull/938#issuecomment-1315044132

@dimakuv  any specific comment we need to add for loader.env.OMP_NUM_THREADS

how about a comment
#To limit the number of threads created

2022-11-15 10:36 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/938)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski and @TejaswineeL)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/938#-NGuqVcS2dzCEx3yrm8G:-NGuqVcT3J0jZdy2eIiG:br5flms) (no related file):*
@tejaswineel Please use the Reviewable plugin to GitHub (the big purple button in the PR description) to have conversations.

___
___
*[`CI-Examples/python/python.manifest.template` line 12 at r1](https://reviewable.io/reviews/gramineproject/gramine/938#-ND3ZPzc6nEjQv-9WOR5:-NGuqgc968Ol-w5Hr1Wo:b8c1l7n) ([raw file](https://github.com/gramineproject/gramine/blob/b8bd6d9c1a85f16c9a01216ae4dbb4959ad4f58b/CI-Examples/python/python.manifest.template#L12)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@tejaswineel Will you add the comment?
</blockquote></details>

I suggest a comment like this:
```
# Python's NumPy spawns as many threads as there are CPU cores, and each thread
# consumes a chunk of memory, so on large machines 1G enclave size may be not enough.
# We limit the number of spawned threads via OMP_NUM_THREADS env variable.
```

(Please re-wrap my proposed comment to 100-chars-per-line limit.)


<!-- Sent from Reviewable.io -->

2022-11-15 18:07 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/938)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @TejaswineeL)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/938#-NGuqVcS2dzCEx3yrm8G:-NGwTCFU4EvNwsMJZ0so:b-xw23sf) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@tejaswineel Please use the Reviewable plugin to GitHub (the big purple button in the PR description) to have conversations.
</blockquote></details>

@tejaswineel Once you've fixed some comment from a reviewer, you need to get into Reviewable and click "Done" at that comment.

___
___
*[`CI-Examples/python/python.manifest.template` line 12 at r1](https://reviewable.io/reviews/gramineproject/gramine/938#-ND3ZPzc6nEjQv-9WOR5:-NGwT0YP-7E8Yrt3iItO:b-iapb30) ([raw file](https://github.com/gramineproject/gramine/blob/b8bd6d9c1a85f16c9a01216ae4dbb4959ad4f58b/CI-Examples/python/python.manifest.template#L12)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I suggest a comment like this:
```
# Python's NumPy spawns as many threads as there are CPU cores, and each thread
# consumes a chunk of memory, so on large machines 1G enclave size may be not enough.
# We limit the number of spawned threads via OMP_NUM_THREADS env variable.
```

(Please re-wrap my proposed comment to 100-chars-per-line limit.)
</blockquote></details>

You missed `...consumes a chunk...`
___
*[`CI-Examples/python/python.manifest.template` line 12 at r2](https://reviewable.io/reviews/gramineproject/gramine/938#-NDXnvDHA7cbg_XRvdyf:-NGwT5kYAycEWeamsvkw:bxjz3cg) ([raw file](https://github.com/gramineproject/gramine/blob/36168d5a9543acd85760d4fdfd9cfdc66fb00152/CI-Examples/python/python.manifest.template#L12)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Also, please move this new line to right-after `loader.env.LD_LIBRARY_PATH` -- it's best to group environment variables together.
</blockquote></details>

You didn't do that.


<!-- Sent from Reviewable.io -->

2022-11-16 07:55 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/938)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @TejaswineeL)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/938#-NGuqVcS2dzCEx3yrm8G:-NGzQdJO6mW150a2i4Da:bchqqzy) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@tejaswineel Once you've fixed some comment from a reviewer, you need to get into Reviewable and click "Done" at that comment.
</blockquote></details>

@tejaswineel You didn't mark the comments in Reviewable...

___
___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/938#-ND3X5emC9MCyY2h7aBO):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

https://gramine.readthedocs.io/en/stable/devel/contributing.html
</blockquote></details>

I'll change the title during final rebase to `[CI-Examples] Add OMP_NUM_THREADS envvar in Python example`
___
*[`CI-Examples/python/python.manifest.template` line 12 at r2](https://reviewable.io/reviews/gramineproject/gramine/938#-NDXnvDHA7cbg_XRvdyf:-NGzQCLN8Wcr25VdILGE:b-q59rpr) ([raw file](https://github.com/gramineproject/gramine/blob/36168d5a9543acd85760d4fdfd9cfdc66fb00152/CI-Examples/python/python.manifest.template#L12)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You didn't do that.
</blockquote></details>

Done now.


<!-- Sent from Reviewable.io -->

2022-11-16 15:58 UTC, boryspoplawski submitted a review, later dismissed
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/938)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @TejaswineeL)



<!-- Sent from Reviewable.io -->

2022-11-16 18:56 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/938)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/938#-ND3X5emC9MCyY2h7aBO):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I'll change the title during final rebase to `[CI-Examples] Add OMP_NUM_THREADS envvar in Python example`
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2022-11-16 18:56 UTC, dimakuv commented
Jenkins, test this please

2022-11-16 19:05 UTC, boryspoplawski approved these changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/938)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-11-16 19:56 UTC, merged