[CI-Examples] Use `--malicious-quote` arg for ra-tls-mbedtls server
gramineproject/gramine pull request #943
Opened 2022-09-29 08:42 UTC by dimakuv

## Description of the changes 

Previously, the server in the `ra-tls-mbedtls` example corrupted the SGX quote (for testing purposes) when it was started with *any* arguments. With this commit, the server recognizes only `--malicious-quote` arg and complains on other arguments. This change prevents users from accidentally corrupting the SGX quote when they mistype something like `gramine-sgx server dcap`.

For the context, see https://github.com/gramineproject/gramine/issues/941.

## How to test this PR? 

CI is enough (it tests `make check_epid_fail`). I also tested manually on an EPID machine and on a Azure DCAP machine.

2022-09-29 13:16 UTC, mkow requested changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/943)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/943#-ND8Lptp2BV6ETpsQbie:-ND8LptqDqqNi9fdCpcr:b-i2tp8h) (no related file):*
Today's lesson: IFing on `argc` without checking the contents is a bad design, we should never do this again, even in tests :)

___
___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/943#-ND8NT5b8KYjuvx5xeB5):*
(just to make it clear that the only purpose for it is testing)



_Suggestion:_
```
`--test-malicious-quote`
```


<!-- Sent from Reviewable.io -->

2022-09-29 13:24 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/943)* status: 0 of 3 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/943#-ND8NT5b8KYjuvx5xeB5):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

(just to make it clear that the only purpose for it is testing)
</blockquote></details>

Done.
___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/943#-ND8PgBjD40jbGVvz8mz):*
Blocking myself to fix the commit message: change to `--test-malicious-quote` everywhere.


<!-- Sent from Reviewable.io -->

2022-09-29 13:40 UTC, mkow reviewed
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/943)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2022-09-29 13:41 UTC, mkow submitted a review, later dismissed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/943)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2022-09-29 15:50 UTC, boryspoplawski submitted a review, later dismissed
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/943)* status: all files reviewed, 3 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/gramineproject/gramine/943#-ND8vmP6ElOlDwFeB6TI):*
Maybe `Add` instead of `Use`? `Use` sounds like the argument was there before.


<!-- Sent from Reviewable.io -->

2022-10-04 07:01 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/943)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski and @mkow)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/943#-ND8PgBjD40jbGVvz8mz):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Blocking myself to fix the commit message: change to `--test-malicious-quote` everywhere.
</blockquote></details>

Done
___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/gramineproject/gramine/943#-ND8vmP6ElOlDwFeB6TI):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Maybe `Add` instead of `Use`? `Use` sounds like the argument was there before.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-10-04 13:29 UTC, boryspoplawski approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/943)* status: all files reviewed, 1 unresolved discussion (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2022-10-04 14:12 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/943)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-10-04 14:15 UTC, merged