[LibOS] Strip trailing spaces in the shebang line
gramineproject/gramine pull request #944
Opened 2022-09-29 10:40 UTC by dimakuv

## Description of the changes 

Previously, the "load shebang" logic didn't strip trailing spaces, which resulted in additional empty arguments to the interpreter (e.g., `#!/bin/bash ` was interpreted as "start `/bin/bash` with the first argument ` `" -- and Bash failed because it expected the first argument to be the program to run).

Kudos to @svenkata9 for finding this bug. It was found on one Docker image that had such a problematic entrypoint Bash script (with trailing spaces in the shebang line), when trying to graminize this image via GSC.

## How to test this PR? 

CI is enough. Modified the `test_212_shebang_test_script` example (the Bash script) to contain trailing spaces.

Without this PR, the modified example fails like this:
```
test_libos.py:244: in test_212_shebang_test_script
    stdout, _ = self.run_binary(['shebang_test_script'])
../../../built-debug/lib/python3.8/site-packages/graminelibos/regression.py:221: in run_binary
    _returncode, stdout, stderr = run_command(cmd, timeout=timeout, **kwds)
../../../built-debug/lib/python3.8/site-packages/graminelibos/regression.py:159: in run_command
    raise subprocess.CalledProcessError(proc.returncode, cmd, raw_stdout, raw_stderr)
E   subprocess.CalledProcessError: Command '['/home/dimakuv/gramineproject/gramine/built-debug/lib/x86_64-linux-gnu/gramine/direct/loader', '/home/dimakuv/gramineproject/gramine/built-debug/lib/x86_64-linux-gnu/gramine/direct/libpal.so', 'init', 'shebang_test_script']' returned non-zero exit status 127.

[0.020] /bin/sh: 0: Can't open
```

2022-09-29 14:32 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/944)* status: 0 of 3 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/gramineproject/gramine/944#-ND8eAj129F-dRW-OLPp):*
TODO(myself): add that we also skip tabs, as Linux does. At final rebase. Something like this:
```
[LibOS] Strip trailing spaces/tabs in the shebang line

Previously, the "load shebang" logic didn't strip trailing spaces/tabs, which
resulted in additional empty arguments to the interpreter (e.g.,
`#!/bin/bash ` was interpreted as "start `/bin/bash` with the first
argument ` `" -- and Bash failed because it expected the first argument
to be the program to run). This commit also adds handling of tabs in addition
to spaces.
```
___
*[`libos/src/libos_rtld.c` line 607 at r1](https://reviewable.io/reviews/gramineproject/gramine/944#-ND8QDGL3TukOfCvrFnh:-ND8V_wz4iBEYx3T2c_6:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/6588d27b3c35045dcc043a4753728db9aeb6501a/libos/src/libos_rtld.c#L607)):*
> ```C
>     shebang[shebang_len] = 0;
> 
>     /* Strip extra space characters */
> ```

Done.
___
*[`libos/src/libos_rtld.c` line 609 at r1](https://reviewable.io/reviews/gramineproject/gramine/944#-ND8RUna-WOARDOnuwop:-ND8U7_gDaF7gfSWvcEQ:b8ancsg) ([raw file](https://github.com/gramineproject/gramine/blob/6588d27b3c35045dcc043a4753728db9aeb6501a/libos/src/libos_rtld.c#L609)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Only partially related to this PR, but how does this loop work? It's supposed to strip leading spaces from `shebang` C-string, right? Or something else? I can't understand what it does by reading the code.
</blockquote></details>

Yes. The code iterates through the first characters of the `shebang` string and breaks the loop when the character is not space (`*p != ' '`).

Before breaking the loop, the length of the string (`shebang_len`) is decremented by the number of "iterated-through" (=space) characters. And the `shebang` string is "copied to the left". That's it.
___
*[`libos/src/libos_rtld.c` line 626 at r1](https://reviewable.io/reviews/gramineproject/gramine/944#-ND8Pc5cEQTV5B1owZdD:-ND8Vam22JvWHtdnhAx_:b-75qgl4) ([raw file](https://github.com/gramineproject/gramine/blob/6588d27b3c35045dcc043a4753728db9aeb6501a/libos/src/libos_rtld.c#L626)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Is Linux trimming only spaces? Please verify with the sources.
</blockquote></details>

Done. Fixed here and everywhere else.

https://github.com/torvalds/linux/blob/af2d861d4cd2a4da5137f795ee3509e6f944a25b/fs/binfmt_script.c#L60-L79

You're right, Linux trims both spaces and tabs.
___
*[`libos/test/regression/shebang_test_script.sh` line 3 at r1](https://reviewable.io/reviews/gramineproject/gramine/944#-ND8R00c86Gn26pxsM_S:-ND8Un295FfAcYLI5HcO:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/6588d27b3c35045dcc043a4753728db9aeb6501a/libos/test/regression/shebang_test_script.sh#L3)):*
> ```Shell
> #!/bin/sh  
> 
> # the trailing spaces in the shebang line above are for testing purposes
> ```

Done.


<!-- Sent from Reviewable.io -->

2022-09-29 15:01 UTC, boryspoplawski approved these changes
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/944)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[`libos/src/libos_rtld.c` line 639 at r2](https://reviewable.io/reviews/gramineproject/gramine/944#-ND8ie04DdUCTGW_m-iv:-ND8ie04DdUCTGW_m-iw:b-hq35fw) ([raw file](https://github.com/gramineproject/gramine/blob/923e7292e66a9e58b482ddcb16a73fa903b78275/libos/src/libos_rtld.c#L639)):*
> ```C
>         sepptr = spaceptr < tabptr ? spaceptr : tabptr;
>     } else {
>         sepptr = spaceptr ? : tabptr;
> ```

Note sure, but don't we write it without space?



_Suggestion:_
```C
?:
```
___
*[`libos/src/libos_rtld.c` line 649 at r2](https://reviewable.io/reviews/gramineproject/gramine/944#-ND8kSYnAshEDgcCRi9F:-ND8kSYnAshEDgcCRi9G:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/923e7292e66a9e58b482ddcb16a73fa903b78275/libos/src/libos_rtld.c#L649)):*
> ```C
>     }
> 
>     const char* argv_shebang[] = {interp, sepptr ? sepptr : NULL, NULL};
> ```





_Suggestion:_
```C
sepptr
```
___
*[`libos/test/regression/scripts/foo.sh` line 1 at r2](https://reviewable.io/reviews/gramineproject/gramine/944#-ND8kuf-59trauCQ8y6T:-ND8kuf-59trauCQ8y6U:bd0hram) ([raw file](https://github.com/gramineproject/gramine/blob/923e7292e66a9e58b482ddcb16a73fa903b78275/libos/test/regression/scripts/foo.sh#L1)):*
> ```Shell
> #!scripts/bar.sh   ALPHA BRAVO CHARLIE DELTA
> ```

A comment about double space would be nice here as well


<!-- Sent from Reviewable.io -->

2022-09-29 15:02 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/944)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/944#-ND8l8I10e4jpp3onhbP:-ND8l8I10e4jpp3onhbQ:b-dudsm7) (no related file):*
Idk what happened, but reviewable put my disposition as approve even though I put some blocking comments and I noticed only after pressing the publish button...

___


<!-- Sent from Reviewable.io -->

2022-09-30 07:26 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/944)* status: 1 of 3 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[`libos/src/libos_rtld.c` line 639 at r2](https://reviewable.io/reviews/gramineproject/gramine/944#-ND8ie04DdUCTGW_m-iv:-NDCGtw6BBB8oQZempIz:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/923e7292e66a9e58b482ddcb16a73fa903b78275/libos/src/libos_rtld.c#L639)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Note sure, but don't we write it without space?
</blockquote></details>

Done
___
*[`libos/src/libos_rtld.c` line 649 at r2](https://reviewable.io/reviews/gramineproject/gramine/944#-ND8kSYnAshEDgcCRi9F:-NDCGx6b15wlGX8W72SA:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/923e7292e66a9e58b482ddcb16a73fa903b78275/libos/src/libos_rtld.c#L649)):*
> ```C
>     }
> 
>     const char* argv_shebang[] = {interp, sepptr ? sepptr : NULL, NULL};
> ```

Done.
___
*[`libos/test/regression/scripts/foo.sh` line 1 at r2](https://reviewable.io/reviews/gramineproject/gramine/944#-ND8kuf-59trauCQ8y6T:-NDCHFQFEO-31KflSwHA:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/923e7292e66a9e58b482ddcb16a73fa903b78275/libos/test/regression/scripts/foo.sh#L1)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

A comment about double space would be nice here as well
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-09-30 17:56 UTC, boryspoplawski approved these changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/944)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)



<!-- Sent from Reviewable.io -->

2022-10-01 23:39 UTC, mkow requested changes
> Reviewed 1 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/944)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[`libos/src/libos_rtld.c` line 609 at r1](https://reviewable.io/reviews/gramineproject/gramine/944#-ND8RUna-WOARDOnuwop:-NDKgPk-7Gy0dkw1geZ4:b2nn7vj) ([raw file](https://github.com/gramineproject/gramine/blob/6588d27b3c35045dcc043a4753728db9aeb6501a/libos/src/libos_rtld.c#L609)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes. The code iterates through the first characters of the `shebang` string and breaks the loop when the character is not space (`*p != ' '`).

Before breaking the loop, the length of the string (`shebang_len`) is decremented by the number of "iterated-through" (=space) characters. And the `shebang` string is "copied to the left". That's it.
</blockquote></details>

Hmm, first, this is weird - why not just `while` + put the logic outside the loop? Second, it seems slightly incorrect - if shebang is spaces-only then they will be left and probably weird things will happen next, because the code later assumes that they were stripped already?


<!-- Sent from Reviewable.io -->

2022-10-04 08:44 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/944)* status: 2 of 3 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[`libos/src/libos_rtld.c` line 609 at r1](https://reviewable.io/reviews/gramineproject/gramine/944#-ND8RUna-WOARDOnuwop:-NDX9StP4-Xw1Z59j3X6:bm7q6wr) ([raw file](https://github.com/gramineproject/gramine/blob/6588d27b3c35045dcc043a4753728db9aeb6501a/libos/src/libos_rtld.c#L609)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Hmm, first, this is weird - why not just `while` + put the logic outside the loop? Second, it seems slightly incorrect - if shebang is spaces-only then they will be left and probably weird things will happen next, because the code later assumes that they were stripped already?
</blockquote></details>

Done. Fair enough.


<!-- Sent from Reviewable.io -->

2022-10-04 15:06 UTC, boryspoplawski reviewed
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/944)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)



<!-- Sent from Reviewable.io -->

2022-10-04 22:56 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/944)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[`libos/src/libos_rtld.c` line 609 at r1](https://reviewable.io/reviews/gramineproject/gramine/944#-ND8RUna-WOARDOnuwop:-ND_CTl68WR9LhpMSaBV:b-r4und0) ([raw file](https://github.com/gramineproject/gramine/blob/6588d27b3c35045dcc043a4753728db9aeb6501a/libos/src/libos_rtld.c#L609)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. Fair enough.
</blockquote></details>

Much more readable now, and correct! Thanks.


<!-- Sent from Reviewable.io -->

2022-10-05 06:51 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/944)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski and @mkow)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/gramineproject/gramine/944#-ND8eAj129F-dRW-OLPp):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

TODO(myself): add that we also skip tabs, as Linux does. At final rebase. Something like this:
```
[LibOS] Strip trailing spaces/tabs in the shebang line

Previously, the "load shebang" logic didn't strip trailing spaces/tabs, which
resulted in additional empty arguments to the interpreter (e.g.,
`#!/bin/bash ` was interpreted as "start `/bin/bash` with the first
argument ` `" -- and Bash failed because it expected the first argument
to be the program to run). This commit also adds handling of tabs in addition
to spaces.
```
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2022-10-05 09:47 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/944)* status: all files reviewed, 1 unresolved discussion (waiting on @boryspoplawski)



<!-- Sent from Reviewable.io -->

2022-10-05 13:55 UTC, merged