[CI-Examples] Harden Redis example
gramineproject/gramine pull request #954
Opened 2022-10-05 14:59 UTC by dimakuv

## Description of the changes 

After Gramine v1.3, we have nice features and can finally get rid of insecure manifest options.

This PR removes the following insecure manifest options:
- `loader.insecure__use_cmdline_argv` in favor of `loader.argv`,
- `sgx.allowed_files`, they are not needed at all.

## How to test this PR? 

CI is enough. Also tested manually, including on a cloud machine with a public IP and connecting remotely (this was for testing `--protected-mode no`).

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/954)

2022-10-05 15:04 UTC, dimakuv commented
FYI: there will be more PRs like this, removing insecure options from examples. I hope that @oshogbo could help me in this task as well.

2022-10-05 15:31 UTC, mkow requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/954)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`CI-Examples/redis/README.md` line 25 at r1](https://reviewable.io/reviews/gramineproject/gramine/954#-NDcksqs-1diMjWxsZed:-NDcksqs-1diMjWxsZee:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/676a021dee152b5af544d46fb23e22ef7392ec04/CI-Examples/redis/README.md#L25)):*
> ```Markdown
> kill %%
> 
> # run Redis in non-SGX Gramine against a benchmark (args are hard-coded in manifest)
> ```





_Suggestion:_
```Markdown
hardcoded in the manifest
```
___
*[`CI-Examples/redis/README.md` line 49 at r1](https://reviewable.io/reviews/gramineproject/gramine/954#-NDclBq_02kpVk1k2-dF:-NDclBq_02kpVk1k2-dG:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/676a021dee152b5af544d46fb23e22ef7392ec04/CI-Examples/redis/README.md#L49)):*
> ```Markdown
>   clients on all interfaces.
> 
> In Gramine case, these parameters are hard-coded in the manifest file, see
> ```

ditto
___
*[`CI-Examples/redis/redis-server.manifest.template` line 16 at r1](https://reviewable.io/reviews/gramineproject/gramine/954#-NDclKy2AIhbKGNpWKUG:-NDclKy2AIhbKGNpWKUH:bdgjjqm) ([raw file](https://github.com/gramineproject/gramine/blob/fc525b51133c45df90c5bb7026cf209e5eec900c/CI-Examples/redis/redis-server.manifest.template#L16)):*
> ```
> # building process: the default is "error" for non-debug builds, and "debug"
> # for debug builds.
> loader.log_level = "{{ log_level }}"
> ```

What was wrong here?
___
*[`CI-Examples/redis/redis-server.manifest.template` line 20 at r1](https://reviewable.io/reviews/gramineproject/gramine/954#-NDckyED1RWlUfDzSYB4:-NDckyEE9RroIvU_E2cA:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/676a021dee152b5af544d46fb23e22ef7392ec04/CI-Examples/redis/redis-server.manifest.template#L20)):*
> ```
> ################################# ARGUMENTS ###################################
> 
> # Hard-code application arguments. See README for explanations.
> ```

ditto


<!-- Sent from Reviewable.io -->

2022-10-05 15:51 UTC, boryspoplawski requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/954)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`CI-Examples/redis/README.md` line 46 at r1](https://reviewable.io/reviews/gramineproject/gramine/954#-NDcoIZj0B8by885fwAu:-NDcoIZk67SW3Af9_HDf:b2x6vpb) ([raw file](https://github.com/gramineproject/gramine/blob/676a021dee152b5af544d46fb23e22ef7392ec04/CI-Examples/redis/README.md#L46)):*
> ```Markdown
> - `protected-mode no` allows clients to connect to Redis on any network
>   interface. Even though we use the loopback interface (which is always allowed
>   in Redis), Gramine hides this information. Therefore, we ask Redis to allow
> ```

I don't understand this comment. If we use loopback anyway, why bother with this argument?


<!-- Sent from Reviewable.io -->

2022-10-05 16:15 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/954)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[`CI-Examples/redis/README.md` line 46 at r1](https://reviewable.io/reviews/gramineproject/gramine/954#-NDcoIZj0B8by885fwAu:-NDcv71q7ih9dzl8zx94:bmtvz85) ([raw file](https://github.com/gramineproject/gramine/blob/676a021dee152b5af544d46fb23e22ef7392ec04/CI-Examples/redis/README.md#L46)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Well, we can also test with public IPs. But I agree, I guess it's fine to keep the default (which is `protected-mode yes`), since we're testing locally. Should I remove this arg? @mkow 
</blockquote></details>

I understood this comment as "we test only loopack because that's only thing making sense in Gramine"


<!-- Sent from Reviewable.io -->

2022-10-05 16:18 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/954)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[`CI-Examples/redis/README.md` line 46 at r1](https://reviewable.io/reviews/gramineproject/gramine/954#-NDcoIZj0B8by885fwAu:-NDcw3-T90_VPAPXG7sv:b-art3xt) ([raw file](https://github.com/gramineproject/gramine/blob/676a021dee152b5af544d46fb23e22ef7392ec04/CI-Examples/redis/README.md#L46)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I understood this comment as "we test only loopack because that's only thing making sense in Gramine"
</blockquote></details>

Hm, you're right, the comment says something completely unclear to me. Looks like the comment is way too old.

I still think I should just remove this whole paragraph, plus remove `protected-mode` arg completely.


<!-- Sent from Reviewable.io -->

2022-10-06 14:47 UTC, boryspoplawski requested changes
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/954)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`CI-Examples/redis/Makefile` line 68 at r2](https://reviewable.io/reviews/gramineproject/gramine/954#-NDgKg-TDrv8-BXXdqql:-NDhiltr53ns8DSxWfId:btfaz5n) ([raw file](https://github.com/gramineproject/gramine/blob/bbef3bd1701757d0f73f79166652d9069abf50b9/CI-Examples/redis/Makefile#L68)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

FYI: I think this is a useful hint for newcomers. They can google Jinja and realize why our manifests look the way they look.
</blockquote></details>

This actually is a Jinja template that we fully render (idk, current sentence sounds like we manually replace them and the fact that syntax is same as Jinja is just conincidence).
___
*[`CI-Examples/redis/Makefile` line 124 at r2](https://reviewable.io/reviews/gramineproject/gramine/954#-NDhjGa38ss5g9SeqRkB:-NDhjGa38ss5g9SeqRkC:b-xt9o8u) ([raw file](https://github.com/gramineproject/gramine/blob/fc525b51133c45df90c5bb7026cf209e5eec900c/CI-Examples/redis/Makefile#L124)):*
> ```Makefile
> .PHONY: start-gramine-server
> start-gramine-server: all
> 	$(GRAMINE) redis-server --save '' --protected-mode no
> ```

How did this pass CI? It was all green, when you had a version with these arguments and also added them in manifest


<!-- Sent from Reviewable.io -->

2022-10-07 07:05 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/954)* status: 2 of 3 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[`CI-Examples/redis/Makefile` line 68 at r2](https://reviewable.io/reviews/gramineproject/gramine/954#-NDgKg-TDrv8-BXXdqql:-NDlFL4S67RF0K_63-wR:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/bbef3bd1701757d0f73f79166652d9069abf50b9/CI-Examples/redis/Makefile#L68)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This actually is a Jinja template that we fully render (idk, current sentence sounds like we manually replace them and the fact that syntax is same as Jinja is just conincidence).
</blockquote></details>

Done
___
*[`CI-Examples/redis/Makefile` line 124 at r2](https://reviewable.io/reviews/gramineproject/gramine/954#-NDhjGa38ss5g9SeqRkB:-NDlEhzq29REpdGeZ7tR:b-i1wd9s) ([raw file](https://github.com/gramineproject/gramine/blob/fc525b51133c45df90c5bb7026cf209e5eec900c/CI-Examples/redis/Makefile#L124)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

How did this pass CI? It was all green, when you had a version with these arguments and also added them in manifest
</blockquote></details>

Because Gramine doesn't fail on this, but just outputs a warning: https://github.com/gramineproject/gramine/blob/master/pal/src/pal_main.c#L472-L473

Which is actually what I observed on my local machine when working on this PR, and it was pretty easy to spot. So I think this is reasonable and should be kept as a warning (not hide it or make it a failure).


<!-- Sent from Reviewable.io -->

2022-10-07 11:02 UTC, boryspoplawski approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/954)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2022-10-07 11:28 UTC, mkow submitted a review, later dismissed
> Reviewed 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/954)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2022-10-10 11:24 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/954)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2022-10-10 14:46 UTC, merged