[CI-Examples] Harden SQLite example
gramineproject/gramine pull request #964
Opened 2022-10-07 13:23 UTC by dimakuv

## Description of the changes 

This PR removes the following insecure manifest options:
- `loader.insecure__use_cmdline_argv` in favor of `loader.argv`,
- `sgx.allowed_files` in favor of an "encrypted" FS mount.

The database files are now stored under the `db/` directory which is mounted as "encrypted" in Gramine. For the SGX case, the encryption key is MRENCLAVE-based; for non-SGX case, the key is a hardcoded dummy.

## How to test this PR? 

CI.

2022-10-07 13:24 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/964)* status: 0 of 6 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[`CI-Examples/sqlite/manifest.template` line 28 at r1](https://reviewable.io/reviews/gramineproject/gramine/964#-NDmbXf85qbpdsRZ-QWh:-NDmbXf85qbpdsRZ-QWi:b-jryg7t) ([raw file](https://github.com/gramineproject/gramine/blob/0da12e81dfcbab566ebdd9e85db72ee525978648/CI-Examples/sqlite/manifest.template#L28)):*
> ```
> {% if not sgx %}
> fs.insecure__keys.default = "ffeeddccbbaa99887766554433221100"
> {% endif %}
> ```

FYI: Jinja templating is cool.


<!-- Sent from Reviewable.io -->

2022-10-07 17:08 UTC, boryspoplawski requested changes
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/964)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`CI-Examples/sqlite/Makefile` line 20 at r1](https://reviewable.io/reviews/gramineproject/gramine/964#-NDnP5Gd3N4ZXHQuh0vb:-NDnP5Gd3N4ZXHQuh0vc:b-emkaw3) ([raw file](https://github.com/gramineproject/gramine/blob/0da12e81dfcbab566ebdd9e85db72ee525978648/CI-Examples/sqlite/Makefile#L20)):*
> ```Makefile
> 		-Dexecdir=$(shell dirname $(shell which sqlite3)) \
> 		-Darch_libdir=$(ARCH_LIBDIR) \
> 		-Dsgx=$(SGX) \
> ```

If I do
```
make
make SGX=1
run_example_without_sgx
run_example_with_sgx
```
one of these will fail (depending whether 2nd make rebuilds the manifest)?
___
*[`CI-Examples/sqlite/manifest.template` line 22 at r1](https://reviewable.io/reviews/gramineproject/gramine/964#-NDnPaiO8EOhfiSDt8f4:-NDnPaiO8EOhfiSDt8f5:b-ow6h58) ([raw file](https://github.com/gramineproject/gramine/blob/0da12e81dfcbab566ebdd9e85db72ee525978648/CI-Examples/sqlite/manifest.template#L22)):*
> ```
>   # SQLite creates several helper files for the DB, so we specify a path instead of a single file
>   { type = "encrypted", path = "/db/", uri = "file:db/",
>     key_name = {% if sgx %} "_sgx_mrenclave" {% else %} "default" {% endif %} },
> ```

Wouldn't it be easier to use the dummy key in all cases?


<!-- Sent from Reviewable.io -->

2022-10-07 17:09 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/964)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`CI-Examples/sqlite/db/.dummy` line 0 at r1](https://reviewable.io/reviews/gramineproject/gramine/964#-NDnPvWxBtuUiAmooCko:-NDnPvWy0sS27Ji6ZLIV:bb8qxc6) ([raw file](https://github.com/gramineproject/gramine/blob/d5599d52d2076006d31493da00f096099298aaf0/CI-Examples/sqlite/db/.dummy#L0)):*
Maybe name this `.gitkeep`? I've seen ppl using such convention


<!-- Sent from Reviewable.io -->

2022-10-10 07:50 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/964)* status: 3 of 6 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[`-- commits` line 10 at r1](https://reviewable.io/reviews/gramineproject/gramine/964#-NE-rSBR0AeT7XDBkH-S):*
I will fix the last sentence during final rebase -- it is now always the `hardcoded dummy key`.
___
*[`CI-Examples/sqlite/Makefile` line 20 at r1](https://reviewable.io/reviews/gramineproject/gramine/964#-NDnP5Gd3N4ZXHQuh0vb:-NE-rCoo-LH7TT2_ljcs:bom71f8) ([raw file](https://github.com/gramineproject/gramine/blob/0da12e81dfcbab566ebdd9e85db72ee525978648/CI-Examples/sqlite/Makefile#L20)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

If I do
```
make
make SGX=1
run_example_without_sgx
run_example_with_sgx
```
one of these will fail (depending whether 2nd make rebuilds the manifest)?
</blockquote></details>

Done. Yes, it was a problem in the previous version (because we used two different FS-mount encryption keys for non-SGX and SGX cases). Now we use a single encryption key, so the above sequence of steps works fine.
___
*[`CI-Examples/sqlite/manifest.template` line 22 at r1](https://reviewable.io/reviews/gramineproject/gramine/964#-NDnPaiO8EOhfiSDt8f4:-NE-qb879lBFSwNmdSod:b9r4sza) ([raw file](https://github.com/gramineproject/gramine/blob/0da12e81dfcbab566ebdd9e85db72ee525978648/CI-Examples/sqlite/manifest.template#L22)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Wouldn't it be easier to use the dummy key in all cases?
</blockquote></details>

Done. I wanted to make this example easy to modify for the "production SGX case" (also, Michal hates hard-coding keys), but it's too complicated for this example, I agree.
___
*[`CI-Examples/sqlite/db/.dummy` line  at r1](https://reviewable.io/reviews/gramineproject/gramine/964#-NDnPvWxBtuUiAmooCko:-NE-qpKR7NozVPEDAkeT:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d5599d52d2076006d31493da00f096099298aaf0/CI-Examples/sqlite/db/.dummy#L)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Maybe name this `.gitkeep`? I've seen ppl using such convention
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-10-10 15:44 UTC, boryspoplawski requested changes
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/964)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`CI-Examples/sqlite/.gitignore` line 3 at r2](https://reviewable.io/reviews/gramineproject/gramine/964#-NE1Yn-0EiyTvpMBHdo-:-NE1Yn-0EiyTvpMBHdo0:b7bj6bx) ([raw file](https://github.com/gramineproject/gramine/blob/7c92cadb31d93ada8bdbfb4071ccfe2682308103/CI-Examples/sqlite/.gitignore#L3)):*
> ```ignore
> /OUTPUT
> /db/*
> !/db/.gitkeep
> ```

Wait, why you `.gitignore` a file that you also commit to the repo?


<!-- Sent from Reviewable.io -->

2022-10-10 21:27 UTC, mkow requested changes
> Reviewed 2 of 6 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/964)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`CI-Examples/sqlite/Makefile` line 46 at r2](https://reviewable.io/reviews/gramineproject/gramine/964#-NE2lu0B3b3iWOAy7lUO:-NE2lu0C-uLHNyQn0rNm:by38e1h) ([raw file](https://github.com/gramineproject/gramine/blob/7c92cadb31d93ada8bdbfb4071ccfe2682308103/CI-Examples/sqlite/Makefile#L46)):*
> ```Makefile
> 	@$(RM) db/*
> 
> 	$(GRAMINE) sqlite3 < scripts/create.sql
> ```

please also add a comment here that the args are hardcoded in the manifest
___
*[`CI-Examples/sqlite/README.md` line 1 at r2](https://reviewable.io/reviews/gramineproject/gramine/964#-NE2mVr2A8kT1V6Wfls4:-NE2mVr2A8kT1V6Wfls5:b-mx9eyh) ([raw file](https://github.com/gramineproject/gramine/blob/7c92cadb31d93ada8bdbfb4071ccfe2682308103/CI-Examples/sqlite/README.md#L1)):*
> ```Markdown
> # SQLite example
> ```

You should also warn here about the hardcoded key in the manifest (and how a secure version should look like).


<!-- Sent from Reviewable.io -->

2022-10-11 11:05 UTC, mkow submitted a review, later dismissed
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/964)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)



<!-- Sent from Reviewable.io -->

2022-10-11 15:30 UTC, boryspoplawski submitted a review, later dismissed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/964)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2022-10-12 07:05 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/964)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski)

___
*[`-- commits` line 10 at r1](https://reviewable.io/reviews/gramineproject/gramine/964#-NE-rSBR0AeT7XDBkH-S):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I will fix the last sentence during final rebase -- it is now always the `hardcoded dummy key`.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2022-10-12 10:58 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/964)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @boryspoplawski)



<!-- Sent from Reviewable.io -->

2022-10-12 15:49 UTC, boryspoplawski approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/964)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-10-12 17:57 UTC, merged