[common] Add truncation to arbitrary size to Protected Files
gramineproject/gramine pull request #972
Opened 2022-10-12 09:59 UTC by dimakuv

## Description of the changes 

Truncation of PFs to arbitrary size is implemented in a slow and trivial way: read the file's contents into a temporary buffer, shrink the file to zero, write back the contents into the file.

Fixes #950.

## How to test this PR? 

CI. I added tests to `libos/test/fs`.

2022-10-13 01:38 UTC, boryspoplawski requested changes
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/972)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`common/src/protected_files/protected_files.c` line 1239 at r1](https://reviewable.io/reviews/gramineproject/gramine/972#-NEDz1rsDOiJkKB-49M3:-NEDz1rsDOiJkKB-49M4:bq0vgym) ([raw file](https://github.com/gramineproject/gramine/blob/db5e74d8a2281621de8ebab313d22e8ea2a33a16/common/src/protected_files/protected_files.c#L1239)):*
> ```C
>     }
> 
>     /* shrink the file
> ```

Maybe we should have some `TODO` somewhere here to implement it properly someday?


<!-- Sent from Reviewable.io -->

2022-10-13 07:35 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/972)* status: 3 of 4 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[`common/src/protected_files/protected_files.c` line 1239 at r1](https://reviewable.io/reviews/gramineproject/gramine/972#-NEDz1rsDOiJkKB-49M3:-NEFFc2g4iFtfqb0dknV:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/db5e74d8a2281621de8ebab313d22e8ea2a33a16/common/src/protected_files/protected_files.c#L1239)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Maybe we should have some `TODO` somewhere here to implement it properly someday?
</blockquote></details>

Done.
___
*[`common/src/protected_files/protected_files.c` line 1248 at r1](https://reviewable.io/reviews/gramineproject/gramine/972#-NEFFce15j3pfj3YD8-t:-NEFFce15j3pfj3YD8-u:brk6ac6) ([raw file](https://github.com/gramineproject/gramine/blob/db5e74d8a2281621de8ebab313d22e8ea2a33a16/common/src/protected_files/protected_files.c#L1248)):*
> ```C
>     if (size > 0) {
>         /* read the file's contents into a temporary buffer */
>         buf = malloc(size);
> ```

Do we want to introduce a stopper like
```
if (size > 10 * 1024 * 1024)
    log_error("Shrinking a file requires to copy in a temporary buffer, but the size of the buffer will be too big");
    return PF_STATUS_DENIED;
```

If yes, what would be the size at which we cut off?

I just want to highlight the problem of allocating an arbitrarily-large buffer here. I actually don't think we need a stopper IF clause, because it will be a random heuristic...


<!-- Sent from Reviewable.io -->

2022-10-13 10:51 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/972)* status: 3 of 4 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[`common/src/protected_files/protected_files.c` line 1248 at r1](https://reviewable.io/reviews/gramineproject/gramine/972#-NEFFce15j3pfj3YD8-t:-NEFwGc5-A9BGKm2Jwnk:b-ezuuh4) ([raw file](https://github.com/gramineproject/gramine/blob/db5e74d8a2281621de8ebab313d22e8ea2a33a16/common/src/protected_files/protected_files.c#L1248)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Do we want to introduce a stopper like
```
if (size > 10 * 1024 * 1024)
    log_error("Shrinking a file requires to copy in a temporary buffer, but the size of the buffer will be too big");
    return PF_STATUS_DENIED;
```

If yes, what would be the size at which we cut off?

I just want to highlight the problem of allocating an arbitrarily-large buffer here. I actually don't think we need a stopper IF clause, because it will be a random heuristic...
</blockquote></details>

I think that allocating arbitrary size might be a problem in case of files.
People don't use protected files with databases which can grow kinda large?
Won't naive solution be just to change the size of data and erase the encrypted part? Even if the hosts file won't shrink it might be a safer solution.


<!-- Sent from Reviewable.io -->

2022-10-13 11:36 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/972)* status: 3 of 4 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @oshogbo)

___
*[`common/src/protected_files/protected_files.c` line 1248 at r1](https://reviewable.io/reviews/gramineproject/gramine/972#-NEFFce15j3pfj3YD8-t:-NEG6x1c1Urwp98QS1ZF:b-79olfk) ([raw file](https://github.com/gramineproject/gramine/blob/db5e74d8a2281621de8ebab313d22e8ea2a33a16/common/src/protected_files/protected_files.c#L1248)):*
> I think that allocating arbitrary size might be a problem in case of files.
> People don't use protected files with databases which can grow kinda large?

Yes, technically people can use PFs for databases, and then this `malloc(size)` may potentially allocate GB-sized buffers. That's why I'm asking about adding a stopper here.

> Won't naive solution be just to change the size of data and erase the encrypted part?

But erase how? Like, what is the pseudo-code for erasing a part of the file contents? For example, how do I truncate from 2 characters to 1 character -- what do I erase? (Recall that encrypted file contents are stored in 4KB blocks, and each block must be re-encrypted with a new derived key after each update.)


<!-- Sent from Reviewable.io -->

2022-10-13 12:28 UTC, boryspoplawski approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/972)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @oshogbo)

___
*[`common/src/protected_files/protected_files.c` line 1248 at r1](https://reviewable.io/reviews/gramineproject/gramine/972#-NEFFce15j3pfj3YD8-t:-NEGJ66NCuWO2Q2oDMDe:b-b04er) ([raw file](https://github.com/gramineproject/gramine/blob/db5e74d8a2281621de8ebab313d22e8ea2a33a16/common/src/protected_files/protected_files.c#L1248)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> I think that allocating arbitrary size might be a problem in case of files.
> People don't use protected files with databases which can grow kinda large?

Yes, technically people can use PFs for databases, and then this `malloc(size)` may potentially allocate GB-sized buffers. That's why I'm asking about adding a stopper here.

> Won't naive solution be just to change the size of data and erase the encrypted part?

But erase how? Like, what is the pseudo-code for erasing a part of the file contents? For example, how do I truncate from 2 characters to 1 character -- what do I erase? (Recall that encrypted file contents are stored in 4KB blocks, and each block must be re-encrypted with a new derived key after each update.)
</blockquote></details>

Regarding cut off: I don't think it's needed - this memory will be freed soon after so having the natural limit of enclave size is IMHO enough. 


<!-- Sent from Reviewable.io -->

2022-10-19 12:37 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/972)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/972#-NEkEl-Y4Fl34APMDzAf:-NEkEl-Y4Fl34APMDzAg:bkma4m9) (no related file):*
Requesting review of @mkow and blocking until he checks.

___


<!-- Sent from Reviewable.io -->

2022-10-21 15:45 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/972)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[`common/src/protected_files/protected_files.c` line 1248 at r1](https://reviewable.io/reviews/gramineproject/gramine/972#-NEFFce15j3pfj3YD8-t:-NEvBxu8E25ez7cO8j7c:bsu3kaa) ([raw file](https://github.com/gramineproject/gramine/blob/db5e74d8a2281621de8ebab313d22e8ea2a33a16/common/src/protected_files/protected_files.c#L1248)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Regarding cut off: I don't think it's needed - this memory will be freed soon after so having the natural limit of enclave size is IMHO enough. 
</blockquote></details>

I was thinking something like:
```
set_header(newsize);

memset(zero_buf, 0 sizeof(*buf));
for (size_t i = newsize; i < actuall_size; i +=sizeof(*buf)) {
      pf_write(pf, size + i, MIN(sizeof(*buf), actuall_size - i), zero_buf);
}
``` 

Or something like that. My goal was just to implement truncate without, really changing the size on the disk.
But I believe mkow prefer other solution.


<!-- Sent from Reviewable.io -->

2022-10-24 09:02 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/972)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`common/src/protected_files/protected_files.c` line 1248 at r1](https://reviewable.io/reviews/gramineproject/gramine/972#-NEFFce15j3pfj3YD8-t:-NF8Dc9e4WOx6umI1PYJ:b-8by9ra) ([raw file](https://github.com/gramineproject/gramine/blob/db5e74d8a2281621de8ebab313d22e8ea2a33a16/common/src/protected_files/protected_files.c#L1248)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

I was thinking something like:
```
set_header(newsize);

memset(zero_buf, 0 sizeof(*buf));
for (size_t i = newsize; i < actuall_size; i +=sizeof(*buf)) {
      pf_write(pf, size + i, MIN(sizeof(*buf), actuall_size - i), zero_buf);
}
``` 

Or something like that. My goal was just to implement truncate without, really changing the size on the disk.
But I believe mkow prefer other solution.
</blockquote></details>

I see, yes, we could use @oshogbo solution as well.

@mkow What solution do you prefer?


<!-- Sent from Reviewable.io -->

2023-07-06 13:27 UTC, dimakuv commented
We hit this again on a MariaDB workload -- without this PR it fails with `ftruncate: Permission denied` on a Protected File. With this PR, it succeeds initialization and continues working.

We should prioritize finishing this PR.

2024-04-08 07:20 UTC, closed without merging