[LibOS] Robus futexes fixes
gramineproject/gramine pull request #980
Opened 2022-10-13 16:36 UTC by boryspoplawski

## Description of the changes 
See commit messages.

Fixes #969

## How to test this PR? 
Try the following patch with and without this PR:
```
diff --git a/libos/src/sys/libos_futex.c b/libos/src/sys/libos_futex.c
index 114ef2e5..712b5ff8 100644
--- a/libos/src/sys/libos_futex.c
+++ b/libos/src/sys/libos_futex.c
@@ -898,9 +898,9 @@ static bool handle_futex_death(uint32_t* uaddr) {
  * Returns 0 on success, negative value on error.
  */
 static int fetch_robust_entry(struct robust_list** entry, struct robust_list** head) {
-    if (!is_user_memory_readable(head, sizeof(*head))) {
-        return -EFAULT;
-    }
+    //if (!is_user_memory_readable(head, sizeof(*head))) {
+    //    return -EFAULT;
+    //}
 
     *entry = *head;
     return 0;
@@ -926,9 +926,9 @@ void release_robust_list(struct robust_list_head* head) {
         return;
     }
 
-    if (!is_user_memory_readable(&head->futex_offset, sizeof(head->futex_offset))) {
-        return;
-    }
+    //if (!is_user_memory_readable(&head->futex_offset, sizeof(head->futex_offset))) {
+    //    return;
+    //}
     futex_offset = head->futex_offset;
 
     if (fetch_robust_entry(&pending, &head->list_op_pending) < 0) {
```

2022-10-13 17:15 UTC, stefanberger reviewed
I tried the PR and the PR + the suggested patch. Both resolve the (one) issue that I had seen before. The following error is now completely gone:

```
[P1:libos] error: Internal memory fault at 0x280e9410018 (handle_futex_death at libos_futex.c, libsysdb.so+0x91c1c, VMID = 1, TID = 0)
```
So that's good.

I had seen 'plain' Segfaults before and they are still there, though.

```
[P1:T1:exec_same] trace: ---- execve("exec_same", [exec_same,2,3,4,5,6,7,8,9,a,b,c,d,e,f,g,h,i,j,], [LD_LIBRARY_PATH=/lib:/lib/powerpc64le-linux-gnu:/usr//lib/powerpc64le-linux-gnu,]) ...
[P1:T2:exec_same] trace: ---- execve("exec_same", [exec_same,2,3,4,5,6,7,8,9,a,b,c,d,e,f,g,h,i,j,], [LD_LIBRARY_PATH=/lib:/lib/powerpc64le-linux-gnu:/usr//lib/powerpc64le-linux-gnu,]) ...
[P1:T1:exec_same] debug: Allocated stack at 0x6f7a14e80000 (size = 0x40000)
[P1:T2:exec_same] debug: Creating pipe: pipe.srv:298fadd003739843d3d74c355f7dcca18817b4f6b2babe49ef9c13c205f5e6ac
[P1:T1:exec_same] debug: remove_r_debug: removing file:/usr/local/lib/powerpc64le-linux-gnu/gramine/tests/libos/regression/exec_same at 0
[P1:T1:exec_same] debug: remove_r_debug: removing file:/usr/local/lib/powerpc64le-linux-gnu/gramine/runtime/glibc/ld64.so.2 at 0x6f7a151a0000
[P1:T1:exec_same] debug: loading "file:/usr/local/lib/powerpc64le-linux-gnu/gramine/tests/libos/regression/exec_same"
[P1:T1:exec_same] debug: append_r_debug: adding file:/usr/local/lib/powerpc64le-linux-gnu/gramine/tests/libos/regression/exec_same at 0
[P1:T1:exec_same] debug: find_interp: searching for interpreter: /lib/ld64.so.2
Segmentation fault (core dumped)
```

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/980#-:-NEHJ8L51hMYwoDgJEWd:b-683m5)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2022-10-13 17:15 UTC, stefanberger reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/980#-:-NEHL5f2-_GuJ7CbCA0r:bnfp4nl)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2022-10-13 17:51 UTC, boryspoplawski reviewed
The patch is for testing, but it shouldn't have any effect on normal execution.
Regarding these segfaults: hard to say, I would need more details...

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/980#-:-NEHT3UQCthz0-_hrk9Q:b-iayona)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2022-10-13 18:31 UTC, stefanberger reviewed
Right. Let me investigate this a bit first. It **may be** related to the TLS memory area getting freed but then also accessed again later on via get_cur_thread()...

The majority of the crashes are fixed by this PR.

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/980#-:-NEHbIPB7-SeJcTgfVuX:b-iijeiy)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2022-10-14 00:02 UTC, mkow approved these changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/980)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2022-10-14 07:13 UTC, dimakuv requested changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/980)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/980#-NEKGH7t47FKPpLdoig-:-NEKGH7uBTwUJdgYtf1b:bdhpp3c) (no related file):*
UBSan detected this error:
```
Failed: ['gramine-direct', 'set_robust_list01'] exited with status 1

[0.023] set_robust_list01    1  TPASS  :  set_robust_list: retval = -1 (expected -1), errno = 22 (expected 22)
[0.023] set_robust_list01    2  TPASS  :  set_robust_list: retval = 0 (expected 0), errno = 0 (expected 0)

[0.023] [P1:T1:set_robust_list01] error: ubsan: null pointer dereference
[0.023] [P1:T1:set_robust_list01] error: ubsan: ../libos/src/sys/libos_futex.c:943:59
```

___


<!-- Sent from Reviewable.io -->

2022-10-14 11:35 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/980)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/980#-NEKGH7t47FKPpLdoig-:-NELGk4q1p4HXQm5YSjy:b-cghx2h) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

UBSan detected this error:
```
Failed: ['gramine-direct', 'set_robust_list01'] exited with status 1

[0.023] set_robust_list01    1  TPASS  :  set_robust_list: retval = -1 (expected -1), errno = 22 (expected 22)
[0.023] set_robust_list01    2  TPASS  :  set_robust_list: retval = 0 (expected 0), errno = 0 (expected 0)

[0.023] [P1:T1:set_robust_list01] error: ubsan: null pointer dereference
[0.023] [P1:T1:set_robust_list01] error: ubsan: ../libos/src/sys/libos_futex.c:943:59
```
</blockquote></details>

Yes, I'm aware

___


<!-- Sent from Reviewable.io -->

2022-10-14 21:09 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/980)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/980#-NEKGH7t47FKPpLdoig-:-NENJVKa3gN2ObxGUTnY:bo1wmwp) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Yes, I'm aware
</blockquote></details>

Following 2-hour tests running exec_same in a loop with the patches in the PR here applied I can say that ppc64 needs them and it improves stability. x86_64 doesn't seem to need them, though.

___


<!-- Sent from Reviewable.io -->

2022-10-14 22:50 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/980)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/980#-NEKGH7t47FKPpLdoig-:-NENg5wOBY8hkGFinx6N:buicagr) (no related file):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

Following 2-hour tests running exec_same in a loop with the patches in the PR here applied I can say that ppc64 needs them and it improves stability. x86_64 doesn't seem to need them, though.
</blockquote></details>

x64 also needs them, it's weird we never triggered it

___


<!-- Sent from Reviewable.io -->

2022-10-18 01:01 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/980)* status: 2 of 3 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "squash! " and "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @stefanberger)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/980#-NEKGH7t47FKPpLdoig-:-NEcatgy8r-umWvO3--c:b-bu91xm) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

x64 also needs them, it's weird we never triggered it
</blockquote></details>

Updated

___


<!-- Sent from Reviewable.io -->

2022-10-18 06:58 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/980)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "squash! " and "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2022-10-18 13:30 UTC, mkow requested changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/980)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "squash! " and "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[`libos/src/sys/libos_futex.c` line 866 at r2](https://reviewable.io/reviews/gramineproject/gramine/980#-NEfFzZR18M_9696SNS7:-NEfFzZS547EL9C5JCPI:b-99g24s) ([raw file](https://github.com/gramineproject/gramine/blob/277a1a49baeceefb9ee1db0cd9b4813f8962d2b8/libos/src/sys/libos_futex.c#L866)):*
> ```C
>     }
>     int ret = is_valid_futex_ptr(uaddr, FUTEX_CHECK_WRITE);
>     if (ret) {
> ```

Not `< 0`? Also, `is_valid_futex_ptr` name is a bit confusing to me, sounds like something which should return a bool, IMO functions returning 0/error codes should rather have `check_` prefix, not `is_`.


<!-- Sent from Reviewable.io -->

2022-10-18 14:31 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/980)* status: 2 of 3 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`libos/src/sys/libos_futex.c` line 866 at r2](https://reviewable.io/reviews/gramineproject/gramine/980#-NEfFzZR18M_9696SNS7:-NEfS37T5vY3riN6CZz0:bcshgu2) ([raw file](https://github.com/gramineproject/gramine/blob/277a1a49baeceefb9ee1db0cd9b4813f8962d2b8/libos/src/sys/libos_futex.c#L866)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Not `< 0`? Also, `is_valid_futex_ptr` name is a bit confusing to me, sounds like something which should return a bool, IMO functions returning 0/error codes should rather have `check_` prefix, not `is_`.
</blockquote></details>

They are equivalent, this function returns `<= 0`, but I guess we usually do `<0`.
Changed name to be more accurate


<!-- Sent from Reviewable.io -->

2022-10-18 15:23 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/980)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

___
*[`libos/src/sys/libos_futex.c` line 866 at r2](https://reviewable.io/reviews/gramineproject/gramine/980#-NEfFzZR18M_9696SNS7:-NEffrDx4fnEZtCSwPY7:b2jqxyh) ([raw file](https://github.com/gramineproject/gramine/blob/277a1a49baeceefb9ee1db0cd9b4813f8962d2b8/libos/src/sys/libos_futex.c#L866)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

They are equivalent, this function returns `<= 0`, but I guess we usually do `<0`.
Changed name to be more accurate
</blockquote></details>

Yeah, that was about our conventions, not correctness. LGTM now.


<!-- Sent from Reviewable.io -->

2022-10-19 11:16 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/980)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-10-19 12:11 UTC, merged