[LibOS] Add `sys.disallow_subprocesses` manifest option
gramineproject/gramine pull request #983
Opened 2022-10-17 13:01 UTC by dimakuv

## Description of the changes 

Some apps (in particular Python) tend to spawn helper subprocesses. There is no simple way to disable such functionality in the apps themselves, so we introduce a new manifest option to force apps to use only the main process and fall back to no-subprocesses logic.

**This is a draft for quick testing! After we'll test that it helps sometimes, we can have discussions on the terribleness of this approach.**

This PR literally disables `fork/vfork/clone` syscalls used to spawn subprocesses.

## How to test this PR? 

We'll test some Python workloads to see if this trick is beneficial...

2023-02-02 12:45 UTC, heavenboy8 commented
Hi, 

This feature is very interesting and important for our own usage of Gramine. :+1: Indeed, we are spawning enclaves on demand containing applications we do not write by ourself and can't monitor. In our scenario, on an SGX machine, several enclaves should run independently and do not exceed the resources they own. Especially, each application can run only one enclave and no more (otherwise an app will take resources (memory) from another app). Therefore having the ability to disallow the fork is a major concern for us. This feature is exactly what we are expecting for. On a security point of view, it enables us to prevent an application to act as a fork bomb. 

Great job and thanks for this feature. :clap: Could we expect it to be integrated in the incoming release 1.4 ?

2023-02-02 12:57 UTC, dimakuv commented
FYI: Jenkins-Direct-Sanitizers failed due to timeout on Blender download (known problem), but I can't restart the pipeline because our Gramine web-site certificate expired.

2023-02-05 23:21 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/983)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/983#-NNYrT4H2Rsefh5-B7B8:-NNYrT4I9nddqe1puxSj:b-3afv3q) (no related file):*
> On a security point of view, it enables us to prevent an application to act as a fork bomb.

@heavenboy8: This PR doesn't provide such guarantees. Gramine is a one-way sandbox - it protects the app from the host, but not the other way. If you want to run untrusted apps inside Gramine then you should wrap everything inside a security sandbox, e.g. https://github.com/google/nsjail.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/983#-NNYrw8S57LU9vej-bUl:-NNYrw8S57LU9vej-bUm:b8kud8d) (no related file):*
> Great job and thanks for this feature. 👏 Could we expect it to be integrated in the incoming release 1.4 ?

@heavenboy8: Nope, sorry. v1.4 is going out in a moment and this PR isn't ready yet.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/983#-NNYsBSuBkVsD3Boiz78:-NNYsBSuBkVsD3Boiz79:b88lg5c) (no related file):*
> There is no simple way to disable such functionality in the apps themselves, so we introduce a new manifest option to force apps to use only the main process

But there's a mechanism made exactly for this in Linux - resource limits. Why not just add emulation for the Linux limit of processes, instead of this custom and less flexible solution?

___


<!-- Sent from Reviewable.io -->

2023-02-06 08:40 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/983)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/983#-NNYrT4H2Rsefh5-B7B8:-NN_qOVR-RHyKKe4CE6a:b-pn0rq0) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> On a security point of view, it enables us to prevent an application to act as a fork bomb.

@heavenboy8: This PR doesn't provide such guarantees. Gramine is a one-way sandbox - it protects the app from the host, but not the other way. If you want to run untrusted apps inside Gramine then you should wrap everything inside a security sandbox, e.g. https://github.com/google/nsjail.
</blockquote></details>

I think there is a point to what @heavenboy8 says. Imagine we have the following scenario:
- Benign host
- Random, possibly malicious, apps on top of Gramine

The host will never do a fork bomb, as it is benign. However, some malicious app may be a fork bomb. There would be two ways to prevent this:
- Limit the number of (child) processes on the host,
- Have something like this PR, and rely on Gramine doing the right thing.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/983#-NNYsBSuBkVsD3Boiz78:-NN_rQWf3G7X_Vny04QZ:bsh159q) (no related file):*
@mkow I like the idea, but could you elaborate?

The main advantage of this PR is that it doesn't require any interaction/request from the application. IIUC, you suggest to implement proper emulation of `nproc` limit inside Gramine. But this would require the application to issue `setrlimit(RLIMIT_NPROC)` on startup/at some point.

Or maybe you mean we should add something like this in the manifest?
```
sys.rlimits.nproc.soft = 1
sys.rlimits.nproc.hard = -1 (aka infinity)
```

If that's your proposal, I really like this idea. We could even shove our already-existing manifest options (like `stack.size` and `brk.size`) under this manifest-options group.

> ... instead of this custom and less flexible solution?

Well, I can only agree. My solution was quick-and-dirty and is not flexible at all. The idea with Linux's resource limits I like much more.

___


<!-- Sent from Reviewable.io -->

2023-02-06 12:07 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/983)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/983#-NNYrT4H2Rsefh5-B7B8:-NNaayi_DMCf70OlvQ5H:bxtljpw) (no related file):*
> some malicious app may be a fork bomb

> Have something like this PR, and rely on Gramine doing the right thing.

But this PR is _not_ protecting against this scenario. As I said, Gramine is only a one way sandbox and we have no way to restrict the app anyhow if it's malicious. This PR is restricting only non-malicious apps which are being nice to Gramine.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/983#-NNYsBSuBkVsD3Boiz78:-NNabV-V7RPzbS_LSOU9:b-2iz4r7) (no related file):*
> Or maybe you mean we should add something like this in the manifest?
> 
> ```
> sys.rlimits.nproc.soft = 1
> sys.rlimits.nproc.hard = -1 (aka infinity)
> ```

Yes, exactly. Emulate the Linux mechanism and add a way to specify its initial state in the manifest.

___


<!-- Sent from Reviewable.io -->

2023-02-06 12:24 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/983)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/983#-NNYrT4H2Rsefh5-B7B8:-NNaf4H30x4_qkQA9HdT:b-kcgo0e) (no related file):*
> This PR is restricting only non-malicious apps which are being nice to Gramine.

Hm, ok, you're right. My scenario with a malicious app is bogus. The only real scenario that this PR would cover is when both the host and the app are benign, but the app may do something security- or privacy-critical when it notices that it's run under root.

Anyway, in the other comment we agreed on having proper Linux resource limits emulation, which would make this PR unnecessary.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/983#-NNYsBSuBkVsD3Boiz78:-NNaf_uL31glcg_ruVlp:bb4g17k) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> Or maybe you mean we should add something like this in the manifest?
> 
> ```
> sys.rlimits.nproc.soft = 1
> sys.rlimits.nproc.hard = -1 (aka infinity)
> ```

Yes, exactly. Emulate the Linux mechanism and add a way to specify its initial state in the manifest.
</blockquote></details>

Yes, good idea. Let me try to cook a PR this week, let's see how hard it is. If it will turn out to be too time-consuming, I'll create a GitHub issue instead.

I'll keep this PR open for now, until I either create another PR or a new GitHub issue.

___


<!-- Sent from Reviewable.io -->

2023-02-10 13:52 UTC, heavenboy8 commented
Hi, 

Actually it's more a matter of "quality of service" than security in our case scenario. 
If my application is supposed to take 8GB of the EPC but it actually takes 16GB because of a fork (which generates a second enclave), it will eat the EPC memory space dedicated to another application and make the other enclaves running in the same SGX machine swap. The performance will then be bad. 

I like the solution implemented in this PR because it controls a behaviour implemented by Gramine: spawn another enclave while a fork occurs. Another choice could have been to refuse the fork because it generates more memory than we have set in the manifest. With that option, we have a better control of the fork behaviour. Let's remind that the problem issues when we import Flask or tensorflow: very common python library.

I've tried to play with `ulimit` and `nproc` instead. It looks like a good idea. However: 

> RLIMIT_NPROC (https://man7.org/linux/man-pages/man2/getrlimit.2.html): This is a limit on the number of extant process (or, more precisely on Linux, **threads**) for the **real user ID** of the calling process.  So long as the current number of processes belonging to this process's real user ID is  greater than or equal to this limit, **fork(2) fails with the error EAGAIN.**

Several things are annoying here:  

1. `ulimit` works on a user and not a single process. So it's not convenient (even impossible in some cases) to put a limit  for the whole processes of a given user whereas we just want to control the fork of a single application under Gramine. 
2. Put `nproc=1` also prevents us from spawning threads (which was completely okay here because spawning a thread does not spawn another enclave). `OpenBLAS blas_thread_init: pthread_create failed for thread 47 of 48: Resource temporarily unavailable.`
2. `EAGAIN` makes the enclave stop under Gramine. Whereas this implementation, does not.

2023-02-10 14:28 UTC, dimakuv reviewed
@heavenboy8 Thanks for looking at this again, very interesting observations. Some comments.

> Another choice could have been to refuse the fork because it generates more memory than we have set in the manifest.

Hm, I don't like this. This is significantly more complicated to track than number of processes. Especially when we take into account EDMM.

> ulimit works on a user and not a single process. So it's not convenient (even impossible in some cases) to put a limit for the whole processes of a given user whereas we just want to control the fork of a single application under Gramine.

This is not a problem for Gramine. Gramine kinda re-creates a Linux environment from the application perspective, so the limit will be only applicable **inside Gramine** and not on your host machine. And since Gramine runs as a single user, the limit will always work for the application that is started under Gramine.

> Put `nproc=1` also prevents us from spawning threads (which was completely okay here because spawning a thread does not spawn another enclave).

Ok, this is something I didn't realize, and this is a real complication for us. I didn't know that `RLIMIT_NPROC` works on Linux tasks (which are both processes and threads), and so indeed -- we have a problem. @mkow @oshogbo  any thoughts? One idea is to introduce a new, Gramine-specific limit like `RLIMIT_NFORK`...

> EAGAIN makes the enclave stop under Gramine. Whereas this implementation, does not.

I'm not sure what you mean here. I guess you mean that you tested some application under Gramine, and if it got EAGAIN, it stopped/terminated? I don't understand why some app would do that on EAGAIN (and won't do it on ENOSYS, as in this PR).

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/983#-:-NNvgzX237fLql9ZxA7t:b-bi9xu9)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2023-02-12 00:02 UTC, mkow reviewed
@heavenboy8: If you could, please use Reviewable when replying, this way the discussions will be properly threaded.

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/983#-:-NO1tVfi7lYa9DO0VM2x:b-ancs0i)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/983#-NNYsBSuBkVsD3Boiz78:-NO1u5hE3ycZ605PH4EO:b-i6drps) (no related file):*
> Several things are annoying here:
> 1. `ulimit` works on a user and not a single process. So it's not convenient (even impossible in some cases) to put a limit  for the whole processes of a given user whereas we just want to control the fork of a single application under Gramine.
> 2. Put `nproc=1` also prevents us from spawning threads (which was completely okay here because spawning a thread does not spawn another enclave). `OpenBLAS blas_thread_init: pthread_create failed for thread 47 of 48: Resource temporarily unavailable.`

Ah, right. This makes `RLIMIT_NPROC` quite useless for your case.

> One idea is to introduce a new, Gramine-specific limit like `RLIMIT_NFORK`...

I don't like the idea of modifying the Linux ABI we emulate.

@dimakuv: I don't have other ideas, so I guess we have to proceed with the approach from this PR?

___


<!-- Sent from Reviewable.io -->

2023-02-13 09:45 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/983)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/983#-NNYsBSuBkVsD3Boiz78:-NO99TYW7Jh80Te9owev:b-q3q3j4) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> Several things are annoying here:
> 1. `ulimit` works on a user and not a single process. So it's not convenient (even impossible in some cases) to put a limit  for the whole processes of a given user whereas we just want to control the fork of a single application under Gramine.
> 2. Put `nproc=1` also prevents us from spawning threads (which was completely okay here because spawning a thread does not spawn another enclave). `OpenBLAS blas_thread_init: pthread_create failed for thread 47 of 48: Resource temporarily unavailable.`

Ah, right. This makes `RLIMIT_NPROC` quite useless for your case.

> One idea is to introduce a new, Gramine-specific limit like `RLIMIT_NFORK`...

I don't like the idea of modifying the Linux ABI we emulate.

@dimakuv: I don't have other ideas, so I guess we have to proceed with the approach from this PR?
</blockquote></details>

Well, ok. If we don't want to introduce any new interfaces, then yes, my approach seems the most straight-forward.

I will add a test case now, and this PR is ready to go then.

___


<!-- Sent from Reviewable.io -->

2023-02-13 10:22 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/983)* status: 0 of 6 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/983#-NNYsBSuBkVsD3Boiz78:-NO9I-Ie0Jc0evNYNhqn:b4rc7df) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Well, ok. If we don't want to introduce any new interfaces, then yes, my approach seems the most straight-forward.

I will add a test case now, and this PR is ready to go then.
</blockquote></details>

Done, added documentation and a test.

___


<!-- Sent from Reviewable.io -->

2023-02-17 14:57 UTC, heavenboy8 commented
Hi @dimakuv , 
Thanks for the last changes. Can we expect a merge on `main` branch soon? We will be glad to use this new feature.

2023-02-17 15:53 UTC, dimakuv reviewed
@heavenboy8 We don't have a `main` branch, we have a `master` branch :)

I think yes, we'll merge this soon-ish. @mkow needs to re-review, but he was generally Ok with this implementation.

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/983#-:-NOV3qwF6bZVrdnvxyMz:b3y304x)* status: 0 of 6 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2023-02-20 00:44 UTC, mkow requested changes
> Reviewed 1 of 1 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/983)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`Documentation/manifest-syntax.rst` line 353 at r3](https://reviewable.io/reviews/gramineproject/gramine/983#-NOgBZ4A2gOaivhI3juH:-NOgBZ4B3C7hO1ht4UHa:b-smugc6) ([raw file](https://github.com/gramineproject/gramine/blob/38fda632e5329c843d908e9802a0e08e3cb3d8e5/Documentation/manifest-syntax.rst#L353)):*
To avoid misuse, please add:

> This option is _not_ a security feature - Gramine by-design is only a one-way sandbox, which doesn't protect the host from the enclave. Don't use this option if you want to somehow mitigate running untrusted enclaves. Instead, to achieve this, you need to run the whole Gramine inside a proper security sandbox.
___
*[`libos/src/sys/libos_clone.c` line 326 at r3](https://reviewable.io/reviews/gramineproject/gramine/983#-NOgDkOw2lKondm2oWHX:-NOgDkOw2lKondm2oWHY:b-2e58hb) ([raw file](https://github.com/gramineproject/gramine/blob/38fda632e5329c843d908e9802a0e08e3cb3d8e5/libos/src/sys/libos_clone.c#L326)):*
> ```C
>                             "(sys.disallow_subprocesses = true)");
>             }
>             return -ENOSYS;
> ```

Not something else? E.g. the same error as returned when you exceed rlimits.
___
*[`libos/test/regression/fork_disallowed.manifest.template` line 14 at r3](https://reviewable.io/reviews/gramineproject/gramine/983#-NOgED771zcdIl1lDd73:-NOgED771zcdIl1lDd74:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/38fda632e5329c843d908e9802a0e08e3cb3d8e5/libos/test/regression/fork_disallowed.manifest.template#L14)):*
> ```
> ]
> 
> # must print a warning `The app tried to create a subprocess, but this is disabled`
> ```





_Suggestion:_
```
warning: "The app tried to create a subprocess, but this is disabled"
```


<!-- Sent from Reviewable.io -->

2023-02-20 10:11 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/983)* status: 3 of 6 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`Documentation/manifest-syntax.rst` line 353 at r3](https://reviewable.io/reviews/gramineproject/gramine/983#-NOgBZ4A2gOaivhI3juH:-NOiHfue4hIofR5ZtYhg:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/38fda632e5329c843d908e9802a0e08e3cb3d8e5/Documentation/manifest-syntax.rst#L353)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

To avoid misuse, please add:

> This option is _not_ a security feature - Gramine by-design is only a one-way sandbox, which doesn't protect the host from the enclave. Don't use this option if you want to somehow mitigate running untrusted enclaves. Instead, to achieve this, you need to run the whole Gramine inside a proper security sandbox.
</blockquote></details>

Done
___
*[`libos/src/sys/libos_clone.c` line 326 at r3](https://reviewable.io/reviews/gramineproject/gramine/983#-NOgDkOw2lKondm2oWHX:-NOiIUTj1B7Sa9mNZ_0a:brcbkow) ([raw file](https://github.com/gramineproject/gramine/blob/38fda632e5329c843d908e9802a0e08e3cb3d8e5/libos/src/sys/libos_clone.c#L326)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Not something else? E.g. the same error as returned when you exceed rlimits.
</blockquote></details>

Done. Surprisingly, the error is `EAGAIN`, see `man 2 fork` for details (`man 2 clone` redirects to `man 2 fork` for this error code).
___
*[`libos/test/regression/fork_disallowed.manifest.template` line 14 at r3](https://reviewable.io/reviews/gramineproject/gramine/983#-NOgED771zcdIl1lDd73:-NOiHpvc8BvMfE2c06SN:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/38fda632e5329c843d908e9802a0e08e3cb3d8e5/libos/test/regression/fork_disallowed.manifest.template#L14)):*
> ```
> ]
> 
> # must print a warning `The app tried to create a subprocess, but this is disabled`
> ```

Done.


<!-- Sent from Reviewable.io -->

2023-02-20 10:56 UTC, mkow requested changes
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/983)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`libos/src/sys/libos_clone.c` line 326 at r3](https://reviewable.io/reviews/gramineproject/gramine/983#-NOgDkOw2lKondm2oWHX:-NOiSKOJCoaX_QWNe2Ro:bm9om98) ([raw file](https://github.com/gramineproject/gramine/blob/38fda632e5329c843d908e9802a0e08e3cb3d8e5/libos/src/sys/libos_clone.c#L326)):*
> Tested some Python workloads; they stopped spawning child enclaves and still behave correctly.

Just to be sure, could you check these workloads again after this change?


<!-- Sent from Reviewable.io -->

2023-02-20 12:20 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/983)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`libos/src/sys/libos_clone.c` line 326 at r3](https://reviewable.io/reviews/gramineproject/gramine/983#-NOgDkOw2lKondm2oWHX:-NOil62k6b_-83OmNT-H:b55hsjd) ([raw file](https://github.com/gramineproject/gramine/blob/38fda632e5329c843d908e9802a0e08e3cb3d8e5/libos/src/sys/libos_clone.c#L326)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> Tested some Python workloads; they stopped spawning child enclaves and still behave correctly.

Just to be sure, could you check these workloads again after this change?
</blockquote></details>

Done.

I also updated the PR description (see "How to test this PR" section), so that everyone can quickly reproduce my tests.


<!-- Sent from Reviewable.io -->

2023-02-20 13:00 UTC, mkow submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/983)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2023-02-21 01:36 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/983)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`libos/src/sys/libos_clone.c` line 315 at r4](https://reviewable.io/reviews/gramineproject/gramine/983#-NOlaBOq4uDbFISmrxtH:-NOlaBOq4uDbFISmrxtI:b-80oidc) ([raw file](https://github.com/gramineproject/gramine/blob/721d2b48f509ce0bbca93b124833d82ae3b06b7f/libos/src/sys/libos_clone.c#L315)):*
> ```C
>         bool disallow_subprocesses;
>         ret = toml_bool_in(g_manifest_root, "sys.disallow_subprocesses",
>                            /*defaultval=*/false, &disallow_subprocesses);
> ```

Please rewrap.


<!-- Sent from Reviewable.io -->

2023-02-21 08:19 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/983)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

___
*[`libos/src/sys/libos_clone.c` line 315 at r4](https://reviewable.io/reviews/gramineproject/gramine/983#-NOlaBOq4uDbFISmrxtH:-NOn2W_rEhenQUMxjck_:b89z1lz) ([raw file](https://github.com/gramineproject/gramine/blob/721d2b48f509ce0bbca93b124833d82ae3b06b7f/libos/src/sys/libos_clone.c#L315)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Please rewrap.
</blockquote></details>

There is nothing to rewrap? Everything seems to be already conforming to 100-char limit.


<!-- Sent from Reviewable.io -->

2023-02-21 08:37 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/983)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`libos/src/sys/libos_clone.c` line 315 at r4](https://reviewable.io/reviews/gramineproject/gramine/983#-NOlaBOq4uDbFISmrxtH:-NOn5ULv0621q_vFniE1:b-6irua0) ([raw file](https://github.com/gramineproject/gramine/blob/721d2b48f509ce0bbca93b124833d82ae3b06b7f/libos/src/sys/libos_clone.c#L315)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

There is nothing to rewrap? Everything seems to be already conforming to 100-char limit.
</blockquote></details>

Shouldn't we rewrap to below (or I misunderstood the guidelines)?



_Suggestion:_
```C
        ret = toml_bool_in(g_manifest_root, "sys.disallow_subprocesses", /*defaultval=*/false,
                           &disallow_subprocesses);
```


<!-- Sent from Reviewable.io -->

2023-02-21 08:50 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/983)* status: 5 of 6 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)

___
*[`libos/src/sys/libos_clone.c` line 315 at r4](https://reviewable.io/reviews/gramineproject/gramine/983#-NOlaBOq4uDbFISmrxtH:-NOn9NjA9g8zcUrpeH5v:begbomf) ([raw file](https://github.com/gramineproject/gramine/blob/721d2b48f509ce0bbca93b124833d82ae3b06b7f/libos/src/sys/libos_clone.c#L315)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Shouldn't we rewrap to below (or I misunderstood the guidelines)?
</blockquote></details>

Done. You are right. I am used to automatically rewrapping in my Vim editor, using `Gq` key combination. Interesting, it didn't work correctly this time, no idea why.


<!-- Sent from Reviewable.io -->

2023-02-22 13:10 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/983)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-02-22 13:34 UTC, dimakuv commented
Jenkins, retest pkg-rpm-almalinux9 please (`Curl error (6): Couldn't resolve host name for https://mirrors.almalinux.org/mirrorlist/9/appstream [getaddrinfo() thread failed to start]`)

2023-02-22 14:22 UTC, dimakuv commented
Jenkins, retest pkg-rpm-almalinux9 please

2023-02-22 14:31 UTC, merged