[python] Move from `toml` library to `tomli` + `tomli-w`
gramineproject/gramine pull request #995
Opened 2022-10-20 11:16 UTC by dimakuv

## Description of the changes 

`toml` Python library (for parsing and dumping TOML files) is buggy and doesn't support the full spec of TOML 1.0.0. This PR replaces it with more robust `tomli` (for parsing) and `tomli-w` (for dumping).

Useful links:
- https://github.com/uiri/toml/issues/404
- https://github.com/hukkin/tomli
- https://github.com/hukkin/tomli-w
- https://pypi.org/project/tomli/
- https://pypi.org/project/tomli-w/
- https://packages.ubuntu.com/jammy/python3-tomli
- https://packages.ubuntu.com/jammy/python3-tomli-w

Closes #990. Fixes #968.

See also https://github.com/gramineproject/gsc/pull/101.

## How to test this PR? 

CI. One LibOS test was modified a bit to test more TOML cases.

2022-10-20 11:21 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/995)* status: 0 of 10 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[`.ci/ubuntu18.04.dockerfile` line 90 at r1](https://reviewable.io/reviews/gramineproject/gramine/995#-NEp6EVe1HsAfceslSTu:-NEp6EVe1HsAfceslSTv:bx9gwnk) ([raw file](https://github.com/gramineproject/gramine/blob/56194869d07e1594a46811e8c7cd953615114300/.ci/ubuntu18.04.dockerfile#L90)):*
> ```Dockerfile
>     'sphinx_rtd_theme<1' \
>     'tomli>=1.1.0' \
>     'tomli-w>=1.0.0' \
> ```

FYI: These are not existing on Ubuntu 18.04 and 20.04. But it exists on Ubuntu 22.04. I guess @woju can take the packages from 22.04 when creating packages for Gramine v1.4?

Also, Python 3.11+ has `tomli` in its standard lib (under a new name `tomllib`). But there is no `tomli-w`, so I don't know if [adding a switch](https://github.com/hukkin/tomli#building-a-tomlitomllib-compatibility-layer) like this would be benefial.
___
*[`libos/test/regression/file_check_policy_strict.manifest.template` line 33 at r1](https://reviewable.io/reviews/gramineproject/gramine/995#-NEp6nP-C7bG29FgrXdD:-NEp6nP-C7bG29FgrXdE:b-vqmg86) ([raw file](https://github.com/gramineproject/gramine/blob/56194869d07e1594a46811e8c7cd953615114300/libos/test/regression/file_check_policy_strict.manifest.template#L33)):*
> ```
> 
>   # test correct parsing of `\\x2d` sequence (previously used `toml` Python parser had a bug)
>   { uri = "file:nonexisting\\x2dfile", sha256 = "0123456789012345678901234567890123456789012345678901234567890123" },
> ```

FYI: this is to test https://github.com/uiri/toml/issues/404 and https://github.com/gramineproject/gsc/pull/101.
___
*[`python/graminelibos/manifest.py` line 107 at r1](https://reviewable.io/reviews/gramineproject/gramine/995#-NEp6ymt1nbUMZkKJ1tg:-NEp6ymt1nbUMZkKJ1th:bs4b6hy) ([raw file](https://github.com/gramineproject/gramine/blob/db86ad2eab2ab449508b85263818f4d6d6e10a50/python/graminelibos/manifest.py#L107)):*
> ```Python
>                   "https://gramine.readthedocs.io/en/latest/manifest-syntax.html#trusted-files")
> 
>         # Current toml versions (< 1.0) do not support non-homogeneous arrays
> ```

FYI: This comment doesn't seem to correspond to the Python logic below (the logic is needed, but this comment is irrelevant for `tomli`).


<!-- Sent from Reviewable.io -->

2022-11-02 10:00 UTC, mkow requested changes
> Reviewed 7 of 10 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/995)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/995#-NFrgKxF-k-doCV8U8AJ:-NFrgKxF-k-doCV8U8AK:b-y9j00a) (no related file):*
Please remember to drop the hack from GSC after merging this PR.

___
___
*[`-- commits` line 4 at r2](https://reviewable.io/reviews/gramineproject/gramine/995#-NFrh7Dy3DloBrT6_U1a):*
It isn't dumping the files, but the structs _to_ files.



_Suggestion:_
```
generating TOML files
```
___
*[`.ci/ubuntu18.04.dockerfile` line 90 at r1](https://reviewable.io/reviews/gramineproject/gramine/995#-NEp6EVe1HsAfceslSTu:-NFrhh_GCQDQK93WEYeO:bqckaiz) ([raw file](https://github.com/gramineproject/gramine/blob/56194869d07e1594a46811e8c7cd953615114300/.ci/ubuntu18.04.dockerfile#L90)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

FYI: These are not existing on Ubuntu 18.04 and 20.04. But it exists on Ubuntu 22.04. I guess @woju can take the packages from 22.04 when creating packages for Gramine v1.4?

Also, Python 3.11+ has `tomli` in its standard lib (under a new name `tomllib`). But there is no `tomli-w`, so I don't know if [adding a switch](https://github.com/hukkin/tomli#building-a-tomlitomllib-compatibility-layer) like this would be benefial.
</blockquote></details>

Blocking until @woju replies.
___
*[`libos/test/regression/file_check_policy_strict.manifest.template` line 33 at r2](https://reviewable.io/reviews/gramineproject/gramine/995#-NFrjEVU4f4zE-y6Rq_Q:-NFrjEVU4f4zE-y6Rq_R:b-x3w907) ([raw file](https://github.com/gramineproject/gramine/blob/32312f721df1be3531da4b445420ee41649ea67f/libos/test/regression/file_check_policy_strict.manifest.template#L33)):*
> ```
> 
>   # test correct parsing of `\\x2d` sequence (previously used `toml` Python parser had a bug)
>   { uri = "file:nonexisting\\x2dfile", sha256 = "0123456789012345678901234567890123456789012345678901234567890123" },
> ```

I think this deserves to be a separate test. I don't like this packing of multiple unrelated tests into a single one, we can accidentally delete them because of this (e.g. when we decide to remove/change `sgx.file_check_policy` switch).


<!-- Sent from Reviewable.io -->

2022-11-03 09:41 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/995)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/995#-NFrgKxF-k-doCV8U8AJ:-NFwr4yL8hIc6vUxtvNo:b71508b) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please remember to drop the hack from GSC after merging this PR.
</blockquote></details>

https://github.com/gramineproject/gsc/pull/106 -- we can't drop the hack, at least not until the next stable release of Gramine. (GSC is supposed to be compatible with the last stable release, which is currently v1.3.1). But in the PR I linked, I added the FIXME at that hack.

___
___
*[`-- commits` line 4 at r2](https://reviewable.io/reviews/gramineproject/gramine/995#-NFrh7Dy3DloBrT6_U1a):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

It isn't dumping the files, but the structs _to_ files.
</blockquote></details>

Will fix during final rebase.
___
*[`libos/test/regression/file_check_policy_strict.manifest.template` line 33 at r2](https://reviewable.io/reviews/gramineproject/gramine/995#-NFrjEVU4f4zE-y6Rq_Q:-NFwrRO50XszuC9J98tJ:bc739p3) ([raw file](https://github.com/gramineproject/gramine/blob/32312f721df1be3531da4b445420ee41649ea67f/libos/test/regression/file_check_policy_strict.manifest.template#L33)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I think this deserves to be a separate test. I don't like this packing of multiple unrelated tests into a single one, we can accidentally delete them because of this (e.g. when we decide to remove/change `sgx.file_check_policy` switch).
</blockquote></details>

A separate test that does what? I mean, what would the corresponding C source do?


<!-- Sent from Reviewable.io -->

2022-11-21 23:39 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/995)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv and @woju)

___
*[`libos/test/regression/file_check_policy_strict.manifest.template` line 33 at r2](https://reviewable.io/reviews/gramineproject/gramine/995#-NFrjEVU4f4zE-y6Rq_Q:-NHRYWqeCm4mLmp9g2Ds:b5xmy9f) ([raw file](https://github.com/gramineproject/gramine/blob/32312f721df1be3531da4b445420ee41649ea67f/libos/test/regression/file_check_policy_strict.manifest.template#L33)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

A separate test that does what? I mean, what would the corresponding C source do?
</blockquote></details>

It can do nothing, just an empty binary with a tricky manifest (we could move all weird/legacy manifest syntaxes testing there, right now we AFAIR have them spread throughout random tests).


<!-- Sent from Reviewable.io -->

2022-11-22 09:07 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/995)* status: 9 of 18 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @woju)

___
*[`-- commits` line 7 at r2](https://reviewable.io/reviews/gramineproject/gramine/995#-NHT_Lns-h7WDJl6pPkj):*
Add a new para during final rebase:
```
New LibOS regression test is added that combines all tricky/legacy TOML syntax, including
the checks for TOML-syntax bugs.
```
___
*[`.ci/ubuntu18.04.dockerfile` line 90 at r1](https://reviewable.io/reviews/gramineproject/gramine/995#-NEp6EVe1HsAfceslSTu:-NHTR_qnE6iYZC4lDwLj:brzpqz8) ([raw file](https://github.com/gramineproject/gramine/blob/56194869d07e1594a46811e8c7cd953615114300/.ci/ubuntu18.04.dockerfile#L90)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Blocking until @woju replies.
</blockquote></details>

@woju ping
___
*[`libos/test/regression/file_check_policy_strict.manifest.template` line 33 at r2](https://reviewable.io/reviews/gramineproject/gramine/995#-NFrjEVU4f4zE-y6Rq_Q:-NHTXyvH6X_iL7Wvnuxi:b-l4ult) ([raw file](https://github.com/gramineproject/gramine/blob/32312f721df1be3531da4b445420ee41649ea67f/libos/test/regression/file_check_policy_strict.manifest.template#L33)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

It can do nothing, just an empty binary with a tricky manifest (we could move all weird/legacy manifest syntaxes testing there, right now we AFAIR have them spread throughout random tests).
</blockquote></details>

Done, good idea.
___
*[`libos/test/regression/file_check_policy_strict.manifest.template` line 30 at r3](https://reviewable.io/reviews/gramineproject/gramine/995#-NHT_ke57IPZKJhCYZnm:-NHT_ke57IPZKJhCYZnn:b-yy1okt) ([raw file](https://github.com/gramineproject/gramine/blob/3620c24244e0282707ea66d198e504cd71b20583/libos/test/regression/file_check_policy_strict.manifest.template#L30)):*
> ```
>   # test TOML inline table syntax with `sha256` (trusted_testfile has hard-coded contents, so we can
>   # use pre-calculated SHA256 hash)
>   { uri = "file:trusted_testfile", sha256 = "41dacdf1e6d0481d3b1ab1a91f93139db02b96f29cfdd3fb0b819ba1e33cafc4" },
> ```

FYI: Note that I kept these syntaxes for TOML inline table syntax here, because it's impossible to combine the two syntaxes in one file (in one `toml_parsing.manifest.template`)


<!-- Sent from Reviewable.io -->

2022-11-22 17:30 UTC, mkow reviewed
> Reviewed 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/995)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @woju)



<!-- Sent from Reviewable.io -->

2022-11-23 18:13 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/995)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`.ci/ubuntu18.04.dockerfile` line 90 at r1](https://reviewable.io/reviews/gramineproject/gramine/995#-NEp6EVe1HsAfceslSTu:-NH_uDDu4wc92BEQJr0Y:b8ap50m) ([raw file](https://github.com/gramineproject/gramine/blob/56194869d07e1594a46811e8c7cd953615114300/.ci/ubuntu18.04.dockerfile#L90)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@woju ping
</blockquote></details>

@dimakuv I've added `python3-tomli` and `python3-tomli-w` to `unstable-bionic` and `unstable-focal` repositories. If you use Ubuntu 22.04, you don't need to do anything. If you use Debian 11, you need to install those from `stable-backports` distro repo. When we'll release, I'll move the packages to `bionic` and `focal` stable repos.


<!-- Sent from Reviewable.io -->

2022-11-23 18:29 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/995)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2022-11-24 08:16 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/995)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`.ci/ubuntu18.04.dockerfile` line 90 at r1](https://reviewable.io/reviews/gramineproject/gramine/995#-NEp6EVe1HsAfceslSTu:-NHch9GABx1AKrP9A4qi:b-ucfknh) ([raw file](https://github.com/gramineproject/gramine/blob/56194869d07e1594a46811e8c7cd953615114300/.ci/ubuntu18.04.dockerfile#L90)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

@dimakuv I've added `python3-tomli` and `python3-tomli-w` to `unstable-bionic` and `unstable-focal` repositories. If you use Ubuntu 22.04, you don't need to do anything. If you use Debian 11, you need to install those from `stable-backports` distro repo. When we'll release, I'll move the packages to `bionic` and `focal` stable repos.
</blockquote></details>

Thanks!


<!-- Sent from Reviewable.io -->

2022-11-25 07:30 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/995)* status: 13 of 18 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[`-- commits` line 4 at r2](https://reviewable.io/reviews/gramineproject/gramine/995#-NFrh7Dy3DloBrT6_U1a):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Will fix during final rebase.
</blockquote></details>

Done
___
*[`-- commits` line 7 at r2](https://reviewable.io/reviews/gramineproject/gramine/995#-NHT_Lns-h7WDJl6pPkj):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Add a new para during final rebase:
```
New LibOS regression test is added that combines all tricky/legacy TOML syntax, including
the checks for TOML-syntax bugs.
```
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2022-11-26 02:01 UTC, mkow approved these changes
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/995)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-11-26 21:07 UTC, merged