[Pal/Linux-SGX] Drop support for old SGX drivers
gramineproject/gramine pull request #997
Opened 2022-10-20 14:14 UTC by mkow

## Description of the changes 

AFAIK all of these (DCAP <= 1.6, super-old OOT version, gsgx) are not being used by anyone since long time ago.

## How to test this PR? 

CI should be enough, but if you have some unusual config then you may want to try it yourself.
Please verify that I removed everything, there may be more leftovers I missed.

2022-10-20 16:48 UTC, boryspoplawski requested changes
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/997)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow and @woju)

___
*[`pal/src/host/linux-sgx/host_main.c` line 1123 at r1](https://reviewable.io/reviews/gramineproject/gramine/997#-NEqHZ4H7PuU3scTin7o:-NEqHZ4H7PuU3scTin7p:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/27b104079ede6287b3a13e87217c5afe815cf784/pal/src/host/linux-sgx/host_main.c#L1123)):*
> ```C
>     if (get_aux_value(envp, AT_HWCAP2, &at_hwcap2) != 0 || !(at_hwcap2 & 0x2)) {
>         log_error("Gramine with Linux-SGX backend requires support for FSGSBASE CPU instruction "
>                   "set in the host kernel. Please update your system.");
> ```





_Suggestion:_
```C
        log_error("Gramine with Linux-SGX backend requires support for FSGSBASE CPU instructions "
                  "in the host kernel. Please update your system.");
```


<!-- Sent from Reviewable.io -->

2022-10-21 08:33 UTC, dimakuv requested changes
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/997)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/997#-NEtdR9J3JkCgVMj-byj:-NEtdR9J3JkCgVMj-byk:b-52qndv) (no related file):*
You say this in the PR description:

> super-old OOT version

but the PR doesn't remove the OOT version (which is correct, I don't want to remove it yet). Was it just a blooper in the PR description?

___
___
*[`meson.build` line 122 at r1](https://reviewable.io/reviews/gramineproject/gramine/997#-NEtdlVA-7syEBN_JFjs:-NEtdlVA-7syEBN_JFjt:beo4oaw) ([raw file](https://github.com/gramineproject/gramine/blob/27b104079ede6287b3a13e87217c5afe815cf784/meson.build#L122)):*
> ```Meson
>         sgx_driver_device_default = '/dev/isgx'
>         sgx_driver_include_path_defaults = ['/opt/intel/linux-sgx-driver']
>     elif sgx_driver == 'dcap1.10'
> ```

Do we want to introduce a new alias `dcap` now? It will be simpler for users than to remember this `dcap1.10` wording.
___
*[`.ci/lib/stage-build-sgx.jenkinsfile` line 14 at r1](https://reviewable.io/reviews/gramineproject/gramine/997#-NEte7ha7I6ywlFOT2Fu:-NEte7ha7I6ywlFOT2Fv:bgshezm) ([raw file](https://github.com/gramineproject/gramine/blob/27b104079ede6287b3a13e87217c5afe815cf784/.ci/lib/stage-build-sgx.jenkinsfile#L14)):*
> ```
>         cd SGXDataCenterAttestationPrimitives
>         git checkout DCAP_1.14
>         # no need to build, we only need the SGX header file (sgx_oot.h)
> ```

What is going on here? I don't get it. The OOT driver is checked out above. Here we check out the latest DCAP driver...
___
*[`Documentation/devel/building.rst` line 190 at r1](https://reviewable.io/reviews/gramineproject/gramine/997#-NEteQAhAWZAvQ37h27y:-NEteQAhAWZAvQ37h27z:bm5u2nv) ([raw file](https://github.com/gramineproject/gramine/blob/27b104079ede6287b3a13e87217c5afe815cf784/Documentation/devel/building.rst#L190)):*
> ```reStructuredText
> * ``upstream`` (default) for upstreamed in-kernel driver (mainline Linux kernel
>   5.11+),
> * ``dcap1.10`` for Intel DCAP version 1.10 or higher,
> ```

ditto (add alias `dcap`)
___
*[`Documentation/devel/building.rst` line 190 at r1](https://reviewable.io/reviews/gramineproject/gramine/997#-NEteSYr7ZU9glq_0xD9:-NEteSYr7ZU9glq_0xDA:b-9gd4au) ([raw file](https://github.com/gramineproject/gramine/blob/27b104079ede6287b3a13e87217c5afe815cf784/Documentation/devel/building.rst#L190)):*
> ```reStructuredText
> * ``upstream`` (default) for upstreamed in-kernel driver (mainline Linux kernel
>   5.11+),
> * ``dcap1.10`` for Intel DCAP version 1.10 or higher,
> ```

Should we also mention that DCAP v1.9 and older are not supported anymore?
___
*[`pal/src/host/linux-sgx/host_main.c` line 1123 at r1](https://reviewable.io/reviews/gramineproject/gramine/997#-NEqHZ4H7PuU3scTin7o:-NEtf6Ge9ZRyz9_7NT1t:bievqb3) ([raw file](https://github.com/gramineproject/gramine/blob/27b104079ede6287b3a13e87217c5afe815cf784/pal/src/host/linux-sgx/host_main.c#L1123)):*
> ```C
>     if (get_aux_value(envp, AT_HWCAP2, &at_hwcap2) != 0 || !(at_hwcap2 & 0x2)) {
>         log_error("Gramine with Linux-SGX backend requires support for FSGSBASE CPU instruction "
>                   "set in the host kernel. Please update your system.");
> ```

+1 to Borys


<!-- Sent from Reviewable.io -->

2022-10-21 17:07 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/997)* status: 7 of 12 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/997#-NEtdR9J3JkCgVMj-byj:-NEvQ84U8ppLI_hizAwf:b-51t3v8) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You say this in the PR description:

> super-old OOT version

but the PR doesn't remove the OOT version (which is correct, I don't want to remove it yet). Was it just a blooper in the PR description?
</blockquote></details>

No, see another discussion pinned at the corresponding code.

___
___
*[`meson.build` line 122 at r1](https://reviewable.io/reviews/gramineproject/gramine/997#-NEtdlVA-7syEBN_JFjs:-NEvSY-sEIr8jFOfKR9S:b5h9jpf) ([raw file](https://github.com/gramineproject/gramine/blob/27b104079ede6287b3a13e87217c5afe815cf784/meson.build#L122)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Do we want to introduce a new alias `dcap` now? It will be simpler for users than to remember this `dcap1.10` wording.
</blockquote></details>

Good idea, done (but we need to preserve the old name also, for backwards compatibility).
Actually, @dimakuv, do you maybe have a server with DCAP driver where you could test this PR?
___
*[`.ci/lib/stage-build-sgx.jenkinsfile` line 14 at r1](https://reviewable.io/reviews/gramineproject/gramine/997#-NEte7ha7I6ywlFOT2Fu:-NEvTiqQBsAqIdVqMKbH:b-hy0j3v) ([raw file](https://github.com/gramineproject/gramine/blob/27b104079ede6287b3a13e87217c5afe815cf784/.ci/lib/stage-build-sgx.jenkinsfile#L14)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What is going on here? I don't get it. The OOT driver is checked out above. Here we check out the latest DCAP driver...
</blockquote></details>

Good question, I have no idea, it doesn't make any sense to me. @woju?
___
*[`Documentation/devel/building.rst` line 190 at r1](https://reviewable.io/reviews/gramineproject/gramine/997#-NEteQAhAWZAvQ37h27y:-NEvU-8U1FtHvGIndLVU:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/27b104079ede6287b3a13e87217c5afe815cf784/Documentation/devel/building.rst#L190)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto (add alias `dcap`)
</blockquote></details>

Done.
___
*[`Documentation/devel/building.rst` line 190 at r1](https://reviewable.io/reviews/gramineproject/gramine/997#-NEteSYr7ZU9glq_0xD9:-NEvU1IJ19OWUuD7mxfk:bwnsfco) ([raw file](https://github.com/gramineproject/gramine/blob/27b104079ede6287b3a13e87217c5afe815cf784/Documentation/devel/building.rst#L190)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Should we also mention that DCAP v1.9 and older are not supported anymore?
</blockquote></details>

We can keep it implicit IMO, it's pretty obvious from the current wording of this list.
___
*[`pal/src/host/linux-sgx/host_main.c` line 1123 at r1](https://reviewable.io/reviews/gramineproject/gramine/997#-NEqHZ4H7PuU3scTin7o:-NEvUGkIBp-Azb3rjZED:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/27b104079ede6287b3a13e87217c5afe815cf784/pal/src/host/linux-sgx/host_main.c#L1123)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

+1 to Borys
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/host_sgx_driver.h.in` line 58 at r1](https://reviewable.io/reviews/gramineproject/gramine/997#-NEvS7_K0XVVi1NB8lJ4:-NEvS7_K0XVVi1NB8lJ5:b-u2cqkd) ([raw file](https://github.com/gramineproject/gramine/blob/db86ad2eab2ab449508b85263818f4d6d6e10a50/pal/src/host/linux-sgx/host_sgx_driver.h.in#L58)):*
> You say this in the PR description:
> > super-old OOT version
> 
> but the PR doesn't remove the OOT version (which is correct, I don't want to remove it yet). Was it just a blooper in the PR description?

Here I remove it. Notice "version" in "super-old OOT version" - I'm not removing OOT support, only support for its older versions.


<!-- Sent from Reviewable.io -->

2022-10-23 14:34 UTC, boryspoplawski submitted a review, later dismissed
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/997)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @woju)

___
*[`.ci/lib/stage-build-sgx.jenkinsfile` line 14 at r1](https://reviewable.io/reviews/gramineproject/gramine/997#-NEte7ha7I6ywlFOT2Fu:-NF4Faoe3dzmeBJfU5nB:bxebix9) ([raw file](https://github.com/gramineproject/gramine/blob/27b104079ede6287b3a13e87217c5afe815cf784/.ci/lib/stage-build-sgx.jenkinsfile#L14)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Good question, I have no idea, it doesn't make any sense to me. @woju?
</blockquote></details>

We build dcap below, just to see that it compiles - we do not run tests on it.


<!-- Sent from Reviewable.io -->

2022-10-24 17:14 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/997)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`meson.build` line 122 at r1](https://reviewable.io/reviews/gramineproject/gramine/997#-NEtdlVA-7syEBN_JFjs:-NF9vy8U8myno9f9F6nY:bla5cxn) ([raw file](https://github.com/gramineproject/gramine/blob/27b104079ede6287b3a13e87217c5afe815cf784/meson.build#L122)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Well, bad news. I should have checked it earlier.

MS Azure provides Ubuntu 18.04 with Linux 5.4 and the **DCAP driver v1.6**. I just tried it out, and this PR doesn't work (because it removes support for this version of DCAP).

I now strongly oppose the removal of `dcap1.6`. I'm still fine with removing the old version of OOT driver and adding alias `dcap` for `dcap1.10`.
</blockquote></details>

`gramine-dcap` packages were always built with `-Dsgx_driver=dcap1.10`. So either this just works, or no-one uses `deb` packages on Azure. Assuming people use `deb` packages: last week you've said that `-Dsgx_driver=dcap1.10` and `-Dsgx_driver=inkernel` are compatible (save for path in `/dev`). If so, then we can remove *both* dcap driver and just provide `/dev` path compatibility. This will have the side effect that you won't be able to compile gramine on Azure, you'd have to use packages, but they would work no problem.

Am I missing something?


<!-- Sent from Reviewable.io -->

2022-10-25 07:57 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/997)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow and @woju)

___
*[`meson.build` line 122 at r1](https://reviewable.io/reviews/gramineproject/gramine/997#-NEtdlVA-7syEBN_JFjs:-NFD2EyWEiaIQFZvRpBw:by6u69a) ([raw file](https://github.com/gramineproject/gramine/blob/27b104079ede6287b3a13e87217c5afe815cf784/meson.build#L122)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

`gramine-dcap` packages were always built with `-Dsgx_driver=dcap1.10`. So either this just works, or no-one uses `deb` packages on Azure. Assuming people use `deb` packages: last week you've said that `-Dsgx_driver=dcap1.10` and `-Dsgx_driver=inkernel` are compatible (save for path in `/dev`). If so, then we can remove *both* dcap driver and just provide `/dev` path compatibility. This will have the side effect that you won't be able to compile gramine on Azure, you'd have to use packages, but they would work no problem.

Am I missing something?
</blockquote></details>

Ok, so this is the state after more testing on Azure VMs:
1. Ubuntu 18.04 with Linux 5.4 and DCAP driver v1.6 (driver under `/dev/sgx/enclave`)
    - works with `gramine-dcap` package v1.3.1;
    - works with Gramine installed through this PR (`-Dsgx_driver=dcap`)
2. Ubuntu 20.04 with Linux 5.15 and in-kernel driver (driver under `/dev/sgx_enclave`)
    - works with `gramine` package v1.3.1;
    - works with Gramine installed through this PR (`-Dsgx_driver=upstream`)

So yes, **DCAP v1.10 is Linux-API-compatible with DCAP v1.6**. Thus, we can drop support for DCAP v1.6, though it makes me cringe. Relying on this almost accidental compatibility sounds wrong. But on the other hand, supporting this whole OOT vs old DCAP vs new DCAP vs upstream also sounds wrong.

@mkow Do you still want to proceed with removing DCAP v1.6?


<!-- Sent from Reviewable.io -->

2022-10-25 09:21 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/997)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @woju)

___
*[`meson.build` line 122 at r1](https://reviewable.io/reviews/gramineproject/gramine/997#-NEtdlVA-7syEBN_JFjs:-NFDQB9uBsTk1sZYeXV4:bi3joax) ([raw file](https://github.com/gramineproject/gramine/blob/27b104079ede6287b3a13e87217c5afe815cf784/meson.build#L122)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ok, so this is the state after more testing on Azure VMs:
1. Ubuntu 18.04 with Linux 5.4 and DCAP driver v1.6 (driver under `/dev/sgx/enclave`)
    - works with `gramine-dcap` package v1.3.1;
    - works with Gramine installed through this PR (`-Dsgx_driver=dcap`)
2. Ubuntu 20.04 with Linux 5.15 and in-kernel driver (driver under `/dev/sgx_enclave`)
    - works with `gramine` package v1.3.1;
    - works with Gramine installed through this PR (`-Dsgx_driver=upstream`)

So yes, **DCAP v1.10 is Linux-API-compatible with DCAP v1.6**. Thus, we can drop support for DCAP v1.6, though it makes me cringe. Relying on this almost accidental compatibility sounds wrong. But on the other hand, supporting this whole OOT vs old DCAP vs new DCAP vs upstream also sounds wrong.

@mkow Do you still want to proceed with removing DCAP v1.6?
</blockquote></details>

Yes, but let's discuss this on the call today. I think woju suggests removing all `dcap*` options, which I tend to like, but it will make Gramine unbuildable with DCAP driver - you'll need to use packages. I think it's not a problem, DCAP drivers are legacy and we support it only because some old Azure instances still have them.


<!-- Sent from Reviewable.io -->

2022-10-26 09:02 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/997)* status: all files reviewed, 3 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/997#-NFIWZRdCmLJClqhfyyx:-NFIWZRe3zWvVFTN0stR:b5tvpbb) (no related file):*
After we merge this PR, 

___
___
*[`meson.build` line 122 at r1](https://reviewable.io/reviews/gramineproject/gramine/997#-NEtdlVA-7syEBN_JFjs:-NFIWfMH0LOEQDqXMVMU:b-i323l5) ([raw file](https://github.com/gramineproject/gramine/blob/27b104079ede6287b3a13e87217c5afe815cf784/meson.build#L122)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Yes, but let's discuss this on the call today. I think woju suggests removing all `dcap*` options, which I tend to like, but it will make Gramine unbuildable with DCAP driver - you'll need to use packages. I think it's not a problem, DCAP drivers are legacy and we support it only because some old Azure instances still have them.
</blockquote></details>

It was discussed on the call yesterday: https://github.com/gramineproject/gramine/discussions/985

So yes, we are fine with dropping support for DCAP v1.6. I'm resolving this comment.


<!-- Sent from Reviewable.io -->

2022-10-26 09:05 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/997)* status: all files reviewed, 3 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/997#-NFIWpjC2zLl_HoXrbVQ:-NFIWpjC2zLl_HoXrbVR:b-xigbny) (no related file):*
After we merge this PR, we need to create a follow-up PR that removes `ISGX_FILE`, `CONFIG_SGX_DRIVER_DEVICE`, `sgx_driver_device`, `sgx_driver_device_default` (from C code and Meson).

Instead, we will rely on the macro `SGX_DCAP`:
- If it is set, then we first try to open `/dev/sgx_enclave`, then fall back to `/dev/sgx/enclave`
- If it is not set (OOT driver), then we try to open `/dev/isgx`

___


<!-- Sent from Reviewable.io -->

2022-10-26 12:12 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/997)* status: 7 of 13 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/997#-NFIWpjC2zLl_HoXrbVQ:-NFIvb649VhwSQrdBerC:bhy9ot6) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

After we merge this PR, we need to create a follow-up PR that removes `ISGX_FILE`, `CONFIG_SGX_DRIVER_DEVICE`, `sgx_driver_device`, `sgx_driver_device_default` (from C code and Meson).

Instead, we will rely on the macro `SGX_DCAP`:
- If it is set, then we first try to open `/dev/sgx_enclave`, then fall back to `/dev/sgx/enclave`
- If it is not set (OOT driver), then we try to open `/dev/isgx`
</blockquote></details>

Will do.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/997#-NFJBQUA9iyvmOaPx2cR:-NFJBQUB-icMLCIeJbg7:bobt132) (no related file):*
We got `13:44:14  error: Gramine with Linux-SGX backend requires support for FSGSBASE CPU instructions in the host kernel. Please update your system.` on bobothebear node. @woju: please take it out of CI, update the kernel + uninstall gsgx from it, and then bring it back. Also, check if any other node has this problem.

___
___
*[`.ci/lib/stage-build-sgx.jenkinsfile` line 14 at r1](https://reviewable.io/reviews/gramineproject/gramine/997#-NEte7ha7I6ywlFOT2Fu:-NFJ0mIqDvAsdWBZan_W:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/27b104079ede6287b3a13e87217c5afe815cf784/.ci/lib/stage-build-sgx.jenkinsfile#L14)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ah, I got it. We actually use the OOT driver (the first git clone above). Then we git-clone the DCAP driver and explain `no need to build [the DCAP driver]` in the comment, in the sense that we'll only need the git-checkout'ed SGX header file for the `meson setup build-dcap` below.

The comment has a misleading `sgx_oot.h` header. This name was correct for old versions of the DCAP driver (see https://github.com/intel/SGXDataCenterAttestationPrimitives/tree/DCAP_1.7/driver/linux/include/uapi/asm).

But this name was changed in the newer DCAP drivers to `sgx_user.h` -- https://github.com/intel/SGXDataCenterAttestationPrimitives/tree/DCAP_1.10/driver/linux/include

@mkow Please change to this:
```
# no need to build, we only need the SGX header file (`driver/linux/include/sgx_user.h`)
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-10-26 12:47 UTC, dimakuv requested changes
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/997)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/997#-NFJBQUA9iyvmOaPx2cR:-NFJJUx-12MixyLnmBag:bipmy45) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

We got `13:44:14  error: Gramine with Linux-SGX backend requires support for FSGSBASE CPU instructions in the host kernel. Please update your system.` on bobothebear node. @woju: please take it out of CI, update the kernel + uninstall gsgx from it, and then bring it back. Also, check if any other node has this problem.
</blockquote></details>

Why did this happen? On this PR?

___
___
*[`Documentation/devel/building.rst` line 195 at r3](https://reviewable.io/reviews/gramineproject/gramine/997#-NFJK2mO5sFB_vylkvHK:-NFJK2mO5sFB_vylkvHL:byfxmvd) ([raw file](https://github.com/gramineproject/gramine/blob/66ae02ae89c7338fc5e85b3059532aeb65091580/Documentation/devel/building.rst#L195)):*
> ```reStructuredText
> where the SGX driver was downloaded or installed in the previous step. For
> example, for the upstreamed driver, you must specify
> ``-Dsgx_driver_include_path="/opt/intel/linux-sgx-driver"``. If this parameter
> ```

What is this path? Looks like for the OOT driver.

For upstream driver, it's like this: `/usr/src/linux-headers-@0@/arch/x86/include/uapi`, where `@0@` is the output of `uname -r`
___
*[`pal/src/host/linux-sgx/host_sgx_driver.h.in` line 18 at r1](https://reviewable.io/reviews/gramineproject/gramine/997#-NFJKHogAWClwpatVlqb:-NFJKHogAWClwpatVlqc:b-thjddo) ([raw file](https://github.com/gramineproject/gramine/blob/27b104079ede6287b3a13e87217c5afe815cf784/pal/src/host/linux-sgx/host_sgx_driver.h.in#L18)):*
> ```
> 
> #mesondefine CONFIG_SGX_DRIVER_UPSTREAM
> #mesondefine CONFIG_SGX_DRIVER_DCAP_1_10
> ```

It's not used anywhere in the C code? So it was deadcode?


<!-- Sent from Reviewable.io -->

2022-10-26 14:08 UTC, llly reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/997)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @woju)

___
*[`pal/src/host/linux-sgx/host_main.c` line 1122 at r3](https://reviewable.io/reviews/gramineproject/gramine/997#-NFJa6JW1q8NiLPmqXi6:-NFJa6JW1q8NiLPmqXi7:b-o4f40v) ([raw file](https://github.com/gramineproject/gramine/blob/66ae02ae89c7338fc5e85b3059532aeb65091580/pal/src/host/linux-sgx/host_main.c#L1122)):*
> ```C
>     uint64_t at_hwcap2;
>     if (get_aux_value(envp, AT_HWCAP2, &at_hwcap2) != 0 || !(at_hwcap2 & 0x2)) {
>         log_error("Gramine with Linux-SGX backend requires support for FSGSBASE CPU instructions "
> ```

We are still officially supporting Ubuntu 18.04 LTS with highest kernel version 5.4.
Without GSGX driver, kernel from Ubuntu packages won't work.


<!-- Sent from Reviewable.io -->

2022-10-26 14:45 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/997)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @llly, @mkow, and @woju)

___
*[`pal/src/host/linux-sgx/host_main.c` line 1122 at r3](https://reviewable.io/reviews/gramineproject/gramine/997#-NFJa6JW1q8NiLPmqXi6:-NFJjr7Y9iPRTpJvRQWo:bqbn22l) ([raw file](https://github.com/gramineproject/gramine/blob/66ae02ae89c7338fc5e85b3059532aeb65091580/pal/src/host/linux-sgx/host_main.c#L1122)):*
<details><summary><i>Previously, llly (Li Xun) wrote…</i></summary><blockquote>

We are still officially supporting Ubuntu 18.04 LTS with highest kernel version 5.4.
Without GSGX driver, kernel from Ubuntu packages won't work.
</blockquote></details>

@llly But one can still just use the GSGX driver from https://github.com/oscarlab/graphene-sgx-driver or (much better) apply the patches from https://github.com/oscarlab/graphene-sgx-driver/tree/master/fsgsbase_patches

The only thing that changes with this PR that Gramine doesn't mention this GSGX driver anymore.

Or is it somehow critical for our purposes?


<!-- Sent from Reviewable.io -->

2022-10-27 07:13 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/997)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @llly, @mkow, and @woju)

___
*[`pal/src/host/linux-sgx/host_main.c` line 1122 at r3](https://reviewable.io/reviews/gramineproject/gramine/997#-NFJa6JW1q8NiLPmqXi6:-NFNH3L17BvdZFm3Xn-S:bf4gljc) ([raw file](https://github.com/gramineproject/gramine/blob/66ae02ae89c7338fc5e85b3059532aeb65091580/pal/src/host/linux-sgx/host_main.c#L1122)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

GSGX is not supported from a long time. It's insecure and was used only for testing purposes quite a long time ago. Only ways to get the support are:
- use `fsgsbase` patchset
- use Ubuntu which have them backported - both 20.04 and 18.04 have them, as long as you use kernel 5.4 ( which is not the default on Ubuntu18.04).

Btw we should ask `oscarlab` to archive https://github.com/oscarlab/graphene-sgx-driver
</blockquote></details>

Oh, one thing that I didn't notice is this "still *officially supporting*". The GSGX driver is surely not something that we recommend for any production usages. And yes, Borys is right, the correct way is to use official Ubuntu kernels with backported FSGSBASE.

The repo was archived, by the way.


<!-- Sent from Reviewable.io -->

2022-10-27 11:59 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/997)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @llly, @mkow, and @woju)

___
*[`.ci/lib/stage-build-sgx.jenkinsfile` line 14 at r1](https://reviewable.io/reviews/gramineproject/gramine/997#-NEte7ha7I6ywlFOT2Fu:-NFOHapyCXz0nRQjswvz:b-ml85x4) ([raw file](https://github.com/gramineproject/gramine/blob/27b104079ede6287b3a13e87217c5afe815cf784/.ci/lib/stage-build-sgx.jenkinsfile#L14)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

I don't like the fact that after this PR we won't test even compiling against newer drivers. Or you can remove it now, but add to the list of things to be done in next PR above.
</blockquote></details>

But don't we cease to support building Gramine with DCAP drivers with this PR (i.e. you just use upstream)? Why would we test it then?
___
*[`pal/src/host/linux-sgx/host_main.c` line 1122 at r3](https://reviewable.io/reviews/gramineproject/gramine/997#-NFJa6JW1q8NiLPmqXi6:-NFOIV_26MNLn35_sEv-:bqrx179) ([raw file](https://github.com/gramineproject/gramine/blob/66ae02ae89c7338fc5e85b3059532aeb65091580/pal/src/host/linux-sgx/host_main.c#L1122)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

If you have 5.4, you're already messing with the kernel, so I think it's fair to require people to have FSGSBASE patchset.
</blockquote></details>

You can install 5.4 from apt (on Ubuntu 18.04 and 20.04), which for most users is far easier from building kernel manually.


<!-- Sent from Reviewable.io -->

2022-10-27 20:29 UTC, woju requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/997)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @llly, and @mkow)

___
*[`.ci/lib/stage-build-sgx.jenkinsfile` line 14 at r1](https://reviewable.io/reviews/gramineproject/gramine/997#-NEte7ha7I6ywlFOT2Fu:-NFQ1H0cAXVxF9qdHkbf:b-vxhmmq) ([raw file](https://github.com/gramineproject/gramine/blob/27b104079ede6287b3a13e87217c5afe815cf784/.ci/lib/stage-build-sgx.jenkinsfile#L14)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

But don't we cease to support building Gramine with DCAP drivers with this PR (i.e. you just use upstream)? Why would we test it then?
</blockquote></details>

Compiling against DCAP driver is (was) a good approximation of compiling against upstream driver. #512 will add one scenario which compiles against upstream driver, but until that is merged, there will be a window when no CI pipeline would compile against anything that resembles upstream driver. This window is something that I don't like. Also, doesn't it just look bad that this PR touches the kernel interface and simultaneously removes a test for this exact area?
___
*[`pal/src/host/linux-sgx/host_main.c` line 1122 at r3](https://reviewable.io/reviews/gramineproject/gramine/997#-NFJa6JW1q8NiLPmqXi6:-NFQ3cDpC-Mv92SXhXYq:b-m7ekg7) ([raw file](https://github.com/gramineproject/gramine/blob/66ae02ae89c7338fc5e85b3059532aeb65091580/pal/src/host/linux-sgx/host_main.c#L1122)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

You can install 5.4 from apt (on Ubuntu 18.04 and 20.04), which for most users is far easier from building kernel manually.
</blockquote></details>

Yes, that's correct, and if you get that 5.4 from 18.04's apt repos, you get FSGSBASE patchset, so it's easier than manually building gsgx driver, right? I don't understand why we don't require it at this point. It's both easier and better. What we can do is to add an explanation to release notes for upcoming version.


<!-- Sent from Reviewable.io -->

2022-10-28 00:16 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/997)* status: 12 of 13 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @llly, and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/997#-NFJBQUA9iyvmOaPx2cR:-NFOuB1UCQlNzAt34VEr:b-bdkyik) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

@dimakuv: ? I explained everything in the message above - there seem to be a CI node still using gsgx and an old kernel (but woju just fixed it).

___
___
*[`.ci/lib/stage-build-sgx.jenkinsfile` line 14 at r1](https://reviewable.io/reviews/gramineproject/gramine/997#-NEte7ha7I6ywlFOT2Fu:-NFOuRAFBnk9xpvGZsKy:bdlw08f) ([raw file](https://github.com/gramineproject/gramine/blob/27b104079ede6287b3a13e87217c5afe815cf784/.ci/lib/stage-build-sgx.jenkinsfile#L14)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Compiling against DCAP driver is (was) a good approximation of compiling against upstream driver. #512 will add one scenario which compiles against upstream driver, but until that is merged, there will be a window when no CI pipeline would compile against anything that resembles upstream driver. This window is something that I don't like. Also, doesn't it just look bad that this PR touches the kernel interface and simultaneously removes a test for this exact area?
</blockquote></details>

Exactly, we don't plan to ever build against the DCAP driver headers again. We'll be using the upstreamed ones for DCAP packages.
___
*[`Documentation/devel/building.rst` line 189 at r3](https://reviewable.io/reviews/gramineproject/gramine/997#-NFNh_wC8aYuanh_6cYq:-NFOuYVT5_9ePuSpHpJE:b-cci5l4) ([raw file](https://github.com/gramineproject/gramine/blob/66ae02ae89c7338fc5e85b3059532aeb65091580/Documentation/devel/building.rst#L189)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

I'd like a word here that it works also with DCAP driver, so people won't hesitate which option they need to choose if they still have this driver.
</blockquote></details>

I did this on purpose, I don't want to advertise this way too much. It's deprecated and people should _really_ stop using it.
___
*[`Documentation/devel/building.rst` line 195 at r3](https://reviewable.io/reviews/gramineproject/gramine/997#-NFJK2mO5sFB_vylkvHK:-NFOuqJZ3wjN5bl8ZYU7:bjjxri0) ([raw file](https://github.com/gramineproject/gramine/blob/66ae02ae89c7338fc5e85b3059532aeb65091580/Documentation/devel/building.rst#L195)):*
> What is this path? Looks like for the OOT driver.

Oops, copy-paste error. Fixed (changed to OOT so we don't need to go into the details about kernel version in the path).

@woju: I'd do it later, after we drop all the legacy stuff entirely.
___
*[`pal/src/host/linux-sgx/host_main.c` line 1122 at r3](https://reviewable.io/reviews/gramineproject/gramine/997#-NFJa6JW1q8NiLPmqXi6:-NFQuU1w4Szm8vSTNOS7:b8ucrli) ([raw file](https://github.com/gramineproject/gramine/blob/66ae02ae89c7338fc5e85b3059532aeb65091580/pal/src/host/linux-sgx/host_main.c#L1122)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Yes, that's correct, and if you get that 5.4 from 18.04's apt repos, you get FSGSBASE patchset, so it's easier than manually building gsgx driver, right? I don't understand why we don't require it at this point. It's both easier and better. What we can do is to add an explanation to release notes for upcoming version.
</blockquote></details>

@dimakuv: Why are you blocking on this discussion? Seems that everything got explained.
@llly: Please also either respond or unblock.


<!-- Sent from Reviewable.io -->

2022-10-28 07:18 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/997)* status: all files reviewed, 3 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/997#-NFJBQUA9iyvmOaPx2cR:-NFSOmTr4cQLbINgqgIN:b-s468xo) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

@dimakuv: ? I explained everything in the message above - there seem to be a CI node still using gsgx and an old kernel (but woju just fixed it).
</blockquote></details>

What I didn't understand initially is how this was detected, given that the GSGX driver was still running on the CI node.

But now I got it -- we check for `AT_HWCAP2` value, which is **not** updated in any way by the GSGX driver, and only appears on newer Linux kernels. So even though the FSGSBASE functionality was enabled on this CI node (in an insecure and hacky way), Gramine didn't really check the availability of instructions themselves and also didn't check for the availability of the GSGX driver (which this PR removed) but rather for the hint from the Linux kernel.

___
___
*[`.ci/lib/stage-build-sgx.jenkinsfile` line 14 at r1](https://reviewable.io/reviews/gramineproject/gramine/997#-NEte7ha7I6ywlFOT2Fu:-NFSRveW2KzTjovN25Ba:b2ks3nn) ([raw file](https://github.com/gramineproject/gramine/blob/27b104079ede6287b3a13e87217c5afe815cf784/.ci/lib/stage-build-sgx.jenkinsfile#L14)):*
I agree with Borys and Michal. To address Woju's point:

> This window is something that I don't like.

I wouldn't care much about this window. #512 will be merged soonish hopefully, and in the meantime I don't see any changes to Gramine that can break its compatibility with the upstream/DCAP driver.
___
*[`Documentation/devel/building.rst` line 189 at r3](https://reviewable.io/reviews/gramineproject/gramine/997#-NFNh_wC8aYuanh_6cYq:-NFSQkb96KfZYBoUd_Ji:b-4f6gu0) ([raw file](https://github.com/gramineproject/gramine/blob/66ae02ae89c7338fc5e85b3059532aeb65091580/Documentation/devel/building.rst#L189)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I did this on purpose, I don't want to advertise this way too much. It's deprecated and people should _really_ stop using it.
</blockquote></details>

I'm with Michal on this one. I think it's time to force people to use the upstream. And those few who *really* need the DCAP driver, to them we'll explain the trick. Also, recall that the DCAP driver requires DCAP headers (at least technically), so it's just not that simple to explain...


<!-- Sent from Reviewable.io -->

2022-10-28 09:19 UTC, woju submitted a review, later dismissed
> Reviewed 2 of 12 files at r1, 1 of 5 files at r2, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/997)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[`.ci/lib/stage-build-sgx.jenkinsfile` line 14 at r1](https://reviewable.io/reviews/gramineproject/gramine/997#-NEte7ha7I6ywlFOT2Fu:-NFSqji89I22nOkcQnsG:b-q8l0hx) ([raw file](https://github.com/gramineproject/gramine/blob/27b104079ede6287b3a13e87217c5afe815cf784/.ci/lib/stage-build-sgx.jenkinsfile#L14)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I agree with Borys and Michal. To address Woju's point:

> This window is something that I don't like.

I wouldn't care much about this window. #512 will be merged soonish hopefully, and in the meantime I don't see any changes to Gramine that can break its compatibility with the upstream/DCAP driver.
</blockquote></details>

OK, you won't break it, then let it be that way.
___
*[`Documentation/devel/building.rst` line 189 at r3](https://reviewable.io/reviews/gramineproject/gramine/997#-NFNh_wC8aYuanh_6cYq:-NFSrHtr5nqVkG5ANBmR:bjda8gt) ([raw file](https://github.com/gramineproject/gramine/blob/66ae02ae89c7338fc5e85b3059532aeb65091580/Documentation/devel/building.rst#L189)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I'm with Michal on this one. I think it's time to force people to use the upstream. And those few who *really* need the DCAP driver, to them we'll explain the trick. Also, recall that the DCAP driver requires DCAP headers (at least technically), so it's just not that simple to explain...
</blockquote></details>

Yeah, steering people to upstream is a good thing.

DCAP driver compiles fine with kernel sources, it's not a trick and it's easy to say "compile with `-Dsgx_driver=upstream` and just run". That's the whole point. Maybe you need those headers for something else, but not for gramine.
___
*[`Documentation/devel/building.rst` line 195 at r3](https://reviewable.io/reviews/gramineproject/gramine/997#-NFJK2mO5sFB_vylkvHK:-NFSqyYX-H-WSIaWbqHT:b-80tlqk) ([raw file](https://github.com/gramineproject/gramine/blob/66ae02ae89c7338fc5e85b3059532aeb65091580/Documentation/devel/building.rst#L195)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> What is this path? Looks like for the OOT driver.

Oops, copy-paste error. Fixed (changed to OOT so we don't need to go into the details about kernel version in the path).

@woju: I'd do it later, after we drop all the legacy stuff entirely.
</blockquote></details>

Sure.


<!-- Sent from Reviewable.io -->

2022-10-28 11:39 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/997)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/997#-NFJBQUA9iyvmOaPx2cR:-NFTNX5OCzD9nvvk77s4:b-7vo826) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What I didn't understand initially is how this was detected, given that the GSGX driver was still running on the CI node.

But now I got it -- we check for `AT_HWCAP2` value, which is **not** updated in any way by the GSGX driver, and only appears on newer Linux kernels. So even though the FSGSBASE functionality was enabled on this CI node (in an insecure and hacky way), Gramine didn't really check the availability of instructions themselves and also didn't check for the availability of the GSGX driver (which this PR removed) but rather for the hint from the Linux kernel.
</blockquote></details>

Ah, I see.

___


<!-- Sent from Reviewable.io -->

2022-10-28 14:10 UTC, boryspoplawski submitted a review, later dismissed
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/997)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2022-10-29 19:09 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/997)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-10-29 23:15 UTC, merged